### ISSUE TITLE
Allow jsonp to rendered to the view

### ISSUE THREAD

**Issue by jeregrine** [phoenixframework/phoenix#1000]
Now that we have @pb82's excellent work on jsonp we need...

```elixir
render conn, "index.jsonp" 
```

So that you could possibly share the json view with the jsonp response type.

**Comment by jeregrine** [comment]
Notes from @josevalim 
```
 jeregrine: it is ok as long as you use a format_encoder we shouldn't special case jsonp for render
```

**Comment by josevalim** [comment]
@jeregrine  what about the default callback? In those cases we will need to always use "callback"?

**Comment by chrismccord** [comment]
> @jeregrine what about the default callback? In those cases we will need to always use "callback"?

We could change the format_encoder contract to accept the assigns
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/view.ex#L444

That way, you could do `render conn, "index.jsonp", callback: "foo"`. Thoughts?

**Comment by scrogson** [comment]
I've started work on this but got stuck. I may reach out to get some
clarity to finish it up today.

**Comment by jeregrine** [comment]
@josevalim and I talked a bit on irc and thinking maybe JSONP would work better just as a controller plug instead of a function/render case.

**Comment by chrismccord** [comment]
José filled me in on the plug idea. I love it. Way better that what I had in mind.

**Comment by josevalim** [comment]
Plug done in 6c11a514ed330cea55d6f5c23ddefa4ec50dfedc.
