### ISSUE TITLE
Correctly scope static file paths generated in forwarded endpoints

### ISSUE THREAD

**Issue by MSch** [phoenixframework/phoenix#1001]
I'm trying to create a phoenix app `logs` that can be used as a dependency by other phoenix/plug-based apps. Ideally you'd just add the dependency and mount the plug.

I've used `forward` in my "main" plug to mount `logs`' phoenix endpoint as `/logs`. The `static_path` helper should take that (the `script_name`) into account so that `<%= static_path(@conn, "/css/app.css") %>` returns  `/logs/css/app.css?vsn=...` instead of `/css/app.css?vsn=..` as it does now.

http://irclogger.com/.elixir-lang/2015-07-01#1435792685

**Comment by chrismccord** [comment]
I'm looking into this now. @josevalim remind me why we specifically exclude script_name from the static_path? (see this test case https://github.com/phoenixframework/phoenix/blob/master/test/phoenix/router/helpers_test.exs#L355-L361) For this case we need the opposite.

**Comment by josevalim** [comment]
The idea is that you want a single place to serve your assets. So even if you are forwarding to `/foo/bar/baz`, the static path is still at `/`. That's why we have a explicit `static_url` configuration for setting up the static path for everyone.

**Comment by josevalim** [comment]
Another way to tackle this is to support multiple endpoints running at the same time instead of doing:

    Endpoint -> Router -> Forward to another Endpoint -> Router

If we do this, we are going through the plug stack twice and things will certainly good bad. In other words, use forward to forward to another router, don't forward to another endpoint. We don't quite support it yet.

**Comment by josevalim** [comment]
We could do this with a `forward "/bar", Endpoint`  inside the main endpoint instead of the router. Not sure how this will play with URL generation though. We will likely need to change how we mount stuff a bit. We can talk over Skype later.

**Comment by josevalim** [comment]
Right now we are closing this, we don't really support mounting an endpoint inside the router. I will update the docs to make it clear.
