### ISSUE TITLE
"phx_join" gets to Channel

### ISSUE THREAD

**Issue by houshuang** [phoenixframework/phoenix#1012]
I found this message in my production log

```elixir
^[[0m^[[31m2015-07-08 07:15:39.279 [error] GenServer #PID<0.15393.0> terminating
Last message: %Phoenix.Socket.Message{event: "phx_join", payload: %{"userid" => 1663, "usernick" => "Tihawah"}, ref: "
29", topic: "rooms:35"}
State: %Phoenix.Socket{assigns: %{}, channel: Survey.RoomChannel, channel_pid: #PID<0.15393.0>, endpoint: Survey.Endpo
int, joined: true, pubsub_server: Survey.PubSub, ref: nil, topic: "rooms:35", transport: Phoenix.Transports.WebSocket,
 transport_pid: #PID<0.15382.0>}
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Survey.RoomChannel.handle_in/3
        (survey) web/channels/room_channel.ex:41: Survey.RoomChannel.handle_in("phx_join", %{"userid" => 1663, "userni
ck" => "Tihawah"}, %Phoenix.Socket{assigns: %{}, channel: Survey.RoomChannel, channel_pid: #PID<0.15393.0>, endpoint:
Survey.Endpoint, joined: true, pubsub_server: Survey.PubSub, ref: "29", topic: "rooms:35", transport: Phoenix.Transpor
ts.WebSocket, transport_pid: #PID<0.15382.0>})
        (phoenix) lib/phoenix/channel/server.ex:214: Phoenix.Channel.Server.handle_info/2
        (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

It's peculiar, because everything else is working well - a bunch of people have been logging on and off and chatting for days, and I only got this one message. (Right afterwards in the log, Tihawah was able to connect to the room and begin chatting normally. I wasn't sure what phx_join was or how I should handle it, but looking (quickly) at the source, it seems like this is an event that should be caught in Transport, and which would lead to the Channel's room function to be called, and not end up in handle_in?

The relevant code is here if it's useful: https://github.com/houshuang/survey/blob/master/web/channels/room_channel.ex

**Comment by chrismccord** [comment]
It would appear to be a client bug. It it possible that your javascript is sending `chan.join()` when it shouldn't? We can certainly improve the handling of this case though and it should not make it into the Channel.Server.

**Comment by houshuang** [comment]
My client library is here
https://github.com/houshuang/survey/blob/master/priv/static/js/chat.js, and
I know it's far from pretty. However it only calls chan.join() once, in
document.ready. I wonder if the page was reloaded or something, and it was
still connected to the channel, but called chan.join? Not sure - since it
seems like the user didn't notice at all (the library transparently
rejoined the chat channel right afterwards) I'm not too worried, but I
wanted to point it out.

On Wed, Jul 8, 2015 at 11:42 PM, Chris McCord <notifications@github.com>
wrote:

> It would appear to be a client bug. It it possible that your javascript is
> sending chan.join() when it shouldn't? We can certainly improve the
> handling of this case though and it should not make it into the
> Channel.Server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1012#issuecomment-119630155>
> .
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by chrismccord** [comment]
I was unable to recreate this, but I have added logging for these cases and the channel will ignore the duplicate join sent from the client.

**Comment by chrismccord** [comment]
If you continue to see a bunch of these logs please let us know. I'm convinced it is a client issue, but your linked js code looked pretty straight forward
