### ISSUE TITLE
Upstart scipt in Deployment doc needs update

### ISSUE THREAD

**Issue by Alamoz** [phoenixframework/phoenix#1014]
Not sure where to contribute to the documentation, so doing it here.

In the documentation under Deployment, in the section showing the Upstart script (http://www.phoenixframework.org/docs/advanced-deployment#section-setting-up-our-init-system), the Upstart script also requires definition of the app HOME, otherwise the app won't start under Upstart. I have experienced this myself, and it has also been reported elsewhere (see https://github.com/bitwalker/exrm/issues/61). The Upstart script needs the following additions (using the directory already from the doc example):

    env HOME=/app
    export HOME

**Comment by chrismccord** [comment]
Please direct guides issues to the phoenix_guides repo. Let's pick this up over there. Thanks!

**Comment by Alamoz** [comment]
Thanks! I just created a PR there.

**Comment by lancehalvorsen** [comment]
Aaaannnd merged. :)
