### ISSUE TITLE
Gitter Channel

### ISSUE THREAD

**Issue by joshua1** [phoenixframework/phoenix#1017]
Hi @chrismccord Can we have a gitter channel for the phoenix framework. It will be really helpful. I know there is an IRC channel and i have been there but gitter is a whole lot better

**Comment by chrismccord** [comment]
We have #elixir-lang on freenode and there is a #phoenix slack channel on the official elixir slack community, so yet-another chat/support place is too much for me to stay on top of. I hope one of those two options serve you well. IRC is our main support hub, but I also try to stay on top of slack activity and help answer questions. Folks are usually around in either place to help out.
