### ISSUE TITLE
mix phoenix.gen.json foo is erroring with 0.14

### ISSUE THREAD

**Issue by bcardarella** [phoenixframework/phoenix#1018]
With a brand new project I ran `mix phoenix.gen.json foo` and got the following error:

```
Generated ecto app
==> phoenix_ecto
Compiled lib/phoenix_ecto.ex
Compiled lib/phoenix_ecto/plug.ex
Compiled lib/phoenix_ecto/json.ex
Compiled lib/phoenix_ecto/html.ex
Generated phoenix_ecto app
==> my_app
Unchecked dependencies for environment dev:
* postgrex (Hex package)
  the dependency postgrex defined

  > In mix.exs:
    {:postgrex, ">= 0.0.0", [hex: :postgrex]}

  does not match the requirement specified

  > In deps/ecto/mix.exs:
    {:postgrex, "~> 0.8.3", [optional: true, hex: :postgrex]}

  Ensure they match or specify one of the above in your MyApp.Mixfile deps and set `override: true`
** (Mix) Can't continue due to errors on dependencies
```

**Comment by bcardarella** [comment]
I get that there is a dependency resolution mismatch, what I don't get is why the version constraints for `postgrex` are conflicting. The Phoenix constraint is `>= 0.0.0` which to me says "all versions" and the Ecto constaint is `~> 0.8.3` which to me says "versions `0.8.3` -` 0.8.n`. Shouldn't Ecto's version constraints over `postgrex` fall within the bounds of the constraint that Phoenix has?

**Comment by chrismccord** [comment]
And your project built properly prior to running `mix phoenix.gen.json` ? Or was this the first time you built it?

**Comment by bcardarella** [comment]
Brand new project, generated with `mix phoenix.new`

I spoke with @ericmj on irc and he thinks this is a mix issue

**Comment by ericmj** [comment]
I'm working on a fix in Hex. We will have a new release out today.

**Comment by chrismccord** [comment]
Ah thanks. I was just able to recreate. Let me do some digging.

**Comment by bcardarella** [comment]
@chrismccord my research shows that `postgrex` `0.9.0` was being installed when I ran `mix deps.get`. I suspect that mix was somehow ignoring the version bounds of Ecto and downloaded what Phoneix's deps said to get. When it attempts to compile at that point the version mismatch is seen by Mix and the error is raised. (pure guess)

**Comment by ericmj** [comment]
A new Hex version has been released with a fix.
