### ISSUE TITLE
mix phonenix.server fails right after mix phoenix.new

### ISSUE THREAD

**Issue by egor-laufer** [phoenixframework/phoenix#1019]
Hi,

Right after running ```mix phoenix.new``` I tried to run ```mix phoenix.server``` and got the following error:

```
Unchecked dependencies for environment dev:
* postgrex (Hex package)
  the dependency postgrex defined

  > In mix.exs:
    {:postgrex, ">= 0.0.0", [hex: :postgrex, optinal: true]}

  does not match the requirement specified

  > In deps/ecto/mix.exs:
    {:postgrex, "~> 0.8.3", [optional: true, hex: :postgrex]}

  Ensure they match or specify one of the above in your Blog.Mixfile deps and set `override: true`
** (Mix) Can't continue due to errors on dependencies
```

This seems to be due to ```postgrex >= 0.0.0``` resolving to ```0.9.0``` now, while ecto still expects ```0.8.3```.

The issue is minor, of course, but it does create confusion for new users (like me :))

**Comment by chrismccord** [comment]
This was a hex bug and has been fixed. Please run

    $ mix hex.local
    $ mix deps.unlock --all
    $ mix deps.get

**Comment by egor-laufer** [comment]
That did the trick, thank you!
