### ISSUE TITLE
updating with mix

### ISSUE THREAD

**Issue by muhendees** [phoenixframework/phoenix#1020]
Hello dears,

maybe it must be at elixir_lang, idk. So, idea is that make phoenix or any other archives to be upgraded by mix cli.
how i see it:
`mix archive.upgrade.phoenix` or `mix upgrade.phoenix` 

why?

it will make updating installing and upgrading phoenix apps faster than goin through links and getting new download link to bump it to mix archive install. 

another idea:

also, i would like to see installing phoenix like `mix archive.install phoenix` :+1: 
good luck to all.

**Comment by optikfluffel** [comment]
@muhendees to be consistent with your `mix archive.install phoenix` idea, upgrading should be `mix archive.upgrade phoenix`, don't you think?

**Comment by muhendees** [comment]
yeah, maybe that will be more elegant.

**Comment by chrismccord** [comment]
Something along these lines is coming in elixir 1.2
