### ISSUE TITLE
Could not find static manifest

### ISSUE THREAD

**Issue by chinh7** [phoenixframework/phoenix#1021]
I had my Phoenix app up and running for a while but then one day it just stopped and the last thing in the log is
```
[error] Could not find static manifest at "/app/_build/prod/lib/phoenix_app/priv/static/manifest.json". Run mix phoenix.digest after building your static files or remove the configuration from config/prod.exs.
```
From the log I realized I should run that mix task to generate the manifest file. But why did it run just fine in the beginning without it?

**Comment by chrismccord** [comment]
Did you upgrade your application recently

**Comment by chinh7** [comment]
I just figured out the reason it stopped was was because of an external datasource. Not really related to Phoenix per se. Thanks for the prompt response
