### ISSUE TITLE
Unintended messaging in tagline

### ISSUE THREAD

**Issue by waf** [phoenixframework/phoenix#1022]
My apologies for a slightly pedantic bug report. Phoenix's tagline in the readme and website is:

> Productive. Reliable. Fast. Most web frameworks make you choose between speed and a productive environment. Phoenix gives you both.

If our set of choices is 3 (productive, reliable, and fast), and Phoenix explicitly gives us 2 ("speed" and "productive"), doesn't that imply that it isn't "reliable"? Especially because we're framing the question in a way that makes the user think about having to choose.

In IT, the ["given a set of 3, pick any 2"](http://whatis.techtarget.com/definition/pick-two) scenario is fairly common.

**Comment by chrismccord** [comment]
I think it's okay as is. Thanks for the feedback though!

**Comment by josevalim** [comment]
I would like to reopen this because I have just entering the phoenix website after a while and now I have to agree. The trouble is that both "Productive. Reliable. Fast." and "Phoenix gives you both" are in bold, so they both end-up calling a lot of attention.

**Comment by josevalim** [comment]
One option, for now, is to simply remove the bold.

**Comment by josevalim** [comment]
I just removed the bold for now.

**Comment by scottmessinger** [comment]
For what it's worth, I've always been confused by the list of three things and then the "Phoenix gives you both." and more than once do a double take to make sure I'm not missing something. I'm looking at the website now, I think the change (to unbold the tagline) really helped (though I think finding a new phrasing of the tagline would be the best long term solution).

**Comment by josevalim** [comment]
One obvious approach is to include all:

```
Most web frameworks make you choose
between speed, maintainability and a productive environment. 
Phoenix gives you all.
```

Another approach is to be more straight-forward:

```
Phoenix is a web framework that brings you a productive environment
without sacrificing speed and maintainability.
```

Thoughts?

**Comment by paulcsmith** [comment]
I like the last version, Jose!

- Sent from my phone. Please excuse typos

**Comment by chrismccord** [comment]
I really like our secondary tagline as it is:

> Most web frameworks make you choose
between speed and a productive environment. 
> Phoenix gives you both

So we might try to rework the main tagline. This paired nicely when it was "Blazing fast web development", but I also like our main tagline, so not sure

**Comment by josevalim** [comment]
I am ok with reverting back to "Blazing fast" but we MUST include something about reliability or maintainability. When I am giving talks about Phoenix, it is the most enjoyed and well-received part. I also think it is very important conceptually, it is what makes us more than just a "faster Rails" at a first glance.

**Comment by paulcsmith** [comment]
Both are really good points. How about something along these lines?

> ## Write blazing fast web applications

> **Most web frameworks make you choose
between productivity, reliabaility and maintainability**
Phoenix has it all.

The "Phoenix has it all" seems a bit too pompous, but I think you get where I'm going with it.

Definitely could use some work, but might be a push in the right direction?

**Comment by josevalim** [comment]
> Most web frameworks make you choose
> between productivity, reliabaility and maintainability
> Phoenix has it all.

This actually fits the current tagline too so I guess we could decouple the discussions. :)

**Comment by paulcsmith** [comment]
Though I do like that "Write blazing fast web applications" is there. Speed is still important I think :S

**Comment by josevalim** [comment]
> Though I do like that "Write blazing fast web applications" is there. Speed is still important I think :S

Speed is important but it is not the main reason, by far. If speed was the main factor, we would have left Rails years ago. Seriously, there are way faster options than Rails for ages. Why haven't we migrated at least to node.js then? I would say because it is harder to write maintainable JS than Ruby. Or because the tooling is not as productive.

So we have been choosing other things above speed for years.  That's why I am against a tagline where the primary focus is performance.

I am pretty sure I said this before though, haha, so let's please focus on the secondary tagline here. We could start another discussion for the main one if you folks are inclined to.

**Comment by josevalim** [comment]
> I am pretty sure I said this before though, haha, so let's please focus on the secondary tagline here. We could start another discussion for the main one if you folks are inclined to.

This was not a comment to you @paulcsmith, but to @chrismccord, as he was the one who brought the topic back. :P`

**Comment by chrismccord** [comment]
> Phoenix has it all.

Paul, you are good! This is nice! So I think this could work per José:

> ## Productive. Reliable. Fast.

> **Most web frameworks make you choose
between productivity, reliability and maintainability**
Phoenix has it all.

:shipit: ?

**Comment by josevalim** [comment]
Last question: which one is better, to repeat the words in the tagline or use different ones?

> Most web frameworks make you choose between
> a productive environment, maintainability and speed
> Phoenix has it all.

**Comment by lancehalvorsen** [comment]
(I'm behind the curve here. It's rough being on the West Coast.)

I think the "Phoenix has it all" might be a bit much. What if we go back a few steps and just tweak it a little.

>Most web frameworks make you choose
between speed, maintainability and a productive environment. 
Phoenix gives you all three.

**Comment by chrismccord** [comment]
> ## Productive. Reliable. Fast.

> **Most web frameworks make you choose between
a productive environment, maintainability and speed**
Phoenix has it all.

**Comment by chrismccord** [comment]
@josevalim I like your changes:

> ## Productive. Reliable. Fast.

> **Most web frameworks make you choose between
a productive environment, maintainability and speed**
Phoenix has it all.

This gets the :+1: from me to ship.

> I think the "Phoenix has it all" might be a bit much.

I think it's okay for tagline to border on a bit much. I mean it underlines the promise that we are selling, we really do "have it all".

**Comment by josevalim** [comment]
Maybe the "has it all" has a strong meaning due from day-to-day usage? Maybe a "Phoenix provides it all" or "With Phoenix, you have all three" would be better?

Actually, I like "With Phoenix, you have all three" because it put the focus back on the "you". Thoughts?

**Comment by paulcsmith** [comment]
I *really* like

> With Phoenix, you have all three

I like the emphasis on *you*. I don't like the "all three" part though. Maybe:

> With Phoenix, you have it all

?

**Comment by chrismccord** [comment]
I will let everyone else hash it out for awhile and get my :shipit: use under control. Focusing on "you" is good

**Comment by josevalim** [comment]
Another idea is:

> Get a productive web framework
> without sacrificing speed and maintainability.

It is shorter and more straight to the point.

**Comment by lancehalvorsen** [comment]
I think my reaction to "have it all" is related to my bias against marketing/sales language. Since it's a bias, I'll definitely go with the majority.

And I really like that last one, @josevalim.
> Get a productive web framework
without sacrificing speed and maintainability.

**Comment by gjaldon** [comment]
I like the last one too

> Get a productive web framework
without sacrificing speed and maintainability.

The start of the tagline has 'Get' which encourages readers to take action. :)

**Comment by paulcsmith** [comment]
I like this version:

> Most web frameworks make you choose between
a productive environment, maintainability and speed.
With Phoenix, you have it all

And I like Jose's. I don't have a strong opinion either way though. Both have their pros/cons. I think we could ship either one

**Comment by doomspork** [comment]
Jose's suggestion is the clearest and most professional sounding to me.  The added benefit of his suggestion is that it no longer tries to compare Phoenix with "Most web frameworks"; it's just straight and to the point which reflects confidence:

> Get a productive web framework
> without sacrificing speed and maintainability.

It may be a factor of living in the Bay, surrounded by ad companies, but "have it all" / "has it all" sounds like hype and I think it cheapens the product.

**Comment by josevalim** [comment]
I went into a call with @chrismccord and I remembered it is bad to have two call to actions "Get a web framework" and "Build APIs, HTML5, ...". So my last proposal is:

> A productive web framework that does not make you
> sacrifice speed and maintainability

OR:

> A productive web framework that
> does not sacrifice speed and maintainability

Or some variation there of. Anyway, the point is that we need to keep one single action and today it is "Build APIs, HTML 5 apps and more" (which is great IMO).

It is on @chrismccord's hands now. Thanks everyone for the feedback.

**Comment by chrismccord** [comment]
This is what I settled on. Thanks everyone!

> ### Productive. Reliable. Fast.
> A productive web framework where speed and maintainability comes without compromise.

**Comment by lancehalvorsen** [comment]
:clap:  :+1:

**Comment by josevalim** [comment]
@chrismccord I am reopening because we need to change the description on GitHub as well as the references in the source code, specially in the generated app. :)

**Comment by josevalim** [comment]
Also, :+1: for the final choice.

**Comment by chrismccord** [comment]
> @chrismccord I am reopening because we need to change the description on GitHub as well as the references in the source code, specially in the generated app. :)

It's on my list, but I was waiting a bit just to make sure my wording choice wasn't poorly received :)
