### ISSUE TITLE
Get the underlying application name

### ISSUE THREAD

**Issue by rbishop** [phoenixframework/phoenix#1029]
It would be nice if we had a function to get the underlying OTP Application or application module name similar to how `Rails.application` works. If this already exists just let me know. If it doesn't exist and you find it useful I'm happy to implement. I imagine this would belong on `Phoenix.Endpoint` or `Phoenix.Config`?

**Comment by josevalim** [comment]
I think it is `Phoenix.Endpoint.config(:otp_app)`?

**Comment by rbishop** [comment]
There is [`Phoenix.Endpoint.Adapter.config/2`](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/adapter.ex#L83-L85) which delegates to [`Phoenix.Config.from_env/3`](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/config.ex#L63-L66).

`Phoenix.Config.from_env` requires me to know the `otp_app` and endpoint module in advance though. I'm hoping for something dumb that just returns the `otp_app` or Module:

```elixir
Phoenix.Config.module
#=> MyApp

Phoenix.Config.otp_app
#=> :my_app
```

**Comment by josevalim** [comment]
No, there is a config generated in your endponit and otp_app is there:

```iex
iex> MyApp.Endpoint.config(:otp_app)
:my_app
```

**Comment by josevalim** [comment]
I realize my original comment was not clear at all, sorry!

**Comment by rbishop** [comment]
No worries! I think it is me that isn't being clear. I'll describe what I'm trying to accomplish in full:

I'm writing a library for Phoenix applications to use. I want to know what the module name of the Phoenix application is. I could just ask the end-user to configure it (`config :my_library, app_name: MyApp`) in their Phoenix application, but I was hoping I could automate that step.

So the problem is that I don't know what `MyApp` is and I'm looking for a way to find that out without the user telling me.

**Comment by josevalim** [comment]
@rbishop ah, I see! We will never support anything like that because, opposite to Rails, Phoenix applications are not singletons. You can have multiple phoenix applications running side by side, on different ports, in the same vm.

**Comment by rbishop** [comment]
That's what I figured the reason would be :) Thanks!

**Comment by chrismccord** [comment]
@rbishop If you have the `conn` you can still get this information: `endpoint_module(conn).config(:otp_app)`

**Comment by rbishop** [comment]
@chrismccord Ohhh! That should work (and looks like it will accomodate multiple Phoenix apps). Thanks!

**Comment by nerboda** [comment]
Would there be anything wrong with doing something like this? @rbishop

```
def get_app_name do
    line = "mix.exs" |> File.stream! |> Enum.take(1)
    [name | _] = Regex.run(~r/(\S+)(?=\.)/, to_string(line))
    
    name
end
```

**Comment by rbishop** [comment]
We settled on requiring our users to specify their app name in the config for our package. Inferring stuff at runtime is tricky. Better to just let them specify it.

**Comment by mguimas** [comment]
@rbishop Would this work for you?

**Comment by karlosmid** [comment]
Hi @mguimas, in this context your proposal will not work because this will return application name of developed library, not the hosting phoenix application name.
