### ISSUE TITLE
Phoenix - Install error

### ISSUE THREAD

**Issue by bcs2002** [phoenixframework/phoenix#1031]
Trying to install Phoenix and gertting this error
D:\>mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.14.0/phoenix_new-0.14.0.ez
Are you sure you want to install archive https://github.com/phoenixframework/phoenix/releases/download/v0.14.0/phoenix_new-0.
14.0.ez? [Yn] Y
** (Mix) Could not access url https://github.com/phoenixframework/phoenix/releases/download/v0.14.0/phoenix_new-0.14.0.ez, er
ror: {:failed_connect, [{:to_address, {'github.com', 443}}, {:inet, [:inet], {:eoptions, {{{:badmatch, ""}, [{:ssl_handshake,
 :dec_hello_extensions, 2, [file: 'ssl_handshake.erl', line: 1737]}, {:ssl_handshake, :decode_handshake, 3, [file: 'ssl_hands
hake.erl', line: 926]}, {:tls_handshake, :get_tls_handshake_aux, 3, [file: 'tls_handshake.erl', line: 155]}, {:tls_connection
, :next_state, 4, [file: 'tls_connection.erl', line: 433]}, {:gen_fsm, :handle_msg, 7, [file: 'gen_fsm.erl', line: 503]}, {:p
roc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 237]}]}, {:gen_fsm, :sync_send_all_state_event, [#PID<0.81.0>, {:s
tart, :infinity}, :infinity]}}}}]}

Where am i wrong? Using Win 7 and Git installed
thx

**Comment by chrismccord** [comment]
For some reason ssl is failing. If you save the file locally, you should be able to install it from a local path:

    mix archive.install ./phoenix_new-0.14.0.ez

**Comment by bcs2002** [comment]
As mentioned in installation page, downloaded the file manually to D:\ folder and gave the cmds:

D:\>mix archive.install ./phoenix_new-0.14.0.ez
Are you sure you want to install archive ./phoenix_new-0.14.0.ez? [Yn] Y
* creating c:/Users/papasat/.mix/archives/phoenix_new-0.14.0.ez

Now i have a 124 kb phoenix_new-0.14.0.ez fine in my C:\Users\bcs\.mix\archives folder.
Is that all? Is the installation over?

**Comment by chrismccord** [comment]
> Now i have a 124 kb phoenix_new-0.14.0.ez file in my C:\Users\bcs\.mix\archives folder.
> Is that all? Is the installation over?

Yep. Now you should be able to run `mix phoenix.new my_new_app` from anywhere on your system to generate a new project.

**Comment by bcs2002** [comment]
Neat. Thanks Chris. 
But the dependency installation showed two npm warnings  and  then a windows box popped up saying erl.exe has stopped working:

Fetch and install dependencies? [Yn] Y
* running npm install && node node_modules/brunch/bin/brunch build
* running mix deps.get
npm WARN package.json @ No license field.
npm WARN optional dep failed, continuing fsevents@0.3.6

The curser is still spinning!

**Comment by chrismccord** [comment]
The warnings seem harmless and the npm deps can take a while to install (but should be no more than a couple minutes). Any luck running `mix phoenix.server` after the npm install finished?

**Comment by bcs2002** [comment]
Its been nearly 15 min now and has not gone beyond these two npm installations. Possibly stuck. Dont know if its downloading or not. Some progress bar or displaying of number of bytes download would be helpful. I think Erlang has also stopped. I'll terminate and start all over again.

**Comment by josevalim** [comment]
@bcs2002 just say no when it asks if you want to install the dependencies automatically and then follow the instructions. :)

**Comment by bcs2002** [comment]
Thanks Jose. But had already started the process...now this time a module error:

Fetch and install dependencies? [Yn] Y
* running npm install && node node_modules/brunch/bin/brunch build
* running mix deps.get
npm WARN package.json @ No license field.
module.js:338
    throw err;
          ^
Error: Cannot find module 'ansi-color'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\dev\my_new_app\node_modules\brunch\node_modules\loggy\index.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

We are all set! Run your Phoenix application:

What is this ansi-color?
But mix phoenix.server ran successfully and the page displayed on 4000 but without the stylesheet(?)

**Comment by chrismccord** [comment]
@bcs2002 Did you follow the instructions and run `npm install` ? What version of node are you running? `node -v`. We require >= 0.12.0

**Comment by bcs2002** [comment]
D:\>node -v
v0.12.7

D:\>npm -v
2.11.3
 and
C:\Users\bcs\Documents\GitHub> git --version
git version 1.8.4.msysgit.0

**Comment by chrismccord** [comment]
And as a sanity check, you ran `npm install` in your project directory and it completed without errors (other than the warnings above) ?

**Comment by bcs2002** [comment]
I've installed nodejs (and npm) in C:\Program Files\nodejs\ with necessary entries in PATH .
Manually downloaded phoenix_new-0.14.0.ez  to  D:\
then gave  D:\> mix archive.install ./phoenix_new.ez
D:\>mix phoenix.new ./dev/my_new_app
D:\>cd ./dev/my_new_app
D:\Dev\my_new_app>mix phoenix.server

Never gave any npm install commands anywhere. Should I? Where?
And why the css files did not run?
Note: I am on windows 7 home

**Comment by lancehalvorsen** [comment]
When the `mix phoenix.new` task prompted to `Fetch and install dependencies? [Yn] Y`, and you responded with `y`, it took care of both the elixir dependencies and the npm ones.

This may not be a satisfying response, but whenever I've had an `npm install` go sideways, I'm rarely able to save it. I often end up deleting the the npm modules and re-running `npm install`.

**Comment by bcs2002** [comment]
Thanks for the input., Lance. 
But do you need to run npm install in the project directory?

**Comment by josevalim** [comment]
@bcs2002 if you say "no" to fetching and intalling dependencies, then you need "npm install", yes. :)

**Comment by bcs2002** [comment]
I gave "Y". Anyway, it compiled without much fuss(except for the last 'ansi-color' error) and ran on 4000. But why a plain display? Looks as if CSS was not applied....

**Comment by lancehalvorsen** [comment]
@bcs2002, yes, you should run `npm install` in the project directory. Inside the project directory, there should be a root-level `node_modules` directory.

**Comment by lancehalvorsen** [comment]
@bcs2002 so Phoenix uses brunch.io by default to handle static assets, including CSS. Brunch installs it's dependencies via npm. If npm isn't able to completely install all of the dependencies, things like this can happen. I'm not sure exactly what is causing the lack of CSS in your particular install, but the npm dependencies for brunch.io seem likely.

**Comment by bcs2002** [comment]
@lancehalvorsen ,But as you(and Jose) mentioned above the "Y" i gave  for 'Fetch and install dependencies'  would have taken care of npm in the project dir. (whereas  a 'n' would have required a npm install ). 
The project dir does have a brunch-config.js file and the node_modules contain those seven *brunch folders(css-brunch, javascript-brunch...etc)

**Comment by lancehalvorsen** [comment]
@bcs2002 yes, but in my experience (on all sorts of projects, not just Phoenix), occasionally npm installs have problems. Sometimes just re-running `npm install` will fix it. Sometimes it's necessary to delete all the existing npm modules and then run `npm install` to try again.

**Comment by bcs2002** [comment]
Tried without deleting...
D:\Dev\my_new_app>npm install

npm WARN package.json @ No license field.

But the package.json mentions the seven brunch dependencies that have already been installed in the node-modules folder. So dont know why then CSS was not applied....

**Comment by chrismccord** [comment]
@bcs2002 To save some back-and-forth. Can you please try the following steps and report back:

Delete the `node_modules` directory in your project.
Run:

    $ npm install
    $ mix phoenix.server

and let us know the output.

**Comment by bcs2002** [comment]
giving the same warning msg and exits
D:\Dev\my_new_app\node_modules>npm install
npm WARN package.json @ No license field.

D:\Dev\my_new_app\node_modules>

**Comment by chrismccord** [comment]
What was the output of `mix phoenix.server` ?

**Comment by bcs2002** [comment]
D:\Dev\my_new_app>mix phoenix.server
[info] Running MyNewApp.Endpoint with Cowboy on http://localhost:4000
module.js:338
    throw err;
          ^
Error: Cannot find module 'ansi-color'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (d:\Dev\my_new_app\node_modules\brunch\node_modules\loggy\index.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by chrismccord** [comment]
For one reason or another (or probably many reasons), some windows users have issues with node. Some have had success by installing brunch globally `npm install -g brunch` , then running brunch directly on the console alongside their phoenix app with `brunch watch`. This will require you to remove the `watchers` configuration line from `dev.exs` (which is where the error is coming from. Please give this a shot as your phoenix app is otherwise all set to go.

**Comment by bcs2002** [comment]
I have manually installed brunch using npm using:

E:\>npm install -g brunch

npm WARN optional dep failed, continuing fsevents@0.3.6
C:\Users\itm\AppData\Roaming\npm\brunch -> C:\Users\itm\AppData\Roaming\npm\node_modules\brunch\bin\brunch

> brunch@1.8.3 postinstall C:\Users\bcs\AppData\Roaming\npm\node_modules\brunch
> node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"

brunch@1.8.3 C:\Users\itm\AppData\Roaming\npm\node_modules\brunch
├── fcache@0.1.1
├── async-waterfall@0.1.5
├── quickly-copy-file@0.1.0
├── commonjs-require-definition@0.2.0
├── async-each@0.1.6
├── commander@2.7.1 (graceful-readlink@1.0.1)
├── debug@2.1.3 (ms@0.7.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── coffee-script@1.9.3
├── source-map@0.3.0 (amdefine@1.0.0)
├── read-components@0.6.1 (component-builder@0.10.1)
├── anysort@1.0.0 (anymatch@1.0.0)
├── chokidar@1.0.5 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, is-binary-path@1.0.1, readdirp@1.3.0)
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.1.6)
├── init-skeleton@0.4.4 (ncp@2.0.0, rimraf@2.3.4)
├── deppack@0.1.1 (browser-resolve@1.7.2, detective@4.0.3)
├── loggy@0.2.0 (growl@1.7.0, ansi-color@0.2.1, date-utils@1.2.17)
└── pushserve@0.1.6 (connect-slashes@0.0.11, commander@2.0.0, express@3.3.8)

E:\>

Brunch folder is available in   C:\Users\bcs\AppData\Roaming\npm\node_modules\ with the brunch coffeescript file in  C:\Users\bcs\AppData\Roaming\npm\node_modules\brunch\bin\  folder.
But when i run mix phoenix.server,  it says it does not exist.

E:\Dev\Phoenix\crudapp>mix phoenix.server

[info] Running Crudapp.Endpoint with Cowboy on http://localhost:4000
[error] Could not start node watcher because script "node_modules/brunch/bin/brunch" does not exist. Please make sure it has been installed by running: npm install

Do you need to add path? 
Which "node_modules/brunch/bin/brunch" is it referring to?

**Comment by bcs2002** [comment]
So any idea whyi am getting this msg even though Brunch folder is available in C:\Users\bcs\AppData\Roaming\npm\node_modules\ ?

E:\Dev\Phoenix\crudapp>mix phoenix.server

[info] Running Crudapp.Endpoint with Cowboy on http://localhost:4000
[error] Could not start node watcher because script "node_modules/brunch/bin/brunch" does not exist. Please make sure it has been installed by running: npm install

**Comment by josevalim** [comment]
What is the name of your app? Is it "Roaming"? Also, are you sure that path exists completely?

**Comment by bcs2002** [comment]
Project folder name is cruddapp. 
E:\Dev\Phoenix\cruddapp>brunch -V
1.8.3

**Comment by josevalim** [comment]
The error message is looking for a path inside your application, so the Roaming one is not useful. Given you do have brunch installed, maybe you should change your watchers configuration in your `config/dev.exs` file to:

    watchers: [brunch: ["watch"]]

**Comment by bcs2002** [comment]
Replaced  the line
 watchers: [node: ["node_modules/brunch/bin/brunch", "watch"]]       in config/dev.exs   with 
 watchers: [brunch: ["watch"]] 

And this is what i got:

E:\Dev\Phoenix\cruddapp>mix phoenix.server
Compiled lib/cruddapp.ex
Compiled web/web.ex
Compiled lib/cruddapp/repo.ex
Compiled web/router.ex
Compiled web/controllers/page_controller.ex
Compiled web/views/error_view.ex
Compiled web/views/layout_view.ex
Compiled web/views/page_view.ex
Compiled lib/cruddapp/endpoint.ex
Generated cruddapp.app
[info] Running Cruddapp.Endpoint with Cowboy on http://localhost:4000
[error] Task #PID<0.324.0> started from Cruddapp.Endpoint terminating
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["e:/Dev/Phoenix/cruddapp", "brunch", ["watch"]]
** (exit) an exception was raised:
    ** (ErlangError) erlang error: :eacces
        :erlang.open_port({:spawn_executable, 'c:/Users/bcs/AppData/Roaming/npm/brunch.cmd'}, [{:cd, "e:/Dev/Phoenix/cruddapp"}, :stderr_to_stdout, :use_stdio, :
exit_status, :binary, :hide, {:args, ["watch"]}])
        (elixir) lib/system.ex:445: System.cmd/3
        (phoenix) lib/phoenix/endpoint/watcher.ex:13: Phoenix.Endpoint.Watcher.watch/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
[info] Running Cruddapp.Endpoint with Cowboy on http://localhost:4000
[error] Task #PID<0.327.0> started from Cruddapp.Endpoint terminating
.....
......
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["e:/Dev/Phoenix/cruddapp", "brunch", ["watch"]]
** (exit) an exception was raised:
    ** (ErlangError) erlang error: :eacces
        :erlang.open_port({:spawn_executable, 'c:/Users/bcs/AppData/Roaming/npm/brunch.cmd'}, [{:cd, "e:/Dev/Phoenix/cruddapp"}, :stderr_to_stdout, :use_stdio, :
exit_status, :binary, :hide, {:args, ["watch"]}])
        (elixir) lib/system.ex:445: System.cmd/3
        (phoenix) lib/phoenix/endpoint/watcher.ex:13: Phoenix.Endpoint.Watcher.watch/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
[info] Application cruddapp exited: shutdown

**Comment by josevalim** [comment]
Ouch, I am out of ideas. I can only think you could do:

    watchers: [node: ["c:/Users/bcs/AppData/Roaming/npm/brunch", "watch"]]

But that will only work on your machine.

**Comment by chrismccord** [comment]
Lastly, if that doesn't work, proceeding with running brunch manually is what I would try like I said above. So follow these steps after you try José's previous config:

1. In your `config/dev.exs` set watchers to empty:

```    
    watchers: []
```
2. Make sure node deps are installed, with brunch global:

```console
my_app> npm install
my_app> npm install -g brunch
```
3. Run `my_app> mix phoenix.server` in a tab
4. Run `my_app> brunch watch` in a tab

Unfortunately some windows folks have had trouble with node and without access to a machine, it's not something I can investigate further. Please find us on #elixir-lang irc if you have questions and maybe we can better pinpoint.

**Comment by bcs2002** [comment]
Pl excuse my reopening . Unable to get through IRC.

Previous brunch error disappeared after running:
>npm config  set  registry="http://registry.npmjs.org/"      and
>npm config  delete  proxy

Now a python error is shown while installing  node-sass. Even when node-sass alone was reinstalled using npm, this python executable error is displayed......

Fetch and install dependencies? [Yn] Y
* running npm install && node node_modules/brunch/bin/brunch build
* running mix deps.get
npm WARN package.json @ No license field.
npm WARN optional dep failed, continuing fsevents@0.3.6
tunneling socket could not be established,   cause=connect    ETIMEDOUT
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (E:\Dev\phoenix\crudf\node_modules\sass-brunch\node_modules\node-sass\node_modules\pangyp\lib\configure.js:104:14)
gyp ERR! stack     at E:\Dev\phoenix\crudf\node_modules\sass-brunch\node_modules\node-sass\node_modules\pangyp\lib\configure.js:65:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\nodejs0.12_64\\node.exe" "E:\\Dev\\phoenix\\crudf\\node_modules\\sass-brunch\\node_modules\\node-sass\\node_modules\\pangyp\\bin\\node
-gyp" "rebuild"
gyp ERR! cwd E:\Dev\phoenix\crudf\node_modules\sass-brunch\node_modules\node-sass
gyp ERR! node -v v0.12.7
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok
Build failed
E:\Dev\phoenix\crudf\node_modules\brunch\lib\watch.js:446
          throw new Error("You probably need to execute `npm install` to insta
                ^
Error: You probably need to execute `npm install` to install brunch plugins. Error: `libsass` bindings not found. Try reinstalling `node-sass`?
  at E:\Dev\phoenix\crudf\node_modules\brunch\lib\watch.js:446:17
  at Array.map (native)
  at loadDeps (E:\Dev\phoenix\crudf\node_modules\brunch\lib\watch.js:431:8)
  at loadPackages (E:\Dev\phoenix\crudf\node_modules\brunch\lib\watch.js:451:13)

**Comment by chrismccord** [comment]
apparently node-sass needs python, so yes if you want sass support. If you don't need sass support, you can remove it from your package.son dups and forgo sass compiling.

**Comment by bcs2002** [comment]
Ok.  Is that why CSS was not applied to the default page?

**Comment by chrismccord** [comment]
yes, we include an app.scss sass file that brunch is failing to build, but it's really just normal css today, so you could rename it to app.css and remove the brunch-sass package from your npm deps in package.json, or you can look into the necessary python dependency to build node-sass

**Comment by bcs2002** [comment]
Fine 
what about db drivers? Are there any drivers available for Phoenix to connect with Oracle?

**Comment by chrismccord** [comment]
Not sure about Oracle. Please direct these questions to irc or the mailing list. I'm on irc now. Thanks!

**Comment by bcs2002** [comment]
This is the error i get now when creating new phoenix project.....first time it is ERR 404 javascript-brunch  not found and second time its is and  uglify-js-brunch....

D:\>mix phoenix.new ./dev/phoenix/crud
* creating ./dev/phoenix/crud/config/config.exs
* creating ./dev/phoenix/crud/config/dev.exs
.....

Fetch and install dependencies? [Yn] Y
* running npm install && node node_modules/brunch/bin/brunch build
* running mix deps.get
npm WARN package.json @ No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "instal
l"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code E404

npm ERR! 404 Not Found: javascript-brunch
npm ERR! 404
npm ERR! 404 'javascript-brunch' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\dev\phoenix\crud\npm-debug.log

We are all set! Run your Phoenix application:

    $ cd ./dev/phoenix/crud
    $ mix phoenix.server

You can also run it inside IEx (Interactive Elixir) as:

    $ iex -S mix phoenix.server


Its javascript-brunch not found. I deleted the project folder and created again....

D:\>mix phoenix.new ./dev/phoenix/crud
* creating ./dev/phoenix/crud/config/config.exs
* creating ./dev/phoenix/crud/config/dev.exs
........

Fetch and install dependencies? [Yn] y
* running npm install && node node_modules/brunch/bin/brunch build
* running mix deps.get
npm WARN package.json @ No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "instal
l"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code E404

npm ERR! 404 Not Found: uglify-js-brunch
npm ERR! 404
npm ERR! 404 'uglify-js-brunch' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\dev\phoenix\crud\npm-debug.log

We are all set! Run your Phoenix application:

    $ cd ./dev/phoenix/crud
    $ mix phoenix.server

You can also run it inside IEx (Interactive Elixir) as:

    $ iex -S mix phoenix.server


This time it is uglify-js-brunch not found
