### ISSUE TITLE
Tidy up transport logging

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1032]

**Comment by chrismccord** [comment]
We should remove `Plug.Logger` from the WebSocket and LongPoll transports in favor of Phoenix.Channel.Transport logging

**Comment by gjaldon** [comment]
@chrismccord I'd like to take this on this if it's available. :)

**Comment by josevalim** [comment]
Oops, sorry, this one is mostly a TODO for me as @chrismccord did most of the work and it is up for me to review it.

**Comment by gjaldon** [comment]
@josevalim ok, copy that. :)
