### ISSUE TITLE
exrm upvert back to the previous version after stoping server

### ISSUE THREAD

**Issue by chawladev** [phoenixframework/phoenix#1034]
I have some issues upgrading the release using exrm. The issue is when after stoping the running release. the upgrades revert back to the initial version when restarting it again.

To Reproduce -
After releasing the version 0.0.1 using mix release for the first time.

Let the production run using $ rel/test_app/bin/test_app start

then Do some changes and change the version number to 0.0.2 and do the mix release to get the version 0.0.2 out.

Then do the upgrade using $ rel/test_app/bin/test_app upgrade "0.0.2"

Everyhing is working fine until here.
When I stop the server using $ rel/test_app/bin/test_app stop

When I start the server again it came back to version "0.0.1" again.

**Comment by gjaldon** [comment]
@chawladev this is not a Phoenix issue but an exrm one, you could file exrm issues here https://github.com/bitwalker/exrm/issues.

**Comment by chawladev** [comment]
Thank you @gjaldon.

I filed up an issue there. https://github.com/bitwalker/exrm/issues/168 to find out the root cause.

Anyhow I've found a quick fix as below incase other people faced facing the same issue.

The issue is that when using $ rel/app_name/bin/app_name upgrade "0.0.2" it doesn't update the value of REL_VSN from "0.0.1" to "0.0.2" in the $ rel/app_name/bin/app_name file

So to fix this just open the file rel/app_name/bin/app_name and find the line with REL_VSN="0.0.1" and then update to REL_VSN="0.0.2" will fix this.
