### ISSUE TITLE
Create test db from development schema

### ISSUE THREAD

**Issue by bcardarella** [phoenixframework/phoenix#1035]
I realize that #951 already was opened but here is my use case:

I am migrating a node.js application over to Phoenix. the database already exists. My development migrations are to normalize the schema with many table/column renames. I currently cannot test the application without creating the test db manually from the development db as a template. This is fine for my development machine, but doesn't work within the context of running the application on Travis where that development db doesn't exist at all.

**Comment by josevalim** [comment]
Can you please open up an ecto issue? Let's discuss what we can do to solve this. We can provide SQL schemas, similar to what Rails does. It has its downsides though. It conflicts a lot, sometimes different PG versions would have different outputs, etc but I cannot think of any better option.
