### ISSUE TITLE
cannot background Phoenix process

### ISSUE THREAD

**Issue by FND** [phoenixframework/phoenix#1041]
It seems like Phoenix resists being backgrounded in the shell (Phoenix v0.14.0 on OS X):

    $ mix phoenix.new --no-brunch tmp
    $ cd tmp
    $ mix phoenix.server &
    …
    Compiled lib/tmp/endpoint.ex
    Generated tmp app
    [info] Running Tmp.Endpoint with Cowboy on http://localhost:4000

    $ jobs
    [1]+  Stopped                 mix phoenix.server

The server accepts connections, but doesn't send any response.

(This is problematic for me because I want to run HTTP tests [using](https://www.innoq.com/en/blog/gabbi-declarative-http-testing/) [gabbi](http://gabbi.readthedocs.org).)

**Comment by josevalim** [comment]
Please try: `elixir --detached -S mix phoenix.server`

**Comment by FND** [comment]
I didn't know about that, thanks! However, I couldn't find a way to get the PID of the Phoenix process (it's not `$!`), so I have no reliable way to kill the server again.

**Comment by josevalim** [comment]
can you check if `erl -detached` gives the proper PID? I need to check if it is an erlang or elixir bug.

**Comment by FND** [comment]
I'm not sure what you're referring to, exactly - so here's what I got:

    $ elixir --detached -S mix phoenix.server &
    [1] 19904

    $ echo $!
    19904

    [1]+  Done                    elixir --detached -S mix phoenix.server

    $ kill 19904
    -bash: kill: (19904) - No such process

    $ lsof -i :4000
    COMMAND    PID USER ...
    beam.smp 19934  fnd ...

So the Phoenix process is independent of the Elixir process that spawned it.

I'm not sure how to reproduce this with Erlang, as there I only get that one process:

    $ erl --detached &
    [1] 20288

    $ echo $!
    20288

    [1]+  Stopped                 erl --detached

    $ ps aux | grep erl
    ... 20288  ...  .../erlang/17.5/lib/erlang/erts-6.4/bin/beam.smp -- -root .../erlang/17.5/lib/erlang -progname erl -- -home /Users/fnd -- --detached

So it's the same PID, but the process is also stopped.

**Comment by josevalim** [comment]
In Erlang it would be "-detached" (single -).

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by FND** [comment]
Ah, sorry about that - this seems more informative:

    $ erl -detached &
    [1] 20515

    $ echo $!
    20515

    [1]+  Done                    erl -detached

    $ kill 20515
    -bash: kill: (20515) - No such process

    $ ps aux | grep erl
    ... 20528  ...  .../erlang/17.5/lib/erlang/erts-6.4/bin/beam.smp -- -root .../erlang/17.5/lib/erlang -progname erl -- -home /Users/fnd -- -noshell -noinput

**Comment by josevalim** [comment]
Yeah, so I have no idea what we can do. Maybe you will need to find someway of getting this information.

**Comment by jonhkr** [comment]
I researched about this and found this http://erlang.org/pipermail/erlang-questions/2013-October/075803.html
Maybe it is related to this issue.

**Comment by FND** [comment]
Thanks, @jonhkr, that thread is certainly relevant - however, the proposed solutions seem fairly heavy-handed for such a simple task.

As for that particular message you'd linked to, I'm not entirely sure it would solve this problem:

> Yes, when you start erl with -s or -run options then a separate process is
> started by init to evaluate these calls. This process then terminates after
> the calls have completed. [adding `receive` at the end of the parent script]
> meant that that call never returned and hence the start process never
> terminated.

So, let's say Elixir had a `--no-halt` option¹ which would prevent the original process from terminating as described above:

    $ elixir --detached --no-halt -S mix phoenix.server &
    $ echo $! # parent's PID

AIUI, that would result in both a parent and a child process - with the difference being that the parent process is still running. Thus it _might_ be possible to kill the child process (which is what I'm after) by killing the parent - assuming they're actually parent and child?

Clearly this is all conjecture. At this point, I'm insufficiently familiar with Elixir to create a reduced test case.


¹ I'm aware Mix does have that option, but it doesn't seem to make a difference.

**Comment by josevalim** [comment]
@FND i think it is not terminating because of the --no-halt function. Probably something misbehaving because it is disconnected from STDIO.

**Comment by FND** [comment]
@josevalim Sorry, my previous comment was nonsense; I'd assumed that `--no-halt` was a Mix option (which in hindsight doesn't make much sense), but it is in fact an Elixir option. So I was imagining something that already exists.

Anyway, even with `--no-halt`, the parent process still terminates:

    $ elixir --detached --no-halt -S mix phoenix.server &
    [1] 3769

    $ echo $!
    3769

    [1]+  Done                    elixir --detached --no-halt -S mix phoenix.server

    $ kill 3769
    -bash: kill: (3769) - No such process

So I still have no way of getting at (i.e. kill) the newly spawned child process. (Presumably `--no-halt` applies to that child process rather than the parent.)

**Comment by josevalim** [comment]
I found a workaround way to get the PID from within Elixir:

    elixir --detached -e "File.write! 'pid', :os.getpid" -S mix phoenix.server && cat pid

**Comment by FND** [comment]
Excellent, that works just as I need it to - thank you! It might not be pretty, but I'll gladly take it if that's all Erlang allows.
