### ISSUE TITLE
Can't compile on heroku

### ISSUE THREAD

**Issue by ulrikaugustsson** [phoenixframework/phoenix#1045]
Created a new app, generated a json-endpoint (?) and followed the official guide to deploying on heroku. But I'm getting this error message when trying to build. I have googled for about 2-3h without any luck and I'm too new to elexir to figure this out by myself.

```
remote: ==> calendar
remote: Compiled lib/calendar.ex
remote: Compiled web/web.ex
remote: 
remote: == Compilation error on file lib/calendar/endpoint.ex ==
remote: ** (CompileError) lib/calendar/endpoint.ex:364: invalid literal nil in <<>>
remote:     (elixir) src/elixir_bitstring.erl:149: :elixir_bitstring.build_bitstr/4
remote:     (elixir) src/elixir_clauses.erl:36: :elixir_clauses.clause/7
remote:     (elixir) src/elixir_def.erl:178: :elixir_def.translate_clause/7
remote:     (elixir) src/elixir_def.erl:167: :elixir_def.translate_definition/8
remote:     (elixir) src/elixir_def.erl:82: :elixir_def.store_definition/9
remote:     lib/calendar/endpoint.ex:2: (module)
remote: 
remote: 
remote:  !     Push rejected, failed to compile elixir app
```

**Comment by chrismccord** [comment]
Can you provide your endpoint.ex source file?

**Comment by ulrikaugustsson** [comment]
I'm not at my computer right now but I haven't changed it after generating the app.

**Comment by josevalim** [comment]
This is related to your URL configuration. Have you set `[url: [path: nil]]` or something of sorts? Please post you config/* files, you certainly have changed them before deploy.

**Comment by ulrikaugustsson** [comment]
Followed this guide: http://www.phoenixframework.org/docs/heroku
So I guess it should be `url: [host: System.get_env("HOST"), port: 80]`

**Comment by josevalim** [comment]
We should deep merge stuff... but just to be double sure, can you try changing that to `url: [host: System.get_env("HOST"), port: 80]`?

**Comment by gjaldon** [comment]
@ulrikaugustsson did you add environment variable for `"HOST"` for your Heroku app? I don't think that was mentioned in the guide.

**Comment by ulrikaugustsson** [comment]
Might be that i have not set the HOST variable, will try that when I get to my computer in about 1h.

**Comment by ulrikaugustsson** [comment]
My endpoint.ex
```Elixir
defmodule Calendar.Endpoint do

	use Phoenix.Endpoint, otp_app: :calendar

	# Serve at "/" the static files from "priv/static" directory.
	#
	# You should set gzip to true if you are running phoenix.digest
	# when deploying your static files in production.
	plug Plug.Static,
		at: "/", from: :calendar, gzip: false,
		only: ~w(css images js favicon.ico robots.txt)

	# Code reloading can be explicitly enabled under the
	# :code_reloader configuration of your endpoint.
	if code_reloading? do
		plug Phoenix.LiveReloader
		plug Phoenix.CodeReloader
	end

	plug Plug.RequestId
	plug Plug.Logger

	plug Plug.Parsers,
		parsers: [:urlencoded, :multipart, :json],
		pass: ["*/*"],
		json_decoder: Poison

	plug Plug.MethodOverride
	plug Plug.Head

	plug Plug.Session,
		store: :cookie,
		key: "_calendar_key",
		signing_salt: "c+bVBr1Y"

	plug :router, Calendar.Router
end
```

**Comment by ulrikaugustsson** [comment]
@josevalim Your fix ended up working, thanks!

**Comment by josevalim** [comment]
Ok, I will investigate because my fix should not be required. Thanks for following up!

**Comment by ulrikaugustsson** [comment]
@josevalim Did you find why that was needed? Just curious.

**Comment by josevalim** [comment]
I cannot reproduce it in master in any way, so I am assuming it was fixed along the way.

**Comment by ulrikaugustsson** [comment]
Awesome!
