### ISSUE TITLE
Compiling invalid SCSS crashes the Brunch pipeline

### ISSUE THREAD

**Issue by dymk** [phoenixframework/phoenix#1050]
Steps to reproduce: 
 - Make a new Phoenix project
 - make `app.scss` some valid CSS, such as `body { background-color: red; }`
 - observe the background color of the page is red
 - change the SCSS to be invalid, such as: `body {}`
 - further changes (even if valid) to app.scss don't recompile app.css in `priv`

The following error will be in the server console: 
```
./phoenix_test_project/node_modules/brunch/lib/fs_utils/pipeline.js:86
        throw new Error("Brunch SourceFile: file " + path + " data is invalid"
              ^
Error: Brunch SourceFile: file web/static/css/app.scss data is invalid
  at ./phoenix_test_project/node_modules/brunch/lib/fs_utils/pipeline.js:86:15
  at libsass.render.success (./phoenix_test_project/node_modules/sass-brunch/index.js:98:7)
  at options.success (./phoenix_test_project/node_modules/sass-brunch/node_modules/node-sass/lib/index.js:163:7)

```

**Comment by chrismccord** [comment]
This is a brunch issue and I can not recreate it on my system. It looks like there was an issue that was patched several months ago here https://github.com/brunch/sass-brunch/issues/75
