### ISSUE TITLE
Obscure errors where the error string is printed as a binary

### ISSUE THREAD

**Issue by arthurcolle** [phoenixframework/phoenix#1051]
I got a few of these types of errors before. Usually they manifest as I'm making changes to controllers or models, and then they appear in my server logs as I try to render pages. If I restart the server, they sometimes go away.

This time, it didn't go away after a restart so I'm posting it as an example.

```
19:49:48.681 [error] GenServer :standard_error_sup terminating
Last message: {:EXIT, #PID<0.22.0>, :eagain}
State: {:state, :standard_error, :undefined, #PID<0.22.0>, {:local, :standard_error_sup}}
** (stop) :eagain
** (ArgumentError) argument error
    (stdlib) :io.put_chars(:standard_error, :unicode, [['web/controllers/order_controller.ex', 58, '48', 58, 32], 'warning: ', [118, 97, 114, 105, 97, 98, 108, 101, 32, 'descr', 32, 105, 115, 32, 117, 110, 117, 115, 101, 100], 10])
    (elixir) src/elixir_errors.erl:257: :elixir_errors.do_warn/1
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```

I translated the [118,...,32] and [32,...,100] ASCII letter lists and got this:

"vˍ;leC��unused" 

No real idea what it means but I just wanted to raise this as something to maybe look out for.

**Comment by arthurcolle** [comment]
Follow up - 

Restarted server again. Gave me an error saying that "a/0 is undefined on line 33"

Checked line 33 of file it mentioned, a/0 was defined before the block. Restarted server again. It worked.

Not really understanding how the underlying framework/Elixir works in such a way for that to be possible...

**Comment by josevalim** [comment]
Other folks have been reporting this too. What is your erlang version?

**Comment by josevalim** [comment]
Can you folks put this to a file and run it:

```elixir
Enum.each 1..1000, fn x ->
  :timer.sleep(1000);
  :io.put_chars(:standard_error, [['web/controllers/order_controller.ex', 58, '48', 58, 32], 'warning: ', [118, 97, 114, 105, 97, 98, 108, 101, 32, 'descr', 32, 105, 115, 32, 117, 110, 117, 115, 101, 100], 10])
end
```

Does it reproduce the error somewhat frequently? Also, were you running `mix phoenix.server` or `iex -S mix phoenix.server`?

**Comment by josevalim** [comment]
Also, which OS are you using? Note you should not translate the message, it is properly encoded. So this is not an encoding issue.

**Comment by josevalim** [comment]
This is an Erlang/Elixir bug. Please provide more info as it would be useful but we can close this.

**Comment by arthurcolle** [comment]
I am using Mac OS X Yosemite 10.10.4

If you give me some commands to run I can give you any information you would like.

**Comment by arthurcolle** [comment]
It continues to happen. If you keep running `mix phoenix.server` eventually it seems to correct itself, but I got this output a few times as well just now:

17:44:11.978 [error] GenServer :standard_error_sup terminating
Last message: {:EXIT, #PID<0.22.0>, :eagain}
State: {:state, :standard_error, :undefined, #PID<0.22.0>, {:local, :standard_error_sup}}
** (stop) :eagain
Compiled web/views/layout_view.ex
Compiled web/views/session_view.ex

```
== Compilation error on file web/views/message_view.ex ==
** (ArgumentError) argument error
    (stdlib) :io.put_chars(:standard_error, :unicode, [['web/templates/message/form.html.eex', 58, '23', 58, 32], 'warning: ', [118, 97, 114, 105, 97, 98, 108, 101, 32, 'curr', 32, 105, 115, 32, 117, 110, 117, 115, 101, 100], 10])
    (elixir) src/elixir_errors.erl:257: :elixir_errors.do_warn/1
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```

**Comment by josevalim** [comment]
@arthurcolle yes, all signs point to an Erlang bug. Can you please run `iex` and paste the first line with Erlang and Elixir versions?

**Comment by arthurcolle** [comment]
```
Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.1.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```

**Comment by arthurcolle** [comment]
It occurred in Erlang 17 as well, but yeah the above is the current versions of Elixir and Erlang
