### ISSUE TITLE
function put_req_header/3 imported from both Phoenix.ConnTest and Plug.Conn

### ISSUE THREAD

**Issue by Raknison** [phoenixframework/phoenix#1056]
Hi,

i generated a complete new phoenix app and created a resource:

    mix phoenix.gen.json User Users name:string

After i edited the router and migrated the database, i ran the tests.

Now i get the error:

    Generated api app
    ** (CompileError) test/controllers/user_controller_test.exs:9: function put_req_header/3 imported from both Phoenix.ConnTest and Plug.Conn, call is ambiguous
    (elixir) expanding macro: Kernel.|>/2
    test/controllers/user_controller_test.exs:9: Api.UserControllerTest.__ex_unit_setup_1/1
    (elixir) lib/code.ex:307: Code.require_file/2

I didn't made any changes to the generated files.

My dependencies in the mix file are:

    %{"cowboy": {:hex, :cowboy, "1.0.2"},
      "cowlib": {:hex, :cowlib, "1.0.1"},
      "decimal": {:hex, :decimal, "1.1.0"},
      "ecto": {:hex, :ecto, "0.14.3"},
      "fs": {:hex, :fs, "0.9.2"},
      "phoenix": {:hex, :phoenix, "0.14.0"},
      "phoenix_ecto": {:hex, :phoenix_ecto, "0.8.0"},
      "phoenix_html": {:hex, :phoenix_html, "1.4.0"},
      "phoenix_live_reload": {:hex, :phoenix_live_reload, "0.4.3"},
      "plug": {:hex, :plug, "0.13.1"},
      "poison": {:hex, :poison, "1.4.0"},
      "poolboy": {:hex, :poolboy, "1.5.1"},
      "postgrex": {:hex, :postgrex, "0.9.1"},
      "ranch": {:hex, :ranch, "1.1.0"}}

Have i done something wrong?

**Comment by josevalim** [comment]
Please downgrade plug to v0.13.0 until the new Phoenix release is out today. /cc @chrismccord

**Comment by Raknison** [comment]
Thanks, it worked for me!
