### ISSUE TITLE
put_req_header/3 call is ambiguous in tests

### ISSUE THREAD

**Issue by stevedomin** [phoenixframework/phoenix#1057]
This was reported on [the mailing today](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/phoenix-talk/mQWpg96lrZQ).

Should we remove the `defdelegate` for these functions from the `Phoenix.ConnTest` module?

`put_req_header/3` and `delete_req_header/2` are removed from the `Plug.Test` module in the upcoming version of Plug so this shouldn't cause any issues.

**Comment by josevalim** [comment]
Please downgrade Plug to v0.13.0 OR wait for the new Phoenix release coming out in a couple hours. :)

**Comment by stevedomin** [comment]
Thanks @josevalim, will let the guy on the ml know
