### ISSUE TITLE
phoenix.js socket.connect() should accept params

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1059]
Today, you pass params to the socket constructor, but should also support them on the connect function to give parity with the user socket?

socket.connect({user_id: "123"}) => def connect(%{"user_id" => "123")

**Comment by josevalim** [comment]
Yes, :+1:. We should maybe even remove the `new Phoenix.Socket()` one.

**Comment by chrismccord** [comment]
Closed via https://github.com/phoenixframework/phoenix/commit/8ade468017af71d325a5a4b57b98ae2eeae31516

**Comment by jarodburchill** [comment]
these days I get the following message when passing params via `connect()`: 
```
passing params to connect is deprecated. Instead pass :params to the Socket constructor
```
what was the reason for deprecating this functionality?

**Comment by jarodburchill** [comment]
here's the commit where the change was first introduced: https://github.com/phoenixframework/phoenix/commit/fc6e00f422f6e3750e120b36943790bb5a2a0256
