### ISSUE TITLE
Generators with `references` field broken by default with form inputs for association

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1071]
It raises an Ecto association NotLoaded and generates a form input like `<%= text_input f, :user %>` we need to either forgo generating the form input for associations, or handle it another way.

**Comment by josevalim** [comment]
I have fixed this in master today.



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
> I have fixed this in master today.

:heart_eyes_cat:
