### ISSUE TITLE
Add phoenix.gen.secret

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1072]
It will just generate a token. It would be useful, for example, for the heroku deployment guide.

**Comment by gjaldon** [comment]
I'll take this on later today. :) Should be quick and simple since we already have the code for it. Just need to expose it as a mix task

**Comment by josevalim** [comment]
I already have it locally, I am working on the deployment guides. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by gjaldon** [comment]
LOL okay :) I'll look out for out for other stuff to work on then. Btw, feel free to throw stuff my way in Phoenix or Ecto, @josevalim. I'm cultivating a habit of contributing daily :D
