### ISSUE TITLE
Treat app.js as a manifest

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1073]
Today there is a lot of confusion about `app.js`. I think it would be best if we treated it as a manifest. So we will ship with two `.js` files, `app.js` and `socket.js`. The `socket.js` is mostly what we have today and the `app.js` will look like this:

```javascript
// All the files imported here will be joined into
// a single "js/app.js" that is loaded in your layout.

// Import code from dependencies
import "deps/phoenix_html/web/static/js/phoenix_html"

// Import files from current project
import "./socket.js"
```

The goal is to make it clear: everything imported in app.js will be loaded. You don't need to touch your layout.

Thoughts?

**Comment by lancehalvorsen** [comment]
From the chat logs and the mailing list, the confusion is clear. Being more explicit about how assets are handled should certainly help.

**Comment by Gazler** [comment]
I think it perhaps needs to be stated how this works. Maybe a reference to the `brunch-config.js` file would do it? Something like:

    // All the files imported here will be joined into
    // a single "js/app.js" that is loaded in your layout.
    // This can be configured in `brunch-config.js`

**Comment by chrismccord** [comment]
@Gazler is right. We need to be better with the wording.

   // All the files imported here will be joined into
   // a single "js/app.js" that is loaded in your layout.

All files are concatenated into app.js regardless of `import` use, so we need to tweak the wording. Definitely +1 on making this clearer in app.js. The `socket.js` can work and is good to show how to import relative files.
