### ISSUE TITLE
Proposal: no_content controller function

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#1082]
If there is a case for responding with no content (perhaps in a DELETE request for an api call that returns JSON) currently the way to do this is:

```elixir
    conn
    |> put_status(201)
    |> text ""
```

I am proposing the following as an alias for the above:

```elixir
    conn
    |> no_content
```

If anyone else thinks this is worth implementing then assign it to me and I'll implement it.

**Comment by josevalim** [comment]
`send_resp(200, "")` is what you want. Also, we should probably send feature discussions to the phoenix-core mailing list. :)
