### ISSUE TITLE
Better error message when rendering `Ecto.Association.NotLoaded`

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix#1085]
I was working with some views in Phoenix 0.14.0 and I called `render_one(post.comments, "index.son")`

I got an error along the lines of `MyApp.NotLoadedView` module does not exist. I was not sure why it was trying to call that view when I passed in comments and later realize it was because I did not preload the `comments` association.

I think it would be nice if it raised a helpful error message when you passed an `Ecto.Association.NotLoaded` as the model to `render_one` or `render_many`. *I can tackle this on Friday if this is something that you think would be helpful.*

```elixir
post = Repo.one(Post)
render_one(post.comments, "index.json")
# I believe it should raise something like:
# "You tried to render Ecto.Association.NotLoaded. 
# This probably means you forgot to preload the record. Try using Repo.preload"
post = post |> Repo.preload(:comments)
render_one(post.comments, "index.json")
# Works as expected
```

**Comment by chrismccord** [comment]
This is a bad error, but we also can't assume that Ecto is the model. If you pass the explicit view name, the error message would be clear, so I'm not sure what the best strategy is to inflect in this case.

**Comment by paulcsmith** [comment]
I think if we did a function like this it wouldn't cause any issues and would be pretty helpful. It wouldn't change inflection or anything like that.

```elixir
def render_one(%Ecto.Association.NotLoaded{}, _view, _template, _options) do
  raise "You tried to render Ecto.Association.NotLoaded. This probably means you forgot to preload the record. Try using Repo.preload"
end
```

Since it's an Ecto specific thing it shouldn't affect anyone else, but should definitely help those that are using Ecto. For records that aren't unloaded Ecto asociations the `render_one` `render_many` function stays as-is.

**Comment by chrismccord** [comment]
`%Ecto.Association.NotLoaded{}` would not expand at compile time unless you had Ecto as a dependency

**Comment by paulcsmith** [comment]
Why wouldn't you use Ecto though? :P I see what you're saying now. I didn't think of the case where someone removed Ecto as a dependency completely. Maybe something in `phoenix_ecto` would help, but I'm not sure what it would be

**Comment by josevalim** [comment]
We could check for `%{__struct__: Ecto.Association.NotLoaded}`, it is not a compile time dependency but I think it is a hardcoding worth doing in order to provide better error messages.

**Comment by paulcsmith** [comment]
Ok cool. Technical question, why would `def render_one(%Ecto.Association.NotLoaded{}...` not work without Ecto as a dependency, but `def render_one(%{__struct__: Ecto.Association.NotLoaded}...` would still work?

**Comment by josevalim** [comment]
`%Ecto.Association.NotLoaded{}` will try to expand and validate the struct at compile time. The latter is just a regular map with different atoms as key and value.

**Comment by paulcsmith** [comment]
Thanks, Jose! I’ll get started on this and open a PR

**Comment by josevalim** [comment]
@paulcsmith please hold on, @chrismccord and I are considering dropping the inflection because it is causing a lot of confusion.

**Comment by paulcsmith** [comment]
@josevalim Ok will do. 

What are people having a hard time with? Passing in the view every time seems a bit tedious, but maybe it's better if it's confusing to so many people

**Comment by chrismccord** [comment]
Taken care of by killing the inflections with :fire:, sorry @paulcsmith . Explicit view is the way to go to for now. We may revisit this later after 1.0 is out. Thanks!
