### ISSUE TITLE
require.define is not a function when using system.js

### ISSUE THREAD

**Issue by Korbin73** [phoenixframework/phoenix#1089]
I'm getting the following error when including phoenix.js on my page: require.define is not a function. It appears that a module loader is being used in this script. Is this just the standard require.js module loader?

I'm using system.js as my module loader which should work for any amd or commonjs formatted file.

**Comment by jontonsoup** [comment]
As a side note on this issue, I'm using webpack and the default pheonix.js does not work. Brunch has a bunch of issues with some react libraries, so I was forced to switch. 

@Korbin73 you can download non brunch code from the tagged phoenix release.

**Comment by Korbin73** [comment]
Ah. Thanks for the reply. Excuse my ignorance but when you say "tagged phoenix release" are you referring to the .15 tag of the repo?

**Comment by Korbin73** [comment]
Actually, I found this old link: https://github.com/phoenixframework/phoenix/issues/942 I guess I will be forced to add brunch back into my project.

**Comment by jontonsoup** [comment]
Yes I am speaking of the tagged release. You don't need brunch, just a module loader (I am using webpack personally)

**Comment by Korbin73** [comment]
Ahhh. I found it https://github.com/phoenixframework/phoenix/blob/master/web/static/js/phoenix.js. Thanks a lot @jontonsoup. Appreciate the help.

**Comment by jontonsoup** [comment]
That one might not work in case head is head is mismatched.




Try https://github.com/phoenixframework/phoenix/releases/tag/v0.15.0

**Comment by jontonsoup** [comment]
Whoops-- on my phone-- in case your client on branch head is mismatched to v15.
