### ISSUE TITLE
Error when generating new app

### ISSUE THREAD

**Issue by sushantsraikar** [phoenixframework/phoenix#1091]
$ mix phoenix.server
.
.
. 
[error] Could not start node watcher because script "node_modules/brunch/bin/brunch" does not exist. Please make sure it has been installed by running: npm install
-----------------
$ npm install
npm WARN package.json @ No license field.
 
> fsevents@0.3.7 install /Users/sushantraikar/projects/phoenix/rud/node_modules/brunch/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! failed to fetch from registry: https://registry.npmjs.org/ansi-color
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sushantraikar/projects/phoenix/rud/npm-debug.log
---------------------------------------------------------

**Comment by josevalim** [comment]
Please upgrade both npm and node and try again. Locally I have:

```
~/OSS/phoenix[master]$ node -v
v0.12.6
~/OSS/phoenix[master]$ npm -v
2.12.1
```

**Comment by josevalim** [comment]
Actually, I am getting the same error. Something may have been messed up in npm registry.

**Comment by sushantsraikar** [comment]
hey @josevalim,
upgrading doesn't help
$node -v
v0.12.7
$ npm -v
2.11.3

same error.

**Comment by josevalim** [comment]
Yes, it is a bug in NPM: https://github.com/npm/npm/issues/9168

Sorry for the inconvenience.  :(

**Comment by paulmillr** [comment]
Fixed.

**Comment by josevalim** [comment]
Thank you!
