### ISSUE TITLE
Validate  long poller changes

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1092]
@ericmj I am assigning this to you so you can check long poller still works as expected in your app before Phoenix 1.0.

**Comment by ericmj** [comment]
Will check it after I get back from vacation in ~1 week.

**Comment by chrismccord** [comment]
@ericmj when you check on things, also please verify that xdomain support is working as expected with the latest server/client versions

**Comment by ericmj** [comment]
Will do.

**Comment by ericmj** [comment]
I haven't noticed any issues in my local testing, but I have not tested on our production system yet. Closing this. Will open new issues if we find anything when we move to phoenix 1.0.

Thank you both for your work on long polling, we appreciate the support for it a lot!
