### ISSUE TITLE
[Version 0.16.0] WebSocket connection error

### ISSUE THREAD

**Issue by seantanly** [phoenixframework/phoenix#1096]
When upgrading my Phoenix app, I'm having problems connecting to the web sockets. This problem shows up even on fresh installs.

Below is the output for Chrome browser. 
```
WebSocket connection to 'ws://127.0.0.1:4000/phoenix/live_reload/socket/websocket' failed: Error during WebSocket handshake: Unexpected response code: 403
```

Connecting on http://localhost:4000 works, but it fails on anything that's not `localhost`, for example http://127.0.0.1:4000

**Comment by josevalim** [comment]
That's because we are checking the origin, which is a recommended security recommendation. If you change your URL host to "127.0.0.1" in your `config/dev.exs` file, it should work. Btw, is there any particular reason you are using `127.0.0.1` instead of localhost?

**Comment by seantanly** [comment]
Hmm, I don't see the mention of Origin in both dev.exs and prod.exs.

On the other hand, why are we blocking calls from the same origin? 

One use case is the current dev machine is running multiple instances of phoenix apps listening on diff port, and proxied by a front such as nginx that has virtual host name configured to proxy to the right phoenix app according to the hostname. Of course the local /etc/host has the respective entries to cater to this.

**Comment by josevalim** [comment]
> On the other hand, is it necessary to block calls from the same origin?

The origins are not the same. localhost != 127.0.0.1, except in your /etc/hosts that Phoenix does not know about. If you are hosting Phoenix through nginx, you need to set `url: [host: "theproperhost"]` in your config/dev.exs. Otherwise you are running Phoenix on localhost and telling it to accept socket connections from elsewhere, which is not going to be safe.

**Comment by seantanly** [comment]
Right, I was under the impression that Same Origin Policy applies to WebSockets too, but apparently it does not!!! Thus, the need for restriction on the server side to prevent [CrossSiteWebSocketHijacking](https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html)

Thanks for the advice, adding `url: [host: "theproperhost"]` fixes the issue.
