### ISSUE TITLE
Potentially Misleading Error Message

### ISSUE THREAD

**Issue by lancehalvorsen** [phoenixframework/phoenix#1103]
When doing strict TDD on a controller, I get an error message which is technically true, but somewhat misleading.

I wrote this test case before either the route or the controller existed.

```elixir
defmodule HelloPhoenix.MessageControllerTest do
  use HelloPhoenix.ConnCase

  setup do
    conn = conn()
    {:ok, conn: conn}
  end

  test "successfully renders the index template", %{conn: conn} do
    conn = get conn, message_path(conn, :index)
    assert html_response(conn, 200) =~ "Messages!"
  end
end
```

When I ran it, I got this error.

```console
** (CompileError) test/controllers/message_controller_test.exs:10: function message_path/2 undefined
    (stdlib) lists.erl:1336: :lists.foreach/2
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
```

This error message is true, but the real problem is that there is no matching route. People who don't know that the path helpers are defined for them based on routes could easily think that their next step is to implement `message_path/2`.

Is it possible to check for existing routes in this situation and change the error message if there aren't any?

**Comment by josevalim** [comment]
We can't really because the message is coming from the Elixir compiler. :(

**Comment by lancehalvorsen** [comment]
Ah, I see. Thanks for checking @josevalim!
