### ISSUE TITLE
Consider increasing the stacktrace depth by default

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1111]
The default is 8, I believe we could run with a minimum of 20 by default but make it configurable. @fishcakez can you think of any implication of changing this?

**Comment by ericmj** [comment]
The default is always 8 for me. I think the application itself should set this up but we can mention in documentation that they can(should?) do it.

**Comment by fishcakez** [comment]
Well there are implications but they seem insignificant:

There was a thread on erlang questions about `:erlang.get_stacktrace/0`: http://erlang.org/pipermail/erlang-questions/2013-November/075928.html. From the description it would seem the call is `O(backtrace_depth)` and so getting a stacktrace term would be more expensive. However there should not be a normal case where the stacktrace is fetched enough times for this to have a significant effect? If someone did hit a pathological case wouldn't the issue exist without the increased depth?

In Elixir 1.1.0 Logger moves the error reason + stacktrace to the head of the log message. In debug mode would there be extra (useless?) stacktrace entries causing message truncation and missing the last message/state information?

I'm not thrilled about the idea of setting a system flag at a "random" point, it be better if we could add a command line argument to OTP and set a default that way. Likely we'd be talking OTP 19 and whatever Elixir release requires it though. I think @ericmj made a good suggestion.

**Comment by josevalim** [comment]
@fishcakez another option is to do that per environment. We could have a configuration flag which we would set to 20 by default on dev/test. Would it be better? Depending on how we like it, we could add it to Elixir later.

**Comment by fishcakez** [comment]
Sure if you like, make sure there is a way not to set it though.

**Comment by paulcsmith** [comment]
This would be extremely helpful especially in test/dev environment. I set mine to 20 in my test helper because I often would only see lines from other modules that were not from my app. Increasing to 20 allowed me to see where the problem started.

**Comment by raarts** [comment]
Just like to add, I have seen a few stacktraces in production, but I always end up increasing the value. The default of 8 is usually not enough. Also, stacktraces being expensive.. if you get enough of them for this to count, you've got a bigger problem on your hands, and the difference between 8 and 16 depth will not make such of a difference in that case. Just sayin'
