### ISSUE TITLE
Can't start multiple instances of Phoenix when using https

### ISSUE THREAD

**Issue by gjaldon** [phoenixframework/phoenix#1112]
Can we still start-up multiple instances of Phoenix? Just checking because my deployments rely on it and it used to work fine. 

Now, I keep getting a `https://myapp.com:80 port already in use` error. If there was no change to that(I don't remember seeing any), it looks this is caused by enabling `https` in a Phoenix app. Is this the expected behavior? This might be a Plug issue, but wasn't sure and haven't dug deep yet.

**Comment by josevalim** [comment]
@gjaldon how are you configuring your Phoenix application? If you are turning on https, you need to make sure it will run on port 443. Because the port 80 will certainly be taken.

**Comment by josevalim** [comment]
Please post your configs for the environment you are having issues.

**Comment by gjaldon** [comment]
Here's my config for prod:

```elixir
config :phoenixcasts, Phoenixcasts.Endpoint,
  secret_key_base: "secret",
  https: [port: 443,
          otp_app: :my_app,
          keyfile: "ssl/key.pem",
          certfile: "ssl/cert.pem",
          cacertfile: "ssl/cacert.pem"]
```

**Comment by josevalim** [comment]
do you have a stacktrace? can you reproduce the error in a simple project? it was supposed to work. I have no idea why it is trying to serve from port 80.

**Comment by josevalim** [comment]
Also, are you starting multiple instances of Phoenix in the same server?!

**Comment by gjaldon** [comment]
Yes. I have a maximum of 2 instances at once. This happens every time I deploy since I start up another Phoenix app with the updated code and redirect traffic from port 80 to that new instance. Once that's done and another 5 secs has passed, the older Phoenix instance is taken down.

I've no stacktrace. Just this `08:44:17.886 [error] Running MyApp.Endpoint with Cowboy on https://myapp.com:80 failed, port already in use`.

Btw, SSL works fine on app.I just can't start multiple instances. I'll try to reproduce in a simple project.

**Comment by josevalim** [comment]
Ah, i See, thanks for the clarification.

I don't think that was supposed to work. If it worked before, it was by chance. What you can check is if ranch supports configuring the socket options and, if so, how to do that via Cowboy. So you can set things like `reuse_addr`. @fishcakez may have a solution for this too.

**Comment by gjaldon** [comment]
I was able to do multiple deploys for a few weeks using that set-up. It just broke when I introduced SSL. 

I'll looking into configuring socket options in Ranch/Cowboy and `reuse_addr`. Thanks for the tips!

**Comment by gjaldon** [comment]
Btw, upgrading to Phoenix 0.16 gives me the following error instead:

`10:53:05.394 [error] Running Phoenixcasts.Endpoint with Cowboy on https://myapp.com:443 failed, port already in use`

**Comment by fishcakez** [comment]
A subset of socket options are supported in ranch (and all of these can be used with cowboy). `:reuseaddr` is enabled by default in ranch so its on already unless you explicitly turn it off. You can pass a listen socket to ranch (and use a file descriptor for that listen socket). However I think you're starting multiple sockets and forwarding using iptables or similar?

Also how is that error occurring? Given you say its the only error I assume its on startup of the new VM using mix run when the old VM is still running?

**Comment by gjaldon** [comment]
Ahh yes, that's exactly the problem. The earlier error threw me off since it showed port 80 instead of port 443. About when the error is occuring, that's correct. 

I use iptables to redirect port 80 traffic to my app's http port which would either be 8080 or 8081. I'll have to do the same with https by starting it in different ports too and redirect port 443 traffic to either of those other ports.
