### ISSUE TITLE
Allow dependencies to provide templates for generators

### ISSUE THREAD

**Issue by nickgartmann** [phoenixframework/phoenix#1115]
`0.16` added support for custom templates in a `priv/templates/phoenix.gen.*` folder. There are a few libraries that affect the way a controller, view, model, etc need to be structured (in my case [jsonapi](https://github.com/jeregrine/jsonapi)). I propose allowing dependencies to also provide templates in the same folder structure.

By doing this, libraries could include (for example) a `priv/templates/phoenix.gen.json/view.ex` file to override our json views, but wouldn't require end-user intervention.

My suggestion for implementation would be to allow `config/dev.ex` to include

```elixir
# this provides the current default implementation
config :phoenix, Mix.Phoenix,
  paths: [".", :phoenix]
```
so users can add deps to the resolution chain by adding

```elixir
# this uses jsonapi views
config :phoenix, Mix.Phoenix,
   paths: [".", :jsonapi, :phoenix]
```

I can PR in the functionality once we decide on a path forward.

**Comment by josevalim** [comment]
Thanks for suggestion!

My take: I am a strong :-1: here. We often prefer explicitness and I think we have a perfect solution here: the templates are always in your application, no need to go chase dependencies to find what they will generate. jsonapi could provide a generator that simply copies everything into your application template directory.

 Thoughts?

**Comment by jeregrine** [comment]
@josevalim so you want JSONAPI to generate a template, and then user calls the gen call again?

**Comment by jeregrine** [comment]
so 
```
mix jsonapi.gen.template
mix phoenix.gen.jsonapi ...
```

**Comment by josevalim** [comment]
No!

```elixir
mix jsonapi.gen.templates
mix phoenix.gen.json
```

Or just provide your own generator instead of changing Phoenix ones.

**Comment by chrismccord** [comment]
I'm going to agree with José on this one. A mix task to run on setup is a nice solution, since it can be doc'd easily in the readme and is a one-time thing. "Add :jsonapi to your mix deps, then run ...`"

**Comment by jeregrine** [comment]
@josevalim the only trick is then we need to emulate about 70% of the generator and keep it in sync with phoenix like this https://github.com/jeregrine/jsonapi/pull/7

**Comment by nickgartmann** [comment]
@jeregrine we'll have to do that anyhow as the framework interface changes. Generator is going to need parity with options provided by Phoenix no matter what (unless they are trivial replacements). If we copy the files over with a `mix jsonapi.gen.templates` and ask on each one if they want to overwrite it should be fine. My hope was to be able to have a few layers stacked on top of each other, in which I can just do `{:nickgartmann_api_templates, "~> 1.0"}` in mix.exs and only have to override the files i want to interact with, but with one layer of templates, copying is probably a fine solution.

**Comment by jeregrine** [comment]
Not a super fan of this decision because it makes third party library generators kind of a pain to maintain/write. Will step defer to your judgement though.

**Comment by josevalim** [comment]
@jeregrine I am not sure which option you are talking about here. We have two afaik:

1. Have your own generators

2. Rely on phoenix templates

The first one is more future proof and the second can break at any occasion. It is only recommended really at the application level. What has been proposed in this issue won't help fix 2) (it may make worse even).

I am not saying the problem does not exist. I am just trying to understand what problem we are discussing and how the proposal described here is meant to fix it.

**Comment by jeregrine** [comment]
@josevalim yea I get it now. Just kinda sucks there is no way to I guess build off the phoenix generators in a way that 1) doesn't duplicate 100% of the phoenix templates and mix tasks just to add a few files/lines. 2) doesn't cause the users to have multiple steps just to generate some code.

**Comment by chrismccord** [comment]
> Just kinda sucks there is no way to I guess build off the phoenix generators in a way that 1) doesn't duplicate 100% of the phoenix templates and mix tasks just to add a few files/lines. 2) doesn't cause the users to have multiple steps just to generate some code.

For the generators, I think this is okay because custom generators are going to be much less common than other extension points like transports, pubsub adapters, etc. So i think the tradeoffs are worth it because it lets us sidestep the opaque view into generators. Ie, you have no idea what `mix phoenix.gen.json` is going to do unless you go dig through your deps' docs. You also get into cases where multiple deps could conflict, so I think the current approach is a good one.
