### ISSUE TITLE
Add back web/static/vendor to generated projects

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1117]
Not sure what happened, but it's not included on new projects in 0.16

**Comment by Gazler** [comment]
Looks like it was removed at https://github.com/phoenixframework/phoenix/commit/9107dd08ef0324dd80a42152c0a36e5bfa9cc2ce#diff-19b1aa473837241cbc876d3ad71bbb75L247

**Comment by stevedomin** [comment]
@chrismccord I'm happy to tackle that one if you haven't started already

**Comment by chrismccord** [comment]
@stevedomin PR please!
