### ISSUE TITLE
option to bind to a specific network interface or IP in config

### ISSUE THREAD

**Issue by jschoch** [phoenixframework/phoenix#1122]
server has eth0, eth1.  Need an option to specify which interface or IP to listen to.

Ranch has this: https://github.com/ninenines/ranch/blob/02ff6533bbbc5dae95959c4979765d532d9e0af6/manual/ranch_tcp.md

**Comment by josevalim** [comment]
I believe the options you pass in `https` and `http` are all forwarded to cowboy.

    http: [ip: {0, 0, 0, 0}]

Can you please check?

**Comment by jschoch** [comment]
yup, that seems to work great, thanks!

**Comment by alex88** [comment]
Is this still valid?

I'm trying with my prod.esx

```
config :myproject, Myproject.Endpoint,
  http: [port: {:system, "PORT"}, ip: {0, 0, 0, 0}],
  url: [host: "mckinsey-ils.visup.me", port: {:system, "PORT"}],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: {:system, "SECRET_KEY"}
```

but running:

```
DATABASE_URL=postgresql://localhost/test PORT=4000 MIX_ENV=prod mix phoenix.server
```

shows

```
21:16:36.038 [info] Running Myproject.Endpoint with Cowboy using http://localhost:4000
```

so it still binds on localhost

**Comment by josevalim** [comment]
@alex88 the reporting is incorrect. I believe we have fixed it although I am not 100% if we have released it. The option should still work though.

**Comment by jfreeze** [comment]
On 1.5.3 with plug_cowboy 2.3.0, any http: param that specifies an :ip param returns :badarg when trying to start the server.

    ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, ElixirConfWeb.Endpoint.HTTP}
        ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup
            ** (EXIT) :badarg

**Comment by chrismccord** [comment]
Can you try: `http: [port: 4010, ip: {127, 0, 0, 1}],` ? Note that you are providing 127.0.0.0, which will fail to bind

**Comment by jfreeze** [comment]
Ah, yeah. Same error.

jimfreeze@Jims-MBP elixir_conf % ./_build/prod/rel/elixir_conf/bin/elixir_conf start
21:09:40.714 [info] Application elixir_conf exited: ElixirConf.Application.start(:normal, []) returned an error: shutdown: failed to start child: ElixirConfWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, ElixirConfWeb.Endpoint.HTTP}
        ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup
            ** (EXIT) :badarg
{"Kernel pid terminated",application_controller,"{application_start_failure,elixir_conf,{{shutdown,{failed_to_start_child,'Elixir.ElixirConfWeb.Endpoint',{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.ElixirConfWeb.Endpoint.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,badarg}}}}}},{'Elixir.ElixirConf.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,elixir_conf,{{shutdown,{failed_to_start_child,'Elixir.ElixirConfWeb.Endpoint',{shutdown,{failed_to_start_child,{ranch_listene

**Comment by johannes-mueller** [comment]
Same problem here. As soon as I put in `ip: {127, 0, 0, 1}` the server fails to start with the error described by @jfreeze.

Any explanations or solutions for that?

**Comment by jfreeze** [comment]
Make sure you don't need to comment out IPv6 line.

# transport_options: [socket_opts: [:inet6]]


Dr. Jim Freeze, Ph.D.
ElixirConf®
ElixirConf.com
ElixirConf.eu
(m) 512 949 9683

**Comment by johannes-mueller** [comment]
Ah yes, thanks. Alternatively you could bind to `ip: {0, 0, 0, 0, 0, 0, 0, 1}`

**Comment by jfreeze** [comment]
I use a reverse proxy and all of my local IP addresses are IPv4, so I can't
see needing IPv6 for some time.


Dr. Jim Freeze, Ph.D.
ElixirConf®
ElixirConf.com
ElixirConf.eu
(m) 512 949 9683
