### ISSUE TITLE
phoenix.gen.json generator handles output of fields differently from phoenix.gen.html

### ISSUE THREAD

**Issue by dmarkow** [phoenixframework/phoenix#1125]
When you run `mix phoenix.gen.html User users name:string`, the index/show templates automatically include the `name` field.

However, when you do the same using `phoenix.gen.json`, the map in the `web/views/user_view.ex` file only returns the `id` field:

```elixir
def render("user.json", %{user: user}) do
  %{id: user.id}
end
```

Not sure if this is intentional (I tried searching previous issues and couldn't find anything relevant), but wanted to check before spending time on a PR.

**Comment by josevalim** [comment]
@dmarkow Yes, let's make them consistent. :)
