### ISSUE TITLE
Incorrect content length for 204 json response

### ISSUE THREAD

**Issue by stephenmuss** [phoenixframework/phoenix#1131]
There seems to be an issue with the content-length response header when sending a JSON no content response.

```elixir
def index(conn, _params) do
  conn |> put_status(:no_content) |> json(nil)
end
```

```sh
curl -i localhost:4000

HTTP/1.1 204 No Content
connection: keep-alive
server: Cowboy
date: Sat, 15 Aug 2015 22:54:23 GMT
content-length: 4
content-type: application/json; charset=utf-8
cache-control: max-age=0, private, must-revalidate
x-request-id: 7442ueh08asj4u7eda9ff8t2sibc78u3
```

You can see the content-length header is 4 where it should be 0.

If I change the action to the following the content-length header is the correct 0

```elixir
def index(conn, _params) do
  conn |> put_status(:no_content) |> text("")
end
```

The following also seems to work

```elixir
def index(conn, _params) do
  conn
  |> put_status(:no_content)
  |> put_resp_header("content-type", "application/json")
  |> text("")
end
```

**Comment by chrismccord** [comment]
So this is not a bug. You are encoding `nil` which is being encoded by Poison as `"null"` 

    iex(2)> Poison.encode!(nil)
    "null"

The correct solution here would be to use:

```elixir
def index(conn, _params) do
  conn
  |> put_status(:no_content)
  |> put_resp_header("content-type", "application/json")
  |> send_resp("")
end
```

Hope that helps!

**Comment by stephenmuss** [comment]
In that case @chrismccord  I would suggest there is still a bug in the implementation.

```elixir
conn |> put_status(:no_content) |> json(nil)
```

By using `put_status(:no_content)` Phoenix appears to exclude any content in the response. If `Poison.encode!(nil)` produces the result `null` which is indeed 4 byte content-length then the content should be included in the response to avoid confusion.

**Comment by chrismccord** [comment]
All `json/2` does is;

    send_resp(conn, conn.status || 200, "application/json", encoder.encode_to_iodata!(data))

In this case, we are using the status if it is already set. So I don't think there's a bug here. Plug is sending no body because you set `no_content`. There's no real fix since it doesn't make a valid response in either case. The solution would be to not set 402 while deviling a payload.

**Comment by josevalim** [comment]
Yes, the bug is in your application in setting a status code that does not really apply. We can't validate the status code for you. :) I am not even sure if you should set  a content type for no content.

**Comment by stephenmuss** [comment]
I'm quite happy to concede that I may have misused the API.

In my case I did in fact want an empty response with a 204 status. I perhaps foolishly assumed that `json(conn, nil)` would simply result in the response content being empty (it does).

But there does seem to be an unexpected side-effect here. I'm willing to accept that I wasn't using `put_status` and `json` correctly. But if the `put_status(conn, :no_content)` results in the content being stripped out, shouldn't the `Content-Length` header also be set to 0? Otherwise, perhaps `put_status(conn, :no_content)` shouldn't result in content being automatically removed and the onus should be on the developer to ensure the response content is empty.

**Comment by josevalim** [comment]
> But if the put_status(conn, :no_content) results in the content being stripped out, shouldn't the Content-Length header also be set to 0? 

We don't remove contents when you call `put_status(conn, :no_content)` at all. Why are you thinking otherwise?

**Comment by josevalim** [comment]
Sorry, to be clear, are you seeing anything in your code that says otherwise? The last sentence was not very well phrased. :)

**Comment by stephenmuss** [comment]
The reason I was asking is because I basically created a new Phoenix project with just the following controller

```elixir
defmodule Blah.PageController do
  use Blah.Web, :controller

  def index(conn, _params) do
    conn |> put_status(:no_content) |> json(nil)
  end
end
```

If I use curl on this endpoint I get the following response
```
HTTP/1.1 204 No Content
connection: keep-alive
server: Cowboy
date: Sun, 16 Aug 2015 08:36:26 GMT
content-length: 4
content-type: application/json; charset=utf-8
cache-control: max-age=0, private, must-revalidate
x-request-id: q8r6rjq8qci3uodoksjm9tlmatafevh8

```

You can see in this response the response body is empty but the content-length is 4. Chris explained above that this is because the string `null` is where the content length is originating.

So it seems to me that somewhere `null` has been removed from the response. Perhaps this happening in Cowboy or some such.

I'm thankful for the suggestions and pointing me to the correct way of doing things. I just wanted to point this out.

**Comment by josevalim** [comment]
@stephenmuss oh, thanks for pointing that out. Yes, so something somewhere is definitely remove the content... it could even be curl but my bet is on cowboy. I will try to track that down and do a bug report.

Thanks @stephenmuss! I learned something here! :D

**Comment by stephenmuss** [comment]
@josevalim, yes I suspected after you said that you did not strip out any content from the response body that it may lay with Cowboy. I don't think it's curl as I also saw the same result in Httpie and Postman.

**Comment by iamvery** [comment]
Sorry to unearth and old issue, but I wanted to mention that it appears `send_resp` has an arity of 3 now. So Chris' above suggestion to pipe `|> send_resp("")` wouldn't work. You need to `|> send_resp(204, "")`. I'm not sure if this is a change or a mistake, but hopefully it helps someone else out (or I'm completely wrong where in you correct me and I update this response :laughing:)

**Comment by halkuon** [comment]
Was this ever solved?
My code as follows:
```  
defp render_response(conn, %{status: :no_content}) do
    conn
    |> put_status(:no_content)
    |> put_resp_header("content-type", "application/json")
    |> send_resp(204, "")
end```

still shows in the header as content-length: 2

**Comment by arvidkahl** [comment]
I would like to make a note here that this is ESSENTIAL for requests sent from an iOS device to a(ny) API. Any HTTP request sent from an iOS device that returns both a `204` status and a non-empty response (indicated by a `content-length` header with any value but 0) will cause the connection to run into a timeout on the device.

**Comment by bluebrown** [comment]
Is there no option to only set the status and nobody at all? An http response doesnt need to have a body. It should be possible to send headers with content-lenght 0 to the client. Using this empty string feels cumbersome.

The below doesnt work, while it should IMO.

```
 conn
    |> put_status(204)
    |> send_resp()
```

It fails with

```
cannot send a response that was not set
```
