### ISSUE TITLE
Consider option to opt-out of format param

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1132]
We have had our first report of the `format` param clashing with a json post body. We could either namespace this param for less likely clashing, or (my preference), have an accept's plug option to opt-out /set the format param. Something like

```elixir
plug :accepts, formats: ~w(html), param: "format"
# or 
plug :accepts, formats: ~w(html), param: :none
```

We could still have the plug default to accepting a list of formats as it does today for backwards compat. Thoughts?

**Comment by chrismccord** [comment]
The other option is for folks to use the `conn.body_params`, but this seems like something that will bite people from time to time

**Comment by chrismccord** [comment]
To counter my previous comment, `conn.body_params` is not enough because the accepts plug is 406'ing the users request based on their `format` value.

**Comment by josevalim** [comment]
We use `conn.params["format"]` in a bunch of places so we can't just make it configurable. I think we would need two steps:

1. Store the format in `conn.private.phoenix_format`. We would likely need `put_format/2`.
2. Make it configurable.

It could also help if we read the value only from conn.query_params and stop reading it from conn.params. We should do this before 1.0 anyway.

**Comment by gjaldon** [comment]
@chrismccord I'd like to take this issue on, it's available. :)

**Comment by josevalim** [comment]
We still haven't decided how this should be solved. What is your take on
the issues raised here? Which solution would you implement? Any thoughts?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by gjaldon** [comment]
I think making it configurable would be great. To make the parameter name configurable, we could do the following:

1. Replace all the `conn.params["format"]` or any other ways we access `params["format"]` with `get_format/1`
2. Read the value only from `conn.query_params` and store it in `conn.private.phoenix_format` then add a `put_format/2` as you suggested
3. Make param name configure and explicitly set it like `plug :accepts, formats: ~w(html), param: "_format"` in `MyApp.Endpoint`. To make it less likely for clashes to happen when passing query params for format, we could use `"_format"` instead which would be consistent with `"_csrf_token"` in Plug.

These are mostly what you guys have suggested above and a bit of my own ideas. What do you guys think?

**Comment by josevalim** [comment]
I am :+1: to making it `_format` and :-1: on a configuration option (still).

I am also not sure we should read only from `query_params`. Can anyone think of the pros and cons here? The only scenario where it would be beneficial is error handling. You can't really configure the _format in the body if we fail parsing the body.... so it typically seems best to push to query_params. It is the same reason I don't want to make it a configuration option.

**Comment by chrismccord** [comment]
@gjaldon Thanks, but I will be taking this one on.

**Comment by josevalim** [comment]
So to sum up everyone's points, I think we should: 

1. Replace all the `conn.params["format"]` or any other ways we access `params["format"]` with `get_format/1`
2. Read the value only from `conn.query_params` and store it in `conn.private.phoenix_format` via `put_format/2`
3. Change the default from `"format"` to `"_format"`

All on board? Thanks @gjaldon.

**Comment by gjaldon** [comment]
:+1: happy to contribute!
