### ISSUE TITLE
Phoenix.Controller.redirect/2 accepts protocol-relative URLs as local

### ISSUE THREAD

**Issue by antipax** [phoenixframework/phoenix#1133]
According to the [docs](http://hexdocs.pm/phoenix/Phoenix.Controller.html#redirect/2), `Phoenix.Controller.redirect to: str` should only accept paths, but this code:

```elixir
defmodule MyApp.PageController do
  use MyApp.Web, :controller

  def index(conn, _params) do
    conn
    |> redirect to: "//google.com"
  end
end
```

will result in a redirect to google.com.

**Comment by chrismccord** [comment]
Fixed! Thanks for reporting!
