### ISSUE TITLE
Dynamically digest, compress and add file to static manifest

### ISSUE THREAD

**Issue by gjaldon** [phoenixframework/phoenix#1138]
Context:
In my Phoenix app, I currently upload files to the file system and store them in priv/static so I can serve them via Plug.Static. My prob now is in prod, when I upload files, I have to manually run `mix phoenix.digest` and then the server needs to restart so the cache_static_manifest will be loaded into Phoenix.Config.cache

Would be great to be able to dynamically digest, compress and add a file to the static manifest.

**Comment by josevalim** [comment]
@gjaldon quick questin: do you really need to restart? I mean.. you should still be able to generate URLs and serve it... it just won't be cached, right?

**Comment by gjaldon** [comment]
@josevalim I can generate the path to the asset but I get a `404 (Not Found)` until I restart the app. Haven't figured out why yet. I'm using the default config for prod where `cache_static_manifest: "priv/static/manifest.json"`.

**Comment by josevalim** [comment]
Which path is generated? We should still support accessing the files locally. The caching is all done when generating the URL. Plug.Static does not cache.

**Comment by gjaldon** [comment]
I see the problem now. `static_path/1` generates `{:nocache, path}` because the file is not found. When this https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/adapter.ex#L190 runs, it looks for file in the `_build` directory. I just store the uploaded file into `priv/static` of my app's root. Should I copy the files straight to the `_build` directory instead?

Btw, I'll submit a PR for the digesting and compressing of a single file.

**Comment by josevalim** [comment]
Yes, the build one is the one that matters. Hold on a PR. We still need to figure out how it will work. It also won't work across multiple instances either.

**Comment by chrismccord** [comment]
I thought we already handled this with a function to expire the cache forcefully?

**Comment by josevalim** [comment]
Closing this then.

**Comment by nguyenvinhlinh** [comment]
I know this thread has been close, however, even I did remove `cache_static_manifest` in prod.exs, my uploaded file which stays at `/priv/static/images/' still cannot loaded without restart server.  Is there anyway to work without using extra plug.

**Comment by josevalim** [comment]
can you update your Phoenix version? because i think this has changed on phoenix 1.1.2 or 1.1.3. We should always be able to generate the url (although it won't have the versioned query string).

**Comment by nguyenvinhlinh** [comment]
I does not work, I dont understand. 
Here is my dependency: 
```elixir
 defp deps do
    [{:phoenix, "~> 1.1.3"},
     {:phoenix_ecto, "~> 1.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:ibrowse, github: "cmullaparthi/ibrowse", tag: "v4.1.2"},
     {:httpotion, "~> 2.1.0"},
     {:base64url, "~> 0.0.1"}
    ]
  end
```

And here is the prod.exs's important config:
```elixir
config :image_quick_share, ImageQuickShare.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "example.com", port: 80]

# Do not print debug messages in production
config :logger, level: :info

```

**Comment by josevalim** [comment]
Which error are you seeing?

**Comment by josevalim** [comment]
I mean, you can still access the image directly with `static_path("/images/uploads/foo.png")`. What are you giving as input and what are you expecting as output?

**Comment by nguyenvinhlinh** [comment]
In my template, I wrote
```elixir
<% src = static_path(@conn, "/files/#{@conn.assigns[:id]}") %>
<%= src %>
<img src="<%= src %>" />
```

They display the path correctly, static_path did it well, no trouble with the static_path. At the console log, I read the console log. I said that:
```text
16:50:57.628 request_id=ttb2nda0p9o9pcior35tasm28guej52l [info] GET /files/1453913457497231333Screenshot_from_2016-01-08_22-49-35.png
16:50:57.643 request_id=ttb2nda0p9o9pcior35tasm28guej52l [info] Sent 404 in 15ms
```

**Comment by josevalim** [comment]
The answer is above. You need to write the file to `_build/prod/lib/your_app/priv/static`. The ideal is actually to put them in a separate directory and have a symlink from priv/static.

**Comment by nguyenvinhlinh** [comment]
oh that good. Thank you :D

**Comment by josevalim** [comment]
Glad to help! let me know how it goes!

**Comment by nguyenvinhlinh** [comment]
Okay, I remembered. I have worked for more than 10 hours at the company. I have to go to home now. I will test tomorrow, I mean today. right now it's 00:05 am

**Comment by nguyenvinhlinh** [comment]
I have finished implemented the issue. in the root of project, I make a new directory name `upload_files`. 

On the other hand, in the `/priv/static/` I make a symlink to the `upload_files`, meanwhile, in the `_build/prod/---/static/` I also make a symlink to the upload file. 

It works well, you can test here with image at `http://128.199.95.172:4000/image/new`

**Comment by josevalim** [comment]
Glad to hear it worked!

**Comment by TimPelgrim** [comment]
Is it normal that the symlink from `_build/prod/---/static/` breaks when running `mix phoenix.digest` in the production environment. I keep having to remake it when deploying my app.

**Comment by TimPelgrim** [comment]
The symlink is gone, the directory `_build/prod/---/static/` first contains a symlink to `../../../../priv` (priv in the root folder) but after running `mix phoenix.digest` it is a normal directory. I currently use the `priv/static` for uploads but I am starting to doubt this is the way to go in production, perhaps a custom route would be better for user uploads. Any pointers would be greatly appreciated.
