### ISSUE TITLE
Generated controller tests use atom keys rather than string keys

### ISSUE THREAD

**Issue by neoeno** [phoenixframework/phoenix#1139]
Summary: phoenix generators generate controller tests that pass atom-keyed maps as controller params, but in production controllers will receive string-keyed maps. This can be misleading if you're new to the framework.

---

Currently `phoenix.gen.html` generates tests more or less like this:

```elixir
defmodule Project.UserControllerTest do
  use Project.ConnCase

  alias Project.User
  @valid_attrs %{name: "some content", age: 42}
  @invalid_attrs %{}

# [...]

  test "creates resource and redirects when data is valid", %{conn: conn} do
    conn = post conn, user_path(conn, :create), user: @valid_attrs
    assert redirected_to(conn) == user_path(conn, :index)
    assert Repo.get_by(User, @valid_attrs)
  end
```

As you can see, `@valid_attrs` is generated using atom keys. This works well enough, but is a little misleading as the controller will actually receive string keys most of the time (ref http://hexdocs.pm/plug/Plug.Conn.html#t:params/0).

Since generators are often used by the newly initiated (read: me) as canonical example code, it would be nice to have them reflect the reality — controllers take string keys.

I wrote a PR to change this, but it turns out that the form of the generated tests relies on `@valid_attrs` being atoms (`Repo.get_by/2` expects atom keys). Since it's named `@valid_attrs`, not `@valid_params`, this makes sense.

So if we were to pass string keys to the controller, we could generate a `@valid_params` that is the same as `@valid_attrs` but with string keys, or convert one to the other — or something else?

What do you think?

I'm happy to work on this — but it'd be good to get a steer on what everyone thinks is the best solution before I dive in.

**Comment by josevalim** [comment]
I completely agree. Please send a PR indeed. :) We can convert the existing parameters.

**Comment by neoeno** [comment]
For anyone who sees this: 

Discovered today that controllers always receive string keys, even if they're passed atom keys by the tests. Which makes this less of an inconvenience than I thought.
