### ISSUE TITLE
Phoenix Live Reload websocket 404

### ISSUE THREAD

**Issue by mpahrens** [phoenixframework/phoenix#1148]
In my phoenix app:
www.github.com/tufts-lpc/blockytalky_elixir

After updating to 0.16 I got an error in Google Chrome, but only on the reload websocket, not on the other websockets I set up to use for my application.

After updating to 0.17 following the instructions in the news blog, I still get a similar error in my Chrome Developer Console:
`WebSocket connection to 'ws://localhost:4000/phoenix/live_reload/socket/websocket?vsn=1.0.0' failed: Error during WebSocket handshake: Unexpected response code: 404`

I don't know if this is similar to #1096 but my url host is set correctly (localhost) and my other websockets still work correctly. 

You can look at my develop branch to see what I am building :) Thanks in advanced!

**Comment by chrismccord** [comment]
You didn't follow all the upgrade instructions :)

https://github.com/tufts-LPC/blockytalky_elixir/blob/master/blockytalky/lib/blockytalky/endpoint.ex#L17-L20

You are missing the live reload socket definition, you need:

```elixir
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end
```

**Comment by mpahrens** [comment]
Ah, I did my 0.14 and 0.15 upgrades at the same time and so I must have missed that one. Thanks a bunch!
