### ISSUE TITLE
Error trying to run freshly generated application

### ISSUE THREAD

**Issue by locks** [phoenixframework/phoenix#1155]
Hi, I'm looking to try out Phoenix for a new API I'm building, but trying to run `mix phoenix.server` on a freshly generated application gives me the following error:

```
$ mix phoenix.server
Compiled lib/fzc.ex
Compiled web/web.ex
Compiled lib/fzc/repo.ex

== Compilation error on file lib/fzc/endpoint.ex ==
** (CompileError) lib/fzc/endpoint.ex:1: function router/2 undefined
    (stdlib) lists.erl:1336: :lists.foreach/2
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
```

## Reproduction steps
* `$ mix phoenix.new fzc`
* `$ cd fzc`
* `$ mix phoenix.server`

**Comment by chrismccord** [comment]
It looks like you generated your application with an older version of phoenix than what `mix deps.get` pulled down. We removed `plug :router, MyApp.Router` in lib/my_app/endpoint.ex` in favor of `plug MyApp.Router`. The easiest solution is the following:

Grab the latest phoenix:

    mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.17.0/phoenix_new-0.17.0.ez

Now generate your app:

    mix phoenix.new fzc

If you want to upgrade your existing code (if you wrote features), we have upgrade guides in the changelog that will take you step by step. Feel free to chime in here if you have issues, or find me on irc and we'll get things sorted out.

**Comment by josevalim** [comment]
@chrismccord I think new applications must be generated with `~> x.y.z` instead of `~> x.y`. What do you think?

**Comment by chrismccord** [comment]
> I think new applications must be generated with ~> x.y.z instead of ~> x.y. What do you think?

:+1:

**Comment by locks** [comment]
Thank you @chrismccord, that did indeed fix my problem!
