### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by cgarciae** [phoenixframework/phoenix#1157]
I find that dependency injection solves great problems

1. Solves the problem of locating a service
2. Solves the problem of locating the <b>correct</b> service given a context (production, testing, etc)
3. Solves the problem of constructing a service that depends on other services

Is there any kind of dependency injection in Phoenix? If not how is testing done? How are e.g. queries to a database mocked?

I am investigation different technologies for a new project and testing is a main concern, maybe with Elixir's dynamic and functional nature DI is not necessary (still thinking about this) but a substitute mechanism must achieve the same goals.

Thanks!

**Comment by chrismccord** [comment]
Please direct general questions and discussion to the mailing list https://groups.google.com/forum/#!pendingmsg/phoenix-talk

For examples of dependency injection when testing, see the options we pass in to the pubsub supervisors and servers, such as the long poll timeout window. Folks on the mailing list might have more examples. Thanks

**Comment by cgarciae** [comment]
Thanks! Will do.
