### ISSUE TITLE
Use of generator for JSON resource results in syntax errors, forcing project compilation to fail.

### ISSUE THREAD

**Issue by ybur-yug** [phoenixframework/phoenix#1159]
I have made an example repository [here](https://github.com/ybur-yug/generator_bug_example/tree/ed324dd304da0093195e8766625ba990c8a46b5c). The first commit demonstrates the bug, the second fixes it. (link is to first commit)

The exact process for replication is as follows:

```bash
$ mix phoenix.new example_bug
$ cd example_bug
$ mix phoenix.gen.json Post posts title:string content:string
# a bunch of output comes from compilation, but then
$ mix compile
Compiled web/views/changeset_view.ex

== Compilation error on file web/views/post_view.ex ==
** (SyntaxError) web/views/post_view.ex:14: syntax error before: title
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

If we look at the file causing this (`post_view.ex:14`):

```elixir
defmodule ExampleBug.PostView do
  use ExampleBug.Web, :view

  def render("index.json", %{posts: posts}) do
    %{data: render_many(posts, ExampleBug.PostView, "post.json")}
  end

  def render("show.json", %{post: post}) do
    %{data: render_one(post, ExampleBug.PostView, "post.json")}
  end

  def render("post.json", %{post: post}) do
    %{id: post.id
      title: post.title
      content: post.content}
  end
end
```

The comma is missing on the 5th line up from the bottom in `render/2`.

I looked up the source for the generators and it appears it probably happens somewhere around [here](https://github.com/phoenixframework/phoenix/blob/376f6faeb5576cd76b3a4e86b9b2cd75d4b1c3f3/lib/mix/tasks/phoenix.gen.json.ex#L75).

I can gladly open up a PR with a fix and work on it locally, or if its something trivial you could knock out in a minute let me know if thats preferred.

Cheers

**Comment by josevalim** [comment]
This is fixed in master I believe.

**Comment by josevalim** [comment]
Just double checked, it is. :) Thanks for the report.
