### ISSUE TITLE
Initial install `brunch build` command suggestion

### ISSUE THREAD

**Issue by austinpray** [phoenixframework/phoenix#1160]
Hey guys!

I noticed the command you are using to run brunch.

![image](https://cloud.githubusercontent.com/assets/2192970/9530695/0dafa476-4cc7-11e5-982a-7691e84dc895.png)

This works, but it requires knowledge of the brunch build tool's source code. I recommend the following:

```js
npm install && $(npm bin)/brunch build
```

alternatively in package.json you could add:

```json
{
 "scripts": {
    "build": "brunch build"
  }
}
```

and then the docs look like

```js
npm install && npm run build
```

Technically this is the way npm intends you to reference binaries. Nothing earth-shatteringly important here but wanted to make the suggestion anyway.

¯\_(ツ)_/¯

**Comment by josevalim** [comment]
I would keep it like this because it would be a pain to adopt your solution in a way that works on all OS. :( Although I agree  you are correct. Thanks for opening the issue! :heart:

**Comment by chrismccord** [comment]
If we can verify that npm run works on windows, it could be something to consider, but I don't have the means to test that at the moment. Thanks for the suggestion, but we'll have to wait on this one.

**Comment by austinpray** [comment]
What about the second way? The package.json route works everywhere AFAIK.

**Comment by chrismccord** [comment]
> just saw your comment come through @chrismccord. I'll see if I can test it on windows and such.

thanks. Let us know what you find
