### ISSUE TITLE
phoenix.server does not always detect port in use

### ISSUE THREAD

**Issue by smathieu** [phoenixframework/phoenix#1166]
I ran in the following issue while going through the up and running tutorial. My computer had something running on port 4000.

```
➜ hello_phoenix  lsof -i :4000
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google     1542 simon   83u  IPv4 0xc131de7a852eaff9      0t0  TCP localhost:63093->localhost:terabase (ESTABLISHED)
beam.smp  13019 simon   34u  IPv4 0xc131de7a852eee59      0t0  TCP *:terabase (LISTEN)
beam.smp  13019 simon   37u  IPv4 0xc131de7a852eb8c9      0t0  TCP localhost:terabase->localhost:63093 (ESTABLISHED)
```

When I run the phoenix server:

```
➜ hello_phoenix  mix phoenix.server
[info] Running HelloPhoenix.Endpoint with Cowboy on http://localhost:4000
29 Aug 12:28:12 - info: compiled 5 files into 2 files, copied 3 in 1678ms
```

however, this never returns:

```
➜ hello_phoenix  curl localhost:4000
```

I would have expected the server to refuse to start since another process is already listening on that port. 

I'm running OS X 14.5.0, elixir 1.0.5 and phoenix 1.0.0.

**Comment by josevalim** [comment]
Actually, it is not so simple. TCP acceptors usually use the SO_REUSEADDR option, so if you terminate a process quickly without closing the socket, a new process can still bind to that port depending on the socket state.

However, setting SO_REUSEADDR may cause other side-effects, and not emit EADDRINUSE in some situations. This article has a long explanation about this: http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t. Unless I am missing something, there isn't much we can do to fix this.

**Comment by smathieu** [comment]
Ok, it looks like it's a weird edge case on my system. I also can't detect that the socket is open programatically. Thanks to the Phoenix and Elixir team for being really responsive on this.
