### ISSUE TITLE
"db" directory is not created when generating a new phoenix app using --database sqlite

### ISSUE THREAD

**Issue by rbenaley** [phoenixframework/phoenix#1167]
When I created a new app using "mix phoenix.new myapp --database sqlite" then I executed "cd myapp && mix ecto.create" the task has finished with the following error:

** (Mix) The database for Myapp.Repo couldn't be created, reason given: {:cantopen, 'unable to open database file'}.

After inspecting the end of the file "myapp/config/dev.exs" I can see that the database adapter configuration is correct:

#Configure your database
config :myapp, Myapp.Repo,
  adapter: Sqlite.Ecto,
  database: "db/myapp_dev.sqlite",
  pool_size: 10

But the "db" directory does not exist in the application directory.

The workaround is to create the "db" directory prior executing "mix ecto.create", it would be desirable to fix that issue.

Affected and used version: 1.0.0

**Comment by josevalim** [comment]
Please report this to sqlite_ecto: https://github.com/jazzyb/sqlite_ecto. It is their responsibility to ensure the directory exists in storage_up. /cc @jazzyb

**Comment by josevalim** [comment]
And thank you for reporting a bug in the first place!

**Comment by rbenaley** [comment]
Reported to sqlite_ecto, ref: https://github.com/jazzyb/sqlite_ecto/issues/36

**Comment by rbenaley** [comment]
The issue has been fixed by sqlite_ecto 1.0.1.

I have validated it via "mix phoenix.new myapp --database sqlite && cd myapp && mix ecto.create"

**Comment by josevalim** [comment]
yay!
