### ISSUE TITLE
Setting custom primary key is too complicated. 

### ISSUE THREAD

**Issue by iguberman** [phoenixframework/phoenix#1175]
This is really a feature request/suggestion and not a bug.   Feel free to just close it if you disagree with my point.  :)  I'm very new to Phoenix/Elixir.  

Setting custom primary_key that's not id:integer is a bit too complicated for such important and very basic functionality.    It would be super helpful to have a way to set primary key without going through the steps described below.   Something like this for instance: 

`mix phoenix.gen.json User users name:string:primary_key age:integer info:text`  

Here is my newbie experience to get this working:
After trying to find an easy way to do this and reading more docs and not finding the answer (possibly I don't know where to look), I found phoenix channel on slack. 
Luckily phoenix support there is AMAZING!   I posted the questions and got replies pretty much immediately.   

All the changes I had to make are in this gist (3 files): https://gist.github.com/iguberman/8ab630670bf6cd07b549  After I made all the manual changes -- I still got an exception related to id column missing.  So I added a dummy id (with null values) back into my table to work around that.   Now I got it working!  But I still have the dummy id column in my users table -- not ok for a work project. 

So, after all this I'm looking into plug + postgrex instead of Phoenix per recommendations I got on phoenix channel.  Possibly it is a more suitable toolset for my particular situation, but possibly having more ease and flexibility with setting primary key could be a win for Phoenix?   I really liked the idea of having this RESTful service ready after just 5 easy steps, if only it was ok for my primary key to be an integer and its column name to be 'id', but I have no control over this part -- it's a work requirement.

**Comment by josevalim** [comment]
Hello @iguberman!

We are glad you are enjoying Phoenix!

Setting another primary key is not automated on purpose: we don't think you should be changing the primary key that frequently. For example, a lot of Phoenix/Ecto works assuming there is an ID field. For example, when you generate a URL? We default to the ID field. When you set up an association? It defaults to the ID field.

The database will also be happier if you have an ID field too. Finding by ID would be much faster than looking up by name. Even when both are indexed.

You can of course change the primary key but then you will need to give Phoenix and Ecto small hints in many different places. For example...

> So I added a dummy id (with null values) back into my table to work around that. Now I got it working! But I still have the dummy id column in my users table -- not ok for a work project.

You probably need to tell your model what the new primary key field and to use the :name when generating URLs:

    @derive {Phoenix.Param, :name}
    @primary_key {:name, :string, []}
    schema "users" do
      # ...
    end

This should be it for getting started, but again, you should double-check, even triple-check, if it is worth changing you primary key column.

For all those reasons, we don't want to automate changing primary key. We could improve the docs but I don't want to make it part of the default workflow.

**Comment by iguberman** [comment]
Thanks so much for the feedback! :) @josevalim 
I'm still convinced this is very important feature because sometimes people start from an already existing project or DB schema or from existing requirements and don't have a choice (like in my case).   I do agree that a link to a good and up-to-date document covering how to specify your custom primary key  would be sufficient at least for some time.    With your suggestion above I finally was able to get it working like I wanted with the following modifications to the code after I ran 
>`mix phoenix.gen.json User users name:string age:integer`

in models/user.ex
1.   Add 
    `@primary_key {:name, :string, []}` 
     right above 
     `schema "users" do` 
 (for some reason I had exceptions when I had  `@derive {Phoenix.Param, :name}` so I removed it)
2.  Add somewhere
```
defimpl Phoenix.Param, for: Chat.User do 
    def to_param(user) do
        user.name
   end
end
```

modified migrations/20150901215253_create_user.exs like so:
```
def change do
    create table(:blob, primary_key: false) do
      add :name, :string, primary_key: true
      add :age, :integer
      timestamps
    end
```

modified views/user_view.ex:
```
def render("user.json", %{user: user}) do
    %{# REMOVED THIS ITEM: id: user.id,
      name: user.name,
      age: user.age
     }
end
```

modified web/controllers/user_controller.ex show, update, and delete methods:

```
def show(conn, %{"id" => name}) do
    user = Repo.get_by!(User, name: name)
...
```
```
def update(conn, %{"id" => name, "user" => user_params}) do
    user = Repo.get_by!(User, name: name)
...
```
```
 def delete(conn, %{"id" => name}) do
    user = Repo.get_by!(User, name: name)
...
```
