### ISSUE TITLE
Sending a channel message to all windows of a certain user

### ISSUE THREAD

**Issue by leikind** [phoenixframework/phoenix#1179]
This is not a bug report, this is a question, sorry, no one in the Slack channel could help so, being desperate, I will ask the question here.

 I have sockets authenticated with `Phoenix.Token`:

```elixir
  def connect(%{"token" => token}, socket) do

    case Phoenix.Token.verify(socket, "user_id", token, max_age: @two_weeks) do
      {:ok, user_id} ->  {:ok, assign(socket, :user, user_id)}
      {:error, reason} -> :error
    end
  end
```

and my socket module exposes function `id`

```
  def id(socket),  do: "users_socket:#{user_id(socket)}"

  defp user_id(socket), do: socket.assigns[:user]
```

which, as far as I understand, registers all sockets in the PubSub server with a topic like "users_socket:42".

This allows me to run 

```elixir
Foo.Endpoint.broadcast("users_socket:42", "disconnect", %{})
```

which sends a disconnect message to all sockets of the user with ID 42. It does work. 

But how do I send a **_channel_** message to all windows of that user? 
I need a way to send messages to browser windows on a server side event.

This is my failed attempt:

```elixir
pubsub_server =  Foo.Endpoint.__pubsub_server__
Phoenix.PubSub.broadcast! pubsub_server, "users_socket:42", %Phoenix.Socket.Broadcast{
  topic: "mychannel:main",
  event: "msg",
  payload: %{body: "hello there"}
}
```

I am definitely missing something.

Sure, I can store active sockets in my own GenServer where they are connected, but it just doesn't feel right, as these sockets are already somewhere there registered in PubSub.

Thank you for your time.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
