### ISSUE TITLE
generator, config file problem

### ISSUE THREAD

**Issue by elbarto132** [phoenixframework/phoenix#1182]
I was just wondering why my app was using the Repo config from config.exs instead of dev.exs
Then i looked in config.exs and found this:

```
# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{Mix.env}.exs"

config :websocket, Websocket.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "websocket_repo",
  username: "user",
  password: "pass",
  hostname: "localhost"
```

I didn't change anything in this file by myself, so there has to be a problem with a generator which generates this code

**Comment by josevalim** [comment]
Ah, it seems you used ecto.gen.repo. I will open up an ecto bug.
