### ISSUE TITLE
mix phoenix.digest failing on Elixir v1.1.0-beta

### ISSUE THREAD

**Issue by chrismcg** [phoenixframework/phoenix#1185]
```
chris@gairmi % mix phoenix.digest
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:126: Enumerable.member?/2
    (elixir) lib/enum.ex:1188: Enum.member?/2
    lib/phoenix/digester.ex:79: Phoenix.Digester.compress/1
    lib/phoenix/digester.ex:46: anonymous fn/2 in Phoenix.Digester.do_compile/2
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
```

Seeing this with my test project https://github.com/chrismcg/phlink on 1.1.0-beta from the Precompile.zip after cleaning everything and rebuilding. Works fine on 1.0.5.

**Comment by chrismcg** [comment]
It's the `Application.get_env(:phoenix, :gzippable_exts)` that returns nil

**Comment by chrismcg** [comment]
Erlang 18.0.3 if that's relevant

**Comment by josevalim** [comment]
Thank you for trying Elixir beta out. It happens to a bug in Phoenix that was relying on Phoenix app being loaded without invoking a task (or without invoking it manually). A temporary workaround is to use `mix do app.start, phoenix.digest`.
