### ISSUE TITLE
mix phoenix.routes failing on Elixir v1.1.0-beta

### ISSUE THREAD

**Issue by wsmoak** [phoenixframework/phoenix#1189]
`mix phoenix.routes` fails with Elixir 1.1.0-beta.  Reported by shreekavi in Slack, confirmed by chrismcg.

To reproduce,
```
$ mix phoenix.new delete_me_1115
$ cd delete_me_1115
$ mix phoenix.routes
[...]
** (UndefinedFunctionError) undefined function: DeleteMe_1115.Router.__routes__/0 (module DeleteMe_1115.Router is not available)
    DeleteMe_1115.Router.__routes__()
    lib/phoenix/router/console_formatter.ex:9: Phoenix.Router.ConsoleFormatter.format/1
    lib/mix/tasks/phoenix.routes.ex:29: Mix.Tasks.Phoenix.Routes.run/1
    (mix) lib/mix/cli.ex:54: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

If I switch back to Elixir 1.0.5 then the `mix phoenix.routes` command works fine.

A similar (?) issue #1185 in phoenix.digest was fixed by https://github.com/phoenixframework/phoenix/commit/a21cd067842274878bbcb0c25339965ec848faea

The adapted workaround of `mix do app.start, phoenix.routes` suggested in #1185 does work.

**Comment by josevalim** [comment]
@chrismccord I am on this so we can ship 1.0.2.

**Comment by josevalim** [comment]
@wsmoak thank you for reporting!
