### ISSUE TITLE
empty page

### ISSUE THREAD

**Issue by hkairi** [phoenixframework/phoenix#1190]
Hi

i have started a new project following the instructions ( from the guides )

mix phoenix.new my_app
mix ecto.create
mix phoenix.server

when i go the http://localhost:4000/

i got a blank page .. and no errors

**Comment by josevalim** [comment]
You need to give us more information. Do you see anything in the terminal? Which Phoenix, Elixir (`elixir -v` and Erlang (`erl`) versions?

**Comment by hkairi** [comment]
i see nothing in the terminal. No messages . No errors

Erlang/OTP 18 [erts-7.0.2]
Elixir 1.0.5
Phoenix 1.0.0

i am using Yosemite (Mac os)

**Comment by josevalim** [comment]
Thanks. This is so weird, I have no idea why this is happening. If you do `iex -S mix phoenix.server`, does it at least print the headers? Can you please paste the result here?

**Comment by hkairi** [comment]
![capture d ecran 2015-09-06 a 21 15 33](https://cloud.githubusercontent.com/assets/28127/9706664/86221ee4-54dc-11e5-926f-df18a1349a2a.png)

i refreshed many times the blank page and i have no output in the console .

very weird :(

**Comment by josevalim** [comment]
Have you tried accessing `127.0.0.1:4000` or your local IP address just to be sure it is nothing something with localhost?

**Comment by josevalim** [comment]
Try `ping localhost` too.

**Comment by hkairi** [comment]
localhost responds to ping.

it worked with the 127.0.0.1:4000 

weird thing

**Comment by jerefrer** [comment]
Just had the same issue here, ` 127.0.0.1:4000` did the trick. I'm on Archlinux.

Maybe it should put this somewhere at the end of the "Up And Running" guide page ?

    If your screen looks like the image above, congratulations! You now have a working Phoenix application.
    If not, try 127.0.0.1:4000. If it still doesn't work please file an issue on Github

... or something.

I tried googling `phoenix framework blank page` and found nothing so I came here but I think not every young developer has the habit of going to check Github issues.

Now I'm gonna try this awesome framework :)

**Comment by lancehalvorsen** [comment]
@hkairi and @jerefrer, just out of curiosity, what do your `/etc/hosts` files look like? On OS X, mine has this line by default:

`127.0.0.1       localhost`

**Comment by hkairi** [comment]
@josevalim mine looks like this

# /etc/hosts

127.0.0.1 localhost
::1             localhost

**Comment by lancehalvorsen** [comment]
@hkairi sorry, that was me. Once I re-read all the comments from the top, I realized that it wasn't the right question, so I deleted it.

**Comment by tobinharris** [comment]
Just had the same problem - installed for first time following setup guide, then went to `localhost:4000` in browser and got a blank page. Went to `127.0.0.1:4000` and all works fine. Weird indeed.

**Comment by antonzaytsev** [comment]
Same here, only 127.0.0.1:4000 works. On localhost:4000 have blank page without any logs in console.

**Comment by jbhatab** [comment]
Same for me.

**Comment by jaunkst** [comment]
+1

**Comment by rizalmuthi** [comment]
I have the same problem. 
Next step is, how do we change from 127.0.0.1:4000 to make the localhost:4000 works?
Thanks

**Comment by Lesuk** [comment]
This issue helped me #342
