### ISSUE TITLE
`mix test` fails in new project using mongodb

### ISSUE THREAD

**Issue by wsmoak** [phoenixframework/phoenix#1194]
Reported by a user on irc.  `mix test` doesn't work in a newly created Phoenix project using mongodb.
To reproduce:

```
$ mix new my_project --database mongodb
# Y to Fetch and install...
$ cd my_project
$ mix test
[...]
** (RuntimeError) cannot begin test transaction with pool Ecto.Pools.Poolboy.
In order to use test transactions with Ecto SQL, you need to
configure your repository to use Ecto.Adapters.SQL.Sandbox:

    pool: Ecto.Adapters.SQL.Sandbox

    (ecto) lib/ecto/adapters/sql.ex:379: Ecto.Adapters.SQL.test_transaction/3
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/enum.ex:579: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:579: Enum.each/2
    (mix) lib/mix/tasks/test.ex:183: Mix.Tasks.Test.run/1
    (mix) lib/mix/cli.ex:54: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

Also tried `mix ecto.create` (as instructed in the output) before `mix test` -- no change.

Based on the error (and comparing to a default postgres project) I tried adding the `pool: ...` line to config/test.exs, but that just produced a different error message.

phoenix 1.0.2 and latest on master, Elixir 1.1.0-latest on master

**Comment by josevalim** [comment]
Thank you! It is a matter of removing "Ecto.Adapters.SQL.begin_test_transaction(Demo.Repo)" from the test_helper.exs. I will fix it in master. :)

**Comment by josevalim** [comment]
Fixed in master!
