### ISSUE TITLE
Provide aliases for ecto.reset and ecto.setup

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1198]
They are convenient and will fit as an example of aliases. Here is the code:

```elixir
["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
 "ecto.reset": ["ecto.drop", "ecto.setup"]]
```

Thoughts?

**Comment by josevalim** [comment]
Alternatively, we can ship with those by default on Ecto, but Ecto wouldn't load the seeds file.

**Comment by dukex** [comment]
I'm newbie and I don't understand the big picture but looks nice the ```ecto.setup```/```echo.reset``` in phoenix(running ```seeds.exs```)

**Comment by chrismccord** [comment]
:+1: but I need to open that issue on ecto where drop/reset raises if not dev or test (with --force option). I like that this give a mix alias example.

**Comment by parkerl** [comment]
:heart: this idea but I would like to see `ecto.reset` and the like in ecto proper.

**Comment by Tica2** [comment]
In ecto issue was here:
https://github.com/elixir-lang/ecto/issues/936

**Comment by stevedomin** [comment]
@chrismccord are you referring to this issue: https://github.com/elixir-lang/ecto/issues/934

**Comment by gjaldon** [comment]
I agree with @parkerl. Would be nice to have these conveniences in Ecto.

**Comment by josevalim** [comment]
If those conveniences are in ecto, they can't do things like running seed files.
