### ISSUE TITLE
Remove Repo alias from models and views from installer

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1203]
As it alignes with our definition of models and views being pure layers.

/cc @chrismccord @batate

**Comment by Gazler** [comment]
Isn't this already the case?

https://github.com/phoenixframework/phoenix/blob/e92ca7c7f950484cf08ebe443d073713d5a719be/installer/templates/new/web/web.ex#L23

**Comment by josevalim** [comment]
It is indeed. :)

**Comment by josevalim** [comment]
Tahnk you!
