### ISSUE TITLE
Delete link could not work

### ISSUE THREAD

**Issue by knt45** [phoenixframework/phoenix#1204]
I try to make example app with phoenix 1.0.2.

I run 

```
mix phoenix.gen.html User users name:string email:string
```

But delete link could not work in web\templates\user\index.html.eex.

Generated code is

```
<%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
```

To work, I rewrite like this.

```
<%= button "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
```

But in this code, confirm dialog did not appear.

**Comment by josevalim** [comment]
The generated code works fine for me with a new app.

Since delete requires javascript. Are you using brunch and are you sure your assets have been compiled?

**Comment by knt45** [comment]
Thank you for your advice.
