### ISSUE TITLE
Run an Elixir application in a Phoenix project context

### ISSUE THREAD

**Issue by chinh7** [phoenixframework/phoenix#1205]
Hello
I currently have a Phoenix app that runs multiple instances. Also there is this Elixir application (Quantum) I would like to just have one single running instance.
If I am to add Quantum to the project's mix.exs, Quantum's cronjob will get triggered multiple times at one point in time (because of multiple instances of Phoenix)
Is there any way to not add Quantum to the project itself but still be able to run Quantum in its context?
Something similar to `bundle exec` in the Rails world
Thanks

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
