### ISSUE TITLE
POST JSON works fine for a model with custom primary_key, but a weird exception gets generated at the end

### ISSUE THREAD

**Issue by iguberman** [phoenixframework/phoenix#1214]
>mix phoenix.gen.json Drive drives drive_id:string state:integer

I followed the steps to change primary_key to be drive_id instead of the Ecto id.  
> mix ecto.migrate

>curl -i -X POST -H 'Content-Type:application/json' -d '{"drive":{"state": 1,"drive_id": "moo1"}}' http://localhost:4000/v1/drives     

This command works fine and results in a new entry in drives table in DB, but there is an exception at the end which makes no sense.  

[info] POST /v1/drives
[debug] Processing by Dutracker.DriveController.create/2
  Parameters: %{"drive" => %{"drive_id" => "moo5", "state" => 5}}
  Pipelines: [:api]
[debug] BEGIN [] OK query=0.3ms
[debug] INSERT INTO "drives" ("drive_id", "inserted_at", "state", "updated_at") VALUES ($1, $2, $3, $4) ["moo5", {{2015, 9, 15}, {15, 26, 55, 0}}, 5, {{2015, 9, 15}, {15, 26, 55, 0}}] OK query=0.4ms
[debug] COMMIT [] OK query=1.0ms
[info] Sent 500 in 14ms
[error] #PID<0.298.0> running Dutracker.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /v1/drives
** (exit) an exception was raised:
    ** (ArgumentError) structs expect an :id key when converting to_param or a custom implementation 
        (phoenix) lib/phoenix/param.ex:116: Phoenix.Param.Any.to_param/1
        (dutracker) web/router.ex:1: Dutracker.Router.Helpers.drive_path/4
        (dutracker) web/controllers/drive_controller.ex:20: Dutracker.DriveController.create/2
        (dutracker) web/controllers/drive_controller.ex:1: Dutracker.DriveController.phoenix_controller_pipeline/2
        (dutracker) lib/phoenix/router.ex:265: Dutracker.Router.dispatch/2
        (dutracker) web/router.ex:1: Dutracker.Router.do_call/2
        (dutracker) lib/dutracker/endpoint.ex:1: Dutracker.Endpoint.phoenix_pipeline/1
        (dutracker) lib/plug/debugger.ex:90: Dutracker.Endpoint."call (overridable 3)"/2
        (dutracker) lib/phoenix/endpoint/render_errors.ex:34: Dutracker.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

**Comment by josevalim** [comment]
You need to tell Phoenix how to convert your data structure to an ID that is used in the routes. By default, if we use the ID field. Since you removed it, Phoenix is clueless. Add this to your model before the schema call:

    @derive {Phoenix.Param, key: :drive_id}

I will improve the error message. :)

**Comment by iguberman** [comment]
Yes, that did it! Thank you Jose!   Looks like this info needs to be added
to this doc:
https://github.com/phoenixframework/phoenix_guides/blob/master/bonus_guides/EE_custom_primary_key.md
