### ISSUE TITLE
Create mix task for generating a controller

### ISSUE THREAD

**Issue by kyledecot** [phoenixframework/phoenix#1217]
This can currently be done when using `mix phoenix.gen.html` but it would be nice if we could extract the controller portion of this so that we could just do `mix phoenix.gen.controller`. Thoughts?

**Comment by josevalim** [comment]
We thought about it but it should be an empty controller and an empty
controller does not add much.

In any case, we should probably discuss this in the Phoenix code mailing
list. :)


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
I'm not convinced this is needed at this time and it gets complex quickly. Do we generated the view? templates? what if you just want a plain controller for json? Or you want a JSON view but no web/templates/new_controller folder? I'd prefer to wait on this one. Thanks for the suggestion. Feel free to take it up on the mailing list for other's thoughts

**Comment by kyledecot** [comment]
@chrismccord I guess I suggested this because both `phoenix.gen.json` and `phoenix.gen.html` both contain code for generating a controller file (and it's test file). Seems like having a dedicated task for this would DRY the code up a little.
