### ISSUE TITLE
Send own heartbeats to client from channel server

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1220]
https://github.com/phoenixframework/phoenix/commit/b440ef03daa43cc94d4fa3f3ece086f272b6a6f7#commitcomment-13248466

**Comment by josevalim** [comment]
It should ship with 1.0.3.

**Comment by nolman** [comment]
Thanks!

**Comment by chrismccord** [comment]
@josevalim I desperately tried to avoid `Phoenix.Utils`, but all other homes for `now_ms()` were worse. Let me know if you have a better idea
