### ISSUE TITLE
Query strings are ignored in GET requests 

### ISSUE THREAD

**Issue by iguberman** [phoenixframework/phoenix#1222]
I think this is the only thing right now that prevents Phoenix from fully supporting RESTful services out of the box.    I.e. whether I call `localhost:4000/users` or `localhost:4000/users?age=6`   I get ALL users regardless of the age.   

This is my generated user_controller.ex

```elixir
def index(conn, _params) do   #  _params is a map of query string parameters
                                                #   %{"age" => "6"}  but it is simply ignored
      drives = Repo.all(Drive)
      render(conn, "index.json", drives: drives)
 end
```

**Comment by simonprev** [comment]
I think naming a param with an underscore simply ignores the content. 

```elixir
def index(conn, params) do
```

This should map `params` to the expected value.

**Comment by iguberman** [comment]
No, whether it's params or _params it has to be used somehow further in the method, but it's not.   Also I'm a newbie to the whole thing and I was looking at Ecto to modify the generated index method to  send params to a proper Ecto method but haven't yet figured it out..   (i.e. changing `Repo.all(Drive)' to `Repo.all(Drive, params)` won't do it )    I will spend a few more hours and will eventually figure it out, but I think this is functionality so basic that it should be supported out of the box.

**Comment by Gazler** [comment]
For future reference - it is worth reading https://github.com/phoenixframework/phoenix/blob/master/CONTRIBUTING.md to know where to post your questions.

All of the functions in a controller take 2 arguments (by default - this is overridden.)

Since the parameters are not used the second argument is `_params` which identifies that the argument is required to pattern match the function, but is ignored. However the parameter is still available and can be used.

The reason the `params` are ignored is because they are not used. To use them you would have to use the parameter in some way:

```
def index(conn, _params) do
      drives = case params["age"] do
        nil -> Repo.all(Drive)
        age -> Repo.all(Ecto.Query.from(d in Drive, where: d.age == ^age)
      render(conn, "index.json", drives: drives)
 end
```

**Comment by chrismccord** [comment]
Thanks @Gazler, this is the correct answer. @iguberman I'm going to close since this isn't a bug, but feel free to chime in here if anything is not clear.

**Comment by iguberman** [comment]
I think I shoud've called this issue "Phoenix misses query string support
to be fully RESTful out of the box"  and should've made it a feature
request :)   That's what I meant this issue to be -- my bad for not making
it clear.

Thanks so much @Gazler -- your answer is approximately what I was looking
for in my project (though I was looking for a method in Ecto to take in a
map and turn it into a where clause, that way this part of the code won't
need to change manually if fields are added or removed during a migration)


My project is a very simple RESTful interface and the reason I opened this
issue is because this functionality doesn't work out of the box.

I think it is very natural for someone to generate a json model and then
try to query it like this: localhost:4000/users?age=6   -- if they do it
returns a full user list -- it doesn't even produce an error message
indicating that query strings are not supported.

RESTful protocol is very popular, and like I mentioned in this issue,
Phoenix seems to be literally just this one step away from fully supporting
it (without any manual code manipulations)

Thanks,
Irina.

**Comment by chrismccord** [comment]
Ah I see. Yes, you need to take the params yourself and compose them against Ecto, or whatever data layer you are using.

**Comment by iguberman** [comment]
I'll post this for discussion to the phoenix-core -- I finally read the
CONTRIBUTING.md!    Sorry  if I'm causing too much noise before I read
enough documentation and all.   Trying to introduce Phoenix at work for a
project where it really fits but need to produce results faster than I can
read all the docs :)
