### ISSUE TITLE
Try to catch controller action match errors and 400

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1225]

**Comment by stevegraham** [comment]
:+1:

**Comment by chrismccord** [comment]
My new plan to solve this is to rely on `action/3` clauses instead of mucking with stacktraces, for example this works today, and is clearer than our current approach:

```elixir
defmodule MyController do

  def action(conn, _) do
    apply(__MODULE__, :action, [action_name(conn), conn, conn.params])
  end
  
  def action(:show, conn, params) do
    ...
  end
  
  def action(:index, conn, params) do
     ...
  end
  
  def action(_, conn, params), do: send_resp(conn, :bad_request, "")
end
```

Whatever we do here must be backwards compatible now that 1.0 has shipped, so this would have to be further off as a default if we went this direction. We could release a `Phoenix.ActionController` that injects this behavior and leave `Phoenix.Controller` untouched, or if we're feeling adventurous, we could detect if any `:action` clauses have been defined and use the new behavior. The latter is likely too much though. Thoughts?

**Comment by josevalim** [comment]
Nah, I am :-1:. We already have one way of doing things, we shouldn't have two unless we have very good reasons. This can either be a separate or people can easily implement it in their apps.

**Comment by chrismccord** [comment]
@josevalim good points. I'm definitely on board with the one way to do things, especially for learning material that's out there. I'll shelve this idea for now, with the flip side that folks can use that snippet exactly as shown today if they really want catch-all handling.
