### ISSUE TITLE
Compilation error at phoenix.gen.json

### ISSUE THREAD

**Issue by rhazdon** [phoenixframework/phoenix#1232]
Hi guys,

I tried to generate a JSON resource with the command line 
> $ mix phoenix.gen.json

My example:
> $ mix phoenix.gen.json User users for_name:string last_name:string

After that I want to update the database via 
> mix ecto.migrate

The following error occurs:
```bash
MyMac:rest_api user$ mix ecto.migrate
Compiled web/views/changeset_view.ex
Compiled web/views/user_view.ex
Compiled web/models/user.ex

== Compilation error on file web/controllers/user_controller.ex ==
** (CompileError) web/controllers/user_controller.ex:20: function user_path/3 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

It seems phoenix generates a function that does not exist. 

The malfunction in user_controller.ex. The line between the *** *** is the affected line:
```elixir
def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> put_status(:created)
   ***  |> put_resp_header("location", user_path(conn, :show, user)) ***
        |> render("show.json", user: user)
      {:error, changeset} ->
        conn
        |> put_status(:unprocessable_entity)
        |> render(RestApi.ChangesetView, "error.json", changeset: changeset)
    end
  end
```

Thank you for your help!

**Comment by chrismccord** [comment]
After you ran the command, the first thing the output told you to do was to run add `resource "/users", UserController` to a scope in your router. It looks like you missed that step :)

**Comment by rhazdon** [comment]
Shame on me... thank you... you're absolutely right... :)
