### ISSUE TITLE
Enable custom HTTP methods

### ISSUE THREAD

**Issue by iStefo** [phoenixframework/phoenix#1236]
As a follow-up to #1234, this issue should track the progress of a `match(verb)` primitive for the Router module that enables serving requests with non-traditional HTTP methods such as `MOVE`, `COPY` etc., which are required when implementing a server that can speak the WebDAV protocol or others.

In #1234 it was decided that a new primitive would be the best choice for such an enhancement because it enables the creation of own, domain specific macros (such as `get/3`, `post/3` etc.) and does not require recompiling Phoenix when adding new methods.

Ping @chrismccord @josevalim.

**Comment by stevedomin** [comment]
@chrismccord I know you assigned it to yourself but I'm really keen on giving it a go if you haven't started. I'd like to dig more into Phoenix internals and seems like a good occasion to do so.

**Comment by tejasmanohar** [comment]
@stevedomin There's no solution out yet so I bet a PR would be appreciated :wink: ... at least that's how it usually works from my experience.

**Comment by chrismccord** [comment]
@stevedomin sorry for the delay, but I am on this. I will keep you on deck for the next thing we'll need help with :)

**Comment by chrismccord** [comment]
This has been added to master, and you can now do:

```elixir
match(:move, "/events/:id", EventController, :move)
```
