### ISSUE TITLE
String or binary salt value for Phoenix.Token

### ISSUE THREAD

**Issue by MattNguyen** [phoenixframework/phoenix#1238]
The documentation for `Phoenix.Token` indicates a salt must be passed into params for `sign/3` and `verify/4` (https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/token.ex#L13). 

However, running `Phoenix.Token.sign(endpoint, "user", user_id)` (with proper variable substitution) in iex returns a `FunctionClauseError` unless the salt value is binary. Indeed, their function definitions guard for binary values explicitly (https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/token.ex#L71). 

Every example and documentation  around `Phoenix.Token` uses string values for the salt, so it's a little perplexing that the specs pass with string values. Can someone help me understand why this is the case? Should there be documentation to explicitly cast string values to binary?

FYI - I'm about a week into learning Elixir/Phoenix so there are definitely gaps in knowledge. Any help would be greatly appreciated. Thanks!

**Comment by chrismccord** [comment]
A string is a binary, so nothing is wrong from the example you provided:

```elixir
iex(1)> is_binary("user")
true
```

Can you provide the exact line of code and full stack trace that is causing this error? Are you sure in your code that you weren't passing a char list with single quotes?

**Comment by MattNguyen** [comment]
Doh! Definitely single quotes. Thanks for the quick response!

**Comment by chrismccord** [comment]
No problem. elixir-lang irc is a great place for quick access to help for little snags like this. Happy learning :)
