### ISSUE TITLE
Not found :heardbeat key

### ISSUE THREAD

**Issue by JustMikey** [phoenixframework/phoenix#1239]
I am getting this weird error every few seconds when my server is running. I haven't even touched sockets functionality yet so I am not even sure what is going on. The error is the following:

`[error] Ranch protocol #PID<0.1297.0> (:cowboy_protocol) of listener SocialNetwork.Endpoint.HTTP terminated
** (exit) exited in: Phoenix.Endpoint.CowboyWebSocket.resume()
    ** (EXIT) an exception was raised:
        ** (KeyError) key :heartbeat not found in: [serializer: Phoenix.Transports.WebSocketSerializer, timeout: :infinity, transport_log: false]
            (elixir) lib/keyword.ex:235: Keyword.fetch!/2
            (phoenix) lib/phoenix/transports/websocket.ex:99: Phoenix.Transports.WebSocket.ws_init/1
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:59: Phoenix.Endpoint.CowboyWebSocket.websocket_init/3
            (cowboy) src/cowboy_websocket.erl:131: :cowboy_websocket.handler_init/3
            (phoenix) lib/phoenix/endpoint/cowboy_websocket.ex:36: Phoenix.Endpoint.CowboyWebSocket.resume/3
            (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4`

Maybe I dont understand something or maybe something is actually not working right. I just thought that I had to report.

**Comment by chrismccord** [comment]
Try `mix deps.clean phoenix_live_reload`

Please reopen if that doesn't solve it for you

**Comment by dashingshakeel** [comment]
** (KeyError) key :database not found in: [otp_app: :rumbl, repo: Rumbl.Repo, adapter: Ecto.Adapters.Postgres, pool_size: 18, ssl: true]
    (elixir) lib/keyword.ex:312: Keyword.fetch!/2
    lib/ecto/adapters/postgres.ex:65: Ecto.Adapters.Postgres.storage_up/1
    lib/mix/tasks/ecto.create.ex:34: anonymous fn/2 in Mix.Tasks.Ecto.Create.run/1
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
