### ISSUE TITLE
POST functionality inconsistent with PUT, GET, and DELETE in referenced models

### ISSUE THREAD

**Issue by iguberman** [phoenixframework/phoenix#1240]
Hope you find this a reasonable complaint... 

**Background:**
```console
$mix phoenix.new --no-html gps_data
$mix ecto.create
$mix phoenix.gen.json Datum data lat:float lon:float data:map
$mix phoenix.gen.json Tag tags name:string value:string datum_id:references:data
```
Modify models/data.ex like so to create one-to-many datum-tags association:

```elixir
schema "data" do
    field :lat, :float
    field :lon, :float
    field :data, :map

    has_many :tags, GpsData.Tag

    timestamps
end
```

Modify required_fields in models/datum.ex:
```elixir
@required_fields ~w(lat lon data tags)
```

**Issue:**

Create a new datum object by POSTing a json that includes tags list in the datum object -- I actually didn't expect this to work but it did -- Phoenix is AWESOME!!! :)  

```json
{"datum": {
   "lon":55.12345678912345,
   "lat":88.12345678912345,
   "data":{"key":"info", "value":"A lot more info" }, 
   "tags":[
        {"name":"responsible", "value":"Neo"}, 
        {"name":"user","value":"nanderson"}, 
        {"name":"occupation", "value":"hacker"}
    ] 
 } 
}
```

```console
$curl -i -X POST -H 'Content-Type:application/json' -d '{"datum": {"lon":55.12345678912345,"lat":88.12345678912345,"data":{"key":"info", "value":"A lot more info" }, "tags":[{"value":"Neo","name":"responsible"}, {"name":"user","value":"nanderson"}, {"name":"occupation", "value":"hacker"}] } }' http://localhost:4000/api/data > out.html
```

Works great!   I got all the proper associations created in the DB: 3 tag entries and 1 datum entry!  Now I got my hopes up and expect that all the other methods work like this too (NOTE: I won't query tags separately and I won't even add them to routes.ex because from a business perspective they really are part of datum object)

Now I run GET:
```console
$curl -i -X GET http://localhost:4000/api/data/1
{"data":{"lon":55.12345678912345,"lat":88.12345678912345,"id":4,"data":{"value":"A lot more info","key":"info"}}}
```
No tag info :( 

Run PUT -- definitely expect it to work with JSON object of the same format I used  in POST:
```console
$curl -i -X PUT -H 'Content-Type:application/json' -d '{"datum": {"lon":55.00045678912345,"lat":88.00045678912345,"data":{"key":"info", "value":"A lot more updated info!" }, "tags":[{"value":"Neo","name":"responsible"}, {"name":"user","value":"nanderson"}, {"name":"occupation", "value":"programmer"}] } }' http://localhost:4000/api/data/1 > out.html
```
Server error:
```
[error] #PID<0.352.0> running GpsData.Endpoint terminated
Server: localhost:4000 (http)
Request: PUT /api/data/1
** (exit) an exception was raised:
    ** (ArgumentError) attempting to cast or change association `tags` from `GpsData.Datum` that was not loaded. Please preload your associations before casting or changing the model
        (ecto) lib/ecto/changeset/relation.ex:146: Ecto.Changeset.Relation.load!/2
        (ecto) lib/ecto/changeset.ex:459: Ecto.Changeset.cast_field/6
        (ecto) lib/ecto/changeset.ex:408: Ecto.Changeset.do_process_param/8
        (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/changeset.ex:372: Ecto.Changeset.cast/5
        (gps_data) web/controllers/datum_controller.ex:40: GpsData.DatumController.update/2
        (gps_data) web/controllers/datum_controller.ex:1: GpsData.DatumController.action/2
        (gps_data) web/controllers/datum_controller.ex:1: GpsData.DatumController.phoenix_controller_pipeline/2
        (gps_data) lib/phoenix/router.ex:255: GpsData.Router.dispatch/2
        (gps_data) web/router.ex:1: GpsData.Router.do_call/2
        (gps_data) lib/gps_data/endpoint.ex:1: GpsData.Endpoint.phoenix_pipeline/1
        (gps_data) lib/plug/debugger.ex:90: GpsData.Endpoint."call (overridable 3)"/2
        (gps_data) lib/phoenix/endpoint/render_errors.ex:34: GpsData.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Run DELETE:
```console
$curl -i -X DELETE http://localhost:4000/api/data/1 > out.html
```
Server error:

```
[error] #PID<0.336.0> running GpsData.Endpoint terminated
Server: localhost:4000 (http)
Request: DELETE /api/data/1
** (exit) an exception was raised:
    ** (Ecto.ConstraintError) constraint error when attempting to delete model:

    * foreign_key: tags_datum_id_fkey

If you would like to convert this constraint into an error, please
call foreign_key_constraint/3 in your changeset and define the proper
constraint name. The changeset has not defined any constraint.

        (ecto) lib/ecto/repo/model.ex:274: anonymous fn/5 in Ecto.Repo.Model.constraints_to_errors/3
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/repo/model.ex:221: anonymous fn/8 in Ecto.Repo.Model.do_delete/4
        (ecto) lib/ecto/repo/model.ex:36: Ecto.Repo.Model.delete!/4
        (gps_data) web/controllers/datum_controller.ex:57: GpsData.DatumController.delete/2
        (gps_data) web/controllers/datum_controller.ex:1: GpsData.DatumController.action/2
        (gps_data) web/controllers/datum_controller.ex:1: GpsData.DatumController.phoenix_controller_pipeline/2
        (gps_data) lib/phoenix/router.ex:255: GpsData.Router.dispatch/2
        (gps_data) web/router.ex:1: GpsData.Router.do_call/2
        (gps_data) lib/gps_data/endpoint.ex:1: GpsData.Endpoint.phoenix_pipeline/1
        (gps_data) lib/plug/debugger.ex:90: GpsData.Endpoint."call (overridable 3)"/2
        (gps_data) lib/phoenix/endpoint/render_errors.ex:34: GpsData.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

So, obviously it requires a LOT more manual work now to get this working as expected.    But to me it would be very natural if it worked out of the box with referenced model, especially considering that POST does work like this already.    I know this is a lot to ask for and may not be the highest priority issue, but I'm curious if you agree to this being a valid request/expectation -- considering that POST works great, but the other 3 requests don't?    If so -- I would be happy to contribute as I'm making progress solving this problem for my own purposes.

**Comment by josevalim** [comment]
I am not sure I agree it should work by default. Maybe we could
automatically preload the data on update. But there is nothing we can do on
delete. If we delete by default, others would be surprised by us removing
data when we should not. If we nullify the dependency, it can be
inconsistent. At best, we could generate on_delete on the migrations so it
is at least clear what to change.

The idea of Phoenix generators is never to provide compete full blown
functionality, but to get you started. And I think the error messages are
guiding you to make the best decisions as required.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Btw, POST doesn't work by default unless you add the tags to the list of
required or optional fields. So a small intervention is required for all
actions, otherwise Phoenix would default to rendering and exposing all
associations, which would be catastrophic! :)

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by rhazdon** [comment]
I'm a little bit confused about the reference of datum_id
```bash
$mix phoenix.gen.json Tag tags name:string value:string datum_id:references:datum
```

Should not be there a reference to data instead of datum?

**Comment by iguberman** [comment]
Oh, good catch @josevalim -- I forgot to mention in the issue description that I added tags as required field in datum.ex:

`@required_fields ~w(lat lon data tags)`   
I also agree with DELETE comment -- it might be a bit dangerous to just go ahead and delete stuff if the associations changed (unless there is a way to detect associations and be able to DELETE or not DELETE referenced models).   But if PUT and possibly GET worked consistently with POST it would be super nice.    I understand that I want Phoenix to be more than what it's intended to be (as with all open-source projects! ;)  ) but I also think it would be great for wider Phoenix (as well as Elixir/Erlang) adoption if it did some obvious things out of the box (and I would love to contribute as soon as I become a more mature Elixir/Phoenix user! :) )  (RESTful services is such a popular use case)

**Comment by iguberman** [comment]
Thank you very much @rhazdon -- I modified the issue description (as well as the README file I copied it from)

**Comment by iguberman** [comment]
I tried one more thing with the PUT, I am now only updating one field in the data table without touching the tags:
```console
$curl -i -X PUT -H 'Content-Type:application/json' -d '{"datum": {"lat":91.00045678912345 } }' http://localhost:4000/api/data/1 > out.html
```
Now this looks more like a bug than a mere inconsistency.   I can't perform any update on a table that has required references like `tags` in this particular case. This time around I wasn't even trying to update tags along with other fields in one sweep like I did in my original example and here is the error I got:

```
[info] Sent 500 in 14ms
[error] #PID<0.304.0> running GpsData.Endpoint terminated
Server: localhost:4000 (http)
Request: PUT /api/data/1
** (exit) an exception was raised:
    ** (ArgumentError) attempting to cast or change association `tags` from `GpsData.Datum` that was not loaded. Please preload your associations before casting or changing the model
        (ecto) lib/ecto/changeset/relation.ex:146: Ecto.Changeset.Relation.load!/2
        (ecto) lib/ecto/changeset.ex:459: Ecto.Changeset.cast_field/6
        (ecto) lib/ecto/changeset.ex:408: Ecto.Changeset.do_process_param/8
        (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/changeset.ex:372: Ecto.Changeset.cast/5
        (gps_data) web/controllers/datum_controller.ex:43: GpsData.DatumController.update/2
        (gps_data) web/controllers/datum_controller.ex:1: GpsData.DatumController.action/2
        (gps_data) web/controllers/datum_controller.ex:1: GpsData.DatumController.phoenix_controller_pipeline/2
        (gps_data) lib/phoenix/router.ex:255: GpsData.Router.dispatch/2
        (gps_data) web/router.ex:1: GpsData.Router.do_call/2
        (gps_data) lib/gps_data/endpoint.ex:1: GpsData.Endpoint.phoenix_pipeline/1
        (gps_data) lib/plug/debugger.ex:90: GpsData.Endpoint."call (overridable 3)"/2
        (gps_data) lib/phoenix/endpoint/render_errors.ex:34: GpsData.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```
Why preload association if it's not even being  changed?

NOTE: It all works if I remove `tags` from  `@required_fields ~w(lat lon data)` but I want it there because we don't create datum objects with no tags (it's a one-to-many, not zero-to-many relationship)

**Comment by josevalim** [comment]
If you mark it as a required field, you need to preload it otherwise we can't really know if it has been set or not (because it was not loaded).

**Comment by josevalim** [comment]
If you do `Repo.preload(model, :tags)` in your actions it should be enough. :)

**Comment by iguberman** [comment]
Thanks so much Jose!  I added `Repo.preload` line  to update/delete/index/show.  With some minor tweaks I was able to get PUT and DELETE working properly: added `has_many :tags, NanoOdw.Tag, on_replace: :delete` instead of just `has_many :tags, NanoOdw.Tag` for being able to update tags from full data json and also for DELETE to work I had to explicitely delete all the tags first.     I still can't get datum object displayed with tags -- even though the actual map object as I get it from DB does contain them, it still get's displayed without them.  I'm sure it's another easy fix, but I have no idea where to look.      

I think it would be very useful to have a repo somewhere with various RESTful examples in Phoenix -- unless there is one already I don't know anything about?   Or maybe add it to bonus_guides?  If there isn't -- I would be happy to create it!   @josevalim

**Comment by iguberman** [comment]
Now, that I got more or less familiar with this side of things...   There is this method in relation.ex
```elixir
def load!(model, %NotLoaded{__field__: field}) do
 raise ArgumentError, "attempting to cast or change association `#{field}` " <>
      "from `#{inspect model.__struct__}` that was not loaded. Please preload your " <>
      "associations before casting or changing the model"
  end
```

@josevalim @chrismccord   
IMHO -- instead of raising an exception it would be nice if it was "lazy-loading" the missing field for the user right there.   So the user doesn't call `Repo.preload(model, :tags)` in every access method.    Doesn't it make sense for an ORM to lazily load association data?   And novices won't be turned off by weird exceptions.    Unless  there is a strong reason against it?

**Comment by michalmuskala** [comment]
Ecto is making a deliberate choice not to lazy load. Lazy loading leads to issues like N+1 queries, that are easily solved by thinking first what data will be needed during the request explicitly - requiring to preload associations forces you to think about this. 

For me the bigger issue would be things happening automatically besides my back, that are hidden and possibly hard to understand, rather than a little bit of verbosity here and there.

**Comment by iguberman** [comment]
Thanks a lot @michalmuskala  -- totally answers my question :+1:

**Comment by chrismccord** [comment]
I don't think there is anything for us to handle on the generators side, but maybe we can better highlight preloading in the guides? // @lancehalvorsen. I'm closing for now, but feel free to follow up with questions. Thanks!

**Comment by iguberman** [comment]
Maybe it would be nice to add more specific how-to info to the exception message in relation.ex `load!`?  I.e. 

```elixir
def load!(model, %NotLoaded{__field__: field}) do
    raise ArgumentError, "attempting to cast or change association `#{field}` " <>
      "from `#{inspect model.__struct__}` that was not loaded. Please preload your " <>
      "associations before casting or changing the model. " <>
      "It can be done by calling `Repo.preload(model, #{inspect field})`"
  end
```

**Comment by josevalim** [comment]
That's a great idea @iguberman!

@chrismccord I would like to also always add on_delete on references in migrations, so please let's leave this open until I fix both Ecto and the references. :)

**Comment by iguberman** [comment]
Cool -- thanks! @josevalim :)
