### ISSUE TITLE
Discuss if messages should be automatically queued on the client

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1241]

**Comment by zmoshansky** [comment]
#1295 Highlights a use case where queuing is helpful. "Making a call to join a channel and send a message immediately". Definitely cleaner calling join and setting an `onJoin` callback to then push.

**Comment by chrismccord** [comment]
Taken care of in https://github.com/phoenixframework/phoenix/commit/58405d6a490fb32050e7ae111147931462c06761

Messages are only buffered for the timeout window, then discarded
