### ISSUE TITLE
Issues with phoenix.gen.json & integer

### ISSUE THREAD

**Issue by kettleio** [phoenixframework/phoenix#1242]
I'm running into problems when using the phoenix.gen.json command with anything other than **string**. For example, running the following command will always result in an error when I go to compile:

```$ mix phoenix.gen.json Score scores player:string score:integer```

The errors look something like this:
```
== Compilation error on file lib/kettle_phoenix/endpoint.ex ==
** (UndefinedFunctionError) undefined function: KettlePhoenix.Router.init/1 (module KettlePhoenix.Router is not available)
    KettlePhoenix.Router.init([])
    (plug) lib/plug/builder.ex:198: Plug.Builder.init_module_plug/3
    (plug) lib/plug/builder.ex:186: anonymous fn/4 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:186: Plug.Builder.compile/3
    (phoenix) expanding macro: Phoenix.Endpoint.__before_compile__/1
    lib/kettle_phoenix/endpoint.ex:1: KettlePhoenix.Endpoint (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

My router.ex file looks like this:

```
defmodule HelloPhoenix.Router do  
  use HelloPhoenix.Web, :router

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", HelloPhoenix do
    pipe_through :api

    resources "/scores", ScoreController, except: [:new, :edit]
  end 

end 
```

If I convert the score to **string** it works fine and I don't get the compiling errors.

**Comment by CJPoll** [comment]
@kettleio So what was the solution to the issue?

**Comment by josevalim** [comment]
@CJPoll are you running into the same error? can you please provide full stacktrace and so on? I shoudln't really be happening and integers/strings should not matter. :)

**Comment by CJPoll** [comment]
I was getting something similar, but figured it out. I was interested because my problem was also manifesting as `App.Router.init([])` not existing. It was otherwise unrelated.

**Comment by kettleio** [comment]
@CJPoll the issue was actually rather silly. I changed the name of my controller function in my routes without updating it inside the controller itself. After regenerating with phoenix.gen.json, using the correct names, the problem was solved.

@josevalim phoenix.gen.json is a great tool - thank you!
