### ISSUE TITLE
Documentation query

### ISSUE THREAD

**Issue by TigerWolf** [phoenixframework/phoenix#1245]
When creating a project and looking through the documentation to find a particular method, I have found some methods that appear to be missing. 

For example, with the form helpers `form_for` I cannot find in the latest documentation. Also the form input helpers like `text_input` do not appear in the docs either.

How would I go about contributing to this documentation?

**Comment by jeffkreeftmeijer** [comment]
I think you've been looking in Phoenix's documentation (http://hexdocs.pm/phoenix/Phoenix.html), while the HTML helpers like `form_for` and `text_input` are in the Phoenix.HTML project, which has separate documentation (http://hexdocs.pm/phoenix_html/Phoenix.HTML.html), and you can't find methods like `form_for` from the search box on http://hexdocs.pm/phoenix/Phoenix.html, which indeed is quite confusing.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
