### ISSUE TITLE
no function clause matching in Phoenix.HTML.Tag.tag/2

### ISSUE THREAD

**Issue by dikaio** [phoenixframework/phoenix#1249]
While going over the [Phoenix.HTML](http://hexdocs.pm/phoenix_html/Phoenix.HTML.html) module I wasn't able create html tags with the code below. I'm not sure if I'm doing something wrong or if it's a bug.

This was being added to the **app.html.eex** file.
```Elixir
<%= tag :p, "<hello>" %>
```

**Comment by chrismccord** [comment]
What you want is `content_tag :p, "<hello>"`

**Comment by dikaio** [comment]
:grin: :thumbsup:
