### ISSUE TITLE
Preload and chaining - Error message

### ISSUE THREAD

**Issue by TigerWolf** [phoenixframework/phoenix#1255]
When you chain Preload, you get a really unhelpful error message:

`log = Repo.get!(Log, id) |> Repo.preload [:user] |> Repo.preload [:activity] `

`    ** (UndefinedFunctionError) undefined function: :user.__struct__/0`

After messing around re-reading the [docs](http://www.phoenixframework.org/docs/ecto-models#section-data-relationship-and-dependencies) , I finally found out that preload can deal with multiple models

`log = Repo.get!(Log, id) |> Repo.preload [:activity, :user] `

Is there a way to make this error message more helpful?

**Comment by chrismccord** [comment]
Your first error is caused by the lack of parens to disambiguate your piping. What you wanted is:

    log = Repo.get!(Log, id) |> Repo.preload([:user]) |> Repo.preload([:activity])

Elixir saw your first example as:

    log = Repo.get!(Log, id) |> Repo.preload([:user] |> Repo.preload [:activity])

**Comment by TigerWolf** [comment]
Thanks. Is is possible/valuable to improve the error message in this case?

**Comment by chrismccord** [comment]
Unfortunately it's not possible to improve this particular error message since Elixir is seeing the expression as `[:user]` being passed to repo preload. When piping, be sure to wrap in parens and you'll avoid these kinds of problems.

**Comment by TigerWolf** [comment]
Thank you.
