### ISSUE TITLE
Question: How much does Phoenix focus on realtime data?

### ISSUE THREAD

**Issue by AdamBrodzinski** [phoenixframework/phoenix#1256]
Hello, i'm looking to switch my stack to Elixir/Phoenix and I can't find a solid answer of where Phoenix is heading. It would be awesome if you could elaborate on what plans Phoenix has for the future.

Ideally i'd like a framework that is realtime sockets 1st and then REST as a backup. Meteor does something similar to that where all data is sent down in realtime and no API endpoints are required. However Meteor is becoming too restrictive when wandering outside the box (and can't scale like Erlang).

After reading the guides my impression was that server-side rendering and REST are a large part of the framework. However it seems like realtime apps are hardly ever serverside (unless it's crippled like Rails) and are almost always native apps or single page JS apps. Most of the tutorials seem to focus on making server rendered pages as well.

From my limited testing it seems like it's currently focused on quickly scaffolding out a Rails like app with static (server rendered) pages, forms, etc...and there isn't much to scaffold out a resource over a channel (however perhaps i'm not doing it right yet!)

At any rate I look forward to using it (and RethinkDB), at the very least i'm going to use it on an upcoming admin dash app :+1: :beers:

**Comment by josevalim** [comment]
Welcome @AdamBrodzinski! Discussions are welcome but the issues tracker is not the place to have them. :) Please move it to the Phoenix mailing list, where more people can participate and contribute to the conversation.
