### ISSUE TITLE
Generate URL safe tokens from Phoenix.Token

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1257]

**Comment by josevalim** [comment]
We should fix this in Plug. :)

**Comment by jeregrine** [comment]
And or maybe add a new fn to URI   



—

**Comment by josevalim** [comment]
Elixir is fine, it has everything we need.  We just need to use url_encode64/url_decode64 in Plug.

**Comment by scrogson** [comment]
Handling this in Plug will break backwards compatibility. I know there are a few people using Plug's crypto stuff to be able to share cookies with Rails apps.

Since the tokens generated from Plug are generally used in cookies, it feels slightly out of place for Plug, IMHO.

**Comment by josevalim** [comment]
We can easily maintain compatibility with Plug by using `Base.url_decode64` and falling back to `Base.decode64`. Any reason why this wouldn't work?

**Comment by scrogson** [comment]
@josevalim ok, that sounds good. :+1:

**Comment by scrogson** [comment]
I'll take care of this in Plug.

**Comment by chrismccord** [comment]
ping @scrogson . how are coming on this one?

**Comment by scrogson** [comment]
PR posted here: https://github.com/elixir-lang/plug/pull/309
