### ISSUE TITLE
Documentation clarification for SSL

### ISSUE THREAD

**Issue by fremontmj** [phoenixframework/phoenix#1258]
In the SSL guide it says:

"If we add the otp_app: key whose value is the name of our application, we can put the key and certificate files in the priv directory of our application, and Plug will look for them there. The values of our environment variables should then be relative paths."

This did not work for me.  

I put the files in the priv directory, and my prod.exs file had (among other things):

 https: [port: 443,
          otp_app: :dieLaughing,
          keyfile: "playfulthinking.key",
          certfile: "playfulthinking.crt"
         ]
This is the error I got:

PORT=4000 MIX_ENV=prod mix phoenix.server                 ✱ ◼
{"Kernel pid terminated",application_controller,"{application_start_failure,dieLaughing,{{shutdown,{failed_to_start_child,'Elixir.DieLaughing.Endpoint',{shutdown,{failed_to_start_child,'Elixir.Phoenix.Endpoint.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<\"could not start Cowboy adapter, the file /Users/michaelfremont/Documents/playthink/code/dieLaughing/_build/prod/lib/dieLaughing/ssl/playfulthinking.key required by SSL's :keyfile does not exist\">>},[{'Elixir.Plug.Adapters.Cowboy',fail,1,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,223}]},{'Elixir.Plug.Adapters.Cowboy',put_ssl_file,3,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,200}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,\"lib/enum.ex\"},{line,1387}]},{'Elixir.Plug.Adapters.Cowboy',normalize_cowboy_options,2,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,144}]},{'Elixir.Plug.Adapters.Cowboy',args,4,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,45}]},{'Elixir.Plug.Adapters.Cowboy',child_spec,4,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,112}]},{'Elixir.Phoenix.Endpoint.CowboyHandler',child_spec,3,[{file,\"lib/phoenix/endpoint/cowboy_handler.ex\"},{line,75}]},{'Elixir.Phoenix.Endpoint.Server',init,1,[{file,\"lib/phoenix/endpoint/server.ex\"},{line,26}]}]}}}}},{'Elixir.DieLaughing',start,[normal,[]]}}}"}

I had to set the relative path to "/priv/<filename>":

 https: [port: 443,
          otp_app: :dieLaughing,
          # documentation claimed the path should be relative to priv, but it's really relative to project root
          keyfile: "priv/playfulthinking.key",
          certfile: "priv/playfulthinking.crt"
         ]

... and then it worked.

I'm using Phoenix 1.0.0.

Thanks!

**Comment by josevalim** [comment]
You are correct. The guides are out of date. Can you please send a pull
request for the guides? Thank you!

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
tracking the issue here. Thanks!
https://github.com/phoenixframework/phoenix_guides/issues/395
