### ISSUE TITLE
Documentation for mix phoenix.new on Hexdocs

### ISSUE THREAD

**Issue by sdn90** [phoenixframework/phoenix#1263]
Was lookin for documentation on `mix phoenix.new` and couldn't find it on Hexdocs. Found the documentation written `installer/lib/phoenix_new.ex` but I think this would be pretty helpful if it was generated with the rest of the documentation.

**Comment by chrismccord** [comment]
Since we don't publish a real `phoenix.new` hex package, we can't push up hex docs for it. I will loop back around to this idea when Elixir gets `mix archive.install hex phoenix`. Thanks!
