### ISSUE TITLE
phoenix.js can't leave() if channel is not joined

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1265]
Easily reproduced by trying to leave on a failed join. The same would happen for leaving on an `onError` callback:

```javascript
// channel onClose callbacks are never triggered and socket membership is not cleaned up
// This is because we wait for the server to ack our leave to avoid races, but 
// we aren't joined.
chan.join().receive("error", reason => chan.leave() )
```

**Comment by chrismccord** [comment]
cc @ericmj

**Comment by josevalim** [comment]
@chrismccord we need to solve this along side the other channel issue and think about a new release.

**Comment by chrismccord** [comment]
Closed in https://github.com/phoenixframework/phoenix/commit/58405d6a490fb32050e7ae111147931462c06761
