### ISSUE TITLE
Tell users to configure their database after mix phoenix.server

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1280]
Today, we tell users after phoenix.install to run `mix ecto.create`. However, often their database is not properly configured which puts them far from the rewards of seeing their phoenix app running. Because we don't need the repo on the home, we should tell users to run Ecto at the end:

```
Before moving on, configure your database in config/dev.exs and run:

    mix ecto.create

```

/cc @napcs

**Comment by doomspork** [comment]
Would you always show this message or first identify whether they had run `mix ecto.create`?  If no one is actively working on this or #1279 I'd love to give them a shot.

**Comment by josevalim** [comment]
@doomspork that info will be shown at the end of phoenix.install, so we would always show it if ecto is being used.

**Comment by doomspork** [comment]
Gotcha, thanks for the quick response @josevalim!
