### ISSUE TITLE
URL helpers aren't properly escaping dynamic segments

### ISSUE THREAD

**Issue by foxnewsnetwork** [phoenixframework/phoenix#1286]
Say I have an `Account` model with an `id` field that is a base64 encoded string. If I run this through the URL helpers generated by the `Phoenix.Router`, it will fail if the base64 string happens to have slashes or pluses in it.

For example: If I have:

```elixir
account = %Account{id: "sPupZ6593LQ16nwMYChvCRqcATwKpqo10KAil7oGV4E="}
path = conn |> account_path(:show, account.id)
conn |> get(path, [])
# Everything is fine, 200

account = %Account{id: "k7mboJUEaF32w66hqN4LP7Y/v5+/R8029Wy7Iu4MUmo="}
path = conn |> account_path(:show, account.id)
conn |> path(path, [])
# 406 error
# The slashes aren't escaped, and the router 406s due to it the request is some weird format
```

Looking through the code:

https://github.com/phoenixframework/phoenix/blob/v1.0.3/lib/phoenix/router/helpers.ex#L175

It seems we just sort drop the segments without escaping them...

Can we get some sort of fix where instead of:
```elixir
defp segments(segments, [], _reserved) do
    segments
end
```
We have something like:
```elixir
defp segments(segments, [], _reserved) do
    encode_uri_component segments
end
```

**Comment by josevalim** [comment]
If you call `URI.encode_www_form` here in those two places

1. https://github.com/phoenixframework/phoenix/blob/v1.0.3/lib/phoenix/router/helpers.ex#L173
2. https://github.com/phoenixframework/phoenix/blob/v1.0.3/lib/phoenix/router/helpers.ex#L170

We should be good to go? can you please try a patch with tests? Thank you!

**Comment by foxnewsnetwork** [comment]
okay, understood
