### ISSUE TITLE
How to reload the server in production.

### ISSUE THREAD

**Issue by blisscs** [phoenixframework/phoenix#1288]
From the phoenix guide we use following command to boot up the server phoenix in production.

``` MIX_ENV=prod PORT=4001 elixir --detached -S mix do compile, phoenix.server ```

The question is  - if I use git post-receive hook to extract and replace updated files in the project folder. How can I reload it.
Or
Another way around is it possible write a process id of the server to a file and I will use the os kill command to kill that process and then I use the above command line code to boot the server agains.

Thanks.

**Comment by chrismccord** [comment]
I'll loop back around to the --detached state recommendation in the guides, but this is beyond the cope for the phoenix repo. You might also have luck on the mailing list, but there are numerous deploy options and post-receive hook may or may not be the best option or require special setup outside the scope of the guides.

**Comment by gjaldon** [comment]
@blisscs to reload phoenix.server, you can kill the process listening on port 4001 and then run phoenix.server again. In linux, you can find the pid of the process running on a specific port by doing `lsof -i:4001`. This returns the pid of your phoenix app running in port 4001. Then you can use `kill` to stop it.

**Comment by blisscs** [comment]
Thank you @chrismccord. and @gjaldon I tried using the lsof -i:4001 to see the PID and then kill it and run the main command again. it works as intended now I am trying to automate it and make it a script.
Thank you very much.
Dev.

**Comment by blisscs** [comment]
I found the solution from https://github.com/phoenixframework/phoenix/issues/1041 by @josevalim  which is to use the following command.

```elixir --detached -e "File.write! 'pid', :os.getpid" -S mix phoenix.server ```

And to use
```kill `cat pid` ```

to kill it and then reload it again. 

I have tried and it works fine. Do you think they can drawbacks by using this method with git-hook if yes please let's me know.

Thank you 
Dev.

**Comment by PeterDavidCarter** [comment]
With nginx, apache etc you can do this with a simple `systemctl restart` command. Should it be necessary to manually kill the server process every time? This seems like a bit of a hassle for production servers that are likely to be reloaded often. Particularly those sitting behind an nginx proxy anyway, where form many web applications the performance benefits of Cowboy might be less obviously (which would mitigate the hassle).

**Comment by PeterDavidCarter** [comment]
With nginx, apache etc you can do this with a simple `systemctl restart` command. Should it be necessary to manually kill the server process every time? This seems like a bit of a hassle for production servers that are likely to be reloaded often. Particularly those sitting behind an nginx proxy anyway, where form many web applications the performance benefits of Cowboy might be less obvious (which would mitigate the hassle).

**Comment by PeterDavidCarter** [comment]
With nginx, apache etc you can do this with a simple systemctl restart command. Should it be necessary to manually kill the server process every time? This seems like a bit of a hassle for production servers that are likely to be reloaded often. Particularly those sitting behind an nginx proxy anyway, where for many web applications the performance benefits of Cowboy might be less obviously (which would mitigate the hassle).

**Comment by PeterDavidCarter** [comment]
With nginx, apache etc you can do this with a simple systemctl restart command. Should it be necessary to manually kill the server process every time? This seems like a bit of a hassle for production servers that are likely to be reloaded often. Particularly those sitting behind an nginx proxy anyway, where for many web applications the performance benefits of Cowboy might be less obvious (performance benefit would mitigate the hassle).

**Comment by PeterDavidCarter** [comment]
For anyone who's finding this annoying, you can use `fuser -k 4000/tcp` to very quickly kill the process before reloading. If you're Phoenix process is running on another port, obvs just substitute 4000 for your Phoenix serving port. 🍨 💛

**Comment by PeterDavidCarter** [comment]
For anyone who's finding this annoying, you can use fuser -k 4000/tcp to very quickly kill the process before reloading. If your Phoenix process is running on another port, obvs just substitute 4000 for your Phoenix serving port. 🍨 💛

**Comment by PeterDavidCarter** [comment]
For anyone who's finding this annoying, you can use `fuser -k 4000/tcp` to very quickly kill the process before reloading. If your Phoenix process is running on another port, obvs just substitute 4000 for your Phoenix serving port. 🍨 💛
