### ISSUE TITLE
phoenix.js clear channel pushBuffer on join; race condition

### ISSUE THREAD

**Issue by zmoshansky** [phoenixframework/phoenix#1295]
There is a race if you try to open a channel and send a push immediately. The messages get buffered but never sent as the channel connects on the first attempt (doesn't trigger `rejoin()`).

Easy fix is to flush the push buffer on join.
```
    this.joinPush.receive("ok", () => {
      this.state = CHANNEL_STATES.joined
      this.rejoinTimer.reset()
      this.pushBuffer.forEach( pushEvent => pushEvent.send() )
      this.pushBuffer = []
    })
```
Related: #1241

**Comment by chrismccord** [comment]
Can you describe the potential race with some sample code?

**Comment by zmoshansky** [comment]
```
let channel = this.socket.channel(type + ":" + id, {});
    channel.join()
      .receive("ok", resp => { console.log("Joined successfully", resp) })
      .receive("error", resp => { console.log("Unable to join", resp) });
channel.push("msg", body)
```

Which in my codebase is done via a call like:

```
this._getOrOpenChannel('user', account.id).push("msg", body));
```
`this._getOrOpenChannel('user', account.id)` returns the channel in question, or opens it and then returns it.

**Comment by chrismccord** [comment]
This is expected as can't push anything to the server until you've joined successfully. I'm not sure if we should queue indefinitely for these cases as you'll want to have your UI control whether or not events are pushed to the server based on the status of the join

**Comment by chrismccord** [comment]
For example, your code above assumes the join was successful, which won't always be the case

**Comment by zmoshansky** [comment]
Of course, my server would never be down ;) However, this is done in the rejoin case. So if for some reason this call failed the first time it would succeed in that instance which is odd behaviour.

One could do the following, but it seems inconsistent with the existing behaviour of rejoin.

```
channel.join()
      .receive("ok", resp => { channel.pushBuffer.forEach( pushEvent => pushEvent.send() )
      channel.pushBuffer = [] })
      .receive("error", resp => { clear_queue });
```

**Comment by zmoshansky** [comment]
As it stands, I think the current behaviour may still be a bug as it seems to eat my messages and never alert me of that fact. *ie. queing them instead of returning an error, then never clearing the queue.

**Comment by jerel** [comment]
How about this?

``` js
getChannel(socket, user, id) {
  return new Promise((resolve, reject) => {
    let channel = socket.channel(`${user}:${id}`);
    channel.join()
      .receive("ok", msg => resolve({channel, payload: msg.payload})
      .receive("error", reject)
  });
}
```
Should allow you to handle success or failure elegantly in your UI or code:
``` js
getChannel(socket, 'bob', 1).then(({channel, payload}) => {
  console.log("joined with", payload);
  channel.push("msg", "the body");
}).catch(error => {
  console.log('Error joining:', error);
})
```
It seems easier to reason about rather than firing messages into a channel and trusting it to connect eventually. However if messages are silently dropped then that does seem like unwanted behavior.

**Comment by josevalim** [comment]
@chrismccord given the plan is to queue until we reach a timeout... for rejoins... it probably makes sense to treat first joins the same way, no? Less cases to consider in the code?

**Comment by zmoshansky** [comment]
@jerel Thanks, The use of promises would definitely help improve the API. I'd omitted the error handling code for brevity, but I like the promise based approach enough that I may sorta like:

```

openChannel(socket, type, id) {
  return new Promise((resolve, reject) => {
    let channel = socket.channel(`${type}:${id}`)
    channel.join()
      .receive("ok", msg => resolve({channel, payload: msg.payload})
      .receive("error", reject)
  })
  .then(({channel, payload}) => {
    console.log("joined with", payload)
  }).catch(error => {
    console.log('Error joining:', error)
  })
}

getChannel(socket, type, id) {
  // Check for existing channel
  this.openChannel(socket, type, id)
}

someFunc(socket, type, id) {
  getChannel(socket, 'bob', 1).then(({channel, payload}) => {
    channel.push("msg", "the body")
  }).catch(error => {
    console.log('Error sending:', "msg", "the body");
  })
}

**Comment by chrismccord** [comment]
This is fixed in master
