### ISSUE TITLE
mix test fails on new project

### ISSUE THREAD

**Issue by sbrother** [phoenixframework/phoenix#1298]
See [StackOverflow question](http://stackoverflow.com/questions/33181775/phoenix-framework-mix-test-fails-with-argumenterror-on-new-app). `mix test` fails with the error

    ** (ArgumentError) argument error
    :erlang.exit(nil, :normal)
    (ecto) lib/ecto/adapters/postgres.ex:55: Ecto.Adapters.Postgres.stop/2
    (ecto) lib/mix/ecto.ex:75: Mix.Ecto.ensure_stopped/2
    test/test_helper.exs:3: (file)
    (elixir) lib/code.ex:363: Code.require_file/2

on new apps generated with `mix phoenix.new`. The issue can be resolved by adding `{:ecto, "== 1.0.4"}` to `mix.exs`, so it seems to be related to ecto 1.0.5.

**Comment by ericmj** [comment]
This is an ecto bug, please reopen on https://github.com/elixir-lang/ecto.
