### ISSUE TITLE
Mix.Tasks.Phoenix.New absent from documentation

### ISSUE THREAD

**Issue by jlecour** [phoenixframework/phoenix#1300]
Hi,

I might be missing something, but I can't find the documentation for `Mix.Tasks.Phoenix.New` in http://hexdocs.pm/phoenix/

I'm quite new to the Elixir ecosystem, so I don't know where to start to help on this, but I'd be glad if there is anything I can help fix (if needed).

Thanks

**Comment by josevalim** [comment]
Welcome @jlecour! Thanks for the report.

It is because it is not really part of Phoenix. Currently you can see the info for any task with `mix help phoenix.new`, in future releases, `mix phoenix.new` only will also show the help. :)
