### ISSUE TITLE
Bug in ecto 1.05 as mix test fails for any new app.

### ISSUE THREAD

**Issue by hail2skins** [phoenixframework/phoenix#1302]
http://stackoverflow.com/questions/33181775/phoenix-framework-mix-test-fails-with-argumenterror-on-new-app

I opened that on Stackoverflow and someone there told me how to fix it.   But I figure you guys might care.   By putting ecto version 1.04 in my mix file, everything works as anticipated.   I do not know if the guy there is right about it being a bug, but I know what he told me to do fixed it and he seems to know more than me, so, hope this helps you guys as this is a GREAT project.

**Comment by chrismccord** [comment]
Thanks! It's a bug on the Ecto side that is fixed in master
