### ISSUE TITLE
Generating API  causes Unchecked dependencies for environment dev

### ISSUE THREAD

**Issue by conradwt** [phoenixframework/phoenix#1307]
I'm getting an error message when attempting to generate an API using Elixir 1.2-dev and Phoenix 1.0.3.  Thus, I performed the following steps:

* create the application

```elixir
$ mix phoenix.new testapp
* creating testapp/config/config.exs 
* creating testapp/config/dev.exs
* creating testapp/config/prod.exs
* creating testapp/config/prod.secret.exs
* creating testapp/config/test.exs
* creating testapp/lib/testapp.ex
* creating testapp/lib/testapp/endpoint.ex
* creating testapp/test/views/error_view_test.exs
* creating testapp/test/support/conn_case.ex
* creating testapp/test/support/channel_case.ex
* creating testapp/test/test_helper.exs
* creating testapp/web/channels/user_socket.ex
* creating testapp/web/router.ex
* creating testapp/web/views/error_view.ex
* creating testapp/web/web.ex
* creating testapp/mix.exs
* creating testapp/README.md
* creating testapp/lib/testapp/repo.ex
* creating testapp/test/support/model_case.ex
* creating testapp/priv/repo/seeds.exs
* creating testapp/.gitignore
* creating testapp/brunch-config.js
* creating testapp/package.json
* creating testapp/web/static/css/app.css
* creating testapp/web/static/js/app.js
* creating testapp/web/static/js/socket.js
* creating testapp/web/static/assets/robots.txt
* creating testapp/web/static/assets/images/phoenix.png
* creating testapp/web/static/assets/favicon.ico
* creating testapp/test/controllers/page_controller_test.exs
* creating testapp/test/views/layout_view_test.exs
* creating testapp/test/views/page_view_test.exs
* creating testapp/web/controllers/page_controller.ex
* creating testapp/web/templates/layout/app.html.eex
* creating testapp/web/templates/page/index.html.eex
* creating testapp/web/views/layout_view.ex
* creating testapp/web/views/page_view.ex

Fetch and install dependencies? [Yn] Y
* running npm install && node node_modules/brunch/bin/brunch build
* running mix deps.get

We are all set! Run your Phoenix application:

    $ cd testapp
    $ mix ecto.create
    $ mix phoenix.server

You can also run your app inside IEx (Interactive Elixir) as:

    $ iex -S mix phoenix.server
```

* change to the application directory

```elixir
$ cd testapp
```

* create the API

```elixir
$ mix phoenix.gen.json User users name:string age:integer
Unchecked dependencies for environment dev:
* phoenix_live_reload (Hex package)
  the dependency is not available, run "mix deps.get"
* cowboy (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix_html (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix (Hex package)
  the dependency is not available, run "mix deps.get"
* postgrex (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix_ecto (Hex package)
  the dependency is not available, run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies
```

**Comment by conradwt** [comment]
OK, it seems that Hex was corrupted.  Also, the following command doesn't appear to have been ran because I would get "Unchecked dependencies for environment dev":

```eliir
* running mix deps.get
```

Thus, I'm somewhat confused as to the goal "Fetch and install dependencies? [Yn] Y" during the application creation process.  It appears to do something because it took almost ~32 seconds to get back to the Unix prompt.  It would be nice if there was some type of progress indicator or standard out of the actions being performed when one agrees to fetch and install dependencies.  Finally, I had to explicitly type "mix deps.get" to get the dependencies to download and install.

**Comment by josevalim** [comment]
It works fine here. If you have a corrupted version of Hex though, then it would explain why things did not work for you.

Also, when you run "fetch and install dependencies", we are fetching both npm and elixir dependencies in parallel and the slowest one, by far, is the npm ones and there isn't much we can do to improve the visiblity on that side of things.

Let us know if "mix deps.get" still doesn't work after you fixed Hex and if so, please provide Mix and Phoenix version, (mix --version and mix phoenix.new --version). Thank you!

**Comment by conradwt** [comment]
@josevalim I was able to get things to work with Elixir 1.1.1 but now with Elixir 1.2-dev.  I'm using using the following versions:

```elixir
$ mix --version
Mix 1.2.0-dev

$ mix phoenix.new --version
Phoenix v1.0.3
```

**Comment by conradwt** [comment]
It appears to be working now.  If Phoenix depends on Hex for downloading modules from their respective repositories, would it be a good idea to simply include Hex as part of the Phoenix installation process?

**Comment by josevalim** [comment]
@conradwt Why are you using a development version of Elixir? it may have bugs and there is no guarantee Phoenix supports it already. There is no guarantee even Hex works. :)

Also, Hex is always automatically installed every time you need it, so there is no need to worry about shipping it with Phoenix.
