### ISSUE TITLE
Some thoughts now when I generated my first phoenix project

### ISSUE THREAD

**Issue by phenomen2277** [phoenixframework/phoenix#1308]
The first thing I had to do is to google "how to remove the bootstrap" boilerplate. I also want to see "clean" files in /js and /css folders. By clean, I mean that they boilerplate code should be moved somewhere else and bootstrapped from their instead...

I think choosing sqlite as a standard dbms in development would be better. 

Otherwise!
You are doing a great job ppl!

**Comment by chrismccord** [comment]
Removing bootstrap is selecting all in app.css and hitting backspace :)

What is not clean about the current approach?

Postgres remains the best default in my

**Comment by bryansray** [comment]
> The first thing I had to do is to google "how to remove the bootstrap" boilerplate

Which "bootstrap" boilerplate are you referring to? Sorry, the first thing that comes to my mind here, BootstrapCSS; which I don't believe comes in Phoenix?

> I also want to see "clean" files in /js and /css folders.

Do you mean like a "mix clean" task that clears out those directories? Or you literally want those directories to start out clean?

> Postgres remains the best default in my

I've always been a fan of postgres. phoenix.new does allow you to pass in the ecto adapter doesn't it?

**Comment by phenomen2277** [comment]
app.css does contain bootstrap 3.x classes. I link my css's using CDN. In my first project i thought of using boostrap 4.alpha using CDN. The problem is that you do not know if the app.js contain the boostrap components, those which require .js files. Unless you go through the app.js and see for yourself.

**Comment by chrismccord** [comment]
Sorry I meant to finish my comment earlier. We appreciate feedback, but please use the mailing list for input like this. I think our current approach is a great starting point for new applications. Thanks!

**Comment by phenomen2277** [comment]
@chrismccord It is just thoughts man.
