### ISSUE TITLE
Phoenix reports wrong port during startup on port 0

### ISSUE THREAD

**Issue by Kavec** [phoenixframework/phoenix#1314]
When configuring Phoenix to run Cowboy via port 0, Cowboy correctly receives an ephemeral port from the OS and starts listening on it, but Phoenix reports it's running on port 0 instead of the ephemeral port the http server is listening for new connections on. This requires using command-line tools like `lsof` to hunt down the actual port number.

The error occurs because [CowboyHandler.info/3](https://github.com/phoenixframework/phoenix/blob/6d0dbb3/lib/phoenix/endpoint/cowboy_handler.ex#L100-L104) pulls the port number directly from the configuration (which usually works as expected, port 0 is a bit of an edge case). 

*Something* needs to be asked what port Cowboy is listening on; I've only had a week and a half's worth of Elixir buddying and haven't quite made my way far enough through learning the Phoenix/Cowboy/Elixir/Erlang/OTP ecosystem to make the least intrusive change and submit a PR. :/

**Comment by chrismccord** [comment]
I'd like to see if there's something we can do here that isn't couple'd directly to cowboy. I don't think there's anything in plug that exposes this at the moment. This is up for grabs if someone wants to take a look

**Comment by druzn3k** [comment]
@chrismccord I could try, but I cannot guarantee success (I'm still newbie). If the premise it's ok for you, I will take a look. :+1:

**Comment by dm1try** [comment]
seems [`:ranch.get_port/1` can help](https://github.com/ninenines/cowboy/blob/27ecd7fca1c9111a09beb42ffe7efea0c317fd45/test/cowboy_test.erl#L24)

**Comment by dm1try** [comment]
just checked it:
```elixir
if config[:port] == 0 do
  ref = hd(a)
  ephemeral_port = :ranch.get_port(ref)
  "#{info(scheme, endpoint, config)} (ephemeral port #{ephemeral_port})"
else
  info(scheme, endpoint, config)
end
```
[info] Running Testapp.Endpoint with Cowboy on http://localhost:0 (ephemeral port 45994)
```

**Comment by chrismccord** [comment]
Awesome. We need to expose this at the plug level so it can be adapter independent. Thanks for doing the leg work!

**Comment by dm1try** [comment]
Sure, I didn't know about such thing like an ephemeral port until now, so the "work" was informative :)

I haven't enough time for the implementation, so if anyone want to help - just do it!

**Comment by scrogson** [comment]
I'll take a look into getting this into Plug.

**Comment by chrismccord** [comment]
@scrogson ping. Are you still planning to tackle this one?

**Comment by scrogson** [comment]
@chrismccord I took a look into it, but I can't seem to figure out how to expose this in Plug. Maybe I could pair up with you or @josevalim?

**Comment by josevalim** [comment]
Closing in favor of the PR.
