### ISSUE TITLE
Question about timing during Phoenix.Token.sign

### ISSUE THREAD

**Issue by ianwalter** [phoenixframework/phoenix#1316]
I'm using Phoenix.Token to generate unique keys. Some of my tests generate a token and then regenerate a token and make sure that the first token was deleted from the store. These tests are failing occasionally because they are running so quickly that the first token and second token are the same (i.e. under a millisecond).

Would it be fair to propose that tokens get signed with the time in microseconds or should I just add a 1ms wait time in between generating the first token and regenerating the second?

**Comment by chrismccord** [comment]
Can you hold a reference to the first token and use that in your test? It doesn't sound like there is a need to regenerate it if you already know the value? I think ms is fine, and we'd technically have races at microseconds, but much less aggravated. :)

**Comment by ianwalter** [comment]
Yes, I'm holding a reference to the first token and then creating a new token by calling a `regenerate` function. The reason for the `regenerate` function is to delete the first token and create a new unique token. The test then checks if the first token has been deleted, but fails when the new token is the same as the old token because it thinks it hasn't been deleted. So adding `:timer.sleep(1)` inbetween `generate` and `regenerate` fixes the problem because now the keys are unique. I was just wondering if I could avoid the `sleep` but it sounds like it's the best solution. Thanks for your help Chris.

**Comment by josevalim** [comment]
If you need to sleep 1 millisecond you will be alright. :D
