### ISSUE TITLE
ability to reload phoenix web server 

### ISSUE THREAD

**Issue by 0xAX** [phoenixframework/phoenix#1318]
Hello,

I'm searching for ability to reload phoenix release without stopping. I'm integrating [exrm_reload] (https://github.com/xerions/exrm_reload) for this point.

What I need to restart cowboy web server? I have config something like this:

```elixir
{http,[{ip,{0,0,0,0}},{port,<<"4000">>}]},
```

Now I can change port in the release config and catch it in the code. How can i restart web server now on the new port? I've tried to call the:

```elixir
MyApp.Endpoint.config_change(changed, removed)
```

which just calls the `Phoenix.Endpoint.config_change/2` as I understand correctly. But after the call of the `MyApp.Endpoint.config_change`/2
I see that cowboy isn't restarted and I can access my web application only via the old port.

Thank you

**Comment by josevalim** [comment]
Can you please use the mailing list for questions? A lot more folks will be able to help there.
