### ISSUE TITLE
link helper with delete method does not work on windows

### ISSUE THREAD

**Issue by torrick** [phoenixframework/phoenix#1319]
OS: Windows 7 x64
Elixir: 1.1.1
Phoenix: 1.0.3
Node: 4.1.2
Browser: Chrome 46.0.2490.80

Steps to reproduce:
* `mix phoenix.new blog`
* `mix phoenix.gen.html Post posts title:string body:string
* `mix ecto.create` and `mix ecto.migrate`
* `mix phoenix.server`
* Create a couple posts
* Navigate to localhost:4000/posts
* Click on the delete link

Expected: Confirmation dialog shows and when confirmed the post is deleted
Actual: No dialog is presented, no error in the console.  

I've tested this on two different windows 7 x64 boxes and received the same result each time.  I tested on a macbook air and it worked as expected so I'm stumped.  

Interestingly when I run `require("deps/phoenix_html/web/static/js/phoenix_html");` in the console after the page loads the delete links work properly.

**Comment by josevalim** [comment]
That's so weird. Can you get the compiled .js file from priv/static from both versions and compare them?

**Comment by chrismccord** [comment]
The `autoRequire` feature is new in brunch, so please include the brunch version listed in package.json

**Comment by chrismccord** [comment]
We had another report of this issue from another windows user. His autoRequire wast not being included. `require("web/static/js/app")` was missing from the bottom of app.js, so I think this issue is actually worse than described, because *all* application js won't be executed. I'm trying to isolate, but node and brunch versions all appear fine. The autoRequire code in brunch's source also seems fine, so I'm not quite sure what is going on. // @paulmillr

**Comment by torrick** [comment]
@chrismccord I can confirm that seems to be my issue as well.  The windows version of the compiled app.js is missing the `require("web/static/js/app")` line but the mac version includes it.  For the record I'm on brunch 1.8.5. 

Let me know if I can provide any additional information to help track this down.

**Comment by chrismccord** [comment]
You can track the issue https://github.com/brunch/brunch/issues/1035

An interim fix for windows users is to change your autoRequire config in brunch-config.js to use a backslash path:

```javascript
 modules: {
    autoRequire: {
      "js\app.js": ["web/static/js/app"]
    }
  }, 
```

**Comment by torrick** [comment]
Confirmed my links are working with the fix.  A slight modification was needed though: 

```
 modules: {
    autoRequire: {
      "js\\app.js": ["web/static/js/app"]
    }
  }, 
```

The only caveat is the confirmation doesn't seem to work now.  Either way this is a suitable workaround for me until it gets fixed.

**Comment by josevalim** [comment]
OH! We need to fix this on the brunch side then!

**Comment by chrismccord** [comment]
For now I added both joinKeys to support all platform to brunch-config. Brunch is prepping a major version release, so it may be a bit before the fix lands.
