### ISSUE TITLE
POST request results 400 status

### ISSUE THREAD

**Issue by dmitrytrager** [phoenixframework/phoenix#1320]
My app is based on generated code mostly. The deps are:
```
defp deps do
    [{:phoenix, "~> 1.0.3"},
     {:phoenix_ecto, "~> 1.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:basic_auth, "~> 1.0.0"}]
  end
```
There are some code pieces.
Router:
```
scope "/", FsDev do
    pipe_through :browser # Use the default browser stack

    resources "notes", NoteController, only: [:create, :show]
    resources "tags", TagController, only: [:index, :show] do
      resources "notes", NoteController, only: [:index]
    end
    get "/", TagController, :index
  end
```
Controller:
```
defmodule FsDev.NoteController do
  use FsDev.Web, :controller

  alias FsDev.Note
  alias FsDev.Tag
  alias FsDev.NoteTag

  plug :find_tag when action in [:index]
  plug :prepare_tags when action in [:create]
  plug :scrub_params, "note" when action in [:create]

  def create(conn, %{"note" => note_params}) do
    changeset = Note.changeset(%Note{}, note_params)

    case Repo.insert(changeset) do
      {:ok, note} ->
```
Model:
```
defmodule FsDev.Note do
  use FsDev.Web, :model

  alias FsDev.Tag
  alias FsDev.NoteTag

  schema "notes" do
    field :title, :string
    field :url, :string

    has_many :note_tags, FsDev.NoteTag
    has_many :tags, through: [:note_tags, :tag]

    timestamps
  end

  @required_fields ~w(title url)
  @optional_fields ~w()
```

When I try to submit a form with new note details I can see '/notes' in browser address string and empty page. No errors, no debug data in console. I just see in browser debug console that response status is 400 (bad request), but unable to understand why. Is this a bug? What could be the reason? Is it Phoenix itself or maybe Cowboy?

Mac OS 10.11, Elixir 1.1.1, Erlang 18.1

**Comment by chrismccord** [comment]
Check the params in the console logs that you are sending up:

```elixir
 def create(conn, %{"note" => note_params})
```

We 400 when you are matching on params, but no clause matches. It sound like you are not sending a "note" map up.

**Comment by dmitrytrager** [comment]
@chrismccord I can have another version of create method:
```
  def create(conn, _params) do
    Logger.debug "create"
  end
```
But this does not change anything. No log messages, no entities in console. And result is 400.

**Comment by josevalim** [comment]
@dmitrytrager can you post your stacktrace and logs from terminal?

**Comment by dmitrytrager** [comment]
@josevalim these are the logs:
```
Compiled web/controllers/note_controller.ex
Generated fs_dev app
[info] Running FsDev.Endpoint with Cowboy on http://localhost:4000
29 Oct 12:50:31 - info: compiled 5 files into 2 files, copied 3 in 1905ms
[info] GET /
[debug] Processing by FsDev.TagController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] SELECT t0."id", t0."name", t0."ref_count", t0."inserted_at", t0."updated_at" FROM "tags" AS t0 [] OK query=162.4ms queue=4.9ms
[info] Sent 200 in 264ms
```
Is is not updated after form submit, get request results only.

**Comment by dmitrytrager** [comment]
The is no exception in explicit form. Not sure how to get stacktrace.

**Comment by josevalim** [comment]
I am confused, it says 200 in the logs?

**Comment by dmitrytrager** [comment]
@josevalim I think 200 is a result of previous query, that rendered form for me.

**Comment by josevalim** [comment]
So nothing is logged when you get the 400? Can you publish a sample
application that reproduces the issue?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by dmitrytrager** [comment]
@josevalim https://github.com/dmitrytrager/fs-dev-notes please

**Comment by josevalim** [comment]
I cannot reproduce the error. I am trying to create a note, for example, and it fails on this line: https://github.com/dmitrytrager/fs-dev-notes/blob/master/web/controllers/note_controller.ex#L88

That's because parameters are always sent inside `conn.params["note"]["tag_list"]`. I would recommend you to clean up your controller in order to pin point the issue.

**Comment by dmitrytrager** [comment]
Thanks @josevalim. I will try to do it

**Comment by dmitrytrager** [comment]
I tried different env. And it worked. I mean I was able to see error in browser and console. But my macbook still hides all exceptions leading to 400 status from me.

**Comment by desmondmonster** [comment]
@dmitrytrager I'm having a similar issue.  How did you resolve this?

**Comment by josevalim** [comment]
@desmondmonster do you have a stacktrace?

**Comment by josevalim** [comment]
@desmondmonster also, please try cleaning up your cookies for the host you are accessing. I am wondering if one of Cowboy's security mechanisms, like limiting the header size, is kicking in. This would happen if you have large cookies.

**Comment by desmondmonster** [comment]
@josevalim There's no stack trace - I submit the form via Chrome, then see a blank page.  Phoenix logs show no request at all, nothing.  Chrome logs indicate Cowboy's returned a 400.

**That said** clearing my cookies on localhost solved the problem.  thanks!
