### ISSUE TITLE
Rollback npm scripts

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1322]
#1270 and #1273 need to be rolled back as they are causing issues for some windows users.

**Comment by josevalim** [comment]
Done!

**Comment by mareksuscak** [comment]
Guys, do you happen to remember what was the issue with those two PRs? I'd love to take another look at it and fix it.

**Comment by josevalim** [comment]
@mareksuscak we still ship with the scripts but we don't use them by default in your config/dev.exs because they were not working on some Windows machines.

**Comment by mareksuscak** [comment]
@josevalim Yup I know. I actually read [your comment](https://github.com/phoenixframework/phoenix/issues/1540#issuecomment-182781673) but there are no further details which I'm interested in. I could possibly help you guys debug and fix the issue so that we can have a truly easy to change asset pipeline.

**Comment by mareksuscak** [comment]
Any chance it's been [this eaccess error](https://github.com/phoenixframework/phoenix/issues/684) related to the lack of shebang support on Windows?

**Comment by chrismccord** [comment]
No idea. If someone would let to debug widows support for npm scripts we'd accept a PR that was sure to work. As is today, running without npm scripts in package.json works across all platforms so it's not a huge priority for us to track this issue down.

**Comment by josevalim** [comment]
To add to that, the flip to and from npm scripts is literally a one line of code change. So if someone can track it down and guarantee it works on Windows, that's great, but indeed low priority on our side.

**Comment by mareksuscak** [comment]
Sure, I understand. I have extensive experience with Node and JavaScript and do have access to a dev Windows machine. I am willing to put in some time to debug the issue and contribute to Phoenix as I think it's a great project (and so is Elixir!). I just need some clue to start with. I'll start with this eaccess error then.

Huge thanks for everything you guys do for the open source world BTW.
