### ISSUE TITLE
Unknown type `unique` given to generator

### ISSUE THREAD

**Issue by bigbassroller** [phoenixframework/phoenix#1326]
Hello,

Thanks for the awesome Phoenix project.

I am trying to use the `unique` type key to use for authenticating unique email addresses. I am running phoenix v1.0.3.

When running this example from `https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phoenix.gen.model.ex` line 46:
 `mix phoenix.gen.model Post posts title:unique unique_int:integer:unique`

I get this error:
 `** (Mix) Unknown type `unique` given to generator`

It should be available, according to `https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phoenix.gen.model.ex` line 46. 

But if I go to my local copy of Phoenix, `/deps/phoenix/lib/mix/tasks/phoenix.gen.model.ex` there is no mention of the `unique` key. 

What is up with that? 

Cheers,
Mike

**Comment by Gazler** [comment]
This was added in this commit: https://github.com/phoenixframework/phoenix/commit/5f230cf52a5f601e4a1cd35dbb6a2d8ba8082728

So I don't think it is available unless you are using the master branch.

**Comment by Gazler** [comment]
This was added in this commit: https://github.com/phoenixframework/phoenix/commit/8758c5b846f0ddc34ac96221ee872f3c08457fb4

It will only be available if you are using the master branch of phoenix.

**Comment by josevalim** [comment]
@Gazler is right. :)

**Comment by bigbassroller** [comment]
Thanks for the reply. I got it working now, thanks to the documentation "Running a Phoenix master project".

First I had to delete the phoenix.new thing inside /Users/yourusername/.mix/archives
and then git clone https://github.com/phoenixframework/phoenix and cd into that directory and into the installer folder
then create the project with the --dev flag inside of there:
`mix phoenix.new projectname --dev`
.. follow the install steps.
 `mix phoenix.gen.model User users email:unique crypted_password`
then works :)

**Comment by Immortalin** [comment]
@josevalim when will the be released?

**Comment by ericmj** [comment]
@Immortalin Yes.

**Comment by nacengineer** [comment]
FWIW all you have to do to run from master is change the source of phoenix  in mix.exs

```
{:phoenix, "~> 1.0.4"}
```

becomes 
```
{:phoenix, git: "https://github.com/phoenixframework/phoenix.git", tag: "master"}
```
not you may have mix dependency errors use mix help deps or add override: true if you're feeling lucky

```
{:phoenix, git: "https://github.com/phoenixframework/phoenix.git", tag: "master", override: true}
```

then run 

```
mix do deps.get, compile
```

**Comment by Immortalin** [comment]
@nacengineer thanks!

**Comment by acrolink** [comment]
Is it possible using `mix phoenix.gen.model ..` to specify a composite unique key? i.e I need a unique key based on values of two fields together. Thanks.

**Comment by josevalim** [comment]
@acrolink then you should rather change the generated migration. There is a certain limit of expressivity we can add to the command line instruction. However, the migration is code, and there you will have much more flexibility.

**Comment by acrolink** [comment]
@josevalim I guess I can skip the migration file and define the keys on the postgres shell? Correct?

**Comment by josevalim** [comment]
If you define on the shell, who is going to guarantee you will remember to do that in production or that you and your co-workers will remember to the same on your machines in development? The migration is the way to go, change the file, just don't do so through the command line.
