### ISSUE TITLE
 Phoenix.Socket.Transport check_origin with invalid URI from client - Cordova

### ISSUE THREAD

**Issue by zmoshansky** [phoenixframework/phoenix#1328]
#### Problem 
On mobile clients like Cordova (turns html app into hybrid app), it sends an origin of `file://`. This is troublesome as one cannot whitelist `file://` since it is parsed with URI.parse.

#### Origin Validity
I'm not sure about whether `file://` is actually a valid origin according to [ietf rfc 6454](https://tools.ietf.org/html/rfc6454#section-7.3). I think this implies that it is valid.
```
 If uri-scheme is "file", the implementation MAY return an
       implementation-defined value.

          NOTE: Historically, user agents have granted content from the
          file scheme a tremendous amount of privilege.  However,
          granting all local files such wide privileges can lead to
          privilege escalation attacks.  Some user agents have had
          success granting local files directory-based privileges, but
          this approach has not been widely adopted.  Other user agents
          use globally unique identifiers for each file URI, which is
          the most secure option.

```

#### Potential Solutions
 - Allow `check_origin: ["https://example.com", "file://"]`
  - Doesn't currently work due to URI.parse; although the origin may not have to be a URI depending on interpretation of RFC 6454.
 - Treat invalid origins (not parse-able with URI.parse) the same as nil
 - Do nothing :(

#### Alternative Solutions
 - Unfortunately it doesn't seem like it's possible to specify the origin header when building with Cordova. 
 - `check_origin: false`

**Comment by chrismccord** [comment]
Why does cordova send an origin at all? Is it configurable?

**Comment by zmoshansky** [comment]
I have no clue why they would send it. I've searched for a couple hours for a solution and can't seem to find a way to set the origin header. 

My best guess is that it just uses the behaviour of chromium; where it makes sense that it wouldn't be modifiable.

**Comment by zmoshansky** [comment]
https://chromium.googlesource.com/chromium/src/+/master/url/origin.h#53

**Comment by chrismccord** [comment]
Does `check_origin: false` work as a workaround for you today, or do you still get 403'd?

**Comment by zmoshansky** [comment]
`check_origin: false` does work as a workaround. As noted above, not ideal long term since browser clients can't take advantage of the protection.

**Comment by chrismccord** [comment]
I agree. We're going to treat invalid URI's as nil.
