### ISSUE TITLE
Access is not a protocol, cannot derive Access for Phoenix.Socket -- any guidance?

### ISSUE THREAD

**Issue by bob-hinrichs** [phoenixframework/phoenix#1330]
Hello,
I'm wondering if there might be some guidance out there.  I am a complete noob with Elixir and Phoenix, sorry about that.

Just followed instructions linked to install Elixir via Homebrew.  v1.1.1 was installed on my El Capitan OS.
During phoenix install, received this warning:
warning: the dependency :poison requires Elixir "~> 1.0.0" but you are running on v1.1.1

Otherwise looked relatively smooth.

Phoenix compilation fails with this error:

== Compilation error on file lib/phoenix/socket.ex ==
** (ArgumentError) Access is not a protocol, cannot derive Access for Phoenix.Socket
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    (elixir) lib/protocol.ex:591: Protocol.derive/5
    (stdlib) lists.erl:1337: :lists.foreach/2
    (elixir) lib/protocol.ex:579: Protocol.__derive__/3
    lib/phoenix/socket.ex:24: (module)

I notice that Elixir v1.0.2+ is required as per the Phoenix docs, but figure I'd grab the latest due to that '+'.

**Comment by josevalim** [comment]
You are using a very old Phoenix version. Update it or update the Phoenix
installer according to Phoenix website.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by bob-hinrichs** [comment]
Thank you very much for your prompt answer. Somehow a google search had led me to the documentation for the old version.  I notice some dev sites place a notice on such docs that a newer version exists.  I totally understand time for doc maintenance is always a challenge as the community grows and software is young.

**Comment by josevalim** [comment]
Great to hear!

**Comment by jmodjeska** [comment]
For other Googlers: I had this same problem, also owing to blindly following the first Google result. It might help to add a note at the top of older Phoenix docs alerting (naive) readers to the fact that there's a newer version available, and they're not reading the active version's docs.
