### ISSUE TITLE
Bugs after upgrading to Phoenix 1.0.3 and Elixir 1.1.1

### ISSUE THREAD

**Issue by Alamoz** [phoenixframework/phoenix#1331]
Having problems after upgrading to Phoenix 1.0.3 and Elixir 1.1.1. When I build a release, I get a warning and then the release dies:

warning: the dependency :exrm requires Elixir ">= 0.15.1 and ~> 1.0.0" but you are running on v1.1.1

==> Conform: No schema found, conform will not be packaged in this release!

Lots of:  ===> Application metadata file exists but is malformed: 

When I just run the app, it throws an "undefined_column" for a new column I've added to the database. I'm guessing the compile didn't catch it.

Here is my mix.exs file:

defmodule Myapp.Mixfile do
  use Mix.Project

  def project do
    [app: :myapp,
     version: "0.0.1",
     elixir: "~> 1.1.1",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type `mix help compile.app` for more information
  def application do
    [mod: {Myapp, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger,
                    :phoenix_ecto, :postgrex]]
  end

  # Specifies which paths to compile per environment
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies
  #
  # Type `mix help deps` for examples and options
  defp deps do
    [{:phoenix, "~> 1.0.3"},
     {:phoenix_ecto, "~> 0.4"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0"},
     {:cowboy, "~> 1.0"},
     {:exrm, "~> 0.15.3"}]
  end
end

IMO you should show an example mix.exs file, along with any necessary syntax changes, in the documentation for every release.

Thanks!

**Comment by josevalim** [comment]
You are upgrading from which version? Phoenix did not introduce any
breaking changes from 1.0.0, it is more likely to be an exrm issue.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by lancehalvorsen** [comment]
You might want to upgrade to the latest version of exrm as well. Version 19.9 is on hex.pm.

https://hex.pm/packages/exrm/0.19.9

**Comment by Alamoz** [comment]
Yes, I had to upgrade exrm to 0.19.9, that solved the problem. I am still unclear on what versions of components to use when upgrading Phoenix. Is there a method to determine which versions of each component to use? Why not include a sample mix.exs in the upgrade docs?

Thanks again guys! The new version is performing even faster!
