### ISSUE TITLE
--no-compile argument is ignored

### ISSUE THREAD

**Issue by blast-hardcheese** [phoenixframework/phoenix#1333]
`mix help phoenix-server` suggests `This task accepts the same command-line arguments as run`, but this doesn't seem to be the case when trying to use `--no-compile`.

```
[deploy@ip-172-12-53-36 api]$ HEX_HOME=".hex" PATH=$PATH:../../elixir/bin mix phoenix.server --no-compile
==> decimal
Compiled lib/decimal.ex
Generated decimal app
==> poison
Compiled lib/poison.ex
Compiled lib/poison/decoder.ex
Compiled lib/poison/parser.ex
Compiled lib/poison/encoder.ex
Generated poison app
make: `priv/bcrypt_nif.so' is up to date.
==> comeonin
Compiled lib/comeonin/bcrypt/base64.ex
Compiled lib/comeonin/bcrypt.ex
...
```

What I'm trying to do is tar the build directory after running `mix compile`, then deploy that with no further compilation necessary, so while the current behavior is definitely not a deal-breaker, it is definitely a nice-to-have.

Alternately, if someone has suggestions for static deployment (ideally without any compilers, although given the nature of erlang, I suspect this isn't possible).

Thanks!

**Comment by josevalim** [comment]
Which Elixir version?

**Comment by josevalim** [comment]
About shipping Elixir with no need for compilers, please check: http://www.phoenixframework.org/docs/advanced-deployment

**Comment by blast-hardcheese** [comment]
@josevalim Looks like version `1.1.1`.

Thanks for the link! I had skimmed it before, but it wasn't clear to me that it would create a static environment-- this is great!

**Comment by josevalim** [comment]
I am closing this because --no-compile is not going to work when the task belongs to a dependency. Thank you!
