### ISSUE TITLE
Publish API documentation for the Phoenix Channels JavaScript client

### ISSUE THREAD

**Issue by ericlathrop** [phoenixframework/phoenix#1335]
The only documentation for the JavaScript side that I could find was [in the guides](www.phoenixframework.org/docs/channels#section-joining-channels). The guide is nice, but 
comprehensive API documentation should be published for reference.

**Comment by chrismccord** [comment]
This is something that I'd like to get out once we extract the client to its own repo (current WIP), for now the source is your best bet https://github.com/phoenixframework/phoenix/blob/master/web/static/js/phoenix.js#L1-L86

Thanks for the idea!

**Comment by bchase** [comment]
For anyone else who stumbles across this, `master` now uses the new v1.3 file structure, so `phoenix.js` has moved here:

https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L2-L103

**Comment by michalmuskala** [comment]
In the next release they also should be generated as part of regular documentation thanks to https://github.com/phoenixframework/phoenix/pull/2333
