### ISSUE TITLE
expose code_change for channels

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1336]

**Comment by stevedomin** [comment]
@chrismccord can you give a bit more background/info on the issue, want to make sure I understand it correctly.

**Comment by chrismccord** [comment]
Sure, we need to expose the `code_change` callback from the Channel.Server to the user's channel. So we'll need to implement it on the Channel.Server, and proxy it to an inject `code_change` function on the user's channel. So `use Phoenix.Channel` will need to inject a default code_change callback that is overridable. Make sense?

**Comment by stevedomin** [comment]
Yes, I think so, I'll give it a try
