### ISSUE TITLE
Confusion about broadcast on the socket/channel.

### ISSUE THREAD

**Issue by arathunku** [phoenixframework/phoenix#1339]
Hi, 

I had some confusion this morning about broadcasting because I wanted to send a event directly on the socket and I've read in the generated `user_socket.ex` about:

```
  # Would allow you to broadcast a "disconnect" event and terminate
  # all active sockets and channels for a given user:
  #
  #     MyApp.Endpoint.broadcast("users_socket:" <> user.id, "disconnect", %{})
  #
```

so I thought - awesome! I'll just change the disconnect to my event and it's going to work. I try to publish the event:

```
iex(34)> Endpoint.broadcast!("users_socket:749393", "auction:added", %{})
:ok
```

and I get nothing on the client, nor any message in the console but the output was `:ok` and I had my id specified:
```elixir
  def id(socket), do: "users_socket:#{socket.assigns.user_id}"
```
so I've assumed that there's an error on my side and started debugging. I wasn't able to pinpoint the error, therefore I've [asked on slack](https://elixir-lang.slack.com/archives/phoenix/p1446798546000298) where thankfully @trarbr helped me to discover that we can only publish "disconnect", if I want to send something to the user I've to use channels with a wildcard.

It would be great to fix that and there a couple of options (I can work on PR) 

1. Update the docs in the generator
2. Allow users to publish custom messages on the socket
3. Return an error when something couldn't be broadcasted instead of `:ok`

**Comment by chrismccord** [comment]
Broadcasting on the socket's topic is a special case where the transport subscribes to that id for forced disconnects. That message never makes it to the client. The rule is, if you need to communicate with the client, you do it over a channel on a topic. So "messaging a socket directly" isn't a concept in the channel layer. You have a conversation on channel managed by the socket transport. Also, broadcasting, like sending a message to a pid in Elixir is one-way. There's nothing to return other than `:ok`. You handle the error case when you don't get a response in a time that you expected it. So the only thing for use to do is # 1. If you have thoughts on what could make it clearer, please send a PR. Thanks!
