### ISSUE TITLE
Data inserted into Ecto repo during setup_all block is wiped out in every test

### ISSUE THREAD

**Issue by Diamond** [phoenixframework/phoenix#1341]
Right now, the process of calling `Ecto.Adapters.SQL.restart_test_transaction(App.Repo, [])` (such as what is created by default in `test/support/model_case.ex` and `test/support/conn_case.ex`) wipes out any data, even if it was created as part of a `setup_all` block in the test. It does this whether a `setup` callback is defined or not. I've created an example of this at the following repo:

https://github.com/Diamond/setup_all_bug

I apologize if this is the intended behavior and not actually an issue.

**Comment by chrismccord** [comment]
By default we run each test block in a transaction, so if you want setup_all behavior, you'll need to edit your `test/support/model_case.ex`, or set up special tags for each kind of transaction scenario you want. Let me know if that is not clear, but this isn't a bug so much as as default behavior that goes against what you're wanting. Luckily the model_case is a file that you own and can extend as needed.
