### ISSUE TITLE
Improve default Postgres config

### ISSUE THREAD

**Issue by fphilipe** [phoenixframework/phoenix#1345]
I was following the [Up and Running](http://www.phoenixframework.org/docs/up-and-running) guide and came across an error when I ran `mix ecto.create`:

    ** (Mix) The database for HelloPhoenix.Repo couldn't be created, reason given: psql: FATAL:  role "postgres" does not exist

So I looked up the generated *dev* config and saw this (similar for *test*):

```elixir
# Configure your database
config :hello_phoenix, HelloPhoenix.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "hello_phoenix_dev",
  hostname: "localhost",
  pool_size: 10
```

I then removed the `username`, the `password`, and the `hostname` and `mix ecto.create` worked.

I'd like to propose that these arguments are removed in postgres's case since they're not needed by default. The database name is enough. Rails default config for postgres doesn't specify these settings: https://github.com/rails/rails/blob/823d3a8de0ccfe2301e51ac1e06e106035edb8e6/railties/lib/rails/generators/rails/app/templates/config/databases/postgresql.yml#L17-L31

**Comment by josevalim** [comment]
Thank you. Sounds good to me!

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
:+1: . @stevedomin is grabbing this one.

**Comment by holyxiaoxin** [comment]
+1

**Comment by Gazler** [comment]
@holyxiaoxin Please see https://github.com/phoenixframework/phoenix/pull/1346#issuecomment-163961581

**Comment by dustypomerleau** [comment]
+1—This still seems to be the case. Commenting out the default username and password in dev.exs fixes the problem, but it takes a long time for new users to discover this.

**Comment by josevalim** [comment]
Unfortunately these defaults depend on how Postgres is installed on the
machine, so regardless of what we pick, some users will be affected.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
