### ISSUE TITLE
Can't see homepage at localhost:4000

### ISSUE THREAD

**Issue by ekkapob** [phoenixframework/phoenix#1349]
I can't browse to homepage. I followed Phoenix Up & Running instructions with no errors so far. However, when I browse to the homepage port 4000, nothing show up, like no connection at all. I tried with different ports (ref: https://github.com/phoenixframework/phoenix/issues/962) but no luck.

`Chrome: This webpage is not available ERR_CONNECTION_REFUSED`
`Firefox: Unable to connect - Firefox can't establish a connection to the server at localhost:4000..`

All commands run without errors
````
➜ mix ecto.create
The database for HelloPhoenix.Repo has been created.

➜ mix phoenix.server
[info] Running HelloPhoenix.Endpoint with Cowboy on http://localhost:4000
12 Nov 01:30:57 - info: compiled 5 files into 2 files, copied 3 in 3480ms
````

**Comment by chrismccord** [comment]
try `http://127.0.0.1:4000` and report back. Some users have have issues on localhost for one reason or another

**Comment by ekkapob** [comment]
120.0.0.1 works. Thanks @chrismccord for the lighting response.

**Comment by chrismccord** [comment]
Awesome. I don't see how this is on our end, and I can't recreate locally so for now loopback address is a usable workaround. Hop on elixir-lang irc if you have any issues

**Comment by bbrock25** [comment]
I just experienced this issue as well on chrome but was able to use localhost on firefox.

**Comment by doomspork** [comment]
This just recently happened to me, no other changes to the system.  It occurred in the middle of running my Phoenix application.  As a work around I've shifted to using [lvh.me](lvh.me) which maps to localhost and enables me to use subdomains.  

There's been at least a half dozen folks with a similar issue in Slack.  Would be great to figure out what's behind this.  Tough to see it as a system issue when it's impacting more and more users of a particular framework and language.  Hard to believe we all made the same mistakes, independent of OS, while using Phoenix.

**Comment by chrismccord** [comment]
> There's been at least a half dozen folks with a similar issue in Slack. Would be great to figure out what's behind this.

Unfortunately given how arbitrary this seems to come up which no means to recreate it, and often reported as browser dependent, I wouldn't know where to begin. I also don't have time to chase down this particular rabbit hole. If someone wants to take a deep-dive that would be fantastic.

**Comment by doomspork** [comment]
I agree @chrismccord, that was a general statement.  I've tried a handful of things I can't seem to make any headway.  It's a perplexing problem but it does seem to be related in some way to Phoenix, Plug, Elixir, or Cowboy.  Localhost works just fine for Ruby, Python, and Java applications.

**Comment by ianfleeton** [comment]
I had a similar issue and was able to continue using the same browser (Chrome) after clearing cache, cookies, etc., which made me think at the time it was a bad cookie or something tied to the domain name. I do a lot of other development on localhost so there could be all sorts being sent. I haven't had this happen again to confirm a better link.

**Comment by zlu** [comment]
Probably something changed in /etc/hosts.  Maybe add this back:

```
127.0.0.1 localhost
```

**Comment by doomspork** [comment]
@zlu the `/etc/hosts` was never changed and the entry still exists.  Since `localhost:4000` works across other languages and frameworks that might suggest it's not a host issue :grinning:

**Comment by sjoonk** [comment]
I think it's something related with cowboy not phoenix framework. And it's something related Chrome browser. On Safari, it works.

**Comment by joshhepworth** [comment]
I wanted to add some info to this, as I ran into this issue.

It seems that Chrome _can_ connect, but will not render anything other than a totally empty page (view source shows no content). It worked without issue in Firefox and Safari.

I _meant_ to delete cookies one by one to see if a particular cookie was causing the problem, however I accidentally wiped them all out – which did solve the problem. Deleting the cookies stored at `localhost` was the only change I made to get it working.

I also do Rails and Express development, so it's possible cookies set by one of those are interfering with something in the rendering stack. I'm super new to Phoenix dev, so I'm not sure where to look, but if I run into it again (and remember to delete cookies one by one), I'll add information here.

**Comment by josevalim** [comment]
Yes, Cowboy simply discards the request for large headers because allowing otherwise is a possible attack vector. So erasing cookies is the way to go.

**Comment by joshhepworth** [comment]
Sounds like it's likely just related to one of the cookies being large in that list – I had cookies for 10+ different Rails projects in there, and I bet one or two were pushing 500bytes. Generally sounds like this might be related to [this issue](https://github.com/elixir-lang/plug/issues/365).

That being said, is there a way to adjust this number somehow (and what is the max size set to)? Seems like sometimes I'd want to be able to increase the number – plenty of sites have largish cookies, my browser is showing 5 on Amazon over 500bytes.

**Comment by josevalim** [comment]
I believe the default is 4k. See here: https://ninenines.eu/docs/en/cowboy/1.0/manual/cowboy_protocol/index.html#max_header_value_length

You can change it by setting the following in your config.exs file (iirc):

    http: [protocol_options: [max_header_value_length: 8192]]

**Comment by mnussbaumer** [comment]
The empty white page on `localhost:4000` just happened to me and I can confirm it's a cookie issue. I had previously created a new app with phoenix and `localhost:4000` worked just fine. I deleted that app, created a new one, and it would work with `127.0.0.1:4000` but not with `localhost:4000` - just a totally blank page. So what happened was that I was using exactly the same name as another app I had with Ruby On Rails, which in turn had a session cookie created for that app name and that conflicted with the new phoenix app.  Erasing that cookie solved the issue, so if you're seeing a total blank screen when visiting `localhost` check to see if you don't happen to have a previously set cookie with the same name as the app you're currently trying to run.

**Comment by josevalim** [comment]
Btw, this has been fixed in Plug v1.4 since it now warns on the terminal when this happens.

**Comment by mnussbaumer** [comment]
It doesn't show anything when it's simply an existing cookie (without exceeding max length)?

Micaels-MacBook-Pro:dinastywars mnussbaumer$ mix phoenix.server
[info] Running Dinastywars.Endpoint with Cowboy using http://localhost:4000
27 Jul 20:53:33 - info: compiled 6 files into 2 files, copied 3 in 1.9 sec

Nothing was being output when I was hitting `localhost:4000`.

**Comment by josevalim** [comment]
@mnussbaumer what is your plug version? Also, Plug will just log something if the server returns 400.

**Comment by mnussbaumer** [comment]
Ahh you're right, sorry @josevalim - I just assumed I would have the latest version because I installed everything phoenix/elixir/erlang yesterday . Thanks - it reads plug 1.3.5 - I'm completely new to phoenix btw

**Comment by josevalim** [comment]
No problem and welcome!

**Comment by mnussbaumer** [comment]
Thanks, and for your work too - it looks great, sounds great and I will try to use it moving on from Rails - Besides the issues on github (since my knowledge is a bit more superficial) is there any way to contribute? Or mailing list? There are also some broken links, like http://phoenixframework.org/docs/understanding-plug and /community

**Comment by josevalim** [comment]
The issues on github are the main way. For the guides, reach the phoenix_guides repo. The guides are currently being reworked for v1.3 so, if I assume they will need help with sanity checking everything as soon as it goes live.

**Comment by kkkkeeee** [comment]
Hi, I am facing the same error. I tried to open localhost:4000 and 127.0.0.1:4000 on Chrome and Microsoft Edge on Windows. But still I cannot open the homepage.

Could anyone help me with it?

**Comment by mnussbaumer** [comment]
@kkkkeeee can you provide some more info? Do you get a blank page? Or an error? What shows up on iex? And on the javascript console?

**Comment by kkkkeeee** [comment]
HI,

What is shown on the console is :
C:\Users\zhaikeke\Documents\LeetCode\Elixir\hello>mix phx.server
[info] Running HelloWeb.Endpoint with Cowboy using http://0.0.0.0:4000
13:48:07 - info: compiled 6 files into 2 files, copied 3 in 1.1 sec

For the localhost webpage, I got:
This page isn’t working

*localhost* sent an invalid response.
ERR_INVALID_HTTP_RESPONSE

That's all I have. I didn't open any javascript console.

Yours Sincerely,
Keke

On Wed, Nov 8, 2017 at 11:25 AM, Micael Nussbaumer <notifications@github.com

**Comment by OvermindDL1** [comment]
It's usually better to ask questions like this on the forum for quicker responses.

But what is your git address so we can try out what you are trying so we can see the issue?

**Comment by vellmoss** [comment]
I worked through a VPN tunnel. Disconnected it - and everything became OK.

**Comment by OvermindDL1** [comment]
> I worked through a VPN tunnel. Disconnected it - and everything became OK.

Heh, sounds like the VPN is redirecting local connections, that is... very odd...  ^.^;

**Comment by vellmoss** [comment]
when I looked at the page on F12 (Chrome), I saw in the tab "Application" tags:
<div id = "footer">
<p> Created on Wed, Jan 16, 2018 18:00:59 GMT on us02.vpn99.net (squid / 3.5.20) </ p>
<! - ERR_CONNECT_FAIL ->
</ DIV>
which led me to this idea. vpn99.net is the tunnel through which I work.
p.s. sorry for my English :-((

**Comment by PeterDavidCarter** [comment]
This particular rabbit still appears to be affecting your service offering. I'd suggest myself as an Alice but I also have a day-job and a side-business already. Interestinging, loopback (127.0.0.1 and 0.0.0.0 aren't working for me at present, but typing localhost is, albeit without images).

**Comment by Awankelabu5566** [comment]
Done

**Comment by web-apply** [comment]
review here [http://localhost:4000](https://localhosts.mobi/4000)
