### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by shalakhin** [phoenixframework/phoenix#1351]
Hey there!

Is there any i18n support for phoenix? What do you suggest to use with phoenix to have i18n? It seems `linguist` should be used?

**Comment by chrismccord** [comment]
gettext is what you want to use, and you can integrate it today very easily (https://github.com/elixir-lang/gettext/). We are going to include it as a default in 1.1

**Comment by scrogson** [comment]
We are planning on adding i18n support via gettext.
