### ISSUE TITLE
iex -S mix phoenix.server returns an ERROR. :bug

### ISSUE THREAD

**Issue by DavidStrada** [phoenixframework/phoenix#1355]
When I fired the command `iex -S mix phoenix.server` i'm using your guide up and run ( http://www.phoenixframework.org/docs/up-and-running )[up and run] I got the following stack trace ( i believe this is an stack trace ), anyhow he's the info :

``` console
» iex -S mix phoenix.server
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]


=INFO REPORT==== 16-Nov-2015::17:43:07 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application hello_phoenix: HelloPhoenix.start(:normal, []) returned an error: shutdown: failed to start child: HelloPhoenix.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Server
        ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, HelloPhoenix.Endpoint.HTTP}
            ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup
                ** (EXIT) {:listen_error, HelloPhoenix.Endpoint.HTTP, :eaddrinuse}

```

**Comment by chrismccord** [comment]
> ** (EXIT) {:listen_error, HelloPhoenix.Endpoint.HTTP, :eaddrinuse}

Your port is in use, but you should have received a printed error before the stack that told you so. Try a different port

**Comment by chrismccord** [comment]
I just verified, you should have seen this logged:

    [error] Running Chat.Endpoint with Cowboy on http://localhost:4000 failed, port already in use


Can you try again and report back on whether or not you see that error logged?

**Comment by DavidStrada** [comment]
I'm quite new to elixir/phoenix how should i pass a port flag ? checked iex --help but couldn't find any.

**Comment by chrismccord** [comment]
The default port is 4000, and it's set in `config/dev.exs` (or test.exs/prod.exs), but `iex` by default will use dev. So bump the port int your endpoint config in dev.exs and you should be all set. If you want to make it dynamic, you can use a PORT env var (like in prod.exs), i.e.:

    http: [port: System.get_env("PORT") || 4000]

then `PORT=4001 iex -S mix phoenix.server`

**Comment by DavidStrada** [comment]
When i used `port=4001` **it worked!,** however using the dynamic port. `http: [port: {:system, "PORT"}],`

``` console
[error] Server can't start because :port in config is nil, please use a valid port number
[info] Application hello_phoenix exited: HelloPhoenix.start(:normal, []) returned an error: shutdown: failed to start child: HelloPhoenix.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Server
        ** (EXIT) shutdown

=INFO REPORT==== 16-Nov-2015::18:24:26 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application hello_phoenix: HelloPhoenix.start(:normal, []) returned an error: shutdown: failed to start child: HelloPhoenix.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Server
        ** (EXIT) shutdown
```

**Comment by chrismccord** [comment]
Perfect! It reports the error as expected: `[error] Server can't start because :port in config is nil, please use a valid port number`. Hop on elixir-lang irc if you have questions and welcome aboard!

**Comment by DavidStrada** [comment]
Thanks :+1:

**Comment by TimHeckel** [comment]
Alternatively, you can do: `lsof -i tcp:4000 | grep beam | awk '{print $2}' | uniq | xargs kill` to kill the phoenix server
