### ISSUE TITLE
Integrate with brunch 2.0

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1361]
In particular, we need to check if they respect the behaviour where they listen to stdin, so when we close Phoenix, brunch automatically shuts down. We also need to check if the generated JS and config works as expected:

https://github.com/brunch/brunch/blob/master/CHANGELOG.md

**Comment by paulmillr** [comment]
As always — let's solve any Brunch-related issues that may appear together!

**Comment by stevedomin** [comment]
Are you happy for me to take this @josevalim?

**Comment by chrismccord** [comment]
@paulmillr definitely! What new features are brewing? Also, how is npm support coming? I know lack of npm support has been a pain point for a lot of our users. With bower on the out, landing stable npm integration would be super nice.

**Comment by josevalim** [comment]
Please do. :D

**Comment by paulmillr** [comment]
@chrismccord NPM is the next big step for 2.1. Definitely a super-huge priority. I was dissapointed that bower "didn't make it". :crying_cat_face:

**Comment by stevedomin** [comment]
Fixed by https://github.com/phoenixframework/phoenix/pull/1365 (forgot to mention the issue in the PR)
