### ISSUE TITLE
changes to router.ex not reflected after refresh.  Server restart necessary

### ISSUE THREAD

**Issue by aweis** [phoenixframework/phoenix#1366]
Steps to reproduce:

Start with the hello_phoenix application
Start server: mix phoenix.server
Go to localhost:4000, confirm it is working
Add the following to the scope
get "/here", PageController, :index
go to http://localhost:4000/here
Get: no route found for GET

restart server, route now works

versions: 

Phoenix v1.0.3 installed from here: mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v1.0.3/phoenix_new-1.0.3.ez
OS: OSX El Capitan 10.11.1 (15B42)

**Comment by sevenseacat** [comment]
never had a problem with this myself.

**Comment by chrismccord** [comment]
Can you rule out your editor doing some syntax checking in the background and causing the code reloading to not reload the file (since it was already recompiled). Use a plain old text editor to try it out. I know there is a vim plugin that causes issues with the code reloader.

**Comment by aweis** [comment]
Hi @chrismccord.  Good call, it did work when I was using a text editor other than vim.  Do you know which vim plugin you were referring to so I can see if I can disable it?

**Comment by aweis** [comment]
I found this issue: https://github.com/phoenixframework/phoenix/issues/1165, which I think is exactly the same as what I am seeing.
