### ISSUE TITLE
mix ecto.migrate failed with CompileError

### ISSUE THREAD

**Issue by bossyang** [phoenixframework/phoenix#1367]
I followed the blog http://maxwellholder.com/blog/build-a-blog-with-phoenix-and-ember.

Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.1.1
OSX Mavericks
````
~/workspace/peep_blog/peep_blog_backend > mix phoenix.gen.json Post posts title:string body:text
* creating web/controllers/post_controller.ex
* creating web/views/post_view.ex
* creating test/controllers/post_controller_test.exs
* creating web/views/changeset_view.ex
* creating priv/repo/migrations/20151121134834_create_post.exs
* creating web/models/post.ex
* creating test/models/post_test.exs

Add the resource to your api scope in web/router.ex:

    resources "/posts", PostController, except: [:new, :edit]

Remember to update your repository by running migrations:

    $ mix ecto.migrate
```

````
~/workspace/peep_blog/peep_blog_backend > mix ecto.migrate
Compiled web/models/post.ex
Compiled web/views/changeset_view.ex

== Compilation error on file web/controllers/post_controller.ex ==
** (CompileError) web/controllers/post_controller.ex:20: function post_path/3 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
````

**Comment by chrismccord** [comment]
I think you missed the directions in the above output :)

"Add the resource to your api scope in web/router.ex:

    resources "/posts", PostController, except: [:new, :edit]"

**Comment by bossyang** [comment]
@chrismccord  Thanks!

**Comment by eduardonunesp** [comment]
The error persists here event with changes.

== Compilation error on file web/controllers/post_controller.ex ==
** (CompileError) web/controllers/post_controller.ex:20: undefined function post_path/3
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.2.5

Phoenix 1.1.6

**Comment by eduardonunesp** [comment]
Actually is a different error

**Comment by josevalim** [comment]
You need to add the route to your router as the generator asks you to
before running migrations.

On Saturday, June 11, 2016, Eduardo Nunes Pereira <notifications@github.com>
wrote:

> Actually is a different error
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1367#issuecomment-225327807>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbjEj_0al1sta3b2Yzt3GO5CSE2FKks5qKgocgaJpZM4Gm6_F>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eduardonunesp** [comment]
Actually the error has nothing to do with the procedure above. After recreate the project and follow the steps without any of my previous "tricks" the project worked. Sorry, my bad.

**Comment by ttaranto** [comment]
Thanks!
