### ISSUE TITLE
Error around generating new apps, assign @view_module not available in eex template

### ISSUE THREAD

**Issue by davidbegin** [phoenixframework/phoenix#1369]
This is only my 1st day looking at Phoenix, and 2nd day for Elixir, so
I know how barely anything works, and I could missing something obvious,
but to me, it looks like this commit introduced a bug around generating a new Phoenix application:
https://github.com/phoenixframework/phoenix/commit/1ec8f3bce5d3caec1dddac6590e99ab506c6d998

I made a repo of the steps I used to determine what commit caused this change
in behavior: https://github.com/davidbegin/phoenix-new-app-bug

I am going to try to start figuring out exactly what is happening, but if it is an actual issue, it
would probably be better for someone with more experience with Elixir/Phoenix.

**Comment by davidbegin** [comment]
Yep this is user error.

I generated a new Phoenix application on master, but I had my Phoenix in my mix.exs pointing to 1.0.3.
This was all I needed for a fix https://github.com/davidbegin/phoenix-new-app-bug/commit/7f7e1219a587704e33bd3b06edad256af2b8f771

So this can be closed, but there is a chance that other brand new people might hit this problem.
And I am not sure what is the best way to make the issue more obvious.

**Comment by josevalim** [comment]
This is a bug I think, we need to update Phoenix generators to depend on Phoenix master as well for now if it does not yet.

**Comment by chrismccord** [comment]
If you use Phoenix 1.0.3 from hex, this won't be an issue. master is our unstable, unreleased branch. I'll update the generators to point to master just in case folks are on edge, but if you're just getting started, it's best to be on stable. Thanks!
