### ISSUE TITLE
Cannot written file javascript in project.

### ISSUE THREAD

**Issue by vanloc0301** [phoenixframework/phoenix#1373]
I was build phoenix app and start with command:
mix phoenix.server
It show error like this:
[info] Running ElmPhoenixApp.Endpoint with Cowboy on http://localhost:4000
26 Nov 00:45:26 - warn: 'web\static\css\app.css' compiled, but not written. Check your stylesheets.joinTo config.
26 Nov 00:45:26 - warn: 'web\static\js\app.js' compiled, but not written. Check your javascripts.joinTo config.
26 Nov 00:45:26 - warn: 'web\static\js\socket.js' compiled, but not written. Check your javascripts.joinTo config.
26 Nov 00:45:26 - warn: 'deps\phoenix_html\web\static\js\phoenix_html.js' compiled, but not written. Check your javascripts.joinTo config.
26 Nov 00:45:26 - warn: 'deps\phoenix\web\static\js\phoenix.js' compiled, but not written. Check your javascripts.joinTo config.
How to resolve this?

**Comment by chrismccord** [comment]
Sounds like a permissions issue? Can you try running `brunch watch` on the console by itself and report back?

**Comment by vanloc0301** [comment]
Error like this:
![capture](https://cloud.githubusercontent.com/assets/4168981/11405532/f00291d0-93da-11e5-85e7-0ec4fd475fbc.PNG)
I was searching on the internet, explain because *.js using ES6.
I running Phoenix v1.0.0, Erlang 18.0 and Elixir 1.1.0 in windows 7.
Thanks.

**Comment by stevedomin** [comment]
@vanloc0301 can you upload the content of your `brunch-config.js` somewhere?

**Comment by vanloc0301** [comment]
@stevedomin , my brunch-config.js here

http://pastebin.com/FR9A6Csj

**Comment by tdeschryver** [comment]
I believe you have to add your stylesheets path.

I updated the config - http://pastebin.com/m8ZLJqk0

Added:
`
stylesheets: {
      joinTo: "css/app.css"
    }
`

**Comment by stevedomin** [comment]
@vanloc0301 if the css issue is still there after you updated your `brunch-config` with @tdeschryver's one then I'd say like Chris, it's probably a permission issue.

**Comment by vanloc0301** [comment]
@tdeschryver @stevedomin , sorry, I was provider brunch-config of root/phoenix.
I posted brunch-config in my project add here.

http://pastebin.com/rM2d5AGL
This file was added:
` stylesheets: { joinTo: "css/app.css" } `
like default when I create new app.

**Comment by stevedomin** [comment]
@vanloc0301 is it working for you now?

**Comment by vanloc0301** [comment]
![capture](https://cloud.githubusercontent.com/assets/4168981/11451372/e173a60e-95f6-11e5-9557-9a15ade59e55.PNG)
No, I can't solved this problem.

**Comment by vanloc0301** [comment]
I was reinstall windows.

But I also meet error like this.
I create with `mix phoenix.create path/path1`. And I don't write any line code

**Comment by chrismccord** [comment]
Please update to the latest version of phoenix (1.0.4) 

    mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v1.0.4/phoenix_new-1.0.4.ez

Then generate a new application and report back. Thanks!

**Comment by vanloc0301** [comment]
I was update phoenix to latest version.
I don't know why only me meet this case.

1. I install node.js v5.1.0, mingw, elixir 1.1.0, erlang 18.1, postgres 9.4.5 beta1.
2. Clone phoenix repositories and `cd install`. Execute command:
`mix phoenix.new example_project`

`mix phoenix.server` - complie source and open: `localhost:4000`
I was update with your command.
`mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v1.0.4/phoenix_new-1.0.4.ez`

In all case, I have this error.

**Comment by chrismccord** [comment]
Unfortunately this looks like an obscure node/brunch bug on your windows installation, so I'm out of things to try to fix on our end. If you come to a resolution, please let us know so we can pay it forward to the next person that runs into this. Thanks!
