### ISSUE TITLE
phoenix.js - reason is not defined

### ISSUE THREAD

**Issue by Thomas101** [phoenixframework/phoenix#1376]
Hey,

Found the variable `reason` that has been referenced in [phoenix.js on line 235](https://github.com/phoenixframework/phoenix/blob/master/web/static/js/phoenix.js#L235) but it has not been defined. Causes it break on timeout

```
  this.joinPush.receive("timeout", () => {
      if(this.state !== CHANNEL_STATES.joining){ return }

      this.socket.log("channel", `timeout ${this.topic}`, reason)
      this.state = CHANNEL_STATES.errored
      this.rejoinTimer.setTimeout()
    })
```

Can I suggest changing it to be one of
```
this.socket.log("channel", `timeout ${this.topic}`)
this.socket.log("channel", `timeout ${this.topic}`, 'timeout')
```

Thanks
Tom

**Comment by chrismccord** [comment]
Fixed. Thanks!
