### ISSUE TITLE
Running rel/app/bin/app console crashes

### ISSUE THREAD

**Issue by sashaafm** [phoenixframework/phoenix#1382]
I've been trying to deploy my app for testing and showing in AWS and I've been following the guide at the Phoenix's website, but I keep getting this error when I get to that point of trying if it works in the environment. I'm using AWS Ubuntu's 14.04 image.

Root: /home/ubuntu/app/rel/app
/home/ubuntu/app/rel/app
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [async-threads:10] [kernel-poll:false]

{"Kernel pid terminated",application_controller,"{application_start_failure,app,{{shutdown,{failed_to_start_child,'Elixir.App.Endpoint',{shutdown,{failed_to_start_child,'Elixir.Phoenix.Endpoint.Server',{undef,[{'Elixir.Phoenix.LiveReloader.Socket','__transports__',[],[]},{'Elixir.Phoenix.Endpoint.CowboyHandler','-child_spec/3-fun-1-',3,[{file,\"lib/phoenix/endpoint/cowboy_handler.ex\"},{line,62}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,\"lib/enum.ex\"},{line,1387}]},{'Elixir.Phoenix.Endpoint.CowboyHandler',child_spec,3,[{file,\"lib/phoenix/endpoint/cowboy_handler.ex\"},{line,61}]},{'Elixir.Phoenix.Endpoint.Server',init,1,[{file,\"lib/phoenix/endpoint/server.ex\"},{line,20}]},{supervisor,init,1,[{file,\"supervisor.erl\"},{line,272}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}}}},{'Elixir.App',start,[normal,[]]}}}"}

Crash dump is being written to: erl_crash.dump...done
Kernel pid terminated (application_controller) ({application_start_failure,app,{{shutdown,{failed_to_start_child,'Elixir.App.Endpoint',{shutdown,{failed_to_start_child,'Elixir.Pho

And my config file is the following:

# This file is responsible for configuring your application
# and its dependencies with the aid of the Mix.Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.
use Mix.Config

# Configures the endpoint
config :app, App.Endpoint,
  url: [host: "localhost"],
  root: Path.dirname(__DIR__),
  secret_key_base: "0ijP5EMvNzzHGHvbsHx4ZpahQzfiBsf7ryPS9cpG5ixJjWRIESE2r5KUQydiQNO/",
  render_errors: [accepts: ~w(html json)],
  pubsub: [name: App.PubSub,
           adapter: Phoenix.PubSub.PG2],
  server: true

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{Mix.env}.exs"

# Configure phoenix generators
config :phoenix, :generators,
  migration: true,
  binary_id: false

And finally my /lib/app.ex file:

defmodule App do
  use Application

  # See http://elixir-lang.org/docs/stable/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    children = [
      # Start the endpoint when the application starts
      worker(App.Endpoint, []),
      # Start the Ecto repository
      worker(App.Repo, []),
      # Here you could define other workers and supervisors as children
      # worker(App.Worker, [arg1, arg2, arg3]),
    ]

    # See http://elixir-lang.org/docs/stable/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: App.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    App.Endpoint.config_change(changed, removed)
    :ok
  end
end

The Endpoint was set as a supervisor, but I changed it to worker like it is specified in the guide. Not sure if that had any implication.

**Comment by josevalim** [comment]
It seems you are running or building the release in the development environment, as it is trying to access the LiveReloader which is not available in production.

**Comment by chrismccord** [comment]
Please direct support requests to the phoenix-talk mailing list. José's advice would be the first area to investigate since LiveReloader should be be trying to be accessed in a prod release. elixir-lang irc is also a great place for help. Thanks!
