### ISSUE TITLE
Bump Phoenix.Ecto dependency

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1385]
The new version should:

* depend on Ecto 1.1
* deprecate json encoding of changesets
* use the new traverse_errors functionality in views
* use Ecto.Schema instead of Ecto.Model

**Comment by stevedomin** [comment]
@josevalim can I take this one?

**Comment by josevalim** [comment]
@stevedomin please don't because this is mostly a reminder. Those tasks are spread across multiple projects and @chrismccord and I are already working on it. Sorry and thanks!

**Comment by stevedomin** [comment]
No worries :)
