### ISSUE TITLE
Expose check for webserver running

### ISSUE THREAD

**Issue by hansihe** [phoenixframework/phoenix#1386]
When running the ecto.setup task, the database is automatically seeded by running seeds.exs. When doing this, the full supervisor tree of the application will be started. Some processes in the supervisor tree may want to fetch data from the database, which causes problems when the database is not yet seeded. By checking if the webserver is running, you can conditionally start services that require data from the database only when the full application is running.

**Comment by josevalim** [comment]
Correction: we will always start the app. I suggest for us to provide a flag that allows you to choose if the app the given service should be started or not. :)

**Comment by josevalim** [comment]
We should not need to pass the conf. It breaks the purpose of the function
for third party developers. I think the function we have defined is going
to have a different implementation than the you one extracted.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by chrismccord** [comment]
> We should not need to pass the conf. It breaks the purpose of the function
> for third party developers. I think the function we have defined is going
> to have a different implementation than the you one extracted.

I added it so we could share the logic with Adapter. Let's sync on irc these evening or tomorrow
