### ISSUE TITLE
Vagrant - Mix Phoenix.New Fails

### ISSUE THREAD

**Issue by rpkittle** [phoenixframework/phoenix#1391]
Trying to create a Phoenix App in Vagrant ubuntu/trusty64.

Any ideas? What additional info can I provide to help troubleshoot the cause?

I have used this resource as a reference:
http://www.phoenixframework.org/docs/installation

```
vagrant@vagrant-ubuntu-trusty-64:/$ mix phoenix.new test_app
** (FunctionClauseError) no function clause matching in Path.expand_dot/2
    (elixir) lib/path.ex:642: Path.expand_dot([], [])
    lib/phoenix_new.ex:390: Mix.Tasks.Phoenix.New.in_umbrella?/1
    lib/phoenix_new.ex:170: Mix.Tasks.Phoenix.New.run/4
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by josevalim** [comment]
Please include Erlang and Elixir version, include the Phoenix one. You can get those by running `iex` (the first two lines) and `mix phoenix.new --version`.

**Comment by rpkittle** [comment]
Below are the versions!

```
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [async-threads:10] [kernel-poll:false]
Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
Phoenix v1.0.4
```

**Comment by josevalim** [comment]
Thank you. Can you please start `iex` in the same directory as you tried to run the command and let me know what this returns:

```
iex> Path.expand(Path.join ["test_app", "..", ".."])
???
iex> Path.expand(Path.join [File.cwd!, "test_app", "..", ".."])
???
```

**Comment by josevalim** [comment]
Nevermind. I found the bug. :)

Running `Path.expand(Path.join ["test_app", "..", ".."])` from `/` causes elixir to fail. Ported this report to elixir here: https://github.com/elixir-lang/elixir/issues/4050. Please just try to create the project inside a nested directory for now (like /bar/baz). Sorry for the inconvenience, a temporary fix has also been pushed to Phoenix.

**Comment by rpkittle** [comment]
Thank you for the diligence!
