### ISSUE TITLE
mix test seems to hang on inet_gethost

### ISSUE THREAD

**Issue by edyu** [phoenixframework/phoenix#1395]
On mac os x El Capitan (10.11.1):
1. I used brew to install elixir 1.1.1 and then installed the latest v1.0.4 phoenix today. 
2. create any new application using "mix phoenix.new new_app --database mysql"
3. mix ecto.create
4 mix test (hangs forever)
From the Terminal app, I can see that the test is hang on the process inet_gethost

**Comment by chrismccord** [comment]
Is it waiting on mysql? Is your mysql database up and running?

**Comment by chrismccord** [comment]
aldo see if `mix test --trace` provides any useful output for us

**Comment by edyu** [comment]
The mysql database is up and running. Otherwise, mix ecto.create would've failed.
mix test --trace just hangs. Let me delete the folder and recreate it to see if mix test --trace does anything in that case.

**Comment by edyu** [comment]
FYI mix phoenix.server works ok

**Comment by edyu** [comment]
Just hangs
https://gist.github.com/edyu/638df4867e7866d7c97d

**Comment by edyu** [comment]
beam.smp -- -root /usr/local/Cellar/erlang/18.1/lib/erlang -progname erl -- -home ~ -- -pa /usr/local/Cellar/elixir/1.1.1/bin/../lib/eex/ebin /usr/local/Cellar/elixir/1.1.1/bin/../lib/elixir/ebin /usr/local/Cellar/elixir/1.1.1/bin/../lib/ex_unit/ebin /usr/local/Cellar/elixir/1.1.1/bin/../lib/iex/ebin /usr/local/Cellar/elixir/1.1.1/bin/../lib/logger/ebin /usr/local/Cellar/elixir/1.1.1/bin/../lib/mix/ebin -elixir ansi_enabled true -noshell -s elixir start_cli -extra /usr/local/bin/mix test --trace

**Comment by edyu** [comment]
inet_gethost 4	16,211
inet_gethost 4	16,212

**Comment by edyu** [comment]
Those are from the Inspector on Terminal tab showing the running processes.

**Comment by edyu** [comment]
Not sure whether this is helpful. When I kill the process I get the following:
10:54:48.821 [error] GenServer NewApp.Repo.Pool terminating
** (stop) killed
** (exit) exited in: GenServer.call(#PID<0.2011.0>, {:query, "SELECT s0.`version` FROM `schema_migrations` AS s0", [], [timeout: :infinity, log: false]}, :infinity)
    ** (EXIT) killed
    (elixir) lib/gen_server.ex:544: GenServer.call/3
    (ecto) lib/ecto/adapters/mysql/connection.ex:25: Ecto.Adapters.MySQL.Connection.query/4
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.query/7
    (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4
    (ecto) lib/ecto/adapters/sql.ex:244: Ecto.Adapters.SQL.query/6
    (ecto) lib/ecto/adapters/sql.ex:222: Ecto.Adapters.SQL.query/5
    (ecto) lib/ecto/adapters/sql.ex:183: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/sql.ex:478: Ecto.Adapters.SQL.execute/6

**Comment by josevalim** [comment]
It does seem it just can't connect to MySQL.

**Comment by edyu** [comment]
@josevalim  mix ecto.create passes though which creates the tables with the same credentials. Why would test not be able to connect? Is there a way to test it? I can manually connect to mysql on the terminal.

**Comment by edyu** [comment]
Process Information

--------------------------------------------------
=proc:<0.274.0>
State: Waiting
Name: inet_gethost_native
Spawned as: inet_gethost_native:server_init/2
Spawned by: <0.273.0>
Started: Tue Dec  8 11:07:37 2015
Message queue length: 0
Number of heap fragments: 0
Heap fragment data: 0
Link list: [#Port<0.9055>, <0.273.0>]
Dictionary: [{rid,1},{num_requests,0}]
Reductions: 83
Stack+heap: 233
OldHeap: 0
Heap unused: 156
OldHeap unused: 0
Memory: 2864
Stack dump:
Program counter: 0x000000002048a340 (inet_gethost_native:main_loop/1 + 40)
CP: 0x0000000000000000 (invalid)
arity = 0

**Comment by josevalim** [comment]
@edyu `ecto.create` uses the mysql command line to create the database which may bypass or work differently than the TCP authentication which Ecto surely uses.

**Comment by edyu** [comment]
I can confirm that postgres version of "mix test" works. I did need to create the super user 'postgres' for the database first. Let me see if I need to do the same for mysql.

**Comment by edyu** [comment]
So I can see that mix ecto.create will create the database new_app_dev.
mix test will create the database new_app_test and also the table schema_migrations. The table is empty. 

I'm stuck at this point. It looks like an ecto bug as http://www.phoenixframework.org/docs/using-mysql makes it look like as long as you put --database mysql things would just work but it doesn't seem that way for mysql.

**Comment by josevalim** [comment]
It does work on my machine. If it doesn't work in yours I would bet it is something related to the configuration. Maybe the host, port, username, pass does not work. You can try by passing this information explicitly to mysql and see how it goes.

**Comment by edyu** [comment]
@josevalim ok thanks. Do you have any particular command that you want me to pass to mysql? I'm using the default configuration of 'root' user with no password as is in the ecto config file because I haven't changed anything. I'm doing this on a mac with the lasted version of everything. Thanks.

**Comment by josevalim** [comment]
I am not sure.  Run `mysql --help` and try out the options there, trying to pass all parameters that you have specified in your `config/dev.exs` file. Here is how we call mysql, just in case: https://github.com/elixir-lang/ecto/blob/master/lib/ecto/adapters/mysql.ex#L151-L152

**Comment by edyu** [comment]
use Mix.Config

# We don't run a server during test. If one is required,
# you can enable the server option below.
config :msql_app, MsqlApp.Endpoint,
  http: [port: 4001],
  server: false

# Print only warnings and errors during test
config :logger, level: :info

# Configure your database
config :msql_app, MsqlApp.Repo,
  adapter: Ecto.Adapters.MySQL,
  username: "root",
  password: "",
  database: "msql_app_test",
  hostname: "localhost",
  pool: Ecto.Adapters.SQL.Sandbox

**Comment by edyu** [comment]
Well, I tried on the command line and the command works on command-line. I don't think it's configuration problem unless there is something special about homebrew version of mysql.

**Comment by edyu** [comment]
Looking at the source code, I'm not seeing the code passing in "-D <database_name>" anywhere. Unless the code always prefix "use <database_name>;" before every SQL command, I don't see how it would work.

**Comment by edyu** [comment]
@josevalim what version of mysql are you using? I'm using 5.7.9 (the latest from homebrew).

**Comment by ericmj** [comment]
5.7.9 seems to have some issues with the mysql driver: https://github.com/xerions/mariaex/issues/83

**Comment by liveforeverx** [comment]
I've released 0.6.1 now. It is has support now for MySQL 5.7.

**Comment by chrismccord** [comment]
@edyu please jump on mariax 0.6.1 and report back. I don't think there's an issue to clear up on the phoenix side, so if you still have issues, we should follow up on the meriaex repo or Ecto side. Thanks!

**Comment by edyu** [comment]
@chrismccord how do I deal with the dependency hell? Pretty much every dependency is somewhat "out of date" in that mariaex 0.4.3 is pulled down (not even 0.5.x). How do I update mariaex to 0.6.1? I guess there is an easy way but I don't know how. Thank you.

**Comment by liveforeverx** [comment]
@edyu : Add to toplevel application: `{:mariaex, "~> 0.6.1", override: true}`

**Comment by edyu** [comment]
@liveforeverx woot, that worked. Thank you. I'll update the other bug as well with your comment. Thank you.
