### ISSUE TITLE
Please update the mariaex dependency to 0.6.1 to work with mysql 5.7.9

### ISSUE THREAD

**Issue by edyu** [phoenixframework/phoenix#1397]
The default homebrew version of mysql is 5.7.9 which mariaex 0.6.1 would work but phoenix needs to update the dependencies in order for 0.6.1 to be pulled down as part of mix deps.get. 
The phoenix-ecto may need to update to use the newer version of mariaex.

**Comment by edyu** [comment]
The current workaround from bug #1395 
from @liveforeverx: 
Add(or replace) to toplevel application: {:mariaex, "~> 0.6.1", override: true}

**Comment by josevalim** [comment]
Nice that you solved it. Upcoming ecto versions will support that, it is already in master, for now you need to use override indeed!
