### ISSUE TITLE
Mix hangs when password is not present in database config

### ISSUE THREAD

**Issue by Ortuna** [phoenixframework/phoenix#1399]
Great work on the framework guys! :heart: :heart: 

This behavior was very hard to debug since I'm a newcomer to Phoenix.

Running `mix ecto.create` and `mix ecto.migrate` hangs the mix process with not warnings or errors when the configuration file is missing the password key or password is blank.
Coincidentally my password was not black, and changing it to the correct password allowed me to connect to the database. I believe there should be some type of error if ecto cannot connect to Postgres even without a password.

My faulty configuration:
```elixir
# Configure your database                                                  
config :prose, Prose.Repo,                                                 
  adapter: Ecto.Adapters.Postgres,                                         
  username: "username",                                                      
  password: "",                                                            
  database: "my_database",                                                   
  pool_size: 10                                                            
```

Similar results with but `ecto.migrate` does error with a missing `:password` key: 
```elixir
# Configure your database                                                  
config :prose, Prose.Repo,                                                 
  adapter: Ecto.Adapters.Postgres,                                         
  username: "username",                                                                                           
  database: "my_database",                                                   
  pool_size: 10                                                            
```

Additionally I would love to tackle this issue with some guidance.

ref #1346 -- may have fixed this, but not sure how to test out that branch locally

**Comment by chrismccord** [comment]
An incorrect password should definitely result in an error to the user, not hanging. Can you confirm any difference between `password: ""` and `password: "somethingobviouslynotcorrect"` ?

**Comment by Ortuna** [comment]
The `password: "somethingobviouslynotcorrect"` case does fail with an error on both `mix ecto.create` and `mix ecto.migrate`.

The `password: ""` case hangs as mentioned.

**Comment by ericmj** [comment]
@Ortuna Can you help us with some information to make it easier for us to reproduce?

What postgres version are you using? Also include the contents of the `pg_hba.conf` file, you can find it by running `SHOW hba_file;` in `psql`.

**Comment by Ortuna** [comment]
postgres version and build info:
` PostgreSQL 9.4.5 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 5.2.1-21ubuntu2) 5.2.1 20151003, 64-bit`

and the default `pg_hba.conf` file:

````
...snip...
# DO NOT DISABLE!
# If you change this first entry you will need to make sure that the
# database superuser can access the database using some other method.
# Noninteractive access to all databases is required during automatic
# maintenance (custom daily cronjobs, replication, and similar tasks).
#
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                peer
#host    replication     postgres        127.0.0.1/32            md5
#host    replication     postgres        ::1/128                 md5
````

**Comment by josevalim** [comment]
fixed in ecto
