### ISSUE TITLE
Need best way for phoenix umbrella applications

### ISSUE THREAD

**Issue by bajarmeh** [phoenixframework/phoenix#1406]
I'm beginner for phoenix framework. I liked this framework.
I Need best way for phoenix umbrella applications architecture.

like this:

apps/phoenix_core
apps/phoenix_cms
apps/phoenix_blog

Please help me.

**Comment by sevenseacat** [comment]
I don't think the issue tracker is the best forum to seek help working with Phoenix.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
