### ISSUE TITLE
Delete button generated in phoenix.gen.html not working

### ISSUE THREAD

**Issue by Hajto** [phoenixframework/phoenix#1408]
I have created fresh app with phoenix (v1.0.2) and Delete button is not working properly. It only appends # to address path on browser.

Appending to app.html.eex fixed the problem:
<script>require("web/static/js/app").App.run()</script>

But i can clearly see that there are two app.js being downloaded in browser sources debug widow.

I calso see that the script "phoenix_html.js" is being concatinated to one of the app files.

Here is stack post with this issue: http://stackoverflow.com/questions/34272706/delete-link-not-working-phoenix/34289440#34289440

**Comment by josevalim** [comment]
If you have this in your app.js, it should be automatically imported for you:

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/static/brunch/app.js#L14

**Comment by chrismccord** [comment]
If you are on windows, please see this discussion and the workaround:

https://github.com/phoenixframework/phoenix/issues/1319

Explicitly requiring your app module in a script tag in the layout is not required. This has been fixed on the latest version of brunch.

**Comment by josevalim** [comment]
Should we bump the brunch version installed by default with phoenix?

**Comment by josevalim** [comment]
In case we haven't yet, bumping and forcing folks to run the latest will be very helpful.

**Comment by josevalim** [comment]
Chris said he already bumped.
