### ISSUE TITLE
Gettext compile error with 1.1

### ISSUE THREAD

**Issue by zhangsoledad** [phoenixframework/phoenix#1411]
![b7040f66-4189-4ce1-99a8-1b9f39846813](https://cloud.githubusercontent.com/assets/3198439/11862165/a4c07464-a4c2-11e5-93ce-3816bc8a8f19.png)
![eec08480-d33f-4f7b-ad40-61ebdfa1804c](https://cloud.githubusercontent.com/assets/3198439/11862214/4b693a08-a4c3-11e5-8a4f-195ab53c550e.png)

**Comment by zhangsoledad** [comment]
![a04a416e-0024-405a-a38e-be59b3c18216](https://cloud.githubusercontent.com/assets/3198439/11862304/521fb89e-a4c4-11e5-90b0-a4de10db683e.png)

**Comment by tispratik** [comment]
Have you tried `mix deps.clean gettext`

**Comment by josevalim** [comment]
You are likely missing the Erlang-parsetools package. Some distributions break Erlang into multiple Packages so you need to install them manually. Elixir v1.2 will include a better error message.

Chris, let's change the title to mention gettext and leave this open to help others that will certainly stumble upon this (on my phone, sorry).

**Comment by zhangsoledad** [comment]
@josevalim thx, I miss some Erlang package, better error message is very helpful for beginner, i develop on mac, use brew is so easy, but on linux need more procedure, thank you for your nice job!!!

**Comment by franzejr** [comment]
Thanks for keeping this open. I just got this error and the title helped me! Fixed that installing `erlang-parsetools` mentioned by @josevalim.

**Comment by erikdsi** [comment]
I had the same error as zhang. After I installed erlang-parsetools I'm getting a different error: 
```
/usr/lib/erlang/lib/parsetools-2.1/include/yeccpre.hrl: no such file or directory
```
I tried to ls the directory but there was no /include directory inside parsetools-2.1 just a single directory called **ebin** inside /usr/lib/erlang/lib/parsetools-2.1.

I'm using ubuntu 14.04.3, Elixir 1.1.1 and OTP 18.

**Comment by zhangsoledad** [comment]
@erikdsi  try `sudo apt-get install erlang`
https://github.com/elixir-lang/gettext/issues/67

**Comment by josevalim** [comment]
You may need erlang-parsetools-dev or something of sorts in case they don't include headers in the sources.

**Comment by erikdsi** [comment]
@zhangsoledad that worked, thanks a bunch.

The installation page at the Phoenix website implies that Erlang comes with Elixir and as I could fire up the erl repl I had no idea.

**Comment by nathanhornby** [comment]
I had the same issue as @erikdsi . On my mac it did indeed come with Elixir, but in Ubuntu I had no such luck. Considering the ubiquity of Ubuntu servers I'd personally mention this - it stumped me for a while!

**Comment by walkr** [comment]
I had the same error, but it works now. I just had to install `erlang-parsetools`.

Here's my recipe for installing erlang:

```shell
$ wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
$ apt-get update
$ apt-get install erlang-base-hipe install erlang-dev install erlang-eunit erlang-parsetools
```

**Comment by he9lin** [comment]
thx all. just do `sudo apt-get install  erlang-parsetools` resolved this issue for me on my vagrant instance (ubuntu 14.04, Elixir 1.1.1 and OTP 18)

**Comment by FrontierPsychiatrist** [comment]
Installing `erlang-parsetools` and `erlang-dev` on my Ubuntu 15.10 machine resolved this issue for me.

**Comment by burhan** [comment]
The instructions here do not work on the latest LTS release:

```
$ sudo apt-get install erlang-parsetools erlang-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
erlang-dev is already the newest version (1:18.3-dfsg-1ubuntu3).
erlang-parsetools is already the newest version (1:18.3-dfsg-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ mix ecto.migrate                                 
Hex was built against against Elixir 1.0.5 and you are running 1.1.0-dev, please run `mix local.hex` to update to a matching version

== Compilation error on file lib/gettext/backend.ex ==
** (CompileError) lib/gettext/backend.ex:16: undefined function ::/2
    (elixir) expanding macro: Kernel.@/1
    lib/gettext/backend.ex:16: Gettext.Backend (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

==> gettext
could not compile dependency gettext, mix compile failed. You can recompile this dependency with `mix deps.compile gettext` or update it with `mix deps.update gettext`
```

**Comment by ericmj** [comment]
@burhan For some reason you are using an old development release (1.1.0-dev) of elixir. Try to update to a more recent, stable version.

**Comment by burhan** [comment]
@ericmj On a fresh install of 16.04, using the repository from `erlang-solutions.com`, I have the following issues when I try to upgrade:

```
$ apt-cache policy esl-erlang                           
esl-erlang:
  Installed: (none)
  Candidate: 1:18.3
  Version table:
     1:18.3 999
        999 http://binaries.erlang-solutions.com/ubuntu xenial/contrib amd64 Packages
$ apt-cache policy elixir      
elixir:
  Installed: (none)
  Candidate: 1.1.0~0.20150708-1
  Version table:
     1.1.0~0.20150708-1 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
$ sudo apt-get install esl-erlang
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 esl-erlang : Depends: libwxbase2.8-0 but it is not installable or
                       libwxbase3.0-0 but it is not installable
              Depends: libwxgtk2.8-0 but it is not installable or
                       libwxgtk3.0-0 but it is not installable
              Recommends: erlang-mode but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by zhangsoledad** [comment]
@burhan  you need install libwxgtk
```
sudo apt-get install -y libwxgtk3.0-dev
```

**Comment by burhan** [comment]
@zhangsoledad Its already installed:

```
$ sudo apt-get install -y libwxgtk3.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libwxgtk3.0-dev is already the newest version (3.0.2+dfsg-1.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by zhangsoledad** [comment]
i haven't try 16.04, seems there is no xenial dist for erlang 
https://groups.google.com/forum/#!topic/elixir-lang-talk/zobme8NvlZ4
maybe this can help you @burhan

**Comment by burhan** [comment]
The strange thing is if you go here `https://packages.erlang-solutions.com/erlang/` you'll see a deb for 16.04, but this doesn't install with the same dependency issue.

**Comment by ayaseangle** [comment]
@he9lin u r right.

**Comment by kephas** [comment]
`apt-file search yeccpre.hrl` told me the missing file is in `erlang-dev` on Debian
