### ISSUE TITLE
poison cannot encode the message from ecto

### ISSUE THREAD

**Issue by weejulius** [phoenixframework/phoenix#1413]
Hi,

 I add a validate_length in a schema, however the poison is failed to encode the message from the validation.

the error message:  unable to encode value: {"超过%{count}字符", [count: 20]}

phoenix version: 1.1

**Comment by Gazler** [comment]
Hi,

Could you please provide the view you are using to render the errors? You now need to call `Ecto.Changeset.traverse_errors` in Phoenix 1.1.

**Comment by weejulius** [comment]
sorr y for the missing

**Comment by josevalim** [comment]
Let's leave it open as others will certainly simple upon this. :)

**Comment by djdrzzy** [comment]
I definitely did just stumble upon this! Thanks for leaving it open! 😀
