### ISSUE TITLE
phoenix.gen.html --no-brunch and Delete button

### ISSUE THREAD

**Issue by jturner** [phoenixframework/phoenix#1414]
When creating a new app with --no-brunch and then using mix phoenix.gen.html to create new models produces an index with non-functioning Delete buttons. The /priv/static/js/app.js is empty and thus leaving the Delete button non-functional.

Should the app.js at least contain code to support the Delete button in the --no-brunch case? Or should it have a no javascript fall back?

**Comment by josevalim** [comment]
@jturner I think we should rather emit a warning or update the docs or leave comments on the generated app.js. I don't want to reimplement all JS code we may add if folks decide to not use brunch.

**Comment by jturner** [comment]
Sure, something to give the user an idea why it's not working would be helpful. By looking at a brunch based app I was able to find what file to look at to get the code from. Thanks
