### ISSUE TITLE
It's not possible to use macros in controllers 

### ISSUE THREAD

**Issue by ftaebi** [phoenixframework/phoenix#1420]
To demonstrate my usecase:

This is my macro module

    defmodule MyMacroMod do
      defmacro defsomething(head, body) do
        quote do
          def unquote(head) do
            unquote body[:do]
          end
        end
      end
    end

This is my controller

    defmodule Project.V1.MyController do
    use Phoenix.Controller
    import MyMacroMod

      defsomething arbitrary_function_name(conn) do
        ...
      end
    end

The compilation process will now fail with

    web/controllers/v1/cart_controller.ex:1: warning: redefining module Project.V1.CartController
    
    == Compilation error on file web/controllers/v1/cart_controller.ex ==
    ** (FunctionClauseError) no function clause matching in :lists.mapfoldl/3
        (stdlib) lists.erl:1352: :lists.mapfoldl(#Function<5.111138652/2 in :elixir_exp.expand_args/2>, %Macro.Env{aliases: [], context: :match, context_modules: [Project.V1.CartController], export_vars: nil, file: "path_to_project/web/controllers/v1/cart_controller.ex", function: {:show, 2}, functions: [{Phoenix.Controller, [accepts: 2, action_name: 1, allow_jsonp: 1, allow_jsonp: 2, clear_flash: 1, controller_module: 1, delete_csrf_token: 0, endpoint_module: 1, fetch_flash: 1, fetch_flash: 2, get_csrf_token: 0, get_flash: 1, get_flash: 2, get_format: 1, html: 2, json: 2, layout: 1, layout_formats: 1, protect_from_forgery: 1, protect_from_forgery: 2, put_flash: 3, put_format: 2, put_layout: 2, put_layout_formats: 2, put_new_layout: 2, put_new_view: 2, put_secure_browser_headers: 1, put_secure_browser_headers: 2, put_view: 2, redirect: 2, render: 1, render: 2, render: 3, render: 4, router_module: 1, scrub_params: 2, text: 2, view_module: 1, view_template: 1]}, {Plug.Conn, [assign: 3, async_assign: 3, await_assign: 2, await_assign: 3, chunk: 2, clear_session: 1, configure_session: 2, delete_req_header: 2, delete_resp_cookie: 2, delete_resp_cookie: 3, delete_resp_header: 2, delete_session: 2, fetch_cookies: 1, fetch_cookies: 2, fetch_query_params: 1, fetch_query_params: 2, fetch_session: 1, fetch_session: 2, get_req_header: 2, get_resp_header: 2, get_session: 2, halt: 1, merge_resp_headers: 2, put_private: 3, put_req_header: 3, put_resp_content_type: 2, put_resp_content_type: 3, put_resp_cookie: 3, put_resp_cookie: 4, put_resp_header: 3, put_session: 3, put_status: 2, read_body: 1, read_body: 2, register_before_send: 2, resp: 3, send_chunked: 2, send_file: 3, send_file: 4, send_file: 5, ...]}, {Kernel, [!=: 2, !==: 2, *: 2, +: 1, +: 2, ++: 2, -: 1, -: 2, --: 2, /: 2, <: 2, <=: 2, ==: 2, ===: 2, =~: 2, >: 2, >=: 2, abs: 1, apply: 2, apply: 3, binary_part: 3, bit_size: 1, byte_size: 1, div: 2, elem: 2, exit: 1, function_exported?: 3, get_and_update_in: 3, get_in: 2, hd: 1, inspect: 1, inspect: 2, is_atom: 1, is_binary: 1, is_bitstring: 1, is_boolean: 1, is_float: 1, is_function: 1, is_function: 2, is_integer: 1, ...]}], lexical_tracker: #PID<0.437.0>, line: 9, macro_aliases: [], macros: [{MyMacroMod, [defguarded: 2]}, {Phoenix.Controller.Pipeline, [plug: 1, plug: 2]}, {Kernel, [!: 1, &&: 2, ..: 2, <>: 2, @: 1, alias!: 1, and: 2, binding: 0, binding: 1, def: 1, def: 2, defdelegate: 2, defexception: 1, defimpl: 2, defimpl: 3, defmacro: 1, defmacro: 2, defmacrop: 1, defmacrop: 2, defmodule: 2, defoverridable: 1, defp: 1, defp: 2, defprotocol: 2, defstruct: 1, destructure: 2, get_and_update_in: 2, if: 2, in: 2, is_nil: 1, match?: 2, or: 2, put_in: 2, raise: 1, raise: 2, reraise: 2, ...]}], module: Project.V1.CartController, requires: [Kernel, Kernel.Typespec, MyMacroMod, Phoenix.Controller, Phoenix.Controller.Pipeline, Plug.Conn], vars: [conn: 689]}, MyMacroMod)
        (elixir) src/elixir_map.erl:11: :elixir_map.expand_map/3
        (stdlib) lists.erl:1353: :lists.mapfoldl/3
        (stdlib) lists.erl:1354: :lists.mapfoldl/3
        (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
        (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in  Kernel.ParallelCompiler.spawn_compilers/8

**Comment by chrismccord** [comment]
Can you please provide a project (or full gist) that recreates this? I think we are missing some code to fully diagnose your error, but I"m confident that it is not `Phoenix.Controller` related. Thanks!

**Comment by ftaebi** [comment]
Thanks, i created a minimal test project with the current phoenix version and my version (1.0.3). The problem did not occur in both cases. So it has to be an interference with something else.
