### ISSUE TITLE
Do not find templates by path

### ISSUE THREAD

**Issue by ericmj** [phoenixframework/phoenix#1423]
This is the only instance in any Elixir project where I have found that code is searched for in the filesystem instead of letting the compiler figure it with module names.

The convention of searching by path is confusing to users because it happens rarely in Elixir and I feel it is against the spirit of Elixir and Phoenix due to it being a bit too much magic.

There are other solutions that makes the search explicit or uses module names instead file names. For example a `@template_path` attribute in the view or the template being a sub namespace of the view.

**Comment by josevalim** [comment]
We already have a configuration called `:root` that does exactly this. We can't let the compiler figure this one out, so we need a convention, it must either be the module name (camelcase) or the snake case version and we chose the snake one as we typically don't start directories in uppercase.

**Comment by michalmuskala** [comment]
I think the main issue is that this convention is implicit. I think what @ericmj proposes would be to make it explicit and, for instance, as a default generate the `:root` configuration inside the view.

**Comment by ericmj** [comment]
Yes, exactly what @michalmuskala said.

**Comment by chrismccord** [comment]
> as a default generate the :root configuration inside the view.

This is explicitly generated in web.ex's `view` block. I think including it every view would be overkill since it is never going to change.

**Comment by chrismccord** [comment]
`root:` is also different in this context. What @ericmj and @michalmuskala are asking for is is a root setting per view, where the root setting today is the "mount" point for all views in the system. We debated this way back if you search the issues, and honestly I think an explicit, direct path per view module would be more work, and more error prone than what we have today.

**Comment by michalmuskala** [comment]
Because I'm not using html templates day-to-day, I think I misunderstood the `:root` configuration. That is not what I meant. The problem is that `UserView` implies looking for templates in `root/user`, and `FooBarView` in `root/foo_bar`. The proposal would be to have the `user` and `foo_bar` subpath in the view explicitly, instead of implicitly figured out from the view module's name.

**Comment by chrismccord** [comment]
@ericmj or @michalmuskala can you show code of what you would like to see. Is it something like:

```elixir
defmodule MyApp.PageView do
  use MyApp.Web, dir: "web/templates/page"
end
```

I still feel our current solution is the better option, and is one of the few times where implicit lookup is okay (even though we set the root explicitly in web.ex). If we have some code to talk around this might be easier :)

**Comment by michalmuskala** [comment]
What I imagine could be either what you propose, or we could keep the `:root` configuration, and add additional `:path` one:

```elixir
defmodule MyApp.Web do
  def view(opts) do
    quote do
      use Phoenix.View, Keyword.merge(root: "web/templates", unquote(opts))
      # ...
    end
  end

  # ...
end
```

```elixir
defmodule MyApp.PageView do
  use MyApp.Web, :view, path: "page"
end
```

This would also mean we could simplify this: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/view.ex#L120-L147 to something like:

```elixir
  defmacro __using__(options) do
    if root = Keyword.get(options, :root) && path = Keyword.get(options, :path) do
      quote do
        import Phoenix.View

        use Phoenix.Template, root: Path.join(unquote(root), unquote(path))

        @view_resource String.to_atom(Phoenix.Naming.resource_name(__MODULE__, "View"))

        @doc "The resource name, as an atom, for this view"
        def __resource__, do: @view_resource
      end
    else
      raise "expected :root and :path to be given as options"
    end
  end
```

**Comment by paulcsmith** [comment]
This is one of those things where I think having the convention leads to better directory structure (easier to get started when you hop on a project and know where things are) and less typing. Kind of like REST makes it easier to reason about controller and routes because we have a uniform interface. This convention makes things easier to organize and reason about IMO

**Comment by josevalim** [comment]
I am :-1: because of the reasons said above. We put a lot of thoughts into the implicit/explicit discussion but I believe this is one of the cases where implicit is worth because, once you figure out the rule, it makes your life much easier.

**Comment by trans** [comment]
Did anything ever come of this? I have a view called `CoCView` and it converts that to `co_c`, but obviously I want it to be `coc`. I'm fairly new to Phoenix and I've been fighting the auto-magic for a couple of hours now, without a solution yet.
