### ISSUE TITLE
Error following "up and running" instructions

### ISSUE THREAD

**Issue by babakness** [phoenixframework/phoenix#1425]
Hello--I'm following the instructions at http://www.phoenixframework.org/docs/up-and-running

```mix phoenix.server```

Gives me this error

```
== Compilation error on file lib/phoenix/code_reloader.ex ==
** (CompileError) lib/phoenix/code_reloader.ex:61: function full_path/1 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6

could not compile dependency :phoenix, "mix compile" failed. You can recompile this dependency with "mix deps.compile phoenix", update it with "mix deps.update phoenix" or clean it with "mix deps.clean phoenix"
```

I am an absolute beginner and just want to learn more about Phoenix. I'm running this on a Mac OSX Yosemite machine.

**Comment by chrismccord** [comment]
You are on an old version of phoenix, please follow the instructions here to jump on the latest:
http://www.phoenixframework.org/docs/installation

From there, you should be able to regenerate a new project and you'll be all set. 

> I am an absolute beginner and just want to learn more about Phoenix.

Welcome! :)

In the future, please submit support requests to the phoenix-talk mailing list
http://www.phoenixframework.org/docs/installation

Welcome aboard!
