### ISSUE TITLE
Rendering raw changeset errors with phoenix_ecto 2.0

### ISSUE THREAD

**Issue by aerosol** [phoenixframework/phoenix#1428]
Bumping `phoenix_ecto` to 2.0, crashes Phoenix 1.0.4 templates rendering form errors, when the `message` is a tuple coming from, for example, `validate_length` check.

I found the breaking commit here: https://github.com/phoenixframework/phoenix_ecto/commit/90436c97cd2883513743313e3660d6bc40f1b4a8

Phoenix crashes with:

```
no function clause matching in Phoenix.HTML.Safe.Tuple.to_iodata/1
```

I understand this is due the in-the-works gettext support. 

Can error traversing be handled within Phoenix.HTML making [this test](https://github.com/phoenixframework/phoenix_ecto/blob/master/test/phoenix_ecto/html_test.exs#L74-L85)'s assumptions no longer valid? 

Please let me know what can I do to stay with the most recent Ecto release and I'll work on a PR that's relevant.

cc @radar @zoldar

**Comment by aerosol** [comment]
Sorry I just found [this]( https://github.com/phoenixframework/phoenix/commit/ed3eb4c45bd3a1e5b56deef7c363c258782a0e2c), I guess I'll try keeping up with the master.

**Comment by aerosol** [comment]
(I would be grateful for a rationale behind this not being a part of Phoenix.HTML though)

**Comment by chrismccord** [comment]
> (I would be grateful for a rationale behind translate_errors not being a part of Phoenix.HTML though)

Localization is also important for API only applications, so this applies beyond Phoenix.HTML

**Comment by aerosol** [comment]
Thanks, makes sense

On Sat, Dec 26, 2015, 4:35 AM Chris McCord <notifications@github.com> wrote:

> (I would be grateful for a rationale behind translate_errors not being a
> part of Phoenix.HTML though)
>
> Localization is also important for API only applications, so this applies
> beyond Phoenix.HTML
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1428#issuecomment-167274816>
> .
>
-- 
/A.
