### ISSUE TITLE
Truncate String function helper

### ISSUE THREAD

**Issue by victorlcampos** [phoenixframework/phoenix#1430]
Hi guys,
in RoR we have String#truncate that helps alot: https://github.com/rails/rails/blob/db69474b553c0619d1e86346a889d14fd825f19f/activesupport/lib/active_support/core_ext/string/filters.rb#L65

It will be nice that we can have this in Phoenix:
https://gist.github.com/victorlcampos/cb81c68f093d825d30fb

What do you think?

**Comment by chrismccord** [comment]
Please submit feature requests to the phoenix-talk mailing list for discussion. We reserve the issues list for core bug fixes/development. Thanks!

**Comment by doomspork** [comment]
@victorlcampos you can find `#truncate` in Crutches which is an ActiveSupport port to Elixir: [String#truncate/3](http://hexdocs.pm/crutches/Crutches.String.html#truncate/3).

Doubt it makes sense to added these helpers to Phoenix anyways.

**Comment by victorlcampos** [comment]
@doomspork, thx, I did not know Crutches...
@chrismccord, sry, I open here because of this comment in Readme: "We usually keep a list of features and bugs in the issue tracker."

**Comment by chrismccord** [comment]
I'm undecided right now on how far we want to push helpers in phoenix_html. For now, we'd like to keep it lean and let other libraries be used, since it is all simple function imports. One thing I'll note is I would avoid Crutches as you don't need such a heavy dependency for a single truncate function.

**Comment by victorlcampos** [comment]
@chrismccord, agree!
