### ISSUE TITLE
Proposal: auto generate models from existing database

### ISSUE THREAD

**Issue by aesmail** [phoenixframework/phoenix#1431]
It would be extremely helpful if phoenix had this option. It would be something similar to django's [inspectdb](https://docs.djangoproject.com/en/1.9/howto/legacy-databases/#auto-generate-the-models) command, where the framework would inspect the database schema and generates the appropriate models. This eases the transition to phoenix for existing apps that were written in a different framework.

Personally, I needed this feature a lot to save time and effort regenerating an already-existing schema. It's not a perfect solution, but it's extremely faster and less error-prone than when manually rewriting the models.

Having the database information already set in the config.exs file, the command might look something like this:

`mix phoenix.gen.schema <database_name>`

This could be the equivalent of multiple `mix phoenix.gen.model <table_name>` commands for every table found in the database.

Thoughts?

**Comment by chrismccord** [comment]
Please direct feature request to the mailing list. We reserve the issue tracker to bugs and active feature development. This sounds like a great third-party library (nudge nudge :), but not something for core to maintain. Thanks!

**Comment by aesmail** [comment]
Thank you Chris and sorry for posting in the wrong place. I got your hint ;). It would be an interesting challenge.
