### ISSUE TITLE
Add --no-primary-key support to migration generator

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1434]
This will be useful for upcoming many to many in Ecto:

    mix phoenix.gen.migration posts_tags post_id:references:posts tag_id:references:tags --no-primary-key

Contributions are welcome!

**Comment by jespr** [comment]
There isn't any `phoenix.gen.migration` mix task as it is right now, right? So you would want that to be introduced, with an optional `--no-primary-key`?

**Comment by josevalim** [comment]
Doh, I am sorry. I am not sure the best way to proceed then. Adding a `phoenix.gen.migration` task would copy the efforts from ecto. On the other hand, adding the migration features from Phoenix to Ecto sounds like too much to have in Ecto. Thoughts?

**Comment by chrismccord** [comment]
Perhaps the happy medium is to support `--no-model` for `phoenix.gen.html/json/model` ?

**Comment by jespr** [comment]
Either that - or move the migration creation from `phoenix.gen.model` in to `phoenix.gen.migration` - and have `phoenix.gen.model utilize that when creating migrations

That way you would be able to call `phoenix.gen.migration` externally as well - and it wouldn't copy efforts from ecto as far as I can see?

**Comment by chrismccord** [comment]
I don't wan't to duplicate ecto's task for only a single flag, so I am :-1: on a phoenix.gen.migration task unless we have a better reason to deviate

**Comment by jespr** [comment]
The simple approach would be better, I agree. The only thing I'm worried about, is that `mix phoenix.gen.model PostTag post_tags post_id:references:posts --no-model` might seem a bit confusing? And would there be use cases for having the `--no-model` flag for `phoenix.gen.html`?

**Comment by josevalim** [comment]
@chrismccord we have already copied Ecto's task, except today Ecto's task is inside `phoenix.gen.model`. So after thinking about it a bit, I would add `phoenix.gen.migration migration_name attributes --no-primary-key`. I think it is the best way to go.

**Comment by josevalim** [comment]
Actually, ignore me, I am wrong. Providing both tasks would be confusing. On the other hand, providing `--no-model` to the model generator would also be confusing and providing `--no-primary-key` as well because it only makes sense to have no primary key when you have no model. I think this is too confusing right now to justify the games, so I am voting to close this.

@jespr thanks for pointing out the flaws in my proposal. :)

**Comment by chrismccord** [comment]
> I think this is too confusing right now to justify the games, so I am voting to close this.

Agreed. The only other option I can think of is to have a task specific to many-to-many, i.e. `mix phoenix.gen.many_to_many posts_tags post_id:references:posts tag_id:references:tags`

**Comment by josevalim** [comment]
Yeah, lets close this for now then. Thanks everyone
