### ISSUE TITLE
Router paths that don't start with forward slash should raise

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1438]
This regression popped in somewhere

**Comment by princemaple** [comment]
Does it include `resources`? Many examples of `resources` in the [guide](http://www.phoenixframework.org/docs/routing) are without the leading `/`.

**Comment by chrismccord** [comment]
Yes, those examples should be fixed. Thanks!

**Comment by tracehelms** [comment]
First time contributor here. This one doesn't sound too hard and I'd like to help out. Is this as easy as adding some sort of validation on [this method](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/router/route.ex#L35)?

**Comment by chrismccord** [comment]
Thanks @tracehelms , but since this is a breaking change, we have to hold off for now.

**Comment by tracehelms** [comment]
Ok, thanks for the quick response! I'll see if there's something else I can help with.

**Comment by josevalim** [comment]
Chris, it is fine as long as we just warn (and not raise).

On Thursday, February 18, 2016, Trace Helms <notifications@github.com>
wrote:

> Ok, thanks for the quick response! I'll see if there's something else I
> can help with.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1438#issuecomment-185837240>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
@tracehelms José is right, we can warn in such cases for now ([example](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/test/conn_test.ex#L121-L124)), so please go ahead. Your initial intuition on where to begin was correct :)

**Comment by ericmj** [comment]
What's the reason for the forward slash requirement?

**Comment by chrismccord** [comment]
> What's the reason for the forward slash requirement?

Just for consistency. It's something we used to enforce, but was accidentally removed. It's nice to say anywhere you use a path, the forward slash prefix is required. For example, we already enforce this on the static_path helpers. https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/adapter.ex#L220-L222

 Also, so we don't end up with:

```elixir
scope "api" do
  resources "/users", UserController do
    get "scores", ScoreController
  end
end
```

**Comment by ericmj** [comment]
Wouldn't it be better to enforce no forward slash? We get the same consistency and we type one less character.

**Comment by chrismccord** [comment]
Personally I prefer the slash, especially for the router, because it implies they are path segments, and composable. Without the slash they could be mistaken as named identifiers (that's a stretch, but you get the idea):

```elixir
scope "/api" do
  resources "/users", UserController do
    get "/scores", ScoreController
  end
end
```

The above paths compose to "/api/users/:user_id/scores"

**Comment by tracehelms** [comment]
Just saw this message. I'll get started today.

**Comment by tracehelms** [comment]
Hey @chrismccord, I started working on this at the `Route.build` level, but realized that by that point all of the `/` are stripped out, [as seen here](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/router/scope.ex#L27). 

Does it make sense to move the warning to be logged in [this function](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/router/scope.ex#L21) instead? From what I can tell, http verb helpers (`get, post, etc`), `match`, `forward`, `trace`, `options`, `connect`, and `resources` all go through that function. The only thing that doesn't is `scope`.
