### ISSUE TITLE
"You must restart your server after changing the following configuration files" in umbrella app

### ISSUE THREAD

**Issue by chncdcksn** [phoenixframework/phoenix#1439]
I'm on Windows 10, Elixir 1.1.1, and Phoenix 1.1.1. I've also reproduced this error in Linux, so it isn't a Windows exclusive error. If this is a Mix issue I can recreate the report there. This will set up an umbrella app that will error when going to `localhost:4000` in your browser.

    $ mix new umbrella --umbrella
    $ cd umbrella/apps
    $ mix phoenix.new testphoenix
    $ cd ../
    $ mix phoenix.server

And this is the error given.

    [error] #PID<0.323.0> running Testphoenix.Endpoint terminated
    Server: localhost:4000 (http)
    Request: GET /
    ** (exit) an exception was raised:
        ** (RuntimeError) you must restart your server after changing the following configuration files:

      * _build/dev/lib/testphoenix/.compile.lock
      * mix.exs
      * config/config.exs
      * config/dev.exs
      * config/prod.exs
      * config/prod.secret.exs
      * config/test.exs

            (phoenix) lib/phoenix/code_reloader/server.ex:20: Phoenix.CodeReloader.Server.reload!/1
            (phoenix) lib/phoenix/code_reloader.ex:47: Phoenix.CodeReloader.call/2
            (testphoenix) lib/testphoenix/endpoint.ex:1: Testphoenix.Endpoint.phoenix_pipeline/1
            (testphoenix) lib/plug/debugger.ex:92: Testphoenix.Endpoint."call (overridable 3)"/2
            (testphoenix) lib/phoenix/endpoint/render_errors.ex:34: Testphoenix.Endpoint.call/2
            (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
            (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

**Comment by chrismccord** [comment]
Can you push a project that recreates this to github for me to attempt to isolate? Thanks!

**Comment by chncdcksn** [comment]
No problem. https://github.com/chncdcksn/phoenix_umbrella_error
