### ISSUE TITLE
Elixir fails to compile templates when a different machine hasn't compiled new routes

### ISSUE THREAD

**Issue by leolorenzoluis** [phoenixframework/phoenix#1454]
I encountered this issue when trying to pull changes from a different machine. After pulling changes from GitHub, one of the changes I have in the template is 

    <%= link "Test", to: test_path(@conn, :index) %>

The problem is, since this machine hasn't compiled its new routes from the previous machine, then elixir won't compile and complain that  **undefined function test_path/2**

Quick fix is to remove that new path in the template and recompile using **mix phoenix.routes**. 

This is acceptable for one change but if there are multiple new routes that are linked in templates, then it would cost the productivity of the developer.

**Comment by josevalim** [comment]
Restarting the application should be all that is required in this case. You don't need to run "mix phoenix.routes" because it does not do anything in particular to your routes besides compiling them in the same way calling "mix phoenix.server" again would.

**Comment by leolorenzoluis** [comment]
I did call mix phoenix.server but it didn't successfully recompile.

**Comment by chrismccord** [comment]
Were you using an editor plugin that does syntax checking or linting? Some plugins have been known to cause issues because they compile the elixir files on save, causing the changes to not be picked up by the code reloader. It would also cause the app to appear to not compile when the server is restarted.

**Comment by leolorenzoluis** [comment]
No, not using any plugins at all. I will try again when I get a chance if I can reproduce this to another VM. I'm pretty sure it didn't recompile because of the routes issues but I'll retest it.

**Comment by chrismccord** [comment]
You mentioned a VM. Were you happening to be using a VM with a shared volume where you were editing the source from the host, but hosting the elixir server on the VM? This has been known to cause compile issues with different ctimes

**Comment by leolorenzoluis** [comment]
No, it's a different volume. I am just using VMs. I spinned off a new VM as a new dev environment and just git pulled.
