### ISSUE TITLE
Continue instrumenting the controller/channel

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1455]
We need to instrument the action dispatch and use the information in logging instead of `Phoenix.Controller.Logger`. We also need to revisit how to enable/disable logger because the API today is through `use Phoenix.Controller, log: false` which is not accessible through `web/web.ex`.

**Comment by chrismccord** [comment]
Do we need to make the options accessible? Since web.ex has no magic, a user could define their own new clause for specialized controllers for these cases, imo. Thoughts?

**Comment by chrismccord** [comment]
They can also `use Phoenix.Controller, log: false` directly and forgo web.ex. Since the `log: false` is an edge case, and we pass no other options regularly, I'm for leaving web.ex as is.

**Comment by josevalim** [comment]
I don't think they are OK options but we could probably do a better job, possibly something that also works per action.

**Comment by chrismccord** [comment]
For web.ex, what about:

```elixir
use MyApp.Web, {:controller, log: false}
...
def controller(opts) do
  quote do
    use Phoenix.Controller, unquote(opts)
    import MyApp.Router.Helpers
    import MyApp.Gettext
  end
end

defmacro __using__({which, opts}) when is_atom(which) do
  apply(__MODULE__, which, [opts])
end
defmacro __using__(which) when is_atom(which) do
  apply(__MODULE__, which, [[]])
end
```

**Comment by josevalim** [comment]
I would rather have `use MyApp.Web, type: :controller, log: false` but I don't like how it makes everything more complex, more unquote, etc. The simpler, the best.

**Comment by chrismccord** [comment]
@josevalim for the tuple case, it would allow the existing usage, with an option to use a tuple for these edge cases. I don't like `:type` because what if `:type` becomes an option you need to pass down to the using module? The tuple keeps things segregated and only would be used as needed, otherwise `use App.Web, :controller`

**Comment by michalmuskala** [comment]
Why not two arguments?

```elixir
use MyApp.Web, :controller, log: false
#...
def controller(opts) do
  quote do
    use Phoenix.Controller, unquote(opts)
    import MyApp.Router.Helpers
    import MyApp.Gettext
  end
end

defmacro __using__(which, opts // []) when is_atom(which) and is_list(opts) do
  apply(__MODULE__, which, [opts])
end
```

**Comment by chrismccord** [comment]
`use` only accepts 1 argument. We've decided to not change anything with web.ex, but we're going to revisit controller logging behavior.
