### ISSUE TITLE
Update Phoenix website

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1460]
We need to:
- [x] List companies using Phoenix in production
- [ ] Promote the book
- [ ] Overhaul the guides

**Comment by novabyte** [comment]
@josevalim We use Phoenix at [Heroic Labs](https://heroiclabs.com). :smile:

**Comment by doomspork** [comment]
Not sure if it's helpful or not but I've been maintaining a list of companies using Elixir (and Phoenix) in production: https://github.com/doomspork/elixir-companies

**Comment by josevalim** [comment]
That is extremely helpful. :)

**Comment by ndeet** [comment]
On the top right the widget where you currently see the latest 1.1.2 release, that thing does nothing :) I would expect after selecting a version I will get release notes or at least to the github release page? Selecting "view all versions" brings me to an overview, where every click on a link brings me back to the home page. 
Tested with Chrome 47 

... oh and I looked into the source and saw some spooky ng- prefixed classnames and some commented js code ^^  *ishowmyselfout*

**Comment by chrismccord** [comment]
readme hosts our guides and it sounds like that feature is broken on their end so there isn't anything for us to fix in this case. Thanks!

**Comment by davejlong** [comment]
Phoenix drives our Twilio integrated phone system at [Cage Data](http://cagedata.com). Handles voicemails and conference calling.

**Comment by ybur-yug** [comment]
@josevalim I'd love to contribute to the guides. Be it working on a section/expanding it or simply proofreading in general. I commented on another issue as well -- I'd love to contribute a bit. I've been lucky enough to be working almost exclusively in Elixir/Phoenix the last few months and I'm starting to feel comfortable enough to hopefully be useful :smile:

**Comment by josevalim** [comment]
@ybur-yug that's exciting to hear! We really need someone to help us with the guides, there are a lot of issues open and contributions but we haven't had the time to maintain it. The repository is here: https://github.com/phoenixframework/phoenix_guides

Let us know if you have any questions!

**Comment by ybur-yug** [comment]
@josevalim Awesome, I'll poke around the issues and get a feel for where I could give the most useful help.

**Comment by 19smitgr** [comment]
I don't think it's very important, but there's a typo on the blog page of the Phoenix website. Just take out the "i" in: `mix phoeinix.server`

**Comment by Gazler** [comment]
@19smitgr Thanks for raising it. Should be fixed now.

**Comment by sashaafm** [comment]
@19smitgr and @Gazler I had warned about that typo in the Phoenix Guides repo because there was the same typo in another page (I think Lance took care of it). Maybe it's a recurring problem in several pages?

**Comment by 19smitgr** [comment]
I don't think it is because searching `url:phoenixframework.com "phoeinix"` on Google doesn't return anything other than what he just fixed.

**Comment by rstacruz** [comment]
> Overhaul the guides

what sort of help do you guys need with this one? I happen to love writing documentation and building UI design ;)

**Comment by chrismccord** [comment]
We mainly will focus on updating the guides to include missing pieces around features that materialized after the guides were written – generators, more in depth channel usage, presence, etc. We will also be introducing changes to generators with Phoenix 1.3, so hang tight for now, but I appreciate the willingness to help!

**Comment by josevalim** [comment]
@chrismccord one of the plans was also to eventually move to ExDoc guides too. :)

**Comment by Gazler** [comment]
@josevalim @chrismccord https://github.com/phoenixframework/phoenix_guides/issues/391 is the related issue.

**Comment by BenBals** [comment]
I, as someone learning Phoenix, found it extremely helpful to get to know about the way the abstractions work. It was confusing for me to get told "this is the view, it handles preparations for rendering", but not what a view actually *is*. It was very insightful, when @josevalim said in a podcast that it's just a module exposing a `render` function. That makes working with it so much easier. Knowing not only the abstract ideas, but the actual rules and properties of a `view` module. Such information should be easier to get than stumbling upon it in a podcast.

I hope you get what I am trying to say. I would be pleased to find such information in the future guides.

**Comment by brazford** [comment]
How do I contribute to documentation? Write an issue? Create a pull request? I'm just starting out with phoenix, and there's no better time to correct the small stuff.

**Comment by xanderdunn** [comment]
Doing a Google search for [phoenix getting started](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=phoenix%20getting%20started) gives this ancient getting started page from x0.10.0 (March 2015).  As that's a super common search term for beginners, it should provide useful results.

**Comment by diego4serve** [comment]
Please in the official guides consider using syntax highlighting on example code like hexdocs.pm

**Comment by chrisarcand** [comment]
I just stumbled upon this issue after having opened https://github.com/phoenixframework/phoenix_guides/issues/663 a few days ago. Many of my frustrations are shared by multiple people in this [now old] issue, including the old 0.10.0 docs, readme.io annoyances, etc :)

@josevalim @chrismccord I also note the guides haven't been committed to almost three months; Do you need another maintainer to help...? I opened the issue to ask about these weirdnesses but if you literally need someone to sort out said weirdnesses I totally understand and that's a different matter :) How readme.io and website connect with the ex_doc is what's hidden to me right now.

**Comment by josevalim** [comment]
@chrisarcand I believe we are ditching readme.io and moving all the guides to ex_doc. The reasons the guides have been low in commits is because with the work on v1.3.0 we will have to rewrite a good part of the docs to provide the best experience. So there is a lot of work waiting for v1.3.0 to be out.

**Comment by chrisarcand** [comment]
@josevalim Awesome. Thanks for the clarification!

**Comment by inoas** [comment]
### Site throws debug info / error

Took a look at Diesel (Rust) realized it is soo far from SQL for my taste (I like CakePHP3 ORM and Arel) wanted to see if Phoenix/Ecto are closer to SQL-'think': Got this error instead:

![img_3401](https://cloud.githubusercontent.com/assets/20972207/24327498/5b6bb3e4-11d3-11e7-9333-60efbaf2125a.PNG)
![img_3402](https://cloud.githubusercontent.com/assets/20972207/24327500/5b918182-11d3-11e7-8f0d-2ea774391ea8.PNG)
![img_3403](https://cloud.githubusercontent.com/assets/20972207/24327499/5b8fb122-11d3-11e7-8377-91604cc13b74.PNG)
![img_3404](https://cloud.githubusercontent.com/assets/20972207/24327501/5b927ca4-11d3-11e7-9bd9-e6e01c018c91.PNG)

**Comment by shdblowers** [comment]
we use Elixir Phoenix at [Findmypast](http://www.findmypast.com/)

**Comment by dczombera** [comment]
Regarding companies using Elixir,  [Solaris Bank ](https://www.solarisbank.de) uses Elixir for its backend. It's a new bank with a modern stack which offers an API powered financial platform . I don't work for them but I used to use their API.

**Comment by alexfromvl** [comment]
There is a request to add language translations to the site. I would be happy to join the project of translating documentation into different languages.

**Comment by chrismccord** [comment]
Translations will have to be put on hold until at least the major overhaul dust settles. Thanks for the interesting in helping out!

**Comment by udaysinghcode** [comment]
Hey everybody! 

Big fan of Phoenix + the community on Slack is just so friendly and great. @chrismccord + team you've really made something special here. 

Quick question for you all:

Is there a need to update the site to provide documentation for the state of the release candidate? We had a big discussion about contexts and accounts, and although everything isn't hashed out yet - would it make sense to add a little bit about them on the site? I totally get if the site is just meant for the stable build, but it would be nice to have a place to read more about 1.3.x rather than hunt through the blogosphere.

Happy to do so if required!

**Comment by chrismccord** [comment]
We are working on the 1.3 guides now and will release them soon with 1.3 final. Hang tight!

**Comment by jeroenbourgois** [comment]
@chrismccord just to get an idea, is soon something like in the next few weeks or more the next few months? I do *not* want to be rude, but we are kicking off a new project and it if we are talking in weeks we might just wait a bit more to start with the final 1.3

**Comment by Gazler** [comment]
Closing as the site now has its own repo.
