### ISSUE TITLE
JSON response formatted in reverse alphabetical order

### ISSUE THREAD

**Issue by msurekci** [phoenixframework/phoenix#1466]
http://hexdocs.pm/phoenix/Phoenix.Controller.html#json/2

This function returns any JSON passed to it in reverse alphabetical order. Is it possible to format the JSON response and have it spit it out the way you like?

For example if I pass the following as the second argument:
```
{
  a: 1,
  b: 2
}
```

It will return:
```
{
  b: 2,
  a: 1
}
```

**Comment by Gazler** [comment]
Maps are an unordered data structure. This is also true for JSON objects. If you have a look at http://stackoverflow.com/questions/4515676/keep-the-order-of-the-json-keys-during-json-conversion-to-csv it will explain further.

If you wish to maintain the order then you should consider using a list/array.

Please direct questions to the mailing list in future.
