### ISSUE TITLE
clarify PubSub semantics around a pid joining a topic multiple times

### ISSUE THREAD

**Issue by adamkittelson** [phoenixframework/phoenix#1474]
It looks like the behavior at present is that a pid can subscribe to a pubsub topic multiple times, and will receive multiple broadcasts if it does so, and unsubscribing will remove all subscriptions to the topic for that pid.

https://gist.github.com/adamkittelson/60919b8bb70651f1ca7d

I brought it up in irc and Jose asked me to open an issue so you can nail down the semantics you want and test them to avoid changes having them change unexpectedly in a future refactoring.

**Comment by chrismccord** [comment]
dup of #1473
