### ISSUE TITLE
Phoenix returns lower-cased HTTP headers breaking jQuery auto-parsing

### ISSUE THREAD

**Issue by qertoip** [phoenixframework/phoenix#1476]
Lowercase HTTP headers used by Phoenix are perfectly fine according to RFC 7230 but not very practical in the real world.

For one they break jQuery auto-parsing as it assumes "Content-Type" and not "content-type". While  formally it's a jQuery bug no one except Phoenix developers seem to have ever been affected as the bug is still present in the latest jQuery.

All major knowledge sources including Wikipedia list HTTP headers capitalized.

As the common belief is that they should be capitalized many HTTP clients are likely to assume the same and be broken by Phoenix choice.

What do you think / should I try to submit a patch?

**Comment by josevalim** [comment]
Honestly, I would hate to "fix" this. Because that's why we have a spec. Phoenix is not breaking anything, so they are not broken by Phoenix choice, they are broken because they don't follow the spec. I would really try to get a conversation started with the jquery team before we move on.

**Comment by qertoip** [comment]
I'm afraid jQuery is just a tip of the iceberg.

We will likely face an uphill battle trying to fix all HTTP clients in the world as everyone seems to be naively using capitalized headers.

Besides lowercase headers just seem awkward.

For me it is a Phoenix usability issue. I have lost about an hour hunting the bug in my app just to find it being a combination of jQuery and Phoenix and not in my code.

Kindly please reconsider from usability standpoint.

**Comment by josevalim** [comment]
Can you please support a small application that reproduces the error? I would like to investigate it a bit deeper before doing a widely backwards incompatible change to Phoenix.

**Comment by chrismccord** [comment]
@qertoip we definitely care about usability, but I'm with José in that I'd like to collect more data before sweeping changes. This is the very first time this issue has been raised, for jQuery or any other http clients. 

> I'm afraid jQuery is just a tip of the iceberg.

I'd really like to verify this. Are you aware of any other commonly used clients that are affected by this?

**Comment by dm1try** [comment]
@qertoip could you please clarify the place there jQuery parses the content-type. I found [this line](https://github.com/jquery/jquery/blob/e077ffb083743f4a4b990f586c9d25d787e7b417/src/ajax.js#L146)
```javascript
ct = s.mimeType || jqXHR.getResponseHeader( "Content-Type" );
```

But `getResponseHeader` has [the case-insensitive implementation](https://github.com/jquery/jquery/blob/e077ffb083743f4a4b990f586c9d25d787e7b417/src/ajax.js#L452-L461)
```javascript
getResponseHeader: function( key ) {
					var match;
					if ( completed ) {
						if ( !responseHeaders ) {
							responseHeaders = {};
							while ( ( match = rheaders.exec( responseHeadersString ) ) ) {
								responseHeaders[ match[ 1 ].toLowerCase() ] = match[ 2 ];
							}
						}
						match = responseHeaders[ key.toLowerCase() ];
					}
					return match == null ? null : match;
```

**Comment by josevalim** [comment]
Adding to @dm1try's response, jQuery's test suite seems to use different casing as well: https://github.com/jquery/jquery/search?p=1&q=content-type&utf8=%E2%9C%93

**Comment by nuss-justin** [comment]
@qertoip This also seems very broken to me considering that with HTTP/2 (which Phoenix doesn't do right now, but probably will in the future) all headers are sent lover case and the browsers probably aren't going to change that only for broken libraries and frameworks.

**Comment by qertoip** [comment]
Sorry gentlemen, by bad.

For some reason the JSON in my app is being returned in quotes (despite correct content-type assigned by Phoenix, etc). Not sure why this is the case but it's certainly due to my very limited Phoenix understanding.

Thanks a lot for your prompt support!

**Comment by chrismccord** [comment]
Glad you got it sorted out! If you need help sorting out the JSON payload issues, hop on elixir-lang irc
