### ISSUE TITLE
phoenix.js leaks `exports` into global scope which breaks javascript libraries

### ISSUE THREAD

**Issue by Burgestrand** [phoenixframework/phoenix#1479]
Commit here: https://github.com/phoenixframework/phoenix/commit/1bb26492327df619022fe2164a6a622728e2e9d0?diff=unified#diff-cf6d64b6ab9de528b5d0ed6c5db05f3aR7

```javascript
var exports = …
```

This is run in the global scope, this in itself is no good. See https://github.com/umdjs/umd for more information regarding proper wrappers.

Furthermore, `exports` is a common word in Node, which makes libraries assume they run in such an environment, with code such as this:

```javascript
"function" == typeof define && define.amd ? define(["jquery" ], t) : t("object" == typeof exports ? require("jquery") : jQuery)
```

This is not an uncommon wrapper, and now that `exports` exists, it will attempt to use `require`, which does not exist in the global scope, :bomb:!

**Comment by josevalim** [comment]
Good catch. I will work on a Phoenix. @chrismccord I think we should ship 1.1.3 afterwards.
