### ISSUE TITLE
brunch build failing

### ISSUE THREAD

**Issue by brandocorp** [phoenixframework/phoenix#1480]
I am trying to learn Phoenix as a new erlang/elixir/node/npm user. I was doing just fine following tutorials when I started seeing this error. It doesn't seem to matter what I do now, I can't get past this.

```
19 Jan 17:41:16 - error: Compiling of deps/phoenix/web/static/js/phoenix.js failed. deps/phoenix/web/static/js/phoenix.js: Cannot set property 'Symbol(should not be considered a local binding)' of undefined
```

Any help is appreciated

https://gist.github.com/brandocorp/ef745aca8ff657187814

System Infomation

```
System Version:	OS X 10.11.2 (15C50)
Kernel Version:	Darwin 15.2.0

Phoenix v1.1.1

$ erl -v
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
$ elixir -v
Elixir 1.1.1
$ node -v
v5.3.0
$ npm -v
3.3.12
```

**Comment by josevalim** [comment]
Can you try updating Phoenix? Version v1.1.2 changed the generated app to use a saner dependency mechanism, your bug may be fixed there.

**Comment by josevalim** [comment]
To clarify, you will need to build a new app after you updated! :D

**Comment by brandocorp** [comment]
I will try that. Thanks for the quick response!

**Comment by brandocorp** [comment]
Looks like that has fixed my issues. Thanks @josevalim !
