### ISSUE TITLE
Deployment instructions regarding exrm possibly out of date

### ISSUE THREAD

**Issue by seenickcode** [phoenixframework/phoenix#1482]
Greetings, 

(I'm writing here as I'm not sure where to submit issues with the Phoenix tutorials)

I would like to deploy my new Phoenix project and have attempted to follow http://www.phoenixframework.org/v0.7.2/docs/deployment but I am having issues running my release following the instructions.

Here are the steps I've run after following the tutorial with a brand new Phoenix project:
````
mix phoenix.new testapp
cd testapp
````
Per the instructions, I added the following to my ``testapp.ex`` file:
````
Testapp.Endpoint.start
````

I then add :exrc to list of applications in mix.exs, then run:
````
mix deps.get
mix deps.compile
mix release
````

I then run ``rel/testapp/bin/testapp console`` and get:
````
Exec: /Users/seenickcode/Code/testapp/rel/testapp/erts-7.2.1/bin/erlexec -boot /Users/seenickcode/Code/testapp/rel/testapp/releases/0.0.1/testapp -boot_var ERTS_LIB_DIR /Users/seenickcode/Code/testapp/rel/testapp/erts-7.2.1/../lib -env ERL_LIBS /Users/seenickcode/Code/testapp/rel/testapp/lib -config /Users/seenickcode/Code/testapp/rel/testapp/releases/0.0.1/sys.config -pa /Users/seenickcode/Code/testapp/rel/testapp/lib/consolidated -args_file /Users/seenickcode/Code/testapp/rel/testapp/releases/0.0.1/vm.args -user Elixir.IEx.CLI -extra --no-halt +iex -- console
Root: /Users/seenickcode/Code/testapp/rel/testapp
/Users/seenickcode/Code/testapp/rel/testapp
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

{"Kernel pid terminated",application_controller,"{application_start_failure,testapp,{bad_return,{{'Elixir.Testapp',start,[normal,[]]},{'EXIT',{undef,[{'Elixir.Testapp.Endpoint',start,[],[]},{'Elixir.Testapp',start,2,[{file,\"lib/testapp.ex\"},{line,9}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}

Crash dump is being written to: erl_crash.dump...done
Kernel pid terminated (application_controller) ({application_start_failure,testapp,{bad_return,{{'Elixir.Testapp',start,[normal,[]]},{'EXIT',{undef,[{'Elixir.Testapp.Endpoint',start,[],[]},{'Elixir.
````

Any ideas?  I'd like to see others successfully deploy Phoenix projects by following this tutorial.

Thanks in advance!

**Comment by doomspork** [comment]
@seenickcode those are the v0.7.2 docs which are likely out-of-date.  The latest (v1.1.3) article is here: http://www.phoenixframework.org/docs/advanced-deployment

**Comment by seenickcode** [comment]
Ok thank you for your help.  It appears the out of date docs are the default still with no redirect:

<img width="874" alt="screen shot 2016-01-20 at 10 01 32 pm" src="https://cloud.githubusercontent.com/assets/75833/12462968/75239a50-bfc1-11e5-927e-ad2bf67902ae.png">

**Comment by seenickcode** [comment]
FYI, I'm following the instructions here: http://www.phoenixframework.org/docs/deployment and am running into issues:

````
brunch build --production
MIX_ENV=prod mix phoenix.digest
PORT=4001 MIX_ENV=prod mix phoenix.server
testapp$ PORT=4001 MIX_ENV=prod mix phoenix.server
** (Mix) Could not start application testapp: could not find application file: testapp.app
````

**Comment by seenickcode** [comment]
I've followed the tutorial you've mentioned @doomspork and I seem to still be having issues:

I added the following to my dependencies list in mix.exs:
````{:exrm, "~> 1.0.0-rc7"}````

I ran:
````
MIX_ENV=prod mix phoenix.digest
MIX_ENV=prod mix release
````

And got:
````
Building release with MIX_ENV=prod.
** (MatchError) no match of right hand side value: {:error, {:copy_failed, :eacces}}
    src/rlx_prv_assembler.erl:554: :rlx_prv_assembler.create_start_clean/4
    src/rlx_prv_assembler.erl:59: :rlx_prv_assembler.do/1
    src/relx.erl:308: :relx.run_provider/2
    (stdlib) lists.erl:1262: :lists.foldl/3
    src/relx.erl:291: :relx.run_providers_for_actions/2
    lib/exrm/utils/utils.ex:104: ReleaseManager.Utils.relx/5
    lib/mix/tasks/release.ex:343: Mix.Tasks.Release.do_release/1
    lib/mix/tasks/release.ex:79: Mix.Tasks.Release.do_run/1
````

Any ideas?

**Comment by chrismccord** [comment]
@seenickcode Please reserve support questions for the phoenix-talk mailing list. We use the issue tracking for bugs and active feature development. Someone on the mailing list or irc will be able to point you in the right direction. Thanks!
https://groups.google.com/forum/#!forum/phoenix-talk

**Comment by seenickcode** [comment]
No prob, @chrismccord Sorry about that!  

FYI maybe the team should include a small link such as "Questions? Problems?" on each tutorial page at http://www.phoenixframework.org/docs in order to solicit more feedback (apart from the "Suggest Edits" link).  I think it'll help smooth adoption for newcomers.

**Comment by seenickcode** [comment]
Question posted:  https://groups.google.com/forum/#!topic/phoenix-talk/3CQMA8n2XZw
