### ISSUE TITLE
Deprecate Phoenix.ConnTest.conn/0 and add Phoenix.ConnTest.build_conn/0

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix#1486]
We discussed this in IRC https://botbot.me/freenode/elixir-lang/2016-01-21/?msg=58418573&page=10

There is often confusion around this because people often create a conn with `conn/0` and assign it to a `conn` variable. Switching to `build_conn/0` should help make this more clear.

Should we also deprecate `conn/3` and add `build_conn/3` so there aren't two function names for building connections?

**Comment by josevalim** [comment]
Yes, let's rename both. :)
