### ISSUE TITLE
Add i10n support other than gettext

### ISSUE THREAD

**Issue by qiuzhanghua** [phoenixframework/phoenix#1492]
I can write plugin to detect browser's Accept-Language and call Gettext's put_locale, but for any string in a template should use gettext to porcess, it's tedious.

Can I define template like this:

|- templates
|  |- user
|      |- index.html.eex
|      |- index_zh_CN.html.eex
|      |- index_en.html.eex

to support i10n.

btw, My plug to detect Accept-Language, I am new to elixir and phoenix.

defmodule LocalePlug do
  import Plug.Conn

  def init(default \\ "en") do
    default
  end

  def call(conn, default) do
    if conn.assigns[:locale] do
     conn
    else
      accept_languages = get_req_header(conn, "accept-language")
      locale = if length(accept_languages) == 0 do
        default
      else
        hd(accept_languages) |> resolve(default)
      end
      conn |> assign(:locale, locale)
    end
  end

  def resolve(accept_language, default \\ "en") do
      cond do
        is_nil(accept_language) -> default
        String.length(accept_language) < 2 -> default
        true ->
          (case :binary.match(accept_language, ",") do
            :nomatch -> accept_language
            {pos, _} ->
              :binary.part(accept_language, 0, pos)
                |> String.strip
                |> String.replace("-", "_")
          end)
      end
   end

end

...
in router.ex

  def i10n(conn, _) do
    if (conn.assigns[:locale]) do
      Gettext.put_locale(Hello.Gettext, conn.assigns.locale)
    end
    conn
  end

  pipeline :browser do
   ...
    plug LocalePlug, "en"
    plug :i10n
  end

**Comment by josevalim** [comment]
You can build that as a plug in your application. I would recommend the following:

* properly parse the accept-language header into formats you expect in your application
* when rendering the template, use "index.en.html", "index.cn.html" and so on as the template name

Right now there are no plans to automate this. Maybe we could consider some sort of callback that allows those to be modified and make "render :index" automatically become "index.en.html" and so on.

**Comment by qiuzhanghua** [comment]
Thanks!
What does you mean about "some sort of callback that allows those to be modified and make "render :index" automatically become "index.en.html"" and how ?

**Comment by josevalim** [comment]
Today, when you call `render conn, :index`, Phoenix will automatically render "index.html" (or "index.json"). I am thinking we could find a way to make it render "index.en.html" or "index.cn.json" and so on. Another option is to support some sort of flag that enables locale lookup like "locale: true". We will need to discuss and study the options.

**Comment by josevalim** [comment]
Hi @qiuzhanghua ! I have discussed this issue with @chrismccord and we have concluded that best solution to this problem is actually for you to provide your own render functions that performs the concatenation for you.

```elixir
defmodule Localizer.Controller do
  def get_locale(conn), do: conn.assigns[:locale]
  def put_locale(conn, value), do: assign(conn, :locale, value)
  def render(conn, template, assigns \\ []) when is_binary(template) do
    Phoenix.Controller.render(conn, template <> "." <> get_locale(conn), assigns)
  end
end
```

You could provide a similar function to the view as well:

```elixir
defmodule Localizer.View do
  def locale_render(module, template, assigns \\ %{}) when is_binary(template) do
    Phoenix.View.render(conn, template <> "." <> Map.fetch!(assigns, :locale), assigns)
  end
end
```

This way, it is very clear when you are using the localized templates and you have control over the whole process.
