### ISSUE TITLE
Error with new version of brunch

### ISSUE THREAD

**Issue by StevenReitsma** [phoenixframework/phoenix#1493]
Since the new version of brunch (4 hours ago, version 2.2.0) the default project is not working anymore.

```
mix phoenix.new test_phoenix
cd test_phoenix
mix ecto.create
mix phoenix.server
```

returns:

```
PS D:\Development\test_phoenix> mix phoenix.server
[info] Running TestPhoenix.Endpoint with Cowboy using http on port 4000
23 Jan 02:56:28 - error: undefined of web\static\js\app.js failed. Cannot find module 'phoenix_html' from 'web\static\js
 module 'phoenix' from 'web\static\js'
```

I'm assuming something is wrong with either the brunch config, or brunch itself. I'm very new to phoenix so I honestly have no idea how to fix this. This is actually my first project and the new brunch version is really just bad timing I guess.

Temporary fix:
```
npm install brunch@2.1.3
```

**Comment by josevalim** [comment]
I cannot reproduce the error on my Mac. So I am assuming it is something specific to Windows.

**Comment by josevalim** [comment]
@paulmillr here is a sample app that should reproduce it: https://github.com/josevalim/brunch_sample

    npm install
    node_modules/brunch/bin/brunch build

Btw, @StevenReitsma can you confirm the app above reproduces it? Thanks for the report!

**Comment by StevenReitsma** [comment]
Ah sorry, I probably should have mentioned I'm on Windows.
The sample app you posted indeed reproduces the error.

**Comment by paulmillr** [comment]
2.2 is a test release before the actual (2.2.x) stable release; but yes, good catch

**Comment by goshakkk** [comment]
I was able to reproduce this in Win7 VM. Figuring out the fix now

**Comment by goshakkk** [comment]
This appears to be an issue with `node-resolve`: https://github.com/substack/node-resolve/blob/master/lib/async.js

Path handling is somewhat messed up

**Comment by goshakkk** [comment]
I've found the underlying cause and submitted a PR to `node-resolve`: https://github.com/substack/node-resolve/pull/91

**Comment by goshakkk** [comment]
I'm not a node packaging guru, but I guess we'll need to wait for this to be merged and a new release of `node-resolve` created, then a new release of `browser-resolve` against that newer `node-resolve`, and only then bump `browser-resolve` in `brunch` (doh...) 

@paulmillr would you chime in?

--- 

As a side note, with brunch 2.2, `config.npm.whitelist` is no longer needed so might want to remove it from the generators @josevalim (I still see them in that sample app)

**Comment by paulmillr** [comment]
I think we can fork that for now and make the fork our dependency. Not sure whether substack is going to merge this soon

**Comment by riaan53** [comment]
brunch 2.2.0 works perfectly on my mac with phoenix 1.1.3. And now react-router is also working because of the submodule :)

**Comment by josevalim** [comment]
Thanks @paulmillr and @goshakkk for looking into it so promptly!

**Comment by josevalim** [comment]
@goshakkk I have currently pinned Phoenix to depend only on brunch 2.1.x so we have to explicitly update it, in order to avoid similar hiccups in the future! I will remove whitelist once we effectively migrate to 2.2.

**Comment by hugoestr** [comment]
I am on Windows 10. I ran into the same error with v1.1.3.  The work around that  StevenReitsma  posted, where you install brunch 2.1.3 also fixed the issue.

**Comment by josevalim** [comment]
Great job folks. I see all the PRs have been merged! :heart: Please let me know when a new brunch is out and I will update the deps in Phoenix. :)

**Comment by paulmillr** [comment]
2.2.2 is ready. Let me know if you have a problem with it @StevenReitsma

**Comment by StevenReitsma** [comment]
Works like a charm. Thanks all for picking this up.

**Comment by josevalim** [comment]
Thank you @paulmillr and @goshakkk! I gave 2.2.2 a try and I noticed this:

> 29 Jan 13:37:35 - info: compiled 6 files into 2 files, copied 3 in 1.1 sec

It called my attention because it is one more file than it should be. Then inspecting the `app.js` file I found that a "process" module was being registered:

https://gist.github.com/josevalim/c954391540fedd69e4e8#file-app-js-L124

I also noticed that our own libraries were being registered twice. Once with the expected name:

https://gist.github.com/josevalim/c954391540fedd69e4e8#file-app-js-L1257

And another with the filesystem path:

https://gist.github.com/josevalim/c954391540fedd69e4e8#file-app-js-L1280

We definitely do not need the second. Is there a way to skip it? Here is our package.json:

https://github.com/phoenixframework/phoenix_html/blob/master/package.json

Any feedback is appreciated!

**Comment by josevalim** [comment]
Btw, with 2.2.2 is npm enabled by default or shuold we still set:

```js
npm: {
    enabled: true
  }
```

?

**Comment by goshakkk** [comment]
> Then inspecting the app.js file I found that a "process" module was being registered

The process shim is included by default since some node modules rely on it being present without explicitly `require`ing

> And another with the filesystem path:

Again, it can sometimes be the case that the full fs path is getting required, so deppack adds it just in case. There's no way to skip it for now, but deppack should be getting smarter to detect that in the future

> Btw, with 2.2.2 is npm enabled by default or shuold we still set:

Yep, off by default, still has to be explicitly enabled.

**Comment by josevalim** [comment]
@goshakkk thank you. I would appreciate if those were options so we reduce the amount of included content.

Also please notice that process is being included twice:

https://gist.github.com/josevalim/c954391540fedd69e4e8#file-app-js-L124
https://gist.github.com/josevalim/c954391540fedd69e4e8#file-app-js-L1283

:)

**Comment by josevalim** [comment]
Maybe an includeProcess flag inside npm that automatically includes the shim if you find a dependency needs it. :)

**Comment by goshakkk** [comment]
@josevalim brunch/brunch#1143 should: a) not include the `process` shim by default if it can't find occurrences of `process.` in the source files; b) not add file-system based module names except for the `stream` shim (so far, that's the only thing relying on it).

I couldn't, however, reproduce the process duplication issue locally in an elixir app, probably not a big concern for now either way

cc @paulmillr

**Comment by josevalim** [comment]
Beautiful, thank you @goshakkk! :heart:

I will give your commit a try after it is merged, if I still see the process duplication for some reason, I will create a repo that reproduces the issue clearly.

**Comment by goshakkk** [comment]
@josevalim that PR is merged now & Brunch 2.2.3 released. Can you give it a try now? Cheers!

**Comment by williamgueiros** [comment]
Ping

**Comment by chrismccord** [comment]
@williamgueiros we will investinage the new brunch release as we find the time. The latest update to this thread is 3 days ago. Please refrain from pings/+1's that don't contribute to the discussion. Thanks!

**Comment by williamgueiros** [comment]
@chrismccord sorry, i try to help you on this issue.

**Comment by josevalim** [comment]
@goshakkk I gave it a try and everything looks great, thank you! :heart:

The only error I found is that the generated paths for the npm deps look like this:

    var require = __makeRequire((function(n) { return req(n.replace('./', 'phoenix_html//priv/static/')); }), {});

I believe that double slash is a bug? Anyway, it doesn't affect us because we don't use such requires, but I thought you would like to know about it anyway!
