### ISSUE TITLE
Please mention that elixir is the language used in this framework in website

### ISSUE THREAD

**Issue by rohithmeethal** [phoenixframework/phoenix#1494]
"A productive web framework that does not compromise speed and maintainability." could be changed to "A productive web framework for elixir language that does not compromise speed and maintainability."

It took me morethan 30 seconds to understand the same from the web landing page

**Comment by chrismccord** [comment]
Please direct copy and website improvements to the phoenix-talk mailing list and the phoenix_guides repo. Thanks!

**Comment by josevalim** [comment]
Why the fact it runs in Elixir matters at first? We do detail it later on,
but I don't think it needs to be the *first* thing we say.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
