### ISSUE TITLE
Add @spec and @doc for functions(routes) generated by macros

### ISSUE THREAD

**Issue by qiuzhanghua** [phoenixframework/phoenix#1498]
for a Hello style phoenix application, I run ```iex``` and then 
```
h Hello.Router.Helpers.api_user_path 
```
I got 
```elixir
def api_user_path(conn_or_endpoint, action)
def api_user_path(conn_or_endpoint, action, params)
def api_user_path(conn_or_endpoint, action, id, params)
```
would you please auto generate @spec and @doc ?

As a programmer from other language from Java etc, I think it's very important, especially for beginners.
(or for IDE to generate assistant hints)
and It is not hard.

I learn to write a etude for elixir as following:

```elixir
defmodule AtomicMaker do
  defmacro create_functions(element_list) do
    Enum.map element_list, fn {symbol, weight} ->
      quote do
        @doc """
          get weight of #{unquote(symbol)} ->  #{unquote(weight)}
        """
        @spec unquote(symbol)() :: number()
        def unquote(symbol)() do
          unquote(weight)
        end
      end
    end
  end
end
```
```elixir
defmodule Atomic do
  require AtomicMaker

  AtomicMaker.create_functions([{:h, 1.008}, {:he, 4.003},
    {:li, 6.94}, {:be, 9.012}, {:b, 10.81}, {:c, 12.011},
    {:n, 14.007}, {:o, 15.999}, {:f, 18.998}, {:ne, 20.178},
    {:na, 22.990}, {:mg, 24.305}, {:al, 26.981}, {:si, 28.085},
    {:p, 30.974}, {:s, 32.06}, {:cl, 35.45}, {:ar, 39.948},
    {:k, 39.098}, {:ca, 40.078}, {:sc, 44.956}, {:ti, 47.867},
    {:v, 50.942}, {:cr, 51.996}, {:mn, 54.938}, {:fe, 55.845}])
end
```

**Comment by josevalim** [comment]
I agree we should generate @spec. However, I am not sure what we could generate for the docs that would be useful. Ideas?

**Comment by qiuzhanghua** [comment]
for docs:
1. parameter explain
2. sample
3. which macro generate it(such as see Phoenix.Router.resources or Pheonix.Route.get)
4. of course description is required

BTW, docs for Pheonix.Route.get should add more as Phoenix.Router.resources.

Thanks!

**Comment by georgeslandry** [comment]
@qiuzhanghua I would be happy to work with you on documentation.

I am not a developer but I am very interested in this framework as I think its perfect for creating client side P2P software for a project I am developing.

For more info take a look at: http://sovereignprime.com/blog/2016/1/25/genesis

**Comment by ybur-yug** [comment]
@josevalim would you be interested in a small PR to generate the `@spec` portion? I am having trouble thinking of something that could be meaningfully generated for the `@doc` but would be happy to work on the Typespec portion.

**Comment by josevalim** [comment]
Let's, we can definitely get started with at least the `@spec` bit. :D

**Comment by ybur-yug** [comment]
Okay! I've never contributed before, but I'm assuming if I follow the guidelines in `CONTRIBUTING.md` I should be fine to get started?

**Comment by josevalim** [comment]
Yes. and if you have questions, let us know!

**Comment by ybur-yug** [comment]
Will do!

**Comment by ybur-yug** [comment]
@josevalim Would the macros associated with this be inside the `router` section of the code? I figured I'd start at the tests and move up the chain.

**Comment by josevalim** [comment]
Yes. router/helpers.ex iirc. :)

**Comment by ybur-yug** [comment]
@josevalim so I have the proper block and got it to add some `@doc` tags just to experiment (this is the first time I've worked with 'real' macros and not something super simple/trivial with them) and have it working, but I was curious about what the typespecs guard args/output as if done property?

I have a pseudo-code example of what I mean down here:



```elixir
..
      @spec unquote(:"#{helper}_path")(Conn, symbol(), ?):: Path.t
      def unquote(:"#{helper}_path")(conn_or_endpoint, unquote(opts), unquote_splicing(vars)) do
        unquote(:"#{helper}_path")(conn_or_endpoint, unquote(opts), unquote_splicing(vars), [])
      end
..
```

Basically, what would I use to represent the `Conn` type, and the return value?

Sorry if this is a super-newb question.

**Comment by josevalim** [comment]
@ybur-yug 

The connection is `Plug.Conn.t` but notice it can also be an endpoint or a socket so you need `Plug.Conn.t | Phoenix.Endpoint.t | Phoenix.Socket.t`. The second element is `atom()` and the third is  going to be `Phoenix.Param.t` BUT it is not a single entry. You will need to repeat it by the amount of vars you have. Using something like unquote_splicing. Something like:

    var_types = Enum.map vars, fn _ -> quote(do: Phoenix.Param.t) end
    @spec unquote(:"#{helper}_path")(Plug.Conn.t, atom(), unquote_splicing(var_types)):: String.t

**Comment by ybur-yug** [comment]
@josevalim Thanks!

**Comment by josevalim** [comment]
I am closing this. The feature is still desired and we would love to help but it is low priority for us. So a contribution is welcome but we won't have time to focus on it ourselves! Thank you!
