### ISSUE TITLE
phoenix.js in npm should be the latest version

### ISSUE THREAD

**Issue by aphillipo** [phoenixframework/phoenix#1503]
https://www.npmjs.com/package/phoenix-js

Unfortunately this hasn't been updated in 4 months and the file changed 7 days ago.

Anyway that this can be automated because when building an api for a javascript web app (in a different repo) it feels weird to be copying in the file rather than having an npm package.

This is all very very minor of course!  Elixir and Phoenix are an astounding achievement!

**Comment by josevalim** [comment]
Thank you @aphillipo but we are not the ones maintaining the package. However, on the positive side, phoenix-js is very easy to maintain. If you are using it from within a phoenix project, you only need to use "file:deps/phoenix" as your npm dependency (as we ship with a package.json now).

**Comment by aphillipo** [comment]
I'd say install from NPM is much much cleaner - my frontend (react-native, single page apps, etc.) all live in a different repo than my phoenix api.  Which to my mind makes sense.

I understand you guys not wanting the extra work though :-)  Thanks!

**Comment by josevalim** [comment]
Good point. @aphillipo ping the maintainer of the project then. :) that should fix it!
