### ISSUE TITLE
Add option to render_errors to use a layout

### ISSUE THREAD

**Issue by ericmj** [phoenixframework/phoenix#1504]
It should also be made clear in the docs that the layout should have no logic that can fail when rendering errors.

**Comment by ericmj** [comment]
It is also not clear from the docs what happens if the accepts check in render_errors fails.

**Comment by chrismccord** [comment]
@ericmj do you want to tackle this one?

**Comment by ericmj** [comment]
I am in the middle of converting hex_web to phoenix atm but will try to find some time this weekend to work on this.

**Comment by josevalim** [comment]
@ericmj feel free to assign this to me if you would rather focus on Hex. :)

**Comment by ericmj** [comment]
Assigned it over.

**Comment by ericmj** [comment]
A consistency issue needs to be fixed also. When the ErrorView is called explicitly with `render(ErrorView, ...)` the default layout is rendered but not when an exception is raised.

**Comment by josevalim** [comment]
@ericmj we are not going to fix the last comment because the layout is always the default from the controller, you need to call put_layout accordingly. Fixing it means either hardcoding or extending the view-controller contract which we don't want to. :)

**Comment by ericmj** [comment]
@josevalim So just to make it clear, until next phoenix is out I should call `put_layout(conn, false)` when calling the error view?

**Comment by josevalim** [comment]
Forever, yes. That's exactly what Phoenix's render errors call too.

On Saturday, February 6, 2016, Eric Meadows-Jönsson <
notifications@github.com> wrote:

> @josevalim <https://github.com/josevalim> So just to make it clear, until
> next phoenix is out I should call put_layout(conn, false) when calling
> the error view?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1504#issuecomment-180771683>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
Maybe phoenix should provide a controller function that wraps this all up. Rendering errors is now:

```elixir
conn
|> put_status(404)
|> put_layout(false)
|> render(MyApp.ErrorView, :"404", ...)
```

**Comment by josevalim** [comment]
It is 4 lines of code Eric. :P you can surely handle it in the app.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
Of course I can implement any given function in phoenix myself, that's beside the point. If every time you want to render errors correctly and consistently you have to call three functions then I think that should be wrapped up in a single function. Everyone who writes a phoenix app probably wants to call the error view. So we either have to add to the guides that to render errors you have to call these three functions or we simply provide a single function for you that does it.

**Comment by joshhart** [comment]
I'm a new Elixir/Phoenix developer coming from Ruby. Without this code, my gut instinct would be to write a bunch of conditionals to solve this problem. I suspect this is true of lots of people coming from the same direction as me.

Rather than wrap those lines into a new function, could the code above not be included, by default, when generating a new Phoenix app? It could be commented out and have some explanatory code with it, explaining how/where you might want to change it to suit your needs, but the more good-practice examples you put right in front of me the better!

It's only 4 line but they're good lines. They help guide me towards the kind of code I should be writing and that is incredibly helpful.

Thanks all for such great work.
