### ISSUE TITLE
Phoenix for Pure REST APIs

### ISSUE THREAD

**Issue by VJCORE** [phoenixframework/phoenix#1505]
hello , i am really impressed by phoenix. its just awesome, so i was thinking if we can have something like to just create apis , we can do right now , i know , but it comes with lot of extra files, so can we minimize that , and come up with pure rest based project using phoenix ?

**Comment by chrismccord** [comment]
> hello , i am really impressed by phoenix. its just awesome

Hi. and thanks!


Yes, Phoenix is great for purely REST apis. You can get what you want by doing `mix phoenix.new my_api --no-brunch --no-html`. In the future, please direct questions to the phoenix-talk mailing list as we reserve the issue tracker for  bugs and active feature development. Thanks!

**Comment by brado** [comment]
On a related note, it would be really great to also be able to generate **both** HTML and JSON API for the same models in the same web app. If there are complications with automating this with the generators, understood, but it would be really great to have some guide / doc and example code with best practice (or any working practice) for getting both HTML and JSON controllers and views to coexist gracefully in the same web app. I've been struggling with this for the past week and it is anything but intuitive. I believe with this established use-case, it would be a good foundation for discussion and would likely also bring to light some helpful improvements to phoenix and generators. 

I'd like to be able to contribute myself in the near future -- perhaps this is something I could contribute once I have it figured out myself.

**Comment by stevedomin** [comment]
@brado can we move that discussion to the mailing-list, I'd love to hear more about where/when you are struggling

**Comment by brado** [comment]
Done....I posted to the phoenix-talk list here: 

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/phoenix-talk/Bf9ZajD-bHg/MwUD3U84CgAJ
