### ISSUE TITLE
Newly generated phoenix app has two warnings in the endpoint

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix#1508]
A newly installed phoenix 1.1.4 app has a warning in the endpoint. I'm not sure this is an actual issue, or if it's something that should just be ignored. It may not be a real issue, so if not I'll close it :)
```
endpoint.ex:1: Function current_time/0 will never be called
endpoint.ex:1: Function time_diff/2 will never be called
```

I've created a [phoenix app](https://github.com/paulcsmith/dialyze-demo) that you can clone and run `mix do compile, dialyzer.plt, dialyzer` and see the output.

**Comment by josevalim** [comment]
It is fixed in Phoenix master. :)

**Comment by paulcsmith** [comment]
Nice! I didn't realize the put_layout stuff fixed this as well! :+1:

**Comment by josevalim** [comment]
Ah no, this was fixed a couple days ago instead. :)

**Comment by paulcsmith** [comment]
Oh I see. That makes more sense haha :)
