### ISSUE TITLE
Controller.accepts handles errors by itself

### ISSUE THREAD

**Issue by yolk** [phoenixframework/phoenix#1521]
Since this [commit](https://github.com/phoenixframework/phoenix/commit/aea71ff031c9bcaec7ceabb9a17b6a6a826bd8cc) Controller.accepts doesn't raise an Phoenix.NotAcceptableError expection anymore, it rather reponds with an 406 and halts the connection.

Is there any reason for handling it this way? Because this behaviour isn't consistent with the way exception are handled elsewhere (e.g. Plug.Parsers). This prevents me from handling the error with render_errors and the ErrorView. Shouldn't there be an consistent way to handle errors/exceptions?

Btw. The docs still mention the raised exception on [line 81](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/controller.ex#L81)

**Comment by josevalim** [comment]
I have updated the docs for now. I think we can revert it back to raising as long as we handle it in the render_errors layer.

**Comment by yolk** [comment]
Thanks for the quick reply and fix in the docs. Should I revert the changes in a pull request?

**Comment by josevalim** [comment]
Please do. :)

**Comment by yolk** [comment]
Any idea how to handle the case of an invalid format in the request for the error rendering? Should I just catch the raised exception in RenderErrors.fetch_format/2 and rerender the error with the first accepted format? 

Right now it renders a plain 406 if you throw an error and your request accepts no mime types accepted by RenderErrors: https://github.com/phoenixframework/phoenix/blob/master/test/phoenix/endpoint/render_errors_test.exs#L167

I guess this actually hides the original error (a 500 in this case) behind the 406 and would only make sense if the 406 orginated from the original requested resource. "unknown/unkown" would always raise an NotAcceptableError and this situation wouldn't accure. A better example would be an request for an pdf or rss/atom feed, which is an acceptable mime type for the original resource, but in most cases not for rendering an error.

**Comment by josevalim** [comment]
What does the HTTP spec says about 500s? Should they be parseable according to the accepts header? If so, we have no other option than return 406.

**Comment by yolk** [comment]
I couldn't find anything about how to handle a error case combined with incompatible accept header; but if I understand RFC 2616 correctly it seems to be acceptable to serve another content type in case nothing matches the accept header:

> Note: HTTP/1.1 servers are allowed to return responses which are
      not acceptable according to the accept headers sent in the
      request. In some cases, this may even be preferable to sending a
      406 response. User agents are encouraged to inspect the headers of
      an incoming response to determine if it is acceptable.
http://www.rfc-base.org/txt/rfc-2616.txt

So it seems a http 1.1 client should be able to handle a response format it didn't ask for. Wouldn't this be better than hiding a 5xxer behind a 406 which contains no details? Even more so because this 406 is not for the original requested resource (which we would still serve the 406 if the negotiation faild at this earlier point), but for serving the error content of the unrelated 500er error.

I think there are three ways how to handle the situation (imo from worst to best):

1. Serve a 406 with no details about what caused the error. A client would have to guess that the 406 wasn't for the requested resource but the (not shown) error.
2. Serve a 500 with no details.
3. Serve a 500 (or other matching 5xx or 4xx) with error details in content type not acceptable for the client. If the client can't understand the response it should ignore/discard the content and you are back to (2).

**Comment by yolk** [comment]
Maybe of interest: a paragraph above the RFC states for 406 errors:

> Unless it was a HEAD request, the response SHOULD include an entity containing a list of available entity characteristics and location(s) from which the user or user agent can choose the one most appropriate. The entity format is specified by the media type given in the Content-Type header field. Depending upon the format and the capabilities of the user agent, selection of the most appropriate choice MAY be performed automatically. However, this specification does not define any standard for such automatic selection. 

This means even when returning a 406 error because the accept header didn't match for the requested resource the server "should include a entity"; and the server should chose a acceptable format for the error entity: "The entity format is specified by the media type given in the Content-Type header field."

**Comment by josevalim** [comment]
@yolk so let's rescue the error and render the error page using in the first format in the list of formats. Great job on the research! :D

**Comment by yolk** [comment]
Just made a pull request with the changes. Hope it is acceptable ;)

**Comment by yolk** [comment]
Thanks for the quick merge. Did you see my question regarding the halted-line at https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/render_errors.ex#L69 

I guess this could be removed/cleaned up!?

**Comment by josevalim** [comment]
Sorry, I missed the question. :) Yes, we can remove that line. New PR please? :D
