### ISSUE TITLE
Logging after exception

### ISSUE THREAD

**Issue by yolk** [phoenixframework/phoenix#1522]
Is there any way for Plug.Logger to log the "Sent/Chunked"-Line in case of an exception? I would like to have a way to log the resulting http error codes in the same way as when I am on the happy path ;)

The problem seems to be that I can't plug anything above the Phoenix.Endpoint.RenderErrors-module, because it wraps the call-method of the endpoint. Maybe this should could simply be another plug, so I could decide which plugs are trustworthy enougth to work above it?

**Comment by josevalim** [comment]
@chrismccord I think we need to fix this in Phoenix. With latest Plug, we will only log 500 status code and the non-500 is logged by debugger which means we won't log anything for prod cases.

**Comment by chrismccord** [comment]
Can I get some more details on what exactly isn't being logged? On master we log the status code in prod always regardless of 500 or non 500 whenever we wrap.

**Comment by chrismccord** [comment]
As far as I've confirmed, we correctly log on exceptions on master. If you're able to provide a way to reproduce otherwise, please ping this thread. Thanks!
