### ISSUE TITLE
Issue when broadcasting multiple messages from handle_in

### ISSUE THREAD

**Issue by CD1212** [phoenixframework/phoenix#1524]
I have a `handle_in` rule in one of my channels along the lines of the following:
```
user = socket.assigns.current_user

case Project.for_user(user, project_id) do
  nil ->
    {:reply, {:error, %{error: "Project not found"}}, socket}

  project ->
    case Project.action(user, project, params) do
      {:ok, entry} ->
      socket
       |> broadcast("action2", %{entry: entry})
       |> broadcast("action1", User.activity(user)) # This is user_channel.ex:41
       {:noreply, socket}

      {:error, changeset} ->
        {:reply, {:error, respond_errors(changeset)}, socket}
      end
    end
end
```

On Phoenix 1.1.3 I would always receive the following error in development mode. **Both broadcast messages would successfully reach the client**. I would only get it in test mode when using `broadcast!` instead of `broadcast`

After upgrading to 1.1.4 I get it in testing and development. I have tried swapping action1 and action2 (not their real names) around, but the exception always occurs on line 41, the second one.

```
** (EXIT from #PID<0.426.0>) an exception was raised:
         ** (FunctionClauseError) no function clause matching in Phoenix.Channel.assert_joined!/1
             (phoenix) lib/phoenix/channel.ex:398: Phoenix.Channel.assert_joined!(:ok)
             (phoenix) lib/phoenix/channel.ex:297: Phoenix.Channel.broadcast/3
             (amasses) web/channels/user_channel.ex:41: MyApp.UserChannel.handle_in/3
             (phoenix) lib/phoenix/channel/server.ex:229: Phoenix.Channel.Server.handle_info/2
             (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
             (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

I was hesitant before submitting this issue because the following snippet works perfectly, so Phoenix can definitely handle multiple `broadcast` calls from `handle_info`. 

```
def handle_in("trigger:err", _params, socket) do
    broadcast!(socket, "dummy:1", %{a: "b"})
    broadcast!(socket, "dummy:2", %{a: "b"})
    {:noreply, socket}
end
```

**Comment by chrismccord** [comment]
You cannot pipe broadcasts like in your examples because we do not return the socket. Your code is effectively calling `broadcast(:ok, ...)`. The bottom example with two separate broadcasts (no pipe), is the correct solution. Hope that helps, but nothing to fix on our end. Thanks!

**Comment by CD1212** [comment]
Thanks Chris, much appreciated. I hoped it wasn't something silly I was doing wrong.....
