### ISSUE TITLE
Generated controller tests with namespaced models have wrong path 

### ISSUE THREAD

**Issue by brado** [phoenixframework/phoenix#1525]
I have encountered this repeatedly with phoenix.gen.json (the only one I've tried namespaces with), but I suppose that it is possible that there's a problem with phoenix.gen.html too. Here's the problem: when generating objects for namespaced models, controller tests have the wrong path, and tests fail. Example: 

```
mix phoenix.gen.json API.V1.Car cars name:string description:string
```

This results in controller tests with a paths of

```
car_path
```

This results in failures of all controller tests. Changing the path to: 

```
api_v1_car_path
```

fixes all test failures, and tests will then succeed.

**Comment by josevalim** [comment]
The generator is correct. If you run the command above, it will ask you to add the following route:

```elixir
resources "/api/v1/cars", API.V1.CarController, except: [:new, :edit]
```

Which generates paths like this:

```
 car_path  GET     /api/v1/cars      Demo.API.V1.CarController :index
 car_path  GET     /api/v1/cars/:id  Demo.API.V1.CarController :show
 car_path  POST    /api/v1/cars      Demo.API.V1.CarController :create
 car_path  PATCH   /api/v1/cars/:id  Demo.API.V1.CarController :update
           PUT     /api/v1/cars/:id  Demo.API.V1.CarController :update
 car_path  DELETE  /api/v1/cars/:id  Demo.API.V1.CarController :delete
```

Look how the helper is `car_path`. I am guessing you are generating the resource inside a namespaced scope, which is affecting the generated path. Then you do have to fix it manually as there is no way the generator could guess this.

The alternative is for us to change the default helper generated for namespaced resources. For this, we would need to add a `namespace` option to the router, similar to what we have in the controller and view.

**Comment by brado** [comment]
I am using namespaced scopes, e.g.: 
```
  scope "/api", MyProject.API, as: :api do
    pipe_through :api

    scope "/v1", V1, as: :v1 do
      resources "/cars", CarController, except: [:new, :edit]
    end
  end
```
A primary motivation for namespacing is to prevent a conflict between HTML and JSON artifacts created by phoenix.gen.html and phoenix.gen.json generators. So it probably is reasonable to assume that if namspaced module, generated artifacts, and URL path are needed, that the path name will need to be namespaced too. Sounds like the namspace option is probably a good idea.

**Comment by josevalim** [comment]
Your comment just made me realize this would be a backwards incompatible change. If we change this, the example above would generate `api_v1_api_v1_car_path`. So we will need to move this to Phoenix 2.0. The benefit is that, once we do this change, you will no longer need the `:as` option in your scopes.

**Comment by omidbachari** [comment]
@josevalim May I take this issue? Just to be clear, we want to implement:

> change the default helper generated for namespaced resources. For this, we would need to add a namespace option to the router, similar to what we have in the controller and view.

Please let me know what else you might expect from this feature.

**Comment by chrismccord** [comment]
@omidbachari let's hold on this for now as it's slated for 2.0, which we're not yet moving towards. Thanks!

**Comment by chrismccord** [comment]
We're going to hold on changing any path helper generation because the current approach is the simplest since we always use the last segment of the controller module for the helper, and allowing explicit helper names as an option when you want to customize. I think this strikes a good balance that is the least surprising for users.
