### ISSUE TITLE
Generated JSON views should use specific model names rather than "data"

### ISSUE THREAD

**Issue by brado** [phoenixframework/phoenix#1526]
When running the JSON generator, the generated view results in a parent JSON name of "data" rather than the specific model name. This isn't an error, but I believe it is an oversight and/or not the best alternative. Example, if you execute the following: 
```
mix phoenix.gen.json API.V1.Car cars name:string description:string
```
it will generate a view which looks like this: 
```
defmodule MyProject.API.V1.CarView do
  use MyProject.Web, :view

  def render("index.json", %{cars: cars}) do
    %{data: render_many(cars, MyProject.API.V1.CarView, "car.json")}
  end

  def render("show.json", %{car: car}) do
    %{data: render_one(car, MyProject.API.V1.CarView, "car.json")}
  end

  def render("car.json", %{car: car}) do
    %{id: car.id,
      name: car.name,
      description: car.description}
  end
end
```
This isn't the best option. While prefacing the specific JSON output with "data" is syntactically correct, the resulting JSON looks as follows: 
```
data : {
...
}
```
It would be much better for both readability and downstream integration development / debugging if the JSON document indicated its specific contents, as such: 
```
car: {
...
}
```
So for the generated view, it would be better if it were generated as follows: 
```
defmodule MyProject.API.V1.CarView do
  use MyProject.Web, :view

  def render("index.json", %{cars: cars}) do
    %{cars: render_many(cars, MyProject.API.V1.CarView, "car.json")}
  end

  def render("show.json", %{car: car}) do
    %{car: render_one(car, MyProject.API.V1.CarView, "car.json")}
  end

  def render("car.json", %{car: car}) do
    %{id: car.id,
      name: car.name,
      description: car.description}
  end
end
```
The resulting JSON will then properly describe its contents in both plural ("cars") and singular ("car") scenarios.

**Comment by ericmj** [comment]
`data` isn't necessarily bad. JSON API uses it for example.

**Comment by chrismccord** [comment]
We went with `data` because of JSON API http://jsonapi.org/ . Not that we generate a fully json api compliant payload, but it's designed to provide structure for you to build from. As this is not an issue, please take changes like this to the mailing list since we reserve the issue tracker for active feature development and bugs. Thanks!

**Comment by brado** [comment]
I wasn't saying that "data" was bad. It is syntactically correct, nothing wrong with it. However, as the generated view understands both the specific model name both singular and plural, it seemed logical to follow likewise and produce a JSON document that actually indicates what its contents are. It seemed that given the choice between a generic name and one with specific meaning, the latter might be desirable.

I confess that I was unaware of the JSON API specification's hard-use of "data". I understand now. Thanks -- and apologies for posting this here --  I didn't realize that enhancement requests were inappropriate as Git issues for the Phoenix  project (I've worked on a number of projects which explicitly managed its feature requests with Git issues) -- I'll take them to the mailing list next time.

**Comment by brado** [comment]
Actually, I did neglect to mention one thing about this. POST operations seem to require JSON with the descriptive name (in this case, "car") rather than "data". That seems a little asymmetrical with the GET operations.
