### ISSUE TITLE
Generators produce controller tests with ID's which fail against Mongo object ID's. 

### ISSUE THREAD

**Issue by brado** [phoenixframework/phoenix#1527]
I asked about this on the mongo_ecto project, but it appears the matter is upstream in the nature of the Phoenix generator. Whatever the case, it causes the generated controller tests from pheonix.gen.html and phoenix.gen.json to fail.

I am using mongo_ecto, which talks to MongoDB and uses ObjectIDs as it ID type. If I run this command: 
```
mix phoenix.gen.html Car cars name:string description:string
```
the generated controller test file will contain this test: 
```
  test "renders page not found when id is nonexistent", %{conn: conn} do
    assert_error_sent 404, fn ->
      get conn, car_path(conn, :show, "11111111-1111-1111-1111-111111111111")
    end
  end
```
This test fails, because the ID string is invalid. If this ID is changed to this: 
```
  test "renders page not found when id is nonexistent", %{conn: conn} do
    assert_error_sent 404, fn ->
      get conn, car_path(conn, :show, "56a537b63e0eee155869a051")
    end
  end
```
Then the test succeeds. In the discussion on the mongo_ecto project, while the issue is specific to MongoDB's ID requirements, the answer I received is that because of the nature of the Phoenix generators, this is not something that can be fixed in the mongo_ecto code, but has to be fixed upstream. 

I confess I don't have the knowledge of the Phoenix or mongo_ecto codebase to speak further on the matter, but if someone can point me to the place in the Phoenix source which is in play here, I'd be happy to take a look and brainstorm on a solution. At any rate, it does constitute a bug, and some provision should be made to either fix it outright in Phoenix, or to expose functionality to allow it to be fixed downstream in mongo_ecto.

**Comment by josevalim** [comment]
I think we will have to introduce something like sample_binary_id generator option or something of sorts. What do you think @michalmuskala?

**Comment by michalmuskala** [comment]
Yeah, I don't see a different solution. But where would we store this setting?

**Comment by josevalim** [comment]
@michalmuskala config file, the same place where we set binary_id: true. wdyt?

**Comment by michalmuskala** [comment]
Yeah, I think we can't do any better. I'll make a PR
