### ISSUE TITLE
Up and running guide.

### ISSUE THREAD

**Issue by note89** [phoenixframework/phoenix#1528]
In the up and running guide when i came to 
```
$ mix ecto.create
```
i got the following error 
```
** (Mix) The database for HelloPhoenix.Repo couldn't be created, reason given: psql: FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"
.
```

There is probably a way to send arguments to ecto.create with the password or some config file i can edit. That info should be avaible right there. 
I dont know what password ecto.create are trying to use as standard.

**Comment by josevalim** [comment]
You must configure your database in the `config/dev.exs` file.

**Comment by Niler851** [comment]
Tnx i did that :) 
Just thought that it might be good to make a note of that in the up and running. 
alot of other errors where described when it came to ecto.create but not that one.

You rock Jose!
