### ISSUE TITLE
the description about :name option in form_for/4 should be updated?

### ISSUE THREAD

**Issue by hykw** [phoenixframework/phoenix#1532]
http://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html in `With connection data` has a following snippet.

```elixir
<%= form_for @conn, search_path(@conn, :new), [name: :search], fn f -> %>
  <%= text_input f, :for %>
  <%= submit "Search" %>
<% end %>
```

When you use form_for/4 like above, a warning `the :name option in form_for/inputs_for is deprecated, please use :as instead` would occur, so it should be like below?

```elixir
<%= form_for @conn, search_path(@conn, :new), [as: :search, name: :search], fn f -> %>
  <%= text_input f, :for %>
  <%= submit "Search" %>
<% end %>
```

IMHO, you shouldn't omit :name because it specifies the name in `<form>`.

c.f.
  http://stackoverflow.com/questions/35214940/how-to-set-name-in-form-without-name/35269413

**Comment by josevalim** [comment]
I will update the docs. You should use `as: :search` for our internal parameters. The name is for the HTML attribute. Thank you!
