### ISSUE TITLE
No way to filter params in Channel logs

### ISSUE THREAD

**Issue by stevedomin** [phoenixframework/phoenix#1537]
Currently this is no way of filtering params in Channel logs. It would be useful to reuse the `filter_params` config to filter out sensitive information in the channel logs.

This came through the mailing list: https://groups.google.com/forum/#!topic/phoenix-talk/EZFmddtju9o

**Comment by stevedomin** [comment]
I'll start working on it.

**Comment by chrismccord** [comment]
:+1:  thanks!

**Comment by stevedomin** [comment]
This issue can be closed now that #1539 has been merged
