### ISSUE TITLE
Error being logged when attempting to connect to `wss` when not supported

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#1538]
When connecting to the WebSocket using `wss` instead of `ws` and ssl is not being used, the following error is logged to the console:

>     (cowboy) src/cowboy_protocol.erl:168: :cowboy_protocol.parse_method("", {:state, #Port<0.9715>, :ranch_tcp, [:cowboy_router, :cowboy_handler], false, [listener: Chat.Endpoint.HTTP, dispatch: [{:_, [], [{["phoenix", "live_reload", "socket", "longpoll"], [], Plug.Adapters.Cowboy.Handler, {Phoenix.Transports.LongPoll, {Chat.Endpoint, Phoenix.LiveReloader.Socket, :longpoll}}}, {["phoenix", "live_reload", "socket", "websocket"], [], Phoenix.Endpoint.CowboyWebSocket, {Phoenix.Transports.WebSocket, {Chat.Endpoint, Phoenix.LiveReloader.Socket, :websocket}}}, {["socket", "longpoll"], [], Plug.Adapters.Cowboy.Handler, {Phoenix.Transports.LongPoll, {Chat.Endpoint, Chat.UserSocket, :longpoll}}}, {["socket", "websocket"], [], Phoenix.Endpoint.CowboyWebSocket, {Phoenix.Transports.WebSocket, {Chat.Endpoint, Chat.UserSocket, :websocket}}}, {:_, [], Plug.Adapters.Cowboy.Handler, {Chat.Endpoint, []}}]}]], :undefined, :undefined, 5, 1, 100, 4096, 64, 4096, 100, 5000, 1455126982563}, <<22, 3, 1, 0, 141, 1, 0, 0, 137, 3, 1, 90, 185, 254, 121, 105, 21, 93, 158, 64, 7, 238, 140, 222, 39, 80, 197, 70, 254, 227, 193, 50, 29, 210, 55, 194, 141, 177, 68, 201, 225, 61, 98, 0, 0, 28, 192, 10, 192, 20, ...>>)

Steps to reproduce:

1. `git clone git@github.com:Gazler/phoenix_chat_example.git -b chore/upgrade-phoenix`
2. `cd phoenix_chat_example`
3. `mix deps.get`
4. `npm install`
5. `mix phoenix.server`
6. Open a JavaScript console and type `new WebSocket("wss://localhost:4000/socket/websocket")`
7. Look at the Phoenix logged output

**Comment by josevalim** [comment]
What do you mean by SSL not being used? Btw, this looks like a cowboy bug. :) You mean there is no https: true?

**Comment by Gazler** [comment]
@josevalim Yeah, I mean that the server is not using `https`, however the attempted websocket is `wss`.

**Comment by chrismccord** [comment]
To recap, the client is sending encrypted traffic to the server expecting to parse unecrypted data. We could try to address this in cowboy, but the consensus is crashing is the correct behaviour. Thanks for looking into this @Gazler !
