### ISSUE TITLE
views

### ISSUE THREAD

**Issue by alec-c4** [phoenixframework/phoenix#1550]
Hi, guys.
i'm planning to improve a little views in phoenix, how do you think - will it be suitable? I'd like to set default template with following:

components:
- switch from sex to slim
- add support for scss/sass
- add support for coffee script

CSS part:
- normalize.css
- grid from skeleton.css

JS part:
- add modernizr.js
- add mithril.js

views part:
- rewrite templates to slim
- rewrite css to scss and js to coffee

and also i'd like to add some best practices from https://github.com/h5bp/html5-boilerplate

Maybe it looks like i'm trying to create rails or something like it, and that is why i'm asking for :) Maybe any other feature for default app template? What do you think?

**Comment by alec-c4** [comment]
also maybe it will be useful to add docker support out of the box? please have a look https://github.com/iron-io/dockers/tree/master/elixir

**Comment by imanhodjaev** [comment]
@alec-c4 I am pretty comfortable with ES6 because it is the future to come if not already came so why coffee? And I think many other people also will agree on this.

**Comment by josevalim** [comment]
Please use the phoenix core mailing list for proposals but it is unlikely we will accept any of these changes. First of all, you need to argue why those changes are relevant and this discussion is missing. Second, all of those changes bring more dependencies into the project. Why use Slim when we have EEx that ships with Elixir? Why add more .js dependencies if it is not guaranteed everyone needs them? What are the benefits? Finally, there is no reason to use Coffee now with ES6. Even brunch itself moved away from Coffee into ES6. Feel free to expand on those points in the core mailing list but without well founded arguments, do not expect any change.
