### ISSUE TITLE
Migrate to Ecto 2.0

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1564]
* [x] Remove `Mix.Task.run` from test_helper.exs and move it to mix.exs aliases
* [x] Replace test_transaction by Ecto sandbox (async: false should set shared mode)
* [x] Use `%{}` instead of `:empty` in generators (but only if Ecto version is 2.0.0)
* [x] Use `cast/3 + validate_required` instead of `cast/4` and get rid of scrub_params (but only if Ecto version is 2.0.0)
* [x] No pool_size: 1 limit for test (Ecto should warn)
* [x] Update gettext messages (length should no longer use count) (see #1589)

**Comment by stevedomin** [comment]
@josevalim: happy to help with any of this if you me to

**Comment by nathany** [comment]
>  Remove Mix.Task.run from test_helper.exs and move it to mix.exs aliases

For those using the beta of Ecto 2, what should test_helper look like?

**Comment by josevalim** [comment]
@nathany your test_helper should remove both Mix.Task.run. Instead, in your mix.exs, you should have something like this inside `def aliases`:

    "test": ["ecto.create --quiet", "ecto.migrate", "test"]

**Comment by nathany** [comment]
Thanks José. Making that change solved an error we were seeing in CI:

```
[error] Postgrex.Protocol (#PID<0.6145.0>) failed to connect: ** (Postgrex.Error) FATAL
(invalid_catalog_name): database “my_app_test" does not exist
```

**Comment by nathany** [comment]
Possibly another TODO is to use Allowances for Channel testing for handle_in's use of Task.start? https://github.com/phoenixframework/phoenix/blob/master/test/phoenix/test/channel_test.exs#L59

We had to put the following in ChannelCase:

```elixir
setup do
  :ok = Ecto.Adapters.SQL.Sandbox.checkout(MyApp.Repo)
  Ecto.Adapters.SQL.Sandbox.mode(MyApp.Repo, {:shared, self()})
end
```

**Comment by josevalim** [comment]
Yes, that's documented in `Ecto.Adapters.SQL.Sandbox`. :) My proposal is to actually have this in test cases:

```elixir
setup tags do
  :ok = Ecto.Adapters.SQL.Sandbox.checkout(MyApp.Repo)
  unless tags[:async] do
    Ecto.Adapters.SQL.Sandbox.mode(MyApp.Repo, {:shared, self()})
  end
end
```

This way you will use a shared connection whenever your tests are sync.

**Comment by nathany** [comment]
Sounds good. We'll update our code to use that pattern. I assume that it will be the default in generators for future apps.

**Comment by amarsahinovic** [comment]
I'm not 100% sure if this is related to Ecto 2.0 (could be related to Phoenix.HTML perhaps?), but in my project I'm using Ecto 2.0 and I've noticed that my form error messages are not showing up, so I've changed the first line of `error_tag/2` method in `web/views/error_helpers.ex` to use `form.source.errors[field]` instead of just `form.errors[field]` so it fetches directly from changeset errors.

**Comment by josevalim** [comment]
@amarsahinovic thanks. We will investigate when we start tackling this. :)

**Comment by josevalim** [comment]
See #1649
