### ISSUE TITLE
Phoenix cookie session storage: ambiguous error 

### ISSUE THREAD

**Issue by thousandsofthem** [phoenixframework/phoenix#1565]
### Environment

* Elixir version (elixir -v): 1.2.2
* Phoenix version (mix deps): 1.1.4
* NodeJS version (node -v): v5.4.0
* NPM version (npm -v): 3.5.2
* Operating system: OSX 10.9.5

### Steps to reproduce:

The code: (simplified)
```elixir
user = Repo.get_by(User, username: user_params["username"])
conn
  |> put_session(:current_user, user)
  |> redirect(to: some_path)
```

### Expected behavior
After redirect phoenix should either operate just fine or show an error in console

### Actual behavior
After putting object in session every single url (including nondexistent) is showing as "400 Bad Request" with zero-size body in browser
Nothing in logs, even with log level debug

Most likely it was "too big object for a cookie session storage". No way to get anything useful from phoenix itself though

**Comment by thousandsofthem** [comment]
Just in case user model: https://gist.github.com/thousandsofthem/9f434f9a72a6aeae3fb2

**Comment by josevalim** [comment]
You are right. I have moved this to plug: https://github.com/elixir-lang/plug/issues/355

**Comment by josevalim** [comment]
Thank you for the report!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
