### ISSUE TITLE
Move bootstrap css styles to vendor/css directory

### ISSUE THREAD

**Issue by ktec** [phoenixframework/phoenix#1566]
Any thoughts on having the bootstrap content in a `vendor/css/bootstrap.css` for a freshly created app instead of `app.css`? 

It kinda makes sense when you think about it and it would help when explaining to new folks..."oh you don't need all that, you can delete it if you want" tends to confuse people.

**Comment by chrismccord** [comment]
Please see the previous discussions and conclusions are this on the issue tracker. Thanks!

**Comment by ktec** [comment]
For anyone else that finds this, the latest discussion/conclusion appears to be here https://github.com/phoenixframework/phoenix/pull/831
