### ISSUE TITLE
Failing phoenix.digest exists with 0

### ISSUE THREAD

**Issue by kyledecot** [phoenixframework/phoenix#1573]
When running `MIX_ENV=prod mix phoenix.digest` when `priv/static` doesn't exist you'll get:

> The input path "priv/static" does not exist

However when looking at the exit code it appears that it still returns `0`.

![screen shot 2016-03-02 at 12 54 44 pm](https://cloud.githubusercontent.com/assets/192464/13469565/f71ebf42-e075-11e5-82e6-87f1b2259ab3.png)

**Comment by chrismccord** [comment]
Fixed! Thanks for the report!

**Comment by josevalim** [comment]
The reason we were not exiting is so it works in umbrella. This will
unfortunately break it. I am not sure we can have the best of both words
though.

On Wednesday, March 2, 2016, Chris McCord <notifications@github.com> wrote:

> Fixed! Thanks for the report!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1573#issuecomment-191354139>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
@josevalim ah, I checked out the compile task and saw it properly exited, so I went that route. Why does it break umbrellas? Should the task continue if it fails?

**Comment by josevalim** [comment]
If you run digest in the umbrella root, it will be recursive but not all of
them are Phoenix projects. Maybe we can just not say anything if the source
is not there.

On Wednesday, March 2, 2016, Chris McCord <notifications@github.com> wrote:

> @josevalim <https://github.com/josevalim> ah, I checked out the compile
> task and saw it properly exited, so I went that route. Why does it break
> umbrellas? Should the task continue if it fails?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1573#issuecomment-191355388>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by chrismccord** [comment]
Shall I revert for now?

**Comment by josevalim** [comment]
Yes, I think so.

On Wednesday, March 2, 2016, Chris McCord <notifications@github.com> wrote:

> Shall I revert for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1573#issuecomment-191356672>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by kyledecot** [comment]
@josevalim @chrismccord unfortunate but understandable. Is this odd-behavior documented somewhere that I missed? If not, should we have this noted somewhere (not sure where that would be though)?
