### ISSUE TITLE
Incorrect error checking on database flag when new project created

### ISSUE THREAD

**Issue by fuzzygroup** [phoenixframework/phoenix#1576]
I accidentally used a single - flag preceding database when I was attempting to specify mysql.  Example:

mix phoenix.new blog_phoenix  –database mysql

Obviously that should have been --database but rather than an error being displayed, I instead got the postgres adapter.  Some level of better error checking on command line parameters is likely needed.

    Elixir version (elixir -v): Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.2.3

    Phoenix version (mix deps):
    fs 0.9.1 (Hex package) (rebar) locked at 0.9.2 (fs) ok
    gettext 0.10.0 (Hex package) (mix) locked at 0.10.0 (gettext) ok
    ranch 1.2.1 (Hex package) (rebar) locked at 1.2.1 (ranch) ok
    poison 2.1.0 (Hex package) (mix) locked at 2.1.0 (poison) ok
    phoenix_pubsub 0.0.1 (https://github.com/phoenixframework/phoenix_pubsub.git) (mix) locked at 137481d ok
    cowlib 1.0.2 (Hex package) (rebar) locked at 1.0.2 (cowlib) ok
    cowboy 1.0.4 (Hex package) (rebar) locked at 1.0.4 (cowboy) ok
    plug 1.1.2 (Hex package) (mix) locked at 1.1.2 (plug) ok
    phoenix_html 2.5.0 (Hex package) (mix) locked at 2.5.0 (phoenix_html) ok
    phoenix 1.2.0-dev (https://github.com/phoenixframework/phoenix.git) (mix) locked at f1d77c1 ok

    phoenix_live_reload 1.0.3 (Hex package) (mix)
    locked at 1.0.3 (phoenix_live_reload)
    ok

    NodeJS version (node -v):
    v5.7.0
    NPM version (npm -v): 3.8.0
    Operating system: OSX 10.10.2

**Comment by ericmj** [comment]
This is due to how Elixir's OptionParser works, it would have to be improved there first.

**Comment by chrismccord** [comment]
As Eric said, this is something that would be preferably handled on the Elixir `OptionParser` side so I don't thinks it's something we should address here. Thanks!

**Comment by lexmag** [comment]
We can easily improve it with existing `OptionParser`, we should [use `:strict` option instead of `:switches`](https://github.com/phoenixframework/phoenix/blob/71b55933aef9069aed982bbc6979d8eb9eaaae3f/installer/lib/phoenix_new.ex#L148) and print the errors if any of them exists.
Even with the change on the Elixir side we would need to use `:strict` option anyway.
