### ISSUE TITLE
Publish js client file to npm

### ISSUE THREAD

**Issue by JackSt** [phoenixframework/phoenix#1585]
The amount of phoenix packages is confusing, we need an official package to be finally published to npm.

**Comment by JackSt** [comment]
@chrismccord why did you close the issue? Isn't it the thing, that needs to be done?

**Comment by chrismccord** [comment]
Please see the dozen other issues around this and check the guidelines before opening an issue in the future. Thanks!

**Comment by JackSt** [comment]
@chrismccord Nice move, Chris. We can clearly see your attitude to js community. Thanks! :+1:
