### ISSUE TITLE
Set minimum length to phoenix.gen.secret

### ISSUE THREAD

**Issue by riverrun** [phoenixframework/phoenix#1587]
At the moment, you can run `mix phoenix.gen.secret` with any non-negative number, and there is no minimum length. You can, for example, run `mix phoenix.gen.secret 0`, and it will give you an empty string. I think we should be setting a minimum for this, perhaps at 32, which seems to be the minimum in the gen.secret test.

A possible fix would be to add a guard to the `random_string` function:

    defp random_string(length) when length > 31 do
      :crypto.strong_rand_bytes(length) |> Base.encode64 |> binary_part(0, length)
    end
    defp random_string(_), do: Mix.raise "that's too short!"

**Comment by chrismccord** [comment]
:+1 PR?

**Comment by riverrun** [comment]
I can send a PR, but maybe it's easier if you just add those few lines yourself.
