### ISSUE TITLE
Rendering errors causes issues with before_send callbacks

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix#1594]
### Environment

* Elixir version (elixir -v): 1.2.3
* Phoenix version (mix deps): 1.1.4
* Operating system: OS X 10.11.3

### Current behavior

We have a plug that makes sure that we check that a user has permission to access a specific action. The plug will raise if we forget to check for a permission. After digging around the Phoenix code for awhile it looks like `call` is overridden in the router or in the endpoint and catches exceptions and tries to render them. This causes the `before_send` callbacks to be called, but it uses an old version of the connection (the one from the router I believe).

```elixir
defmodule RequirePermissionCheck do
  def init(opts), do: opts
  
  def call(conn, _opts) do
    register_before_send(conn, fn(conn) ->
      if conn.assigns[:permissions_checked] do
        conn
      else
        raise "Make sure you check the permissions for /admin routes"
      end
    end)
  end
end

defmodule MyApp.Router do
  use Phoenix.Router
  
  scope "/admin", MyApp do
    pipe_through [:browser, RequirePermissionCheck]
    
    get "/users/:id", UserController, :show
  end
end

defmodule MyApp.UserController do
  use MyApp.Web, :controller
  
  plug :require_permissions, :view_users
  
  def show(conn, _params) do
    # Raises Ecto.NoResultsError, but also calls the register_before_send 
    # when attempting to render the error
    Repo.get!(User, 99999)
  end
  
  defp require_permission(conn, permission_name) do
    conn
    |> assign(:permissions_checked, true)
    |> check_permission(permission_name)
  end
  
  defp check_permission(conn, permission_name) do
    if permission_name in conn.assigns.user.permissions do
      conn
    else
      conn |> send_resp(403, "you need permission") |> halt
    end
  end
end
```

### Expected behavior

I would expect for the before_sends to not be called when a an error is raised, especially since the state of the connection is not the last state of the connection, but the state from further up the stack. I think that the `before_sends` should be stripped before attempting to render the error with the ErrorView. This will make it so that before_sends don't throw an error because they expect the conn to be in a state from further down the plug stack.

**Comment by josevalim** [comment]
> I would expect for the before_sends to not be called when a an error is raised, especially since the state of the connection is not the last state of the connection, but the state from further up the stack.

I don't think that's generally true. We may as well think of other before_send that MUST be invoked in those situations, like a Logger one. The truth is that you are putting the connection in a state that can never be rendered.

My suggestion to fix this is to actually move this to the endpoint. Have a plug after the router that will check if the permissions plug was invoked and, if that's the case, the permissions were eventually checked. This way you guarantee it is invoked only on success cases.

**Comment by paulcsmith** [comment]
@josevalim I didn't think of the logger when I wrote this. Those are excellent points. I also didn't think of adding it to the end of the endpoint after the router plug. Thank you for the great suggestion! It worked perfectly
