### ISSUE TITLE
`package.json` generated by `mix phoenix.new` needs to have `babel-preset-es2015`

### ISSUE THREAD

**Issue by kirbyfan64** [phoenixframework/phoenix#1596]
### Environment

* Elixir version (elixir -v): Elixir 1.3.0-dev (e1a1065)
* Phoenix version (mix deps): 1.1.4
* NodeJS version (node -v): 5.6.0
* NPM version (npm -v): 2.7.4
* Operating system: Ubuntu 14.04 x64

### Expected behavior

Running `mix phoenix.new <directory>` and then `npm install` in that directory should install ALL dependencies.

### Actual behavior

It doesn't. Recent versions of Babel require you to manually install the presets (see point 3 [here](http://jamesknelson.com/the-six-things-you-need-to-know-about-babel-6/)), but `package.json` doesn't list `babel-preset-es2015`. Therefore, running `mix phoenix.server` will output:

```
[info] Running HelloPhoenix.Endpoint with Cowboy using http on port 4000
15 Mar 15:37:02 - error: Compiling of web/static/js/app.js failed. Couldn't find preset "es2015" relative to directory "web/static/js" ; Compiling of web/static/js/socket.js failed. Couldn't find preset "es2015" relative to directory "web/static/js"
```

**Comment by chrismccord** [comment]
Please update to the latest `npm` version ~ `3.x.x` and that should solve it for you.

**Comment by kirbyfan64** [comment]
@chrismccord Maybe the installation guide should mention that that version is needed?

**Comment by chrismccord** [comment]
Since node 5.x comes with npm 3.x, I don't think we need it in the guides, but I'm glad you got everything up and running!

**Comment by kirbyfan64** [comment]
> node 5.x comes with npm 3.x

Yeah, that's probably because of the way I updated Node...whoops...
