### ISSUE TITLE
Anti-generator mix tasks

### ISSUE THREAD

**Issue by EricSchank** [phoenixframework/phoenix#1597]
As someone who's new to Phoenix, I find myself (too often) wanting to "undo" a call to `phoenix.gen.html` and it's friends.  It would be very helpful to be able to rollback or destroy the files that were created by the generator.

Something like `phoenix.des.html User users` could solve this by deleting all the previously generated files.

**Comment by chrismccord** [comment]
Thanks for the idea and PR, but your version control system in these cases is your friend and best place for cleaning up unwanted changes. I am :-1: on this because it's tricky to know which files you don't and don't want deleted. Thanks!

**Comment by romenigld** [comment]
I would like to have this destroy for rollback as well..
