### ISSUE TITLE
How to fetch data using Phoenix Framework?

### ISSUE THREAD

**Issue by HamzaLJ** [phoenixframework/phoenix#1602]
I have a server where the Phoenix Framework is installed. Now, I am trying to fetch the data sent from the server using the [client JS library](https://www.npmjs.com/package/phoenix-elixir). But I am stuck in the middle, there is no documentation/tutorial, whatsoever how to implement it and run it on the client side.

I've been digging for the last couple of hours, but unfortunately there is almost no resources about what I am looking for.

Currently, I have an HTML/JS page in which I would like to preview the data fetched using the client library.

I KNOW, MAYBE IT'S NOT THE RIGHT PLACE POST IT BUT BELIEVE ME, I NEED YOU URGENT HELP AS I THERE IS NO DOCUMENTATIONS/TUTORIALS SHOWING HOW TO DO IT AND I AM STUCK IN THE MIDDLE.

**Comment by chrismccord** [comment]
Please consult the mailing list per the issue template. Thanks!

**Comment by HamzaLJ** [comment]
@chrismccord, can you please give me a direct link for the mailing list? 
Or do me a big favor, and help me?

**Comment by chrismccord** [comment]
* [phoenix-talk Mailing list][5]
* [#elixir-lang][1] on [Freenode][2] IRC
* [elixir-lang slack channel][3]


  [1]: https://webchat.freenode.net/?channels=#elixir-lang
  [2]: http://www.freenode.net/
  [3]: https://elixir-slackin.herokuapp.com/
  [5]: http://groups.google.com/group/phoenix-talk
