### ISSUE TITLE
Unable to join ("Ignoring unmatched topic" error) #989

### ISSUE THREAD

**Issue by shanthivardhan** [phoenixframework/phoenix#1603]
I am seeing this issue "Ignoring unmatched topic" when I try to join from sample iOS app with the following configuration in my user_socket.ex.

`
    defmodule PhoenixServer.UserSocket do
      use Phoenix.Socket
      channel "test:*", PhoenixServer.TestChannel , via: [Phoenix.Transports.WebSocket]
      transport :websocket, Phoenix.Transports.WebSocket
      transport :longpoll, Phoenix.Transports.LongPoll
    end
`

Removing , via: [Phoenix.Transports.WebSocket] fixes the issue.

**Comment by chrismccord** [comment]
You have a race condition on the client that is creating duplicate subscriptions. Removing the transport "fixes" it by refusing to accept any websocket connections :) Please search the issues for similar questions. Thanks!
