### ISSUE TITLE
(KeyError) key :otp_app not found

### ISSUE THREAD

**Issue by yours0** [phoenixframework/phoenix#1604]
web/models/repo.ex:1: warning: redefining module BookStore.Repo

== Compilation error on file web/models/repo.ex ==
** (KeyError) key :otp_app not found in: [adapter: Ecto.Adapters.Postgres]
    (elixir) lib/keyword.ex:312: Keyword.fetch!/2
    lib/ecto/repo/supervisor.ex:32: Ecto.Repo.Supervisor.parse_config/2
    web/models/repo.ex:2: (module)
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

### Environment

* Elixir version (elixir -v):Elixir 1.2.2
* Phoenix version (mix deps):* connection 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (connection)
  ok
* fs 0.9.1 (Hex package) (rebar)
  locked at 0.9.2 (fs)
  ok
* gettext 0.10.0 (Hex package) (mix)
  locked at 0.10.0 (gettext)
  ok
* ranch 1.2.1 (Hex package) (rebar)
  locked at 1.2.1 (ranch)
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy)
  ok
* decimal 1.1.1 (Hex package) (mix)
  locked at 1.1.1 (decimal)
  ok
* poison 1.5.2 (Hex package) (mix)
  locked at 1.5.2 (poison)
  ok
* db_connection 0.2.3 (Hex package) (mix)
  locked at 0.2.3 (db_connection)
  ok
* cowlib 1.0.2 (Hex package) (rebar)
  locked at 1.0.2 (cowlib)
  ok
* cowboy 1.0.4 (Hex package) (rebar)
  locked at 1.0.4 (cowboy)
  ok
* plug 1.1.1 (Hex package) (mix)
  locked at 1.1.1 (plug)
  ok
* phoenix_html 2.5.0 (Hex package) (mix)
  locked at 2.5.0 (phoenix_html)
  ok
* phoenix 1.1.4 (Hex package) (mix)
  locked at 1.1.4 (phoenix)
  ok
* phoenix_live_reload 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (phoenix_live_reload)
  ok
* postgrex 0.11.1 (Hex package) (mix)
  locked at 0.11.1 (postgrex)
  ok
* ecto 1.1.3 (Hex package) (mix)
  locked at 1.1.3 (ecto)
  ok
* phoenix_ecto 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (phoenix_ecto)
  ok
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:win7

repo.ex:
defmodule BookStore.Repo do use Ecto.Repo, adapter: Ecto.Adapters.Postgres
	def conf do
		parse_url "ecto://postgres:123456@localhost/book_store_dev"
	end
    def priv do
      app_dir(:book_store, "priv/repo")
    end
end
### Expected behavior
database create

### Actual behavior
error

**Comment by josevalim** [comment]
Hi! :) You are using a very old example of Ecto repository. Check the README on Ecto for an example on how to set up the repository with configuration: https://github.com/elixir-lang/ecto
