### ISSUE TITLE
Phoenix.CodeReloader causes incredibly show responses

### ISSUE THREAD

**Issue by madshargreave** [phoenixframework/phoenix#1606]
Hey

For some reason, when I have Phoenix.CodeReloader enabled under code reloading, requests on my local machine takes around 10 seconds to complete.

Upon an incoming request, the log shows nothing until after that timeframe. When the first request log message appear, the request is fulfilled immediately. 

I have tried to isolate the problem by disabling various plugs in the pipeline, but i'm sure it's due to Phoenix.CodeReloader now.

Any ideas?

**Comment by josevalim** [comment]
Can you please fill in a proper bug report using the template that shows up before you open up an issue? We need to know Phoenix version, Elixir versions and things like that.

**Comment by josevalim** [comment]
Closing and waiting for the new report, thank you.

**Comment by madshargreave** [comment]
I have narrowed it down to my web/static folder being the cause of the issue.

If I remove all my js/css and assets, the problem goes away.

In my JS folder I have to seperate webpack React projects

**Comment by madshargreave** [comment]
The time delay is directly correlated with the size/number of packages in node_modules

**Comment by josevalim** [comment]
@madshargreave I think you meant to add that to #1607. :) Btw, that would totally explain the issue. Do you have node_modules inside web/static?

**Comment by madshargreave** [comment]
Indeed I have

**Comment by josevalim** [comment]
@madshargreave do you have an option to not do that? Because Elixir will look at all directories in web for Elixir files.

**Comment by madshargreave** [comment]
I see, currently I have just 'embedded' an self-contained React app inside the static folder. I will look into it

**Comment by josevalim** [comment]
Cool. webpack should allow you have stuff at the root of the phoenix project and compile stuff outside.I am really glad you figure this out though, great job!

**Comment by madshargreave** [comment]
Thanks, I'll try that :)
