### ISSUE TITLE
Asset paths are wrong when forwarding in router

### ISSUE THREAD

**Issue by ericmj** [phoenixframework/phoenix#1608]
When using another phoenix project as a dependency I have to hard-code the paths to my assets. It would be nice if i could prefix them under a path like is done for all other router helpers when forwarding.

Relatedly, there is no way currently to make phoenix pick up the manifest.json of a dependency to generate digested static paths.

/cc @josevalim

**Comment by chrismccord** [comment]
If you pass the endpoint module to the `static_path` helper it will use the correct path, but ideally we'd be able to reconcile if you pass the conn instead. @ericmj is this something you'd like to tackle?

**Comment by josevalim** [comment]
I asked @ericmj to open this because we certainly choose to not do so for
@conn but I can't remember the reasons.

**Comment by ericmj** [comment]
Yes, I would like to help out here. But I need some guidance on how to solve it since I assume it requires API changes.

**Comment by joshnuss** [comment]
So if app A depends on app B, does this mean all of B's assets need to be compiled with webpack into another bundle? or should A just import B's assets as needed?
