### ISSUE TITLE
Upgrade brunch to 2.5.x

### ISSUE THREAD

**Issue by dmitriid** [phoenixframework/phoenix#1610]
### Environment

* Phoenix version: 1.1.4

### Expected behavior

Compile NPM scoped packages (`@<orgname>/<packagename>`)

### Actual behavior

Fails to compile due to https://github.com/brunch/brunch/issues/1213 which was recently fixed.

---

A very quick preliminary glance showed that upgrading to latest brunch shouldn't break anything
Also note: since brunch 2.3.x the `npm` section in the brunch config is no longer required.

**Comment by chrismccord** [comment]
Thanks! Can you do an exhaustive check and make sure everything works as it should?

**Comment by dmitriid** [comment]
I'm currently working on a personal project, with .js files shuffled around etc. So far so good

I'll try to make a more exhaustive check, and get back to you

**Comment by dmitriid** [comment]
I guess you can close this issue for now. While still working on some personal staff ran into more problems with `@org/package` style packages (such as brunch not picking up `@`-packages imported from other `@`-packages). Couldn't figure out what the problem was, so ended up switching to webpack :)
