### ISSUE TITLE
Argument error exception in iolist_size() during Plug.Conn.send_resp/1 in prod environment only

### ISSUE THREAD

**Issue by kroburg** [phoenixframework/phoenix#1612]
### Description

The root cause of the problem is known. There were some put_flash() which used the 'char_list' instead of a "string" with unicode characters. I.e. put_flash(:error, 'Бум') instead of put_flash(:error, "Бум").

In development environment Phoenix merges whole response into the single "string". But in production environment it uses raw iolist. And that iolist contains 'char_lists' from put_flash().

Since I write a lot of Python on the daily basis, I'm used to write 's' for strings instead of "s". So we need to ensure that such errors will not sneak from dev to prod without notice.

### Environment

Elixir 1.2.3
Phoenix 1.1.4

### Sample stack trace

Phoenix crash on some requests with argument error exception:
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.iolist_size([[["" | "<!DOCTYPE html>n....
        (cowboy) src/cowboy_req.erl:901: :cowboy_req.reply_may_compress/7
        (cowboy) src/cowboy_req.erl:888: :cowboy_req.reply/4
        (plug) lib/plug/adapters/cowboy/conn.ex:34: Plug.Adapters.Cowboy.Conn.send_resp/4
        (plug) lib/plug/conn.ex:345: Plug.Conn.send_resp/1
        (clean_games) web/controllers/login_controller.ex:11: CleanGames.LoginController.action/2
        (clean_games) web/controllers/login_controller.ex:11: CleanGames.LoginController.phoenix_controller_pipeline/2
        (clean_games) lib/phoenix/router.ex:261: CleanGames.Router.dispatch/2

**Comment by josevalim** [comment]
We should really be catching the bug in development too. Thanks for the report.

**Comment by chrismccord** [comment]
Closed via https://github.com/phoenixframework/phoenix_html/commit/cb24e1ec0796146fa6d90a69fd24ed5fe33af1a2
Thanks for reporting!
