### ISSUE TITLE
Channel doesn't receive "OK" callback

### ISSUE THREAD

**Issue by madshargreave** [phoenixframework/phoenix#1618]
Elixir 1.2.1
Phoenix (master branch)
Node v5.0.0
NPM 3.7.3
Mac OSX El Capitan 10.11.2

### Expected behavior
I am trying to join a Phoenix channel from my React application. On the server I successfully join the channel, so I expected the channel.recieve('ok..) callback to be invoked

### Actual behavior

Client Code:

```
const channel = socket.channel('apps:' + appId, {visitor_id: visitorId})

    channel.join()
      .receive('ok', (response) => {
        console.log("OK APP")
        dispatch(openAppConnectionSuccess())
      })
      .receive('error', (response) => {
        const message = humps.camelizeKeys(message.data)

        dispatch(openAppConnectionFailure())
      })
      .receive("timeout", () => console.log("Networking issue. Still waiting...") )
```
Even though I receive the OK event from the server, the receive('ok) is never invoked.

My server logs:

```
info] JOIN apps:ASD-VyMXJS5Jk to Resend.AppChannel
  Transport:  Phoenix.Transports.WebSocket
  Parameters: %{"visitor_id" => "53a878e0-f33e-11e5-b672-cdd8ee86b4e0"}
[info] Replied apps:ASD-VyMXJS5Jk :ok
[info] Resend.AppChannel received join event with topic "apps:ASD-VyMXJS5Jk" but channel already joined
```

Client logs: 

```
push: apps:ASD-VyMXJS5Jk phx_join (1) Object {visitor_id: "53a878e0-f33e-11e5-b672-cdd8ee86b4e0"}
client.js?6a8d:55 [HMR] connected
socket.js:5 channel: timeout apps:ASD-VyMXJS5Jk 10000
phoenix.js:61 Networking issue. Still waiting...
socket.js:6 transport: connected to ws://localhost:4000/socket/websocket?vsn=1.0.0 EventTarget {CONNECTING: 0, OPEN: 1, CLOSING: 2, CLOSED: 3}
socket.js:12 Socket open
socket.js:5 transport: connected to ws://localhost:4000/socket/websocket?vsn=1.0.0 EventTarget {CONNECTING: 0, OPEN: 1, CLOSING: 2, CLOSED: 3}
socket.js:11 Socket open callback
socket.js:5 receive: ok apps:ASD-VyMXJS5Jk phx_reply (1) Object {status: "ok", response: Object}
socket.js:5 receive:  apps:ASD-VyMXJS5Jk presence_diff  Object {leaves: Object, joins: Object}
socket.js:5 push: apps:ASD-VyMXJS5Jk phx_join (2) Object {visitor_id: "53a878e0-f33e-11e5-b672-cdd8ee86b4e0"}
socket.js:5 receive: error apps:ASD-VyMXJS5Jk phx_reply  Object {status: "error", response: Object}
```

**Comment by chrismccord** [comment]
You appear to have a race condition on the client where you need to close the channel before rejoining:

> [info] Resend.AppChannel received join event with topic "apps:ASD-VyMXJS5Jk" but channel already joined

Can you double check your logic and report back?

**Comment by madshargreave** [comment]
There's only a single place I join the channel in my code and this is run once when the application launches (double checked this)

I noticed the error occurs once I connect from another browser, or simply refreshes the page.

Should I call channel.leave, before calling channel.join() to make sure it's closed properly? This seems inefficient

**Comment by chrismccord** [comment]
The only way you'll receive this is if you are firing `join` more than once, or instantiating two channel objects on the same topic that both join. So there's something going on in the app, maybe a double binding issue?

**Comment by madshargreave** [comment]
Hmm

I noticed on repeat rejoins I get

push: apps:ASD-VyMXJS5Jk phx_join (null)

Why this is?

**Comment by chrismccord** [comment]
The ref should never be null on join and I don't see a code path that would allow it to be. Are you on the latest js client?

**Comment by madshargreave** [comment]
Yep I'm on the latest

**Comment by chrismccord** [comment]
Can you provide an example that reproduces this?

**Comment by chrismccord** [comment]
Please provide an example app to reproduce this issue and I can take a look. In the meantime, I'm cleaning up some issues. Thanks!

**Comment by madshargreave** [comment]
Problem is resolved now, it was due to me having a large node_modules inside my web folder

**Comment by mariolorente** [comment]
@madshargreave What was exactly the problem? I am facing exactly the same
