### ISSUE TITLE
CSRF protection issue w/ Safari

### ISSUE THREAD

**Issue by endersstocker** [phoenixframework/phoenix#1621]
### Environment

* Elixir version: 1.2.3
* Phoenix version: 1.1.4
* NodeJS version: 5.9.1
* NPM version: 3.7.3
* Operating system: OS X 10.11.4 / iOS 9.2.1

### Steps to reproduce

1. View a Phoenix form in a browser that is configure to reopen the last page on launch
2. Quit the browser
3. Relaunch the browser
4. Submit the form

### Expected behavior

The form should post without raising `Plug.CSRFProtection.InvalidCSRFTokenError` in all modern browsers.

### Actual behavior

Posting the form raises `Plug.CSRFProtection.InvalidCSRFTokenError` in Safari for both OS X and iOS.

### Test case

A [bare-bones Phoenix app](//github.com/endersstocker/csrf-test) to demonstrate the issue.

### References

This issue appears to affect Rails as well. See: [https://github.com/rails/rails/issues/21948]()

It is suggested there that the issue affects Chrome on Android as well.

**Comment by chrismccord** [comment]
I'm not sure how we could address this without going the route that Django chose, but they seem to have had their own set of issues. Also since [OWASP suggests the shorter the token TTL the better](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#General_Recommendation:_Synchronizer_Token_Pattern]), I don't like any possible workaround that goes against this. @kronicdeth any thoughts here?

**Comment by KronicDeth** [comment]
I feel like this is similar to something we encountered when I worked at Rapid7.  If that's the case, @joevennix may be able to help.  He worked a lot on Safari issues when we were both working there.

**Comment by endersstocker** [comment]
@chrismccord I agree that a long-lasting cookie is not the solution. Forms on [Twitter](//twitter.com/login) and [Google](//accounts.google.com/ServiceLogin) appear to refresh their tokens when Safari is relaunched. I’m not sure what mechanisms they are using to achieve this.

**Comment by aphillipo** [comment]
>>> Forms on Twitter and Google appear to refresh their tokens when Safari is relaunched

At least twitter is 100% javascript at this point and thus probably can't be cached in the same way by the browser.

Setting Cache-Control header to no-store, no-cache should fix this according to the above bug and this is exactly what you are telling the browser to do - don't cache the form if there is a CSRF required.

**Comment by aphillipo** [comment]
What do people think about catching Plug.CSRFProtection.InvalidCSRFTokenError and redirecting to the current page by default, thus getting a new token?

**Comment by chrismccord** [comment]
That sounds like a really good solution as long as you can prevent infinite redirects/retries, maybe with a query param?

**Comment by aphillipo** [comment]
Actually it doesn't work because this isn't on the page reload it's on form submission from the cached loaded page.  I'll try the cache-control no-store, no-cache stuff now and send a PR if it works.

**Comment by aphillipo** [comment]
It looks like the actual fix will go into Plug itself, not phoenix.  

I tried adding the no-store, no-cache in the example and the issue is fixed.

I intend to check for a csrf token before adding the header in the csrf plug so you can probably close this.

**Comment by chrismccord** [comment]
Sounds good. Thanks!
