### ISSUE TITLE
Multiple posts results in PUT

### ISSUE THREAD

**Issue by tdejager** [phoenixframework/phoenix#1625]
### Environment

* Elixir version (elixir -v): Elixir 1.2
* Phoenix version (mix deps): Phoenix 1.1.4
* NodeJS version (node -v): 5.1.0
* NPM version (npm -v): 3.3.12
* Operating system: OSX

### Expected behavior

My routes are defined as follow:

```elixir
    get "/", FooController, :index
    get "/activeren/:code", FooController, :card_index: 
    post "/activeren", FooController, :activate
    # For testing
    get "/view/:lot_nummer", FooController, :view
```

All these methods are also implemented in the FooController. In the index method I display a form that the user must fill in. Some incorrect input can cause the form to fail. In my controller, I do some error handling:

```elixir
 case Recaptcha.verify(conn.remote_ip, params["g-recaptcha-response"]) do
      :ok ->
        case do_processing(client_params) do
          {:ok, client} ->
            ...
              {:ok, lot} ->
                .....
                conn
                |> put_flash(:info, "Activation was succesfull!")
                |> render("activate.html", lot: lot)
              {:error, txt} ->
                display_error(conn, txt, Client.changeset(client, client_params))

```

This all seems to work. The display errors method is as follows:

```elixir
 defp display_error(conn, errors, changeset) do
    conn
    |> put_flash(:error, "Errors: #{errors}" )
    |> render("index.html", changeset: changeset)
  end
```

This returns the user back to the form with some errors that are displayed. This template is the same as the one returned by the index method. At this point everything is still working as expected. However, when the user re-submits using the same form:

```
info] POST /activate
[warn] ** (Phoenix.Router.NoRouteError) no route found for PUT /activeren (Lukkieduck.Router)
    (lukkieduck) web/router.ex:1: Lukkieduck.Router.match_route/4
    (lukkieduck) web/router.ex:1: Lukkieduck.Router.do_call/2
    (lukkieduck) lib/lukkieduck/endpoint.ex:1: Lukkieduck.Endpoint.phoenix_pipeline/1
    (lukkieduck) lib/plug/debugger.ex:93: Lukkieduck.Endpoint."call (overridable 3)"/2
    (lukkieduck) lib/phoenix/endpoint/render_errors.ex:34: Lukkieduck.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

### Actual behavior

It seems as though the second post request erroneously triggers a PUT request even though somewhere in the pipeline it is seen as a POST.

When adding the following code:
```elixir
    put "/activeren", FooController, :activate
```
The request is handled correctly.

### Question
Could this be a bug or am I doing something wrong? Note I keep using the same request data, i.e. I don't do a redirect after an error because I would like to display the changeset in the form. Could this perhaps be the source of this error?

Thanks!

Tim

**Comment by chrismccord** [comment]
Can you include your form/template code?

**Comment by tdejager** [comment]
Sure! Btw, thank you for all the great work done chris, I'm very much enjoying the phoenix framework!

```eex

<%= form_for @changeset, foo_path(@conn, :activate), fn f -> %>
 
...

             <div class="form-group">
                    <%= text_input f, :client_first_name, [class: "form-control input-sm", placeholder: "First name", required: true] %>
                </div>
...
            <div class="row">
                <div class="form-group">
                    <div class="col-md-6">
                        <%= raw Recaptcha.display %>
                    </div>
                </div>
              </div>
 ...
                 <div class="form-group">
                    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                        <%= submit "Activate!", class: "btn btn-info btn-block" %>
                    </div>
                 </div>
<% end %>

```

I've left out some form fields but it's just a regular form.

Which is contained in my app.html.eex:

```eex

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Activeer hier uw lot!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>"></link>


  </head>

  <body>
      <header> </header>
    <div class="container-fluid body-content">

    <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    </div>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>
```

**Comment by chrismccord** [comment]
Thanks!

Aha, since you are using a changeset:

    <%= form_for @changeset, foo_path(@conn, :activate), fn f -> %>

The form method will be derived form the changeset persisted state. So POST for new records, PUT for existing records to be updated. We haven't seen the full code here so I'm not sure how your records are handled in the controller, but you can either accommodate updating the changeset via a PUT route, which is just fine, or your can force the method with a `method: "post"` option to the form.

**Comment by tdejager** [comment]
Ah thanks Chris, sorry could not find this with some googling. However, I suppose it should be somewhere in the documentation, and I just missed it thanks. To confirm yes, I was persisting the changeset to database.
