### ISSUE TITLE
Detecting presence away

### ISSUE THREAD

**Issue by madshargreave** [phoenixframework/phoenix#1636]
Hey

What's the preferred way of detecting/registering users as being away in the Presense module?

I'd like to set a user as away if they onfocus (switch) a tab in the browser, or if they haven't performed any actions for a set amount of time

**Comment by chrismccord** [comment]
Please use the issue templates when opening issues, as we've asked before :) This is a mailing list question so better to ask there. tldr; you can store a `last_active_at` time in the presence metadata and update it periodically from the channel and use this info on the client to assess "here but not active" states. Thanks!
