### ISSUE TITLE
Updating presences

### ISSUE THREAD

**Issue by madshargreave** [phoenixframework/phoenix#1639]
Elixir 1.2.1
Phoenix (master branch)
Node v5.0.0
NPM 3.7.3
Mac OSX El Capitan 10.11.2

Hi

I am storing the client's current URL pathname as metadata using Presence.

I am trying to update it as seen below:

```
def handle_info(:register, socket) do
    Presence.track(socket, id, %{
      id: id,
      location: nil,
      ..other_metadata
    })
    push socket, "presence_state", Presence.list(socket)

...
def handle_in("location_change", %{"location" => location}, socket) do
    id = socket.assigns.id
    Presence.update(socket, id, %{location: location})
    ...
```

Problem is that when I call update, the `presence_diff` event is dispatched in which the presence is both set in `joins` and `leaves`.

Furthermore, the previous `other_metadata` metadata is overriden, ie. the `joins` object only contains `%{location: location}`.

Is this a bug? If not, what is the correct way to simply update the presence as I'm trying to do here

UPDATE:

Client code:

```
import { createAction, handleActions } from 'redux-actions'
import { routeActions } from 'react-router-redux'
import { Presence } from 'phoenixjs'
import axios from '../utils/axios'
import humps from 'humps'

/*
Constants
 */

export const ACTIVE = 'active'
export const AWAY   = 'away'

export const PRESENCE_JOINED = 'PRESENCE_JOINED'
export const PRESENCE_LEFT   = 'PRESENCE_LEFT'
export const SET_PRESENCES   = 'SET_PRESENCES'

/*
Actions
 */

export const presenceJoined = createAction(PRESENCE_JOINED)
export const presenceLeft   = createAction(PRESENCE_LEFT)
export const setPresences   = createAction(SET_PRESENCES)

export function listenActivity () {
  return (dispatch, getState) => {
    const {
      phoenix: { channel }
    } = getState()

    const _presences = {}

    const onJoin = (id, current, newPres) => {
      if (!current) {
        // dispatch(presenceJoined({ id: newPres }))
      }
    }

    const onLeave = (id, current, leftPres) => {
      if (current.metas.length === 0) {
        // dispatch(setPresences({ presences }))
      }
    }

    channel.on('presence_diff', diff => {
      diff = humps.camelizeKeys(diff)
      console.log("BEFORE DIFF PRESENCE" , Object.keys(_presences).length, _presences["cnwmgoz0y000046ctfyvwq126"])
      Presence.syncDiff(_presences, diff)
      console.log("AFTER DIFF PRESENCE" , Object.keys(_presences).length, _presences["cnwmgoz0y000046ctfyvwq126"])

      let presences = Presence.list(_presences, listPresenceBy)
      dispatch(setPresences({ presences }))
    })

    channel.on('presence_state', state => {
      state = humps.camelizeKeys(state)
      Presence.syncState(_presences, state)

      let presences = Presence.list(_presences, listPresenceBy)
      dispatch(setPresences({ presences }))
    })
  }
}

export function setStatus ({ status }) {
  return (dispatch, getState) => {
    const { channel } = getState().phoenix

    const data = { status }
    const payload = humps.decamelizeKeys(data)
    channel.push("status_changed", payload)
  }
}

export const actions = {
  setPresences,
  presenceJoined,
  presenceLeft,
  setStatus
}

const initialState = {
  visitors: [],
  users: []
}

export default handleActions({
  [SET_PRESENCES]: (state, { payload }) => {
    const users = payload.presences.filter(presence => presence.type === 'user')
    const visitors = payload.presences.filter(presence => presence.type === 'visitor')

    return {
      ...state,
      visitors,
      users
   }
  }
}, initialState)

function listPresenceBy (id, { metas: [first, ...rest]}) {
  first.id = id
  return first
}
```

**Comment by chrismccord** [comment]
We need to see your client code as well. Updating a presence will indeed be sent as a back-to-back leave followed by a join, but the way the `Phoenix` javascript object applies the events maintains order.

**Comment by madshargreave** [comment]
Updated

**Comment by chrismccord** [comment]
We need to see more code than that. Particularly what does setPresences do? It would also be helpful to see the web console logs by enabling the `logger` option on the client, as well as a logged information on what your `presences` object looks like before and after apply the diff. Without more information it's hard to understand what isn't working for you. Thanks!

**Comment by madshargreave** [comment]
Updated with full file

Also, this is before/after of applying diff

```
// Before

{
  appId: "ASSg-022I4pZc",
  avatar : null,
  id: "clmh9e2dg00008zctfyvwq126",
  phxRef: "g20AAAAIsdzaneRo6H0=",
  status: "active",
  type: "visitor"
}


// After
{
  id: "clmh9e2dg00008zctfyvwq126"
  location: "/settings/profile"
  phxRef: "g20AAAAIWnIKeaXg6XA="
  phxRefPrev: "g20AAAAIsdzaneRo6H0="
}
```

**Comment by chrismccord** [comment]
For the logging, please show all the output of the console when you run:
    
    let socket = new Socket("/ws", {logger: (kind, msg, data) => { console.log(`${kind}: ${msg}`, data) } })

Also please log the *entire* `presences` object, not just what the callback receives.

**Comment by chrismccord** [comment]
It looks like you are keeping your own `state.presences` list and adding/removing, where you should be using `Presence.list(presences, listBy)` and provide a listBy functions o choose/extend the metadata you care about. The result of that call can then be set as the `state.presences` instead of keeping your own map and trying to keep state on join/leave yourself. Please try that and report back

**Comment by madshargreave** [comment]
Updated client code as suggested. 

Example of how I am loosing the previous metadata on updates

<img width="861" alt="screen shot 2016-04-11 at 19 37 05" src="https://cloud.githubusercontent.com/assets/5479890/14436463/170f53ea-001d-11e6-99a6-64b81e084146.png">

**Comment by chrismccord** [comment]
Please log the entire `presences` object. The diff is correct as it contains both join and leave as expected.

**Comment by madshargreave** [comment]
Diff:

<img width="1194" alt="screen shot 2016-04-11 at 20 13 15" src="https://cloud.githubusercontent.com/assets/5479890/14437546/067ca0c8-0022-11e6-822a-47bb1153eb81.png">

`presences` object

<img width="1238" alt="screen shot 2016-04-11 at 20 13 53" src="https://cloud.githubusercontent.com/assets/5479890/14437562/15fe5ac8-0022-11e6-8999-9d52f4e62752.png">

**Comment by chrismccord** [comment]
I need to also the the `presences` object *before* the diff :)

**Comment by madshargreave** [comment]
For some reason my consol was bugging out when I was logging the whole object, so here I just log the presence[affectedId] instead.

receive:
<img width="1149" alt="screen shot 2016-04-11 at 22 15 43" src="https://cloud.githubusercontent.com/assets/5479890/14441056/2dee8976-0033-11e6-95d7-4ca0f99288f6.png">


affected key in presences:
<img width="717" alt="screen shot 2016-04-11 at 22 16 03" src="https://cloud.githubusercontent.com/assets/5479890/14441059/32f6336a-0033-11e6-9aa4-96cba4d16319.png">

As you can see, it simply gets removed

**Comment by chrismccord** [comment]
The entire `presences` object is undefined? Can you update your code with the latest you are using, including the console.logs?

**Comment by madshargreave** [comment]
No, sorry if I'm being unclear. For some reason, Chrome was unable to properly log the whole object at once, so I just logged the affected ID/entity

Ill update the code so you can see

**Comment by chrismccord** [comment]
I need to see the whole thing. Is this code public somewhere? It's hard to debug without all the datas :)

**Comment by chrismccord** [comment]
Can you package up a basic app that recreate this issue and push to github? That would be the best way to move forward and try to diagnose. Thanks!

**Comment by madshargreave** [comment]
Ill try to setup a basic app as soon as I have time, however I discovered 2 things.

1) I was camelCasing the socket response before calling the syncDiff/syncState, which fails because `syncDiff` is removing leaves using `phx_ref` and not `phxRef`.

2) It appears that it's not the frontend code that's the head of the problem. Even upon receiving the initial `presence_state` event, it has overriden the the old metadata from the call to `Presence.update`

This is my server code

```
def handle_in("visitor_location_change", %{"location" => location}, socket) do
    id = socket.assigns.id
    Presence.update(socket, id, %{location: location}) // this part overrides the other metadata instead of merging it
    {:noreply, socket}
  end

  def handle_info(:register, socket) do
    %{id: id, type: type, app_id: app_id} = socket.assigns

    Presence.track(socket, id, %{
      id: id,
      status: "active",
      type: type,
      app_id: app_id,
    })

    push socket, "presence_state", Presence.list(socket)
    {:noreply, socket}
  end
```

**Comment by chrismccord** [comment]
Update does *not* merge, it updates the presence with the new metadata, so your `Presence.update(socket, id, %{location: location})` would replace all metadata previously. If you want to include the prev values, you need to provide them. I think that solves everything, no?

**Comment by madshargreave** [comment]
I see, that was the problem. Thanks for the help, much appreciated
