### ISSUE TITLE
Add lib/ to reloadable_paths by default

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1642]
Pending feedback

**Comment by wojtekmach** [comment]
(sorry if this point was already discussed) would this change the `lib/` vs `web/` debate? AFAIK up to this point the distinction was made precisely about reloading.

**Comment by josevalim** [comment]
There is a discussion in the mailing list but it would end the lib/ vs web/ debate. We have other plans for that but it may take a while to become concrete. :)

**Comment by wojtekmach** [comment]
Good thing Programming Phoenix haven't hit the bookshelves yet ;-)
