### ISSUE TITLE
Allow pubsub_server configuration on channels

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1644]

**Comment by chrismccord** [comment]
Holding on this for now

**Comment by josevalim** [comment]
Do you remember the rationale? I believe we agreed on this after our Skype calls? Also as a way to unify both Presence and Channel APIs?

**Comment by chrismccord** [comment]
We still need to figure out the unification but the issue is the channel level is not the right place because the transport must know about the pubsub server, for example for the "disconnect" message as well as the long poll server. So we need this info one level up

**Comment by josevalim** [comment]
Maybe the socket is enough? Let's see how it will end up after I merge Sasa
changes.

On Friday, May 20, 2016, Chris McCord <notifications@github.com> wrote:

> We still need to figure out the unification but the issue is the channel
> level is not the right place because the transport must know about the
> pubsub server, for example for the "disconnect" message as well as the long
> poll server. So we need this info one level up
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1644#issuecomment-220678470>
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
