### ISSUE TITLE
Namespaced app fails to render internal server error

### ISSUE THREAD

**Issue by vic** [phoenixframework/phoenix#1648]
### Environment

* Elixir version (elixir -v): 1.2.4
* Phoenix version (mix deps): master
* NodeJS version (node -v): na
* NPM version (npm -v): na
* Operating system: OSX El Capitan

### Steps to reproduce

1. Using the latest phoenix distribution, just create a new application with a custom namespace:

```
mix phoenix.new foo_bar --module Foo.Bar
```

2. cd into the app and run `mix test` as normal, all test are green at this step.
3. change PageController to raise an exception on an action.
    For example, by creating an invalid pattern match `1 = 2`
4. run `mix test` again, one test is red as expected but the error message is not.

### Expected behavior

Expected the following error caused by our change
```
  1) test GET / (Foo.Bar.PageControllerTest)
     test/controllers/page_controller_test.exs:4
     ** (MatchError) no match of right hand side value: 2
```

### Actual behavior

The reported error is:
````
 1) test GET / (Foo.Bar.PageControllerTest)
     test/controllers/page_controller_test.exs:4
     ** (UndefinedFunctionError) undefined function Foo.ErrorView.render/2 (module Foo.ErrorView is not available)
     stacktrace:
       Foo.ErrorView.render("500.html", %{conn: %Plug.Conn{adapter:
````

### Possible Solution

After getting this error and looking at phoenix master, I found the solution was to
change the `web/web.ex` file inside my application and explicitly set the error view:

```elixir
  def router do
    quote do
      use Phoenix.Router
      # Following line fixes this issue
      use Phoenix.Endpoint.RenderErrors, view: Foo.Bar.ErrorView, accepts: ~w(html)
    end
  end
```

After this change, `mix test` report the correct error caused by our bad pattern match.

My guess is that when provided a custom namespaced module, the generator under
`installer/templates/new/web/web.ex` should also emit the line to specify an ErrorView.
Is this correct? Or am I missing something, I'd be more than happy to provide a test and patch
if you can confirm this is the way to go for solving this issue.

Cheers!

**Comment by chrismccord** [comment]
The solution is to set the `ErrorView` in your configuration:

https://github.com/phoenixframework/phoenix/blob/ecd84f283f0203163b1f864747e1d0acd5aeca64/lib/phoenix/endpoint.ex#L71-L77 . I'll take a look at accommodating this in the generator. Thanks!
