### ISSUE TITLE
Fix `module_to_template_root` for modules without prefix.

### ISSUE THREAD

**Issue by alexeypetrushin** [phoenixframework/phoenix#1651]
Currently it works like following:

```
Phoenix.Template.module_to_template_root(MyApp.UserView, MyApp, "View") # => user
Phoenix.Template.module_to_template_root(UserView, MyApp, "View") # => ""
```

For small apps using `MyApp` prefix everywhere feels too verbose. But, if I try to rename view from `MyApp.UserView` to `UserView` it fails because suddenly it can't find templates anymore.

To fix it we can change it to work as following:

```
Phoenix.Template.module_to_template_root(UserView, MyApp, "View") # => "user"
```

**Comment by Gazler** [comment]
You can use an alias for this.

```
Phoenix.Template.module_to_template_root(UserView, MyApp, "View") # => ""
alias MyApp.UserView
Phoenix.Template.module_to_template_root(UserView, MyApp, "View") # => "user"
```

**Comment by josevalim** [comment]
Let's please move this discussion to the core mailing list as well. It can be a separate one to the current there. You may be able to use the :namespace option to fix this too, by setting the option to `namespace: Elixir` although my feedback would be to not drop namespaces.
