### ISSUE TITLE
websocket raises an erlang error message when a matching connect is not found

### ISSUE THREAD

**Issue by DylanBruzenak** [phoenixframework/phoenix#1659]
### Environment

* Elixir version (elixir -v): Elixir 1.2.3

* Phoenix version (mix deps): phoenix 1.0.4
* NodeJS version (node -v): v5.10.1
* NPM version (npm -v): 3.8.3
* Operating system: ubuntu 14.04
docker image: https://github.com/marcelocg/phoenix-docker/blob/master/Dockerfile

### Expected behavior

Should print a nicely formatted elixir error. 

### Actual behavior

Prints an erlang error:

** (ErlangError) erlang error: [reason: :function_clause, mfa: {Phoenix.Endpoint.CowboyWebSocket, :init, 3}, stacktrace: [{ChatServer.UserSocket, :connect, [%{"auth_token" => "TEST_TOKEN"}, %Phoenix.Socket{assigns: %{}, channel: nil, channel_pid: nil, endpoint: ChatServer.Endpoint, handler: ChatServer.UserSocket, id: nil, joined: false, pubsub_server: ChatServer.PubSub, ref: nil, serializer: Phoenix.Transports.WebSocketSerializer, topic: nil, transport: Phoenix.Transports.WebSocket, transport_name: :websocket, transport_pid: #PID<0.337.0>}], [file: 'web/channels/user_socket.ex', line: 23]}, {Phoenix.Socket.Transport, :connect_vsn, 6, [file: 'lib/phoenix/socket/transport.ex', line: 157]}, {Phoenix.Transports.WebSocket, :init, 2, [file: 'lib/phoenix/transports/websocket.ex', line: 77]}, {Phoenix.Endpoint.CowboyWebSocket, :init, 3, [file: 'lib/phoenix/endpoint/cowboy_websocket.ex', line: 11]}, {:cowboy_handler, :handler_init, 4, [file: 'src/cowboy_handler.erl', line: 64]}, {:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 442]}], req: [socket: #Port<0.6358>, transport: :ranch_tcp, connection: :keepalive, pid: #PID<0.337.0>, method: "GET", version: :"HTTP/1.1", peer: {{192, 168, 99, 1}, 60459}, host: "192.168.99.100", host_info: :undefined, port: 4000, path: "/socket/websocket", path_info: :undefined, qs: "auth_token=TEST_TOKEN", qs_vals: :undefined, bindings: [], headers: [{"connection", "Upgrade"}, {"upgrade", "websocket"}, {"host", "192.168.99.100:4000"}, {"sec-websocket-version", "13"}, {"sec-websocket-key", "MTMtMTQ2MTE4OTEzMDY1MA=="}, {"sec-websocket-extensions", "permessage-deflate; client_max_window_bits"}], p_headers: [{"connection", ["upgrade"]}], cookies: :undefined, meta: [], body_state: :waiting, buffer: "", multipart: :undefined, resp_compress: false, resp_state: :waiting, resp_headers: [], resp_body: "", onresponse: :undefined], opts: {Phoenix.Transports.WebSocket, {ChatServer.Endpoint, ChatServer.UserSocket, :websocket}}]

== Reproduction steps ==

1.) Create a simple phoenix web socket app
2.) Add a parameter to the connect method match
3.) use: wscat -c "ws://yourip:port/socket/websocket

do not pass the correct param. No match is found, error is raised.

**Comment by josevalim** [comment]
Yes, this should be fixed on latest Phoenix. :) See #1440. Thank you!
