### ISSUE TITLE
Run Phoenix on Vagrant

### ISSUE THREAD

**Issue by wende** [phoenixframework/phoenix#1662]
### Environment

* Elixir version (elixir -v): 1.2.0
* Phoenix version (mix deps): 1.1.4
* NodeJS version (node -v): 5.6.0
* NPM version (npm -v): 3.6.0
* Operating system: Any UNIX system with Vagrant.

When running phoenix on Vagrant machine, and modifying files in web/static/ files the watcher triggers fire, and recompile the assets.
However the files served after the trigger differ from what they really are.
They are served with corrupted content of `X` null characters at the end, where `X` apparently is a number of modified characters in file.

For instance
```javascript
// web/static/js/script.js
console.log("hello world")
```
And we want to change it to
```javascript
// web/static/js/script.js
console.log("hello world")
1 + 1
```
Once we save it, Phoenix recompiles the file and serves it as
```javascript
// web/static/js/script.js
console.log("hello world")
\0\0\0\0\0
```

I don't know if it's the right repository to put issue on, but since the error is not caused by `inotify`, and also not by `bruch` then I decided to post it here to see if someone more competent will be able to help me.

As a side note we and our team love Elixir and Phoenix, and we'd love to be able to make universal development environment with Vagrant for our team. Our startup is doing great and it couldn't be without you and your hard work.
Sincere kudos from the whole development team!

**Comment by chrismccord** [comment]
If you search the phoenix-talk and elixir-lang mailing lists you'll find similar repots, and it is traced to the differences between mtimes from the host volume and the VM. The only solution for now unfortunately is to edit the files on the same volume as the VM is being hosted from. I don't think there's anything for us to address on the Phoenix end and I'm not aware of a potential fix as of now. Hope that helps!

**Comment by wende** [comment]
Unfortunately tested 
`echo anything >> assets/js/custom.js`
on both host and guest machine, the result is the same.
That's unlucky. With so many things to configure, we'd really make a use of some way of one-command configuration of the whole dev environment.

Do you know any other ways than installing all of it manually?
Thank you in advance

**Comment by rudolfb** [comment]
Hi Krzysztof,

Download and install an Ubuntu Xenial into VMWare or a VirtualBox:

  http://releases.ubuntu.com/16.04/

Here you will find a script …

  https://github.com/rudolfb/ubuntu-xenial-elixir-install-shell-script

that installs


  *     Dependencies
  *     Git – also configures your git global settings
  *     Spacemacs / Emacs including alchemist and a .spacemacs file that seems to work for me
  *     Node 5.x
  *     Postgres and pgadmin (un: postgres, pw: postgres)
  *     Elixir incl. Erlang
  *     Phoenix
  *     Elm
  *     Atom

At the end of the script all of the version numbers of all the installed software is displayed.

Add the runnable permission to the text file.

Open the script, and search for GIT_USER_EMAIL and GIT_USER_NAME and enter your detail, then save the file.

Run the script as a normal user:

  ./install.sh 2>&1 | tee install.log

You will be prompted to enter your superuser password. After entering the password the rest of the script installs everything automatically. The log is displayed to screen and in parallel is written to file.

It got boring having to do this all the time, and Vagrant just did not want to work the way I wanted it to. Having to start rsync-auto manually every time I wanted to use the Vagrant machine to sync between the Vagrant and the host was not my idea of an easy working setup.

Please take the above with a pinch of salt. Beginner …. Any tips welcome.

Regards

Rudolf Bargholz
