### ISSUE TITLE
How do you rename the routes path?

### ISSUE THREAD

**Issue by Gacnt** [phoenixframework/phoenix#1664]
I have
```
  scope "/", BdoPug do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :index
    
    resources "/auth", UserController, only: [:create, :new]
    
  end
```

Which I can access by going to

`/auth/new` and `/auth/create`

I'd like to rename these to

`/auth/register` and `/auth/login`

Is this possible? e.g.

`resources "/auth", UserController, only: [:create, :new], ["register", "login"]`

Or maybe

`resources "/auth", UserController, only: [create: "register", new: "login"]`

**Comment by chrismccord** [comment]
You can use

```elixir
  scope "/", BdoPug do
    pipe_through :browser # Use the default browser stack

    get "/", HomeController, :index

    get "/auth/register", UserController, :new
    get "/auth/login", UserController, :post
  end
```

In the future please follow the issue template guidelines and send questions to irc, slack, the phoenix-talk mailing list, or the phoenix-forum on elixirforum.com
