### ISSUE TITLE
Performance related issue in Phoenix

### ISSUE THREAD

**Issue by antonyr** [phoenixframework/phoenix#1668]
Here is the problem description.
I tried to benchmark Phoenix against Puma with JRuby fairly similar code. I tried to apache bench to benchmark this application and I tried to hit it from within another aws box.
In aws server, I made the concurrency to 2, it worked neatly and certainly performed twice better than JRuby. However when I increased the concurrency to 4, that is when a problem started showing up. The reason was some requests took a lot of time, essentially request was timing out. Then I increased the timeout to 100seconds. Then with concurrency 4 for 1000 worked well, I could notice that some request took really long time. Although it broke randomly sometimes with concurrency 4, rerunning it was fine sometimes. Then I increased the concurrency to 6 for 1000 requests, then it started breaking randomly and all the time.

However testing with JRuby didn't give a problem at all even once, increasing the concurrency to 16, it 
didn't flinch even once.
You may create a .env file in the project location and declare the following, for the api
API_SERVER=54.203.87.182:8080

### Environment

* Elixir version (elixir -v): 1.2.2
* Phoenix version (mix deps): 1.1.4
* NodeJS version (node -v):  N/A
* NPM version (npm -v): N/A
* Operating system: Ubuntu 14.04.2 in aws

Please let me know if you have further clarifications.

**Comment by jeregrine** [comment]
@antonyr with theses like this we'll need to see the code as well as any parameters you used to run it.

**Comment by chrismccord** [comment]
Please use another tool such as `wrk` to benchmark as `ab` has been known to produce bad results against erlang web servers. i.e., check the CPU usage on the app when running against ab and you'll find your cores are probably < 30% utilized. Also, we haven't had any information about the kinds of applications you are comparing, what middlewares are enabled etc. Please remeasure and report back with more information if you continue to see less ideal numbers, ideally with an example application of the kind of app you are using.

**Comment by aamirtharaj-rpx** [comment]
@chrismccord @jeregrine 
I forgot to attach the code for this thing. You can find it here
https://github.com/antonyr/phoenix_benchmark

**Comment by aamirtharaj-rpx** [comment]
I will also use wrk and share the results with you guys. Thanks in advance for taking time and reviewing it.

**Comment by chrismccord** [comment]
Ah that is much more helpful :) A first few obvious things to do

1) remove any plugs in your endpoint that are not applicable to these runs, i.e. Plug.Static, Plug.Session (assuming the other app isn't doing session stuff)
https://github.com/antonyr/phoenix_benchmark/blob/master/lib/phoenix_benchmark/endpoint.ex#L2-L36

2) Logging can be expensive and I don't know what kind of logs the other app is doing or not doing. If you aren't logging in the jruby app, set your log level to `:error` in `config/prod.exs`: i.e.:

    config :logger, level: :error

3) Make sure you are benchmarking with `MIX_ENV=prod`.
4) Let us know your CPU utilization during the runs

**Comment by chrismccord** [comment]
And the glaring issue now that I just saw the benchmark controller; your controller is doing http requests, so  you are very very likely maxing your HTTPotion pool:
https://github.com/antonyr/phoenix_benchmark/blob/master/web/controllers/benchmark_controller.ex#L34

You need to increase the underlying http client pool in order to get real results

**Comment by aamirtharaj-rpx** [comment]
Thanks for the note. I'll fix the pool size, test it and get back.
I would not want to remove plugs like session, static etc as this won't stay on par with JRuby server as that use all the default middlewares.

**Comment by antonyr** [comment]
@chrismccord after making that change, I ran the test at concurrency 6, It broke again with the similar exception
I'll test it against `wrk` and let you know the results.
``
07:54:46.528 [error] #PID<0.322.0> running PhoenixBenchmark.Endpoint terminated
Server: localhost:4040 (http)
Request: GET /api/benchmarks
** (exit) an exception was raised:
    ** (BadMapError) expected a map, got: nil
        (stdlib) :maps.find("thai restaurant mountain view", nil)
        (elixir) lib/map.ex:131: Map.get/3
        (phoenix_benchmark) web/controllers/benchmark_controller.ex:44: PhoenixBenchmark.BenchmarkController.sync_c$ll_parser/1
        (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
        (phoenix_benchmark) web/controllers/benchmark_controller.ex:18: PhoenixBenchmark.BenchmarkController.index/$
        (phoenix_benchmark) web/controllers/benchmark_controller.ex:3: PhoenixBenchmark.BenchmarkController.action/$
        (phoenix_benchmark) web/controllers/benchmark_controller.ex:3: PhoenixBenchmark.BenchmarkController.phoenix$controller_pipeline/2
        (phoenix_benchmark) lib/phoenix/router.ex:261: PhoenixBenchmark.Router.dispatch/2
``

**Comment by antonyr** [comment]
@jeregrine @chrismccord 
Please check the code once to see if I set the http client pool right

**Comment by josevalim** [comment]
@antonyr your code is crashing. For example, here:

https://github.com/antonyr/phoenix_benchmark/blob/master/web/controllers/benchmark_controller.ex#L42

It seems distanceBySuggestion is returning nil, causing the request to fail.

**Comment by antonyr** [comment]
@josevalim 
It is returning so only under very high load. If I make concurrency 1, things go fine very well.

**Comment by josevalim** [comment]
Can you please paste the command you are running to benchmark the server?

**Comment by aamirtharaj-rpx** [comment]
sure @josevalim. Here it is 
`wrk -t4 -c600 http://54.203.87.182:4444/api/benchmarks`

**Comment by chrismccord** [comment]
I don't see any changes to the code that configured ibrowse pool options (what HTTPotion uses). I'm also not sure which options you'll need to set. You can try to use the HTTPoison library instead which allows you to pass hackney pool options down https://github.com/edgurgel/httpoison/issues/73#issuecomment-145318591

Please give that a shot. As this sits, the perf results are unrelated to Phoenix.

**Comment by antonyr** [comment]
Thanks for your suggestion @chrismccord 

This is the line I was previously referring to.
https://github.com/antonyr/phoenix_benchmark/blob/master/web/controllers/benchmark_controller.ex#L7
Now, I was able to push up the pool size and I could execute the following command successfully and changed the http client to httpoison
`ab -n1000 -c16 http://54.203.87.182:4444/api/benchmarks`

However the following command is still breaking with timeout
`wrk -t4 -c600 http://54.203.87.182:4444/api/benchmarks`
with the following exception
``
** (exit) an exception was raised:
    ** (HTTPoison.Error) :timeout
        (phoenix_benchmark) web/models/search_inside.ex:2: SearchInside.request!/5
        (phoenix_benchmark) web/controllers/benchmark_controller.ex:28: PhoenixBenchmark.BenchmarkController.search_inside/0
        (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
``
If you want to look at a code, please follow this link
https://github.com/antonyr/phoenix_benchmark/blob/poison/web/controllers/benchmark_controller.ex#L9
Please note that this is in a new branch called `poison`
I am not sure how `wrk` works.
Do you think you can shed some light on this?

**Comment by chrismccord** [comment]
You are still maxing your httpoison pool, but it's quite large at 10k connections, so it appears you are rather at the mercy for the external service you are hitting. at c600 you are hitting your local app which then slams the remote service with http requests. If those responses start taking a while, then your http pool is going to start timing out. I don't think benchmarking this way is going to yield great results because you are ultimately benchmarking that external service, not the app.

**Comment by chrismccord** [comment]
You are also calling start_pool within your controller, which means you'll be calling that for every single request that hits the app. Instead you should start the pool with your app startup. Since we haven't identified this as a phoenix issue, please refer to the mailing list or hop on elixir-lang irc and I'd be happy to chat more. Thanks!

**Comment by antonyr** [comment]
@chrismccord  @josevalim  I appreciate you guys for the support.
