### ISSUE TITLE
Extract embedded normalize.css to phoenix.css and leave app.css for app specific styles

### ISSUE THREAD

**Issue by miguelcoba** [phoenixframework/phoenix#1669]
# Issue description
I want to open an issue to extract the normalize.css embedded in app.css to a new phoenix.css file and use the app.css for app specific styles. 
Reasons for this:

- the embedded normalize.css line is a very long (122375 chars to be precise) and that causes slowness in editors when rendering or scrolling
- it is difficult to read what that line contains as it is minified
- the normalize.css is a good set of defaults for all phoenix apps and will be seldom or never modified (as it's better to override its values)
- the new app.css will be shorter, and will have only the styles the developer cares

### Expected behavior
Separate CSS defaults applicable for most phoenix apps from app specific styles.
Avoid rendering issues in text editor when opening app.css caused by embedded normalize.css in app.css

### Actual behavior
Currently the rendering of the normalize.css line in app.css causes some editors to render/scroll slowly
Mixed concerns in app.css that bundles together css resetting values with app specific values

**Comment by miguelcoba** [comment]
Well, I wrote too fast. Checking the old discussions I found:
"The stock css will remain as is until we have good reason to change it" in this pull request that already does what I was asking for: https://github.com/phoenixframework/phoenix/pull/831

@chrismccord Any new thoughts on this issue?

**Comment by miguelcoba** [comment]
OMG! Thank you very much!

**Comment by RichMorin** [comment]
I think it's time to revisit this issue. Specifically, I'd like the very long (`normalize.css` ?) line to be removed from `phoenix.css` into a separate file and also distributed in non-minified and commented form. This would make it _much_ easier to examine, for folks who want to learn from the distributed CSS setup, override parts of it, etc.

**Comment by chrismccord** [comment]
You are free to remove the minified normalize.css line and add your own normalize.css file, but it's not something we'll distribute separately
