### ISSUE TITLE
Different host for websocket connections

### ISSUE THREAD

**Issue by princemaple** [phoenixframework/phoenix#1672]
Hi,

This is not a bug report. Just a sanity check.

Today, I discovered that cloudflare doesn't really support websockets. (it does, as a beta feature, for business and enterprise plans). The workaround for this is to set up a different domain/subdomain that doesn't go through cloudflare servers.

However, [this line](https://github.com/phoenixframework/phoenix/blob/master/web/static/js/phoenix.js#L488) suggests that phoenix.js does not take options for using a different host.

Just wondering, if there is any danger / inconvenience to do so? If there isn't anything that's terribly concerning, I'd happily contribute to make this an option available so that the users of phoenix.js can opt to use a different host.

Thanks.

**Comment by chrismccord** [comment]
> This is not a bug report. Just a sanity check.

Mailing list and irc is a great place for those questions! :)
