### ISSUE TITLE
v8::ObjectTemplate::Set() with non-primitive values is deprecated

### ISSUE THREAD

**Issue by chansuke** [phoenixframework/phoenix#1675]
### Environment

* Elixir version (elixir -v): 1.2.4
* Phoenix version (mix deps): 1.1.4
* NodeJS version (node -v):  v6.0.0
* NPM version (npm -v):  3.8.6
* Operating system: El Capitan

### V8 error
I upgraded nodejs to v6 and shows JS and C stack trace when I run `mix phoenix.server`.
It says `v8::ObjectTemplate::Set() with non-primitive values is depracated` and some issues are already opened in various projects.e.g:https://github.com/nodejs/node/pull/6228

How can I handle with this error?Just wait for next release of node or temporarily downgrade the node version?

**Comment by chrismccord** [comment]
> How can I handle with this error?Just wait for next release of node or temporarily downgrade the node version?

As this is not on our side, you'll need to address the issues on the node/brunch/whatever side that is throwing the error on node v6. For now, node v5 is your best workaround. Thanks!
