### ISSUE TITLE
Phoenix.Controller.put_secure_browser_headers not implemented per documentation

### ISSUE THREAD

**Issue by dotdotdotpaul** [phoenixframework/phoenix#1676]
Minor issue/question:  The documentation for put_secure_browser_headers says "Custom headers may also be given", but the implementation doesn't actually use the _opts argument for anything.

[Link to line in lib/phoenix/controller.ex](https://github.com/phoenixframework/phoenix/blob/v1.1.4/lib/phoenix/controller.ex#L778)

Not sure what the expected behavior is -- is this an issue of "unfinished function" or an issue of "outdated documentation"?

**Comment by chrismccord** [comment]
Fixed. Thanks!
