### ISSUE TITLE
Docs for Mix.Tasks.Phoenix.New

### ISSUE THREAD

**Issue by jlevycpa** [phoenixframework/phoenix#1678]
Hi All,

Thanks for all of the great work on the framework! I just wanted to mention that it doesn't look like the docs for Mix.Tasks.Phoenix.New are getting built and included on Hexdocs.pm. 

Maybe this is located somewhere else because it's part of the installer?

**Comment by ericmj** [comment]
I believe you are supposed to get the docs `mix help phoenix.new`. ex_doc is similar, no docs on hexdocs but you can find them with `mix help docs`.

**Comment by jlevycpa** [comment]
Hmm, but doesn't it seem strange that the docs for all of the other Phoenix mix tasks are on hexdocs except for phoenix.new?

**Comment by ericmj** [comment]
Possibly. Keep in mind that the installer is a separate mix application so it wouldn't be documented on https://hexdocs.pm/phoenix. There is not even a hex package for phoenix_new so it can't be published to hexdocs.

**Comment by chrismccord** [comment]
Hey @jlevycpa thanks for the suggestion but as eric said, it's a separate application that we package as an achieve and is not published to hex. We do have helpful docs wth `mix help phoenix.new`

```
mix help phoenix.new

                                mix phoenix.new

Creates a new Phoenix project.

It expects the path of the project as argument.

┃ mix phoenix.new PATH [--module MODULE] [--app APP]

A project at the given PATH will be created. The application name and module
name will be retrieved from the path, unless --module or --app is given.

Options

  • --app - the name of the OTP application
  • --module - the name of the base module in the generated skeleton
  • --database - specify the database adapter for ecto. Values can be
    postgres, mysql, mssql, sqlite or mongodb. Defaults to postgres
  • --no-brunch - do not generate brunch files for static asset building.
    When choosing this option, you will need to manually handle JavaScript
    dependencies if building HTML apps
  • --no-ecto - do not generate ecto files for the model layer
  • --no-html - do not generate HTML views.
  • --binary-id - use binary_id as primary key type in ecto models

Examples

┃ mix phoenix.new hello_world

Is equivalent to:

┃ mix phoenix.new hello_world --module HelloWorld

Without brunch:

┃ mix phoenix.new ~/Workspace/hello_world --no-brunch

```

**Comment by jlevycpa** [comment]
Thanks, guys. I appreciate the explanation.
