### ISSUE TITLE
Plug init regression

### ISSUE THREAD

**Issue by benwilson512** [phoenixframework/phoenix#1686]
### Environment

* Elixir version (elixir -v): 1.3-dev, also confirmed on 1.2.4
* Phoenix version (mix deps): 1.2.0-rc.0
* Operating system: OS X

### Expected behavior

A super basic plug
```elixir
defmodule PlugInitTest.TestPlug do

  def init(_), do: %{foo: :bar}
  def call(conn, _), do: conn
end
```

In a super basic router:
```
defmodule PlugInitTest.Router do
  use Phoenix.Router

  forward "/", PlugInitTest.TestPlug
end
```

Should not blow up (and doesn't in 1.1).

### Actual behavior

```
== Compilation error on file lib/router.ex ==
** (CompileError) lib/router.ex: invalid quoted expression: %{foo: :bar}
    (elixir) expanding macro: Kernel.|>/2
    lib/router.ex:1: PlugInitTest.Router.match_route/4
    /Users/ben/projects/plug_init_test/lib/router.ex:1: Phoenix.Router.__before_compile__/1
```

There's a missing `Macro.escape` somewhere...

**Comment by Gazler** [comment]
https://github.com/phoenixframework/phoenix/commit/a1a68a2e414b52fdf756017a8909e90cc611f2a3 is the culprit
