### ISSUE TITLE
get remote_ip from socket

### ISSUE THREAD

**Issue by mateuszkitlas** [phoenixframework/phoenix#1688]
### Expected behavior
get remote_ip from socket in Channel

### Actual behavior
 I can get it from conn in View, but not in Channel.

http://stackoverflow.com/questions/33276202/how-to-get-remote-ip-from-socket-in-phoenix-framework

**Comment by chrismccord** [comment]
Please search the mailing lists for discussions around this. Closing since this is not an issue.
