### ISSUE TITLE
Add Notifier layer to send mail

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#169]
This could be an optional dep or we could just include it. It would be nice to implement as a behavior and support multiple backends. Initial support could use:
https://github.com/Vagabond/gen_smtp

**Comment by erickhsiao** [comment]
It may out of topic, but wondering anyone interesting about adding <a href='http://sendy.co' target='_blank'>sendy</a> into this layer

**Comment by chrismccord** [comment]
Whatever we end up providing will be adapter based, so sendy support would be possible with a third-party package. We've got some other areas to finish up before this though.

**Comment by kamilc** [comment]
My few cents is that my mailman library (https://github.com/kamilc/mailman) has been updated not too long ago. I have integration with the Mix.Config soon too to make it easier to integrate the library wherever one pleases.

**Comment by kamilc** [comment]
Oh and mailman **is** adapter based

**Comment by scrogson** [comment]
Going to start feeling this out.

**Comment by stevedomin** [comment]
Was just looking at this as well @scrogson, would be really happy to help out if you need.

**Comment by josevalim** [comment]
Oh, awesome. I think we can close this though, we have decided to not make it part of 1.0 so we do recommend folks to explore different solutions and we can make an informed decisions later on! @chrismccord ?

**Comment by chrismccord** [comment]
Yes, we are punting on this for later. @scrogson please feel free to explore and we can see what comes for it once 1.0 is out. We should at minimum have a guide outlining some examples with existing libs.
