### ISSUE TITLE
Generating json model fails

### ISSUE THREAD

**Issue by walkr** [phoenixframework/phoenix#1691]
In a newly created Phoenix App I'm trying to generate a json model but it fails:

```shell
$  mix phoenix.gen.json User users name:string
```

** (RuntimeError) could not find controller.ex in any of the sources
    lib/mix/phoenix.ex:24: anonymous fn/5 in Mix.Phoenix.copy_from/5
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/phoenix.ex:19: Mix.Phoenix.copy_from/5
    lib/mix/tasks/phoenix.gen.json.ex:52: Mix.Tasks.Phoenix.Gen.Json.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
### Environment

* Elixir version (elixir -v): 1.2.4

* Phoenix version (mix deps):
* connection 1.0.2 (Hex package) (mix) locked at 1.0.2 (connection) ok
* fs 0.9.1 (Hex package) (rebar)
  locked at 0.9.2 (fs)
  ok
* gettext 0.11.0 (Hex package) (mix)
  locked at 0.11.0 (gettext)
  ok
* ranch 1.2.1 (Hex package) (rebar)
  locked at 1.2.1 (ranch)
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy)
  ok
* decimal 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (decimal)
  ok
* poison 2.1.0 (Hex package) (mix)
  locked at 2.1.0 (poison)
  ok
* db_connection 0.2.5 (Hex package) (mix)
  locked at 0.2.5 (db_connection)
  ok
* phoenix_pubsub 1.0.0-rc.0 (Hex package) (mix)
  locked at 1.0.0-rc.0 (phoenix_pubsub)
  ok
* cowlib 1.0.2 (Hex package) (rebar)
  locked at 1.0.2 (cowlib)
  ok
* cowboy 1.0.4 (Hex package) (rebar)
  locked at 1.0.4 (cowboy)
  ok
* plug 1.1.4 (Hex package) (mix)
  locked at 1.1.4 (plug)
  ok
* phoenix_html 2.5.1 (Hex package) (mix)
  locked at 2.5.1 (phoenix_html)
  ok
* phoenix 1.2.0-rc.0 (Hex package) (mix)
  locked at 1.2.0-rc.0 (phoenix)
  ok
* phoenix_live_reload 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (phoenix_live_reload)
  ok
* postgrex 0.11.1 (Hex package) (mix)
  locked at 0.11.1 (postgrex)
  ok
* ecto 2.0.0-rc.4 (Hex package) (mix)
  locked at 2.0.0-rc.4 (ecto)
  ok
* phoenix_ecto 3.0.0-rc.0 (Hex package) (mix)
  locked at 3.0.0-rc.0 (phoenix_ecto)
  ok

* Operating system: OS X

### Expected behavior

Model should be generated

### Actual behavior

```shell
$  mix phoenix.gen.json User users name:string
```

** (RuntimeError) could not find controller.ex in any of the sources
    lib/mix/phoenix.ex:24: anonymous fn/5 in Mix.Phoenix.copy_from/5
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/phoenix.ex:19: Mix.Phoenix.copy_from/5
    lib/mix/tasks/phoenix.gen.json.ex:52: Mix.Tasks.Phoenix.Gen.Json.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

**Comment by starbelly** [comment]
Hi, @walkr I was unable to reproduce this with a fresh project. Tried the following : 

    mix phoenix.gen.json HappyFoo foos bar:string
    * creating web/controllers/happy_foo_controller.ex
    * creating web/views/happy_foo_view.ex
    * creating test/controllers/happy_foo_controller_test.exs
    * creating web/models/happy_foo.ex
    * creating test/models/happy_foo_test.exs
    * creating priv/repo/migrations/20160506030244_create_happy_foo.exs

mix.exs:

* connection 1.0.2 (Hex package) (mix)
* fs 0.9.1 (Hex package) (rebar)
* gettext 0.11.0 (Hex package) (mix)
* ranch 1.2.1 (Hex package) (rebar)
* poolboy 1.5.1 (Hex package) (rebar)
* decimal 1.1.2 (Hex package) (mix)
* poison 2.1.0 (Hex package) (mix)
* db_connection 0.2.5 (Hex package) (mix)
* phoenix_pubsub 1.0.0-rc.0 (Hex package) (mix)
* cowlib 1.0.2 (Hex package) (rebar)
* cowboy 1.0.4 (Hex package) (r
* plug 1.1.4 (Hex package) (mix)
* phoenix_html 2.5.1 (Hex package) (mix
* phoenix 1.2.0-rc.0 (Hex package) (mix)
* phoenix_live_reload 1.0.5 (Hex package) (mix)
* postgrex 0.11.1 (Hex package) (mix)
* ecto 2.0.0-rc.4 (Hex package) (mix)
* phoenix_ecto 3.0.0-rc.0 (Hex package) (mix)

**Comment by walkr** [comment]
I still get the same error. 
What version of `phoenix_new` are you using?

```shell
$ ls ~/.mix/archives/

hex-0.11.5.ez             phoenix-1.2.0-rc.0.ez     phoenix_new-1.2.0-rc.0.ez
```

**Comment by starbelly** [comment]
$ head ~/.mix/archives/phoenix_new.ez  | grep -a vsn
              {vsn,"1.2.0-rc.0"},

**Comment by chrismccord** [comment]
I am also unable to recreate this. Can you please jump on the latest Phoenix archive and try to recreate on a fresh project?

    mix archive.install https://github.com/phoenixframework/archives/raw/master/1.2-rc/phoenix_new.ez

I don't believe this is an issue on our end. If you still get the errors after the new archive and new project, please make the project available for me to take a look. Thanks!

**Comment by walkr** [comment]
I just ended up uninstalling/reinstalling Elixir and phoenix_new and now it works.

**Comment by starbelly** [comment]
> I just ended up uninstalling/reinstalling Elixir and phoenix_new – because I just couldn't figure it out – and now it works. 

 Software  ; )
