### ISSUE TITLE
New project UserSocket and docs should use singular topic convention

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1696]
Up for grabs. Easy starter for someone so chime in to claim it :)

**Comment by chrismccord** [comment]
ie,` "rooms:*"` => `"room:*"`

**Comment by riacataquian** [comment]
Can I grab this one @chrismccord? :)

**Comment by chrismccord** [comment]
It's all yours! Thanks!

**Comment by riacataquian** [comment]
@chrismccord Are we going to remove the required topic name when generating new channels?

**Comment by chrismccord** [comment]
Yes. It can be optional now and default to the snake-cased module name. You can use `Phoenix.Naming.underscore`

**Comment by chrismccord** [comment]
@riacataquian Bah, it looks like we already tackled this in https://github.com/phoenixframework/phoenix/commit/1bbda32a57310539c9ba8c3c88045276a37fac2c

Sorry to send you down the wrong path! The next starter issue I'll try to ping and it's yours. Thanks for the willingness to help! :)

**Comment by scrogson** [comment]
Yeah, I tackled that a few weeks ago ;)

**Comment by riacataquian** [comment]
Sure @chrismccord! :) But it seems to me that the docs are not yet fixed? Perhaps I can do that. Example here: https://github.com/phoenixframework/phoenix/blob/c47a5b160382ff179a94fe88e080d2833b7d627e/lib/phoenix/channel.ex

**Comment by chrismccord** [comment]
@riacataquian you are right. Please go ahead! We also want to make sure the generated UserSocket module uses "room:*"

**Comment by riacataquian** [comment]
Ok on it, @chrismccord. 👍

**Comment by scrogson** [comment]
Thank you @riacataquian! ❤️ 💛 💚

**Comment by riacataquian** [comment]
My pleasure! 👍
