### ISSUE TITLE
Make it possible to choose the origin of the test/type of spec with generators

### ISSUE THREAD

**Issue by pragmaticivan** [phoenixframework/phoenix#1698]
The current implementation is using:

```
    files = [
      {:eex, "model.ex",       "web/models/#{path}.ex"},
      {:eex, "model_test.exs", "test/models/#{path}_test.exs"},
    ] ++ migration(opts[:migration], path)

    Mix.Phoenix.copy_from paths(), "priv/templates/phoenix.gen.model", "", binding, files
```

Since ExUnit is not the only tool for testing with the elixir, things such as `https://github.com/antonmi/espec_phoenix` would need to reuse the generator features from phoenix. 
Not sure if that requires code implementation of if the package in question would need to "overwrite" the current generators for that.

Maybe project attributes such as `test_stack: [tool: Espec],` would solve the problem to identify which package should generate the test files.

**Comment by josevalim** [comment]
I think we should hold on on anything like this for now because we have plans for changing how Phoenix generators work. Therefore, anything we add now will definitely be short-lived.

**Comment by chrismccord** [comment]
Thanks! But I am unlikely to support other testing stacks. As José said, we are in flux for plans after 1.2 is out, so closing for now.
