### ISSUE TITLE
Investigate performance regression when running inside releases

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1702]

**Comment by chrismccord** [comment]
This doesn't have to be top priority, but we should look into recreating he various reports we've seen. @Gazler if you're not able to own this one, feel free to punt on it and we'll loop back around later once other areas settle.

**Comment by Gazler** [comment]
I'll look at creating an app that we can use for this reliably, as well as documenting configuration so that we can actually reproduce the tests!

**Comment by tisba** [comment]
I briefly talked with @Gazler at the end of ElixirConf in Berlin. I have some experience in setting up large scale load tests using tsung and and I'm happy to help wherever I can.

**Comment by noma4i** [comment]
Phoenix real world deploy is focused on running phoenix app in production inside release. This issue should be reviewed.

**Comment by chrismccord** [comment]
It's on our list to investigate, but not a priority for us compared to the backlog. Many folks are happily running Phoenix inside a release in production.

**Comment by josevalim** [comment]
> It's on our list to investigate, but not a priority for us compared to the
> backlog. Many folks are happily running Phoenix inside a release in
> production.
>
Precisely. As far as we know, it it's happening only on some situations. So
if someone believes they are running into it, please report here why they
think it is the case and give more information so we can provide help.

>

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
We've had no movement on this for months, so I'm closing. If folks do run into performance regressions inside a release compared to outside, we've love info to help track down the potential causes.
