### ISSUE TITLE
Better Error messages (with suggestions) than 'module Hello.Web is not loaded and could not be found'

### ISSUE THREAD

**Issue by yepesasecas** [phoenixframework/phoenix#1703]
Hi, 
I'm new to Phoenix and Elixir. I just got my `Programing Phoenix` book.

In First chapter says 'create a Hello project'. But i changed the name to "phoenix_hello". 

So when i got to the Controller part I wrote: 
```
defmodule PhoenixHello.HelloController do
  use Hello.Web, :controller

  def world(conn, _params) do
    render conn, "world.html"
  end
end
```
and I got the error you see below. but, that error doesn't say anything. it took me several minutes to see the issue. :P 

I may not be the first one to have this issue. and the error message is not so helpful. they can **suggest developer what are you doing wrong. Like some RoR Error messages**

**Did you mean use 'PhoenixHello.Web, :controller' ?**

### Environment
Elixir 1.2.5

* connection 1.0.2 (Hex package) (mix)
* fs 0.9.1 (Hex package) (rebar)
* gettext 0.11.0 (Hex package) (mix)
* ranch 1.2.1 (Hex package) (rebar)
* poolboy 1.5.1 (Hex package) (rebar)
* decimal 1.1.2 (Hex package) (mix)
* poison 1.5.2 (Hex package) (mix)
* db_connection 0.2.5 (Hex package) (mix)
* cowlib 1.0.2 (Hex package) (rebar)
* cowboy 1.0.4 (Hex package) (rebar)
* plug 1.1.4 (Hex package) (mix)
* phoenix_html 2.5.1 (Hex package) (mix)
* phoenix 1.1.4 (Hex package) (mix)
* phoenix_live_reload 1.0.5 (Hex package) (mix)
* postgrex 0.11.1 (Hex package) (mix)
* ecto 1.1.6 (Hex package) (mix)
* phoenix_ecto 2.0.1 (Hex package) (mix)
* NodeJS version (node -v):

NPM 3.6.0

Mac OS X El Capitan v10.11.4

### Expected behavior
```
== Compilation error on file web/controllers/hello_controller.ex ==
**Did you mean 'use PhoenixHello.Web, :controller' ?
** (CompileError) web/controllers/hello_controller.ex:2: module Hello.Web is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    web/controllers/hello_controller.ex:2: PhoenixHello.HelloController (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

### Actual behavior
```
== Compilation error on file web/controllers/hello_controller.ex ==
** (CompileError) web/controllers/hello_controller.ex:2: module Hello.Web is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    web/controllers/hello_controller.ex:2: PhoenixHello.HelloController (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

**Comment by sashaafm** [comment]
I suggested this in Elixir Core two weeks ago with a solution and PR. From what José Valim said this is not actually possible since there is no way to determine which modules are available for sure (I believe this has something to do with actual modules in the source code vs what modules are loaded at a given time but don't quote me on that).

**Comment by chrismccord** [comment]
> I'm new to Phoenix and Elixir. I just got my Programing Phoenix book.

Awesome! Welcome! As @sashaafm said, we strive for good error messages, but we unfortunately can't improve this one. Also see this comment on a similar issue recently to get a better understanding. Elixir-lang irc and slack are great places for help when you're ramping up with issues like this. Hope that helps!

https://github.com/phoenixframework/phoenix/issues/1665#issuecomment-213403177

**Comment by yepesasecas** [comment]
thank you @sashaafm @chrismccord :)

**Comment by rezarose** [comment]
Hi @yepesasecas ,
I also new to Phoenix and Elixir. Do you got any workaround as error solution.
Thanks.
