### ISSUE TITLE
mix phoenix.routes Failing for Application Created with a Custom Base Module 

### ISSUE THREAD

**Issue by jrstewart** [phoenixframework/phoenix#1706]
Running `mix phoenix.routes` on a new Phoenix 1.2.0-rc.0 application generated using the --module flag is throwing an error.

This is also occurring in an application that I moved from 1.1.4 to 1.2.0-rc.0 that uses a custom base module.
 
### Environment

* Elixir version (elixir -v): 1.2.5
* Phoenix version (mix deps): 1.2.0-rc.0
* NodeJS version (node -v): 6.1.0
* NPM version (npm -v): 3.8.6
* Operating system: Mac OS X El Capitan

### Expected behavior

This should produce a list of the application routes:
```
mix phoenix.new test_app --module Test.App
mix phoenix.routes
```

### Actual behavior

```
mix phoenix.new test_app --module Test.App
mix phoenix.routes
** (UndefinedFunctionError) undefined function TestApp.Router.__routes__/0 (module TestApp.Router is not available)
    TestApp.Router.__routes__()
    (phoenix) Phoenix.Router.ConsoleFormatter.format/1
    (phoenix) lib/mix/tasks/phoenix.routes.ex:30: Mix.Tasks.Phoenix.Routes.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by chrismccord** [comment]
The `phoenix.routes` task assumes `Test.Router` by default, but allows you to pass an explicit module. In your case, you must pass the router module, i.e. `mix phoenix.routes Test.App.Router` as there is no way for us to know which module you want. Thanks!

**Comment by josevalim** [comment]
You can also do `config :my_app, namespace: Test.App` so Phoenix knows where to lookup the default value. Such is documented in `mix help phoenix.routes`.

**Comment by jrstewart** [comment]
Thank you for the help. I did notice the configuration option in mix `mix help phoenix.routes` documentation. My confusion came from the documentation showing the following example:

```
config :my_app,
  app_namespace: My.App
```

Using namespace instead of app_namespace resolved the issue for me. Thanks.

**Comment by scrogson** [comment]
This has been fixed on master.
