### ISSUE TITLE
Publish Phoenix.js to npm

### ISSUE THREAD

**Issue by nicholaswyoung** [phoenixframework/phoenix#1707]
I now have control of the `phoenix` [module name on npm.](https://groups.google.com/forum/#!topic/phoenix-core/yaK6t0eoqYU)

@chrismccord @josevalim, etc core team members: drop your npm usernames here so I can add them to the registry.

**Comment by aphillipo** [comment]
How do people feel about solving this problem for all packages - i.e. quickly knocking up something with a github login that can take paths of JS tagged in a repo/release and automatically mirror these changes to npm.  This could work for any packages and you could specify all the metadata in the UI.  Just seems better than relying on whoever it is to remember, creating a bug every time  someone forgets etc.  My time is limited right now but I'll try to find time if people like the idea; I'd rather people stole the idea though :-D

**Comment by josevalim** [comment]
That's awesome @nicholaswyoung, thank you! I am @josevalim on npm as well.

**Comment by nicholaswyoung** [comment]
@josevalim 👍  

Do we want to publish with Phoenix.js in it's own repo (`phoenix-core` would rely on the `npm` package, that way.) I'd say this approach is standard in the Node world, and in other language systems that interface with JS.

But I can also investigate how we might publish from within the `phoenix-core` repo, if that's your preference.

**Comment by josevalim** [comment]
I think we should just publish from this repository. It already has the .js files and package.json. It is just a matter of adding Chris to NPM and updating the release instructions to include the NPM publishing step.

**Comment by chrismccord** [comment]
Great work! I'm still unsure about the repo setup, so for now I'd prefer to keep everything as is, but publish to npm as we release

**Comment by nicholaswyoung** [comment]
That's easy enough, though I continue my warning that it isn't exactly convention. (And I could see a event where the JS package needs a bugfix and version bump on its own.... and could be confusing to newcomers.)

@chrismccord I assume you have the same username on npm as here?

**Comment by chrismccord** [comment]
@nicholaswyoung yup

**Comment by nicholaswyoung** [comment]
On it. Expect an incoming PR with necessary changes, then you should be able to run `npm publish` at will. :)

**Comment by nicholaswyoung** [comment]
**Update:** should we do the same with `phoenix_html`? To my mind, it doesn't make sense to publish one but not the other. [It's available, after all.](https://www.npmjs.com/package/phoenix-html)

**Comment by chrismccord** [comment]
Unsure. It's like 5 LOC, but then again we're talking node :-P

**Comment by chrismccord** [comment]
But yes, we should publish it as a separate package to be consistent and it would remove the need to run mix deps.get before npm install, so +1 on phoenix_html package. It won't change often, so little maintenance once we push it up

**Comment by casio** [comment]
Awesome, can't believe this is finally happening : )

I'll repeat my thoughts here: imho having an own repo(at least for the client) will have quite some extra benefits. 
Hotfixes as @nicholaswyoung mentions, someday testing stories(yay!) with the whole unit/crossbrowser machineries not cluttering the core repo, might even help reduce js related tickets in the main repo, etc.

Anyway: great move, looking forward to install/update from an official npm package!

**Comment by chrismccord** [comment]
I will revisit a separate repo as we go, but for now I'd like to keep things simple. It's easier to coordinate releases and new features living under one repo. For example, the Presence feature would have been much more work to stage out experiments and releases across multiple repos.

**Comment by nicholaswyoung** [comment]
I'll migrate both npm dependencies, just for simplicity.

**Comment by casio** [comment]
@chrismccord uhu, understand. And thanks for considering!

Just fyi in the unlikely case you're not aware of it, you can always use `npm link`[1] to work on your local master or eg. a Presence feature branch and just push to core & client repos as you go. 
People eager to try out experiments can use git branches/hashes in their `package.json`, so basically no need to do interim releases.

[1] https://docs.npmjs.com/cli/link

**Comment by nicholaswyoung** [comment]
Closed by #1710.
