### ISSUE TITLE
Phoenix is not listed in GitHub Showcases

### ISSUE THREAD

**Issue by eksperimental** [phoenixframework/phoenix#1714]
I was checking out the Explore feature of GitHub, and to my surprise, Phoenix is not listed in
https://github.com/showcases/web-application-frameworks

I think it will be a really good place to expose the framework,
but I have no idea how to submit it for review

Hope you guys can take care of it

**Comment by ericmj** [comment]
The issue tracker is reserved for issues. If you'd like to discuss use the mailing list.
