### ISSUE TITLE
hello_phoenix project "mix phoenix.server" Don't start

### ISSUE THREAD

**Issue by rainly** [phoenixframework/phoenix#1720]
### Precheck
$ mix phoenix.server
Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"

10:57:27.825 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) an exception was raised:
        ** (CompileError) nofile:1: undefined function key/0
            (elixir) src/elixir_exp.erl:463: :elixir_exp.expand_arg/2
            (stdlib) lists.erl:1353: :lists.mapfoldl/3
            (elixir) src/elixir_exp.erl:472: :elixir_exp.expand_args/2
            (elixir) src/elixir_exp.erl:355: :elixir_exp.expand/2
            (elixir) src/elixir.erl:246: :elixir.quoted_to_erl/3
            (elixir) src/elixir.erl:197: :elixir.eval_forms/4
            (elixir) lib/code.ex:168: Code.eval_string/3

10:57:27.827 [info]  Application inets exited: :stopped

10:57:27.827 [info]  Application ssl exited: :stopped

10:57:27.827 [info]  Application public_key exited: :stopped

10:57:27.827 [info]  Application asn1 exited: :stopped

10:57:27.827 [info]  Application crypto exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {:EXIT, {%CompileError{description: "undefined function key/0", file: "nofile", line: 1}, [{:elixir_exp, :expand_arg, 2, [file: 'src/elixir_exp.erl', line: 463]}, {:lists, :mapfoldl, 3, [file: 'lists.erl', line: 1353]}, {:elixir_exp, :expand_args, 2, [file: 'src/elixir_exp.erl', line: 472]}, {:elixir_exp, :expand, 2, [file: 'src/elixir_exp.erl', line: 355]}, {:elixir, :quoted_to_erl, 3, [file: 'src/elixir.erl', line: 246]}, {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 197]}, {Code, :eval_string, 3, [file: 'lib/code.ex', line: 168]}]}}}}, {Hex, :start, [:normal, []]}}}}
    (hex) lib/hex.ex:5: Hex.start/0
    (mix) lib/mix/hex.ex:52: Mix.Hex.start/0
    (mix) lib/mix/dep/loader.ex:143: Mix.Dep.Loader.with_scm_and_app/4
    (mix) lib/mix/dep/loader.ex:99: Mix.Dep.Loader.to_dep/3
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/dep/loader.ex:295: Mix.Dep.Loader.mix_children/1
    (mix) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
    (mix) lib/mix/dep/converger.ex:52: Mix.Dep.Converger.all/4

### Environment

* Elixir version (elixir -v):

elixir -v

Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.2.5

* Phoenix version (mix deps):

mix deps

Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"

11:02:02.109 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) an exception was raised:
        ** (CompileError) nofile:1: undefined function key/0
            (elixir) src/elixir_exp.erl:463: :elixir_exp.expand_arg/2
            (stdlib) lists.erl:1353: :lists.mapfoldl/3
            (elixir) src/elixir_exp.erl:472: :elixir_exp.expand_args/2
            (elixir) src/elixir_exp.erl:355: :elixir_exp.expand/2
            (elixir) src/elixir.erl:246: :elixir.quoted_to_erl/3
            (elixir) src/elixir.erl:197: :elixir.eval_forms/4
            (elixir) lib/code.ex:168: Code.eval_string/3

11:02:02.110 [info]  Application inets exited: :stopped

11:02:02.110 [info]  Application ssl exited: :stopped

11:02:02.110 [info]  Application public_key exited: :stopped

11:02:02.111 [info]  Application asn1 exited: :stopped

11:02:02.111 [info]  Application crypto exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {:EXIT, {%CompileError{description: "undefined function key/0", file: "nofile", line: 1}, [{:elixir_exp, :expand_arg, 2, [file: 'src/elixir_exp.erl', line: 463]}, {:lists, :mapfoldl, 3, [file: 'lists.erl', line: 1353]}, {:elixir_exp, :expand_args, 2, [file: 'src/elixir_exp.erl', line: 472]}, {:elixir_exp, :expand, 2, [file: 'src/elixir_exp.erl', line: 355]}, {:elixir, :quoted_to_erl, 3, [file: 'src/elixir.erl', line: 246]}, {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 197]}, {Code, :eval_string, 3, [file: 'lib/code.ex', line: 168]}]}}}}, {Hex, :start, [:normal, []]}}}}
    (hex) lib/hex.ex:5: Hex.start/0
    (mix) lib/mix/hex.ex:52: Mix.Hex.start/0
    (mix) lib/mix/dep/loader.ex:143: Mix.Dep.Loader.with_scm_and_app/4
    (mix) lib/mix/dep/loader.ex:99: Mix.Dep.Loader.to_dep/3
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/dep/loader.ex:295: Mix.Dep.Loader.mix_children/1
    (mix) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
    (mix) lib/mix/dep/converger.ex:52: Mix.Dep.Converger.all/4

* mix hex.info (mix hex.info):
mix hex.info
11:05:19.397 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) an exception was raised:
        ** (CompileError) nofile:1: undefined function key/0
            (elixir) src/elixir_exp.erl:463: :elixir_exp.expand_arg/2
            (stdlib) lists.erl:1353: :lists.mapfoldl/3
            (elixir) src/elixir_exp.erl:472: :elixir_exp.expand_args/2
            (elixir) src/elixir_exp.erl:355: :elixir_exp.expand/2
            (elixir) src/elixir.erl:246: :elixir.quoted_to_erl/3
            (elixir) src/elixir.erl:197: :elixir.eval_forms/4
            (elixir) lib/code.ex:168: Code.eval_string/3

11:05:19.398 [info]  Application inets exited: :stopped

11:05:19.398 [info]  Application ssl exited: :stopped

11:05:19.398 [info]  Application public_key exited: :stopped

11:05:19.398 [info]  Application asn1 exited: :stopped

11:05:19.398 [info]  Application crypto exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {:EXIT, {%CompileError{description: "undefined function key/0", file: "nofile", line: 1}, [{:elixir_exp, :expand_arg, 2, [file: 'src/elixir_exp.erl', line: 463]}, {:lists, :mapfoldl, 3, [file: 'lists.erl', line: 1353]}, {:elixir_exp, :expand_args, 2, [file: 'src/elixir_exp.erl', line: 472]}, {:elixir_exp, :expand, 2, [file: 'src/elixir_exp.erl', line: 355]}, {:elixir, :quoted_to_erl, 3, [file: 'src/elixir.erl', line: 246]}, {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 197]}, {Code, :eval_string, 3, [file: 'lib/code.ex', line: 168]}]}}}}, {Hex, :start, [:normal, []]}}}}
    (hex) lib/hex.ex:5: Hex.start/0
    (hex) lib/mix/tasks/hex/info.ex:22: Mix.Tasks.Hex.Info.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
* NodeJS version (node -v):

v6.2.0

* NPM version (npm -v):

3.8.9

* Operating system:

OSX 10.9.5

**Comment by yuyabee** [comment]
Run ```mix local.hex``` as suggested in the error message and retry?

**Comment by rainly** [comment]
mix local.hex
Found existing archive(s): hex-0.12.0.ez.
Are you sure you want to replace them? [Yn] Y
* creating /Users/osxssdly/.mix/archives/hex-0.12.0.ez
osxssdlys-Mac-Pro:hello_phoenix osxssdly$

**Comment by rainly** [comment]
ix local.hex
Found existing archive(s): hex-0.12.0.ez.
Are you sure you want to replace them? [Yn] Y
* creating /Users/osxssdly/.mix/archives/hex-0.12.0.ez
osxssdlys-Mac-Pro:hello_phoenix osxssdly$ mix phoenix.server
Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"

11:30:57.374 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) an exception was raised:
        ** (CompileError) nofile:1: undefined function key/0
            (elixir) src/elixir_exp.erl:463: :elixir_exp.expand_arg/2
            (stdlib) lists.erl:1353: :lists.mapfoldl/3
            (elixir) src/elixir_exp.erl:472: :elixir_exp.expand_args/2
            (elixir) src/elixir_exp.erl:355: :elixir_exp.expand/2
            (elixir) src/elixir.erl:246: :elixir.quoted_to_erl/3
            (elixir) src/elixir.erl:197: :elixir.eval_forms/4
            (elixir) lib/code.ex:168: Code.eval_string/3

11:30:57.375 [info]  Application inets exited: :stopped

11:30:57.375 [info]  Application ssl exited: :stopped

11:30:57.375 [info]  Application public_key exited: :stopped

11:30:57.375 [info]  Application asn1 exited: :stopped

11:30:57.375 [info]  Application crypto exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {:EXIT, {%CompileError{description: "undefined function key/0", file: "nofile", line: 1}, [{:elixir_exp, :expand_arg, 2, [file: 'src/elixir_exp.erl', line: 463]}, {:lists, :mapfoldl, 3, [file: 'lists.erl', line: 1353]}, {:elixir_exp, :expand_args, 2, [file: 'src/elixir_exp.erl', line: 472]}, {:elixir_exp, :expand, 2, [file: 'src/elixir_exp.erl', line: 355]}, {:elixir, :quoted_to_erl, 3, [file: 'src/elixir.erl', line: 246]}, {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 197]}, {Code, :eval_string, 3, [file: 'lib/code.ex', line: 168]}]}}}}, {Hex, :start, [:normal, []]}}}}
    (hex) lib/hex.ex:5: Hex.start/0
    (mix) lib/mix/hex.ex:52: Mix.Hex.start/0
    (mix) lib/mix/dep/loader.ex:143: Mix.Dep.Loader.with_scm_and_app/4
    (mix) lib/mix/dep/loader.ex:99: Mix.Dep.Loader.to_dep/3
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/dep/loader.ex:295: Mix.Dep.Loader.mix_children/1
    (mix) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
    (mix) lib/mix/dep/converger.ex:52: Mix.Dep.Converger.all/4

**Comment by yuyabee** [comment]
Did you run ```mix deps.get```?
Could you paste the result of ```mix hex.info```?

**Comment by rainly** [comment]
$ mix deps.get

Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"

15:44:06.165 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) an exception was raised:
        ** (CompileError) nofile:1: undefined function key/0
            (elixir) src/elixir_exp.erl:463: :elixir_exp.expand_arg/2
            (stdlib) lists.erl:1353: :lists.mapfoldl/3
            (elixir) src/elixir_exp.erl:472: :elixir_exp.expand_args/2
            (elixir) src/elixir_exp.erl:355: :elixir_exp.expand/2
            (elixir) src/elixir.erl:246: :elixir.quoted_to_erl/3
            (elixir) src/elixir.erl:197: :elixir.eval_forms/4
            (elixir) lib/code.ex:168: Code.eval_string/3

15:44:06.166 [info]  Application inets exited: :stopped

15:44:06.166 [info]  Application ssl exited: :stopped

15:44:06.166 [info]  Application public_key exited: :stopped

15:44:06.166 [info]  Application asn1 exited: :stopped

15:44:06.166 [info]  Application crypto exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {:EXIT, {%CompileError{description: "undefined function key/0", file: "nofile", line: 1}, [{:elixir_exp, :expand_arg, 2, [file: 'src/elixir_exp.erl', line: 463]}, {:lists, :mapfoldl, 3, [file: 'lists.erl', line: 1353]}, {:elixir_exp, :expand_args, 2, [file: 'src/elixir_exp.erl', line: 472]}, {:elixir_exp, :expand, 2, [file: 'src/elixir_exp.erl', line: 355]}, {:elixir, :quoted_to_erl, 3, [file: 'src/elixir.erl', line: 246]}, {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 197]}, {Code, :eval_string, 3, [file: 'lib/code.ex', line: 168]}]}}}}, {Hex, :start, [:normal, []]}}}}
    (hex) lib/hex.ex:5: Hex.start/0
    (mix) lib/mix/hex.ex:52: Mix.Hex.start/0
    (mix) lib/mix/dep/loader.ex:143: Mix.Dep.Loader.with_scm_and_app/4
    (mix) lib/mix/dep/loader.ex:99: Mix.Dep.Loader.to_dep/3
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/dep/loader.ex:295: Mix.Dep.Loader.mix_children/1
    (mix) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
    (mix) lib/mix/dep/converger.ex:52: Mix.Dep.Converger.all/4

**Comment by rainly** [comment]
$ mix hex.info

15:44:47.206 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) an exception was raised:
        ** (CompileError) nofile:1: undefined function key/0
            (elixir) src/elixir_exp.erl:463: :elixir_exp.expand_arg/2
            (stdlib) lists.erl:1353: :lists.mapfoldl/3
            (elixir) src/elixir_exp.erl:472: :elixir_exp.expand_args/2
            (elixir) src/elixir_exp.erl:355: :elixir_exp.expand/2
            (elixir) src/elixir.erl:246: :elixir.quoted_to_erl/3
            (elixir) src/elixir.erl:197: :elixir.eval_forms/4
            (elixir) lib/code.ex:168: Code.eval_string/3

15:44:47.207 [info]  Application inets exited: :stopped

15:44:47.207 [info]  Application ssl exited: :stopped

15:44:47.207 [info]  Application public_key exited: :stopped

15:44:47.207 [info]  Application asn1 exited: :stopped

15:44:47.207 [info]  Application crypto exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {:EXIT, {%CompileError{description: "undefined function key/0", file: "nofile", line: 1}, [{:elixir_exp, :expand_arg, 2, [file: 'src/elixir_exp.erl', line: 463]}, {:lists, :mapfoldl, 3, [file: 'lists.erl', line: 1353]}, {:elixir_exp, :expand_args, 2, [file: 'src/elixir_exp.erl', line: 472]}, {:elixir_exp, :expand, 2, [file: 'src/elixir_exp.erl', line: 355]}, {:elixir, :quoted_to_erl, 3, [file: 'src/elixir.erl', line: 246]}, {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 197]}, {Code, :eval_string, 3, [file: 'lib/code.ex', line: 168]}]}}}}, {Hex, :start, [:normal, []]}}}}
    (hex) lib/hex.ex:5: Hex.start/0
    (hex) lib/mix/tasks/hex/info.ex:22: Mix.Tasks.Hex.Info.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2

**Comment by josevalim** [comment]
There is definitely something suspicious in your installation. For example, information like this: "15:44:47.207 [info] Application inets exited: :stopped" should only show up under special flags. How did you install both your Erlang and Elixir? Have you tried installing from scratch?

**Comment by rainly** [comment]
brew install erlang

**Comment by rainly** [comment]
brew install elixir

**Comment by rainly** [comment]
$ erl -v
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V7.3  (abort with ^G)

**Comment by rainly** [comment]
$ iex
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.2.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>

**Comment by chrismccord** [comment]
@rainly did you get this figured out? If not, can you try `brew update && brew reinstall elixir` ?

**Comment by rainly** [comment]
The problem is still

**Comment by chrismccord** [comment]
You have tried reinstalling erlang from scratch in addition to elixir, yes?

**Comment by rainly** [comment]
Yes ,Install Erlang and elixir from source

**Comment by chrismccord** [comment]
when you installed from source, are you positive you weren't referencing the brew versions of erlang/elixir in your PATH?

**Comment by rainly** [comment]
Before installed from source, I remove brew version erlang/elixir.

**Comment by rainly** [comment]
Well, I want intend to give up

**Comment by chrismccord** [comment]
As an absolute sanity check, can you show the output of `which erlang` and `which elixir` as well as your current stack trace? We should be able to get things sorted out! :) I've never seen errors like this on OS X

**Comment by chrismccord** [comment]
I am also on elixir-lang irc if you can hop on there so we can have quicker back and forth

**Comment by rainly** [comment]
Before  run I have checked，no problem ,correct.

**Comment by rainly** [comment]
@chrismccord ,Thank you vrey much  ! But i decided to give up.

**Comment by chrismccord** [comment]
Sorry to hear! If you feel like giving it another try please find us on elixir-lang irc and I'm positive we can get things sorted out.

**Comment by stocks29** [comment]
I ran into a similar error after upgrading to elixir 1.3 and upgrading hex to 0.13.0 (not sure which did it). Deleting my `~/.hex/hex.config` file fixed the problem.

**Comment by bruce** [comment]
For confirmation: I've also encountered this error after switching from using Erlang Solutions' Erlang + Elixir HEAD to using asdf. As @stocks29 mentions, deleting my `~/.hex/hex.config` file fixed the problem.

**Comment by ericmj** [comment]
@bruce @stocks29 The `hex.config` issue should be a separate issue or is the error message the same as the ones above?

See https://github.com/hexpm/hex/issues/279.

**Comment by LeakyBucket** [comment]
I was getting the following tonight after upgrading to hex `0.13.0` (I was already on elixir `1.3`).

```
21:18:43.728 [info]  Application hex exited: Hex.start(:normal, []) returned an error: shutdown: failed to start child: Hex.State
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {1, :erl_parse, ['syntax error before: ', []]}}
            (hex) lib/hex/config.ex:5: Hex.Config.read/0
            (hex) lib/hex/state.ex:21: Hex.State.start_link/0
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
** (MatchError) no match of right hand side value: {:error, {:hex, {{:shutdown, {:failed_to_start_child, Hex.State, {:EXIT, {{:badmatch, {:error, {1, :erl_parse, ['syntax error before: ', []]}}}, [{Hex.Config, :read, 0, [file: 'lib/hex/config.ex', line: 5]}, {Hex.State, :start_link, 0, [file: 'lib/hex/state.ex', line: 21]}, {:supervisor, :do_start_child, 2, [file: 'supervisor.erl', line: 365]}, {:supervisor, :start_children, 3, [file: 'supervisor.erl', line: 348]}, {:supervisor, :init_children, 2, [file: 'supervisor.erl', line: 314]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}}, {Hex, :start, [:normal, []]}}}}
    (hex) lib/hex.ex:5: Hex.start/0
    (mix) lib/mix/hex.ex:53: Mix.Hex.start/0
    (mix) lib/mix/dep/loader.ex:144: Mix.Dep.Loader.with_scm_and_app/4
    (mix) lib/mix/dep/loader.ex:99: Mix.Dep.Loader.to_dep/3
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/dep/loader.ex:299: Mix.Dep.Loader.mix_children/1
    (mix) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
    (mix) lib/mix/dep/converger.ex:55: Mix.D
```

deleting `~/.hex/hex.config` fixed it for me as well.
