### ISSUE TITLE
Code reloading does not always work when using Atom on Windows 10

### ISSUE THREAD

**Issue by ghalle** [phoenixframework/phoenix#1722]
### Environment

* Elixir version (elixir -v): 1.2.5
* Phoenix version (mix deps): 1.2.0-rc.0
* NodeJS version (node -v): 6.0.0
* NPM version (npm -v): 3.8.6
* Operating system: Windows 10
* Atom: 1.7.3

### Expected behavior
Code reloading always happen after saving a file using Atom

### Actual behavior
Code reloading only works after trying to save the file multiple times

Rarely an error also happen when refreshing the page after saving a file:
```
** (File.Error) could not remove files and directories recursively from e:/../priv: file already exists
    (elixir) lib/file.ex:916: File.rm_rf!/1
    (mix) lib/mix/utils.ex:254: Mix.Utils.symlink_or_copy/2
    (mix) lib/mix/project.ex:407: Mix.Project.build_structure/2
    (phoenix) lib/phoenix/code_reloader/server.ex:111: Phoenix.CodeReloader.Server.mix_compile/1
    (phoenix) lib/phoenix/code_reloader/server.ex:83: Phoenix.CodeReloader.Server.mix_compile/3
    (phoenix) lib/phoenix/code_reloader/server.ex:40: anonymous fn/2 in Phoenix.CodeReloader.Server.handle_call/3
    (phoenix) lib/phoenix/code_reloader/server.ex:132: Phoenix.CodeReloader.Server.proxy_io/1
    (phoenix) lib/phoenix/code_reloader/server.ex:38: Phoenix.CodeReloader.Server.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

This only affects code reloading of .ex files saved using atom, other editors like Sublime Text 3 always work, reloading of assets using brunch always work.

**Comment by chrismccord** [comment]
I am almost sure this is caused by a plugin you are using with Atom that is doing syntax checking/linting. The issue with plugins like this is they compile your files on save to check for compilation errors but this races the code reloader because we recompile files on new page requests. If mix reports no files need recompiled, because they've already been compiled by the plugin, there's nothing for us to reload. Hope that helps!

**Comment by ghalle** [comment]
@chrismccord Thanks, I had a plugin that did on the fly linting, I disabled it and it works now.
