### ISSUE TITLE
`{:stop, :normal, socket}` is not documented for closing channel sockets

### ISSUE THREAD

**Issue by jclem** [phoenixframework/phoenix#1727]
While attempting to figure out how to gracefully terminate a socket from a `Phoenix.Channel`, I realized that the `:normal` reason is not documented in the `Phoenix.Channel` documentation for v1.1.4. Returning anything other than `{:stop, :normal, socket}` appears to throw an error and send `phx_error` to the client.

**Comment by josevalim** [comment]
`:normal`, `:shutdown` and `{:shutdown, _}` are values defined by OTP for grateceful shutdown. The Supervisor docs have a session on them which we could likely copy and paste into the channel docs as a more accessible reference to Phoenix developers.
