### ISSUE TITLE
`Phoenix.Channel.handle_out/3` is not documented.

### ISSUE THREAD

**Issue by jclem** [phoenixframework/phoenix#1728]
While working on what I mention in https://github.com/phoenixframework/phoenix/issues/1727, I realized that `Phoenix.Channel.handle_out/3` is not documented in Phoenix v1.1.4 other than mentioning in the `Phoenix.Channel` docs (even searching for it yields no results).

**Comment by chrismccord** [comment]
The best we can do is call it out in the moduledocs like we do currently:
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/channel.ex#L101-L128

Once we only support elixir 1.3, we can make mark it in `@optional_callbacks` and it will appear in the docs as a callback. Thanks!
