### ISSUE TITLE
Maxing out database connections

### ISSUE THREAD

**Issue by endersstocker** [phoenixframework/phoenix#1730]
### Environment

* Elixir version: 1.2.3
* Phoenix version: 1.2.0-rc.0, 1.2.0-rc.1
* NodeJS version: 5.3.0
* NPM version: 3.3.12 
* Operating system: Ubuntu 14.04

### Issue

Phoenix apps deployed to Heroku following [the official guide](http://www.phoenixframework.org/docs/heroku) are now maxing out database connections for the Postgres Hobby Dev tier after upgrading to Phoenix 1.2.0-rc. Running `heroku pg | grep Connections` on a sleeping dyno emits `Connections: 0/20` for a Phoenix 1.1.4 deploy, but `Connections: 20/20` for a Phoenix 1.2.0-rc deploy. Consequences include the inability to run migrations or `psql`.

**Comment by chrismccord** [comment]
My understanding was a "sleeping dyno" is one that is spun down? It rather sounds like a change on Heroku's end, not ours as far as the way they idle dynos? In any case, can you set your Ecto pool_size lower and retry?

**Comment by josevalim** [comment]
It seems the best idea is to do in the Heroku guides:

```elixir
[pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")]
```

Can we set the POOL_SIZE only when running the server on Heroku?

/cc @jeregrine

**Comment by jeregrine** [comment]
@josevalim this is what we do in our heroku projects. I can add this to the docs.

**Comment by jeregrine** [comment]
I guess github doesn't like me amending commits :P
