### ISSUE TITLE
Argument error on ecto.create

### ISSUE THREAD

**Issue by eloyucu** [phoenixframework/phoenix#1732]
### Environment

* Elixir version (elixir -v): 1.2.3
* Phoenix version (mix deps): 1.1.4
* NodeJS version (node -v): 4.4.4
* NPM version (npm -v): 3.9.0
* Operating system: Windows 10

I just try to install the phoenix framework following the book (mix phoenix.new hello; cd hello; mix ecto.create;), and I find a error on this last commad. This error doesn´t prevent to run the server (using mix phoenix.server), but I think it could causes problems on the future, with the connections to the database or something...
Here is the problem

```
(...more lines of info...)
Consolidated List.Chars
Consolidated String.Chars
Consolidated Collectable
Consolidated Enumerable
Consolidated IEx.Info
Consolidated Inspect
** (ArgumentError) argument error
    (stdlib) :io.put_chars(:standard_error, :unicode, [[[], <<42, 42, 32, 40, 77, 105, 120, 41, 32, 84, 104, 101, 32, 100, 97, 116, 97, 98, 97, 115, 101, 32, 102, 111, 114, 32, 72, 101, 108, 108, 111, 46, 82, 101, 112, 111, 32, 99, 111, 117, 108, 100, 110, 39, 116, 32, 98, 101, ...>>], 10])
    (mix) lib/mix/cli.ex:67: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

 
Should I worry? 

Thank you very much.

**Comment by chrismccord** [comment]
Is this the entire stack trace? @josevalim any obvious windows specific signs to you before I dig deeper?

**Comment by jerel** [comment]
Looks like the argument in ascii starts with "** (Mix) The database for Hello.Repo couldn't be" so the original issue might be that the database wasn't created?

**Comment by josevalim** [comment]
It seems whatever is being printed was not returned as UTF-8 by the adapter. I am not sure if there much we can do. :(

**Comment by eloyucu** [comment]
Well, I tried to create a new project with the flag --database mysql, and after execute mix ecto.create, I get no warning, no error, no nothing!!
So... I have a problem with postgre... but, does no one else who had experienced same problem on windows 10?? (I install the postgre from a installer... I suppose it is the most common)

**Comment by josevalim** [comment]
@eloyucu the previous version was definitely working, it just failed when printing the message but everything else was fine. Ecto 2.0 will have better results for this, specially because it no longer uses command line to for create and drop.

**Comment by eloyucu** [comment]
Sorry... after a second test with postgresql I realized it was my fault. I hadn´t set up the config/dev.exs with the correct password for the user of the database.

It something that you don´t say on the book, I hope you do not displease me tell, I only do for improve the next edition. There is another thing that it is not on the book but is on the web: when you make a new controller (using the router.ex), and a new template, it seems to be enough as to make the request to the new action... but it is not true (I think), we need to make a view handler (¿no?).

PS: I am going to add it in the erratum page (as a suggestion).

**Comment by eloyucu** [comment]
Excuse me... I had re-read those first lines... and you don´t create a new controller, so you don´t have why use a view.
