### ISSUE TITLE
Consider casting Presence.track key to string

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1734]
Presence.list returns a map keyed off the grouped presences, but if the key is not a string, Poison will get angry:

    (Poison.EncodeError) expected string or atom key, got: 1

We can either convert to a string if an integer is passed or we can raise and inform the user, but the former is likely the way to go.

**Comment by josevalim** [comment]
We are going to change it in the Presence level and not in the tracker, right?

**Comment by chrismccord** [comment]
Yup
