### ISSUE TITLE
wrong controller function used when trying to create new resource when there are multiple scopes with same path but no duplicate routes

### ISSUE THREAD

**Issue by andshape** [phoenixframework/phoenix#1738]
### Precheck 
Looked at SO, Phoenix mailing list and existing bug list. The closest related question I could find on SO is this: http://stackoverflow.com/questions/36170123/phoenix-elixir-ecto-casterror-value-new-in-where-cannot-be-cast-to-type

### Environment

* Elixir version (elixir -v): 1.2.4
* Phoenix version (mix deps): 

1. connection 1.0.2 (Hex package) (mix)
2.  fs 0.9.1 (Hex package) (rebar)
3.  gettext 0.11.0 (Hex package) (mix)
4.  ranch 1.2.1 (Hex package) (rebar)
5.  poolboy 1.5.1 (Hex package) (rebar)
6.  decimal 1.1.2 (Hex package) (mix)
7.  poison 2.1.0 (Hex package) (mix)
8.  db_connection 0.2.5 (Hex package) (mix)
9.  cowlib 1.0.2 (Hex package) (rebar)
10.  cowboy 1.0.4 (Hex package) (rebar)
11.  plug 1.1.5 (Hex package) (mix)
12.  phoenix_html 2.5.1 (Hex package) (mix)
13.  phoenix 1.1.4 (Hex package) (mix)
14.  phoenix_live_reload 1.0.5 (Hex package) (mix)
15.  postgrex 0.11.1 (Hex package) (mix)
16.  ecto 1.1.8 (Hex package) (mix)
17.  phoenix_ecto 2.0.2 (Hex package) (mix)

* NodeJS version (node -v): v5.10.1
* NPM version (npm -v): 3.8.3
* Operating system: Windows 10

### Setup
Steps to reproduce:

1. Create a new phoenix project
2. run: Mix phoenix.gen.html User users name:string
3. Define your routes like this:

```
scope "/", Routestest do
    pipe_through :browser # Use the default browser stack

    resources "/users", UserController, only: [:show]
  end

  scope "/", Routestest do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/users", UserController, only: [:create, :new, :index, :edit, :update, :delete]
  end
```
Note how there are two scopes with the same path but with no overlapping routes, which should be legal according to this http://www.phoenixframework.org/docs/routing. 
4. run mix ecto.setup
5. run mix phoenix.server 
6. navigate to http://localhost:4000/users 
7. click on New user link.

Note that the link is autogenerated (from phoenix.gen.html): <%= link "New user", to: user_path(@conn, :new) %>

### Expected behavior
Clicking on the "New user" link should lead me to the form where I can create the new user.

### Actual behavior
Crash: Phoenix routes me to the "show" function instead of the "new" function (and sets id = new)

The problem seem to be that it looks at the very first scope and only sees the show action and doesn't take into account that a new action is defined in a later scope. This means that the routes are defined as:
```

user_path  GET     /users/:id       Routestest.UserController :show
page_path  GET     /                Routestest.PageController :index
user_path  GET     /users           Routestest.UserController :index
user_path  GET     /users/:id/edit  Routestest.UserController :edit
user_path  GET     /users/new       Routestest.UserController :new
```

This means that the route http://localhost:4000/users/new matches the show route (id = new). If I, on the other hand, had only defined one scope for the users resource and had explicitly defined the allowed actions as [:show, :create, :new, :index, :edit, :update, :delete] it would have been smart enough to know that :new takes "precedence" to show (even though it is defined later in the action list). This is also reflected in the routes if you run mix phoenix.routes in this case:

```
user_path  GET     /users           Routestest.UserController :index
user_path  GET     /users/:id/edit  Routestest.UserController :edit
user_path  GET     /users/new       Routestest.UserController :new
user_path  GET     /users/:id       Routestest.UserController :show
```

You see the new-route is higher up the list than the show-route. I would expect it to be smart enough to do the same if the actions had been defined in different scopes with the same path.

**Comment by chrismccord** [comment]
This is expected, /users/new is the same matching path as /users/123, but when you used `resources "/users"`... phoenix will define the routes in the proper order that "/users/new" matches first. Because you used the first scope/route to specifically handle `:show`, it will always match /users/new, regardless of the 2nd route.

> The problem seem to be that it looks at the very first scope and only sees the show action and doesn't take into account that a new action is defined in a later scope.

This isn't something we handled for you so you need to handle the route precedence yourself and if you have overlapping scopes you need to take care in the order they are defined in. Hope that helps!

**Comment by andshape** [comment]
Hi Chris

Super fast response from you = awesome! :-)
I did already resolve it by explicitly defining the order I wanted the scopes in a way to get the correct routing table  (+ defining an extra scope), but I would still expect phoenix to handle new vs. show for me. 

Imagine you had two or more resources and for each of the resources you wanted some of the action-routes through one pipeline and some through another. A practical example could be that you had an authentication pipeline you wanted to use for some of the actions and the remaining actions were open to anyone . In this case we could define two scopes (with the same path): One for each pipeline. Now imagine that we end up in the following situation:

```
scope "/", MyApp do
    pipe_through [:pipeline_a]
    resources "/resourcea", ResourceAController, only: [:show]
    resources "/resourceb", ResourceBController, only: [:new]
#... more routes
end

scope "/", MyApp do
      pipe_through [:pipeline_b]
      resources "/resourcea", ResourceAController, only: [:new]
      resources "/resourceb", ResourceBController, only: [:show]
#... more routes
end
```

There is no way to reorder the scopes to get the right behaviour. The only way to resolve it is to introduce yet another scope like this:

```
scope "/", MyApp do
    pipe_through [:pipeline_a]
    resources "/resourceb", ResourceBController, only: [:new]
end

scope "/", MyApp do
      pipe_through [:pipeline_b]
      resources "/resourcea", ResourceAController, only: [:new]
      resources "/resourceb", ResourceBController, only: [:show]
end

scope "/", MyApp do
    pipe_through [:pipeline_a]
    resources "/resourcea", ResourceAController, only: [:show]
end
```

Right?

**Comment by chrismccord** [comment]
> Imagine you had two or more resources and for each of the resources you wanted some of the action-routes through one pipeline and some through another. A practical example could be that you had an authentication pipeline you wanted to use for some of the actions and the remaining actions were open to anyone .

You can move the authentication plug to the controller and do `plug Auth when action in [:new, :show]`. In such cases I usually split my routes and controllers as they have different concerns, but the conditional plug solves this occasional cases nicely
