### ISSUE TITLE
Phoenix.js continuously tried to rejoin a channel when joining when the server is down

### ISSUE THREAD

**Issue by lboekhorst** [phoenixframework/phoenix#1740]
### Environment

* Elixir version (elixir -v): 1.2.3
* Phoenix version (mix deps): 1.1.4 (`phoenix` JS library from npm, 1.2.0-rc.0)
* NodeJS version (node -v): 5.7.1
* NPM version (npm -v): 3.8.1
* Operating system: OS X El Capitan

### Expected behavior

The scenario is as follows:

- Shutdown Phoenix
- Join `rooms:shipment:123` while Phoenix is down (`channel.join()`)
- Start Phoenix

After this, I expect phoenix.js to join `rooms:shipment:123` and properly push messages to it.

### Actual behavior

It continuously attempts to reconnect to `rooms:shipment:123` after the web socket connection has opened.

`[info] MyApp.ShipmentChannel received join event with topic "channels:shipment:123" but channel already joined`

Because phoenix.js is clearly in a state where it is under the impression it has not joined the channel, pushing messages onto it will not work even though it already properly joined. I think there is a race condition going on between the channel's reply handler (`this.on(CHANNEL_EVENTS.reply...)` and the `onError` callback because if I put a `debugger` statement in the reply handler, and in the `onError` handler, it will join the channel just once, but if I remove them, it will continuously try to join the channel again.

**Comment by chrismccord** [comment]
I was unable to recreate your exact issue, but it may be because we handle duplicate joins differently on the server in 1.2. I did however find an issue where channels were rejoined on reconnect who previously hand't joined. Can you give phoenix.js on master a shot? If you still find you are seeing the issue, can you tried Phoenix 1.2rc-0 so I can narrow down? Thanks!

**Comment by lboekhorst** [comment]
It just upgraded to Phoenix 1.2.0-rc.1 with phoenix.js on master and it's working as I would expect now. Awesome, thanks!
