### ISSUE TITLE
is it possible to add an exclude option for force_ssl?

### ISSUE THREAD

**Issue by sikanhe** [phoenixframework/phoenix#1743]
Right now I am deploying a site to aws ELB, where the load balancer performs health checks by sending a request to http to my ec2 instances. 

I have ssl terminated at the ELB level, however, I still want to redirect all http traffic to https, and since you cannot do that at the ELB/DNS level, I tried to use force_ssl: [rewrite_on: x_forwarded_proto] at the app level to redirect to https. 

however, since ELB needs ping the app servers with http, the servers respond with 302 and the check fails. 

I am wondering if there is a way to set a route "/health_check" where it will bypass the force_ssl redirect?

**Comment by chrismccord** [comment]
yes, you can add the plug to a pipeline or you can wrap the plug in your own plug which has an `exclude` path list, which checks the request path and calls the force ssl plug conditionally. In the future please direct questions to the mailing list or irc. We reserve the issue tracker for issues, as is layed out in the issue template

**Comment by sikanhe** [comment]
@chrismccord sorry about that, thank you so much.
