### ISSUE TITLE
Inform users of changed mime type configuration

### ISSUE THREAD

**Issue by ericmj** [phoenixframework/phoenix#1744]
Using the new :mime type library is a breaking change and users should be informed about it in the upgrade guides since all mime configurations will silently stop working if you do change your config.

I would also suggest adding the same warning plug has: https://github.com/elixir-lang/plug/blob/master/lib/plug/mime.ex#L4

**Comment by ericmj** [comment]
Two mime bugs in two days on hex.pm:

https://github.com/hexpm/hex_web/commit/20fb066adf962bd5c18ec5a171e1e0a46836099a
https://github.com/hexpm/hex_web/commit/23ff712b5590ac064f68de92bc4e33de3e6ca75d

Also, when you change the configuration you need to force recompile your dependencies. This either means running `mix deps.clean` or deleting `_build/` which is confusing itself and even more complicated on places like Heroku.

**Comment by josevalim** [comment]
I have reverted the changes otherwise we will run into situations like @ericmj has posted. If we want to use the `Mime` library, we need to depend on Plug v1.2 (which has not been released yet).
