### ISSUE TITLE
priv/static not created if not existing

### ISSUE THREAD

**Issue by eproxus** [phoenixframework/phoenix#1754]
### Environment

* Elixir version (elixir -v):

   ```
   Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

   Elixir 1.2.6
   ```
* Phoenix version (mix deps):

    ```
    * phoenix 1.2.0-rc.1 (Hex package) (mix)
      locked at 1.2.0-rc.1 (phoenix) 08fdf0f2
      ok
    ```
* NodeJS version (node -v): `v6.2.1`
* NPM version (npm -v): `3.9.3`
* Operating system: OS X 10.11.5

### Expected behavior

When running `mix phoenix.digest` on a clean checkout, I expect the folder `priv/static` to be filled with compiled static assets.

### Actual behavior

```
$ mix phoenix.digest
The input path "priv/static" does not exist
```

**Comment by josevalim** [comment]
"priv/static" is the *source* directory. So how can it generate compiled static assets with there is no *source* directory? You probably forgot to call something like `brunch build --type production`, so I would say it is really good this error message is there. :)

**Comment by eproxus** [comment]
I thought the assets came from `web/static`? Which is the target directory?

**Comment by eproxus** [comment]
Okay, after reading http://www.phoenixframework.org/docs/deployment#section-compiling-your-application-assets things cleared up a bit. Sorry for the noise!

**Comment by Panda-404** [comment]
In my case, to fix it I did this:
 cd assets 
 npm install
 npm run deploy

**Comment by unozerocode** [comment]
Thanks @Panda-404 , that fixed it for me.  
Even though I am using a framework that uses yarn, I still had to run the `npm run deploy` command to fix this.
🥇
