### ISSUE TITLE
Use the new calendar types in Ecto generators

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#1756]
This is for v1.2 and it will require us to sync ecto, phoenix_ecto and phoenix_html releases.

**Comment by josevalim** [comment]
This is also pending on Ecto 2.1 and a new Phoenix Ecto.

**Comment by chrismccord** [comment]
Notes: We'll use `:naive_datetime` in the Ecto generators

**Comment by josevalim** [comment]
We should support both naive_datetime and utc_datetime in the generator "syntax". We need to decide what to do with "datetime" (raise or convert to naive_datetime).

**Comment by chrismccord** [comment]
`:datetime` is rewritten as `:naive_datetime` and documented in Gen.Schema
