### ISSUE TITLE
Problem with rendering shared partials

### ISSUE THREAD

**Issue by nicohvi** [phoenixframework/phoenix#1758]
Hey guys, love the library 👍 

### Environment
* Elixir version: 1.2.5
* Phoenix version: 1.1.6
* Operating system: OS X

I have defined the following shared partial
```elixir
defmodule App.SharedView do
  use App.Web, :view
end
```

```elixir
# web/templates/shared/_flash.html.haml
%section#flash
  %p= get_flash(@conn, :error)
```

However, when I try *this* I get an error
```elixir
# in a different template
= render Gnome.SharedView, "_flash.html" assigns
```

```
Could not render '_flash.html' for App.SharedView, please define a matching clause for render/2 or define a template at "web/templates/shared2. The following templates were compiled:

*_flash.html
```

This works fine though
```elixir
= Phoenix.View.render(App.SharedView, "_flash.html", assigns)
```

I might just be overlooking something simple :-)

**Comment by chrismccord** [comment]
Based on the error message, it looks like you passed `'flash.html'`, as a single quote char list, instead of double quote string. Can you double check?

**Comment by Troush** [comment]
If you call your view as `= render Gnome.SharedView, "_flash.html" assigns`
You need to define your view as:
```
defmodule Gnome.SharedView do
  use Gnome.Web, :view
end
```

**Comment by nicohvi** [comment]
You're absolutely correct @chrismccord! Thank you very much :-)
