### ISSUE TITLE
warning: redefining module Mix.Tasks.Phoenix.New

### ISSUE THREAD

**Issue by gmile** [phoenixframework/phoenix#1759]
When I run `mix test` in phoenix repo after cloning, I get this warning:

```
warning: redefining module Mix.Tasks.Phoenix.New (current version loaded from /Users/gmile/.mix/archives/phoenix_new.ez/phoenix_new/ebin/Elixir.Mix.Tasks.Phoenix.New.beam)
```
It appears that there's a conflict between having phoenix repo for development and having installed a `phoenix_new` task above.

Given the `phoenix_new` task above is the [right way](https://github.com/phoenixframework/phoenix/issues/756#issuecomment-186903988) of creating new phoenix projects, **should the warning continue to exist**?

I always thought of warnings as a way of tell programmer to prepare & update his code for upcoming changes in tools he's using, which doesn't seem to be the case here.

**Comment by gmile** [comment]
Actually, I'm having as second thought. This isn't an actual issue. As an example, I get warnings all the time when running `iex` and recompiling/reloading the code. Working around warnings like that wouldn't make much sense.

Closing this.

**Comment by chrismccord** [comment]
Since you have the phoenix.new mix archive installed, when compiling/running phoenix itself it will override the already loaded mix archive with its own phoenix.new, so this is expected and not a problem.

**Comment by gmile** [comment]
@chrismccord thanks for clarifying this!
