### ISSUE TITLE
Demo Channel Chat  Site does not work ( http://phoenixchat.herokuapp.com )

### ISSUE THREAD

**Issue by keithn** [phoenixframework/phoenix#1762]
### Expected behavior

Awesome Chats with myself

### Actual behavior

Nothing happens on the screen, dropping to the browser console...

channel: error rooms:lobby undefined
app.js:21 something went wrong undefined
app.js:15 CLOSE CloseEvent {wasClean: false, code: 1006, reason: "", type: "close", target: WebSocket…}
phoenix.js:637 WebSocket connection to 'ws://phoenixchat.herokuapp.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 400
app.js:7 transport: [object Event] undefined
app.js:7 channel: error rooms:lobby undefined
app.js:21 something went wrong undefined
app.js:7 transport: close CloseEvent {wasClean: false, code: 1006, reason: "", type: "close", target: WebSocket…}
app.js:7 channel: error rooms:lobby undefined
app.js:21 something went wrong undefined
app.js:15 CLOSE CloseEvent {wasClean: false, code: 1006, reason: "", type: "close", target: WebSocket…}

Would really like to know what went wrong.... Bit worried if a deployed app can just "break".

**Comment by Mazyod** [comment]
The websocket path doesn't look right to me, which version are you using?

```
ws://phoenixchat.herokuapp.com/ws
```

The path has always been `/socket` (then `/websocket` for websocket transport)

**Comment by chrismccord** [comment]
Please open an issue on the phoenix_chat_example project, as this is not phoenix related :) Thanks!
