### ISSUE TITLE
mix test - ** (ArgumentError) cannot load `"20160528004928"` as type :integer

### ISSUE THREAD

**Issue by sergiotapia** [phoenixframework/phoenix#1763]
I just updated a dummy Phoenix app that I have that I only changed the HTML for the main template for.

```
$ mix deps.update phoenix phoenix_html phoenix_live_reload
```

Now `mix test` fails:

```
sergiotapia at Sergios-iMac in ~/Work/nanote on master [!]
$ mix test
** (ArgumentError) cannot load `"20160528004928"` as type :integer
    (ecto) lib/ecto/repo/queryable.ex:132: Ecto.Repo.Queryable.load!/3
    (ecto) lib/ecto/adapters/sql.ex:515: anonymous fn/3 in Ecto.Adapters.SQL.process_row/3
    (elixir) lib/enum.ex:1246: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (ecto) lib/ecto/adapters/sql.ex:513: Ecto.Adapters.SQL.process_row/3
    (elixir) lib/enum.ex:1183: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/ecto/adapters/sql.ex:283: Ecto.Adapters.SQL.decode/2
    (ecto) lib/ecto/adapters/sql.ex:272: Ecto.Adapters.SQL.decode/3

    (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapters.SQL.query/5
```

### Environment

* Elixir version (elixir -v): 1.3.0
* Phoenix version (mix deps): 1.1.6
* NodeJS version (node -v): v6.0.0
* NPM version (npm -v): 3.8.6
* Operating system: OSX El Capitan 10.11.3

### Expected behavior

Should run the sample test that comes with any brand new generated Phoenix project.

### Actual behavior

Crashes with above error.

---

The app itself still runs fine with `mix phoenix.server`

**Comment by michalmuskala** [comment]
Do you use an already created rails database for this? A similar error is often caused by trying to run ecto migrations on a rails database.

**Comment by sergiotapia** [comment]
Good catch, yes I do have a database created with Rails. I'll try dropping the database and re-running `mix test`.

**Comment by sergiotapia** [comment]
That fixed the issue - right on
