### ISSUE TITLE
No matching clause error causes a request to hang forever instead of returning a 400/404

### ISSUE THREAD

**Issue by sikanhe** [phoenixframework/phoenix#1765]
Repo to reproduce: https://github.com/sikanhe/bug

So I have a route path defined as `get "/series/:id", SeriesController, :get`

I have a controller action called :get, however it does not have matching function clause. So it should return status of 400 or at least throw error.  

However, what happens in this app is that it will just hang the request forever and never respond. After some digging, i found that i had debug_errors: false, I turned it on, now the error is shown in the iex console and the path correctly returns a 400 status. However shouldn't it return 400 regardless of the debug_errors: false setting?  

This also hangs my app in production as well. 

I am unable to reproduce this in a fresh project, so I am wondering if it is any config in my app that is causing this but i am lost. 

P.S, making many requests like this will also cause beam to be running at 140+ energy drain on my macbook and cause its battery to drain quickly. This has been happening in my dev app for a couple weeks, had no idea because the hanging requests gets lost in the debug messages with other requests.

**Comment by sikanhe** [comment]
I think i found out what was wrong, i have a no` render("400.json", _assign) ` defined inside ErrorView. So i think it is stuck in a recursive loop here it is trying to find a 400.json view for the no matching clause for render("400.json") ? This is my guess.

**Comment by chrismccord** [comment]
That was indeed the case. We now detect the infinite call-stack when rendering and raise a `Phoenix.Template.UndefinedError` like any normal case. Thanks for finding this and providing great details for recreation!

**Comment by josevalim** [comment]
Chris, I would raise only if the value in template_not_found is the current
module.

On Wednesday, June 22, 2016, Chris McCord <notifications@github.com> wrote:

> That was indeed the case. We now detect the infinite call-stack when
> rendering and raise a Phoenix.Template.UndefinedError like any normal
> case. Thanks for finding this and providing great details for recreation!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1765#issuecomment-227871027>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbh6NvLIKqxTuW51dY1rX458P_kgAks5qOZ7zgaJpZM4I7PpG>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
@josevalim good catch! I'll make the change
