### ISSUE TITLE
Task compile.phoenix is broken on 1.3.0

### ISSUE THREAD

**Issue by dustinfarris** [phoenixframework/phoenix#1766]
### Environment

* Elixir version (elixir -v): __1.3.0__ (does not happen with 1.2.6)
* Phoenix version (mix deps): 1.1.6 or 1.2.0-rc.1
* Operating system: OSX or Linux (Ubuntu)

### Expected behavior

Running `MIX_ENV="prod" mix do clean, compile` operates normally

### Actual behavior

```
└──➤ MIX_ENV="prod" mix do clean, compile
** (MatchError) no match of right hand side value: {:error, {:plug, {'no such file or directory', 'plug.app'}}}
    (phoenix) lib/mix/tasks/compile.phoenix.ex:11: Mix.Tasks.Compile.Phoenix.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1183: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.ex:84: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
```

**Comment by radar** [comment]
I can verify this issue happens on a new Phoenix 1.2.0-rc app, except I see this output:

```
MIX_ENV="prod" mix do clean, compile
** (Mix) The task "compile.phoenix" could not be found. Did you mean "compile.elixir"?
```

**Comment by aaronjensen** [comment]
Are you on elixir 1.3? This is an elixir 1.3 specific issue as far as I can tell. I don't believe `deps.compile` is run by default when doing `compile` anymore.

**Comment by chrismccord** [comment]
It indeed appears to be the Elixir 1.3 issue, but I'll let @josevalim verify before closing. Thanks!

**Comment by radar** [comment]
Yes I am on Elixir 1.3.0, installed from Homebrew this morning.

**Comment by dustinfarris** [comment]
@aaronjensen yes on 1.3.0.  Your command works.  So is this not a bug?

Stumbled across via edeliver here: https://github.com/boldpoker/edeliver/blob/master/libexec/erlang#L172

So assuming either phoenix task needs to be updated or edeliver needs to updated or both.

**Comment by dustinfarris** [comment]
A little more digging (again, on 1.3.0):

If I blow out _build (rm -r), this works:

```
rm -rf _build && mix do clean
```

This also works:

```
rm -rf _build && mix do compile
```

This does _not_ work:

```
rm -rf _build && mix do clean, compile
```

**Comment by josevalim** [comment]
Fixed in Elixir master, thank you!
