### ISSUE TITLE
Link content not rendered when a bare integer is provided to link/2 helper

### ISSUE THREAD

**Issue by colinrymer** [phoenixframework/phoenix#1769]
### Environment

* Elixir version (elixir -v): 1.3.0
* Phoenix version (mix deps): 1.1.6 and 1.2.0-rc.1 (master@3401373)
* NodeJS version (node -v): 5.3.0
* NPM version (npm -v): 3.7.0
* Operating system: OS X 10.11.2

### Expected behavior
When I use `<%= link(1, to: "/") %>`, I get `<a href="/">1</a>` as the rendered html. (`1` is being used in this case as a hardcoded example of an ID)

### Actual behavior
`<%= link(1, to: "/") %>` is rendered as `<a href="/"></a>`

If I call `Phoenix.HTML.Link.link/2` directly in IEx, I get what appears to be an expected result, though I'm slightly surprised the `1` in the middle of the list isn't quoted.:

```elixir
iex(1)> Phoenix.HTML.Link.link(1, to: "/")
{:safe, ["<a href=\"/\">", 1, "</a>"]}
```

**Comment by colinrymer** [comment]
Apologies if this should be opened in [phoenix_html](https://github.com/phoenix_framework/phoenix_html) instead. Based on the response from `Phoenix.HTML.Link.link(1, to: "/")`, I took that to be an issue with something Phoenix was doing.

After a little more exploration, it looks like this might be a bug with `phoenix_html` instead, so if I need to close this and open an issue there, I'm happy to do so.

**Comment by josevalim** [comment]
It is fixed in phoenix_html master. :)

**Comment by colinrymer** [comment]
Awesome! Thanks for the super quick response! :D
