### ISSUE TITLE
Revisit directory and naming conventions

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#177]
Hello everyone,

I would like to start a discussion around the naming and directory conventions on Phoenix. Here are some concerns:
1. Phoenix doesn't make a distinction between code that requires the server to be restarted and code that does not
2. Phoenix inherits the singular/plural conventions from Rails (although I am not sure if there is a way around it)

Regarding 1., there is a bunch of code in Phoenix applications that cannot simply be recompiled. Everything in a supervision tree, for example, won't work if simply recompiled without the supervision tree being restarted. On the other hand, restarting the supervision tree automatically is a lot of work and error prone.

One solution in this case is to have a web/ directory, where the router, model, controllers, views and template will be defined. Very little work is needed to make this work on Phoenix side, we would just need to:
1. Add `elixirc_paths: ["lib", "web"]` to the `mix.exs` file
2. Change the code reloader plug to only use "web" when calling the compile task

This way, we can at least say, everything in web is automatically reloaded, changing everything else requires a server restart. In this structure, we would have:

```
web
  /controllers
  /models
  /views
  /templates
  router.ex
```

Regarding the singular and plural conventions, although we are familiar with Rails' one, I believe most of us can recall being confused with Rails conventions on the matter at some point. Maybe it is worth departing from Rails here.

On the opposite side, Phoenix has departed from Rails by having `MyApp.Controllers.Users` while Rails has `UsersController`. Although the app namespacing is a good idea, I am not sure the controller namespacing is a good one, simply because we can have many namespacing ending with `.Users`, as in `MyApp.Controllers.Users` and `MyApp.Views.Users`.

One possible solution is go with singular, suffixed modules. For example, `MyApp.UserController`. We would still have to worry about singular and plural in the named routes though, which we could discuss at a later point.

**Comment by HannesHolste** [comment]
What's the best practice for naming routes using English terms that have no plural, e.g. knowledge?

Avoid words with no plurals – e.g. by naming it knowledgeitems – or artificially make it plural, e.g. "knowledges"?

**Comment by chrismccord** [comment]
We don't pluralize anything, so there is no problem naming it "knowledge" :)
