### ISSUE TITLE
Show sources in compile errors

### ISSUE THREAD

**Issue by rstacruz** [phoenixframework/phoenix#1775]
Sup friends.

When we receive a compile-time error, it looks like this:

![image](https://cloud.githubusercontent.com/assets/74385/16387244/994d5434-3cc6-11e6-8ddb-cf2496aa1613.png)

But for a runtime error, it looks like this:

![image](https://cloud.githubusercontent.com/assets/74385/16387255/a64d3bfe-3cc6-11e6-948e-c25fe41bd514.png)

Is there a way to show sources on compile-time errors as well? FWIW, I'm developing a [template engine](https://github.com/rstacruz/phoenix_expug) and I'm trying to make the experience as hassle-free as possible.

**Comment by josevalim** [comment]
The issue so far is that compilation is very driven by writing to standard output. We could improve it in the long term but we would need to push some work to Elixir first.
