### ISSUE TITLE
Proposal: new error page

### ISSUE THREAD

**Issue by rstacruz** [phoenixframework/phoenix#1776]
Hey, friends. Let's talk about Phoenix's error page. I think we can do a lot of improvement here.

![image](https://cloud.githubusercontent.com/assets/74385/16389363/2a53dc92-3cd0-11e6-9ab6-6cb0d6bf6227.png)

## Situation
This design has served Phoenix and better_errors well for a while, but it can use some improvement.

- The exception messages are limited to one line (tho more info can be shown on hover). This is kind of cumbersome, considering many Elixir errors can span multiple lines.

- The request info/headers/params/session area (below the source) made sense for better errors, because better_errors allowed you to inspect what's in each stack frame. Not quite so in Phoenix. It feels weird that it's huge and it looks like it changes when you click on a stack frame on the left.

- It feels needlessly verbose. Most times I'm only concerned about what error happened, and the line that triggered it. These need to be presented more prominently.

## Proposal

How about something more like this?

![image](https://cloud.githubusercontent.com/assets/74385/16389501/cdc811fe-3cd0-11e6-8842-e6c86928aa8b.png)

Gone is the weird frame-like scrolling; instead, it scrolls down naturally like a page would. (except for the stack trace... you should be able to scroll it down on its own iframe-like container.)

You'll see that above the fold, most the relevant things are what immediately draws your attention.

> ![image](https://cloud.githubusercontent.com/assets/74385/16389698/b691af3a-3cd1-11e6-9321-f88648018911.png)

By putting all the "more info" stuff at the bottom, we get more space to do more interesting things. How links to search Google for the error? Or maybe link to the relevant hexdocs?

> ![image](https://cloud.githubusercontent.com/assets/74385/16389571/1e3142a0-3cd1-11e6-8ef4-33d23db50e9e.png)

This is a rough draft of course, but if you like where this is going I'd be happy to polish it up and implement it.

## By the way

I'm the author of the original [better_errors error page](https://github.com/charliesome/better_errors), which I believe Phoenix's is based off of :)

**Comment by josevalim** [comment]
This is so elegant, thank you! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

> The exception messages are limited to one line (tho more info can be shown on hover). This is kind of cumbersome, considering many Elixir errors can span multiple lines.

This has been my biggest pet peeve and you solved it perfectly! I absolutely love the links to search and docs too. Well done!

Btw, the debug pages come from Plug. Here is the source: https://github.com/elixir-lang/plug/blob/master/lib/plug/debugger.ex and here is the template: https://github.com/elixir-lang/plug/blob/master/lib/plug/templates/debugger.eex

I would merge this PR in a heartbeat. :) Let me know if there is anything I can do to help!

**Comment by josevalim** [comment]
> I'm the author of the original better_errors error page, which I believe Phoenix's is based off of :)

Yes! I emailed you 3 years ago to ask for permission. :D

**Comment by rstacruz** [comment]
oh man I'm so sorry I didn't see your email on that, haha, but it's all MIT license so it's all good!

**Comment by rstacruz** [comment]
(Oh, you may have emailed Charlie @charliesome—he's the author of better_errors, I just contributed frontend work to his project)

**Comment by josevalim** [comment]
@rstacruz No problems! I e-mailed you both but went ahead because of MIT anyway. :D

**Comment by chrismccord** [comment]
@rstacruz this looks amazing! I love every changed you're proposing. Your work on better_errors is something I include in every talk I give about having "pretty errors", and this would take it over the top :)

We'd love to have this in place if you're up for it. Since this is on the plug side, we'll need to think how to best get this in plug, but also allow it to be extensible so we can include the help links that are dep specific. Thanks!

**Comment by rstacruz** [comment]
Neat! What would be the best way to put together a little development setup to hack Plug.Debugger? (I'm guessing maybe something like a mini-phoenix app with `deps/plug` being part of elixirc_paths and Phoenix.CodeReloader reloadable_paths?)

**Comment by rstacruz** [comment]
> but also allow it to be extensible so we can include the help links

After giving this some thought, I realized that feature might have been thinking way too far ahead—for a first iteration, maybe something that just implements the baseline functionality that the current version has would be best.

**Comment by chrismccord** [comment]
yes that sounds like a good firs step in plug. With some hooks to plug debugger I think we could make it extensible, but getting baseline in place first is a good start

**Comment by josevalim** [comment]
And if we decide to go ahead with the links anyway, I can help with making them configurable. :)

**Comment by rstacruz** [comment]
okay, that's quick and easy. thanks for the tips!

**Comment by allyraza** [comment]
@rstacruz if you need help I can certainly lend you a hand

**Comment by rstacruz** [comment]
hmm, `r Plug.Debugger` isn't quite reloading template changes for me.

**Comment by josevalim** [comment]
@rstacruz I will investigate soon and provide a small Plug app that does code reloading only for Plug.Debugger. :D

**Comment by rstacruz** [comment]
haha, cool, i'm doing ctrl+c - up - enter for now :D

**Comment by josevalim** [comment]
@rstacruz if you create a file named `app.exs` at the root of your Plug checkout with the following contents:

```elixir
defmodule MyRouter do
  use Plug.Router
  use Plug.Debugger

  plug :reload
  plug :match
  plug :dispatch

  defp reload(conn, _) do
    IEx.Helpers.r(Plug.Debugger)
    conn
  end

  get "/oops" do
    _ = conn
    raise "oops"
  end
end

{:ok, _} = Plug.Adapters.Cowboy.http MyRouter, port: 4000
```

You can start it with `mix run --no-halt app.exs` and now you access `localhost:4000/oops` for a custom exception or any route for a function clause error. Live reloading should work (although it is a hack :D).

**Comment by rstacruz** [comment]
Thanks for everyone who's volunteering to help! I have it working on [this branch](https://github.com/rstacruz/plug/tree/feature/new-error-page), feel free to try it out (maybe with @josevalim's test code up there). Just a few more refinements and I'll open up a PR.

![plugtest](https://cloud.githubusercontent.com/assets/74385/16785592/71be5e20-48c1-11e6-91a5-51b96a473336.gif)

**Comment by rstacruz** [comment]
Okay, that's done! I'd imagine this is next:

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/code_reloader.ex

**Comment by josevalim** [comment]
@rstacruz yes, that would definitely be the next step. I have changed Phoenix master to depend on Plug 1.2-dev in case you want to give it a try inside Phoenix.

**Comment by josevalim** [comment]
Actually, we still need to change the code reloader error pages. So I am reopening this. :D
