### ISSUE TITLE
Phoenix JS sdk keeps trying to connect even after successfully connecting to the sever

### ISSUE THREAD

**Issue by bvjebin** [phoenixframework/phoenix#1778]
I have found a problem with the Phoenix JS SDK. Because of the JS SDK missing an important callback, the following logs are printed in the server continuously.

```
module=Phoenix.Channel.Server line=217 Server.ServerMessagesDeliveryAcksChannel received join event with topic "server.message_delivery_acks" but channel already joined
module=Phoenix.Channel.Server line=217 Server.GlobalPresenceChannel received join event with topic "global_presence_channel" but channel already joined
```

The following is the setup required to reproduce.

1) The SDK must be used from an html page which should join 4 to 5 channels.
2) The phoenix server must run in IEx mode.

Following are the steps to reproduce:
1) Visit the html page where the Phoenix JS is used to connect to the phoenix server application.
2) Once the connection is successful, make some change to one of the files in the `lib` directory and save it. (Doing changes to `lib` files need the server to be restarted. No hot reload. Here is the catch)
3) Now refresh the html page so that the Phoenix JS SDK will try to connect to the server.
4) Leave the setup to throw exceptions for a minute and then restart the phoenix server application (Don not refresh the html page).

Keep watching the IEx console. You will find that even after the channels have connected successfully, the Phoenix JS SDK will try reconnecting for which the server will respond with "already joined" response.

This scenario is not a real world scenario where one changes the `lib` file in the servers and that creates these kind of problems.

But few network fluctuations are triggering the same behavior and in my production application, nearly 80% of the logs are filled with these statements. Believe me, in 10 days 12GB log file is generated out of which 80% is this message logged for 7 channels. It happens very randomly and goes away when the client application is refreshed. But it happens and happens very often. I couldn't reproduce with the exact network condition but the same result happened via the above mentioned steps.

When I debugged the JS file, I figured out that the below given piece of code in the **Channel** function is not getting called during the above scenario which is the callback that resets the rejoin timer and marks the status to be "joined".

```
this.joinPush.receive("ok", function () {
  _this2.state = CHANNEL_STATES.joined;
  _this2.rejoinTimer.reset();
  _this2.pushBuffer.forEach(function (pushEvent) {
    return pushEvent.send();
  });
  _this2.pushBuffer = [];
});
```

Moreover, as workaround, I overrode the **onMessage**​ callback in the channel instances with the below piece of code ​from my application ​which fixed the issue for me. I know this is not a clean solution, but still works. I hope this can be fixed from within the JS SDK.
```
channelInstance.onMessage = function(event, payload) {
    if(event === "phx_reply" && payload.status === "ok") {
        channelInstance.state = "joined";
        channelInstance.rejoinTimer.reset();
        channelInstance.pushBuffer.forEach(function(pushEvent) {
            return pushEvent.send();
        });
        channelInstance.pushBuffer = [];
    }
};
```

One Suggestion: 
In case of the JS SDK, why shouldn't it stop trying to join the channels if the socket is not connected(errored out)? Once the socket is back, only then start the timer for joining the channels. This way channel joins won't be independent of the socket connect and the actions will be in series(one after the other) and ensures no race condition or missing callback executions. Again, you guys know the decision behind the implementation. 

Let me know if you need any more information on this.

### Environment

* Elixir version (elixir -v): 1.2.3
* Phoenix version (mix deps): 1.1.4
* NodeJS version (node -v): 5.2.0
* NPM version (npm -v): 3.3.12
* Operating system: mac 10.11.3

**Comment by chrismccord** [comment]
Please upgrade to Phoenix 1.2 and this should be fixed. Please reopen if that is not the case. Thanks!

**Comment by bvjebin** [comment]
Is Phoenix 1.2 officially released?

**Comment by chrismccord** [comment]
Yep. You can follow the upgrade guides here https://gist.github.com/chrismccord/29100e16d3990469c47f851e3142f766

**Comment by bvjebin** [comment]
Thanks. I will grade and let you know if I face the issue.
