### ISSUE TITLE
Add possibility to turn off phoenix.digest query string ?vsn=d

### ISSUE THREAD

**Issue by VladShcherbin** [phoenixframework/phoenix#1784]
* Phoenix version (mix deps): 1.2

Currently, when we run `phoenix.digest`, it adds `?vsn=d` to the links in the files. It also adds fingerprint to the filename, so this `?vsn=d` is not necessary.

It is suggested to use only fingerprints in filename and to remove query string from links ([link](https://gtmetrix.com/remove-query-strings-from-static-resources.html)).

Can we have an option to disable this query string so it won't be added into files and to the links, currently it seems to be hardcoded.

**Comment by VladShcherbin** [comment]
Seems related to [issue](https://github.com/phoenixframework/phoenix/issues/1499) and [commit](https://github.com/phoenixframework/phoenix/commit/ee34b6bcbd46c204974d43a801993b5ddf79d5a3)

**Comment by josevalim** [comment]
You still need the query string to tell the server to cache for long periods of times.

**Comment by josevalim** [comment]
Sorry, premature send. Therefore, we can have an option to disable the query string (if we don't have one yet) but the default should be to leave it enabled.

**Comment by VladShcherbin** [comment]
@josevalim yes, a config option with default _enabled_ would be awesome.

I have nginx pointing to phoenix app, so I think if will work fine.

Thank you.

**Comment by josevalim** [comment]
Can you send a PR please?

On Wednesday, June 29, 2016, Vlad Shcherbin <notifications@github.com>
wrote:

> @josevalim <https://github.com/josevalim> yes, a config option with
> default *enabled* would be awesome.
>
> I have nginx pointing to phoenix app, so I think if will work fine.
>
> Thank you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1784#issuecomment-229376471>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbifvC1oUSTeqn7sgMZjMehQ5a5bLks5qQoNogaJpZM4JBIt5>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by VladShcherbin** [comment]
@josevalim I would love to, but I'm still not that good with `elixir`, sorry.

**Comment by chrismccord** [comment]
> It is suggested to use only fingerprints in filename and to remove query string from links

Hey @VladShcherbin , this is no longer suggested for any modern proxy:
http://wiki.squid-cache.org/ConfigExamples/DynamicContent

I'm closing since I don't think dropping the query string param is necessary, but please feel free to follow up on this issue if you have a real-world usecase in the wild where the presence of the param is causing problems. Thanks!

**Comment by stuartc** [comment]
@chrismccord struggling with this at the moment - I'm no caching expert; however it seems with the forced suffix `?vsn=d`, all the ETAG stuff that can be provided by `Plug.Static` appears to be unreachable.

Is the general approach to configure nginx [etc.] properly and forget out it?

**Comment by mpranjic** [comment]
> I'm closing since I don't think dropping the query string param is necessary, but please feel free to follow up on this issue if you have a real-world usecase in the wild where the presence of the param is causing problems. Thanks!

I'm having an issue in Firefox where static files are not cached when there's `vsn=d` query parameter.
Removing the query (in browser's Network tab) and resending the request twice causes the second one to be cached as expected (because of the ETag).

**Comment by sulphur** [comment]
it is beacuse `Plug.Static` don't put Etag's when `vsn` query params is present

**Comment by OvermindDL1** [comment]
> it is beacuse Plug.Static don't put Etag's when vsn query params is present

Well that sounds like a bug...

**Comment by sulphur** [comment]
not sure. You rather want to manage your cache via `vsn` query string or via etags. Never both IMHO

**Comment by sulphur** [comment]
but i think you can configure plug static to do both
