### ISSUE TITLE
mix phoenix.gen.html should add the route to router.ex

### ISSUE THREAD

**Issue by sanford** [phoenixframework/phoenix#1787]
### Expected behavior

Enter:

mix phoenix.gen.html User users attribute:type attribute2:type2....

Expect:

resources "/users", UserController

to be added to router.ex

### Actual behavior

A comment is printed on the screen at the end of many lines of output which easily gets lost when generating more than one model at a time.

### Use Case

When setting up a fresh project its not uncommon to generate 4+ models at a time.  Unfortunately instead of focusing on the models, the current generator forces you to context switch to the router.ex file in fear of losing track of all the router lines in your scrollback buffer.

Even worse, for folks new to the framework they may not notice the comment in the wall of generator output.

### Suggested options

Either:

* Add the 'resources ...' line in router.ex

or:

* Add a commented out '# resources ...' line that we can uncomment later

Either way, it lets us defer the router.ex editing until we're ready to context switch and saves us a bunch of hunt & copy & paste & worry we didn't copy them all.

**Comment by michalmuskala** [comment]
This was discussed multiple times. While it would be completely awesome to do that, I'm not really sure it's not doable. The main difficulty being - which scope should this resources be added to? You have just two in the most basic case, but most apps I've seen have much more - I don't think there's a way to automatically decide which is the correct one.

**Comment by sanford** [comment]
@michalmuskala Sure, then how about the 2nd suggestion above?  Add a commented out resources line to the router.ex file - that's trivial to move to the right place.   

`# resources "/users", UserController # uncomment this line and move to the right scope.
`
and perhaps add a note in the command output to the user:


```
The following commented-out route has been added to router.ex.  Please uncomment and move to the correct scope for your application:
# resources "/users", UserController # uncomment this line and move to the right scope.
```

Or something like that.

The goal is being able to mentally defer router work until after you're done generating a bunch of models.  

Getting the route into the router.ex file as a comment perhaps solves both concerns?

**Comment by josevalim** [comment]
I think this will actually be more work. Now I need to pay attention to the
command, find the comment in the router and move it accordingly. We are
effectively adding one extra step and more text.

It makes sense for when generating multiple resources but that's not the
common case.

On Saturday, July 2, 2016, sanford <notifications@github.com> wrote:

> @michalmuskala <https://github.com/michalmuskala> Sure, then how about
> the 2nd suggestion above? Add a commented out resources line to the
> router.ex file - that's trivial to move to the right place.
>
> # resources "/users", UserController # uncomment this line and move to the
> right scope.
>
> and perhaps add a note in the command output to the user:
>
> The following commented-out route has been added to router.ex.  Please uncomment and move to the correct scope for your application:
> # resources "/users", UserController # uncomment this line and move to the right scope.
>
> Or something like that.
>
> The goal is being able to mentally defer router work until after you're
> done generating a bunch of models.
>
> Getting the route into the router.ex file as a comment perhaps solves both
> concerns?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1787#issuecomment-230092337>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbmyRwNWW_C9JarER3wTVFNN9CqX5ks5qRiwygaJpZM4JDnK->
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
Thanks for the suggestion! You can search the issues list and mailing list for discussions around the decisions, but this is not something we'll be addressing.
