### ISSUE TITLE
"MIX_ENV=prod mix release" dies in Phoenix 1.2.0

### ISSUE THREAD

**Issue by Alamoz** [phoenixframework/phoenix#1789]
Everything in my app appears to be in order. The app runs perfectly in development mode.

### Environment

* Elixir version:  1.3.0
* Phoenix version:  1.2.0
* NodeJS version:  v6.2.2
* NPM version:  3.10.3
* Operating system:  Linuxmint 17.3  (Ubuntu 14.04 package base)

### Expected behavior

"MIX_ENV=prod mix release" should produce a release of my Phoenix app.

### Actual behavior

The mix process dies with the follow output at the end:

===> Provider successfully run: app_discover
===> Running provider resolve_release
===> Solving Release myapp-0.0.1
===> Provider (resolve_release) failed with: {error,
                                                     {rlx_prv_release,
                                                      {failed_solve,
                                                       {unreachable_package,
                                                        myapp}}}}

==> ERROR: "Unable to find application myapp. See the debug output for more information."

**Comment by josevalim** [comment]
@Alamoz can you please post your `mix.exs`?

**Comment by Alamoz** [comment]
I created the app fresh from Phoenix 1.2.0, it is not an upgrade from a previous version. Here is mix.exs:

defmodule Myapp.Mixfile do
  use Mix.Project

  def project do
    [app: :Myapp,
     version: "0.0.1",
     elixir: "~> 1.2",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases(),
     deps: deps()]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {Myapp, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:exrm, "~> 1.0"}]
  end

  # Aliases are shortcuts or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"],
     "test": ["ecto.create --quiet", "ecto.migrate", "test"]]
  end
end

**Comment by josevalim** [comment]
@Alamoz there is an inconsistency somewhere. Notice the release is looking for an application named "myapp"  in lowercase but your app is named "Myapp" uppercase. You should find where "myapp" is used and convert it to "Myapp" or rename everything to "myapp".

Other than that, this seems to be a bug, mix phoenix.new should not allow an app name in uppercase generally.

**Comment by Alamoz** [comment]
I didn't create the app with an uppercase name, Phoenix generated the "Myapp" names from the "myapp" I used when creating the app. I will look through the files and try to find the inconsistency.

**Comment by Alamoz** [comment]
The app mixes "Myapp" and "myapp" in various places, there is no consistency. When I try changing the case, various other bugs occur. Now when I try generating a release I get a different complaint:

** (Mix) Cannot execute task because the project was not yet compiled. When build_embedded is set to true, "MIX_ENV=prod mix compile" must be explicitly executed

**Comment by josevalim** [comment]
Can you recover which command you used to build the app?

I have just tried locally and "mix phoenix.new myapp" worked fine with no
uppercase app names.

On Sunday, July 3, 2016, Adrien Lamothe <notifications@github.com> wrote:

> The app mixes "Myapp" and "myapp" in various places, there is no
> consistency. When I try changing the case, various other bugs occur. Now
> when I try generating a release I get a different complaint:
>
> ** (Mix) Cannot execute task because the project was not yet compiled.
> When build_embedded is set to true, "MIX_ENV=prod mix compile" must be
> explicitly executed
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1789#issuecomment-230173947>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbiPu61AcygX1wYWB5N-nnSR7verzks5qSB1jgaJpZM4JD8B2>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Alamoz** [comment]
OK, this is what ended up working:

$ mix release.clean
$ MIX_ENV=prod mix compile
$ MIX_ENV=prod mix release

Something must have been munged up. I never had to do the "MIX_ENV=prod mix compile" step before, maybe now with Phoenix 1.2.0 that is required, because of the "build_embedded" flag set to true by default?

**Comment by Alamoz** [comment]
The uppercase names are in mix.exs and do occur when a new app is created, I just did it again and the uppercase names are still there; they were also in that same format in my older Phoenix apps:

defmodule Myapp.Mixfile do ...

  def application do
    [mod: {Myapp, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex]]
  end

**Comment by Alamoz** [comment]
I'm thinking this is a documentation issue, that now you have to perform the "MIX_ENV=prod mix compile" step before building a release.

**Comment by ericmj** [comment]
It's this name we are looking for in your `mix.exs` file:

```elixir
def project do
[app: :Myapp, ...]
end
```

It should be lowercase when generated by `phoenix.new`. If it's not my guess is that you have an old version of the generator.

**Comment by Alamoz** [comment]
@ericmj  I created the app from the latest Phoenix release, I installed it just today. Anyway, the release was generated after I performed the steps mentioned.

**Comment by chrismccord** [comment]
@Alamoz can you triple check the command you ran by running `history | grep phoenix.new` ? The :Myapp name is very peculiar and not something the generator should have done if the command you used is the one you reported.

**Comment by Alamoz** [comment]
The name created by the generator was correct, it was lower case. I'm obfuscating my app name in these posts with "Myapp", the actual name is something else. I made the mistake of renaming it "Myapp" when replacing the names.

**Comment by chrismccord** [comment]
Ok thanks for the follow up. Since we don't have a means to recreate this, we'll have to wait until we get other reports or more info. Glad you got things working!

**Comment by Alamoz** [comment]
As a follow-up comment, when building a production release you do have to perform the "$ MIX_ENV=prod mix compile" step, otherwise this error is thrown:

** (Mix) Cannot execute task because the project was not yet compiled. When build_embedded is set to true, "MIX_ENV=prod mix compile" must be explicitly executed

Grep for "build_embedded" shows:

deps/phoenix_pubsub/mix.exs:     build_embedded: Mix.env == :prod,

So, you may want to update the documentation to reflect this. Thanks for all your help @chrismccord @josevalim @ericmj !
