### ISSUE TITLE
[Static Files] Route doesn't work when you change the folder structure

### ISSUE THREAD

**Issue by yordis** [phoenixframework/phoenix#1794]
I did some setup with Webpack and my output configuration look likes this
```js
output: {
    path: './priv/static',
    filename: '[name].js'
  }
```
As you notice I put all my assets under `./priv/static/` which means that I will have something like `./priv/static/application.js`.

and then I did something like
```html
<script src="<%= static_path(@conn, "/application.js") %>"></script>
```

### Environment

* Elixir version (elixir -v): 1.3.1
* Phoenix version (mix deps):  1.2.0
* NodeJS version (node -v): 6.2.2
* NPM version (npm -v): 3.9.5
* Operating system: OS X, 10.11.5

### Expected behavior
Phoenix should deliver the `application.js` file.

### Actual behavior
`(Phoenix.Router.NoRouteError) no route found for GET /application.js`

The only way I make this works is put my Javascript files under `./priv/static/js*` which means that now I have to organize my files under the `static` folder with specific folder structures and because of that now I have to put `/js/*` in my URLs in the HTML.

I don't want to lose the freedom of having whatever structure I want even under `static` folder. URLs are part of my application design as well and in this case Phoenix is forcing me.

**Comment by josevalim** [comment]
Check your `lib/my_app/endpoint.js`. In `Plug.Static` there is a list of files you want to serve under `priv/static`. You will see that `js` is listed but `application.js` isn't. The reason we have such list is for two reasons: the first is security, so any file accidentally dropped in priv/static is not server, the other one is for performance, so we check for static files only when necessary. You are free to change it accordingly, Phoenix is not forcing you to stick with it, but now you are aware of the trade-offs. :)

**Comment by yordis** [comment]
@josevalim thanks a lot for the help. At least now I have the ability to do whatever I want, that was my main concern about it!
