### ISSUE TITLE
Broadcast failing if the channel does not define handle_out/3

### ISSUE THREAD

**Issue by dmorneau** [phoenixframework/phoenix#1795]
### Environment

* Elixir version (elixir -v): 1.3.1
* Phoenix version (mix deps): 1.2.0
* NodeJS version (node -v): 6.2.2
* NPM version (npm -v): 3.9.5
* Operating system: OS X

### Expected behavior

I would expect broadcasts to work in a channel that does not have `handle_out/3` as long as `intercept/1` is not used.

### Actual behavior

I think since https://github.com/phoenixframework/phoenix/pull/1700/ was merged, broadcasts now fail unless `handle_out/3` is defined in the channel.

```
[error] GenServer #PID<0.412.0> terminating
** (UndefinedFunctionError) function MyApp.MyChannel.handle_out/3 is undefined or private. Did you mean one of:

      * handle_in/3
      * handle_info/2

    (myapp) MyApp.MyChannel.handle_out("snapshot", %{ <snip> })
    (phoenix) lib/phoenix/channel/server.ex:233: Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by chrismccord** [comment]
> I would expect broadcasts to work in a channel that does not have handle_out/3 as long as intercept/1 is not used.

This should be true. Can you provide a full example that recreates the problem?

**Comment by dmorneau** [comment]
I noticed it only happens when I use phoenix_pubsub_redis (2.1.0), with pg2 it works fine. I'll dig some more and report back.

**Comment by dmorneau** [comment]
Here's a repro (start redis in the background, then run `mix test`): https://github.com/dmorneau/phoenix/commit/72de969e944bdd925e920d527ec1adb2c3985de0

The existing test ("push broadcasts by default") also fails because `handle_out` is being called for a message that's not supposed to be intercepted.

Note that phoenix_pubsub_redis doesn't start as of 2.1.0. Changing `|> Keyword.merge(@defaults, opts)` to `opts = Keyword.merge(@defaults, opts)` in `phoenix_pubsub_redis/redis.ex` fixes it. I've been meaning to submit a PR for that file but I would need to get some approvals first.

**Comment by chrismccord** [comment]
You are right. This is a bug on the phoenix_pubsub_redis side. I'm addressing it now. Thanks!

**Comment by chrismccord** [comment]
This has been fixed. You should be all set on phoenix_pubsub_redis v2.1.2. Thanks for reporting!

**Comment by dmorneau** [comment]
Awesome, thanks!
