### ISSUE TITLE
Large amount of files under /priv slows down dev server

### ISSUE THREAD

**Issue by jhlllnd** [phoenixframework/phoenix#1796]
### Environment

* Elixir version (elixir -v) :1.3.1
* Phoenix version (mix deps): 1.2.0
* NodeJS version (node -v): 6.2.2
* NPM version (npm -v): 3.9.5
* Operating system: Debian Jessie (amd64)

### Expected behavior
Server is as fast as usual

### Actual behavior
Server slows down when there is a very large amount of files under /priv. (16k files: 1s instead of ~20ms)

I have a SPA written in JS that is in a Git sub-module under /priv/app. As every JS app there is a large node_modules folder that slows down the server even when that files aren't important for the phoenix app.

I can remove that sub-folder because i only need the compiled result under /priv/static. So I don't need any help but I thought i let you guys know.

**Comment by chrismccord** [comment]
> I can remove that sub-folder because i only need the compiled result under /priv/static. So I don't need any help but I thought i let you guys know.

This is the answer. We are aware of the slowdown, but there's not an easy optimization for us for cases like this when the files are in the elixirc paths or priv. The best answer is to only build your files into priv/, and leave the reset of the source with node_modules outside, like we do with web/static
