### ISSUE TITLE
Changing the structure of the database on the fly causes: ERROR (feature_not_supported): cached plan must not change result type 

### ISSUE THREAD

**Issue by janjiss** [phoenixframework/phoenix#1797]
Okay, so this might qualify as a bug or might not, but we have a shared database between two apps. The structure does not actually change for us, but I was not able to reproduce the bug with barebones app without changing the structure of the table, hence the example changes the type of the column.

When we change the structure of the table outside of phoenix, db connections in the pool throw an error of:  ERROR (feature_not_supported): cached plan must not change result type.

New connections are not effected

### Steps to reproduce:

mix phoenix.new hello
cd hello
mix
mix phoenix.gen.json Hello hello hello:string```

Add the resource to your api scope in web/router.ex:

    resources "/hello", HelloController, except: [:new, :edit]

mix ecto.migrate
mix ecto.schema.dump

go to localhost:4000/hello

take following code from priv/repo/structure.sql that was generated by mix ecto.schema.dump:
```SQL
CREATE TABLE hello (
    id integer NOT NULL,
    hello character varying(255),
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
```
and change it to:
```SQL
CREATE TABLE hello (
    id integer NOT NULL,
    hello integer,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
```
Execute the query in your favourite PG client.

Refresh localhost:4000/hello and you will get: 

ERROR (feature_not_supported): cached plan must not change result type

NOTE: You might need to hit refresh several times for the query to be executed in one of the old connections or limit your pool size to 1. 

If you kill Elixir.Hello.Repo in observer or restart the app, it fixes the problem. 

Similar issue in ActiveRecord: https://github.com/rails/rails/issues/1892

### Environment

* Elixir version (elixir -v): Elixir 1.3.1
* Phoenix version (mix deps): 
 connection 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (connection) 3145f741
  ok
* fs 0.9.1 (Hex package) (rebar)
  locked at 0.9.2 (fs) ed17036c
  ok
* gettext 0.11.0 (Hex package) (mix)
  locked at 0.11.0 (gettext) 80c1dd42
  ok
* ranch 1.2.1 (Hex package) (rebar)
  locked at 1.2.1 (ranch) a6fb992c
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (decimal) 79a769d4
  ok
* poison 2.2.0 (Hex package) (mix)
  locked at 2.2.0 (poison) 4763b69a
  ok
* db_connection 1.0.0-rc.3 (Hex package) (mix)
  locked at 1.0.0-rc.3 (db_connection) d9ceb670
  ok
* phoenix_pubsub 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (phoenix_pubsub) c31af4be
  ok
* cowlib 1.0.2 (Hex package) (rebar)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.0.4 (Hex package) (rebar)
  locked at 1.0.4 (cowboy) a324a8df
  ok
* plug 1.1.6 (Hex package) (mix)
  locked at 1.1.6 (plug) 8927e402
  ok
* phoenix_html 2.6.0 (Hex package) (mix)
  locked at 2.6.0 (phoenix_html) b9f7e091
  ok
* phoenix 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (phoenix) 1bdeb99c
  ok
* phoenix_live_reload 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (phoenix_live_reload) 829218c4
  ok
* postgrex 0.11.2 (Hex package) (mix)
  locked at 0.11.2 (postgrex) 139755c1
  ok
* ecto 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (ecto) b02331c1
  ok
* phoenix_ecto 3.0.0 (Hex package) (mix)
  locked at 3.0.0 (phoenix_ecto) b947aaf0
  ok
* Operating system: All

**Comment by chrismccord** [comment]
This is an Ecto issue, so please address there, but first I would take this to the mailing list. It sound like once the pool connections crash they are re-established and work properly? If so, I don't know there is much for us to handle. Under the scenario where you need to migrate the schema outside the application, you will have to structure your deploys/restarts accordingly. Hope that helps!

**Comment by janjiss** [comment]
@chrismccord Nope, they don't get re-established properly. Anyways, I will post this issue to mailing list. Much appriciated
