### ISSUE TITLE
code_reloader not reloading phoenix build in dev

### ISSUE THREAD

**Issue by maz-dev** [phoenixframework/phoenix#1800]
### Environment

* Elixir version (elixir -v): 1.3.0
* Phoenix version (mix deps): phoenix 1.2.0
* NodeJS version (node -v): n/a
* NPM version (npm -v): n/a
* Operating system: OSX El Capitan

### Expected behavior
Phoenix should recompile on elixir file change and reload.

### Actual behavior
It doesn't reload, for example I delete a function from a module and it's still available in iex untill I kill the vm.

Code reloader is set to true in dev config and new empty projects are showing the same behavior.
phoenix_live_reload is installed and present in mix.exs.

This issue is appearing with multiple editors used (atom, sublime, webstorm and emacs).
I don't know where to start the troubleshooting, so if you have any suggestion I'll try it asap.

**Comment by josevalim** [comment]
Try turning off all editors and then touch any file in "web". When you access the page, do you see a "Compiling ..." message in your terminal? And are you sure there is nothing running in the background that could potentially compile your code?

**Comment by maz-dev** [comment]
not reloading by touching a file and nothing related to elixir or erlang running in the background.

**Comment by maz-dev** [comment]
Nothing new after a permissions repair.

Done so far:
- No editor running
- No process related to elixir or erlang, except the beam process spawned by running mix phoenix.server
- Touching a file doesn't trigger the reload
- Permissions checked and repaired
- Added on spotlight privacy list to force reindexing
- Deleted the _build folder
- Checked out the main project from git 
- New projects are not reloading either
- FSevents seems to be working fine with nodejs projects on my machine

**Comment by maz-dev** [comment]
I did a full reinstall (it was planned anyway).

Code_reload is now working fine. My guess is that it was a OSX FS issue. 

Closing this issue.
