### ISSUE TITLE
Phoenix.Presence Dialyzer issues

### ISSUE THREAD

**Issue by OvermindDL1** [phoenixframework/phoenix#1804]
### Precheck

Googled but found nothing

### Environment

* Elixir version (elixir -v): Elixir 1.3.1 Erlang/OTP 18
* Phoenix version (mix deps): phoenix 1.2.0
* NodeJS version (node -v): v6.2.0
* NPM version (npm -v): 3.8.9
* Operating system: Windows 10 and Debian Jesse

### Expected behavior
Presence should dialyze cleanly

### Actual behavior

A plain:
```elixir
  use Phoenix.Presence, otp_app: :my_server,
                        pubsub_server: MyServer.PubSub
```
Causes:
```elixir
issue_presence.ex:75: Expression produces a value of type {'ok',pid()}, but this value is unmatched
issue_presence.ex:75: The inferred return type of init/1 ({'ok',#{}}) has nothing in common with {'error',_} | {'ok',pid()}, which is the expected return type for the callback of 'Elixir.Phoenix.Presence' behaviour
issue_presence.ex:75: The inferred return type of track/3 ({'error',_} | {'ok',binary()}) has nothing in common with 'ok', which is the expected return type for the callback of 'Elixir.Phoenix.Presence' behaviour
issue_presence.ex:75: The inferred return type of track/4 ({'error',_} | {'ok',binary()}) has nothing in common with 'ok', which is the expected return type for the callback of 'Elixir.Phoenix.Presence' behaviour
issue_presence.ex:75: The inferred return type of update/3 ({'error',_} | {'ok',binary()}) has nothing in common with 'ok', which is the expected return type for the callback of 'Elixir.Phoenix.Presence' behaviour
issue_presence.ex:75: The inferred return type of update/4 ({'error',_} | {'ok',binary()}) has nothing in common with 'ok', which is the expected return type for the callback of 'Elixir.Phoenix.Presence' behaviour
```

Adding this to the file:
```elixir
  @dialyzer [
    {:nowarn_function, 'init': 1},
    {:nowarn_function, 'track': 3},
    {:nowarn_function, 'track': 4},
    {:nowarn_function, 'update': 3},
    {:nowarn_function, 'update': 4},
    ]
```
Will silence most of it, except for this (which happens on the `use` line above)
```elixir
issue_presence.ex:75: Expression produces a value of type {'ok',pid()}, but this value is unmatched
```

**Comment by josevalim** [comment]
We should fix those instead of not warning. A PR is welcome!

On Monday, July 11, 2016, OvermindDL1 <notifications@github.com> wrote:

> Precheck
>
> Googled but found nothing
> Environment
>
>    - Elixir version (elixir -v): Elixir 1.3.1 Erlang/OTP 18
>    - Phoenix version (mix deps): phoenix 1.2.0
>    - NodeJS version (node -v): v6.2.0
>    - NPM version (npm -v): 3.8.9
>    - Operating system: Windows 10 and Debian Jesse
>
> Expected behavior
>
> Presence should dialyze cleanly
> Actual behavior
>
> A plain:
>
>   use Phoenix.Presence, otp_app: :my_server,
>                         pubsub_server: MyServer.PubSub
>
> Causes:
>
> issue_presence.ex:75: Expression produces a value of type {'ok',pid()}, but this value is unmatched
> issue_presence.ex:75: The inferred return type of init/1 ({'ok',#{}}) has nothing in common with {'error',_} | {'ok',pid()}, which is the expected return type for the callback of 'Elixir.Phoenix.Presence' behaviour
> issue_presence.ex:75: The inferred return type of track/3 ({'error',_} | {'ok',binary()}) has nothing in common with 'ok', which is the expected return type for the callback of 'Elixir.Phoenix.Presence' behaviour
> issue_presence.ex:75: The inferred return type of track/4 ({'error',_} | {'ok',binary()}) has nothing in common with 'ok', which is the expected return type for the callback of 'Elixir.Phoenix.Presence' behaviour
> issue_presence.ex:75: The inferred return type of update/3 ({'error',_} | {'ok',binary()}) has nothing in common with 'ok', which is the expected return type for the callback of 'Elixir.Phoenix.Presence' behaviour
> issue_presence.ex:75: The inferred return type of update/4 ({'error',_} | {'ok',binary()}) has nothing in common with 'ok', which is the expected return type for the callback of 'Elixir.Phoenix.Presence' behaviour
>
> Adding this to the file:
>
>   @dialyzer [
>     {:nowarn_function, 'init': 1},
>     {:nowarn_function, 'track': 3},
>     {:nowarn_function, 'track': 4},
>     {:nowarn_function, 'update': 3},
>     {:nowarn_function, 'update': 4},
>     ]
>
> Will silence most of it, except for this (which happens on the use line
> above)
>
> issue_presence.ex:75: Expression produces a value of type {'ok',pid()}, but this value is unmatched
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1804>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAAlbhq7Ad8SVrErELW1S2K5XOiCXJchks5qUopOgaJpZM4JJpGG>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by OvermindDL1** [comment]
Indeed they should!  I will not be able to make a PR while at work, however I might be able to do so when at home since the SO is out of town this evening.  Will try so if possible.  :-)

**Comment by OvermindDL1** [comment]
A question, would you be opposed to having dialyxir as a dev-only dependency?  Would make it easier to have others verify cleanliness of dialyzing as well.

**Comment by OvermindDL1** [comment]
Setup a mini-PR at #1805 to fix a few immediate issues for now.

**Comment by chrismccord** [comment]
@OvermindDL1 Thanks! We'll gladly accept PR's around this so if you have others beyond #1805, please submit. In the meantime I'll close so we can keep a handle on what has and hasn't been done.
