### ISSUE TITLE
Extract the phoenix.js client for easier use with a separate frontend.

### ISSUE THREAD

**Issue by ospaarmann** [phoenixframework/phoenix#1806]
I just wanted to check back on [this issue](https://github.com/phoenixframework/phoenix/issues/827) and ask if there are any plans extracting the phoenix.js client? It would be extremely helpful, especially since more and more people will use phoenix just as a backend / API and create the frontend in Angular 2 or React.

**Comment by chrismccord** [comment]
It is published independently on npm

**Comment by ospaarmann** [comment]
Oh. Thanks! Which one is the official package? There are a couple.

**Comment by ospaarmann** [comment]
Sorry, nevermind. I think being tired and trying to figure things out is not a good combo...

https://www.npmjs.com/package/phoenix
