### ISSUE TITLE
Generating bad code with mix phoenix.gen.json 

### ISSUE THREAD

**Issue by keithn** [phoenixframework/phoenix#1812]
I initially opened a question here...

http://stackoverflow.com/questions/38350228/generating-a-model-referencing-self-column-name-error

which is to do with 

`mix phoenix.gen.json Part parts name part_of:references:parts`

which has an error when queying the database expecting a column named part_of_id 

` ** (Postgrex.Error) ERROR (undefined_column): column p0.part_of_id does not exist`

I wasn't sure if it's an error or not, but playing around with it, it seems like there is a hidden assumption that if you don't magically know that references NEED to be suffixed with _id the command above generates non working code.

I'd expect the command to fail and tell you you need to suffix _id 
or alternatively, it injects _id for you.

### Environment

Elixir 1.3.0
* connection 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (connection) 3145f741
  ok
* fs 0.9.1 (Hex package) (rebar)
  locked at 0.9.2 (fs) ed17036c
  ok
* gettext 0.11.0 (Hex package) (mix)
  locked at 0.11.0 (gettext) 80c1dd42
  ok
* ranch 1.2.1 (Hex package) (rebar)
  locked at 1.2.1 (ranch) a6fb992c
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (decimal) 79a769d4
  ok
* poison 2.2.0 (Hex package) (mix)
  locked at 2.2.0 (poison) 4763b69a
  ok
* db_connection 1.0.0-rc.3 (Hex package) (mix)
  locked at 1.0.0-rc.3 (db_connection) d9ceb670
  ok
* cowlib 1.0.2 (Hex package) (rebar)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.0.4 (Hex package) (rebar)
  locked at 1.0.4 (cowboy) a324a8df
  ok
* plug 1.1.6 (Hex package) (mix)
  locked at 1.1.6 (plug) 8927e402
  ok
* phoenix_html 2.6.1 (Hex package) (mix)
  locked at 2.6.1 (phoenix_html) 7d53fb8d
  ok
* phoenix 1.1.6 (Hex package) (mix)
  locked at 1.1.6 (phoenix) 7bf19002
  ok
* phoenix_live_reload 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (phoenix_live_reload) 829218c4
  ok
* postgrex 0.11.2 (Hex package) (mix)
  locked at 0.11.2 (postgrex) 139755c1
  ok
* ecto 1.1.8 (Hex package) (mix)
  locked at 1.1.8 (ecto) 0f0348e6
  ok
* phoenix_ecto 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (phoenix_ecto) 1aff51d1
  ok

Windows 10

**Comment by josevalim** [comment]
Thank you @keithn! This is duplicated of #1605 though, so we are closing it in favor of the original report.
