### ISSUE TITLE
Endpoint with wrong otp_app fails silently

### ISSUE THREAD

**Issue by michalmuskala** [phoenixframework/phoenix#1815]
### Environment

* Elixir version (elixir -v): master
* Phoenix version (mix deps): master

### Expected behavior

When `use Phoenix.Endpoint` is called with an `otp_app` that does not exist (or the given module is not configured) an error is raised.

### Actual behavior

There's no error, the default configuration is silently merged and the application just doesn't work.
When starting with `mix phoenix.server` nothing happens and the app sits there infinitely.

This is very confusing and error prone to simple typos in application or module name.

**Comment by romul** [comment]
@chrismccord Have you already started work on this issue?
I was thinking about adding 

```elixir
def from_env!(otp_app, module, defaults) do
  config = Application.fetch_env!(otp_app, module)
  merge(defaults, config)
end
```
to Phoenix.Config and use it [here](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/adapter.ex#L90).
