### ISSUE TITLE
Intermittent failure in controller tests

### ISSUE THREAD

**Issue by barruumrex** [phoenixframework/phoenix#1819]
I’m running into an intermittent failure in my controller tests. The failure doesn’t reproduce when using the same seed. When it fails, it fails for all dispatch actions in all controller tests. I'd give more details, but I can't get the tests to fail consistently in either environment. I'll happily provide more details and dig further, but at this point I need some guidance. 

```
     ** (ArgumentError) argument error
     stacktrace:
       (stdlib) :ets.lookup(BridgeApi.Endpoint, :secret_key_base)
       (bridge_api) lib/phoenix/endpoint.ex:482: BridgeApi.Endpoint.config/2
       (elixir) lib/map.ex:513: Map.update!/3
       (bridge_api) lib/bridge_api/endpoint.ex:1: BridgeApi.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/device_controller_test.exs:17: (test)
```

### Environment

* Elixir: 1.3.1
* Phoenix: 1.2.0
* NodeJS: None
* NPM: None
* Operating system: OSX and Ubuntu

**Comment by josevalim** [comment]
It is failing because the ETS table no longer exists. If the ETS table no longer exists, it is because the endpoint is being shutdown. Do you restart your application as part of your tests? Or do you have children in your test suite that is crashing possibly causing the supervisor to restart?

You can try running the tests with this: `elixir --logger-sasl-reports true -S mix test` and it will print reports every time a supervisor restarts and so on.

**Comment by barruumrex** [comment]
Oh. I was coming at it from the other direction. Assumed that sometimes the table hadn't been created yet. I hadn't even considered it might have been crashing. I even have a likely culprit now. 

Thanks you so much!

**Comment by barsukov** [comment]
I had the same issue just really the same and it took me at least half of the day to figure out what happened, the error message is miserable and did not say anything. I think this issue should be reopened, and the error message must be improved. In my case it was that I missed in mix.es to write in the application section:

```
  def application do
    [mod: {Foo, []},
     extra_applications: [:logger]]
  end
```

The second is to rename `Foo.Application` in my `/lib` to `Foo` and rename the file.
It was umbrella subapp. I hope it will save time for somebody in the future.
But this kind of error message is really confusing.
