### ISSUE TITLE
Templates in subdirectories are not compiled

### ISSUE THREAD

**Issue by lessless** [phoenixframework/phoenix#1825]
### Environment

* Elixir version: Elixir 1.3.1 / Erlang/OTP 18 [erts-7.3]
* Phoenix version (mix deps): locked at 1.2.0 (phoenix) 1bdeb99c
* NodeJS version (node -v): v6.2.2
* NPM version (npm -v): 3.9.5
* Operating system: OS X El Capitan 10.11.5 (15F34)

### Expected behavior

It is possible to render template from relative subdirectories

### Actual behavior
Given following file structure 

```
templates
└── layout
    ├── app.html.eex
    ├── gmaps
    │   ├── acceptance.html.eex
    │   ├── dev.html.eex
    │   └── prod.html.eex
    └── header
        └── regular.html.slim
```
and following contents of the `layout_view.ex`:

```
defmodule App.LayoutView do
  use Ave88.Web, :view
  use Phoenix.View, root: "web/templates"
  #...
end
```

when I try to render `gmaps/dev.html` from the `templates/layout/app.html.eex`:

```
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <%= render "gmaps/dev.html" %>
  </head>
```

there is a following error in the console:

```
[error] #PID<0.383.0> running App.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (Phoenix.Template.UndefinedError) Could not render "gmaps/dev.html" for App.LayoutView, please define a matching clause for render/2 or define a template at "web/templates/layout". The following templates were compiled:

* app.html

Assigns:

%{template_not_found: App.LayoutView}
```

Instead, when I'm trying to enforce subdirectories traversing with  `use Phoenix.View, root: "web/templates",  path:"**/*"` then  `app.html` couldn't be rendered:

```
[error] #PID<0.383.0> running App.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (Phoenix.Template.UndefinedError) Could not render "app.html" for App.LayoutView, please define a matching clause for render/2 or define a template at "web/templates/**/*". The following templates were compiled:

* web/templates/layout/app.html
* web/templates/layout/gmaps/acceptance.html
* web/templates/layout/gmaps/dev.html
* web/templates/layout/gmaps/prod.html
* web/templates/layout/header/regular.html
```

**Comment by josevalim** [comment]
Have you tried setting `:pattern` instead? The `:path` changes something else, in particular, the option above would always include all templates from all views in every view.

**Comment by miskolc** [comment]
What was the fix for this issue?
When I write
`  use Phoenix.View, root: "web/templates", pattern: "**/*"`
I get 

    == Compilation error on file web/views/layout_view.ex ==
    ** (CompileError) web/views/layout_view.ex:3: definitions with multiple clauses and default values require a function head. Instead of:
    
        def foo(:first_clause, b \\ :default) do ... end
        def foo(:second_clause, b) do ... end
    
    one should write:
    
        def foo(a, b \\ :default)
        def foo(:first_clause, b) do ... end
        def foo(:second_clause, b) do ... end
    
    def render/2 has multiple clauses and defines defaults in a clause with a body
        web/views/layout_view.ex:3: (module)
        (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
        (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

**Comment by chrismccord** [comment]
@miskolc try `use Phoenix.View, root: "web/templates", pattern: "*/**"`

If that doesn't work, we need more information, including your directory hierarchy, view modules, phoenix version, etc

**Comment by denispeplin** [comment]
Actually, `use Phoenix.View, root: "web/templates", pattern: "**/*"`  works.
Difference is in the last part: `"**/*"` instead of `"*/**"`.

**Comment by josevalim** [comment]
Can you provide a sample application that reproduces the error?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by suazithustra** [comment]
[meow_umbrella.zip](https://github.com/phoenixframework/phoenix/files/1958180/meow_umbrella.zip)

**Comment by josevalim** [comment]
I have added a better error message to phoenix. A fix in Elixir is coming soon too! Thanks for the app!

**Comment by suazithustra** [comment]
```
def view do
    quote do
        use Phoenix.View, root: "lib/app_web/templates", pattern: "**/*",
                                       namespace: AppWeb
...
```
Thanks 👍
