### ISSUE TITLE
Update RuntimeError for missing root for watchers to reflect deprecation.

### ISSUE THREAD

**Issue by Fahrradflucht** [phoenixframework/phoenix#1826]
### Environment

* Elixir version (elixir -v): `1.3.1`
* Phoenix version (mix deps): `1.2.0`
* NodeJS version (node -v): `6.2.1`
* NPM version (npm -v): `3.10.6`
* Operating system: `OSX 10.11.6`

### Initial setup
1. Setup a new phoenix project. (I only tested with `--no-brunch`
2. Add a watcher with no `cd:` argument.
3. Run `mix phoenix.server`

### Expected behavior
Get an error that watchers need a `cd:` argument and something like:
```
Pass the :cd option at the end of your watcher argument list in config/dev.exs. For examp
le:

    watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
               cd: Path.expand("../", __DIR__)]]
```

### Actual behavior
The runtime error is:
```
** (RuntimeError) please set root: Path.dirname(__DIR__) in your endpoint inside
config/config.exs in order to use code reloading or watchers
```

Adding a root in `config/config.exs` and restarting the server solves the issue, but returns a deprecation warning: `[warn] using the :root endpoint configuration for watchers is deprecated.`

**Comment by josevalim** [comment]
This has been fixed in master, thank you!
