### ISSUE TITLE
Incorrect conn.remote_ip when used behind a load balancer

### ISSUE THREAD

**Issue by jbrowning** [phoenixframework/phoenix#1830]
Phoenix seems to derive the `conn.remote_ip` address from `conn.peer`, which is incorrect when the app is behind a load balancer/proxy or within a Docker environment. Not sure if this is a Phoenix issue or a Plug issue but I figured I should start here. 😃 

### Environment

* Elixir version (elixir -v): 1.3.2
* Phoenix version (mix deps): 1.1.6
* NodeJS version (node -v): v5.4.1
* NPM version (npm -v): 3.8.6
* Operating system: Ubuntu 16.04 LTS

### Expected behavior

Given the header:

```
X-FORWARDED-FOR "96.91.186.3, 172.31.49.124"
```

The `conn.remote_ip` value should be set to `96.91.186.3`, which is the actual client IP address.

### Actual behavior

The `conn.remote_ip` value is set to same value as `conn.peer`, which if run in a Docker container is often the IP of the Docker host.

**Comment by josevalim** [comment]
We don't change based on x-forwarded-for by design because doing so when x-forwarded-for is not actually enabled is a security risk. So you need to implement a plug that will read x-forwarded and do the appropriate changes. Maybe one is even already available!

**Comment by jbrowning** [comment]
Thanks for the super quick reply Jose! I'll work on getting this added to the [Phoenix Behind a Proxy](http://www.phoenixframework.org/docs/serving-your-application-behind-a-proxy) guide.

**Comment by venkatd** [comment]
Hi @jbrowning I believe I'm dealing with the same challenge. What would I need to do in this plug? Thanks!

**Comment by jbrowning** [comment]
@venkatd we ended up going with [plug_x_forwarded_for](https://hex.pm/packages/plug_x_forwarded_for).

**Comment by venkatd** [comment]
Thanks @jbrowning. Newbie question: where did you mount the plug? Was it in the router? If so, would love to see the snippet of how you did it.

Thanks!

**Comment by omin** [comment]
I'm going through the same thing. Just added https://github.com/awetzel/plug_forwarded_peer to fix it.
