### ISSUE TITLE
Garbage files in phoenix 1.2 hex package

### ISSUE THREAD

**Issue by aerosol** [phoenixframework/phoenix#1834]
I assume that once it's published there's not much to be done about it, but perhaps you'd like to know this:

```
$ wget https://repo.hex.pm/tarballs/phoenix-1.2.0.tar
--2016-07-25 12:03:08--  https://repo.hex.pm/tarballs/phoenix-1.2.0.tar
Resolving repo.hex.pm... 151.101.17.5
Connecting to repo.hex.pm|151.101.17.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 174080 (170K) [application/octet-stream]
Saving to: ‘phoenix-1.2.0.tar’

phoenix-1.2.0.tar                                  100%[================================================================================================================>] 170.00K  --.-KB/s    in 0.1s

2016-07-25 12:03:09 (1.31 MB/s) - ‘phoenix-1.2.0.tar’ saved [174080/174080]


12:03:09 hq1@kosmos /tmp/foo
$ tar xvzf phoenix-1.2.0.tar
x VERSION
x CHECKSUM
x metadata.config
x contents.tar.gz

12:03:12 hq1@kosmos /tmp/foo
$ tar xvzf contents.tar.gz

12:05:55 hq1@kosmos /tmp/foo
$ ls **/\#*
lib/phoenix/#controller.ex#                      lib/phoenix/#logger.ex#                          lib/phoenix/#router.ex#                          lib/phoenix/transports/#websocket_serializer.ex#
lib/phoenix/#dynamic_dispatch.ex#                lib/phoenix/#naming.ex#                          lib/phoenix/controller/#pipeline.ex#
```

**Comment by aerosol** [comment]
(it doesn't break phoenix in any way)

**Comment by Gazler** [comment]
It is caused by https://www.emacswiki.org/emacs/AutoSave

**Comment by josevalim** [comment]
@chrismccord should probably edit the releases file to make sure bogus files are removed before. :P

**Comment by chrismccord** [comment]
hrm, I have a global gitignore that should have prevented those autosaves, but computers, how do they work!?

**Comment by Gazler** [comment]
@chrismccord I guess the hex publish task doesn't use your .gitignore though?

**Comment by michalmuskala** [comment]
Should there be a `.hexignore` file?

**Comment by chrismccord** [comment]
Ah right. My git workflow made me not even question what files hex would grab. I'm sure they appeared in the hex publish list, but they are easily missed.

**Comment by ericmj** [comment]
> I'm sure they appeared in the hex publish list, but they are easily missed.

They are indeed :/

> Should there be a .hexignore file?

Possibly. This is also an education problem. It is likely you won't use .hexignore until you are bit by this once and by then you probably already learned to double check the output.

We could also use .gitignore as @Gazler suggested but I am not sure if that will be a good idea in every case.

If you'd like to discuss this further please open on issue on Hex.

**Comment by chrismccord** [comment]
Agree this is an education issue since I should have checked the output. I also don't think gitignore is the way to go because the autosaves are in my global gitignore, not the projects, so hex wouldn't be able to check there. Additionally, I don't want to contribute to yet-another-dot-file, so my preference currently would be to leave hex as is. I'll add a note to the RELEASE.md instructions as josé suggested.

**Comment by aerosol** [comment]
Another one: `deps/phoenix_pubsub/lib/phoenix_pubsub/#pg2_server.ex#`

Would it make sense for hex to use `git ls-files` to obtain the list to be packaged?
