### ISSUE TITLE
Skip copying files with --no-brunch on pheonix.new when --no-html is specified

### ISSUE THREAD

**Issue by kenips** [phoenixframework/phoenix#1835]
On phoenix.new if you pass `--skip-brunch --no-html` static files are still getting copied. This [appears to be by design](https://github.com/phoenixframework/phoenix/blob/90f8b45163a545b264787b73388cb2356d775c3a/installer/lib/phoenix_new.ex#L303). However with both options specified I don't see why static files are needed.

Not sure about being smart and detecting `--no-html` within `copy_static`. I'm happy if `--no-api` is given with more specific documentation on it doing both options above AND not copying static files over.

Happy to submit a PR for either case. Thanks for all the great work again!

**Comment by josevalim** [comment]
From looking at the code it seems it should be fixed. No reason to copy those files if `--no-html` is given.
