### ISSUE TITLE
unable to submit blank date from date_select helper

### ISSUE THREAD

**Issue by justinbkay** [phoenixframework/phoenix#1837]
There is no way to have a form with an optional date using the date_select helper.  I modified the helper to be able to submit a blank date, but Ecto says it is an invalid date.  I thought that empty strings were converted to nil and the field would not be modified.  This might be an Ecto but, but I'm not sure.

On the server the incoming params look like this:

<pre>
<code>
"last_maintained" => %{"day" => "", "month" => "", "year" => ""}
</code>
</pre> 

and the error is invalid date.  The date is not a required field, but is cast in the changeset.

**Comment by chrismccord** [comment]
Please open this on the phoenix_html side and provide relevant information like phoenix and ecto versions. Thanks!
https://github.com/phoenixframework/phoenix_html

**Comment by josevalim** [comment]
@justinbkay you can open up an issue directly in Ecto. :) But please include the Ecto version.
