### ISSUE TITLE
Instructions for adding bootstrap Javascript to Phoenix app

### ISSUE THREAD

**Issue by marick** [phoenixframework/phoenix#1839]
I wanted to add the Javascript part of bootstrap. As a newbie to the JS ecosystem and brunch, I had a fair amount of trouble coming up with https://github.com/marick/eecrit/commit/699c0e83993e9e940144b3d4a60d0b0afe04fa18 I'd like to submit a pull request to make it easier for the next person. How?

* To docs? Which one?
* Sample files to live in the generated app (like `app.sample.bootstrap.js`)?
* Comments in the source files? (But can `package.json` have comments?)

### Environment
* Phoenix version (mix deps): 1.2.0

**Comment by chrismccord** [comment]
This would be an addition to the phoenix guides, but we may not be keeping bootstrap with Phoenix 1.3, so I would prefer to hold on this one even for the guides. That said, if the brunch guides on phoenixframework.org could b improved where they would help this kind of question, then we're definitely open to help! Thanks!

**Comment by josevalim** [comment]
For completeness, I believe you can also download jquery and put it in vendor (and that would be it). It is interesting to know though you can depend on it via NPM.
