### ISSUE TITLE
phoenix.new --database sqlite results in invalid dependencies

### ISSUE THREAD

**Issue by blutack** [phoenixframework/phoenix#1843]
Sorry if this is the wrong place to report this - I'm not sure whether it's an issue with Ecto or the sqlite_ecto library but I guess it's Phoenix setting the dependencies.

I ran ```mix phoenix.new hello_phoenix --database sqlite``` and the resulting phoenix app will not start due to unsatisfactory dependencies.

I do understand that SQLite is not the recommended option for new Phoenix projects but it's an option in the generator so it would be good if it worked (if for nothing else than to save having to fire up postgres for a playaround project).

### Environment

* Elixir version (elixir -v):
Erlang/OTP 19
Elixir 1.3.2
* Phoenix version (mix deps): 1.2.0 (can't list from project with broken dependencies though)
* NodeJS version (node -v): 6.3.1
* NPM version (npm -v): 3.10.3
* Operating system: OSX

### Expected behavior
```mix phoenix.server``` works.

### Actual behavior
```
$ mix phoenix.server
Unchecked dependencies for environment dev:
* phoenix_live_reload (Hex package)
  the dependency is not available, run "mix deps.get"
---SNIP---
** (Mix) Can't continue due to errors on dependencies
```

```
$ mix deps.get
Running dependency resolution

Failed to use "ecto" (versions 2.0.0-beta.0 to 2.0.3) because
  phoenix_ecto (version 3.0.0) requires ~> 2.0.0-rc
  sqlite_ecto (versions 0.0.2 and 0.1.0) requires ~> 0.11


Failed to use "ecto" (versions 2.0.0-beta.0 to 2.0.3) because
  phoenix_ecto (version 3.0.0) requires ~> 2.0.0-rc
  sqlite_ecto (version 0.2.0) requires ~> 0.12.1


Failed to use "ecto" (versions 2.0.0-beta.0 to 2.0.3) because
  phoenix_ecto (version 3.0.0) requires ~> 2.0.0-rc
  sqlite_ecto (version 0.3.0) requires ~> 0.13.1


Failed to use "ecto" (versions 2.0.0-beta.0 to 2.0.3) because
  phoenix_ecto (version 3.0.0) requires ~> 2.0.0-rc
  sqlite_ecto (versions 0.4.0 and 0.4.1) requires ~> 0.14.0


Failed to use "ecto" (versions 2.0.0-beta.0 to 2.0.3) because
  phoenix_ecto (version 3.0.0) requires ~> 2.0.0-rc
  sqlite_ecto (version 0.5.0) requires ~> 0.15.0


Failed to use "ecto" (versions 2.0.0-beta.0 to 2.0.3) because
  phoenix_ecto (version 3.0.0) requires ~> 2.0.0-rc
  sqlite_ecto (version 0.6.0) requires ~> 0.16.0


Failed to use "ecto" (versions 2.0.0-beta.0 to 2.0.3) because
  phoenix_ecto (version 3.0.0) requires ~> 2.0.0-rc
  sqlite_ecto (versions 1.0.0 to 1.0.2) requires ~> 1.0


Failed to use "ecto" (versions 2.0.0-beta.0 to 2.0.3) because
  phoenix_ecto (version 3.0.0) requires ~> 2.0.0-rc
  sqlite_ecto (version 1.1.0) requires ~> 1.1

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

**Comment by blutack** [comment]
See also https://github.com/jazzyb/sqlite_ecto/issues/47

**Comment by ericmj** [comment]
Nothing phoenix can do about this except drop the sqlite option to --database until the sqlite_ecto project is updated.

**Comment by blutack** [comment]
I thought that might be the case - it does look like sqlite_ecto is a ways off reaching that point.

**Comment by josevalim** [comment]
Yes, we should remove support for such option.
