### ISSUE TITLE
"App.Endpoint.path/1 is undefined" once a CompileError happens; no live reload

### ISSUE THREAD

**Issue by skosch** [phoenixframework/phoenix#1845]
Thank you for a wonderful framework! :tada:
If this belongs in `phoenix_live_reload`, I'm happy to delete and re-post this.

### Environment
* Elixir version (elixir -v): 1.3.1
* Phoenix version (mix deps): 1.2.0, live_reload is at 1.0.5
* NodeJS version (node -v): 5.7.0
* NPM version (npm -v): 3.6.0
* Operating system: Linux, 64bit
* Webpack/HMR setup: mostly identical to http://mikker.github.io/2016/02/04/updated-phoenix-webpack-react-setup.html – this may be relevant, although I don't see how it could be

### Expected behavior

When introducing syntax errors, I expect `CompileErrors` to show up in my console. Upon fixing those syntax errors, I expect live reload to kick in, recompile, and the app should work again.

### Actual behavior

Live reload works perfectly fine, as long as I'm making changes that compile.

Introducing a syntax error – e.g. deleting a bracket somewhere – results in an (expected) error à la
```
== Compilation error on file web/resolver/reviewer.ex ==
** (SyntaxError) web/resolver/reviewer.ex:640: unexpected token: "end". "(" starting at line 23 is missing terminator ")"
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

[error] #PID<0.5898.0> running App.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /reviewers/2016/1234
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function App.Endpoint.path/1 is undefined (module App.Endpoint is not available)
        (app) App.Endpoint.path("/phoenix/live_reload/frame")
        (phoenix_live_reload) lib/phoenix_live_reload/live_reloader.ex:115: Phoenix.LiveReloader.reload_assets_tag/1
        (phoenix_live_reload) lib/phoenix_live_reload/live_reloader.ex:97: anonymous fn/1 in Phoenix.LiveReloader.before_send_inject_reloader/1
        (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug) lib/plug/conn.ex:909: Plug.Conn.run_before_send/2
        (plug) lib/plug/conn.ex:355: Plug.Conn.send_resp/1
        (phoenix) lib/phoenix/code_reloader.ex:50: Phoenix.CodeReloader.call/2
        (app) lib/app/endpoint.ex:1: App.Endpoint.phoenix_pipeline/1
        (app) lib/plug/debugger.ex:93: App.Endpoint."call (overridable 3)"/2
        (app) lib/app/endpoint.ex:1: App.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```
Fixing the file and saving it doesn't trigger *anything* now; I have to restart `mix phoenix.server` for everything to work again. Reloading the (now dead) page in the browser merely leads to the error above being re-printed in the terminal (or a variation of it, say, `call/2` or some other Endpoint function being undefined).

Is this a misconfiguration on my part? Why does the Endpoint die, and why doesn't it restart by itself?

P.S. I should note that as far as I can tell, other errors don't cause this problem (say, Ecto not finding a column etc.)

**Comment by josevalim** [comment]
Can you provide an app that reproduces this particular error so we can further investigate it?

**Comment by skosch** [comment]
Thanks @josevalim! Turns out, I'm now pretty sure this is due to the behaviour of [Absinthe](https://github.com/absinthe-graphql/absinthe), so I'm retracting my complaints – sorry for the noise :)
