### ISSUE TITLE
Generated "invalid attributes" test for model with no attributes incorrectly fails

### ISSUE THREAD

**Issue by folz** [phoenixframework/phoenix#1849]
* Elixir version (elixir -v): 1.3.1
* Phoenix version (mix deps): 1.2.0
* NodeJS version (node -v): v5.10.1
* NPM version (npm -v): 3.8.6
* Operating system: Linux Mint 17.3

### Steps to reproduce

In a new Phoenix project, generate a model with no attributes, e.g.

`mix phoenix.gen.model Thing things`

Then try to test it:

`mix test`

### Expected behavior

Mix will pass all generated tests.

### Actual behavior

Mix fails on the "invalid attributes" test because an empty struct is a valid changeset for models with no attributes.

**Comment by codyjroberts** [comment]
Similar issue with `mix phoenix.gen.json`.  The `put` test below fails when a model is created with valid attrs.  Test passes as expected when a non empty model is created and 'valid' invalid attributes are supplied.

https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phoenix.gen.json/controller_test.exs#L48-L52
```elixir
test "does not update chosen resource and renders errors when data is invalid", %{conn: conn} do
  <%= singular %> = Repo.insert! %<%= alias %>{}
  conn = put conn, <%= singular %>_path(conn, :update, <%= singular %>), <%= singular %>: @invalid_attrs
  assert json_response(conn, 422)["errors"] != %{}
end
```

How would we go about determining the types of a generated model's attributes?

**Comment by Gazler** [comment]
Since `mix phoenix.gen.json` and `mix phoenix.gen.html` are designed to be learning tools for getting started quickly. Perhaps the simplest solution would be to require attributes to be present when running the generator tasks.

**Comment by codyjroberts** [comment]
To be more explicit, the issue I presented still exists when giving attributes to the generator.

**Comment by folz** [comment]
I sometimes use bare models with no attributes when I'm starting a project
or new feature, as a placeholder of sorts.

Maybe a --bare flag could distinguish between accidentally forgetting
attributes and deciding to create a bare model?

**Comment by chrismccord** [comment]
I am 👎 on a bare flag because we intentionally avoid sophistication in the generators so we can promote their use as learning tools. @codyjroberts If the problem is still present when giving attributes to the generator, can you share the command you ran, the generated test code, and what is failing?

**Comment by codyjroberts** [comment]
Sorry for the delay.  I found it via `ja_serializer` and here is that issue for reference https://github.com/AgilionApps/ja_serializer/issues/149.

Reproduce with
```
mix phoenix.new --no-brunch gen_json_example
cd gen_json_example
mix phoenix.gen.json Todo todos title:string description:string
```

Add `resources "/todos", TodoController, except: [:new, :edit]` to `router.ex` in the api pipeline.

```elixir
#test/controllers/todo_controller_test.exs

49   test "does not update chosen resource and renders errors when data is invalid", %{conn: conn} do                                                                                                                                                                  
50     todo = Repo.insert! %Todo{}                                                                                                                                                                                                                               
52     conn = put conn, todo_path(conn, :update, todo), todo: @invalid_attrs                                                                                                                                                                                           
53     assert json_response(conn, 422)["errors"] != %{}                                                                                                                                                                                                                
54   end 
```

`mix test ./test/controllers/todo_controller_test.exs:49` passes

when changed to

```elixir
test "does not update chosen resource and renders errors when data is invalid", %{conn: conn} do
  todo = %Todo{title: "fix json generator", description: "generates false positive"}
  |> Repo.insert!                                                                                                                                
  conn = put conn, todo_path(conn, :update, todo), todo: @invalid_attrs
  assert json_response(conn, 422)["errors"] != %{}                                                                                                                            
end 
```

The test fails with

```
test/controllers/todo_controller_test.exs:49                                                                                                                                                                                                                   
** (RuntimeError) expected response with status 422, got: 200, with body:                                                                                                                                                                                      
{"data":{"title":"fix json generator","id":7,"description":"generates false positive"}}                                                                                                                                                                        
stacktrace:                                                                                                                                                                                                                                                    
(phoenix) lib/phoenix/test/conn_test.ex:362: Phoenix.ConnTest.response/2                                                                                                                                                                                     
(phoenix) lib/phoenix/test/conn_test.ex:408: Phoenix.ConnTest.json_response/2                                                                                                                                                                                
test/controllers/todo_controller_test.exs:53: (test)
```

The generator creates an empty map for `@invalid_attrs`.  When `@invalid_attrs` is a map with actual invalid attributes, e.g. `%Todo{title: -1, description: "generates false positive"}`, then the test passes as intended.

**Comment by codyjroberts** [comment]
Hey @chrismccord, it looks like you're working on some new generators so I'm not sure how relevant this is now.  If it is, I had success creating a function similar to `Mix.Phoenix.type_to_default/1` but instead generating invalid attributes.

You can see the diff's [here](https://github.com/codyjroberts/phoenix/commit/a7a4bffb7c65d8802c558752b3209a05b0f4af2d)

**Comment by chrismccord** [comment]
The new generates will revisit this area so this is no longer relevant. Thanks for reporting!
