### ISSUE TITLE
How to log response for every request??

### ISSUE THREAD

**Issue by youthy** [phoenixframework/phoenix#1862]
I want log every response body but I don't want to change code in deps.
Is there another proper, elegant way?
```
/cowboy/conn.ex
  def send_resp(req, status, headers, body) do
    IO.puts "#{inspect body, pretty: true}"
    {:ok, req} = Request.reply(status, headers, body, req)
    {:ok, nil, req}
  end
```
or
```
phoenix/view.ex
defp encode(content, template) do
    IO.puts "#{inspect content, pretty: true}"
    if encoder = Template.format_encoder(template) do
      encoder.encode_to_iodata!(content)
    else
      content
    end
  end
```

**Comment by josevalim** [comment]
There is a Plug.Conn.register_before_send callback you can use for that. See how Plug.Logger is implemented. Also, please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
