### ISSUE TITLE
Generated mix.exs db creation and migrations for tests

### ISSUE THREAD

**Issue by nathany** [phoenixframework/phoenix#1864]
### Environment

* Elixir version (elixir -v): Elixir 1.3.1
* Phoenix version (mix deps): 1.2.1

### Expected behavior

❯ mix phoenix.new MyApp

Expecting aliases to setup "mix test" to create and migrate the database as described here:
https://github.com/phoenixframework/phoenix/issues/1564#issuecomment-194957150

```
"test": ["ecto.create --quiet", "ecto.migrate", "test"]
```

Related: https://discuss.circleci.com/t/add-support-for-elixir-erlang/2215/20

### Actual behavior

The generated mix.exs file only contains:

```elixir
defp aliases do
  ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
  "ecto.reset": ["ecto.drop", "ecto.setup"]]
end
```

**Comment by josevalim** [comment]
That's what we generate on master: https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/mix.exs#L56 :)

**Comment by nathany** [comment]
👍 thanks @josevalim
