### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by Jo0go** [phoenixframework/phoenix#1866]
Could anyone help me figure this out?

I want to be able to upload files, and in particular images, and store them locally. I'm aware of `plug Plug.Static`, but isn't it for static assets? Whereas  uploaded files aren't static. 

1) Also, I already have this in my application generated automatically:
```
    # lib/my_app/endpoint.ex
    plug Plug.Static,
      at: "/", from: :my_app, gzip: false,
      only: ~w(css fonts images js favicon.ico robots.txt)
```
Indeed, it's for static assets. How should I go about uploaded files? I want to store them in a different directory. Not necessarily outside of my project, but anywhere where it won't be compiled in the production beam file by default. 

2) Given an uploaded file name, I want to be able to get its full url/path from a) controller b) view. How can I do that?

**Comment by chrismccord** [comment]
Please follow the issue template and submit support requests to the mailing list.  We reserve the issue tracker for actual issues. Thanks!

**Comment by Jo0go** [comment]
@chrismccord Ok!!!!!!!!!!!
