### ISSUE TITLE
Enhancement:  Watcher is not restarted if it dies.

### ISSUE THREAD

**Issue by OvermindDL1** [phoenixframework/phoenix#1870]
While developing sometimes Brunch can die (missing a comma in the config or something), which then kills the static file reloading, which can cause a few hours of head-scratching while wondering why my CSS is not applying to the elements that I think it should be (of which restarting the server fixes it, but then can take a minute).  Instead of just being a ` System.cmd(cmd, args, merged_opts)` at https://github.com/phoenixframework/phoenix/blob/b4d14eb9dd8c358afca0616ede6bb43409c5ada0/lib/phoenix/endpoint/watcher.ex#L15 a port that can watch when the remote connection dies and as such auto-restart it would be a much nicer experience.  If the file watcher for the rest of the phoenix source also watched the files in the root directory (package.json, brunch-config.js, elm-package.json, etc...) then if the watcher dies and it auto-restarts it and it dies again in, say, 10 seconds or less then it waits for one of those files to update again else it defaults to an exponential backup (or both) then that would be fantastic.

### Environment

* Elixir version:  Elixir 1.3.1
* Phoenix version:  1.2.0
* NodeJS version:  v6.2.0
* NPM version:  3.8.9
* Operating system:  Win 10

### Expected behavior

Watchers auto-restart when they die

### Actual behavior

Watcher stays dead if it dies.

**Comment by josevalim** [comment]
It doesn't need to be a port nor anything that complex. We could instead observe the status code from System.cmd and wait for x seconds before existing with non-normal reason.

**Comment by OvermindDL1** [comment]
Ahh right, System.cmd is blocking, that would be quite easy then.
