### ISSUE TITLE
Add mix task to clean older versions of assets

### ISSUE THREAD

**Issue by aaronjensen** [phoenixframework/phoenix#1876]
## Problem

Depending on your method of deployment, asset directories can either grow indefinitely or be emptied unsafely and prematurely.

This will lead to either running out of disk space (and then needing to do an unsafe purge of some sort) or users not being served older assets that they may need while running an older version of a single page app with dynamic asset loading.

Here are two scenarios where the strategy of deploying an entirely new priv/static directory is broken:

### Single Page App

1. User A loads Version A of a SPA and downloads Asset A1.
1. You deploy Version B of your SPA which includes Asset B1 and B2.
1. User B navigates to another "page" in your single page app, which triggers a load of Asset A2. 1. They get a 404 because you are currently serving Version B which does not include old assets.

### Regular apps (narrow window)

1. User A loads Version A of your app
1. Just as they're loading it, you're deploying Version B which includes a new logo file, Logo B.
1. User A's browser tries to load Logo A, but it's 404 because only Logo B is available.

Both of these scenarios could be mitigated with a CDN as long as someone has loaded the assets at least once. We cannot rely on that, however. 

Both scenarios could also be mitigated by uploading and serving assets from something like S3, but that should be an unnecessary piece of infrastructure, not a necessary one.

See initial discussion here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/phoenix-core/QRU-WUogUyI/ZG13JK3xDQAJ

## How does Rails solve this?

Rails solves this by storing more information in their manifest, specifically:

1. Old files
2. mtimes of those files

They then provide a rake task that can delete anything older than the past N versions as long as it is also older than T seconds ago.

## Proposed Solution

- [ ] Mimic Rails/Sprocket's manifest file format, at least the parts that we need:

    ```json
    {
      "files": {
        "application-8c357e6c2c428e1cb27cf646c6882f7e79326fbb63dc6602997f42d12f273ede.js": {
          "logical_path": "application.js",
          "mtime": "2016-08-21T07:55:52-07:00",
          "size": 369053,
          "digest": "8c357e6c2c428e1cb27cf646c6882f7e79326fbb63dc6602997f42d12f273ede",
          "integrity": "sha256-jDV+bCxCjhyyfPZGxogvfnkyb7tj3GYCmX9C0S8nPt4="
        },
        "application-af04b226fd7202dfc532ce7aedb95a0128277937e90d3b3a3d35e1cce9e16886.css": {
          "logical_path": "application.css",
          "mtime": "2016-08-21T07:55:43-07:00",
          "size": 703,
          "digest": "af04b226fd7202dfc532ce7aedb95a0128277937e90d3b3a3d35e1cce9e16886",
          "integrity": "sha256-rwSyJv1yAt/FMs567blaASgneTfpDTs6PTXhzOnhaIY="
        },
        "application-b2f29fb423b1f5b2e837bc5dfedb3b6e8d934d82b943303be59d6c41cccd2136.js": {
          "logical_path": "application.js",
          "mtime": "2016-08-21T07:58:01-07:00",
          "size": 369072,
          "digest": "b2f29fb423b1f5b2e837bc5dfedb3b6e8d934d82b943303be59d6c41cccd2136",
          "integrity": "sha256-svKftCOx9bLoN7xd/ts7bo2TTYK5QzA75Z1sQczNITY="
        }
      },
      "assets": {
        "application.js": "application-b2f29fb423b1f5b2e837bc5dfedb3b6e8d934d82b943303be59d6c41cccd2136.js",
        "application.css": "application-af04b226fd7202dfc532ce7aedb95a0128277937e90d3b3a3d35e1cce9e16886.css"
      }
    }
    ```

    Note that `integrity` is deprecated and will be removed. 

- [ ] Provide a new mix task:

    ```bash
    mix phoenix.digest.clean [--keep N] [--age T]
    ```

**Comment by josevalim** [comment]
Perfect, thank you! I would do the following changes to the manifest:

  1. Include a version
  2. Remove integrity (as you mentioned)
  3. Rename "assets" to "latest", "files" to "digests"
  4. Keep mtime as an integer

So it would look like:

```json
{
  "digests": {
    "application-8c357e6c2c428e1cb27cf646c6882f7e79326fbb63dc6602997f42d12f273ede.js": {
      "logical_path": "application.js",
      "mtime": 32132171,
      "size": 369053,
      "digest": "8c357e6c2c428e1cb27cf646c6882f7e79326fbb63dc6602997f42d12f273ede"
    },
    "application-af04b226fd7202dfc532ce7aedb95a0128277937e90d3b3a3d35e1cce9e16886.css": {
      "logical_path": "application.css",
      "mtime": 32132171,
      "size": 703,
      "digest": "af04b226fd7202dfc532ce7aedb95a0128277937e90d3b3a3d35e1cce9e16886"
    },
    "application-b2f29fb423b1f5b2e837bc5dfedb3b6e8d934d82b943303be59d6c41cccd2136.js": {
      "logical_path": "application.js",
      "mtime": 32132171,
      "size": 369072,
      "digest": "b2f29fb423b1f5b2e837bc5dfedb3b6e8d934d82b943303be59d6c41cccd2136"
    }
  },
  "latest": {
    "application.js": "application-b2f29fb423b1f5b2e837bc5dfedb3b6e8d934d82b943303be59d6c41cccd2136.js",
    "application.css": "application-af04b226fd7202dfc532ce7aedb95a0128277937e90d3b3a3d35e1cce9e16886.css"
  },
  "version": 1
}
```

The "latest" bit is the manifest we have today. It is always built from scratch. The "digests" is the one we will add and we will never remove data from it between runs (unless we run "phoenix.digest.clean").

**Comment by RobinClowers** [comment]
@josevalim I'm going to take a crack at implementing this (I work with @aaronjensen), and I just wanted to clarify something. Is that version meant to be the version of the manifest schema (so it would be hard coded to 1?) or did you mean it to be the version of the app manifest, in which case it would increment every time you run the digest task?

**Comment by josevalim** [comment]
Yes, the manifest version, hardcoded to 1!

**Comment by josevalim** [comment]
Amazing work @RobinClowers! Thanks everyone else who reviewed and provided comments! :heart:
