### ISSUE TITLE
In Docker, asset changes cause reload, template changes don't

### ISSUE THREAD

**Issue by amencarini** [phoenixframework/phoenix#1882]
### Environment

* Elixir version: 1.3.2 
* Phoenix version: 1.2.1
* NodeJS version: 6.4.0
* NPM version: 3.10.3
* Operating system: OS X 10.11.6

I'm running Phoenix in a Docker container: Docker for Mac 1.12.0-a, Debian Jessie based image. I've mounted a volume on the container.

### Expected behavior

When I change a view or template on the host machine, the page gets automatically reloaded.
When I change a template inside of Docker, the page gets automatically reloaded.
When I change a JavaScript file on the host machine, the page gets automatically reloaded.

### Actual behavior

When I change a view or template on the host machine, **_the page does not get automatically reloaded_**.
When I change a template inside of Docker, the page gets automatically reloaded.
When I change a JavaScript file on the host machine, the page gets automatically reloaded.

**Comment by chrismccord** [comment]
This sounds like a known issue with shared volumes between the host and container, which we unfortunately don't have a fix for due to mismatched ctimes/mtimes. You can search the issues list for more info. Thanks!

**Comment by amencarini** [comment]
Sorry about that, the only reference I found seemed related to Vagrant so I thought it wouldn't apply. Would it be worth raising this with the Docker people?

**Comment by josevalim** [comment]
@amencarini here is what I would try the following. Inside your Docker container, start IEx and run:

    File.stat("path/to/some/file/on/host").mtime

Then change the file in the host system and run the command above again to notice if the mtime changed or it is the same:

    File.stat("path/to/some/file/on/host").mtime

After that, perform the same steps again but using bash and the `stat` syscall:

    stat path/to/some/file/on/host

I think this will help us figure out where the mtime changes are being lost.

It may also be a general compilation issue. Elixir uses mtimes to know if files should change, so if you are compiling files into the container, it may change all timestamps in a way Elixir always thinks the code is up to date. Running somthing like `mix compile --force` would fix it.

**Comment by amencarini** [comment]
@josevalim I tried your suggestions:

- `File.stat("path/to/some/file/on/host")` picks up the changes; 
- `stat path/to/some/file/on/host` picks up the changes. 
- It does not seem like `mix compile --force` is helping with the auto-reloading.

Not sure if this is of interest, but as an additional bit of info, `mix compile --force` has this behaviour:
- I make a change, save, reload the page, the change shows.
- I make a change, save, run `mix compile --force`, reload the page, the change _does not show_.
- I then make a change, save, reload the page, and changes start showing again as normal (minus the autoreload).

Another thing I noticed, again, not sure if related: if I modify templates with no browser open on the page, the compilation on save is not reported by the logs.

Also, the Docker instance logs the following: 

```
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
```

This output does not appear on my host, but I'm not sure if this is related to Node.

**Comment by josevalim** [comment]
> I make a change, save, run mix compile --force, reload the page, the change does not show.

This is not going to work because if you run `mix compile --force`, another process will pick up the changes and not your Phoenix server.

>  if I modify templates with no browser open on the page, the compilation on save is not reported by the logs

Phoenix does not have recompilation on save. If you have recompilation on save from an editor, that's the one interfering with Phoenix, because your editor is recompiling the code and not allowing Phoenix to do so .

**Comment by amencarini** [comment]
Got it. Thanks for the time guys, and let me know if you want me to run more tests.

**Comment by josevalim** [comment]
@amencarini does the tips above fix your workflow? Was it missing changes because an editor was picking them up or something? :)

**Comment by amencarini** [comment]
No, I don't have recompilation on save, so the "problem" persists (more of an annoyance really).
