### ISSUE TITLE
Brunch config issue

### ISSUE THREAD

**Issue by kapilTewari** [phoenixframework/phoenix#1889]
Hi! I have admin folder in web/static/js and web/static/css. Where I keep my admin scripts and styles separate. How can I set brunch to compile/build my admin styles and javascripts to separate admin_style.css and admin_script.js files, not in app.css and app.js file. I just can't understand how to do it with brunch.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
