### ISSUE TITLE
phoenix.gen.{html,json,model} generates invalid module name when app name ends with `_[0-9]+`

### ISSUE THREAD

**Issue by utkarshkukreti** [phoenixframework/phoenix#1891]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.3.2
```
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 6.2.1
* NPM version (npm -v): 3.9.3
* Operating system: Mac OSX 10.11

### Steps

```
$ mix phoenix.new foo_1 --no-brunch
$ cd foo_1
$ mix phoenix.gen.html Post posts title:string
$ vim web/router.ex # add the requested line to `web/router.ex`
$ mix compile
```

### Expected behavior

The app should compile.

### Actual behavior

```
$ mix compile
Compiling 15 files (.ex)

== Compilation error on file web/models/post.ex ==
** (CompileError) web/models/post.ex:2: module Foo_1.Web is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    web/models/post.ex:2: Foo_1.Post (module)
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

$ head web/models/post.ex
defmodule Foo_1.Post do
  use Foo_1.Web, :model

  schema "posts" do
    field :title, :string

    timestamps()
  end

  @doc """

$ head web/web.ex
defmodule Foo1.Web do
  @moduledoc """
  A module that keeps using definitions for controllers,
  views and so on.

  This can be used in your application as:

      use Foo1.Web, :controller
      use Foo1.Web, :view
```

The same thing happens with `phoenix.gen.json` and `phoenix.gen.model`.

### Notes

I think the problem is with the generators using [`Mix.Phoenix.base/0`](https://github.com/phoenixframework/phoenix/blob/3c4a4ef17ec0835ef685a0bb75e8e0550deeaf30/lib/mix/phoenix.ex#L135-L149) which converts `foo_1` to `Foo_1` while `phoenix.new` generates modules starting with `Foo1` for an app named `foo_1`.

```
iex(1)> Phoenix.Naming.camelize "foo_1"
"Foo_1"
```

**Comment by shhavel** [comment]
@utkarshkukreti 
I think it was recently fixed - https://github.com/phoenixframework/phoenix/commit/94344be3421c34ac316147e3d2d3414e1e74c67d
Thanks

**Comment by utkarshkukreti** [comment]
@shhavel thanks! I checked the open issues/pull requests and closed issues but probably missed closed pull requests.
