### ISSUE TITLE
Consider dynamic check_origin

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1895]
Would support something like mfa style config, for example:

```
check_origin: {MyApp.Accounts, :allowed_hosts, []}
```

//cc @josevalim

**Comment by josevalim** [comment]
Sounds good!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by chrismccord** [comment]
Holding off on this one. tldr is use cases that require fine-grained origin checking will likely need more than this and will be best suited by their own check origin plug handling

**Comment by josevalim** [comment]
Keep in mind a custom plug is not going to work for channels. :)

**Comment by OvermindDL1** [comment]
> Keep in mind a custom plug is not going to work for channels. :)

/side-note:  Would love plugs on channels.
