### ISSUE TITLE
Can't access config value from inside the config file

### ISSUE THREAD

**Issue by EHadoux** [phoenixframework/phoenix#1897]
Hi, 

I can't access a value set by ```config/3``` in the same file.

Take any config file, say ```config.exs```.
Go after a config, say
```
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]
```

Put ```IO.puts(Application.get_env(:logger, :console)[:format])```.
At compilation, a String should appear, instead, ```Application.get_env(:logger, :console)[:format]``` returns nil.

Actually, I'd like to define my API keys in a secret config file, I don't want to rely on ENV variables (at the moment).

### Environment

* Elixir version (elixir -v): 1.3.2
* Phoenix version (mix dips): 1.2.1
* Operating system: Mac

I hope it's the good place.
Thanks!

**Comment by josevalim** [comment]
You would need to store that in a variable. configuration is only stored after the whole file is read.

**Comment by EHadoux** [comment]
Ok, I see.
Thanks!

**Comment by arsduo** [comment]
@EHadoux how did you end up solving the problem? I'm running into the same issue (setting the Redis URL in dev.exs, test.exs, etc. and then wanting to reference it later for other configuration in config.exs).

**Comment by SLOBYYYY** [comment]
I also need this. Did anyone figure it out?

**Comment by PJUllrich** [comment]
I had a similar problem and my solution was:
```elixir
format = "$time $metadata[$level] $message\n"

config :logger, :console, 
  format: format
```
After declaring the `format` variable you can reuse it in different `config`s
