### ISSUE TITLE
Watcher: run bash

### ISSUE THREAD

**Issue by theduke** [phoenixframework/phoenix#1899]

**Comment by josevalim** [comment]
If you execute:

```bash
sh "echo test"
```

you will get the same error:

```bash
sh: echo test: No such file or directory
```

You probably want:

```elixir
sh: ["-c", "echo test"]
```

Also, please use the mailing list or StackOverflow for questions/help the next time around, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

**Comment by theduke** [comment]
@josevalim  thanks for the swift reply, I had actually figured it out.

Also, regarding mailing list: understood. ^^
