### ISSUE TITLE
Phoenix.ChannelTest __stringify__/1 fails when the value is a struct (like Ecto.DateTime)

### ISSUE THREAD

**Issue by Ivor** [phoenixframework/phoenix#1904]
In testing channels, if you `push` a message that contains structs it fails since the structs might not implement Enumarable and `__stringify__` assumes that anything that matches `%{}` does implement it. 

```
  def push(socket, event, payload \\ %{}) do
    ref = make_ref()
    send(socket.channel_pid,
         %Message{event: event, topic: socket.topic, ref: ref, payload: __stringify__(payload)})
    ref
  end
```

```
  def __stringify__(%{} = params),
    do: Enum.into(params, %{}, &stringify_kv/1)
  def __stringify__(other),
    do: other

  defp stringify_kv({k, v}),
    do: {to_string(k), __stringify__(v)}
```

The non-testing PubSub works fine for publishing payloads like this. Perhaps `__stringify__` should check if params has a `to_string` function and call that and fall back to `Enum.into` if it doesn't?

**Comment by chrismccord** [comment]
> The non-testing PubSub works fine for publishing payloads like this.

Can you describe a little more how this works? The issue is you are pushing a struct from the client, to the server and it will need to be encoded/decoded. So my first recommendation would be to not push structs to the server unless they can be encoded, but I don't believe we pass the channel tests thru any specific encoder, so maybe we should allow a configurable serializer.

**Comment by Ivor** [comment]
The specific case I have at the moment broadcasts a model instance that has been converted to a map, however, some of the values in the map are `Ecto.DateTime` values. This doesn't seem to bother the functioning of the application as my messages reach their destination as expected when running the app. However, if I `push` the same value to the socket in the test I get:

```
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for #Ecto.DateTime<2016-09-06 11:46:14>
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:116: Enumerable.reduce/3
       (elixir) lib/enum.ex:1627: Enum.reduce/3
       (elixir) lib/enum.ex:1121: Enum.into/4
       (phoenix) lib/phoenix/test/channel_test.ex:548: Phoenix.ChannelTest.stringify_kv/1
       (elixir) lib/enum.ex:1115: anonymous fn/4 in Enum.into/3
       (stdlib) lists.erl:1263: :lists.foldl/3
       (elixir) lib/enum.ex:1121: Enum.into/4
       (phoenix) lib/phoenix/test/channel_test.ex:352: Phoenix.ChannelTest.push/3
``` 

Does something similar to __stringify__ happen in the non-test version? Perhaps using the same serializer the non-test PubSub uses will work. I am a little out of my depth here.

**Comment by chrismccord** [comment]
What are your channel clients in the production version? Browser? Other Elixir apps? `push` to to test messages pushed from a remote client, so there is necessary encoding that's going to happen. For example, if you did have an Elixir Channels client in prod, it would have to encode the Ecto.Datetime to something that could be decoded by the transport. I think we're missing something in between test and prod. Are you sure you're not confusing `push` with normal message sending that can be picked up in `handle_info` in the channel?

**Comment by josevalim** [comment]
@chrismccord the actual integration flow would encode to json and from json. I think doing so in testing would be wasteful though. The best suggestion I have right now is to stop stringifying if we see a struct. We should only traverse maps and lists and not all data types. Probably adding one extra clause to the stringify function.

**Comment by chrismccord** [comment]
@josevalim in that case, we shouldn't promote pushing structs though right? The issue is for proper testing, you shouldn't push up anything that can't be properly encoded and decode. If we passively allow it, we're allowing data that can't happen in prod

**Comment by josevalim** [comment]
@chrismccord any data could happen in prod as long as you implement the Poison protocols for it. Doesn't latest Poison support Elixir datetime types? There is also custom protocols. So we should either allow everything and trust the user or call encode/decode using a chosen protocol.

**Comment by chrismccord** [comment]
> So we should either allow everything and trust the user or call encode/decode using a chosen protocol.

My vote is we allow the user to choose a transport serializer, and we default to JSON. This would allow us to remove `__stringify__` and match up with what you expect in prod.

**Comment by josevalim** [comment]
> My vote is we allow the user to choose a transport serializer, and we default to JSON. This would allow us to remove __stringify__ and match up with what you expect in prod.

FWIW, we chose the other option for Plug. But there are complications there we do not have in channels, such as file upload. I am fine with any of the solutions above for channels.

**Comment by Ivor** [comment]
Thank you both for taking the time to discuss this. I really appreciate it.

**Comment by AlejandroHuerta** [comment]
Going with the limitations of stringify is there any plans for having those functions also work with list? Currently it simply passes a list as is. So if you have a list of maps those maps do not get stringified. It took me awhile to figure out the issue but it;s not difficult to get around.
