### ISSUE TITLE
Documentation mix phoenix.gen.channel generates error message

### ISSUE THREAD

**Issue by COLABORATI** [phoenixframework/phoenix#1907]
The section about `phoenix.gen.channel` in the [Mix Tasks](http://www.phoenixframework.org/docs/mix-tasks#section--mix-phoenix-gen-channel-) Documentation contains this example command:
```
$ mix phoenix.gen.channel Room rooms
```
which generates this error:
```
** (Mix) mix phoenix.gen.channel expects just the module name:
    mix phoenix.gen.channel Room
```

**Comment by tute** [comment]
Thanks! Proposed a PR fixing it.
