### ISSUE TITLE
Phoenix.HTML.Safe not implemented for %{}

### ISSUE THREAD

**Issue by jpospychala** [phoenixframework/phoenix#1908]
hi,
I created model with map field, like:

mix phoenix.gen.html Model models name:string body:map

but the generated code doesnt't work:

$ mix test
.....

  1) test lists all entries on index (Website.ModelControllerTest)
     test/controllers/model_controller_test.exs:8
     ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %{}
     stacktrace:
       (phoenix_html) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
       (phoenix_html) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
       (website) web/templates/model/index.html.eex:18: anonymous fn/3 in Website.ModelView.index.html/1
       (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
       (website) web/templates/model/index.html.eex:14: Website.ModelView."index.html"/1
       (website) web/templates/layout/app.html.eex:20: Website.LayoutView."app.html"/1
       (phoenix) lib/phoenix/view.ex:335: Phoenix.View.render_to_iodata/3
       (phoenix) lib/phoenix/controller.ex:641: Phoenix.Controller.do_render/4
       (website) web/controllers/model_controller.ex:1: Website.ModelController.action/2
       (website) web/controllers/model_controller.ex:1: Website.ModelController.phoenix_controller_pipeline/2
       (website) lib/website/endpoint.ex:1: Website.Endpoint.instrument/4
       (website) lib/phoenix/router.ex:261: Website.Router.dispatch/2
       (website) web/router.ex:1: Website.Router.do_call/2
       (website) lib/website/endpoint.ex:1: Website.Endpoint.phoenix_pipeline/1
       (website) lib/website/endpoint.ex:1: Website.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/model_controller_test.exs:9: (test)

underlying database is postgres

$ mix deps
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* fs 0.9.1 (Hex package) (rebar)
  locked at 0.9.2 (fs) ed17036c
  ok
* gettext 0.11.0 (Hex package) (mix)
  locked at 0.11.0 (gettext) 80c1dd42
  ok
* ranch 1.2.1 (Hex package) (rebar)
  locked at 1.2.1 (ranch) a6fb992c
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (decimal) 79a769d4
  ok
* poison 2.2.0 (Hex package) (mix)
  locked at 2.2.0 (poison) 4763b69a
  ok
* db_connection 1.0.0-rc.5 (Hex package) (mix)
  locked at 1.0.0-rc.5 (db_connection) 1d9ab6e0
  ok
* phoenix_pubsub 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (phoenix_pubsub) c31af4be
  ok
* cowlib 1.0.2 (Hex package) (rebar)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.0.4 (Hex package) (rebar)
  locked at 1.0.4 (cowboy) a324a8df
  ok
* plug 1.1.6 (Hex package) (mix)
  locked at 1.1.6 (plug) 8927e402
  ok
* phoenix_html 2.6.2 (Hex package) (mix)
  locked at 2.6.2 (phoenix_html) 944a5e58
  ok
* phoenix 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (phoenix) 1bdeb99c
  ok
* phoenix_live_reload 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (phoenix_live_reload) 829218c4
  ok
* postgrex 0.11.2 (Hex package) (mix)
  locked at 0.11.2 (postgrex) 139755c1
  ok
* ecto 2.0.4 (Hex package) (mix)
  locked at 2.0.4 (ecto) 03fd3b9a
  ok
* phoenix_ecto 3.0.1 (Hex package) (mix)
  locked at 3.0.1 (phoenix_ecto) 42eb486e
  ok

**Comment by shhavel** [comment]
Actually for me generated controller test works fine, but only if there are no entries with present field `body` on index page and if model's body is nil on show page. If assign `body` to any map tests become broken.

So there are actually two issues with generated HTML:

**1.** map field cannot be displayed on **show** and **index** pages due to error: `Phoenix.HTML.Safe not implemented for %{}`  

To fix this we can define protocol `Phoenix.HTML.Safe` for `Map`:

```elixir
defimpl Phoenix.HTML.Safe, for: Map do
  def to_iodata(data), do: data |> Poison.encode! |> Plug.HTML.html_escape
end
```

This requires adding dependency `poison` to `phoenix_html`

Or change generated show and index page to something like that:

fragment of `show.html.eex`:

```eex
<li>
  <strong>Body Key1:</strong>
  <%= @model.body["key1"] %>
</li>

<li>
  <strong>Body Key2:</strong>
  <%= @model.body["key2"] %>
</li>
```

fragments of `index.html.eex`:

```eex
<th>Body Key1</th>
<th>Body Key2</th>

# ...

<td><%= model.body["key1"] %></td>
<td><%= model.body["key2"] %></td>
```

**2**. on **form** `text_input` is generated for map field which cannot be saved due to validation error: `body is invalid`. Reported on stackoverflow:
http://stackoverflow.com/questions/34900490/phoenix-framework-how-to-populate-a-map-field-through-a-form-for
http://stackoverflow.com/questions/35549618/mix-phoenix-gen-html-with-map-field-type   

We can generate working inputs in the form to specify the right direction for developers

```eex
<div class="form-group">
  <%= label f, :body_key1, "Body Key1", class: "control-label" %>
  <%= text_input f, :body_key1, name: "model[body][key1]", value: f.data.body["key1"], class: "form-control" %>
  <%= error_tag f, :body_key1 %>
</div>

<div class="form-group">
  <%= label f, :body_key2, "Body Key2", class: "control-label" %>
  <%= text_input f, :body_key2, name: "model[body][key2]", value: f.data.body["key2"], class: "form-control" %>
  <%= error_tag f, :body_key2 %>
</div>
```

or at least one key:

```eex
<div class="form-group">
  <%= label f, :body_key, "Body Key", class: "control-label" %>
  <%= text_input f, :body_key, name: "model[body][key]", value: f.data.body["key"], class: "form-control" %>
  <%= error_tag f, :body_key %>
</div>
```

Thanks

**Comment by chrismccord** [comment]
As we won't be implementing the protocol for maps, I am closing this. We can handle this on the generator side by not generating map fields, or going with #1913. Please follow that issue for updates. Thanks!
