### ISSUE TITLE
Documentation: Channels Guide teaches how  to build XSS channels

### ISSUE THREAD

**Issue by COLABORATI** [phoenixframework/phoenix#1910]
Well, I am sure that you are aware of this, but that should be one more reason to change it. 
The [Channels Guide](http://www.phoenixframework.org/docs/channels) teaches people how to build channel apps that are vulnerable to xss attacks - `payload` is not sanitized. 
I believe it is a good practice to teach people about important security issues from day one of their web dev experience so they not get used to make it an afterthought.

**Comment by josevalim** [comment]
:+1:

**Comment by chrismccord** [comment]
Please open an issue on the phoenix_guides repo. Thanks!
