### ISSUE TITLE
Documentation Feature Request: Secure Transport for Channels

### ISSUE THREAD

**Issue by COLABORATI** [phoenixframework/phoenix#1911]
To avoid a biblical flood of insecure copy-pasted phoenix applications the Channels Guide should contain a best practice example implementation of how to build secure channel communication. It should be explained how to use transport security from the client and how to set it up on the server.
Also the examples should implement transport security by default.

**Comment by josevalim** [comment]
This is done by setting the `force_ssl` flag to true. It is documented in the config/prod.exs file of all new Phoenix applications:

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/config/prod.exs#L38-L44

If we need to do something here, we probably just just mention the `force_ssl` documentation in the SSL chapter. Everything else is pretty much done.
