### ISSUE TITLE
Documentation: Session Guide should contain information about CSRF

### ISSUE THREAD

**Issue by COLABORATI** [phoenixframework/phoenix#1912]
The [Session Guide](http://www.phoenixframework.org/docs/sessions) follows the same pattern like the current Channel Guide of not mentioning obvious security issues that come with sessions and how to handle them with phoenix. These issues are obvious for experts only, but the guides are read by non-experts, too, and you should not trap them into building insecure apps, instead teach them about web security from day one of their web dev experience. 
Also the examples in this guide should contain the canonical example implementation of how to implement sessions in a secure way with phoenix. 
Please do not make security issues a private homework for interested users. I do not want to study source code to understand how to build a secure app with phoenix - the docs should instead show me the best possible way to implement best security practices by default. 
IMHO "security hardened by community", is one of the most important key selling points of open source software, so it is a little bit disappointing when security becomes a second class citizen in end user documentation of open source projects. 
Thanks for your attention!

**Comment by josevalim** [comment]
@COLABORATI I agree we should list those even though we protect you from almost all of them out of the box. The only issue that I recall from the top of my mind that requires user care is session fixation attach which requires the user to drop the session ID on commands that require authentication.

Btw, for future reference, issues about the Phoenix Guides should be opened on the Phoenix Guides repo. :)
