### ISSUE TITLE
Plugin (Engine) migrations

### ISSUE THREAD

**Issue by gwincr11** [phoenixframework/phoenix#1919]
I am building a Phoenix plugin that needs migrations. It would be nice if there was a better way to add migrations from a plugin. I am thinking there are a couple possibilities.

1. Probably the easiest to implement would be letting custom mix tasks create migrations using the Phoenix mix task gen model. However to do this the migration and the model creation need to be decoupled.

2. Ecto migrate could check plugins migration folders.

I am not sure what the best path forward is, there are a few plugins out there that I have seem that are re-implementing migration creation but this seems like something Phoenix should make easier. Am I missing something?

Thanks
Cory

**Comment by chrismccord** [comment]
Please send feature requests to the mailing list as we reserve the issue tracker for issues, per the issue template. Thanks!

**Comment by gwincr11** [comment]
Thanks done.
