### ISSUE TITLE
mongodb_ecto version conflict

### ISSUE THREAD

**Issue by hcvst** [phoenixframework/phoenix#1924]
Hi, 

Phoenix looks like a great framework (thank you) and I would like to give it a try.

This is my first attempt to use Phoenix and since I would like to use MongoDB here's how
I generated the project: 

`mix phoenix.new helloMongo --database mongodb`

This fails however in the dependency installation step with:

```
Fetch and install dependencies? [Yn] 
* running mix deps.get
* error command failed to execute, please run the following command again after installation: "mix deps.get"
* running npm install && node node_modules/brunch/bin/brunch build
* error command failed to execute, please run the following command again after installation: "npm install && node node_modules/brunch/bin/brunch build"

```

Changing into the project directory and running `mix deps.get` shows that there is a version conflict.

`Failed to use "ecto" (versions 2.0.0 to 2.0.5) because
  mongodb_ecto (versions 0.1.0 to 0.1.2) requires ~> 1.0
  phoenix_ecto (version 3.0.1) requires ~> 2.0
`

`mix phoenix.new` works fine for postgres.

As I am new to Phoenix and the entire Elixir ecosystem I am reluctant to try to fix this myself for fear of running into issues down the line since this project should go into production eventually.

### Environment
Elixir version (elixir -v): Elixir 1.3.2
```
mix deps
* phoenix_live_reload (Hex package)
  the dependency is not available, run "mix deps.get"
* gettext (Hex package)
  the dependency is not available, run "mix deps.get"
* cowboy (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix_html (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix_pubsub (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix_ecto (Hex package)
  the dependency is not available, run "mix deps.get"
* mongodb_ecto (Hex package)
  the dependency is not available, run "mix deps.get"
```

**Comment by ericmj** [comment]
Phoenix is compatible with Ecto 2.0 and the Mongo adapter has not been updated to support Ecto 2.0 yet. You have to chose another database or use an older version of Phoenix and Ecto.

**Comment by hcvst** [comment]
Thanks Eric.
