### ISSUE TITLE
error: Resolving deps of web\static\js\app.js failed on Windows7

### ISSUE THREAD

**Issue by d-sato2** [phoenixframework/phoenix#1930]
### Problem
```
mix deps.update --all
mix deps.clean --all
mix deps.get
mix ecto.create && mix ecto.migrate
npm install
mix phoenix.server
```

returns error

```
$ mix phoenix.server
[info] Running Chat.Endpoint with Cowboy using http on port 4000
21 Sep 10:07:55 - error: Resolving deps of web\static\js\app.js failed. Improperly-cased require: 'phoenix' in c:\User\phoenix_chat_example\web\static\js\app.js
21 Sep 10:07:55 - info: compiled 5 files into 2 files in 1.7 sec
```

### Environment

* Elixir version 1.3.1:
* Phoenix version 1.1.6:
* NodeJS version 6.6.0:
* NPM version 3.10.3:
* Operating system:Windows7 64bit

### ```package.json``` contents
```
{
  "repository": {
  },
  "dependencies": {
    "babel-brunch": "~6.0.0",
    "brunch": "2.7.4",
    "clean-css-brunch": "~1.8.0",
    "css-brunch": "~1.7.0",
    "javascript-brunch": "~1.8.0",
    "uglify-js-brunch": "~1.7.0",
    "phoenix": "file:deps/phoenix",
    "phoenix_html": "file:deps/phoenix_html"
  }
}
```
### ```deps/phoenix/package.json``` contents
```
{
  "name": "phoenix",
  "version": "1.1.6",
  "main": "./priv/static/phoenix.js",
  "repository": {
  },
  "devDependencies": {
    "brunch": "^2.1.1",
    "babel-brunch": "^6.0.0",
    "uglify-js-brunch": ">= 1.0 < 1.8"
  },
  "files": ["LICENSE.md", "package.json", "priv/static/phoenix.js"]
}
```

### part of ```web\static\js\app.js``` contents
```JavaScript
import {Socket, LongPoller} from "phoenix"
```

**Comment by chrismccord** [comment]
Can you reproduce this on Phoenix 1.2? You will need to bump your phoenix dep to "~> 1.2". Please try that and report back. Thanks!

**Comment by d-sato2** [comment]
@chrismccord 
I reproduced this on Phoenix 1.2 and still same error message remain, but, I do not know why, it works.
```
[info] Running Chat.Endpoint with Cowboy using http://0.0.0.0:4000
21 Sep 11:52:03 - error: DEPS_RESOLVE_CASE of web/static/js/app.js failed. Improperly-cased require: 'phoenix' in c:/Users/harp179/desktop/phoenix_sample2/phoenix_chat_example/web/static/js/app.js
21 Sep 11:52:03 - info: compiled 5 files into 2 files in 2.7 sec
```

I tryed following steps
```
git clone https://github.com/chrismccord/phoenix_chat_example
cd phoenix_chat_example

changed  in ```mix.exs```
from
```{:phoenix, "~> 1.1.2"}```
to
```{:phoenix, git: "https://github.com/phoenixframework/phoenix.git", override: true}```

mix deps.get
npm install
mix phoenix.server

**Comment by d-sato2** [comment]
@chrismccord 
I reproduced this on Phoenix 1.2 and still same error message remain, but, I don't know why, it works!

### error message
```
[info] Running Chat.Endpoint with Cowboy using http://0.0.0.0:4000
21 Sep 11:52:03 - error: DEPS_RESOLVE_CASE of web/static/js/app.js failed. Improperly-cased require: 'phoenix' in c:/Users/harp179/desktop/phoenix_sample2/phoenix_chat_example/web/static/js/app.js
21 Sep 11:52:03 - info: compiled 5 files into 2 files in 2.7 sec
```

### tried steps
```
git clone https://github.com/chrismccord/phoenix_chat_example
cd phoenix_chat_example
```
changed ```mix.exs```
from
```{:phoenix, "~> 1.1.2"}```
to
```{:phoenix, git: "https://github.com/phoenixframework/phoenix.git", override: true}```


changed ```package.json```
from
```"brunch": "~2.1.3"```
to
```"brunch": "~2.8.2"```

```
mix deps.get
npm install
mix phoenix.server
```

**Comment by chrismccord** [comment]
Since it's working for you now, even with the error message, and I don't have access to a Windows 7 instance, I'm marking this one as resolved. If you are unable to compile assets in the future. Please open  another issue. Thanks!

**Comment by StefRave** [comment]
I reproduced the issue on Windows. It happens when you change directory in powershell with the wrong casing. E.g. "cd c:\SRC" when the directory name id "c:\src"

**Comment by nathanchere** [comment]
Been getting this issue still with Phoenix 1.3.3 on Win10. @StefRave you nailed it. The inconsistency with this issue has been driving me nuts, thanks a tonne for solving it.
