### ISSUE TITLE
mix phoenix.digest should handle source maps

### ISSUE THREAD

**Issue by aaronjensen** [phoenixframework/phoenix#1936]
When building sourcemaps w/ webpack you get something like:

```
//# sourceMappingURL=bundle.js.map
```

at the bottom of your js file. `mix phoenix.digest` will digest and rename the `bundle.js` and the `bundle.js.map` but it does not update the `sourceMappingURL`.

Is this a responsibility of phoenix? Is this not an issue w/ the brunch build for some reason? Ideally it'd be handled by phoenix.

**Comment by josevalim** [comment]
We should handle that. A PR is welcome! :D

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
To be clear, we have source maps in dev by virtue of brunch. I don't think digest needs anything in particular? If `brunch build --prod` strips them out by default, we could ship a config that includes them, but I think this is up to the user. I don't think the digest task itself should be concerned with this since it's asset builder specific? Or am I missing something?

**Comment by aaronjensen** [comment]
@chrismccord the digest task breaks sourcemaps by virtue of not changing the `sourceMappingURL` if you want them in production.

It all depends on the user's workflow for production sourcemaps. Some upload them to their error tracker, others serve them behind an ip blocker, etc. I'd suggest having a default that doesn't break them if the user wants them would be good.

**Comment by chrismccord** [comment]
ah derp, I see. Can this be as simple as updating the url via a regex just like we do with css? I am 👍 if someone want's to take this one!

**Comment by ntilwalli** [comment]
I think it should also preserve the file name convention.  My `base.css.map` file gets digested to `base.css-e73a374a4c0650448f26e781ad616aa3.map`.  The hash string should be appended to the token before the first period, not the token before the last period imho.

**Comment by Szetty** [comment]
hi :) I think I would take this issue, @chrismccord can u assign it to me?

**Comment by chrismccord** [comment]
@Szetty It's all yours :) Thanks!

**Comment by aaronjensen** [comment]
It looks like this was done and merged, thanks @Szetty!
