### ISSUE TITLE
multiply slashes

### ISSUE THREAD

**Issue by chernyshof** [phoenixframework/phoenix#1940]
i found that if you add some slashes in url nothing changing
for example:

we have url : 
example.com/users

and if we add slash it works correctly 
example.com/users/

and if add more it works correctly too
example.com/users////

and if u make something like that it works too
example.com////users

**Comment by shhavel** [comment]
I do not think this is a bug, it does not break URL specification.
Related stackoverflow questions:
http://stackoverflow.com/questions/10161177/url-with-multiple-forward-slashes-does-it-break-anything
http://stackoverflow.com/questions/20523318/is-a-url-with-in-the-path-section-valid

But you can configure redirect or return 404 by checking `conn.request_path`

**Comment by chrismccord** [comment]
This would be on the plug side, not on phoenix, but I wouldn't consider this a bug or something that needs fixed. In the future, please follow the issue template when opening new issues. Thanks!
