### ISSUE TITLE
Ignoring unmatched topic "rooms:lobby" in HelloPhoenix.UserSocket?

### ISSUE THREAD

**Issue by phpapi** [phoenixframework/phoenix#1943]
I followed the office guide to tring channel, dont know why the server output this, does lose some step ?

```
[info] Running HelloPhoenix.Endpoint with Cowboy using http://localhost:4000
[info] GET /
[debug] Processing by HelloPhoenix.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 334ms
[warn] Ignoring unmatched topic "rooms:lobby" in HelloPhoenix.UserSocket
27 Sep 04:12:30 - info: compiling
Setting up watches.  Beware: since -r was given, this may take a while!
27 Sep 04:12:32 - info: compiled 6 files into 2 files, copied 3 in 6.2 sec
Watches established.
```

**Comment by josevalim** [comment]
@phpapi yes, you probably missed some step. Check your UserSocket module and see if you are matching on the rooms:lobby topic on the channel call. Also, please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
