### ISSUE TITLE
ErrorView attempting to render HTML when specified format is non-HTML

### ISSUE THREAD

**Issue by mitchellhenke** [phoenixframework/phoenix#1945]
### Environment

* Elixir version: 1.3.3
* Phoenix version: master
* Operating system: macOS 10.12

### Expected behavior
I have a mime-type specified with an encoder like this:

```elixir
config :phoenix, :format_encoders,
  "json-api": Poison

config :mime, :types, %{
  "application/vnd.api+json" => ["json-api"]
}
```

A custom exception with a status of 501 with Plug.Exception:
```elixir
defmodule MyError do
  defexception message: "default message"
end

defimpl Plug.Exception, for: MyError do
  def status(_exception), do: 501
end
```

A controller route that raises that exception, and an ErrorView that should handle it correctly:
```elixir
defmodule ErrorReportingEcto404.PageController do
  use ErrorReportingEcto404.Web, :controller
  alias ErrorReportingEcto404.Thing

  def show(conn, %{"id" => id}) do
    IO.inspect conn.private[:phoenix_format]
    raise MyError, "this is an error"
    render conn, "index.json-api"
  end

  def index(conn, _) do
    IO.inspect conn.private[:phoenix_format]
    render conn, "index.json-api"
  end
end


defmodule ErrorReportingEcto404.ErrorView do
  use ErrorReportingEcto404.Web, :view

  # Uncomment me for passing test
  # def render("501.html", _assigns) do
  #   "Not Implemented"
  # end

  def render("501.json-api", _assigns) do
    %{
      id: "NOT IMPLEMENTED",
      status: 501
    }
  end

  def render("500.json-api", _assigns) do
    %{
      id: "INTERNAL_SERVER_ERROR",
      title: "500 Internal server error",
      status: 500
    }
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(template, assigns) do
    IO.inspect assigns.conn.private[:phoenix_format]
    render "500.json-api", assigns
  end
end
```

My test looks like this, and I would expect it to pass:

```elixir
defmodule ErrorReportingEcto404.PageControllerTest do
  use ErrorReportingEcto404.ConnCase

  test "GET /:id", %{conn: conn} do
    assert_error_sent 501, fn ->
      conn
      |> put_req_header("accept", "application/vnd.api+json")
      |> put_req_header("content-type", "application/vnd.api+json")
      |> get("/0")

    end
  end
end
```

### Actual behavior

The test fails with:

```elixir
"json-api"
"html"
  1) test GET / (ErrorReportingEcto404.PageControllerTest)
     test/controllers/page_controller_test.exs:4
     expected error to be sent as 501 status, but got an error with no response from:

     ** (FunctionClauseError) no function clause matching in Phoenix.Template.HTML.encode_to_iodata!/1

     stacktrace:
       (phoenix) lib/phoenix/template/html.ex:12: Phoenix.Template.HTML.encode_to_iodata!(%{id: "INTERNAL_SERVER_ERROR", status: 500, title: "500 Internal server error"})
       (phoenix) lib/phoenix/controller.ex:641: Phoenix.Controller.do_render/4
       (phoenix) lib/phoenix/endpoint/render_errors.ex:54: Phoenix.Endpoint.RenderErrors.__catch__/5
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       (phoenix) lib/phoenix/test/conn_test.ex:615: Phoenix.ConnTest.wrap_request/1
       (phoenix) lib/phoenix/test/conn_test.ex:569: Phoenix.ConnTest.assert_error_sent/2
       test/controllers/page_controller_test.exs:5: (test)
```

I added some IO.inspect to the controller and the view, and within the controller phoenix_format is `"json-api"` as expected, but becomes `"html"` in the ErrorView.

I have a repo with all of the code [here](https://github.com/mitchellhenke/ErrorReportingEcto404)

I'm not sure how related (if at all) it is to #1928

**Comment by JoshSmith** [comment]
While my [example repository](https://github.com/JoshSmith/ErrorReportingEcto404) is nowhere near as thorough as this, adding it in case it helps.

**Comment by josevalim** [comment]
@mitchellhenke what if you add json-api here? https://github.com/mitchellhenke/ErrorReportingEcto404/blob/master/config/config.exs#L16

**Comment by mitchellhenke** [comment]
@josevalim ahhh, that does fix it, thank you!  Is there a place in the docs that covers this?

**Comment by josevalim** [comment]
@mitchellhenke it is covered in the endpoint docs. And I am afraid the error message is not nice, although I have no idea how to improve it. :S

**Comment by JoshSmith** [comment]
Thanks as always @josevalim! You're a beast. 🙌

**Comment by mitchellhenke** [comment]
@josevalim To me, the surprising part is the multiple places to update `accepts`, and that the error doesn't suggest that I'm trying to render a format that `ErrorView` isn't configured to handle.   If it's something that would be possible to add, I would be glad to have a go at adding something along the lines of "current format is #{phoenix_format}, but #{error_view_module} is not configured to handle it. Check Endpoint config ...etc. etc."  Would that make sense to do?

**Comment by josevalim** [comment]
> To me, the surprising part is the multiple places to update accepts, and that the error doesn't suggest that I'm trying to render a format that ErrorView isn't configured to handle.

Great catch. Maybe we should log in those cases? Here is the source:

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/render_errors.ex#L93

I think if we log something like `"using fallback format x for error view because #{Exception.message(e)}. Please customize your render_view configuration if desired"` or something similar is likely enough?

**Comment by mitchellhenke** [comment]
@josevalim sounds good to me, I'll put together a PR

**Comment by josevalim** [comment]
:heart:
