### ISSUE TITLE
Check_origin fails when endpoint is configured with environment variable

### ISSUE THREAD

**Issue by ThijsWouters** [phoenixframework/phoenix#1947]
I have configured my endpoint with an environment variable.

    config :app, App.Endpoint, 
      ...
      url: [
        host: {:system, "HOST"},
      ],
      ...

When I try to connect to my socket, it fails with `Could not check origin for Phoenix.Socket transport.`

### Environment

* Elixir version (elixir -v): 1.3.2
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 6.6.0
* NPM version (npm -v): 3.10.3
* Operating system: Debian Linux

### Expected behavior

The origin check passes, when started with the correct HOST variable.

### Actual behavior

The origin check fails.

**Comment by chrismccord** [comment]
Can you confirm if the host env set in your app, and not nil? The default check_origin should fallback to the URL host if check_origin is not set

**Comment by josevalim** [comment]
I believe the host is loaded at compilation time. So if you are compiling locally and setting the HOST during production, it is not going to work. Can you please confirm this is the case? If so, we should probably fix it or at least document it.

**Comment by ThijsWouters** [comment]
@chrismccord The host is set correctly. When I execute `App.Endpoint.struct_url/0` the host is set to the correct host.

@josevalim I am using {:system, "HOST"}, which according to the docs should work. When I used `System.get_env/1`, then the variables needed to be available at compilation time.

**Comment by josevalim** [comment]
> @josevalim I am using {:system, "HOST"}, which according to the docs should work. 

I am aware, that's why I am asking if you are compiling locally and setting the HOST during production. :) Because if you are doing that and it does not work, I believe it is a cross origin bug.

**Comment by ThijsWouters** [comment]
I am compiling on the server, but the HOST is not set at that point. I only set the HOST when I start the application.

**Comment by josevalim** [comment]
Ok, thank you. So bug confirmed. :)
