### ISSUE TITLE
TypeError: require(...).App is undefined

### ISSUE THREAD

**Issue by phpapi** [phoenixframework/phoenix#1950]
I've added this code to web/static/js/app.js,

```
export var App = {
  run: function(){
    console.log("Hello!")
  }
}
```

Then add this line to web/templates/layout/app.html.eex in the end.

`<script>require("web/static/js/app").App.run()</script>`

Then refresh the browse its showing this in console:
```
TypeError: require(...).App is undefined
<script>require("web/static/js/app").App.run()</script>
```
I asked from stackoverflow but that answer have not resolve this error.

I see a line containing 
`require.register("web/static/js/app.js"` in localhost:4000/js/app.js , 
 but not contain 
`var App = { ... run: function() { console.log ... } ... }`

**Comment by chrismccord** [comment]
In the future, please follow the issue template as my first question would have been to ask which phoenix version, brunch version, node version, etc you are using. Phoenix for a long while now has not used the `require("web/static/js/app")` and instead ships with brunch's autoRequire feature enabled, so you may want to start there. Thanks!
