### ISSUE TITLE
plug json_decoder customization not used in tests

### ISSUE THREAD

**Issue by brainlid** [phoenixframework/phoenix#1951]
### Environment

* Elixir version: 1.3.3.
* Phoenix version: 1.2.0
* Operating system: Arch Linux / MacOS

### Expected behavior

A customized json_decoder module for plug parsers should be called during tests.

### Actual behavior

From endpoint.ex

```elixir
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: MyApp.CustomDecoder
```

```elixir
defmodule MyApp.CustomDecoder do
  def decode!(body) do
    IO.puts "&&&&&&&&&&&&&&&&&&&&&&"
    body
    |> Poison.decode!
  end
end
```

In "dev" mode, every request to the endpoint fires the custom decoder.

In "test" mode, the custom decoder is never used.

In dev and prod we have the desired behavior. However, we are unable to write tests that depend on that special behavior provided by our decoder as it is never called.

**Comment by chrismccord** [comment]
your configured decoder should definitely be called. I will look into this in a bit, thanks!

**Comment by josevalim** [comment]
@brainlid how are you sending parameters during tests? Your decode will only be invoked if you pass your response body as a string and set the request content-type to the application/json. If you are passing directly parameters, such as `post "/foo", %{...}`, it won't invoke the decoder because the parameters are already decoded (and we won't encode them just so they can be decoded right after).

**Comment by brainlid** [comment]
@josevalim: ah, that makes sense. Yes, our controller tests are sending a map. 

What our json_decoder does special is to perform Macro.underscore on the incoming data. Making "userName" become "user_name". So it really doesn't have anything to do with json_decoding, it's just pre-processing it to change the keys. 

We do this to better support mobile development where the tooling works best with snakeCase text.

Is there a better place to do that then?

**Comment by chrismccord** [comment]
@brainlid if you want to exercise the decoder, you can do as josé said and make sure you set the content type to application/json, then pass an encoded string, something like:

```elixir
setup %{conn: conn} do
  {:ok, conn: put_req_header(conn, "content-type", "application/json")}
end

test "...", %{conn: conn} do
  get conn, "/foo",  json(%{snake_key: "value"})`
end

def json(%{} = payload), do: MyEncoder.encode!(payload)
```

If we can improve the docs or you have other questions, please let us know. Thanks!
