### ISSUE TITLE
Provide --no-gettext option for phoenix.new

### ISSUE THREAD

**Issue by johnnyshields** [phoenixframework/phoenix#1955]
IMHO I18n is overkill for many smaller applications and it would be nice to be able to exclude it when generating a new app.

In addition, folks coming from Rails like myself might prefer the Rails/Linguist-style "key-value" I18n; in my case I have 10,000+ translation keys and a translation workflow based around that structure.

**Comment by josevalim** [comment]
Once the work on the new generators are done we can look into it. It should be relatively straight-forward.

**Comment by chrismccord** [comment]
Noted in the generator PR

**Comment by tvsijin** [comment]
Any updates?
