### ISSUE TITLE
mix phoenix.gen.html better contains validation states in template

### ISSUE THREAD

**Issue by chenxsan** [phoenixframework/phoenix#1961]
### Environment

* Elixir version (elixir -v): 1.3.3
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 6.3.1
* NPM version (npm -v): 3.10.3
* Operating system: macOS Sierra

### Expected behavior

When running `mix phoenix.gen.html` command, expect the generated templates as below (Please forgive me if the code is bad, I'm very new with Phoenix and Elixir):

```
  <div class="form-group <%= if f.errors[:title] do ~s(has-error) else ~s(has-success) end %>">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>
```
And when there are errors in changeset, we got:

<img width="459" alt="screen shot 2016-10-10 at 3 48 45 pm" src="https://cloud.githubusercontent.com/assets/1091472/19229581/281d045c-8f01-11e6-9e78-2db20655308c.png">

### Actual behavior

Instead we got:

```
  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>
```
And when there are errors in changeset, we got:

<img width="309" alt="screen shot 2016-10-10 at 3 47 38 pm" src="https://cloud.githubusercontent.com/assets/1091472/19229573/1c90bf0c-8f01-11e6-82b1-ec1b1de8ba7a.png">

The `help-block` text is muted, it's difficult to notice the error.

As far as I know, Phoenix uses Bootstrap in the templates, I think it would be better to include [validation states](http://getbootstrap.com/css/#forms-control-validation) in the templates code.

**Comment by shhavel** [comment]
This is actually great to implement this in html generator.
Currently I am forced to add this to each field in a template form:

```eex
  <div class="form-group <%= if f.errors[:category], do: "has-error" %>">
    <%= label f, :category, class: "control-label" %>
    <%= text_input f, :category, class: "form-control" %>
    <%= error_tag f, :category %>
  </div>
```

**Comment by josevalim** [comment]
This is better to implement in your app. We wrote about it here: http://blog.plataformatec.com.br/2016/09/dynamic-forms-with-phoenix/
