### ISSUE TITLE
mix phoenix.digest should base the hash of a CSS file on the digested_contents after linked assets have been replaced

### ISSUE THREAD

**Issue by nauger** [phoenixframework/phoenix#1964]
### Environment
- Elixir version (elixir -v): 1.2.6
- Phoenix version (mix deps): 1.2.1
- NodeJS version (node -v): v5.11.1
- NPM version (npm -v): 3.8.6
- Operating system: Centos 7
### Expected behavior

When digesting a css asset, the digest filename hash should be based on the digested file contents (after replacing linked assets with their digested variant file names.)

```
css digest hash = hash(digested file contents) 
```
### Actual behavior

```
css digest hash = hash(original, unreplaced, file contents)
```

What this means in practice, is that updating an asset that's included in a spreadsheet will not cause the file name to change (even though the internal contents have changed) leading to caches not busting.

**Comment by josevalim** [comment]
Thank you for the report.

I am not sure if that can work because you can run into circular dependencies? Imagine that file a.css references b.css and b.css references a.css. In order to digest them, I need to convert their URLs to the digested ones, but I won't be able to do so before I digest the other one?

I agree with the issue but I am not sure what is the best way to fix it.

**Comment by vinnymac** [comment]
@josevalim I imagine you would not allow such a thing to occur. Other projects that digest such as sprockets deal with this by throwing a [CircularDependencyError](https://docs.omniref.com/ruby/gems/sprockets/2.8.0/symbols/Sprockets::CircularDependencyError#!). Throwing an error in that type of situation would be alright with most users I would imagine.

I was researching to find support for this feature, disappointed to see it does not have any. I'll have to digest using an alternative mechanism for now. Glad to see others in the wild who need this.

**Comment by chrismccord** [comment]
I'm open to PRs that would provide this feature, but it's not a priority for us now with other 1.3 features. Closing for now, but if someone would like to take a stab, please chime in. Thanks!
