### ISSUE TITLE
How to change the default config in cowboy

### ISSUE THREAD

**Issue by phpapi** [phoenixframework/phoenix#1972]
Well, I kown the cowboy is the web server. If i dont want my website showing is localhost:4000,  I have a domain,want to host to my phoenix website, Then how to change the cowboy config to host this domain.
or add a new vhosts in it.

**Comment by josevalim** [comment]
Please use the mailing list, ElixirForum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
