### ISSUE TITLE
what can I do with phoenixframework?

### ISSUE THREAD

**Issue by andywang2014** [phoenixframework/phoenix#1974]
Hello,as the title,what can I do with phoenixframework? can I developer apps with the framework?as the server api?

**Comment by Gazler** [comment]
Please keep the issue tracker for actual issues. http://www.phoenixframework.org/ is a good starting place for a description of the framework.

**Comment by andywang2014** [comment]
Thanks.And how could I create native mobile apps with real-time streaming technology called Channels?

**Comment by Gazler** [comment]
Again, the issue tracker should be for issues only. Please try https://elixirforum.com/ or https://stackoverflow.com/questions/tagged/phoenix-framework for general help.

**Comment by andywang2014** [comment]
ok,thanks.
