### ISSUE TITLE
force_ssl redirects to endpoint hostname instead of using Host header

### ISSUE THREAD

**Issue by ericmj** [phoenixframework/phoenix#1976]
`Plug.SSL` redirects based on the Host header and I think Phoenix should use the same default with the option to use a custom hostname.

As an example Hex.pm can be reached via two hostnames, either hex.pm or hexpm.herokuapp.com. This is good redundancy if there are DNS issues which has happened two times since Hex.pm went live. First with dnssimple [1] and more recently with Dyn [2].

Visiting https://hexpm.herokuapp.com works fine but when visiting http://hexpm.herokuapp.com you are redirected to https://hex.pm which may be inaccessible.

[1] https://blog.dnsimple.com/2014/12/incident-report-ddos/
[2] https://www.dynstatus.com/incidents/5r9mppc1kb77

**Comment by ericmj** [comment]
Note that due to HSTS headers after you have visited the https version hexpm.herokuapp.com once http://hexpm.herokuapp.com will correctly redirect to the https version of hexpm.herokuapp.com.

**Comment by josevalim** [comment]
@ericmj you can specify `host: nil` in your Plug.SSL configuration and it will use whatever is in the Host.

**Comment by ericmj** [comment]
> you can specify host: nil in your Plug.SSL configuration and it will use whatever is in the Host.

That's my point, Phoenix does not allow this. Or are you suggesting using `Plug.SSL` directly instead of the `force_ssl` endpoint config?

**Comment by josevalim** [comment]
@ericmj in Phoenix v1.2.1 we use put_new, which means that it will keep the nil value if you set `host: nil`:

https://github.com/phoenixframework/phoenix/blob/v1.2/lib/phoenix/endpoint.ex#L570

**Comment by ericmj** [comment]
That's great, I will try to document this. Thank you!

**Comment by josevalim** [comment]
It is documented too. :) But only in master!

**Comment by ericmj** [comment]
Even better :)
