### ISSUE TITLE
Warn on unhanded handle_info in channel

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#1980]
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/gen_server.ex#L554-L560

**Comment by kelvinst** [comment]
Just updating your link: https://github.com/elixir-lang/elixir/blob/cbbccd8d9f4073c85e3095d5a6c583f6194b450d/lib/elixir/lib/gen_server.ex#L560-L569

I guess fixing the commit SHA this way will not change the lines anymore. 😬
