### ISSUE TITLE
Channel logging is insufficient to understand source of errors

### ISSUE THREAD

**Issue by myronmarston** [phoenixframework/phoenix#1984]
### Environment
- Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.2
```
- Phoenix version (mix deps):

```
➜  delorean git:(myron/increase-timeout) cat mix.lock | grep phoenix
  "phoenix": {:hex, :phoenix, "1.2.1", "6dc592249ab73c67575769765b66ad164ad25d83defa3492dc6ae269bd2a68ab", [:mix], [{:cowboy, "~> 1.0", [hex: :cowboy, optional: true]}, {:phoenix_pubsub, "~> 1.0", [hex: :phoenix_pubsub, optional: false]}, {:plug, "~> 1.1", [hex: :plug, optional: false]}, {:poison, "~> 1.5 or ~> 2.0", [hex: :poison, optional: false]}]},
  "phoenix_html": {:hex, :phoenix_html, "2.7.0", "19e12e2044340c2e43df206a06d059677c59ea1868bd1c35165438d592cd420b", [:mix], [{:plug, "~> 1.0", [hex: :plug, optional: false]}]},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.5", "829218c4152ba1e9848e2bf8e161fcde6b4ec679a516259442561d21fde68d0b", [:mix], [{:fs, "~> 0.9.1", [hex: :fs, optional: false]}, {:phoenix, "~> 1.0 or ~> 1.2-rc", [hex: :phoenix, optional: false]}]},
  "phoenix_pubsub": {:hex, :phoenix_pubsub, "1.0.0", "c31af4be22afeeebfaf246592778c8c840e5a1ddc7ca87610c41ccfb160c2c57", [:mix], []},
```
- NodeJS version (node -v):

Not using node.  The front end is an entirely different code base so we have no assets.
- NPM version (npm -v):

See above.
- Operating system:

OS X locally, Ubuntu in prod.
### Expected behavior

The logging I get from Phoenix/Plug for normal HTTP requests is quite good.

```
2016-10-25T06:26:16.540 request_id=5i4mgbo84cui7sm06fea456g957lim12 module=Plug.Logger [info] GET /delorean-api/on-page/prod.4089487.831342/summary/google.en-US/week
# ...
2016-10-25T06:26:16.597 request_id=5i4mgbo84cui7sm06fea456g957lim12 campaign=prod.4089487.831342 module=Plug.Logger [info] Sent 200 in 56m
```

Each request is tagged with an id, and the input is logged (the `GET /path` bit), and then later the response and response time is logged.  I can clearly see what each request and response was.

For channels, I expect like a similar level of logging:
- Everything associated with specific channel should have a unique channel id (similar to the `request_id` for HTTP) that allows you to easily find all the log messages related to that channel.
- Every time a client sends an event, the input should be logged (similar to the `GET /path` bit above) and the response logged.  Having all of this would help me be able to see how a channel got in a specific state by seeing all the events the client sent to it.
### Actual behavior

The logging I see for phoenix channel interactions is much more limited than what I expected.  Looking through my production logs, I see this:

```
2016-10-25T06:50:10.659 module=Phoenix.Logger [info] JOIN keyword_analysis to DeloreanAPI.KeywordAnalysisChannel
  Transport:  Phoenix.Transports.WebSocket
  Parameters: %{}
2016-10-25T06:50:10.660 module=Phoenix.Socket.Transport [info] Replied keyword_analysis :ok
```

...which is the input and output for the join request, but that's about it.  I'm not seeing any similar messages for the events sent by clients, and no `channel_id` attached to each log message. (I realize I'd have to configure my logger to include the `channel_id` for it to appear in my logs, but Phoenix isn't even setting it via `Logger.metadata`).

**Comment by josevalim** [comment]
We could set the Logger.metadata although I am not convinced if we should log all incoming events? Channel is a regular GenServer, which means in case of crashes, it should include the source of the error, including the last incoming process message.

**Comment by josevalim** [comment]
@myronmarston actually, maybe we should rather change Logger to always include pid as metadata in the Logger?

**Comment by josevalim** [comment]
Ignore the Logger suggestion, it won't work in many cases (including this one).

**Comment by myronmarston** [comment]
> Channel is a regular GenServer, which means in case of crashes, it should include the source of the error, including the last incoming process message.

In my case, this doesn't help, because it's another process under a different supervision tree that crashed in response to a message from my channel process.  I'm trying to understand what the client events were that led to the state that caused the message that caused the other process to crash.

> although I am not convinced if we should log all incoming events? 

Are you mostly concerned about verbosity?  Seems like we could at least log all incoming events at a low log level (e.g. `debug`), although that probably wouldn't help me in this specific case (I think we use `info` in prod).

**Comment by josevalim** [comment]
I guess worst scenario we could make the log level configurable, so :+1:.

**Comment by chrismccord** [comment]
@josevalim you were pretty against logging on all `handle_in`'s, so are you sure you'd like to see this change? I am indifferent. What would the configuration options look like? Keep in mind we instrument `:phoenix_channel_receive` already today, so logging could be done by users today via instrumentation.

**Comment by josevalim** [comment]
@chrismccord if i remember our conclusion was to postpone until we need it. Also, good point about the instrumentation. @myronmarston, why don't you give it a try? :)

**Comment by myronmarston** [comment]
> @myronmarston, why don't you give it a try? :)

TBH, with everything else on my plate, I'm unlikely to get to this any time soon.  Not sure if you want to keep this issue open or not.

**Comment by myronmarston** [comment]
Thanks, @chrismccord!
