### ISSUE TITLE
Sessions are missing when requesting via XHR

### ISSUE THREAD

**Issue by mikker** [phoenixframework/phoenix#1998]
### Environment

* Elixir version (elixir -v): `Elixir 1.3.2, Erlang/OTP 19`
* Phoenix version (mix deps): `phoenix 1.2.1`
* NodeJS version (node -v): `node v7.0.0`
* NPM version (npm -v): `npm 3.10.8`
* Operating system: `macOS 10.12.1 Sierra`

### Expected behavior

When requesting via XHR, with the `:fetch_session` plug and all, sessions should work.

### Actual behavior

When I make GET requests via XHR, the session data is missing.

I have created a test project that has the error:
https://github.com/mikker/phoenix-session-xhr-bug
Instructions to reproduce are included on the index page.

Log output looks good:

```
[info] GET /
[debug] Processing by Sesstest.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 249µs
[info] GET /api/lists
[debug] Processing by Sesstest.ApiController.request/2
  Parameters: %{"format" => "_json", "path" => ["lists"]}
  Pipelines: [:browser]
[info] Sent 200 in 235µs
```

**Comment by chrismccord** [comment]
Please amend the title to include the issue template and fix your screenshot :) Also, including the output logs here for a xhr request would be very helpful. Thanks!

**Comment by josevalim** [comment]
The big is mostly likely in the client. By adding `IO.inspect conn.req_headers`, we can see it is not sending the cookie headers:

```
[{"host", "localhost:4000"}, {"connection", "keep-alive"},
 {"user-agent",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"},
 {"accept", "*/*"}, {"referer", "http://localhost:4000/"},
 {"accept-encoding", "gzip, deflate, sdch, br"},
 {"accept-language", "en-US,en;q=0.8,pt;q=0.6"}]
```

Please investigate the client configuration and see if there is a way to ask it to send cookies.

**Comment by mikker** [comment]
@josevalim From @chrismccord on IRC:

> "By default, fetch won't send any cookies to the server, resulting in unauthenticated requests if the site relies on maintaining a user session."

**Comment by chrismccord** [comment]
This fix for others that run into this, using the js `fetch` api is to include the `credentials` key, which will wire up the cookie headers for you:

`fetch("/some-path", {credentials: "same-origin"})...`
