### ISSUE TITLE
Introduce current_path and current_url

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2002]
Today those need to be built by hand. See [discussion here](https://elixirforum.com/t/how-to-get-the-current-url/2390/6).

**Comment by Psli** [comment]
+1

**Comment by chrismccord** [comment]
@josevalim should these by default encode conn.query_params, with optional 2nd argument that allows explicit params?

**Comment by uzairaslam196** [comment]
But in case I need keys within request url, there is no any way to get it.
For example:
I need path in this way “/teams/:team_id/user_teams/:id”, but `conn.request_path` and `current_path` gives like this “/teams/2/user_teams/1”
