### ISSUE TITLE
Apache`s RewriteEngine analogue for Plug.Static

### ISSUE THREAD

**Issue by sintro** [phoenixframework/phoenix#2004]
Is it possible to make something like Apache's RewriteEngine rules (remember that `.php` and `.html` removing) using default Phoenix server stack ? I am looking for any solution, how to serve my static `index.html` file without hitting the Phoenix (probably, only by Cowboy webserver, without touching the Phoenix routing). Every suggested solution I have found in web either use something like rendering html in controller (and this is too bad decision because I am not only walk through all the plugs in Phoenix, but also spend time to read the file and generate the html), or doing redirect to static `index.html` from `root` route's path. And then it appears like `localhost:4000/index.html` (if I serve the file as static in ) in address bar, while I need `localhost:4000` Plug.Static, like:
```
plug Plug.Static,
    at: "/", from: :vision_nfc, gzip: false,
    only: ~w(css fonts index.html images js favicon.ico robots.txt)
```
This task is easily solved in apache and nginx, but how to do it with default Cowboy server + Phoenix app?

**Comment by josevalim** [comment]
You can see how Plug.Static is implemented but mostly what it does is to call the `Plug.Conn.sendfile` (which is likely the syscall Apache and Nginx use too) so you can implement something similar and plug it at the top of your endpoint. Also, 
please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
