### ISSUE TITLE
Error: Compiling web/static/js/socket.js

### ISSUE THREAD

**Issue by MCarroll** [phoenixframework/phoenix#2006]
After a setting up a generic phoenix install and then running the mix phoenix.server I get the following output and error messages: 

⋊> /u/l/w/spa mix phoenix.server                                        10:43:25
[info] Running Spa.Endpoint with Cowboy using http://localhost:4000
19 Nov 10:46:10 - **error: Compiling of web/static/js/socket.js failed. /usr/local/package.json: Error while parsing JSON - Unexpected end of JSON input**
19 Nov 10:46:10 - **error: Compiling of web/static/js/app.js failed. /usr/local/package.json: Error while parsing JSON - Unexpected end of JSON input**
19 Nov 10:46:10 - info: compiled 2 files into app.css, copied 3 in 1.3 sec

The app run when you go to http://localhost:4000 and produces the following error in the browser console:  Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:4000/js/app.js

Seems to be a separate issue than what is described here: https://github.com/phoenixframework/phoenix/issues/1410 

### Environment

* Elixir version (elixir -v): 1.3.4
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 7.1.0
* NPM version (npm -v): 4.0.2
* Operating system: OS X 10.12

**Comment by josevalim** [comment]
Do you have a file at "/usr/local/package.json"? If so, what is in it? Can you remove it?

More importantly, but probably not directly related to your setup, why is node/npm/brunch trying to load it?

**Comment by MCarroll** [comment]
Yes and it is empty.

Have made no changes to default basic install.  As vanilla as it can be.

Ok deleted "/usr/local/package.json" and it compiles with no errors and no console errors.

Thanks
