### ISSUE TITLE
Sending Email Guide

### ISSUE THREAD

**Issue by haslinger** [phoenixframework/phoenix#2008]
The templates in the guide fail for me to compile as long they are not renamed to *.eex,
so welcome.text.eex, welcome.html.eex email.html.eex email.text.eex are the correct names.

**Comment by optikfluffel** [comment]
There's already an [open PR at phoenixframework/phoenix_guides](https://github.com/phoenixframework/phoenix_guides/pull/625).

**Comment by haslinger** [comment]
Right, thanks, so let's close this here.
