### ISSUE TITLE
conn.remove_ip is always 127.0.0.1

### ISSUE THREAD

**Issue by paragasu** [phoenixframework/phoenix#2009]
### Precheck
I am running phoenix behind nginx proxy and setup according to the suggested configuration
as mention in the docs [Phoenix behind proxy](http://www.phoenixframework.org/docs/serving-your-application-behind-a-proxy)

### Environment

* Elixir 1.3.3
* Phoenix 1.2.1
* NodeJS v5.12.0
* NPM version 3.3.4
* Operating system: Linux 4.8.0-1-amd64, Debian Jessie

### Expected behavior

I have a controller code as below,
```
def create(conn, %{"scammer" => scammer_params}) do
    remote_ip = Enum.join(Tuple.to_list(conn.remote_ip), ".")`
end
```
Will return current user remote IP address

### Actual behavior
Always return  `127.0.0.1` every time.

**Comment by josevalim** [comment]
We don't perform IP rewriting automatically because doing so without an actual proxy is a security risk. Here is a discussion with snippets and projects you could use: https://github.com/elixir-lang/plug/issues/319
