### ISSUE TITLE
(Phoenix.Router.NoRouteError) no route found for GET /phoenix/live_reload/socket/websocket

### ISSUE THREAD

**Issue by satb** [phoenixframework/phoenix#2010]
After creating a new app without brunch or html and starting it up after install, we get this debug message constantly printed to the console

"(Phoenix.Router.NoRouteError) no route found for GET /phoenix/live_reload/socket/websocket"

```
$ mix phoenix.new testapp --no-brunch --no-html
$ cd testapp
testapp $ mix ecto.create
testapp $ mix phoenix.server
[info] Running Testapp.Endpoint with Cowboy using http://localhost:4000
[info] GET /phoenix/live_reload/socket/websocket
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /phoenix/live_reload/socket/websocket (Testapp.Router)
    (testapp) web/router.ex:1: Testapp.Router.match_route/4
    (testapp) web/router.ex:1: Testapp.Router.do_call/2
    (testapp) lib/testapp/endpoint.ex:1: Testapp.Endpoint.phoenix_pipeline/1
    (testapp) lib/plug/debugger.ex:123: Testapp.Endpoint."call (overridable 3)"/2
    (testapp) lib/testapp/endpoint.ex:1: Testapp.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

^C
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution

```

Environment:
```
elixir -v
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.4
```

**Comment by josevalim** [comment]
What is your Phoenix version?

**Comment by satb** [comment]
Phoenix version 1.2.1
```
defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"}]
  end
```

**Comment by chrismccord** [comment]
Is it possible you have an "old" app running in another tab that included html support? That would explain the logs. If not, can you push your test app to a public repo so we can take a look? Thanks!

**Comment by satb** [comment]
@chrismccord - Thank you. You are right. There is a tab open with an old app. Sorry for the trouble.

**Comment by nikolal** [comment]
I am getting the same issue and I don't have another app running.
I deleted an app with the same name before I created new one with --no-html flag.

**Comment by Echoes93** [comment]
Same here:
  `render_errors: [view: AppWeb.ErrorView, accepts: ~w(json)]`
Tried multiple of times, didn't manage to make it work properly. 
ErrorView is standard:
`
  def render("404.json", _assigns) do
    %{errors: %{detail: "Page not found"}}
  end

  def render("500.json", _assigns) do
    %{errors: %{detail: "Internal server error"}}
  end
`

**Comment by leodaher** [comment]
@nikolal did you manage to solve your problem? I am facing this same issue.

**Comment by TakaKeiji** [comment]
This issue is still present in 2023...

```
mix phx.new apitest --database sqlite3 --no-html --no-assets --no-mailer --no-dashboard --no-gettext
```

And getting...
```
[info] GET /phoenix/live_reload/socket/websocket
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /phoenix/live_reload/socket/websocket (ApitestWeb.Router)
```

Environment:
```
elixir -v
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.15.4 (compiled with Erlang/OTP 26)
```

Mix deps:
```
defp deps do
    [
      {:phoenix, "~> 1.6.15"},
      {:phoenix_ecto, "~> 4.4"},
      {:ecto_sql, "~> 3.6"},
      {:ecto_sqlite3, ">= 0.0.0"},
      {:telemetry_metrics, "~> 0.6"},
      {:telemetry_poller, "~> 1.0"},
      {:jason, "~> 1.2"},
      {:plug_cowboy, "~> 2.5"}
    ]
  end
```

No extra stuff running in the background, no extra projects, just this clean setup of phoenix is giving me this periodic message.
