### ISSUE TITLE
NoRouteError when get css file

### ISSUE THREAD

**Issue by Ljzn** [phoenixframework/phoenix#2011]
### Environment

* Elixir version (elixir -v): 1.2
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 7.1.0
* NPM version (npm -v): 3.10.9
* Operating system: ubuntu 16.04 64

### Actual behavior
in `layout/app.html.eex`
```
<link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
```

in `brunch-config.js`
```
  stylesheets: {
      joinTo: "css/app.css",
      order: {
        after: ["web/static/css/app.css"] 
      }
```

when run `mix phoenix.server`
```
[info] GET /css/web/static/css/app.css
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /css/web/static/css/app.css (Elmtp.Router)
    (elmtp) web/router.ex:1: Elmtp.Router.match_route/4
    (elmtp) web/router.ex:1: Elmtp.Router.do_call/2
    (elmtp) lib/elmtp/endpoint.ex:1: Elmtp.Endpoint.phoenix_pipeline/1
    (elmtp) lib/plug/debugger.ex:123: Elmtp.Endpoint."call (overridable 3)"/2
    (elmtp) lib/elmtp/endpoint.ex:1: Elmtp.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

But in the browser everything just good.

**Comment by Ljzn** [comment]
in `endpoint.ex`
```
  plug Plug.Static,
    at: "/", from: :elmtp, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)
```

I tried delete the `_build` and `node_modules`, but still have that error.

**Comment by h1u2i3** [comment]
Try browse your site  in private (chrome, Ctrl + Shift + n),  this error may be caused by a browser 
plugin.

**Comment by Ljzn** [comment]
I removed `<link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">`, and use CDN, then no more error.

**Comment by chrismccord** [comment]
The path is odd, in that it includes web/static. Can you provide steps to recreate the error or put this a minimal project on GitHub that displays the error so we can help further?

**Comment by Ljzn** [comment]
@chrismccord  ok. https://github.com/Ljzn/static_css_error

**Comment by josevalim** [comment]
I cannot reproduce it in the given repo. I see:

    <link rel="stylesheet" href="/css/app.css">

Can you possibly try to figure out what is trying to access "/css/web/static/css/app.css"?

**Comment by Ljzn** [comment]
@josevalim  I updated my elixir version from 1.4.0-dev to 1.5.0-dev yesterday, then the error disappeared. I don't know whether they are related. 

Sorry, I can't reproduce the error. Please close this issue.

**Comment by dischoen** [comment]
If you're interested, I had the same error  today (2021), 
I tracked it down to nodejs installed in ubuntu20. the error disappeared when I switched to nodejs 15.7.0 via asdf.

elixir 1.11.2
erlang 23.0
nodejs 10.19.0 (ubuntu 20..04)

This seems to be the root:

ERROR in ./css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Object.entries(...).flatMap is not a function
    at flattenColorPalette (/home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/tailwindcss/lib/util/flattenColorPalette.js:8:83)
    at /home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/tailwindcss/lib/plugins/divideColor.js:27:53
    at plugins.forEach.plugin (/home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/tailwindcss/lib/util/processPlugins.js:69:5)
    at Array.forEach (<anonymous>)
    at _default (/home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/tailwindcss/lib/util/processPlugins.js:63:11)
    at /home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/tailwindcss/lib/processTailwindFeatures.js:64:54
    at LazyResult.runOnRoot (/home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/postcss/lib/lazy-result.js:355:26)
    at runLoaders (/home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/webpack/lib/NormalModule.js:316:20)
    at /home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/dieter/learning/pragstudio-liveview-pro-code/lsystemnode/assets/node_modules/postcss-loader/dist/index.js:103:7)
 @ ./js/app.js 4:0-24
