### ISSUE TITLE
mix phoenix.gen.model generating wrong module names.

### ISSUE THREAD

**Issue by klintmane** [phoenixframework/phoenix#2012]
### Environment

* Elixir version (elixir -v): 1.3.4
* Phoenix version (mix deps): 1.2.1
* Operating system: W10

### Expected behavior
In a directory named `issue_1`, `mix phoenix.gen.model` should generate model modules named `Issue1.Modelname`, similar to `mix phoenix.new`.

### Actual behavior
The generated modules are instead named like `Issue_1.Modelname` resulting in a compilation error of `module Issue_1.Web is not loaded and could not be found`.

**Comment by kelvinst** [comment]
Well, this looks like a real problem. I will open a pull request for it soon.

**Comment by kelvinst** [comment]
Sorry, do you have the whole command you are running on the generator?

**Comment by kelvinst** [comment]
Well, just looking a little bit for the code, this is already fixed on master. More specifically on [this commit](https://github.com/phoenixframework/phoenix/commit/94344be3421c34ac316147e3d2d3414e1e74c67d).

**Comment by klintmane** [comment]
I hope it helps, but I found this is also the case when using `mix phoenix.routes`.

**Comment by josevalim** [comment]
@klintmane the commit above would also have fixed it for `mix phoenix.routes`. Thank you @kelvinst for checking and @klintmane for reporting.
