### ISSUE TITLE
Phoenix app interplay between conform and plug initialization: *.conf settings are not applied

### ISSUE THREAD

**Issue by smoes** [phoenixframework/phoenix#2014]
### Environment

* Elixir version (elixir -v): Elixir 1.3.3, Erlang OTP 18
* Phoenix version (mix deps): 1.1
* NodeJS version (node -v): v5.1.0
* NPM version (npm -v): 3.3.12
* Operating system: OSX

### Expected behavior

We are using conform to generate a pretty configuration file for our client. 
The client can change the `url.scheme` from http to https. Depending on that, we want Plug.Session to use secure headers (via `secure: Application.get_env(...)...[:scheme] == "https"`). The expected behavior is, that when *.conf in the released app is changed (conform), the Plug.Session configuration can be changed... 

### Actual behavior

..., however, it can't. We managed to find the slight difference: When reading the value defined in the *.conf file in a plug initialization it is nil. We managed to create a work around for our own plug, passing a callback instead of the scheme itself. At that later point in execution the value defined in *.conf is available as expected. How can it be achieved in a user-configurable manner?  

This issue is posted in this repo since it seems to be an issue with the interplay of the different components in the framework.

**Comment by josevalim** [comment]
I am not sure if this is a Phoenix issue. Isn't the difference related to compile time? I.e. when your application is being compiled, you haven't yet loaded the conform configuration and therefore the value is still nil?

**Comment by smoes** [comment]
Thank you one more time for your very fast response @josevalim . Regarding your question, I don't know. Is/or can Application.get_env be evaluated at compile time? Since, if I put a value in prod.exs in the config folder this value is taken instead of nil and it works like a charm (however, this value can not be set by our customers).

**Comment by josevalim** [comment]
@smoes what is in your config/config.exs is read before compiling but i am not sure how it plays with conform.

**Comment by chrismccord** [comment]
Closing since we have not heard back with more info to move forward. Thanks!
