### ISSUE TITLE
Problem to response with status without boy

### ISSUE THREAD

**Issue by mrkaspa** [phoenixframework/phoenix#2016]
I got this in my code  to respond a http request api

```
put_status(conn, :ok)
```

When I run controller test works fine but when I go to a http client an try to get that response this appears

```
12:00:17.145 [error] #PID<0.2874.0> running Gateway.Endpoint terminated
Server: localhost:4000 (http)
Request: PUT /api/worker_vehicle/10/service/371/take
** (exit) an exception was raised:
    ** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection
        (plug) lib/plug/adapters/cowboy/handler.ex:42: Plug.Adapters.Cowboy.Handler.maybe_send/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by chrismccord** [comment]
You need to send a response. If you want to send an empty response, you need to do:

```elixir
conn
|> put_status(:ok)
|> send_resp("")
```

In the future please follow the issue template. thanks!

**Comment by mrkaspa** [comment]
@chrismccord thanks, it's just weird that in unit tests this doesn't crash

**Comment by chrismccord** [comment]
You didn't provide your unit test code, but it's likely because you were calling the controller directly which is just a functional call and doesn't itself send a response.

**Comment by mrkaspa** [comment]
probably it's
