### ISSUE TITLE
Umbrella application with multiple code reloaders causes compilation failures

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#2017]
In one of our applications, a 404 error was resulting in a recompilation that would fail. I am able to replicate this 100% of the time in my private application. I have yet to replicate it outside of this app.

It would fail with an error that looked like:

```
== Compilation error on file web/controllers/user_controller.ex ==
** (MatchError) no match of right hand side value: {:error, :enoent}
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

@fishcakez helped me debug the issue using `dbg` (thanks @fishcakez <3) which lead to this (tracing the File.cd! call):

```
(<0.2882.0>) call 'Elixir.File':'cd!'(<<"/home/gazler/broken_app/apps/my_web">>,#Fun<Elixir.Mix.Project.2.132385615>) ({'Elixir.Mix.Dep',
                                                                                                                                 in_dependency,
                                                                                                                                 3})
(<0.2735.0>) call 'Elixir.File':'cd!'(<<"/home/gazler/broken_app/apps/my_web/apps/notifier">>,#Fun<Elixir.Mix.Project.2.132385615>) ({'Elixir.Mix.Dep',
                                                                                                                     in_dependency,
                                                                                                                     3})
```

You can see that it is trying to navigate to an app in the umbrella inside of another app in the umbrella (`apps/my_web/apps/notifier` should be `apps/notifier`)

This is caused by the Phoenix code reloader ( https://github.com/phoenixframework/phoenix/blob/e2da4a8e50d80abbe6392137673152624ec3326d/lib/phoenix/code_reloader/server.ex#L105 which calls https://github.com/elixir-lang/elixir/blob/7c84e97a7107765343b20a75be217237d4da55f0/lib/mix/lib/mix/dep.ex#L162)

I have verified this is the issue by disabling code reloading in all but one of my phoenix applications in the umbrella.

One suggested fix is to ensure that there is only one code reloader active at once. However I wasn't sure if the issue should be fixed in Phoenix or Mix. @josevalim @chrismccord

**Comment by josevalim** [comment]
It has already been fixed in master. :) https://github.com/phoenixframework/phoenix/commit/32b84e260df08f71642c526e4b8b1b7ec6959fa0
