### ISSUE TITLE
Using the generator boolean fields are really big

### ISSUE THREAD

**Issue by pedromig** [phoenixframework/phoenix#2022]
### Environment

* Elixir version (elixir -v): 1.3.4
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 7.1.0
* NPM version (npm -v): 3.10.9
* Operating system: Ubuntu 16.04

If you use the html generator like this:

`
$ mix phoenix.gen.html Budget budgets name:string must_use_all_votes:boolean allow_comments:boolean
`

The generated form has really big checkboxes because they shouldn't have the form-control class.

I believe this could be fixed replacing in the file lib/mix/tasks/phoenix.gen.html.ex 

`
 {key, :boolean} ->
120	        {label(key), ~s(<%= checkbox f, #{inspect(key)}, class: "form-control" %>), error(key)}
`

with

`
 {key, :boolean} ->
120	        {label(key), ~s(<%= checkbox f, #{inspect(key)}, class: "checkbox" %>), error(key)}
`

And fixing the associated tests.

I know experienced developers won't use the generators, but for newcomers like me first impressions are valued so this should be fixed. If you consider this to be a valid issue I can submit a pull request with my suggested fix.

### Expected behavior

Using the html generator with a boolean field, in the web form the checkbox should be of regular size.

![check2](https://cloud.githubusercontent.com/assets/2277878/20868228/29b6007a-ba4e-11e6-8f01-0940aaec46b6.png)

### Actual behavior

When using the the generator with a boolean field, the checkbox is really big as is shown here.

![checkbox](https://cloud.githubusercontent.com/assets/2277878/20868162/b2aba08a-ba4c-11e6-9413-cc63178a1eda.png)

**Comment by josevalim** [comment]
@pedromig good catch. Can you please send a PR?

**Comment by bossyang** [comment]
According to [Bootstrap docs](http://getbootstrap.com/css/#forms), the _checkbox_ input element should be wrapped by _label_ and a _div_ with class _checkbox_.
```html
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
```
Therefore, I have to manually change code as follows from
```eex
  <div class="form-group">
    <%= label f, :is_admin, class: "control-label" %>
    <%= checkbox f, :is_admin, class: "form-control" %>
    <%= error_tag f, :is_admin %>
  </div>
```
To
```eex
  <div class="checkbox">
    <label>
    <%= checkbox f, :is_admin, class: "form-control" %> Is Admin?
    </label>
    <%= error_tag f, :is_admin %>
  </div>
```

Is there a better way?

**Comment by josevalim** [comment]
@bossyang we would need to change the generators to generate the proper tag upfront. A PR similar to the one @aesmail sent is welcome.

**Comment by OvermindDL1** [comment]
Would something like this work though?
```elixir
  <div class="form-group">
    <%= label f, :is_admin, class: "control-label", do:
      checkbox f, :is_admin, class: "form-control" %>
    <%= error_tag f, :is_admin %>
  </div>
```elixir
Or this:
  <div class="form-group">
    <%= label f, :is_admin, class: "control-label" do %>
      <%= checkbox f, :is_admin, class: "form-control" %>
    <% end %>
    <%= error_tag f, :is_admin %>
  </div>
```
