### ISSUE TITLE
Getting module attribute warnings on Elixir 1.4.0-rc.0

### ISSUE THREAD

**Issue by myronmarston** [phoenixframework/phoenix#2024]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.0-rc.0 (fbfb41d)
```

* Phoenix version (mix deps):

```
* phoenix_pubsub 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (phoenix_pubsub) c31af4be
* phoenix_html 2.7.0 (Hex package) (mix)
  locked at 2.7.0 (phoenix_html) 19e12e20
* phoenix 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (phoenix) 6dc59224
* phoenix_live_reload 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (phoenix_live_reload) 829218c4
```

* NodeJS version (node -v):
N/A

* NPM version (npm -v):
N/A

* Operating system:

OS X El Capitan

### Expected behavior

I expect to be able to compile my project with `--warnings-as-errors` while using Phoenix.

### Actual behavior

After upgrading to Elixir 1.4.0-rc.0, I'm getting warnings while compiling my `web/router.ex` file:

```
warning: module attribute @phoenix_pipeline_scopes was set but never used
  web/router.ex:1

warning: module attribute @phoenix_router_scopes was set but never used
  web/router.ex:1
```

I don't actually have those module attributes in the file, but I believe they are coming from code injected by the `use MyApp.Web, :router` line (which in turn calls `use Phoenix.Router`).

We run all our CI builds with `mix compile --warnings-as-errors --force` to ensure our code base stays warning-free.  Usually this ignores warnings in dependencies like Phoenix but here Elixir considers the warning to come from our project due to the macro's code injection into our module, so we can't upgrade Elixir and keep our `--warning-as-errors` flag :(.

**Comment by josevalim** [comment]
Those are dynamically set. I believe they won't trigger on Elixir v1.4.0-rc.2 and final. Correct @chrismccord?

**Comment by chrismccord** [comment]
This is fixed on elixir's 1.4 branch, but not yet rc'd. Your best bet for now would be to not compile warnings as errors on 1.4 rc. Thanks!

**Comment by myronmarston** [comment]
Great, thanks!

**Comment by chrismccord** [comment]
I can confirm the warnings are gone on Elixir's v1.4 branch, so they should be fixed in the next released rc.1
