### ISSUE TITLE
Route changes when cheangeset is invalid

### ISSUE THREAD

**Issue by zimt28** [phoenixframework/phoenix#2026]
### Environment

* Elixir version (elixir -v): 1.3.2
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 6.2.1
* NPM version (npm -v): 3.9.3
* Operating system: macOS Sierra 10.12.1

### Expected behavior
I've use Phoenix' generators to create a resource:

```elixir
resources "/user_accounts", UserAccountController
```

When editing or creating an entry, and the changeset isn't valid, I'd expect the URL to stay the same:

```
http://localhost:4000/user_accounts/06ec8e95-77ea-4102-9dae-e08cc6d77ef4/edit

                   ----> invalid input ----> redirects to

http://localhost:4000/user_accounts/06ec8e95-77ea-4102-9dae-e08cc6d77ef4/edit
```

### Actual behavior

In the case described above I still get the correct screens, but the URLs change as follows:

```
http://localhost:4000/user_accounts/06ec8e95-77ea-4102-9dae-e08cc6d77ef4/edit

                   ----> invalid input ----> redirects to

http://localhost:4000/user_accounts/06ec8e95-77ea-4102-9dae-e08cc6d77ef4
```
```
http://localhost:4000/user_accounts/new

                   ----> invalid input ----> redirects to

http://localhost:4000/user_accounts
```

**Comment by josevalim** [comment]
Yes, that's by design since Phoenix adopts a REST-ish design on its router where operations are done on the resource with proper HTTP verb.
