### ISSUE TITLE
Channels broadcast fastlane is not configurable

### ISSUE THREAD

**Issue by studzien** [phoenixframework/phoenix#2028]
### Environment

* Elixir version (elixir -v): 1.3.3
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): v4.3.2
* NPM version (npm -v): 2.14.12
* Operating system: Amazon Linux AMI 2016.09

### Expected behavior

`config/config.exs`:
```elixir
config :app_name, AppName.Endpoint,
  pubsub: [name: AppName.PubSub,
           adapter: Phoenix.PubSub.PG2,
           fastlane: nil]
```

trace of a pubsub adapter initialization:
```erlang
(<0.224.0>) call 'Elixir.Phoenix.PubSub.PG2':init(['Elixir.Encs.PubSub',
 [{pool_size,1},
  {name,'Elixir.Encs.PubSub'},
  {adapter,'Elixir.Phoenix.PubSub.PG2'},
  {fastlane,nil}]])
```

### Actual behavior

`config/config.exs`:
```elixir
config :app_name, AppName.Endpoint,
  pubsub: [name: AppName.PubSub,
           adapter: Phoenix.PubSub.PG2,
           fastlane: nil]
```

trace of a pubsub adapter initialization:
```erlang
(<0.224.0>) call 'Elixir.Phoenix.PubSub.PG2':init(['Elixir.Encs.PubSub',
 [{fastlane,'Elixir.Phoenix.Channel.Server'},
  {pool_size,1},
  {name,'Elixir.Encs.PubSub'},
  {adapter,'Elixir.Phoenix.PubSub.PG2'},
  {fastlane,nil}]])
```

This seems to be introduced by #1501 
Since this PR includes tests for calls of `Local.broadcast` with `nil` as a `fastlane` and this code path seems to be unreachable in a component test (after applying appropriate configuration), I'm assuming that this is not an expected behaviour.

**Comment by josevalim** [comment]
@studzien If you are starting it via the endpoint, then the fastlane configuration you pass will be ignored. You can always start it manually in your supervision tree and then just give the name to the endpoint configuration if you don't want this behaviour.

We are also working on another project where the fastlane configuration is moved exclusively to dispatch time as it should help clear some things up.
