### ISSUE TITLE
Update help for phoenix.new

### ISSUE THREAD

**Issue by LTheGreats** [phoenixframework/phoenix#2038]
### Environment

* Elixir version (elixir -v): 1.3.4
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): v7.2.0
* NPM version (npm -v): 3.10.9
* Operating system: Ubuntu Linux 16.04 LTS

### Expected behavior
I expected `mix help phoenix.new` to say something like:
```
Creates a new Phoenix project.

It expects the path of the project as argument.

┃ mix phoenix.new PATH [--module MODULE] [--app APP]

A project at the given PATH will be created. The application name and module
name will be retrieved from the path, unless --module or --app is given.

Options

  • --app - the name of the OTP application
  • --module - the name of the base module in the generated skeleton
  • --database - specify the database adapter for ecto. Values can be
    postgres or mysql. Defaults to postgres.
    ...
```

### Actual behavior
Instead on the area that had ` • --database` I got:
```
• --database - specify the database adapter for ecto. Values can be
    postgres, mysql, mssql, or mongodb. Defaults to postgres.
```
And that should change because Ecto 2.0 and above does not support mssql and mongodb any more.

**Comment by curtisault** [comment]
Why is ecto dropping support for mssql? Now that mssql can be installed on Linux/macOS via docker, I had intended to start taking a look at getting an instance of mssql working with Elixir.

**Comment by josevalim** [comment]
Agreed @LTheGreats. We should do this after #1927 is merged.

@curtisault Ecto is not dropping support for mssql but rather there is no adapter ready for Ecto 2.0. I have heard of some folks working on it, hopefully it will be out there sooner than later.

**Comment by LTheGreats** [comment]
:+1:
