### ISSUE TITLE
Add ability to conditionally plug based on action name

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#204]

**Comment by johnsinco** [comment]
Did this ever get integrated into Phoenix?  We were looking for something along these lines to handle situations like 
```
plug Authenticate, only: :create
````

**Comment by Gazler** [comment]
@johnsinco You can do this in a controller:

```elixir
plug Authenticate when action in [:create]
```

**Comment by taylorbrooks** [comment]
@Gazler Where is the documentation for using `when action in [:create]`?

I'd love to read more around this.

**Comment by Gazler** [comment]
@taylorbrooks http://hexdocs.pm/phoenix/Phoenix.Controller.Pipeline.html#summary
