### ISSUE TITLE
Brunch is hammering my pitiful laptop

### ISSUE THREAD

**Issue by rschooley** [phoenixframework/phoenix#2043]
Observation 1: killing the phoenix server process with cmd+c leaves a brunch process watching (can get many going)
Observation 2: having brunch running is giving my laptop heartburn

I realize this is not a phoenix thing, but as a core dependency to running phoenix, and that there are orphaned processes when killing the server, I thought I would post here before being thrown out of Brunch's issue tracker.

### Environment

* Elixir version (elixir -v): Elixir 1.3.4
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): v7.2.1
* NPM version (npm -v): 3.10.9
* Operating system: macOS Sierra 10.12.2

### Expected behavior
My laptop not to sound like a hovercraft.

### Actual behavior
My laptop is an older Air.  I reluctantly have to add the disclaimer: I can Rails on this laptop.  Now that is out of the way, node is just wrecking my CPU and fan.

This only starts once I start `mix phoenix.server`, starts a few seconds in, then it takes off.  This is with a basic hello world phoenix app.  

Any thoughts on what to do here would be awesome, thanks.

You can see here how I have 4 brunches running, and the havoc they bring.  Even having one will eventually destroy my poor laptop.

![screen shot 2016-12-24 at 10 44 02 pm](https://cloud.githubusercontent.com/assets/473595/21469649/e1ef3cfa-ca2b-11e6-8c3f-b57b9a332c36.png)

![screen shot 2016-12-24 at 10 44 24 pm](https://cloud.githubusercontent.com/assets/473595/21469650/eb5347b4-ca2b-11e6-9221-ad484c71fbd2.png)

**Comment by josevalim** [comment]
You should not have four brunch running but only one. For some reason, they were not killed by the time Phoenix terminated. If you kill the brunch runners and make sure only one is running, does it have acceptable performance? Then it would be interesting to try to reproduce the cases where brunch does not terminate when the server terminates.

Can you please let us known your brunch version?

**Comment by rschooley** [comment]
Oh I know what it is, this isn't in the hello world app I have (disinformation).  I followed a post to get  sass-brunch to work with an app.scss, and that causes the app to compile the assets nonstop.

```
25 Dec 23:16:18 - info: compiling
25 Dec 23:16:22 - info: compiling.
25 Dec 23:16:26 - info: compiling..
25 Dec 23:16:30 - info: compiling...
```

I will go back and figure out how to make that work.

My bad, nothing to see here, move along, move along.  (thanks for the quick reply)
