### ISSUE TITLE
Channel topic not matching when MIX_ENV=prod

### ISSUE THREAD

**Issue by olieidel** [phoenixframework/phoenix#2052]
### Environment

* Elixir version (elixir -v): 1.3.4
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): v7.2.0
* NPM version (npm -v): 3.10.9
* Operating system: OSX 10.11.6

### Expected behavior
Connect to a Phoenix Channel in production (MIX_ENV=prod).

### Actual behavior
When I start the server in dev mode, it works, however with MIX_ENV=prod, it doesn't match and I get:
```
17:05:51.133 [warn] Ignoring unmatched topic "meters" in EidelSolar.UserSocket
```

I'm pretty much going crazy because I can't understand why it works flawlessly when MIX_ENV=dev..
Any hint how I can debug this further?

Keep up the awesome work with Phoenix, it's truly a joy to work with. Happy New Year!

user_socket.ex
```
defmodule EidelSolar.UserSocket do
  use Phoenix.Socket

  channel "meters", EidelSolar.MetersChannel

  transport :websocket, Phoenix.Transports.WebSocket
  # transport :longpoll, Phoenix.Transports.LongPoll

  def connect(_params, socket) do
    {:ok, socket}
  end
  def id(_socket), do: nil
end
```

endpoint.ex
```
...
socket "/socket", EidelSolar.UserSocket
...
```

ChannelStore.js
```
import { observable, action } from 'mobx'
import { ws_url } from '../config'
import { Socket } from 'phoenix'

class ChannelStore {
  socket;
  metersChannel;
  metersStore;

  connect = () => {
    this.socket = new Socket(ws_url, {}) // ws_url = '/socket'
    this.socket.connect()
    this.metersChannel = this.socket.channel('meters', {})
    this.metersChannel.join()
    this.metersChannel.on('new_data', this.handleNewMeterData)
  }

  handleNewMeterData = (data) => {
    this.metersStore.update(data)
  }

  @action setMetersStore = (metersStore) => {
    this.metersStore = metersStore
  }
}

const channelStore = new ChannelStore()
export { channelStore }
```

**Comment by josevalim** [comment]
Just for sanity check purposes, what happens if you rename the channel to "meters:main"? It should not matter but worth checking. If that still fails, we will need a sample application that reproduces the error to further investigate it.

Happy New Year!

**Comment by olieidel** [comment]
It gets even weirder. I changed the channel topic back to "meters" and now it still works.

I suspect I might have missed a "MIX_ENV=prod mix compile" step in the first place, could this be a valid explanation?

Anyway, I do suspect that the problem was somehow related to something I did and not the Channel Implementation of Phoenix.

**Comment by josevalim** [comment]
> I suspect I might have missed a "MIX_ENV=prod mix compile" step in the first place, could this be a valid explanation?

Yes, it would be.

**Comment by josevalim** [comment]
Oops, premature send. I am glad this is solved!

**Comment by tcoopman** [comment]
Just a FYI I had this same issue and triggering a recompile fixed it. No idea why it failed in the first place though...
