### ISSUE TITLE
Phoenix.gen.html should generate put/patch for edit updates. no route found for POST /users/1

### ISSUE THREAD

**Issue by nico-amsterdam** [phoenixframework/phoenix#2053]
Maybe in the past it was allowed to use POST for updates, but now that doesn't work anymore.
I use Elixir 1.3, Phoenix 1.2, Phoenix_html 2.9.1, Ubuntu 16.04
The command used to generate:
   mix phoenix.gen.html User users name address date_of_birth:datetime number_of_children:integer notifications_enabled:boolean

In router.ex, I added: resources "/users", UserController
Notice that there is NO user_path POST /users/:id in my phoenix.routes:

                 user_path  GET     /users                               PhoenixExample.UserController :index
                 user_path  GET     /users/:id/edit                      PhoenixExample.UserController :edit
                 user_path  GET     /users/new                           PhoenixExample.UserController :new
                 user_path  GET     /users/:id                           PhoenixExample.UserController :show
                 user_path  POST    /users                               PhoenixExample.UserController :create
                 user_path  PATCH   /users/:id                           PhoenixExample.UserController :update
                            PUT     /users/:id                           PhoenixExample.UserController :update
                 user_path  DELETE  /users/:id                           PhoenixExample.UserController :delete

Creating a new user works, but when edit is selected, a 'no route found for POST /users/1' is thrown when you push the submit button.
Of course the HTML form cannot use PUT, PATCH, DELETE, but there is a hidden _method field that should be filled with the intended method.

MY FIX:
------
After generating I changed web/templates/user/form.html.eex line 1:
<%= form_for @changeset, @action, @options, fn f -> %>

in edit.html.eex the options parameters is added:
<%= render "form.html", changeset: @changeset,
action: user_path(@conn, :update, @user),
options: [method: "put"] %>  

and in new.html.eex the options parameters is added:
<%= render "form.html", changeset: @changeset,
action: user_path(@conn, :create),
options: [method: "post"] %>

----
I kindly request to change your generator templates.

**Comment by chrismccord** [comment]
phoenix_ecto will look at the changeset and determine the correct http method. Are you positive you didn't change the generated controller code that constructs the changeset? Can you try running the html generator again and seeing if you get the same behavior? Thanks!

**Comment by josevalim** [comment]
Phoenix never allowed to use POST for updates. We automatically figure it out based on changeset. So either the data being given to the changeset did not come from the database or there is something else happening. An application that reproduces the error would help us investigate this.

**Comment by nico-amsterdam** [comment]
I didn't expect a response this Sunday! HAPPY NEW YEAR!!!

I misunderstood how this works, and I should have told you that I was using ecto_mnesia.
Anyway, to be certain I checked-out my project in a different directory, and surprisingly that one worked.
Back to my old project, what finally worked was:
   mix deps.update ecto_mnesia
which upgraded ecto_mnesia from 0.6.5 to 0.6.10

I was a little bit misguided by 'mix deps.get' which outputs at the end:
  All dependencies up to date
but my dependency with ecto_mnesia is defined like this:
   {:ecto_mnesia, github: "Nebo15/ecto_mnesia", ref: "master"}

I guess it is a good practice to run 'mix deps.update --all' once in awhile. 
For example feeder_ex has a dependency with feeder ~> 2.0 and mix.deps.update upgraded feeder from 2.0.1 to 2.1.0
