### ISSUE TITLE
Generating release: ** (CaseClauseError) no case clause matching: :eacces

### ISSUE THREAD

**Issue by raarts** [phoenixframework/phoenix#2054]
### Environment

* Elixir version (elixir -v): `1.3.4`
* Phoenix version (mix deps): `1.2.1`
* NodeJS version (node -v): `v7.2.0`
* NPM version (npm -v): `3.10.9`
* Operating system:  `Darwin Rons-MacBook-Air.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64`

### Expected behavior

I followed the manual for advanced deployment: http://www.phoenixframework.org/docs/advanced-deployment, up to generating the release, and then I did: 

$ `MIX_ENV=prod mix release`

Expecting to get a release.

### Actual behavior

I received the following error:
```
Building release with MIX_ENV=prod.
** (CaseClauseError) no case clause matching: :eacces
    lib/exrm/utils/utils.ex:110: ReleaseManager.Utils.relx/5
    lib/mix/tasks/release.ex:339: anonymous fn/4 in Mix.Tasks.Release.do_release/1
    lib/ex_unit/capture_io.ex:146: ExUnit.CaptureIO.do_capture_io/2
    lib/ex_unit/capture_io.ex:119: ExUnit.CaptureIO.do_capture_io/3
    lib/mix/tasks/release.ex:338: Mix.Tasks.Release.do_release/1
    lib/mix/tasks/release.ex:78: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Googling around suggested running this command with sudo. But I can't give software root access without knowing why it needs it, especially in this case, as it should only be building a release.

**Comment by josevalim** [comment]
I would recommend opening an issue in the exrm project or trying distillery, which supersedes exrm: https://github.com/bitwalker/distillery (there is already a task to update the guides to distillery 😃 ).

**Comment by raarts** [comment]
Oh gee, almost starting to feel like Javascript fatigue.. ;-) 
Just for reference there is an open issue on exrm: #[401](https://github.com/bitwalker/exrm/issues/401)
