### ISSUE TITLE
Creating new project Brunch fails to install.

### ISSUE THREAD

**Issue by natemacinnes** [phoenixframework/phoenix#2064]
### Environment

* Elixir version (elixir -v): 1.4.0
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 7.4.0
* NPM version (npm -v): 4.0.5
* Operating system: macOS 10.12.2

### Expected behavior

`$ mix phoenix.new project` should create new vanilla project without errors.

### Actual behavior
When the above command is performed the following error occurs:

```bash
* error command failed to execute, please run the following command again after installation: "npm install && node node_modules/brunch/bin/brunch build"
```
After having ensured that brunch is installed globally:
`$ npm install brunch -g`

And cd'ing into the project, running `$ npm install && node node_modules/brunch/bin/brunch build` results in:

```bash
npm ERR! addLocal Could not install /Users/camel/Development/blog/si_blog/deps/phoenix
npm ERR! addLocal Could not install /Users/camel/Development/blog/si_blog/deps/phoenix_html
...
npm ERR! enoent ENOENT: no such file or directory, open '/Users/camel/Development/blog/si_blog/deps/phoenix'
```

Hoping I could be pointed in the right direction.

Thanks!

**Comment by natemacinnes** [comment]
mix deps.get had not been run and resolved the issue.

**Comment by rajatpunkstaa** [comment]
Even I'm having same issues. 
`Fetch and install dependencies? [Yn] Y
* running mix deps.get
* error command failed to execute, please run the following command again after installation: "mix deps.get"
* running npm install && node node_modules/brunch/bin/brunch build
* error command failed to execute, please run the following command again after installation: "npm install && node node_modules/brunch/bin/brunch build"`
Can anyone knows how to fix this ? 
I tried running `mix deps.get` again but it doesn't work.
I'm using Elementary OS Loki

**Comment by rajatpunkstaa** [comment]
Even I'm having same issues. Here's a log of my terminal :
` Fetch and install dependencies? [Yn] Y 
running mix deps.get
error command failed to execute, please run the following command again after installation: "mix deps.get"
running npm install && node node_modules/brunch/bin/brunch build
error command failed to execute, please run the following command again after installation: "npm install && node node_modules/brunch/bin/brunch build" `

Can anyone knows how to fix this ? I tried running `mix deps.get` again but it doesn't work.
I'm using Elementary OS 0.4.1 Loki

**Comment by kingshalaby** [comment]
I had the same issue, solution was:
- installing brunch globally: sudo npm install brunch -g
- under the web project, run: mix deps.get
- npm install && node node_modules/brunch/bin/brunch build
