### ISSUE TITLE
Static assets are not compiled during tests

### ISSUE THREAD

**Issue by dipth** [phoenixframework/phoenix#2068]
### Environment

* Elixir version (elixir -v): 1.3.4
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): v4.6.2
* NPM version (npm -v): 4.1.1
* Operating system: Linux semaphore-1611 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior

When running acceptance tests on a clean CI instance that hasn't run the project before like so:

```
MIX_ENV=test mix local.hex --force
MIX_ENV=test mix deps.get
MIX_ENV=test mix ecto.create ecto.migrate
npm install
mix test
```

I would expect the acceptance tests to be able to load compiled static assets just like in dev

### Actual behavior

The static assets are not compiled and any references to static assets (app.js for instance) will result in a 404 during acceptance tests, causing tests that depend on javascript behaviour to fail.

**Comment by josevalim** [comment]
@dipth in development assets are compiled by setting up a watcher that notices file system changes and acts accordingly. You can either enable the watcher for tests or explicitly call `brunch build` in your CI or in your test_helper.exs. The idea here is that Phoenix doesn't do anything to compile your assets, the code is all in your app, so you should change your config or your test helper or your CI stack accordingly.
