### ISSUE TITLE
mix test should in some way reset the test database

### ISSUE THREAD

**Issue by Valentin-Seehausen** [phoenixframework/phoenix#2072]
Hey, first of all thank you for the awesome work you did and this great framework.

I found an issue that is irritating: Any change to a schema won't effect the test database.

`mix ecto.rollback` and `mix ecto.reset` do only effect the dev database (which actually makes sense).

`MIX_ENV=test ecto.reset` does reset the test database.

What is irritating from a silly user flow (I took myself as an example): You start your application, prepare it with mix ecto.create (because Phoenix tells you so after creation). And after a while, when you test different schema variants, you wonder why the test database does not update.

What could be a solution? One could update in mix.exs:

`"test": ["ecto.create --quiet", "ecto.migrate", "test"]`

But that if one would reset the database on every test, that would take too long.

Jep, just wanted to mention it, because there was a discussion two years ago. (https://github.com/phoenixframework/phoenix/issues/951). Also I was not the only one with this issue. https://elixirforum.com/t/rollback-test-database/1158/4

Maybe just warn the user somehow? Give a hint in reset or rollback, which database was affected?

Kind regards

**Comment by Valentin-Seehausen** [comment]
https://github.com/elixir-ecto/ecto/issues/1924

**Comment by Valentin-Seehausen** [comment]
https://github.com/elixir-ecto/ecto/issues/1924

**Comment by josevalim** [comment]
Ecto 2.1 ships with tasks to dump and load a schema dump, maybe we can change the test tasks to rely on that instead. So this is worth considering exploring.

However, if those do not work, I think always including the cost of dumping/creating/migrating the database is too prohibitive. We will see.

**Comment by Troush** [comment]
I don't think that we are need to add this by default to `test` flow.
The cost of recreating database each run will negatively effect hot-tests runs that are common in current ecosystem and will require developers to manually turn it off.
But on other side you can currently modify your mix tasks as you wish and if you have a use cases to do this in not default way
