### ISSUE TITLE
mix phoenix.digest.clean should probably call build_structure

### ISSUE THREAD

**Issue by aaronjensen** [phoenixframework/phoenix#2074]
`mix phoenix.digest` [calls `Mix.Project.build_structure()`](https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phoenix.digest.ex#L46-L50) after it digests to ensure that what is generated in priv is copied to _build.

Should we also call it after `mix phoenix.digest.clean` so that things deleted in priv will also be deleted in _build?

**Comment by josevalim** [comment]
Yes please!

**Comment by aaronjensen** [comment]
Ok, I'll fix that and a few other nasty bugs in digest.clean. Pull request coming soon.
