### ISSUE TITLE
Can't build phoenix Windows 7 SSL Errors

### ISSUE THREAD

**Issue by arthurchipdean** [phoenixframework/phoenix#2078]
I am behind a proxy which rewrites the ssl certificates. This causes mix to fail whenever it fetches dependencies. I was able to use the solution described here: https://github.com/hexpm/hex/issues/137 for a while but recently I'm getting errors when trying to run `mix phoenix.server`.

I ran:
` mix phoenix.new test_phoenix`
`cd test_phoenix/`
`HEX_UNSAFE_HTTPS=1 mix deps.get && npm i`

Everything proceeds normally up until this point so I'm not including the output. 

Now when I do `mix phoenix.server` I get this error ( the error remains even if I try to use HEX_UNSAFE_HTTPS ):

```
$ HEX_UNSAFE_HTTPS=1 mix phoenix.server
===> Fetching pc ({pkg,<<"pc">>,<<"1.4.0">>})

=ERROR REPORT==== 1-Feb-2017::10:25:07 ===
SSL: certify: ssl_handshake.erl:1523:Fatal error: unknown ca
===> Plugin pc not available. It will not be used.
===> Fetching rebar3_hex ({pkg,<<"rebar3_hex">>,<<"3.0.0">>})

=ERROR REPORT==== 1-Feb-2017::10:25:07 ===
SSL: certify: ssl_handshake.erl:1523:Fatal error: unknown ca
===> Plugin rebar3_hex not available. It will not be used.
===> Fetching pc ({pkg,<<"pc">>,<<"1.4.0">>})

=ERROR REPORT==== 1-Feb-2017::10:25:08 ===
SSL: certify: ssl_handshake.erl:1523:Fatal error: unknown ca
===> Plugin pc not available. It will not be used.
===> Fetching rebar3_hex ({pkg,<<"rebar3_hex">>,<<"3.0.0">>})

=ERROR REPORT==== 1-Feb-2017::10:25:08 ===
SSL: certify: ssl_handshake.erl:1523:Fatal error: unknown ca
===> Plugin rebar3_hex not available. It will not be used.
===> Fetching pc ({pkg,<<"pc">>,<<"1.4.0">>})

=ERROR REPORT==== 1-Feb-2017::10:25:08 ===
SSL: certify: ssl_handshake.erl:1523:Fatal error: unknown ca
===> Plugin pc not available. It will not be used.
===> Fetching rebar3_hex ({pkg,<<"rebar3_hex">>,<<"3.0.0">>})

=ERROR REPORT==== 1-Feb-2017::10:25:08 ===
SSL: certify: ssl_handshake.erl:1523:Fatal error: unknown ca
===> Plugin rebar3_hex not available. It will not be used.
===> Compiling fs
===> Unable to run pre hooks for 'compile', command 'compile' in namespace 'pc' not found.
** (Mix) Could not compile dependency :fs, "escript.exe "z:/.mix/rebar3" bare compile --paths "c:/Users/adean/Desktop/elixir/test_phoenix/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile fs", update it with "mix deps.update fs" or clean it with "mix deps.clean fs"
```

I'm using:
Windows 7 64 bit
Erlang/OTP 19 [erts-8.0] [64-bit] [smp:4:4] [async-threads:10] Elixir 1.3.4
Phoenix 1.2.1
Node 6.5.0
Npm: 4.0.2

### Expected behavior
I should be able to build a phoenix project without errors.

### Actual behavior
I get ssl errors described above.

**Comment by chrismccord** [comment]
Can you run `mix local.rebar` and then retry? Also, this may be related to Erlang 19.1. I believe a fix for 19.2 included ssl issues. Can you try url 19.2 and report back? Thanks!

**Comment by OvermindDL1** [comment]
> I am behind a proxy which rewrites the ssl certificates.

Uhh... that will most certainly fail in a *LOT* of circumstances.  Wtf?

I'd bet what is happening is the proxy is rewriting them to older unsupported SSL certificates, which the newer Erlang is rightfully disallowing due to major security issues.  But still, a proxy should *NOT* be doing that...

**Comment by arthurchipdean** [comment]
Ok after uninstalling and reinstalling several times I got it to work with Erl 19.2. Oddly enough it still fails with the same error if I try to go into the test_phoenix folder that was generated yesterday with the old version. Generating a new phoenix app now compiles and launches successfully though. Thanks!
