### ISSUE TITLE
Endpoint config documentation not matching code

### ISSUE THREAD

**Issue by lukaszsamson** [phoenixframework/phoenix#2083]
The [docs](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html) state that:

> Runtime configuration, instead, is accessed during or after your application is started and can be read **and written** through the config/2 function...

However the implementation supports only reading
`def config(key, default \\ nil) do`
`  case :ets.lookup(__MODULE__, key) do`
`    [{^key, val}] -> val`
`    [] -> default`
`  end`
` end`

### Environment

* Phoenix version (mix deps): 1.2.1

**Comment by chrismccord** [comment]
Good catch! Can you send a doc PR to fix this? Thanks!
