### ISSUE TITLE
Cannot connect to application in production mode.

### ISSUE THREAD

**Issue by bkochendorfer** [phoenixframework/phoenix#209]
I am following the walkthrough guide and the app does not seem to listen when running in production mode.

``` bash
%    MIX_ENV=prod PORT=4001 elixir -pa _build/prod/consolidated -S mix phoenix.start
==> ranch (compile)
==> cowlib (compile)
==> cowboy (compile)
lib/yodel/controllers/users.ex:4: warning: variable conn is unused
Compiled lib/yodel/controllers/pages.ex
Compiled lib/yodel/controllers/users.ex
Compiled lib/yodel/views.ex
Compiled lib/yodel.ex
Compiled lib/yodel/supervisor.ex
Compiled lib/yodel/config/config.ex
Compiled lib/yodel/views/pages.ex
Compiled lib/yodel/views/layouts.ex
Compiled lib/yodel/config/test.ex
Compiled lib/yodel/config/prod.ex
Compiled lib/yodel/config/dev.ex
Compiled lib/yodel/router.ex
Generated yodel.app
Running Elixir.Yodel.Router with Cowboy on port 4001
```

Curl fails

``` bash
% curl localhost:4001
curl: (7) Failed connect to localhost:4001; Connection refused
```

Nothing listening on that interface

``` bash
% lsof -i :4001 | wc -l
       0
```

**Comment by Chipairon** [comment]
Hi @chrismccord ,
I am trying to deploy an application to production using the steps outlined on the guide (http://www.phoenixframework.org/v0.9.0/docs/deployment).

I start the application with `/path/to/release/bin/my_app start` and I am getting the same problem described here (connection refused).

On my dev machine I am able to connect using your suggestion about protocol consolidation:
```
MIX_ENV=prod mix compile.protocols
MIX_ENV=prod PORT=4001 elixir -pa _build/prod/consolidated -S mix phoenix.server
```

But what is the recommended approach to start the application on a production environment?

**Comment by josevalim** [comment]
Release do not work with Phoenix. Instead of building a release, maybe it would be best to run it in production as you are running on your dev machine (which is completely fine).

**Comment by josevalim** [comment]
To be more precise, releases do not support environment variables, and we use them. If you hardcode the port you want to run in production in your config/config.exs file, it should be fine.

**Comment by chrismccord** [comment]
> Release do not work with Phoenix.

To be clear, releases should work fine, but you need to make sure your configurations supports it by setting `server: true` for your endpoint and make your port `{:system, "PORT"}`

**Comment by josevalim** [comment]
The {:system, "PORT"} thing only works on master.

**Comment by Chipairon** [comment]
Thanks for the quick replies :heart: 

I am serving the app from a subdomain on port 80 behind an nginx proxy so I followed this guideline (http://www.phoenixframework.org/v0.9.0/docs/serving-your-application-behind-a-proxy)
Turns out the app works fine if I do NOT put any port option on url.
```
 config :phoenix, TwitterRt.Endpoint,                                                                                                                                                                              
   url: [host: "sub.domain.com"],                                                                                                                                                                       
   http: [port: 4000],
```

But fails with connection refused if I do:
```
 config :phoenix, TwitterRt.Endpoint,                                                                                                                                                                              
   url: [host: "sub.domain.com", port: 80],                                                                                                                                                                       
   http: [port: 4000],
```

Note: This is happening on phoenix version 0.9.0 
In version 0.10.0 it works equally well with and without `port: 80` on the url configuration.

**Comment by josevalim** [comment]
Oh wow, the fact it doesn't work with the `url[:port]` is a very weird bug as it should not affect the server at all.
