### ISSUE TITLE
JavaScript LongPoll fallover

### ISSUE THREAD

**Issue by Thomas101** [phoenixframework/phoenix#2098]
### Environment

* Elixir version (elixir -v): 1.4.1
* Phoenix version (mix deps): 1.2
* NodeJS version (node -v): 6.9.2
* NPM version (npm -v): 3.10.9
* Chrome 56.0.2924.87

Hi,

I've noticed that when you setup the Socket to use LongPoll rather than WebSocket if the server returns a non-json response the client lib ends up failing to parse and crashes which means it never reconnects. In our case it was when the server went down briefly, nginx would return a html 502 page which causes the client to die and then it would never reconnect. When using WebSocket, this isn't a problem. Here's the code we used...

```js
socket = new Socket(url, { })
socket.transport = LongPoll
socket.connect()
```

...here's the error we get...

![err](https://cloud.githubusercontent.com/assets/103586/23020857/f6fbdd1c-f440-11e6-9b27-e9cf82ee07cc.png)

I was looking at opening a pull request, but wasn't sure what the right option was or whether this should even be fixed in the client. The code that's failing is the `Ajax.parseJSON` call which is being called from either `Ajax.xhrRequest` or `Ajax.xdomainRequest`.

The options I was looking at were...

1.) Changing the server to return a blank response, which would return `null` on the client.
2.) Checking the http status code for a 200-type response and returning `null` if the http code is erroneous. This could have backwards compatibility problems though as someone may be using a http error status and still returning valid json. XDomainRequest doesn't support reading the http status code.
3.) Running the `JSON.parse` in `Ajax.parseJSON` in a try catch and returning `null` on exception.

I was going to suggest number 3 to maintain backwards compatibility and resilience against the server returning non-json data. Happy to take guidance on this though.

Thanks!

**Comment by chrismccord** [comment]
Fixed via your 3rd option. Thanks for reporting!
