### ISSUE TITLE
(Mix) Could not compile dependency :fs

### ISSUE THREAD

**Issue by jasonzoladz** [phoenixframework/phoenix#2102]
### Environment

* Elixir version (elixir -v): `1.42`
* Phoenix version (mix deps): `1.2.1`
* NodeJS version (node -v): `6.9.4`
* NPM version (npm -v): `4.3.0`
* Operating system: `OS X 10.12.2`

### Expected behavior

```bash
$ mix phoenix.new someapp
$ cd someapp
$ mix phoenix.server
``` 
...should start a server.

### Actual behavior

`** (Mix) Could not compile dependency :fs`

### Things I've already tried

* This stuff:  `You can recompile this dependency with "mix deps.compile fs", update it with "mix deps.update fs" or clean it with "mix deps.clean fs"`

* Everything mentioned [HERE](https://elixirforum.com/t/phoenix-basic-setup-error/3189/15), including:

```bash
$ mix local.rebar
$ rm -rf _build
$ mix phoenix.server
```

### Aside

EDIT:  SEE @chrismccord comment below.
~~The onboarding experience is pretty bad with Phoenix -- which is saying a lot, as I currently have Haskell in production.~~

**Comment by josevalim** [comment]
Can you please include the full stacktrace and error message that around "** (Mix) Could not compile dependency :fs"?

**Comment by jasonzoladz** [comment]
```bash
==> fs (compile)
Compiling c_src/mac/cli.c
In file included from c_src/mac/cli.c:2:
In file included from c_src/mac/cli.h:4:
c_src/mac/common.h:5:10: fatal error: 'CoreServices/CoreServices.h' file not found
#include <CoreServices/CoreServices.h>
         ^
1 error generated.
ERROR: compile failed while processing /Users/able/Learning/Elixir/rumbl/deps/fs: rebar_abort
** (Mix) Could not compile dependency :fs, "/Users/able/.mix/rebar compile skip_deps=true deps_dir="/Users/able/Learning/Elixir/rumbl/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile fs", update it with "mix deps.update fs" or clean it with "mix deps.clean fs"
```

And, yes, I bought your book.  :)

**Comment by jasonzoladz** [comment]
Btw, I do, in fact, have `CoreServices/CoreServices.h` on my system.

**Comment by chrismccord** [comment]
> The onboarding experience is pretty bad with Phoenix -- which is saying a lot, as I currently have Haskell in production.

Other than this dependency issue, are there other factors that makes your experience "pretty bad"? In the interim you could forgo live-reloading in dev and remove the `phoenix_live_reload` dependency, as well as the following two lines from your endpoint.ex:

    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader

That should get you up and running in the meantime. I've never seen this particular error building fs so it's going to be difficult to track down.

**Comment by josevalim** [comment]
Based on this: http://stackoverflow.com/questions/5720039/g-on-mac-os-x-coreservices-h-error What does `gcc -v` return on your system?

**Comment by jasonzoladz** [comment]
@chrismccord, Thanks for the workaround.

The particular error seems to be the same as noted [HERE](https://elixirforum.com/t/phoenix-basic-setup-error/3189/6).  (See comment by PESHWAR on January 8th.)

Re: onboarding... A minor factor is opacity in the setup process.  The installation and getting started mentions nothing about the other programs (_e.g._: hex, rebar) that you are prompted to install.  Should I install them?  What are they?  Why am I installing them?  (I can find these answers after digging around.  But it's less than ideal.)

The larger factor is that I can't seem to find materials on using Phoenix without all the macro magic.  (I'm not against using them in future, but I want to _understand_ what's going on first.)  Obviously, I can go read the source, but there really ought to be documentation that shows you how to build basic Phoenix app without all the magic.  "Plugs are just functions... " Got it.  But how exactly does this plug magic hang together?  I was hoping to find that information it in the "Programming Phoenix" book.  But it's not there :(

**Comment by jasonzoladz** [comment]
@josevalim 
I'm using Apple's clang.  Here's the output from `gcc -v`:

```bash
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by chrismccord** [comment]
> A minor factor is opacity in the setup process. The installation and getting started mentions nothing about the other programs (e.g.: hex, rebar) that you are prompted to install. Should I install them? What are they? Why am I installing them? (I can find these answers after digging around. But it's less than ideal.)

The official installation guides cover these issues. For example, "If we have just installed Elixir for the first time, we will need to install the Hex package manager as well. Hex is necessary to get a Phoenix app running (by installing dependencies) and to install any extra dependencies we might need along the way." Did you go thru the guides? 
http://www.phoenixframework.org/docs/installation

> The larger factor is that I can't seem to find materials on using Phoenix without all the macro magic... I was hoping to find that information it in the "Programming Phoenix" book. But it's not there

We spend a good portion of the book explaining plug and exactly detailing how the plug pipeline that phoenix builds is just functions.

We also demystify the "magic" in our plug guide http://www.phoenixframework.org/docs/understanding-plug

Additionally, it's not clear what all you interpret as "macro magic". Our router indeed heavily uses macros, which builds your plug pipeline for your otherwise generic elixir application. If there are areas that you feel aren't explained well, please open an issue on the guides so we can improve. Thanks!

**Comment by jasonzoladz** [comment]
Thanks so much for the "understanding-plug" link.  I missed it somehow. That's exactly what I was looking for.

**Comment by jasonzoladz** [comment]
@josevalim If you think of anything that I might do to work around this issue and get hot reloading working on a mac, please let me know.  I'll move over to Ubuntu for now.

**Comment by jasonzoladz** [comment]
Thanks for taking time to respond.  I appreciate it.  Closing this for now (as I don't think Phoenix/Elixir is for me and you're likely to have other/higher bugfix priorities).

**Comment by davidsilvasmith** [comment]
Restarting per https://github.com/synrc/fs/issues/44 fixed this issue for me.
