### ISSUE TITLE
phoenix default page should be responsive

### ISSUE THREAD

**Issue by nhooyr** [phoenixframework/phoenix#2103]
### Expected behavior
When scaling down the default phoenix framework page, it should respond appropriately to screen resizes. However, it does not. It looks awkward when resizing to a small size.

### Actual behavior
![screen shot 2017-02-19 at 3 19 40 am](https://cloud.githubusercontent.com/assets/10180857/23100556/4eaeded4-f652-11e6-98a7-049186a626d0.png)

The logo gets clipped and the `Get Started` part ends up above the logo.

**Comment by josevalim** [comment]
Someone please send a PR that improves this in case someone is using the Phoenix page as a template. We probably need to scale the logo and make sure it sits on top of the menu.

**Comment by josevalim** [comment]
Closing it in favor of the PR #2105!
