### ISSUE TITLE
Provide a good way to test changesets validation errors in Phoenix v1.3

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2104]
See: https://elixirforum.com/t/assertion-with-in-failed-changeset-errors/3758

**Comment by chrismccord** [comment]
Perhaps Phoenix.Ecto could expose a basic errors_on function?

**Comment by josevalim** [comment]
@chrismccord I don't like adding functions to Phoenix.Ecto because it would be another place for looking for functions, which may be already confusing between Ecto, Ecto.Changeset, Ecto.Query and Ecto.Repo. We could make it part `Ecto.Changeset`, provided we have a good naming, but it may also be a good opportunity to show how test helpers work in Phoenix (which was our original rationale for errors_on).

**Comment by wojtekmach** [comment]
> We could make it part Ecto.Changeset, provided we have a good naming

perhaps it would be overloading it too much, but we could have a default implementation of `fun` argument for `Ecto.Changeset.traverse_errors`. Otherwise, generating the helper function sounds like a good solution, people will have a place to extend this behavior to support their use cases.

**Comment by michalmuskala** [comment]
One problem I see with providing a default function to `traverse_errors/2` is naming - is like if we provided a default to `Enum.map/2`.

Other than that, I'm fine with having a default - as @wojtekmach noticed the one provided as an example could be a good one. I have copied it over into several places already, when I needed to "normalise" the errors in some way.

**Comment by josevalim** [comment]
In master.
