### ISSUE TITLE
Generated modules have incorrect namespaces when the app name ends with _{number}

### ISSUE THREAD

**Issue by pawelduda** [phoenixframework/phoenix#2109]
### Environment
* Elixir version (elixir -v): 1.4.0
* Phoenix version (mix deps): 1.2.1
* Operating system: Ubuntu 16.04 LTS

### Steps to repro:
```
$ mkdir foo_2
$ cd foo_2
$ mix phoenix.new .
$ mix phoenix.gen.model Test tests test:string
$ iex -S mix phoenix.server
```

### Expected behavior:
Module generated using `mix phoenix.gen.model` has namespace `Foo2.Test`.

### Actual behavior
Module generated using `mix phoenix.gen.model` has namespace `Foo_2.Test` (and attempts to use `Foo_2.Web` instead of `Foo2.Web`):
```elixir
# foo_2/web/models/test.ex
defmodule Foo_2.Test do
  # Foo_2.Web does not exist, Foo2.Web does
  use Foo_2.Web, :model 
   (...)
```

```
➜  foo_2 iex -S mix phoenix.server
Erlang/OTP 19 [erts-8.2] [source-fbd2db2] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Compiling 13 files (.ex)

== Compilation error on file web/models/test.ex ==
** (CompileError) web/models/test.ex:2: module Foo_2.Web is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    web/models/test.ex:2: Foo_2.Test (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I have not checked other generators but I think they might be affected as well, as the issue comes from `Phoenix.Naming.camelize/1`.

**Comment by chrismccord** [comment]
This is not reproducible in the new `phx.new` generators and we have deprecated the `phoenix.new` generator so this is no longer an issue. Thanks!
