### ISSUE TITLE
phoenix.js removing specific listener with Channel.off?

### ISSUE THREAD

**Issue by davidye** [phoenixframework/phoenix#2112]
Right now the javascript API for channels allows attaching multiple callbacks to an event:

`on(event: string, callback: (response?: any) => void): void;`

But off does not allow removing a specific callback:

`off(event: string): void;`

This would be a nice enhancement?

**Comment by chrismccord** [comment]
This is a feature request, and as the issue template states, the issue tracker is not for feature requests. Please use the phoenix-core mailing list instead. This is not something I plan on implementing as I don't think it's needed often in practice.
