### ISSUE TITLE
Allow --no-context on gen.{html, json} and allow --no-schema on gen.{html, json, context}

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2137]

**Comment by chrismccord** [comment]
what does --no-context do when generating controller code?

**Comment by josevalim** [comment]
@chrismccord I would say we generate the controller code calling the context but the missing pieces are left for the developer to fill. This can be a great way to TDD a non-Ecto context.

**Comment by mattludwigs** [comment]
@josevalim @chrismccord I was starting to work on this, and I have some code that seems to work based off of what my understanding of the requirements are. I could be misunderstanding those requirements though, so I wanted to get clarification on what you mean by:

> I would say we generate the controller code calling the context but the missing pieces are left for the developer to fill

Does this mean literally only the controller will be generated, or does this mean the controller, templates, and view (files that will live in the web directory) will only be generated. Also, I am assuming, as of right now, we are not going to be generating the Ecto schema, so would it make sense not to generate the migration as well?

**Comment by josevalim** [comment]
> Does this mean literally only the controller will be generated, or does this mean the controller, templates, and view (files that will live in the web directory) will only be generated.

All the files in web will be generated. Implementation-wise, it means we won't call `Gen.Context.copy_new_files`. :)

**Comment by mattludwigs** [comment]
Thank you for your response! I will continue working on this tomorrow afternoon/evening sometime.

**Comment by mattludwigs** [comment]
@josevalim am I correct in thinking`phx.gen.context` with the `--no-schema` flag would not generate the migration as well as the not generating the schema module?
