### ISSUE TITLE
Document the options on gen.{context, html, json}

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2138]

**Comment by chrismccord** [comment]
we reference this in the docs for html/json:

    Read the documentation for `phx.gen.schema` for more information on attributes
    and supported options.

Should we dup it in the tasks?

**Comment by josevalim** [comment]
@chrismccord I would say so. We still need the reference you pasted, because of attributes and what not, but quickly duplicating the options can provide a better overview for everyone reading the docs.
