### ISSUE TITLE
Support a context_app: :foo configuration that will properly generate contexts in umbrellas

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2139]
We can use `Mix.Project.deps_paths` to locate the filesystem path once an app name is given. `:context_app` should be generated by default on new apps.

/cc @wojtekmach

**Comment by josevalim** [comment]
See #2133 for original discussion.

**Comment by zimt28** [comment]
Will this be part of the `1.3` release?

**Comment by josevalim** [comment]
It is planned to, yes.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
Quick status update, I started looking into it but I have been pretty constrained lately and I'm not sure when I would be done. Here's my WIP branch: https://github.com/wojtekmach/phoenix/tree/wm-umbrella-context if anyone is interested in picking it up

**Comment by shankardevy** [comment]
I have a working version of this. Will send a PR shortly.

**Comment by X4lldux** [comment]
This version creates a file tree that doesn't reflect module. Creates this tree:
```
|--lib
|  |-- foo
|      |-- blog
|          |-- blog.ex   # defmodule Foo.Blog
|          |-- post.ex   # defmodule Foo.Blog.Post
```
but, shouldn't it create this tree instead?
```
|--lib
|  |-- foo
|      |-- blog
|      |   |-- post.ex   # defmodule Foo.Blog.Post
|      |-- blog.ex       # defmodule Foo.Blog
```

**Comment by josevalim** [comment]
No, we have changed to the first format on purpose to keep files neatly together.

**Comment by X4lldux** [comment]
I guess it's a matter of opinion/style, but good to know it was no mistake and there's a logic behind that 👍 😄

**Comment by ryanwinchester** [comment]
@josevalim with the new dir structure, do we name the modules:

`Foo.Blog.Blog` and `Foo.Blog.Post` to follow the convention

or `Foo.Blog` and `Foo.Blog.Post` to not look weird?
