### ISSUE TITLE
No longer generate belongs_to relationships when using references in the new generators

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2151]
Because there is a higher chance we will get the wrong module name now and because we may end-up accidentally pushing developers to have associations across contexts.

@chrismccord, what do you think?

**Comment by chrismccord** [comment]
I think this is the way to go, but I would continue to generate the belongs_to provided the context already exists and the assoc'd schema lives inside it. Yay/nay?

**Comment by chrismccord** [comment]
ah I see. :+1: to not generating belongs_to for now

**Comment by josevalim** [comment]
Fixed in master.

**Comment by dustinfarris** [comment]
Specifying "blog_posts" makes perfect sense to me.  Former Django dev here, and this all makes me feel right at home.

**Comment by dustinfarris** [comment]
Specifying `blog_posts` makes perfect sense to me.  Former Django dev here and this all makes me feel right at home.

**Comment by sobolevn** [comment]
Was confused a lot by missing `belongs_to` at first.
