### ISSUE TITLE
The generated 'belongs_to' schema module is wrong if the referenced schema is in a different context

### ISSUE THREAD

**Issue by aesmail** [phoenixframework/phoenix#2160]
When I create a schema that "belongs_to" another schema in another context, the newly generated schema includes an invalid name for the referenced schema.

Example:
`mix phx.gen.json Accounts User users name`
`mix phx.gen.json Businesses Store stores user_id:references:accounts_users slogan:string`

### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): master (commit 3345fda23608b5d3dd98319ca480dce17dfa84c4)
* NodeJS version (node -v): 6.3.1
* NPM version (npm -v): 4.1.1
* Operating system: macOS Sierra 10.12.3

### Expected behavior

The `Businesses.Store` module should include a schema with:
`belongs_to :user, MyApp.Accounts.User, foreign_key: :user_id`

### Actual behavior

The `Businesses.Store` module includes the following line:
`belongs_to :user, MyApp.Businesses.User, foreign_key: :user_id`

I'm actually not sure if what I'm doing is the right way.
Should I *NOT* link two different schemas from two different contexts?
Or is this a bug in the new generators?

I think this also might help you with #2151.

**Comment by josevalim** [comment]
Yes, that's what #2151 is about. :) We will no longer generate the belongs_to, this way you can upgrade to a relationship as necessary. Thank you!
