### ISSUE TITLE
binary-id flag doesn't work in 1.3

### ISSUE THREAD

**Issue by zimt28** [phoenixframework/phoenix#2168]
### Environment

* Elixir version (elixir -v): 1.4.0
* Phoenix version (mix deps): latest from master branch

### Expected behavior
When running `phx.new` with `--binary-id`, I'd expect Phoenix to use binary ids automatically, as this feature is [still documented](https://github.com/phoenixframework/phoenix/blob/c91443b54c8605acb69f093e6597c956c19d490f/installer/lib/mix/tasks/phx.new.ex#L36-L37).

### Actual behavior
As the schemas don't have a reference to a `web.ex` like in `1.2` anymore, the required would have to be added to each schema: 

```
@primary_key {:id, :binary_id, autogenerate: true}
@foreign_key_type :binary_id
```

Migrations would also need to be changed. Should this still be supported? It's quite simple to change this behaviour manually.

**Comment by josevalim** [comment]
It is fixed in master. :)

**Comment by kenips** [comment]
@josevalim could you please clarify that fixed here means the generator is generating the above lines correctly, and not automatically working? If that's the case this should also be documented in http://phoenixframework.org/blog/upgrading-from-120-to-130.

**Comment by PhillippOhlandt** [comment]
What's not working? My Phoenix app, generated with `1.3-rc2` works just fine with binary ids.

**Comment by itsdeezy** [comment]
@PhillippOhlandt In version 1.3-rc3, since removal of the `/web` directory and `web.exs`, you now have to explicitly state per schema your primary key and foreign key are type of binary.

**Comment by PhillippOhlandt** [comment]
I have this in my config `generators: [binary_id: true]` so the generators create a valid schema and migration.
