### ISSUE TITLE
Api don't concurrent request 

### ISSUE THREAD

**Issue by zentechnamhoang** [phoenixframework/phoenix#2169]
Hi all, I load test by Jmeter with a simple request such as: 

`def test(conn, params) do`
      `IO.inspect :calendar.local_time`
      `:timer.sleep(2000)`
     ` json conn, %{result: true}`
  `end`

I see sequential response of API. But I need to them response concurrent 
![screen shot 2017-03-07 at 10 59 39 pm](https://cloud.githubusercontent.com/assets/14228357/23665005/d5f32f28-0389-11e7-9a84-83b2b467850f.png)

Config of Jmeter
Number of threads: 10
Ramp-Up Period: 1
loop count: 1

@chrismccord 
Thanks everyone!

**Comment by josevalim** [comment]
You are sleeping for 2 seconds. So your responses will wait 2 seconds. All of the requests are sleeping concurrently, otherwise you would see responses like 2 seconds, 4 seconds, 6 seconds, etc.

**Comment by zentechnamhoang** [comment]
@josevalim, I test with another function, but I saw the after request must wait for response of the before request. Should all requests run concurrently?

`def charge(conn, params) do`
      
`      with {:ok, response} <- PaymentWrapper.charge(:default_payment, params) do`
`           json conn, %{result: true}`
`      else
`         {:error, response} ->`
`           conn = put_status conn, 400`
`            json conn, %{result: true, message: response.reason}`
`      end`
`  end`

![screen shot 2017-03-08 at 1 42 45 am](https://cloud.githubusercontent.com/assets/14228357/23672239/a0f3183a-03a0-11e7-8b2e-382ce7e74fe1.png)

**Comment by josevalim** [comment]
Yes, all requests run concurrently. Otherwise requests after the 2 seconds wait you would see requests taking 2.4 seconds and so on.

**Comment by zentechnamhoang** [comment]
Sorry, I think all request don't run concurrently. Because I test on 2 different terminals, the requests run concurrently.

![screen shot 2017-03-08 at 9 05 48 am](https://cloud.githubusercontent.com/assets/14228357/23687030/4024698e-03df-11e7-9a53-45ea805c3727.png)

If I run load test on Jmeter or same browser, request will not run concurrently. But when run different browser or terminal, then request concurrent
