### ISSUE TITLE
New Generators --binary-id switch

### ISSUE THREAD

**Issue by jamilabreu** [phoenixframework/phoenix#2177]
### Environment

* Elixir version (elixir -v): 1.4
* Phoenix version (mix deps): 1.3-dev

### Expected behavior
I believe `mix phx.new appname --binary-id` should cause generators (i.e `mix phx.gen.schema`) to set --binary-id switch to true by default.

### Actual behavior
`mix phx.new appname --binary-id` adds

`config :appname,
  ecto_repos: [AppName.Repo],
  generators: [binary_id: true]`

to `config.exs`, but `mix phx.gen.schema` doesn't generate appropriate code in schema or migration file by default (still needs --binary-id switch to generate needed code)

Needed code: `@primary_key {:id, :binary_id, autogenerate: true}; @foreign_key_type :binary_id)` in Schema and `create table(:users, primary_key: false) do / add :id, :binary_id, primary_key: true...` in migration file.

**Comment by josevalim** [comment]
I can't reproduce the bug. It works fine here. We also have a test to show that it is reading the configuration from the app environment: https://github.com/phoenixframework/phoenix/blob/master/test/mix/tasks/phx.gen.schema_test.exs#L225

What am I missing?

**Comment by josevalim** [comment]
Btw, are you sure that you are using Phoenix master?

**Comment by jamilabreu** [comment]
That was it ^, archive wasn't all the way caught up to master. :man_facepalming: Sorry!

**Comment by josevalim** [comment]
No problem! Thanks for sanity checking!
