### ISSUE TITLE
:format_encoders leaks into other Umbrella Phoenix applications

### ISSUE THREAD

**Issue by cbarratt** [phoenixframework/phoenix#2186]
In one of my Umbrella Applications I'm using the following config:
```
config :phoenix, :format_encoders,
  json: Blah.blah
```

My team has recently started working on adding another Phoenix application to the Umbrella. Upon trying to call their Controller which is using `json(conn, ...)` it was erroring trying to access `Blah.blah`.

I'm struggling to figure out how to have these configured individually :(

### Environment

* Elixir version (elixir -v): Elixir 1.4.0
* Phoenix version (mix deps): phoenix 1.3.0-rc.0
* Operating system: Mac OSX Sierra

I've omitted Node as neither Phoenix apps use brunch/node/npm

### Expected behavior
Individually configured format_encoders per Umbrella application.

### Actual behavior
Whichever configuration is loaded last seems to take precedence.

**Comment by chrismccord** [comment]
Format encoders are global configuration, so this is a known limitation. I believe pre-1.0, we discussed this and decided to wait until someone needed more flexibility... and here you are :)

I definitely think is something we should support, but we need to investigate where we rely on it and if those places have enough information to properly scope the configuration lookup.

**Comment by cbarratt** [comment]
Excellent! I'm kind of glad I wasn't missing something glaringly obvious here 😊

That sounds totally sane, I was hoping to some how specify this at the app level but realised it wasn't possible :( 

If I can be of any help, feel free to have me try things out!

Appreciate the speedy explanation!

**Comment by chrismccord** [comment]
We've decided to wait on this one, you can see the discussion here or rationale https://github.com/phoenixframework/phoenix/pull/2188#issuecomment-286732895 Thanks!

**Comment by cbarratt** [comment]
Thanks @chrismccord - I guess I understand Josè's POV totally :)

I guess my only choice will be to convert both apps to use the same JSON format_encoder (and I could specify this in the global `config/config.exs`?)

**Comment by josevalim** [comment]
@cbarratt options are:

1. use the same encoder for both and specify the configuration at the config/config.exs in the umbrella root

2. create a new `blah_json` encoder function in your controller that encodes using `blah`. Check out the `json` implementation in Phoenix, there is not much to it

3. Register blah_json and json as the format_encoders and use different extensions when desired
