### ISSUE TITLE
phoenix.js Socket reconnectTimer is not reset after disconnect()

### ISSUE THREAD

**Issue by davidye** [phoenixframework/phoenix#2187]
### Environment

* Phoenix version (mix deps): 1.2.1

### Expected behavior

The socket is not connected but is attempting to reconnect via reconnectTimer. In this state, I think it would make sense that calling socket.disconnect() resets reconnectTimer.

### Actual behavior

After calling socket.disconnect(), the socket continues trying to reconnect. I believe it is due to the following line:

https://github.com/phoenixframework/phoenix/blob/62f18c71888ce700cc86933296e619f8a9dee0be/assets/js/phoenix.js#L523

**Comment by chrismccord** [comment]
Fixed on master
