### ISSUE TITLE
Phoenix 1.3 drops headers that is set by plugs in 404 error

### ISSUE THREAD

**Issue by AndrewDryga** [phoenixframework/phoenix#2198]
When [updating to latest Phoenix](https://github.com/Nebo15/eview/pull/5/files) we noticed that on 404 errors it started to drop headers that was set by plugs like `request_id`, which was something we relied on. (We use common plug in all our projects to have well-defined response structure. There is also a [custom ErrorView](https://github.com/Nebo15/eview/blob/master/lib/eview/views/phoenix_error_view.ex) that catches all responses and makes sure that response is the same for errors.)

Look like now there are no ways to modify conn (copy headers that we need to response from `assigns.reason.conn.resp_headers` in ErrorView before sending it?

**Comment by josevalim** [comment]
Hi @AndrewDryga! Can you also please try latest plug? This is definitely a regression, so if you can try to find the root cause or provide a mechanism that reproduces the issue we will be glad to investigate further.

**Comment by AndrewDryga** [comment]
It's already using latest Plug. Ill try to dig deeper.

**Comment by AndrewDryga** [comment]
Looks like [in default 404 match](https://github.com/phoenixframework/phoenix/blob/2e3ef1fb8fb568d081c2974a84003ff7d710a166/lib/phoenix/router.ex#L328) we raise `NoRouteError` and passing there `conn` that has all information (including `before_send` and `resp_headers`), but [`RenderErrors.__catch__/5`](https://github.com/phoenixframework/phoenix/blob/2e3ef1fb8fb568d081c2974a84003ff7d710a166/lib/phoenix/endpoint/render_errors.ex#L55) receives conn that is already stripped.

**Comment by AndrewDryga** [comment]
And [in Endpoint](https://github.com/phoenixframework/phoenix/blob/da9f7653b9daf29a4c415be52a19ee6f4473e083/lib/phoenix/endpoint.ex#L630) we are passing very raw `conn` to `__catch__` so this is place where headers is lost.

**Comment by AndrewDryga** [comment]
@josevalim Looks like when we catch exception that is occurred while executing Plugs, we catch it and render error with empty `conn`. Can you suggest best way to fix it, or maybe it's expected?

Things that come in mind:
- Match `NoRouteError` in `catch` block and use conn from this struct
- Do the same, but copy only certain fields.

Also do we want `before_send` callbacks to be executed after raised error? I think so, because we might want Logger to see error..

**Comment by josevalim** [comment]
@AndrewDryga do you know why it worked before though? In Phoenix v1.2 there seems to be it would have loss of connection information too.

**Comment by AndrewDryga** [comment]
@josevalim I guess I have [found commit that](https://github.com/phoenixframework/phoenix/commit/a3834735543977c988e1cd0e78069076a464cf44#diff-8f320b1261d864714a994ecd364abaca), which removes function clause that used `reason.conn` instead of empty `conn` to render response.

Is there are specific reason for it? I guess it's useful to mutate conn on errors, changing headers and running `before_send` is a good examples.

**Comment by cmpaul** [comment]
@josevalim Was there a resolution to this? I'm seeing this same behavior after upgrading to 1.3. Just digging into it now, but this looked related (getting a `NoRouteError` instead of the 404 response we used to get).

**Comment by marklee22** [comment]
I upgraded to phoenix v1.3.3, but still seems the headers I add in my plug are dropped. I can see my module plug being called, but the headers are not preserved on the 404.

What is the proper way to preserve headers for all requests? I tried it with `before_send` too and it didn't seem to work either.

**Comment by AndrewDryga** [comment]
@marklee22 can you create a minimal repo to reproduce this issue?
