### ISSUE TITLE
css-brunch is deprecated

### ISSUE THREAD

**Issue by Aiken00** [phoenixframework/phoenix#2208]
[https://github.com/brunch/css-brunch](https://github.com/brunch/css-brunch)

> This plugin is deprecated in favor of built-in possibilities of [Brunch] (since 2.10), which can handle CSS automatically. We recommend to remove it from package.json. For css-modules use postcss-brunch.

Is phoenix going to change it in the coming 1.3 release?

**Comment by voughtdq** [comment]
AFAIK removing `css-brunch` from the `package.json` dependencies and running `npm uninstall css-brunch` does not break anything. However, I'm not sure how to formally prove this.

**Comment by josevalim** [comment]
@voughtdq thanks for the heads up. We will probably just remove it from our side as well and verify the newly geerated application works just fine. Less things to fetch from NPM is always a plus.

**Comment by chrismccord** [comment]
I have verified css-brunch is no longer required. Thanks for the heads up!
