### ISSUE TITLE
Ecto/ Generator config in Umbrella

### ISSUE THREAD

**Issue by zimt28** [phoenixframework/phoenix#2211]
When creating an umbrella application, the following is added to `apps/app_web/config/config.exs` (I created the project whith `--binary-id`)

```elixir
# General application configuration
config :app_web,
  namespace: App.Web,
  ecto_repos: [App.Repo],
  generators: [binary_id: true]
```

As Ecto isn't used in the interface directly and generators that create interface specific code don't care about the type of ids, wouldn't it make more sense to have these config options in the `apps/app/config/config.exs` file?

**Comment by josevalim** [comment]
It is there on purpose. So we run migrations automatically for you before running tests and you don't need to change between apps.
