### ISSUE TITLE
phx.gen.html produces failing tests for Decimal fields

### ISSUE THREAD

**Issue by bryanstearns** [phoenixframework/phoenix#2212]
### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): master@2b5c1e70
* NodeJS version (node -v): 7.7.3
* NPM version (npm -v): 4.1.2
* Operating system: MacOS Sierra 10.12.3

### Expected behavior

In phoenix/installer...
```
mix phx.new decimals --dev
mix phx.gen.html Game Score scores value:decimal
mix test
```
... tests would pass

### Actual behavior

Tests for the Decimal attribute fail:
```
Compiling 10 files (.ex)
Generated decimals app
...

  1) test scores update_score/2 with valid data updates the score (Decimals.GameTest)
     test/game_test.exs:41
     Assertion with == failed
     code:  score.value() == "456.7"
     left:  #Decimal<456.7>
     right: "456.7"
     stacktrace:
       test/game_test.exs:45: (test)

.

  2) test scores create_score/1 with valid data creates a score (Decimals.GameTest)
     test/game_test.exs:32
     Assertion with == failed
     code:  score.value() == "120.5"
     left:  #Decimal<120.5>
     right: "120.5"
     stacktrace:
       test/game_test.exs:34: (test)

..............

Finished in 0.2 seconds
20 tests, 2 failures

Randomized with seed 314685
```

Searching for similar issues, I found https://github.com/phoenixframework/phoenix/pull/917; I'm not sure (haven't dug into the cause) but I don't think this is Ecto's problem. I'm also not sure whether I should have the expectation that the generated tests would always pass, but it's also not obvious to me what the tested-for values should be -- as that issue points out, Decimal.new("x") isn't what would happen "in real life" either.

(I'd be happy to work on fixing this if I could get a pointer to the right direction... thanks!)

**Comment by chrismccord** [comment]
this is a bug. I'm taking care of this now. Thanks for the report!
