### ISSUE TITLE
Websocket integration tests are flaky when running in Travis CI

### ISSUE THREAD

**Issue by gradenb** [phoenixframework/phoenix#2214]

**Comment by samdvr** [comment]
@garbles can you please provide more detail so people can reproduce the issue you are seeing and fix them

**Comment by garbles** [comment]
![image](https://cloud.githubusercontent.com/assets/1139884/24683938/5bebb7de-1957-11e7-8ec6-5f56ad9182ef.png)

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please open up a new issue and make sure to fill in all the information requested in the template shown inside the text box. Thank you!
