### ISSUE TITLE
phx.gen.json not placing views and controllers in web/ directory (Phoenix 1.3)

### ISSUE THREAD

**Issue by ashutoshrishi** [phoenixframework/phoenix#2218]
### Steps
- Generate a new phoenix 1.3 app with `mix phx.new --no-html --no-brunch blah`
- Use the task `mix phx.gen.json Accounts User users name:string email:string:unique`

I am not sure if this is intended behaviour but looking at the module documentation in https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phx.gen.json.ex#L21-L26 , it states the following:
- a view in `web/views/user_view.ex`
- a controller in `web/controllers/user_controller.ex`

So I was expecting the `lib/blah/web/{controllers, views}` to be populated, but instead `lib/blah/{controllers, views}` were. The module name is correct:
`Blah.Web.UserController`

### Environment

* Elixir version: 1.4.2
* Phoenix version: 1.3.0-rc.1
* NodeJS version: v7.7.1
* NPM version: 4.1.2
* Operating system: MacOS 10.12.1

### Expected behaviour
- Expecting files `lib/blah/web/controllers/user_controller.ex` and `lib/blah/web/views/user_view.ex` to be created.

### Actual behaviour
- Controllers and views  are generated in `lib/blah/controllers/user_controller.ex` and `lib/blah/views/user_view.ex`.
- Now there are two controllers folder in `lib/blah/controllers` and the empty `lib/blah/web/controllers`.

**Comment by ashutoshrishi** [comment]
# Some Extra Information
- I am in an umbrella app. But I didn't generate it through a `phx` task. Is that why the `web/` prefix is not used?

**Comment by josevalim** [comment]
Chris, we moved the generated configuration to the umbrella config/config.
Maybe we should check if the generator namespace is configured and if not
we should generate it even for umbrella apps.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
Our generators do not use a `web/` directory for umbrella applications because they assume the phoenix application is the web application, and the business logic lives in a separate directory, so the behaviour you are seeing is expected.

**Comment by josevalim** [comment]
Reopening this as @chrismccord and I found this case should also work as "advertised". Thank you.
