### ISSUE TITLE
Channel instance initialized from constructor keep rejoining

### ISSUE THREAD

**Issue by jackalcooper** [phoenixframework/phoenix#2219]
### Environment

* Elixir version (elixir -v): Elixir 1.4.2
* Phoenix version (mix deps): 1.3rc1
* NodeJS version (node -v): 7.4.0
* NPM version (npm -v): 4.0.5
* Operating system: macOS Sierra

### Expected behavior
Channel instance initialized from constructor or  initialized by calling method of Socket instance should behave the same

### Actual behavior
Channel instance initialized from constructor keep rejoining while  instance initialized by calling method of Socket instance works well.

Here is the JavaScript code to illustrate my point:
```javascript
import {Socket, Channel, Push, Presence} from "phoenix"
let socket = new Socket("/socket", undefined)
socket.connect()
function handleReiceive(any) {
  console.log(any);
  return /* () */0;
}

let channel = new Channel("user:lobby", undefined, socket);
// let channel = socket.channel("user:lobby", {})
channel.join()
  .receive("ok", handleReiceive)
  .receive("error", handleReiceive)

export default socket
```

**Comment by chrismccord** [comment]
The `Channel`'s consturctor is private. You should only create channel instances off the socket's `channel/2` function.
