### ISSUE TITLE
mix phx.gen.html task command nests context_module.ex file inside context module folder 

### ISSUE THREAD

**Issue by dgross881** [phoenixframework/phoenix#2221]
I am going off the Lonestar Elixir keynote talk 1.3 so I'm not 100% positive this is a bug or just the new format. The mix task phx.gen.html is nesting the context_module.ex file inside the context_module folder. Should it be this way ? 

### Environment

* Elixir version (elixir -v): phoenix, "~> 1.3.0-rc" 
* Phoenix version (mix deps): mix * NodeJS version (node -v): same as mix phx.new 
* NPM version (npm -v): 4.0.5 
* Operating system: OSX

### Expected behavior
 ``mix phx.gen.html Post posts title:string body:text``

**Expected Tree**  
![screen shot 2017-03-28 at 8 56 35 pm](https://cloud.githubusercontent.com/assets/4744111/24435361/7638cf4e-13fa-11e7-9106-44663ca84fbb.png)

### Actual behavior

**Actual Tree** 
![screen shot 2017-03-28 at 8 55 24 pm](https://cloud.githubusercontent.com/assets/4744111/24435135/1b0be2a6-13f9-11e7-8d75-54c759b6fd4f.png)

**Comment by chrismccord** [comment]
Expected. Thanks!
