### ISSUE TITLE
Info about posible bug in view json rendering dates

### ISSUE THREAD

**Issue by Speedkore** [phoenixframework/phoenix#2222]
I don't know if it is fixed in the latest version, we have found an inconsistent behavior in rendering dates in iso:extended:z format. The problem is that when nanoseconds or microseconds is 0, the string renderer does not render "....17:22:22.000000z", it renders "....17:22:22z", this causes many parsers to fail in java, swift, etc because they are not all that good.

This forced us to use this hacking on every date  of any view that renders json dates for consistency Ex. 
"%{
 date: date |> Timex.set([microsecond: {0,0} ])
}"

Current versions used:
 {:phoenix, "1.2.0"},  
 {:phoenix_ecto, "3.0.1"},
 {:timex, "3.0.8"},
 {:timex_ecto, "3.0.4"},

**Comment by Speedkore** [comment]
Elixir 1.3.4
when microseconds and nanoseconds are 0, we have 2017-01-03T16:56:36Z, otherwise we have 2017-03-06T15:18:46.648569Z

**Comment by josevalim** [comment]
Ok. And they most commonly show up as .000000, right?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Speedkore** [comment]
yes, but if you have bad luck, or if you expressly insert it with 0 nanoseconds, you will have the short output

**Comment by josevalim** [comment]
Thank you. Moved here: https://github.com/elixir-ecto/ecto/issues/1935
