### ISSUE TITLE
Safari excepcion an crash

### ISSUE THREAD

**Issue by taorg** [phoenixframework/phoenix#2231]
### Environment
* Elixir version (elixir -v):Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.4.2
* Phoenix version (mix deps):
* NodeJS version (node -v): v6.9.4
* NPM version (npm -v):
* Operating system: Mac Os Sierra, iOS

### Expected behavior
No errors no crashes 

### Actual behavior
Hello it seems Safari is not great managing websockets but I think this deserves to be mended.
Specially on iOS.
It starts as drab's bug so here is the thread with all the information needed 
https://github.com/grych/drab/issues/13#issuecomment-290988144

Thanx

**Comment by josevalim** [comment]
@taorg do you get an error from the Phoenix side of things? If so, what error is it?

In any case, there isn't much we can do here if the browser suddenly closes the connection, as if you were force quitting the browser. Thank you for the report anyway!
