### ISSUE TITLE
archive.install for v1.2.3

### ISSUE THREAD

**Issue by Sly777** [phoenixframework/phoenix#2237]
Hey all,

I realise there is v1.2.3 for Phoenix, but the problem is I cannot install it via "mix archive.install" because there is no ez file of v1.2.3 on github. What can I do for this? Or how can I help?

**Comment by chrismccord** [comment]
Since the installer did not change for the .3 release, there is no need for a new mix achieve. The 1.2x installer will set `{:phoenix< "~> 1.2"}` so you are fun as is.
