### ISSUE TITLE
help screen when doing mix phoenix.new --no-ecto

### ISSUE THREAD

**Issue by LTheGreats** [phoenixframework/phoenix#2239]
### Environment

* Elixir version (elixir -v): 1.4.0
* Phoenix version (mix deps): v1.2.1
* NodeJS version (node -v): v7.2.0
* NPM version (npm -v): 3.10.9
* Operating system: Ubuntu 16.04

### Expected behavior
 When I ran `$ mix phoenix.new --no-ecto` I expected it to generate a new
phoenix application without ecto. 

### Actual behavior
When I ran `$ mix phoenix.new --no-ecto` I got the help screen.

**Comment by lsiqueira** [comment]
It's missing the project name:

`$ mix phoenix.new hello_world --no-ecto`

**Comment by chrismccord** [comment]
As @lsiqueira said, it shows the help screen because you need to include a project name, so no issue on our side. Thanks!

**Comment by LTheGreats** [comment]
Ooops.. Sorry!
