### ISSUE TITLE
Failed Web Socket Integration Test.

### ISSUE THREAD

**Issue by Afsoon** [phoenixframework/phoenix#2242]
### Environment

* Elixir version (elixir -v): 1.4.1
* Phoenix version (mix deps): 1.3.0-rc1 (Forked the last friday)
* NodeJS version (node -v): 7.3.0
* NPM version (npm -v): 3.10.10
* Operating system: OS X El Capitan 10.11.1

### Reproducing

Execute the follow command `mix test --seed 971383`.

### Expected behavior

Running `mix test --seed 971383` should pass all test, like the following execution:
![5e8420825df85aa2ddddd9edfa9ba2e2](https://cloud.githubusercontent.com/assets/713534/24850514/a999db46-1dd0-11e7-89bc-d14291a3bc71.png)

### Actual behavior

Running `mix test --seed 971383` the following test are going to fail:
![9bd26bf56b93bc8cae477dccf3812099](https://cloud.githubusercontent.com/assets/713534/24850407/4562023e-1dd0-11e7-8ffa-86ff9d2dcc25.png) 

I think this issue is related to this [Websocket integration tests are flaky when running in Travis CI #2214](https://github.com/phoenixframework/phoenix/issues/2214)

**Comment by Ljzn** [comment]
I can repeat this error. There seems some error when registering the process.

add Inspect in ` phoenix/test/phoenix/integration/websocket_test.exs`
```
    def join(topic, message, socket) do
      try do
        Process.register(self(), String.to_atom(topic))
      catch
        a, b ->
          IO.inspect a
          IO.inspect b
      end
      send(self(), {:after_join, message})
      {:ok, socket}
    end
```

run `mix test --seed 971383`

then get 
```
:error
%ArgumentError{message: "could not register the pid #PID<0.2742.0> with name :\"room:admin-lobby\". Or it is not alive, or the name is already taken, or it has already been given another name"}
```
