### ISSUE TITLE
Poison 3.0

### ISSUE THREAD

**Issue by slashmili** [phoenixframework/phoenix#2246]
Is there any chance of getting support for Poison 3.0 in Phoenix 1.2.X?

Most of projects start supporting Poison 3.0 and it's not possible to upgrade unless I upgrade to Phoenix 1.3-rc

something like 
```elixir
{:poison, "~> 1.5 or ~> 2.0 or ~> 3.0"}
```

[Poison](https://github.com/devinus/poison) doesn't have a CHANGELOG file but just by looking at the interface it looks like it's keeping the interface same as prior versions.

**Comment by josevalim** [comment]
`{:poison, "~> 3.0", override: true}` in your mix.exs in you should be fine.
