### ISSUE TITLE
Bad url in MyApp.Endpoint output when starting application

### ISSUE THREAD

**Issue by Eiji7** [phoenixframework/phoenix#2247]
### Environment

* Elixir version (elixir -v):
```elixir
Erlang/OTP 19 [erts-8.3.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.2
```
both installed using [asdf](https://github.com/asdf-vm/asdf)
* Phoenix version (mix deps):
```elixir
* phoenix 1.2.3 (Hex package) (mix)
  locked at 1.2.3 (phoenix) b68dd6a7
  ok
```
so it's latest stable Phoenix version
* NodeJS version (node -v):
**v6.9.4**
* NPM version (npm -v):
**3.10.10**
* Operating system:
```bash
# uname -a
Linux funtoo 4.4.39-gentoo #2 SMP Sun Mar 19 14:12:39 CET 2017 x86_64 Intel(R) Core(TM) i3 CPU M 370 @ 2.40GHz GenuineIntel GNU/Linux
```

### About problem
I used static IP in my Endpoint host configuration for testing locally my site with mobile device. After some time I returned to my project and I just don't remember about that change. The problem is that when I run `mix phoenix.server` then I got info:
> [info] Running MyApp.Endpoint with Cowboy using http://localhost:4000

### Steps to reproduce
0. Install latest **Erlang** and **Elixir** stable versions using **asdf** tool.
1. Follow official [installation guide](http://www.phoenixframework.org/docs/installation)
2. create new app: `mix phoenix.new my_app` and allow to fetch and install dependencies
3. in file: `config/dev.exs` change:
```elixir
# from:
http: [port: 4000],
# to:
http: [ip: ip, port: 4000],
```
where `ip` is your ip address from `ifconfig` in `Tuple` notation
4. run `mix phoenix.server` and you will see:
> [info] Running MyApp.Endpoint with Cowboy using http://localhost:4000

### Behavior
Url returned by `MyApp.Endpoint` is invalid and can mislead. Please change it to valid url that is created using current project configuration.

**Comment by josevalim** [comment]
There are two different properties. One is the ip+port that you run on, the other is the url you access it at. For example, "github.com" is how I access github but there is a machine somewhere running at a certain ip and port. Your change above is changing exactly this ip and port and it does not affect "localhost:4000". If you want to change that, change the URL configuration accordingly.

**Comment by Eiji7** [comment]
@josevalim: I know about what you said, but now I see that `localhost` is **default** host always no matter what IP I enter or what is the contents of `/etc/hosts`.
I through that it should return domain assigned to IP from `/etc/hosts` or (if not exist in this file) from **DNS** or finally return just IP as fallback, but it's simple returns it as a **default value** that I need to change manually.
