### ISSUE TITLE
mix phx.gen.context repeatly generate code in context module 

### ISSUE THREAD

**Issue by developerworks** [phoenixframework/phoenix#2249]
### Environment

* Elixir version (1.4.2):
* Phoenix version (1.3.0-rc):
 Operating system: Mac OSX

### Expected behavior

I think place generated code in the schema module is better than the context module. if i have many schema module in a context, all generated code such as `list_*`, `get_*`, `create_*` in the context module will have the context module is big. 

### Actual behavior

If type in `mix phx.gen.schema Acc User users name` twice in command line, the context module include repeated code.

**Comment by chrismccord** [comment]
The list/get/create functions are not duped if they currently exist, unmodified.
