### ISSUE TITLE
Generated brunch-config.js has incorrect links to brunch docs

### ISSUE THREAD

**Issue by smpallen99** [phoenixframework/phoenix#2253]
The follow links do not work in my project's generated brunch-config.js file. I used `mix phx.new` to generate the project.

```
https://github.com/brunch/brunch/blob/master/docs/config.md#files
https://github.com/brunch/brunch/tree/master/docs#concatenation
``` 

I think these links should be updated to point to `brunch.io`. For example `http://brunch.io/docs/config#-files`

**Comment by chrismccord** [comment]
Good catch! Can you send a PR? Thanks!

**Comment by smpallen99** [comment]
Yes, I can send a PR Chris
