### ISSUE TITLE
mix phx.gen.schema error about array type is unclear

### ISSUE THREAD

**Issue by kuon** [phoenixframework/phoenix#2257]
When creating a schema with `mix.phx.gen.schema` the `array` type support is unclear.

For example:

```
$ mix phx.gen.schema Awesome.Test awesome_tests foo:jsonb
** (Mix) Unknown type `:jsonb` given to generator. The supported types are: array, binary, boolean, date, decimal, float, integer, map, naive_datetime, references, string, text, time, utc_datetime, uuid

$ mix phx.gen.schema Awesome.Test awesome_tests foo:array
** (Mix) Unknown type `array` given to generator
```

The first error (which is expected) lists `array` as supported type, but when `array` is used as a type, it is not accepted. The first error message should inform the user about the `array:element_type` syntax.

Tested on phoenix 1.3 master installed from 3e46a129187aa6b5d0734fdae75594df496bea68

**Comment by chrismccord** [comment]
You need to pass the type of the array elements, for example ` mix phx.gen.schema Awesome.Test awesome_tests foo:array:string`. I agree we can improve the error in this case. Thanks for the report!

**Comment by kuon** [comment]
Yes I found the actual syntax in the doc. This issue is just about improving the error message, cheers!

**Comment by jeroenvisser101** [comment]
@chrismccord @gavlak this is fixed now right?
