### ISSUE TITLE
Add support for yarn 

### ISSUE THREAD

**Issue by andrewoko-odion** [phoenixframework/phoenix#2260]
npm takes too long to fetch and install node packages
I however, would be grateful to see the integration of `yarn` into the Phoenix Framework, 

Are there any plans already to add support for`yarn` the Phoenix core?

**Comment by josevalim** [comment]
@andrewoko-odion when opening up issues, **please read and fill-in the issues template**. You will notice that we ask developers to search the issues tracker to reduce the load on the Phoenix team, and, if you do so, you will find out this has been discussed in the past.

**Comment by Gazler** [comment]
https://github.com/phoenixframework/phoenix/pull/1963
