### ISSUE TITLE
Generated socket path is not consistent with comment code in pheonix.js

### ISSUE THREAD

**Issue by tony612** [phoenixframework/phoenix#2263]
I found generated socket code in [`endpoint.ex`](https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_web/endpoint.ex#L4) is 
```elixir
socket "/socket", <%= web_namespace %>.UserSocket
```

But the comment code in [phoenix.js](https://github.com/phoenixframework/phoenix/blob/master/priv/static/phoenix.js#L28) is
```
//     let socket = new Socket("/ws", {params: {userToken: "123"}})
```

It's not a big problem, but a little confusing if I try to write the js code with the comment's help especially I don't use brunch.

**Comment by chrismccord** [comment]
Fixed. Thanks!
