### ISSUE TITLE
Print generated the HTML tag in iex with correct encoding

### ISSUE THREAD

**Issue by xareelee** [phoenixframework/phoenix#2265]
I tried to print the result of `Phoenix.HTML.Link.link`:

```elixir
$ iex -S mix
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Generated rumbl app
Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> Phoenix.HTML.Link.link("Home", to: "/")
{:safe, [60, "a", [[32, "href", 61, 34, "/", 34]], 62, "Home", 60, 47, "a", 62]}
```

according to the book **Programming Phoenix**,  it should be expected as:

```elixir
{:safe, ["<a href=\"/\">", "Home", "</a>"]}
```

Is this a bug? Or the API has been changed?

**Comment by josevalim** [comment]
What we generate is actually called iolist: https://www.bignerdranch.com/blog/elixir-and-io-lists-part-2-io-lists-in-phoenix/

We don't guarantee a certain shape, only that it will be an iolist. If you want a string, you can call `Phoenix.HTML.safe_to_string` in your tests or terminal and that will always return a proper and readable format.

**Comment by xareelee** [comment]
Thanks, it works.

```elixir
iex> Phoenix.HTML.safe_to_string Phoenix.HTML.Link.link("Home", to: "/")
"<a href=\"/\">Home</a>"
```
