### ISSUE TITLE
Host cannot be configured at runtime via on_init/1

### ISSUE THREAD

**Issue by donpinkster** [phoenixframework/phoenix#2266]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2
```
* Phoenix version (mix deps): 1.3.0-rc.1
* Operating system: macOS Sierra

### Expected behavior
When I return the following in the `on_init/1` call I expect that I can GET the homepage
`{:ok, Keyword.put(config, :url, [scheme: "https", host: "localhost", port: 443])`

According to the documentation this is a runtime configuration.

### Actual behavior
When GET'ting the homepage it throws the following error
```
09:44:34.002 [info] Running MyApp.Web.Endpoint with Cowboy using http://:::8000
09:46:33.316 [error] #PID<0.493.0> running MyApp.Web.Endpoint terminated
Server: localhost:8000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in String.split/3
        (elixir) lib/string.ex:344: String.split(nil, "/", [])
        (plug) lib/plug/router/utils.ex:112: Plug.Router.Utils.split/1
        (phoenix) lib/phoenix/endpoint/supervisor.ex:190: Phoenix.Endpoint.Supervisor.script_name/1
        (phoenix) lib/phoenix/config.ex:48: Phoenix.Config.cache/3
        (elixir) lib/map.ex:646: Map.update!/3
        (MyApp) lib/MyApp/web/endpoint.ex:1: MyApp.Web.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/don/src/MyApp/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

It seems that the host is actually needed on compile time. It works when moving the configuration back into the Endpoint configuration itself.

**Comment by josevalim** [comment]
Please do:

    {:ok, Keyword.put(config, :url, [scheme: "https", host: "localhost", port: 443, path: "/"])

We will update the code to not assume the path is set.
