### ISSUE TITLE
minimal average response time

### ISSUE THREAD

**Issue by allabouts** [phoenixframework/phoenix#2277]
Hi everyone!

Am I right that minimal response time for "empty" phoenix page generation is 20 ms? (ttlb in chrome timeline)
Is it because of cowboy web-server?

**Comment by josevalim** [comment]
Can you please use the mailing list or elixir forum for discussions?  The issues tracker is for issues only.

For what is worth, I would expect a response time around 1ms if you are running on the same machine. Otherwise latency is going to be the main blocker.
