### ISSUE TITLE
recompile Failure

### ISSUE THREAD

**Issue by kobdesign** [phoenixframework/phoenix#2280]
### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v): 4.2.0
* Operating system: OSX V.10.11.16

### Expected behavior
recompile Success

### Actual behavior
I received warning message ->

warning: variable "recompile" does not exist and is being expanded to "recompile()", please use parentheses to remove the ambiguity or change the variable name
  iex:1

:noop

Thank you

**Comment by josevalim** [comment]
@kobdesign you must do as the warn says, and use `recompile()` instead of `recompile`.
