### ISSUE TITLE
Upgrade guide unclear on what to do with models

### ISSUE THREAD

**Issue by raarts** [phoenixframework/phoenix#2281]
### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): 1.3.0.rc1 
* NodeJS version (node -v): 7.9.0
* NPM version (npm -v): 4.2.0
* Operating system: OSX

### Expected behavior

They aren't even mentioned, only 'writing an upgrade guide' is mentioned.
My gen.json command generated files in an unexpected directory, not in my models directory.

### Actual behavior

This should be explained more in the Upgrade guide.

**Comment by chrismccord** [comment]
This is coming in the rework of the Phoenix guides so hang tight. Thanks!
