### ISSUE TITLE
mix phx.new - node brunch(ERROR) - windows 10/ 64 bit ( phonix 1.3.0-rc.1)

### ISSUE THREAD

**Issue by laingit** [phoenixframework/phoenix#2283]
### Environment

node -v     **v6.9.4**
npm -v      **4.1.2**
elixir -v   **Erlang/OTP 18 [erts-7.3] [64-bit] [smp:8:8] [async-threads:10]** **Elixir 1.4.0**
mix deps **phoenix 1.3.0-rc.1 (Hex package) (mix)   locked at 1.3.0-rc.1 (phoenix) 0d04948a**
Operating system: **Windows 10 /64 BIT**

E:\aprj\elixirPrj>**_mix phx.new dipgeo_**
* creating dipgeo/config/config.exs
..... (more creating)
* creating dipgeo/assets/static/favicon.ico

Fetch and install dependencies? [Yn] **Y** 
* running mix deps.get
* running mix deps.compile
* running **cd assets && npm install && node node_modules/.bin/brunch build** **(NOT WORKING -- ERROR)**
* error command failed to execute, please run the following command again after installation:

    cd assets && npm install && node node_modules/.bin/brunch build

E:\aprj\elixirPrj>**cd dipgeo**

E:\aprj\elixirPrj\dipgeo>**cd assets**

E:\aprj\elixirPrj\dipgeo\assets>**npm install**
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN assets No description

E:\aprj\elixirPrj\dipgeo\assets>**node node_modules\.bin\brunch build**  **(NOT WORKING -- ERROR)**
**(note: I am using node)**
E:\aprj\elixirPrj\dipgeo\assets\node_modules\.bin\brunch:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

E:\aprj\elixirPrj\dipgeo\assets>**node_modules\.bin\brunch build** **(WORKS -- OK)**
**(note: I am NOT using node)**
16:01:22 - info: compiled 6 files into 2 files, copied 3 in 1.5 sec

E:\aprj\elixirPrj\dipgeo\assets>

**Comment by OvermindDL1** [comment]
For note, I'm not sure why his did not work, I followed the same steps, using the standard windows command shell (nothing special), and got:
```shell
C:\Users\<user>\Projects\tmp>mix phx.new dipgeo
* creating dipgeo/config/config.exs
* creating dipgeo/config/dev.exs
* creating dipgeo/config/prod.exs
* creating dipgeo/config/prod.secret.exs
* creating dipgeo/config/test.exs
* creating dipgeo/lib/dipgeo/application.ex
* creating dipgeo/lib/dipgeo/web/channels/user_socket.ex
* creating dipgeo/lib/dipgeo/web/views/error_helpers.ex
* creating dipgeo/lib/dipgeo/web/views/error_view.ex
* creating dipgeo/lib/dipgeo/web/endpoint.ex
* creating dipgeo/lib/dipgeo/web/router.ex
* creating dipgeo/lib/dipgeo/web/web.ex
* creating dipgeo/mix.exs
* creating dipgeo/README.md
* creating dipgeo/test/support/channel_case.ex
* creating dipgeo/test/support/conn_case.ex
* creating dipgeo/test/test_helper.exs
* creating dipgeo/test/web/views/error_view_test.exs
* creating dipgeo/lib/dipgeo/web/gettext.ex
* creating dipgeo/priv/gettext/en/LC_MESSAGES/errors.po
* creating dipgeo/priv/gettext/errors.pot
* creating dipgeo/lib/dipgeo/repo.ex
* creating dipgeo/priv/repo/seeds.exs
* creating dipgeo/test/support/data_case.ex
* creating dipgeo/lib/dipgeo/web/controllers/page_controller.ex
* creating dipgeo/lib/dipgeo/web/templates/layout/app.html.eex
* creating dipgeo/lib/dipgeo/web/templates/page/index.html.eex
* creating dipgeo/lib/dipgeo/web/views/layout_view.ex
* creating dipgeo/lib/dipgeo/web/views/page_view.ex
* creating dipgeo/test/web/controllers/page_controller_test.exs
* creating dipgeo/test/web/views/layout_view_test.exs
* creating dipgeo/test/web/views/page_view_test.exs
* creating dipgeo/.gitignore
* creating dipgeo/assets/brunch-config.js
* creating dipgeo/assets/css/app.css
* creating dipgeo/assets/css/phoenix.css
* creating dipgeo/assets/js/app.js
* creating dipgeo/assets/js/socket.js
* creating dipgeo/assets/package.json
* creating dipgeo/assets/static/robots.txt
* creating dipgeo/assets/static/images/phoenix.png
* creating dipgeo/assets/static/favicon.ico

Fetch and install dependencies? [Yn] y
* running mix deps.get
* running mix deps.compile
* running cd assets && npm install && node node_modules/brunch/bin/brunch build

We are all set! Run your Phoenix application:

    $ cd dipgeo
    $ mix phx.server

You can also run your app inside IEx (Interactive Elixir) as:

    $ iex -S mix phx.server

Before moving on, configure your database in config/dev.exs and run:

    $ mix ecto.create


C:\Users\<user>\Projects\tmp>
```
Calling `node node_modules/.bin/brunch` is indeed entirely correct.  Binaries should not be called from the sub package directory...

**Comment by laingit** [comment]
It **IS** working after commit from Josè   in 1863865

**Comment by OvermindDL1** [comment]
> It IS working after commit from Josè in 1863865

Because it reverted the change, but that really should not have been necessary so it is a great question why your's is breaking as it works here on windows without issue.

**Comment by laingit** [comment]
Hi OvermindDL1, in your example (**node node_modules/brunch/bin/brunch build**) call this

Fetch and install dependencies? [Yn] y
running mix deps.get
running mix deps.compile
running cd assets && npm install && **node node_modules/brunch/bin/brunch build**

My example
running cd assets && npm install && **node node_modules/.bin/brunch build (ERROR)**

____________________________________________________________________________
**node node_modules/.bin/brunch build (this command doesn't work)** I tried this in phoenix 1.2 and 1.3

I think is something related to **node** on Windows

#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../brunch/bin/brunch" "$@"
  ret=$?
else 
  node  "$basedir/../brunch/bin/brunch" "$@"
  ret=$?
fi
exit $ret

**Comment by OvermindDL1** [comment]
That is definitely a shell file, not a node file, it should be called directly, not with node, should be called like `node_modules/.bin/brunch build`, which will work on linux/mac with the above file and will work on windows since windows calls the `brunch.cmd` file instead, which also works.  Everything in the `.bin` directory should be called straight according to my googling, should not be called with node in front.

**Comment by josevalim** [comment]
@OvermindDL1 but early windows versions do not support shebangs so we cannot simply call `node_modules/.bin/brunch build` directly (unless node guarantees to insert a brunch.cmd in there).

**Comment by OvermindDL1** [comment]
> (unless node guarantees to insert a brunch.cmd in there).

Brunch guarantees it, it is the responsibility of the library that makes the binary, and brunch does it right.  :-)

Also, a side-note, the node_modules or .bin directories can be changed globally, the proper way to get the path to the `.bin` directory is to run `npm bin` and it will output the full path for the system.  Though I doubt many actually change it.
