### ISSUE TITLE
path helper inconsistency with phx.gen.html generator

### ISSUE THREAD

**Issue by nhooyr** [phoenixframework/phoenix#2289]
After using the phx.gen.html generator, it will say:
```
Add the resource to your browser scope in lib/hello_phoenix/web/router.ex:

    resources "/users", UserController
```

Problem is that one should really be adding

```elixir
 resources "/users", UserController, as: :user
```

Because in the phx.gen.html controller template, there is this line:
https://github.com/phoenixframework/phoenix/blob/0f40dc2f20d6123fb1d8511eb5a0f47563546565/priv/templates/phx.gen.html/controller.ex#L21

```elixir
        |> redirect(to: <%= schema.route_helper %>_path(conn, :show, <%= schema.singular %>))
```

`schema.route_helper` is set at
https://github.com/phoenixframework/phoenix/blob/4420a23586712239b6cea2f0e20750f357a35b1f/lib/mix/phoenix/schema.ex#L75 as the singular name of the generated resource.

Thus, the controller is assuming that path helper is named after the singular name of the generated resource but the message from the generator is not asking the user to rename the path helper, thus the user will get an error when they try and compile phoenix after running the generator.

**Comment by josevalim** [comment]
@nhooyr I am not sure I follow. `resources "/users", UserController` will generate `user_path` as the helper name.

**Comment by nhooyr** [comment]
It does not for me. I had to add `as: :user` myself.

**Comment by nhooyr** [comment]
These are the exact commands I am running

```
mix phx.new foo
cd foo
mix phx.gen.html Accounts User users name:string email:string bio:string number_of_poets:integer
mix compile # error here
```

The error I get is:

```
❯ mix compile
Compiling 16 files (.ex)

== Compilation error on file lib/test/web/controllers/user_controller.ex ==
** (CompileError) lib/test/web/controllers/user_controller.ex:21: undefined function user_path/3
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by josevalim** [comment]
After you migrate, you need to add `resources "/users", UserController` to your own router. Have you done so?

**Comment by nhooyr** [comment]
I forgot to save that line, that is why I got the error. I'm sorry for the noise.
