### ISSUE TITLE
Error on `npm install` with `mix phx.new appname`

### ISSUE THREAD

**Issue by genya0407** [phoenixframework/phoenix#2294]
### Environment

* Elixir version (elixir -v): Elixir 1.4.2
* Phoenix version (mix deps): 1.3.0-rc.1
* NodeJS version (node -v): v7.10.0
* NPM version (npm -v): 4.2.0
* Operating system: macOS Sierra 10.12.4

### Problem

I want to create new app named `chat`.
However, `mix phx.new chat` fails with following error :

```shell
$ mix phx.new chat
* creating chat/config/config.exs
* creating chat/config/dev.exs
...
* creating chat/assets/static/images/phoenix.png
* creating chat/assets/static/favicon.ico

Fetch and install dependencies? [Yn] y
* running cd assets && npm install && node node_modules/brunch/bin/brunch build
* error command failed to execute, please run the following command again after installation:

    cd assets && npm install && node node_modules/brunch/bin/brunch build
...
```

After failing above command, I executed ` cd assets && npm install && node node_modules/brunch/bin/brunch build` manually.
However, it also failed with following errors:

```shell
> cd assets && npm install && node node_modules/brunch/bin/brunch build
npm ERR! addLocal Could not install /Users/sangenya/dev/trash/chat/deps/phoenix
npm ERR! addLocal Could not install /Users/sangenya/dev/trash/chat/deps/phoenix_html
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /Users/sangenya/dev/trash/chat/deps/phoenix
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/sangenya/dev/trash/chat/deps/phoenix'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/sangenya/dev/trash/chat/deps/phoenix'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sangenya/.npm/_logs/2017-05-14T08_48_29_092Z-debug.log
```

### Solution

After I executed `mix deps.get`, `cd assets && npm install && node node_modules/brunch/bin/brunch build` succeeded.

Maybe, it's better to stop auto-running above command, and append the command to the instruction.

For example:

```shell
...

We are all set! Run your Phoenix application:

    $ cd chat
    $ mix deps.get
    $ cd assets && npm install && node node_modules/brunch/bin/brunch build && cd ..
    $ mix phx.server

...
```

Thanks.

**Comment by josevalim** [comment]
The command works most times so we should still try to run it. The issue is
that the deps.get command failed and the error cascaded, causing the
instructions to be a bit confusing. We need to address that.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by willykaram** [comment]
@josevalim perhaps we could add a note to the Up & Running guide to clarify that if someone encounters this error, they can simply manually fets any dependencies needed after running the command and manually install brunch. I could add a comment to that effect in that guide. Alternatively, we could also create a new Bonus Guide called Troubleshooting, in which we can add a few pointers for these sorts of edge cases. The goal of either approach being to reduce friction and provide a clear solution to any of these minor issues as new users are getting up and running. 

Note there's some pretty wild answers online as to how to solve this, and a few post where people have asked this in a few places where there isn't answer. I'll try to answer those and direct them to the appropriate solution you'd prefer.

**Comment by josevalim** [comment]
> @josevalim perhaps we could add a note to the Up & Running guide to clarify that if someone encounters this error, they can simply manually fets any dependencies needed after running the command and manually install brunch

That's what the new code is doing. If any of those commands fail, we just show instructions to try it again inside the app itself, without an error message. After all, those commands are optional.

In any case, a Troubleshooting page sounds like a very good idea!

**Comment by willykaram** [comment]
As an example, just posted a suggestion solution here on S/O: https://stackoverflow.com/questions/41381652/elixir-phoenix-returns-brunch-io-error/44221521#44221521
