### ISSUE TITLE
clear_flash does not clear all references of Flash messages

### ISSUE THREAD

**Issue by wicliff** [phoenixframework/phoenix#2298]
### Environment

* Elixir version (elixir -v): 1.4.2 
* Phoenix version (mix deps): 1.2.3
* NodeJS version (node -v): 6.6
* NPM version (npm -v): 3.103
* Operating system:
MacOS

### Expected behavior
When  `clear_flash` is used on a `conn`, all flash messages accumulated until then should be cleared and no flash messages should be shown in current and future screens. 

### Actual behavior
- Flash message is cleared for the current screen
- When User visits another screen, flash message (old one, which should have been deleted) now appears

Done some digging

- `clear_flash` sets the `:phoenix_flash` to `%{}` 
-  There is another element  in conn - `:plug_session` which has key `%{ "phoenix_flash": "Old Error Message"}`

This key is not removed, and on subsequent request these values are copied to main `:phoenix_flash`

Right now, I have cleared by using `put_session(conn, "phoenix_flash", nil)` in addition to the `clear_flash`.

```
conn
|> clear_flash
|> put_session("phoenix_flash", nil)
```

Can some one check if this is a bug.

**Comment by chrismccord** [comment]
This indeed appears to are a bug. I should have a fix momentarily. Thanks for reporting!
