### ISSUE TITLE
"compile.phoenix" could not be found

### ISSUE THREAD

**Issue by gordysc** [phoenixframework/phoenix#2315]
### Environment

* Elixir version (elixir -v): 1.4.4
* Phoenix version (mix deps): 1.2.0
* NodeJS version (node -v): 7.7.3
* NPM version (npm -v): 4.6.1
* Operating system:  Mac OS Sierra 10.12.4

### Expected behavior
mix phoenix.routes should show all of my routes for my Phoenix project

### Actual behavior
I'm getting the following error:
```
** (Mix) The task "compile.phoenix" could not be found. Did you mean "compile.elixir"?
```

I can reproduce this easily if I add other dependencies, like: [comeonin](https://github.com/riverrun/comeonin), [argon2_elixir](https://github.com/riverrun/argon2_elixir), etc.

This appears to be very similar to #1766 .  Do I have to install something locally to make this compile? Is this even an issue with Phoenix? Or is it Elixir? The other libraries?  Sorry, I just started working with Phoenix yesterday and this seems a little hard to diagnose.

I am seeing this when I run `mix compile` and the part that says **-dynamiclib -undefined** makes me suspect it's the latter, but wanted to ask here first since it is complaining about `phoenix.new`:

```
mix compile
==> elixir_make
Compiling 1 file (.ex)
Generated elixir_make app
==> comeonin
mkdir -p priv
cc -g -O3 -Wall -I/usr/local/Cellar/erlang/19.3/lib/erlang/erts-8.3/include -Ic_src -fPIC -shared -dynamiclib -undefined dynamic_lookup c_src/bcrypt_nif.c c_src/blowfish.c -o priv/bcrypt_nif.so
Compiling 8 files (.ex)
Generated comeonin app
```

**Comment by josevalim** [comment]
Can you please provide us a way to reproduce the issue @gordysc? It can be a sample app that you push to GitHub. You were not supposed to need anything else to be installed. As long as you depend on Phoenix itself, you should be covered.

**Comment by gordysc** [comment]
@josevalim it's as simple as adding the above dependencies.  All I'm doing is taking a fresh project and adding any of the dependencies above and mix starts complaining about `compile.phoenix`

**Comment by josevalim** [comment]
I have tried doing just that before my comment above and I could not reproduce it. It may be something in your machine, it may not, so we need a way to reproduce it. :)

**Comment by gordysc** [comment]
Figured it out, this can be closed.  Thanks for the fast responses @josevalim!

The issue for future reference is I had the following:
```
defp deps do
   [{:phoenix, "~> 1.2.4"},
   ...
  {:cowboy, "~> 1.0"}],
  [{:comeonin, "~> 3.0"}]
```

Instead of (notice the closing bracket):
```
   [{:phoenix, "~> 1.2.4"},
   ...
  {:cowboy, "~> 1.0"},
  {:comeonin, "~> 3.0"}]
```
...stupid PEBCAK bugs...
