### ISSUE TITLE
Mix phx.new is inconsistent for umbrella projects (new vs existing)

### ISSUE THREAD

**Issue by pedroassumpcao** [phoenixframework/phoenix#2316]
### Environment

* Elixir version (elixir -v): 1.4.4
* Phoenix version (mix deps): 1.3.0-rc.2
* NodeJS version (node -v): 7.9.0
* NPM version (npm -v): 4.2.0
* Operating system: OS Sierra

### Expected behavior

When generating a new Phoenix project inside an existing umbrella app, the file structure should be the same as if I was starting a new Phoenix project as umbrella from scratch.

### Actual behavior

Running `mix phx.new app_name_web` inside `app_name/apps` generates file structure as a non-umbrella app, even mix.exs is set up as umbrella in `project/0`.

Following file structure (from /lib from the hello_web app) if I start from scratch with `--umbrella` a brand new project:

```
lib
├── hello_web
│   ├── application.ex
│   ├── channels
│   │   └── user_socket.ex
│   ├── controllers
│   │   └── page_controller.ex
│   ├── endpoint.ex
│   ├── gettext.ex
│   ├── router.ex
│   ├── templates
│   │   ├── layout
│   │   │   └── app.html.eex
│   │   └── page
│   │       └── index.html.eex
│   └── views
│       ├── error_helpers.ex
│       ├── error_view.ex
│       ├── layout_view.ex
│       └── page_view.ex
└── hello_web.ex
```

Following file structure (from /lib) if I generate a new Phoenix app inside an existing umbrella project, running the generator inside `apps` folder with `mix phx.new app_name_web`:
```
lib
└── app_name_web
    ├── application.ex
    └── web
        ├── channels
        │   └── user_socket.ex
        ├── controllers
        │   └── page_controller.ex
        ├── endpoint.ex
        ├── gettext.ex
        ├── router.ex
        ├── templates
        │   ├── layout
        │   │   └── app.html.eex
        │   └── page
        │       └── index.html.eex
        ├── views
        │   ├── error_helpers.ex
        │   ├── error_view.ex
        │   ├── layout_view.ex
        │   └── page_view.ex
        └── web.ex
```

**Comment by pedroassumpcao** [comment]
Closing this issue, the expected behavior can be achieved with `mix phx.new.web` generator inside `app_name/apps` folder. Awesome!

**Comment by chrismccord** [comment]
Yes, exactly :)
