### ISSUE TITLE
Generator doesn't produce a valid migration

### ISSUE THREAD

**Issue by loeschg** [phoenixframework/phoenix#2318]
### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): 1.3.0-rc.2
* NodeJS version (node -v): 7.2.0
* NPM version (npm -v): 3.10.9
* Operating system: 10.11.6

### Expected behavior
`mix phx.gen.json Accounts User users username:string password:string` (essentially the example suggestion)
`> mix ecto.migrate`

Expect migration to complete successfully

### Actual behavior

```
> mix ecto.migrate
Compiling 6 files (.ex)

== Compilation error on file lib/bottles_app/web/controllers/user_controller.ex ==
** (CompileError) lib/bottles_app/web/controllers/user_controller.ex:18: undefined function user_path/3
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
in web/controllers/user_controller.ex
```
```
   14   def create(conn, %{"user" => user_params}) do
   15     with {:ok, %User{} = user} <- Accounts.create_user(user_params) do
   16       conn
   17       |> put_status(:created)
✖  18       |> put_resp_header("location", user_path(conn, :show, user))
   19       |> render("show.json", user: user)
   20     end
   21   end
```

**Comment by chrismccord** [comment]
Do you follow the console output and add the `resources ...` route to your router? If so, can you provide the route that you added? It looks like you skipped a step :) Thanks!

**Comment by loeschg** [comment]
ugh. Sorry for the noise.
