### ISSUE TITLE
Update mix.exs in generators to follow convention in Elixir v1.5

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2320]

**Comment by aptinio** [comment]
@josevalim, @chrismccord I'd be happy to take this on.

**Comment by sebastiandedeyne** [comment]
Sorry for hijacking, but are the new 1.5 conventions documented anywhere (yet)?

**Comment by aptinio** [comment]
@sebastiandedeyne, see https://github.com/elixir-lang/elixir/pull/6215
