### ISSUE TITLE
Task `compile.phoenix` not found when running `mix ecto.create`

### ISSUE THREAD

**Issue by emanchado** [phoenixframework/phoenix#2321]
### Environment

* Elixir version (elixir -v): 1.4.4 (also seems to fail now with 1.2.6, but I think it used to work before!)
* Phoenix version (mix deps): 1.1.6
* NodeJS version (node -v): 4.7.2
* NPM version (npm -v): 4.5.0
* Operating system: Linux (ElementaryOS, based on Ubuntu Xenial)

### Expected behavior

I run `mix deps.get` and then `mix ecto.create` on a fresh copy of https://github.com/emanchado/cataloger and the database is created.

### Actual behavior

When I run `mix ecto.create`, I get the following error:

```
** (Mix) The task "compile.phoenix" could not be found. Did you mean "compile.elixir"?
```

I have tried a bunch of combinations from answers to similar problems I found on the internet, to no avail :-(

**Comment by josevalim** [comment]
This worked fine on my machine. Can you remove the `_build` and `deps` directory and try again just in case your build got corrupted?

**Comment by emanchado** [comment]
Ah, I hadn't seen the suggestion to delete `deps`, just `_build`. That seemed to fix the initial hurdle, but then I get tons of warnings, and compilation error at the end:

```** (CompileError) web/views/item_view.ex: internal error in lint_module;
crash reason: badarg

  in function  erl_anno:anno_info/1
     called as erl_anno:anno_info(-1)
  in call from erl_lint:loc/2 (erl_lint.erl, line 640)
  in call from erl_lint:icrt_export/4 (erl_lint.erl, line 3094)
  in call from erl_lint:icrt_clauses/4 (erl_lint.erl, line 3076)
  in call from erl_lint:expr/3 (erl_lint.erl, line 2168)
  in call from erl_lint:'-expr_list/3-fun-0-'/3 (erl_lint.erl, line 2330)
  in call from lists:foldl/3 (lists.erl, line 1263)
  in call from erl_lint:exprs/3 (erl_lint.erl, line 2100)
  in call from erl_lint:exprs/3 (erl_lint.erl, line 2101)
  in call from erl_lint:'-expr_list/3-fun-0-'/3 (erl_lint.erl, line 2330)
  in call from lists:foldl/3 (lists.erl, line 1263)
  in call from erl_lint:expr/3 (erl_lint.erl, line 2306)
  in call from erl_lint:exprs/3 (erl_lint.erl, line 2100)
  in call from erl_lint:'-expr_list/3-fun-0-'/3 (erl_lint.erl, line 2330)
  in call from lists:foldl/3 (lists.erl, line 1263)
  in call from erl_lint:expr/3 (erl_lint.erl, line 2306)
  in call from erl_lint:exprs/3 (erl_lint.erl, line 2100)
  in call from erl_lint:'-expr_list/3-fun-0-'/3 (erl_lint.erl, line 2330)
  in call from lists:foldl/3 (lists.erl, line 1263)
  in call from erl_lint:'-expr_list/3-fun-0-'/3 (erl_lint.erl, line 2330)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Although [`item_view.ex`](https://github.com/emanchado/cataloger/blob/master/web/views/item_view.ex) is actually pretty small.

**Comment by emanchado** [comment]
And thanks for the super-quick answer BTW!

**Comment by josevalim** [comment]
`mix deps.update phoenix_html` should fix the compilation issue.

**Comment by emanchado** [comment]
Ah, thanks, that did it! I also had to `deps.update phoenix_ecto` but after that everything ran fine. Thanks!

**Comment by hakimkal** [comment]
I had a funny one. I decided mid way to switch from VSCode to Intellij IDEA IDE and ran into this error

** (Mix) The task "compile.phoenix" could not be found. Did you mean "compile.elixir"?
I deleted my _build and deps directory and ran deps.update --all
Problem solved!
