### ISSUE TITLE
Generating schemas with phx.gen.{context, json, html} with references, is unclear

### ISSUE THREAD

**Issue by MartinElvar** [phoenixframework/phoenix#2322]
Hello :-) 

Excuse the bit unclear title, could't come up with anything more describing, feel free to correct it. :)

### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): 1.3.0-rc.2
* NodeJS version (node -v): v7.4.0
* NPM version (npm -v): 4.0.5
* Operating system: MacOS

### To the case

Today i started a new project with Phoenix 1.3 RC 2, and i started generating some schemas, i used the mix phx.gen.context to get myself a Tenant schema.

```mix phx.gen.context Accounts Tenant tenants name:string logo:string```

All good!

I migrated, and got to my user schema straight away.

```mix phx.gen.context Accounts User users name:string email:string tenant:references```

I could't remember how to state my reference, phoenix helped me out with a fantastic error message 👍 .

```
** (Mix) Phoenix generators expect the table to be given to tenant:references.
For example:

    mix phx.gen.schema Comment comments body:text post_id:references:posts
```

I corrected my command as a result.

```mix phx.gen.context Accounts User users name:string email:string tenant_id:references:tenants password_digest:string```

Great success, but then i ran mix ecto.migrate, and got.

```
13:50:27.956 [info]  == Running Pharma.Repo.Migrations.CreatePharma.Accounts.User.change/0 forward

13:50:27.956 [info]  create table accounts_users
** (Postgrex.Error) ERROR 42P01 (undefined_table): relation "tenants" does not exist
```

Hmm weird i thought. But i quickly realised that in phoenix 1.3, the context is prefixed to the table names, so i quickly altered my migration and my schema file.

```Elixir
  schema "accounts_users" do
    field :email, :string
    field :name, :string
    field :password_digest, :string
    field :picture, :string
    - field :tenant_id, :id
    + field :accounts_tenant_id, :id

    timestamps()
  end
```

```Elixir
  use Ecto.Migration

  def change do
    create table(:accounts_users) do
      add :name, :string
      add :email, :string
      add :password_digest, :string
      add :picture, :string
      - add :tenant_id, references(:tenants, on_delete: :nothing)
      + add :accounts_tenant_id, references(:accounts_tenants, on_delete: :nothing)
      
      timestamps()
    end

    - create index(:users, [:tenant_id])
    + create index(:accounts_users, [:accounts_tenant_id])
  end
```

So that begs the question, what is the correct way to enter the references type?

```mix phx.gen.context Accounts User users name:string email:string accounts_tenant_id:references:accounts_tenants password_digest:string```

If so, i guess we should update the error message mentioned previously. 

Or should the generation command itself figure out the context of the referenced schema, and build the migration and schema accordingly?

**Comment by chrismccord** [comment]
It should be as you ended with:

```
mix phx.gen.context Accounts User users name:string email:string accounts_tenant_id:references:accounts_tenants password_digest:string
```
  
Perhaps our examples and error message for references could show ` mix phx.gen.schema Blog.Comment blog_comments body:text post_id:references:blog_posts` ? would that make it clearer?

**Comment by josevalim** [comment]
Please send a PR where we update the error message. What do you think about this:

```
** (Mix) Phoenix generators expect the table to be given to tenant:references. For example:

    mix phx.gen.schema Comment comments body:text post_id:references:blog_posts

Note that table names are typically prefixed with the context, such as "blog_" in the example above.
```

**Comment by MartinElvar** [comment]
Way better yea, i will pop a PR asap 👍  Thx for the prompt reply!

**Comment by MartinElvar** [comment]
What option would you prefer?

```post_id:references:blog_posts```
To.
```blog_post_id:references:blog_posts```

From a database perspective the ladder makes sense, as it clearly states the foreign key. What do you think?

**Comment by josevalim** [comment]
I would vote for the former because that would be a weird column name on Ecto side, especially because it most likely belongs to the same context as the current schema.

**Comment by josevalim** [comment]
Closing in favor of the PR.
