### ISSUE TITLE
Using the TO_TIMESTAMP function in a WHERE statement causes an error.

### ISSUE THREAD

**Issue by EugeneHPC** [phoenixframework/phoenix#2327]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps): 4.10.0
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

### Expected behavior
```
SELECT 
  "type", COUNT(DISTINCT "offset")
FROM "log"
LEFT OUTER JOIN (SELECT TO_TIMESTAMP('2017-05-29 02:53:00') AS "start") AS "s" ON 1=1
LEFT OUTER JOIN (SELECT TO_TIMESTAMP('2017-05-29 02:55:00') AS "end") AS "e" ON 1=1
WHERE "date" >= "start" AND "date" < "end"
GROUP BY "type"
```
-> It return the correct result

```
SELECT 
  "type", COUNT(DISTINCT "offset")
FROM "log"
WHERE "date" >= TO_TIMESTAMP('2017-05-29 02:53:00') AND "date" < TO_TIMESTAMP('2017-05-29 02:55:00')
GROUP BY "type"
```
-> It return the java.lang.NullPointerException

The second query should return the same result as above, and why is this issue happening?

**Comment by EugeneHPC** [comment]
@josevalim I want to know why the problem with the second query occurs. Can you tell me what's wrong?

**Comment by stevedomin** [comment]
@EugeneHPC this Github project is for [Phoenix, an Elixir web framework](http://www.phoenixframework.org). Looks like you are using [Apache Phoenix](https://phoenix.apache.org). 

The issue tracking software for Apache Phoenix is here: https://issues.apache.org/jira/browse/PHOENIX/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel

**Comment by EugeneHPC** [comment]
@stevedomin This is my mistake. I was completely mistaken. Thank you for your reply and sorry for the wrong issue.
