### ISSUE TITLE
No phx.new task

### ISSUE THREAD

**Issue by laurent44Accenture** [phoenixframework/phoenix#2330]
### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): 
* NodeJS version (node -v): not installed
* NPM version (npm -v): NA
* Operating system: Windows 10

### Expected behavior
I'v checked out the master and even tried the tag v1.3.0-rc2
I have deleted my .mix and .hex folder then run mix deps.get
I should have a mix task mix phx.new

### Actual behavior

I don't have the mix phx.new task

mix --help output:  
mix phoenix.gen.html  # Generates controller, model and views for an HTML based resource
mix phoenix.server    # Starts applications and their servers
mix phx.digest        # Digests and compresses static files
mix phx.digest.clean  # Removes old versions of static assets.
mix phx.gen.channel   # Generates a Phoenix channel
mix phx.gen.context   # Generates a context with functions around an Ecto schema
mix phx.gen.embedded  # Generates an embedded Ecto schema file
mix phx.gen.html      # Generates controller, views, and context for an HTML resource
mix phx.gen.json      # Generates controller, views, and context for a JSON resource
mix phx.gen.presence  # Generates a Presence tracker
mix phx.gen.schema    # Generates an Ecto schema and migration file
mix phx.gen.secret    # Generates a secret
mix phx.routes        # Prints all routes
mix phx.server        # Starts applications and their servers

I have probably missed something.

**Comment by josevalim** [comment]
The project generator needs to be installed: `mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez`

If you'd rather install it from source, check the installer directory in the project (and its instructions).

**Comment by laurent44Accenture** [comment]
Well I did try to install it. Must have made a mistake somewhere.
I'v used the the link you provided and it's working. Thanks

**Comment by josevalim** [comment]
Maybe you got the old installer (phx.new is new and part of the upcoming v1.3 release).
