### ISSUE TITLE
Add phoenix.js documentation to phoenix docs

### ISSUE THREAD

**Issue by bryanjos** [phoenixframework/phoenix#2331]
This is a proposal to add phoenix.js docs to Phoenix's docs in hexdocs. 

I believe we can accomplish this by:

- [ ] Converting the comments for the functions in phoenix.js to the jsdoc format
- [ ] Create a task to make documentation output using a js documentation generator
      Either one of the following could work:
  * [documentation.js](http://documentation.js.org/)
  * [jsdoc](http://usejsdoc.org/)
- [ ] Make sure the above places the docs into the `doc` directory before they are pushed to hexdocs

**Comment by chrismccord** [comment]
@bryanjos are you volunteering to tackle these proposal? :) If so, please go ahead! Thanks!

**Comment by bryanjos** [comment]
@chrismccord I am! Hoping to send a PR or 2 within the next week or so

**Comment by webdeb** [comment]
@bryanjos nice work! is that issue still active?

**Comment by bryanjos** [comment]
@webdeb no I believe this can be closed now
