### ISSUE TITLE
Associations with mix phx.gen.schema, seems to fail

### ISSUE THREAD

**Issue by MartinElvar** [phoenixframework/phoenix#2335]
Hello A-Team,

I'm trying to generate a intermediate schema, thus i don't want a controller and view to be generated for me, so i turn to phx.gen.schema. 

### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): 1.3.0-rc.2
* NodeJS version (node -v): v7.4.0
* NPM version (npm -v): 4.0.5
* Operating system: MacOS

### Expected behavior

The following should generate a migration file and a schema file for me.

```mix phx.gen.schema MyApp.Posts.ArticlesTags article_id:references:article tag_id:references:tags```

### Actual behavior

I get the following error.

```
# -> mix phx.gen.schema MyApp.Posts.ArticlesTags article_id:references:article tag_id:references:tags

** (Mix) Expected the plural argument, "article_id:references:article", to be all lowercase using snake_case convention

mix phx.gen.schema and phx.gen.embedded expect both a module
name and the plural of the generated resource followed by
any number of attributes:

    mix phx.gen.schema Blog.Post blog_posts title:string
```

The references seem to work with json and html, also should't i get to specify my Posts context?
Or am i completely wrong about the gen command 😄 

Thank you!

**Comment by josevalim** [comment]
The error message says you need to pass a plural argument and you are not
passing one. Why?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by MartinElvar** [comment]
My bad, bad paste, here are the correct one.

```
mix phx.gen.schema Heaped.Posts.ArticlesTags article_id:references:articles tag_id:references:tags
** (Mix) Expected the plural argument, "article_id:references:articles", to be all lowercase using snake_case convention

mix phx.gen.schema and phx.gen.embedded expect both a module
name and the plural of the generated resource followed by
any number of attributes:

    mix phx.gen.schema Blog.Post blog_posts title:string
```

Maybe i'm misunderstanding something.

**Comment by MartinElvar** [comment]
My bad, guess the error message turned my focus to "article_id:references:articles" my argument 😄 .
