### ISSUE TITLE
Phoenix Postgres Connection Problem

### ISSUE THREAD

**Issue by decentname** [phoenixframework/phoenix#2338]
I have postgres install with simple_crud_phoenix db. When i run mix phoenix.server. i get infinite loop og this error.  mix ecto.create and mix ecto.migrate works fine. 

[error] GenServer #PID<0.4051.0> terminating
** (stop) exited in: GenServer.call(Postgrex.TypeManager, {:get, Ecto.Adapters.Postgres.TypeModule, {'localhost', 5432, "simple_crud_phoenix"}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:729: GenServer.call/3
    lib/postgrex/protocol.ex:621: Postgrex.Protocol.bootstrap/3
    lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

**Comment by josevalim** [comment]
We you click "New issue", there is some existing text in the text area that we ask you to fill in. Can you please do so accordingly? Thank you.

**Comment by josevalim** [comment]
In any case, the error is likely that you passing `:postgrex` in your applications list inside `def application` in your mix.exs file.
