### ISSUE TITLE
Add config_change callback back to generated Application

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2339]

**Comment by josevalim** [comment]
In master.

**Comment by drozzy** [comment]
What does `config_change` do? I can't find a description...

Is it supposed to be defined in the `application.ex` file?

**Comment by fertapric** [comment]
@drozzy it's not currently defined as a callback in Elixit's `Application`, but you can find more information in the Erlang documentation http://erlang.org/doc/apps/kernel/application.html#Module:config_change-3
