### ISSUE TITLE
Document use of "raw" websockets

### ISSUE THREAD

**Issue by farao** [phoenixframework/phoenix#234]
In the README, the use of the new channels is explained very well. Unfortunately, there is no real documentation on how to use phoenix just with normal websockets (without the channels). Even the api doc (http://api.phoenixframework.org/Phoenix.Socket.Handler.html) is incomplete and probably lacks examples to be easily understood. Could you add documentation for it or point me (and other users) to an explanation, if it already exists elsewhere? Thanks!

**Comment by arrowcircle** [comment]
I tried this in my router, but always get error:

** (CompileError) web/router.ex:28: undefined function dispatch_option/2

What I doing wrong?

**Comment by josevalim** [comment]
The dispatch_option option is gone. At this moment we don't allow use of the raw websockets. We could allow this though as an option you give directly to the webserver. Then you can manage things directly through cowboy.

@chrismccord do you want to bring this back in some way? My only requirement is that it is very clear it is a cowboy specific option.

**Comment by arrowcircle** [comment]
@josevalim could you please tell me more about it? Is it possible in current version of phoenix?

**Comment by josevalim** [comment]
No, it is not possible.

**Comment by chrismccord** [comment]
We don't currently support raw websocket connections. You can wire up your own Plug cowboy adapter options to make a regular cowboy_websocket_hander, but I don't have a link handy atm. Maybe a simple channel setup would work for your usecase?

**Comment by arrowcircle** [comment]
@chrismccord no, phoenix channels does not work for me, I need raw websockets.

> You can wire up your own Plug cowboy adapter options to make a regular cowboy_websocket_hander

This looks like a black magic for me. Could you please get me more info to get it done?

**Comment by jeregrine** [comment]
@arrowcircle  https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/cowboy_websocket.ex#L36 down are the functions you need to implement. And then you need to add to the dispatch option in the router and or endpoint? I will see if I can get an example up and running next weekend maybe.

**Comment by arrowcircle** [comment]
@chrismccord exactly, I just cant use default channel responses with js lib I use thats why i want to make a custom endpoint with http api to it

**Comment by jeregrine** [comment]
@arrowcircle which library? We need examples of shimming phoenix into existing projects.

**Comment by chrismccord** [comment]
> I just cant use default channel responses with js lib I use thats why i want to make a custom endpoint with http api to it

It might be easier to shim on the client with phoenix.js -> your lib. We need to know more though to know for sure.

**Comment by arrowcircle** [comment]
@chrismccord @jeregrine I writing an alternative backend for pusher.com library for learning purpose. I already made a partial functionality in erlang and now want to try elixir.

**Comment by narrowtux** [comment]
Sorry to necro this, I also need raw websockets to make an API that doesn't rely on having to install the phoenix.js library first (as that requires the developer to use babel and limits them to JavaScript only).

**Comment by chrismccord** [comment]
> I also need raw websockets to make an API that doesn't rely on having to install the phoenix.js library first (as that requires the developer to use babel and limits them to JavaScript only).

To be clear, phoenix channels is transport agnostic and *does not* require javascript. See various third party channel adapters in Java, C#, objc, swift, etc.

Also phoenix.js does not rely on babel once built. We ship a precompiled version of phoenix.js that is already built, so babel is not required to use it.

**Comment by narrowtux** [comment]
Thanks for mentioning the other languages, this somehow slipped my mind.

I _could_ make a custom serializer as well but I really just need this one websocket to be a static URL anything can connect to and it doesn't need Phoenix.Channel either since all it does is forward messages from an AMQP queue to the websocket.

I finally found the [documentation](https://hexdocs.pm/phoenix/1.2.1/Phoenix.Endpoint.CowboyHandler.html) on how to use the cowboy router around the phoenix one which is a bit of a hassle, but works.

**Comment by gertjana** [comment]
> phoenix channels is transport agnostic
but this does require you to implement the channel adapters on the client side, 
in my case, I have little control over the client and it uses the subprotocol headers to determine the message protocol, so support for normal web sockets would benefit me greatly

**Comment by satom99** [comment]
I set [phx_raws](https://github.com/satom99/phx_raws) up after a few hours of testing. I did not quite like setting up _cowboy_ manually so I got my way around it!

Hope this is useful to you as it is to me. @gertjana @narrowtux @arrowcircle 

I obviously am open to collaborators, not only in order to improve the code but to prevent it from breaking on new Phoenix versions.

**Comment by narrowtux** [comment]
That’s awesome!
