### ISSUE TITLE
help on add features 

### ISSUE THREAD

**Issue by harinanda** [phoenixframework/phoenix#2340]
i want to add auth component to be added to actuval base like meteor with different integrations 

hari nanda

### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

**Comment by josevalim** [comment]
Please use the mailing list, forum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
