### ISSUE TITLE
** (Mix) The task "phx.gen.context" could not be found

### ISSUE THREAD

**Issue by thomasdola** [phoenixframework/phoenix#2341]
### Environment

* Elixir version (elixir -v): 1.4
* Phoenix version (mix deps): v1.3.0-rc.2
* Operating system: archlinux

### Expected behavior
I have an umbrella app with 

- apps/blog

- apps/blog_web

When i run `mix phx.gen.context Accounts User users username:string:unique` inside `apps/blog` it should create the appropriate files and inject codes.

### Actual behavior
I have an umbrella app with 

- apps/blog

- apps/blog_web

When i run `mix phx.gen.context Accounts User users username:string:unique` inside `apps/blog` it complains about not being able to find the task.
But when i run the same task in `apps/blog_web`, it does work.
From what i have read `apps/blog` is where these schemas and context should live.

**Comment by josevalim** [comment]
This mode of operation is not yet supported (cross umbrella generation). It is on the roadmap but we are not sure if it will be done before 1.3 final. Thank you.

**Comment by chrismccord** [comment]
The flow right now is to run this task inside the `*_web` app, since it is the one that depends on phoenix and has the necessary configuration to know which `context_app` to generate the non-web files in.
