### ISSUE TITLE
Phoenix 1.3 generator not generating associations

### ISSUE THREAD

**Issue by mikeni** [phoenixframework/phoenix#2343]
### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): master (post rc2)
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

### Issue

Currently, the generator is creating id fields for the associations instead of writing belongs_to association statements.

Not sure if this is intentional.

It seems the issue is because there is context and schema now, the pattern of specifying the association in the command line doesn't allow you to distinguish between context and schema in the 
command line

for example

hawaii_banana_id:references:fruits_hawaii_banana:unique

the only way figure out what is context and schema is to take the key, (specified in parenthesis)
(hawaii_banana)_id:references:fruits_hawaii_banana:unique

and intersect it with the references name (2nd parenthesis)
(hawaii_banana)_id:references:fruits_(hawaii_banana):unique

otherwise we would have to have another format, such as 
hawaii_banana_id:references:fruits:hawaii_banana:unique

what do you guys think?

**Comment by aesmail** [comment]
I believe leaving out the association on the schema is intentional as per #2151

**Comment by mikeni** [comment]
Hmm, I agree with Chris, we need belongs_to back in there before 1.3 is released.  

Otherwise, we need clear instructions just like adding the resource to the router file that you need to change the field statement to an association statement.

**Comment by mikeni** [comment]
closing this issue

**Comment by mikeni** [comment]
Actually, wanted to keep this open for a request for clear instructions in the shell instructions.

**Comment by chrismccord** [comment]
> we need clear instructions just like adding the resource to the router file that you need to change the field statement to an association statement.

This will not be the normal mode of operation though.  You will only add `belongs_to` as you see fit, and mostly only for schemas within the same context. The only change I would make at this point would be to generate `belongs_to` for times the schema is shared in the same context, but it's not something I'm planning for 1.3 final at this point. If you would like to send a PR with this feature I would gladly consider it. Thanks!
