### ISSUE TITLE
Shift from Cowboy to Phoenix

### ISSUE THREAD

**Issue by decentname** [phoenixframework/phoenix#2344]
Hey, I have a cowboy project with schemas and handlers specified. But, there is no support for sessions and CSRF protection in cowboy. So, how can i shift this project to phoenix. Phoenix uses cowboy as dependency and invokes Plug.Adapter.cowboy.Handler . Is there any easy way to shift to phoenix? I could not find support to migrate from cowboy to phoenix.

**Comment by chrismccord** [comment]
Please use the mailing list and forums for questions as we reserve the issues list to issues only. Thanks!
