### ISSUE TITLE
Add some alias shortcuts for common commands

### ISSUE THREAD

**Issue by Aiken00** [phoenixframework/phoenix#2350]
Like Rails, it provides some alias commands like `rails s` for `rails server` and `rails c` for `rails console`.

Would it be a good idea if phoenix provides something similar(e.g. `mix ps` for `mix phx.server`)  and by default set those in `def alias` in `mix.exs`?

**Comment by chrismccord** [comment]
Users are free to alias on their own so I'm not convinced to add a 'mix phx.s' by default. Thanks!
