### ISSUE TITLE
Bug form submit 

### ISSUE THREAD

**Issue by cedrico2016** [phoenixframework/phoenix#2353]
### Environment

* Elixir version (elixir -v):  1.4.4

* Phoenix version (mix deps):
 logger_file_backend 0.0.9 (Hex package) (mix)
  locked at 0.0.9 (logger_file_backend) 5c2f7d4a
  ok
* remix 0.0.2 (Hex package) (mix)
  locked at 0.0.2 (remix) f0611565
  ok
* mimerl 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (mimerl) 993f9b0e
  ok
* misc_random 0.2.6 (Hex package) (mix)
  locked at 0.2.6 (misc_random) 95998114
  ok
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* hashids 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (hashids) 16f7d1cd
  ok
* metrics 1.0.1 (Hex package) (rebar3)
  locked at 1.0.1 (metrics) 25f094de
  ok
* fs 0.9.1 (Hex package) (rebar)
  locked at 0.9.2 (fs) ed17036c
  ok
* unicode_util_compat 0.2.0 (Hex package) (rebar3)
  locked at 0.2.0 (unicode_util_compat) dbbccf67
  ok
* idna 5.0.2 (Hex package) (rebar3)
  locked at 5.0.2 (idna) ac203208
  ok
* bunt 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (bunt) 951c6e80
  ok
* gettext 0.13.1 (Hex package) (mix)
  locked at 0.13.1 (gettext) 5e0daf4e
  ok
* eiconv 1.1 (https://github.com/zotonic/eiconv.git) (rebar3)
  locked at 644fb5e
  ok
* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (decimal) 157b3ced
  ok
* parallel_stream 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (parallel_stream) 4c78d3e6
  ok
* comeonin 2.5.1 (Hex package) (mix)
  locked at 2.5.1 (comeonin) b39cc11f
  ok
* poison 2.2.0 (Hex package) (mix)
  locked at 2.2.0 (poison) 4763b69a
  ok
* ssl_verify_fun 1.1.1 (Hex package) (rebar)
  locked at 1.1.1 (ssl_verify_fun) 28a4d65b
  ok
* porcelain 2.0.3 (Hex package) (mix)
  locked at 2.0.3 (porcelain) 2d77b17d
  ok
* gen_smtp 0.11.0 (Hex package) (rebar3)
  locked at 0.11.0 (gen_smtp) d90ff2f0
  ok
* canada 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (canada) 08f94fff
  ok
* scrivener 2.2.1 (Hex package) (mix)
  locked at 2.2.1 (scrivener) 5a84cdfc
  ok
* combine 0.9.2 (Hex package) (mix)
  locked at 0.9.2 (combine) cd3c8721
  ok
* csv 1.4.2 (Hex package) (mix)
  locked at 1.4.2 (csv) cedb2f23
  ok
* certifi 1.2.1 (Hex package) (rebar3)
  locked at 1.2.1 (certifi) c3904f19
  ok
* hackney 1.8.6 (Hex package) (rebar3)
  locked at 1.8.6 (hackney) 21a725db
  ok
* tzdata 0.5.12 (Hex package) (mix)
  locked at 0.5.12 (tzdata) 1c17b686
  ok
* timex 3.0.8 (Hex package) (mix)
  locked at 3.0.8 (timex) 71d5ebaf
  ok
* earmark 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (earmark) a0b0904d
  ok
* db_connection 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (db_connection) 2865c2a4
  ok
* httpoison 0.11.2 (Hex package) (mix)
  locked at 0.11.2 (httpoison) 9e59f17a
  ok
* arc 0.8.0 (Hex package) (mix)
  locked at 0.8.0 (arc) bb7cf8ea
  ok
* credo 0.7.4 (Hex package) (mix)
  locked at 0.7.4 (credo) 0c33bcce
  ok
* phoenix_pubsub 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (phoenix_pubsub) c10ddf62
  ok
* pdf_generator 0.3.5 (Hex package) (mix)
  locked at 0.3.5 (pdf_generator) 9cf9420a
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* mime 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (mime) 01c1d6f4
  ok
* ibrowse 4.2.2 (Hex package) (rebar3)
  locked at 4.2.2 (ibrowse) b32b5baf
  ok
* httpotion 3.0.0 (Hex package) (mix)
  locked at 3.0.0 (httpotion) 4ce0af28
  ok
* mailman 0.3.0 (Hex package) (mix)
  locked at 0.3.0 (mailman) 2d54de5f
  ok
* plug 1.3.4 (Hex package) (mix)
  locked at 1.3.4 (plug) b4ef3a38
  ok
* phoenix_html 2.9.3 (Hex package) (mix)
  locked at 2.9.3 (phoenix_html) 1b5a2122
  ok
* ueberauth 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (ueberauth) 9160c601
  ok
* ueberauth_identity 0.2.3 (Hex package) (mix)
  locked at 0.2.3 (ueberauth_identity) 216f18ca
  ok
* maru 0.10.3 (Hex package) (mix)
  locked at 0.10.3 (maru) 10e31925
  ok
* pay 0.1.3 (https://github.com/denic/pay.git) (mix)
  locked at 240c5a2
  ok
* phoenix 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (phoenix) 6dc59224
  ok
* phoenix_live_reload 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (phoenix_live_reload) 829218c4
  ok
* scrivener_html 1.5.1 (Hex package) (mix)
  locked at 1.5.1 (scrivener_html) 42f4b003
  ok
* postgrex 0.12.1 (Hex package) (mix)
  locked at 0.12.1 (postgrex) 2f8b46cb
  ok
* ecto 2.0.6 (Hex package) (mix)
  locked at 2.0.6 (ecto) 9dcbf819
  ok
* arc_ecto 0.7.0 (Hex package) (mix)
  locked at 0.7.0 (arc_ecto) 428ed7ea
  ok
* canary 0.14.2 (Hex package) (mix)
  locked at 0.14.2 (canary) fa5f66db
  ok
* tributary 0.2.1 (Hex package) (mix)
  locked at 0.2.1 (tributary) 325d53df
  ok
* distillery 1.4.0 (Hex package) (mix)
  locked at 1.4.0 (distillery) d633cd32
  ok
* edeliver 1.4.2 (Hex package) (mix)
  locked at 1.4.2 (edeliver) 8c9428ed
  ok
* secure_random 0.5.0 (Hex package) (mix)
  locked at 0.5.0 (secure_random) f49e4bfe
  ok
* scrivener_ecto 1.1.3 (Hex package) (mix)
  locked at 1.1.3 (scrivener_ecto) f5615f67
  ok
* phoenix_ecto 3.0.0 (Hex package) (mix)
  locked at 3.0.0 (phoenix_ecto) b947aaf0
  ok

* NodeJS version (node -v):  v4.7.2
* NPM version (npm -v):  3.5.2
* Operating system:
Kubuntu 17.04
### Actual behavior
I am having 2 forms (id: "office_profile_form" and id: "delete_avatar_form"] , 
The office_profile_form allows user to fill a form and to upload a foto. When a foto has been upload i'm adding a button to delete the foto.. So for that i've added a secon form,delete_avatar_form, placed after the first one. The submit button for the second form (delete foto) is included dynamically (condition if the foto exists or not) in the first form and only make a post request to and endpoint (method: delete). 
Both forms are explicitally submitted via javascript.

Problem: 
When the no foto has been uploaded => the submit button for the second form is not present. everytthing goes correctly (the office_profile_form is being submitted successfully and makes the job). 
But when a foto has been upload (submit button for delete_avatar_form is added), the office_profile_form is no more being submitted after click on the submit button.. The delete method is called instead. I get something like :"no route found for DELETE /stb/office/8 (StfunWeb.Router)" and i don't need to implement that delete method because i don't need that. 
Am i doing something wrong? 

a submit button for the second form is included in the first one and is included dynamically through an if condition. The forms are explicitally submitted via Javascript. When the submit button of the second form is not included (condition is false)

A overview of the code can be seen here
https://gist.github.com/cedrico2016/b6a0d9739e1ced95d5f7f8baa44f458c

**Comment by webdeb** [comment]
@cedrico2016 the issue tracker is for bugs and general-issues only, that issue does not look like phoenix bug. I am sure, the question will get more attention on Stackoverflow / Slack  or the Elixir Forum.

**Comment by Gazler** [comment]
Nested forms are not permitted in the HTML spec https://stackoverflow.com/questions/379610/can-you-nest-html-forms. When you create a delete link, a form is created in the HTML, and pressing the button submits the form.

Since you are submitting with JavaScript, I'd recommend not setting the method to delete, so that the hidden form is submitted.

When @webdeb said is also true. Please use one of the suggested places there for help specific to your application.
