### ISSUE TITLE
Phoenix.ChannelTest does not respond to "disconnect" broadcast

### ISSUE THREAD

**Issue by scouten** [phoenixframework/phoenix#2355]
### Environment

* Elixir version (elixir -v): Elixir 1.4.4
* Phoenix version (mix deps): 1.2.1.
* NodeJS version (node -v): 6.10.0
* NPM version (npm -v): 3.10.10
* Operating system: MacOS 10.12.3

### Expected behavior

When following this example code ...

```
  # Socket id's are topics that allow you to identify all sockets for a given user:
  #
  #     def id(socket), do: "user_socket:#{socket.assigns.user_id}"
  #
  # Would allow you to broadcast a "disconnect" event and terminate
  # all active sockets and channels for a given user:
  #
  #     <%= YourAppp.Endpoint.broadcast("user_socket:#{user.id}", "disconnect", %{})
  #
  # Returning `nil` makes this socket anonymous.
```

... in unit tests, the socket should be disconnected.

### Actual behavior

It is not.

Debugging output shows that the transport in use is `Phoenix.ChannelTest`. A search of that file in Phoenix 1.2.1 shows no occurrence of the string `"disconnect"`. This would seem to be at odds with the spec described in `Phoenix.Socket.Transport`:

```
  On subscribed, the transport must be able to handle "disconnect"
  broadcasts on the given id topic.
```

**Comment by chrismccord** [comment]
Thanks for the report! This has been fixed on master and you can now do:

```elixir
    {:ok, socket} = connect(UserSocket, %{})
    socket.endpoint.broadcast!(socket.id, "disconnect", %{})
    assert_broadcast "disconnect", %{}
```

**Comment by scouten** [comment]
@chrismccord thank you!
