### ISSUE TITLE
confusing error message when plug imports Router.Helpers

### ISSUE THREAD

**Issue by nhooyr** [phoenixframework/phoenix#2357]
I came across the error described in this post https://stackoverflow.com/questions/40561203/module-myapp-router-helpers-is-not-loaded-and-could-not-be-found

The error is not clear at all about what the issue is, I would have had no idea how to debug it if it were not for that post. Is it possible to make it more clear?

**Comment by josevalim** [comment]
What is your Elixir version? I am afraid we improved the deadlock reporting in the compiler but there isn't anything Phoenix can do here. Deadlocks are unfortunately tricky to handle.

**Comment by michalmuskala** [comment]
I don't think there's even a deadlock reported since the `Helpers` module is defined completely dynamically. I hit this myself couple times and tried looking for a solution, but I wasn't able to find any way it could be improved with the current way the `Helpers` module is created.

**Comment by nhooyr** [comment]
I'm on elixir 1.4.4

**Comment by chrismccord** [comment]
I understand this is a confusing and unhelpful error, but it's not something we can address in phoenix itself. We cover this error in the book and guides and that's as far as we can go without elixir compiler changes. Thanks!
