### ISSUE TITLE
Symlink into assets/vendor?

### ISSUE THREAD

**Issue by pikeas** [phoenixframework/phoenix#2359]
`assets/package.json` currently references Phoenix's files like this:

    {
      ...
      "dependencies": {
        "phoenix": "file:../deps/phoenix",
        "phoenix_html": "file:../deps/phoenix_html"
      },
    }

Instead of making a reference outside of the assets folder, why not reference `vendor/phoenix`, and symlink `vendor/phoenix` to `../deps/phoenix`?

**Comment by josevalim** [comment]
We find the current mechanism clearer, thank you!
