### ISSUE TITLE
Make all logging optional or configurable

### ISSUE THREAD

**Issue by ssboisen** [phoenixframework/phoenix#2365]
### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): 1.2.4

We're currently using version 1.2.4 which doesn't have much options wrt disabling or configuring logging. This get's really spammy in a production system with thousands of concurrent users, we've solved it currently by dropping those messages at our logging endpoint but it would be nice to simply not emit those logs at all.

It seem like some work have been done on master in order to add some options to v.1.3. E.g. [Phoenix.Logger](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/logger.ex#L94) and [Phoenix.Channel](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/channel.ex#L301). Perhaps it's an oversight but I just wanted to point out that [Phoenix.Socket.Transport](https://github.com/phoenixframework/phoenix/blob/65ab206dea7891af7188c0d887769039e897a9a3/lib/phoenix/socket/transport.ex#L246) doesn't provide any option for disabling or changing the level - it would be very nice if that could be added.

**Comment by josevalim** [comment]
If we are missing some flags, please send pull requests. :)

**Comment by chrismccord** [comment]
Channel logging is configurable in 1.3, so unless you have other specific log needs, this is solved for you once 1.3 goes final :) . Thanks!
