### ISSUE TITLE
mix.phx.new generates umbrella application in wrong path

### ISSUE THREAD

**Issue by hubertlepicki** [phoenixframework/phoenix#2367]
I'm using the new 1.3 generator phx.new with --umbrella flag. The help for this task states:

> It expects the path of the project as an argument.
> 
>     mix phx.new PATH [--module MODULE] [--app APP]

And this works as expected, the application is generated under PATH that was specified. However, when you give --umbrella flag the application will be generated under PATH_umbrella, i.e. the _umbrella suffix is always added to the path.

I'm just setting up new project and I'm using docker, and wanted to generate it under /app. This seems to be impossible, I have to generate it under /app_umbrella and then move everything to /app.

**Comment by chrismccord** [comment]
I'm okay with folks having to take a 2nd step to rename the root folder when needed after they generate the project. If we get a lot of request for a command line switch I may reconsider but for now I think it's not a big price to pay. Thanks!

**Comment by hubertlepicki** [comment]
No, having to rename folder is not big price to pay.

It gets slightly more pricier when /app is where you intended to generate the app, because it's the mounted volume, and anything else is volatile storage that gets discarded after the container shuts down. Then you're like "where the hell are my files?"
