### ISSUE TITLE
Not all node_modules install

### ISSUE THREAD

**Issue by p-adams** [phoenixframework/phoenix#2370]
### Environment

* Elixir version (elixir -v): 1.4.5
* Phoenix version (mix deps): just cloned the latest from repo
* NodeJS version (node -v): 8.0.0
* NPM version (npm -v): 4.6.1
* Operating system: MacOs Sierra 

### Expected behavior

To install all node_modules

### Actual behavior

      npm WARN assets No description
      20:43:01 - info: compiling
      20:43:05 - error: Compiling of js/app.js failed. Error: Couldn't find preset "es2015" relative to     directory "/Users/user/Desktop/phoenix"
      Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
      20:43:05 - error: Compiling of js/socket.js failed. Error: Couldn't find preset "es2015" relative    to directory "/Users/user/Desktop/phoenix"
      Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
      20:43:05 - info: compiled 2 files into app.css, copied 3 in 11.1 sec

**Comment by son1112** [comment]
@p-adams did you find a solution and would you mind sharing? I'm running into a very similar issue

**Comment by p-adams** [comment]
Unfortunately not. I sort of gave up in hopes that it may be resolved when
the official release of 1.3 hits.

On Sun, Aug 6, 2017 at 3:08 PM, Anderson Reinkordt <notifications@github.com
