### ISSUE TITLE
mix phx.gen.html creates migrations in the wrong folder

### ISSUE THREAD

**Issue by kuffel** [phoenixframework/phoenix#2371]
The migration files are being generated into a wrong folder. 

### Commands to reproduce the problem

> mix phx.new my_blog --database mysql --no-brunch
> cd  my_blog
> mix phx.gen.html Blog Posts posts title:string

### Expected behavior

A migration here: priv/repo/migrations/20170629095742_create_blog_posts.exs

### Actual behavior

The migration file is being generated into:

Users/john.doe/Desktop/my_blog/priv/repo/migrations/20170629095742_create_blog_posts.exs

### Environment

* Elixir version (elixir -v): 
> Erlang/OTP 19 [erts-8.2] [64-bit] [smp:4:4] [async-threads:10]
> Elixir 1.4.5

* Phoenix version (mix deps):
> phoenix 1.3.0-rc.2

* NodeJS version (node -v):
> v7.5.0

* NPM version (npm -v):
> 4.1.2

* Operating system:
> Windows 10 Pro - Version 10.0.15063

**Comment by Gazler** [comment]
This should be fixed on master. Please see https://github.com/phoenixframework/phoenix/issues/2325

Let me know if it doesn't work for you and I'll re-open the issue.
