### ISSUE TITLE
confusion with contexts

### ISSUE THREAD

**Issue by nhooyr** [phoenixframework/phoenix#2372]
There have been several threads on elixir forums regarding confusion with contexts. For example, https://elixirforum.com/t/contexts-a-barrier-too-high-for-newbies/5929

A simple way to alleviate anxiety regarding contexts would be to append a message to `mix help phx.gen.html` and other generators stating that if they do not understand what a context is, they can always use a default context like `app` and then can always refactor later.

**Comment by chrismccord** [comment]
We are working on the context guides which will help with some of the mentioned issues. Please reserve the issue tracker for issues. Thanks!
