### ISSUE TITLE
Consider to add `Model.new` to schema generators

### ISSUE THREAD

**Issue by webdeb** [phoenixframework/phoenix#2375]
Consider to add `Model.new` to schema generators

`def new(attrs), do: changeset(%MySchema{}, attrs)`

So instead of writing all that:

`MySchema.changeset(%MySchema{}, %{name: "Phoenix framework"})`

Could be a bit simpler, and better readable.

`MySchema.new(%{name: "Phoenix framework"})`

**Comment by josevalim** [comment]
This has been changed in Phoenix v1.3 generators. Plus, a changeset is not a struct.

**Comment by MContagious** [comment]
@josevalim 
Can you give a simple example where will be a changeset is not the same struct as the model?

**Comment by josevalim** [comment]
`%User{} != Ecto.Changeset.change(%User())` those are two completely different data structures.

**Comment by webdeb** [comment]
> Plus, a changeset is not a schema struct.

@josevalim true! Then maybe:

```
def changeset(%Struct{}, attrs \\ %{}) do
...
end

def changeset(attrs), do: changeset(%Struct{}, attrs)
```

Just to avoid tautology and have a nicer, shorter syntax 

`Struct.changeset(%{ name: "Phoenix" })`
