### ISSUE TITLE
wired result with path helper functions.

### ISSUE THREAD

**Issue by vanillahsu** [phoenixframework/phoenix#2377]
### Environment

* Elixir version (elixir -v): 1.4.5
* Phoenix version (mix deps): 1.3.0-rc.2
* NodeJS version (node -v): 
* NPM version (npm -v):
* Operating system: FreeBSD & Linux (ubuntu)

### Expected behavior
> mix phx.routes
  title_path  GET   /v1/api/titles/:id         XXX.Web.TitleController :index
> iex -S mix
iex(1)> alias XXX.Web.Endpoint
XXX.Web.Endpoint
iex(2)> XXX.Web.Router.Helpers.title_path(Endpoint, :index)
"/v1/api/titles"
iex(3)> XXX.Web.Router.Helpers.title_path(Endpoint, :index, 1)
** (Protocol.UndefinedError) protocol Enumerable not implemented for 1
      (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
      (elixir) lib/enum.ex:116: Enumerable.reduce/3
      (elixir) lib/enum.ex:1776: Enum.reduce/3
    (xxx) lib/xxx/web/router.ex:1: XXX.Web.Router.Helpers.segments/3
    (xxx) lib/xxx/web/router.ex:1: XXX.Web.Router.Helpers.title_path/3
### Actual behavior
it should return "/v1/api/titles/1", not throw exception.

**Comment by josevalim** [comment]
Can you please provide your routes definition? From the look of it it seems you have conflicting routes.

**Comment by vanillahsu** [comment]
Here is the definition.

--
    get "/titles", TitleController, :index
    get "/titles/:id", TitleController, :index
--
Thanks for your advice, after I check, I believe it's my fault, thanks.
