### ISSUE TITLE
Inconsistency in generated ecto table names with contexts

### ISSUE THREAD

**Issue by bcardarella** [phoenixframework/phoenix#2378]
In 1.3#master

When I run:

`mix phx.gen.context Customer Organization organizations name:string`

The generated table name in the migration is `customer_organizations`

Then if I want to generate a new schema that is within the same context:

`mix phx.gen.schema Customer.Account accounts name:string`

The generated table in the new migration is `accounts`

Unless I am missing something, I would think there should be consistency here. Either the first generator should not attempt to pre-pend the namespace onto the table name or the second generator should prepend the namespace if I generate it within one.

Personally, I would prefer no namespacing. I was surprised to see that the table name was being namespaced without my explicit asking for this. Feels a bit "rails"-y to me.

**Comment by chrismccord** [comment]
I think it's likely you ran `mix phx.gen.context` against the rc and then `mix phx.gen.schema` against master. We dropped the namespacing for all cases in master.

**Comment by bcardarella** [comment]
Ah, its possible. Thanks!
