### ISSUE TITLE
1.3-rc2 generated contexts / fallback controller doesn't appear to handle 404 on show

### ISSUE THREAD

**Issue by BDQ** [phoenixframework/phoenix#2379]
First, let me say thanks for an awesome project, I'm new to Phoenix, but it's been amazing so far! Anyway, I think I've spotted a minor issue with the new generated context stuff in 1.3-rc2:

The generated `get_`*singular*`!` function for a context module, indicates it expects to (and does)  raise an `Ecto.NoResultsError` exception when the ID is not found.

See: https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.context/schema_access.ex#L28

But the fallback_controller.ex function that renders a 404 expects `{:error, :not_found}` as you can see here: https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.json/fallback_controller.ex#L15

So when you try and GET an unknown id from the generated controller `show` function it doesn't handle it gracefully and you get an unhandled `Ecto.NoResultsError` stacktrace/error view.

Would it make sense to change the generated `get_`*singular*`!` function to use `get` over `get!` and return `{:error, :not_found}`  when appropriate? I'm happy to submit a PR for this, if this is in fact something that should be corrected.

**Comment by chrismccord** [comment]
This is intention as the generated fallback controller is just an example for you to grow your datatype m matching on. The `Ecto.NoResultsError` will still be translated to a 404, but you are right that it will not be handled by the fallback controller. For those folks wanting to handle it without an exception, we recommend to expose context functions that don't raise, as you alluded to. Thanks!

**Comment by wojtekmach** [comment]
btw, this issue came up in the past and there's more more context there: https://github.com/phoenixframework/phoenix/issues/2271

**Comment by BDQ** [comment]
Ah ok, thanks for the clarification and apologies for the duplication. Would it make sense to remove the `call(conn, {:error, :not_found})` function from the FallbackController to prevent this expectation? Seems a little odd that there's generated code that's never going getting hit?
