### ISSUE TITLE
phoenix.gen.html form incomplete

### ISSUE THREAD

**Issue by hassan** [phoenixframework/phoenix#2381]
### Environment

* Elixir version (elixir -v): Elixir 1.4.5
  Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
* Phoenix version (mix deps): phoenix 1.2.4 (Hex package) (mix)
                                                  locked at 1.2.4 (phoenix) 4172479b
OR
                                                  phoenix 1.3.0-rc.2 (Hex package) (mix)
                                                  locked at 1.3.0-rc.2 (phoenix) 53104ada
* NodeJS version (node -v): v8.1.2
* NPM version (npm -v): 5.0.3
* Operating system: macOS Sierra (10.12.5)

### Expected behavior

Running this command 
```mix phoenix.gen.html Thing things name:string colors:array:string```
should result in a form with a text field for "name" and some kind of selector (drop-down, collection of checkboxes) for the "colors".

### Actual behavior

Only "name" field is generated in the "form.html.eex" file -- see [example generated app](https://github.com/hassan/elixir-forms-example)

**Comment by chrismccord** [comment]
We don't support array inputs in the form  as part of our generators. Thanks!

**Comment by hassan** [comment]
Uh, well. In that case a warning and/or a link to some documentation on what that might look like *if* it were supported would be nice...

**Comment by josevalim** [comment]
I like the idea of having checkboxes or a multiple_select with some bogus values: foo, bar, baz. PR please?

**Comment by josevalim** [comment]
Btw, sorry for cutting in @chrismccord but we didn't provide one because I didn't know what to generate but @hassan gave some good suggestions. I think we can move forward.

**Comment by hassan** [comment]
Happy to take a swing at this, may take me a little while though. And I just discovered that ```deps/phoenix_guides/docs/testing/testing_views.md``` is basically empty, so... onward!

**Comment by josevalim** [comment]
@hassan that guide wouldn't be helpful to this problem though (we don't generate unit view tests per input). My advise would be find out how the other inputs are handled and attempt to add a clause in there that uses multiple_select as well.

**Comment by shankardevy** [comment]
@hassan to add to what @josevalim has mentioned, you might need to look specifically into this code:

https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phoenix.gen.html.ex#L111-L117

Where the generator ignores the `array` field type along with `reference` type. However, you can see the generator has code for other input types such as `string` and `integer`.

**Comment by rodrigozc** [comment]
@hassan , look at the article below from @arthurchipdean

https://medium.com/@chipdean/phoenix-array-input-field-implementation-7ec0fe0949d

**Comment by taiansu** [comment]
Wondering if @hassan or anyone is still working on this. If not I'll love to implement it and send the PR this couple days.

**Comment by josevalim** [comment]
@taiansu please go ahead :)

**Comment by hassan** [comment]
@taiansu yes, please feel free; I had started but got sidetracked and am a bit crunched right now.
