### ISSUE TITLE
Help/Question for postgres setup

### ISSUE THREAD

**Issue by zawmoelwin** [phoenixframework/phoenix#2382]
### Environment
* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): "1.2.4"
* NodeJS version (node -v): v8.0.0
* NPM version (npm -v): "5.0.0"
* Operating system: "Ubuntu 16.4"

### Command
(sudo) mix phoenix.server 
// I need sudo to compile for the first time

### Expected behavior
Should not give any error.

### Actual behavior
[error] Postgrex.Protocol (#PID<0.193.0>) failed to connect: ** (Postgrex.Error) FATAL 3D000 (invalid_catalog_name): database "test_again_dev" does not exist.

```
\du from psql shows that user has createdb right.
zaw       | Superuser, Create role, Create DB  
```
```
CREATE DATABASE works fine from pgsql command.
psql zaw -c "CREATE DATABASE mytemplate2 WITH ENCODING 'UTF8' TEMPLATE template0"
CREATE DATABASE
```

```
pg_hba.conf file setting for 
# Database administrative login by Unix domain socket
local   all             postgres                                trust
local   all             zaw	                                trust
```

Manual creation of the database with the project database name(i.e precreate the database manually) works very nicely.

**Comment by jurvis** [comment]
did you run `mix ecto.create`?

**Comment by lcacciagioni** [comment]
If you are in trying to test you can do `MIX_ENV=test mix ecto.create` before doing `mix test`.

**Comment by chrismccord** [comment]
Greetings @zawmoelwin,

We reserve the issue tracker for bugs and issues related to Phoenix, and this appears to be a Postgres issues specific to your setup. If you post a question for help on the Elixir Forum (https://elixirforum.com) I'm sure someone there will put you on the right track. Thanks!

Chris
