### ISSUE TITLE
model generator gives incorrect model name for foreign keys with non-default names

### ISSUE THREAD

**Issue by bgschiller** [phoenixframework/phoenix#2384]
### Environment

* Elixir version (elixir -v): 1.4.4
* Phoenix version (mix deps): 1.2.4
* NodeJS version (node -v): v6.9.1
* NPM version (npm -v): 3.10.8
* Operating system: macOS 10.11.4

### Expected behavior

When I run `mix phoenix.gen.model Item items owner_id:references:users`,  I expect `web/models/item.ex` to have a line saying 

```
    belongs_to :owner, MyApp.User
```

### Actual behavior

`web/models/item.ex` to has a line saying 

```
    belongs_to :owner, MyApp.Owner
```

**Comment by josevalim** [comment]
This behaviour is no longer present on master, as we change how belongs_to are generated. However, if we add it back, we should do it based on the `owner_id`, as you suggested. :+1:
