### ISSUE TITLE
action_fallback should also handle mismatched controller

### ISSUE THREAD

**Issue by webdeb** [phoenixframework/phoenix#2386]
### Environment

* Elixir version (elixir -v): 1.4
* Phoenix version (mix deps): 1.3.0-rc2

### Problem

To simplify my life, I am pattern matching the request inside the controller, like:

```
def create(%{ "items" => items }) when is_list(items) do
...
end
```
### Expected behavior

When an action is not found, because for example, there were not given the expected params to the controller, `action_fallback` should handle that mismatch, and let the given `FallbackController` do the rest.

### Actual behavior

Error:

** (Phoenix.ActionClauseError) could not find a matching MyApp.Web.ShopController.create clause
     to process request. This typically happens when there is a
     parameter mismatch but may also happen when any of the other
     action arguments do not match. The request parameters are:**

       %{}

The suggested solution is to define a `def create(conn, _params), do: :params_mismatch` action inside the controller, to avoid the error. This means you have to define such a proxy for each controller action.

I think it makes sense to let the `action_fallback` handle such a mismatch, if possible.

**Comment by josevalim** [comment]
I am not sure it is a good match. Action fallback is not about handling
errors, it is about values.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by webdeb** [comment]
@josevalim thanks for your reply! Its just sounds like it should redirect to a `fallback action`. I am just not sure if that error-handling could be limited only to mismatch errors inside the controller, or if this would propagate to all possible errors, like mismatch errors in some deeper application logic. This would't be good in turn.

**Comment by josevalim** [comment]
The ActionClauseError is already rendered as the appropriate 400, so you likely don't need to do anything here. If you really want to customize it, then yes, you will need to rely on the action fallback clauses with pattern matching instead of errors.
