### ISSUE TITLE
true-case-path casing problem on shared hosting 

### ISSUE THREAD

**Issue by alienfromouterspace** [phoenixframework/phoenix#2389]
Just to let you know. Maybe you would consider using some alternative instead.
I submitted details to the developer:
https://github.com/barsh/true-case-path/issues/2

**Comment by chrismccord** [comment]
Please follow the issue template when opening issues. Closing as this does not appear to be an issue. If you are having a problem with paths, please open a new issue with the details filled out. Thanks! :)
