### ISSUE TITLE
Error: EACCES: permission denied, scandir '/' [shared hosting user installation]

### ISSUE THREAD

**Issue by alienfromouterspace** [phoenixframework/phoenix#2390]
Reformated and added additional information as requested in: https://github.com/phoenixframework/phoenix/issues/2389
Also submited to: https://github.com/barsh/true-case-path/issues/2

### Environment

**_Shared hosting_** with : 

* Elixir version (elixir -v): 
```
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:12:8] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.3.4
```
* Phoenix version (mix deps):
```

* connection 1.0.4 (Hex package) (mix)

  locked at 1.0.4 (connection) a1cae722

  ok

* fs 0.9.1 (Hex package) (rebar)

  locked at 0.9.2 (fs) ed17036c

  ok

* gettext 0.13.1 (Hex package) (mix)

  locked at 0.13.1 (gettext) 5e0daf4e

  ok

* ranch 1.3.2 (Hex package) (rebar3)

  locked at 1.3.2 (ranch) e4965a14

  ok

* poolboy 1.5.1 (Hex package) (rebar)

  locked at 1.5.1 (poolboy) 6b461639

  ok

* decimal 1.4.0 (Hex package) (mix)

  locked at 1.4.0 (decimal) fac965ce

  ok

* poison 2.2.0 (Hex package) (mix)

  locked at 2.2.0 (poison) 4763b69a

  ok

* db_connection 1.1.2 (Hex package) (mix)

  locked at 1.1.2 (db_connection) 2865c2a4

  ok

* phoenix_pubsub 1.0.2 (Hex package) (mix)

  locked at 1.0.2 (phoenix_pubsub) bfa7fd52

  ok

* cowlib 1.0.2 (Hex package) (rebar3)

  locked at 1.0.2 (cowlib) 9d769a1d

  ok

* cowboy 1.1.2 (Hex package) (rebar3)

  locked at 1.1.2 (cowboy) 61ac29ea

  ok

* mime 1.1.0 (Hex package) (mix)

  locked at 1.1.0 (mime) 01c1d6f4

  ok

* plug 1.3.5 (Hex package) (mix)

  locked at 1.3.5 (plug) 7503bfcd

  ok

* phoenix_html 2.9.3 (Hex package) (mix)

  locked at 2.9.3 (phoenix_html) 1b5a2122

  ok

* phoenix 1.2.4 (Hex package) (mix)

  locked at 1.2.4 (phoenix) 4172479b

  ok

* phoenix_live_reload 1.0.8 (Hex package) (mix)

  locked at 1.0.8 (phoenix_live_reload) 4333f9c7

  ok

* postgrex 0.13.3 (Hex package) (mix)

  locked at 0.13.3 (postgrex) c277cfb2

  ok

* ecto 2.1.4 (Hex package) (mix)

  locked at 2.1.4 (ecto) d1ba9328

  ok

* phoenix_ecto 3.2.3 (Hex package) (mix)

  locked at 3.2.3 (phoenix_ecto) 450c7498

  ok


```
* NodeJS version (node -v):
```
v7.9.0
```
* NPM version (npm -v):
```
4.0.5
```
* Operating system:
```
FreeBSD 10.3-STABLE
```

### Expected behavior

Umm... no errors while installing?

### Actual behavior
```
[spider@server]:<~/hello_phoenix>$  mix phoenix.server

[info] Running HelloPhoenix.Endpoint with Cowboy using http://localhost:5566

/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:321

        throw er

        ^

​

Error: EACCES: permission denied, scandir '/'

  at Object.fs.readdirSync (fs.js:914:18)

  at GlobSync._readdir (/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:275:41)

  at GlobSync._processReaddir (/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:135:22)

  at GlobSync._process (/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:130:10)

  at new GlobSync (/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:46:10)

  at Function.globSync [as sync] (/usr/home/spider/hello_phoenix/node_modules/true-case-path/node_modules/glob/sync.js:24:10)

  at trueCasePathSync (/usr/home/spider/hello_phoenix/node_modules/true-case-path/index.js:29:15)

  at trueCasePath 

```

**Comment by chrismccord** [comment]
Thanks for filling out the issue template. Since this is an issue on the node dep side, there is unfortunately not for us to handle on our side. Hopefully someone over on the true-case-path side can get you pointed in the right direction. Thanks!

**Comment by alienfromouterspace** [comment]
I just let you know you (developers) are using component that is probably unusable (as it is now) at  shared hosting. And makes phoenix impossible to install without manual modification of 3rd party (I guess it's 3rd party) component. Because that sounds like too much effort to do.

If it is not issue for phoenix development team then there is nothing more I can add to this discussion. Let's hope that original author is willing to fix this. If he is not then I got no idea who should be addressed. 

If phoenix team is not interested in supporting shared hosting installation, then please let me know now. It would be helpful information.

**Comment by alienfromouterspace** [comment]
@chrismccord 
Well, no reply in a week so far. Other projects I get in touch with typically tried to consider use of alternative components instead of faulty one.

**Comment by ryanwinchester** [comment]
@alienfromouterspace deploying apps to shared hosting is probably a bad idea, in general

there are lots of affordable proper hosting services out there.

to name a few:

- https://www.digitalocean.com/pricing/
- https://www.linode.com/pricing
- https://amazonlightsail.com/pricing/
