### ISSUE TITLE
"module Rzjb.DataCase is not loaded and could not be found" during mix test after phx.gen.json

### ISSUE THREAD

**Issue by wzin** [phoenixframework/phoenix#2391]
### Overview

I'm getting a weird error during tests after generating json context on a fresh project.

### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 20 [RELEASE CANDIDATE 2] [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.4.5
```

* Phoenix version (mix deps):

  * phoenix_html 2.9.3 (Hex package) (mix)
  * phoenix 1.3.0-rc.2 (Hex package) (mix)
  * phoenix_live_reload 1.0.8 (Hex package) (mix)
  * phoenix_ecto 3.2.3 (Hex package) (mix

* NodeJS version (node -v):

4.2.6

* NPM version (npm -v):

3.5.2

* Operating system:

ubuntu 16.04

### Expected behavior

```
mix phx.gen.json Objects Game games name:string configuration:map
<add games resource to router>
mix test
<tests are green>
```

### Actual behavior

```
mix phx.gen.json Objects Game games name:string configuration:map
<add games resource to router>
mix test
...** (CompileError) test/rzjb/web/controllers/game_controller_test.exs:2: module Rzjb.Web.ConnCase is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    test/rzjb/web/controllers/game_controller_test.exs:2: Rzjb.Web.GameControllerTest (module)
    (elixir) lib/code.ex:370: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:57: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5

```

**Comment by chrismccord** [comment]
Thanks for the report. I'll take a look!

**Comment by chrismccord** [comment]
This has been fixed in https://github.com/phoenixframework/phoenix/commit/8d34c3bcc538e750c3f3a336e2ef435fd2525795 and will be merged to master soon. Thanks for the report!
