### ISSUE TITLE
Compilation fails on code reload (maybe due to new elixir version)

### ISSUE THREAD

**Issue by chime-mu** [phoenixframework/phoenix#2394]
### Environment

* Elixir version (elixir -v): Erlang/OTP 20 Elixir 1.5.0-rc.1 (704fb9599)

* Phoenix version (mix deps): phoenix 1.2.4
* NodeJS version (node -v): v6.11.1
* NPM version (npm -v):3.10.10
* Operating system:Linux, ubuntu 16.04

### Expected behavior

When modifying files (router, controller, template), the code will be recompiled correctly

### Actual behavior

On hot code reload, I got
```
== Compilation error in file lib/hello_phoenix/endpoint.ex ==
** (ArgumentError) argument error
    (stdlib) :ets.new(HelloPhoenix.Endpoint, [:set, :public, :named_table])
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
[error] Phoenix.CodeReloader.Server HelloPhoenix.Endpoint.CodeReloader received unexpected message in handle_info/2: {:DOWN, #Reference<0.2794923760.963379201.248324>, :process, #PID<0.505.0>,
 :killed}
```

When stopping and restarting the server the code compiled without a problem

This happened while going the Phoenix example *Adding Pages*

**Comment by josevalim** [comment]
Thank you, this is a bug in Elixir which has been fixed on v1.5.0-rc.2. So you can either upgrade Elixir or downgrade to 1.4.5 (stable).
