### ISSUE TITLE
Plug.MIME.type/1 is deprecated, please use MIME.type/1 instead

### ISSUE THREAD

**Issue by ramka001** [phoenixframework/phoenix#2402]
### Environment

* Elixir version (elixir -v): 1.4.5
* Phoenix version (mix deps): 1.2.4
* NodeJS version (node -v): v4.2.6
* NPM version (npm -v): 5.3.0
* Operating system: Elementary OS Loki (Ubuntu 16.04 LTS)

### Expected behavior
Generated equinox app
[info] Running Equinox.Endpoint with Cowboy using http://localhost:4000
25 Jul 15:54:50 - info: compiled 6 files into 2 files, copied 3 in 965ms
[info] GET /
[debug] Plug.Session could not verify incoming session cookie. This may happen when the session settings change or a stale cookie is sent.
[debug] Processing by Equinox.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 17ms

### Actual behavior

[info] GET /
[debug] Plug.Session could not verify incoming session cookie. This may happen when the session settings change or a stale cookie is sent.
[debug] Processing by Equinox.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
Plug.MIME.type/1 is deprecated, please use MIME.type/1 instead
    (phoenix) lib/phoenix/controller.ex:636: Phoenix.Controller.do_render/4
    (equinox) web/controllers/page_controller.ex:1: Equinox.PageController.action/2
    (equinox) web/controllers/page_controller.ex:1: Equinox.PageController.phoenix_controller_pipeline/2
    (equinox) lib/equinox/endpoint.ex:1: Equinox.Endpoint.instrument/4
    (equinox) lib/phoenix/router.ex:261: Equinox.Router.dispatch/2
    (equinox) web/router.ex:1: Equinox.Router.do_call/2
    (equinox) lib/equinox/endpoint.ex:1: Equinox.Endpoint.phoenix_pipeline/1
    (equinox) lib/plug/debugger.ex:99: Equinox.Endpoint."call (overridable 3)"/2
    (equinox) lib/equinox/endpoint.ex:1: Equinox.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /opt/development/workspace/equinox/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

## Quick Fix  is to update the Phoenix.Controller replace  

line 636  
###  content_type = Plug.MIME.type(format)
  to  
###  content_type = MIME.type(format)

and line 958
###  defp parse_exts(type),         do: Plug.MIME.extensions(type) 
 to

**Comment by josevalim** [comment]
Yes, you either need to update Phoenix or set plug to `{:plug, "~> 1.3.0"}` in your deps.

**Comment by ramka001** [comment]
FYI, the later release of :plug is still causing the problem {:plug, "~> 1.4"}

**Comment by josevalim** [comment]
Yes, you need to either update Phoenix or set plug to `{:plug, "~> 1.3.0"}`.
