### ISSUE TITLE
Could not create a new project with mix phx.new of 1.3.0-rc.3

### ISSUE THREAD

**Issue by blisscs** [phoenixframework/phoenix#2404]
Hello There,

I would like to update an issue when I try the ``mix phx.new``. I am getting the below error -

```
$ mix phx.new test
** (KeyError) key :lib_web_name not found
    lib/phx_new/single.ex:99: Phx.New.Single.put_web_app/1
    lib/mix/tasks/phx.new.ex:116: Mix.Tasks.Phx.New.generate/3
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```
* Elixir version (elixir -v): 1.4.4
* Phoenix version (mix deps): 1.3.0-rc.3
* Operating system: ubuntu 17.04

When using with elixir version 1.4.5. It's working fine.

**Comment by chrismccord** [comment]
This looks like an old archive conflicting with the new one. Please run

    mix archive.uninstall phx_new

then reinstall the 1.3 archive with:

    mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez

**Comment by blisscs** [comment]
Thank you @chrismccord. Remove and reinstall the 1.3 archive make it works now.

**Comment by jailandrade** [comment]
Thanks @chrismccord! your solution works for me

**Comment by Dwiga** [comment]
@chrismccord cool.. it's works
