### ISSUE TITLE
Installation fails on Elixir 1.5.0

### ISSUE THREAD

**Issue by neeharv** [phoenixframework/phoenix#2408]
### Environment

* Elixir version (elixir -v): 1.5.0
* Phoenix version (mix deps): 0.10.0
* NodeJS version (node -v): 7.1.0
* NPM version (npm -v): 4.6.1
* Operating system: OS X 10.2.5

### Expected behavior
Phoenix is installed succesfully

### Actual behavior
Following the guide here - http://www.phoenixframework.org/v0.10.0/docs/getting-started

1. `brew update && brew install elixir`
2. `git clone https://github.com/phoenixframework/phoenix.git && cd phoenix && git checkout v0.10.0 && mix do deps.get, compile`

Error-
```txt
== Compilation error in file lib/phoenix/socket.ex ==
** (ArgumentError) Access is not a protocol, cannot derive Access for Phoenix.Socket
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    (elixir) lib/protocol.ex:614: Protocol.derive/5
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) lib/protocol.ex:602: Protocol.__derive__/3
    lib/phoenix/socket.ex:24: (module)
```

**Comment by sevenseacat** [comment]
That's a really old version of Phoenix... any reason you're not using anything newer? 1.3rc3 is the most recent.

**Comment by neeharv** [comment]
Ah, looks like I got the version wrong. If you google `phoenix get started`, the first link takes you to the installation page of the 0.10 version, which I assumed was the latest. Thank you for helping me out with this 👍
