### ISSUE TITLE
Mix phx.routes doesn't found the autogenerated router

### ISSUE THREAD

**Issue by bdusauso** [phoenixframework/phoenix#2409]
### Environment

* Elixir version: 1.4.5
* Phoenix version: 1.3.0-rc3
* NodeJS version: project generated with --no-brunch
* NPM version: project generated with --no-brunch
* Operating system: MacOS 10.12.5

### Expected behavior

`mix phx.routes` would find the router by itself and list all the routes

### Actual behavior

`** (Mix) no router found at CoreWeb.Router or Core.Router.
An explicit router module may be given to phx.routes.`

Explicitly passing the `Core.Web.Router` works fine

**Comment by bdusauso** [comment]
It seems my configuration was messed up, some rc2/rc3 confusion.
Sorry for the inconvenience.

**Comment by josevalim** [comment]
No worries, thanks for trying the RCs out!

**Comment by joaquinalcerro** [comment]
@bdusauso I am using Coherence and experiencing this behavior. Can you help me out with the configuration issues you found? Thanks
