### ISSUE TITLE
Generate scheme creates wrong index for `references` fields

### ISSUE THREAD

**Issue by mveytsman** [phoenixframework/phoenix#2412]
### Environment

* Elixir version (elixir -v): Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
* Phoenix version (mix deps):  1.3.0-rc.3
* NodeJS version (node -v): v6.11.1
* NPM version (npm -v): 3.10.10
* Operating system: OSX 10.11

### Expected behavior

When running `mix phx.gen.schema  Foo foos bar:references:bars` I expect to see the following in `priv/repo/migrations/TIMESTAMP_create_foos.exs`:

```elixir
defmodule Abacist.Repo.Migrations.CreateFoos do
  use Ecto.Migration

  def change do
    create table(:foos) do
      add :bar_id, references(:bars, on_delete: :nothing)

      timestamps()
    end

    create index(:foos, [:bar_id])
  end
end
```

### Actual behavior

I see the following:
```elixir
defmodule Abacist.Repo.Migrations.CreateFoos do
  use Ecto.Migration

  def change do
    create table(:foos) do
      add :bar_id, references(:bars, on_delete: :nothing)

      timestamps()
    end

    create index(:foos, [:bar])
  end
end
```
I get the following error on `mix ecto.migrate`

```
13:53:37.940 [info]  create index foos_bar_index
** (Postgrex.Error) ERROR 42703 (undefined_column): column "bar" does not exist
...
`

**Comment by chrismccord** [comment]
This behavior is correct since we require the explicit name of the foreign key. In your case, you need to use this command:

    mix phx.gen.schema Foo foos bar_id:references:bars

Note the `bar_id` instead of `bar`. Hope that helps. Thanks!

**Comment by mveytsman** [comment]
ooooooppppsss I didn't read the docs carefully enough sorry!

It's confusing because `bar:references:bars` generates 

```
 add :bar_id, references(:bars, on_delete: :nothing)
```

So it's somehow inflecting `bar_id` from `bar` in one place but not the other.
