### ISSUE TITLE
The phx_new.ez archive file is for 1.3.0-rc.3 instead of the expected 1.3.0 release

### ISSUE THREAD

**Issue by esvinson** [phoenixframework/phoenix#2414]
### Environment
N/A

### Expected behavior
https://github.com/phoenixframework/archives/blob/master/phx_new.ez  should be the 1.3.0 release

### Actual behavior
It appears the new archive wasn't pushed before the release announcement/tag was created.

https://github.com/phoenixframework/archives/blob/master/phx_new.ez is 1.3.0-rc.3 instead of 1.3.0

**Comment by chrismccord** [comment]
I forgot to push. Fixed & Thanks!
