### ISSUE TITLE
mix phx.routes is missing a "." in web_mod/2

### ISSUE THREAD

**Issue by buelsenfrucht** [phoenixframework/phoenix#2423]
Version 1.3.0-rc3 introduced method web_mod/2.
Path: lib/mix/tasks/phx.routes.ex

I think it should be 

`defp web_mod(base, name), do: Module.concat(["#{base}.Web", name])`
instead of
`defp web_mod(base, name), do: Module.concat(["#{base}Web", name])`

**Comment by josevalim** [comment]
Phoenix v1.3.0 (the final version) uses `MyAppWeb` as the namespace and not `MyApp.Web`, so the current version is correct. :) Thank you for the report!
