### ISSUE TITLE
1.3.0 RC3 -> 1.3.0 Upgrade Issue

### ISSUE THREAD

**Issue by brandonparsons** [phoenixframework/phoenix#2427]
Hi there,

Just upgraded to the full release version of 1.3.0 (from RC3) with basically no issues. The only trouble I'm running into is from the websocket library.

I'm getting the following error in the javascript console:

```
WebSocket connection to 'ws://localhost:4000/phoenix/live_reload/socket/websocket?vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 403
```

And the following error shows in my server logs:

```
[error] The client's requested channel transport version "2.0.0" does not match server's version requirements of "~> 1.0.0"
```

I have run a `mix clean` and blown away all of the javascript assets (`rm -rf priv/static`).

Versions:

```
  "phoenix": {:hex, :phoenix, "1.3.0", "1c01124caa1b4a7af46f2050ff11b267baa3edb441b45dbf243e979cd4c5891b", [:mix], [{:cowboy, "~> 1.0", [hex: :cowboy, repo: "hexpm", optional: true]}, {:phoenix_pubsub, "~> 1.0", [hex: :phoenix_pubsub, repo: "hexpm", optional: false]}, {:plug, "~> 1.3.3 or ~> 1.4", [hex: :plug, repo: "hexpm", optional: false]}, {:poison, "~> 2.2 or ~> 3.0", [hex: :poison, repo: "hexpm", optional: false]}], "hexpm"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "3.2.3", "450c749876ff1de4a78fdb305a142a76817c77a1cd79aeca29e5fc9a6c630b26", [:mix], [{:ecto, "~> 2.1", [hex: :ecto, repo: "hexpm", optional: false]}, {:phoenix_html, "~> 2.9", [hex: :phoenix_html, repo: "hexpm", optional: true]}, {:plug, "~> 1.0", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
  "phoenix_html": {:hex, :phoenix_html, "2.9.3", "1b5a2122cbf743aa242f54dced8a4f1cc778b8bd304f4b4c0043a6250c58e258", [:mix], [{:plug, "~> 1.0", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.8", "4333f9c74190f485a74866beff2f9304f069d53f047f5fbb0fb8d1ee4c495f73", [:mix], [{:fs, "~> 0.9.1", [hex: :fs, repo: "hexpm", optional: false]}, {:phoenix, "~> 1.0 or ~> 1.2-rc", [hex: :phoenix, repo: "hexpm", optional: false]}], "hexpm"},
  "phoenix_pubsub": {:hex, :phoenix_pubsub, "1.0.2", "bfa7fd52788b5eaa09cb51ff9fcad1d9edfeb68251add458523f839392f034c1", [:mix], [], "hexpm"}
```

Elixir: 1.5.0
Erlang: 20.0
Node: 8.2.1
NPM: 5.3.0
Mac OS X

**Comment by josevalim** [comment]
Did you try nuking node_modules?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
Can you provide the contents of your `UserSocket` file? Thanks!

**Comment by chrismccord** [comment]
Your js is updated, since the js is correct that it is asking for 2.0. The issue is the server is only accepting 1.0. So maybe you have a hard-coded transport serializer at `~> 1.0`?

**Comment by brandonparsons** [comment]
You guys don't mess around :)

I don't have a `UserSocket` file explicitly - I'm not using Phoenix channels at all yet.

I have the following in `endpoint.ex`:

```elixir
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end
```

I tried blowing away the entirety of `node_modules`, then did a `mix clean` and removed `priv/static`. Recompiled everything, and still getting the issue.

**Comment by brandonparsons** [comment]
In my `mix.exs` file I have `{:phoenix_live_reload, "~> 1.0", only: :dev}` --- should this be changed?

**Comment by chrismccord** [comment]
As a sanity check for me, can you kill the server and make sure nothing else is running on port 4000, such as an older phoenix project? 

    $ lsof -i :4000

That should return nothing and verify there isn't another phoenix app that the 2.0 front-end is trying to hit. After that, please give things another shot and let us know if the log still persists. There's nothing in Phoenix 1.3.0/Phoenix Live Reload 1.0.8 that would restrict things to channel v1.0.0. The only way I can see this happening is if the server is running an older Phoenix version <= 1.3.rc2

**Comment by chrismccord** [comment]
Actually, it sounds like `phoenix_live_reload` didn't get recompiled. Please also try `mix deps.clean phoenix_live_reload`. `mix clean` will also clean your project build, but leave deps untouched.

**Comment by brandonparsons** [comment]
@chrismccord That seems to have fixed it (`mix deps.clean phoenix_live_reload`).

Closing the issue, as seems to be purely user error!
