### ISSUE TITLE
phoenix watchers fail for npm

### ISSUE THREAD

**Issue by tcoopman** [phoenixframework/phoenix#2433]
Trying to add a npm script to watchers fails:

```
** (ErlangError) Erlang error: :eacces
    erlang.erl:2112: :erlang.open_port({:spawn_executable, 'c:/Program Files/nodejs/npm.cmd'}, [:use_stdio, :exit_status, :binary, :hide, {:args, ["ls"]}])
    (elixir) lib/system.ex:611: System.cmd/3
```

This looks the same like in #683.

### Environment

* Elixir version: 1.5.0
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 8.1.2
* NPM version (npm -v):  5.03
* Operating system: windows 10

**Comment by josevalim** [comment]
What is your Erlang version?

**Comment by josevalim** [comment]
It is either a permission access on the .cmd file OR you are using an Erlang version that does not support `.cmd` extensions.

**Comment by tcoopman** [comment]
I'm going to check on monday, it's my work laptop. But I believe I'm on erlang 20.

**Comment by tcoopman** [comment]
I'm on erlang 20 and running iex as administrator also doesn't fix the issue.

**Comment by josevalim** [comment]
If you rename it to `.bat` like the original issue suggests, does it work?

**Comment by josevalim** [comment]
Also, are you able to invoke that `npm.cmd` manually?

**Comment by tcoopman** [comment]
I can invoke `npm.cmd` manually.
Renaming to `npm.bat` does indeed fix the issue

**Comment by josevalim** [comment]
@tcoopman so it is still an Erlang issue. I thought this was resolved but apparently not quite. I will report it to the appropriate place, thank you!
