### ISSUE TITLE
400 bad request issues

### ISSUE THREAD

**Issue by fbjork** [phoenixframework/phoenix#2437]
Recently we were bitten by random 400 bad requests to our website due to header values exceeding 4k which is the default in Cowboy. It was hard to debug this issue as there were no stack trace shown in the logs.

To fix this issue I added this to the Endpoint config:

```elixir
http: [protocol_options: [max_request_line_length: 8192, max_header_value_length: 8192]
```

Therefore I would like to propose 2 changes in Phoenix:

1. Show better logs when 400 bad requests happen
2. Increase the default max header values size to 8k

**Comment by josevalim** [comment]
Plug v1.4.0 includes those warnings. Which version are you using?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fbjork** [comment]
@josevalim 1.4.3. It only warns if the headers are empty I believe?

**Comment by josevalim** [comment]
@fbjork in my tests the headers were always empty if cowboy reached any of those limits.

**Comment by fbjork** [comment]
@josevalim we didn't see anything in our logs after upgrading to Plug 1.4.3

**Comment by josevalim** [comment]
I will try to reproduce it here once again but I am afraid something else may be at play. Maybe a copy of the request headers could help me consistently reproduce it?

**Comment by fbjork** [comment]
You should be able to reproduce by sending headers with cookies that are larger than 4k to Phoenix/Cowboy.

**Comment by josevalim** [comment]
@fbjork that's what I did. I did it once again and I could reproduce the message. Here are the steps:

Add the following to "plug.exs" inside any project that has plug 1.4.0+ as a dependency:

```elixir
defmodule MyPlug do
  import Plug.Conn

  def init(options) do
    # initialize options

    options
  end

  def call(conn, _opts) do
    conn
    |> put_resp_content_type("text/plain")
    |> send_resp(200, "Hello world")
  end
end

{:ok, _} = Plug.Adapters.Cowboy.http MyPlug, []
```

Now run `mix run --no-halt plug.exs`. Visit the page at `localhost:4040` and you should see "Hello world". Now set a large cookie using the browser console (in Chrome I did Application -> Storage -> Cookies). Then I did a new request and saw this in the terminal:

```elixir
00:00:50.654 [error] Cowboy returned 400 and there are no headers in the connection.

This may happen if Cowboy is unable to parse the request headers,
for example, because there are too many headers or the header name
or value are too large (such as a large cookie).

You can customize those values when configuring your http/https
server. The configuration option and default values are shown below:

    protocol_options: [
      max_header_name_length: 64,
      max_header_value_length: 4096,
      max_headers: 100,
      max_request_line_length: 8096
    ]
```

**Comment by jolson88** [comment]
I just ran into this today but for a different reason. And in our case, the new code was a false positive as it wasn't an error. Basically, our load balancer (F5) was doing a `GET /` for a health check (with no headers). For some reason (still TBD), the library that is serving the request (Graphiql) returns 400, assuming it expects certain headers to be present. So in our case, it was a valid 400 and the request had no headers, so it wasn't any sort of parsing error. But the new code generates Logger.error (even though it's not actually a logger in this case): https://github.com/elixir-plug/plug/blob/master/lib/plug/adapters/cowboy.ex#L240. 

This has caused us to get an extraneous amount of logging out after upgrading from 1.3.5 to 1.4.3 of Plug because this happens every five seconds on every single web node we have in production. 

Any thoughts on proper fix?

**Comment by jeroenbourgois** [comment]
Would like some more info too, the same output when sending a request without headers. I do not really know what settings to apply to allow the headers. Still have to find out who is making the headerless requests... But it is hard to see in the logs because of all these warnings :)

**Comment by efexen** [comment]
Having trouble with this as well right now.

Recently updated our Phoenix from 1.3.0-rc to 1.3.0 which changed Plug from 1.3.5 to 1.4.3  and the errors started as we deployed this.

We use an AWS LoadBalancer (ALB) and it appears to be the health check request is missing headers causing Cowboy to return 400. This also causes the instance to be marked as inactive.

I've not seen any way to add headers for the health check so bit stuck as to how to resolve this.

**Comment by josevalim** [comment]
@efexen can you write down the request that is sent by ALB? I need a mechanism to reproduce this issue because I cannot (I have even pasted a minimal app above).

**Comment by efexen** [comment]
@josevalim not sure how I'd go about capturing the request

**Comment by efexen** [comment]
@josevalim doing this locally reproduces the error:
`curl http://localhost:4000 -H 'User-Agent:' -H 'Accept:' -H 'Host:'`

The 3 headers listed above are not sent as they don't have a value set

**Comment by josevalim** [comment]
@efexen I tried this in the plug mentioned above and got:

```
18:29:28.274 [error] Cowboy returned 400 and there are no headers in the connection.

This may happen if Cowboy is unable to parse the request headers,
for example, because there are too many headers or the header name
or value are too large (such as a large cookie).

You can customize those values when configuring your http/https
server. The configuration option and default values are shown below:

    protocol_options: [
      max_header_name_length: 64,
      max_header_value_length: 4096,
      max_headers: 100,
      max_request_line_length: 8096
    ]
```

What am I missing?

**Comment by efexen** [comment]
@josevalim that's the error, problem is that the AWS LoadBalancer we are using doesn't send headers and I don't think it can be configured to send headers as part of it's health check.

In the previous version this returned 200 and didn't error out.

**Comment by josevalim** [comment]
@efexen this error is only reported if Cowboy returns 400: https://github.com/elixir-plug/plug/blob/master/lib/plug/adapters/cowboy.ex#L240-L259

So Plug is not changing a previous 200 to a 400. Maybe you also updated your Cowboy version and that broke things?

**Comment by sjmueller** [comment]
We're being hit by this one by trying to run `MIX_ENV=prod mix phx.server`locally on our dev machines. It really would be great to surface why cowboy replied with 400, rather than just this generic "catch all" error. We're left in the dark having no idea how to satiate cowboy so that it has what it needs to run smoothly.

**Comment by josevalim** [comment]
Folks, I don't know how else I can put this. We understand this is frustrating and we would love to fix this error but nobody has provided a mechanism to reproduce it so we are simply unable to fix it. In all tests I have done using Plug v1.4.0 onwards something is sent to the Logger.

**Comment by britto** [comment]
In our case the issue was related to one of the header values being too long, so increasing `max_header_value_length` to 8k solved the problem.

I agree with @josevalim about the fact that there is no simple way to intercept requests in Phoenix and debug them before they reach Cowboy. We can, however, resort to some alternatives. If our app is behind a CDN or another webserver we can try to track down offending requests –those that violate the restrictions defined in `protocol_options`– by going over their logs instead.

**Comment by efexen** [comment]
@josevalim I think I get what you mean now, I've tested it with older versions of Plug and on `1.3.5` it silently fails with a 400 where as after updating Plug to `1.4.0` the error is sent to the Logger which causes a lot of errors to be logged.

I think the fact that it was silently failing was masking the fact that it was not working under the hood.

This does highlight potentially another problem though; that Cowboy returns 400 for AWS LoadBalancer status checks because of missing headers. Should I log this somewhere else or am I missing something?

**Comment by astjohn** [comment]
@efexen, @josevalim - I'm not entirely sure if this is related, but our health checks were fine on Google Cloud until we decided to force phoenix to use ssl everywhere. Now seeing a similar error to this. I'm assuming GCE also has empty headers when the load balancer is making its requests.

**Comment by pdamoc** [comment]
Are there any configuration options that would silence this error for requests without headers (this seams to be the case for our production app, a health check without headers).  

We are using nginx in a reverse proxy configuration with multiple phoenix 1.3 apps running of different ports. All pages use "Let's Encrypt" SSL certificates mounted on nginx.

**Comment by josevalim** [comment]
@pdamoc on plug master there is such configuration: https://github.com/elixir-plug/plug/blob/master/lib/plug/adapters/cowboy.ex#L34

**Comment by pdamoc** [comment]
@josevalim is it possible to set that flag to `false` through phoenix configuration?

**Comment by josevalim** [comment]
@pdamoc iirc you set it under `http: [log_error_on_incomplete_requests: false]` (and https).

**Comment by pdamoc** [comment]
@josevalim as per the edited comment above, I tried that and failed to start the app (`:badarg`)

**Comment by josevalim** [comment]
Can you please post full stacktrace and everything?

**Comment by pdamoc** [comment]
```
Mac-mini:appname username$ mix phx.server
[info] Application appname exited: AppName.Application.start(:normal, []) returned an error: shutdown: failed to start child: AppNameWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Handler
        ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, AppNameWeb.Endpoint.HTTP}
            ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup
                ** (EXIT) :badarg
[info] Application phoenix_ecto exited: :stopped
[info] Application absinthe_ecto exited: :stopped
[info] Application ecto exited: :stopped
[info] Application poolboy exited: :stopped
[info] Application money exited: :stopped
[info] Application postgrex exited: :stopped
[info] Application decimal exited: :stopped
[info] Application db_connection exited: :stopped
[info] Application connection exited: :stopped
[info] Application guardian exited: :stopped
[info] Application uuid exited: :stopped
[info] Application jose exited: :stopped
[info] Application base64url exited: :stopped
[info] Application phoenix_live_reload exited: :stopped
[info] Application file_system exited: :stopped
[info] Application absinthe_plug exited: :stopped
[info] Application absinthe exited: :stopped
[info] Application swoosh exited: :stopped
[info] Application phoenix_html exited: :stopped
[info] Application cowboy exited: :stopped
[info] Application cowlib exited: :stopped
[info] Application ranch exited: :stopped
[info] Application csv exited: :stopped
[info] Application parallel_stream exited: :stopped
[info] Application comeonin exited: :stopped
[info] Application number exited: :stopped
[info] Application pbkdf2_elixir exited: :stopped
[info] Application logger_file_backend exited: :stopped
[info] Application httpotion exited: :stopped
[info] Application ibrowse exited: :stopped
[info] Application rollbax exited: :stopped
[info] Application timex exited: :stopped
[info] Application combine exited: :stopped
[info] Application tzdata exited: :stopped
[info] Application hackney exited: :stopped
[info] Application metrics exited: :stopped
[info] Application ssl_verify_fun exited: :stopped
[info] Application certifi exited: :stopped
[info] Application mimerl exited: :stopped
[info] Application idna exited: :stopped
[info] Application unicode_util_compat exited: :stopped

=INFO REPORT==== 20-Dec-2017::12:54:11 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application appname: AppName.Application.start(:normal, []) returned an error: shutdown: failed to start child: AppNameWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Handler
        ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, AppNameWeb.Endpoint.HTTP}
            ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup
                ** (EXIT) :badarg
```

**Comment by josevalim** [comment]
@pdamoc I cannot reproduce it locally when using Plug latest master. What is your Phoenix version?

**Comment by josevalim** [comment]
Or even better, can you reproduce it in a new app and push it to GitHub?

**Comment by pdamoc** [comment]
I'm using Phoenix 1.3.0 

I can reproduce the issue by creating a new app with `mix phx.new appname` and just adding the `http` config line from above. 

Here is a sample repo with the error included:
https://github.com/pdamoc/cowboy_issue

**Comment by webdeb** [comment]
@pdamoc it would be easier if the first commit would be the default phx project, and the second commit your changes..

**Comment by pdamoc** [comment]
@webdeb the only change I made was to add this line:
https://github.com/pdamoc/cowboy_issue/blob/master/config/config.exs#L15

**Comment by josevalim** [comment]
@pdamoc you need to use Plug master. The option indeed won't work in previous Plug versions. Add this to your mix.exs:

    {:plug, github: "elixir-plug/plug", override: true}

**Comment by josevalim** [comment]
Oh, you can also use:

    {:plug, "~> 1.5.0-rc.0", override: true}

**Comment by pdamoc** [comment]
@josevalim Thank you! I can confirm that the `curl` command from above that I was using to trigger the error no longer produces a logged error.

**Comment by EvertYipYip** [comment]
I only received this error when `force_ssl: [rewrite_on: [:x_forwarded_proto]]` was set in my endpoint config

**Comment by stevegraham** [comment]
In our app we have a Phoenix app that proxies requests to another Phoenix app. With tcpdump I noticed this error when an external client would chunk the request to the 1st service, and we didn't strip the "transfer-encoding" request header. Therefore our 2nd service would receive a request with the "transfer-encoding: chunked" request header but a normally encoded request body from the 1st service (because the 1st service read, and processed the entire request before proxying).

Hope this helps someone.

**Comment by josevalim** [comment]
I think this is all addressed. Thanks everyone for the input! :heart:

**Comment by saxxi** [comment]
Hi, we are getting the same issue where on AWS ECS the load balancer pings our server with empty `Host` headers causing the system to think the app is unhealthy and therefore request its termination.

We tried different approaches (`plug middleware`, `static file` as `/status`, `put_req_header`, `log_error_on_incomplete_requests: false`), but none seems working.

This is our configuration:

```
config :notification_service, NotificationServiceWeb.Endpoint,
 check_origin: false,
 http: [log_error_on_incomplete_requests: true],
 render_errors: [view: NotificationServiceWeb.ErrorView, accepts: ~w(json)],
 pubsub: [name: NotificationService.PubSub,
          adapter: Phoenix.PubSub.PG2]
```

```
  defp deps do
    [ ....
       {:plug, "~> 1.5.1", override: true},
    ]
  end
```

```
config :notification_service, NotificationServiceWeb.Endpoint,
  http: [port: 4000],
  https: [port: 4443, # <- tried to disable this but it doesn't change
          otp_app: :notification_service,
          keyfile: "priv/keys/localhost.key",
          certfile: "priv/keys/localhost.cert"],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []
```

```
base64url 0.0.1
 connection 1.0.4
 corsica 1.1.2
 cowboy 1.1.2
 cowlib 1.0.2
 db_connection 1.1.3
 decimal 1.5.0
 distillery 1.5.2
 ecto 2.2.10
 gettext 0.15.0
 guardian 1.0.1
 joken 1.5.0
 jose 1.8.4
 mime 1.3.0
 phoenix 1.3.2
 phoenix_ecto 3.3.0
 phoenix_pubsub 1.0.2
 plug 1.5.1
 poison 3.1.0
 poolboy 1.5.1
 postgrex 0.13.5
 ranch 1.3.2
 socket 0.3.13
 uuid 1.1.8
```

As we're close to deployment and system is failing we'd be, in extreme emergency situation, also okay with a monkey patch solution or any kind of hack.

Any ideas? Thank you :)

**Comment by OvermindDL1** [comment]
@saxxi I'd recommend asking this on the elixir forums.

As an aside, does `curl -I <full-url>` work?  What output does it give?

**Comment by saxxi** [comment]
Thanks for replying @OvermindDL1. This is what happens `with Host`:

```
$ curl -i localhost:4000/status  -H 'Host:anything-here'
HTTP/1.1 200 OK
server: Cowboy
date: Mon, 04 Jun 2018 07:18:34 GMT
content-length: 19
cache-control: max-age=0, private, must-revalidate

{"version":"0.0.3"}%
```

And this is what we think is happening on the server side, ie from `AWS ALB`'s health check, reproducible as above in local env too:

```
$ curl -i localhost:4000/status  -H 'Host:'
HTTP/1.1 400 Bad Request
connection: close
server: Cowboy
date: Mon, 04 Jun 2018 07:19:17 GMT
content-length: 0
```

The logged error (same as `production`):

```
[error] Cowboy returned 400 because it was unable to parse the request headers.

This may happen because there are no headers, or there are too many headers
or the header name or value are too large (such as a large cookie).

You can customize those values when configuring your http/https
server. The configuration option and default values are shown below:

    protocol_options: [
      max_header_name_length: 64,
      max_header_value_length: 4096,
      max_headers: 100,
      max_request_line_length: 8096
    ]
```

Regarding the solution to the issue I was hoping we could add or replace a `plug` before [this line](https://github.com/elixir-plug/plug/blob/master/lib/plug/adapters/cowboy.ex#L273) kicks in and inject something like:

```
# Request -> [OurMiddleware] -> [Plug] -> [Phoenix] -> ...

defmodule NotificationServiceWeb.Endpoint do
  plug :add_host_if_blank
  use Phoenix.Endpoint

  defp add_host_if_blank
      conn = conn
      |> put_req_header("Host", "custom-host") # this seems to work only on testing?
  end
end
```

How can I achieve this?

**Comment by knightq** [comment]
The RFC itself impose to respond with 400 on missing host header.

> All Internet-based HTTP/1.1 servers MUST respond with a 400 (Bad Request) status code to any HTTP/1.1 request message which lacks a Host header field.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

**Comment by knightq** [comment]
The problem is that if Cowboy forces (without escapes) this behaviour, any Cowboy based app (almost every Phoenix ones) wont work on AWS...
Even if I agree that Amazon should adhere to the RFC, I doubt that they will (soon), and it would be great if we can "close an eye" in these cases...

**Comment by efexen** [comment]
I'd just like to echo my support for what @knightq is saying above.

The AWS behaviour might well be outside of the RFC spec and arguably should be addressed and Cowboy quite rightly is following said spec strictly as expected.

This does however put the wider adoption of Phoenix in to a tricky place in the middle where the biggest cloud services provider is incompatible. This community is very small and has no leverage on AWS to make what could be a breaking change to the way their load balancers operate and.

As much as I hate it but some type of option to behave out of spec for either Cowboy or Phoenix would be ideal solution to unblock teams keen to adopt this.

**Comment by josevalim** [comment]
Phoenix can't do anything. The request is being rejected before it reaches Phoenix.

**Comment by mnussbaumer** [comment]
Can't you configure the health check to use a tcp port instead?

**Comment by knightq** [comment]
No, we need an application load balancer (HTTP) to handle evenly the SSL certs.

**Comment by mnussbaumer** [comment]
@knightq I was recently looking into AWS Load Balancers, and from the previous posts my understanding was that the problem you're running into is due to the health checks sent by the Load Balancer missing the Host header (not regular load balanced traffic). What I read on the AWS documentation was that it allows you to customise how you want to perform the health checks, and so that you can use a tcp port instead of an http, which means you can write a small tcp receive block that just replies correctly?

(btw I'm not saying cowboy shouldn't allow to be "overriden", but that this can be a solution "now" to use the functionality while pushing for a correction both on AWS and/or cowboy to allow another response)

**Comment by knightq** [comment]
Hi @mnussbaumer, you are right: the problem is the Health check on the AWS Elastic Container Service Application Load Balancer.
Unfortunately you cannot choose which kind of check to perform.

If you need an Application (HTTP) Load Balancer (we do) you get an HTTP check.
It you can use a TCP Load Balancer (we cannot) you get a TCP check.

AFAIK, you cannot change the "type" of check (i.e. performa a TCP health check on a HTTP LB) and makes also sense.

Again, thank you for your interest in this issue.

**Comment by knightq** [comment]
Anyway, @essen is looking at [this issue on cowboy](https://github.com/ninenines/cowboy/issues/1294), let's hope he will fix and also he will backport the fix on 1.x branch (since Phoenix, at least on the currently last stable release 1.3.2, has a dependency on cowboy 1.x)
