### ISSUE TITLE
Phoenix 502 errors Apache HTTP proxy

### ISSUE THREAD

**Issue by martin-langhoff** [phoenixframework/phoenix#2438]
### Environment

* Elixir version (elixir -v): elixir v1.3.3
* Phoenix version (mix deps): 1.2.3
* NodeJS version (node -v): v5.12.0
* NPM version (npm -v): .8.6
* Operating system: CentOS 6

We have a large/complex app based on Phoenix. Apache 2.4 serves static assets, and proxies through to REST endpoints and WebSockets to Elixir/Phoenix.

We occassionally get 502 errors with large POST payloads. This problem goes away immediately if we use, in apache configuration,

```
SetEnv force-proxy-request-1.0 1
SetEnv proxy-nokeepalive 1
```

### Expected behavior
HTTP/1.1 works well, even with keepalives :-)

### Actual behavior
502 errors.

**Comment by chrismccord** [comment]
Do you have any errors on the phoenix side when you get 502's?

**Comment by martin-langhoff** [comment]
None, unfortunately. I apologize for the lack of detail. It is tricky for us to repro in dev/test enviroments, so no network traces either. Yet. We'll be trying to flesh it out. 

Dug through recent changes and issues here in gh and didn't spot anything related.

**Comment by chrismccord** [comment]
Since we've had no movement or further details on this there's no path for us to move forward on it. If you have more insight into the 502's from Apache, please let us know. Thanks!
