### ISSUE TITLE
Database config ignored and no db action taken (new project).

### ISSUE THREAD

**Issue by pbudzik** [phoenixframework/phoenix#2442]
### Environment

* Elixir version (elixir -v): 1.5.1
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system: Ubuntu 16.04

### Expected behavior

Auth errors if wrong credentials, db create if valid.

### Actual behavior

Console:

x@y:/tmp/t4$ mix ecto.create
Compiling 13 files (.ex)
Generated t4 app
The database for T4.Repo has already been created

Intentionally wrong config for dev is ignored. No errors. No db created if valid config.

**Comment by josevalim** [comment]
Can you please provide the config you are trying and the database you are using?

**Comment by pbudzik** [comment]
It is a new gen-ed project. Have changed login/pass only. I have a postgres running.

---
use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :t4, T4Web.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
                    cd: Path.expand("../assets", __DIR__)]]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :t4, T4Web.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/t4_web/views/.*(ex)$},
      ~r{lib/t4_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :t4, T4.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgr1es",
  password: "postg1res",
  database: "t4_dev",
  hostname: "local1host",
  pool_size: 10

**Comment by josevalim** [comment]
Thanks, I was able to reproduce it and moved it to Ecto issues tracker: https://github.com/elixir-ecto/ecto/issues/2169
