### ISSUE TITLE
Longpolling on tvos doesn't work

### ISSUE THREAD

**Issue by spunkedy** [phoenixframework/phoenix#2444]
### Environment

* client environment: tvOS 10.2 
* https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js

### Expected behavior
When trying to use the socket.js inside tvos, web sockets are not available 

When using longPolling I would expect that the library would work. 

```
import {Socket,LongPoll} from "./3rd/socket.js"
let socket = new Socket("/socket", { transport: LongPoll, params: {token: "asdf"}})
```

### Actual behavior

The `location` variable and the `window` variable are not available. 

This is how I have solved it for 1.2.

https://gist.github.com/spunkedy/c8f476a0c5daf417a7b17083a7ced55e

I know that this is such a small percentage. However the longpolling works quite nicely for channels since the ws doesn't. 

Is this something that I should push up a PR for? or just keep my local delta version going.

**Comment by chrismccord** [comment]
If you provide the full endpoint URL, the `window.location` reference should not be hit. Please try this against phoenix.js stable:

    let socket = new Socket("ws://localhost:4000/socket", { transport: LongPoll, params: {token: "asdf"}})

That should be all you need with no changes necessary :)

**Comment by spunkedy** [comment]
I wish, this code still has `window` 

```  static request(method, endPoint, accept, body, timeout, ontimeout, callback){
    if(window.XDomainRequest){
      let req = new XDomainRequest() // IE8, IE9
      this.xdomainRequest(req, method, endPoint, body, timeout, ontimeout, callback)
    } else {
      let req = window.XMLHttpRequest ?
                  new window.XMLHttpRequest() : // IE7+, Firefox, Chrome, Opera, Safari
                  new ActiveXObject("Microsoft.XMLHTTP") // IE6, IE5
      this.xhrRequest(req, method, endPoint, accept, body, timeout, ontimeout, callback)
    }
  }```

**Comment by chrismccord** [comment]
To be clear, can you paste the exact JS errors you run into when providing the full URL? I"m not familiar with tvOS, is there no `window` reference at all? What is the global scope in tvOS?

**Comment by spunkedy** [comment]
Sure, I will also go and update to the latest stable and see what the delta's are that I need. I will also document the errors etc. 

And no, there is no window. This is is TVMLKit with es6. 
https://developer.apple.com/documentation/tvmljs

**Comment by chrismccord** [comment]
Great. Thank you!

**Comment by spunkedy** [comment]
<img width="993" alt="screen shot 2017-08-15 at 1 53 22 am" src="https://user-images.githubusercontent.com/690735/29305138-93cdf172-815c-11e7-9a59-60eda29e7396.png">

using: 

```
let socket = new Socket("http://localhost:4000/socket", { transport: LongPoll, params: {token: "asdf"}})
```

Gets rid of the `location` requirements, however I still need to do a typeof check `typeof window != 'undefined'` to get it working.

If you'd like I can do a PR if you want to review it.

**Comment by chrismccord** [comment]
Please do! I also think we can ditch the window reference for XMLHTTPRequest and consolidate this fix.

**Comment by spunkedy** [comment]
sounds good.

**Comment by aesmail** [comment]
I recently created a "workaround" for phoenix channels to work with NativeScript.
I'm not sure if this could help and/or might give some ideas, but here you go:
https://gist.github.com/aesmail/3270eab8cdae8f6ff78136ba52925be6

**Comment by spunkedy** [comment]
@aesmail maybe we can find a way to support both of the edge cases so we don't have to have delta's everywhere

**Comment by chrismccord** [comment]
@spunkedy any progress on this front?

**Comment by spunkedy** [comment]
@chrismccord no, the project that is using this I hoping to get back to this week.  If that's too uncertain we can close this and I can just do a PR once it's ready

**Comment by spunkedy** [comment]
I put in the pull request here: #2471 

Just in time before I leave for the elixir conf

**Comment by spunkedy** [comment]
This was merged it, closing out
