### ISSUE TITLE
FR: Change fallback mode to upgrade / make connection startup more reliable

### ISSUE THREAD

**Issue by wowcut** [phoenixframework/phoenix#2445]
Hi, from the [source](https://github.com/phoenixframework/phoenix/blob/v1.2/web/static/js/phoenix.js) it looks like the main and only fallback mechanism is [this](https://github.com/phoenixframework/phoenix/blob/ee1fa2a29ac8a11f5b6bd5ce91ccc943156e5916/web/static/js/phoenix.js#L476) line of code: 
```JavaScript
this.transport            = opts.transport || window.WebSocket || LongPoll
```
Is this observation right? Looks like only the most obvious fallback is realized this way and many edge cases are not handled. 

I would like to request to change that to the way socket.io handles [this](https://github.com/socketio/engine.io#goals):
```
...Unlike the previous Socket.IO core, it always establishes a long-polling connection first, then tries to upgrade to better transports that are "tested" on the side...
```
I am sure the socket.io authors have lots of experience with this problem domain and probably their design decision can be somethig to learn from. How do you think of that?

Thanks for your attention!

**Comment by chrismccord** [comment]
If you need auto fallback, you need to handle it yourself by making use of the `transport` option, and `socket.onError` callback to fallback if ws connection fails. We don't plan on adding this kind of support today. In the future, please send questions and feature requests to the mailing lists, slack, irc, or the elixir forums as we reserve the issue tracker for issues around active development. Thanks!

**Comment by wowcut** [comment]
imho you decide too quick.

**Comment by OvermindDL1** [comment]
@wowcut You could make a library that adds that functionality, would be nice to release it on npm/mix.  :-)
