### ISSUE TITLE
When run mix phx.digest that could not minify assets 

### ISSUE THREAD

**Issue by leanhthang** [phoenixframework/phoenix#2448]
I'm developer Rails and newbie in Phoenix, in Raills when i run production mode, Rails support compress and minify assets with `rake assets:precompile RAILS_ENV=production`.
About Phoenix I'm try `mix phx.digest`  it work fine, but that could not minify (css/js) like Rails (Example pattern: https://jscompress.com/).
I’m hoping for some solutions can resolve that.
Thank you,
![app_js_compress](https://user-images.githubusercontent.com/6843034/29436532-2d129ff6-83d6-11e7-9095-e64c954bb8fb.png)
![real_compress](https://user-images.githubusercontent.com/6843034/29437002-9466ddfa-83d8-11e7-934e-99c01a4ed6cd.png)

**Comment by chrismccord** [comment]
Please send support requests to IRC, slack, or the Phoenix forum at elixirforum.com . We reserve the issue list for issues and this appears to be a question about asset minification solutions. Thanks!
