### ISSUE TITLE
Phoenix.Presence "presence_diff" interception duplicates metas with the same phx_ref

### ISSUE THREAD

**Issue by bartekupartek** [phoenixframework/phoenix#2451]
### Environment

* Elixir version (elixir -v): Elixir 1.4.5
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): v8.1.4
* NPM version (npm -v): 5.0.3
* Operating system: macOS Sierra

### Expected behavior

Add standard Presence.track:

```
  def handle_info(:after_join, socket) do
    current_user = socket.assigns.current_user
    Presence.track(socket, current_user.id, %{
      online_at: :os.system_time(:milli_seconds),
      username: current_user.username
    })

    presence_state = Presence.list(socket)
    push socket, "presence_state", presence_state

    {:noreply, socket}
  end
```

Without interception of `presence_diff` event metas count is 1.

Browser:
```
{
  "12": {
    "metas": [
      {
        "username": "bart",
        "phx_ref": "P7Nin/t3RYg=",
        "online_at": 1503313728179,
        "count": 1,
        "id": "12"
      }
    ]
  }
}
```
### Actual behavior

Pass `msg` via `presence_diff` interception:

```
  intercept ["presence_diff"]

  def handle_out("presence_diff", msg, socket) do
    push socket, "presence_diff", msg
    {:noreply, socket}
  end
```

It duplicates metas for each current user eg. user with key 12 has opened one window, but when I just add interception for `presence_diff` then metas are duplicated:

Browser:
```
{
  "12": {
    "metas": [
      {
        "username": "bart",
        "phx_ref": "oIrgQ3O+JlI=",
        "online_at": 1503314448704,
        "count": 2,
        "id": "12"
      },
      {
        "username": "bart",
        "phx_ref": "oIrgQ3O+JlI=",
        "online_at": 1503314448704
      }
    ]
  }
}
```

**Comment by chrismccord** [comment]
Can you verify your phoenix_pubsib version? Are you doing anything in your Presence.fetch callback?

**Comment by bartekupartek** [comment]
I'm using my fork [bartekupartek/phoenix_pubsub](https://github.com/bartekupartek/phoenix_pubsub/) from master, but I've verified that it also occurs on `{:phoenix_pubsub, "1.0.2"}`, I'm not overriding fetch function. 
I've observed in the browser that without interception first arrives `presence_diff` with correct metas than `presence_state`, with interception first `presence_state` than `presence_diff` with already duplicated metas.

**Comment by chrismccord** [comment]
Oh I see, this is duped on the client, not server. I think this is related to the other open issue. I will take a look. Thanks!

**Comment by bartekupartek** [comment]
I've added workaround for this issue.
