### ISSUE TITLE
Request headers aren't persisted during controller tests

### ISSUE THREAD

**Issue by rosswilson** [phoenixframework/phoenix#2452]
### Issue

Controller tests that use the `conn` object with request headers only send those headers for the first request. If the `conn` instance is used to make a second request then any request headers don't get sent to the app.

The Phoenix generators `phx.gen.json` and `phx.gen.html` create controller tests that follow this pattern of making two requests using the same `conn`. When I started to implement auth within my app I discovered that only the first request sends my `authorization` request header.

I did some digging and think that this is where all request headers (apart from `accepts`) are being dropped: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/test/conn_test.ex#L469

### Example app

I've put a bare-bones example app together with a few controller tests replicating this issue: https://github.com/rosswilson/phoenix_req_header_issue

### Expected behaviour

A conn that has been configured with request headers should use those header values for any subsequent requests, not just the first.

I do wonder whether this is intentional, given the below comment. If that is the case, what is the recommended approach for including req headers for multiple requests within a single test? Should I be using `build_conn()` each time?

### Actual behaviour

Only the first request includes the configured headers.

### Environment

* Elixir version (elixir -v): Elixir 1.5.0
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 8.2.1
* NPM version (npm -v): 5.3.0
* Operating system: Mac OS 10.12.6

**Comment by josevalim** [comment]
You don't need to call build_conn() every time but you need to recycle the connection and copy the relevant headers. Maybe you could contribute `recycle/2` that accepts the headers to copy as argument, as that would make your life much easier. :)

I don't think we should simply copy all headers though because some may, indeed, only be specific to some requests.

**Comment by rosswilson** [comment]
Thanks for the lightning fast reply. I like the idea of declaratively defining which request headers should be copied.

> Note `recycle/1` is automatically invoked when dispatching to the endpoint, unless the connection has already been recycled.

This suggests an explicit `recycle` would mark the connection as already recycled, preventing double recycling. Since the currently recycle process is automatically invoked, is there a nice way of keeping this, perhaps a way of defining on the initial conn the headers to keep? e.g.

```
conn = conn
|> put_req_header("authorization", "secret")
|> persist_req_header("authorization")
|> get("/")
```

Or

```
conn = conn
|> put_req_header("authorization", "secret", persist: true)
|> get("/")
```

**Comment by josevalim** [comment]
@rosswilson we could also do that, as long as someone figures out the implementation. Maybe we should store it in conn.private.

**Comment by rosswilson** [comment]
Great, I quite like `put_req_header("authorization", "secret", persist: true)`, would you be open to a PR?

**Comment by josevalim** [comment]
Yup!

**Comment by josevalim** [comment]
Ping!

**Comment by rosswilson** [comment]
Apologies, I started looking into this and must’ve got distracted. Let me take another look and I’ll fire a PR across.

**Comment by josevalim** [comment]
I think a simpler solution here is to simply recycle authorization... since browsers "recycle" that too.

**Comment by rosswilson** [comment]
Maybe you’re right. We could make it configurable, but is it worth it? I wonder if anyone is implicitly relying on the auth to not be persisted?

**Comment by josevalim** [comment]
@rosswilson I don't think so. If they are, they can always call delete_req_header too.

**Comment by mojidabckuu** [comment]
Faced with that issue. What if I am trying to test isolated part of the app. So in that case I have explicitly call everywhere and single line endpoint calls become massive spaghetti being like

```elixir
conn = conn 
  |> put_my_mock_things()
  |> get(con, some_path(conn, :index))
```

Adding some extra logic into `Conn` like `persist: true` or event `put_private(conn, key, value, opts)` which is not considered as part of the real production logic is not good idea, imho. What if we could override recycle fun?

**Comment by AlexGascon** [comment]
@josevalim I'm facing a similar problem but with a different header (a custom one, `api_key`) and just found this issue.

After reading your second comment, I was thinking about implementing `recycle/2` as you mentioned, that would let the user select which headers to persist. Will you still be interested in it?
