### ISSUE TITLE
generated .gitignore does not end in a newline

### ISSUE THREAD

**Issue by jmarca** [phoenixframework/phoenix#2456]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

**Comment by chrismccord** [comment]
Thanks for the report, but I don't see this an issue :)

**Comment by jmarca** [comment]
Sorry, I hit "return" instead of tab.  Updated with the issue.

If I could figure out where the issue is, I'd post a patch, but I don't know enough erlang/elixir to fix.

**Comment by chrismccord** [comment]
Can you send a PR and update the gitignore files inside `installer/templates/` ? Thanks!

**Comment by jmarca** [comment]
Okay.

**Comment by jmarca** [comment]
How/where should I test it?

**Comment by chrismccord** [comment]
We don't need a test so you can simply add a new line to the end of the gitignore files, then save, commit, and PR :)

**Comment by jmarca** [comment]
but... I think I figured out a test...

before
```
iex(6)> {:ok, gitignore} = File.read("installer/templates/phx_assets/brunch/gitignore")
...
iex(7)> gitignore =~ ~r/\n$/                                                           
false
```
after
```
iex(9)> {:ok, gitignore} = File.read("installer/templates/phx_assets/brunch/gitignore")
...
iex(10)> gitignore =~ ~r/\n$/                                                           
true
```

And I wrote a simple test and it is failing, so I'll try to make it pass

**Comment by jmarca** [comment]
created a pull request for the newlines here (PR 2457)

and another for my tests here (PR 2458) 

Not sure my tests are "good enough" and in the right place, but I got them to fail when running the installed version of phx.new and to pass when running the version from the repository...but only after following the instructions to install the new version of phx.new.  I'm not sure how to make those tests under installer run with the *not-installed* version of the installer.
