### ISSUE TITLE
Obsolete links in the main page template

### ISSUE THREAD

**Issue by expilo** [phoenixframework/phoenix#2463]
### Environment

* Elixir version (elixir -v): 1.5.1
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 7.2.1
* NPM version (npm -v): 3.9.0
* Operating system: Debian Jessie

### Expected behavior
Only up-to-date links should be listed on the main page of a new app

### Actual behavior

A new Phoenix app generated with `mix phx.new`  presents links to obsolete and duplicated resources:

* phoenix-talk list (http://groups.google.com/group/phoenix-talk) is deprecated
* there is no link to phoenix forum nor to Slack.
* Although the links `Guides` (http://phoenixframework.org/docs/overview), `Docs` (https://hexdocs.pm/phoenix) and `Get started` (http://www.phoenixframework.org/docs) are different they all point to  the same web page which seems inconsistent.

**Comment by PhillippOhlandt** [comment]
With the Twitter acc is wrong. The Phoenix Twitter account is quite active. You've just seen the pinned tweet.

**Comment by expilo** [comment]
Yes, you're  right. Removing that.

**Comment by chrismccord** [comment]
Fixed. Thanks!
