### ISSUE TITLE
Autogenerated FallbackController in a new app has dialyzer errors

### ISSUE THREAD

**Issue by xadhoom** [phoenixframework/phoenix#2467]
### Environment

* Elixir version (elixir -v): 1.5.1
* Phoenix version (mix deps): 1.3.0
* Operating system: Linux

### Expected behavior
Dialyzer should not have errors

### Actual behavior
FallbackController calls to render/3 has the following error:
> The call 'Elixir.Phoenix.Controller':render....breaks the contract ('Elixir.Plug.Conn':t(),binary() | atom(),'Elixir.Keyword':t() | map()) -> 'Elixir.Plug.Conn':t()

### More details
Sample app created with
- mix phx.new sample
- added `{:dialyxir, "~> 0.5", only: [:dev], runtime: false}` to deps
- created a sample json with ecto/context with `mix phx.gen.json Accounts User users name:string`

The call should be render/4 so just adding an empty map as 4th param makes dialyzer happy.

**Comment by josevalim** [comment]
Fixed here: https://github.com/phoenixframework/phoenix/commit/7af99b6de21d58057188264f6e377ec6b29e4c86
