### ISSUE TITLE
Adding URL helpers to boilerplate code while using mix.phx.json

### ISSUE THREAD

**Issue by sivagollapalli** [phoenixframework/phoenix#2468]
Thanks for the great framework. Since I am new to the framework I am playing with generators. In the process, I have scaffold user as follows

```
mix phx.new helper_issue --no-html --no-brunch
```

```
mix phx.gen.json V1 User users username:string
```
Above generator added following snippet to the `user` controller

```
 def create(conn, %{"user" => user_params}) do
    with {:ok, %User{} = user} <- V1.create_user(user_params) do
      conn
      |> put_status(:created)
      |> put_resp_header("location", user_path(conn, :show, user))
      |> render("show.json", user: user)
    end
  end
```
Since I am using JSON generator, I think it should not add `put_resp_header("location", user_path(conn, :show, user))`. Thoughts please?

Versions:
Elixir: `1.5`
Phoenix: `1.3`

**Comment by josevalim** [comment]
The HTTP spec recommends setting the location header when the status code is 201 (`put_status(:created)`).

**Comment by chrismccord** [comment]
Welcome aboard! The location url of the created resource makes sense. You are free to remove that line if it's not something you want. Remember, generators are a starting point :)

**Comment by sivagollapalli** [comment]
@chrismccord I agree with you. But it throws the following error when I access. 

```
== Compilation error in file lib/helper_issue_web/controllers/user_controller.ex ==
** (CompileError) lib/helper_issue_web/controllers/user_controller.ex:18: undefined function user_path/3
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
It would be difficult for newbie person to sort why this error occurs. So, I thought when user uses json generators we will comment/remove `put_resp_header("location", user_path(conn, :show, user))` or give a intimation to remove these code snippets to user. Would that make sense?

**Comment by josevalim** [comment]
After the generator runs we ask you to add a line to the router which would
then solve this issue.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by PhillippOhlandt** [comment]
I ran into the compiler issue the first time too, but as @josevalim said, just follow the instructions and you are all good. Maybe the text could be a little bit tweaked so it tells the user that a compilation error could/will occur when the line is not added to the router.
