### ISSUE TITLE
 error: Processing of web/static/js/app.js failed. 

### ISSUE THREAD

**Issue by davidsrn** [phoenixframework/phoenix#2470]
I've already tried every solution I found.
I currently learning phoenix and I'm stuck with this error.
Already tried npm install,  mix deps.get and done ecto.create and ecto.migrate

After running `mix phx.server` it returns:

`Running Discuss.Endpoint with Cowboy using http://0.0.0.0:4000
error: Processing of web/static/js/socket.js failed. Error: Could not load module 'phoenix' from 'c:/Users/david/Desktop/TEC/Elixir-Tutorial/discuss/web/static/js'. Possible solution: run `npm install`.
Stack trace was suppressed. Run with LOGGY_STACKS=1 to see the trace.
error: Processing of web/static/js/app.js failed. Error: Could not load module 'phoenix_html' from 'c:/Users/david/Desktop/TEC/Elixir-Tutorial/discuss/web/static/js'. Possible solution: run `npm install`.
Stack trace was suppressed. Run with LOGGY_STACKS=1 to see the trace.
20:55:35 - info: compiled 2 files into app.css, copied 3 in 1.2 sec`

**Environment**

* Elixir version: 1.5.1
* Phoenix version: 13.0
* NodeJS version: 8.4.0
* NPM version: 5.4.0
* Operating system: Windows 10 Pro 64 bit

**Socket.js**
`
import {Socket} from "phoenix"
let socket = new Socket("/socket", {params: {token: window.userToken}})
socket.connect()
channel.join()
  .receive("ok", resp => { console.log("Joined successfully", resp) })
  .receive("error", resp => { console.log("Unable to join", resp) })
export default socket
`

**app.js**
`import "phoenix_html"`

**Comment by chrismccord** [comment]
What output did/do you receive when you run `npm install`? Make sure you run it at your project root (the location of your package.json)

**Comment by davidsrn** [comment]
I received `up to date in 2.721s`

**Comment by chrismccord** [comment]
As a sanity check, can you remove the `node_modules` directory from your project root, then re-run `npm install` and include the exact output? Thanks!

**Comment by davidsrn** [comment]
Weird, the output was:
`
npm ERR! path C:\Users\david\Desktop\TEC\Elixir-Tutorial\discuss\node_modules\nan\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\david\Desktop\TEC\Elixir-Tutorial\discuss\node_modules\nan\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\david\Desktop\TEC\Elixir-Tutorial\discuss\node_modules\nan\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\david\\Desktop\\TEC\\Elixir-Tutorial\\discuss\\node_modules\\nan\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\david\\Desktop\\TEC\\Elixir-Tutorial\\discuss\\node_modules\\nan\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\david\AppData\Roaming\npm-cache\_logs\2017-09-04T02_15_02_664Z-debug.log
`

**Comment by chrismccord** [comment]
I'm vaguely aware of some folks having issues with symlinks on windows 10. Can you try `npm --unsafe-perm true install` ?

**Comment by davidsrn** [comment]
Output:
npm ERR! path C:\Users\david\Desktop\TEC\Elixir-Tutorial\discuss\node_modules\fsevents\node_modules\ansi-regex\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\david\Desktop\TEC\Elixir-Tutorial\discuss\node_modules\fsevents\node_modules\ansi-regex\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\david\Desktop\TEC\Elixir-Tutorial\discuss\node_modules\fsevents\node_modules\ansi-regex\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\david\\Desktop\\TEC\\Elixir-Tutorial\\discuss\\node_modules\\fsevents\\node_modules\\ansi-regex\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\david\\Desktop\\TEC\\Elixir-Tutorial\\discuss\\node_modules\\fsevents\\node_modules\\ansi-regex\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\david\AppData\Roaming\npm-cache\_logs\2017-09-04T02_22_46_288Z-debug.log



The log:
[2017-09-04T02_22_46_288Z-debug.txt](https://github.com/phoenixframework/phoenix/files/1273482/2017-09-04T02_22_46_288Z-debug.txt)

**Comment by chrismccord** [comment]
I'm shooting in the dark, but you could try: `npm --bin-links false install`

**Comment by davidsrn** [comment]
I think it's the same error, I might start the project from scratch to move on and see if it works.
Output:
npm ERR! path C:\Users\david\Desktop\TEC\Elixir-Tutorial\discuss\node_modules\fsevents\node_modules\mime-db\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\david\Desktop\TEC\Elixir-Tutorial\discuss\node_modules\fsevents\node_modules\mime-db\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\david\Desktop\TEC\Elixir-Tutorial\discuss\node_modules\fsevents\node_modules\mime-db\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\david\\Desktop\\TEC\\Elixir-Tutorial\\discuss\\node_modules\\fsevents\\node_modules\\mime-db\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\david\\Desktop\\TEC\\Elixir-Tutorial\\discuss\\node_modules\\fsevents\\node_modules\\mime-db\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\david\AppData\Roaming\npm-cache\_logs\2017-09-04T02_39_38_713Z-debug.log

Log:
[2017-09-04T02_39_38_713Z-debug.txt](https://github.com/phoenixframework/phoenix/files/1273514/2017-09-04T02_39_38_713Z-debug.txt)

**Comment by davidsrn** [comment]
UPDATE:
Somehow, even with the errors, when I run `mix phx.server` there are no errors shown.

**Comment by tjchester** [comment]
I had the same issue as @davidsrn on Windows 10 Pro 64 bit. I had originally run `npm install` from within the _Terminal_ of VS Code. After reading the discussion above, I deleted my _node_modules_ folder in my Phoenix project and then ran `npm install` again but this time from within an **elevated** command prompt. After that completed, my Phoenix server started without the aforementioned errors.

**Comment by chrismccord** [comment]
Thanks for the update @tjchester! @davidsrn please give things a shot with the elevated command prompt. Since we've had no other movement on this for a while, I'm closing, but feel free to chime in with updates or more information. Thanks!

**Comment by bottlenecked** [comment]
Hey, just in case someone else happens upon this:
I followed the [phoenix 1.2 -> 1.3 migration guide](https://www.phoenixframework.org/blog/upgrading-from-120-to-130) and it mentions updating the dependencies in `package.json` to `"phoenix": "file:../deps/phoenix"`

Turns out I had an umbrella app, so for me the correct setup was this

```json
"dependencies": {
 "phoenix": "file:../../../deps/phoenix",
 "phoenix_html": "file:../../../deps/phoenix_html"
}
```
(i.e. no symlink issues or similar)
