### ISSUE TITLE
Error in Upgrade Guide?

### ISSUE THREAD

**Issue by benjamin79** [phoenixframework/phoenix#2472]
Hi,
before:   import MyApp.ErrorHelpers
after:     import MyAppWebErrorHelpers

Shouldn´t this be   import MyAppWeb.ErrorHelpers ?

**Comment by nekath** [comment]
@benjamin79 You are right, it should be `MyAppWeb.ErrorHelpers`.

**Comment by Gazler** [comment]
@benjamin79 good spot! Please open a PR on https://github.com/phoenixframework/phoenix_site/blob/master/posts/blog--upgrading-from-120-to-130.markdown

**Comment by Gazler** [comment]
Closed in https://github.com/phoenixframework/phoenix_site/commit/9d420945a7d9da51e7bd5c01179fea3f35c96126

**Comment by benjamin79** [comment]
Sorry, i totally forgot to do it.

**Comment by Gazler** [comment]
@benjamin79 No problem. Thanks for raising the issue!
