### ISSUE TITLE
Endpoint config documentation incomplete for :url

### ISSUE THREAD

**Issue by lukaszsamson** [phoenixframework/phoenix#2489]
Documentation for :scheme in :url key is missing. It's hard to guess if it accepts atoms or strings. It's not clear if it accepts {:system, "SCHEME"}

### Environment

* Phoenix version (mix deps): 1.3

**Comment by mikaoelitiana** [comment]
I tried using it with  {:system, "API_URL_SCHEME"} but it didn't work for me. I had the following error : 
```
* (exit) an exception was raised:
10/13/2017 11:20:00 AM    ** (FunctionClauseError) no function clause matching in URI.default_port/1
10/13/2017 11:20:00 AM        (elixir) lib/uri.ex:44: URI.default_port({:system, "API_URL_SCHEME"})
10/13/2017 11:20:00 AM        (elixir) lib/uri.ex:555: String.Chars.URI.to_string/1
10/13/2017 11:20:00 AM        (phoenix) lib/phoenix/endpoint/supervisor.ex:184: Phoenix.Endpoint.Supervisor.url/1
10/13/2017 11:20:00 AM        (phoenix) lib/phoenix/config.ex:48: Phoenix.Config.cache/3
10/13/2017 11:20:00 AM        (api) lib/api_web/router.ex:1: APIWeb.Router.Helpers.feature_url/4
10/13/2017 11:20:00 AM        (ja_serializer) lib/ja_serializer/builder/link.ex:25: JaSerializer.Builder.Link.build/3
10/13/2017 11:20:00 AM        (elixir) lib/enum.ex:1274: anonymous fn/3 in Enum.map/2
10/13/2017 11:20:00 AM        (stdlib) lists.erl:1263: :lists.foldl/3
```

**Comment by josevalim** [comment]
It is removed from the docs because the feature is deprecated. You are not supposed to be relying on it anymore. :)

**Comment by mikaoelitiana** [comment]
Thank you for clarification @josevalim. What solution should we use instead for generated URL scheme configuration?

**Comment by webdeb** [comment]
@mikaoelitiana checkout the generate `endpoint.ex` file, there is the `init/2` callback, where you can alter the config during application startup.

**Comment by mikaoelitiana** [comment]
thank you @webdeb. So I think this ticket should be closed now.

**Comment by lukaszsamson** [comment]
Please reopen it.
The docs still does not mention if `:scheme` accepts atoms or strings nor the tricky interaction between `:https` setting and `:url` setting.
Making it work as expected required digging through source code.

**Comment by josevalim** [comment]
Sure, but can you please open up a pull request to get the conversation started?

**Comment by lukaszsamson** [comment]
Yep, I can do that.
