### ISSUE TITLE
Don't recommend generating a skeleton app in the intro

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#2492]
@nisstyre56 raised this issue on the phoenix_guides

---

In the guide located at https://hexdocs.pm/phoenix/installation.html#content it recommends doing mix phx.new web --no-brunch --no-ecto which generates an application without brunch to compile static assets (like JS). It does not say why you would want to generate only a skeleton app, so I'm wondering if it might be a good idea to generate a full app instead.

My rationale is that if you follow the guide and get to the point where you want to implement a channel, it seems to assume that you've setup brunch, so either you have to manually setup static asset compilation with brunch, or regenerate your entire app, both of which are frustrating and interrupt the learning process. I think it would be better to recommend just doing mix phx.new so that the guide can be followed from start to finish without having to get sidetracked.

**Comment by josevalim** [comment]
I think that's a good idea. The problem is that you then need PG and node and I am not sure if the goal was to skip those dependencies.

**Comment by chrismccord** [comment]
So that section of the guides is only there to show you can generate a "skeleton" app with bare deps should you want that. It's not meant to recommend or have newcomers follow that as a step in the guides process. I think a small wording change is all we need? As users go thru the up and running we indeed have them generate a full app.

**Comment by nisstyre56** [comment]
@chrismccord I think it would be helpful to just have the section be titled "Installation" and mention that you can do `phx.new` if you want the full installation, or `phx.new web --no-brunch --no-ecto` for a skeleton app. I think what tripped me up was not realizing how important brunch is at the beginning.

**Comment by ksolo** [comment]
@chrismccord @josevalim @Gazler 
Reviewing the documentation, the page linked is stating what you'll need to have installed on your machine before jumping to the "Up and Running" section. I think it would be better to remove that section altogether and make an aside on the "Up and Running" that let's you know you can create a skeleton app, say for instance in an API only setting.

**Comment by chrismccord** [comment]
@ksolo sounds good. Can you send a PR?
