### ISSUE TITLE
Guides Overhaul

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#2493]
@chrismccord originally raised this issue on phoenix_guides

---

It's time to pay down my guides debt with a review and overhaul of the guides and much needed TLC. 

cc @Gazler, @willykaram, @jeregrine 

Here's a shortlist to get us 1.3.0 stable ready. I'm marking the ones that I'm claiming, but others are up for grab if folks have bandwidth on refreshing the existing guides:

* [x] Existing* guides in need of a refresh to include new features and latest conventions:
  * [x] [@heatherm] Installation
    * [x] needs to be bumped to 1.3 version requirements
      * [x] Erlang 18
      * [x] Elixir 1.5
    * [x] needs to reference new `phx_new` archive urls
    * [x] needs to use new `phx.new` task
  * [x] Up And Running
    * [x] needs to use new `phx.new`, `phx.server` tasks
    * [x] all example output needs to be updated to new output
  * [x] [CM] Adding Pages
    * [x] needs to discuss new directory structure and update tree listings
    * [x] needs to discuss new assets directory. `web/static` has moved to `assets`. `web/static/assets` has moved to `assets/static`, etc.
    * [x] modules need to use new `Web` namespace
    * [x] `Map.get(assigns, :messenger)` should be `assigns.messenger` since we've long raised on missing assigns
    * [x] __new additions__
      * [x] make small mention of EEx engine escaping by default when talking about templates (explained in detail later in Views guide, but should be mentioned here)
  * [x] [@gazler] Routing
    * [x] web namespace
    * [x] needs to use `phx.routes` with new example output
    * [x] __new additions__
      * [x] cover basic `forward` usecases and usage
  * [x] Plug
    * [x] null-arity calls should use parens
    * [x] web namespace in examples
  * [x] Controllers
    * [x] web namespaces
    * [x] revamp code examples to follow conventions, such as always using parens when piping, no single line pipe.
    * [x] __new additions__
      * [x] discuss `halt` when talking about controller plugs and its importance to prevent invoking the controller action
      * [x] action_fallback
  * [x] Views
    * [x] web namespaces
    * [x] update file path locations
    * [x] output of iex examples need refreshed
    * [x] __new additions__
      * [x] [CM] should show examples of functions on the view being available in eex templates and discuss why
  * [ ] Channels
    * [x] should cross-ref TBD presence guide at the end
    * [x] web namespace
    * [x] file paths
    * [ ] should warn about using `handle_out` with potential N query problems
    * [ ] linked `phoenix_chat_example` desperately needs overhaul to 1.3 and polished
    * [ ] __new additions__
      * [ ] needs to better discuss process-model on server
      * [ ] needs to discuss `handle_info`
      * [ ] Discuss channel security and auth, with examples (we can lift examples from generated socket.js file)
      * [x] should cross-ref Phoenix.Token
      * [ ] bonus points if we can show embedded gifs of examples as we go
  * [x] [CM] Ecto Models (larger revisions required here compared to previous guides)
    * [x] rename to Ecto Schemas
    * [x] heavier focus on the purpose of schemas casting using input
    * [x] use `phx.gen.schema` task
    * [x] __new additions and major revisions__
      * [x] do not discuss relationships in detail, deferring to context guide which will build off this example
      * [x] close guide by discussing wrapping up Ecto repo access and queries into contexts, with TBD cross-ref
  * [x] Testing Guides
    * [x] blocked until context guide is written, which testing guides will build off of
  * [ ] Deployment
    * [ ] review Heroku and update for proper console update
    * [x] update exrm guide to use distillery
  * [x] Bonus Guides
    * ...

*New* guides needed for new features and lacking content:
  * [x] [CM] Presence
  * [ ] [CM]Umbrella applications - @mcelaney 
  * [x] [CM] Contexts
  * [x] `phx.gen.*` generators, some of these can be grouped into a larger guide, such as a guide on Ecto Schemas
  * [x] Endpoint guide [@gazler] https://github.com/phoenixframework/phoenix_guides/pull/567

Other items to tackle:
  * move guide hosting over to hexdocs. Most of this work is in place, but we need to update the homepage of phoenixframework.org to link back to the hexdocs guides instead of readme hosting.

**Comment by jmarca** [comment]
I posted an update to the phoenix_guides repo for context_testing.  I took a look at the recently updated one, and still see issues.  Is it still "in progress" or is it safe to dive in and make changes?

**Comment by mcelaney** [comment]
@Gazler Has anyone picked up the Umbrella App guide?  If not I can try to hit this week...

**Comment by Gazler** [comment]
@mcelaney Not that I am aware of. Please do!

**Comment by aphillipo** [comment]
Anything you want me to look at @Gazler ?  Have some time at the weekend and next week even if it's testing examples.

**Comment by Gazler** [comment]
@aphillipo Any of the unchecked tasks above are up for grabs. Pong sounds like it'd make a cool blog post, I think we want to continue with the chat example in the official guide as it is very relatable for people and pretty much the hello world of WebSockets.

**Comment by sashaafm** [comment]
Are you thinking about adding a specification for the new Channels Wire v2 protocol?

**Comment by oldpond** [comment]
mix test fails after adding Credential in the Context guide.  

Assertion with == failed
     code:  assert user == Accounts.get_user!(user.id())
     left:  %Freight.Accounts.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: 13, inserted_at: ~N[2017-12-01 17:05:49.383252], name: "some name", updated_at: ~N[2017-12-01 17:05:49.383269], username: "some username", credential: #Ecto.Association.NotLoaded<association :credential is not loaded>}
     right: %Freight.Accounts.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: 13, inserted_at: ~N[2017-12-01 17:05:49.383252], name: "some name", updated_at: ~N[2017-12-01 17:05:49.383269], username: "some username", credential: nil}

**Comment by starbelly** [comment]
I can take on updating the phoenix chat example if that's still desired @Gazler
