### ISSUE TITLE
Get key from Ecto Model's @derive of Phoenix.Param

### ISSUE THREAD

**Issue by JamieREvans** [phoenixframework/phoenix#2495]
I know there isn't really a great way to extend the behavior of the `Phoenix.Param` macro for modules, but it would really help out a lot of 3rd party libraries and even Phoenix routing if we could do something like this:

``` elixir
defmodule MyModule do
  @derive {Phoenix.Param, key: :my_key}
  defstruct [:id, :my_key]
end

> Phoenix.Param.key(%MyModule{})
:my_key
```

This would allow routers not to continuously have to specify the `param` key and tools like `Canary` would benefit from it, as well. Is there a good reason to not expose this functionality? Is it because it's a little dirty having to instantiate a struct to get the value?

**Comment by chrismccord** [comment]
Please send feature requests to the phoenix-core mailing list as we reserve the issue tracker for issues, per the issue template. Thanks!
