### ISSUE TITLE
Phoenix.View.render_to_string fails for non-html templates

### ISSUE THREAD

**Issue by asd1o2487c** [phoenixframework/phoenix#2498]
### Environment

* Elixir version (elixir -v): 1.5
* Phoenix version (mix deps): 1.3
* Operating system: macOS

template `email/magic_link.text.haml`
```haml
= gettext("Here is your login link:")

= session_url(Web.Endpoint, :redeem_token, @token)

= gettext("It is valid for 15 minutes.")
```

### Expected behavior
```elixir
iex(4)> Phoenix.View.render_to_string(Web.EmailView, "magic_link.text", token: "asd")
"Here is your login link:\nhttp://localhost:4000/3/login/asd\nIt is valid for 15 minutes.\n"
```

### Actual behavior
```elixir
iex(4)> Phoenix.View.render_to_string(Web.EmailView, "magic_link.text", token: "asd")
** (ArgumentError) argument error
    :erlang.iolist_to_binary({:safe, [[[[[["" | "Here is your login link:"] | "\n"] | "http://localhost:4000/3/login/asd"] | "\n"] | "It is valid for 15 minutes."] | "\n"]})
    (phoenix) lib/phoenix/view.ex:339: Phoenix.View.render_to_string/3
```

So, for something which ends not with `.html`, `render` function returns `{:safe, iolist}` and not just `iolist` which IO.iodata_to_binary expects.

And bamboo wants files ending with `.text` and it calls `Phoenix.View.render_to_string`.

**Comment by josevalim** [comment]
@asd1o2487c does it work if the template is eex? If so, isn't this rather a bug on haml, no?

**Comment by asd1o2487c** [comment]
Oh, it might be. Will check now.

**Comment by asd1o2487c** [comment]
@josevalim you are right, it works with `.eex`.
