### ISSUE TITLE
template_not_found/2 in ErrorView doesn't seem to work.

### ISSUE THREAD

**Issue by jung-hunsoo** [phoenixframework/phoenix#2500]
### Environment

* Elixir version (elixir -v): 1.5.1
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 6.11.2
* NPM version (npm -v): 3.10.10
* Operating system: Ubuntu 14.04

### Expected behavior
1) Set `debug_errors: false` in dev.exs not to override the error behavior
2) Simply change the template_not_found/2 block in ErrorView to render "404.html" instead of the default "500.html".
`def template_not_found(_template, assigns) do`
`  render "404.html", assigns`
`end`
3) Then call a non-existing page in a browser to intentionally call template_not_found.
4) "Page not found" should be presented.

### Actual behavior
1) through 3. are same as above
4) "Internal server error" is presented.

As per my log `[info] Sent 500 in 1ms` phoenix seems to throw 500 even `Phoenix.Template.raise_template_not_found/3` is called by.

### Logs
[error] #PID<0.454.0> running NohoguWeb.Endpoint terminated
Server: www.mu**.com:443 (http)
Request: GET /pages/about_us2
** (exit) an exception was raised:
    ** (Phoenix.Template.UndefinedError) Could not render "about_us2.html" for NohoguWeb.PageView, please define a matching clause for render/2 or define a template at"lib/nohogu_web/templates/page". The following templates were compiled:

* about_us.html
* index.html
* philosophy.html
* statistics.html

...

Assigned keys: [:conn, :current_user, :template_not_found, :view_module, :view_template]

        (phoenix) lib/phoenix/template.ex:364: Phoenix.Template.raise_template_not_found/3
        (nohogu) lib/nohogu_web/templates/layout/app.html.eex:24: NohoguWeb.LayoutView."app.html"/1
        (phoenix) lib/phoenix/view.ex:332: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:740: Phoenix.Controller.do_render/4
        (nohogu) lib/nohogu_web/controllers/page_controller.ex:1: NohoguWeb.PageController.action/2
        (nohogu) lib/nohogu_web/controllers/page_controller.ex:1: NohoguWeb.PageController.phoenix_controller_pipeline/2
        (nohogu) lib/nohogu_web/endpoint.ex:1: NohoguWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (nohogu) lib/nohogu_web/endpoint.ex:1: NohoguWeb.Endpoint.plug_builder_call/2
        (nohogu) lib/nohogu_web/endpoint.ex:1: NohoguWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/cabox/workspace/nohogu/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

**Comment by josevalim** [comment]
I believe the template_not_found callback is invoked per view. So you would need to change the LayoutView in the example above.

In your case, it is probably best to configure the `Phoenix.Template.UndefinedError` raises a 404. Something like:

```elixir
defimpl Plug.Exception, for: Phoenix.Template.UndefinedError do
  def status(_) do
    404
  end
end
```

Or something of sorts.
