### ISSUE TITLE
Add schema test back to context generator

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#2501]
As discussed at ElixirConf with @jeregrine

**Comment by chrismccord** [comment]
@jeregrine ping

**Comment by jeregrine** [comment]
My bad, can take a look tomorrow evening.

**Comment by chrismccord** [comment]
Take your time, just a nudge :) <3 <3 <3

**Comment by chrismccord** [comment]
Ping @jeregrine :) I can grab this one if you don't have time to take it?

**Comment by jeregrine** [comment]
Please do <3
