### ISSUE TITLE
Absolute static url + path 

### ISSUE THREAD

**Issue by webdeb** [phoenixframework/phoenix#2506]
In some cases you need to have an absolute static url for the assets, for example in an email.

We could add an additional `static_url/1` function which would accept a path like `static_path/1` does.

If this makes sense, I would like to submit a PR.

**Comment by josevalim** [comment]
Such function already exists: https://github.com/phoenixframework/phoenix/blob/cb469a4d2f7ee3ca14b1a4bf8de4ee7a590067a5/lib/phoenix/router/helpers.ex#L151-L164

It is in your `MyApp.Router.Helpers`. :)

**Comment by webdeb** [comment]
Oh, wow, I just looked inside the Endpoint ;)
thank you @josevalim
