### ISSUE TITLE
Cannot read property 'verbose' of undefined

### ISSUE THREAD

**Issue by ramka001** [phoenixframework/phoenix#2519]
### Environment

* Elixir version (elixir -v): 1.5.1
* Phoenix version (mix deps):1.3.0
* NodeJS version (node -v): 8.4.0
* NPM version (npm -v): 5.4.2
* Operating system: Elixir Loki (Ubuntu 16.04 LTS)

### Expected behavior
When the mix phx.server is executed It is expected to just return

[info] Running MyWeb.Endpoint with Cowboy using http://0.0.0.0:4000
along with the page load info

### Actual behavior

Now I'm currently receiving

Compiling 27 files (.ex)
Generated myweb app
[info] Running MyWeb.Endpoint with Cowboy using http://0.0.0.0:4000
[info] GET /
[info] user=nil message=""
[debug] Processing with MyWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 18ms
02:53:57 - info: compiling
[debug] Live reload: priv/static/js/app.js
[debug] Live reload: priv/static/css/app.css
[info] GET /
[info] user=nil message=""
[debug] Processing with MyWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 392µs

**02:53:58 - info: compiled 149 files into 2 files, copied 7 in 5.3 sec
02:53:58 - error: Cannot read property 'verbose' of undefined
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace.** 

I've narrowed the problem to the nodejs brunch. I've tried rebuilding the node-sass as advised by some of the forums, but this doesn't resolve the issue.  Any suggestions ?

**Comment by chrismccord** [comment]
This sounds like a node-sass specific issue, which is a package we don't ship with. Unfortunately, I don't have any pointers, but I would try to jump on the latest node/npm and `rm -rf node_modules` then retry.

**Comment by gimKondo** [comment]
@ramka001 
Perhaps, did you install sass-brunch with copycat-brunch?
When I installed both of them and don't set brunch-config.js, I found a same error.
I could solve by adding `copycat: {}` into plugins section.

Actually, I find this problem at log with `LOGGY_STACKS=1` in according to error message .
```
error: Cannot read property 'verbose' of undefined
    at copycat.onCompile (/usr/src/app/node_modules/copycat-brunch/lib/index.js:10:40)
    at allHooks.map.plugin (/usr/src/app/node_modules/brunch/lib/watch.js:41:29)
    at Array.map (<anonymous>:null:null)
    at Object.mergedHooks.(anonymous function) [as onCompile] (/usr/src/app/node_modules/brunch/lib/watch.js:40:23)
    at write.then.data (/usr/src/app/node_modules/brunch/lib/watch.js:305:18)
    at <anonymous>:null:null
```
