### ISSUE TITLE
Suggestion: Lighten up current guides & move advanced functionality to a new advanced section.

### ISSUE THREAD

**Issue by gemantzu** [phoenixframework/phoenix#2523]
I was checking on new guides today and I felt bloated with information (that router guide made me a little bit dizzy).

I feel like most of the guides could use a little division, meaning that we could leave only crucial information to the current ones, only what is needed to get started and create a new Advanced section with more advanced guides on each topic. 

This could attract us newcomers and newbs better and probably have the advanced stuff in more appropriate section for advanced users to find and use.

What do you guys think about this?

**Comment by chrismccord** [comment]
Thanks for the feedback! This is too big of a task to tackle in the immediate future, but the team will take this under consideration as we carry the guides forward.
