### ISSUE TITLE
Developer dashboard

### ISSUE THREAD

**Issue by kagux** [phoenixframework/phoenix#2524]
Hey guys,

@chrismccord, during your last keynote in London, you briefly mentioned developer dashboard. 
Coincidentally, we’ve been working on very similar concept over at [ex_debug_toolbar](https://github.com/kagux/ex_debug_toolbar). To be fair, we started tackling developer experience from a different angle (toolbar). It includes requests history, but a standalone dashboard is a great idea that we’d like to implement in upcoming releases.

Your keynote excited us as we feel like there is a big opportunity to improve quality of life for developers. We open this issue to see how far have you gone with your concept and if you and the team were open to consider collaborating with us working on phoenix and [ex_debug_toolbar](https://github.com/kagux/ex_debug_toolbar) together to match your and our vision of developer dashboard and toolbar experience.

Apologies if this is not the right place for this discussion. If you prefer, we could move this to slack or email.

Thanks!

**Comment by chrismccord** [comment]
I think I mentioned the toolbar in my talk, but I forgot the name :) I love the work that is going on there. Things are too early at the moment to start tackling anything collaboration wise, but we'd love to explore that. I'll ping once we're underway. Thanks!
