### ISSUE TITLE
action override removed?

### ISSUE THREAD

**Issue by asd1o2487c** [phoenixframework/phoenix#2529]
### Environment

* Elixir version (elixir -v): 1.5.1
* Phoenix version (mix deps): 1.3
* Operating system: macOS

### Expected behavior
```elixir
defmodule Web.ChatController do
  use Web, :controller
  alias Store.{Chats, Chat, User}

  action_fallback Web.FallbackController

  # fail if there is no match (no current user in assigns)
  # since the user must be logged in in order to access chats
  def action(%{assigns: %{current_user: current_user}} = conn, params) do
    apply(__MODULE__, action_name(conn), [conn, params, current_user])
  end

  # API

  # fail if the current user is not %User{} (can be nil)
  def create(conn, %{"user_id" => receiver_id}, %User{id: requester_id}) do
    with {:ok, %Chat{} = chat} <- Chats.create_chat(receiver_id, requester_id, requester_id) do
      render(conn, "create.json", chat: chat)
    end
  end
end
```
### Actual behavior
`create/3` never matches, `create/2` is called instead
```sh
[info] POST /api/chats/create
[debug] QUERY OK source="users" db=1.2ms queue=0.1ms
SELECT ... FROM "users" AS u0 WHERE (u0."id" = $1) [21]
[debug] Processing with Web.ChatController.create/2
  Parameters: %{"user_id" => 10}
  Pipelines: [:api]
```

**Comment by chrismccord** [comment]
Please include your complete controller and web.ex file. Thanks!

**Comment by asd1o2487c** [comment]
Hi, @chrismccord! I've updated the issue, it now includes all the relevant parts (I've omitted other actions).

**Comment by chrismccord** [comment]
Our Logger assumes /2, so for a sanity check it seems. your create/3 is called but the logs are misleading?

**Comment by asd1o2487c** [comment]
web.ex

```elixir
defmodule Web do

  def controller do
    quote do
      use Phoenix.Controller, namespace: Web
      import Plug.Conn
      import Web.Router.Helpers
      import Web.Gettext
    end
  end
...
end
```

**Comment by chrismccord** [comment]
Also note that `action/2` is a plug and *does not* receive the conn.params as the 2nd argument. It receives a list of plug options, which is `[]` in this case. So you are invoking your `create` function with `[]` as the params, where it should be `conn.params`. That should be causing a function clause mismatch, but your provided logs show 200, so do you have other `create` clauses?

**Comment by asd1o2487c** [comment]
@chrismccord yeah, just thought of that. The correct action override is
```elixir
  def action(%{assigns: %{current_user: current_user}} = conn, params) do
    apply(__MODULE__, action_name(conn), [conn, params, current_user])
  end
```

**Comment by asd1o2487c** [comment]
> but your provided logs show 200

Where? I get `[info] Sent 400 in 57ms`

> do you have other create clauses?
No, just that one.

**Comment by chrismccord** [comment]
To be clear, this is what you want:

```elixir
  def action(%Plug.Conn{assigns: %{current_user: current_user}} = conn, _opts) do
    apply(__MODULE__, action_name(conn), [conn, conn.params, current_user])
  end
```

**Comment by asd1o2487c** [comment]
@chrismccord I prefer a singe match in the function head.
