### ISSUE TITLE
Phx.gen.html does not generate files in lib by default

### ISSUE THREAD

**Issue by lorenzosinisi** [phoenixframework/phoenix#2531]
### Environment

* Elixir version (elixir -v): Erlang/OTP  - Elixir 1.5.1
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v):v7.7.3
* NPM version (npm -v): 4.1.2
* Operating system: Mac OS

### Expected behavior
The command: 
mix phx.gen.html Poll polls title:string closed:boolean 
It is expected to create the files in /lib folder as documented here https://github.com/phoenixframework/phoenix/blob/v1.3.0/lib/mix/tasks/phx.gen.html.ex#L27

### Actual behavior
The command: 
mix phx.gen.html Poll polls title:string closed:boolean 
creates part of the files in lib (the models) while controllers and views are created into the /web folder.

**Comment by josevalim** [comment]
Can you make sure that you are running `mix phx.gen.html` and not `mix phoenix.gen.html`? From the argument list that you passed, it seems you are using the latter and the latter only exists for backwards compatibility.

**Comment by lorenzosinisi** [comment]
Yes, my bad. Thank you!
