### ISSUE TITLE
Got InvalidCSRFTokenError

### ISSUE THREAD

**Issue by cohki0305** [phoenixframework/phoenix#2534]
### Environment

* Elixir version (elixir -v):  Elixir 1.5.1
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): v6.10.1
* NPM version (npm -v): v4.2.0
* Operating system: Mac 10.12.6

### Expected behavior

Render new.html

### Actual behavior

I got InvalidCSRFTokenError when rendering "new.html"
> invalid CSRF (Cross Site Request Forgery) token, make sure all requests include a valid '_csrf_token' param or 'x-csrf-token' header

Because I am using `form_for`, I thought this error does not happen. 
ref. https://hexdocs.pm/phoenix_html/1.0.0/Phoenix.HTML.Form.html#form_for/4

When failing to insert record, I got this error.

Error tells that csrf token of session is gone.
<img width="1209" alt="2017-09-30 19 31 48" src="https://user-images.githubusercontent.com/12666715/31045066-b54452ae-a616-11e7-94df-3bf2b432935e.png">

My code is following

**template**

```new.html.eex

<%= form_for @changeset, registrations_path(@conn, :create), fn form -> %>

  <div class="form-group">
    <label>Email</label>
    <%= email_input form, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Password</label>
    <%= password_input form, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Register", class: "btn btn-primary" %>
  </div>
<% end %>
```

**controller**

```elixir

defmodule UserAuthenticator.Users.RegistrationsController do
  use UserAuthenticator.Web, :controller
  alias UserAuthenticator.User
  alias UserAuthenticator.Endpoint

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)
    case User.create(changeset, Repo) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Wellcome" <> changeset.params["email"])
        |> redirect(to: redirect_path_after_registration(conn))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Failed to create account")
        |> render("new.html", changeset: changeset)
    end
  end

  defp redirect_path_after_registration(conn) do
    page_path(conn, :index)
  end
end
```

**Comment by cohki0305** [comment]
I can avoid this error if I use `redirect`

```
{:error, changeset} ->
        conn
        |> put_flash(:error, "Failed to create account")
        |> redirect(to: registrations_path(conn, :new))
```

**Comment by josevalim** [comment]
Everything was supposed to work just fine, yes. Do you have a simple app that reproduces the error?

**Comment by cohki0305** [comment]
@josevalim 
Yes, this is my repository.
https://github.com/cohki0305/phoenix_user_authenticator/tree/create-user-model

Maybe, I fixed the problem.
I remove [the line](https://github.com/cohki0305/phoenix_user_authenticator/blob/create-user-model/web/router.ex#L22), so this error is gone.

Sorry for taking your time.

**Comment by josevalim** [comment]
If you remove that line you remove the CSRF protection. So that's probably not the way you want to go. :)

**Comment by cohki0305** [comment]
That sounds not good :o
I didn't know function of `pipe_through :browser`...

**Comment by josevalim** [comment]
I have tried your branch and it works fine. Maybe there is something wrong with your cookie and, if that's the case, I would like to figure it out.

Can you please give me your cookie for this site? If you are using Google Chrome as your browser, you can do so by opening the "Inspector", then you click the "Application" tab, choose "Cookies" on the left pane and then you will be able to see the "_user_authenticator_key"  name and the value. You can please forward me the value? Then I will try it locally.

If you are using other browsers you probably have something similar. Note `document.cookie` won't work since our cookies are HTTP only by default.

**Comment by cohki0305** [comment]
this is `_user_authenticator_key` name and value.

```
Name
_user_authenticator_key

Content
SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYRWlld1hObkt1TXRuM29CZmh6WmUxQT09.DU3vPTzIYP6jGumAJ5a1s8ZY4gwKipeLJyXqSSZ7u-8

Domain
localhost

Path
/

Send for
Any kind of connection

Accessible to script
No (HttpOnly)

Created
Saturday, September 30, 2017 at 9:03:00 PM

Expires
When the browsing session ends
```

I tried using other browsers, safari and vivaldi, but I got same error.

**Comment by cohki0305** [comment]
I get the error when failing to insert record at two times.
I mean, 
it is possible to insert record from `http://localhost:4000/users/registers/new`.
But I can not insert it from `http://localhost:4000/users/registers` after rendering "new.html"

**Comment by cohki0305** [comment]
My repository code is little different from description's code.
I am using 'render' method.

**Comment by josevalim** [comment]
I cannot reproduce this at all, not even with your cookie. Here is what I did:

1. Visit /users/registers/new
2. Fill in the first field with "foo@bar.com" and the second with "foobar"
3. Press submit
4. It works

Can you please outline step by step what you are doing? Or do a small video? Thanks.

**Comment by cohki0305** [comment]
@josevalim 

Thank you for trying.

Step is following.

1. Visit /users/registers/new
2. Fill in the first field with "foo@bar.com" and the second with "foobar"
3. Press submit
4. It works
5. Try again `step 2`
6. Press submit

![kapture 2017-09-30 at 22 49 25](https://user-images.githubusercontent.com/12666715/31046340-abe1e3be-a631-11e7-93d3-e0a845424b93.gif)

Did you try with the code? 
As https://github.com/phoenixframework/phoenix/issues/2534#issuecomment-333305619, code in repository was little different.

**Comment by josevalim** [comment]
Thanks, I can reproduce the behaviour, now I am trying to understand why it happens. :)

**Comment by josevalim** [comment]
Oh, you are correct! You should remove the **second** `pipe_through [:browser]` in your router because you are piping through it twice and on the second time the token has already been discarded!

@chrismccord should we raise if people try to pipe_through the same plug more than once?

**Comment by josevalim** [comment]
So to clarify, you were correct, you should remove [this line](https://github.com/cohki0305/phoenix_user_authenticator/blob/create-user-model/web/router.ex#L22) since you already invoked it above.

**Comment by cohki0305** [comment]
@josevalim 
I understand why this error happens. Thanks a lot!

It seems to be more helpful to raise Exception when people try it more than once.

**Comment by chrismccord** [comment]
Yes I agree we should raise. This is also another reason why I discourage the use of nested scopes as it makes these kinds of issue more likely to happen.

**Comment by yyolf117** [comment]
I have the same error. The thing that it used to work before. Why not now anymore?

**Comment by yyolf117** [comment]
Actually, I don't understand: neither in my app, nor in here https://github.com/cohki0305/phoenix_user_authenticator/blob/create-user-model/web/router.ex there's 2 nested "pipeline :browser". Again: there's no double ":browser" or nested one for the same route.

Can anyone clear this up?

**Comment by issoft2** [comment]
@josevalim
Sorry I just started using elixir and phoenix this year and I encountered the same situation, however, I discover that I configured my app to run on https and was trying to use http instead. Thanks

**Comment by thomas-profitt** [comment]
I had a problem with this symptom, in dev. No other devs working on the project had the symptom.

My problem was that the app was configured in dev.exs to host as "localhost.test", which the other devs had pointed to localhost in their hosts. I was the only dev trying to access it from localhost, a different hostname. When I tried through "localhost.test", it worked normally.
