### ISSUE TITLE
`mix xref callers` and templates

### ISSUE THREAD

**Issue by wojtekmach** [phoenixframework/phoenix#2543]
### Environment

* Elixir version (elixir -v): Elixir 1.5.2/OTP 20
* Phoenix version (mix deps): v1.4.0-dev
* Operating system: macOS Sierra

### Expected behavior

Let's say I have following files:

```elixir
# post_view.ex
defmodule ExampleWeb.PostView do
  use ExampleWeb, :view
end
```

```eex
# lib/example_web/templates/post/index.html.eex
line 1
line 2
<%= String.upcase("foo") %>
```

I'd expect the following output from mix xref callers:

```
$ mix xref callers String.upcase
lib/example_web/templates/post/index.html.eex:3: String.upcase/1
```

### Actual behavior

```
$ mix ref callers String.upcase
lib/example_web/views/post_view.ex:3: String.upcase/1
```

Note xref correctly got the line number but used views' filename instead of template's.

I'm not sure if this is something that can be fixed in either Phoenix or Elixir.

If `xref callers` points to the right file it could be used to trivially perform a refactoring like: `post_path` => `Routes.post_path` (https://github.com/phoenixframework/phoenix/issues/2530): `xref callers ExampleWeb.Router.Helpers` would give us all the places a route was used and we could sed that.

**Comment by josevalim** [comment]
It is a bug in Elixir, can you please file a report there? Thanks.
