### ISSUE TITLE
Support umbrella projects in phx.new prompt_to_install_deps 

### ISSUE THREAD

**Issue by jrowlingson** [phoenixframework/phoenix#2545]
### Environment

* Elixir version (elixir -v): Elixir 1.5.2
* Phoenix version (mix deps): Phoenix v1.3.0
* NodeJS version (node -v): v8.1.3 
* NPM version (npm -v): 5.0.3
* Operating system: macOS 10.12.6

### Expected behavior

```
❯ mix phx.new app_name --umbrella

Fetch and install dependencies? [Yn] n

We are almost there! The following steps are missing:

    $ cd app_name_umbrella
    $ mix deps.get
    $ cd apps/app_name_web/assets && npm install && node node_modules/brunch/bin/brunch build
```

### Actual behavior

```
❯ mix phx.new app_name --umbrella

Fetch and install dependencies? [Yn] n

We are almost there! The following steps are missing:

    $ cd app_name_umbrella
    $ mix deps.get
    $ cd assets && npm install && node node_modules/brunch/bin/brunch build
```

### Notes

https://github.com/phoenixframework/phoenix/blob/c88e4ae6675f61cbf30cca010611289e8e16ae82/installer/lib/mix/tasks/phx.new.ex#L147

Related https://github.com/phoenixframework/phoenix/issues/2293, https://github.com/phoenixframework/phoenix/issues/685

**Comment by chrismccord** [comment]
Fixed on master. Thanks for the report!
