### ISSUE TITLE
Router guide example not working

### ISSUE THREAD

**Issue by ilansh** [phoenixframework/phoenix#2549]
### Environment

* Elixir version (elixir -v): Elixir 1.5.1
* Phoenix version (mix deps): phoenix 1.3.0
* NodeJS version (node -v): v8.6.0
* NPM version (npm -v):  5.3.0
* Operating system: Ubuntu 16.04.2 LTS (Xenial Xerus)

### Expected behavior

A warning should be issued when ambiguous routes are defined.
At the end of the first section of router guide in the docs (https://hexdocs.pm/phoenix/routing.html#content), it says that after running `mix compile` with the added ambiguous route from the example, a warning will be issued.

### Actual behavior
No warning was issued by the compiler.

**Comment by chrismccord** [comment]
Something must have changed with the Elixir compiler because some folks are reporting this and others are not. I'll see what I can find out

**Comment by chrismccord** [comment]
This is an elixir bug we are tracking on the elixir side: https://github.com/elixir-lang/elixir/issues/6637

Thanks for reporting!
