### ISSUE TITLE
URI module does not exit into Elixir using Phoenix

### ISSUE THREAD

**Issue by EnriqueAldana** [phoenixframework/phoenix#2551]
### Environment

* Elixir version (elixir -v): 1.4.2
* Phoenix version (mix deps): 1.2.5
* NodeJS version (node -v): 6.9.5
* NPM version (npm -v): 3.10.10
* Operating system: MacOS Sierra 10.12.6

### Expected behavior
I have built a helper to get a path part of one URI given.
It is the module definition

defmodule MesPhoenix.Uri do
  def get_path(uri_path) do
   {:ok,ruta}= uri_path |> URI.parse |> Map.fetch(:path)
end
end

When I try to use it like this:

defmodule MesPhoenix.Auth do
import Plug.Conn
import Phoenix.Controller
alias MesPhoenix.Console
alias MesPhoenix.Uri

def authorization_user(conn, opts) do
url_path_source= conn |> get_req_header("referer")
  {:ok,path}= Uri.get_path(url_path_source)   <--------------Here shot an error

### Actual behavior

when I try to use URI.parse function the runtime error appears like this:
no function clause matching in URI.parse/1

However when I try to use on iex console it working fine. i.e
iex (1)> alias MesPhoenix.Uri
iex (2)> Uri.get_path("http://localhost:4000/users/index")
iex (3)> {:ok,"/users/index"}

**Comment by chrismccord** [comment]
Please include your entire stack trace. It is likely your `get_req_header("referrer")` is returning a chartist and not a string that your URI function expects. The stack trace will tell you what values were passed and what failed to match. Thanks!

**Comment by EnriqueAldana** [comment]
Perfect. I got it.
Thanks

Jesus Enrique Aldana Sánchez
