### ISSUE TITLE
Add Phoenix.Controller.xhr?(conn)

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2552]
It is a commonly used function so it probably makes sense for us to provide it. Implementation is also straightforward:

    "XMLHttpRequest" in get_req_header(conn, "x-requested-with")

**Comment by ali-l** [comment]
I'd like to implement this.

On a side note, I was looking at Phoenix.Controller and it seems like the file has become quite large. Do you think there's an opportunity for splitting it into smaller pieces?

**Comment by josevalim** [comment]
Let’s wait for confirmation from Chris before doing it.

Also no need to split it. Splitting it apart will make things harder to
find and navigate for users.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by chrismccord** [comment]
👍 please go ahead with a PR. thanks!

**Comment by obahareth** [comment]
What is different about this feature and the `ajax?` function that already exists [here](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/controller.ex#L882)?

**Comment by josevalim** [comment]
None. We will just make it public, simplify, document and test it.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ali-l** [comment]
I just realized that the `x-requested-with` header is not a standard, but a convention used by libraries such as jQuery. `fetch` does not include this header by default, which could result in unexpected behaviour.

Rails had a bit of relevant discussion: rails/rails#21709, then decided to keep it (for reasons that are unclear to me).

Any thoughts?

**Comment by OvermindDL1** [comment]
Yeah I'd vote for not including xhr or any form there-of, it is very jQuery centric and it is well *well* on its way out.  Plus would you test for just `x-requested-with`?  Or would you test for the intercooler request header (which is different), or the unpoly request header (which is yet again different), or turbolinks, or etc... etc...  That sounds like a very slippery slope.  The current header functionality is already good for all uses without special-casing for N-javascript libraries.

**Comment by josevalim** [comment]
Thanks everyone. Less work to do then!
