### ISSUE TITLE
"Remote Shell" section in Heroku Deployment doc is out of date

### ISSUE THREAD

**Issue by jonahwh** [phoenixframework/phoenix#2558]
Heroku now supports a feature called [Heroku Exec](https://devcenter.heroku.com/articles/exec) that

> is a feature for creating secure TCP and SSH tunnels into a dyno.

[It has been generally available for a couple weeks now](https://devcenter.heroku.com/changelog-items/1264)

The [Heroku deployment documentation](https://github.com/phoenixframework/phoenix/blob/cec42ab4ef74bd2519018b8fea2592af1bc84572/guides/docs/deployment/heroku.md) section "Remote shells and remote observer are not possible." should be updated to reflect that.

**Comment by ericmj** [comment]
Do you have examples of you how to do remote shells and observer using Heroku Exec?

**Comment by jonahwh** [comment]
Not personally, but [here's a blog post](https://medium.com/@karmajunkie/distributed-elixir-on-heroku-59b691d9868e) that provides an example - the post is more about distributed elixir, but the procedures provided would allow a remote shell to connect via Heroku Exec.

**Comment by ericmj** [comment]
It looks like the examples in the post are no longer working. If we have working examples it would be a good addition to the guides.

**Comment by jonahwh** [comment]
So you can't do a traditional remote shell from your local machine, but the following procedure I just tested works:

1. Start phoenix with a command like the following in your `Procfile`
`elixir --sname server -S mix phoenix.server`
2. Use Heroku Exec to Tunnel into your running Dyno
`heroku ps:exec -aYOUR_HEROKU_APP_NAME`
3. Connect to the server's shell
`iex --sname console --remsh server@${HOSTNAME}`

And you'll be connected, albeit from inside the running server, so you can't interface with your local system.

**Comment by ayrat555** [comment]
@Gazler so what's the status of the issue? is this a working solution?

**Comment by Gazler** [comment]
I'm happy to accept a PR on this issue. I don't use Heroku, so would need to do a Heroku deploy to verify myself if nobody else can verify the best solution.

**Comment by happysalada** [comment]
Just tested the solution. Here is how it worked for me
1. Use the following Procfile
`web: MIX_ENV=prod elixir --sname union_server -S mix phx.server`
2. Use heroku Exec to tunnel into the running Dyno
if you have only one remote and only one app running on it
`heroku ps:exec`
if you have  multiple apps
`heroku ps:exec --app YOUR_HEROKU_APP_NAME`
if you have  multiple remotes
`heroku ps:exec --remote YOUR_HEROKU_REMOTE_NAME`
3. connect to the server's shell (hostname should be lest as is)
`iex --sname console --remsh union_server@${HOSTNAME}`

Just worked for me like a charm! If this can wait until this weekend, I don't mind having a go at a PR.

**Comment by happysalada** [comment]
Just opened a PR regarding this https://github.com/phoenixframework/phoenix/pull/2826
Any comments appreciated.

**Comment by Gazler** [comment]
Cloased via #2826
