### ISSUE TITLE
`_csrf_token` reuse not violates CSRFProtection in the same browser session.

### ISSUE THREAD

**Issue by jechol** [phoenixframework/phoenix#2563]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 8.6.0
* NPM version (npm -v): 5.3.0
* Operating system: macOS Sierra 10.12.6

### Expected behavior

When I copy `_csrf_token` from a form and reuse it in the same form, I expected it would violate CSRFProtection plug.

### Actual behavior

Form submit was handled without CSRF violation if I reuse `_csrf_token` in the same browser session.
Form submit only errors out when I reuse `_csrf_token` after restart browser.

**Comment by josevalim** [comment]
Why would you expect it to not work? It is the same *session*. Which attack would we be preventing? Can you please expand?

**Comment by jechol** [comment]
I thought that _csrf_token must not be reused even for same session. 

I'm novice regarding to CSRF subject, so please close this issue if it's not actually an issue.

**Comment by josevalim** [comment]
@jechol it is tricky because if you don't allow token reuse and the user is using two tabs, submitting one tab invalidates the content in another tab.

Although you are right that not the same token should be used, we rather use the same base which is then masked.

If someone knows of security concerns with this approach, we will be glad to hear.

**Comment by PhillippOhlandt** [comment]
I am doing some scraping recently which involves parsing the CSRF token in order to submit forms and I can confirm that the token is not bound to the specific form but to the whole session. So, since everyone I know handles it this way, I don't think there are any security concerns.
