### ISSUE TITLE
Rescue undefined function errors on Helpers and raise nice error message

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2570]
Pairs with #2530.

**Comment by starbelly** [comment]
@josevalim I can take this one. Making sure its not being done.

**Comment by josevalim** [comment]
@starbelly actually, I don't think this necessary as of Elixir v1.5 and OTP 20 we have improved the error messages in Elixir itself. :)

**Comment by josevalim** [comment]
So I will go ahead and close this, as I think we are good to go as it is now.

**Comment by josevalim** [comment]
Apologies for the out of date issue!

**Comment by starbelly** [comment]
Not a prroblem! 👍  We'll pick another one 😄
