### ISSUE TITLE
handle_out for channel without intercept in docs

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#2579]
The first code example here (https://hexdocs.pm/phoenix/channels.html#incoming-events) does show a `handle_out/3` callback without an `intercept` definition, which is only present in the next following example. For me this does look like `intercept` would only be needed if one would like to stop messages from being sent, but not for only editing the payload. It's just that it would be needed for both cases.

**Comment by chrismccord** [comment]
Good catch! Can you sent a PR to exclude the `handle_out` clause from the first code example?
