### ISSUE TITLE
XXX.Router.Helpers showing up in ExDoc documentation

### ISSUE THREAD

**Issue by raarts** [phoenixframework/phoenix#2580]
In Phoenix I have XXX.Router.Helpers shows up in ExDoc documentation. That's an auto-generated module, and I can't find how to set a `@moduledoc false` on that. 

### Environment

Phoenix 1.3.0

### Expected behavior

Not showing up in ExDoc docs

### Actual behavior

Showing up in generated documentation

**Comment by chrismccord** [comment]
There's no way to set moduledoc false on it today. Is there a particular reason you need to exclude it from docs?

**Comment by raarts** [comment]
I was going through all modules that are generates as a result of phx.new, and putting modulesdoc false everywhere. I think the documentation in there is better suited for learning, then meant to be in the final documentation. To me it would be more fitting to put those 'training' docs in the source code only, for example as ordinary comments, for programmers who are not familiar with Phoenix, but are still being tasked with working on it. I was able to exclude all of the modules but this one. That's why I brought this up.

**Comment by chrismccord** [comment]
Gotcha. We can't use comments since the module is generated outside of a separate file. I prefer to wait on this one until we get more reports of the documentation being as issue for folks. Thanks!

**Comment by imilakovic** [comment]
I have the exactly same thoughts as @raarts :)

For now, I'll just manually remove generated .html files that do not belong to final documentation. But it would be great if we could somehow override `@moduledoc` when using `use` macro.
