### ISSUE TITLE
Generators: Keep the fields' order

### ISSUE THREAD

**Issue by zimt28** [phoenixframework/phoenix#2585]
### Environment

* Elixir version: 1.5.2 
* Phoenix version: 1.3.0

### Expected behavior

`mix phx.gen.html CRM Client clients title email_address`

should generate 

```elixir
schema "clients" do
  field :title, :string
  field :email_address, :string

  timestamps()
end
``` 

### Actual behavior

`mix phx.gen.html CRM Client clients title email_address`

sorts the fields alphabetically

```elixir
schema "clients" do
  field :email_address, :string
  field :title, :string

  timestamps()
end
```

**Comment by chrismccord** [comment]
Thanks for the report! In this case I don't consider this an issue and you are free to list your fields as you see fit after the generates are finished :)
