### ISSUE TITLE
Example Phoenix CRUD app

### ISSUE THREAD

**Issue by gogogarrett** [phoenixframework/phoenix#259]
I played with elixir / phoenix this last week and enjoyed myself, but I found it very hard to find existing sample / demo applications using it. As a result I've created a basic small CRUD app that I think would be helpful for beginners perhaps as reference in the README or something similar.

[phoenix_crud](https://github.com/gogogarrett/phoenix_crud)

Feel free to give me your open thoughts.

Cheers.

**Comment by hiphoox** [comment]
Thanks @gogogarrett!  In the example you said that for delete and update operations you need to add some javascript. @chrismccord Is it a better way to do that?
