### ISSUE TITLE
Redirect to external url

### ISSUE THREAD

**Issue by decentname** [phoenixframework/phoenix#2596]
Current support for redirection to external url does not redirect to the url instead shows a text "You are being redirected". I want to redirect directly to the new external url instead of manually clicking the redirected tag.  Current support : `redirect(conn, external: some_url)`

**Comment by PhillippOhlandt** [comment]
That's normal behavior. The response contains that text as body and a `302` status code with the proper location header. The client (browser, etc.) handles that on its own.

**Comment by decentname** [comment]
my bad. I was setting status code 201 at some point in my code due to which it could not redirect.
