### ISSUE TITLE
phx.gen.schema foreign key index column name

### ISSUE THREAD

**Issue by alisinabh** [phoenixframework/phoenix#2598]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): (doesn't matter)
* NPM version (npm -v): (doesn't matter)
* Operating system: Linux

### Expected behavior

When running gen commands, the created migration adds indexes on foreign keys.
(in my case keys are binary-ids instead of auto increment integers but that does not seem to matter)

The foreign key indexes does not have the `_id` suffix.

For example:

```elixir
mix phx.gen.schema Comment comments comment:string user:references:users
```

generates the following line:

```elixir
create index(:comments, [:user])
```

### Actual behavior

Generating indexes with `_id` suffixes like:

```elixir
create index(:comments, [:user_id])
```

**Comment by chrismccord** [comment]
We require the explicit name of the key, such as `mix phx.gen.schema Comment comments comment:string user_id:references:users`. There are other discussions on the issues tracker around this if you are interested in previous thoughts. Thanks!

**Comment by alisinabh** [comment]
Thanks @chrismccord 

My problem was that in the adding fields it knew it should add `_id` suffix but in indexes it didn't, so it looked like a bug.

```elixir
def change do
    create table(:comments) do
      add :comment, :string
      add :user_id, references(:users, on_delete: :nothing)

      timestamps()
    end

    create index(:comments, [:user])
  end
```
