### ISSUE TITLE
[On-line doc]presence guide link break  

### ISSUE THREAD

**Issue by leiding** [phoenixframework/phoenix#2600]
Hi,
 In the page https://hexdocs.pm/phoenix/channels.html, When I click the link "presence guide" It said pages not found.

paragraph from the doc：

Phoenix ships with a way of handling online users that is built on top of Phoenix.PubSub and Phoenix channels. The usage of presence is covered in the **presence guide.**

Example Application

To see an example of the application we just built, checkout the project phoenix_chat_example.

You can also see a live demo at http://phoenixchat.herokuapp.com/.

**Comment by Gazler** [comment]
Thanks for raising!

I've fixed this in https://github.com/phoenixframework/phoenix/commit/848ef8db1043cd3cd2f774a3a26b275d454bcdef but not deployed yet as I'll have to manually back merge.
