### ISSUE TITLE
Controller action fallback can't be restricted to certain actions

### ISSUE THREAD

**Issue by PhillippOhlandt** [phoenixframework/phoenix#2604]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3
* NodeJS version (node -v): 6.9.5
* NPM version (npm -v): 3.10.10
* Operating system: OSX

### Expected behavior

When I try to restrict an action_fallback to certain actions in a controller, like any other plug, it applies only to those actions. Use case is to have different fallback controllers for different actions (HTML or API).

```elixir
action_fallback MyAppWeb.ApiFallbackController when action in [:posts, :following, :followers]
```

### Actual behavior

When using the guard, it throws the following error:

```
lib/my_app_web/controllers/user_controller.ex:5: undefined function when/2
```

**Comment by chrismccord** [comment]
This isn't a feature we support today, but you could get what you want by calling `Phoenix.Controller.controller_module` and `Phoenix.Controller.action_name` in your fallback plug. Thanks!
