### ISSUE TITLE
Phoenix.js docs doesn't match published version

### ISSUE THREAD

**Issue by stavro** [phoenixframework/phoenix#2608]
The live phoenix.js docs are confusing, because it implies that `v1.3.0` should have the `bindingRef` support for `channel.on()` and `channel.off()`, but that was not part of `1.3.0`.  The only way to tell is by looking at the code.

Perhaps these were published prematurely?

![image](https://user-images.githubusercontent.com/2391584/32075355-6d7ed940-ba51-11e7-9f53-fc6bf30fd0aa.png)

**Comment by Gazler** [comment]
Thanks for raising this. I have updated the docs to correctly reflect the state of 1.3
