### ISSUE TITLE
"Bonus Guides" section is missing from the canonical guides page

### ISSUE THREAD

**Issue by sobbybutter** [phoenixframework/phoenix#2609]
The "Bonus Guides" section is missing from the left pane when visiting https://hexdocs.pm/phoenix/overview.html, but appears when directly visiting a URL to one of its subtopics, e.g. https://hexdocs.pm/phoenix/1.3.0/static_assets.html#content

**Comment by Gazler** [comment]
The bonus guides have been moved out of the guides and into blog posts to keep the guides more focused on the core features. They have been posted on http://phoenixframework.org/blog with the static assets guide available at http://phoenixframework.org/blog/static-assets

It shouldn't be possible to still access https://hexdocs.pm/phoenix/1.3.0/static_assets.html#content - I think this may be a bug with hexdocs.

**Comment by sobbybutter** [comment]
Gotcha. I can't help but wonder, though, if those posts would be better served in the guides. It seems like Static Assets, Sessions, Config, etc. would be really helpful to someone who's just starting out with Phoenix, and putting them in the guides would make them easier to find.

Regardless, much love for all the great work by the Phoenix team! <3 <3

**Comment by Gazler** [comment]
@sobbybutter We made a conscious decision to move or remove the bonus guides from the guides section as it was becoming a dumping ground for additional guides.

This bug has been fixed on hex anyway, so am closing. Thanks for the report.
