### ISSUE TITLE
use npm run watch in dev.exs instead of hard specify brunch

### ISSUE THREAD

**Issue by julien-leclercq** [phoenixframework/phoenix#2611]
### Environment

* Phoenix version : 1.3.0

Since a freshly generated phoenix app's `package.json` includes a watch script in its `package.json` : should not the `dev.exs` file use this script instead of hard specify it ? 

This would allow to customize module bundling in a more transparent way for the developper.

**Comment by Gazler** [comment]
I think this may have been tried before https://github.com/phoenixframework/phoenix/pull/2610

**Comment by josevalim** [comment]
Yup, the issue in our experience is Windows. If somsone is willing to try different Windows versions and guarantee this solution works, please go ahead.
