### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by filyv** [phoenixframework/phoenix#2615]
The link for the documentation seems to be broken:

https://hexdocs.pm/phoenix/1.3.0/file_uploads.html

**Comment by ericmj** [comment]
@filyv Where did you find that link?

**Comment by filyv** [comment]
It's the 3rd result

<img width="1031" alt="screen shot 2017-10-31 at 12 56 39 pm" src="https://user-images.githubusercontent.com/30848993/32243514-0a6af3a0-be3b-11e7-8242-aee4a1f0dde7.png">

**Comment by ericmj** [comment]
We can't control google search results. Removed pages will stay in google search results until google detects that they are not there anymore.

**Comment by chrismccord** [comment]
Thanks for the report! Hopefully google detects the 404 and prunes the results before too long. Thanks!
