### ISSUE TITLE
Cross-origin error on Firefox when linking to app via Messenger

### ISSUE THREAD

**Issue by SylvainBigonneau** [phoenixframework/phoenix#2616]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 8.8.1
* NPM version (npm -v): 5.4.2
* Operating system: Ubuntu 16.04 (server), elementaryOS 0.4.1 (client)
* Browser: Firefox 56.0

### Expected behavior

Using Firefox (desktop), when reaching a Phoenix app from a link in Facebook Messenger, the socket functionalities should work.

### Actual behavior

If you go to a Phoenix app that makes use of channels (for example, [PhoenixChat](http://phoenixchat.herokuapp.com)) from a link on Messenger, the socket functionalities fail and the console contains this error:

> SecurityError: The operation is insecure.

The console's stacktrace links to the line where `socket.connect()` is called on the app.

Any other situation I tried (using another browser and/or coming from somewhere else, Google for example) did not give any problem, **unless** I test this in a tab where I already got the error. Then it keeps failing on this tab.

Tried on two different machines, the same problem occurs.

**Comment by josevalim** [comment]
@SylvainBigonneau if you use the network tools provided by Firefox, can you please check which URL it is trying to connect to and can you make sure that the protocol is suitable?

It *looks* like a Firefox bug but I am not even sure where to start figuring that out.

**Comment by SylvainBigonneau** [comment]
@josevalim Sure, it is leaving through the usual redirection URL that Facebook puts when you link in Messenger : https://l.facebook.com/l.php?u=http%3A%2F%2Fphoenixchat.herokuapp.com%2F

I tried copying that address and pasting it in a new tab, the bug does not happen. Will try to test on websocket websites using other frameworks to see if they fail too.

**Comment by SylvainBigonneau** [comment]
@josevalim OK my bad, tried on this go app http://go-websocket-chat-demo.herokuapp.com/

The bug happens too, so you're right.

**Comment by josevalim** [comment]
I will go ahead and close this as it is not a Phoenix issues but if someone knows of a straight-forward workaround please leave a comment!
