### ISSUE TITLE
Auto-generated JSON controller tests fail for schemas with date fields

### ISSUE THREAD

**Issue by jswny** [phoenixframework/phoenix#2618]
### Environment

* Elixir version (elixir -v): `1.5.2`
* Phoenix version (mix deps): `1.3.0`
* NodeJS version (node -v): `8.9.0`
* NPM version (npm -v): `5.5.1`
* Operating system: macOS High Sierra `10.13`
* PostgreSQL version: `9.6.3`
* Ecto version: `2.2.6`

### Steps to reproduce
1. `mix phx.new bug`
2. `mix phx.gen.json Core Bar bars date:date`
3. Uncomment the `/api` scope in `router.ex` and paste the following in: `resources "/bars", BarController, except: [:new, :edit]`
4. `mix test`

### Expected behavior
All tests (auto-generated) pass with no failures.

### Actual behavior
```
➜  bug mix test
....

  1) test create bar renders bar when data is valid (BugWeb.BarControllerTest)
     test/bug_web/controllers/bar_controller_test.exs:28
     Assertion with == failed
     code:  assert json_response(conn, 200)["data"] == %{"id" => id, "date" => ~D"2010-04-17"}
     left:  %{"id" => 13, "date" => "2010-04-17"}
     right: %{"id" => 13, "date" => ~D[2010-04-17]}
     stacktrace:
       test/bug_web/controllers/bar_controller_test.exs:33: (test)

.

  2) test update bar renders bar when data is valid (BugWeb.BarControllerTest)
     test/bug_web/controllers/bar_controller_test.exs:47
     Assertion with == failed
     code:  assert json_response(conn, 200)["data"] == %{"id" => id, "date" => ~D"2011-05-18"}
     left:  %{"id" => 14, "date" => "2011-05-18"}
     right: %{"id" => 14, "date" => ~D[2011-05-18]}
     stacktrace:
       test/bug_web/controllers/bar_controller_test.exs:52: (test)

...........

Finished in 0.2 seconds
18 tests, 2 failures

Randomized with seed 221519
```

Upon further investigation including help in [this thread](https://elixirforum.com/t/is-this-a-bug/9790), the problem appears to be that the test tries to use the date sigil (`~D[2010-04-17]`) generated and hardcoded into the test while the JSON response will always be a string. The offending piece of code (one of two) is as follows (from `test/bug_web/controllers/bar_controller_test.exs`:
```
assert json_response(conn, 200)["data"] == %{
  "id" => id,
  "date" => ~D[2010-04-17]}
```

To fix this, the test can be updated to use the string values for the dates in the two offending tests like so:
* `create bar renders bar when data is valid` -> `"date" => "2010-04-17"`
* `update bar renders bar when data is valid` -> `"date" => "2010-05-18"`

The generator code for this test is located [here](https://github.com/phoenixframework/phoenix/blob/master/priv/templates/phx.gen.json/controller_test.exs).

**Comment by chrismccord** [comment]
Fixed. Thanks for the report!
