### ISSUE TITLE
Phoenix fails to build in production

### ISSUE THREAD

**Issue by PeterDavidCarter** [phoenixframework/phoenix#2620]
### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.2
```

* Phoenix version (mix deps):
```
* file_system 0.2.2 (Hex package) (mix)
  locked at 0.2.2 (file_system) 7f1e9de4
  ok
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* gettext 0.13.1 (Hex package) (mix)
  locked at 0.13.1 (gettext) 5e0daf4e
  ok
* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poolboy 1.5.1 (Hex package) (rebar3)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.4.1 (Hex package) (mix)
  locked at 1.4.1 (decimal) ad9e501e
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) d9eb6366
  ok
* db_connection 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (db_connection) 2865c2a4
  ok
* phoenix_pubsub 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (phoenix_pubsub) bfa7fd52
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* mime 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (mime) 01c1d6f4
  ok
* plug 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (plug) 236d77ce
  ok
* phoenix_html 2.10.4 (Hex package) (mix)
  locked at 2.10.4 (phoenix_html) d4f99c32
  ok
* phoenix 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (phoenix) 1c01124c
  ok
* phoenix_live_reload 1.1.3 (Hex package) (mix)
  locked at 1.1.3 (phoenix_live_reload) 1d178429
  ok
* postgrex 0.13.3 (Hex package) (mix)
  locked at 0.13.3 (postgrex) c277cfb2
  ok
* ecto 2.2.6 (Hex package) (mix)
  locked at 2.2.6 (ecto) 3fd10676
  ok
* distillery 1.5.2 (Hex package) (mix)
  locked at 1.5.2 (distillery) eec18b2d
  ok
* edeliver 1.4.4 (Hex package) (mix)
  locked at 1.4.4 (edeliver) f019e1e8
  ok
* phoenix_ecto 3.3.0 (Hex package) (mix)
  locked at 3.3.0 (phoenix_ecto) 702f6e16
  ok
```

* NodeJS version (node -v):
`v8.7.0`

* NPM version (npm -v):
5.4.2

* Operating system:

Debian 9

### Expected behavior

Expected `MIX_ENV=prod mix compile` to complete without errors.

### Actual behavior

Fails with error:

```
== Compilation error in file lib/haaksploits/repo.ex ==
** (ArgumentError) missing :adapter configuration in config :haaksploits, Haaksploits.Repo
    lib/ecto/repo/supervisor.ex:69: Ecto.Repo.Supervisor.compile_config/2
    lib/haaksploits/repo.ex:2: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

**Comment by OvermindDL1** [comment]
This is not a Phoenix error, but rather it is telling you the problem:

```elixir
== Compilation error in file lib/haaksploits/repo.ex ==
** (ArgumentError) missing :adapter configuration in config :haaksploits, Haaksploits.Repo
```

It says that you are missing the `:adapter` configuration in your config file (`config/prod.ex` if you are building in the `prod` environment).

It usually helps to ask about coding problems on the https://elixirforum.com/ instead of as Issues on the repo.  ^.^

**Comment by PeterDavidCarter** [comment]
I did, but no-one seemed to be able to help. If it's necessary to add an :adapter configuration shouldn't that be covered in the Phoenix deployment docs? Because that's what I've been following to the letter.

**Comment by OvermindDL1** [comment]
https://elixirforum.com/t/adapter-error-when-deploying-to-production-using-phoenix-with-edeliver/9835/3

It was only 4 hours ago, it takes time, and you generally get faster responses there than there.  ^.^;

**Comment by PeterDavidCarter** [comment]
Thanks for responding on the Elixir forums. I think you might have a point in your response there, and I think I see where the problem arose. If it works I might raise a future issue regarding the error messages, but tbh I think until I'm in a position to fix the error message to be useful myself I might hold off...

E.g. status: in testing.

**Comment by OvermindDL1** [comment]
This might still be a good issue to enhance that deployment documentation if it is missing a description on remembering to set the adapter and so forth at the very least.  :-)

**Comment by PeterDavidCarter** [comment]
Yes. Once I've tested and made sure the suggestion you made is accurate (not doubting it, btw; just need to test) I'll be sure to put in a pull request for the docs.

**Comment by chrismccord** [comment]
By default we include the Ecto Repo config (including the adapter) in your prod.secret.exs. It appears you removed the config from that file so you need to make sure either your prod.exs, or prod.secret.exs contains the following:

```elixir
config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "...",
  password: "...",
  database: "...",
  pool_size: 15
```

**Comment by PeterDavidCarter** [comment]
The file now contains:

```
use Mix.Config

# In this file, we keep production configuration that
# you'll likely want to automate and keep away from
# your version control system.
#
# You should document the content of this
# file or create a script for recreating it, since it's
# kept out of version control and might be hard to recover
# or recreate for your teammates (or yourself later on).
config :haaksploits, HaaksploitsWeb.Endpoint,
  secret_key_base: "mysecretkey"

# Configure your database
config :project, Project.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "haaksploits",
  password: "mypassword",
  database: "haaksploits_prod",
  pool_size: 15
```


And it's still doing exactly the same thing as before.
