### ISSUE TITLE
Non-sensical error message when running mix phoenix.new inside umbrella app

### ISSUE THREAD

**Issue by christophermlne** [phoenixframework/phoenix#2623]
I'm trying to create a new Phoenix app within an existing umbrella project but am encountering a strange error that doesn't point its cause.

`mix phoenix.new api --no-ecto`
=> ** (Mix) Application name must start with a letter and have only lowercase letters, numbers and underscore, got: "api". The application name is inferred from the path, if you'd like to explicitly name the application then use the `--app APP` option.

ok, so let's try that:

`mix phoenix.new api --app api --no-ecto`
=> ** (Mix) Application name must start with a letter and have only lowercase letters, numbers and underscore, got: "api"

well that doesn't make any sense. should it be --app=api? let's try that:

`mix phoenix.new api --app=api --no-ecto`
=> ** (Mix) Application name must start with a letter and have only lowercase letters, numbers and underscore, got: "api"

i wonder if i should remove "app" when i'm passing in the --app flag? let's try that:

`mix phoenix.new --app=api --no-ecto`

=> mix phoenix.new
=> Creates a new Phoenix project.
=> It expects the path of the project as argument.

Path? Hmm...it's expecting the path of the project as argument. That might be a clue. Since we're already inside the app folder, let's try using a dot as the path:

`mix phoenix.new . --app=api --no-ecto`
=> ** (Mix) Application name must start with a letter and have only lowercase letters, numbers and underscore, got: "api"

And so here we are. I'm opening this as a usability issue. It might very well be that I'm doing something wrong, but I couldn't tell what it is from the error message.

### Environment

* Elixir version (elixir -v): `Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.0`
* Phoenix version (mix deps): N/A.
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

### Expected behavior
app should be created in apps folder within umbrella app

### Actual behavior
non-sensical error message

**Comment by chrismccord** [comment]
This is caused by an older archive failing against OTP 20. You should be able to fix it by `mix archive.uninstall phoenix_new` then reinstalling the archive. If that fails please let us know and we can look further. Thanks!

**Comment by christophermlne** [comment]
@chrismccord tried that just now and it didn't work.

i'll just install phoenix into a different folder and then copy it back into the umbrella project to get around the issue. 

not sure this issue should be closed though.
