### ISSUE TITLE
Phoenix process silently fails to start as daemon

### ISSUE THREAD

**Issue by PeterDavidCarter** [phoenixframework/phoenix#2625]
After killing the phoenix production process with fuser (`fuser -k 4000/tcp`) to workaround lack of restart capability, `MIX_ENV=prod PORT=4000 elixir --detached -S mix do compile, phx.server`
silently fails to start production server.

Should at the very least throw an error of some kind here.

**Comment by PeterDavidCarter** [comment]
The problem here was that the process needed to be run as root, but this process should not have failed silently, and should have thrown an appropriate error message, as the `phx.server` command does.

**Comment by OvermindDL1** [comment]
Uh, it shouldn't need to be run as root.  Port 4000 is well above the 2000 root limit, in addition I run my phoenix server in redhat as a service but loaded into a specific user account so it is not root there either.  Do you have a specific reproducible example that we can just copy/paste in?

Also is Phoenix not throwing an error in your log?  If you are `--detached`'ing it then the stdout is detached before the system even loads to do anything, but I do immediately have `Logger` going out to a log file, which does indeed load before Phoenix as I get the endpoint hosting message.

**Comment by PeterDavidCarter** [comment]
`mix phx.server` gave me:

```
mix phx.server
** (File.Error) could not write to file "/home/lbdbus/haaweb/_build/dev/lib/haaksploits/.compile_priv_gettext": permission denied
```

And a bunch of other errors that clued me into needing to run as root (was running as lbdbus user).

There was also another problem: 

https://stackoverflow.com/questions/47169333/fuser-doesnt-kill-process-on-port/47169415#47169415

Which seems plausibly connected, though obviously not directly a Phoenix thing.

**Comment by PeterDavidCarter** [comment]
I didn't look at the error log, but imo it should really log to the console at least with the location of the appropriate error log.

**Comment by OvermindDL1** [comment]
> And a bunch of other errors that clued me into needing to run as root (was running as lbdbus user).

That really makes me wonder if it was really running as the lbdbus user and about what those file permissions were.  After checking that then I'd blast the entire `_build` directory and try again as the `lbdbus` user directly.

> Which seems plausibly connected, though obviously not directly a Phoenix thing.

I'm not sure about that, I don't use `fuser -k` but what I'd immediately think is either you didn't have permission or it did not kill the process 'group' (but rather just that single node, and it could have been restarted by the runtime) where `kill` properly terminated the process group leader?

> I didn't look at the error log, but imo it should really log to the console at least with the location of the appropriate error log.

What console?  If you run with `--detached` then there is no console attached.  It specifically forks 'away' from the tty before it ever runs even a single line of BEAM code.

**Comment by PeterDavidCarter** [comment]
![screen shot 2017-11-08 at 00 16 02](https://user-images.githubusercontent.com/23146481/32524940-11f624ca-c41a-11e7-92cd-1cb41d4bb77f.png)
![screen shot 2017-11-08 at 00 14 12](https://user-images.githubusercontent.com/23146481/32524941-1429f212-c41a-11e7-90a0-f2c600964f1b.png)
![screen shot 2017-11-08 at 00 14 13](https://user-images.githubusercontent.com/23146481/32524946-15568894-c41a-11e7-91f5-caace717c947.png)

Note that though the message about non-root users not being able to see information was shown, it was corroborated that there was no port 4000 process, since nginx is setup in such a way that 502 bad gateway is shown when this happens, which was the case.

**Comment by PeterDavidCarter** [comment]
I addition, as you can see, the server process was run as the ldbbus user, and hence should have been visible from a `netstat -tulpn` command issued by that user.

**Comment by chrismccord** [comment]
As Overmind said, you don't get console output when running as detached, so you'll need to configure and check your error logs instead if you want to run this way. Have you enabled a file logging backend? Do your errors get written there?

**Comment by PeterDavidCarter** [comment]
I don't see any necessary reason why console logging couldn't be added to a daemon process. Unless you have it configured in an unusual way. I suppose I could write a bash script to output the location of the log file to console if you tell me where said log file is.

**Comment by PeterDavidCarter** [comment]
You have written a good framework here Chris. Very good in fact, but your response doesn't deal with the problem I outlined in that the daemon process both can and should output an error log location, if not a full error log.

**Comment by josevalim** [comment]
@PeterDavidCarter it is not up to us to decide. --detached mode comes from the VM and what it does with IO is not up to us. My recommendation is for you to use distillery for building releases as that will set up the logs for you or use `run_erl` directly, which includes daemon mode and file logging: http://erlang.org/doc/man/run_erl.html

**Comment by PeterDavidCarter** [comment]
I've been using edeliver and distillery, but process was too complex and distracted from other, more pressing concerns. You should not need to change anything 'coming from the VM' if you impliment a simple, low-overhead wrapper like the one I outlined above.

**Comment by josevalim** [comment]
It is not our plan to provide such a wrapper but, if it is simple and low-overhead, then please go ahead with your implementation and if you can make it available for others, then even better! We rather want to focus on making distillery more accessible and less distracting.

**Comment by PeterDavidCarter** [comment]
Perhaps it would be better if I look into contributing to distillery then, if that's the way development is moving. Simpler and more accessible sounds a noble goal amd much of the additionally functionality appeals.

**Comment by PeterDavidCarter** [comment]
Perhaps it would be better if I look into contributing to distillery then, if that's the way development is moving. Simpler and more accessible sounds a noble goal and something likely worth the time to contribute to.
