### ISSUE TITLE
Redirect to "." fails

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#2627]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0

### Expected behavior

I've often used redirects to `.` in a system I'm currenty moving to phoenix, so I could redirect to the same page without knowing which page it is and conveniently getting rid of any get request params. 

### Actual behavior

It does fail with this error: `the :to option in redirect expects a path but was "."`

**Comment by chrismccord** [comment]
You can use `redirect(conn, to: current_path(conn, %{}))` to redirect to the current page with query params stripped.
