### ISSUE TITLE
Typo in defmodule Phoenix.Endpoint documentation

### ISSUE THREAD

**Issue by cutdekprod** [phoenixframework/phoenix#2630]
File lib/phoenix/endpoint.ex
Line 67 says `:supervivsor`

**Comment by webdeb** [comment]
seams to be already fixed in master 
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint.ex#L67

**Comment by chrismccord** [comment]
Thanks for the heads up! As webbed said, it will be live in the next release.
