### ISSUE TITLE
Cant run commands directly for non-umbrellas

### ISSUE THREAD

**Issue by Fudoshiki** [phoenixframework/phoenix#2637]
### Environment

* 
  ```
  Erlang/OTP 20 [erts-9.1.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe [kernel-poll:false] [dtrace]
  Elixir 1.5.2
  ```
* 
  ```
  phoenix 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (phoenix) 1c01124c
  ```
* `Node.js v9.2.0`
* `Yarn 1.3.2`
* `macOS High Sierra Beta 10.13.2 (17C79a)`

### Expected behavior
```elixir
defp aliases do
    [
      "app.setup": ["deps.get", "ecto.setup", "cmd cd assets && yarn"],
      "app.reset": ["cmd rm -rf _build deps mix.lock assets/node_modules assets/yarn.lock", "app.setup"],
      "ecto.setup": ["run priv/repo/seeds.exs"],
      "ecto.reset": ["ecto.drop", "ecto.setup"],
      "test": ["test"]
    ]
  end
```
Run `mix.reset` should run  `"cmd cd assets && yarn"`

### Actual behavior
When run `mix app.setup` all good,
When `run app.reset`, this doesn't run part  `"cmd cd assets && yarn"`

### From Discord
ericmj
```
@sharevari cmd is used for umbrella apps, if you are not in an umbrella i think it's a noop
```

@ericmj so, how i can run shell commands?

ericmj
```
i think you have to wrap it in a task and run Mix.shell().cmd()
for task aliases the task can be a function
you may also want to raise the issue that we cant run commands directly for non-umbrellas
```

**Comment by ericmj** [comment]
Sorry, I was not being clear. This is a feature request for Elixir since Mix tasks are not part of Phoenix. Elixir feature requests should be sent to the Elixir Core mailing list.

**Comment by Fudoshiki** [comment]
@ericmj Should I open new issue in Elixir repository?

**Comment by ericmj** [comment]
@Fudoshiki I guess you can open on the Elixir repository because it's at least arguably a documentation bug that `cmd` is a noop for non-umbrellas.
