### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by PeterDavidCarter** [phoenixframework/phoenix#2648]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): v8.7.0
* NPM version (npm -v): 5.5.1
* Operating system: MacOS 10.13.1

### Expected behavior

As per

https://hexdocs.pm/phoenix/channels.html#content

I expected this code:

```
chatInput.addEventListener("keypress", event => {
  if(event.keyCode === 13){
    channel.push("new_msg", {body: chatInput.value})
    chatInput.value = ""
  }
})

```
To work without error.

### Actual behavior

```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at socket.js:67
    at initModule (app.js:42)
    at require (app.js:59)
    at expanded (app.js:34)
    at app.js:5
    at initModule (app.js:42)
    at require (app.js:59)
    at socket.js:1
```

Logged to the console and chat functionality not available. JavaScript `.load` events also fail silently.

**Comment by webdeb** [comment]
If you code is exact like the one in the example, then probably you are loading the JS before the actual html.. This is why it cannot find the node.. Its recommended to load the js just before the closing `</body>` tag

**Comment by PeterDavidCarter** [comment]
Moved the JS to just before the closing body tag but the issue persists. Wrapping in `$(function() { });` doesn't help either.

**Comment by webdeb** [comment]
I looked at your code. And basically the JS will only work on pages where the 
`<input id="chat-input"></input>` is rendered, which means, that you will get this error on pages where this input does not exists. If it would be there, then `document.querySelector` would definitely find it, right?

**Comment by webdeb** [comment]
A very simple and basic solution to that, without any frameworks or so involved would be to check for the presence of the chat-input before assigning the listener to it.

```
const chatInput = document.querySelector('#chat-input');
if (chatInput) {
  // chatInput was found, this means we are on a page, where we can chat
  // rest of your code

}
```

**Comment by PeterDavidCarter** [comment]
Thanks webdeb. I ended up using a very similar solution in jQuery:

```
$("#chat-input").load(function() {
  chatInput.addEventListener("keypress", event => {
    if(event.keyCode === 13){
      channel.push("new_msg", {body: chatInput.value})
      chatInput.value = ""
    }
  })
});
```
