### ISSUE TITLE
test "--no-start" problem

### ISSUE THREAD

**Issue by silently** [phoenixframework/phoenix#2651]
### Actual behavior

Just run these 3 steps:
```
$ mix phx.new tmp
$ cd tmp
$ mix test --no-start
** (ArgumentError) argument error
    (stdlib) :ets.lookup_element(Ecto.Registry, nil, 3)
    (ecto) lib/ecto/registry.ex:18: Ecto.Registry.lookup/1
    (ecto) lib/ecto/adapters/sql/sandbox.ex:426: Ecto.Adapters.SQL.Sandbox.mode/2
    (elixir) lib/code.ex:376: Code.require_file/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
```
So it seems the "--no-start" option indeed prevents the application and its children (`Tmp.Repo` especially) to be launched, but Ecto seems so be needed somehow, crashing the test suite.

### Expected behavior

Possibility to use the `--no-start` option with ExUnit

### Environment

* Elixir version (elixir -v): 1.5.1
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): v7.10.0
* NPM version (npm -v): 4.2.0
* Operating system: MacOS

**Comment by josevalim** [comment]
I don’t think this would ever work. “mix test” is by default configured to
migrate the database. Your test helper sets up a sandbox. You are free to
undo those changes in your mix.exs but I don’t see a purpose for doing it
out of the box.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by silently** [comment]
Ok, anyway I tried this option since I wanted to test a "singleton" module GenServer independently from the fact its started by an application worker (so that I can "reboot" its state during test cases with different/new/known data).

Maybe a better solution is to "unsingletonized" it and to use different `:name`s when launched by the app VS `start_supervised` during test cases.

Moreover I need mix to launch the app for web tests!
