### ISSUE TITLE
`mix phx.new.web app_name` and mix `mix phx.gen.html` conflicts if app_name is not suffixed with `_web`

### ISSUE THREAD

**Issue by EvertYipYip** [phoenixframework/phoenix#2656]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 8.4.0
* NPM version (npm -v): 5.5.1
* Operating system: macOS Sierra 10.12.6

### Expected behavior
 `mix phx.new.web app_name` and mix `mix phx.gen.html` work fine together, no matter what the app_name is.

If for example the app name is `foo_web` and you run `mix phx.new.web foo_web` and `mix phx.gen.html Account User users name: string` everything works as expected.

### Actual behaviour
 `mix phx.new.web app_name` and mix `mix phx.gen.html` conflicts if app_name is not suffixed with `_web`

If for example the app name is `foo` and you run `mix phx.new.web foo` and `mix phx.gen.html Account User users name: string` the controller contains the namespace `FooWeb.UserController` and uses `use FooWeb, :controller` however `FooWeb` does not exist since the app name is `Foo`. The PageController (generated with the creation of the app) does this right however.

Same problem occurs in `FooWeb.UserView`

### Possible solutions
- Force the developer to suffix his app_name with `_web` when using `mix phx.new.web`, raise if not.
- Automatically suffix app_name with `_web` when creating new web app. (Or prompt developer for it)
- Remove suffixing with `_web` when building context struct: https://github.com/phoenixframework/phoenix/blob/d36148ae7b6570d45227abaabd2af9740beff542/lib/mix/phoenix/context.ex#L77-L84

**Comment by alexgaribay** [comment]
@chrismccord What is your preferred solution?

**Comment by henry-hz** [comment]
i think the best solution would be to leave it open, and fix the main user-view and controller code generation, and for mix phx.new applications, it's okay to add automatically the _web into the context, once all the files (web and ecto) are created together, something that is less frequent when creating umbrella apps
