### ISSUE TITLE
Phoenix.ActionClauseError vs new FunctionClauseError

### ISSUE THREAD

**Issue by michalmuskala** [phoenixframework/phoenix#2657]
When no action clause matches the request parameters phoenix will generate a `Phoenix.ActionClauseError`. This was fine in Elixir < 1.5, where the generic `FunctionClauseError` wasn't very readable and the extra information Phoenix provided in the error message were quite useful.

The situation changed with the Elixir 1.5 release and the `Exception.blame` mechanism that is wonderful - especially the part where it lists the function clauses and analyses them to say why they didn't match the argument.

I know that the `Phoenix.ActionClauseError` also serves another role - it allows serving a 400 response instead of the 500 one - which is correct since the endpoint received unexpected data.

It would be wonderful, if `Phoenix.ActionClauseError` featured a similar message to what is given by `Exception.blame` for `FunctionClauseError`s. I think it would make lives of developers much easier, I'm not sure, though, how feasible that is.

**Comment by chrismccord** [comment]
Is there any way we can hook into Exception.blame for this information?

**Comment by michalmuskala** [comment]
I was thinking about this, but it seems `Exception.blame` hardcodes to only augment `FunctionClause` and doesn't provide any extension points. Then iex, `Plug.Debugger`, ex unit always call `Exception.blame` also providing no extension point. I'm not really sure how we could leverage this, but I think it would be really beneficial.

I think this warrants a cc @josevalim 

Maybe in 1.6 we could get some new callback on exception modules to "provide additional info"? I think this could be generally useful - basically have two modes for exceptions - verbose (used in tests in dev) and terse (used in prod). There are many exceptions that log instructions on how to fix the situation, but they are not really that needed in prod and just strain the logging service.

**Comment by josevalim** [comment]
@michalmuskala I think the simplest approach would be to add `def blame` to the exception behaviour. Thoughts?

**Comment by michalmuskala** [comment]
For reference, discussion moved to https://github.com/elixir-lang/elixir/issues/7074

**Comment by davydog187** [comment]
Is this actionable now? It seems like we can only add this behavior for Elixir >= 1.6

**Comment by davydog187** [comment]
Great, I'll take a stab. Thanks @josevalim

**Comment by davydog187** [comment]
I started experimenting with the implementation. I would appreciate some guidance on the goals of this issue @michalmuskala

**Comment by michalmuskala** [comment]
The general idea is that the `Phoenix.ActionClauseError` module should implement the optional `blame/1` callback in a similar way that [`FunctionClauseError` does](https://github.com/elixir-lang/elixir/blob/fca649e909d62bc34e9948d863091076c4c9c419/lib/elixir/lib/exception.ex#L955) - leveraging `Exception.blame_mfa/3` to give information on available clauses and what exactly didn't match.

**Comment by davydog187** [comment]
Started an exploration [here](https://github.com/davydog187/phoenix/tree/dl_add_blame) yesterday to start understanding the problem.

Curious how this could integrate with the plug debugger as it doesn't seem that Plug.Debugger allows you to stylize error messages

**Comment by michalmuskala** [comment]
I think `Plug.Debugger` should be able to handle it just fine on its own. If not, I think it should be changed in `Plug.Debugger` - it should work fine with the general elixir features.

**Comment by chrismccord** [comment]
ping @davydog187 any progress on this one yet?

**Comment by davydog187** [comment]
hey @chrismccord, I don't have any updates but was planning on giving it another go this week. Would love some guidance on the expected feature set. Also happy to hand off if you wanted to expedite.
