### ISSUE TITLE
Phoenix.ChannelTest/join and socket state issue

### ISSUE THREAD

**Issue by NeilMenne** [phoenixframework/phoenix#2660]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): n/a
* NPM version (npm -v): n/a
* Operating system: Mac OS High Sierra

### Expected behavior
If the `Channel` mutates the socket as part of a handle_in/_out, that mutation must be replicated in the test. It only seems to matter with ChannelTest.join.

### Actual behavior
`socket` cannot be updated within the test without duplicating the `assign`s in the test. Here's a simple setup:

```
defmodule ChanDevWeb.RoomChannel do
  use ChanDevWeb, :channel

  def join("room:" <> _rest, _payload, socket) do
    if authorized?(socket) do
      {:ok, assign(socket, :state, :unset)}
    else
      {:error, %{reason: "unauthorized"}}
    end
  end

  def handle_in("set_state", %{"new_state" => x}, socket) do
    {:reply, :ok, assign(socket, :state, x)}
  end

  def handle_in("get_state", _msg, socket) do
    {:reply, {:ok, %{"curr_state" => socket.assigns.state}}, socket}
  end

  @doc """
  You can't join a second channel until you've set the state appropriately
  """
  defp authorized?(socket), do: Map.get(socket.assigns, :state, :set) == :set
end
```

```
defmodule ChanDevWeb.RoomChannelTest do
  use ChanDevWeb.ChannelCase

  alias ChanDevWeb.{UserSocket, RoomChannel}

  test "set_state updates state" do
    {:ok, socket} = connect(UserSocket, %{})
    {:ok, _reply, socket} = subscribe_and_join(
      socket,
      RoomChannel,
      "room:lobby",
      %{}
    )

    ref = push socket, "set_state", %{"new_state" => :set}
    assert_reply ref, :ok, %{}

    # socket state on the server clearly set appropriately
    ref = push socket, "get_state", %{}
    assert_reply ref, :ok, %{"curr_state" => :set}

    # fails because of {:error, %{reason: "unauthorized"}}
    {:ok, _reply, socket} = join(socket, "room:lobby2")
  end
end
```

**Comment by josevalim** [comment]
That’s by design. The test is emulating the socket from the point of view
of the client. It doesn’t have access to the server socket state.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
It is also worth mentioning that the socket from different channels are not
shared as well.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by chrismccord** [comment]
I think José cleared things up, but if you have questions feel free to follow up. Closing as this is not an issue. Thanks!

**Comment by NeilMenne** [comment]
That makes it sound like you can't use the same socket for multiple channels.

**Comment by josevalim** [comment]
It is the same TCP socket but each channel gets its own data structure
represneting the socket.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by NeilMenne** [comment]
So the assigns are essentially reset per channel on the socket?

**Comment by NeilMenne** [comment]
That would explain why the behavior I'm seeing, it was just unexpected.

**Comment by NeilMenne** [comment]
I got it now:

```
test "set_state updates state" do
    {:ok, conn_socket} = connect(UserSocket, %{})
    {:ok, _reply, socket} = subscribe_and_join(
      conn_socket,
      RoomChannel,
      "room:lobby",
      %{}
    )

    ref = push socket, "set_state", %{"new_state" => :set}
    assert_reply ref, :ok, %{}

    ref = push socket, "get_state", %{}
    assert_reply ref, :ok, %{"curr_state" => :set}

    {:ok, _reply, socket} = join(conn_socket, "room:lobby2")
  end
```

**Comment by NeilMenne** [comment]
Thanks for clarification. Is the "channel state is not shared" thing documented somewhere?
