### ISSUE TITLE
Layout view commenting unclear

### ISSUE THREAD

**Issue by PeterDavidCarter** [phoenixframework/phoenix#2661]
The default generated Layout view is has code as follows:

```
  @doc """
  Generates name for the JavaScript view we want to use
  in this combination of view/template.
  """
  def js_view_name(conn, view_template) do
    [view_name(conn), template_name(view_template)]
    |> Enum.reverse
    |> List.insert_at(0, "view")
    |> Enum.map(&String.capitalize/1)
    |> Enum.reverse
    |> Enum.join("")
  end
```

To me this could be clearer. What is a JavaScript view and does it allow for per-page JavaScript loading? If so, this would be a very useful feature to know about.

**Comment by josevalim** [comment]
The layout generated by Phoenix is empty:
https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_web/views/layout_view.ex

Maybe something else has added it? Can you reproduce this issue in a brand
new app?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by chrismccord** [comment]
As José said, this is not code produced by our project generator so it must have been placed there by another teammate or package. Thanks!
