### ISSUE TITLE
Attempting to build and install phx.new locally results in 'chris' directory error

### ISSUE THREAD

**Issue by PeterDavidCarter** [phoenixframework/phoenix#2662]
### Environment

Elixir version (elixir -v): 1.5.2
Phoenix version (mix deps): 1.3.0
NodeJS version (node -v): 8.7.0
NPM version (npm -v): 5.5.1
Operating system: macOS Sierra 10.13.1

### Expected behavior

Following:

> 
> Provides phx.new installer as an archive. To build and install it locally:
> 
> $ cd installer
> $ MIX_ENV=prod mix archive.build
> $ mix archive.install

Was expected to build and install on my local machine, so I can develop it.

### Actual behavior

Installer tries to install to the `chris` user directory!

```
== Compilation error in file lib/phx_new/ecto.ex ==
** (File.Error) could not read file "/Users/chris/oss/phoenix/installer/templates/phx_ecto/repo.ex": no such file or directory
    (elixir) lib/file.ex:272: File.read!/1
    lib/phx_new/generator.ex:28: anonymous fn/4 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/phx_new/generator.ex:24: anonymous fn/3 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Phx.New.Generator.__before_compile__/1
    lib/phx_new/ecto.ex:1: Phx.New.Ecto (module)
```

I mean, I suppose I could change my (user)name to chris, but I'm not sure if this is a little too drastic a workaround 😳.

**Comment by chrismccord** [comment]
I remember something around this that was fixed pretty far back. Can you make sure you have the latest 1.3 branch checked out and retry?:

```
$ cd /path/to/phoenix
$ git fetch
$ git checkout v1.3
$ ... repeat archive build/install
```

Thanks!

**Comment by PeterDavidCarter** [comment]
Does the same thing. I'm gonna try recloning the repo though.

**Comment by PeterDavidCarter** [comment]
Nope, same thing with a new clone, so definitely the latest version.

**Comment by PeterDavidCarter** [comment]
Solution was to reclone the repo and then run `mix archive.uninstall phx_new` as well, which removed the old archive.
