### ISSUE TITLE
Multiple AJAX requests when using turbolinks and remote forms 

### ISSUE THREAD

**Issue by NicolayD** [phoenixframework/phoenix#2664]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 6.9.1
* NPM version (npm -v): 3.10.8
* Operating system: macOS Sierra 10.12.6 

### Expected behavior

Use turbolinks and submit a form with an AJAX request without reloading the page.
The library I use is [ex_turbolinks](https://github.com/imranismail/ex_turbolinks).

### Actual behavior

Following the instructions on the ex_turbolinks github page, everything seemed to be working fine.
However, after inspecting, I found out that every time I submitted the form that has data-remote set to true (essentially a search form), there was one additional cancelled AJAX request being sent. The form itself worked, but the piling cancelled AJAX requests started slowing the loading time after a while. 

### Possible solutions

I tried a few methods, for example using Turbolinks.clearCache(), but it didn't work.
What helped me solve the problem was moving the `<script src="<%= static_path(@conn, "/js/app.js") %>"></script>` tag in app.html.eex from the body to the head. This is where I found this solution: https://github.com/turbolinks/turbolinks-classic/issues/153#issuecomment-13637290

I know this is not a strictly Phoenix issue and there might be a better solution, but I thought of posting it here as the answer I found is related to the default Phoenix layout.

**Comment by josevalim** [comment]
I think having the script tag in the body is the best approach if you are not using turbolinks. If you are using turbolinks than indeed you should move it around. Maybe the turbolinks or ex_turbolinks project should have that in their README. Thanks for the report!
