### ISSUE TITLE
Is any date of 1.4 release?

### ISSUE THREAD

**Issue by cystbear** [phoenixframework/phoenix#2668]
Hi guys,

do you have any kind of release_cycle // milestones_map or something like this?
Example: [Symfony Releases](https://symfony.com/doc/current/contributing/community/releases.html#schedule)

Actually I am waiting for 1.4 to start hacking Elixir and Phoenix

**Comment by webdeb** [comment]
> Actually I am waiting for 1.4 to start hacking Elixir and Phoenix

Phoenix is production ready, elixir is running at scale. Whats the point of waiting?

**Comment by josevalim** [comment]
It will be ready when it is ready. :) I agree with @webdeb, there is no point to wait for 1.4, especially because it will be more of a maintainance release with experimental HTTP 2 support.

**Comment by cystbear** [comment]
I was at some conference in Kyiv, and José said that 1.4 will be released soon. And 1.4 with IMPROVED dir structure.

**Comment by josevalim** [comment]
@cystbear that was for version 1.3, which is already out.  :)

**Comment by cystbear** [comment]
ok, good to know
