### ISSUE TITLE
timeout solutions with phoenix ?

### ISSUE THREAD

**Issue by mydearxym** [phoenixframework/phoenix#2671]
hi there ~ 

i am working on a GraphQL-related project with phoenix and Face a [situation](https://www.howtographql.com/advanced/4-security/):  

> For example, a server configured with a 5 seconds timeout would stop the execution of any query that is taking more than 5 seconds to execute.

i read the [question on Elixir/forum](https://www.howtographql.com/advanced/4-security/), but it seems unsolved .

may i ask is there a official solution for this kind of situation ?

**Comment by PhillippOhlandt** [comment]
Hey,

this issue tracker is only for actual issues. Questions are better suited for the Elixir forum or [Slack](https://elixir-slackin.herokuapp.com/) as more people will see and are able to respond there.
