### ISSUE TITLE
WebSocket transport sets wrong ContentLength header when responding 403

### ISSUE THREAD

**Issue by lukaszsamson** [phoenixframework/phoenix#2675]
When `Phoenix.Socket.connect/2` callback returns `:error` and 403 response is sent to the client it gets wrong Content-Length (or wrong response body `"-"`)
It is rather harmless as clients handle such responses nicely but it results in nginx warnings:
```
10.60.11.39 - - [07/Dec/2017:13:14:23 +0000] "GET /socket/websocket?token=[client token]&vsn=2.0.0 HTTP/1.1" 403 99 "-" "[client user agent]" "[clinet ip]"
2017/12/07 13:14:23 [warn] 13#13: *7305514 upstream sent more data than specified in "Content-Length" header while reading upstream, client: [internal ip], server: [external host], request: "GET /socket/websocket?token=[client token]&vsn=2.0.0 HTTP/1.1", upstream: "http://[internal ip]:[port]/socket/websocket?token=[client token]&vsn=2.0.0", host: "[external host]"
```
[RFC6455](https://tools.ietf.org/html/rfc6455#section-1.3) states:
Any status code other than 101 indicates that the WebSocket handshake has not completed and that the semantics of HTTP still apply. The headers follow the status code.

### Environment

* Phoenix version (mix deps): 1.3
* hosted behind nginx reverse proxy

**Comment by chrismccord** [comment]
Before I deep dive into this, can you try to recreate this without nginx in front? That way we can rule out nginx ws forwarding. Thanks!

**Comment by lukaszsamson** [comment]
Looks like there is something wrong going on. I was able to reproduce the issue without nginx.
Here's the curl output
```
Lukaszs-MacBook-Pro:backoffice lukaszsamson$ curl -v "http://localhost:4000/socket/websocket?token=eyJ&vsn=2.0.0"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4000 (#0)
> GET /socket/websocket?token=eyJ&vsn=2.0.0 HTTP/1.1
> Host: localhost:4000
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< server: Cowboy
< date: Thu, 14 Dec 2017 18:43:00 GMT
< content-length: 0
< cache-control: max-age=0, private, must-revalidate
< 
* Excess found in a non pipelined read: excess = 99 url = /socket/websocket?token=eyJ&vsn=2.0.0 (zero-length body)
* Connection #0 to host api.develop.bitzonk.com left intact
```
But looking on tcpdump I can see that there are two responses written to the socket
one:
```
HTTP/1.1 403 Forbidden
server: Cowboy
date: Thu, 14 Dec 2017 19:17:49 GMT
content-length: 0
cache-control: max-age=0, private, must-revalidate
```
and then
```
HTTP/1.1 204 No Content
server: Cowboy
date: Thu, 14 Dec 2017 19:17:49 GMT
content-length: 0
```

**Comment by josevalim** [comment]
Maybe we are giving the wrong conn/req to Cowboy, which is causing it to send a 204.

**Comment by chrismccord** [comment]
Thanks! I will take a closer look.

**Comment by lukaszsamson** [comment]
I tried to reproduce this issue in cowboy (both 1.1 and 2.2). Cowboy works as expected.

**Comment by lukaszsamson** [comment]
It turned out to be already fixed in https://github.com/phoenixframework/phoenix/pull/2602

**Comment by chrismccord** [comment]
Great! I'll make sure it makes it into the changeling as a bug fix. Thanks!
