### ISSUE TITLE
mix phx.gen.html MyApp is based on the premise that all web apps will use _web suffix

### ISSUE THREAD

**Issue by henry-hz** [phoenixframework/phoenix#2676]
Sometimes we want to give a clean name as: admin , instead of admin_web for our umbrella applications. But if we do so, generators still inject in controllers and views files the _Web suffix. 

### Environment

* Elixir version (elixir -v):  1.5.2
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system: debian

### Expected behavior
mix phx.gen.html MyApp shoud create views and controlers with use Admin, :controller name

### Actual behavior
use AdminWeb, :controller is created, even that the application name is simple Admin (and not AdminWeb)

**Comment by chrismccord** [comment]
Dup of https://github.com/phoenixframework/phoenix/issues/2656 which @alexgaribay is taking a look at soon. Thanks for the report!
