### ISSUE TITLE
Move ownership of phx.sh to the Phoenix Framework and Update the Guides.

### ISSUE THREAD

**Issue by idyll** [phoenixframework/phoenix#2681]
## Motivation

With H2 support right around the corner we will need to be in a position where we can setup TLS for testing locally. While there's been debate around if it's easier to use localhost directly for TLS I believe it is very important to have a dedicated host when you factor in the use of HSTS

Once HSTS is enabled for localhost it is difficult to turn it off, and it will break other things. Like Kube Proxy or your local development environment.

The spec for HSTS does not include any consideration for localhost. https://tools.ietf.org/html/rfc6797#page-28

## Proposal

I have already registered `phx.sh` and it is hosted with DNSimple. 
The following DNS entries are in place:
 - A phx.sh -> 127.0.0.1
 - CNAME *.phx.sh -> phx.sh
 - CNAME *.dev.phx.sh -> phx.sh

which should give developers several options for setting up their development ENV.

A developer could then generate a self-signed certificate for `phx.sh` and use it for testing. This could be included in the project setup script.

I wish to transfer control of `phx.sh` to the Phoenix Framework team. I am willing to pay for domain registration and DNS indefinitely.

## Benefits.

I see the following as benefits to this approach:
 - allows a developer to test HSTS locally without locking localhost.
 - the trust of a locally sign snake-oil cert could be restricted to the phx.sh domain instead of all of localhost.
 - the Phoenix Framework CI could use a real phx.sh cert for testing removing the need to trust a snake-oil cert in tests.
  - Google is going to be breaking `.dev` support in Chrome for anyone still using it. This will work as an alternative.

## Other Considerations.

For offline development a user would need to add an entry for `phx.sh` to `/etc/hosts`.

**Comment by idyll** [comment]
For interest sake, if you actually turn of HSTS for `localhost` in Safari you will need to:
 - delete your full browsing history
 - remove `~/Library/Cookies/HSTS.plist`

in order to open up pages via HTTP again.

**Comment by Gazler** [comment]
Thanks for the proposal. I can't say I've ever had Kube Proxy fail as a result of using a self-signed cert against localhost, but I have lost time debugging HSTS issues, so if it can happen, then we want to avoid it.

I like the idea of using a subdomain when they set up their project. We should perhaps offer a separate mix task for simply generating the certificate - this means we don't have to include the certificates in version control and a use can run `mix phx.cert.generate` after cloning the repo.

There are ways to avoid the warning page for a self-signed certificate that we could allow the user to optionally set:

https://tech.finn.no/2015/09/25/setup-nginx-with-http2-for-local-development/ (see the first comment)

I think we can definitely come up with a low-friction approach to using HTTPS locally.

**Comment by idyll** [comment]
Yeah I think a mix task is in order if we need the SAN instead of the CN for Chrome. (I usually use Safari for development so I forget about that.)

I know there are other places to read up on this on the web but maybe a guide is in order so that the advice is coming from a trustworthy source.

**Comment by LostKobrakai** [comment]
Here's how laravel valet is creating certificates locally (for macs) just issued by `valet secure` in a projects folder: https://github.com/laravel/valet/blob/master/cli/Valet/Site.php#L200-L267

**Comment by voltone** [comment]
Here's something I created a little while ago:
https://gist.github.com/voltone/4d209059c5947d8b73413e05d0e665de

I'd be happy to create a PR to add it (probably without the SKI extension, which has little purpose in a self-signed certificate). I could change it to an ECDSA certificate to remove the dependency on OTP 20, but then we'd have to pick a default curve that is available in all environments, and I don't really have enough data.

**Comment by voltone** [comment]
As for HSTS, we could add a configuration option to Plug.SSL to disable the HSTS response header for a configurable list of hosts. We could set that list to variants of "localhost" in `config/dev.exs` by default.

I believe there is no negative security impact: an attacker could modify the Host header to trick the server into disabling HSTS, but in the context where that would work the attacker has several other options for neutralising HSTS. HSTS is known to be ineffective against an active attacker on the first connection between a client and a server.

/CC @GriffinMB

**Comment by NatTuck** [comment]
Wow.

Turning HSTS on by default for *anything* is a really bad idea. That's a serious ops commitment that's basically unrecoverable if you trick anyone into having it on by mistake.

**Comment by voltone** [comment]
That's why we need to update Plug.SSL to be more dynamic. When you want to enable HSTS on your production domain you need to add Plug.SSL to your pipeline, which currently affects all environments.

So Plug.SSL needs to look at MIX_ENV and/or the requested hostname to decide whether to return the HSTS header. I'm sure people run their app in `MIX_ENV=prod` outside production, e.g. for benchmarking or staging, so MIX_ENV alone is probably not enough.

Hence my proposal: create a configuration parameter for HSTS-enabled domains. The defaults in `config/dev.exs` would prevent the kind of issues people have experienced with `localhost` once they add Plug.SSL to their pipeline. But perhaps the domain list should be a whitelist rather than a blacklist, in which case there is no need for that.

**Comment by voltone** [comment]
Ah, right, so Phoenix can enable Plug.SSL per environment. It tries to prevent HSTS from locking in `localhost` by looking at the configured host, which doesn't prevent accidental activation of HSTS altogether. It might be better to do that at the Plug level by looking at the request hostname.

Let's continue the discussion in elixir-plug/plug#693

**Comment by josevalim** [comment]
Phoenix will depend on Plug v1.6 that won't set HSTS for localhost. Meanwhile, note that Plug.SSL is opt-in and the sample configuration explicitly lists the hsts default. Thanks everyone!
