### ISSUE TITLE
Request Param AND Body handling in ConnTest

### ISSUE THREAD

**Issue by grosscr** [phoenixframework/phoenix#2682]
### Environment

* Elixir version (elixir -v):1.4.2
* Phoenix version (mix deps):1.3

### Request

I would like to request that Phoenix.ConnTest (and [Plug](https://github.com/elixir-plug/plug/blob/master/lib/plug/adapters/test/conn.ex#L96) under the hood) support request body and request params handling in the same request, instead of either/or. We have a use case where the request body is a binary blob and parameters are passed for configuring how the request is handled. With this use case we can't make unit tests for the controller because we can't pass both along at the same time. We have to do separate integration tests or enable the server in the test environment and use an HTTP client to communicate with the application.

**Comment by parihar** [comment]
What are the downsides to returning `query` as the third element of the tuple in `body_or_params(nil, _query, headers)` and `body_or_params(body, _query, headers) when is_binary(body)`?

**Comment by josevalim** [comment]
If you have a body, then you should pass params as the query string, as in a HTTP request:

    post(conn, "/foo?bar=baz", binary_body)

**Comment by grosscr** [comment]
I could swear I had tried that and it hadn't worked. But trying again it appears to work. Thanks!
