### ISSUE TITLE
App.css rolbacks with every mix phx.server command

### ISSUE THREAD

**Issue by dokuzbir** [phoenixframework/phoenix#2683]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 6.11.2
* NPM version (npm -v): 3.10.10
* Operating system: Ubuntu 14.04

### Actual behavior
I cant save permanently app.css. With every phx.server command rollbacks default again. Even i delete it ,it rebuilds again

**Comment by josevalim** [comment]
Please provide more information as it is not clear what issue you are referring to.

Keep in mind that by default Phoenix uses a build tool that outputs files to priv/static. So if you are writing to priv/static/app.css, the build tool will override it. Please pass the --no-brunch flag when creating the new app or move your static files to the assets directory.

**Comment by dokuzbir** [comment]
Thanks got it. It was priv/static/app.css
