### ISSUE TITLE
Pages over a certain length served with H2 hang in Safari (and _just_ Safari)

### ISSUE THREAD

**Issue by idyll** [phoenixframework/phoenix#2686]
If you setup a new Phoenix project from master with H2 support and create a page that's length is over 18000 chars the page will hang when loading in Safari.

The server sends back a 200 OK (at least that is logged) but Safari never displays the data. Chrome works, Firefox works, curl works. It's *just* Safari. And only in production.

The thing that has me perplexed is that the failure *only* happens when the `MIX_ENV=prod`. If you run in dev mode the page loads. It only fails in production mode.

I have created a repo with a project that reproduces this issue.

Grab it here:
   https://github.com/idyll/snowday

If you run the above repo you will see that going to the following two pages will hang Safari:

 - https://snowday.phx.sh/test/one
 - https://snowday.phx.sh/test/two

However going to these two smaller pages works:

 - https://snowday.phx.sh/test/three
 - https://snowday.phx.sh/test/four

And again, it works in dev. To replicate `MIX_ENV=prod mix phx.server`

I have an open radar with Apple but I am not convinced this is 100% on Safari. (This is not a Webkit issue, the Webkit team doesn't handle the H2 part.)

**Comment by idyll** [comment]
@Gazler I could use your thoughts on this. I think it's a Safari bug. And I am trying to get Apple details they need to fix it. But I can't explain why this would work in `dev` mode...

I am suspicious that it may be a Cowboy issue that the other browsers tolerate, but Safari won't.

**Comment by idyll** [comment]
I can also replicate the failure with h2c: github.com/fstab/h2c

Run the project in production mode and then if you install h2c and then run: 

```
h2c start --dump
```

in one shell and 

```
h2c connect https://snowday.phx.sh:4000
h2c get /test/three
h2c get /test/two
```

in another you can see the failure on the second request while the first one works.

See details on h2c in this blogpost:
https://blog.cloudflare.com/tools-for-debugging-testing-and-using-http-2/

**Comment by Gazler** [comment]
If it works in dev, but not in production, then it might be to do with the config. I'd start by removing config values until the production config matches the dev config. If they match exactly and it is still an issue, at least we can rule that out.

The other thing to do is to replicate the bug using Cowboy to see if there is indeed an issue with Cowboy.

**Comment by idyll** [comment]
I've stripped everything out of the prod config at this point. It didn't help.

**Comment by idyll** [comment]
I have tried using a static HTML file served from assets and it works as expected in the production ENV. I don't know what that proves though.

**Comment by idyll** [comment]
I've added a 5th test case that should be the exact content from test 1 but just served as a HEREDOC without templates. The result is that it works for 5 but not for one.

Here is the diagnostic output from H2C. First with 5 (works) then with 1 (fails).

Note that the data streamed for the failing case doesn't even come close to what we should be sending.

```
h2c start --dump
-> SETTINGS(0)
    - ACK
    {empty}

<- SETTINGS(0)
    - ACK
    {empty}

<- SETTINGS(0)
    + ACK
    {empty}

-> SETTINGS(0)
    + ACK
    {empty}

-> HEADERS(1)
    + END_STREAM
    + END_HEADERS
    :method: GET
    :scheme: https
    :authority: snowday.phx.sh:4000
    :path: /test/five

<- HEADERS(1)
    - END_STREAM
    + END_HEADERS
    :status: 200
    cache-control: max-age=0, private, must-revalidate
    content-length: 32049
    content-type: text/html; charset=utf-8
    date: Wed, 20 Dec 2017 18:41:13 GMT
    server: Cowboy
    strict-transport-security: max-age=31536000
    x-content-type-options: nosniff
    x-frame-options: SAMEORIGIN
    x-request-id: 2k119i1234321nlp9o000006
    x-xss-protection: 1; mode=block

<- DATA(1)
    - END_STREAM
    {16384 bytes}

<- DATA(1)
    + END_STREAM
    {15665 bytes}

-> HEADERS(3)
    + END_STREAM
    + END_HEADERS
    :method: GET
    :scheme: https
    :authority: snowday.phx.sh:4000
    :path: /test/one

<- HEADERS(3)
    - END_STREAM
    + END_HEADERS
    :status: 200
    cache-control: max-age=0, private, must-revalidate
    content-length: 30736
    content-type: text/html; charset=utf-8
    date: Wed, 20 Dec 2017 18:41:20 GMT
    server: Cowboy
    strict-transport-security: max-age=31536000
    x-content-type-options: nosniff
    x-frame-options: SAMEORIGIN
    x-request-id: 2k119idpof8i0pdmug000016
    x-xss-protection: 1; mode=block

<- DATA(3)
    - END_STREAM
    {345 bytes}

<- DATA(3)
    - END_STREAM
    {12 bytes}

<- DATA(3)
    - END_STREAM
    {375 bytes}

```

**Comment by idyll** [comment]
I've setup Charles Proxy and have more information that I can share.
The place where Safari hangs is this piece of code:
```
<%= get_flash(@conn, :info) %>
```
If I remove it and the other `<%= get_flash(@conn, :error) %>` then we get a lot further. Safari still hangs, but before it does it receives a full frame of data.

**Comment by hpopp** [comment]
I hacked together a working solution by forcing `Plug.Conn.send_resp/3` to convert any list body to a string before sending to cowboy. I'm guessing EEx renders recursive lists of strings?

I can raise a PR for it. The current behavior really underutilizes http/2 connections. Most DATA frames are 30-50 bytes, whereas cowboy supports ~16kb per frame by default.

**Comment by idyll** [comment]
The list of strings is iodata. I have been looking more at the template. It doesn't need to be `get_flash` to trip things up. `<%= nil %>` will create the error as well, as long as there are 18,000+ chars after in in the template getting rendered into layout.

**Comment by idyll** [comment]
Okay here's where I am @Gazler I have a test that isolates a iodata that hangs Safari:


```
  def test_five(conn, params) do
    fill = """
    <p>
    Ne per causae definitiones, ut veniam vocent cum. Eu torquatos expetendis eam. Volumus delicata neglegentur ne eam. Ut mel ubique facilis fastidii, cum no temporibus adversarium. Mucius scribentur intellegebat quo eu, id luptatum inciderint scribentur nam. Duis propriae in eam, an cum forensibus temporibus. Magna animal necessitatibus et sed, erroribus evertitur an est.
    </p>
    <p>
    Posse ipsum sapientem at pri, eam ut option vocibus. Cu nullam corpora ius, ne stet splendide est. Meliore ponderum nec ea, quo ea suscipit phaedrum. Per wisi elaboraret ut.
    </p>
    <p>
    Agam dicta sensibus quo an, vel ipsum veniam graeco cu. An viris aeterno dolorem est, novum diceret gubergren cum ad. Usu menandri patrioque scripserit te, usu an fugit molestiae. Qui tollit appellantur ut, pri solet aperiam facilis te. Integre electram quo et, persequeris consectetuer ne nam.
    </p>
    <p>
    Ut eam dicunt voluptua principes, dicit perfecto mediocrem ad eam. Te suas integre quo. Nec posse atqui omittantur no, ad sea sumo veritus mandamus. Qui facer viris latine et. Cu tation altera quo, illud oporteat est ne.
    </p>
    <p>
    His in quod noluisse vivendum. Modus etiam alterum et pri. Id quo dolorem indoctum. Elitr signiferumque at cum. Id habeo graeci consetetur qui. Nam ut sumo epicuri.
    </p>
    <p>
    Assentior voluptatum ex eum. Ea est nemore democritum, ei odio iriure accumsan nam, no veniam voluptua perpetua vim. Vim et volumus denique, ad verear argumentum vim. At idque velit cum, quis illum ponderum eos te. Integre labitur disputando et pri. Te atqui legere adipisci has, no eum erant verear appellantur.
    </p>
    <p>
    Quod audire abhorreant in est, pro novum partiendo ei, et quot porro pericula cum. Quaestio interesset scribentur cu nec, usu ei tritani eligendi adipiscing. Mea at antiopam dissentias constituam, an eam illud graece, probo habeo minim eam no. Sit aliquam interesset et.
    </p>
    <p>
    An purto tota equidem his, et nec aliquid splendide, has ut ridens deserunt. Has at omittam appellantur, ei lorem audire gubergren vis. Ei sumo erat comprehensam nam, eam an enim ceteros corpora. Mea ut eirmod eripuit ornatus ceteros.
    <p>
    """

    html conn, [[["" | ""] | ""] |
     fill <> fill <> fill <> fill <> fill <> fill <> fill <> fill <> fill <> fill <> fill <> fill <> fill <> fill <> fill <> fill
    ]
  end
```

Thoughts on how this actually works would be appreciated.

@hpopp I have added this to my code to replace test 5. What do those frames look like?

**Comment by idyll** [comment]
I've created a project that reply with the iodata directly from Cowboy and opened an issue here:
https://github.com/ninenines/cowboy/issues/1247

**Comment by josevalim** [comment]
Hi @idyll, were you able to reproduce this with pure Erlang? This is definitely a blocker on us releasing Phoenix with HTTP 2 support. Thanks!

**Comment by idyll** [comment]
@josevalim I have an example here:
https://github.com/idyll/safari_test_erlang

I have added it to ninenines/cowboy#1247

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by idyll** [comment]
@josevalim Cowboy 2.2.1 just dropped. With a fix for this.

I am trying it out now and will report my findings.

**Comment by josevalim** [comment]
Awesome, thank you for reporting and Loic for working on a fix promptly! :heart:
