### ISSUE TITLE
Customizing Routes via RegEx

### ISSUE THREAD

**Issue by jamilabreu** [phoenixframework/phoenix#2688]
Background conversation with Chris in Google group here:
https://groups.google.com/forum/#!topic/phoenix-talk/1x8CqmXKCGk

### Environment

* Elixir version (elixir -v): 1.5.3
* Phoenix version (mix deps): 1.3.0
* Operating system: OSX

Chis posted sample code related to customizing routes based on a RegEx:
```
defmodule MyApp.Router do

  scope "/", MyApp do
    get "/:id", SlugRouter, :show
    get "/:id", OtherController, :show
  end
end

defmodule MyApp.SlugRouter do
  import Plug.Conn

  def init(opts), do: opts

  def call(%Plug.Conn{params: %{"id" => id}} = conn, action) do
    cond do
      Regex.match?(~r/^\d{5}$/, id) ->
        SomeController.call(conn, SomeController.init(action))
      Regex.match?(~r/^A\d{4}$/, id) ->
        OtherController.call(conn, OtherController.init(action))
      true -> conn
    end
  end
end
```
### Expected behavior
I expect `get "/:id", OtherController, :show` to catch any routes not handled by `get "/:id", SlugRouter, :show`.

### Actual behavior
In Phoenix 1.3 there seems to be an error related to the `true -> conn` part above. 

I'm getting `** (Plug.Conn.NotSentError) a response was neither set nor sent from the connection` on the route, and `unused import Plug.Conn` in the console.

It works when adding another direct call: `true -> SomeOtherController.call(conn, SomeOtherController.init(action))` but not with just `true -> conn`

Here's a repo where I recreate what I'm seeing: 

https://github.com/jamilabreu/regex_routing
[Link to router.ex file](https://github.com/jamilabreu/regex_routing/blob/master/lib/regex_routing_web/router.ex)

**Comment by josevalim** [comment]
After we dispatch a router, we don't go back to the router to try again - doing so would actually be a break change, as controllers and plugs invoked by the router are not required to halt. You will have to manually dispatch to your OtherController from your SlugRouter.
