### ISSUE TITLE
`mix phx.server --no-deps-check` still checks dependencies

### ISSUE THREAD

**Issue by jonathanperret** [phoenixframework/phoenix#2690]
### Environment

* Elixir version (elixir -v): 1.5.3
* Phoenix version (mix deps): 1.3.0
* Operating system: macOS 10.12.6

### Expected behavior

Create a new Phoenix app:

```
$ mix phx.new my_app
…
Fetch and install dependencies? [Yn] Y
…
$ cd my_app
```

Nuke one of the dependencies:

```
$ rm -rf deps/poison
```

Start the app with `--no-deps-check`, as mentioned in the doc for `mix phx.server`:

```
$ mix phx.server --no-deps-check
```

The app should start (and eventually fail when it tries to use the broken dependency).

### Actual behavior

Mix refuses to start the app, as if `--no-deps-check` had not been specified:

```
$ mix phx.server --no-deps-check
Unchecked dependencies for environment dev:
* poison (Hex package)
  the dependency is not available, run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies
```

It appears Mix automatically invokes the `deps.loadpaths` task, but without passing on the arguments:

```
$ MIX_DEBUG=1 mix phx.server --no-deps-check
** Running mix loadconfig (inside Hellophoenix145.Mixfile)
** Running mix phx.server --no-deps-check (inside Hellophoenix145.Mixfile)
** Running mix deps.loadpaths (inside Hellophoenix145.Mixfile)
Unchecked dependencies for environment dev:
* poison (Hex package)
  the dependency is not available, run "mix deps.get"
** (Mix.Error) Can't continue due to errors on dependencies
    (mix) lib/mix.ex:291: Mix.raise/1
    (mix) lib/mix/tasks/deps.loadpaths.ex:26: Mix.Tasks.Deps.Loadpaths.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:324: Mix.Task.get_task_or_run/3
    (mix) lib/mix/task.ex:283: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
```

As it turns out, Mix needs to do `deps.loadpaths` for the task `phx.server` to even be available, so it looks like by the time execution reaches `Mix.Tasks.Phoenix.Server#run`, it is too late to disable the dependency check. A workaround is to explicitly invoke `deps.loadpaths` before `phx.server`:

```
$ mix do deps.loadpaths --no-deps-check, phx.server
[info] Running Hellophoenix145Web.Endpoint with Cowboy using http://0.0.0.0:4000
```

I don't know if there is a way to make `phx.server --no-deps-check` work as expected, but I think at least it should not be the example given in the documentation given (unless I'm missing something) it does not have the desired effect.

**Comment by josevalim** [comment]
I am not sure if there is a fix we could apply here, unfortunately. Manually loading the deps before seems like the way to go.

**Comment by jonathanperret** [comment]
How about just changing the docs to illustrate `mix phx.server` with an argument other than `-- no-deps-check`? For example, `mix phx.server --no-compile` seems to work as expected.

**Comment by josevalim** [comment]
@jonathanperret that would be perfect, the command you pasted in the issue is exactly the way to go. PR please?

**Comment by jonathanperret** [comment]
Sure, give me a couple days.
