### ISSUE TITLE
Investigate using Jason instead of Poison

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2693]
This will also require changing phoenix_ecto / ecto.

**Comment by wilbertom** [comment]
What can of investigation needs to be done for this? Is it:

* How much effort it would be
* Seeing if there is a performance boost
* Something else?

**Comment by chrismccord** [comment]
It won't be a large effort. The only thing to evaluate is the readiness of Jason stability and prod ready wise.

**Comment by michalmuskala** [comment]
The biggest difference of Jason vs Poison is that Jason does not allow encoding arbitrary structs - it always requires either implementing or deriving the protocol. This would mean the change wouldn't be completely seamless - fortunately, deriving the protocol is just one line `Protocol.derive(Jason.Encoder, MyStruct)`.

**Comment by michalmuskala** [comment]
Just an FYI, I've released version 1.0.

**Comment by chrismccord** [comment]
@josevalim this is taken care of in #2734 , and `phoenix_ecto` no longer depends or implements any Poison protocol so we are good there. What needs done on Ecto's side to make this complete?

**Comment by mpranjic** [comment]
Can someone explain what are the benefits of using Jason instead of Poison?

**Comment by michalmuskala** [comment]
The primary reason is performance. Jason is about twice as fast and uses half the memory while being almost 100% functionally compatible with Poison.

**Comment by javierg** [comment]
Will this be released to 1.3?

**Comment by beardedeagle** [comment]
@javierg if you look at Jason's readme, instructions are provided for use with phoenix 1.3:
https://github.com/michalmuskala/jason/blob/master/README.md

**Comment by peterwillcn** [comment]
To fix the issue I had to add:

{:poison, "~> 3.1"}
to my deps in mix.exs
