### ISSUE TITLE
`mix help` shows both `phx.gen.html` and `phoenix.gen.html`

### ISSUE THREAD

**Issue by westoque** [phoenixframework/phoenix#2694]
### Environment

* Elixir version (elixir -v): `Elixir 1.5.3`
* Phoenix version (mix deps): `1.3.0`
* NodeJS version (node -v): `v8.9.1`
* NPM version (npm -v): `5.6.0`
* Operating system: Mac OSX

### Expected behavior

`mix help` should only show `phx.gen.html`.

We could also just deprecate `phoenix.gen.html` and call `phx.gen.html` internally.

### Actual behavior

`mix help` shows both `phoenix.gen.html` and `phx.gen.html` and they both do different things. the former creates the files in `web/` and the latter in `lib/`

**Comment by josevalim** [comment]
phoenix.gen.html no longer exists in master, so this problem will be addressed when v1.4 is out. :)

**Comment by westoque** [comment]
thanks @josevalim ❤️
