### ISSUE TITLE
Accept header handling phoenix 1.3

### ISSUE THREAD

**Issue by nulian** [phoenixframework/phoenix#2696]
While upgrading from phoenix 1.2 -> 1.3 our 404 page started to return as html instead of json.

Found out that is because of Accept header handling of phoenix 1.3.

In phoenix 1.2 ```Accept: application/json, */*``` is returned as json.
But in phoenix 1.3 it is returned as html if you remove the ```*/*``` in 1.3 it will return json again.

That seems to me a breaking change in how phoenix handles accept headers.
Anyway to force phoenix 1.3 returning 404 error in json again.

**Comment by josevalim** [comment]
It doesn't seem that the behaviour changed between releases:

* v1.2: https://github.com/phoenixframework/phoenix/blob/v1.2/lib/phoenix/controller.ex#L899-L914

* v1.3: https://github.com/phoenixframework/phoenix/blob/v1.3/lib/phoenix/controller.ex#L1078-L1093

**Comment by josevalim** [comment]
Both versions also document the html behaviour, [explained here in the v1.2 branch](https://github.com/phoenixframework/phoenix/blob/v1.2/lib/phoenix/controller.ex#L830-L841).

It is worth noting that returning HTML is also valid per the spec. If you don't want HTML to be returned, then :html should not be in your list of accepts. You can have separate pipelines in your router for html and json.

**Comment by nulian** [comment]
Hmm weird that if I use the basic generated app with a simple endpoint and throw an 404 error there is a functionality change with that when I downgrade to phoenix 1.2 just like in our application.

The pipeline already has accepts ["json"] only difference is the 404 that reacts differently I know you can set error view in config globally with your app to accept json html but not sure how I can differentiate that between pipelines.

**Comment by josevalim** [comment]
If it only happens in your app then we would need a way to reproduce the error to really understand what is happening.

**Comment by nulian** [comment]
I mean is also happens in a newly generated app with a mix phx.gen.json Accounts User users name:string.
When I have a router like this.

```
defmodule MyAppWeb.Router do
  use MyAppWeb, :router

  defmodule NoRouteError do
    @moduledoc """
    Exception raised when no route is found.
    """
    defexception plug_status: 404, message: "no route found", conn: nil, router: nil
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", MyAppWeb do
    pipe_through :api

    resources "/users", UserController, only: [:index]
  end
end
```

And a UserController like this

```
defmodule MyAppWeb.UserController do
  use MyAppWeb, :controller

  alias MyApp.Accounts
  alias MyApp.Accounts.User

  def index(conn, _params) do
    raise MyAppWeb.Router.NoRouteError, "No record found"
    render(conn, "index.json", users: %{test: "hallo"})
  end

end
```

In the config I added html to error view

```
# This file is responsible for configuring your application
# and its dependencies with the aid of the Mix.Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.
use Mix.Config

# General application configuration
config :my_app,
  ecto_repos: [MyApp.Repo]

# Configures the endpoint
config :my_app, MyAppWeb.Endpoint,
  url: [host: "localhost"],
  secret_key_base: "OQ2kFJQyz1S+K2JqFL0CTAmyu90WVpbH7tjvGJkuuV6ep1CDqnDWTK+nkKiR7C8F",
  render_errors: [view: MyAppWeb.ErrorView, accepts: ~w(json html)],
  pubsub: [name: MyApp.PubSub,
           adapter: Phoenix.PubSub.PG2]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{Mix.env}.exs"
```

And then do ```curl http://localhost:4000/api/users -H "Accept: application/json, */*"```

When I use phoenix 1.3 I get an error because no html error view exists yet else it would be the html view.
If I use phoenix 1.2 I get ```{"errors":{"detail":"Page not found"}}```

**Comment by josevalim** [comment]
Thanks, that helps a lot. Although I still can't quite see why the behaviour changed between releases. We will have to investigate and may be change the current behaviour to only happen if the first entry is html.

**Comment by josevalim** [comment]
Can you please push this tiny app to github to make sure we are working on the same code base?

**Comment by nulian** [comment]
https://github.com/nulian/simpel_app

With master phoenix1.3 and phoenix1.2 branch

Different responses between using ```curl http://localhost:4000/api/users -H "Accept: application/json, */*"``` on both branches
