### ISSUE TITLE
Tests error with json generator and naive_datetime

### ISSUE THREAD

**Issue by shouston3** [phoenixframework/phoenix#2700]
### Environment

* Elixir version (elixir -v): 1.4.1
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 7.4.0
* NPM version (npm -v): 5.6.0
* Operating system: macOS

I run the following commands:

```bash
mix phx.new date_bug && cd date_bug && mix ecto.create
mix phx.gen.json X Y z date:naive_datetime
# edit the `router.ex` file appropriately, following:
# Add the resource to your :api scope in lib/date_bug_web/router.ex:
#
#    resources "/z", YController, except: [:new, :edit]
mix ecto.migrate
```

### Expected behaviour
mix test # to not error

### Actual behavior
mix test # errors

See the error on travis here: https://travis-ci.org/shouston3/date_bug/jobs/324551671#L609

Sorry if I've made any mistakes with raising this issue.
Thanks for all your amazing work @chrismccord @josevalim

**Comment by chrismccord** [comment]
Are you using mysql by chance? This sounds like a dup of #2272 and #2152 . Let me know and I will take a look. Thanks!

**Comment by shouston3** [comment]
I'm using postgres v9.4
I don't think it's a duplicate of those issues.

Note: the issue doesn't occur when running the same commands with `mix phx.gen.html`

**Comment by chrismccord** [comment]
Confirmed fixed in https://github.com/phoenixframework/phoenix/commit/1ae3b9a5ab0e1508e00a1a32e28fcd000e521a43

Thanks for the report!
