### ISSUE TITLE
Deprecation warning when old version of cowlib compiles

### ISSUE THREAD

**Issue by jacobherrington** [phoenixframework/phoenix#2701]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 6.11.3
* NPM version (npm -v): 5.6.0
* Operating system: Mac OS Sierra 10.12.6 

### Expected behavior

No warning when cowlib compiles?

### Actual behavior

```
$ mix deps.compile
...
===> Compiling cowlib
src/cow_multipart.erl:392: Warning: call to crypto:rand_bytes/1 will fail, 
since it was removed in 20.0; use crypto:strong_rand_bytes/1
```

I'm new to Phoenix and Elixir/Erlang in general, so I'm not sure if this has been around for awhile, but I found nothing on Google. Based on [this issue](https://github.com/ninenines/cowlib/issues/51), it seems that this warning would not appear if Phoenix used a newer version of cowlib. 

If this isn't just user error, I'd be happy to work on this with someone who is more familiar with Phoenix.

**Comment by josevalim** [comment]
Phoenix master already supports Cowboy 2, which allows more recent cowlib versions. Note this warning is not an issue though, it is used only for http clients and not servers.

Thanks for opening the issue and have fun!
