### ISSUE TITLE
Using Supervisor.Spec, deprecated in Elixir 1.5

### ISSUE THREAD

**Issue by wilbertom** [phoenixframework/phoenix#2702]
When creating a new project using `mix phx.new`, for example `mix phx.new hello`, the resulting `lib/hello/application.ex` file uses the `Supervisor.Spec` module. This module was deprecated in Elixir `1.5`. 

### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): v9.3.0
* NPM version (npm -v):5.5.1
* Operating system: Debian jessie

**Comment by josevalim** [comment]
The module was soft-deprecated in Elixir v1.5, which means we can use it up to Elixir v1.7 without warnings. If we remove it, we would only support Elixir v1.5, and it is a bit too soon to enforce that. We will keep an eye on it though, thanks!

**Comment by wilbertom** [comment]
I see, thanks @josevalim! Sorry, just getting started with Elixir, should have double checked how deprecations work in Elxir.

**Comment by josevalim** [comment]
No worries at all and have fun!
