### ISSUE TITLE
Unable to reply asynchronously to a socket push with just an atom status

### ISSUE THREAD

**Issue by van-mronov** [phoenixframework/phoenix#2704]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* Operating system: macOS

### Expected behavior
`Phoenix.Channel.reply/2` replies with an empty payload in case of the second argument is an atom (represented status).

### Actual behavior
According to the documentation for `Phoenix.Channel.reply/2` the type of the second argument is an atom or a tuple: `@type reply :: status :: atom | {status :: atom, response :: map}`.
But it supports only tuple as reply now and fails if pass an atom:
`(FunctionClauseError) no function clause matching in Phoenix.Channel.reply/2`

### Possible solutions
Reply with an empty payload like `handle_in` callbacks.

**Comment by josevalim** [comment]
Can you please provide the code you are trying out as well as the full message with stacktrace?

**Comment by josevalim** [comment]
Nevermind, I just saw the PR. ;)
