### ISSUE TITLE
`phx.new` generates the wrong directories when `--module` is provided

### ISSUE THREAD

**Issue by lucasmazza** [phoenixframework/phoenix#2707]
When generating a new app, the given app name is used for the directories inside `lib`, like:

```
$ mix phx.new foobar
$ tree foobar/lib/ -L 1
foobar/lib/
├── foobar
├── foobar.ex
├── foobar_web
└── foobar_web.ex

2 directories, 2 files
```

But when `--module` is used, the directories inside `lib` are named after the main argument and not `--module`:

```
$ mix phx.new foobar --module MyApp
$ tree foobar/lib/ -L 1
foobar/lib/
├── foobar
├── foobar.ex
├── foobar_web
└── foobar_web.ex

2 directories, 2 files
```

In the above scenario one would expect to have `foobar/lib/my_app` and `foobar/lib/my_app_web` instead of `foobar/lib/foobar` and `foobar/lib/foobar_web`.

### Environment

* Elixir 1.5.3
* Phoenix 1.3.0
* macOS 10.13.2

**Comment by chrismccord** [comment]
This is by design. You can customize the file and directory names by also providing the `--app` argument. The `--module` option only relates to the generated module name. Thanks!

**Comment by lucasmazza** [comment]
@chrismccord thanks for explaining that, we might have jumped too quickly over the docs.
