### ISSUE TITLE
warnings during 'npm install'

### ISSUE THREAD

**Issue by ebengt** [phoenixframework/phoenix#2710]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 19 [erts-8.2] [source-fbd2db2] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Elixir 1.5.3

* Phoenix version (mix deps):
* file_system 0.2.4 (Hex package) (mix)
  locked at 0.2.4 (file_system) f0bdda19
  ok
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* gettext 0.14.0 (Hex package) (mix)
  locked at 0.14.0 (gettext) 1a019a2e
  ok
* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poolboy 1.5.1 (Hex package) (rebar3)
  locked at 1.5.1 (poolboy) 6b461639
  ok
* decimal 1.4.1 (Hex package) (mix)
  locked at 1.4.1 (decimal) ad9e501e
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) d9eb6366
  ok
* db_connection 1.1.3 (Hex package) (mix)
  locked at 1.1.3 (db_connection) 89b30ca1
  ok
* phoenix_pubsub 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (phoenix_pubsub) bfa7fd52
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* mime 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (mime) 78adaa84
  ok
* plug 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (plug) 236d77ce
  ok
* phoenix_html 2.10.5 (Hex package) (mix)
  locked at 2.10.5 (phoenix_html) 4f9df6b0
  ok
* phoenix 1.3.0 (Hex package) (mix)
  locked at 1.3.0 (phoenix) 1c01124c
  ok
* phoenix_live_reload 1.1.3 (Hex package) (mix)
  locked at 1.1.3 (phoenix_live_reload) 1d178429
  ok
* postgrex 0.13.3 (Hex package) (mix)
  locked at 0.13.3 (postgrex) c277cfb2
  ok
* ecto 2.2.8 (Hex package) (mix)
  locked at 2.2.8 (ecto) a4463c09
  ok
* phoenix_ecto 3.3.0 (Hex package) (mix)
  locked at 3.3.0 (phoenix_ecto) 702f6e16
  ok

* NodeJS version (node -v):
v8.9.4

* NPM version (npm -v):
5.6.0

* Operating system:
Darwin Mac-Mini.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
### Expected behavior
No warnings during 'npm install' in subdirectory 'assets'.

### Actual behavior
During installation/creation of Phoenix directory I do:
1) mix phx.new adir
2) cd adir
3) mix deps.get
4) cd assets 
5) npm install

npm WARN deprecated babel-preset-latest@6.24.1: We're super 😸  excited that you're trying to use ES2017+ syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN deprecated coffee-script@1.11.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated babel-preset-es2016@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated babel-preset-es2017@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

**Comment by chrismccord** [comment]
Thanks for the report! I don't get these warnings so I'm not sure why your babel would be warning. In this case, this particular dependency is a child dep of a deeper dependency, maybe babel-brunch, but I'll need to go digging first. Since our js builds have been historically finicky for users, I don't want to bump dep versions just yet. Fortunately the warnings on your side are harmless and your project js should build just fine in the meantime.
