### ISSUE TITLE
Channel.terminate/2 specification

### ISSUE THREAD

**Issue by Virviil** [phoenixframework/phoenix#2711]
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/channel.ex#L290

This callback has wrong specification. Right specification seems to be:
```
@callback terminate(reason :: {:shutdown, :left | :closed}, Socket.t) ::
              {:shutdown, :left | :closed} |
              term
```

This causes Dialyzer to warn about wrong specification.

**Comment by chrismccord** [comment]
Good catch! Can you send a PR? Thanks!
