### ISSUE TITLE
mix.new puts `web` in project root

### ISSUE THREAD

**Issue by formido** [phoenixframework/phoenix#2715]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 7.9.0
* NPM version (npm -v): 4.2
* Operating system: Ubuntu

### Expected behavior

When running `mix phoenix.new test --no-brunch --no-html --no-ecto` the `web` directory is placed in `lib` like when I run `mix phoenix.new test`.

### Actual behavior

`web` is placed in project root.

**Comment by chrismccord** [comment]
Can you include the exact commands you can along with the directory tree? Note: the new generators use the `phx` prefix, ie `mix phx.new`. The `phoenix.*` tasks are deprecated. Perhaps you are seeing the new `lib/test_web` directory that the `phx.new` generator correctly generates?

**Comment by formido** [comment]
You're right. From my `history`:

```
 2087  mix phoenix.new hours_board --no-brunch --no-html --no-ecto
 2088  cd hours_board/
```
...irrelevant lines...
```
 2094  ls
 2095  ls lib
 2096  ls lib/hours_board
```
*!? I know I haven't used Phoenix, but I could have sworn I'd run across some discussion on Hacker News or something about `web` being moved into `lib`...*
```
 2098  cd /tmp
 2099  mix phx.new test
 2100  cd test
 2101  ls
 2102  ls lib
```
I must have have been referencing a couple different guides.
