### ISSUE TITLE
Raise on unknown :only and :except options in resources

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2723]
Otherwise you may try to select or skip an action that does not exist and it can be quite puzzling why it doesn't work.

See original discussion here: https://stackoverflow.com/questions/48358986/cant-create-a-nested-resource-in-phoenix/48361577#48361577

**Comment by starbelly** [comment]
Ping, can take this one.

**Comment by josevalim** [comment]
Please go ahead!

**Comment by chrismccord** [comment]
Sorry @starbelly , I took care of this on my flight and didn't have a chance to chime in here. Closed in https://github.com/phoenixframework/phoenix/commit/54a5b691430dbfc9cf882351dcb8c02ef9797a29 Thanks!

**Comment by starbelly** [comment]
@chrismccord n/p! Skating rink! 👍
