### ISSUE TITLE
H2 content from pages served with Cowboy 2.2.1 is rendered out of order.

### ISSUE THREAD

**Issue by idyll** [phoenixframework/phoenix#2725]
With the Cowboy 2.2.1 update I have been testing several applications and noticed that content is being presented out of order in Chrome and Safari.

A portion of the body content is being rendered before the initial HTML tag. Portions of the content are also missing.

I have am trouble reproducing the issue with a sample that I can provide to debug but I have opened an issue on Cowboy so that we can track it here:

   https://github.com/ninenines/cowboy/issues/1258

**Comment by idyll** [comment]
Head's up @josevalim - we are going to need to get this fixed as well before release...

**Comment by idyll** [comment]
Okay 2.2.2 has been tagged and I have tested it, even using a couple applications. It works. We're good.

**Comment by josevalim** [comment]
Awesome, thanks for all the testing!

**Comment by idyll** [comment]
Someone still needs to push 2.2.2 to hex...

**Comment by josevalim** [comment]
Oh, I believe @gazler pushed the last ones. Ping @gazler!

**Comment by Gazler** [comment]
Done!

https://hex.pm/packages/cowboy/2.2.2
