### ISSUE TITLE
Incorrect JavaScript in Static Assets Guide 

### ISSUE THREAD

**Issue by jayjun** [phoenixframework/phoenix#2726]
In [this](http://phoenixframework.org/blog/static-assets) guide,
```html
<script>require("assets/static/js/app").App.run()</script>
```
doesn’t work. Only
```html
<script>require("js/app").App.run()</script>
```
does.

**Comment by chrismccord** [comment]
Can you send a PR? Thanks!

**Comment by jayjun** [comment]
Sorry, I realised the guide is part of the Phoenix blog? http://phoenixframework.org/blog/static-assets

Either way, the article is not in this repo.

**Comment by Gazler** [comment]
@jayjun You can change it in this repo https://github.com/phoenixframework/phoenix_site/blob/master/posts/blog--static-assets.markdown

**Comment by jayjun** [comment]
Thanks @Gazler. Pull request submitted https://github.com/phoenixframework/phoenix_site/pull/23.

**Comment by Gazler** [comment]
Closing in favour of PR. Thanks @jayjun
