### ISSUE TITLE
Unable to load jquery using npm as per the documentation

### ISSUE THREAD

**Issue by arcseldon** [phoenixframework/phoenix#2728]
Please see [detailed explanation on SOF here](https://stackoverflow.com/questions/48485090/how-to-add-jquery-to-phoenix-1-3-using-npm)

Workaround of copying the `jquery.min.js` file into `assets/vendor` folder does work.

**Comment by chrismccord** [comment]
This is a brunch related question and something better suited to the js community and brunch for folks to point you in the right direction. Fwiw, I tend to vendor my js deps in /assets/js/vendor . They will be concatenated above your app bundle in app.js and available on the global scope.
