### ISSUE TITLE
Cannot find module 'phoenix' from 'js/socket.js'

### ISSUE THREAD

**Issue by Merff** [phoenixframework/phoenix#2735]
Hi! Sometimes (not always) I get an error when working with channels: ` Cannot find module 'phoenix' from 'js/socket.js'.`
I have a standard configuration socket.js
Restarting the server helps for a while.

### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 9.3.0
* NPM version (npm -v): 5.5.1
* Operating system: Ubuntu 16.04

brunch and package files:
[js-files.tar.gz](https://github.com/phoenixframework/phoenix/files/1676298/js-files.tar.gz)

Thanks!

**Comment by chrismccord** [comment]
Is your current setup working for you? If this is only on occasion it's not going to be possible for us to reproduce easily. When this happens, does your app bundle compile successfully? Is it possible you see then when you get a broken js build? Thanks!

**Comment by Merff** [comment]
Thanks. I try to get more info.

**Comment by chrismccord** [comment]
Please let us know if you're able to provide more information about the issue and we'll try to point you in the right direction. Thanks!

**Comment by denispeplin** [comment]
Elixir 1.7.2
Phoenix 1.3.4
Node 8.12.0
Npm 6.4.1
Ubuntu 16.04

Everything worked, then error appeared after I changed `socket.js`, and didn't disappeared after server restart and page reload. Fixed the issue with stopping the server, running `npm install`, starting server again and reloading the page.
