### ISSUE TITLE
Errored channels on socket disconnect

### ISSUE THREAD

**Issue by thiagogsr** [phoenixframework/phoenix#2736]
I’m broadcasting `disconnect` on my user socket and it is closing as well but the channels don't. Them state are `errored`, so it is rejoined seconds later.

It is my debug on browser console:

```javascript
window.socket.channels.map(channel => `${channel.topic} -> ${channel.state}`) // on connect, it is ok
["gamification:100 -> joined"]
window.socket.channels.map(channel => `${channel.topic} -> ${channel.state}`) // on `disconnect` broadcast
["gamification:100 -> errored"]
window.socket.channels.map(channel => `${channel.topic} -> ${channel.state}`) // seconds later everything is reconnected
["gamification:100 -> joined"]
```

I’m broadcasting with:
```elixir
MyAppWeb.Endpoint.broadcast("user_socket:#{user_id}", "disconnect", %{})
```

The doc says:
https://github.com/phoenixframework/phoenix/blob/e7d87a38a691dbe8fbbc614cbe1e3857d21d3962/lib/phoenix/socket.ex#L109-L112

### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.3.0
* NodeJS version (node -v): 9.3.0
* NPM version (npm -v): 5.6.0
* Operating system: OSX 10.13.2

### Expected behavior
Closed channels to avoid this rejoin: https://github.com/phoenixframework/phoenix/blob/83603fb6577818f48e6fd41c673d3ca3a4880046/assets/js/phoenix.js#L384-L388

### Actual behavior
Errored channels

**Comment by chrismccord** [comment]
This is by design as broadcasting "disconnect" is a forceful exit and not a graceful shutdown. If the goal is to perm-ban users, when they try to reconnect you will refuse them in UserSocket.connect to close the loop.

**Comment by thiagogsr** [comment]
The user token to connect on socket is the same, so they will able to reconnect. Is there a way to do a graceful shutdown on phoenix? I saw some solutions broadcasting a message to a channel and removing the socket assign but I don't like this solution because I have many channels for the same socket, I don't want choose a randomly channel to do this.

**Comment by chrismccord** [comment]
If you are perm banning users you necessarily have to handle the token issue. For example even if we allowed graceful shutdown, the user could just refresh the page or trigger a reconnect in the console with the same token. Part of your UserSocket.connect authentication needs to check that the user's account status. So you need to verify token => lookup user => verify active status. Make sense?

**Comment by thiagogsr** [comment]
Thanks your attention. It is not a perm banning, just a logout. For now I'm leaving all channels then disconnecting the socket on JS, we would like some solution for this on backend since we don't have the session state on database. Is there a good practice to change these tokens by user session?

**Comment by chrismccord** [comment]
You need a mechanism to invalidate tokens which will require you to store some state on the backend. There's really no way around that. The easiest way would be to store a counter for the user that you bump on login/logout which is included in the user's token salt. This will invalidate tokens while avoiding storing the session in the DB.

**Comment by thiagogsr** [comment]
Thank you @chrismccord, really appreciate your attention.
