### ISSUE TITLE
Changing name of AppWeb to Web causes breaking changes

### ISSUE THREAD

**Issue by justuseapen** [phoenixframework/phoenix#2743]
### Environment

* Elixir version (elixir -v): Elixir 1.5.2
* Phoenix version (mix deps): Phoenix 1.3.0
* NodeJS version (node -v): v8.7.0
* NPM version (npm -v): 5.6.0
* Operating system: osx 10.13.2

### Expected behavior
Upon renaming the directory `app_web` to `web`, I would expect generators to automagically or through some basic configuration use the new directory for views/templates/controllers. 

### Actual behavior
The generator makes all the web modules inside a new directory called `app_web`. This is inconvenient.

I see the `web_path` is set insde the `Mix.Phoenix` module. I can hardcode a solution for myself in my phoenix dep installation, but that's not an ideal long term solution especially since myself and at least one other developer I'm aware of prefer the `Web` naming convention over the `AppWeb` naming convention.

Maybe this is a feature request? Maybe it's a simple configuration issue? Maybe I'm missing something? Please advise.

**Comment by josevalim** [comment]
Yes, if you rename the structure, then generators will no longer work. This is the same if you rename the directory "controllers", "views" or any other to something else. We don't think adding more configuration to the code will be worth it here.
