### ISSUE TITLE
Move javascript files at the root to the assets directory

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#2747]
Let's mirror the structure in the Phoenix itself after applications.

**Comment by chrismccord** [comment]
We can move brunch-config.js, but package.json will need to stay given our file based npm dep setup for existing applications. I think we can also move .babelrc, but who really knows?!

**Comment by josevalim** [comment]
Good point. Not worth the trouble to move one file around. We can see if we can get rid of .babelrc later.
