### ISSUE TITLE
`Phoenix.Channel.reply/2` doesn't accept just status.

### ISSUE THREAD

**Issue by blatyo** [phoenixframework/phoenix#2749]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.0 (compiled with OTP 20)

* Phoenix version (mix deps): phoenix 1.3.0
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system:

### Expected behavior

[Phoenix.Channel.reply/2](https://hexdocs.pm/phoenix/Phoenix.Channel.html#reply/2) accepts a [reply](https://hexdocs.pm/phoenix/Phoenix.Channel.html#t:reply/0) as the second argument, which includes a status like `:ok`.

### Actual behavior

[Phoenix.Channel.reply/2](https://hexdocs.pm/phoenix/Phoenix.Channel.html#reply/2) requires a status response tuple. For example, `{:ok, nil}`. See the code [here](https://github.com/phoenixframework/phoenix/blob/v1.3.0/lib/phoenix/channel.ex#L476), that has the issue.

**Comment by chrismccord** [comment]
This was fixed in https://github.com/phoenixframework/phoenix/commit/71f06558bc542cb0800686e4f3175d69f835d358#diff-cfa0128824823c13a720654d72db9564 and will be in the next release. Thanks!
