### ISSUE TITLE
Allow silencing Phoenix.Token warning

### ISSUE THREAD

**Issue by michalmuskala** [phoenixframework/phoenix#2755]
### Environment

* Elixir version (elixir -v): 1.7.0-dev (c42df09f3)
* Phoenix version (mix deps): 1.3.0

### Expected behavior

We're stuck for some time having to support tokens issued with `Phoenix.Token` with an infinite expiration timeout. I understand the reasoning behind the warning in [`Phoenix.Token.verify/4`](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/token.ex#L179) perfectly, it's unfortunately very annoying when I can't do much about it.

It would be great, if there was a way to silence the warning - I propose passing `max_age: :infinity` as an explicit way to opt-out from the token age checking. This should be the least disruptive and should make sure that the person using it understands the trade-offs.

### Actual behavior

We're spammed with the warnings, since they are issued at runtime.

**Comment by josevalim** [comment]
@michalmuskala please do send a PR so we handle `:infinity`. It is a great way to handle this more explicitly.
