### ISSUE TITLE
get remote_ip from socket

### ISSUE THREAD

**Issue by raarts** [phoenixframework/phoenix#2758]
### Environment

all versions

### Expected behavior

I want to be able to find the remote ip address when I'm in a Phoenix.Socket

### Actual behavior

It's not available.

I have searched for discussions on this, but very little turned up. I understand sockets are transport independent, but all mentioned transports have a remote ip address anyway. My use case: it would be useful for correlating log messages for  absinthe clients. We use a standardized log format, and now in the socket messages we put in a literal 'remote_ip' instead of the actual ip address.

**Comment by josevalim** [comment]
I agree. Although if we support this we should add general support for remote_ip rewriting based on proxies to Phoenix.

**Comment by chrismccord** [comment]
I have considered a `socket.meta` of sorts that the transport could populate vs having a static `remote_ip` field on the socket. Alternatively since the vast majority of transports would have an IP, we could default the value to something like `:unset` could work. Thoughts?

**Comment by chrismccord** [comment]
As José alluded to, the other issues here are any plugs in the endpoint for remote_ip rewriting won't take effect, so it's not as simple as it seems to support

**Comment by scrogson** [comment]
Couldn't we plug something above the `socket` macro call in the endpoint to rewrite the `remote_ip`? Then the socket handler could just use the `remote_ip` field in the `conn`?

**Comment by chrismccord** [comment]
We intercept the socket mounts before the plug pipeline so that wouldn't apply

**Comment by scrogson** [comment]
Ah, right.

**Comment by raarts** [comment]
It's a crazy idea, but would it be possible to write a plug that intercepts socket mounts, and continues as a socket? Authentication, and things like remote_ip might be easier that way. 
Just shoot me down, I admit I am clueless here.

**Comment by chrismccord** [comment]
We can't do that from a WebSocket upgrade point of view as we are in the upgrade request and can only send specific responses without a body. Also from a security perspective we can't use the session cookies for authentication because of CSWHJ – http://www.christian-schneider.net/CrossSiteWebSocketHijacking.html

**Comment by josevalim** [comment]
Related to #2889 and #2771.

**Comment by rmoorman** [comment]
Couldn't the part where endpoint and transport/sockets are glued together be done as a plug? Why is the socket mount intercepted before the plug pipeline?

If we would want to make sure that only specific responses are sent and no cookies are used, wouldn't that also be achievable within the plug.

Having it as part of the plug pipeline could be part of the puzzle in order to solve some issues around forwarding information to the socket and guarding sockets in general (e.g. rate limiting, authorization).

**Comment by josevalim** [comment]
In master with #2889.

**Comment by josevalim** [comment]
Actually, the remote ip is not available yet. But we do have the foundation in case somebody wants to add it.

**Comment by rmoorman** [comment]
It would be great to have the remote_ip field in there as well. But the plug documentation states that "(...) remote_ip - the IP of the client, example: {151, 236, 219, 228}. This field is meant to be overwritten by plugs that understand e.g. the X-Forwarded-For header or HAProxy’s PROXY protocol. It defaults to peer’s IP (...)"

The way sockets are connected to the endpoint currently (if I am not mistaken @josevalim) is directly without any usual "interference" from plugs.

Without making the sockets part of the plug pipeline, remote_ip is basically the ip information found within the peer data (which can be read as of #2889). One could manually call some functions within the socket's connect/3 to resolve the "real" remote_ip (just like a plug could) though.

But in the end I think it could make more sense to to have the remote_ip field from the conn available as well only if we can make it possible that plugs can adjust it as needed before the conn reaches the socket.

IIRC @chrismccord mentioned on IRC that it could be problematic to attach the sockets using a plug.

**Comment by josevalim** [comment]
Actually, because you can fetch the peer data and x-forwarded-for in master, this is now possible. Sorry for the emotional rollercoaster. :D

But yes, if we want to support explicit remote_ip, then we need to support x-forwarded-for built-in.

**Comment by rmoorman** [comment]
For reference, as discussed with @josevalim on IRC, there is no way to let cowboy upgrade within a plug. (at least not with cowboy 1 ... maybe in cowboy 2 though)
