### ISSUE TITLE
Requesting get_flash/1 to be added to myapp_web.ex in the new app generator

### ISSUE THREAD

**Issue by nickjj** [phoenixframework/phoenix#2767]
When generating a new HTML driven app with Phoenix 1.3, it creates a `myapp_web.ex` file.

Inside of the view section, you might see something similar to this:

```elixir
  def view do
    quote do
      # ...

      import Phoenix.Controller, only: [get_flash: 2, view_module: 1]

      # ...
    end
  end
```

This works well if you're accessing your flash messages in an HTML template like so:

```eex
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
```

But, you could also use a comprehension like this:

```eex
<%= for {type, message} <- get_flash(@conn) do %>
  <p class="alert alert-<%= type %>" role="alert"><%= message %></p>
<% end %>
```

If you try to do this, you'll encounter an undefined function error because `get_flash/1` is undefined.

I'm proposing 1 of 2 things:

1. We add `get_flash: 1 ` to the list of default functions that are pulled in through `myapp_web.ex`
2. Change the template to use a comprehension and replace`get_flash/2` with `get_flash/1` in `myapp_web.ex`

What do you think?

*As a newcomer who was exploring open source projects, I wanted to use the comprehension but it tripped me up for a little bit because it didn't occur to me that it wasn't included by default.*

**Comment by chrismccord** [comment]
Can you send a PR that includes get_flash/1 in the new project generators? Thanks!
