### ISSUE TITLE
possible security problem with check_origin

### ISSUE THREAD

**Issue by matteosister** [phoenixframework/phoenix#2770]
### Environment

* Elixir version (elixir -v): 1.6.0
* Phoenix version (mix deps): 1.3.0 (and master branch)
* NodeJS version (node -v): v8.9.4
* NPM version (npm -v): 5.6.0
* Operating system: linux ubuntu

### Expected behavior
check_origin: true in the websocket configuration should disallow connection from any origin that is different from the one configured in the endpoint url.host configuration

### Actual behavior
We are doing a penetration test for checking our website security. They found that, with a local client (html file on local filesystem) is possible to open a connection and bypass the _check_origin_ flag.
Every browser sends different origin headers, right now firefox send "null" and chrome "file://".
I think that the problem is in the use of the function URI.parse/1, called [here](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket/transport.ex#L395) and [this specific pattern matching](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket/transport.ex#L449). the host for the reported origin headers is always nil, so the origin_allowed? function will always resolve to true, without evaluating the _check_origin_ flag, that in this case I think should be honoured.

Maybe there is some reason because of this. So I'm reporting the problem just to check if we are doing something wrong.

Let me know if you need any other help, or a pull request.
Many thanks in advance.

**Comment by josevalim** [comment]
Thanks @matteosister!

This clause was added when tackling #1328. So I would recommend forbidding those by default and require people to explicitly allow file:///.

**Comment by matteosister** [comment]
@josevalim Awesome! @chrismccord let me know if you want some help with a pull request.

**Comment by josevalim** [comment]
I just said this in the mailing list: there has been demand to allow custom protocols such as the one for chrome extensions. Maybe the best plan here is to revert #1328 and allow a MFA to be specified too.

**Comment by chrismccord** [comment]
+1 for MFA as a feature since there has also been demand for dynamic lookup for cases such as account-based check origin
