### ISSUE TITLE
default array values in schema

### ISSUE THREAD

**Issue by cyzanfar** [phoenixframework/phoenix#2774]
Is there a way to add default values for an `array` type in `Ecto.schema` like so:

```
  def change do
    alter table(:user) do
      add :skills, {:array, :string}, default: [
        "css",
        "html"
      ]
    end
  end
```

**Comment by josevalim** [comment]
Short answer: `default: fragment("[\"css\", \"html\"]"`.

Please use the Elixir Forum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
