### ISSUE TITLE
when _csrf_token params includes "+" invalid csrf error

### ISSUE THREAD

**Issue by dokuzbir** [phoenixframework/phoenix#2784]
I have a callback url for third party post request. 
"http://localhost:4000/callback?_csrf_token=#{Plug.CSRFProtection.get_csrf_token}"

when crsf token includes "+" i get invalid crsf error. For example that token;
`"HVIlKXk5eEYJby8uQW8dCTc+ISkINgAAy9Ka2p45OWci27Y9uOIYDA=="`

at error screen that token turns to that, plus dissappears
`"HVIlKXk5eEYJby8uQW8dCTc ISkINgAAy9Ka2p45OWci27Y9uOIYDA=="`

other token possibilities are passing correctly.

**Comment by josevalim** [comment]
You need to call URI.encode in the parameters if you are building URLs by hand. That;s for any parameter, not only the token.

**Comment by dokuzbir** [comment]
`URI.encode("http://localhost:4000/callback?_csrf_token=#{Plug.CSRFProtection.get_csrf_token}")`

I still get same error with that code

URL

`http://localhost:4000/callback?_csrf_token=FW02N1pAWSoFPCYUTAciHEpOCHE2EAAAq4tbu0oI0LkN4UzH+xRAcA==`

Params at error page
```
Params

_csrf_token

    "FW02N1pAWSoFPCYUTAciHEpOCHE2EAAAq4tbu0oI0LkN4UzH xRAcA=="


```

**Comment by jccf091** [comment]
I got the same issue but the token was generated by Phoenix.
