### ISSUE TITLE
Supervisor tree ordering

### ISSUE THREAD

**Issue by quolpr** [phoenixframework/phoenix#2788]
Why phoenix has such order of supervisor tree by default in generated file:

```
# Start the endpoint when the application starts
supervisor(MyApp.Endpoint, []),
# Start the Ecto repository
supervisor(MyApp.Repo, []),
# Here you could define other workers and supervisors as children
# worker(MyApp.Worker, [arg1, arg2, arg3]),
```

Can we have situation, when endpoint is started, but request can’t access to DB because MyApp.Repo is not started yet?

I think generated file must be so:
```
supervisor(MyApp.Repo, []),
# Here you could define other workers and supervisors as children
# worker(MyApp.Worker, [arg1, arg2, arg3]),
supervisor(MyApp.Endpoint, [])
```

What do you think? Does it have any concerns?

**Comment by josevalim** [comment]
We start the repo first:

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_single/lib/app_name/application.ex#L10-L17

Maybe someone changed your code?

**Comment by chrismccord** [comment]
As of Phoenix 1.2+ we made the change that you suggested above, so perhaps you are running an app taht was generated for 1.0 or 1.1?

**Comment by josevalim** [comment]
Oh, I was actually tracking back and noticed that we did generate the wrong thing in 1.1. Chris was faster than me. :)
