### ISSUE TITLE
Docs on profiling a Phoenix application?

### ISSUE THREAD

**Issue by raarts** [phoenixframework/phoenix#2789]
This is a doc feature request. I have been googling, on stackoverflow trying to find out how to profile my Phoenix application (which performs badly).  Unfortunately I have spent many hours trying to find out how to do it. People point me to erlang documentation (which I honestly do not find helpful, since I don't know how to go from the fprof page to using it in IEX, see me struggling in [this SO question](https://stackoverflow.com/questions/49149928/how-can-i-profile-my-elixir-phoenix-server)) .

Because `mix help` shows a `profile.fprof` command it would seem to me it can be used to profile my Phoenix app. But there are no docs on how to do that. See [this question](https://stackoverflow.com/questions/49157248/undefinedfunctionerror-function-profile-run-test-0-is-undefined-module-pro) where admittedly I was being a bit foolish. 

A short page in the Phoenix documentation would probably go a long way.

**Comment by optikfluffel** [comment]
@raarts For now, maybe [this blogpost from dnsimple](https://blog.dnsimple.com/2018/02/server-timing-with-phoenix/) could help you figure out what's slow in your app. There's also [PryIn](https://pryin.io), which has a 14 day trial.

**Comment by raarts** [comment]
Hi, thanks. My Phoenix app is a graphQL server. The backends can do 13K req/sec, but my server only does 500. I want to find out which functions are the hotspots in my app. 
Any thoughts on that? Thanks.

**Comment by optikfluffel** [comment]
Maybe you can find out more [using Erlang's Observer Tool](https://faizmokhtar.com/2018/01/22/using-erlang-observer-tool-in-elixir/) to see if for example a `GenServer` piles up messages in it's queue and becomes a bottleneck or something similar.

**Comment by chrismcg** [comment]
Have a look at https://elixirforum.com/t/erlang-erlang-in-anger-free/6091 too, it's also worth searching the forum for mentions of it

**Comment by chrismccord** [comment]
I'll second that Erlang in Anger is a great resource. I think a profiling guide would be great, but it's an advanced topic and it spills outside of Phoenix into general Elixir profiling as the slowdowns that folks run into are usually outside of the Phoenix stack in that the bottlenecks are in the stateful systems your web front-end is hitting. If someone would like to volunteer for this effort, we would be happy to review a profiling guide, but it's not something we have planned in the near term. Thanks!
