### ISSUE TITLE
no default phx mix task

### ISSUE THREAD

**Issue by kswope** [phoenixframework/phoenix#2792]
```
mix deps               # Lists dependencies and their status
mix ecto               # Prints Ecto help information
mix hex                # Prints Hex help information
mix local              # Lists local tasks
mix phx                😞
```

**Comment by chrismccord** [comment]
`mix help phx` still works :)

**Comment by kswope** [comment]
```
(xenial)kevin@localhost:~/hello$ mix help phx
** (Mix) The task "phx" could not be found. Did you mean "phx.new"?
```

And since you brought it up
```
mix help ecto
```

Tells the user to run 

```
mix ecto
```

Which brings us full circle, we need

```
mix phx
```

For consistency and discoverability.

**Comment by josevalim** [comment]
Agreed. We didn’t implement it before because we supported earlier elixir
versions but it should be straightforward now. pr please?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by kswope** [comment]
Don't "pr please" me, I don't know what I'm doing! 

I just started, that's why I'm the one who noticed this omission ;)

**Comment by OvermindDL1** [comment]
> Don't "pr please" me, I don't know what I'm doing!

Lol, great time to learn though!  :-)

**Comment by pdawczak** [comment]
I don't have experience creating mix tasks either, and this seems like a great opportunity to try it - if you don't mind?

**Comment by kswope** [comment]
Ok I'm assigning this to @pdawczak  :-)

**Comment by josevalim** [comment]
Closing in favor of the PR. :)
