### ISSUE TITLE
Mentor availability label [mentor-available]

### ISSUE THREAD

**Issue by pragmaticivan** [phoenixframework/phoenix#2793]
Having a "mentor-available" label would allow anyone interested in contributing to quickly filter issues for which a mentor is available. They could contact the mentor(s) and be confident that they will be able to move things forward. That would encourage people interested in contributing to actually start doing it more. This could lead to more permanent collaborators added to the project.

Some projects are doing that and generating more contributions.

**Comment by chrismccord** [comment]
Thanks for the idea! We tag issues as level:starter for opportunities for newcomers to jump in. The core team is also generally available on irc and slack for questions so I don't yet think we need this feature as far as accessibility goes. I think this kind of idea is great, but I also think it places a larger burden on the core-team, which we're not yet at a point and size to take on direct mentor roles. Thanks!
