### ISSUE TITLE
Links to codebase from documentation on hexdocs.pm are not working (missing tag 1.3.2 in repo)

### ISSUE THREAD

**Issue by michallepicki** [phoenixframework/phoenix#2800]
### Expected behavior
The `</>` button in [the documentation](https://hexdocs.pm/phoenix/Phoenix.html#content) should lead to module/function code.

### Actual behavior
github 404 for all modules / functions in the current docs

**Comment by michallepicki** [comment]
Is 1.3.2 actually released? There's nothing in the [changelog](https://github.com/phoenixframework/phoenix/blob/master/CHANGELOG.md) but it's present in [hex.pm](https://hex.pm/packages/phoenix)

**Comment by wojtekmach** [comment]
since master tracks v1.4, that release was off v1.3 branch: https://github.com/phoenixframework/phoenix/tree/v1.3

**Comment by michallepicki** [comment]
I believe hexdocs points to tags, not branches. In the [main (current) documentation](https://hexdocs.pm/phoenix/Phoenix.html#content) the address under </> button leads [here](https://github.com/phoenixframework/phoenix/blob/v1.3.2/lib/phoenix.ex#L1). It works for [1.3.1 docs](https://hexdocs.pm/phoenix/1.3.1/Phoenix.html#content) - it leads [here](https://github.com/phoenixframework/phoenix/blob/v1.3.2/lib/phoenix.ex#L1)

**Comment by wojtekmach** [comment]
the tag is obviously not pushed, you made that pretty clear. I was just responding to why you were not seeing the release in changelog on master.

**Comment by chrismccord** [comment]
Tags pushed. Thanks!
