### ISSUE TITLE
CSS not optimize with webpack

### ISSUE THREAD

**Issue by obsidienne** [phoenixframework/phoenix#2809]
### Expected behavior
In production, CSS should be minized.

### Actual behavior
CSS is not minized in production. 

Following this [medium article](https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a), optimization is done using uglifyJS.

I think the following code is missing to optimize CSS: https://github.com/webpack-contrib/css-loader#minimize

Thanks

**Comment by josevalim** [comment]
@obsidienne I assume you are using Phoenix master?

**Comment by obsidienne** [comment]
@josevalim Yes, I have copied the configuration from https://github.com/phoenixframework/phoenix/tree/master/installer/templates/phx_assets
