### ISSUE TITLE
"mix phx.server" command stalling on 1.4.0-dev umbrella projects

### ISSUE THREAD

**Issue by leveloid** [phoenixframework/phoenix#2815]
### Environment

* Elixir version (elixir -v): 1.6.4
* Phoenix version (mix deps): Master
* Operating system: OSX

### Actual behavior
On a clean install of an umbrella project (`mix phx.new project_name --binary-id --umbrella --dev`) - `mix phx.server` stalls right before Cowboy server is supposed to start. The process seems to hang indefinitely, with cancelling the entire process being the only solution.

Non-umbrella projects ('mix phx.new project_name --binary-id --dev') work as expected.

**Comment by chrismccord** [comment]
Thanks for the report! Looks like this was accidentally introduced in  https://github.com/phoenixframework/phoenix/commit/46dd1d53be7dfa928b5872c715c0856db9e3104a
