### ISSUE TITLE
Webpack 4 +  ExtractTextPlugin issues

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#2818]
As per the comments [here](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/749#issuecomment-374549467) it seems like efforts to support webpack 4 with the ExtractTextWebpackPlugin have come to a halt, while there are various issues with the existing beta version. Might be nice to have a look at alternatives until 1.4 is released.

**Comment by Gazler** [comment]
Looks like https://github.com/webpack-contrib/mini-css-extract-plugin is the advised replacement.
