### ISSUE TITLE
Deprecations on `ecto.create`

### ISSUE THREAD

**Issue by msbit** [phoenixframework/phoenix#2823]
Just ran `mix ecto.create` for the first time, and received deprecation warnings regarding `phoenix`.

### Environment

* Elixir version (elixir -v): `Elixir 1.6.4 (compiled with OTP 20)`
* Phoenix version (mix deps): `1.3.2 (Hex package) (mix)`
* NodeJS version (node -v): `v9.10.0`
* NPM version (npm -v): `5.8.0`
* Operating system: `macOS 10.13.3`

### Expected behavior

Install, no warnings.

### Actual behavior

```
...
==> phoenix
Compiling 74 files (.ex)
warning: Enum.partition/2 is deprecated, use Enum.split_with/2
  lib/phoenix/endpoint/handler.ex:39

warning: Enum.partition/2 is deprecated, use Enum.split_with/2
  lib/mix/tasks/phoenix.gen.model.ex:155

warning: Enum.partition/2 is deprecated, use Enum.split_with/2
  lib/mix/phoenix/schema.ex:234

Generated phoenix app
...
```

**Comment by josevalim** [comment]
Thanks @msbit . Those are fixed on master!
