### ISSUE TITLE
Add Postcss to thé web pack config file

### ISSUE THREAD

**Issue by obsidienne** [phoenixframework/phoenix#2824]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

### Expected behavior
In production, the css generated should add prefixes. 

### Actual behavior
No prefixes added. 

Postcss permits a lot of css improvement, it could be an interesting improvement.

**Comment by josevalim** [comment]
We want to keep the number of dependencies tight for now. Folks can bring their favorite tools accordingly. :)
