### ISSUE TITLE
update Heroku deployment guide with webpack

### ISSUE THREAD

**Issue by happysalada** [phoenixframework/phoenix#2827]
The current deployment process to heroku won't work with the [current phoenix static assets buildpack](https://github.com/gjaldon/heroku-buildpack-phoenix-static) out of the box. It needs a bit of customization. I was wondering if there is a plan to update the buildpack or if the docs should be updated.

Bascially it's a matter of adding a phoenix_static_buildpack.config file with the following
```
compile="compile"
```

and having a `compile` file (just like a procfile, it's just a file named compile) with the following
```
yarn deploy
cd ..
mix phx.digest
```

If the docs need to be updated, I have time to make a PR.

**Comment by chrismccord** [comment]
It should be updated as part of the 1.4 release. Thanks!

**Comment by happysalada** [comment]
this was closed by #2834
