### ISSUE TITLE
How to run Phoenix app in FreeBSD with port 80

### ISSUE THREAD

**Issue by manju16832003** [phoenixframework/phoenix#2828]
### Environment

* Elixir version (elixir -v): 1.5.6
* Phoenix version (mix deps): 1.5.3
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system: FreeBSD

### Expected behavior
I'm trying to deploy Phoenix app into FreeBSD,
Previously I used this command to deploy Phoenix app for debian based system using
`MIX_ENV=prod PORT=80 elixir --detached -S mix do compile, phx.server`

### Actual behavior

However, same command does not work in FreeBSD

Here is the error

`MIX_ENV=prod: Command not found.`

**Comment by josevalim** [comment]
MIX_ENV=prod and PORT=80 are environment variables. So you need to look how environment variables are set in whatever shell you are using for FreeBSD.

**Comment by julp** [comment]
With (c)sh shell, you need to add the `env` keyword ahead: `env MIX_ENV=prod PORT=80 elixir --detached -S mix do compile, phx.server`
