### ISSUE TITLE
Routing Guide is unclear for beginners

### ISSUE THREAD

**Issue by alienscience** [phoenixframework/phoenix#2833]
### Environment

* Webpage: https://hexdocs.pm/phoenix/routing.html#forward

### Expected behavior

I am going through the guide/tutorial and I am a beginner with both Phoenix and Elixir. The tutorial has been very clear and enjoyable. Up to this point I have known what to type and what to try out. 

Up until this point every bit of code has been given with the filename that I should edit.

### Actual behavior
Starting at this section there are different options for the `forward` macro. Should I use the first one or do I add authentication? The information in this section is useful but I do not know what I should type to follow the tutorial.

Also starting at the paragraph:
> However for convenience and to allow you to test the code above, here is the implementation of BackgroundJob.Plug that you can copy into your application:

As a beginner, It is not clear to me where plugins should go in a Phoenix application. Unlike the guide up until this point, there is no filename with the code sample.

**Comment by Gazler** [comment]
Thanks for raising this, hearing from beginners is always useful. This file can go anywhere inside the `lib` directory. I'd recommend `lib/plugs/background_job_plug.ex` - if you want to open a PR to change it to:

 > here is the implementation of BackgroundJob.Plug that you can copy into your application inside `lib/plugs/background_job_plug.ex`:

That would be appreciated.

**Comment by halian-vilela** [comment]
Funny, for some reason it did not land in the online version. I'm here for the same purpose, glad you could help, but the online doc is still with the previous version: 

> Writing an actual background job worker is beyond the scope of this guide. However for convenience and to allow you to test the code above, here is the implementation of BackgroundJob.Plug that you can copy into your application

https://hexdocs.pm/phoenix/routing.html#content
