### ISSUE TITLE
Message flow diagram in the Channels guide looks bad

### ISSUE THREAD

**Issue by facundoolano** [phoenixframework/phoenix#2840]
* Operating system: macOS
* Browser: Firefox and Chrome

There seems to be an issue with the [message flow diagram in the channels guide](https://hexdocs.pm/phoenix/channels.html#overview). See attached screenshot.

<img width="960" alt="screen shot 2018-04-09 at 5 35 23 pm" src="https://user-images.githubusercontent.com/1040941/38521650-abb220d0-3c1c-11e8-89d8-dea5bb546231.png">

**Comment by Gazler** [comment]
@nathanl fixed this for https://github.com/phoenixframework/phoenix/pull/2765 - maybe he can advise what to do here.

**Comment by nathanl** [comment]
We just need to release the updated version. The docs shown are for v1.3.2, released March 8. The fixed diagram (which switches from unicode to ASCII characters) was merged to master on March 9.
