### ISSUE TITLE
Maintenance/end-of-life/security updates policy?

### ISSUE THREAD

**Issue by henrik** [phoenixframework/phoenix#2852]
One was recently added to Elixir itself: https://github.com/elixir-lang/elixir/issues/7489

Is there such a thing for Phoenix? Could one be added, or would it at least be possible to get an informal idea in a comment on this ticket?

**Comment by henrik** [comment]
@chrismccord Hi! We happened to discuss this at work today, so just wanted to check if there are any news. Completely understand if it's not at the top of the priority list of course :)

**Comment by strzibny** [comment]
Yep, this would clear some worries for companies wanting to rely on Phoenix. I asked on mailing list to no vein.

In my opinion saying the project does not yet have a core team to handle it is completely fine. We all understand it, but being silent is weir and looks like the project is abandon (which is far from the trush looking at LiveView etc).

@chrismccord this is now a  one year stale issue.

**Comment by chrismccord** [comment]
> In my opinion saying the project does not yet have a core team to handle it is completely fine. We all understand it, but being silent is weird and looks like the project is abandon

We've had two Phoenix releases in the last month, with the latest less than a week ago. Our issue tracker tracks outstanding bugs and TODOs, of which this one is still on my plate. I need to plan these policies while coordinating with the Phoenix team on our commitments and availability to support older versions, which takes time and effort that has to be balanced with all the other work we are doing.

> @chrismccord this is now a one year stale issue.

I'm aware of how long our issues are open for, so pinging to remind me only adds noise to my inbox. We have just 16 open issues at the moment, so this one in particular has not slipped my mind, but it's lower priority than others. I understand this issues is important to you and other folks, but please be patient :)

**Comment by strzibny** [comment]
Thanks for the reply and I am very sorry for adding the noise. Even a reply such as this one is helpful (there just wasn't any reply to both mailing list issue and this issue). If someone is a manager evaluating Phoenix they might find these issues instead of the frequent releases.

Anyway thank you for an update and for your work on Phoenix. I only have a success of Phoenix in mind and it was not to "complain".
