### ISSUE TITLE
1.3.2 view guide references 1.4 feature

### ISSUE THREAD

**Issue by axelson** [phoenixframework/phoenix#2854]
### Expected behavior

hexdocs for 1.3.2 should not mention the Jason library

### Actual behavior

hexdocs mention the Jason library: 

> Phoenix uses Jason to encode Maps to JSON

Source: https://github.com/phoenixframework/phoenix/blob/v1.3.2/guides/docs/views.md#rendering-json

**Comment by josevalim** [comment]
fixed, tks
