### ISSUE TITLE
Minor confusion in comments on socket.js

### ISSUE THREAD

**Issue by dcaixinha** [phoenixframework/phoenix#2858]
Hey all, just noticed some confusing code comment on the [socket.js](https://github.com/phoenixframework/phoenix/blob/46dd1d53be7dfa928b5872c715c0856db9e3104a/installer/templates/phx_assets/webpack/socket.js#L51) of a newly generated Phoenix project.

Basicaly the docs state "[...] pass the token on connect as below [...]", but then no token is passed on connect — as it's done, as usual, when instatiating the `Socket` object. Should I submit a PR to change this?

**Comment by chrismccord** [comment]
Please send a PR to clarify “as above”, or better yet move the comment up above the instantiaton. Thanks!

**Comment by chrismccord** [comment]
Fixed in https://github.com/phoenixframework/phoenix/commit/43455a669c26f9238d7dc597ff22635a35161a52
