### ISSUE TITLE
Create an Ember Data Phoenix channel adapter

### ISSUE THREAD

**Issue by hugo** [phoenixframework/phoenix#286]
Phoenix works great out of the box with Ember Data's HTTP/Rest adapter, but the realtime web is much more buzzwordy so I've got a half working adapter for WebSocket's based on `phoenix.js` and getting it fully functional as per the [custom adapters](http://emberjs.com/guides/models/customizing-adapters/) guide shouldn't be difficult.

I'm creating this issue here to solicit opinions on the best way to handle this on Phoenix's end.

I think having a channel "ember" and event handlers like this looks right:

``` elixir
def event(socket, "user:update:" <> id, user) do
   # update the user
  reply socket, "user:updated:#{id}" %{error: nil, user: user}
  socket
end
```

I then put all the logic for updating the user in the user model, so both the REST endpoints and WebSocket work the same way, and it's just a different transport. Does that seem right?

**Comment by hunterboerner** [comment]
@thisishugo have you gotten something working. I would love to use this.
