### ISSUE TITLE
mix.create error 

### ISSUE THREAD

**Issue by xieyuheng** [phoenixframework/phoenix#2862]
I am following the guide :: https://hexdocs.pm/phoenix/up_and_running.html#content

I have problem using `mix.create`

```
mix ecto.create
Compiling 13 files (.ex)
Generated hi app
** (Mix) The database for Hi.Repo couldn't be created: FATAL 28000 (invalid_authorization_specification): role "root" does not exist

13:44:33.620 [error] GenServer #PID<0.312.0> terminating
** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification): role "root" does not exist
    (db_connection) lib/db_connection/connection.ex:163: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
```

the question is that I configed my db as (my config/dev.exs is the default one.) :
```
# Configure your database
config :hi, Hi.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "hi_dev",
  hostname: "localhost",
  pool_size: 10
```
but why the error says 'role "root" does not exist' ?

my `deps` are the following :
```
  defp deps do
    [
      {:phoenix, "~> 1.3.2"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.10"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"}
    ]
  end
```

------

I am using archlinux.

I installed and configed postgresql following : https://wiki.archlinux.org/index.php/PostgreSQL

I changed the password of the default postgres user of the db to "postgres" by 
```
\password
```

**Comment by josevalim** [comment]
Can you please push this Repo to github? At first nothing looks suspicious.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by xieyuheng** [comment]
I pushed it here :: https://github.com/xieyuheng/hi

**Comment by josevalim** [comment]
@xieyuheng thanks. I don't have a role "root" on my machine and the repo above worked fine. I wonder if there is something in your installation requiring root. Can you try this command in your terminal?

    psql -c "\du"

**Comment by xieyuheng** [comment]
here it is : 
```
[postgres@cicada ~]$ psql -c "\du"
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 xyh       |                                                            | {}
```

**Comment by xieyuheng** [comment]
the problem might be my env,
I will try to fix it and report later.

**Comment by xieyuheng** [comment]
the problem is due to the following in my env :

```
DATABASE_URL="mysql://root:cicada@localhost/broker_dev"
```

sorry to bother you, and thank you for your time.

closing this issue.
