### ISSUE TITLE
Defining multiple routes paths on the same controller and action is failing

### ISSUE THREAD

**Issue by nicolasblanco** [phoenixframework/phoenix#2864]
### Environment

* Elixir version (elixir -v): 1.6.4
* Phoenix version (mix deps): 1.3.2
* Operating system: OS X

### Expected behavior

When defining multiple routes on the same controller and same action with different named parameters like:

```
  get "/products/:foo", ProductController, :show
  get "/products/:foo/:bar", ProductController, :show
  get "/products/:foo/:bar/:rebar", ProductController, :show
```

I would like to be able to call them using the same path name and a different number of arguments.

### Actual behavior

The `product_path` function is clearly redefined multiple times but only the first definition is working properly.

```
iex(1)> MyappWeb.Router.Helpers.product_path
** (UndefinedFunctionError) function MyappWeb.Router.Helpers.product_path/0 is undefined or private. Did you mean one of:

      * product_path/3
      * product_path/4
      * product_path/5
      * product_path/6

    (myapp) MyappWeb.Router.Helpers.product_path()
iex(1)> MyappWeb.Router.Helpers.product_path(MyappWeb.Endpoint, :show, "1")
"/products/1"

iex(2)> MyappWeb.Router.Helpers.product_path(MyappWeb.Endpoint, :show, "1", "2")
** (Protocol.UndefinedError) protocol Enumerable not implemented for "2". This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range, Scrivener.Page, Stream, Timex.Interval

iex(2)> MyappWeb.Router.Helpers.product_path(MyappWeb.Endpoint, :show, "1", "2", "3")
** (Protocol.UndefinedError) protocol Enumerable not implemented for "3". This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range, Scrivener.Page, Stream, Timex.Interval
```

If it's not possible to redefine the same route path on a different number of named argument, would it be possible to have a good warning message or a better exception?

In that case, why the path is still correctly redefined?

Thanks.

**Comment by nicolasblanco** [comment]
I've investigated this problem and it looks like for all definitions aside the first one, an empty params list is mandatory.

```
iex(1)> DokkitoWeb.Router.Helpers.product_path(DokkitoWeb.Endpoint, :show, "1")
"/products/1"
iex(2)> DokkitoWeb.Router.Helpers.product_path(DokkitoWeb.Endpoint, :show, "1", "2")
** (Protocol.UndefinedError) protocol Enumerable not implemented for "2".
iex(2)> DokkitoWeb.Router.Helpers.product_path(DokkitoWeb.Endpoint, :show, "1", "2", [])
"/products/1/2"
iex(3)> DokkitoWeb.Router.Helpers.product_path(DokkitoWeb.Endpoint, :show, "1", "2", "3", [])
```

**Comment by josevalim** [comment]
@nicolasblanco yeah, the definitions are clearly conflicting with each other. You are correct, we need to have a better UX around this.

**Comment by nicolasblanco** [comment]
@josevalim : Thanks for the answer José. Right now of course I can mitigate the problem by using the `as` option and set a different path name for the routes. But knowing that Elixir can have multiple definitions for the same function name, I was hoping to be able to use the same path...

**Comment by josevalim** [comment]
I have recently optimized the router and i could confirm that this issue exists. More than that, if we can solve this issue, we can optimize routes generation by probably making it half of the time it takes today. We just need to discuss a relevant approach for it.
