### ISSUE TITLE
Phoenix.Token “forever valid” warning - why is a max age recommended? 

### ISSUE THREAD

**Issue by ghost** [phoenixframework/phoenix#2868]
👋

And is it necessary for it to [default to 86400](https://github.com/phoenixframework/phoenix/blob/v1.3/lib/phoenix/token.ex#L226)? Wouldn't it be less surprising to keep it as a warning (maybe slightly updated with the actual description of a possible vulnerability)? 

I've also wondered about this on the forum https://elixirforum.com/t/phoenix-token-forever-valid-warning-why-is-a-max-age-recommended/13952.

> what kind of vulnerability would storing a “forever valid” session id have. In other words, is this warning only for the users who store some extra data in the token (besides the session id) which can go stale?

By the "session id' here I mean something like a user id.

**Comment by idi-ot** [comment]
@chrismccord, sure, but it's not just a question, the issue that I wanted to discuss is 

> And is it necessary for it to default to 86400? Wouldn't it be less surprising to keep it as a warning (maybe slightly updated with the actual description of a possible vulnerability)?

As you can see on the forum, there isn't any additional threat to forever valid tokens in some use cases like mine, and if I didn't know that in phoenix v2 the tokens would change their default behaviour, the app would've stopped working after a day ... But I see that the documentation has been updated after phoenix v1.3 to include a note about infinite expiration time, which was kind of what I wanted to do.
