### ISSUE TITLE
Prepare for deprecation of System.stacktrace/0

### ISSUE THREAD

**Issue by michalmuskala** [phoenixframework/phoenix#2869]
The stacktrace should be always grabbed inside the `catch` or `rescue` blocks of `try` directly and not in a called function. This will prepare plug for deprecation of `:erlang.get_stacktrace` and `System.stacktrace()` and introduction of the `__STACKTRACE__` pseudo-variable.

After a brief review the only problematic place seem to be `Phoenix.Endpoint.RenderErrors.__catch__/4`.

I suggest it should grab the stacktrace in the macroe'd `try` (possibly skipping it when given a `Plug.Conn.WrapperError` with an additional `rescue` clause).

**Comment by josevalim** [comment]
I have done part of the work in plug in already, so I went ahead and tidy it up here too!
