### ISSUE TITLE
Custom Transports don't seem to be supported

### ISSUE THREAD

**Issue by rmoorman** [phoenixframework/phoenix#2872]
### Environment

* Elixir version (elixir -v): 
````
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.4 (compiled with OTP 19)
````
* Phoenix version (mix deps):
````
* file_system 0.2.4 (Hex package) (mix)
  locked at 0.2.4 (file_system) f0bdda19
  ok
* gettext 0.15.0 (Hex package) (mix)
  locked at 0.15.0 (gettext) 40a2b8ce
  ok
* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) d9eb6366
  ok
* phoenix_pubsub 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (phoenix_pubsub) bfa7fd52
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* mime 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (mime) 78adaa84
  ok
* plug 1.5.0 (Hex package) (mix)
  locked at 1.5.0 (plug) 224b25b4
  ok
* phoenix_html 2.11.2 (Hex package) (mix)
  locked at 2.11.2 (phoenix_html) 86ebd768
  ok
* phoenix 1.3.2 (Hex package) (mix)
  locked at 1.3.2 (phoenix) 2a00d751
  ok
* phoenix_live_reload 1.1.3 (Hex package) (mix)
  locked at 1.1.3 (phoenix_live_reload) 1d178429
  ok
* dingen 0.0.1 (apps/dingen) (mix)
  ok
* dingen_web 0.0.1 (apps/dingen_web) (mix)
  ok
`````
* NodeJS version (node -v): `v8.9.2`
* NPM version (npm -v): `5.6.0`
* Operating system: `Mac OSX High Sierra 10.13.4 (17E199)`

### Expected behavior
Copying the `Phoenix.Transports.WebSocket` module into my own app (which by the way is named `dingen_web`) only changing the module name and using that transport module as transport within the app's socket module (`transport :websocket, DingenWeb.WebSocketTransport` leads to a working Phoenix socket/channels setup just as when using `transport :websocket, Phoenix.Transports.WebSocket`.
And in extension a completely customized transport should work too.

### Actual behavior
Copying the `Phoenix.Transports.WebSocket` module into my own app only changing the module name and using that transport module as transport within the app's socket module (`transport :websocket, DingenWeb.WebSocketTransport` does not work just as when using `transport :websocket, Phoenix.Transports.WebSocket`.
The request from the Phoenix socket client (browser javascript) leads to a 404 within the router. No socket connection is established.

Within the logs, the following can be witnessed
````
[info] GET /socket/websocket
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /socket/websocket (DingenWeb.Router)
    (dingen_web) lib/dingen_web/router.ex:1: DingenWeb.Router.__match_route__/4
    (dingen_web) lib/phoenix/router.ex:303: DingenWeb.Router.call/2
    (dingen_web) lib/dingen_web/endpoint.ex:1: DingenWeb.Endpoint.plug_builder_call/2
    (dingen_web) lib/plug/debugger.ex:102: DingenWeb.Endpoint."call (overridable 3)"/2
    (dingen_web) lib/dingen_web/endpoint.ex:1: DingenWeb.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /path/to/project/dingen_umbrella/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
````

### Probable cause
After some investigation on my side, this behaviour seems to be caused by `Phoenix.Endpoint.CowboyHandler.child_spec/3` and the private function `Phoenix.Endpoint.CowboyHandler.default_for/1`.
The `default_for/1` function is called by `child_spec/3` in order to resolve the `handler` module for the connection. But `default_for/1` does return `nil` for every passed in argument except the built in transports `LongPoll` and `WebSocket` which causes the handler to be `nil` for any custom transport.
As a result, the cowboy dispatches list does not contain dispatch items for custom transports which  does explain the 404s when a custom transport is used (to the best of my knowledge).
For the relevant code see [cowboy_handler.ex lines 83 to 113](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/cowboy_handler.ex#L83-L113)
The same issue seems to be present within the [cowboy2_handler.ex module](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/cowboy2_handler.ex#L80-L118).

**Comment by josevalim** [comment]
Yes. You need to change the default options in your custom transport and
set the cowboy field which will tell cowboy which cowboy handler it should
use.

Keep in mind though there is a PR to change how transport work to make it
much easier to write custom transports. I can post a link later. I would
suggest waiting a week and using master if your goal is to use custom
transports.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by rmoorman** [comment]
@josevalim Adding this to the return value of `default_config/1` of my custom transport worked indeed:
```
   def default_config() do
     [serializer: [{Phoenix.Transports.WebSocketSerializer, "~> 1.0.0"},
                   {Phoenix.Transports.V2.WebSocketSerializer, "~> 2.0.0"}],
+     cowboy: Phoenix.Endpoint.CowboyWebSocket,
      timeout: 60_000,
      transport_log: false]
   end
```
Currently I am writing some explorational code so I will go with the current implementation but I am really looking forward to the changes within the PR you mention as I would like to use a custom transport in production soon. Thank you for and keep up the great work!
