### ISSUE TITLE
Add prefix option to Router.Helpers

### ISSUE THREAD

**Issue by KamilLelonek** [phoenixframework/phoenix#2874]
### Environment

* Elixir version (elixir -v):

```bash
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.4 (compiled with OTP 20)
```

* Phoenix version (mix deps):

```bash
* phoenix 1.3.2 (Hex package) (mix)
  locked at 1.3.2 (phoenix) 2a00d751
```

### Expected behavior

I have two `Routers` in my application:

1. The parent one:

```elixir
defmodule Router do
  use Phoenix.Router

  forward("/mobile", Mobile.Router)
end
```

2. The child one:

```elixir
defmodule Mobile.Router do
  use Phoenix.Router

  scope "/quizzes", Quiz, as: :mobile do
    get("/", Controller, :index, as: :quizzes)
  end
end
```

I expect my `Router.Helper` to return:

```elixir
Mobile.Router.Helper.mobile_quizzes_path(Endpoint, :index)
# => "/mobile/quizzes"
```

### Actual behavior

Of course, it's not possible as the "child" `Router` doesn't know about how it's scoped in the "parent" `Router`. It returns:

```elixir
Mobile.Router.Helper.mobile_quizzes_path(Endpoint, :index)
# => "/quizzes"
```

which actually doesn't exist.

It would be good to add some option for path helpers like e.g.:

* `:scope`
* `:prefix`
* `:namespace`

to prepend the generated path with the appropriate scope.

**Comment by josevalim** [comment]
It doesn't work using the Endpoint because we don't know how the router has been accessed/mounted. It does work, however, if you pass a connection.

There are a couple ways you can solve this. The simplest is probably to call `Endpoint.struct_uri` and add a path to the returned struct and pass the changed struct as argument to your functions. This is the general mechanism to customize generated URLs.

**Comment by KamilLelonek** [comment]
Using `conn` as `Phoenix.ConnTest.build_conn()` behaves exactly the same way.

**Comment by Voronchuk** [comment]
In case someone else has also stumbled on issues with tests, replacing default `conn` generator with smth like this works:

```
def admin_conn do
    %{Phoenix.ConnTest.build_conn() | script_name: ["admin"]}
end
```

**Comment by TheMoonDawg** [comment]
@Voronchuk You are a lifesaver my friend. 🙇🏻
