### ISSUE TITLE
`mix ecto.create` compile errors

### ISSUE THREAD

**Issue by English3000** [phoenixframework/phoenix#2879]
### Environment

* Elixir version (elixir -v): for both 1.6.4 and 1.6.5
* Phoenix version (mix deps): `"~> 1.3.0"`
* NodeJS version (node -v): 6.10.1
* NPM version (npm -v): 6.0.0
* Operating system: macOS High Sierra

### Expected behavior

```bash
~/Desktop/explore_new$ mix ecto.create
Compiling 13 files (.ex)
Generated explore_new app
The database for ExploreNew.Repo has been created
```

### Actual behavior

```bash
~/Desktop/explore_new$ mix ecto.create
Compiling 13 files (.ex)

== Compilation error in file lib/explore_new_web/endpoint.ex ==
** (CompileError) lib/explore_new_web/endpoint.ex:4: undefined function socket/3
```

**Fix:**
```ex
# endpoint.ex
socket "/socket", ExploreNewWeb.UserSocket#,
    # websocket: true,
    # longpoll: false
```

```bash
~/Desktop/explore_new$ mix ecto.create
Compiling 13 files (.ex)

== Compilation error in file lib/explore_new_web/endpoint.ex ==
** (UndefinedFunctionError) function Phoenix.json_library/0 is undefined or private
    (phoenix) Phoenix.json_library()
    lib/explore_new_web/endpoint.ex:30: (module)
```

**Fix:**
```ex
plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison #Phoenix.json_library()
```

Just upgraded to new `phx.new` today.

**Comment by josevalim** [comment]
@English3000 it seems you have upgraded to `phx.new` master. master is unstable and it relies on non-released versions of Phoenix. I recommend you to use a stable phx.new by running this command:

    mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez

**Comment by English3000** [comment]
@josevalim Thanks for the clarification, and for creating Elixir!

If it's helpful--as I was just using it for a personal project--I'm happy to report any other issues I run into.

**Comment by English3000** [comment]
Here's an error:

```bash
ERROR in ./js/app.js
Module build failed: SyntaxError: Unexpected token (23:7)

  21 | import { render } from "react-dom";
  22 |
> 23 | render(<h1>Hi!</h1>, document.getElementById("replace-with-js"));
     |        ^
```
