### ISSUE TITLE
Diverging Plug dependency

### ISSUE THREAD

**Issue by Jwashton** [phoenixframework/phoenix#2886]
### Environment

* Elixir version (elixir -v): `Elixir 1.6.5 (compiled with OTP 19)`
* Erlang version (asdf current erlang): `20.3.6`
* Phoenix version (mix deps): `* phoenix 1.4.0-dev (../..) (mix)`
* NodeJS version (node -v): `v10.1.0` (but probably not applicable)
* NPM version (npm -v): `5.6.0` (same as above)
* Operating system: Fedora 28

### Expected behavior

Following [these instructions in the readme](https://github.com/phoenixframework/phoenix#generating-a-phoenix-project-from-unreleased-versions) I should be able to take the following actions

```bash
$ cd installer
$ mix phx.new dev_app --dev --no-ecto # Skipping db for simplicity
... Y to install deps
$ cd dev_app
$ mix phx.server
```

### Actual behavior

Deps install successfully, but running the server fails immediately with this error:

```
$ mix phx.server
Unchecked dependencies for environment dev:
* plug (https://github.com/elixir-plug/plug.git)
  lock outdated: the lock is outdated compared to the options in your mix.exs. To fetch locked version run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies
```

Can we either fix the dependency issue, or add another instruction to the readme telling users to add something like `{:plug, git: "git://github.com/elixir-plug/plug.git", override: true}` to the deps list before they fetch dependencies?

This issue is specifically about the missing step in the readme, but it may be worth noting that I also tripped on [this bug](https://github.com/elixir-lang/elixir/issues/7685) in the process of trying to figure this out.

**Comment by Jwashton** [comment]
For reference, right after generating `dev_app`, this is what the dependency tree looks like:

```
$ mix deps.tree
dev_app
├── gettext ~> 0.11 (Hex package)
├── jason ~> 1.0 (Hex package)
├── phoenix_pubsub ~> 1.0 (Hex package)
├── cowboy ~> 1.0 (Hex package)
│   ├── cowlib ~> 1.0.2 (Hex package)
│   └── ranch ~> 1.3.2 (Hex package)
├── phoenix_html ~> 2.11 (Hex package)
│   └── plug ~> 1.5 (Hex package)
│       ├── mime ~> 1.0 (Hex package)
│       └── cowboy ~> 1.0.1 or ~> 1.1 or ~> 2.3 (Hex package)
├── phoenix (../..) *override*
│   ├── cowboy ~> 1.0 or ~> 2.3 (Hex package)
│   ├── plug ~> 1.5 (https://github.com/elixir-plug/plug.git) *override*
│   ├── phoenix_pubsub ~> 1.0 (Hex package)
│   └── jason ~> 1.0 (Hex package)
└── phoenix_live_reload ~> 1.0 (Hex package)
    ├── file_system ~> 0.2.1 or ~> 0.3 (Hex package)
    └── phoenix ~> 1.0 or ~> 1.2 or ~> 1.3 (Hex package)
```

Both lines that mention `plug` have the version set to `~> 1.5`, but one is a hex package, and the other is set to the git repo with the override flag set.

**Comment by josevalim** [comment]
It is a temporary issue while we depend on Plug master. It should be addressed shortly.
