### ISSUE TITLE
Deprecation warning in Router.pipeline/1 with Plug 1.5.1

### ISSUE THREAD

**Issue by xtian** [phoenixframework/phoenix#2888]
Plug 1.5.1 [deprecated Plug.Conn.WrapperError.reraise/3](https://github.com/elixir-plug/plug/commit/7e7164576fe181a3aaf6afd629199edf45a0a591#diff-ed8c15512ce84b85449e74f5a48d5bbbR21), which is used in the [`Router.pipeline/1`](https://github.com/phoenixframework/phoenix/blob/7fbc2734416819660999fd3df856c3500b86f8d5/lib/phoenix/router.ex#L280) macro in the latest released version of Phoenix.

Although this deprecation is fixed on master, I think it should be backported to the v1.3 branch because any apps which update to Plug 1.5.1 will get a build failure if they build with `--warnings-as-errors`.

### Environment

* Elixir version (elixir -v): 1.6.5
* Phoenix version (mix deps): 1.3.2

**Comment by josevalim** [comment]
@xtian you can also configure xref to exclude those deprecation warnings for now. See `mix help xref`. The problem with fixing those right now is because it would impose a requirement on Plug v1.5.1 and I don't think we should not force deps to update their plug version in a minor update.

**Comment by john-griffin** [comment]
Our travis build also just hit this because we run with `--warnings-as-errors`.

**Comment by chrismccord** [comment]
As José said, `xref` exclusions would be the way to go as we can't push plug 1.5.1 on all users. Thanks!

**Comment by alex-knowles** [comment]
For reference, here's how you can modify your `mix.exs` file to exclude this specific deprecation warning, as @josevalim suggested.

```elixir
  def project do
    [
      ...
      xref: xref()
    ]
  end

  defp xref do
    [
      exclude: [
        {Plug.Conn.WrapperError, :reraise, 3}
      ]
    ]
  end
```

**Comment by esambo** [comment]
Or you could downgrade plug to `1.5.0` as pointed out in the [forums](https://elixirforum.com/t/deprecation-warnings-on-a-brand-new-project-warning-plug-conn-wrappererror-reraise-3-is-deprecated/14268/4)

**Comment by Gazler** [comment]
This should be fixed in Phoenix 1.3.3

**Comment by AndrewDryga** [comment]
@john-griffin For CI it's better to compile in two passes. First `mix deps.compile` and then `mix compile --warnings-as-errors`. Then warnings in dependencies won't bother your workflow :).

**Comment by Gazler** [comment]
@AndrewDryga The problem here is that the warnings was caused by the macros  used in the `MyApp.Router` module. This means that the warning is displayed as part of your application, and not as a warning in a dependency.

**Comment by wojtekmach** [comment]
@AndrewDryga `--warnings-as-errors` will not error if warnings came from deps. (Not sure if this behaviour changed between elixir versions.)
