### ISSUE TITLE
undefined function socket/3 on a fresh install

### ISSUE THREAD

**Issue by happysalada** [phoenixframework/phoenix#2890]
With the latest master, on a fresh mix phx.new, I get an error on compilation (when trying to run the first mix ecto.migrate)
Here is the following error
```
== Compilation error in file lib/angelhack2018_web/endpoint.ex ==
** (CompileError) lib/angelhack2018_web/endpoint.ex:4: undefined function socket/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```
I used the following guide to update the installer `https://github.com/phoenixframework/phoenix/blob/master/installer/README.md`

### Environment

* Elixir version (elixir -v):1.6.5
* Phoenix version (mix deps):1.3.0
* NodeJS version (node -v):9.4.0
* NPM version (npm -v):5.6.0
* Operating system:MacOS

Not sure if I it's me running the installer wrongly or if it's an actual error

**Comment by josevalim** [comment]
Fixed in master, thanks!
