### ISSUE TITLE
Want to create boilerplate

### ISSUE THREAD

**Issue by ghostrick** [phoenixframework/phoenix#2891]
We usually use Phoenix to develop a lot of projects.
So, we want to create a boilerplate.

We need a function that makes it easy to change the project name.
Does the solution exist?

**Comment by josevalim** [comment]
Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
