### ISSUE TITLE
Phoenix does not allow connections via 0.0.0.0

### ISSUE THREAD

**Issue by PeterDavidCarter** [phoenixframework/phoenix#2893]
### Environment

* Elixir version (elixir -v): 

Erlang/OTP 20 [erts-9.2] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:10]

Elixir 1.6.4 (compiled with OTP 19)

* Phoenix version (mix deps):

phoenix 1.3.2 (Hex package) (mix)

* NodeJS version (node -v):

v9.11.1

* NPM version (npm -v):

5.6.0

* Operating system:

Windows 10 Professional

### Expected behavior

Should serve to the address Cowboy server reports it is accessible on (0.0.0.0:4000)

### Actual behavior

Only accessible via localhost:4000 and even then without images

**Comment by StevenNunez** [comment]
Hi! You need to change a setting in your config.exs.

```
config :app, App.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4000]
```

That should do it.

**Comment by PeterDavidCarter** [comment]
The above does not help with the original problem and results in the following additional error output:

`[info] Running PhoenixApiWeb.Endpoint with Cowboy using http://0.0.0.0:4000
You have configured application :app in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :app exists or remove the configuration.`

**Comment by PeterDavidCarter** [comment]
On the other hand adding:

```config :phoenixApi, PhoenixApiWeb.Endpoint,
  http: [ip: {0, 0, 0, 0}, port: 4000]
```

Does not result in an error, but does not fix the problem either.

**Comment by josevalim** [comment]
I am wondering if we should convert 0.0.0.0 to localhost in the logged message.

**Comment by PeterDavidCarter** [comment]
I think that might be a good idea. The problem with images not serving isn't a huge issue for me since I needed to create a smith/docker build eventually anyway, but for beginners I think it's best if the logging message shows something that's most likely where the user can access from the browser.

**Comment by chrismccord** [comment]
I have always been able to serve `http://0.0.0.0:4000` by default with no issues (even without having to specifically bind to the adapter to this IP. This is sounding like a potential issues with Windows 10. Can you give us more information? Has this always been an issue for you? Only recently? Can you try a different browser? What about curling 0.0.0.0:4000?

**Comment by josevalim** [comment]
@chrismccord 0.0.0.0 is not theoretically correct though. It is fine to say you are listening on 0.0.0.0 (any address) but accessing it seems to be rather an accident if it works? 127.0.0.1 would be the best choice, as localhost may not be configured in /etc/hosts, but all practical purposes localhost should be fine.

**Comment by emilerousseau** [comment]
I have also tested this behaviour on the Windows 10 Linux Subsystem, with Ubuntu installed and am seeing the same results, though this of course does not exclude a Windows related cause...

I am also interested in what the practical benefit of serving to 0.0.0.0 may be. As Jose said for practical reasons localhost seems adequate for quickstart purposes, and I can't think of situations I've personally encounted where I would need to serve to all local addresses simultaniously, though it would be particularly useful if doing so were important to some features of this framework, or even if conceptually aligned to multiplexing and of discoverable interest.

I shall get dress, showered and breakfasted and will then run curl and perhaps a few other networking related functions then share the results in an update to this post.

I believe things just started to get interesting...

**Comment by PeterDavidCarter** [comment]
@chrismccord I have also tested this behaviour on the Windows 10 Linux Subsystem, with Ubuntu installed and am seeing the same results, though this of course does not exclude a Windows related cause...

I am also interested in what the practical benefit of serving to 0.0.0.0 may be. As @josevalim said for practical reasons localhost seems adequate for quickstart, and I can't think of situations I've personally encounted where I would need to serve to all local addresses simultaniously, though it would be particularly useful if doing so were important to some features of this framework, or even if conceptually aligned to multiplexing and of discoverable interest to students of the framework using it as a learning tool.

I shall get dressed, showered and breakfasted and will then run curl and perhaps a few other networking related functions then share the results in an update to this post.

I believe things just started to get interesting...

**Comment by michallepicki** [comment]
@PeterDavidCarter 0.0.0.0:4000 is not a usable **destination** IP address, so if it works as a curl target on a MacBook, it works only coincidentally (maybe you have it pointing to 127.0.0.1 in hosts file there or it is treated as a special case in Windows). See [IANA IPv4 Special-Purpose Address Registry](https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml#table-iana-ipv4-special-registry-1) for more info.
So this part is, as I believe, not a bug, since you are able to access the server through `localhost`.

But I'm not sure why images are not serving on Windows.

**Comment by x-ji** [comment]
OK it might be something related to Firefox instead of Phoenix. With Chrome I'm able to connect every time even with `localhost` instead of `0.0.0.0`.
