### ISSUE TITLE
I have an 500 error when my relation table UUID is invalid

### ISSUE THREAD

**Issue by shahryarjb** [phoenixframework/phoenix#2897]
### Environment

* Elixir version (v1.6.4):
* Phoenix version (1.3):
* NodeJS version (v9.3.0):
* NPM version (5.6.0):
* Operating system: mac os last update

### Expected behavior

it is likely that phoenix Json can't know its relation table which is UUID , For this purpose I have an error, but it know invalid UUID of id table.

please see this post which I have described.
https://elixirforum.com/t/how-to-stop-500-errors-when-uuid-doesnt-match/14072/27

I was forced to write this : 

```elixir 

    def changeset(struct, params \\ %{}) do
        struct
        |> cast(params, @all_fields)
        |> validate_required(@all_fields)
        |> validate_field_relational(:cms_learn_category_id)
    end


defp validate_field_relational(changeset, field) do
      field_concerned = get_field(changeset, field)
      case Ecto.UUID.cast(field_concerned) do
        :error ->
            add_error(changeset, field, "relational field is invalid")
        _ ->
          changeset
      end
    end
```

**Comment by chrismccord** [comment]
As this is not a Phoenix issue please refer to your forum post for support requests where folks there can assist you. Thanks!

**Comment by shahryarjb** [comment]
exactly, this is Phoenix business, I have done this for myself. Phoenix can't understand UUID well for the sake of this bug. I just wanted notice you.
