### ISSUE TITLE
Remove yarn integration from project generators

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#2904]
Today it is an implicit lookup and another thing to go wrong outside of the team's direct control. npm has had improvements as well since yarn's release, and users are free as always to use yarn on their new projects themselves.

**Comment by josevalim** [comment]
FWIW, it hasn't been merged yet: #1963  :)

**Comment by chrismccord** [comment]
Oh, even easier for me then! :D

**Comment by ryanwinchester** [comment]
As a yarn user, I am totally fine with this.

It's easy enough to say "no" when the installer asks to install dependencies. I've been doing it since forever anyway since I never use brunch 😅
