### ISSUE TITLE
Have we lost the option for a global @timestamps_opts ?

### ISSUE THREAD

**Issue by kswope** [phoenixframework/phoenix#2910]
Looks like we could put this in web/web.ex
```
def model do
  quote do
    use Ecto.Schema
    @timestamps_opts inserted_at: :created_at

    import Ecto
    import Ecto.Changeset
    import Ecto.Query
  end
end
```

This, probably for good reason, doesn't work in yourapp_web.ex

But it doesn't look like it works in yourapp.ex either.  Maybe this needs to be coordinated with ecto.

I think this is a really important feature for rails to phoenix rewrites.

Whoever decided to be edgy and use "inserted_at" instead of "created_at", I'm angry at you.

**Comment by josevalim** [comment]
You can still do it, as `@timestamp_opts` is still supported by Ecto, we just don't do it by default. For instsance, You can define a `MyApp.Schema` that you will use in your schemas and inject the `@timestamps_opts` thingy.

**Comment by kswope** [comment]
For posterity here is the relevant documentation, including an example of exactly what @josevalim suggested.

https://hexdocs.pm/ecto/Ecto.Schema.html#module-schema-attributes

**Comment by saxxi** [comment]
Yepp, to sum up the hint and the documentation, here's how to convert the app to follow the "Rails way".

In `lib/db/schema.ex`:

```
defmodule YourApp.Db.Schema do
  defmacro __using__(_) do
    quote do
      use Ecto.Schema
      @primary_key {:id, :binary_id, autogenerate: true} # UUID by default
      @foreign_key_type :binary_id # UUID by default
      @timestamps_opts [inserted_at: :created_at]
    end
  end
end
```

Then in your model:

```
defmodule YourApp.Users.User do
  use YourApp.Db.Schema
```
