### ISSUE TITLE
Code links on Phoenix hex docs bring you to 404

### ISSUE THREAD

**Issue by smorin** [phoenixframework/phoenix#2913]
### Environment

Hex docs for Phoenix: https://hexdocs.pm/phoenix/Phoenix.html

### Expected behavior

Click on code link (top right) on any phoenix documentation page should bring you the code for that page.  E.g.  https://hexdocs.pm/phoenix/Phoenix.html click ```</>``` 

### Actual behavior

Clicking code link brings you to a "404" E.g.  https://hexdocs.pm/phoenix/Phoenix.html click ```</>```   --> https://github.com/phoenixframework/phoenix/blob/v1.3.3/lib/phoenix.ex#L1

**Comment by chrismccord** [comment]
Thanks for the heads up! This was caused by a bad tag push on my part with the 1.3.3 release. I just fixed it and the links are now functional. <3 <3 <3
