### ISSUE TITLE
Fallback to LongPoll not working on iOS

### ISSUE THREAD

**Issue by michaelkschmidt** [phoenixframework/phoenix#2914]
There is a known issue on iOS Websockets with Proxy servers:
https://stackoverflow.com/questions/5574385/websockets-on-ios

We thought that phoenix.js would fall back to LongPoll, but it seems to ignore the failure

### Environment
* Operating system: iOS

### Expected behavior
If the websocket fails to connect, it should fall back to long poll:
https://hexdocs.pm/phoenix/js/#socket

### Actual behavior
No fallback occurs.

**Comment by josevalim** [comment]
@michaelkschmidt Have you enabled the long pool transport in your user_socket.ex? IIRC it comes disabled by default.

**Comment by chrismccord** [comment]
phoenix.js does not automatically fallback to the LongPoll transport if websocket connection fails, so it's available as a "fallback" in feature only. If you want to force long polling on the client you can do something like:

```javascript
import {Socket, LongPoll} from "phoenix"

let socket = new Socket("/socket", {transport: LongPoll})
```
If you want the auto fallback you are looking for, you could do:

```javascript
import {Socket, LongPoll} from "phoenix"
let socket = new Socket("/socket")
let connectionEstablishedOnce = false


let bindChannels = (socket) => {
  let roomChannel = socket.channel(...)
  roomChannel.on(...)
  roomChannel.join()...
}

let onConnectionEstablished = (socket) => {
  if(!connectionEstablishedOnce){
    connectionEstablishedOnce = true
    bindChannels(socket)
  }
}
socket.onOpen(() => onConnectionEstablished(socket))
  
socket.onError(() => {
  if(!connectionEstablishedOnce){
    socket.disconnect()
    let longPollSocket = new Socket("/socket", {transport: LongPoll})
    longPollSocket.onOpen(() => onConnectionEstablished(longPollSocket))
  }
})

socket.connect()
```

This would fallback if the websocket connection never fails to be established. If you need more exotic fallback such as "spotty" websockets, then that's something you would need to implement. Hope that helps!

**Comment by chrismccord** [comment]
Also to be clear, we "fallback" to LongPoll if `WebSocket` is not defined, such as old browsers.

**Comment by michaelkschmidt** [comment]
@josevalim @chrismccord Thanks for the clarification--we didn't understand that is what is meant by "fallback" 🙂.  We will try adding the "onError" hook you suggested

**Comment by maennchen** [comment]
@chrismccord I think it would be a good addition to have this fallback feature in the phoenix.js. (disabled by default, can be enabled with an option)

Would you consider a PR that implements this?

**Comment by chrismccord** [comment]
I don't have any plans to add auto fallback since it can be tricky to get right and I have no experience with the referenced proxies who don't handle WS, so the behavior of the fallback may not be the same across all networks. As this is possible today, I think it would be a great little js package someone could open source.

**Comment by ivanovv** [comment]
For anyone trying to copy code provided by @chrismccord  verbatim, there is one change you have to do – call `longPollSocket.connect()`

```js
socket.onError(() => {
  if(!connectionEstablishedOnce){
    socket.disconnect()
    let longPollSocket = new Socket("/socket", {transport: LongPoll})
    longPollSocket.onOpen(() => onConnectionEstablished(longPollSocket))
    longPollSocket.connect()
  }
})
```

**Comment by ivanovv** [comment]
My 2c on this issue – websockets not working for some reason is a harsh reality, and I do think this should be a part of Phoenix framework if we really claim that there is graceful fallback to longpoll and it `just works`. 
From my personal experience I cant tell I was absolutely sure `it just works` after all the presentations and conf talks I've watched about Phoenix

**Comment by arjan** [comment]
@ivanovv I agree with you, this is something that a framework should solve. Socket.IO for instance has reliability [listed](https://github.com/socketio/engine.io#goals) as one of their design goals. (they take a different approach though, first connect with long poll and at the same time upgrading the transport to WebSockets, if possible)

**Comment by michaelkschmidt** [comment]
@arjan I agree too.  The problem occurs on any iOS device using a proxy server, so it’s wide spread in corporate environments

**Comment by arjan** [comment]
@chrismccord any chance of putting this back on the table? I'm willing to contribute..

**Comment by chrismccord** [comment]
@arjan I'm willing to consider a PR if you're up for it. If it doesn't add too much complexity and is reliable I don't see a reason to avoid it. Thanks!

**Comment by chrismccord** [comment]
@arjan note, please make fallback opt-in if you decide to tackle it

**Comment by arjan** [comment]
My current line of thinking is this:

The tricky thing is getting the channels to join the new socket. In [your proposed solution](https://github.com/phoenixframework/phoenix/issues/2914#issuecomment-398111457) you create a new socket instance, and then you have to let the channels know that the socket switched underneath them. That can be quite hairy as the logic for joining the channel might be somewhere else entirely.

What I ended up doing today was patching the current socket instance with the LongPoll transport and just calling connect on it again:

```javascript
    socket.onError(() => {
      if (!connectionEstablishedOnce) {
        socket.disconnect(null, 3000) // an error code is needed otherwise onClose handlers kick in
        socket.transport = LongPoll
        socket.connect()
      }
    })
```

This way, the current channels will join automatically (due to their rejoinTimer), and do not need to be updated with the new socket instance. Seems to work OK for me, but I'm wondering whether this has any other implications.

**Comment by chrismccord** [comment]
That is fine since we would be handling this internally, where private access to the transport attribute or any future synching of the transport options would be done. So the above would be potentially problematic for user-land, but since we would own it, it's perfectly fine for us to do internally.

**Comment by arjan** [comment]
Okay, I'll see what I can do, although it will take some time, holiday season just started..

**Comment by arjan** [comment]
I'm sorry I never did the PR. However I have it working locally like this, I created a helper function to create a `Socket` instance:

```javascript
let socket = null
let connectionEstablishedOnce = false

export function getExternalSocket(config) {
  if (!socket) {
    const opts = {
      params: { },
      heartbeatIntervalMs: 5000,
      reconnectAfterMs: () => 1000
    }

    socket = new Socket(config.socket || `wss://mydomain.com/socket`, opts)

    socket.onOpen(() => {
      connectionEstablishedOnce = true
    })

    socket.onClose(() => {
      const params = { ...socket.params(), reconnect: true }
      socket.params = () => params
    })

    socket.onError(() => {
      if (!connectionEstablishedOnce) {
        // close the socket with an error code
        socket.disconnect(null, 3000)
        // fall back to long poll
        socket.transport = LongPoll
        // reopen
        socket.connect()
      }
    })

    socket.connect()
  }
  return socket
}
```

This basically switches over to longpoll when the WS connection errors and it has never successfully connected before.

**Comment by indrekj** [comment]
We're using this code to fallback to LongPoll but to also to try to upgrade it back: https://gist.github.com/indrekj/692c28aedfe5ec42e26d4502845cd06d

**Comment by jcsrb** [comment]
ended up using something similar to https://github.com/phoenixframework/phoenix/issues/2914#issuecomment-545632596

I suggest not falling back to LP after first error, we encountered intermittent WS initialization issues when using tethered mobile connections, you can access the number of tries `socket.reconnectTimer.tries` and fall back after a few

**Comment by arjan** [comment]
Also note that in my implementation the `reconnect: true` parameter gets set as a socket param, which is not ideal, consider this case:
The socket stores the reconnect param in the assigns so channels can differentiate on this parameter after join (for instance, as in my case: send the chat history or not). However, if a new channel is joined *after* a reconnect has happened, this new channel will also get the reconnect in its assigns, which is not true for this channel because it's a newly joined channel (from the channel's view its a clean connect).

**Comment by ivanovv** [comment]
should we reopen this one? it looks like there was some interesting discussion in this issue, and there were hopes that longpoll fallback would be part of the framework.

**Comment by josevalim** [comment]
Here is a solution that also works with LiveView:

```javascript
import { Socket, LongPoll } from 'phoenix'

let socket = liveSocket.socket
let fallbackToLongPoll = true
let originalOnConnError = socket.onConnError

socket.onOpen(() => {
  fallbackToLongPoll = false
})

socket.onConnError = (...args) => {
  if (fallbackToLongPoll) {
    // No longer fallback to longpoll
    fallbackToLongPoll = false
    // close the socket with an error code
    socket.disconnect(null, 3000)
    // fall back to long poll
    socket.transport = LongPoll
    // reopen
    socket.connect()
  } else {
    originalOnConnError.apply(socket, args)
  }
}
```

Note it uses privates APIs, so use it at your own risk.  Also, don't trust my JavaScript code. 😄

**Comment by collegeimprovements** [comment]
Symantec and a lot of other security proxies, blocks websockets by default or have a feature to do so. 
Security teams at various companies blocks them for various reasons. 
This breaks liveview apps and due to this reason we can't use LiveView for any external app 😐 😬 😐

**Comment by dognotdog** [comment]
Another interesting use case for this are captive portal pages: eg., in `iOS` captive portal browsers websockets don't work, but the `longpoll` fallback as in @josevalim's JS does.

**Comment by chrismccord** [comment]
This is now supported for the basic fallback with a new `replaceTransport` function, which can be called if websockets fail to connection and a connection has yet to be established:

```javascript

import {Socket, LongPoll} from "phoenix"

...
socket.onError((error, transport, establishedConnections) => {
  if(transport === WebSocket && establishedConnections === 0){
    socket.replaceTransport(LongPoll)
    socket.connect()
  }
}
```

**Comment by lpender** [comment]
Hey, I'm running into this issue (websocket 403s behind proxy) with {:phoenix, "~> 1.5.8"}, {:phoenix_html, "~> 2.11"}. 

The `socket` object doesn't seem to have `transport` or a `replaceTransport` method anymore. 

Is there an updated method here? 

Thanks

**Comment by lpender** [comment]
Thanks for this.

One thing I noticed, it looks like the type of `transport` needs to be updated for TypeScript:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/phoenix/index.d.ts#L42

It's looking for a string but it should be some sort of... function or constructor ?  

I'll see if I can figure out what the type should be but I wanted to flag it in the meantime.

**Comment by metabren** [comment]
Just in case anyone finds this issue after searching for how to do this for live view. In your JS somewhere:

```
import { Socket, LongPoll } from "phoenix"
import { LiveSocket } from "phoenix_live_view";

...
// setup liveSocket as per docs with CSRF & hooks

const socket = liveSocket.getSocket();
socket.onError((error, transport, establishedConnections) => {
  if (transport === WebSocket && establishedConnections === 0) {
    // this line does the replace _and_ the connect — note it's on the liveSocket, not the socket.
    liveSocket.replaceTransport(LongPoll);
  }
});
```

Then in your endpoint, add long polling support to your `socket/3` call:

```
socket("/live", Phoenix.LiveView.Socket,
  // websocket: [<options in here>],
  // add this line
  longpoll: [connect_info: [session: @session_options], log: false]
)
```

**Comment by sherbondy** [comment]
> Just in case anyone finds this issue after searching for how to do this for live view. In your JS somewhere:
> 
> ```js
> import { Socket, LongPoll } from "phoenix"
> import { LiveSocket } from "phoenix_live_view";
> 
> // setup liveSocket as per docs with CSRF & hooks
> 
> const socket = liveSocket.getSocket();
> socket.onError((error, transport, establishedConnections) => {
>   if (transport === WebSocket && establishedConnections === 0) {
>     // this line does the replace _and_ the connect — note it's on the liveSocket, not the socket.
>     // tiny typo in original code snippet: ** liveSocket > socket **
>     socket.replaceTransport(LongPoll);
>   }
> });
> ```

Tiny typo in the code snippet provided, think `liveSocket.replaceTransport`  was meant to be `socket.replaceTransport` yea?

**Comment by walter** [comment]
For reference, Longpoll Fallback has been officially implemented in Phoenix, but will only take effect for newly generated apps.

For existing apps, after upgrading to Phoenix 1.7.11 or later, you should be able to do something like this (adjust to your situation):

```Elixir
# in MyAppWeb.Endpoint, adjust the socket/3 call to configure longpoll in addition to web socket
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

```
```JavaScript
// in assets/js/app.js
// adjust LiveSocket configuration to declare`longPollFallbackMs` 
let liveSocket = new LiveSocket("/live", Socket, {
  longPollFallbackMs: 2500,
  params: {_csrf_token: csrfToken}
})
```

Also make sure your Phoenix JS packages are up-to-date as well.
