### ISSUE TITLE
Show a list of routes on the 404 page

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#2916]
When a user encounters a 404 error, we should show a list of the available routes in the application to assist with typos.

I've seen this feature in [buffalo](https://github.com/gobuffalo/buffalo) (for golang) and [rails](https://github.com/rails/rails/) (for ruby). I'm sure there will be other frameworks with this feature.

**Comment by beardedeagle** [comment]
This feature should be configurable. As in I should be able to disable it. It could be a security risk in some apps or just plain undesirable in prod.

**Comment by chrismccord** [comment]
It is only used with the existing `debug_errors: true`, which is only enabled explicitly in dev.exs by default so that is a non-issue
