### ISSUE TITLE
phx.new and other tasks / installer/lib/mix/tasks/ documentation is missing.

### ISSUE THREAD

**Issue by smorin** [phoenixframework/phoenix#2925]
The documentation for the mix task modules[1] in the installer are missing from: https://hexdocs.pm/phoenix/Phoenix.html

Is this documentation somewhere else?

- [1] https://github.com/phoenixframework/phoenix/tree/master/installer/lib/mix/tasks

**Comment by josevalim** [comment]
It would be nice if they were listed with the other tasks in the docs
though. Maybe we can do it with some elixirc_paths mangling.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by smorin** [comment]
@josevalim I'll try and look on how that works to see if I can submit a pr for that.

**Comment by chrismccord** [comment]
Closed via https://github.com/phoenixframework/phoenix/commit/641d27d364146926eea10020038f5a8beaa12ff1
