### ISSUE TITLE
mix docs => error

### ISSUE THREAD

**Issue by smorin** [phoenixframework/phoenix#2933]
mix docs generates an error see below.

smorin-local:phoenix smorin$ npm -v 
6.1.0
smorin-local:phoenix smorin$ node -v
v10.5.0
smorin-local:phoenix smorin$ mix docs
Docs successfully generated.
View them at "doc/index.html".
Docs successfully generated.
View them at "doc/Phoenix.epub".
sh: documentation: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! phoenix@1.3.0 docs: `documentation build js/phoenix.js -f html -o ../doc/js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phoenix@1.3.0 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/smorin/.npm/_logs/2018-06-25T23_38_38_726Z-debug.log

==============
Log file: /Users/smorin/.npm/_logs/2018-06-25T23_38_38_726Z-debug.log
==============

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'docs' ]
2 info using npm@6.1.0
3 info using node@v10.5.0
4 verbose run-script [ 'predocs', 'docs', 'postdocs' ]
5 info lifecycle phoenix@1.3.0~predocs: phoenix@1.3.0
6 info lifecycle phoenix@1.3.0~docs: phoenix@1.3.0
7 verbose lifecycle phoenix@1.3.0~docs: unsafe-perm in lifecycle true
8 verbose lifecycle phoenix@1.3.0~docs: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/smorin/code/elixirscratch/phoenix/assets/node_modules/.bin:/usr/local/Cellar/erlang/20.3.4/lib/erlang/erts-9.3/bin:/usr/local/Cellar/erlang/20.3.4/lib/erlang/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin
9 verbose lifecycle phoenix@1.3.0~docs: CWD: /Users/smorin/code/elixirscratch/phoenix/assets
10 silly lifecycle phoenix@1.3.0~docs: Args: [ '-c',
10 silly lifecycle   'documentation build js/phoenix.js -f html -o ../doc/js' ]
11 info lifecycle phoenix@1.3.0~docs: Failed to exec docs script
12 verbose stack Error: phoenix@1.3.0 docs: `documentation build js/phoenix.js -f html -o ../doc/js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:961:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
13 verbose pkgid phoenix@1.3.0
14 verbose cwd /Users/smorin/code/elixirscratch/phoenix/assets
15 verbose Darwin 17.6.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "docs"
17 verbose node v10.5.0
18 verbose npm  v6.1.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error phoenix@1.3.0 docs: `documentation build js/phoenix.js -f html -o ../doc/js`
23 error spawn ENOENT
24 error Failed at the phoenix@1.3.0 docs script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by chrismccord** [comment]
Did you install the npm deps in assets/ ? Pleas do this then try again:

```
$ cd assets
$ npm install
$ cd ..
$ MIX_ENV=docs mix docs
```

**Comment by smorin** [comment]
Thanks @chrismccord that worked I am adding commands in my pull request for the next guy to build it too.  https://github.com/phoenixframework/phoenix/pull/2934
