### ISSUE TITLE
Error in Endpoint cowboy_protocol terminates gen_server

### ISSUE THREAD

**Issue by jamesvl** [phoenixframework/phoenix#2935]
### Environment

* Elixir version (elixir -v): 1.6.6
* Phoenix version (mix deps): 1.3.3
* NodeJS version (node -v): 10.0.0
* NPM version (npm -v): 6.0.1
* Operating system: Fedora 28

### Expected behavior

Hitting any endpoint does not cause random gen_server crashes and 500 errors.

### Actual behavior

Endpoints randomly crash in Phoenix 1.3.3. The below error is all the logging I get from attaching to the erlang console in production:

```
17:00:32.537 [error] #PID<0.2445.0> running MyApp.Endpoint (cowboy_protocol) terminated
Server: example.org:80 (http)
Request: POST /path/8/any/337/here/37
** (exit) exited in: :gen_server.call(#PID<0.1956.0>, {:checkout, #Reference<0.2352882790.4029939713.206560>, true, 15000}, 5000)
    ** (EXIT) time out
```

The request can be a GET or a POST (or DELETE), could happen on any path, and unfortunately, truly was random - sometime the path would work and respond right away, other times it hit this timeout. Sometime is cropped up as soon as I restarted the vm, other times it would take several minutes before it started occurring. (Once it began, it would occur would occur more frequently.)

This didn't occur in development. The Phoenix instance was running on localhost behind an nginx reverse proxy, which would redirect any requests to port 80 to https on port 443. (Phoenix was on http only, configured to run on port 4001.)

The line `Server: example.org:80 (http)` in the output confuses me - nowhere was Phoenix configured to run on port 80, and incoming requests that triggered this error were on port 443.

I tried a variety of other changes, but finally downgrading Phoenix to 1.3.2 seems to have made the issue go away.

I'm happy to include any other details if it may help.

**Comment by michalmuskala** [comment]
This is most probably the same issue as https://github.com/elixir-ecto/db_connection/issues/127

**Comment by josevalim** [comment]
Let's continue the discussion in db_connection. It seems to be an OS issue, possibly an Erlang one, but not related to Elixir or Phoenix.

About the "Server: example.org:80", please check the `:url` configuration in your config/prod.exs.

**Comment by jamesvl** [comment]
@michalmuskala Yep, it's the same issue as you pointed out. I'll see if I can add anything there.

@josevalim My config/prod.exs has this for my `:url` config, which was part of my confusion: `url: [host: "my.example.org", scheme: "https", port: 443]` - I still have no idea where the port 80 would have come from the log, but it's probably unrelated.
