### ISSUE TITLE
The typespec of `Channel.terminate` is incorrect

### ISSUE THREAD

**Issue by tcoopman** [phoenixframework/phoenix#2937]
Phoenix version: 1.3.2

When I try to implement `terminate` on Channels like this: `def terminate({:shutdown, reason}, socket)` I get an error from `Dialyzer`:

```
[ElixirLS Dialyzer] The inferred type for the 1st argument of terminate/2 ({'shutdown',_}) is not a supertype of map(), which is expected type for this argument in the callback of the 'Elixir.Phoenix.Channel' behaviour
```

Looking at the behaviour it is indeed implemented as a `map` (https://github.com/phoenixframework/phoenix/blob/0e9dce51aa2f836222e5ec2ef88ea80b737ee4a7/lib/phoenix/channel.ex#L290) but the documentation and the inspected behaviour is that I do indeed get a tuple.

**Comment by chrismccord** [comment]
This was fixed in https://github.com/phoenixframework/phoenix/commit/966c86f4b1f8c303457a50c01ad194f0e2b54fdf#diff-cfa0128824823c13a720654d72db9564 and will be out soon with 1.4 . Thanks!

**Comment by tcoopman** [comment]
Thanks, didn't think of looking at master
