### ISSUE TITLE
mix phx.server leaks inotifywait processes

### ISSUE THREAD

**Issue by rbino** [phoenixframework/phoenix#2942]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.6.6 (compiled with OTP 21)
```
* Phoenix version (mix deps): 1.3.3
* Operating system: tested on a clean `elixir:slim` Docker image, it behaves the same on `elixir:latest` and on my Debian buster laptop.

### Steps to reproduce
```
$ docker pull elixir:slim
$ docker run -it elixir:slim bash
```
In the container
```
$ apt update && apt install inotify-tools procps -y
$ mix local.hex
$ mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez
$ mix phx.new test --no-ecto --no-brunch
$ cd test
$ mix phx.server
$ ps -e | grep inotify
```

### Expected behavior
`inotifywait` process should terminate when `mix phx.server` is aborted.

### Actual behavior
`inotifywait` remains active. Every time `mix phx.server` is executed, a new `inotifywait` process is spawned and never killed.

The project doesn't have brunch so there are no additional watchers in `dev.exs`

**Comment by josevalim** [comment]
Thank you @rbino! Can you please file this on https://github.com/falood/file_system? I am almost sure it is an issue there. When we start a port, we need to make sure the port is listening to stdin and that it closes itself when stdin is closed. There is a section about this in the Port module docs: https://hexdocs.pm/elixir/Port.html

**Comment by rbino** [comment]
Ok, can you give me some hints to see how and where that library is used in Phoenix so I can try to reproduce the problem with a smaller example?

Thanks

**Comment by josevalim** [comment]
@rbino Your application depends on phoenix_live_reload and phoenix_live_reload depends and starts file_system.

**Comment by rbino** [comment]
Fixed with https://github.com/falood/file_system/pull/54, I think we can close the issue.
