### ISSUE TITLE
Docs unclear about multiplex example

### ISSUE THREAD

**Issue by niahoo** [phoenixframework/phoenix#2952]
Hi, 

In the docs, we can see in [channel.ex:228](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/channel.ex#L228) an example about subscribing to different topics from within a unique channel.

I think the docs should mention more clearly that `put_new_topics` sole purpose is to avoid duplication.

**Comment by chrismccord** [comment]
Can you send a PR? Thanks!

**Comment by niahoo** [comment]
Sure :)

**Comment by willykaram** [comment]
@niahoo we are doing some work on the phx docs/guides today and tomorrow. We could potentially do a review of PR if you were able to send one.

**Comment by niahoo** [comment]
Hey so sorry this is deep in my todo-list and I'm not able to have internet everyday since i'm travelling. I will definitely send a PR "someday" but if you want a cleaner repo you may want to close this.

Sorry for the late answer !
