### ISSUE TITLE
Ensure guides use new Routes alias on route helper invocations

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#2955]

**Comment by Gazler** [comment]
The following files all have a reference to *_path, so may need updating.

- guides/channels.md
- guides/views.md
- guides/endpoint.md
- guides/controllers.md
- guides/routing.md
- guides/testing/testing_controllers.md
- guides/contexts.md
- guides/phoenix_mix_tasks.md

**Comment by mnussbaumer** [comment]
Perhaps I can do these changes if someone tells me what are the new path helpers?

**Comment by Gazler** [comment]
@mnussbaumer There are a few things that need changing.

Anywhere `*_path` is referenced in a controller, view or template, it should be changed from `page_path(conn...)` to `Routes.page_path(conn...)`

For example:

https://github.com/phoenixframework/phoenix/blame/acba7e150d82f94e1bfcd14a3dc9bc260e2585ab/guides/routing.md#L253

The example output from `mix phx.routes` should remain unchanged.

We will also need to update the explanation in routing.md in this section https://github.com/phoenixframework/phoenix/blob/acba7e150d82f94e1bfcd14a3dc9bc260e2585ab/guides/routing.md#path-helpers

**Comment by Gazler** [comment]
The line from iex in the path helpers section linked above should be changed from. `import HelloWeb.Router.Helpers` to `alias HelloWeb.Router.Helpers, as: Routes` 

This will reflect what is default in a new generated application.

**Comment by mnussbaumer** [comment]
@Gazler ok, so the import statements changed to alias and *_paths prefixed with `Routes.`, with exception of `phx.routes` task output, probably with a note? 

When does this need to be pushed? Just making sure, I'll be able to dedicate some time for it today, and remaining week, but will decide when exactly to start according to when you need this up.

**Comment by Gazler** [comment]
@mnussbaumer If you are able to do it this week, that'd be great. If you're not sure what to write for the updated explanation, just do a PR with the route changes and we can do the rest in a separate PR.

**Comment by mnussbaumer** [comment]
@Gazler , k, I will take a stab at the explanation too, and we go from there,
I'll be on this then 👍 

(I don't have much experience in PR'ing, but the procedure is to download the current master, branch, make the changes, and push the branch right?)

**Comment by Gazler** [comment]
@mnussbaumer Thanks.

You can find instructions for how to open a PR on https://github.com/phoenixframework/phoenix/blob/master/CONTRIBUTING.md#pull-requests

**Comment by Gazler** [comment]
Closed via https://github.com/phoenixframework/phoenix/pull/2957
