### ISSUE TITLE
Cyclically repeated connect to websocket after the falling of one of the nodes

### ISSUE THREAD

**Issue by DmitryKK** [phoenixframework/phoenix#2975]
I have cluster of two nodes. To start the cluster I use `libcluster`. 

To run first node i perform command:

`PORT=4000 iex --name first@127.0.0.1 -S mix phx.server`

To run second node i perform command:

`PORT=4001 iex --name second@127.0.0.1 -S mix phx.server`

Port of load balancer is 2085. Client listens this port.

Client establishes websocket connection and connects to my channel. Then I stop the node that the client has joined.

### Environment

* Elixir version (elixir -v): Elixir 1.6.3 (compiled with OTP 20)
* Phoenix version (mix deps): 1.3.3
* NodeJS version (node -v): 5.6.0
* NPM version (npm -v): 5.6.0
* Operating system: macOS High Sierra
* Load Balancer: HAProxy

### Expected behavior

Client will reconnect to websocket once time after its disconnection.

### Actual behavior

Client reconnects to websocket many times after its disconnection. Сyclically (see screenshot)

![default](https://user-images.githubusercontent.com/7626966/42897463-c4331114-8ac8-11e8-91d4-cea6b8afed2c.png)

**Comment by josevalim** [comment]
@DmitryKK if you need the client to stop connecting, then you need to explicitly tell the client to do so. Otherwise, for production setups, if a server temporarily goes down or the client loses internet connection, then we definitely want it to keep trying until a connection can be reestablished.

**Comment by josevalim** [comment]
Or are you saying that the client should successfully reconnect in the new node? I agree this should be expected but this is likely an issue with your proxy setup. How long does it take for a proxy to stop routing requests to a dead node? Can you check with HA Proxy that it has noticed your node is dead?

**Comment by DmitryKK** [comment]
@josevalim, sorry, I did not describe the problem completely. The thing is client establishes connect successfully and begins to receive messages from websocket. Then, a disconnect occurs unexpectedly because close event comes from server. And certainly the client reconnects. Why close event comes from server permanentlу like it's a dead node echo?

**Comment by chrismccord** [comment]
Yes this definitely sounds like an issue with the proxy. The client will reconnect with exponential backoff, forever, as designed since this is usually what you want. The server only sends close codes in certain circumstances, such as broadcasting "disconnect" to the socket id. Otherwise a crash in the transport would also kill the connection, but your logs would reflect that.
