### ISSUE TITLE
Add documentation for creating a Phoenix Socket client

### ISSUE THREAD

**Issue by PabloReszczynski** [phoenixframework/phoenix#2977]
The Phoenix/Elixir ecosystem would greatly benefit by allowing more languages to connect to it as clients.
For the time being we only have the official JavaScript implementation and some unofficial in Java, Elm, Swift, [etc](https://github.com/search?q=phoenix+socket).

Some of these implementation were done mostly by translating the JavaScript implementation to the target language, but it may be hard to the developers to keep up with any updates on the internal API of phoenix socket.

Having some documentation and specification of how to create a client in any language, would allow Phoenix to reach many platforms and help their developers to keep up with how Phoenix changes.

**Comment by chrismccord** [comment]
The JavaScript client is well documented feature wise, and our Transport documentation covers the wire protocol that ships by default (V2.WebSocketSerializer for example). Outside of this, a guide for writing your own client would be helpful for the small number of folks writing their own client, but it's not an area the team plans to devote time over other plans. Thanks!
