### ISSUE TITLE
Could not check origin for Phoenix.Socket transport. Can we log the origin?

### ISSUE THREAD

**Issue by steffenix** [phoenixframework/phoenix#2983]
### Issue

I am having an issue with the socket connection, I have some connections from a website that I ignore, I would like to know what's the origin. 

I have logged and found were the requests were coming from using a plug before `sockets` in the endpoint.ex file.

But, would it be possible to log the origin in: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/socket/transport.ex#L363
I can help.

### Environment

* Elixir version (elixir -v): Elixir 1.6.6 (compiled with OTP 20)
* Phoenix version (mix deps): 1.3.3
* Operating system: Mac os

**Comment by josevalim** [comment]
PR please :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by steffenix** [comment]
https://github.com/phoenixframework/phoenix/pull/2985
