### ISSUE TITLE
PubSub config required at compile time

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#2992]
If an application has the following in `config.exs`:

```elixir
# Configures the endpoint
config :config_test, ConfigTestWeb.Endpoint,
  render_errors: [view: ConfigTestWeb.ErrorView, accepts: ~w(html json)],
  pubsub: [name: ConfigTest.PubSub, adapter: Phoenix.PubSub.PG2, pool_size: 1]
```

Then the supervision tree looks like this (correctly using the PubSub name):

![config-exs](https://user-images.githubusercontent.com/477511/43637976-fcba05f4-970e-11e8-94e5-ef0d49765214.png)

However, if the same config us in the `MyApp.Endoint.init/2` function:

```elixir
  def init(_, config) do
    {:ok, Keyword.merge(config, default_config())}
  end

  defp default_config() do
    [
      pubsub: [name: ConfigTest.PubSub, adapter: Phoenix.PubSub.PG2, pool_size: 1]
    ]
  end
```

 then it looks like:

![config-init](https://user-images.githubusercontent.com/477511/43637988-0ae4d28a-970f-11e8-953d-e1bef616a80e.png)

In this case, a generic name of `Elixir.Supervisor` is used (this is as a result of `Module.concat(nil, "Supervisor")` from https://github.com/phoenixframework/phoenix_pubsub/blob/daedc139726f38b6de2a84ca8d9d1eeb4f5b6307/lib/phoenix/pubsub/pg2.ex#L50)

**Comment by josevalim** [comment]
If an adapter is given, we need to validate that the name exists.
