### ISSUE TITLE
Kind of idea. Credentials

### ISSUE THREAD

**Issue by soteras** [phoenixframework/phoenix#2993]
Hello everyone 😄  Rails 5.2 introduced a new feature called Credentials and I think that is a good feature for Phoenix (or elixir) sometimes we have a build server and prod server in *build server* we need environment variables to build a project with Distillery, the point is that's not easy to change environment variables to each project pipeline and usually we use (puppet, chef, etc) for that things. I'll be very happy if have a possibility to add the project credentials together with the project (encrypted). To learn more about credentials.

https://www.engineyard.com/blog/rails-encrypted-credentials-on-rails-5.2
https://github.com/rails/rails/pull/30067

**Comment by chrismccord** [comment]
Please send feature requests to the mailing list or open up a discussion on the forum to gauge feedback and ideas on new features. We reserve the issue tracker for issues. Thanks!
