### ISSUE TITLE
Raise when Plug.Router.forward/2 API is used instead of Phoenix.Router.

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#2995]
Currently, Plug.Router has a [forward/2](https://hexdocs.pm/plug/Plug.Router.html#forward/2) macro that looks like:

    forward "/foo", to: SomePlug, init_opts: [foo: :bar]

Phoenix also has a `forward` macro, with the following API:

    forward "/foo", SomePlug, foo: :bar

A user could easily be confused (for example. when reading documentation for a library based on Plug) and try to use the Plug arguments in the Phoenix Router.

This currently fails with:
```

== Compilation error in file web/router.ex ==
** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must contain only:

  * strings
  * integers representing Unicode codepoints
  * or a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[to: SomePlug, init_opts: [foo: :bar]]

    (elixir) lib/list.ex:821: List.to_string/1
    (phoenix) lib/phoenix/naming.ex:21: Phoenix.Naming.resource_name/2
    (phoenix) lib/phoenix/router/scope.ex:25: Phoenix.Router.Scope.route/8
    web/router.ex:56: (module)
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

Instead, we should detect if the forward macro that a user is attempting to use the Plug style arguments and raise with the changes required.

**Comment by soteras** [comment]
I think we could acept the plug style.
