### ISSUE TITLE
Phoenix.Presence crashes channel when a handle_out is not defined

### ISSUE THREAD

**Issue by mobileoverlord** [phoenixframework/phoenix#2997]
### Environment

* Elixir version (elixir -v): 1.6.6
* Phoenix version (mix deps): master
* NodeJS version (node -v): -
* NPM version (npm -v): - 
* Operating system: all

### Expected behavior

A channel should not have to define a handle_out for messages that are not in the intercepts.

### Actual behavior

The channel is crashing because it attempts to call the `handle_out/3`

Here is the channel that we are executing:
https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex

Here is the error that it receives:

```
{:undef, [{NervesHubDeviceWeb.DeviceChannel, :handle_out, ["presence_diff", %{joins: %{"device-1234" => %{metas: [%{connected_at: "1533827614", phx_ref: "8qCdoSyYMXU=", update_available: false}]}}, leaves: %{}}, %Phoenix.Socket{assigns: %{}}, channel: NervesHubDeviceWeb.DeviceChannel, channel_pid: #PID<0.855.0>, endpoint: NervesHubDeviceWeb.Endpoint, handler: NervesHubDeviceWeb.UserSocket, id: "device:device-1234", join_ref: "1", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: NervesHubWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V1.JSONSerializer, topic: "device:device-1234", transport: :websocket, transport_pid: #PID<0.851.0>}], []}, {Phoenix.Channel.Server, :handle_info, 2, [file: 'lib/phoenix/channel/server.ex', line: 300]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}
```

So it looks like its getting here and dying: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/channel/server.ex#L300

We have added this PR which fixed our issue currently.
https://github.com/nerves-hub/nerves_hub_web/pull/175

**Comment by chrismccord** [comment]
Your fix would consume the presence_diff, and make it not reach the client, unless somehow the message is being fastlaned *and* subscribed in the channel, which would be very odd. Are you using the stock websocket transport and pubsub adapter? Is the error 100% reproducible as soon as a presence joins? I will try to replicate and report back. Thanks!

**Comment by chrismccord** [comment]
To be clear, intercepting `presence_diff` is doable, but you would need to `push` the event down to the client to complete the loop. In your example it is filtered.

**Comment by chrismccord** [comment]
For posterity, this was caused by a missing `:fastlane` config in the linked application. It's wiring up its own Phoenix pubsub supervisor, instead of the one the endpoint bootstraps by default. In this case, the `fastlane: Phoenix.Channel.Server` option must be provided to the adapter config if using phoenix channels, so this is something we can help future folks avoid with a doc PR if @mobileoverlord wants to send one. I'm not sure which is the best place for it to live, Phoenix.Channel docs perhaps? Thanks!
