### ISSUE TITLE
Extensible schemes

### ISSUE THREAD

**Issue by tpitale** [phoenixframework/phoenix#2998]
Attempting to build a custom adapter for a new scheme (`coap`) on top of Phoenix master 1.4.0-dev.

This line hard codes the only scheme options as `http` and `https`:
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/supervisor.ex#L79

Is there a way to add other scheme/port mappings through configuration? I haven't be able to determine if it's possible reading the code.

Thanks!

**Comment by chrismccord** [comment]
The endpoint is only concerned with http, so in your case you would start your coap server in a separate supervision tree that you add to your own app supervisor. Make sense?

**Comment by tpitale** [comment]
I'm attempting to use phoenix, an endpoint/router etc, with an Adapter that handles `coap`. CoAP maps to http in a constrained set of features. I'm attempting to build an OSS library to adapt it to phoenix.

**Comment by chrismccord** [comment]
I'm not familiar enough with coap, but you're saying you'd be able to munge the data pipe into http requests that would be translated to a %Plug.Conn{} and sent thru the endpoint/router?

**Comment by tpitale** [comment]
Yeah, the `scheme` doesn't _really_ matter to these adapters other than in telling me to use `coap` or `coaps`.

**Comment by tpitale** [comment]
I suppose I could just "map" http => coap, and https => coaps.

**Comment by tpitale** [comment]
I dunno, still feels a little weird to me that the schemes are hardcoded. I get it as defaults since only Cowboy/2 is included as an adapter and it only handles http.

**Comment by tpitale** [comment]
For reference, this is the RFC for CoAP: https://tools.ietf.org/html/rfc7252

**Comment by josevalim** [comment]
What @chrismccord is saying is that all that code does is to start a process in a supervision tree. There is no need for it to be done inside the endpoint supervision tree. Instead you could do this:

```elixir
[
  MyApp.Endpoint,
  {Coap, opts}
]
```

This also applies to Phoenix. Phoenix could just move the http and https out of its supervision tree. There is not much reason for it to be there as well.

**Comment by tpitale** [comment]
@josevalim Let me try that.

**Comment by tpitale** [comment]
When I use `MyApp.Endpoint` in my own supervision tree, this code attempts to start it via the phoenix endpoint supervisor: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint.ex#L608-L621

**Comment by josevalim** [comment]
@tpitale yes, the endpoint will be started. And then you should start whatever other services alongside it.

**Comment by tpitale** [comment]
@josevalim This isn't _another_ service. This is the `Adapter` for this `Endpoint`.

The endpoint supervisor accepts an `adapter` config: `user_adapter`. I'm writing an adapter that _isn't_ for http.

**Comment by josevalim** [comment]
@tpitale there is no reason for it to have to be an adapter with Phoenix v1.4. :) We have profoundly streamlined the experience of starting any server. You could even start `Plug.Adapters.Cowboy2` easily in your supervision tree, outside of the Phoenix endpoint, and make it work with Phoenix. The whole work done in v1.4 is to guarantee exactly that we don't require Phoenix to know about each possible adapter in the world.

**Comment by josevalim** [comment]
Just to show an actual example, here is what I need to do to start my endpoint using https instead of relying on Phoenix doing it for me:

```elixir
    dispatch = [
      {:_,
       [
         {:_, Phoenix.Endpoint.Cowboy2Handler, {DemoWeb.Endpoint, []}}
       ]}
    ]

    children = [
      DemoWeb.Endpoint,
      {Plug.Adapters.Cowboy2,
       scheme: :http, plug: DemoWeb.Endpoint, options: [port: 4040, dispatch: dispatch, ref: :custom]}
    }
```

My proposal is for you to have something like PhoenixCOAP that you can start in your tree like this:

    {PhoenixCOAP, endpoint: DemoWeb.Endpoint}

And you should be able to bootstrap everything without relying on Phoenix internals or adapter API.

**Comment by tpitale** [comment]
I can do this easily enough:
`{CoAP.Phoenix.Listener, [:coap, DemoWeb.Endpoint]}`

But it's difficult to then get the config for DemoWeb.Endpoint with its configured `@otp_app`. There isn't an `endpoint.config` AFAICT to just get the full configuration defined for a given mix env.

And then, my bigger issue is having everyone who wants to use this code doing it this way. Why not use the built in patterns/tools/apis that Phoenix already provides?

Doing it the way I was suggesting means the `Endpoint` looks and works like any other in Phoenix, except we set the `adapter` option in the `config.exs`. That seems like a much better experience. It seems like this is exactly what the `adapter` option should be for.

**Comment by josevalim** [comment]
Why would you need to read all of its config though? If you really need it,
you can get the OTP app and then read the whole config directly from the
app environment. But I would first wonder why you need all of it.

Anyway, The reason why it should not be inside of Phoenix is because we
should figure out ways to break the already large supervision tree in the
endpoint apart, and not to provide more ways to shove more things inside of
it.

If it was any other app, adding entries to the supervision tree is the way
to go. Why does Phoenix have to be different? Let’s keep it simple and
clear.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by tpitale** [comment]
@chrismccord 

> Sorry, to be clear, your adapter can masquerade as http scheme and no changes are needed, right?

https://github.com/tpitale/coap_ex/blob/master/lib/coap/phoenix/adapter.ex#L3

But this also means any config (e.g., for port) has to be passed under the `:http` key in `config.exs`, which is a bit confusing.

**Comment by tpitale** [comment]
If I attempt to do this using the application supervision tree

```
children = [
  {CoAP.Phoenix.Listener, [CoapPhxTestWeb.Endpoint]}
]
```

I could try to get the config like this (based on this older issue https://github.com/phoenixframework/phoenix/issues/1029):

```
otp_app = endpoint.config(:otp_app)
config = Phoenix.Endpoint.Supervisor.config(otp_app, endpoint)
# then I can use config[:coap] to get port and other config
```

This raises an error on `:ets.lookup`, I'm guessing because the key doesn't exist yet for otp_app?

```
** (Mix) Could not start application coap_phx_test: CoapPhxTest.Application.start(:normal, []) returned an error: shutdown: failed to start child: CoapPhxTestWeb.Endpoint
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            (stdlib) :ets.lookup(CoapPhxTestWeb.Endpoint, :otp_app)
            (coap_phx_test) lib/phoenix/endpoint.ex:629: CoapPhxTestWeb.Endpoint.config/2
            lib/coap/phoenix/listener.ex:58: CoAP.Phoenix.Listener.config_for/1
            lib/coap/phoenix/listener.ex:29: CoAP.Phoenix.Listener.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by tpitale** [comment]
> This raises an error on :ets.lookup, I'm guessing because the key doesn't exist yet for :otp_app?

To fix this I seem to have to start the `Endpoint` as an http endpoint through the normal endpoint supervision _anyway_. Now I'm running two!

**Comment by tpitale** [comment]
This thread is all over the place. I'd like to think that I've shown in multiple ways that the most easy/direct path to make what I'm looking for possible and ergonomic for users is the PR I shared.

Unless there is a better, ergonomic, and supported way to get config for the endpoint, I don't think doing it through "direct" supervision (as opposed to phoenix's standard endpoint supervision) is the right path.

Closing this. Will open a new issue, depending on where the PR goes.

**Comment by josevalim** [comment]
> The coap adapter will not be part of the Phoenix project itself. I'm trying to integrate with Phoenix as simply as possible.

Yes, I understand your goals. What I am saying is that you don't need to run it as a Phoenix adapter. It can be a regular service. So in your diagram, "new" will be a sibling of "phx".

> To fix this I seem to have to start the Endpoint as an http endpoint through the normal endpoint supervision anyway. Now I'm running two!

You are correct, you need to start the endpoint, but **it is not true that the endpoint needs to run http**. You can remove the http/https configuration and all of the other services in the endpoint will run, but not the http/https ones. This is exactly the confusion we aim to solve. The endpoint is a bunch of individual separate services but because they are hidden inside the endpoint, there is an impression you can't run part of them or individually.

It is very likely in future releases we will move other services, such as pubsub, out of the endpoint too.

> This thread is all over the place. I'd like to think that I've shown in multiple ways that the most easy/direct path to make what I'm looking for possible and ergonomic for users is the PR I shared.

It isn't. :)

If you run `mix phx.new`, all you need to run your coap service is to **add** a single line in `APP_NAME/application.ex`. Will it start coap and http? Yes. If the user wants it, great. If they don't, they can also remove the http configuration. As I said, there is no reason to go through the indirection of adapters and try to hide even more services from the user.

**Comment by tpitale** [comment]
> It isn't. :)

Wow.

**Comment by josevalim** [comment]
Hi @tpitale, apologies if I sounded hostile. That's my bad. My intention was to politely disagree. In hindsight, saying "I disagree" would have been better.

I believe I have also shown in multiple ways that there is a better approach to this problem, that does not require to change Phoenix. One that is not coupled to Phoenix internals and it is clearer to users, with better ergonomics.

Of course, you are free to say "it isn't" too. :) We do not have to agree. I may even turn out that I am wrong. But hopefully it provides enough context for now to why we have rejected the proposal.

Have a good one!

**Comment by josevalim** [comment]
And just in case it is not clear, you can get the coap configuration in the endpoint like this: `endpoint.config(:coap)`. You do not need to access `Phoenix.Endpoint.Supervisor` (which is private, btw). Phoenix should provide all of the tools for you to address this without having to change it.

**Comment by tpitale** [comment]
Thank you for the clarification and the info on config.

In the case of config I was previously missing that the endpoint had to be started (as a worker?) so that :ets had the config for lookup.

**Comment by josevalim** [comment]
@tpitale the endpoint is always started as a supervisor. And it will have multiple workers inside. If there is no http/https configuration, then the http/https workers won't be started, but everything else is (pubsub, config, etc).
