### ISSUE TITLE
Broken link on page "hexdocs.pm/phoenix/up_and_running.html"

### ISSUE THREAD

**Issue by r0h4n** [phoenixframework/phoenix#3020]
### Environment

* Phoenix version (mix deps): 1.3.4

### Expected behavior
- On page https://hexdocs.pm/phoenix/up_and_running.html
- Search for link title  "_The next step_" 
- The `href` value should be `https://hexdocs.pm/phoenix/adding_pages.html` 

### Actual behavior
Current `href` value is http://www.phoenixframework.org/docs/adding-pages , this is the broken link.

**Comment by soteras** [comment]
@chrismccord could you close this issue please? https://github.com/phoenixframework/phoenix/pull/2958

**Comment by chrismccord** [comment]
We need to back-port #2958 to the v1.3 branch and re-push hex docs

**Comment by Gazler** [comment]
Done!
