### ISSUE TITLE
config_change and what it's for?

### ISSUE THREAD

**Issue by drozzy** [phoenixframework/phoenix#3025]
Just learning phoenix, coming from erlang/otp, it is not clear to me what the purpose of this function in application.ex file is:

```
  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MyAppWeb.Endpoint.config_change(changed, removed)
    :ok
  end
```

Some things I don't understand are:

- What is it for? (The doc states "Reload the endpoint configuration on application upgrades" - but what does that mean? What are application upgrades? Is it the same as `code_change` in OTP?)
- Who calls this function?
- How is this function called?
- Is there any way to not put it into my top-level `application.ex` file? (Since my app contains other OTP apps aside from phoenix app)

Thank you!

**Comment by josevalim** [comment]
It is a callback of the `Application` module: http://erlang.org/doc/apps/kernel/application.html#Module:config_change-3

Apparently its docs are missing from Elixir, we will update it, thanks!

**Comment by nelsonic** [comment]
Docs for `config_change/3` are: https://hexdocs.pm/elixir/Application.html#c:config_change/3 🔗 
But it's still unclear _where_ it's being invoked in our app ... 😞

**Comment by jayjun** [comment]
@drozzy @nelsonic The Erlang VM calls `config_change/3` when you do hot code upgrades (see the end of [Release Handling](http://erlang.org/documentation/doc-10.4/doc/design_principles/release_handling.html#updating-application-specifications) docs).

Phoenix generates the callback for you and `MyAppWeb.Endpoint.config_change` is there so Phoenix can migrate its state.

**Comment by nelsonic** [comment]
@jayjun thanks for clarifying/confirming that it's used during release.
Does that imply that if no config changes were made the function is _not_ invoked?
Or is it idempotent and therefore it does not matter how many times it's invoked?

**Comment by jayjun** [comment]
@nelsonic The docs that José helpfully [linked](https://github.com/phoenixframework/phoenix/issues/3025#issuecomment-413765640) says it’s only invoked after if there are changes. 🙂

It’s up to you to make `config_change` idempotent, non-idempotent or no-op even. It’s only called once every upgrade/downgrade, if that’s what you’re asking.
