### ISSUE TITLE
Phoenix.Presence.list/1 raising dialyzer warnings

### ISSUE THREAD

**Issue by whitepaperclip** [phoenixframework/phoenix#3027]
### Environment

* Elixir 1.7.2
* Phoenix 1.3.x, master
* Erlang 21.0.5

Given the following modules:

```elixir
defmodule MyAppWeb.Presence do
  use Phoenix.Presence,
    otp_app: :my_app,
    pubsub_server: MyAppWeb.PubSub
end
```

```elixir
defmodule MyAppWeb.RoomChannel do
  use MyAppWeb, :channel
  use Guardian.Phoenix.Socket

  # def join(args) ...

  @impl true
  def handle_in("new_msg", %{"body" => body}, socket) do
    recipient_id = body["recipient_id"]

    if is_nil(Presence.list(room)[recipient_id]) do
      Chat.conversation_read_by!(conversation, recipient_id, false)

      # Send push notification
      Notifications.broadcast!(:message_created, message: message)
    end
  end
end
```

The call to `Presence.list/1` causes Dialyzer to raise a warning. It can be suppressed by calling: `Phoenix.Presence.list(MyAppWeb.Presence, room)`, but this shouldn't be required.

`lib/my_app_web/channels/room_channel.ex:68: The call 'Elixir.MyAppWeb.Presence':list(_room@1::<<_:8,_:_*1>>) will never return since it differs in the 1st argument from the success typing arguments: (#{'__struct__':='Elixir.Phoenix.Socket', 'topic':=#{'__struct__':='Elixir.Phoenix.Socket', 'topic':=#{'__struct__':='Elixir.Phoenix.Socket', 'topic':=map(), _=>_}, _=>_}, _=>_})`

**Comment by AlexRiedler** [comment]
Since I was debugging this a bit as well; it seems dialyzer believes the correct type should be:

```ex
@spec list(%Phoenix.Socket{
  :topic => %Phoenix.Socket{:topic => %Phoenix.Socket{:topic => map(), _ => _}, _ => _},
  _ => _
}) :: no_return()
```

However that seems incredibly broken since that would break the type definition of Phoenix Socket itself. Which started to make me believe it was broken in dialyzer (but its hard to know how it's getting to this definition, or how it is being implied AFAIK).

Also if you remove:
```ex
def list(%Phoenix.Socket{topic: topic}), do: list(topic)
```

from the `__using__`, you get a no_return from dialyzer instead on list/2.

**Comment by AndrewDryga** [comment]
There is another dialyzer warning in the same module:
```
apps/talkinto_web/lib/talkinto_web/presence.ex:71:unmatched_return
Expression produces a value of type:

:ignore | {:error, _} | {:ok, pid()} | {:ok, pid(), _}

but this value is unmatched.
```

I think it comes from [`c:handle_diff/2`](https://github.com/phoenixframework/phoenix/blob/3ce1d5fe6881a6f5c7ccc41a18113795f26dceb0/lib/phoenix/presence.ex#L184).

**Comment by axelson** [comment]
I ran into this also and I believe it is fixed in https://github.com/phoenixframework/phoenix_pubsub/pull/116 which was released yesterday as part of phoenix_pubsub 1.1.1 https://hex.pm/packages/phoenix_pubsub/1.1.1

@whitepaperclip and @AndrewDryga does using phoenix_pubsub 1.1.1 fix this for you?

**Comment by chrismccord** [comment]
This is fixed with the release of Phoenix PubSub 1.1.1 as @axelson has shown, so please update. Thanks!

**Comment by whitepaperclip** [comment]
@chrismccord @axelson I updated Phoenix PubSub to 1.1.1, and while the original warning is gone, it's been replaced by another:

`lib/my_app_web/presence.ex:2: The inferred return type of init/1 ({'ok',#{'node_name':=binary(), 'pubsub_server':=atom(), 'task_sup':='Elixir.MyAppWeb.Presence.TaskSupervisor'}}) has nothing in common with {'error',_} | {'ok',pid()}, which is the expected return type for the callback of the 'Elixir.Phoenix.Presence' behaviour`

There's nothing in my `presence.ex` other than:

```elixir
defmodule MyAppWeb.Presence do
  use Phoenix.Presence,
    otp_app: :my_app,
    pubsub_server: MyAppWeb.PubSub
end
```

**Comment by whitepaperclip** [comment]
(This is on Phoenix 1.3.4 - I haven't checked the 1.4.0 RC yet.)
