### ISSUE TITLE
Phoenix Conn Params Conflates Array Values and String Values

### ISSUE THREAD

**Issue by mmacheerpuppy** [phoenixframework/phoenix#3029]
### Environment

* Elixir version (elixir -v): 1.7.1
* Phoenix version (mix deps): v1.3.4 
* NodeJS version (node -v): unused
* NPM version (npm -v): unused
* Operating system: Winodows 10

### Expected behavior 

No need to manually detect whether a parameter in URL query params is a list within a controller.

### Actual behaviour

It is necessary to manually detect whether a parameter in URL query params is a list or a string as a result of conflated treatment of key-value pairs. This means the developer must check whether each parameter in `params` is a list or a string, or result in unsafe code.

### Issue Summary

Consider the following query parameters are entered in Phoenix...

`?querytest=test&querytest2[]=test&querytest2=test3&querytest2[]=test4` 

From Phoenix params passed to the controller, these parameters will display as...

`%{"querytest" => "test", "querytest2" => ["test", "test4"]}`

But now consider the following query parameters... 

`?querytest=test&querytest2[]=test&querytest2=test3`

The Phoenix params passed to the controller become...

`%{"querytest" => "test", "querytest2" => "test3"}`

The result of this is if a developer wants to use the `params` passed within the `params` controller, then the developer must implement manual detection on whether the value at `querytest2` is a string or a list. The reason for this is Phoenix makes no distinction to the keys of query parameters whether the parameters are entered in list form i.e. `query[]` or string form `query`. 

Now consider the following argument...

To developers, it is intuitive to make use of the query-parameters passed to Phoenix controllers. However, as we have demonstrated the result is developers can't tell uniquely from the `params` map whether or not the value is a list. This is problematic since developers may write code to handle the string in the query `?query_string=my_string`, when the user passes in `?query_string?[]=my_string`. This can result in enumeration errors: we do not expect our `params` in the Phoenix controller to be a list, and vice versa.

The default Elixir library handles this issue more elegantly by not conflating URL query parameters. For instance, when passing our code to `URI.decode_query`  we are greeted with the map `%{"querytest" => "test", "querytest2" => "test3", "querytest2[]" => "test4"}`. We thus do not have to manually handle the use case of whether or not `querytest2` is equal to an array.

I'm not entirely sure how this issue could be dealt with since it might break a lot of Phoenix controller code by making a rash update. But it means potentially we could cause internal errors on a lot of websites by simply passing an array when a controller expects a string or vice versa. One suggestion would be to meaningfully merge both the the way Phoenix and URI.decode handle query string parameters, such that we include both `querystring` (from Phoenix) and `querystring[]` (similar to URI.decode) keys in the `params` map passed to the controller, but this would likely result in a lot of overhead for the Phoenix Web Framework. 

The advantage would be, we know that our `params` key is an array in virtue of which key it is so we can use effective pattern matching on `params`, and not manual value type checking, which I'm willing to place credence not everyone has implemented for all of the parameters they expect the values to be either strings or arrays, potentially all of them.

### Example 

Using `URI.decode` I am able to handle my connection query parameters with inclusive pattern matching that couldn't be achieved with the default Phoenix web server params, without of course the manual type checking of keys for their data-types the keys for which I argued above could be _arbitrary_... 

```
    # We use URL.decode_query in order to avoid conflated treatment of whether our variables are an array or a string. This allows for effective pattern matching (we don't need to worry about what if "dogs" is an array). 
    query_params = URI.decode_query(conn.query_string)
    # Pattern match query params to check expected values in different domains.
    case query_params do
      # Rules for type "Dog". This is where, without URI.decode_query, type could have been an array.
      %{type: dog = "A good boy"} ->
        my_func_expects_a_string(dog)
        # Do something with the connection
       # Rules for type "Dog". This is where, without URI.decode_query, type could have been an array.
      %{type[]: dogs = _]} ->
        my_func_expects_an_array(dogs)
        # Do something with the connection
      _ ->
         conn
        |> put_status(:not_found)
        |> put_view(DfmsWeb.ErrorView)
        |> render("404.html")
      end
```

**Comment by mmacheerpuppy** [comment]
<!--
### Environment

* Elixir version (elixir -v): 1.7.1
* Phoenix version (mix deps): latest 
* NodeJS version (node -v): unused
* NPM version (npm -v): unused
* Operating system: Winodows 10

### Expected behavior

No need to manually detect whether a parameter in URL query params is a list within a controller.

### Actual behavior

It is necessary to manually detect whether a parameter in URL query params is a list or a string as a result of conflationary treatment of key-value pairs. This means the developer must check whether parameters are a list or a string. 

### Summary and Examples

Consider the following query parameters are entered in Phoenix...

`?querytest=test&querytest2[]=test&querytest2=test3&querytest2[]=test4` 

From Phoenix params passed to the controller, these parameters will display as...

`%{"querytest" => "test", "querytest2" => ["test", "test4"]}`

But now consider the following query parameters... 

`?querytest=test&querytest2[]=test&querytest2=test3`

The Phoenix params passed to the controller become...

`%{"querytest" => "test", "querytest2" => "test3"}`

The result of this is if a developer wants to use the `params` passed within the `params` controller, then the developer must implement manual detection on whether the value at `querytest2` is a string or a list. The reason for this is Phoenix makes no distinction to the keys of query parameters whether the parameters are entered in list form i.e. `query[]` or string form `query`. 

Now consider the following argument...

To developers, it is intuitive to make use of the query-parameters passed to Phoenix controllers. However, as we have demonstrated the result is developers can't tell uniquely from the `params` map whether or not the value is a list. This is problematic since developers may write code to handle the string in the query `?query_string=my_string`, when the user passes in `?query_string?[]=my_string`. This can result in enumeration errors: we do not expect our `params` in the Phoenix controller to be a list, and vice versa.

The default Elixir library handles this issue more elegantly by not conflating URL query parameters. For instance, when passing our code to `URI.decode_query`  we are greeted with the map `%{"querytest" => "test", "querytest2" => "test3", "querytest2[]" => "test4"}`. We thus do not have to manually handle the use case of whether or not `querytest2` is equal to an array.

I'm not entirely sure how this issue could be dealt with since it might break a lot of Phoenix controller code by making a rash update. But it means potentially we could cause internal errors on a lot of websites by simply passing an array when a controller expects a string or vice versa. One suggestion would be to meaningfully merge both the the way Phoenix and URI.decode handle query string parameters, such that we include both `querystring` (from Phoenix) and `querystring[]` (similar to URI.decode) keys in the `params` map passed to the controller, but this would likely result in a lot of overhead for the Phoenix Web Framework. 

The advantage would be, we know that our `params` key is an array in virtue of which key it is so we can use effective pattern matching on `params`, and not manual value type checking, which I'm willing to place credence not everyone has implemented for all of the parameters they expect the values to be either strings or arrays, potentially all of them.

**Comment by chrismccord** [comment]
By default, the `Plug.Parser` uses `Plug.Conn.fetch_query_params`, which calls `Plug.Conn.Query.decode`, providing the current behavior. To get what you want, you could plug your own query parser plug *above* the Plug.Parser in your endpoint and use the decode you shared above to achieve the desired results. Using your own plug will work perfectly since once you parse the query params yourself and populate conn.query_string, the later call inside Plug.Parsers will be a noop. As this is not an issue in itself in plug or phoenix, your best bet is a custom plug to handle query params exactly as you wish. Hope that helps!
