### ISSUE TITLE
In Phoenix1.3.4: mix ecto.create error in a new fresh project with an Ecto.InvalidURLError( unsupported query parameter `sslmode`)

### ISSUE THREAD

**Issue by mayulu** [phoenixframework/phoenix#3039]
Hi,

After I started a new phoenix project with `mix phx.new qbme`, `cd qbme`, and then modify the `config/dev.exs`, changed the database config part:
```
config :qbme, Qbme.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "xxx",
  password: "xxxxxxx",
  database: "qbme_dev",
  hostname: "localhost",
  pool_size: 10
```
And then run `mix ecto.create`, I got the error:
```
** (Ecto.InvalidURLError) invalid url postgres://xxx:xxxxxxxxx@127.0.0.1:5432/postgres?sslmode=disable, unsupported query parameter `sslmode`
```

### Environment
* Elixir version : 1.7.3
* phoenix version: 1.3.4
* Database and version (PostgreSQL):  10.5
* Ecto version : 2.2.10
* phoenix_ecto: 3.3.0
* Database adapter and version : postgrex-0.13.5
* Operating system: macOS 10.13.6

Anyone can give a glue?

Thanks

**Comment by Gazler** [comment]
Closing as this issue is also open on Ecto. https://github.com/elixir-ecto/ecto/issues/2672
