### ISSUE TITLE
Using the wrong url: settings in config results in problems for cache_static_manifest

### ISSUE THREAD

**Issue by Preen** [phoenixframework/phoenix#3041]
Elixir 1.6.4
Phoenix 1.3.4
NodeJS v10.9.0
NPM 3.10.9
OSX 10.13.6 and Ubuntu 16.04 LTS

This is maybe the right behaviour off the app but it was hard to debug as I couldnt see any error when generating the digest/releasing the app.

I used his setting inside the the `App.Endpoint`
`url: [scheme: "https", host: {:system, "MANAGER_HOST"}, port: {:system, "MANAGER_HOST_PORT"}],`

Which resulted in the app not picking up digested assets but instead used e.g `app.js`. So the app worked "fine" except for the digest.

When I switched to
`url: [host: System.get_env("MANAGER_HOST"), port: System.get_env("MANAGER_HOST_PORT")],`
The assets started working as expected in production env with digested file names.

So what could potentially be some kind improvement: is warning the user about this?

**Comment by chrismccord** [comment]
The url configuration should have no coupling to the asset manifest. Can you double check that your original config reproduces the problem? For example, it's possible it was a fluke or your deploy or similar. Thanks!

**Comment by alexgaribay** [comment]
@Preen I'm not able to replicate what you're describing from the sample repo. Could you please list out the commands you are running? Additionally, are you attempting to do a Distillery release as part of the commands?

**Comment by josevalim** [comment]
Closing until we get more information. Thank you!
