### ISSUE TITLE
Recommended install method from docs installs an unreleased Phoenix version

### ISSUE THREAD

**Issue by macbem** [phoenixframework/phoenix#3043]
In Phoenix docs, it's recommended to use `mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez` to install Phoenix. 

However, when I run that command, Phoenix 1.4 is installed and error from #2991 appears.

IMO the recommended install method should always install the latest stable release and it's not the case here, so users have to manually downgrade to 1.3.4 or install Phoenix 1.4 straight from the repo manually.

I don't think it matters, but I've stumbled upon this issue on the latest Elixir & OTP releases from Brew on macOS High Sierra.

**Comment by chrismccord** [comment]
mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez installs the latest stable release, which is 1.3.4, which does not contain the help task. If you install the 1.4-dev release, it will indeed show the help task:

    $ mix archive.uninstall phx_new
    $ mix archive.install https://github.com/phoenixframework/archives/raw/master/1.4-dev/phx_new.ez

thanks!

**Comment by macbem** [comment]
@chrismccord please try again using the newest Elixir release - I'm quite certain that command installs Phoenix 1.4 instead of 1.3.4 - I've tried it. When you have Phoenix 1.4 installed using that command, none of Phoenix-related mix tasks are working because of missing documentation.

```

**Comment by chrismccord** [comment]
Can you include the exact output of the shell commands you ran so I can reproduce? Before you run the install, please also ensure you have done the uninstall command. Thanks!

**Comment by macbem** [comment]
![screen shot 2018-08-31 at 16 45 31](https://user-images.githubusercontent.com/12464061/44919238-4d856c00-ad3d-11e8-96e7-8634f8d6485d.png)

@chrismccord let me know if you need any more details.

**Comment by chrismccord** [comment]
Also note, the 1.4-dev url above is a little stale, but if you build the archive on master, you should indeed get the docs

**Comment by chrismccord** [comment]
The command you ran install the latest stable 1.3.4, which you can verify with `mix phx.new -v`

**Comment by macbem** [comment]
Oh, I see - you're right. I still don't get the docs when I install Phoenix using this method, which is probably another issue, but it still could use a fix. I worked around that by cloning Phoenix repo and running archive installs from `installers` folders directly.

**Comment by chrismccord** [comment]
```
$ mix help phx.new

                                  mix phx.new                         

Creates a new Phoenix project.

...

Location: /Users/chris/.kiex/mix/archives/elixir-1.7.3/phx_new-1.4.0-dev/phx_new-1.4.0-dev/ebin
```

**Comment by chrismccord** [comment]
Yes, the 1.4-dev archive hasn't been pushed with the latest commits, so to get the absolutely latest dev archive you need to build from the installer directory. Glad you got things sorted out!

**Comment by macbem** [comment]
I don't quite understand - you're mentioning `1.4-dev`, while we verified that this command installs Phoenix v. 1.3.4 😄

**Comment by macbem** [comment]
And I'm having the no-docs issue on Phoenix 1.3.4 installed using that method :)

**Comment by chrismccord** [comment]
To be clear:

The following command installs the latest stable phoenix release, which right now is 1.3.4:
     
    mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez

The following command installs the 1.4-dev installer, which we only push occasionally, so it won't necessarily be update to date with HEAD on master:

    mix archive.install https://github.com/phoenixframework/archives/raw/master/1.4-dev/phx_new.ez


Phoenix <= 1.3.4 does not include the commit on master that enables the help task, so only an archive built from master will provide it. Make sense?

**Comment by macbem** [comment]
Either I don't understand something or something is wrong - probably the first part, but let me go through that one last time.

Steps:
- I removed previously installed archives
- I installed the latest stable Phoenix release - 1.3.4

Problem:
When I run *any* `mix phx.*` command (not `mix help phx.*`), I get the no docs error - it looks like those mix tasks can't run without docs for some reason or something is messed up in another place.

Solution:
Clone Phoenix repo manually, checkout `v.1.3.4` branch, go to `installer` dir, uninstall currently installed Phoenix archive, run `MIX_ENV=prod mix do archive.build, archive.install` - now `mix phx.*` and `mix help phx.*` commands are working again.

Question:
Shouldn't `mix phx.*` tasks work OOTB after running `mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez` (which means installing stable, 1.3.4)?

**Comment by josevalim** [comment]
I believe this is the exact same issue as #2991. :)

**Comment by josevalim** [comment]
In a nutshell, the archive `https://github.com/phoenixframework/archives/raw/master/phx_new.ez` was compiled used an old Elixir version and more recent Elixir versions have a new documentation format. If you install the archive manually from your machine it should work (or wait until we provide the new instructions for installation).

**Comment by macbem** [comment]
@josevalim Thanks, I now get why the error was happening 😄I just wanted to make sure to point it out so that others experiencing it would know how to handle it. Thanks for working on making Elixir & Phoenix even more awesome @josevalim @chrismccord :)
