### ISSUE TITLE
Log and instrument UserSocket.connect

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#3046]

**Comment by mmartinson** [comment]
Is this a note for yourself/core team or something you'd be interested in getting a contribution for? If the latter it could be something I could take on, and I'd ask if there were any existing examples in the codebase of patterns you'd like to see.

**Comment by chrismccord** [comment]
This is more a note for me :) We generally tag up-for-grab issues with `level:*` so keep an eye out!
