### ISSUE TITLE
Phoenix.js docs are outdated

### ISSUE THREAD

**Issue by brianpeiris** [phoenixframework/phoenix#3054]
Please update the docs at https://hexdocs.pm/phoenix/js/
They seem to be outdated/incomplete. For example, [docs for Channel.join](https://hexdocs.pm/phoenix/js/#Channel#join) don't exist.

**Comment by brianpeiris** [comment]
Hmm, there's confusing going on in the git history. 1.3.4 was released in Aug 2018 but the [v1.3.4 tree](https://github.com/phoenixframework/phoenix/tree/v1.3.4) contains a phoenix.js that was last updated in July 2017. On the other hand the master branch contains a phoenix.js that was updated in June 2018 with proper documentation.

**Comment by chrismccord** [comment]
This has been fixed on master and will be pushed when we publish 1.4. Thanks!

**Comment by xfumihiro** [comment]
@chrismccord can you publish 1.4.0-rc on npm before 1.4?

**Comment by Gazler** [comment]
The 1.4.0-rc.0 docs are available athttps://hexdocs.pm/phoenix/1.4.0-rc.0/js/

**Comment by xfumihiro** [comment]
@Gazler thanks but I'm looking to install it with **yarn add phoenix**
