### ISSUE TITLE
config with `server: true` breaks tests and doesn't work as expected

### ISSUE THREAD

**Issue by iguberman** [phoenixframework/phoenix#3063]
### Environment

* Elixir version (elixir -v): Elixir 1.7.1
* Phoenix version (mix deps):phoenix 1.3.4
* NodeJS version (node -v): v7.8.0
* NPM version (npm -v): 4.2.0
* Operating system: OS X El Captain 10.11.6

### Expected behavior

Enabling phoenix server from config with `server: true` is equivalent to running `mix phx.server` from another terminal

### Actual behavior

After switching to `server: true`, suddenly the tests are breaking during some assertions down the line (no problems with executing SQL statements).   So something is very different about how the server is run. 
When I try to analyze the DB it is empty even though I'm in the middle of a test case (by putting an `IO.gets` there)  after a successful insert.   I'm a bit confused because I'm populating the DB schema with a flyway script and it works, but the db I was using during `mix phx.server` seems unaffected by my test run with `server: true` even though SQL statements are successful.

**Comment by chrismccord** [comment]
What errors are you receiving? What does your test case look like that failing? Just guessing without seeing the code, but if you changed your tests from using the ConnTest `get/post` and friends to actual HTTP requests against the test web server, then Ecto (which I assume you're using), won't be using the Sandbox pool for the requests. So you need to do more work to have the Ecto sandbox work for full acceptance tests, which the Ecto sandbox plug takes care of for you https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/sql/sandbox.ex . As this does not appear to be an issue with Phoenix, I'm closing, but feel free to follow up if things still look to be an issue for you. Thanks!

**Comment by iguberman** [comment]
Hi Chris,  thanks so much for getting back to me! :) 

It's an integration test with `{:httpotion, "~> 3.1.0"}`,   I didn't change the test at all and I have not been using `ConnTest` at all, I skipped unit testing alltogether for this project due to lack of time.    The only thing I changed was instead of running `mix phx.server` in another terminal, I enabled the server in `config/test.exs` with `server: true` so that I can run the test with one command and also for CI purposes -- assuming that it will have the same effect, but it doesn't seem to be the case.   The tests started logically breaking from doing that (which could be due to some fragilities in the test itself which is ok) -- however I can't troubleshoot it because the DB appears empty despite all the successful SQL queries that I'm sure I've run.   It's the same DB with the same credentials, but it's empty.   Isn't `server:true` running a server against the same DB specified in config ("localhost" 5432, user postgres, etc.   same db name)    It has to because I'm populating it with flyway scripts, (had `ecto.migrate` disabled from the start), if it wasn't then ALL my SQL queries would be failing, but it's not the case.   Why is the DB empty when I try analyzing it during a test case -- beyond me.

**Comment by webdeb** [comment]
A small repo to reproduce would say more then thousands words :)

**Comment by chrismccord** [comment]
@iguberman in your other terminate are you running with `MIX_ENV=test` or with the env var exported to `test`? Otherwise, your normal flow of running `mix phx.server` in another shell was running the dev server. When you run under the app under tests, by default we set up the Ecto sandbox for you, which will wipe the DB across transactional tests, so this is definitely sounds like the issue. It's not an issue with phoenix, but something you'll need to take care with now that you're running the app in the test env, such as seeding data before test cases and using the sandbox plug. Does that make sense?

**Comment by chrismccord** [comment]
Assuming your `mix phx.server` was previously running in `dev`, you could also get this same behaviour with `server: true` by removing the sandbox calls in test_helper.exs, and, data_case.exs, conn_test.exs

**Comment by iguberman** [comment]
Hi Chris,

Yes, that did it!  After removing all the Sandbox calls I see my dev DB being populated.    Thanks so much for your help :)      

Best,
Irina.
