### ISSUE TITLE
`Channel >  Joining Channels` guide won't work

### ISSUE THREAD

**Issue by foliolin** [phoenixframework/phoenix#3070]
### Environment

* Elixir version (elixir -v): 1.7.3
* Phoenix version (mix deps): 1.3.4
* NodeJS version (node -v): v10.11.0
* NPM version (npm -v): 6.4.1
* Operating system: OSX 10.13.6 (17G65)

### Expected behavior

1. Generate a new project with `mix phx.new --no-ecto hello`
2. Follow [the guide](https://hexdocs.pm/phoenix/channels.html#tying-it-all-together) to uncomment `  channel "room:*", HelloWeb.RoomChannel`
3. Follow the guide to create the lib/hello_web/channels/room_channel.ex file
4. Start server via `mix phx.server`
5. Open http://localhost:4000/ in a browser
6. See the phoenix welcome page

### Actual behavior

1. Browser won't stop loading
2. `[error] Ranch protocol :error of listener HelloWeb.Endpoint.HTTP (cowboy_protocol) terminated
** (exit) :undef` is shown in the terminal

**Comment by Gazler** [comment]
I can't reproduce this locally for a new project. Do you have a repo that reproduces the issue?

**Comment by chrismccord** [comment]
Please let us know if you are have more information and care share a repo that reproduces this. Thanks!

**Comment by tmock12** [comment]
@foliolin I ran into the same issue after updating my OS to Mojave. I was able to fix it with:
```shell
mix deps.clean --all && mix deps.get
```

maybe something to do with system libraries? No idea..but give that a try.
