### ISSUE TITLE
Unclear documentation on 'get_csrf_token' and some related functions

### ISSUE THREAD

**Issue by Qqwy** [phoenixframework/phoenix#3073]
I had a problem related to CSRF tokens, so I started browsing through the docs. Doing that, I noticed:

[get_csrf_token/0](https://hexdocs.pm/phoenix/Phoenix.Controller.html#get_csrf_token/0)
which is documented as:
> Gets the CSRF token.

as well as
[delete_csrf_token/0](https://hexdocs.pm/phoenix/Phoenix.Controller.html#delete_csrf_token/0)
which is documented as:
> Deletes any CSRF token set.

Neither of these make clear to an application developer what the functions do, and when (/if) they should be used in application code.

----

Obviously, this is a low-priority, low-hanging-fruit issue, but I stumbled across it so I wanted to let you know :slightly_smiling_face:.

**Comment by akshbn** [comment]
I would like to take this up.

**Comment by Gazler** [comment]
@akshbn It's all yours!

**Comment by akshbn** [comment]
Please check if the explanation below is satisfactory.

**get_csrf_token()**
Checks the Process dictionary, of the process handling the current request, for an existing csrf token. If the token exists, it is returned. If not, a new token is generated and stored in the process dictionary.

Example

```
token = get_csrf_token()

render conn, “index.html”, token: token
```

**delete_csrf_token()**
Deletes the CSRF token from the process dictionary.
The token gets force deleted only after a response has been sent.

**Comment by josevalim** [comment]
It is important to keep the first paragraph concise, as it is used as summary. So for get_csrf_token i would suggest:

> Gets or generates a CSRF token.
>
> If a token exists, it is returned. If not, a new token is generated and stored in the process dictionary.

Everything else looks great. Please do send a PR!

**Comment by akshbn** [comment]
Thanks for the feedback @josevalim. Will send a PR right away.
