### ISSUE TITLE
Error with Cowboy2Adapter on 1.4.0-rc.0 with Cowboy 2.5.0 

### ISSUE THREAD

**Issue by arathunku** [phoenixframework/phoenix#3090]
### Environment

* Elixir version (elixir -v): `Elixir 1.7.1 (compiled with Erlang/OTP 19)`
* Phoenix version (mix deps): `1.4.0-rc.0`
* NodeJS version (node -v): unrelated
* NPM version (npm -v): unrelated
* Operating system: unrelated

### Expected behavior

Phoenix 1.4 working out of the box with the newest Cowboy.

Works correctly (as far as I've tested) with Cowboy 2.4 and 2.3.

Cowboy 2.5.0 is fetched by default when using `~> 2.3`. That's based on [upgrade instructions](https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e)

### Actual behavior

```
** (Mix) Could not start application my_flat: MyFlat.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyFlatWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, MyFlatWeb.Endpoint.HTTP}
        ** (EXIT) an exception was raised:
            ** (UndefinedFunctionError) function :ranch_listener_sup.start_link/6 is undefined or private
                (ranch) :ranch_listener_sup.start_link(MyFlatWeb.Endpoint.HTTP, 100, :ranch_tcp, [num_acceptors: 100, max_connections: 16384, port: 4001], :cowboy_clear, %{env: %{dispatch: [{:_, [], [{:_, [], Phoenix.Endpoint.Cowboy2Handler, {MyFlatWeb.Endpoint, []}}]}]}, stream_handlers: [Plug.Adapters.Cowboy2.Stream]})
                (phoenix) lib/phoenix/endpoint/cowboy2_adapter.ex:52: Phoenix.Endpoint.Cowboy2Adapter.start_link/3
                (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
                (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
                (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
                (stdlib) supervisor.erl:1157: :supervisor.children_map/4
                (stdlib) supervisor.erl:315: :supervisor.init_children/2
                (stdlib) gen_server.erl:374: :gen_server.init_it/2
```

### :sparkles: 

I'm already running 1.4 RC on staging and it looks like everything works as expected. All tests have passed too. Thank you for your work!

**Comment by chrismccord** [comment]
This has been fixed on plug. Please run `mix deps.update plug` and you should be all set.

**Comment by arathunku** [comment]
Oh! I've missed the new Plug version :man_facepalming: :cry: 

```
Upgraded:
  plug 1.6.3 => 1.6.4
* Updating plug (Hex package)
```

Thank you

**Comment by chrismccord** [comment]
I will add it to the upgrade guides so folks don't hit this issue. Thanks!
