### ISSUE TITLE
Error with leave channel in the test of 1.4.0-rc.0

### ISSUE THREAD

**Issue by oo6** [phoenixframework/phoenix#3092]
### Environment

* Elixir version (elixir -v): 1.7.3
* Phoenix version (mix deps): 1.4.0-rc.0
* NodeJS version (node -v): 8.11.3
* NPM version (npm -v): 6.4.1
* Operating system: macOS Mojave

### In my test code
```elixir
test "leave channel" do
  {:ok, _, socket} =
    UserSocket
    |> socket("user_id", %{user_id: 1})
    |> subscribe_and_join(RoomChannel, "room:lobby", %{"id" => 1})

  ref = leave(socket)
  assert_reply :ok, ref
end
```

### Expected behavior

Passed the test

### Actual behavior

```elixir
** (EXIT from #PID<...>) shutdown: :left
```

Working correctly on 1.3.4 (I've tested it).

Close the socket behavior is the same as above.

**Comment by chrismccord** [comment]
The behavior is expected since the test process is linked to the channel process. From the ChannelTest.leave docs:

```
  ## Leave and close

  This module also provides functions to simulate leaving
  and closing a channel. Once you leave or close a channel,
  because the channel is linked to the test process on join,
  it will crash the test process:

      leave(socket)
      ** (EXIT from #PID<...>) {:shutdown, :leave}

  You can avoid this by unlinking the channel process in
  the test:

      Process.unlink(socket.channel_pid)

  Notice `leave/1` is async, so it will also return a
  reference which you can use to check for a reply:

      ref = leave(socket)
      assert_reply ref, :ok

  On the other hand, close is always sync and it will
  return only after the channel process is guaranteed to
  have been terminated:

      :ok = close(socket)

  This mimics the behaviour existing in clients.

...
  """
```
https://github.com/phoenixframework/phoenix/blob/ce2923c1b4f91b25c542adda7ed70dc11b7019fc/lib/phoenix/test/channel_test.ex#L108-L154


In your test, you need to unlink before leaving, or use `close`. Thanks!
