### ISSUE TITLE
Post-install instructions assume project is created in the current directory

### ISSUE THREAD

**Issue by bariscicek** [phoenixframework/phoenix#3103]
### Environment

* Elixir version (elixir -v): Elixir 1.4.2
* Phoenix version (mix deps):1.3.4 (phoenix) aaa1b55e
* NodeJS version (node -v):v8.11.1
* NPM version (npm -v):5.6.0
* Operating system: Linux 4.10.13-200.fc25.x86_64

### Expected behavior
This is pretty trivial thing though wanted to report as a small improvement. When mix is used with phx.new with a relative directory, the instructions comes omiting the parent diretories. 
Command like:
`mix phx.new Codes/hello`
Tells in instructions:
```
We are all set! Go into your application by running:

    $ cd hello
```
Although trivial, this is misleading. 
### Actual behavior
Post-install instructions should consider parent directories as well. (ie.:
```
We are all set! Go into your application by running:

    $ cd ./Codes/hello
```
).

**Comment by josevalim** [comment]
Closing in favor of #3131.
