### ISSUE TITLE
Presence is not a constructor error (1.4.0-rc.2)

### ISSUE THREAD

**Issue by tomciopp** [phoenixframework/phoenix#3116]
### Environment

* Elixir version (elixir -v): 1.7.3
* Phoenix version (mix deps): 1.4.0-rc.2
* NodeJS version (node -v): 10.12.0
* NPM version (npm -v): 6.4.1
* Operating system: macOS Mojave

### Expected behavior
Updating to the new Presence javascript should work based on this upgrade guide: 
https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e

### Actual behavior
When I use the following line:

    let presence = new Presence(channel);

I get the following error in my console. "Presence is not a constructor". Has the API changed since the last edit, is there a bug, or am I doing something wrong?

**Comment by chrismccord** [comment]
Yes it definitely shows the JS side did not get the updates Javascript as 1.3 phoenix.js indeed lacked a constructor. Please run `npm install` In your assets dir. You should be good from there. I’ll add it to the upgrade guides once I’m back at a keyboard

**Comment by tomciopp** [comment]
Nuking the `node_modules` did the trick, which in retrospect is obvious. Adding it to the upgrade guide would be nice.
