### ISSUE TITLE
HTTP HEAD request when using resource macro

### ISSUE THREAD

**Issue by pigmej** [phoenixframework/phoenix#312]
If there is `GET /resource/:id` there should be also `HEAD /resource/:id`

**Comment by buffpojken** [comment]
Sorry to reopen an old-buried corpse - but just ran into this and I'm quite curious about the reasoning behind this?

**Comment by chrismccord** [comment]
As José said:

> If you want to tackle this differently, you are welcome to remove the plug and handle the routes accordingly. If you have a more detailed use case of what you want to do that is not possible today given the steps above, please let us know!

If there is nothing else to add here, then there is no reason for us to continue the discussion :)

**Comment by buffpojken** [comment]
Sorry if my question came out wrong or if this is the wrong place -I'm already handling it by removing the plug and handling the request, I am just curious as to the reasoning for the plug in the first place? I tried searching the list but didn't find anything pertaining to it?

**Comment by eteubert** [comment]
Since I stumbled over this as well, here is my solution:

```elixir
defmodule Plug.MemorizeHead do
  @moduledoc """
  A Plug to add `conn.is_head: true|false` depending on request type.

  Reason: `Plug.Head` changes HEAD to GET requests.

  ## Examples

      Plug.MemorizeHead.call(conn, [])
  """

  @behaviour Plug

  alias Plug.Conn

  def init([]), do: []

  def call(%Conn{method: "HEAD"} = conn, []), do: Map.put(conn, :is_head, true)
  def call(conn, []), do: Map.put(conn, :is_head, false)
end
```

And then add that plug in the `endpoint.ex` before the `Plug.Head` call:

```elixir
plug(Plug.MemorizeHead)
plug(Plug.Head)
```
