### ISSUE TITLE
After uploading the image via ajax, the form page is refreshed in the development environment.

### ISSUE THREAD

**Issue by paulZzhang** [phoenixframework/phoenix#3120]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [kernel-poll:false]
Elixir 1.7.3 (compiled with Erlang/OTP 19)
* Phoenix version (mix deps):  master
* NodeJS version (node -v): v8.12.0
* NPM version (npm -v): 6.4.1
* Operating system: ubuntu16.04

### Expected behavior
After uploading an image via ajax, the form page is not refreshed in the development environment.

### Actual behavior
After uploading the image via ajax, the form page is refreshed in the development environment.

When I comment the code below. The Expected behavior is good.
```
#  if code_reloading? do
#    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
#    plug Phoenix.LiveReloader
#    plug Phoenix.CodeReloader
#  end
```

**Comment by webdeb** [comment]
Where are you uploading to? Maybe it got refreshed because you are using a public directory which is observed for live-reload.

Its better to upload to a `priv/uploads` directory

**Comment by chrismccord** [comment]
@webdeb is exactly right. Wherever you are uploading the file to is included in the `live_reload: [paths: `.. endpoint config. You may change the upload location, or update the live reload config to ignore your specific upload pattern. Thanks!
