### ISSUE TITLE
`mix phx.new` needs to be updated for the 1.4 RC.

### ISSUE THREAD

**Issue by idyll** [phoenixframework/phoenix#3124]
Currently https://github.com/phoenixframework/archives only contains version for 1.4-dev and not the RC.

To help with testing the RC on new projects it would be great if the archives were updated for 1.4.0rc2.

**Comment by chrismccord** [comment]
I'm hesitant to update the archives because the approach going forward will be to install via hex:

    mix archive.install hex phx_new 1.4.0

By keeping the old archive on 1.3, we ensure old content (blogs, books, etc) remains working and relevant. Thanks!

**Comment by idyll** [comment]
@chrismccord thanks!

Is there a place this should be documented? I search but couldn't find it...

**Comment by idyll** [comment]
Also:

```
== Compilation error in file lib/phx_new/ecto.ex ==
** (File.Error) could not read file "/Users/chris/oss/phoenix/installer/templates/phx_ecto/repo.ex": no such file or directory
```
