### ISSUE TITLE
`Ranch protocol :error`

### ISSUE THREAD

**Issue by jamesstonehill** [phoenixframework/phoenix#3128]
### Environment

* Elixir version (elixir -v): 1.7.3
* Phoenix version (mix deps): phoenix 1.3.4
* NodeJS version (node -v): v7.10.1
* NPM version (npm -v): 4.2.0
* Operating system: Mac OS 10.13.6

### Error Running Server
I've created a brand new Phoenix app and whenever I try GET any route I see this error in the terminal:
```
[error] Ranch protocol :error of listener MyAppWeb.Endpoint.HTTP (cowboy_protocol) terminated
** (exit) :undef
```

If I `rm -rf _build` and then restart the server the app usually works, but whenever I kill the server and restart it I get the same issue. My deps are all the default that come bundled with a new vanilla phoenix app.

**Comment by jamesstonehill** [comment]
Not totally sure if this can be considered a Phoenix issue but I figured I'd start here since I'm not so familiar with Elixir stuff ¯\_(ツ)_/¯

**Comment by chrismccord** [comment]
Can you push your app to GH so I can try to recreate the issue? Thanks!

**Comment by gshaw** [comment]
@chrismccord I get the error message when running the test suite on master @ 68ef846c.

E.g,

```console
% mix test
...

==> phoenix
Compiling 67 files (.ex)
Generated phoenix app

...

11:48:02.342 [error] Ranch protocol #PID<0.2370.0> of listener Phoenix.Integration.WebSocketTest.Endpoint.HTTP (connection #PID<0.2369.0>, stream id 1) terminated
** (exit) {:try_clause, {:error, %{bindings: %{}, body_length: 0, cert: :undefined, has_body: false, has_sent_resp: true, headers: %{"connection" => "Upgrade", "host" => "127.0.0.1", "origin" => "http://notallowed.com", "sec-websocket-key" => "L52tlZ577dMXvERfc9gX6Q==", "sec-websocket-version" => "13", "upgrade" => "websocket"}, host: "127.0.0.1", host_info: :undefined, method: "GET", path: "/ws/websocket", path_info: :undefined, peer: {{127, 0, 0, 1}, 51039}, pid: #PID<0.2369.0>, port: 80, qs: "", ref: Phoenix.Integration.WebSocketTest.Endpoint.HTTP, scheme: "http", sock: {{127, 0, 0, 1}, 5907}, streamid: 1, version: :"HTTP/1.1"}}}

...

Finished in 14.3 seconds
17 doctests, 632 tests, 0 failures

Randomized with seed 5620
```

The error message appears 5 times in the test output but it doesn't cause any test failures.

**Comment by aleph-naught2tog** [comment]
Not sure how helpful this is, but I figure if nothing else a little more data doesn't hurt. 🙂

I spent some time stepping back through commits starting from the most recent `master` (at `12785c38` presently) and have the same Ranch set of errors crop up as @gshaw , also with no test failures. I could only pin down two tests they must be arising from (`"refuses unallowed origins"` from, not surprisingly, the WebsocketChannels integration test and `"refuses connects that error with 403 response"`, same test suite) consistently -- sometimes I would get a huge pile more of the Ranch error, sometimes only those two.

**Comment by josevalim** [comment]
The errors you are seeing on the test suite are likely not related. The test suite is triggering those errors on purpose, to assert some behaviours, it just happens that sometimes we are unable to avoid them also logging to the terminal, which is rather a race condition on the log capturing, but unlikely to be a Cowboy/Ranch/Phoenix bug.

**Comment by aleph-naught2tog** [comment]
> which is rather a race condition on the log capturing

That makes total sense, thank you for explaining it 😁

**Comment by josevalim** [comment]
Should be fixed in master.

**Comment by jamesstonehill** [comment]
Seems like this was the underlying issue. https://github.com/w0rp/ale/issues/2084

**Comment by narrowtux** [comment]
I got the same issue after trying to update to Phoenix 1.4 from 1.3. However, it even occurs in the normal webserver so on every request made it shows this error: 

```[error] Ranch protocol #PID<0.2407.0> of listener Platform.Web.Endpoint.HTTP (connection #PID<0.2406.0>, stream id 1) terminated
** (exit) :undef```

While the webserver returns a `500 Internal Server Error`.

My Endpoint is not called `.HTTP` and I have no clue where this suffix is coming from.

**Comment by narrowtux** [comment]
Ok in my case it had something to do with a custom http dispatch option that is probably wrong for cowboy 2.0

**Comment by saurabhK4073** [comment]
> I got the same issue after trying to update to Phoenix 1.4 from 1.3. However, it even occurs in the normal webserver so on every request made it shows this error:
> 
> ```
> [error] Ranch protocol #PID<0.2407.0> of listener Platform.Web.Endpoint.HTTP (connection #PID<0.2406.0>, stream id 1) terminated
> ** (exit) :undef
> ```
> 
> While the webserver returns a `500 Internal Server Error`.
> 
> My Endpoint is not called `.HTTP` and I have no clue where this suffix is coming from.
> 
> EDIT Here's a list of the relevant versions:
> 
> ```
> * ranch 1.7.1 (Hex package) (rebar3)
>   locked at 1.7.1 (ranch) 6b1fab51
>   ok
> * poolboy 1.5.2 (Hex package) (rebar3)
>   locked at 1.5.2 (poolboy) 392b007a
>   ok
> * jason 1.1.2 (Hex package) (mix)
>   locked at 1.1.2 (jason) b03dedea
>   ok
> * poison 3.1.0 (Hex package) (mix)
>   locked at 3.1.0 (poison) d9eb6366
>   ok
> * db_connection 1.1.3 (Hex package) (mix)
>   locked at 1.1.3 (db_connection) 89b30ca1
>   ok
> * phoenix_pubsub 1.1.2 (Hex package) (mix)
>   locked at 1.1.2 (phoenix_pubsub) 496c303b
>   ok
> * cowlib 2.7.0 (Hex package) (rebar3)
>   locked at 2.7.0 (cowlib) 3ef16e77
>   ok
> * cowboy 2.6.1 (Hex package) (rebar3)
>   locked at 2.6.1 (cowboy) f2e06f75
>   ok
> * postgrex 0.13.5 (Hex package) (mix)
>   locked at 0.13.5 (postgrex) 3d931aba
>   ok
> * ecto 2.2.11 (Hex package) (mix)
>   locked at 2.2.11 (ecto) 4bb8f117
>   ok
> * plug_crypto 1.0.0 (Hex package) (mix)
>   locked at 1.0.0 (plug_crypto) 18e49317
>   ok
> * plug 1.7.2 (Hex package) (mix)
>   locked at 1.7.2 (plug) d7b7db7f
>   ok
> * phoenix_html 2.13.1 (Hex package) (mix)
>   locked at 2.13.1 (phoenix_html) fa8f034b
>   ok
> * plug_cowboy 2.0.2 (Hex package) (mix)
>   locked at 2.0.2 (plug_cowboy) 6055f168
>   ok
> * phoenix 1.4.2 (Hex package) (mix)
>   locked at 1.4.2 (phoenix) 3a1250f2
>   ok
> * phoenix_live_reload 1.0.8 (Hex package) (mix)
>   locked at 1.0.8 (phoenix_live_reload) 4333f9c7
>   ok
> * coherence 0.4.0-dev (https://github.com/narrowtux/coherence.git) (mix)
>   locked at 6eea58a (branch: phx-1.3)
>   ok
> * phoenix_ecto 3.6.0 (Hex package) (mix)
>   locked at 3.6.0 (phoenix_ecto) d65dbced
>   ok
> ```

I am facing kinda the same issue. Can you help me out? 
[error] Ranch protocol #PID<0.1796.0> of listener CredibleWeb.Endpoint.HTTP (connection #PID<0.1795.0>, stream id 1) terminated
** (exit) :undef

on starting elixir and going to address 0.0.0.0:4000 i get this everytime.
