### ISSUE TITLE
phx.gen.json not work in 1.4

### ISSUE THREAD

**Issue by ImmortalDragonm** [phoenixframework/phoenix#3133]
I created project without html an webpack
`mix phx.new app --no-html --no-webpack`
and then want to add json

`mix phx.gen.json Accounts User users name:string age:integer`

### Environment

* Elixir version (elixir -v): 1.7.3
* Phoenix version (mix deps): 1.4.0-rc.2
* Operating system: debian 9

### Expected behavior

generate files

### Actual behavior

```
** (UndefinedFunctionError) function Jason.encode!/1 is undefined (module Jason is not available)
    Jason.encode!("some name")
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:273: :erl_eval.expr/5
    (stdlib) eval_bits.erl:88: :eval_bits.eval_field/3
    (stdlib) eval_bits.erl:68: :eval_bits.expr_grp/4
    (stdlib) erl_eval.erl:484: :erl_eval.expr/5
    (stdlib) erl_eval.erl:232: :erl_eval.expr/5
    (stdlib) maps.erl:257: :maps.fold_1/3

```

**Comment by chrismccord** [comment]
Are you sure you created the project with the phx 1.4 generator? What does `mix phx.new -v` report? Jason should be listed in your deps for phoenix 1.4 projects. Is this perhaps an upgraded project that you forgot to add `:jason` to your deps?

**Comment by ImmortalDragonm** [comment]
I removed old version and install new yesterday.
```
mix archive.uninstall phx_new
mix archive.install hex phx_new 1.4.0-rc.2
```
 And i saw this error message.
Today I've tried on another PC. And it work well.
I think, something wrong on my home PC. Tomorrow i'll try again. 

Thank you.
