### ISSUE TITLE
Should we use `async: true` on all generated tests?

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#3134]
Now that we have the SQL sandbox, we can async: true all tests. The question though is that this only actually applies for Postgrex, so we may need a generator flag to control this behaviour.

**Comment by stevedomin** [comment]
@josevalim didn't Ecto always ship with a SQL sandbox?

**Comment by mikemorris** [comment]
I'd lean towards `async: true` for all generated tests (with a flag for Postgrex-only currently), and rely on generated tests and documentation as a way of conveying the benefits of async tests and providing patterns for how to write them effectively.

_It's much easier to increase adoption of functionality if it's a default_, and IMHO this is good direction to push in for guiding users towards writing better tests.

Some tips on documentation language that may help explain async tests from [ava](https://github.com/avajs/ava), a JavaScript framework that runs tests in parallel by default and describes them as "atomic" tests.
- https://github.com/avajs/ava#temp-files
- Note at bottom of https://github.com/avajs/ava#before--after-hooks on caution around before/after hooks

**Comment by mikemorris** [comment]
@stevedomin I'm assuming this is referring to https://hexdocs.pm/phoenix_ecto/Phoenix.Ecto.SQL.Sandbox.html, an implementation on top of https://hexdocs.pm/ecto/2.0.2/Ecto.Adapters.SQL.Sandbox.html

**Comment by stevedomin** [comment]
@mikemorris for some reason I assumed José was talking about something new in Ecto 3.0 :)

**Comment by josevalim** [comment]
Oops, accident. :)

**Comment by popo63301** [comment]
@ericmj How can we learn about those pitfalls?
