### ISSUE TITLE
Channel reconnect timer on socket open?

### ISSUE THREAD

**Issue by sb8244** [phoenixframework/phoenix#3139]
### Environment

* Phoenix.js version: master

### Expected behavior

When a socket opens, the channels would immediately attempt to connect in order to provide maximum availability of message processing.

### Actual behavior

When a socket opens, the channels do not immediately attempt to connect. The channels follow the same reconnection algorithm provided by the socket.

### Ideas

I see two solutions that could solve this problem. The first is to reset all channel reconnect timers onOpen of the socket. The second is to provide a custom reconnection algorithm for channels. I don't see channels as hitting the server when they attempt to connect, so it should be fairly cheap to attempt versus the socket.

**Comment by chrismccord** [comment]
> The first is to reset all channel reconnect timers onOpen of the socket

This sounds like a good plan. Can you send a PR? Thanks!

**Comment by sb8244** [comment]
Can do!

**Comment by sb8244** [comment]
@chrismccord The change involved a bit more (at least for what I'm seeing) in order to prevent trying to rejoin when not in the rejoin flow.
