### ISSUE TITLE
JS docs not updated for 1.4.0

### ISSUE THREAD

**Issue by xtian** [phoenixframework/phoenix#3157]
The following URLs show the docs for 1.3.4:

- https://hexdocs.pm/phoenix/js/
- https://hexdocs.pm/phoenix/1.4.0/js/
- https://hexdocs.pm/phoenix/1.4.0-rc.1/js/
- https://hexdocs.pm/phoenix/1.4.0-rc.2/js/
- https://hexdocs.pm/phoenix/1.4.0-rc.3/js/

https://hexdocs.pm/phoenix/1.4.0-rc.0/js/ does show the correct docs, however.

**Comment by chrismccord** [comment]
Fixed. thanks!
