### ISSUE TITLE
No way to use websockets directly with 1.4

### ISSUE THREAD

**Issue by rogerbraun** [phoenixframework/phoenix#3167]
Because I need to emulate an existing API, I have been using sockets with websockets directly in Phoenix 1.3 using https://github.com/satom99/phx_raws. This breaks in 1.4 and it seems there is no way to just use a websocket outside of going directly through cowboy.

As far as I can see, the only real hurdle here is that I can't control the websocket path. If i mount the socket at `/socket`, the websocket path will actually be `/socket/websocket`.

**Comment by Gazler** [comment]
This should be fixed by https://github.com/phoenixframework/phoenix/pull/3166

**Comment by Gazler** [comment]
Closed by #3166
