### ISSUE TITLE
Setting host: nil fixes host into "localhost"

### ISSUE THREAD

**Issue by imetallica** [phoenixframework/phoenix#3174]
### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
```
* Phoenix version (mix deps): `1.4.0`
* Operating system: `Linux`, `MacOS`

### Expected behavior
After upgrading from 1.3 to 1.4, setting this configuration on the endpoint has different behaviour.

```
url: [
    scheme: "https",
    host: nil,
    port: 443
  ]
```
The `host` is the same as the `url` used.

### Actual behavior
Fixes `host` into `"localhost"`.

### Miscellaneous
If this is the new expected behaviour, then how do we set it dynamically? We should populate it in the docs. :-)

**Comment by imetallica** [comment]
@josevalim Yes, on the new helpers: `Routes.static_url(@conn, "js/foo.js")` for example.

**Comment by chrismccord** [comment]
This was also the behavior in 1.3 as you can see here:
https://github.com/phoenixframework/phoenix/blob/v1.3.4/lib/phoenix/endpoint/supervisor.ex#L191

Thanks!
