### ISSUE TITLE
Default splitting PubSub from Endpoint

### ISSUE THREAD

**Issue by benwilson512** [phoenixframework/phoenix#3179]
Hey folks,

I want to argue that the phoenix generators should, by default, split the pubsub supervision child from the endpoint supervision child.

It is increasingly common for libraries to rely upon the Phoenix pubsub that comes configured with a phoenix generated application since it's high performance and provides easy integration with websockets. The problem is that the current configuration creates the following race condition:

```
# in your application.ex
children = [
  MyApp.Endpoint,
  {Absinthe.Subscription, [MyApp.Endpoint]}
]
```
The Absinthe.Subscription child must go after `MyApp.Endpoint` because it's going to make some `MyApp.Endpoint.subscribe` calls. The issue is, as soon as `MyApp.Endpoint` is alive, the application will start handling HTTP requests. If any of those HTTP requests require that `Absinthe.Subscription` be alive, they will fail.

If instead the generated application looked more like:

```
children = [
  Phoenix.PubSub,
  {Absinthe.Subscription, [Phoenix.PubSub]},
  {MyApp.Endpoint, [Phoenix.PubSub]}
]
```

Then the boot order of the application could help ensure that HTTP requests are not being handled before the app is actually booted.

Thoughts?

**Comment by chrismccord** [comment]
> Hey folks,
> 
> I want to argue that the phoenix generators should, by default, split the pubsub supervision child from the endpoint supervision child.

Hey Ben, this is the plan once we port our Phoenix.PubSub usage to Firenest.PubSub. 1.4 could have taken this approach, but then we would have had two pubsub changes back to back to contend with, so we're waiting for the firenest change to split. In the meantime, you can instruct users to make the following changes:

1) remove the `adapter: ` key from their endpoint pubsub config (keeping the `:name`)
2) Add a PubSub child to their sup tree, above the endpoint. Critically, they must provide the fast lane config:

```elixir
children = [
  {Phoenix.PubSub.PG2, name: App.PubSub, fastlane: Phoenix.Channel.Server},
  AppWeb.Endpoint,
  ...
]
```

Thanks!

**Comment by benwilson512** [comment]
Will do, thanks!
