### ISSUE TITLE
Unexpected HTTP 500 response after raising Phoenix.ActionClauseError

### ISSUE THREAD

**Issue by florish** [phoenixframework/phoenix#3187]
### Environment

* Elixir version (elixir -v): 1.7.4
* Phoenix version (mix deps): 1.4.0
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: elixir:1.7.4-alpine Docker image

### Expected behaviour

I'm currently building a JSON API using Phoenix (`phx.new --no-html --no-webpack`).

For a given API endpoint, The controller action does pattern matching against a certain key in the JSON body (e.g. a "foo" key is expected). If this key isn't there in the `params`, a `Phoenix.ActionClauseError` is raised.

In case of a `Phoenix.ActionClauseError`, I would expect an HTTP 400 error, as this seems to be the intended default behaviour, based on what I read in [this comment](https://github.com/phoenixframework/phoenix/issues/2386#issuecomment-315590839).

### Actual behaviour

I notice that I get HTTP 500 errors in development mode (`http://localhost:4000/foo`) when sending an empty `{}`JSON object as request body for a POST request to `/foo`. 

On further inspection, the behaviour seems to differ given the `debug_errors` setting in `config/dev.exs` for `Myapp.Endpoint`:

* An HTTP 500 error in development for `debug_errors: true`
* An HTTP 400 error in development for `debug_errors: false`

Stack trace from phx.server logs for the HTTP 500 error:

```
Request: POST /foo
** (exit) an exception was raised:
    ** (BadFunctionError) expected a function, got: %Phoenix.ActionClauseError{args: [%Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{current_user: nil}, before_send: [#Function<1.112466771/1 in Plug.Logger.call/2>], body_params: %{}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "localhost", method: "POST", owner: #PID<0.647.0>, params: %{}, path_info: ["foo"], path_params: %{}, port: 4000, private: %{MyAppWeb.Router => {[], %{}}, :phoenix_action => :create, :phoenix_controller => MyAppWeb.FooController, :phoenix_endpoint => MyAppWeb.Endpoint, :phoenix_format => "json", :phoenix_layout => {MyAppWeb.LayoutView, :app}, :phoenix_pipelines => [:api], :phoenix_router => MyAppWeb.Router, :phoenix_view => MyAppWeb.FooView, :plug_session_fetch => #Function<1.58261320/1 in Plug.Session.fetch_session/1>}, query_params: %{}, query_string: "", remote_ip: {172, 19, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"accept", "application/json"}, {"content-length", "2"}, {"content-type", "application/json"}, {"host", "localhost:4000"}, {"user-agent", "curl/7.54.0"}], request_path: "/foo", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "2llklfmcomuvhbgg28000bli"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: nil}, %{}], arity: 2, clauses: nil, function: :create, kind: nil, module: MyAppWeb.FooController}
        (elixir) lib/exception.ex:1062: anonymous fn/2 in FunctionClauseError.blame/3
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/exception.ex:1061: FunctionClauseError.blame/3
        (phoenix) lib/phoenix/exceptions.ex:59: Phoenix.ActionClauseError.blame/2
        (plug) lib/plug/debugger.ex:197: Plug.Debugger.render/6
        (plug) lib/plug/debugger.ex:147: Plug.Debugger.__catch__/5
        (my_app) lib/my_app_web/endpoint.ex:1: MyAppWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:34: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /opt/app/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /opt/app/deps/cowboy/src/cowboy_stream_h.erl:293: :cowboy_stream_h.execute/3
        (cowboy) /opt/app/deps/cowboy/src/cowboy_stream_h.erl:271: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Server log for the HTTP 400 response (no stack trace, due to `debug_errors: false`):

```
POST /foo
Processing with MyAppWeb.FooController.create/2
Parameters: %{}
Pipelines: [:api]
Converted error Phoenix.ActionClauseError to 400 response
Sent 400 in 34ms
```

**Comment by chrismccord** [comment]
> An HTTP 500 error in development for debug_errors: true
> An HTTP 400 error in development for debug_errors: false

This is as designed since we don't wrap and translate errors when debug_errors is enabled. It is false by default, so test and prod will return. your 400 as you want. Thanks!
