### ISSUE TITLE
Running in "subdirectory" not working as expected since 1.4

### ISSUE THREAD

**Issue by marceldegraaf** [phoenixframework/phoenix#3188]
### Environment
* Elixir version (elixir -v): `Elixir 1.6.5 (compiled with OTP 20)`
* Phoenix version (mix deps): `locked at 1.4.0 (phoenix) 56fe9a80`
* NodeJS version (node -v): `v10.12.0`
* NPM version (npm -v): `6.4.1`
* Operating system: macOS Sierra

### Preface
We're running a microservices architecture on our company domain, https://example.com. Our login service is a Phoenix app. We want it running on https://example.com/login. We're using HAProxy as a reverse proxy.

### Expected behavior

In Phoenix 1.3.2 we were able to do this with the following configuration:

```
# config/prod.exs

config :login, LoginWeb.Endpoint,
  http: [port: "8000"],
  url: [host: "example.com", path: "/login", port: "8000"],
  ...
```

```
# login_web/router.ex

scope "/", LoginWeb do
  get("/:provider", AuthController, :new)
end
```

This would allow us to navigate to https://example.com/login/google, which would show `AuthController#new` for the Google OAuth provider. Note that from the perspective of the router the `/login` subdirectory wasn't taken into account.

### Actual behavior

In Phoenix 1.4, however, this same configuration no longer seems to work. Visiting https://example.com/login/google results in a visit to `AuthController#new` with `login` as the value for the `:provider` variable.

The only way to get this to work was to update the `scope` of the router like this:

```
# login_web/router.ex

scope "/login", LoginWeb do
  get("/:provider", AuthController, :new)
end
```

But that means we must now also add the `/login/` path in development. We would like to be able to transparently host the Phoenix application behind the `/login` subdirectory in production.

Is that no longer possible or are we missing something obvious?

**Comment by chrismccord** [comment]
Can you verify this is not an issue with your upstream haproxy, for example by trying to see if Phoenix 1.3.x still works as intended? Also note ,that if you are using cowboy 2, you may need to instruct haproxy to use http 1.1, but I'm not familiar with the haproxy config. Your config looks good to me and should be working as expected. Thanks!

**Comment by marceldegraaf** [comment]
Thanks for your quick reply, and thanks for pointing me in the right direction. I've just tested with Phoenix 1.3 and 1.4 and have confirmed that the HAProxy configuration was the culprit.

The fix was to add this rule to the HAProxy configuration of the backend:

```
reqirep ^([^\ :]*)\ /login/?(.*) \1\ /\2
```

This properly rewrites the request URI for the Phoenix router. In Phoenix, all I had to do now is use this endpoint configuration:

```
# config/prod.exs

config :login, LoginWeb.Endpoint,
  http: [port: "8000"],
  url: [host: "example.com", path: "/login", port: "8000"],
  ...
```

This lets me use the normal `/` scope in the router as well:

```
# login_web/router.ex

scope "/", LoginWeb do
  get("/:provider", AuthController, :new)
end
```

These pages ([here](https://discourse.haproxy.org/t/backend-as-subdir/691/5) and [here](https://stackoverflow.com/a/22257151)) helped me find that incantation.
