### ISSUE TITLE
Resource Protocol

### ISSUE THREAD

**Issue by scrogson** [phoenixframework/phoenix#320]
Would like to get some more discussion/ideas around a `Resource` protocol to be used for "models". This will come in handy for improving route helpers: `Route.user_path(@user)` and many other things.

I have begun to work on some form helpers that would really work best with a protocol like this. Would be great to get some ideas rolling on what this protocol could/should be.

```elixir
defprotocol Phoenix.Resource do
  def param_key(key)
  def model_name(name)
  ...
end

defimpl Phoenix.Resource, for: Any do
  def param_key(_key), do: "id"
end
```

**Comment by josevalim** [comment]
We have added FormData and Param protocol. We will add more if we need them.
