### ISSUE TITLE
mix phx.gen.html generates invalid fixtures

### ISSUE THREAD

**Issue by jrissler** [phoenixframework/phoenix#3216]
### Environment

* Elixir version (elixir -v): 1.7.4
* Phoenix version (mix deps): 1.4.0
* NodeJS version (node -v): 11.4.0
* NPM version (npm -v): 6.4.1
* Operating system: macOS High Sierra

### Expected behavior
With a rather large amount of fields or a decent set of fields with longer names, when mix phx.gen.html generates @valid_attrs, @update_attrs, @invalid_attrs in tests it does not add all the fields.

### Actual behavior
%{field: "", other_fields, field: nil, ...} (,... at end should continue with other fields)

**Comment by chrismccord** [comment]
Can you include the exact command you ran and the exact generated file? We exclude fkey fields, so perhaps that is what you are seeing as missing? Thanks!

**Comment by jrissler** [comment]
Yes - will add those later thanks (wasn't fkey's missing though) - it was more the generated attributes truncated after a certain overall length.

**Comment by jrissler** [comment]
@chrismccord I was able to replicate this with an exact mix phx.json command I ran before in a new phx app (don't want to share the table fields as its a prod table). But I was not able to replicate with any other generator without these specific fields even w even more length (sounds weird I know). Thinking we just close - if I ever run across this again, I'll open a new issue where I can share example replication steps - thanks.

**Comment by chrismccord** [comment]
Very odd. Please let us know if you have a reproducible case that you can share in the future if this comes up again. Thanks!

**Comment by sulphur** [comment]
Hi, 
I've hit the same issue. It is quite simple to reproduce in fact you need to create a context or schema with more than 50 attributes at one time. This will trigger de default Limit for IO.inspect that is 50 and therefore the `@create_attrs` are truncated with `...}` at the end.

I did a PR https://github.com/phoenixframework/phoenix/pull/4007  with a simple fix.
