### ISSUE TITLE
CSRF protection for APIs

### ISSUE THREAD

**Issue by pragdave** [phoenixframework/phoenix#3221]
The default pipeline for APIs is

~~~ elixir
  pipeline :api do
    plug :accepts, ["json"]
  end
~~~

In https://hexdocs.pm/plug/Plug.CSRFProtection.html it says:

> Note that it is recommended to enable CSRFProtection whenever a session is used, even for JSON requests. 

Should this be reflected in the default generated code? 

Cheers

Dave

**Comment by chrismccord** [comment]
The *whenever a session is used* is the key phrase in this case. Our generated `:api` pipeline doesn't include the `fetch_session` plug, so in this case we don't want or need to generate the CSRF token. Thanks!
