### ISSUE TITLE
Ranch listener error

### ISSUE THREAD

**Issue by jamesstonehill** [phoenixframework/phoenix#3222]
### Environment
* Elixir version (elixir -v): `Elixir 1.7.4 (compiled with Erlang/OTP 21)`
* Phoenix version (mix deps): `phoenix 1.4.0`
* NodeJS version (node -v): `v7.10.1`
* NPM version (npm -v): `4.2.0`
* Operating system: `osx`

### Issue
I've created a brand new Phoenix app (source code [here](https://github.com/jamesstonehill/internet_connectivity_monitor)). Whenever I start the server and GET http://localhost:4000 I see this error:
```shell
[error] Ranch listener InternetConnectivityMonitorWeb.Endpoint.HTTP had connection process started with :cowboy_clear:start_link/4 at #PID<0.417.0> exit with reason: {:undef, [{:cowboy_http, :init, [#PID<0.314.0>, InternetConnectivityMonitorWeb.Endpoint.HTTP, #Port<0.18>, :ranch_tcp, :undefined, %{env: %{dispatch: [{:_, [], [{:_, [], Phoenix.Endpoint.Cowboy2Handler, {InternetConnectivityMonitorWeb.Endpoint, []}}]}]}, stream_handlers: [Plug.Cowboy.Stream]}], []}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
```

I can fix the issue by removing the compiled files (`rm -rf _build`) and then when I start the server again everything seems to work for a while but eventually I run into this issue again, often without any actual code changes.

I haven't been able to find steps that reliably reproduce this issue yet but will update if I do.

**Comment by chrismccord** [comment]
Can you verify if you are using an elixir linter in your editor? I believe we've had similar reports which were narrowed down to an editor plugin using recompilation issues. Once the plugin was disabled the issues went away. thanks!

**Comment by jamesstonehill** [comment]
@dalhorinek yeah I'm using ALE so this must be it! Thanks for the info guys!
