### ISSUE TITLE
Include troubleshoot Heroku deployment guide to handle error R10

### ISSUE THREAD

**Issue by edwinthinks** [phoenixframework/phoenix#3228]
### Environment

* Elixir version (elixir -v): 1.5.1
* Phoenix version (mix deps): 1.4.0
* NodeJS version (node -v): v8.11.3
* NPM version (npm -v): 5.6.0
* Operating system: Mac OSX

### Expected behavior

Following the Heroku deployment guide, I should be able to deploy my application without any issues such as the [R10 error](https://devcenter.heroku.com/articles/error-codes#r10-boot-timeout) 

### Actual behavior

While I was trying to deploy my phoenix application to heroku using the md guide, I ran into this issue detailed in this Github issue: https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/73

I was able to avoid the issue when adding `http: [port: {:system, "PORT"}]` to my configuration. Should this be included into the documentation? as a troubleshoot or inside the guide?

**Comment by edwinthinks** [comment]
Opened a PR here: https://github.com/phoenixframework/phoenix/pull/3235 to help address this. Hope  this is helpful :). Thanks again!

**Comment by chrismccord** [comment]
Closed via #3235 . Thanks!
