### ISSUE TITLE
Update Endpoint docs with new supervisor syntax

### ISSUE THREAD

**Issue by michallepicki** [phoenixframework/phoenix#3231]
The [Endpoint module docs](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html) and [Endpoint guide](https://hexdocs.pm/phoenix/endpoint.html) point out that
>  By default, the Endpoint is added to the supervision tree in lib/hello/application.ex as a supervised process

> supervisor(HelloWeb.Endpoint, [])

while the phx generator [doesn't do that anymore](https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_single/lib/app_name/application.ex#L14) and instead adds just the endpoint module name (AFAIK it's thanks to the new supervisor syntax introduced in elixir 1.5).

**Comment by chrismccord** [comment]
Good catch! Can you send a PR? Thanks!

**Comment by michallepicki** [comment]
Closing in favor of the PR
