### ISSUE TITLE
Show socket paths on `mix phx.routes`

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix#3237]
Currently only the paths defined in the router are displayed. It'd be nice to also display the paths for sockets and which modules the sockets route to.

**Comment by lucaspbordignon** [comment]
I don't know if the idea has been approved by the core community of the framework, but if it's a valid idea would like to work on it! 😅

**Comment by chrismccord** [comment]
Hey @lucaspbordignon, we are taking care of it. Thanks!
