### ISSUE TITLE
Heroku Guide needs a blurb about setting the elixir version

### ISSUE THREAD

**Issue by zachmccormick** [phoenixframework/phoenix#3238]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

### Expected behavior
Following the guide will work

### Actual behavior
Need to add an `elixir_buildpack.config` file with the line `elixir_version=1.7.4` or similar in it. Following the directions as they stand today will result in an error such as 
```
supervisors expect the child to be a module, a {module, arg} tuple or a map with the child specification
```
on deploy

**Comment by edwinthinks** [comment]
I can confirm that this is occurring. I suggested to bump the default version of elixir to at least contain the bug fix related to what you encountered. I have a PR open here: https://github.com/HashNuke/heroku-buildpack-elixir/pull/140 which I think would eliminate the requirement (maybe?) to include a blurb on it?

I think either or both would make sense :)
