### ISSUE TITLE
Get match path when using Phoenix Router

### ISSUE THREAD

**Issue by fredr** [phoenixframework/phoenix#3239]
### Environment

* Elixir version (elixir -v):
1.7.4 
* Phoenix version (mix deps):
1.4.0
* Operating system:
Linux

Is it possible to get the match path that Phoenix Router used to match a path? i.e `/users/:id` when requesting `/users/1`?

In `plug` this is possible from 1.5 via the private `plug_route`, but this field seems to not be populated when using Phoenix router.

**Comment by chrismccord** [comment]
Please use the forums, slack, irc, etc for questions as we reserve the issue tracker for issues. Thanks!
