### ISSUE TITLE
mix.bat deps.get failed

### ISSUE THREAD

**Issue by 728443778** [phoenixframework/phoenix#3245]
### Environment

* Elixir version (elixir -v): 1.8.0
* Phoenix version (mix deps): 1.4.0
* NodeJS version (node -v):11.6.0
* NPM version (npm -v):6.5.0
* Operating system:win 10

### Actual behavior
when i use mix.bat deps.get ,the powershell  output 
```
 Updating phoenix (Hex package)
 (Mix) Unpacking tarball failed: inner tarball error, invalid argument
```

**Comment by wojtekmach** [comment]
This is likely a Hex issue on Windows, either causes by FAT partition (https://github.com/hexpm/hex/issues/474) or WSL (https://github.com/hexpm/hex/issues/624)

**Comment by chrismccord** [comment]
Thanks @wojtekmach! @728443778 please follow the linked hex issues. Closing as this is not Phoenix related. Thanks!

**Comment by 728443778** [comment]
ok,simple method,format the fat disc to ntfs
