### ISSUE TITLE
could not read file "/Users/chris/..."

### ISSUE THREAD

**Issue by wintermeyer** [phoenixframework/phoenix#3257]
### Environment

* Elixir version (elixir -v): 1.5.2
* Phoenix version (mix deps): 1.4.0
* NodeJS version (node -v): v8.8.1
* NPM version (npm -v): 5.4.2
* Operating system: macOS 10.14.2

### Expected behavior

While doing every step in https://hexdocs.pm/phoenix/installation.html I stumble over this:

<img width="481" alt="bildschirmfoto 2019-01-25 um 09 50 19" src="https://user-images.githubusercontent.com/69770/51735069-a35d0680-2086-11e9-8bc2-6d52dd8073e1.png">

Assumingely this command should run through without an issue.

### Actual behavior

```
$ mix archive.install hex phx_new 1.4.0
[...]
== Compilation error in file lib/phx_new/ecto.ex ==
** (File.Error) could not read file "/Users/chris/oss/phoenix/installer/templates/phx_ecto/repo.ex": no such file or directory
    (elixir) lib/file.ex:272: File.read!/1
    lib/phx_new/generator.ex:28: anonymous fn/4 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/phx_new/generator.ex:24: anonymous fn/3 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Phx.New.Generator.__before_compile__/1
    lib/phx_new/ecto.ex:1: Phx.New.Ecto (module)
```

Obviously my system doesn't have a `/Users/chis/` directory.

### Workaround

Doing a `mix archive.uninstall phx_new` before. After that it worked.

**Comment by ericmj** [comment]
This issue should be fixed on Elixir 1.8.0.

**Comment by veverkap** [comment]
Is there something we can do if we are running Elixir < 1.8?

**Comment by ericmj** [comment]
Yes, as the issue says there is a workaround: `mix archive.uninstall phx_new`.

**Comment by veverkap** [comment]
Yeah, saw that too late :)  Thanks!
