### ISSUE TITLE
using :acceptors in options is deprecated

### ISSUE THREAD

**Issue by lboekhorst** [phoenixframework/phoenix#3266]
### Environment

* Elixir version (elixir -v): 1.7.2
* Phoenix version (mix deps): 1.4.0
* NodeJS version (node -v): 10.9.0
* NPM version (npm -v): 6.2.0
* Operating system: 10.14.2
* plug_cowboy version: 2.0.1
* cowboy version: 2.6.1
* ranch version: 1.7.1

### Configuration

We have the following options configured on our endpoint:

```
config :my_web, My.Web.Endpoint,
  http: [
    acceptors: String.to_integer(System.get_env("COWBOY_ACCEPTORS")),
  ],
```

### Expected behavior

When I run `mix phx.server`, I do not expect any deprecation warnings.

### Actual behavior

I get the following deprecation warning:

`using :acceptors in options is deprecated. Please pass :num_acceptors to the :transport_options keyword list instead`

**Comment by Gazler** [comment]
I think the deprecation warning is pretty clear on what to do here.

```elixir
  http: [
    transport_options: [num_acceptors: String.to_integer(System.get_env("COWBOY_ACCEPTORS"))]
  ],
```

Please confirm the above works.

**Comment by lboekhorst** [comment]
Please forgive my brainfart. I was adding the `transport_options` to the top-level instead of having it nested in the `http` options. It's working now. Thanks!
