### ISSUE TITLE
Call to Phoenix.Controller.json/2 does not flush data to the client

### ISSUE THREAD

**Issue by brweber2** [phoenixframework/phoenix#3273]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.0
* NodeJS version (node -v): n/a
* NPM version (npm -v): n/a
* Operating system: Ubuntu 16.04.5 LTS (also happening on OS X)

### Expected behavior

`json(conn, %{data: data})` should write the response to the client and the client should receive the data.  

### Actual behavior

Our clients are frequently, but not always, timing out. It looks like the iodata is not being flushed. If we encode the Jason to a string and call `send_resp` the data is always flushed and our clients receive the data. I'm not sure if this is a bug in Phoenix, Jason, Plug, Plug Cowboy or Cowboy or some combination of them. We had to modify our code to the less performant Jason.encode! and call `send_resp` instead of calling `json` which uses Jason.encode_to_iodata! internally. 

This did not happen prior to upgrading to Phoenix 1.4 and Cowboy 2.

**Comment by chrismccord** [comment]
Sounds like the issue being tracked on the cowboy side here: https://github.com/ninenines/cowboy/issues/1352

**Comment by chrismccord** [comment]
Note, in the meantime you could downgrade to cowboy 1 while this gets sorted out, if this is an issue affecting prod users

**Comment by brweber2** [comment]
Chris, thanks for the super quick reply! We have a workaround of encoding the JSON to a binary and then calling send_resp ourselves so in our particular case we are ok, but I just wanted to report the issue so it is documented and addressed.

**Comment by whitepaperclip** [comment]
@brweber2 FWIW, I fixed this by adding `config :phoenix, :json_library, Poison` in my config for the time being. Poison doesn't actually encode to `iodata`, so it solves the problem for now.

**Comment by josevalim** [comment]
Fixed in https://github.com/ninenines/cowlib/pull/76.
