### ISSUE TITLE
Recent changes to Heroku deployment guide not reflected on hexdocs.pm

### ISSUE THREAD

**Issue by sdavidson140** [phoenixframework/phoenix#3274]
I was trying to deploy my new Phoenix app (using v1.4.0) to Heroku and was following the Heroku deployment guide here https://hexdocs.pm/phoenix/heroku.html. 

I eventually stumbled upon a now closed issue #3228, and saw that the docs were updated with a fix to my issue (f2fd439eae16bf85c5ad893df11dd92e176c5758 on Jan 21, 2019)

I noticed the issue was closed when the documentation update was merged into `master`, but it doesn't appear the documentation has been updated at https://hexdocs.pm/phoenix/heroku.html

How often does the documentation get updated on https://hexdocs.pm?
Is there a formal process for the publishing of new documentation when `master` is updated?

### Expected behavior
This is the updated documentation which has been merged to `master`
https://github.com/phoenixframework/phoenix/blob/master/guides/deployment/heroku.md

<img width="982" alt="phoenix_docs-17_27_21_pm" src="https://user-images.githubusercontent.com/13722245/52672969-5635bd00-2eed-11e9-8b1b-74eb7f13fc28.png">

### Actual behavior
This is what I am seeing at https://hexdocs.pm/phoenix/heroku.html

<img width="1289" alt="phoenix_docs-17_26_51_pm" src="https://user-images.githubusercontent.com/13722245/52672971-5635bd00-2eed-11e9-9d76-101550656e9b.png">

**Comment by chrismccord** [comment]
I pushed 1.4.1, including updates docs right around the same time this was opened :D. Thanks!
