### ISSUE TITLE
Test fails when schema don't have timestamp fields

### ISSUE THREAD

**Issue by ehayun** [phoenixframework/phoenix#3275]
### Environment

* Elixir version (elixir -v): 1.8.0
* Phoenix version (mix deps): 1.4.0
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system: linux

### Expected behavior
When creating a schema **without** timestamp, everything is OK when I run the application
When running test it should pass OK

### Actual behavior
When running test I am getting an error that the fields: inserted_at and updated_at are missing

**Comment by mpranjic** [comment]
Does your table migration include timestamps?

**Comment by ehayun** [comment]
no, it is not
I removed it from the migration and from the structure

**Comment by mpranjic** [comment]
I suggest the following:
- make sure that you recreated the tables (`MIX_ENV=test mix ecto.reset`)
- check database structure of a database used for testing (eg. `psql database_name` and `\d table_name`) - does it have the timestamps?
- please copy here the actual error you're getting

**Comment by ehayun** [comment]
I just make a fresh new app and the test was OK.
Maybe it was me did something wrong

Thanks

**Comment by ehayun** [comment]
I just make a fresh new app and the test was OK.
Maybe it was me did something wrong

Thanks
