### ISSUE TITLE
Allow mix phoenix.new to work within an existing mix project

### ISSUE THREAD

**Issue by cromwellryan** [phoenixframework/phoenix#33]
I can imagine this working in two ways (or both)
1. Creating a new module/supervisor within an existing OTP project.  Initially the user would need to integrate this into their `Application.Behaviour` or just let the `mix run router` handle things
2. If the project is currently an umbrella project, create a child project that can be integrated in.

**Comment by hayesgm** [comment]
When using phoenix in umbrella apps, you'll likely have to add:

```elixir
deps_path: "../../deps",
lockfile: "../../mix.lock"
```

to your `Mixfile.project/0` function which was generated by phoenix.  It would be great to add a note about this in documentation.

**Comment by josevalim** [comment]
@hayesgm yup, we have issue #583 to tackle this one :)

**Comment by cgarciae** [comment]
Why does a child created with `mix new my_app --sup` get these extra arguments?

```
     build_path: "../../_build",
     config_path: "../../config/config.exs",
     deps_path: "../../deps",
     lockfile: "../../mix.lock"
```
