### ISSUE TITLE
Phoenix returns a 400 error on urls with square brackets when custom dispatch is enabled

### ISSUE THREAD

**Issue by rinpatch** [phoenixframework/phoenix#3301]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 Erlang/OTP 21

* Phoenix version (mix deps): 1.4.1
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: Gentoo Linux, kernel version 4.19.23

### Expected behavior
When using a custom dispatch like this
```elixir
config :app, App.Endpoint,
  http: [
    dispatch: [
    {:_,
      [
      {"/foobar", Phoenix.Endpoint.Cowboy2Handler, {App.Endpoint, []}},
      {:_, Phoenix.Endpoint.Cowboy2Handler, {App.Endpoint, []}}
    ]}
    ]
  ]
```
Phoenix would still process urls containing square brackets

### Actual behavior

Phoenix gives HTTP 400 errors when urls with square brackets are requested, but as soon as `{"/foobar", Phoenix.Endpoint.Cowboy2Handler, {App.Endpoint, []}}` is removed it resumes to process them normally

**Comment by Gazler** [comment]
Could you give an example of a URL that triggers this issue?

**Comment by rinpatch** [comment]
@Gazler `domain.tld/[`

**Comment by Gazler** [comment]
This is happening in Cowboy (I tried the hello world example). I have confirmed with the @essen that it must be urlencoded in that position according to https://tools.ietf.org/html/rfc3986#section-3.3 so is not considered a bug.

**Comment by rinpatch** [comment]
Yup, after thinking about it I realized you are right. Thanks and sorry for wasting your time!
