### ISSUE TITLE
add phx.gen.controller

### ISSUE THREAD

**Issue by gilcierweb** [phoenixframework/phoenix#3309]
add phx.gen.controller, create only controller and action file html.eex 

### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

**Comment by chrismccord** [comment]
We don't accept feature requests on the issue tracker as we reserve GH issues to bugs and active features in development. Please find previous discussions on why we have decided to exclude this feature. Thanks!
