### ISSUE TITLE
/socket is broken in a new phoenix app created with mix phx.new

### ISSUE THREAD

**Issue by rikur** [phoenixframework/phoenix#3313]
### Environment

Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)

* file_system 0.2.6 (Hex package) (mix)
  locked at 0.2.6 (file_system) fd4dc3af
  ok
* connection 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (connection) a1cae722
  ok
* gettext 0.16.1 (Hex package) (mix)
  locked at 0.16.1 (gettext) e2130b25
  ok
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 6b1fab51
  ok
* telemetry 0.3.0 (Hex package) (rebar3)
  locked at 0.3.0 (telemetry) 099a7f3c
  ok
* decimal 1.7.0 (Hex package) (mix)
  locked at 1.7.0 (decimal) 30d6b52c
  ok
* jason 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (jason) b03dedea
  ok
* db_connection 2.0.5 (Hex package) (mix)
  locked at 2.0.5 (db_connection) ddb2ba67
  ok
* ecto 3.0.7 (Hex package) (mix)
  locked at 3.0.7 (ecto) 44dda84a
  ok
* phoenix_pubsub 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (phoenix_pubsub) 496c303b
  ok
* cowlib 2.7.0 (Hex package) (rebar3)
  locked at 2.7.0 (cowlib) 3ef16e77
  ok
* cowboy 2.6.1 (Hex package) (rebar3)
  locked at 2.6.1 (cowboy) f2e06f75
  ok
* mime 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (mime) 30ce04ab
  ok
* postgrex 0.14.1 (Hex package) (mix)
  locked at 0.14.1 (postgrex) 63247d4a
  ok
* ecto_sql 3.0.5 (Hex package) (mix)
  locked at 3.0.5 (ecto_sql) 7e44172b
  ok
* plug_crypto 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (plug_crypto) 18e49317
  ok
* plug 1.7.2 (Hex package) (mix)
  locked at 1.7.2 (plug) d7b7db7f
  ok
* phoenix_html 2.13.1 (Hex package) (mix)
  locked at 2.13.1 (phoenix_html) fa8f034b
  ok
* plug_cowboy 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (plug_cowboy) d798f8ee
  ok
* phoenix 1.4.1 (Hex package) (mix)
  locked at 1.4.1 (phoenix) 801f9d63
  ok
* phoenix_live_reload 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (phoenix_live_reload) 3bb31a9f
  ok
* phoenix_ecto 4.0.0 (Hex package) (mix)
  locked at 4.0.0 (phoenix_ecto) c43117a1
  ok

v11.10.1
6.7.0
18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

### Expected behavior

To be able to connect to `/socket` with a websocket client.

### Actual behavior

`/socket` hits the router and returns 404. However, `ws://localhost:5000/phoenix/live_reload/socket/websocket?vsn=2.0.0` works just fine.

```
wscat -c ws://127.0.0.1:5000/socket
error: Unexpected server response: 404
--
[info] GET /socket
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /socket (SukkaWeb.Router)```

**Comment by rikur** [comment]
What... I need to connect to `/socket/websocket` instead of `/socket`. Speechless.

**Comment by rikur** [comment]
I don't see the additional `/websocket` mentioned in the documentation. Might be worth adding it.

**Comment by OvermindDL1** [comment]
> I don't see the additional /websocket mentioned in the documentation. Might be worth adding it.

The javascript library will connect to either `$path/websocket` or `$path/longpolling` (or something like that) depending on how the client is called among server settings.  In general any other library that connects to phoenix websocket channels should follow the same pattern as the official javascript library.  For non-phoenix-channel-based websockets they can be on any path the server specifies.  :-)

**Comment by ffimnsr** [comment]
I was searching for this as this is not documented elsewhere `/websocket`. I think this would be better documented as some people doesn't use channels or library just the accompanied websocket.

**Comment by kuon** [comment]
I am using raw web socket from kotlin and also hit this issue. I think it should be documented somewhere too.
