### ISSUE TITLE
Phoenix.Controller.put_layout is missing atom second argument from type spec

### ISSUE THREAD

**Issue by wanton7** [phoenixframework/phoenix#3319]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.2
* NodeJS version (node -v): v10.15.0
* NPM version (npm -v): 6.5.0
* Operating system: Windows 10

### Expected behavior
`|> put_layout(:game)` wouldn't cause Dialyzer warning

### Actual behavior
`|> put_layout(:game)` causes `breaks the contract` Dialyzer warning

I'm just learning Elixir but I think type spec `@spec put_layout(Plug.Conn.t, {atom, binary | atom} | binary | false) :: Plug.Conn.t` should be `@spec put_layout(Plug.Conn.t, {atom, binary | atom} | binary | atom | false) :: Plug.Conn.t`.
Because looking at `defp do_put_layout(conn, layout) when is_binary(layout) or is_atom(layout) do` it seems supports an atom.

**Comment by wanton7** [comment]
I was playing around with phoenix_live_view_example when I came across this warning and also posted issue here https://github.com/chrismccord/phoenix_live_view_example/issues/13

**Comment by chrismccord** [comment]
This is fixed on master. Thanks!
