### ISSUE TITLE
mix ecto.create error

### ISSUE THREAD

**Issue by raymondfx** [phoenixframework/phoenix#3320]
what is this error 
`12:19:58.201 [error] GenServer #PID<0.215.0> terminating
** (Postgrex.Error) FATAL 28000 (invalid_authorization_specification) role "postgres" does not exist
    (db_connection) lib/db_connection/connection.ex:84: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Hello.Repo couldn't be created: killed`

Any Fix to it

**Comment by raymondfx** [comment]
> create a db user.

Fixed

**Comment by kpreston1** [comment]
How did you resolve this @raymondfx

**Comment by delameko** [comment]
This is usually because the database settings are incorrect.  Check you can connect to your postgres instance on the command line.
