### ISSUE TITLE
Pain points when instrumenting for distributed tracing

### ISSUE THREAD

**Issue by tsloughter** [phoenixframework/phoenix#3321]
I've been working on OpenCensus support for Phoenix projects at work and wanted to open an issue about the difficulties experienced to hopefully find solutions for future Phoenix releases to have easier instrumentation. 

* Wrapping request handling in a span:

There are at least 3 ways to insert span creation into the process of routing a request. A plug can be placed in the pipeline and use `register_before_send` for finishing the span. The `call` function can be overridden as Spandex does, https://github.com/spandex-project/spandex_phoenix/blob/master/lib/spandex_phoenix.ex#L151. Or a Phoenix Instrumenter can be used and create a span on the `start` event and finish on the `stop` event.

All of these have trade offs, two of which apply to all of them and are included below as overall issues. 

I'll note also that I am not a fan of span creation in event handlers like with an Instrumenter or Telemetry event. Doing so requires a guarantee that events are handled in the same process so that the pdict can be utilized to carry the span context. An interceptor that can wrap the actual handling of a request (but still have access to the route match) in a `try/catch` would be the optimal solution in my opinion but understand that might not be an option.

* Route name for span name:

Example: a request route `get "/user/:name"` should be able to result in an initial span with the name `"/user/:name"`.

Spandex relies on a hack to reverse engineer the route, https://github.com/spandex-project/spandex_phoenix/blob/master/lib/spandex_phoenix.ex#L255. And even with this hack it is not possible to name the initial span with it and they name that span always the same, `"request"`.

* Setting status after controller completes:

Currently the `stop` event of instrumenter does not receive the `conn` which makes it impossible to get the response status for marking a span's status. This may be fixed by https://github.com/phoenixframework/phoenix/pull/3300/files#diff-10541d7f803c04ad1cdbba70a70c0a55R40.

**Comment by josevalim** [comment]
> There are at least 3 ways to insert span creation into the process of routing a request. A plug can be placed in the pipeline and use register_before_send for finishing the span. 

This is the approach we will take on v1.5 with Plug.Telemetry. I am not a fan of `try/catch` because it doesn't provide any meaningful extra guarantee compared to the Plug approach. You can still miss an event because of links. Plus Phoenix already checkpoints the connection in many `try/catch` and that helps guarantee that `register_before_send` is invoked.

I understand that telemetry may not be the best solution for tracing out of the box but we also want to unify how Phoenix emit events and telemetry is the best option for now.

> Route name for span name

I agree we should include this information.

> Setting status after controller completes:

We are no longer planning to emit the stop event altogether so if you think it is important, please comment on that issue. But yes, we should include the conn if we ever get to emit stop (keeping in mind that stop is not guaranteed to be invoked).

**Comment by tsloughter** [comment]
Actually meant `try/after`, but the reason I mention it and the interceptor idea in https://github.com/elixir-plug/plug/issues/806#issuecomment-474629258 isn't an extra guarantee but the explicitness that they are handled in the same process and that context can be in a variable instead of being required to exist in the pdict. That and an interceptor could be attached to any plug and doesn't require registering functions to carry around in `conn` to call at the end.

I can close this now, it sounds like all of this is at least known and being worked on. Should there be an open issue to track the addition of the route to information available for span creation?

And a separate throwaway comment, it really feels awkward how much is stored in `conn` (instead of also having a context variable). Partly because it is named `conn` so sounds like it is just for connection info, like the socket.

**Comment by josevalim** [comment]
> I can close this now, it sounds like all of this is at least known and being worked on. Should there be an open issue to track the addition of the route to information available for span creation?

Let's leave this open as a reminder to work on 2.

> And a separate throwaway comment, it really feels awkward how much is stored in conn

Right. It is mostly a conn but with a field to store whatever you want to avoid having to pass multiple things around.

**Comment by josevalim** [comment]
Telemetry integration in #3426 address these!
