### ISSUE TITLE
Poison.SyntaxError from Phoenix.Socket.V2.JSONSerializer.decode!/2

### ISSUE THREAD

**Issue by indrekj** [phoenixframework/phoenix#3332]
We added sentry to capture errors happening in the project. We started getting `Poison.SyntaxError` which has happened about ~40 times in the past week. We usually have about 5-20K connections open in any given time, from which about 5% are longpoll connections.

This error only seems to be happening with LongPoll transport. My thoughts are that maybe there's a connection issue and for some reason full payload is not sent.

### Environment
Elixir v1.8.1
Phoenix v1.4.1

### Exception

```
Elixir.Poison.SyntaxError: Unexpected end of input at position 0
  File "lib/poison/parser.ex", line 55, in Poison.Parser.parse!/2
  File "lib/poison.ex", line 83, in Poison.decode!/2
  File "lib/phoenix/socket/serializers/v2_json_serializer.ex", line 30, in Phoenix.Socket.V2.JSONSerializer.decode!/2
  File "lib/phoenix/socket.ex", line 549, in Phoenix.Socket.__in__/2
  File "lib/phoenix/transports/long_poll_server.ex", line 64, in Phoenix.Transports.LongPoll.Server.handle_info/2
  File "gen_server.erl", line 637, in :gen_server.try_dispatch/4
  File "gen_server.erl", line 711, in :gen_server.handle_msg/6
  File "proc_lib.erl", line 249, in :proc_lib.init_p_do_apply/3
```

Should [File "lib/phoenix/socket/serializers/v2_json_serializer.ex", line 30](https://github.com/phoenixframework/phoenix/blob/v1.4.1/lib/phoenix/socket/serializers/v2_json_serializer.ex#L30) include error handling? Maybe log a warning instead of blowing up the process?

**Comment by indrekj** [comment]
Yes, default phoenix.js client (v1.4.1).

**Comment by josevalim** [comment]
@indrekj can you please get a copy of the full input when it happens? You can probably find it in the web browser console.

Regarding the error, i think the exception is the best choice, as otherwise the client may expect the server to have processed it and the client may expect the server to be in a state it isn't.

**Comment by indrekj** [comment]
Ok. This problem hasn't occurred in the past 5 days. I'll keep the issue open few more days. I will try to get the browser logs when this happens.

**Comment by indrekj** [comment]
Small status update.

I haven't been able to capture the error from the browser.

I added some logging to Phoenix.Socket.V2.JSONSerializer which however doesn't give much more information. The error itself is `%Jason.DecodeError{data: "", position: 0, token: nil}`. I've gone through the phoenix JS code but I haven't found how this case could ever happen.

Debugging continues...

**Comment by josevalim** [comment]
Hi @indrekj, any news here?

**Comment by indrekj** [comment]
Hey. Sadly no. It still happens few times each week. It's always LongPolling transport. We have a system to send the frontend logs to the backend but I haven't found anything related to this.

I'm closing this ticket as this happens very rarely and I'm not investigating this any more.

**Comment by apoorv-2204** [comment]
Hello,
I am getting the same error, 
please any suggestions ?
```

22-04-18 12:37:09.104 [error] Ranch listener ArchEthicWeb.Endpoint.HTTP had connection process started with :cowboy_clear:start_link/3 at #PID<0.14528.1> 

exit with reason: {%Jason.DecodeError{data: " my data", position: 1, token: nil}, 

[{Jason, :decode!, 2, [file: 'lib/jason.ex', line: 78, error_info: %{module: Exception}]}, 

{Phoenix.Socket.V1.JSONSerializer, :decode!, 2, [file: 'lib/phoenix/socket/serializers/v1_json_serializer.ex', line: 32]}, 

{Phoenix.Socket, :__in__, 2, [file: 'lib/phoenix/socket.ex', line: 466]}, {Phoenix.Endpoint.Cowboy2Handler, 
:websocket_handle, 2, 

[file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 175]}, {:cowboy_websocket, :handler_call, 6, [file: '/home/apoorv-

ubuntu/Desktop/aenode/deps/cowboy/src/cowboy_websocket.erl', line: 528]}, {:cowboy_http, :loop, 1, [file: '/home/apoorv-

ubuntu/Desktop/aenode/deps/cowboy/src/cowboy_http.erl', line: 257]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl',

 line: 226]}]}
```
