### ISSUE TITLE
missing information in eex diagnostics

### ISSUE THREAD

**Issue by RichMorin** [phoenixframework/phoenix#3336]
If an Extended Elixir file begins with an `<%= if ... %>` entry, but has no `<% end %>` entry, the resulting diagnostic message does not specify the file name (let alone the line number): 

    == Compilation error in file lib/phx_http_web/views/item_view.ex ==
    ** (CompileError) lib/phx_http_web/views/item_view.ex:9:
      undefined function if/1
        (elixir) src/elixir_locals.erl:107:
          :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2
        (elixir) src/elixir_locals.erl:108:
      anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
        (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
        (elixir) lib/kernel/parallel_compiler.ex:208:
      anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

**Comment by chrismccord** [comment]
This looks like an issue for the Elixir side as we only implement an EEx engine, so this error is out of our control. Thanks!
