### ISSUE TITLE
Use send_download without encode_www_form

### ISSUE THREAD

**Issue by AllanKlaus** [phoenixframework/phoenix#3343]
It's is not a bug, but I think it's a feature. I was creating a project that enable users to download files with a large variety of names, that user define. When the final user download a a file with the name like `my custom report.xlsx` when download execute it return a file like `my+custom+report.xlsx` and user need to edit it to download with the correct name. 

Instead of use `send_download(conn, kind, opts)` I used in my project the code below

```
conn
|> put_resp_content_type(content_type, "utf-8")
|> put_resp_header("content-disposition", ~s[attachment; filename="#{filename}"])
|> send_file(conn.status || 200, report, 0, :all)
```

### Expected behavior
When download the file `my custom report.xlsx` the file name that appear to download is `my custom report.xlsx`.

### Actual behavior
When download the file `my custom report.xlsx` the file name that appear to download is `my+custom+report.xlsx`

I created the PR to solve it  #3344

**Comment by josevalim** [comment]
Closing n favor of the OR.
