### ISSUE TITLE
Routing requests to a `StaticController` causes a compiler warning

### ISSUE THREAD

**Issue by jmschles** [phoenixframework/phoenix#3346]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.3
* Operating system: macOS 10.14.1

### Expected behavior

I'd expect to be able to route requests to a controller called `StaticController` without issues.

### Actual behavior

I get a compiler warning that looks like a route collision:
```elixir
warning: this clause cannot match because a previous clause at line 1 always matches
  lib/radio_web/router.ex:1
```

Repro steps:
- Generate a new Phoenix app: `mix phx.new radio --no-ecto --no-html --no-webpack`
- Add a line to the router that points a route to a `StaticController`, i.e. `get "/test", RadioWeb.StaticController, :test`
- Compile the app and you should see the warning

Other notes:
- Module nesting has no effect; any routing to `StaticController` will cause this
- Removing `plug Plug.Static` from `RadioWeb.Endpoint` also has no effect

I hope I've come to the right place with this. Of course it's an easy one to work around; I'm just wildly curious to learn what's happening. The closest I've come is discovering that `Phoenix.Endpoint` defines `static_path/1` and `static_url/0`, which seems like it _could_ conflict with route helpers...

Thanks for reading, and for the amazing work you all do!

**Comment by chrismccord** [comment]
We generate a `static_path/url` on the helpers module, which is used for static asset paths, such as the code we generate in the layout for css/js files. This conflicts with the named helper for `StaticController`, so your best option is to rename the controller, or pass a different route name, such as:

    get "/...", StaticController, :test, as: :my_static

Thanks!

**Comment by josevalim** [comment]
Let's raise in this case, since we know upfront that the "static" prefix is reserved!

**Comment by jmschles** [comment]
Thank you both for the responses! It did take some digging for me to understand that the prefix was the source of the problem, so raising could save future developers some time.
