### ISSUE TITLE
Channel join and immediate leave causes a rejoin loop

### ISSUE THREAD

**Issue by JacquiManzi** [phoenixframework/phoenix#3349]
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 
* Phoenix version (mix deps): 1.3
* NodeJS version (node -v): 10
* NPM version (npm -v): 5.6
* Operating system: Mac OSX

### Expected behavior
Joining a channel and then immediately leaving the channel should not cause a rejoin loop.

### Actual behavior

The below code snippet produces a rejoin loop when using the latest phoenix.js code from master.

```
function* subscribeTest(socket) {
  const channel = yield call([socket, 'channel'], 'topic');
  yield call([channel, 'join']);
  yield call([channel, 'leave']);
}
```

I am still debugging this issue, but `this.joinPush.receive("timeout", () => {` is triggered within the Channel object and since the socket is still connected, it schedules a rejoin, which turns into a never ending rejoin loop.

I'll update this with more information as I debug further, but reverting from master to the previous release makes this problem go away.

**Comment by chrismccord** [comment]
Your phoenix version is listed as 1.3, can you try the latest 1.4.3 client? We fixed and improved a number of things around reconnects. Thanks!

**Comment by chrismccord** [comment]
I just saw your comment:

> The below code snippet produces a rejoin loop when using the latest phoenix.js code from master.

Can you share a standard JS snippet that produces the issues, without the function generator and yields? Thanks!

**Comment by JacquiManzi** [comment]
With vanilla JS:

```
function subscribeTest(socket) {
  const channel socket.channel('topic');
  channel.join();
  channel.leave();
}
```

I observed the same rejoin loop happen with the above code.
