### ISSUE TITLE
[QUESTION] LiveView Integration

### ISSUE THREAD

**Issue by loretoparisi** [phoenixframework/phoenix#3354]
Hello, I have followed the docs, but I was not able to completely integrate the new `LiveView` into the boilerplate project described in the docs [here](https://hexdocs.pm/phoenix/adding_pages.html).
[Here](https://github.com/loretoparisi/phoenix-elixir-boilerplate) is the state of my `LiveView` integration of the Snake LiveView example in the gist [here](https://gist.github.com/chrismccord/60a5705482d26326675c7b752ed0dacd)

The main steps I did

 1. Endpoint `endpoint.ex`. You need to add a 

        socket "/live", Phoenix.LiveView.Socket

 2. Router `router.ex`. Add a route to your `LiveView` with `live` keyword: 

        live "/snake", SnakeView

 3. WebApp `yourapp_web.ex`. Add in `view` def the 

        import Phoenix.LiveView, only: [live_render: 2, live_render: 3]

 4. Config in `configs.exs`. Add a `LiveView` salt token: 

        live_view: [
            signing_salt: "YOUR_TOKEN"
         ]
  5. Add a `live` folder in your `yourapp_web` web app folder. Put your `LiveView` view there:

             ├── hello
             │   └── application.ex
             ├── hello.ex
             ├── hello_web
             │   ├── channels
             │   ├── controllers
             │   ├── endpoint.ex
             │   ├── gettext.ex
             │   ├── live
             │   ├── router.ex
             │   ├── templates
             │   └── views
             └── hello_web.ex

My mix deps are

```elixir
defp deps do
    [
      {:phoenix, "~> 1.4.3"},
      {:phoenix_live_view, github: "phoenixframework/phoenix_live_view"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_html, "~> 2.11"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"}
    ]
  end
```

But something is still missing. I have described the issue on SF [here](https://stackoverflow.com/questions/55542517/call-a-view-with-render-in-phoenix-elixir)

Thank you.

**Comment by chrismccord** [comment]
Please use the forums, slack, or SO for questions as we reserve the issue tracker for issues. Thanks!

**Comment by loretoparisi** [comment]
Unfortunately there is any tutorial that shows how to integrate the LiveView, and on SF there are few users on phoenix tags so far :( Could you be so kind to help? Thank you.
