### ISSUE TITLE
addEventListener error when creating Socket in React Native

### ISSUE THREAD

**Issue by aarontropy** [phoenixframework/phoenix#3373]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.3
* NodeJS version (node -v): 10.10.0
* NPM version (npm -v): 6.4.1
* Operating system: MacOS

### Expected behavior
A socket is created 

### Actual behavior
No socket is created and an error (see below) is thrown

In a React Native application, the code I'm using to create a socket is essentially:
```
import { Socket } from "phoenix";

import { getToken } from "./auth";
import consts from "../config/consts";

export const createSocket = async () => {
  const token = await getToken();
  const params = { token };
  const socketOptions = { params };

  return new Socket(consts.socketUrl, socketOptions);
};
```

The `new Socket` line generates an error: 
```
h.addEventListener is not a function. (In 'h.addEventListener("beforeunload", function (e) {
            n.unloaded = !0, n.abnormalClose("unloaded");
          })', 'h.addEventListener' is undefined)
- node_modules/phoenix/priv/static/phoenix.js:1:10435 in e
* src/utils/socket.js:13:20 in openSocket$
- node_modules/react-native/node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
- node_modules/react-native/node_modules/regenerator-runtime/runtime.js:296:30 in invoke
- node_modules/react-native/node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
- node_modules/react-native/node_modules/regenerator-runtime/runtime.js:152:28 in invoke
- node_modules/react-native/node_modules/regenerator-runtime/runtime.js:162:19 in <unknown>
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in <unknown>
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:152:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:200:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:464:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:320:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:17 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```

It looks like it fails here: https://github.com/phoenixframework/phoenix/blob/f69cffadcff5ad9703b0680d83006f9119eb6850/assets/js/phoenix.js#L744

Which was introduced in commit (f69cffadcff5ad9703b0680d83006f9119eb6850) a few weeks ago in PR #3327

I think what is happening is that when creating a new socket, the constructor checks if there is a global window object, and if there is, adds an event listener to it.  The problem is that React Native will create a window object via a polyfill in order to be compatible with some JS libraries.  That window object does not contain an `addEventListener` method.

So Socket finds a `window` object and tries to call a non-existent method. Mayhem ensues.

### Possible solution
on line 743, when the constructor checks for the presence of a global window object, it should also check for the presence of an `addEventListener` method:
`if (globalWindow && typeof globalWindow.addEventListener === 'function') {`

**Comment by chrismcg** [comment]
I think this is a duplicate of https://github.com/phoenixframework/phoenix/pull/3338

**Comment by aarontropy** [comment]
I think you are right.  I searched issues, but not PRs.  If #3338 were merged it would solve my issue.
