### ISSUE TITLE
Socket `onClose` is not called on `disconnect` (js socket client)

### ISSUE THREAD

**Issue by futpib** [phoenixframework/phoenix#3378]
### Environment

* Phoenix npm package: phoenix@1.4.3

The rest of the environment info is probably irrelevant (but provided).

* Elixir version (elixir -v): Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.4.3
* NodeJS version (node -v): v11.14.0
* NPM version (npm -v): 6.9.0
* Operating system: Linux

### Expected behavior

Channel `onClose` callbacks are called after a `disconnect` call.

This is expected for at least these reasons:
* `onOpen` callbacks are called after `connect`
* if you intent to use `onOpen` and `onClose` to display an "online/offline" indicator, it won't work as expected

### Actual behavior

Channel `onClose` callbacks are not called after a `disconnect` call.

### Workaround

Pass a callback to `disconnect`.

**Comment by cybrox** [comment]
@futpib as a sidenote, for online/offline status indicators, there is also [`Phoenix.Presence`](https://hexdocs.pm/phoenix/Phoenix.Presence.html) which should work correctly for that use case.

**Comment by TheMushrr00m** [comment]
About this topic the documentation says this: 

> * `onClose` hooks are invoked only in two cases. 1) the channel explicitly
>  * closed on the server, or 2). The client explicitly closed, by calling
 > * `channel.leave()`

So i think, as @cybrox said, you need to use Phoenix.precense for handle onLeave events.

**Comment by chrismccord** [comment]
As TheMushr00m said, this is correct behavior per the docs and you can handle your teardown code path inside the disconnect callback as mentioned. Thank you!
