### ISSUE TITLE
Dialyzer issue with Phoenix.HTML.form_for/4

### ISSUE THREAD

**Issue by RichMorin** [phoenixframework/phoenix#3381]
The docs for [Phoenix.HTML.form_for/4](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#form_for/4) say that the third argument to the function is optional and defaults to an empty list.

And, in the section entitled [With connection data](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#module-with-connection-data), I see the following example code:

    <%= form_for @conn, Routes.foo_path(@conn, :new), [as: :foo], fn f -> %>
      <%= text_input f, :for %>
      <%= submit "Search" %>
    <% end %>

However, Dialyzer doesn't like it when I omit the third argument:

     The call:
     ...Form.form_for(any(), any(), (_ -> {:safe, [<<_::8>>, ...]}))

     will never return since it differs in arguments with
     positions 3rd from the success typing arguments:

     (any(), any(), maybe_improper_list())

On the other hand, if I explicitly include an empty list in the call:

        <%= form_for @conn, Routes.foo_path(@conn, :new), [], fn f -> %>

The nastygram goes away.

**Comment by chrismccord** [comment]
Closed via https://github.com/phoenixframework/phoenix_html/commit/ccf8872d7abeaad3056743136ef22d80bc3fe2f3

**Comment by RichMorin** [comment]
Looking over the changes, I can't see how they would resolve this use case. However, I'm clearly not an expert. Can someone point me to a test which is specific to this case?

**Comment by wojtekmach** [comment]
Can you give phoenix_html master a shot on your project and see if the error is fixed? If not, I'm happy to give it another shot. I tested it by creating a new mix project that depends on phoenix_html and has this module:

```elixir
defmodule PhoenixHtmlExample do
  def hello do
    Phoenix.HTML.Form.form_for(%Plug.Conn{}, "/foo", fn _f -> {:safe, "foo"} end)
  end
end
```

**Comment by RichMorin** [comment]
I just tried using phoenix_html master, as follows:

      { :phoenix_html, override: true,
        git: "https://github.com/phoenixframework/phoenix_html.git" },

I then removed one of my empty list hacks and Dialyzer did not complain.  Thanks!
