### ISSUE TITLE
How are you supposed to shutdown the server? Beam keeps running.

### ISSUE THREAD

**Issue by adammfrank** [phoenixframework/phoenix#3385]
### Environment

* Elixir version (elixir -v):
1.8.1
* Phoenix version (mix deps):
1.4.3
* NodeJS version (node -v):
10.15.3
* NPM version (npm -v):
6.4.1
* Operating system:
MacOS 10.14.2
### Expected behavior
Activate the Phoenix server. Beam processes start.
Shutdown the server with ctrl-c, a.
Beam processes should stop.

### Actual behavior
4 Beam processes still running using 32 threads each, destroying my battery.
I've only succeeded in stopping them by restarting my computer.

**Comment by chrismccord** [comment]
ctrl-c should be all you need. Are you positive you didn't have other terminals open with iex running? Are you able to recreate this? Thanks!

**Comment by adammfrank** [comment]
Yes sure, and yes. Every time.

**Comment by adammfrank** [comment]
Should it be using this much power in the first place? I'm just doing the Phoenix tutorial. 

I have 1 route created, and I'm not even using the app, but it sends my fans wild. 

2015 Macbook pro.

**Comment by chrismccord** [comment]
Definitely not. The  beam process should be ideal while the server is running but not severing requests. How are you starting the server? When you ctrl-c out, does it drop you back to the shell or hang?

**Comment by adammfrank** [comment]
Starting with mix phx.server.

It sends me back to the shell.

I'm using iterm2, if that matters.

I think it has to do with editing and maybe hot-reload? This time I tested I only got one process, but 32 threads and 100% CPU usage. It started after I edited a controller while the server was running. I don't know if that is a coincidence or not.

**Comment by delameko** [comment]
What editor are you using?

VSCode with the elixir-ls package runs elixir in the background, so it can run Dialyzer against your code.  It runs everytime you make a code change.  That often causes my Macbook 2014 to squeal.

**Comment by adammfrank** [comment]
I’m using vim with vim-elixir.

**Comment by chrismccord** [comment]
@adammfrank can you verify if it's vim-elixir or a related plugin that's causing this? I think Matt is onto something that it is the likely cause, as I can't see how lingering threads would stay alive. If you run the server fresh without having launch vim and kill it, do you get lingering processes?

**Comment by adammfrank** [comment]
Testing now. For general knowledge, how do I shut down a Beam process for good? They keep restarting, which I suppose is what a good Beam process is supposed to do.

**Comment by krepflap** [comment]
> I think it has to do with editing and maybe hot-reload? This time I tested I only got one process, but 32 threads and 100% CPU usage. It started after I edited a controller while the server was running. I don't know if that is a coincidence or not.

Seems eerily similar to #3365, at least the CPU usage part.

What is your Erlang/OTP version installed on your system? For me the behavior normalized when I reverted to OTP 21.1 from 21.3.

**Comment by josevalim** [comment]
> Testing now. For general knowledge, how do I shut down a Beam process for good? They keep restarting, which I suppose is what a good Beam process is supposed to do.

The VM Is meant to shut down once you shut it down, the VM per-se does not restart.

When you start Phoenix, two processes are started: the VM and node. Both attempt to watch the file system for changes. But nothing should cause all of the CPUs to spike up like that. And you definitely should not have multiple beams around.

Follow up questions are:

  * What is your Erlang/OTP version?
  * If you restart the machine, run `mix phx.server` and then hit Ctrl+C twice. Do you have lingering processes?
  * If the above reproduces the issue, can you also reproduce the issue in a brand new app?

**Comment by adammfrank** [comment]
Hey, sorry for the wait. It appears to be related to Vim Plugins, probably
Ale.
I don't need it for this project, so I removed it and now things are
working fine.

This also sped up Vim remarkably.

https://github.com/elixir-editors/vim-elixir/issues/334#issuecomment-486744791

**Comment by josevalim** [comment]
Thanks for following up!
