### ISSUE TITLE
FR: Adjust Router scope/2 to use pattern matching on conn

### ISSUE THREAD

**Issue by chrism2671** [phoenixframework/phoenix#3390]
Currently allows you to match on `host`.

This can't really be used in cloud environments, as the host (and other fields) are obfuscated by the edge layer.

It might be better to allow users to match on whatever part of `conn` they want, for example, `x-forwarded-hosts`. It might also the possibility to negate things (e.g. match any host except).

**Comment by chrismccord** [comment]
You can use a plug upstream in the endpoint to unwrap the obfuscated host and populate the conn.host, which allows the router to work as is :)
