### ISSUE TITLE
Dialyzer error when passing a plug to get/4

### ISSUE THREAD

**Issue by xadhoom** [phoenixframework/phoenix#3393]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.4

### Expected behavior
When passing a plug to get/4 no dialyzer errors should be reported.

### Actual behavior
Dialyzer blames that the plug init fun is called with `[]` instead it should be called with a valid kw list (which is correct). Something in the `Router.get` macro expansion is driving dialyzer mad, since the code works ok.

Here's the log output:

> lib/foo_web/router.ex:1:no_return
> Function __checks__/0 has no local return.
> ________________________________________________________________________________
> lib/foo_web/router.ex:21:call
> The function call will not succeed.
> 
> FooWeb.Plugs.Test.init([])
> 
> will never return since it differs in arguments with
> positions 1st from the success typing arguments:
> 
> ([{:someparam, _}, ...])
> ________________________________________________________________________________
> done (warnings were emitted)

Minimal repo here: https://github.com/xadhoom/phx_dializer_issue just check how the `Test` plug is used in the router

Side issue: `plug_opts` in `get/4` has no typing, so is expected that any term may be passed to the custom plug, while really only some terms are valid, for example passing a map as plug_opts fails macro expansion.

**Comment by xadhoom** [comment]
Additional info: on 1.4.3 this is not happening

**Comment by josevalim** [comment]
Can you please investigate and send a pull requests? We don't have a lot of time to put into tracking dialyzer issues. Thanks.

**Comment by xadhoom** [comment]
The culprit is the new addition of `__checks__` here https://github.com/phoenixframework/phoenix/commit/dbb449d8a6f9db33da89ebc75be2664eebdc97d3

Should be fixed with PR #3409.
