### ISSUE TITLE
SRI Hash mismatch 

### ISSUE THREAD

**Issue by tomciopp** [phoenixframework/phoenix#3394]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.4
* NodeJS version (node -v): 12.1.0
* NPM version (npm -v): 6.9.0
* Operating system: OSX

### Expected behavior
Routes.static_integrity hash should be valid when added as an attribute on a static asset. 

### Actual behavior
In certain conditions the hash will mismatch causing the asset to not load.

### Background

This was a recent feature added by me, and much to my chagrin I ran into an error once I attempted to run this on our site. I spent yesterday evening tracking down what went wrong and am posting the bug here in case anyone runs into it while attempting to add SRI to their site. 

### The issue

Within the digester code, we add the sha512 as a key during the `build_digest/1` step. However there is a subtle mistake that I made. The `file.content` that is being `sha512`'d  is the raw content, not the digested content. Phoenix will replace the contents of certain attributes so that they reference the same digested urls within the content of the digested file. Since the content is different, obviously the hashes will not match and the integrity attribute will be wrong.

### Fixing

I'm going to clone the digester in my project and see if I can add the `digested_content` to that map in the same step that we are adding the sha. I believe there should be a way to rearrange the steps so that we don't see a slowdown and we can get the correct output. I'm going to take this afternoon to see if I can fix it and will report back here if I fail or with a PR if I succeed. (Success in this case means a verified working version that is accessible over the internet)
If you have any alternative ideas that you think are better options let me know.

**Comment by josevalim** [comment]
It is fine to keep the digested content around too as long as we don't persist it to the manifest. :+1: Thanks for looking into this.

**Comment by funtikas25** [comment]
hello pleas help what the hash is hier ???????
[18:21:27] [WARNING] there has been a problem while writing to the session file ('OperationalError: attempt to write a readonly database')
[18:21:30] [INFO] retrieved: 07b1e0439ba077bc7bdfbbf2341b1d1f:dc
[18:21:30] [DEBUG] performed 249 queries in 380.19 seconds
[18:21:30] [INFO] retrieving the length of query output
[18:21:30] [INFO] retrieved: 21
[18:23:18] [DEBUG] performed 10 queries in 107.48 seconds
[18:23:18] [DEBUG] starting 8 threads
[18:24:14] [INFO] retrieved: o_i________________ 2/21 (9%)
