### ISSUE TITLE
phoenix.js 1.4.4 missing on npm

### ISSUE THREAD

**Issue by sebastianseilund** [phoenixframework/phoenix#3396]
Latest version is 1.4.3.

Was hoping to get a fix for this: 😄 

> Fix bug causing error on window unload when no connection is established

Would be great if someone with publish access could publish a new version. Thanks a lot!

**Comment by chrismccord** [comment]
Published. Thanks!

**Comment by sebastianseilund** [comment]
🚀 Wow fast, perfect! Have a nice weekend :)
