### ISSUE TITLE
Hexdocs Guides out of date

### ISSUE THREAD

**Issue by iv-mexx** [phoenixframework/phoenix#3410]
https://hexdocs.pm/phoenix/contexts.html#cross-context-dependencies

### Expected behavior

The Documentation and Guides on Hexdocs should be up to date with the docs in the repo.

### Actual behavior

The Documentation and Guides on Hexdocs are out of date (even though the documentation shows the current version 1.4.5)

I.e. in the [Contexts Guide](https://hexdocs.pm/phoenix/contexts.html#adding-cms-functions)  the  there is a function `inc_page_views/1` defined that does not work anymore. 

This has already been fixed in the current [Contexts Guide on master](https://github.com/phoenixframework/phoenix/blob/master/guides/contexts.md#adding-cms-functions) (fixed in #3284 ), but this change is not reflected on Hexdocs.

As a beginner trying to learn from the guides on Hexdocs, this just took me a while to figure out.

**Comment by josevalim** [comment]
Fix backported.  A new version will be up soon, thanks!
