### ISSUE TITLE
 Unexpected end of JSON input while parsing near '...,"version":"0.12.0","'

### ISSUE THREAD

**Issue by Arthur-Kamau** [phoenixframework/phoenix#3414]
As per the Pheonix Framework official documentation once you create a project, you should cd into assets and run npm install && node node_modules/webpack/bin/webpack.js --mode development.
however in brand new project i constantly get the error.
npm ERR! Unexpected end of JSON input while parsing near '...,"version":"0.12.0","'.

### Environment

* Elixir version (elixir -v):
Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Phoenix version (mix deps):
All dependencies are up to date

* NodeJS version (node -v):
v10.15.3

* NPM version (npm -v):
6.4.1

* Operating system:
Ubuntu 16.04

### Expected behavior
npm install should complete without failure.

### Actual behavior
npm ERR! Unexpected end of JSON input while parsing near '...,"version":"0.12.0","'

**Comment by chrismccord** [comment]
Can you try again? I just created a fresh project on 1.4.5 and could not replicate. If you are able to trace down which package.json from which dep is throwing the error in the stack trace, that would also be helpful. Perhaps you caught a bad package that has been fixed. Please try a new project on 1.4.5 and report back. Thanks!

**Comment by josevalim** [comment]
Closing for now. If you have any news, please let us now and we will gladly reopen it.
