### ISSUE TITLE
Phoenix does not load in Chrome

### ISSUE THREAD

**Issue by gjaldon** [phoenixframework/phoenix#342]
I'm using latest Chrome(v 37) and latest Phoenix from master. I generated a fresh app using `mix phoenix.new` and did not yet make any changes. When visiting localhost:4000 from Chrome, I just get a blank page and no log messages on the server. When visiting localhost:4000 from Firefox, the page loads and displays fine and I get log messages. 

I also get hits on `not_found_debug` when trying to load favicon.ico which show up only when visiting through Firefox. May be completely unrelated though.

Below is a screenshot of my log messages:
![log-messages](https://www.evernote.com/shard/s280/sh/4070ceeb-db50-4ef4-89d5-4c9de85644ce/ceac74ea795bf138975a2188f923d433/deep/0/Screenshot%209/15/14,%2011:40%20PM.jpg)

Does anyone else get this for Chrome or is there something wrong with my Chrome settings? Rails works fine on my Chrome though.

**Comment by dbackeus** [comment]
Just got the same error. Clearing cookies as recommended here worked.
