### ISSUE TITLE
Ability to ignore Phoenix.Endpoint start

### ISSUE THREAD

**Issue by nsweeting** [phoenixframework/phoenix#3435]
Under certain scenarios, I would like to not start a Phoenix.Endpoint. It would be great if this could be done within the endpoint itself vs whatever is supervising it.

It would require adding `:ignore` as valid return value from the `init/2` callback.

```elixir
def init(_type, opts) do
  if start_endpoint?() do
    {:ok, opts}
  else
    :ingore
  end
end
```

**Comment by chrismccord** [comment]
you can conditionally not add it as a child to your supervision tree, so this usecase is covered. Thanks!
