### ISSUE TITLE
phx_new should use String.trim

### ISSUE THREAD

**Issue by crertel** [phoenixframework/phoenix#3437]
![image](https://user-images.githubusercontent.com/1707779/59120396-4a01bf80-8923-11e9-81dc-0d141400b78e.png)

### Environment

* Elixir version (elixir -v): 1.8.2
* Phoenix version (mix deps): 1.4.6
* NodeJS version (node -v): n/a
* NPM version (npm -v): n/a 
* Operating system: Ubuntu 19.04 

### Expected behavior

Fetching phoenix new shouldn't have a warning in the console during compilation.

### Actual behavior

Fetching phoenix new has a warning in the console during compilation.

**Comment by crertel** [comment]
I'd have just submitted a PR for what is probably a minor bug, but oddly enough the Github link on the [Hex page](https://www.hex.pm/packages/phx_new) points here instead of wherever that package exists.

Indeed, I'm not sure that the Hex package is backed by a public repo, which is the real concerning part.

**Comment by wojtekmach** [comment]
phx_new project exists inside this repo, in the [`installer/`](https://github.com/phoenixframework/phoenix/tree/master/installer) directory so feel free to submit PR :)

**Comment by crertel** [comment]
@wojtekmach it looks like this has already been [fixed](https://github.com/phoenixframework/phoenix/blob/master/installer/lib/phx_new/generator.ex#L82). Do you think the version on hex may be off?

This seems odd.

**Comment by wojtekmach** [comment]
Yes, looks like its fixed on master indeed but a new version hasnt been released yet.

**Comment by josevalim** [comment]
I backported this, thanks for reminding us!
