### ISSUE TITLE
Multi example in the Contexts doc might be outdated

### ISSUE THREAD

**Issue by karloescota** [phoenixframework/phoenix#3438]
### Environment

* Elixir version (elixir -v): Elixir 1.8.2 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): locked at 1.4.6 (phoenix)
* NodeJS version (node -v):
* NPM version (npm -v): 
* Operating system:

Code in the documentation for Contexts under [Strategies for cross-context workflows](https://github.com/phoenixframework/phoenix/blob/master/guides/contexts.md#strategies-for-cross-context-workflows) possibly outdated.

Was getting a failing test case at the latter part of the doc, the one with the Multi implementation.

Error:
** (FunctionClauseError) no function clause matching in Ecto.Multi.run/3

I checked the Multi.run doc and it says
> receives the repo as the first argument, and the changes so far as the second argument

I updated the run code to `Multi.run(:user, fn _, _ -> Accounts.create_user(params) end)`
 and it works.

### Expected behavior
```
def register_account(attrs) do
  Multi.new()
  |> Multi.run(:account, fn _, _ ->
    IO.puts "do something here"
  end)
end
```
<img width="498" alt="Screenshot 2019-06-09 at 12 49 50 AM" src="https://user-images.githubusercontent.com/7534948/59150091-8c74ea80-8a50-11e9-81bd-23809506129b.png">

### Actual behavior

```
def register_account(attrs) do
  Multi.new()
  |> Multi.run(:account, fn _ ->
    IO.puts "do something here"
  end)
end
```
<img width="503" alt="Screenshot 2019-06-09 at 12 41 41 AM" src="https://user-images.githubusercontent.com/7534948/59150001-7e729a00-8a4f-11e9-828e-236577234426.png">

Thank you!

**Comment by wojtekmach** [comment]
Good catch. Passing a 1-arity function to Multi.run was deprecated in Ecto 3.0 and removed in Ecto 3.1.
