### ISSUE TITLE
wrong generated third element of context

### ISSUE THREAD

**Issue by nordbit** [phoenixframework/phoenix#3439]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.6
* NodeJS version (node -v): 8.16.0
* NPM version (npm -v): 6.4.1
* Operating system: macOS 10.13.6

### Expected behavior
mix phx.gen.html MediaManager Photo photos caption:string position:integer gallery_id:references:galleries image_id:references:images user_id:references:users
* creating lib/hello_web/controllers/media_manager/photo_controller.ex
* creating lib/hello_web/templates/media_manager/photo/edit.html.eex
* creating lib/hello_web/templates/media_manager/photo/form.html.eex
* creating lib/hello_web/templates/media_manager/photo/index.html.eex
* creating lib/hello_web/templates/media_manager/photo/new.html.eex
* creating lib/hello_web/templates/media_manager/photo/show.html.eex
* creating lib/hello_web/views/media_manager/photo_view.ex
* creating test/hello_web/controllers/media_manager/photo_controller_test.exs
* creating lib/hello/media_manager/photo.ex
* creating priv/repo/migrations/20190608172902_create_photos.exs
* injecting lib/hello/media_manager/media_manager.ex
* injecting test/hello/media_manager/media_manager_test.exs

Add the resource to your browser scope in lib/hello_web/router.ex:

    resources "/photos", PhotoController

Remember to update your repository by running migrations:

    $ mix ecto.migrate
### Actual behavior
mix phx.gen.html MediaManager Photo photos caption:string position:integer gallery_id:references:galleries image_id:references:images user_id:references:users
* creating lib/hello_web/controllers/photo_controller.ex
* creating lib/hello_web/templates/photo/edit.html.eex
* creating lib/hello_web/templates/photo/form.html.eex
* creating lib/hello_web/templates/photo/index.html.eex
* creating lib/hello_web/templates/photo/new.html.eex
* creating lib/hello_web/templates/photo/show.html.eex
* creating lib/hello_web/views/photo_view.ex
* creating test/hello_web/controllers/photo_controller_test.exs
* creating lib/hello/media_manager/photo.ex
* creating priv/repo/migrations/20190608172902_create_photos.exs
* creating lib/hello/media_manager.ex
* injecting lib/hello/media_manager.ex
* creating test/hello/media_manager_test.exs
* injecting test/hello/media_manager_test.exs

Add the resource to your browser scope in lib/hello_web/router.ex:

    resources "/photos", PhotoController

Remember to update your repository by running migrations:

    $ mix ecto.migrate

The context consists of three elements: gallery, image, photo -  photo is added as last and only two elements are correctly generated
```
...
creating lib/hello/media_manager/photo.ex
...
creating priv/repo/migrations/20190608172902_create_photos.exs
...
```

No big deal, but I wonder

**Comment by chrismccord** [comment]
Thanks for the issue! Can you explain a little more what the expected vs actual behavior is that you're seeing? Also can you expand on "photo is added as last and only two elements are correctly generated". What are "elements" in this case? Thanks!

**Comment by nordbit** [comment]
Generated files are in wrong directories and generator do not modify existing context but putting new file (in wrong directories but with correct data, for examle photo_controller.ex is putted under "lib/hello_web/controllers/" directory not "lib/hello_web/controllers/media_manager/", and existing context file "media_manager.ex" is not injected by generator but created putted as new file under "lib/hello" directory  ). 
Only two generated files are in right place - photo.ex and 20190608172902_create_photos.exs

**Comment by chrismccord** [comment]
Phoenix does not namespace the generated controllers under a context because there is often not a 1:1 mapping between your application and your web interface. For the `media_manager.ex` case, phoenix >= 1.4.1 no longer puts the context underneath a directory of the same name, preferring to stay within established elixir conventions. Thanks for the report, but in this case both issues are expected :)
