### ISSUE TITLE
High level architecture diagram Phoenix Web Framework?

### ISSUE THREAD

**Issue by conradwt** [phoenixframework/phoenix#344]
Is there a high level architecture diagram or blog post which describes the goal for Phoenix Web Framework as well as its subcomponents?

**Comment by jbodah** [comment]
Just was asking this same question. Would love to see a block diagram showing where all the major concepts of phoenix fit in. So far Phoenix feels very familiar, but something that shows where endpoints, views, templates, and the like fit in would be great. For example, I find this little diagram very useful for Rails.

![Rails](http://emberjs.com/images/ember_mvc/railsmvc.png)

**Comment by Gazler** [comment]
@jbodah There is an issue on the guides repository with such a diagram https://github.com/phoenixframework/phoenix_guides/issues/118

**Comment by jbodah** [comment]
Cool thanks for letting me know

**Comment by progsmile** [comment]
Thanks for contexts feature - it's has solved ambiguity of models in 1 folder and provide space for storing business logic. But what's going on with folders: controllers, views, templates? They are still ambiguous with files. Modular structure can save all this parts, but I'm dealing with correct views responding, from controllers

![image](https://user-images.githubusercontent.com/6272773/34326285-9205b8d6-e8b1-11e7-90cc-9f60f4de6920.png)

**Comment by chrismccord** [comment]
You are free to represent your directory structure this way, but I'm not convinced it adds any value over the current hierarchy.
