### ISSUE TITLE
class .alert-success is missing from phoenix.css

### ISSUE THREAD

**Issue by pietrofxq** [phoenixframework/phoenix#3441]
The bootstrapped `phoenix.css` has `.alert-info`, `.alert-warning`, and `.alert-danger`, but it's missing the class `.alert-success`: 

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_static/phoenix.css

I was going to create a PR to add it, but I'm not sure where those colors/styles come from, are they from bootstrap v4?

**Comment by chrismccord** [comment]
We don't use `alert-success` anywhere in our generated code as far as I can tell. Are you seeing otherwise?

**Comment by pietrofxq** [comment]
@chrismccord This was a question from someone in slack, I assume some people are using the default styles on their flash messages and other components. If all generated .css files are supposed to contain only the necessary for the bootstrapped application then I think we can close this

**Comment by chrismccord** [comment]
Sounds good. Thanks! Users are free to add their own css classes and/or replace our css entirely.
