### ISSUE TITLE
Convert subscribe_and_join payload to string keys

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#3443]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

### Expected behavior

Using `Phoenix.ChannelTest.subscribe_and_join` a given payload is sent as is.

### Actual behavior

For `Phoenix.ConnTest.post` and others the params are automatically modified to be string keys. I'm wondering if the same would be useful for channel tests.

**Comment by chrismccord** [comment]
Can you submit a PR? Thanks!
