### ISSUE TITLE
return 404 error using custom dispatch in MIX_ENV=prod mix release

### ISSUE THREAD

**Issue by liketemple** [phoenixframework/phoenix#3446]
Environment:
    - Elixir version (elixir -v): Elixir 1.8.1 Erlang/OTP 22
    - Phoenix version (mix deps): 1.4.7
    - NodeJS version (node -v): N/A
    - NPM version (npm -v): N/A
    - Operating system: macOS version 10.14.5

In order to use the raw websocket of cowboy, I put the custom dispatch in config/config.exs:
```
  config :ygspace_service, MyAppWeb.Endpoint,
  url: [host: "127.0.0.1"],
  render_errors: [view: MyAppWeb.ErrorView, accepts: ~w(html json)],
  pubsub: [name: MyApp.PubSub, adapter: Phoenix.PubSub.PG2],
  http: [
    port: 4000,
    dispatch: [
      {:_,
       [
          {"/ws", MyAppWeb.WebsocketHandler, []},
          {:_, Phoenix.Endpoint.Cowboy2Handler, {MyAppWeb.Endpoint, []}}
       ]}
    ]
  ]
```

Then I try "mix phx.server" in the console, using another websocket client connect the server. It works just fine.

But when I use MIX_ENV=prod mix release, and success build prod release, when connecting to the server, it failed, and I got the Phoenix log:
```
[info] GET /ws
[info] Converted error Phoenix.Router.NoRouteError to 404 response
[info] Sent 404 in 177µs
``` 

**Then I put the same dispatch config to config/prod.exs, got the same 404 error**.
Any Information would be help, thanks a lot.

**Comment by chrismccord** [comment]
Are you positive you aren't overriding this config somewhere? If. you are able to shell into your running release, what does `AppWeb.Endpoint.config(:http)` return? Do you have anything in front of the app in prod like an ngnix proxy? This doesn't look like an issue on our side. Thanks!

**Comment by liketemple** [comment]
Thanks for reply.
I have no nginx proxy in front of the app. And I just run the app on my macbook.
And I shell into the running release, get the return of `MyWebApp.Endpoint.config(:http)`:
```
iex(myweb_app@127.0.0.1)2> MyWebApp.Endpoint.config(:http)
[:inet6, {:port, 4000}]
```

I searched the source folder, only find :inet6 config in the  **config/prod.secret.exs**:
```
config :ygspace_service, MyAppWeb.Endpoint,
  http: [:inet6, port: String.to_integer(System.get_env("PORT") || "4000")],
  secret_key_base: secret_key_base
```

Dose the config in config/prod.secret.exs will overrde the config in config/prod.exs?
Actually, I am not clear of the relationship between prod.exs and prod.secret.exs.

I will try to put the same config in prod.secret.exs and upload the result soon.

**Comment by liketemple** [comment]
After I put the same config into config/prod.secret.exs, everything works fine now.
Thanks a lot.
 
It seems the config/prod.secret.exs will override the config/prod.exs. 
Maybe there is no need to have another Endpoint config in config/prod.secret.exs.

**Comment by chrismccord** [comment]
Correct. You only need to customize your "secrets" in prod.secret. The other values you can set in prod.exs. Glad you got things sorted!

**Comment by jung-hunsoo** [comment]
The problem occurs when using `:inet6`. If @liketemple solve the error by overwriting config data, it's because  `http` is set to `inet4`.

You can check the cowboy's listening address when start a server.

**Comment by kaniini** [comment]
I can confirm that changing http to use `:inet6` kills the endpoint config.  Maybe the dispatch table should be moved out of http settings?

**Comment by kaniini** [comment]
workaround:

```
config :yourapp, YourApp.Endpoint,
  http: [:inet6, port: 4000, endpoint: Application.get_env(:yourapp, YourApp.Endpoint)[:http][:dispatch]]
```

Please, make it possible to specify whether IPv4 or IPv6 is used without blowing away everything.

**Comment by adelnizamutdinov** [comment]
for some reason only copy pasting the config works for me =/
