### ISSUE TITLE
put_secure_browser_headers' docs do not contain warning about mixed-case headers

### ISSUE THREAD

**Issue by zweizeichen** [phoenixframework/phoenix#3459]
I just added a mixed-case header as a parameter to `put_secure_browser_headers` (which uses Plug's `merge_resp_headers` behind the scenes) which resulted in invalid HTTP responses. I filed a PR (elixir-plug/plug#853) to add a small warning to that function's documentation. Do we want to add a similar warning to Phoenix's `put_secure_browser_headers` docs?

**Comment by josevalim** [comment]
Yes please.

**Comment by zweizeichen** [comment]
Sweet, I'll try to get a PR ready soon-ish!
