### ISSUE TITLE
@doc entries leaking from Phoenix macros

### ISSUE THREAD

**Issue by RichMorin** [phoenixframework/phoenix#3461]
# Environment

* Elixir version (elixir -v): 1.9.0 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.4.2
* NodeJS version (node -v):
* NPM version (npm -v): v11.7.0
* Operating system: macOS High Sierra (10.13.6)

### Expected behavior

Phoenix macros should not produce entries in ExDoc output pages for the using modules.

### Actual behavior

As discussed in [Remove Phoenix functions from ExDoc View pages?](https://elixirforum.com/t/23620), some macros are leaking `@doc` entries. Two of these instances (`__templates__` and `__recompile__?`) have been addressed in [Remove docs from underscored functions](https://github.com/phoenixframework/phoenix/commit/a8cb0d15b25dd1c5a08c9d1e42711daba7e48f1b), but the one for `template_not_found` has not. In addition, two other instances (`__resource__` and `render`) are still leaking from `view.ex`.

**Comment by chrismccord** [comment]
This was already done in a8cb0d15b25dd1c5a08c9d1e42711daba7e48f1b . Thanks!

**Comment by RichMorin** [comment]
No, that only addresses two of the instances.

**Comment by chrismccord** [comment]
Your views' `render/2` and `template_not_found/2` and user land functions and can/should be doc'd. I don't consider those leaking

**Comment by RichMorin** [comment]
Even if my code makes use of `render/2` and `template_not_found/2`, it does not _define_ them. So, I don't think they should be documented in my app's View pages. In any case, `a8cb0d1` does not address the leakage of `__resource__/0` from `view.ex`.
