### ISSUE TITLE
error page shows the wrong file

### ISSUE THREAD

**Issue by RichMorin** [phoenixframework/phoenix#3462]
### Environment

* Elixir version (elixir -v): Elixir 1.9.0 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.4.2
* NodeJS version (node -v): v11.7.0
* NPM version (npm -v): 6.5.0
* Operating system: macOS 10.13.6 (High Sierra)

### Expected behavior

When Phoenix displays an error page (eg, for "UndefinedFunctionError at GET /"), the displayed code panel should contain code for the relevant line in the file where the error occurred (eg, ".../app.html.eex:8").

### Actual behavior

Phoenix is reporting the correct line and file (to the right of the panel), but the panel displays code from the correct line in the wrong file (".../LayoutView.ex").

### Discussion

I think this is related to the bug that was fixed in Elixir (https://github.com/elixir-lang/elixir/commit/141915625de624dca86723031bda7c9d3e29559e). That is, Elixir is now returning the information necessary for Phoenix to display the correct line and file, but the file name is being ignored for the purpose of displaying the code.

**Comment by josevalim** [comment]
Can you please provide a minimal app that reproduces the issue? Thank you.

**Comment by RichMorin** [comment]
Please see if https://github.com/RichMorin/PA_trim meets your needs.

**Comment by javimolla** [comment]
I tried with this requirements and it works correctly (I think)
- Elixir version (elixir -v): Elixir 1.9.1 (compiled with Erlang/OTP 20)
- Phoenix version (mix deps): 1.4.9
- NodeJS version (node -v): v12.8.0
- NPM version (npm -v): 6.10.3
- Operating system: Windows 7

![imagen](https://user-images.githubusercontent.com/3923038/62703236-055cd800-b9e9-11e9-9a81-bf733a9e8561.png)

**Comment by josevalim** [comment]
Ah yes, it was a bug in Elixir which has been fixed in v1.9.0. Thanks for following up @javimolla, very appreciated!
