### ISSUE TITLE
Not possible to lower Phoenix.Logger :log level for entire endpoint?

### ISSUE THREAD

**Issue by behe** [phoenixframework/phoenix#3463]
I want to lower the log level to `:debug` for all those `GET /path` and `Sent 200 in 1µs` to see them in dev but get rid of them in my prod builds.

Telemetry and Phoenix.Logger replaced Plug.Logger in https://github.com/phoenixframework/phoenix/pull/3426

Before this commit, you could lower the log level in Plug.Logger by changing it to
`plug Plug.Logger, log: :debug` in your endpoint.

Now it only seems possible to change per route scope?

**Comment by josevalim** [comment]
You can still pass `log: :debug` to `plug Plug.Telemetry, event: ...`.

Also please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
