### ISSUE TITLE
Deployment documentation on hexdcocs.pm broken link

### ISSUE THREAD

**Issue by arialblack14** [phoenixframework/phoenix#3465]
The [Releases](https://github.com/phoenixframework/phoenix/blob/master/guides/deployment/releases.md) page is missing on Hexdocs.pm for 1.4.9 version.

So, the links to Releases on the [Phoenix Deployment intro](https://hexdocs.pm/phoenix/deployment.html#content) and at the end of the [same page](https://hexdocs.pm/phoenix/deployment.html#putting-it-all-together) page are broken.

**Comment by bezborodow** [comment]
404 Not Found: https://hexdocs.pm/phoenix/releases.html

**Comment by josevalim** [comment]
Fixed, thanks.
