### ISSUE TITLE
Bump version to 2.0.0-dev or reinstate instrumenters and mark it @deprecated

### ISSUE THREAD

**Issue by garthk** [phoenixframework/phoenix#3467]
G'day!

With all respect, isn't removing `instrumenters` entirely (19b0b01) a breaking API change for anyone using it, even if the commit message says “deprecate”? It's certainly going to break our code, which relies on it to capture trace spans (opencensus-beam/opencensus_phoenix#7).

I'm still ~new, so I've searched to see if the Elixir community has a different understanding of semantic versioning, or the meaning of the word “breaking”, or of “API”. All I've found is Elixir's v1.0 [release notes](https://elixir-lang.org/blog/2014/09/18/elixir-v1-0-0-released/):

> Elixir will follow semantic versioning, which means code written for Elixir v1.0 will continue to compile and run correctly for all versions under the v1 branch (e.g. v1.0.1, v1.1.0, v1.2.0).

… and the documentation for [`Version`](https://hexdocs.pm/elixir/Version.html):

> parsing and requirements follow [SemVer 2.0 schema](https://semver.org/)

Please straighten me out, or un-break the API so you can keep `1.5.0-dev`, or bump the version to `2.0.0-dev` so you don't forget before release.

**Comment by garthk** [comment]
`#phoenix` reckon:

> phoenix never promised automatic backward compatibility
> if Phoenix want to be SemVer then that is breaking change
> (Not that Phoenix follows see ver, nor does it have to)

… which _if documented_ won't feel as much like a fun game of shout-down-the-newbie. In which case, this is a doc-bug. OTOH, from some of the same denizens:

> it would be “nicer” to deprecate this probably
> It do not need to follow server but AFAIK it is recommended by Hex to do so
> As it simplifies version management

Whatever your _intent_, I'll be delighted if you make it explicit.

**Comment by Schultzer** [comment]
Just to put some perspective on this, we have #2850, which I would argue signal that we follow SemVer.

**Comment by chrismccord** [comment]
Hey Garth,

We debated about this, but no longer emitting events is not a breakage in the API. That said, I can see the argument of it breaking user's code if they have an instrumentation lib expecting certain events. v1.4 has deprecation warnings while keeping the existing API and gives notice to jump up to telemetry. Is there a particular reason telemetry is not an option for you within the opencensus lib? I would strongly recommend migrating to telemetry given that's where the whole community is moving for to instrumentation and metrics. Hope that gives some insight. Thanks!
