### ISSUE TITLE
EEx bugfix in Elixir 1.9 changes the behaviour of rendering html in Phoenix

### ISSUE THREAD

**Issue by lachezar** [phoenixframework/phoenix#3482]
What happened: Elixir 1.9 has a bugfix in EEx, which changes how html pages are rendered in Phoenix (I use 1.4.2, but probably all versions are affected). Because of this now there are no spaces between multiple consecutive `link`, `input` and other embedded function calls in the templates. The result is that the missing space or new lines make Chrome (and probably other browsers) to render Bootstrap styled buttons, links, input fields and other cramped together [1].

1.9 release notes: "[EEx] Consistently trim newlines when you have a single EEx expression per line on multiple lines"

Is it possible to make the `trim` option (and may be other options) configurable from the project's configuration and to backport this for the current Phoenix version (pretty please).

This is the line that configures the EEx rendering right now: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/template/eex_engine.ex#L21

I understand that "just write some css, lul" is an appropriate response to this issue in the eyes of some of the people working with this framework, but it will require a ton of modifications, since adding a left/right margin to all `input`, `a` or `button` elements will change the design on every single page of a moderately large project in an unintentional and probably wrong way in large amount of the cases (e.g. if an element is supposed to be left aligned with margin 0).

Nice:
<img width="486" alt="Screen Shot 2019-07-15 at 8 00 28 PM" src="https://user-images.githubusercontent.com/130336/61237726-66232880-a73b-11e9-804f-5d644d3172dc.png"> 

vs

Cramped:
<img width="483" alt="Screen Shot 2019-07-15 at 8 01 16 PM" src="https://user-images.githubusercontent.com/130336/61237749-763b0800-a73b-11e9-8540-eb92a8fa912f.png">

**Comment by chrismccord** [comment]
Can you share your EEx snippet that produces the above? Thanks!

**Comment by lachezar** [comment]
This is the excerpt of the template that matches the screenshot. 

```
...
<%= form_for @conn, Routes.marketing_path(@conn, :export), [method: :get, autocomplete: "off"], fn f -> %>
    <%= label(f, :date_range, "Date range:", for: "date-picker-field") %>
    <%= text_input(
      f, 
      :date_range, 
      id: "date-picker-field", 
      class: "date-picker-field", 
      data: [date_range_minimum: @date_range_minimum, validation_message: @date_picker_validation_message], value: @default_date, pattern: @date_picker_input_pattern) 
      %>
    <%= submit(dgettext("imperative_verb", "Export"), class: "button", data: [prevent_double_submit: "false"]) %>
  <% end %>
...
```

If I add a second new line after each embedded function call, then the result is not cramped again as it used to be in the previous versions of Elixir.

**Comment by josevalim** [comment]
For now I would recommend to either go with double spaces or an explicit `&nbsp;`. If this continues to be an issue, we can make trim optional. Thanks!
