### ISSUE TITLE
Configuration not imported in Umbrella app

### ISSUE THREAD

**Issue by bdubaut** [phoenixframework/phoenix#3484]
Hi everyone, I'm working in an umbrella app with a phoenix web project in it. I'm using Elixir 1.9 & Phoenix 1.4, and I was struggling to get the new mix releases work: the Mix.Config files were not picked up when building the release (After I followed the [Phoenix guide](https://hexdocs.pm/phoenix/releases.html#releases-assemble) for working with releases).

After some digging and conversation on the [Elixir slack](https://elixir-lang.slack.com/archives/C0LH49EPQ/p1563351442347200), I finally pin-pointed the issue: Phoenix's configuration files are using `Mix.Config` instead of importing the `Config` module from Elixir 1.9

### Environment

* Elixir version (elixir -v): 1.9.0
* Phoenix version (mix deps): 1.4.9
* Operating system: MacOs Mojave

**Comment by andrewmurph** [comment]
I had the same problem a few days ago - reading [Elixir's Release Docs](https://hexdocs.pm/mix/Mix.Tasks.Release.html) helped a lot. 
The section on [runtime configuration](https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-runtime-configuration ) was especially helpful to configure when to serve phoenix web app endpoints depending on the release name.

**Comment by josevalim** [comment]
Yes, unfortunately we cannot change to `import Config` by default because that would force everyone to use Elixir v1.9.0. So the caveats are for now documented in the release guides, thanks.

**Comment by sanjibukai** [comment]
Hello,

> After some digging and conversation on the [Elixir slack](https://elixir-lang.slack.com/archives/C0LH49EPQ/p1563351442347200), I finally pin-pointed the issue: Phoenix's configuration files are using `Mix.Config` instead of importing the `Config` module from Elixir 1.9

So does replacing `use Mix.Config` with `import Config` simply worked in this case? I mean for elixir >1.9 apps is `import Config` a dropin replacement of `use Mix.Config`?

> Yes, unfortunately we cannot change to `import Config` by default because that would force everyone to use Elixir v1.9.0. So the caveats are for now documented in the release guides, thanks.

I wonder if is it possible to make `mix` checking versions in order to apply the correct statement. I'll try to figure out how `mix` is doing things and..

**Comment by josevalim** [comment]
Yes, it should be a drop-in replacement.

**Comment by gertcuykens** [comment]
When doing `mix phx.new ...` Can you maybe just generate a extra comment line in `./config/config.exs` file please that mentions `use Mix.Config` can be replaced with `import Config` when using Elixir v1.9.0+ ?

**Comment by josevalim** [comment]
Phoenix master is v1.9+ so I just did this change. :)

**Comment by sanjibukai** [comment]
> Phoenix master is v1.9+ so I just did this change. :)

Your reactivity rocks José!

Love working with Elixir!
