### ISSUE TITLE
Link to download phoenix_html.js seems outdated

### ISSUE THREAD

**Issue by jpincas** [phoenixframework/phoenix#3487]
At the top of the `app.js` template, the following comment appears:

```// for phoenix_html support, including form and button helpers
// copy the following scripts into your javascript bundle:
// * https://raw.githubusercontent.com/phoenixframework/phoenix_html/v2.10.0/priv/static/phoenix_html.js
```

Using that JS, delete functionality didn't seem to work, so I did some digging and found the latest version of this file at:

`https://raw.githubusercontent.com/phoenixframework/phoenix_html/master/priv/static/phoenix_html.js`

Using that JS fixed my delete issue.

Perhaps the link needs to be changed?

**Comment by javimolla** [comment]
But changing the link pointing to master could be problematic for projects that use older versions of Phoenix

But it be appropiate to change that link for this file path: deps\phoenix_html\priv\static\phoenix_html.js ?

**Comment by josevalim** [comment]
Fixed in master, thanks!
