### ISSUE TITLE
New router checks cause a lot of recompilation, even with plug_init_mode: :runtime

### ISSUE THREAD

**Issue by cblavier** [phoenixframework/phoenix#3493]
Hey there,

When updating phoenix from 1.4.3 to 1.4.4 I had a lot of recompilation (more than 200 files) every times I changed a controller.

I finally figured out that this specific commit caused the problem: `dbb449d8a6f9db33da89ebc75be2664eebdc97d3`, whatever `plug_init_mode` value I set.

I was able (see this [thread](https://elixirforum.com/t/modifying-a-controller-recompiles-my-router-and-all-ui-layer)) to fix a lot of dependency issue using `mix xref`. But as it wasn't even an issue pre 1.4.4, I'm wondering if it should be considered as a regression?

### Environment

* Elixir version (elixir -v): Elixir 1.7.4
* Phoenix version (mix deps): `dbb449d8a6f9db33da89ebc75be2664eebdc97d3`
* Plug: 1.8.2

**Comment by josevalim** [comment]
The checks only add a runtime dependency. For you to be triggered recompilations, it means you still have some compile time dependencies between the router and your code. If you address them, then the issue should disappear.

**Comment by cblavier** [comment]
Ok, I got and solved most of these dependencies.

But I still don't understand why, if the checks were only runtime, I suddenly had 200 files recompiling at each controller change when updating Phoenix to this specific revision (if checks were only runtime it shouldn't have changed anything?)

**Comment by josevalim** [comment]
A runtime dependency is only recompiled if there is a compile time dependency between them. A runtime dependency is not enough to trigger a recompile, which is what I said something else is at stake here.

**Comment by cblavier** [comment]
Ok thanks, I understand now :)

**Comment by josevalim** [comment]
So taking a deeper look it seems the actual issue is a compile time dependency between the endpoint and the router. Now, since the router has a runtime dependency on controllers and i assume many things have a dependency in the endpoint, that's what is triggering it. There is a new plug version out with a fix but you should most likely fix the compile time dependency you have on your endpoint. :)

**Comment by cblavier** [comment]
Already spent 3 days playing with `mix xref` ;-) But I fixed everything now (mostly dependencies from various plugs to Router or LayoutView were causing the issue)
