### ISSUE TITLE
hex docs for deployment is outdated

### ISSUE THREAD

**Issue by calvin-kargo** [phoenixframework/phoenix#3496]
at deployment hexdocs (https://hexdocs.pm/phoenix/deployment.html) there is this
>If for some reason you do not want to rely on environment variables, you can hard code the secrets in your config/prod.secret.exs, but make sure to check the file into your version control system.

looking `phoenix/guides/deployment/deployment.md` there relevant section is
>If for some reason you do not want to rely on environment variables, you can hard code the secrets in your config/prod.secret.exs, but make sure **not** to check the file into your version control system.

**Comment by Gazler** [comment]
Thanks. Backmerged a36fbf07dc34bc1576b607abb0658928f26e9548 into 1.4 and republished the docs.
