### ISSUE TITLE
request process be killed when cancel a request,  mysql transaction never commit or rollback

### ISSUE THREAD

**Issue by taverngoal** [phoenixframework/phoenix#3503]
### Environment

* Elixir version (elixir -v):  `Erlang/OTP 21` and `Elixir 1.8.2`
* Phoenix version (mix deps):  `1.4.9`
* Operating system: `macOS 10.14.5`

### Expected behavior

request process  will not be kill. and mysql transaction will be committed or rollbacked

### Actual behavior

I have a mysql transaction in my action, when I request the action, and then I cancel the request(click Stop in Jmeter, Or close the browser), it shows `[error] MyXQL.Connection (#PID<0.407.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.780.0> exited`, and transaction never be commited or rollback

here's my code:

```elixir
defmodule XxxWeb.HomeController do
  @moduledoc false

  use XxxWeb, :controller
  alias Xxx.Repo

  def index(conn, _params) do

    Repo.transaction fn ->
      Process.sleep(5000)
    end

    json(conn, %{ping: "pong"})
  end
end
```

logs:

```
[info] GET /
[debug] Processing with XxxWeb.HomeController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] QUERY OK db=8.2ms queue=0.1ms
begin []
[error] MyXQL.Connection (#PID<0.407.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.780.0> exited

```

**Comment by taverngoal** [comment]
`Task.Supervisor`  solved my business

But,  is there a nice way improve the business?  settings  or configs?

sorry for my poor English

Thanks

**Comment by Gazler** [comment]
Using a `Task.Supervisor` so that a different process performs the database logic is a reasonable way to handle async database requests.
