### ISSUE TITLE
Syncing presences is slow in Phoenix JS due to clone()

### ISSUE THREAD

**Issue by indrekj** [phoenixframework/phoenix#3509]
State is cloned in two places:
syncState: https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L1282
syncDiff: https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L1323

We have a presence channels with couple of thousand of users. There are users joining and leaving quite often.

Here's a 10 second performance test in chrome:
![Screen Shot 2019-08-05 at 11 06 17](https://user-images.githubusercontent.com/3438/62448746-25826200-b771-11e9-8e12-aa1a20d523f0.png)
![Screen Shot 2019-08-05 at 11 06 49](https://user-images.githubusercontent.com/3438/62448750-274c2580-b771-11e9-85d8-5857ac523e14.png)

`value` links to the `clone` function.

With changing clone to no-op:

![Screen Shot 2019-08-05 at 11 10 07](https://user-images.githubusercontent.com/3438/62448929-9a559c00-b771-11e9-8e1b-3f1d2221a5e5.png)

The difference is huge in our case.

Do you think this could be changed? If not, what do you think about introducing a config variable like `allowStateMutations`?

@chrismccord I think you introduced clone in dffe053. The commit message tells about what but not much about why. What do you think?

**Comment by dvic** [comment]
In case we need to keep clone around: is a deep clone needed? If not,  [1] suggests using Object.assign to do a shallow copy is much faster:
![image](https://user-images.githubusercontent.com/1214337/99526570-b8153780-299b-11eb-8871-6e5718ea13b4.png)

Alternatively, we could copy the lodash implementation to also improve the performance in case of a deep clone.

[1] https://frontbackend.com/javascript/what-is-the-the-fastest-way-to-deep-clone-an-object-in-javascript
