### ISSUE TITLE
redirect/2 and mailto: links

### ISSUE THREAD

**Issue by chrism2671** [phoenixframework/phoenix#3520]
### Environment

* Phoenix version (mix deps): 1.4.9

### Expected behavior
`redirect(conn, external: "mailto:bill@microsoft.com")` opens email client.

### Actual behavior
`redirect(conn, external: "mailto:bill@microsoft.com")` redirects to `https://mailto:bill@microsoft.com`.

**Comment by chrism2671** [comment]
I tried to set the redirect headers manually using `put_resp` and this resulted in the same behaviour, so perhaps this isn't fixable.

**Comment by delameko** [comment]
Even if this could work, the user is going to be left with an empty page in the web browser.

You be better redirecting to a page explaining what's happening, with a mailto link, and a meta tag in the header:

    <meta http-equiv="refresh" content="0; url=mailto:bill@microsoft.com" />

**Comment by chrism2671** [comment]
I think I made a mistake here, closing issue.
