### ISSUE TITLE
Documentation for Generated HTML Forms

### ISSUE THREAD

**Issue by nikhiljha** [phoenixframework/phoenix#3525]
Phoenix's default HTML forms allow you to create lists and maps and tuples, but how to do this isn't documented anywhere.

To get a map %{"two" => "form value"}...

```
<%= text_input f, :options_two, name: "checkmap[options][two]", class: "form-control" %>
```

To get a list ["form value 1", "form value 2"]...

```
<%= text_input f, :options_two, name: "checkmap[options][]", class: "form-control" %>
<%= text_input f, :options_two, name: "checkmap[options][]", class: "form-control" %>
```

To get a tuple with an array in it {"test", %{"one" => "form value", "two" => "form value"}}...

```
<%= text_input f, :options_two, name: "checkmap[options][test][one]", class: "form-control" %>
<%= text_input f, :options_two, name: "checkmap[options][test][two]", class: "form-control" %>
```

But there are a couple things I wasn't able to figure out. For example, how do I get a list of tuples? [%{"one" => "form value", "two" => "form value"}, %{"one" => "form value", "two" => "form value"}]

**Comment by chrismccord** [comment]
Please check the `phoenix_html` docs. If you think they could be improved, we'd definitely love a PR over there. Thanks!
