### ISSUE TITLE
Route logging cannot be disabled

### ISSUE THREAD

**Issue by jeroenbourgois** [phoenixframework/phoenix#3530]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.4.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.2 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): 10.15.3
* NPM version (npm -v): 6.4.1
* Operating system: macOS

### Expected behavior
Hitting the root url should show no logging, when that route has `log: false` in the router:

```
  scope "/", StoplogWeb, log: false do
    pipe_through :browser

    get "/", PageController, :index, log: false
  end
```
This is done on a vanilla new phx project.

### Actual behavior
Two log lines are captured:
```
[info] GET /
[info] Sent 200 in 12ms
```

**Comment by chrismccord** [comment]
That is coming from your `Plug.Logger` in the endpoint, or as of 1.4.9, `Plug.Telemetry`. Thanks!

**Comment by jeroenbourgois** [comment]
@chrismccord yes, I realize that, but the docs made me believe that that plug may be left untouched? The project was newly scaffolded, so I thought it was supposed to work with that setup and I supposed as well that the log: false would just deactivate logging for that route. In our own app I now removed the `Plug.Logger` from the Endpoint and added it throughout several pipelines.

Thanks for the response!

**Comment by Gazler** [comment]
Just to clarify here, the `Plug.Logger` or `Plug.Telemtry` plugs are typically in your endpoint, which will apply to all routes. The log level on the `scope` is specifically for these log messages:

```
08:35:52.267 [debug] Processing with MyApp.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
```
