### ISSUE TITLE
Add accept-language to the list of headers that are copied in Phoenix.ConnTest.recycle

### ISSUE THREAD

**Issue by syfgkjasdkn** [phoenixframework/phoenix#3531]
### Environment

* Phoenix version (mix deps): 1.4

### Expected behavior
Copy the `accept-language` headers over into the recycled `conn` by default in tests.

### Actual behavior
It's not being copied by default: https://github.com/phoenixframework/phoenix/blob/v1.4/lib/phoenix/test/conn_test.ex#L476

### The use-case
When using `Cldr.Plug.SetLocale` (@kipcole9 sorry to bother you, but thought you might be interested in this as well) with "repeated" requests

```elixir
conn = build_conn() |> set_req_header("accept-language", "ja")
conn = get(conn, path) # correct locale
conn = get(conn, other_path) # incorrect locale (uses cldr's default, assuming "ja" is not the default locale), since the conn has been recycled and "accept-language" is no longer present
```

within the same test, the plug [overwrites](https://github.com/elixir-cldr/cldr/blob/7df7f8b8309f8c07f39c498e18794a0152f3bc20/lib/cldr/plug/plug_set_locale.ex#L133) the conn's locale on all requests after the first since it doesn't find the `"accept-language"` header. If, however, `"accept-language"` header was copied in each `recycle` call over into the new conn, that wouldn't be the case.

**Comment by syfgkjasdkn** [comment]
I can make a PR if this makes sense.

However if there are easy workarounds, which don't involve "manually" recycling the `conn` before each repeated request, that'd be great.

**Comment by josevalim** [comment]
@syfgkjasdkn yeah, sounds simple enough! please send a PR. :)
