### ISSUE TITLE
Make channel payload spec more flexible

### ISSUE THREAD

**Issue by LightningK0ala** [phoenixframework/phoenix#3532]
In the phoenix channel callbacks specs, the `payload` argument for `join` and `handle_in` is defined as type map.

Is there a reason why the payload must be a map? I've tried sending a string from the client and it seems to work but unfortunately the current spec means my dialyxir task will fail.

Would it make sense to extend the spec to allow String.t() (and potentially other types)?

https://github.com/phoenixframework/phoenix/issues

**Comment by chrismccord** [comment]
This is intentional to make the serializer contract better constrained for other serialization formats. We have no plans to extend the spec at this time. Thanks!
