### ISSUE TITLE
Connection Refused (ssl: false)

### ISSUE THREAD

**Issue by Rajan** [phoenixframework/phoenix#3536]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): 10.16.3
* NPM version (npm -v): 6.9.0
* Operating system: Ubuntu 19.04 LTS

### Expected behavior

The app should be accessible post following deployment and seeing the following.
```
root@creato:~/creato# PORT=4001 MIX_ENV=prod mix phx.server
19:41:12.715 [info] Running CreatoWeb.Endpoint with cowboy 2.6.3 at :::4001 (http)
19:41:12.729 [info] Access CreatoWeb.Endpoint at http://creato.co

```

### Actual behavior

```
curl -v http://creato.co
* Rebuilt URL to: http://creato.co/
*   Trying 149.28.136.40...
* TCP_NODELAY set
* Connected to creato.co (149.28.136.40) port 80 (#0)
> GET / HTTP/1.1
> Host: creato.co
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 502 Connection refused
< Date: Sun, 25 Aug 2019 19:41:56 GMT
< Connection: close
< Cache-Control: no-store
< Content-Type: text/html
< Content-Language: en
< Content-Length: 213
< 
<HEAD><TITLE>Connection refused</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black">
<FONT FACE="Helvetica,Arial"><B>
 Connection refused</B></FONT>

<!-- default "Connection refused" response (502) -->
</BODY>
* Closing connection 0

```
More tests from cmd.
```
Rajans-MacBook-Pro:~ rajanchandi$ wget http://149.28.136.40
--2019-08-26 01:13:48--  http://149.28.136.40/
Connecting to 149.28.136.40:80... connected.
HTTP request sent, awaiting response... 502 Connection refused
2019-08-26 01:13:48 ERROR 502: Connection refused.

Rajans-MacBook-Pro:~ rajanchandi$ wget http://149.28.136.40:4001
--2019-08-26 01:13:52--  http://149.28.136.40:4001/
Connecting to 149.28.136.40:4001... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-08-26 01:14:08--  (try: 2)  http://149.28.136.40:4001/
Connecting to 149.28.136.40:4001... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-08-26 01:14:26--  (try: 3)  http://149.28.136.40:4001/
Connecting to 149.28.136.40:4001... connected.
HTTP request sent, awaiting response... 

```

**Comment by Rajan** [comment]
A test app did work on port 4000 which was created on the server. After deploying the app from git, everything has stopped working. There's some sort of cowboy2 setup corruption might have happened.

**Comment by chrismccord** [comment]
Can you verify if a fresh application is working for you? Are you upgrading and seeing this? We don't have enough information to say exactly what's going on, but if you could verify a fresh application with default prod config that would help narrow down. Thanks!

**Comment by chrismccord** [comment]
Can you also verify if anything is in front of the app? Load balancer, nginx, etc? The 502 appears from upstream, not us.

**Comment by Rajan** [comment]
There's no Nginx on the system.
It worked after disabling firewalls.

**Comment by captn3m0** [comment]
@Rajan Are you using Jio internet by any chance?

Looks very similar to the issue described here: https://twitter.com/kingslyj/status/1172737012316590080
