### ISSUE TITLE
Phoenix does not evaluate Env config overrides at runtime

### ISSUE THREAD

**Issue by mobileoverlord** [phoenixframework/phoenix#354]
When deploying using exrm, and by setting the PORT env variable prior to launching the application, phoenix is unable to use my env variable for overriding the prod config setting for PORT.

**Comment by bitwalker** [comment]
Just to follow up here with notes from the conversation @josevalim and I had in IRC this morning:

- I'll add support for a new experimental config section `system_env`, which will contain app-specific configuration values which will be pulled from the system environment at boot time.
- If a user has System.get_env calls in config.exs, but no `system_env` section, a warning will be generated notifying them that any runtime configuration which depends on the system environment should be moved to that section.
- At boot time, the `system_env` section will be evaluated, and the environment values will be applied to the appropriate configuration settings via the `-application` flag when booting the VM.

An example of what the `system_env` section would look like in `config.exs`:

```elixir
config :sasl,
  errlog_type: :error
config :phoenix,
  port: 8000

system_env: [
  phoenix: [ port: "PORT" ]
]
```

In this example, `phoenix: port` would be `8000`, unless the `PORT` environment variable is defined, which takes precedence. In this way you can emulate the `System.get_env("PORT") || Application.get_env(:phoenix, :port)` behavior.

I've started a discussion on this [on the exrm issue tracker](https://github.com/bitwalker/exrm/issues/90). Chime in there with thoughts on the specifics. As for how it applies to this particular issue, does everyone feel like this is a workable solution?

**Comment by guilleiguaran** [comment]
@bitwalker @josevalim the proposed solution looks great for me :+1:

**Comment by josevalim** [comment]
We are closing this in favor of the discussion on exrm issues tracker!
