### ISSUE TITLE
Documented telemetry events are not executed anywhere

### ISSUE THREAD

**Issue by dariodf** [phoenixframework/phoenix#3545]
When looking at the telemetry events in https://github.com/phoenixframework/phoenix/pull/3426 I found the documented [`[:phoenix, :endpoint, :start]`](https://github.com/phoenixframework/phoenix/pull/3426/files#diff-2e48d48e1c6c3b085dab25613ade742bR238) and [`[:phoenix, :endpoint, :stop]`](https://github.com/phoenixframework/phoenix/pull/3426/files#diff-2e48d48e1c6c3b085dab25613ade742bR243) events, which are also [attached in the logger](https://github.com/phoenixframework/phoenix/pull/3426/files#diff-f042a7a3427d7a4407a110bee1d419e0R35). However, these events are never executed anywhere in the code.

### Environment

* Phoenix JS library v1.4.9

### Expected behavior

Attaching the `[:phoenix, :endpoint, :start]` and `[:phoenix, :endpoint, :stop]` telemetry events will run the attached functions at the beggining of every request and when the response is sent, as documented.

### Actual behavior

The attached events are never executed, so the attached functions never run.

**Comment by rabidpraxis** [comment]
Phoenix does not directly execute those events. It delegates to a telemetry plug. If you make sure you are using phoenix ~> 1.4.6 and ecto_sql ~> 3.1, then you can add the `Plug.Telemetry` plug and you should be getting those telemetry events.

**Comment by dariodf** [comment]
I misunderstood the docs. Thanks for clearing that up!
