### ISSUE TITLE
specifying that the http listener should use ipv6 should not blow away the rest of the http config

### ISSUE THREAD

**Issue by kaniini** [phoenixframework/phoenix#3549]
### Environment

* Elixir version (elixir -v): `Elixir 1.8.2 (compiled with Erlang/OTP 22)`
* Phoenix version (mix deps): `locked at 1.4.9 (phoenix) 746d098e`
* NodeJS version (node -v): not installed
* NPM version (npm -v): not installed
* Operating system: Alpine Linux 3.10

### Expected behavior

in prod.secret.exs:

```
config :yourapp, YourApp.Endpoint,
  http: [:inet6, port: 4000]
```

should not blow away the rest of `YourApp.Endpoint[:http]` config.

### Actual behavior

Setting inet6 blows away the rest of the endpoint config including dispatch table.

**Comment by minibikini** [comment]
I can confirm.

The Config deep merges keyword lists only and `[:inet6, port: 4000]` is a regular list so Config overwrites `:http` value.

Quick fix: move `:inet6` from `endpoint_config[:http]` to `endpoint_config[:http][:transport_options][:socket_opts]` like this:

```elixir
config :yourapp, YourApp.Endpoint,
  http: [port: 4000, transport_options: [socket_opts: [:inet6]]]
```
