### ISSUE TITLE
URL returned by the c:url/0 in Endpoint ignores path value

### ISSUE THREAD

**Issue by hauleth** [phoenixframework/phoenix#3558]
### Environment

* Elixir version (elixir -v):
  ```
  Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

  Elixir 1.9.1 (compiled with Erlang/OTP 22)
  ```
* Phoenix version (mix deps):
  ```
  * plug 1.8.3 (Hex package) (mix)
    locked at 1.8.3 (plug) 12d5f979
    ok
  * plug_cowboy 2.1.0 (Hex package) (mix)
    locked at 2.1.0 (plug_cowboy) b7576815
    ok
  * phoenix 1.4.10 (Hex package) (mix)
    locked at 1.4.10 (phoenix) 619e4a54
    ok
  ```
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: macOS 10.14.6

### Expected behavior

When set in configuration:

```elixir
config :my_app, MyAppWeb.Endpoint, url: [path: "/foo"]
```

```elixir
iex> MyAppWeb.Endpoint.url
"http://localhost:5000/foo"
```

### Actual behavior

```elixir
iex> MyAppWeb.Endpoint.url
"http://localhost:5000/"
```

**Comment by feliperenan** [comment]
It seems that the function`Endpoint.url/0` is supposed to return only the URL without path.

https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#c:url/0

If you want to get URL + path, I think you should use one of the functions generated in your application helpers.

https://github.com/phoenixframework/phoenix/blob/cb469a4d2f7ee3ca14b1a4bf8de4ee7a590067a5/lib/phoenix/router/helpers.ex#L151-L164

For instance:

```Elixir
iex> MyAppWeb.Router.Helpers.static_url(MyAppWeb.Endpoint, "/")
"https://localhost:4000/custom_path"
```

**Comment by josevalim** [comment]
Yes, as @feliperenan said, this is by design because the path for a request is retrieved from the connection information or from the url configuration. It is one of the things that, if you change dynamically, it can mean that you may generate routes that will never be matched because they got out of sync.
