### ISSUE TITLE
mix tasks documentation in the 1.4.10 release is not up-to-date with master

### ISSUE THREAD

**Issue by vais** [phoenixframework/phoenix#3564]
### Environment

* Elixir version (elixir -v): Elixir 1.9.1 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): phoenix 1.4.10 (Hex package) (mix) locked at 1.4.10 (phoenix) 619e4a54
* NodeJS version (node -v): v10.15.3
* NPM version (npm -v): 6.4.1
* Operating system: Windows 10

### Expected behavior
Documentation for mix tasks (`mix help phx.gen.html`) is up-to-date

### Actual behavior
Documentation for mix tasks (`mix help phx.gen.html`) is __NOT__ up-to-date

E.g. [this commit](https://github.com/phoenixframework/phoenix/pull/3279/commits/b01eba57e4023dbe3a73fd71b14f855b1a5faa4b) has been on `master` since February 19, but it's not in the `1.4.10` release that was released in September. Is this a bug?

**Comment by javimolla** [comment]
I don't know why this file wasn't included in the releases from 1.4.2 to 1.4.10. It's something, probably,  only @chrismccord may answer

Now it's in the master branch, so we can hope it will be included in the future releases

**Comment by josevalim** [comment]
Backported, thanks!
