### ISSUE TITLE
Docs: Include instruction for how to enter the psql console

### ISSUE THREAD

**Issue by trosel** [phoenixframework/phoenix#3568]
### Problem
In [this doc](https://github.com/phoenixframework/phoenix/blob/103f239082a6650f1594865f12aebe42a0d3dc22/guides/phoenix_mix_tasks.md), in this part:

>To fix this, we need to change the permissions on our "postgres" user in the psql console to allow database creation.

there needs to be an explanation for how to enter the psql console.

### Attempted Solution
I'm on Mac OS.

When I type in `psql` inside of the new phoenix "hello" repo, I get the following error:
```
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by javimolla** [comment]
The message says that it can't connect to the database because it does not seem to be started. Check that you have installed PostgreSQL correctly and have it running before trying to connect with the console

**Comment by trosel** [comment]
@javimolla Yes exactly. The suggested solution in the linked document is missing this step. 

This is an essential step to the getting started. If zero guidance is provided, new users will just quit like I did.

**Comment by trosel** [comment]
If someone needs to understand how to use Postgres before they can use Phoenix, that should be listed in a pre-requisites section as well.

**Comment by sushant12** [comment]
@trosel you can find tons of articles on the internet regarding it, so what's the point of adding it in the pre-requisites section? Phoenix can use database other than postgres too u know.

**Comment by trosel** [comment]
>so what's the point of adding it in the pre-requisites section?

Because it's a pre-requisite for the guide.

>Phoenix can use database other than postgres too u know.

I know. But the guide chose to require postgres. 

Look, as you can see in my original post here, the Phoenix docs *already include postgres troubleshooting information*. All I'm asking is that it be a little more comprehensive so beginners like me don't get lost in the cargo cult.

**Comment by delameko** [comment]
Hi @trosel , I can understand where you're coming from, it's frustrating trying to learn a new technology when you suddenly have to learn another new technology as well.

But it's worth bearing in mind that Postgres is quite a big subject in itself.  The troubleshooting in the doc you linked is directly related to errors when running `mix ecto.create`, so trying to run something that's part of Phoenix.  Getting Postgres installed and running correctly is really an entirely separate subject.  

It's also worth realising that Postgres may change in the future and the devs would then be responsible for keeping the documentation for Postgres up to date.

You didn't say whether you got Postgres running.  As you're on a Mac I would highly recommend the [Postgress.app](https://postgresapp.com), and then follow the instructions on the[ CLI docs](https://postgresapp.com/documentation/cli-tools.html) to get psql on the command line. (Uninstall your current Postgres first to avoid conflicts).

**Comment by trosel** [comment]
@delameko I appreciate your perspective on that. And thank you for the recommendations.

Perhaps this already exists, but it might be worth a one sentence call-out like "You should know how to set up a postgres database before you start this guide".

**Comment by kelvinst** [comment]
> Perhaps this already exists, but it might be worth a one sentence call-out like "You should know how to set up a postgres database before you start this guide".

I agree, maybe a link to a good (and official) postgres install and troubleshoot guide would help too.

**Comment by josevalim** [comment]
I think the main issue is what @delameko mentioned, there are just too many ways to run PG and unfortunately we can't cover them all reliable. So a PR with a link to Postgres for more instructions would be welcome. Thanks!
