### ISSUE TITLE
reloadable_apps config is not detecting umbrella project

### ISSUE THREAD

**Issue by 1player** [phoenixframework/phoenix#3569]
The `reloadable_apps` configuration option to the Endpoint is by default nil, which should, as the documentation states, "reload current project if it consists of single app, or all applications within umbrella project".

### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.9
* Operating system: macOS

### Expected behavior

A Phoenix application running inside an umbrella project should have all its siblings reloaded on change.

### Actual behavior

Changes to the sibling projects do not trigger the reloader unless explicitly listed on the `reloadable_apps` config key.

The code reloader calls `Mix.Project.umbrella?` https://github.com/phoenixframework/phoenix/blob/029098e38ca830c35e832b44e58a0cd641fe24f1/lib/phoenix/code_reloader/server.ex#L105-L111 to tell if we're running in an umbrella project, but that function returns true only for the topmost mix project which only describes the umbrella. Any project inside the umbrella will have that function return false, and will never reload sibling projects unless listed manually.

**Comment by chrismccord** [comment]
can you confirm if you run `mix phx.server` form the umbrella root that reloads happen as you want? Is it only when running `mix phx.server` inside the child that you are not seeing sibling reloads?

**Comment by 1player** [comment]
Yeah confirmed that running `mix phx.server` from the root works as intended. I didn't even know this was possible, I usually cd into the inner phoenix app and run phx.server from there.

**Comment by josevalim** [comment]
Yes, we can only know we are in an umbrella if you run from the umbrella. Otherwise we only have a view into the current project, which is not an umbrella, and therefore we can't reload. There is not a trivial fix for this, sorry.
