### ISSUE TITLE
Removing listener might make the next in line listener not being called

### ISSUE THREAD

**Issue by ostap0207** [phoenixframework/phoenix#3572]
* Phoenix JS version: 1.4.9

In the following example, the second listener will never be called when the "event" comes.

```javascript
var ref = channel.on("event", () => {
 channel.off("event", ref);
});

channel.on("event", () => {
 // never called
});
```

This is happening as the listeners being processed one by one in a `for` loop, which does not take to account a case when the listener is removed during the processing and before the triggering of the next listener.
https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L606

The code example above is quite often used in a different way with RxJS.

```javascript
Rx.Observable.fromEvent(channel, "event")
  .take(1)
  .subscrbe(() => {});
```

This will only take one event and remove the listener before other listeners have been triggered.

### Expected behavior
All listeners are called even if one of the listeners is removed during processing

### Actual behavior
The next in line listener will not be called if one of the listeners is removed during processing

**Comment by snewcomer** [comment]
@ostap0207 Interesting observation!  I think what you are advocating for is the bound array under process is not mutated?  Something like `Array.from` or `slice()` handle these needs?

Also, do you happen to have a use case for triggering all of the listeners, even if the array was further processed during one of the iterations?  I also see being able to stop listeners down the chain as beneficial (but have no specific reason why ;) ).  Lmk your thoughts!

**Comment by ostap0207** [comment]
> Something like Array.from or slice() on the bound array before processing handle these needs?

Yes. I had a look at socket.io and they use `slice()`

https://github.com/component/emitter/blob/6bd7817e8a444cb16e8abdf7dd2d7f04d5ca3dc8/index.js#L143

I think only those listeners that are available when the event comes should be called, and any modifications to the array should not affect that. Often the listeners could be in different parts of the application and I think their logic should be independent of other listeners for the same event.
Otherwise, listeners' logic might get coupled and depend on the order of invocation, which sounds prone to errors.

**Comment by snewcomer** [comment]
Great point on `socket.io` 💯 In principle, I agree with you (just having a hard time coming up with a logical situation).  The only thing that I am unsure of is in your example, you provided

```js
var ref = channel.on("event", () => {
 channel.off("event", ref);
});
```

It seems that the intention was to prevent further calls to some event.  

In any case, that seems like undesirable and potentially error prone behaviour, so a PR would be appreciated it you had time!

Emittery does this...
https://github.com/sindresorhus/emittery/blob/3334cff4daf83bfcf7054d35edc51957e3f70f8d/index.js#L220
