### ISSUE TITLE
Need ability to exclude XXX.Router.Helpers from documentation, any advise how to do it?

### ISSUE THREAD

**Issue by ArturTTN** [phoenixframework/phoenix#3579]
Need ability to exclude XXX.Router.Helpers from documentation, any advise how to do it?

_Originally posted by @ArturTTN in https://github.com/phoenixframework/phoenix/issues/2580#issuecomment-542730567_

**Comment by sushant12** [comment]
Why would you want to do it?

**Comment by josevalim** [comment]
It is currently not possible but if someone wants to submit a PR that allows an option on `use Phoenix.Router` that disables it, it would be welcome.

**Comment by chrismccord** [comment]
I don't consider the documentation problematic, but as José said, a PR is welcome. Thanks!
