### ISSUE TITLE
ErrorView documentation out-of-date

### ISSUE THREAD

**Issue by ddowl** [phoenixframework/phoenix#3580]
Hello!

I'm just starting to learn Phoenix by reading through the docs, and noticed that the [section on `ErrorView`s](https://hexdocs.pm/phoenix/views.html#the-errorview) seems a little out of date. For example, the default `ErrorView` looks like:

```
defmodule HelloWeb.ErrorView do
  use HelloWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end
```

for a new Phoenix project, but the documentation presents it as:

```
defmodule HelloWeb.ErrorView do
  use HelloWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end
end
```

The following exercise of adding a `404.html.eex` still works as expected though. I'm personally still a little confused how Views are able to intuit which `"<template_name>.html"` argument is matched on `render/3` in general, but that's a question for StackOverflow I think.

### Environment
(Don't think this matters for docs, but here it is!)
* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 10.16.3
* NPM version (npm -v): 6.9.0
* Operating system: Ubuntu 18.04.3

**Comment by kelvinst** [comment]
Will work on that if you don't mind.

> I'm personally still a little confused how Views are able to intuit which "<template_name>.html" argument is matched on render/3 in general, but that's a question for StackOverflow I think.

About your confusion, it is more related to the internal functionality of Phoenix, so I think the docs is not the place to explain that, so you are right about asking it somewhere else. One tip though, people will answer you much faster if you ask on https://elixirforum.com.

**Comment by josevalim** [comment]
@kelvinst please do send a PR!

**Comment by kelvinst** [comment]
@josevalim I was about to do that and realized it was actually already done: #3388

**Comment by josevalim** [comment]
Cool, thanks for the follow up!
