### ISSUE TITLE
`force_ssl` doesn't work in releases.exs 

### ISSUE THREAD

**Issue by jesseshieh** [phoenixframework/phoenix#3586]
We're trying to enforce ssl and following the [docs](https://hexdocs.pm/phoenix/endpoint.html#force-ssl), we added the `force_ssl` config, but we are also using elixir releases, so we (arbitrarily) put it in our releases.exs file instead of our prod.exs file and it is silently ignored.

I think this happens because `Plug.SSL` is injected by a macro seen [here](https://github.com/phoenixframework/phoenix/blob/029098e38ca830c35e832b44e58a0cd641fe24f1/lib/phoenix/endpoint.ex#L453). Since releases.exs is for runtime configs, the `force_ssl` configuration isn't present during build time when the macros are evaluated and `Plug.SSL` is never injected.

I'm not sure if "fixing" this is the right way to go or if we should just update the documentation to mention that the config must not be in a runtime config such as releases.exs. 

I'm happy to help make the change if you let me know how you'd like to proceed. Thanks again for a great library!

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.4.10

**Comment by josevalim** [comment]
We could add a special case for `force_ssl`, given its importance. The idea is that when we compile, we will store the value of `force_ssl` in the compile module and then when we start the app, we will check if the value matches, if it doesn't, we should log and fail to start.

**Comment by jesseshieh** [comment]
@josevalim gotcha, were you imagining something like [this](https://github.com/phoenixframework/phoenix/compare/master...jesseshieh:js/force_ssl)? If so, I'll finish it up and send a pull request over.

**Comment by josevalim** [comment]
@jesseshieh yes, exactly!

But here is what I would do to clean it up a bit. Store `force_ssl` in a function called `__compile_config__`:

```elixir
@compile_config Keyword.take(config, Phoenix.Endpoint.Supervisor.compile_config_keys)

def __compile_config__ do
  @compile_config
end
```

And then you do the check you added inside Phoenix.Endpoint.Supervisor.start_link. 

The idea of creating the small abstraction above is in case we want to check other compile time config in the future. :)

A PR would be very welcome!
