### ISSUE TITLE
Plug.Static needed for `--no-html --no-webpack`?

### ISSUE THREAD

**Issue by glenwinters** [phoenixframework/phoenix#3588]
I generated a new phoenix project with the below options to only create an API.
```
mix phx.new fancy_drinks --no-html --no-webpack
```

### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 10.16.1
* NPM version (npm -v): 6.9.0
* Operating system: macOS Mojave 10.14.8

### Expected behavior

I don't think `Plug.Static` needs to be in `Endpoint` since I'm only serving an API and no static assets.

### Actual behavior

`Plug.Static` was inserted into `Endpoint`.

```
  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phx.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/",
    from: :fancy_drinks,
    gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)
```

**Comment by chrismccord** [comment]
We can't say one way or the other if a pure API doesn't also need to serve static assets. Users that want to forgo assets can remove the plug :)
