### ISSUE TITLE
Improvements to rendering/layouts

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#359]
I am in the process of documenting how rendering and layouts work. I have detected some issues:
- [x] `render` and `redirect` should halt
- [x] Rendering in the controller and in the view have different APIs
- [x] The layout can be passed as `:within` in the view but not in the controller. unify the APIs and use `:layout` instead of `:within`.
- [x] `put_layout` allows you to change only the template, not the layout module. i would vouch for consistency (pass the same as arguments as within)
- [x] We should ensure assigns are maps throughout Phoenix and that layouts are popped from assigns
- [x] We should add `put_view` to contrast to `put_layout`
- [x] `plug :put_layout_formats, ~w(html)`
- [x] `plug :accepts, ~w(html)`

Thoughts?

**Comment by dcy** [comment]
@josevalim Does eex support template inheritance now? I don't find any document about it.

**Comment by OvermindDL1** [comment]
> @josevalim Does eex support template inheritance now? I don't find any document about it.

Don't think inheritence, think composition.  Templates can call templates.

**Comment by WernerBuchert** [comment]
I would be nice, if eex does support template inheritance, otherwise don't see how you can provide the possibility to develop your own theme, e.g. in the area of ecommerce, as an example shopware:

https://developers.shopware.com/designers-guide/getting-started/#template-inheritance

Or are there better ways with eex to change individual areas of the page and still remain updateable?

At the moment I don't see any promising projects in the area of ecommerce with Elixir or the Phoenixframework.  There are some, but they are all more or less retired. which is actually a pity, because Elixir/Phoenix would actually fit there very well, at least I think so.

**Comment by OvermindDL1** [comment]
> Or are there better ways with eex to change individual areas of the page and still remain updateable?

Template inheritance is still the OOP style of thinking, you want to think the functional style, which is what the BEAM uses.  You can have any part of a page individually be updateable via any condition you want, it's not at all hard, just remember that each template quite literally "is" a function call that returns a string (populated by other functions).  You can pass in functions, call dispatching functions, whatever you want.

Also, an old issue would not get much notice by most people, you really *really* should ask this on the [official forums](https://elixirforum.com/).  ^.^

**Comment by WernerBuchert** [comment]
Thanks for the answer. Maybe it's the old OOP school, i'am not sure, but there is the erlang erlydtl library, which has "extends" and "block", used in Zotonic and i've seen it in some template libraries for Clojure (but i've never used Clojure...). At the moment i can't really imagine how this is going to work without extend and blocks, but i will deal with it in the next weeks. If possible, this should also be extendable for Template Designer, without much programming knowledge.
I've written some question on the official forum, but this was really the first answer, thanks.
https://elixirforum.com/t/resources-for-building-an-e-commerce-store-in-phoenix/1813/63
https://elixirforum.com/t/resources-for-building-an-e-commerce-store-in-phoenix/1813/27
https://elixirforum.com/t/resources-for-building-an-e-commerce-store-in-phoenix/1813/32

**Comment by OvermindDL1** [comment]
It's actually quite easier than that, everything in EEX (not a phoenix thing, it's a generic template engine in Elixir) is just functions, including being able to pass functions into functions.  :-)
