### ISSUE TITLE
use phoenix to connect with hbase

### ISSUE THREAD

**Issue by katty0924** [phoenixframework/phoenix#3608]
hi, when i use  phoenix to connect with hbase, the table i can see is the SYSTEM level, such as CATALOG,FUNCTION, but i can not see the tables which i defined earlier, there are other things which i  should do? such as mapping, or triggering?

**Comment by josevalim** [comment]
Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

PS: btw, you probably have the wrong Phoenix project. :)

**Comment by haljpg** [comment]
> surgical anatomy of Biliary tract
