### ISSUE TITLE
Invalid option: --no-webpack

### ISSUE THREAD

**Issue by GildedHonour** [phoenixframework/phoenix#3615]
` mix phx.new my_app --no-webpack --verbose`

===>

`** (Mix) Invalid option: --no-webpack`

https://hexdocs.pm/phoenix/Mix.Tasks.Phx.New.html#module-options

**Comment by wojtekmach** [comment]
Could you fill in the issue template and include your Phoenix version? You can grab it with `mix phx.new --version`

**Comment by tusqasi** [comment]
I have this same issue

Installed elixir with asdf

Phoenix installer v1.6.6
```
elixir -v
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

**Comment by cw789** [comment]
@tusqasi Have a look at the available options → https://hexdocs.pm/phoenix/Mix.Tasks.Phx.New.html
Phoenix > v1.6 does not use webpack. So you probably want `--no-assets`.

**Comment by tusqasi** [comment]
Ahhhh...
Got it.

**Comment by ORESoftware** [comment]
fun! lol
