### ISSUE TITLE
"Unhandled poll status" in long poll

### ISSUE THREAD

**Issue by jakgajtk** [phoenixframework/phoenix#3621]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): 12.8.0
* NPM version (npm -v): 6.13.0
* Operating system: macOS

### Expected behavior

403 response on long polling is handled without throwing errors in frontend, since Phoenix backend sends this status in case of problems with authorization. 

### Actual behavior

Frontend phoenix library does not handle 403 status for long poll connection, while phoenix backend actually sends it in some cases.

Important lines: 
```
switch(status){
        case 200:
          messages.forEach(msg => this.onmessage({data: msg}))
          this.poll()
          break
        case 204:
          this.poll()
          break
        case 410:
          this.readyState = SOCKET_STATES.open
          this.onopen()
          this.poll()
          break
        case 0:
        case 500:
          this.onerror()
          this.closeAndRetry()
          break
        default: throw new Error(`unhandled poll status ${status}`)
      }
```
Path - assets/js/phoenix.js

How I imagine it:

```
switch(status){
        case 200:
          messages.forEach(msg => this.onmessage({data: msg}))
          this.poll()
          break
        case 204:
          this.poll()
          break
        case 410:
          this.readyState = SOCKET_STATES.open
          this.onopen()
          this.poll()
          break
        case 403:
          this.onerror()
          this.close()
          break
        case 0:
        case 500:
          this.onerror()
          this.closeAndRetry()
          break
        default: throw new Error(`unhandled poll status ${status}`)
      }
```
I have forked version already prepared. I can open PR if someone from maintainers agrees with me on the way of doing it.

**Comment by chrismccord** [comment]
Please send a PR. Thanks!

**Comment by jakgajtk** [comment]
@chrismccord PR prepared - https://github.com/phoenixframework/phoenix/pull/3657

**Comment by jakgajtk** [comment]
PR was merged.
