### ISSUE TITLE
Websocket connection for Live Reload fails in Firefox

### ISSUE THREAD

**Issue by alappe** [phoenixframework/phoenix#3631]
### Environment

* Elixir version (elixir -v): 1.9.4
* Phoenix version (mix deps): 1.4.11
* NodeJS version (node -v): 12.13.1
* NPM version (npm -v): 6.12.1
* Operating system: macOS
* Firefox version: 71.0 (deactivated all extensions)

### Expected behavior

```
mix new --no-ecto ws_issue
cd ws_issue
mix phx.server
```

Then open http://localhost:4000/, make a change, see live reloader working.

### Actual behavior

```
mix new --no-ecto ws_issue
cd ws_issue
mix phx.server
```

Then open http://localhost:4000/

See `Firefox can’t establish a connection to the server at ws://localhost:4000/phoenix/live_reload/socket/websocket?vsn=2.0.0.` in Console of the browser.

**Comment by alappe** [comment]
Nevermind… restarting firefox fixed the issue. Sorry for the noise…

**Comment by lpender** [comment]
Saw this in chrome too -- was helpful to know to restart the browser, thanks

**Comment by formido** [comment]
I'm seeing this too

**Comment by lpender** [comment]
In my case I believe I hadn't renamed all instances of MyApp or my_app

**Comment by formido** [comment]
Well, I'll see if that's a clue for me
