### ISSUE TITLE
Cowboy Link in Overview Page is still navigating to incorrect URL

### ISSUE THREAD

**Issue by Permagate** [phoenixframework/phoenix#3638]
The link to cowboy doc in https://hexdocs.pm/phoenix/overview.html appears to be pointing to a non-existing link `https://ninenines.eu/docs/en/cowboy/1.0/guide/`. However, when I cross-check with the documentation in this repository, #3418 should have updated it to a new link `https://ninenines.eu/docs/en/cowboy/2.6/guide/` which worked for me. Perhaps the change hasn't been deployed yet?

### Expected behavior

When I click the link to cowboy doc in https://hexdocs.pm/phoenix/overview.html, I should navigate to https://ninenines.eu/docs/en/cowboy/2.6/guide.

### Actual behavior

When I click the link to cowboy doc in https://hexdocs.pm/phoenix/overview.html, I navigated to https://ninenines.eu/docs/en/cowboy/1.0/guide instead.

**Comment by Gazler** [comment]
Fixed, that commit wasn't backmerged into v1.4 which the docs are deployed from. Thanks for raising the issue!
