### ISSUE TITLE
How create a project just only with api?

### ISSUE THREAD

**Issue by wahello** [phoenixframework/phoenix#3639]
### As splitting backend and frontend, the question is raised, "How create a project just only with api?", without html in the project created by `mix phx.new`. 

I'am an elixir/Phoenix novice. Maybe, some veteran can remove the web app perfectly.

**Comment by rmoorman** [comment]
I guess that you are looking for `mix phx.new --no-html --no-webpack <projectname>`. To see all options available for the `phx.new` task you can use `mix help phx.new`.

**Comment by rogerleite** [comment]
Hi @wahello. You can use Elixir Forum https://elixirforum.com/ to ask/search for help too, there is a lot of content there.

**Comment by wahello** [comment]
Got it.
