### ISSUE TITLE
Feature suggestion: Improved test helper for building a conn for unit test's

### ISSUE THREAD

**Issue by JonRowe** [phoenixframework/phoenix#3640]
As per the docs you currently need to chain several calls together to build a conn for unit testing controller helpers or plugs, e.g.:

```
conn = build_conn() |> bypass_through(AppWeb.Router, [:pipeline]) |> get("/")
```

For me this was not named particularly well, why am I running a conn through a bypass to get a pipeline run? And why do I have to call get?

What I would like, (and if you're ok with it I'm happy to produce a pr)

```
build_conn_for_pipeline(AppWeb.Router, [:pipeline])
```

I feel this name would be much clearer in the docs as to what it does, and could even be built out of the existing components, and would prevent people face palming like I did!

**Comment by chrismccord** [comment]
Please post feature discussion on the forums as we reserve the issue tracker for issues and active development. In general, the composition approach is the way to go, and you can always write a re-usable function yourself :) Thanks!

**Comment by JonRowe** [comment]
In a way this is an issue as well, because the docs surrounding this are hard to find and things are badly named.
