### ISSUE TITLE
Unused import css from "../css/app.css" in blank phoenix app

### ISSUE THREAD

**Issue by thojanssens** [phoenixframework/phoenix#3641]
Phoenix generates the file `assets/js/app.js`, and within this file there is the following line:
`import css from "../css/app.css"`

My IDE (IntellJ) says:
> Unused import css from "../css/app.css"

Can't we just have `import "../css/app.css"` or what's the purpose of the variable `css`?

Furthermore, if I write `console.log(css)`, it seems that the object is empty, even though we definitely have CSS.

**Comment by draffauf** [comment]
My guess is that while the import value isn't referenced by default, it's set up out of the box to be ready to use local scope for CSS modules:

https://medium.com/garbage-collection/css-modules-local-scope-for-css-a7cd12edfa60

**Comment by snewcomer** [comment]
Great suggestion!  In fact, their docs show it this way.  I imagine we could do this and obtain one small benefit - this type of import doesn't effect the scope of the module (we are only importing it for it's side effects)

https://webpack.js.org/plugins/mini-css-extract-plugin/

@thojanssens I would suggest a PR if you have some time!
