### ISSUE TITLE
install elixir

### ISSUE THREAD

**Issue by klangner** [phoenixframework/phoenix#3651]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

**Comment by Jcambass** [comment]
@klangner Are you looking for help on how to install elixir? If so you can find this information here https://elixir-lang.org/install.html.

Please note that this is the issue track for Phoenix, an elixir web framework and not a support forum or issue tracker for the language itself.

**Comment by klangner** [comment]
I'm sorry I don't know how this issue was created?
I haven't done it myself, at least not manually.
I was trying to install Phoenix and had some trouble, but how it ended up in this ticket ?I have no idea.

**Comment by Jcambass** [comment]
@klangner No worries, If you need some help installing Phoenix you might wanna ask for help inside the Phoenix category on the [elixir forum](https://elixirforum.com/c/phoenix-forum) or on the [elixir slack](https://elixir-slackin.herokuapp.com/).
