### ISSUE TITLE
Missing capability of loading runtime config for Phoenix.Endpoint.socket

### ISSUE THREAD

**Issue by bruteforcecat** [phoenixframework/phoenix#3659]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.12
* NodeJS version (node -v): 11.13.0
* NPM version (npm -v): 6.13.6
* Operating system: macOS Catalina

### Expected behavior
Currently there is no way to set config for [Phoenix.Endpoint.socket/3](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3) in runtime. And this lead to a problem of not able to let socket fetching session if config for Plug.Session is set in runtime like using [Plug.builder_opts](https://github.com/elixir-plug/plug/blob/v1.8.3/lib/plug/builder.ex#L228).

My particular example is I set Plug.Session config runtime by loading up `signing_key` and `encryption_key` from env var. However because of above issue, it looks there is no way to let `Phoenix.Endpoint` and `Phoenix.Socket.Transport` to fetch session with correct session config for Liveview socket(https://github.com/phoenixframework/phoenix_live_view/blob/master/guides) /introduction/installation.md) as config are assumed to be set only in compile time.

### Actual behavior
User should be able to set `Phoenix.Endpoint.socket/3` config in runtime, like Plug.
I wonder if it makes sense to allow passing function with arity 0 to session like the following

```
  socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: load_session/0]],
      longpoll: [connect_info: [session: load_session/0]]
```

I would like to hear what do you guys think. I am also willing to help on this one if you think this is something we should support

**Comment by josevalim** [comment]
It is probably better to use a MFA:

    websocket: [connect_info: [session: {Mod, :fun, []}]]

But yes, a PR would be appreciated. Please ping me once you submit it!

**Comment by josevalim** [comment]
Closing in favor of PR. Thanks!
