### ISSUE TITLE
Channel doesn't know when connection is disconnected and receive errors for all pushes after socket reconnects

### ISSUE THREAD

**Issue by myobie** [phoenixframework/phoenix#3669]
This concerns the `socket.js` client and not the server. I am using the `.js` file directly in the browser and my callsite js is written inside a `<script type="module">` and what you see below is what I am doing without any bundling or cross-compilation.

### Environment

* Operating system: macOS 10.15.3
* Browser: Safari

### Setup

```js
import { Socket } from './socket.js'

const socket = new Socket('/socket')
socket.connect()

const channel = socket.channel('topic')
channel.onError((data) => console.error('channel error', data))
channel.onClose((data) => console.error('channel close', data))
channel.join()

async function sleep(amount) {
  return new Promise((resolve, _reject) => {
    setTimeout(() => { resolve() }, amount)
  })
}
```

### Expected behavior

```js
(async () => {
  socket.disconnect()
  await sleep(1000)

  // Expect the channel to be in the same errored state it would be in if the remote side closed the connection
  assert(channel.state === "errored")

  // Pushing now will buffer and eventually timeout
  let push1 = channel.push("echo")
  await sleep(11000)
  assert(push1.receivedResp.status === 'timeout')

  // reconnect
  socket.connect()
  await sleep(1000)

  // pushing now will work, as the channel has rejoined
  let push2 = channel.push("echo")
  await sleep(1000)
  assert(push2.receivedResp.status === 'ok')
})()
```

### Actual behavior

```js
(async () => {
  socket.disconnect()
  await sleep(1000)

  // The channel stays joined, even tho if the remote had closed the socket it would end up in an errored state
  assert(channel.state === "joined")

  // Pushing now will buffer and eventually timeout, which is correct because the socket could reconnect
  let push1 = channel.push("echo")
  await sleep(11000)
  assert(push1.receivedResp.status === 'timeout')

  // reconnect
  socket.connect()
  await sleep(1000)

  // pushing now will fail as the remote channel is no longer a process and so there is no topic for this socket to match to
  let push2 = channel.push("echo")
  sleep(1000)
  assert(push2.receivedResp.status === 'error')
  assert(push2.receivedResp.response.reason === 'unmatched topic')
})()
```

**Comment by chrismccord** [comment]
I don't see a `channel.join(...)` in the above code. Can you clarify?

**Comment by myobie** [comment]
@chrismccord sorry, that was a bad copy/pasta on my part, I'll add it right now.

**Comment by chrismccord** [comment]
One thing to keep in mind is you shouldn't push any messages from the server until `channel.join().receive("ok", /* code path that pushes */)`

So I am not sure your test scenario is valid because the program should not be arbitrarily pushing. Can you move the pushing code inside the join receive change and still produce the issue?

**Comment by myobie** [comment]
@chrismccord there is a test that says one can push before the join reply: https://github.com/phoenixframework/phoenix/blob/master/assets/test/channel_test.js#L892 – I took this to mean it was alright.

I removed the `channel.join()` from the above and then executed this and got the same results:

```js
channel.join().receive('ok', (_data) => {
  (async () => {
    console.debug('starting disconnect')
    socket.disconnect()
    await sleep(1000)

    let push1 = lobby.push('echo_join_params')
    await sleep(11000)
    console.debug(push1)

    socket.connect()
    await sleep(1000)

    let push2 = lobby.push('echo_join_params')
    await sleep(11000)
    console.debug(push2)
  })()
})
```

**Comment by indrekj** [comment]
I think its the same thing as in https://github.com/phoenixframework/phoenix/pull/3665

**Comment by snewcomer** [comment]
@myobie Mind trying out #3708?  In this  case, you can't rely on async/await and would have to use nested callbacks (to support IE11...for now) in your examples above.  Thanks!

**Comment by myobie** [comment]
@snewcomer yes, using <https://github.com/phoenixframework/phoenix/blob/4eedf321450dbb6e38b115992779abbf53ea8f6e/assets/js/phoenix.js> I can see that the socket receives a `CloseEvent`, the channel's status is `errored`, and then when I manually reconnect the channel is rejoined and I can successfully push messages onto it. 

Is #3708 def going to land into master in the future? If so, then I'd consider this closed.

**Comment by snewcomer** [comment]
@myobie Great!  Yes it will be merged at some point this week once Chris takes a look.  Once merged, it will auto close this!

**Comment by myobie** [comment]
Awesome, and no rush. Thanks for all the hard work and for linking me to the PR. 🎉
