### ISSUE TITLE
files not found with phoenix run under a release

### ISSUE THREAD

**Issue by blset** [phoenixframework/phoenix#3677]
Hello,

it's not clear what is the app dir with releases

I have files generated by the phoenix web app  that can be downloaded. 
They are stored in a directory called downs of the app dir. if I change release I expect these files to stay where they are and be found by all releases

I have added 
 ` plug Plug.Static, at: "/downs", from: Path.expand('./downs'), gzip: false
`
I then generate urls with /downs/xxx

1- if I run the app with mix phx.server from the app dir it works ok
2- if I run the app with _build/rel/prod/v1/bin/v1 start  from the app dir (after having build the release) it works ok

the problem is : 

3- if I upload the release previoulsy built (on another machine) to another directory test1 with the downs dir copied into test1 (but not in priv/static) , and from test1 I run v1/bin/v1 start, the app works ok but the files in downs are not found   

I uploaded in test1 only the content of v1, not the full tree _build/prod/rel/v1

the url is correctly generated but looks like the plug static line is ignored in case 3
 
thanks for any advice

**Comment by chrismccord** [comment]
Please send support requests to the forums or slack as we reserve the issue tracker for issues. Thanks!
