### ISSUE TITLE
Unwanted whitespace trimming in EEx templates

### ISSUE THREAD

**Issue by sn3p** [phoenixframework/phoenix#3681]
This is a known issue (#3482) but it was closed some time ago.
We are experiencing similar issues which are blocking us from updating to Elixir v1.9.0 and up.

According to the [Elixir v1.9.0 release notes](https://elixirforum.com/t/elixir-v1-9-0-released/23366):

> 2. Bug fixes
  [EEx] Consistently trim newlines when you have a single EEx expression per line on multiple lines

What bug does this actually fix?

**Edit:** https://github.com/elixir-lang/elixir/issues/8792 fixed via https://github.com/phoenixframework/phoenix/commit/04295d8eb19ff7c65bd9f2b8f836040bd925c897

> For now I would recommend to either go with double spaces or an explicit `&nbsp;`.

I would expect everything outside EEx expressions to output exactly the way I write it, only replacing the expressions itself. Writing `&nbsp;` or additional newlines feels like a hack rather than a fix. Extra load and error prone because this is not how you would write HTML.

Does this make sense or am I missing a bigger picture here? Please help me understand 😆

> If this continues to be an issue, we can make trim optional.

That would be awesome!! Would be happy to give this a go 😄

### Example

```eex
<%= "Hello" %> <%= "World" %>
```
"Hello World" (expected)

```eex
<%= "Hello" %>
<%= "World" %>
```

"HelloWorld" (unexpected)

```eex
<%= "Hello" %>

<%= "World" %>
```
"Hello World" (expected)

**Comment by josevalim** [comment]
The second example is an EEx bug. The trimming should only trim space after newlines, leaving at least one new line. It will be fixed on Elixir master and v1.10.

**Comment by josevalim** [comment]
Fixed in Elixir master. It was bigger than I thought, so I won't backport it to v1.10. If you want to make it configurable in Phoenix, a PR is also welcome. Thank you!

**Comment by josevalim** [comment]
I have added the option to master and v1.4 too.

**Comment by sn3p** [comment]
> I have added the option to master and v1.4 too.

Awesome thank you so much 🎉
Wanted to give this a go tomorrow but you're too fast ⚡️

**Comment by sn3p** [comment]
I was thinking, in Ruby ERB you can enable trim mode per line by adding a `-` when closing the expression:

```erb
<% # avoids line break after expression -%>
```

Would this be possible and a helpful addition in EEx?

**Comment by bernardo-martinez** [comment]
> I have added the option to master and v1.4 too.

I have added it to my project as:
```
config :phoenix,
  trim_on_html_eex_engine: true
```

 but i don't see any change. In fact looking at phoenix's code i don't see where this config is actually being read. Am i missing something here? 
 
 thanks!
