### ISSUE TITLE
Renaming the wildcard pattern in router

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#3689]
Based on [a topic on the forums](https://elixirforum.com/t/where-to-find-details-about-phoenix-router-glob-like-matching/29520) and few other people asking on the slack channel I'm wondering if it's possible to rename the `glob-like` pattern of `/path/*page` to something like `wildcard` or `catch-all`. Usually a glob does allow for quite a few more features than just trailing wildcard and people seem to expect it to do more than it can. I'm not sure if the current term is widely used though especially in the phoenix book. If so it might make it more difficult to change.

**Comment by chrismccord** [comment]
The name can be anything you want, ie `/path/*wildcard` as it allows you to controlled the named param that appears in `conn.params`, so I think the current behavior is desirable. Thanks!
