### ISSUE TITLE
Unexpected behaviour when subscribing to the same topic on two different moments

### ISSUE THREAD

**Issue by macabeus** [phoenixframework/phoenix#3704]
### Environment

* Elixir version:
```
Erlang/OTP 21 [erts-10.3.5.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.1 (compiled with Erlang/OTP 21)
```

* Phoenix version: `== 1.4.14`
* NodeJS version: `v11.10.1`
* NPM version: `6.7.0`
* Operating system: macOS Catalina 10.15.3

### Expected behavior
When creating two channels with the same topic, just the last one is keep.

### Actual behavior
Should keep both channels.

### Use case
I'm developing a React application. So I have one global `Socket` and each component could create and subscribe for a new channel using this socket.
Sometimes I have two different components that want to subscribe to the same topic, but using different events. So it's happen:

```ts
// when the *first* component is being rending...
const channel = socket.channel('my-nice-topic', { client: 'browser' })
console.log(socket.channels) // [Channel]
channel.on('event-foo', funcFoo)

// when the *second* component is being rending...
const channel = socket.channel('my-nice-topic', { client: 'browser' })
console.log(socket.channels) // [Channel, Channel]
channel.on('event-bar', funcBar)
```

So looks like that everything is fine, rigtht? But not!

The `funcFoo` never is called, even when the `event-foo` happens.
We could check adding a log on `trigger` function:
```ts
console.log('trigger: this.bindings', this.bindings)
```
There is no `event-foo` here.

A workaround that I wrote is, before to create a new channel, check if already there is a channel with the same topic and, if yes, add the event bind on it:

```ts
let i = 0
for (i = 0; i < socket.channels.length; i++) {
  const current = socket.channels[i]
  if (current.topic === topic) {
    current.on(event, func)
    console.log('Added bind to channel', socket)
    return
  }
}

console.log('There is no channel with given topic', socket)

const channel = e.channel(topic, { client: 'browser' })
channel.on(event, func)
```

But I think that this behaviour should be the default on phoenix. This is an unexpected behaviour and it's hard to debug on a large codebase.

I could fix this bug on `phoenix.js`, but before I would like to know if it's that I said makes sense.

**Comment by chrismccord** [comment]
This is an application-level concern. You need to have some intermediate code that ensure's two components share the same channel. Thanks!

**Comment by rmoorman** [comment]
@chrismccord , looking at the examples @macabeus gave, it seems that there are actually two channel objects added to the socket's channel list though which seems a bit odd/inconsistent with the external socket api.

If the correct behaviour of the socket api should be that consecutive calls to `channel/2` with the same topic would lead to only the last invocation be actually leading (triggering the event callbacks), shouldn't the most recently created channel object be the only one in the socket's channel list?

And wouldn't it be better to let the api consumer know that something wrong happened then? (much like we do [in the `join/1` function of the channel](https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L428)

**Comment by macabeus** [comment]
@rmoorman I like the approach to add a warning, but I think that is still better to automatically bind on the new handle on the previous channel.

Another way is adding a flag:
```js
socket.channel('my-nice-topic', { client: 'browser' }, { warningMultipleChannelWithSameTopic: true })
```

(with a better name, of course...)
