### ISSUE TITLE
Add a mix command to scaffold all of the routes and views you need for authentication

### ISSUE THREAD

**Issue by yawmanford** [phoenixframework/phoenix#3711]
Can you please add a mix command to scaffold all of the routes and views you need for authentication. The manual implementation is an overkill for me.

1. The command should be used on fresh applications and will install a layout view, password reset, registration and login views, as well as routes for all authentication end-points.
2. A HomeController should also be generated to handle post-login requests to your application's dashboard.

**Comment by chrismccord** [comment]
Please send feature discussions to the forums or phoenix core mailing list. You may also search hex for packages that provide this kind of functionality. Thanks!
