### ISSUE TITLE
force_ssl release (runtime) config not working on / (but working on websocket routes)

### ISSUE THREAD

**Issue by lguminski** [phoenixframework/phoenix#3714]
### Environment

* Elixir version (elixir -v): `Elixir 1.10.1 (compiled with Erlang/OTP 22)`
* Phoenix version (mix deps): `1.4.16`
* Operating system: MacOS

### Expected behavior
`force_ssl` is described as [runtime configuration](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#module-runtime-configuration), so it is expected that if the following configuration is defined in `config/releases.exs` (NOT in `config/prod.exs`!) it would be applied to all routes. 
```elixir

import Config

config :hello_world, HelloWorldWeb.Endpoint,
  server: true,
  url: [host: "localhost", port: 4001],
  http: [port: 4000],
  https: [
    port: 4001,
    cipher_suite: :strong,
    certfile: "priv/cert/selfsigned.pem",
    keyfile: "priv/cert/selfsigned_key.pem"
  ],
  force_ssl: [hsts: true, host: "localhost:4001", log: :debug, exclude: []]
```

### Actual behavior
If the above configuration is added to a project generated with `mix  phx.new`,  the redirection works perfectly fine on `/socket/websocket` route (both `ws://` and `http://` protocols)

       $ curl -s -D- http://localhost:4000/socket/websocket

        HTTP/1.1 301 Moved Permanently
        location: https://localhost:4001/socket/websocket

but not on `/`

        $ curl -s -D- http://localhost:4000

        HTTP/1.1 200 OK

I suspect that the issue could result from the fact that Endpoint's `plugs` are resolved at compile time, when `:force_ssl` is not available yet. This looks similar to the issue in [this thread](https://elixirforum.com/t/proper-way-to-enforce-https-only/2117), however, its participants eventually decided to terminate SSL on proxy. And I would rather prefer Phoenix to deal with it.

[Here](https://github.com/lguminski/phoenix_force_ssl_runtime_issue_demo) you will find a minimal Elixir project, which demonstrates the problem.

**Comment by lguminski** [comment]
(the demonstration project had a modification that could be confusing. It crept in from my local filesystem. Please pull latest changes. But it doesn't change a thing. The issue is still valid)

**Comment by josevalim** [comment]
Yes, apologies. The docs have been fixed in master. It is a *compile* time config.

**Comment by lguminski** [comment]
@josevalim thank you for making it clear.

My plan was to distribute my app as a Docker image, in such a way that when the location of a certificate file is given via environment variables, the app initializes secure transport, and if no environment is set, just http.

Is there a plan to make `force_ssl` a runtime configuration, which would allow such a use case? Or I rather need to use a heavier setup with a proxy, and delegate tls termination over there?

**Comment by josevalim** [comment]
In this case, it is best to change force_ssl to allow its configuration to be given as a MFArgs, similar to what we do for the session.

**Comment by josevalim** [comment]
A PR on Plug would be appreciated.

**Comment by lguminski** [comment]
Thank you for the tips. I will dig into the code and see what I can do within the time I have.
