### ISSUE TITLE
"Disabling" contexts initially

### ISSUE THREAD

**Issue by veeral-patel** [phoenixframework/phoenix#3729]
Hi! I come from Rails. I like following the services/models/controllers design from Rails, and would like to do that in Phoenix if I can without writing non-idiomatic code.

Later, when I learn what the contexts should be, I'd like to be able to separate my code appropriately into contexts.

Here's a few posts I found on the topic:

- https://elixirforum.com/t/thoughts-on-single-context-phoenix-apps/10169
- https://dev.to/novistore/phoenix-without-contexts-4d33

How should I go about doing this? Thanks!

CC @chrismccord

**Comment by chrismccord** [comment]
Please send questions to slack and the forums, and feature requests to the mailing list as we reserve the issue tracker for issues. Thanks!

**Comment by veeral-patel** [comment]
@chrismccord Got it, thanks Chris!
