### ISSUE TITLE
Custom file structure

### ISSUE THREAD

**Issue by veeral-patel** [phoenixframework/phoenix#3730]
Hi - I'm wondering whether it's possible (and easy) for me to create a Phoenix application without using `mix phx.new`.

As I mentioned in #3729, I'd like to have my own file structure, which has folders for services/models/controllers/etc, which goes against Phoenix's idea of contexts.

I'd like to be able to use Phoenix's migrations support, changesets in models, etc, ideally by just using Phoenix as just another Elixir library and not something that provides a file structure as well.

In Rails, this is difficult to do due to autoloading...is this the case in Phoenix as well?

**Comment by cdvv7788** [comment]
I doubt it. Contexts are just modules. You should be able to organize your project using different structures.

**Comment by veeral-patel** [comment]
@cdvv7788 My concern is if I use a custom file structure, will I be able to use Phoenix's and Ecto's CLI commands?

https://devhints.io/phoenix-migrations

**Comment by cdvv7788** [comment]
The migrations have little to do with the context. You can generate a migration with `phx.gen.migration` for example, and it will only generate a file with a timestamp in the migrations folder which you will need to edit.
I am no expert in phoenix, but I doubt that having a custom structure breaks these commands (as long as it compiles)
