### ISSUE TITLE
Unable to map Existing Hive tables columns to Phoenix View

### ISSUE THREAD

**Issue by RameshChowdeshetty** [phoenixframework/phoenix#3738]
Hi Team,

We have a data with column names contains special characters like Degree (°), equals( =). We have pushed the data to Hbase and Hbase is converted the character into some encoding format like \xEF\xBF\xBD. When we tried to create a view in Phoenix with this columns , it is not importing data, However the view can able to retrieve remaining columns data.

Can you please some one let me know how can we  map column names in phoenix view  which contains the special characters like °, ( , = , and ) in Hbase keys.

**Comment by chrismccord** [comment]
looks like you are looking for a database library when you mention "Phoenix Views"? This is Phoenix, the web framework. Thanks!
