### ISSUE TITLE
[deploying with release] Ecto migrations' rollback not work as expected.

### ISSUE THREAD

**Issue by c4710n** [phoenixframework/phoenix#3744]
### Environment

* Elixir version (elixir -v): `1.10.2`
* Phoenix version (mix deps): `1.4.16`
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system: NixOS

### Brief
I want to run Ecto's migration and rollback operations when using release, so I follow the instruction of [Ecto migrations and custom commands ](https://hexdocs.pm/phoenix/releases.html#ecto-migrations-and-custom-commands) in Phoenix Docs.

Migration is ok:
```
$ `_build/prod/rel/hello/bin/hello eval 'Hello.Release.migrate()'`  # succeed
```
But, rollback still throw errors:
```
$ _build/prod/rel/hello/bin/hello eval 'Hello.Release.rollback(Hello.Repo, 20200405040500)'
12:14:03.919 [error] GenServer #PID<0.209.0> terminating
** (RuntimeError) connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir 1.10.2) lib/keyword.ex:399: Keyword.fetch!/2
    (postgrex 0.15.3) lib/postgrex/protocol.ex:92: Postgrex.Protocol.connect/1
    (db_connection 2.2.1) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
```

### Details
In order to reproduce the issue, I created a demo at https://github.com/c4710n/phx_demo_hello with following steps:
1. init project with `mix phx.new hello`.
2. setup runtime configuration:
   1. rename `config/prod.secret.exs` to `config/releases.exs`.
   2. replace `use Mix.Config` with `import Config`.
   3. remove call of `import_config "prod.secret.exs"`.
3. setup Ecto custom commands for release:
   1. add new module `Hello.Release` from [here](https://hexdocs.pm/phoenix/releases.html#ecto-migrations-and-custom-commands).
4. get deps with `mix deps.get`.
5. create a example migration with `mix ecto.gen.migration create_users`.
6. create release with `MIX_ENV=prod mix release`.
7. create a database:
   - database host: `localhost`
   - database port: `5432`
   - database name: `hello`
   - username: `postgres`
   - password: `postgres`
8. load environment variables `DATABASE_URL` `SECRET_KEY_BASE` with running `source .envrc` in shell.
9. run migrations related commands:
   - `_build/prod/rel/hello/bin/hello eval 'Hello.Release.migrate()'` - SUCCEED
   - `_build/prod/rel/hello/bin/hello eval 'Hello.Release.rollback(Hello.Repo, 20200405040500)'` - FAILED with following errors.

```text
12:14:03.919 [error] GenServer #PID<0.209.0> terminating
** (RuntimeError) connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir 1.10.2) lib/keyword.ex:399: Keyword.fetch!/2
    (postgrex 0.15.3) lib/postgrex/protocol.ex:92: Postgrex.Protocol.connect/1
    (db_connection 2.2.1) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
```

I try to inspect the error, so I set `:show_sensitive_data_on_connection_error` option for `Hello.Repo` like the error messages said:

```elixir
config :hello, Hello.Repo,
  show_sensitive_data_on_connection_error: true
```

Then, I rebuilt the release and run again, but the error message is same as above. It looks like the option has no effects.

I have no idea what to do next. ;(

**Comment by c4710n** [comment]
Ah, I found solution: https://elixirforum.com/t/phoenix-deploying-with-releases-guides-misprint/24390/3
 This is because the application environments is not loaded when rollback is performed. Fix it with:
```sh
defmodule MyApp.Release do
  @app :my_app

  def migrate do
    for repo <- repos() do
      {:ok, _, _} = Ecto.Migrator.with_repo(repo, &Ecto.Migrator.run(&1, :up, all: true))
    end
  end

  def rollback(repo, version) do
    Application.load(@app) # ADDED
    {:ok, _, _} = Ecto.Migrator.with_repo(repo, &Ecto.Migrator.run(&1, :down, to: version))
  end

  defp repos do
    Application.load(@app)
    Application.fetch_env!(@app, :ecto_repos)
  end
end
```

Should this be mentioned in the doc?

**Comment by josevalim** [comment]
It has been fixed in the docs, thank you!
