### ISSUE TITLE
slow performance and high error rate with API

### ISSUE THREAD

**Issue by NidalShater** [phoenixframework/phoenix#3747]
I’m using Phoenix to build an API that takes an HTTP request (JSON) and modify some fields in it (after connecting to MongoDB), send it to another server, receive the response, modify some fields in the response and send it back to the client. I implemented the same application with NodeJS as well

I run both on Ubuntu server (and both in production mode, using PORT=4000 MIX_ENV=prod mix phx.server for phoenix).

The internet speed is low: 200 Kbps (but for both implementations)

I run tests using Apache Jmeter for both of them
Threads: 500
Ramp-up: 1
loops: 10
and get the following results

NodeJS:
14.1/S --- 39.44% error rate
Phoenix:
15.4/S --- 44.56% error rate

what really surprised me is that phoenix is as fast as NodeJS and the error rate of phoenix is higher

I tried many solutions using this [Guide](https://www.theerlangelist.com/article/phoenix_latency)
but nothing works

what should I do?

**Comment by petermm** [comment]
Hi Nidal 

Let's handle this one in the elixirforum thread..

https://elixirforum.com/t/phoenix-slow-performance-and-high-error-rate-with-api-using-mongodb/30378/4
