### ISSUE TITLE
Compilation error on apps generated with --no-html

### ISSUE THREAD

**Issue by aaronrenner** [phoenixframework/phoenix#3751]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): master@9d7444f8
* NodeJS version (node -v): 10.19.0
* NPM version (npm -v): 6.13.4
* Operating system: Ubuntu 19.10

### Expected behavior

After running `mix phx.new app_with_no_html --no-html`, I should be able to run `mix test` and all of the tests should pass.

### Actual behavior

When I run `mix test` after generating a new project with `--no-html`, I get the following error.

```
$ mix test
Compiling 1 file (.ex)

== Compilation error in file lib/app_with_no_html_web/endpoint.ex ==
** (UndefinedFunctionError) function Phoenix.LiveDashboard.RequestLogger.init/1 is undefined (module Phoenix.LiveDashboard.RequestLogger is not available)
    Phoenix.LiveDashboard.RequestLogger.init([param_key: "request_logger", cookie_key: "request_logger"])
    (plug 1.10.0) lib/plug/builder.ex:304: Plug.Builder.init_module_plug/4
    (plug 1.10.0) lib/plug/builder.ex:288: anonymous fn/5 in Plug.Builder.compile/3
    (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug 1.10.0) lib/plug/builder.ex:286: Plug.Builder.compile/3
    (plug 1.10.0) expanding macro: Plug.Builder.__before_compile__/1
    lib/app_with_no_html_web/endpoint.ex:1: AppWithNoHtmlWeb.Endpoint (module)
```

The problem appears to be that the live dashboard code is being injected into `endpoint.ex` when its not injected elsewhere. If I comment out the following lines, in `endpoint.ex` I can get the tests to pass.

```elixir
  socket "/live", Phoenix.LiveView.Socket, websocket: [connect_info: [session: @session_options]]
```
and

```elixir
  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
```

**Comment by chrismccord** [comment]
Looks like we are only injecting the dashboard dep if the `html` binding is set, so we need to changeup the logic here: 
https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_single/mix.exs#L43-L45

Can you send a PR? We also need to check/change the logic in the installer/templates/phx_umbrella/.../mix.exs. Thanks!

**Comment by aaronrenner** [comment]
Thanks so much for pointing me to the right place. Now that I think about it, should LiveDashboard still be installed if the project is generated with `--no-html`? I am thinking yes... A user may generate a project with `--no-html` because they are building a json api, but they may still want LiveDashboard installed. 🤔 What do you think?

**Comment by josevalim** [comment]
Closing in favor of #3755.
