### ISSUE TITLE
Link in repo points to http site 

### ISSUE THREAD

**Issue by lucasverra** [phoenixframework/phoenix#3766]
Link in repo points to http site

**Comment by optikfluffel** [comment]
Since phoenixframework.org is hosted on Github Pages (at least I think it is), maybe this would be an option:

> People with admin permissions for a repository can enforce HTTPS for a GitHub Pages site.

via [help.github.com](https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https)
