### ISSUE TITLE
Default generated --live app's submit button gets stuck on "Searching..." with a package search that yields no results

### ISSUE THREAD

**Issue by nickjj** [phoenixframework/phoenix#3772]
### Environment

* Elixir version (elixir -v): `Elixir 1.10.2 (compiled with Erlang/OTP 22)`
* Phoenix version (mix deps): `phoenix 1.5.0-rc.0`
* Phoenix LiveView version (mix deps): `phoenix_live_view 0.12.0`
* NodeJS version (node -v): `v12.14.0`
* NPM version (npm -v): `6.13.4 (Yarn 1.21.1)`
* Operating system: `Debian Buster`
* Browsers you attempted to reproduce this bug on (the more the merrier): `Chrome stable`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: `Yes`

### Expected behavior

This happens with a brand new Phoenix app generated using `--live`.

Submitting an invalid package name such as "d" would:

1. Disable the submit button
2. Display an error flash message saying it's not found
3. Keep the input field's value with the original search query
4. Enable the submit button (since it's done searching)

### Actual behavior

The above workflow works the first time you do it, but if you submit the form a second time without changing the input field, the submit button gets stuck on "Searching..." and the only way to reset it is to adjust the search term.

After the button gets disabled nothing is sent to the server, so there's no additional logs after clicking the submit button a second time, and there's also no errors in the dev tools console in the browser.

**Here is an animated gif showing the problem:**

![LV issue](https://i.imgur.com/ko6tOlJ.gif)

When you see my mouse cursor get a yellow glow, that is a mouse click happening.

I'm not sure if this is a LiveView or an issue with the default generated app by Phoenix. I didn't change any of the code except I have it running in Docker.

**Relevant bits of the source code included in the generated app:**

```elixir
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end
```

```leex
  <form phx-change="suggest" phx-submit="search">
    <input type="text" name="q" value="<%= @query %>" placeholder="Live dependency search" list="results" autocomplete="off"/>
    <datalist id="results">
      <%= for {app, _vsn} <- @results do %>
        <option value="<%= app %>"><%= app %></option>
      <% end %>
    </datalist>
    <button type="submit" phx-disable-with="Searching...">Go to Hexdocs</button>
  </form>
```

**Comment by chrismccord** [comment]
This was fixed on LV master. Thanks!
