### ISSUE TITLE
mix phx.gen.live 

### ISSUE THREAD

**Issue by thanos** [phoenixframework/phoenix#3774]
### Environment

* Elixir version (elixir -v): Elixir 1.10.2 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.5.0-rc.0 (../..) (mix)
* NodeJS version (node -v): v11.6.0
* NPM version (npm -v): 6.14.3
* Operating system: OSX (Catalina)

### Expected behavior

So to try out the dashboard  I followed the instructions and build the  test `dev_app` in installer. All went well. Then I decided to try using `mix phx.gen.live` generator but found it  has  issues.

 I'm going to use the  following  example to illustrate the probelm:

```
mix phx.gen.live  MarketData Tick ticks trade_id:string 

* creating lib/dev_app_web/live/tick_live/show.ex
* creating lib/dev_app_web/live/tick_live/index.ex
* creating lib/dev_app_web/live/tick_live/form_component.ex
* creating lib/dev_app_web/live/tick_live/form_component.html.leex
* creating lib/dev_app_web/live/tick_live/index.html.leex
* creating lib/dev_app_web/live/tick_live/show.html.leex
* creating test/dev_app_web/live/tick_live_test.exs
* creating lib/dev_app_web/live/modal_component.ex
* creating lib/dev_app_web/live/live_helpers.ex
* creating lib/dev_app/market_data/tick.ex
* creating priv/repo/migrations/20200419174205_create_ticks.exs
* creating lib/dev_app/market_data.ex
* injecting lib/dev_app/market_data.ex
* creating test/dev_app/market_data_test.exs
* injecting test/dev_app/market_data_test.exs
* injecting lib/dev_app_web.ex

Add your DevAppWeb.LiveHelpers import to your view_helpers block in lib/dev_app_web.ex:

    defp view_helpers do
      quote do
        # Use all HTML functionality (forms, tags, etc)
        use Phoenix.HTML

        # Import convenience functions for LiveView rendering
        import Phoenix.LiveView.Helpers
        import DevAppWeb.LiveHelpers
        ...
      end
    end


Add the live routes to your browser scope in lib/dev_app_web/router.ex:

    live "/ticks", TickLive.Index, :index
    live "/ticks/new", TickLive.Index, :new
    live "/ticks/:id/edit", TickLive.Index, :edit

    live "/ticks/:id", TickLive.Show, :show
    live "/ticks/:id/show/edit", TickLive.Show, :edit


Remember to update your repository by running migrations:

    $ mix ecto.migrate
```

### The Problem

The following generated files have issues:
```
lib/dev_app_web/live/tick_live/show.ex
lib/dev_app_web/live/tick_live/index.ex
lib/dev_app_web/live/tick_live/form_component.ex
lib/dev_app_web/live/modal_component.ex
```

`show_live.ex` and `index_live.ex` declare: 
```
use <%= inspect context.web_module %>, :live_view
```
while `form_component.ex` and `modal_component.ex` declare:
```
use <%= inspect context.web_module %>, :live_component
```
but both  `live_view` and  `live_component` are not defined  in the project's `lib/dev_app_web.ex`.

### My Quick  Solution

My quick fix was to add to `lib/dev_app_web.ex`:
```
 def live_view do
    quote do
      use Phoenix.LiveView
      import Phoenix.LiveView.Helpers

      unquote(view_helpers())
    end
  end

  def live_component do
    quote do
      use Phoenix.LiveComponent
      import Phoenix.LiveView.Helpers
      import Phoenix.HTML
      import Phoenix.HTML.Form
      import DevAppWeb.ErrorHelpers

      # Include shared imports and aliases for views
      unquote(view_helpers())
    end
```
Now I'm not sure if this is the correct solution but either way  the generated instructions in https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phx.gen.live.ex
should be fixed.

I'm willing to do a pull request if you guys give me the right direction and if it saves you any work.

Many thanks 
  Thanos

**Comment by wojtekmach** [comment]
@thanos it looks like you haven't generated your project with: `mix phx.new --live` so you'd need to do that or manually add it using https://hexdocs.pm/phoenix_live_view/installation.html.

**Comment by peck** [comment]
> @thanos it looks like you haven't generated your project with: `mix phx.new --live` so you'd need to do that or manually add it using https://hexdocs.pm/phoenix_live_view/installation.html.

hi @wojtekmach, I'm getting the same errors as @thanos did above. Looking at the installation instructions linked I'm not seeing anywhere where `live_component/0` is defined. Am I missing something?

**Comment by wojtekmach** [comment]
when you generated your project with `mix phx.new --live`, you'll get a `myapp_web.ex` that defines `live_component/0`.

**Comment by peck** [comment]
ah, but is there a path to get there previously created projects that are upgrading? Im coming from 1.4.x

**Comment by wojtekmach** [comment]
there's a an upgrade guide here: https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f but it doesn't cover `--live`, I think you'll have to manually compare.

**Comment by peck** [comment]
@wojtekmach got it. Thats what I was missing there. Thanks so much, I'll work on getting that integrated!
