### ISSUE TITLE
Bad link in docs

### ISSUE THREAD

**Issue by michalmuskala** [phoenixframework/phoenix#3785]
### Expected behavior

The link to "overview guides" on the [main Phoenix docs page](https://hexdocs.pm/phoenix/Phoenix.html#content) should be correct.

### Actual behavior

The link 404s to https://hexdocs.pm/overview.html

<img width="405" alt="Phoenix — Phoenix v1 5 0 2020-04-22 23-37-59" src="https://user-images.githubusercontent.com/477062/80040635-6e8e6800-84f2-11ea-9024-e9a77ab9688d.png">

**Comment by josevalim** [comment]
Thabnks ,fixed on master!
