### ISSUE TITLE
Generate a separate module for fixtures on phx.gen.* scaffolds

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#3797]
Today, Phoenix generators include a fixture function into every context and controller/live test file. The issue with this approach is that we often need to share resources between tests, so we end-up forced to move them elsewhere.

My proposal is to generate those fixtures at `test/supoprt/fixtures/CONTEXT_fixtures.ex`. So for example, `mix phx.gen.html Accounts User users` will generate a `MyApp.AccountsFixtures` module which is imported into the tests instead. This is what what is used by `mix phx.gen.auth`.

**Comment by aaronrenner** [comment]
I like this idea, and would be happy to work on it if you like!

**Comment by josevalim** [comment]
:+1: from me. :)

**Comment by Gazler** [comment]
I think this makes sense, it means it is possible to reach into the fixtures from other integration tests easily, for example if you add a GraphQL endpoint to the application.

Do we anticipate the same API as https://github.com/aaronrenner/phx_gen_auth/blob/master/priv/templates/phx.gen.auth/context_fixtures.ex?

Something like `user_fixture`?

When doing something like this on my own projects, I make the import explicit, so it is easy to see at a glance which fixtures the tests use.

For example:

`import AccountFixtures, only: [user_fixture: 1, registration_token_fixture: 1]`

**Comment by josevalim** [comment]
> Something like user_fixture?

Yes.

The `import` vs `alias` is a good distinction. Given tests are always compiled though, we don't get compile time improvements from to `alias`, so this is purely a readability discussion. I prefer `import`s (with or without `:only`).

**Comment by mcrumm** [comment]
:+1: from me!

**Comment by aaronrenner** [comment]
@josevalim I just put together a PR with the proposed generator output changes for `phx.gen.live` https://github.com/aaronrenner/phoenix_generator_proposals_live/pull/1. Please let me know if you think this is heading in the right direction or where it can be improved.

**Comment by josevalim** [comment]
Closing in favor of PR.
