### ISSUE TITLE
Enabling GZip in production

### ISSUE THREAD

**Issue by jamonholmgren** [phoenixframework/phoenix#3803]
### Environment

* Elixir version (elixir -v): 1.7.3
* Phoenix version (mix deps): 1.4.10
* NodeJS version (node -v): v13.5.0
* NPM version (npm -v): 6.13.4
* Operating system: macOS

### Issue

I'm having trouble finding documentation for enabling gzip compression for my Phoenix endpoint.

I've found this "TIL": https://til.hashrocket.com/posts/63dvv2huk4-enable-gzip-for-all-phoenix-responses

But I'm not seeing any official documentation anywhere (including Elixir Plug) for how to do this.

Can someone point me in the right direction? Is that TIL correct? Shouldn't this be documented somewhere?

Thanks!

**Comment by faried** [comment]
> But I'm not seeing any official documentation anywhere (including Elixir Plug) for how to do this.

I searched for it, and it's from [Plug.Cowboy](https://hexdocs.pm/plug_cowboy/Plug.Cowboy.html).  The options are mentioned [here](https://hexdocs.pm/phoenix/Phoenix.Endpoint.Cowboy2Adapter.html#content), though not specifically `:compress`.

**Comment by jamonholmgren** [comment]
@faried That's very helpful! Thank you.

It would be nice to have an example of how this configuration might look. It might even be a good idea to include it in the default project boilerplate, to be honest -- gzip compression seems like something most people would want enabled.

**Comment by josevalim** [comment]
It should be`http: [compress: true]`. The docs in Phoenix.Endpoint also link to Plug.Cowboy. :)
