### ISSUE TITLE
`log: false` not respected in Router matchers

### ISSUE THREAD

**Issue by imranismail** [phoenixframework/phoenix#3806]
I have this route which I want to exclude it from being logged

```
get "/healthz", Proxy.Health, :check, log: false
```

I followed the option documented in Phoenix.Router and Phoenix.Logger, but it doesn't seem to help in removing

### Environment

* Elixir version (elixir -v): 1.10
* Phoenix version (mix deps): 1.5.1
* Operating system: Ubuntu

### Expected behavior
Certain routes will have logs removed with `log: false` option

### Actual behavior
Routes with `log: false` option still outputs to the log stream

**Comment by faried** [comment]
What `log: false` does is turn off the `[:phoenix, :router_dispatch, :start]` event log; see around line 240 in `lib/phoenix/logger.ex`.  That's the message that looks like
```
[debug] Processing with BlahWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
```

To turn the other one off seems more involved.  [This](https://stackoverflow.com/a/57587646) is what I found, but I imagine (hope?) there's a better way.

**Comment by josevalim** [comment]
Each log message has its own place of being enabled/disabled, please see here: https://hexdocs.pm/phoenix/Phoenix.Logger.html

**Comment by faried** [comment]
I'm not the original poster, but I was unable to figure out how to disable the `[:phoenix, :endpoint]` start/stop events from my controller.  Can you please provide a short example?

These are the log messages in question:
```
[info] GET /
[info] Sent 200 in 188µs
```

Putting `plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: false` in my controller, as suggested by the docs, appears to be the wrong way to do it.

**Comment by josevalim** [comment]
That should work.  what is your Phoenix version?
-- 


*José Valimhttps://dashbit.co/ <https://dashbit.co/>*

**Comment by faried** [comment]
This is with elixir 1.10.3, phoenix 1.5.1.  Here are the steps:
```
mix phx.new --no-ecto blah
cd blah
mix phx.server
```
Going to http://localhost:4000/ generates the expected log messages:
```
[info] GET /
[debug] Processing with BlahWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 22ms
```
Changing the PageController line in `lib/blah_web/router.ex` to `get "/", PageController, :index, log: false` gets rid of the *Processing* line:
```
[info] GET /
[info] Sent 200 in 195µs
```
Adding `plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: false` to `lib/blah_web/controllers/page_controller.ex` doesn't change the log output.

I did notice that adding `plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]` to the controller *doubles* the logging output, which implies that the line in the controller code with `log: false` is just disabling itself, not the code in phoenix that outputs the log lines:
```
[info] GET /
[info] GET /
[info] Sent 200 in 11ms
[info] Sent 200 in 20ms
```

**Comment by josevalim** [comment]
Thanks! Is your plug version also recent?
-- 


*José Valimhttps://dashbit.co/ <https://dashbit.co/>*

**Comment by faried** [comment]
Yes, it's 1.10.0 (from `deps/plug/mix.exs`.

**Comment by josevalim** [comment]
I cannot reproduce it. You can see that we do skip it correctly here: https://github.com/phoenixframework/phoenix/blob/v1.5.1/lib/phoenix/logger.ex#L191

Note that you have to set `log: false` on your Plug.Telemetry in your *endpoint*. If you add it to the controller, then it indeed gets duplicated. :)

**Comment by masterkain** [comment]
I have the same problem, vanilla application, all libs updated

endpoint.ex

`plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: false`

router.ex

```
  scope "/health_check", log: false do
    forward "/", HealthCheck
  end
```

logs:

```
│ 12:39:07.262 request_id=FpELd0AkjtEgHG8AAAAi [info] GET /health_check
│ 12:39:07.262 request_id=FpELd0AkjtEgHG8AAAAi [info] Sent 200 in 137µs
```

any way to make it stop? thanks
