### ISSUE TITLE
Documentation has problems about way to start Long-polling by Phoenix Channels JavaScript client

### ISSUE THREAD

**Issue by toyoaki-k** [phoenixframework/phoenix#3811]
Hello!

### Problem
I tried to use long polling by js client, and read the [documentation](https://hexdocs.pm/phoenix/js/#socket).
I found 2 problems about docs.

1. In doc about [Socket](https://hexdocs.pm/phoenix/js/#socket) object, It says that if user want to use long polling user should give `opts.transport` as Socket constructor parameter, and type of transport is **string**. But it seems wrong to me because [in fact Socket constructor expects a **object** which is either WebSocket or LongPoll](https://github.com/phoenixframework/phoenix/blob/5421101f058dac8c802d22ea50e86e5b5cba9e82/assets/js/phoenix.js#L746) as below.
`this.transport            = opts.transport || global.WebSocket || LongPoll`

2. So in fact user needs to import LongPoll object and give it to Socket initialization as its constructor parameter, but there are no docs about LongPoll object. So user can not know way to use LongPoll object.

### Expected

1. type of opts.transport is Object(Websocket or LongPoll)
2. docs about LongPoll object

thank you for reading!

**Comment by snewcomer** [comment]
@toyoaki-k A few notes and improvements for LongPoll would be welcome!  

It is in fact an [Object](https://github.com/phoenixframework/phoenix/blob/5421101f058dac8c802d22ea50e86e5b5cba9e82/assets/js/phoenix.js#L1144) type.  Good point.  Also I think some docs for the LongPoll class would be welcome fo those that need to support certain protocols.  A few lines how to enable Long Poll with how to setup the Socket [with](https://github.com/phoenixframework/phoenix/blob/5421101f058dac8c802d22ea50e86e5b5cba9e82/assets/js/phoenix.js#L11) it would be super useful!

Let me know if you have other questions 👍

**Comment by toyoaki-nihi** [comment]
@snewcomer 
Thank you for your reply.
got it! Let me contribute!

**Comment by toyoaki-k** [comment]
@snewcomer
Thank you for your reply.
Got it! Let me contribute!

**Comment by J0** [comment]
Hey @toyoaki-k,

Just wanted to check if you're still working on this issue and/or if it has already been fixed. Would love to help finish up this issue if no one else is working on it. Let me know!

Joel

**Comment by toyoaki-k** [comment]
Hi @J0,
So sorry for my slow work!
I sent a [PR](https://github.com/phoenixframework/phoenix/pull/4262). Could you review it?

**Comment by J0** [comment]
Hey @toyoaki-k,

Sorry for the delay. Happy to review but do keep in mind I'm not a member of Phoenix so whatever Jose or Chris says goes. I'm happy to offer general feedback though!

**Comment by toyoaki-k** [comment]
@J0 
Oh, sorry I misunderstood. I got it!
If you give me general feedback, it is very helpful for me. Thanks!

**Comment by josevalim** [comment]
Closing in favor of the PR!
