### ISSUE TITLE
validate_required ignored

### ISSUE THREAD

**Issue by jagoanmamah** [phoenixframework/phoenix#3822]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.3 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): 1.5
* NodeJS version (node -v): 13.6.0
* NPM version (npm -v): 6.14.4
* Operating system: ubuntu

### Actual behavior
when i fill in all the inputs, all goes well, but when i only fill in the topics, validate_required is ignored.

![Screenshot 2020-05-03 16:31:44](https://user-images.githubusercontent.com/25195185/80910725-9c2da980-8d5b-11ea-90c4-c9f22c7f1e5b.png)

and i get this error

![Screenshot 2020-05-03 16:26:48](https://user-images.githubusercontent.com/25195185/80910643-29243300-8d5b-11ea-8ed5-cfa8ff0855ed.png)

**Comment by snewcomer** [comment]
@jagoanmamah 👋 We might need a bit more information if you don't mind.  We would need to understand the data structure.  You may have something like `<%= topics %>` in your template, which may not be a list containing binaries or integer.  If you are trying tp print the list in the template, try 

```
<%= for topic <- @topics do %>
  <%= topic.name %>
<% end %>
```

**Comment by chrismccord** [comment]
As Scott said, we need more information, complete code listings, and complete stack trace. This doesn't appear to be an error with Phoenix or Ecto, but we can't say more without seeing more :) Thanks!
