### ISSUE TITLE
Function call(conn, {:error, :not_found}) present in fallback_controller.ex generated by mix phx.gen.json is never called by default

### ISSUE THREAD

**Issue by theagilecoder** [phoenixframework/phoenix#3826]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.1
* NodeJS version (node -v): 12.16.2
* NPM version (npm -v): 6.14.4
* Operating system: Ubuntu 18.04 LTS

I used `mix phx.gen.json` to generate a resource. One of the files created is `fallback_controller.ex`. 
```
defmodule MyapiWeb.FallbackController do
  @moduledoc """
  Translates controller action results into valid `Plug.Conn` responses.

  See `Phoenix.Controller.action_fallback/1` for more details.
  """
  use MyapiWeb, :controller

  def call(conn, {:error, %Ecto.Changeset{} = changeset}) do
    conn
    |> put_status(:unprocessable_entity)
    |> put_view(MyapiWeb.ChangesetView)
    |> render("error.json", changeset: changeset)
  end

  def call(conn, {:error, :not_found}) do
    conn
    |> put_status(:not_found)
    |> put_view(MyapiWeb.ErrorView)
    |> render(:"404")
  end
end
```

The first function will be called when `{:error, %Ecto.Changeset{} = changeset}` is returned, say, when an invalid resource is attempted to be created or updated. But the second function will never be called, atleast in the default scenario, because no one returns `{:error, :not_found}`. So, the 2nd function should not be generated automatically by the generator or a comment has to be added.

More details in Elixir Forum [Post](https://elixirforum.com/t/function-in-fallbackcontroller-generated-by-phoenix-generator-is-never-called-what-is-it-for/31319) where Jose Valim has asked to submit this issue.

**Comment by chrismccord** [comment]
it was added as instruction for the user to show how multiple clauses allow them to handle various scenarios. I'd prefer to keep it, but I'll defer to @josevalim

**Comment by josevalim** [comment]
I think the general agreement is that we should keep it, but we should just document it a bit for a  guidance. WDYT @chrismccord?

**Comment by chrismccord** [comment]
ref #3835 Thanks @josevalim !
