### ISSUE TITLE
Allow using Brotli compressed assets

### ISSUE THREAD

**Issue by hauleth** [phoenixframework/phoenix#3836]
### Environment

* Elixir version (elixir -v): `1.10.3`
* Phoenix version (mix deps): any

### Expected behavior

When I create Brotli-compressed file (with extension `.br`) then `mix phx.digest` should also support it and use it in `cache_manifest.json` properly.

### Actual behavior

Brotli compressed files are treated as "regular" files.

**Comment by josevalim** [comment]
A PR is welcome.

**Comment by josevalim** [comment]
To clarify, I don't believe we should apply brotli compression automatically given it is not supported by default in the VM, but we should allow a workflow like this:

    $ npm deploy --prefix assets
    $ mix phx.digest.brotli       # <- this is a 3rd part task, not part of Phoenix
    $ mix phx.digest

If the workflow above does not work, then a PR is welcome. I will close this one for now as we don't plan to tackle it ourselves. Thanks!

**Comment by hauleth** [comment]
I agree that Phoenix shouldn't apply Brotli compression to the assets. To be completely honest - I do not think it should apply GZIP either, it all should be handled by assets bundler. The problem is that it do not respect the Brotli compressed assets. So assuming that we have:

```
foo.css
foo.css.gz
foo.css.bz
```

Already then running `mix phx.digest` will result with:

```
foo.css
foo.css.gz
foo.css.bz
foo-<hash 1>.css
foo-<hash 1>.css.gz
foo.css-<hash 2>.bz
```

So `.bz` is. not treated as "compressed `foo.css`". That was the point of this issue.

I would love to provide PR, but right now I am too busy with other things and this issue was created as a result of the Slack conversation, so I would like it to be open for the time of being until I or someone will pick it up with a PR.

**Comment by josevalim** [comment]
I see, this can hopefully be easily fixed, we just need to list all .br as a possible compression extension. I will reopen this for now but we may close it in the future if there is no interest in tackling this feature.

**Comment by jayjun** [comment]
A third-party Mix task can work if `mix phx.digest` ignores `.br` files (see pull request above) then ran in this order

```shell
$ npm deploy --prefix assets
$ mix phx.digest
$ mix phx.digest.brotli
```

because `foo.css` must be digested into `foo-<hash>.css` before compression.

---

But pre-compressed Brotli assets are harder. Assets bundlers cannot supply pre-compressed _digest_ assets because digest files are not available before `mix phx.digest`.

If we move digesting to the asset bundler, who generates `cache-manifest.json`?

**Comment by jayjun** [comment]
Another idea. We can pass custom compressors to `mix phx.digest`.

```elixir
config :phoenix,
  compressors: [Phoenix.Digester.Gzip, MyBrotliCompressor]
```

`MyBrotliCompressor` can implement this behaviour.

```elixir
defmodule Phoenix.Digester.Compressor do
  @callback compress(binary()) :: binary()
  @callback ext() :: String.t()
end
```

This way, we are not stuck with `:zlib`. We can use Zopfli or libdeflate for better gzip compression for example.

**Comment by josevalim** [comment]
@jayjun i like such direction too, in case you want to submit a PR. :)

**Comment by josevalim** [comment]
This particular issue i believe we can close tho in favor of PR #3840, but a customizable compression engine would totally work for me too. :)
