### ISSUE TITLE
Looking for feedback on article on multi-page app development

### ISSUE THREAD

**Issue by tipsy-boopenstein** [phoenixframework/phoenix#3837]
Wondering if this interests developers of multi-page frameworks:

https://medium.com/@the1mills/the-browser-innovation-that-could-make-multi-page-apps-great-again-d7268eb213d2

**Comment by chrismccord** [comment]
the forum would be a great place for feedback, but the issue tracker is reserved for active development. Thanks!

**Comment by tipsy-boopenstein** [comment]
link to forum?

**Comment by ZombieHarvester** [comment]
https://elixirforum.com/
