### ISSUE TITLE
Phoenix.Logger for socket_connected not respect `log: Logger.level | false`

### ISSUE THREAD

**Issue by vermaxik** [phoenixframework/phoenix#3841]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.4.17
* NodeJS version (node -v): v12.15.0
* NPM version (npm -v): 6.13.4
* Yarn version (yarn -v): 1.22.4
* Operating system: Alphine 

I make logs cleanup to centralised system and would like to change a level/disable some logs.
For this I need to change level to `:debug` some phoenix logs including sockets.

According the [documentation](https://hexdocs.pm/phoenix/Phoenix.Logger.html#content) I can easily do it with `socket "/foo", MySocket, websocket: [log: :debug]`. But it doesn't work even with `log: false`.

### Expected behavior
Sets the log level:
```
socket "/live", Phoenix.LiveView.Socket, 
   websocket: [connect_info: [session: @session_options], log: :debug]
```
Change log output to:
```
[debug] CONNECTED TO Phoenix.LiveView.Socket in 360µs
```

### Actual behavior
The socket log output still have `info` level:
```
[info] CONNECTED TO Phoenix.LiveView.Socket in 360µs
```

**Comment by chrismccord** [comment]
`:transport_log` is the option you are looking for :)
https://github.com/phoenixframework/phoenix/blob/4aa5bedfffbca3860a59d5c6768ec295fd3478ea/lib/phoenix/endpoint.ex#L731-L732

**Comment by vermaxik** [comment]
Hi Chris,

Thanks for quick answer,  but unfortunately, it's not what I'm looking for :) 

The `transport_log` option add additional log:
```
[debug] GET /live/websocket
```

But what I need, change the log level or disable at all socket connection logs for live_view:

```
[info] CONNECTED TO Phoenix.LiveView.Socket in 521µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "EBYPPm4UdVpmOQwhWmwWNDkyKz8jOS4icoDQ4d62QAxHlUNpSPSjthtc", "vsn" => "2.0.0"} 
```

And that I found here
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/logger.ex#L299

**Comment by chrismccord** [comment]
Ah I see. `log: false` on the websocket options indeed gives you what you want, but you need to be on v1.5

**Comment by vermaxik** [comment]
Ahh, sorry, my fault. Thanks again for the help! 👍
