### ISSUE TITLE
Public way to get the transport PID during/after socket connection

### ISSUE THREAD

**Issue by fxn** [phoenixframework/phoenix#3844]
The `connect/2,3` callback for sockets runs before the transport process is created. Reason is to not spawn a process until the callback accepts the connection.

Therefore, if you want to monitor the socket when the connection is established, there is no public contract to do so. I think it would be useful to have one.

By now I am using this hack (which is not a proposal, just for illustration purposes):

```elixir
defoverridable init: 1

@impl true
def init(state) do
  res = {:ok, {_, socket}} = super(state)
  monitor(self(), socket.assigns.user_id)
  res
end
```

Things done in the monitor:

```
Log that driver #{socket.assigns.driver_id} disconnected.
Decrease a gauge counting drivers connected to this node.
Register a metric with the total duration of the connection.
Etc. 
```

If you'd like to address this, with some guidance I'd be more than happy to volunteer a patch.

**Comment by fxn** [comment]
Note also that Phoenix logs connections, but does not log disconnections, and `:telemetry` does not measure duration. Is as if something was missing in the lifecycle of sockets to me.

**Comment by fxn** [comment]
Hey @josevalim! This is the issue.

So I see have a few options I think:

* We make `init/1` overridable in `Phoenix.Socket`, document the return value, and document that `self()` is the transport PID.
* We say that it is OK-ish to `defoverradible init: 1` in the application socket module, as done above, and document that `self()` is the transport PID.
* Define a new optional callback that the original `init/1` invokes if present passing the transport PID and `socket`.
* Maybe something else?

Do you like any?

**Comment by josevalim** [comment]
Another option is move the id(...) call to inside init, so we can use it instead of init.

**Comment by fxn** [comment]
However, `id/1` is a very specific function meant to return the socket ID. The name is not the one of a "generic entry point callback".

Would be a little strange for me to document that if you want to monitor the socket you can plug code into `id/1` just because `self()` happens to be the transport PID.

**Comment by fxn** [comment]
The solution I like the most is to keep `init/1` private-ish, and support an optional callback, which would be called by `__init__/1` if present.

Such callback would essentially be the `on_connect/2` function in [my post](https://medium.com/@fxn/monitoring-websocket-disconnections-in-phoenix-bbe24f54d996), perhaps with a different name (?), except it would receive the socket and we'd document `self()` there.

People could use that one to for use cases like the ones in my post, log the connection including the user ID, increment a gauge, monitor the process, ..., and keep `connect/2,3` focused on authenticating the connection only.

**Comment by fxn** [comment]
BTW, doing that in `init/1` would be idiomatic probably, but documenting `{:ok, {channels, socket}}` and the super call... don't know how good is that.

**Comment by chrismccord** [comment]
This is also tricky because other transports don't necessarily have a process sitting on top that owns all the channels (ie the long poll transport) so I don't know where it best makes sense to provide this.

**Comment by fxn** [comment]
Let's try to go one step back in case this is a X/Y situation.

Say you want to log disconnections and keep Prometheus metrics as in the example use cases of [my post](https://medium.com/@fxn/monitoring-websocket-disconnections-in-phoenix-bbe24f54d996). If your transport are WebSockets (as in the post), using a monitor works fine.

Would it be possible to have a interface that works for all transports?

**Comment by fxn** [comment]
Hey!

I know you guys like to have as few open issues as possible. This has been open for months without activity, so I'll close it.

Let me just say that keeping track of the number of users connected with the technique explained in this [blog post](https://medium.com/@fxn/monitoring-websocket-disconnections-in-phoenix-bbe24f54d996) has proved to be rock solid. And that is a metric that probably _any_ WebSocket-based Phoenix application wants to have.

The generic concept of transport may difficult generalizing this, but at the same time, if you are WebSocket-only (a common use case?), you can do better.
