### ISSUE TITLE
Endpoint url path does not apply to routes or static_path

### ISSUE THREAD

**Issue by PJUllrich** [phoenixframework/phoenix#3846]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.4.15
* NodeJS version (node -v): 13.8.0
* NPM version (npm -v): 6.13.6
* Operating system: macOS Catalina

### Setup and Problem
```elixir
# config/config.exs
config :app, Web.Endpoint, url: [host: "localhost", path: "/foo"]

# web/endpoint.ex
defmodule Web.Endpoint do
use Phoenix.Endpoint, otp_app: :app
...
plug Plug.Static,
    at: "/foo",
    from: :app,
    gzip: true,
    only: ~w(css fonts images js favicon.ico robots.txt)
end

# web/router.ex
scope "/" do
  pipe_through :browser

  get "/bar", IndexController, :index
end

# web/templates/layout/app.html.eex
<script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
```

I am trying to prefix all paths and urls generated by Phoenix with a subpath like "/foo". I need to use a proxy that sends requests to e.g. "https://domain.com/bar/..." to one Phoenix application and requests with "https://domain.com/foo/..." to another application. Since I don't want to add "/foo" in front of every route in `router.ex` and asset-paths in my `*.eex`-templates, I set the `path`-config in the `Web.Endpoint` and the `at`-config in `Plug.Static`. However, this configuration seems to not be applied consistently depending on whether a `conn` or the `Web.Endpoint` is used for generating urls and paths. 

It is unclear to me which effect the `path` config for the `Endpoint` should have, if not to generate routes and paths consistently with the given prefix. Locally, I'd expect to have routes like `http://localhost:4000/foo/...` to access my routes, but the `/foo`-prefix gets ignored when generating routes. Based on #3558 I assume that this is the intended behaviour, but which rules are applied when are unfortunately not clear to me. Could you please clarify this behaviour? When are the `path` and `at` settings respected and when ignored?

### Expected behavior
```elixir
# When running `mix phx.server` locally in :dev
[info] Running Web.Endpoint with cowboy 2.7.0 at 0.0.0.0:4010/foo (http)
[info] Access Web.Endpoint at http://localhost:4010/foo

> mix phx.routes Web.Router
index_path  GET  /foo/bar  Web.IndexController  :index

<script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
"http://localhost:4000/foo/js/app.js"
```

### Actual behavior
```elixir
# When running `mix phx.server` locally in :dev
[info] Running Web.Endpoint with cowboy 2.7.0 at 0.0.0.0:4010 (http)
[info] Access Web.Endpoint at http://localhost:4010

> mix phx.routes Web.Router
index_path  GET  /bar  Web.IndexController  :index

<script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
"http://localhost:4000/js/app.js"
```

However, the paths are created correctly, when created with the `Web.Endpoint`
```elixir
>  mix run -e "Web.Router.Helpers.index_path(Web.Endpoint, :index) |> IO.inspect()"
"/foo/bar"

> mix run -e 'Web.Router.Helpers.static_path(Web.Endpoint, "/js/app.js") |> IO.inspect()'
"/foo/js/app.js"
```

### Related
[Chris' Post in Elixir-Forum](https://elixirforum.com/t/conn-or-endpoint-in-path-helpers/934/2?u=pjullrich)

**Comment by delameko** [comment]
When I update the Endpoint config to add `path: "/foo` (but no change to Plug.Static), all my assets are served from `/foo`.  (This is on Phoenix 1.5.1)

The router is looking for a matching path, so you just need to change your scope:

    scope "/foo" do
      ...
    end

**Comment by josevalim** [comment]
When you have the connection, the connection is meant to have the prefix information in `conn.script_name`. You will only get this information correctly if you are effectively running behind a proxy, which is what you would do in production. You can reproduce this behaviour by putting nginx in the front.

In other words, the behaviour you see is correct. You just need to make sure the connection has the `conn.script_name` properly set, which is what you would see when running under the /bar path in production. :)
