### ISSUE TITLE
`mix phx.new.web` generates project with Argument Error: `** (ArgumentError) unknown registry: MyApp.PubSub`

### ISSUE THREAD

**Issue by bfcarpio** [phoenixframework/phoenix#3855]
### Environment

* Erlang / OTP: 22
* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.1
* NodeJS version (node -v): 14.2.0
* NPM version (npm -v): 6.14.4
* Operating system: Arch Linux updated as 2020-05-18T18:13:39Z

### Steps taken
1. `mix new umbra --umbrella`
2. `cd umbra/apps`
3. `mix phx.new.web dummy --no-ecto --live`
4. Install dependencies when prompted
5. Move to root of umbrella: `cd ../..`
6. `mix phx.server`

Notes:
+ Behaviour still occurs when running server from the app directory, `dummy`.
+ Behaviour not shown when using `mix phx.new` non-umbrella app
+ `--no-ecto` flag doesn't seem to effect this result, but I included it for accuracy and to reduce the logged errors.

### Expected behavior
Phoenix server starts up and has no errors. Only debug or info logs.

### Actual behavior

Note, app name is `Dummy`

```
13:58:06.888 [error] GenServer #PID<0.2522.0> terminating
** (ArgumentError) unknown registry: Dummy.PubSub
    (elixir 1.10.3) lib/registry.ex:1239: Registry.info!/1
    (elixir 1.10.3) lib/registry.ex:920: Registry.register/3
    (phoenix_pubsub 2.0.0) lib/phoenix/pubsub.ex:117: Phoenix.PubSub.subscribe/3
    (phoenix 1.5.1) lib/phoenix/channel/server.ex:401: Phoenix.Channel.Server.init_join/3
    (phoenix 1.5.1) lib/phoenix/channel/server.ex:375: Phoenix.Channel.Server.channel_join/4
    (phoenix 1.5.1) lib/phoenix/channel/server.ex:299: Phoenix.Channel.Server.handle_info/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
Last message: {:join, Phoenix.Channel.Server}
State: {%{}, {#PID<0.2519.0>, #Reference<0.2004086569.528744452.2624>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveReloader.Channel, channel_pid: nil, endpoint: Dummy.Endpoint, handler: Phoenix.LiveReloader.Socket, id: nil, join_ref: "3", joined: false, private: %{}, pubsub_server: Dummy.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "phoenix:live_reload", transport: :websocket, transport_pid: #PID<0.2519.0>}}
13:58:06.888 [error] an exception was raised:
    ** (ArgumentError) unknown registry: Dummy.PubSub
        (elixir 1.10.3) lib/registry.ex:1239: Registry.info!/1
        (elixir 1.10.3) lib/registry.ex:920: Registry.register/3
        (phoenix_pubsub 2.0.0) lib/phoenix/pubsub.ex:117: Phoenix.PubSub.subscribe/3
        (phoenix 1.5.1) lib/phoenix/channel/server.ex:401: Phoenix.Channel.Server.init_join/3
        (phoenix 1.5.1) lib/phoenix/channel/server.ex:375: Phoenix.Channel.Server.channel_join/4
        (phoenix 1.5.1) lib/phoenix/channel/server.ex:299: Phoenix.Channel.Server.handle_info/2
        (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
```

Errors repeat with sequentially higher `#PID` values however landing page still is responsive.

**Comment by Gazler** [comment]
This is expected, since it is not the responsibility of the web application to start the pubsub server. Typically this would be done elsewhere as you can see if you run:

 > mix phx.new dummy --no-ecto --live --umbrella

Perhaps the docs for the `phx.new.web` task could be updated to reflect this? We could also add a note to the `phx.new.web` output that mentions the expected pubsub name?

**Comment by bfcarpio** [comment]
I would very much appreciate a note in `hexdocs` or even the post-generation output. Even something like the note about what tool Phoenix will use for json would be nice.

Thank you!

**Comment by chrismccord** [comment]
We would be more than happy to accept a PR which makes this clearer. Thanks!

**Comment by bfcarpio** [comment]
I would love to, but I'm just learning Phoenix so I don't even know what the appropriate documentation would be. Frankly, I'd love to read the documentation!

**Comment by suzaku** [comment]
Met the same issue when following examples in the book Phoenix in Action. This is quite misleading for newcomers.

**Comment by fugacityengr** [comment]
I experienced the same problem as suzaku mentioned above,
I am adding the solution I did here so it can help someone googling this problem when also following the Phoenix in Action book examples

I was able to solve it by modifying the `auction_umbrella/apps/auction_web/lib/auction_web/application.ex` file to the following

```elixir
  @impl true
  def start(_type, _args) do
    children = [
      # Start the Telemetry supervisor
      AuctionWeb.Telemetry,

      # Start the PubSub system
      {Phoenix.PubSub, name: AuctionWeb.PubSub},

      # Start the Endpoint (http/https)
      AuctionWeb.Endpoint
      # Start a worker by calling: AuctionWeb.Worker.start_link(arg)
      # {AuctionWeb.Worker, arg}
    ]
```

Note that the order matters in the `children` array so PubSub should come before the `Endpoint` as I have gathered from this [StackOverflow post](https://stackoverflow.com/questions/70467066/unknown-registry-myapp-pubsub)
