### ISSUE TITLE
More Detail on LiveView#terminate

### ISSUE THREAD

**Issue by bmteller** [phoenixframework/phoenix#3857]
`LiveView` exposes a `terminate` function that is called when the web socket terminates (https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:terminate/2
). It would be useful to be able to differentiate the reason for the live view web socket closing for diagnostic purposes. Cowboy lets you differentiate between timeout, the remote side closing by sending the close frame, the socket closing and the local side closing. However, in `Phoenix.Endpoint.Cowboy2Handler` in phoenix these states are all mapped to `:closed`.

**Comment by chrismccord** [comment]
This could be useful for statistics, but it shouldn't be used to drive decisions in your user flow as outline. You must write your durable features in a way that allows LV recovery, regardless of disconnection semantics. So if a user hard refreshes, closes laptop, quits browser, etc and you want that state to be durable, you have to persist it somewhere and restore. LV does its best to help you get back to your previous state, notably by re-sending client input when a tab reconnects, but the disconnect callback itself is not a mechanism to drive recovery.

**Comment by bmteller** [comment]
This is why we want statistics. So we can know if it is worth spending the engineering effort to add recovery to our flows that can't currently be recovered.

**Comment by chrismccord** [comment]
> This is why we want statistics. So we can know if it is worth spending the engineering effort to add recovery to our flows that can't currently be recovered.

To be clear, statistics in this case don't change the described user flow. You need to ensure the page is recovered as expected regardless of users closing laptop, closing a tab, hard refresh, cold deploy, etc. My point is insight into backgrounded tabs will be just that, it won't inform how you implement your features.
