### ISSUE TITLE
[1.5.3][phoenix-dashboard] Js error and LV disconnect on fresh 1.5.3 install.

### ISSUE THREAD

**Issue by markevich** [phoenixframework/phoenix#3866]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.5.3
* NodeJS version (node -v): v11.11.0
* NPM version (npm -v): 6.9.0
* Operating system: MacOs

### Expected behavior
Dashboard works without disconnects and js errors

### Actual behavior

Everything works great except `Metrics` and `RequestLogger` tabs. 

It looks like whenever you clicked on one of those tabs live view session resets(take a look at the timer from dev console) and error `WebSocket connection to ws://localhost:4000/phoenix/live_reload/socket/websocket?vsn=2.0.0 failed: WebSocket is closed due to suspension` bubbles up.

Also loading of those tabs are much slower than others.

Screen recording: https://www.dropbox.com/s/wi6fw1xf6hrtdzi/Screen%20Recording%202020-05-24%20at%2018.12.09.mov?dl=0

### Steps to reproduce:
- `mix archive.install hex phx_new 1.5.3`
- `mix phx.new dashboard_test`
- change db credentials in `config/dev.exs`
- `mix ecto.create`
- `mix phx.server`

Thanks!

**Comment by chrismccord** [comment]
Thanks for the report! Please open this issue on the LiveDashboard side. Thanks!
