### ISSUE TITLE
render/1 in LiveView causes CompileError when ignoring or renaming assigns parameter

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [phoenixframework/phoenix#3871]
### Environment
Ubuntu 18.04.4 LTS
Erlang/OTP 23 [erts-11.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.3 (compiled with Erlang/OTP 21)
phoenix_pubsub 2.0.0
phoenix_html 2.14.2
phoenix 1.5.3
phoenix_live_view 0.13.1
phoenix_live_dashboard 0.2.5
phoenix_live_reload 1.2.2

### Expected behavior
Compile ok.
```elixir
defmodule MyAppWeb.Foobar do
  use MyAppWeb, :live_view
  def render(_), do: ~L"foobar"     # <-- not using variable
end
```

```elixir
defmodule MyAppWeb.Foobar do
  use MyAppWeb, :live_view
  def render(foobar), do: ~L"foobar"     # <-- other name
end
```
### Actual behavior
```
== Compilation error in file lib/my_app_web/live/foobar.ex ==
** (CompileError) lib/my_app_web/live/foobar.ex:3: expected "assigns" to expand to an existing variable or be part of a match
    (elixir 1.10.3) expanding macro: Kernel.var!/1
    lib/my_app_web/live/foobar.ex:3: MyAppWeb.Foobar.render/1
    (phoenix_live_view 0.13.1) expanding macro: Phoenix.LiveView.Helpers.sigil_L/2
    lib/my_app_web/live/foobar.ex:3: MyAppWeb.Foobar.render/1
    (elixir 1.10.3) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by chrismccord** [comment]
~L requires an `assign` binding, so this is expected. Thanks!

**Comment by i-n-g-m-a-r** [comment]
I am sure this is a pragmatic solution, though I wonder whether non-standard Elixir syntax will help newcomers understand Elixir and functional programming.
I have been using Elixir for some time now and stuff like this puzzles me.
When I am using "industry standard" software like Phoenix I am inclined to think that I am wrong when I see stuff that does not match my mental model or the contents of my Elixir books.
(which in my case will distract me from what I was planning to do, but that's another story)
(and yes rtfm)

**Comment by i-n-g-m-a-r** [comment]
I just noticed that string interpolation does not work inside ~L.

works fine:
```elixir
def render(assigns), do: ~L"<div><%= assigns.myself %></div>"
```
not working:
```elixir
def render(assigns), do: ~L"<div>#{assigns.myself}</div>"
```
And then it hit me, it's a sigil...
```elixir
def render(assigns), do: ~L(<div><%= assigns.myself %></div>)
```
And what do you know, works fine.

The render context and all of the quotes got me thinking that I was looking at a string while I was not.
That may sound a little stupid, but in my defense I don't work a lot with sigils and definitely not superpowered ones like ~L.
