### ISSUE TITLE
Cannot use live views with --live and basic gen.live generator

### ISSUE THREAD

**Issue by jcrevits** [phoenixframework/phoenix#3874]
Hi! 👋 

### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.3
* NodeJS version (node -v): 14.0.0
* NPM version (npm -v): 6.14.4
* Operating system: MacOs (latest)
 
### Expected behavior
This happens on every new project that I set up. I hope it's either easy to reproduce or just my machine.

```
mix phx.new foo --live
cd foo
mix ecto.create
mix phx.gen.live Bar Fish fishes name:string
(copy/paste routes to router)
mix ecto.migrate
mix phoenix.server
```

Then go to `localhost:4000` and immediately notice this error message in the logs + I am unable to navigate to the new live pages:
```
[error] an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Channel.start_link/1
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/channel.ex:12: Phoenix.LiveView.Channel.start_link({FooWeb.Endpoint, {#PID<0.529.0>, #Reference<0.752689962.1239416833.29542>}})
        (elixir 1.10.3) lib/dynamic_supervisor.ex:692: DynamicSupervisor.start_child/3
        (elixir 1.10.3) lib/dynamic_supervisor.ex:678: DynamicSupervisor.handle_start_child/2
        (stdlib 3.13) gen_server.erl:706: :gen_server.try_handle_call/4
        (stdlib 3.13) gen_server.erl:735: :gen_server.handle_msg/6
        (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Actual behavior
This should all work since I only used the basic commands. I can fix it by changing the liveview dep to `{:phoenix_live_view, "~> 0.13.0", override: true},` (**override** because of the liveview dashboard which has a hard dependency).

I'm not sure if it's related at all tbh but I see that it's currently set to `0.12.0` in the [phoenix master branch](https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_umbrella/apps/app_name_web/mix.exs#L42)

Like I said, hopefully it's only my machine™. Otherwise this might be a bit of a blocker for many new people getting started with liveview? There's a "gotcha" that I might not be aware of?

**Comment by chrismccord** [comment]
If you move to latest LV and latest dashboard on Phoenix 1.5.3, this will be fixed. Thanks!
