### ISSUE TITLE
Unexpected phx-click behaviour

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [phoenixframework/phoenix#3877]
### Environment
Ubuntu 18.04.4 LTS
Erlang/OTP 23 [erts-11.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.3 (compiled with Erlang/OTP 21)
phoenix_pubsub 2.0.0
phoenix_html 2.14.2
phoenix 1.5.3
phoenix_live_view 0.13.1
phoenix_live_dashboard 0.2.5
phoenix_live_reload 1.2.2

### Expected behavior
```html
<input name="email" type="email" value="">
```
I [posted a question](https://elixirforum.com/t/what-is-the-expected-behaviour-of-phx-blur-on-an-input/31976/2) on the Elixir forum.

Calling code:
```elixir
live_component @socket, EmailInput, [
  id: :email, parent: {__MODULE__, :containing_component}, email: assigns.state.email
]
```

Component:
```elixir
defmodule EmailInput do
  use Phoenix.LiveComponent

  defstruct [:value, :foobar]

  def render(assigns) do
    ~L"""
      <div id="<%= assigns.id %>">
        <ul>
          <%= render_error(assigns) %>
          <li><%= email_input(assigns) %></li>
          <li><%= next_button(assigns) %></li>
        </ul>
      </div>
    """
  end

  def update(%{id: id, email: email} = _assigns, socket) do
    assigns = [
      id: id,
      state: %__MODULE__{value: email, foobar: 0}
    ]
    socket = assign(socket, assigns)
    IO.inspect "initialized: `#{inspect(socket.assigns.state)}`"
    {:ok, socket}
  end

  def handle_event("next", %{"value" => "Next"}, socket) do
    state  = socket.assigns.state
    foobar = state.foobar + 1
    socket = assign(socket, state: %{state | foobar: foobar})
    IO.inspect "next clicked: `#{inspect(socket.assigns.state)}`"
    {:noreply, socket}
  end

  ## private

  defp render_error(%{state: %{foobar: foobar}} = assigns) when foobar === 3 do
    # boom!
    IO.inspect "Email input value is set to \"Next\": `#{inspect(assigns.state)}`"
    Phoenix.HTML.Tag.content_tag :li, "Invalid"
  end

  defp render_error(_), do: []

  defp email_input(assigns) do
    IO.inspect "email_input: `#{inspect(assigns.state)}`"
    Phoenix.HTML.Tag.tag :input, [
      type: "email",
      name: "email",
      value: assigns.state.value
    ]
  end

  defp next_button(assigns), do:
    Phoenix.HTML.Tag.tag :input, [
      type: "button",
      value: "Next",
      "phx-click": "next",
      "phx-target": assigns.myself
    ]

end
```

### Actual behavior
```html
<input name="email" type="email" value="Next">
```
Result is: click, click, boom.

After the third click, as soon as render_error/1 returns a list item, the value of the email input is set to “Next”.
After the fourth click, the list item has been removed and the value is “” again.
The value setting in the state is always “” (only clicking the button).

Console output:
```
"initialized: `%EmailInput{foobar: 0, value: \"\"}`"
"email_input: `%EmailInput{foobar: 0, value: \"\"}`"
"next clicked: `%EmailInput{foobar: 1, value: \"\"}`"
"email_input: `%EmailInput{foobar: 1, value: \"\"}`"
"next clicked: `%EmailInput{foobar: 2, value: \"\"}`"
"email_input: `%EmailInput{foobar: 2, value: \"\"}`"
"next clicked: `%EmailInput{foobar: 3, value: \"\"}`"
"Email input value is set to \"Next\": `%EmailInput{foobar: 3, value: \"\"}`"
"email_input: `%EmailInput{foobar: 3, value: \"\"}`"
"next clicked: `%EmailInput{foobar: 4, value: \"\"}`"
"email_input: `%EmailInput{foobar: 4, value: \"\"}`"
"next clicked: `%EmailInput{foobar: 5, value: \"\"}`"
"email_input: `%EmailInput{foobar: 5, value: \"\"}`"
```

**Comment by i-n-g-m-a-r** [comment]
Additionally, when I change the markup to:
```elixir
    ~L"""
      <div id="<%= assigns.id %>">
        <%= render_error(assigns) %>
        <ul>
          <li><%= email_input(assigns) %></li>
          <li><%= next_button(assigns) %></li>
        </ul>
      </div>
    """
```
and return a `p` instead of a list item:
```elixir
Phoenix.HTML.Tag.content_tag :p, "Invalid"
```
the unexpected behaviour does not occur.

The behaviour seems to be related to rendering the list items.

**Comment by sfusato** [comment]
It’s not set to “Next” actually. “Next” is hard-coded in the message, but not the output of the value:
```
IO.inspect("Email input value is set to \"Next\": `#{inspect(assigns.state)}`")
```
From the console output you copy-pasted above the value is still empty on your 3rd click:
```
"Email input value is set to \"Next\": `%EmailInput{foobar: 3, value: \"\"}`"
```
Value is still value: `""`. I’m not seeing it set as “Next” unless I’m missing something.

**Comment by i-n-g-m-a-r** [comment]
state.value remains `""`.

input.value is set to `"Next"`

the problem is not the state, state is fine, the problem is the value of the email input which is set to Next.

**Comment by sfusato** [comment]
Oh, right, I now get what you mean.

When you render the error, basically that becomes the 1st `li` tag, and the input becomes the 2nd `li` tag. Where before, the button was the 2nd `li` tag. So, it automatically patches the wrong `li` tag.

The problem is that your initial `render_error` call renders `[]`. Either surround it in a `div` node or return an empty `li` from the other `render_error` clause as well.

```diff
- <%= render_error(assigns) %>
+ <div><%= render_error(assigns) %></div>
```
LiveView is as performant as it is especially because it compiles the template in static and dynamic parts, so when it needs to update, it only needs the minimum possible to do so. Otherwise, it could do a replace-all like most other re-implementations of it in other languages do.

**Comment by i-n-g-m-a-r** [comment]
you are right about the 1st list item becoming the 2nd etc.
you are probably also right about the performance penalty.
still I think this is a bug, don't you?

**Comment by chrismccord** [comment]
I cannot recreate this on my side, but note that you need to set the value of the input in an assign and render it to maintain the user input value. If you can provide an example application with a more thorough explanation of the issue then we can say more but looks good from my side. Also note that any subsequent issues should be on the phoenix_live_view repo. Thanks!

**Comment by i-n-g-m-a-r** [comment]
Ok that's strange.
It took me hours to prepare the above example code and only minutes to prepare this application justs by copy/pasting:
https://github.com/i-n-g-m-a-r/lvbug

**Comment by i-n-g-m-a-r** [comment]
@chrismccord as you requested I created an issue here:
https://github.com/phoenixframework/phoenix_live_view/issues/946

**Comment by i-n-g-m-a-r** [comment]
I am wondering about
> you need to set the value of the input in an assign and render it to maintain the user input value

because it seems that the value of an input field is never updated (in the interface) even when a function to render the input is called on each change.

In my LiveComponent I have a render/1 function like this:
```elixir
def render(assigns), do: ~L"""
  <div id="<%= assigns.state.id %>">
    <%= email_input(assigns) %>
  </div>
"""
```
which calls an email_input/1 function:
```elixir
defp email_input(assigns), do:
  # This function is being called every time assigns change.
  Phoenix.HTML.Tag.tag :input, [
    type: "email",
    name: "email",
    value: email_value(assigns.state),  # this value shows up only once
    autofocus: true,
    "phx-key": "Enter",
    "phx-keydown": "keydown",
    "phx-target": assigns.myself,
    "data-set-focus": true
  ]
```
which calls an email_value/1 function:
```elixir
defp email_value(_), do: "foobar"
```
The input field value is set to "foobar" only the first time around on first render.
In this case I would expect the input field value to be reset to "foobar" when submitting a value.
The assigns and the input field value are out of sync.

I am not sure whether this is related to your advice, is it?

**Comment by i-n-g-m-a-r** [comment]
The previous problem does not occur when the input field has a "phx-blur" attribute and the corresponding handler updates the state.
Then the input field value (in the interface) is set to the result of email_value/1.

So this works fine, input field is set to expected value:
```elixir
"phx-blur": "blur",

def handle_event("blur", %{"value" => email}, socket) do
  # put email in state (including validation result etc)
  # socket = ...
  {:noreply, socket}
end
```
This does not work, input field value is never changed:
```elixir
"phx-key": "Enter",
"phx-keydown": "keydown",

def handle_event("keydown", %{"key" => "Enter", "value" => email}, socket) do
  # put email in state (including validation result etc)
  # handle submit, maybe send message
  # socket = ...
  {:noreply, socket}
end
```
