### ISSUE TITLE
Custom input

### ISSUE THREAD

**Issue by jagoanmamah** [phoenixframework/phoenix#3884]
![Screenshot 2020-06-04 10:01:35](https://user-images.githubusercontent.com/25195185/83721242-e3fa6600-a664-11ea-8df7-779c69393465.png)

**Comment by TheMushrr00m** [comment]
text_input/3 instead of text_input/4 ?

**Comment by jagoanmamah** [comment]
Custom input doesn't have id and class

![Screenshot 2020-06-04 14:54:05](https://user-images.githubusercontent.com/25195185/83730453-4d817100-a673-11ea-9924-dd3a71b8865d.png)

**Comment by Gazler** [comment]
You have 2 errors here:

1) There is a syntax error. In Elixir, you can only use the Keyword list syntax without `[]` if it is the last argument. So for example:

```elixir
some_fun(var1, bar: 123, var2)
```

Would have to be:

```
some_fun(var1, [bar: 123], var2)
```

2. More importantly though, there isn't a text_input/4 anyway. You want to add the `value` to opts. So try something like:

```elixir
opts = Keyword.put_new(opts, :value, text_to_tags(tags))
text_input(form, field, opts)
```

**Comment by Gazler** [comment]
We reserve the bug tracker for bug reports.

In future, please use one of the resources mentioned in https://github.com/phoenixframework/phoenix/blob/master/CONTRIBUTING.md#using-the-issue-tracker for personal support requests.
