### ISSUE TITLE
How to access http headers in a socket?

### ISSUE THREAD

**Issue by gsmlg** [phoenixframework/phoenix#3885]
### Environment

* Elixir version (elixir -v): 1.10
* Phoenix version (mix deps): 1.5.3
* NodeJS version (node -v): 12.18.0
* NPM version (npm -v): 6.14.4
* Operating system: Linux

### Expected behavior
Get http header information from connected socket

### Actual behavior
I did not find a way to get header info.
```
%Phoenix.Socket{
  assigns: %{},
  channel: nil,
  channel_pid: nil,
  endpoint: Web.Endpoint,
  handler: Web.UserSocket,
  id: nil,
  join_ref: nil,
  joined: false,
  private: %{},
  pubsub_server: App.PubSub,
  ref: nil,
  serializer: Phoenix.Socket.V2.JSONSerializer,
  topic: nil,
  transport: :websocket,
  transport_pid: nil
}
```

**Comment by Gazler** [comment]
Please use one of the resources listed in https://github.com/phoenixframework/phoenix/blob/master/CONTRIBUTING.md#using-the-issue-tracker for personal support requests.
