### ISSUE TITLE
mix phx.gen.live ... --web option doesn't generate correct live routes

### ISSUE THREAD

**Issue by soykai** [phoenixframework/phoenix#3892]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.5.3
* NodeJS version (node -v): 10.19.0
* NPM version (npm -v): 6.14.5
* Operating system: PopOS 20 (Ubuntu 19)

Ran the following command:
`mix phx.gen.live Blog Post posts title:string ... --web Blog`
and it gave me the following lines, that I was supposed to add to my router.ex
`live "/posts", PostLive.Index, :index`
`live "/posts/new", PostLive.Index, :new`
`live "/posts/:id/edit", PostLive.Index, :edit`

`live "/posts/:id", PostLive.Show, :show`
`live "/posts/:id/show/edit", PostLive.Show, :edit`

For this purpose, let's call the phoenix project's root module "MyApplication".
Without any modifications, I ran the migration, restarted the server and opened the /posts route, but it gave me the error:

>  The MyApplicationWeb.PostLive.Index module is not available

I later realized that it was saved under MyApplicationWeb.Blog.PostLive.Index, probably because I gave it the --web option.

So the generated live routes should've been
`live "/posts", Blog.PostLive.Index, :index`
`live "/posts/new", Blog.PostLive.Index, :new`
`live "/posts/:id/edit", Blog.PostLive.Index, :edit`

`live "/posts/:id", Blog.PostLive.Show, :show`
`live "/posts/:id/show/edit", Blog.PostLive.Show, :edit`

**Comment by chrismccord** [comment]
The routes should be generated inside a `scope "/", AppWeb.Blog do`. Are you sure you didn't miss the wrapping scope? Can you re-run the exact command (`> history`) and copy paste the exact output here? Thanks!

**Comment by soykai** [comment]
ohh ok, yeah I ran the command in a test project and you're right. Thank you for clearing that up, this issue can be closed then! :)

**Comment by sodapopcan** [comment]
I'm having a similar issue.

I have a `--live` generate app which nests and `admin/` with standard, non-live controllers.  I use the html generator like so:

```elixir
$ mix phx.gen.html --binary_id --web admin Admin.Pages Page pages example_field:string
```
My router then looks like this:

```
scope "/", MyAppWeb do
  pipe_through :browser

  live "/", HomeLive, :index

  scope "/admin", Admin do
    resources "/pages", PageController
  end
end
```

Running `$ mix phx.routes` shows that resources generated routes all prefixed with simply `page_` whereas all the generated controllers and templates use `admin_page_`.

I'm using Phoenix 1.5.3.
