### ISSUE TITLE
Missing docs for Endpoint url: [host: nil] behaviour

### ISSUE THREAD

**Issue by Doerge** [phoenixframework/phoenix#3907]
* Phoenix version (mix deps): 1.5.3

Apparently setting the `host` to `nil` in the endpoint config:
```
config :my_app, MyAppWeb.Endpoint,
  url: [host: nil],
```
causes the endpoint to use the host from the request [see this forum post](https://elixirforum.com/t/multiple-domains-in-phoenix/17141/7).
This is not documented anywhere, as far as I can tell. It is briefly mentioned in the compile time config under `:force_ssl` https://hexdocs.pm/phoenix/1.5.3/Phoenix.Endpoint.html#module-compile-time-configuration

Further in https://hexdocs.pm/phoenix/1.5.3/Phoenix.Endpoint.html#module-runtime-configuration `nil` is defined as an illegal value, because it explicitly mentions that `host` must be a string.

Ideally the take-the-host-from the request behavior should be documented along with any additional useful information and drawbacks to using `nil`, if there are any.

Best,
Aske

**Comment by josevalim** [comment]
Good call. Could you please send a PR? There is already a session in `Phoenix.Endpoint` that discusses the `:url`, we could add it there.

**Comment by josevalim** [comment]
Wait, this is not `force_ssl`, but `url`. I am afraid this is not documented behaviour and it works by accident. The issue with keeping `host: nil` is that generating URLs for e-mails and others won't work as expected. The whole behaviour may change at any time.

**Comment by josevalim** [comment]
I just checked that in master if host is not set, it defaults to localhost. Thanks for calling our attention to this!
