### ISSUE TITLE
Incorrect latest release on github

### ISSUE THREAD

**Issue by shankardevy** [phoenixframework/phoenix#3917]
On the right sidebar of https://github.com/phoenixframework/phoenix/, Github shows an incorrect release. Not sure if this is a Github issue.

<img width="417" alt="Screenshot 2020-06-26 at 7 53 19 AM" src="https://user-images.githubusercontent.com/2011812/85813939-42a59200-b782-11ea-85b3-62bdfb05888e.png">

**Comment by chrismccord** [comment]
Fixed ❤️❤️❤️🐥🔥
