### ISSUE TITLE
Telemetry Documentation Unclear for Series of Events

### ISSUE THREAD

**Issue by novaugust** [phoenixframework/phoenix#3927]
I'm working on integrating tracing into phoenix's telemetry, but it's unclear just from the documentation what events I can expect to handle in a request's lifecycle.

The five I'm looking at are:
- Plug.Telemetry start/stop (endpoint)
- router dispatch: start/stop/exception

It's unclear, for example, if a request can experience all five events in its lifecycle. Or does a router dispatch exception event mean that the router doesn't call stop?  What about the endpoint's stop, is it still triggered in a router exception?

**Comment by novaugust** [comment]
And just as a side note, it's seems slightly problematic to me that those crucial endpoint start/stop that the phoenix docs say it's emitting are actually reliant on the user having remembered to plug telemetry in their endpoint during, say, an upgrade (something left off the upgrade guide)

**Comment by josevalim** [comment]
That's because the events are indeed decoupled. Someone can even remove Plug.Telemetry altogether and you should not necessarily assume it is running or it is running at a particular position. The only guarantee is the router event if you do get to dispatch something in the router.

**Comment by josevalim** [comment]
Also keep mind stop and exception are not guaranteed to be invoked if the process crashes due to an exit. This is documented in the telemetry docs, in particular the telemetry:span function.

**Comment by novaugust** [comment]
I understand that a process can just exit and that's tough cookies. I'd just like to update the documentation in phoenix's telemetry section to help users understand how the events relate to each other, rather than just having information about that event as though it lives in a vacuum. That would be helpful for writing functionality that spans the events, like APM integration
