### ISSUE TITLE
mix phx.gen.json won't run in root of an umbrella project

### ISSUE THREAD

**Issue by sriedel** [phoenixframework/phoenix#3933]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.3
* NodeJS version (node -v): 11.3.0
* NPM version (npm -v): 6.10.0
* Operating system: linux

### Expected behavior
mix phx.gen.json can run in an umbrella projects root

### Actual behavior
mix phx.gen.json displays an error when run in an umbrella projects root: "** (Mix) mix phx.gen.json can only be run inside an application directory"

### Steps to reproduce
Generate a new phoenix project, without stuff that is not required for a pure api service:

    mix phx.new foo --umbrella --no-webpack --no-html --no-gettext

Enter the new project and try to generate a JSON resource:

    $ cd foo_umbrella
    $ mix phx.gen.json MyModels MyModel my_models name:string
    ** (Mix) mix phx.gen.json can only be run inside an application directory

Change into an application directory and run there:

    $ cd apps/foo_web
    $ mix phx.gen.json MyModels MyModel my_models name:string
    # runs without errors, creating files within and outside of the CWDs subtree in the filesystem

### Motivation
For someone just getting into phoenix there are two things here that are confusing:
- Which directory should I be using to call the mix task from? foo or foo_web? It's kind of implied in the help text for the mix task (Web namespace section), if you already know whats going to happen and why. Going in blind it's not obvious.
- Having a mix task break out of the directory tree it's executed in and generating/modifying files in a different subdirectory is surprising behaviour. My initial thought was that the mix task can only see within it's current directory tree and thus I'll need to have both foo and foo_web directories within the subtree of the CWD, and I spent half an hour trying to figure out how to invoke the mix task so that it can see both the context and the web directories.

**Comment by ksbulgakov** [comment]
Hi!
Maybe I am wrong. But It looks like [here](https://github.com/phoenixframework/phoenix/blob/43e2cb44b59743acba9c70bd7a756f5f1eeae34b/lib/mix/tasks/phx.gen.auth.ex#L101) should be the same error text as in other generators - "mix phx.gen.cert must be invoked from within your *_web application root directory".

**Comment by gitipedras** [comment]
I am having the same problem...
```mix phx.gen.json Accounts User users email:string password:string
** (Mix) The task "phx.gen.json" could not be found
Note no mix.exs was found in the current directory
```
