### ISSUE TITLE
iex(1)> 'MIX_ENV' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by watcher00090** [phoenixframework/phoenix#3939]
### Environment

* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 21)
* Phoenix version (mix deps): phoenix 1.4.0
* NodeJS version (node -v): v12.18.2
* NPM version (npm -v): 6.14.5
* Operating system: Windows 10 Pro

### Expected behavior

After running "iex -S mix phx.server", the dev server starts seamlessly. 

### Actual behavior

I cannot see my page in localhost:4000, and this error message is printed in the terminal: 

2020-07-26T16:19:33.813000Z info Running OrcasiteWeb.Endpoint with cowboy 2.5.0 at http://localhost:4000
Interactive Elixir (1.10.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> npmiex(1)>  iex(1)> WARNiex(1)>  iex(1)> lifecycleiex(1)>  The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using c:\PROGRA~1\nodej
s\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
iex(1)>
> Orcasite@1.0.0 watch c:\workspace\orcasite\assets
> MIX_ENV=dev webpack-dev-server --mode development --inline --hot --stdin --colors

iex(1)> 'MIX_ENV' is not recognized as an internal or external command,
operable program or batch file.
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  iex(1)> codeiex(1)>  ELIFECYCLE
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  iex(1)> errnoiex(1)>  1
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  Orcasite@1.0.0 watch: `MIX_ENV=dev webpack-dev-server --mode development --inline --hot --stdin --colors`
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  Exit status 1
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  Failed at the Orcasite@1.0.0 watch script.
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  This is probably not a problem with npm. There is likely additional logging output above.
iex(1)>
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  A complete log of this run can be found in:
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>      C:\Users\pcp071098\AppData\Roaming\npm-cache\_logs\2020-07-26T16_19_36_370Z-debug.log
iex(1)> 2020-07-26T16:19:38.456000Z error Task OrcasiteWeb.Endpoint started from #PID<0.474.0> terminating
** (stop) :watcher_command_error
    (phoenix 1.4.0) lib/phoenix/endpoint/watcher.ex:29: Phoenix.Endpoint.Watcher.watch/3
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "watch"], [cd: "c:/workspace/orcasite/assets"]]
iex(1)> npmiex(1)>  iex(1)> WARNiex(1)>  iex(1)> lifecycleiex(1)>  The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using c:\PROGRA~1\nodej
s\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
iex(1)>
> Orcasite@1.0.0 watch c:\workspace\orcasite\assets
> MIX_ENV=dev webpack-dev-server --mode development --inline --hot --stdin --colors

iex(1)> 'MIX_ENV' is not recognized as an internal or external command,
operable program or batch file.
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  iex(1)> codeiex(1)>  ELIFECYCLE
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  iex(1)> errnoiex(1)>  1
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  Orcasite@1.0.0 watch: `MIX_ENV=dev webpack-dev-server --mode development --inline --hot --stdin --colors`
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  Exit status 1
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  Failed at the Orcasite@1.0.0 watch script.
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  This is probably not a problem with npm. There is likely additional logging output above.
iex(1)>
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>  A complete log of this run can be found in:
iex(1)> npmiex(1)>  iex(1)> ERR!iex(1)>      C:\Users\pcp071098\AppData\Roaming\npm-cache\_logs\2020-07-26T16_19_39_957Z-debug.log
iex(1)> 2020-07-26T16:19:42.010000Z error Task OrcasiteWeb.Endpoint started from #PID<0.483.0> terminating
** (stop) :watcher_command_error
    (phoenix 1.4.0) lib/phoenix/endpoint/watcher.ex:29: Phoenix.Endpoint.Watcher.watch/3
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.12) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "watch"], [cd: "c:/workspace/orcasite/assets"]]

My guess is that the line

 MIX_ENV=dev webpack-dev-server --mode development --inline --hot --stdin --colors

isn't working due to the way Windows sets environment variables (see [this stackoverflow post]( https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman). It didn't work in the regular Windows command prompt.

**Comment by josevalim** [comment]
Hi @watcher00090!

To give you a bit more context. When Phoenix boots in development, it starts a watcher that recompiles JS assets. If you open up your config/dev.exs, you will find a `watchers:` configuration. In a recent Phoenix configuration, it will look like this:

```elixir
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]
```

However, in your case, it seems it is trying to run `npm run watch`. In this case, this is not a Phoenix issue, we are running the desired command, which succeeds, and then `npm run watch` itself is the one using environment variables incorrectly (if that's the root cause). My suggestion is to change your watchers configuration to mimic the one above.

**Comment by watcher00090** [comment]
Hi Jose, thanks for getting back to me about this. I made the change and now the server starts, but it doesn't load the files that it'd like for it to. In the web console I'm getting: "net::ERR_CONNECTION_REFUSED" for both my app.js and app.css, and what's really weird is that I don't see anything about this in the terminal. Not sure if this is an issue with my code or something else, but if you'd weight in here I would really appreciate it. How does one go about debugging issues like these?

**Comment by josevalim** [comment]
It is hard to say without looking at your app. Even then, this is not really a Phoenix issue, rather a JS/Webpack one, so it is probably more productive if you can go to a specific JS forum. 

My suggestion is to run the command in isolation, such as `node node_modules/webpack/bin/webpack.js —watch-stdin` in the assets directory, and remove Phoenix from the equation and then attempt to get more specific help. :)
