### ISSUE TITLE
Phoenix.View.render_many can't render .leex templates

### ISSUE THREAD

**Issue by sfusato** [phoenixframework/phoenix#3952]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.4
* NodeJS version (node -v): 14.2.0
* NPM version (npm -v): 6.14.4
* Operating system: Manjaro Linux

### Expected behavior
`render_many/4` should be able to render `.leex` templates.

### Actual behavior

```
    ** (ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: %Phoenix.LiveView.Rendered{dynamic: #Function<0.2130126/1 in ChirpWeb.PageView."render_many.html"/1>, fingerprint: 283660567725508428567016079018915770520, static: ["<p>render_many.html.leex</p>\n"]}
        (phoenix_html 2.14.2) lib/phoenix_html/safe.ex:81: Phoenix.HTML.Safe.List.to_iodata/1
        (phoenix_html 2.14.2) lib/phoenix_html/safe.ex:49: Phoenix.HTML.Safe.List.to_iodata/1
```

**Comment by sfusato** [comment]
Pattern matching on the `%Phoenix.LiveView.Rendered{}` struct and then re-calling `Phoenix.HTML.Safe.to_iodata` with the data inside [`defimpl Phoenix.HTML.Safe, for: List`](https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/safe.ex#L47) seems to do the trick. Is this the right approach?

```elixir
def to_iodata(%Phoenix.LiveView.Rendered{} = data) do
  Phoenix.HTML.Safe.to_iodata(data)
end
```

**Comment by josevalim** [comment]
Unfortunately I don't believe we can support it, as the list handling is really only limited to safe constructs. We would need to introduce live_render_many or similar but perhaps it is best to just use Enum.map then. Thanks for the report! :heart:

**Comment by grzuy** [comment]
Hi,

Just for what is worth, I experienced the same issue with `render_many` with newer `HEEx` templates (not `LEEx`).

Had to use `Enum.map`+`render` instead to make it work.

**Comment by thiagomajesk** [comment]
Same here, just experienced this today with `HEEx`, should we open another issue to track this @josevalim?

**Comment by josevalim** [comment]
No, it cannot work, you have to use a for comprehension in your templates to make it work efficiently for now. The docs have been updated to reflect this is mostly useful on json cases.

**Comment by thiagomajesk** [comment]
I see, this is kind of an unpleasant surprise, to be honest. But, will it be supported eventually? Considering that Phoenix is moving to `HEEx` it seems very counter-intuitive that this breaks after seeing extensive usage within HTML.
