### ISSUE TITLE
Question about new phoenix and websockets

### ISSUE THREAD

**Issue by RDP1974** [phoenixframework/phoenix#3953]
Hello Jose,

I have read somewhere that in the latest version of Phoenix you have exposed WebSockets interface, so to manage them directly (without channel abstraction?) for better performances and management.

It's true?

Thank you.
Kind regards.
R.

### Environment

* Elixir version (elixir -v): 
* Phoenix version (mix deps): 1.54
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system: FreeBSD

**Comment by chrismccord** [comment]
raw WebSocket handlers can indeed be exposed via the `Phoenix.Socket` behavior. Thanks!
