### ISSUE TITLE
non-deterministic integration test - test/phoenix/integration/endpoint_test.exs:108

### ISSUE THREAD

**Issue by adrianomitre** [phoenixframework/phoenix#3955]
### Environment

* The environment is the project CI
  * Elixir version (elixir -v): 1.9.4 on Erlang/OTP 20.3.8.26 and Elixir 1.10.4 on Erlang/OTP 23.0.3
  * Phoenix version (mix deps): master
  * NodeJS version (node -v): 12.16
  * NPM version (npm -v): N/A
  * Operating system: GNU/Linux Alpine 3.12.0

### Actual behavior

Test [`test/phoenix/integration/endpoint_test.exs:108`](https://github.com/phoenixframework/phoenix/blob/master/test/phoenix/integration/endpoint_test.exs#L108) is behaving non deterministically with respect to the codebase.

#### Sets of evidence

Set 1 (same everything, only [an empty commit](https://github.com/phoenixframework/phoenix/pull/3944/commits/34b6eb1e831a03a0cdc6a97d7fe3fee199aae2a6) apart), first observed on https://github.com/phoenixframework/phoenix/pull/3944#issuecomment-668220020:
- https://github.com/phoenixframework/phoenix/pull/3944/checks?check_run_id=941932050 <- fail
- https://github.com/phoenixframework/phoenix/pull/3944/checks?check_run_id=942088825 <- pass

Set 2 (same everything, only (same everything, only [a doc-only-changing commit](https://github.com/phoenixframework/phoenix/commit/87a4d09437528d2ba7bdac949f9782290a45788f) apart):
- https://github.com/phoenixframework/phoenix/runs/945545602 <- fail
- https://github.com/phoenixframework/phoenix/runs/945547458 <- pass

### Expected behavior

Pass or fail deterministically with respect to the source code.

**Comment by chrismccord** [comment]
Passes locally just fine so if you can help isolate on CI via a PR would me much appreciated. Thanks!
