### ISSUE TITLE
a pair of hints

### ISSUE THREAD

**Issue by RDP1974** [phoenixframework/phoenix#3956]
hi Chris,

perhaps can you show a little example or guide how to build a websocket based server where:
- do efficient 1->1 messaging (using a global shared room?)
- show, customize the payload of the low level websocket messaging, incapsulation, frames, json schema -> so to be able to build clients in js, c, or whatever lang 
- do a small parser of the received message, receive -> string managing, parsing -> send
- do plain "unrolled" queries using ecto.sqladapters? Use a pool of sql connections and use an async I/O to avoid locking waiting on DB operations?

Thanks, I'm a newbie of FP and Elixir and coming from strong OOP foundation
kind regards

**Comment by chrismccord** [comment]
This would be a great forum question or addition to the guides as guides PR, but not something we should take up on the issue tracker. Welcome to Elixir and FP :)
