### ISSUE TITLE
Issue with Phoenix server start on background with name option

### ISSUE THREAD

**Issue by aruna470** [phoenixframework/phoenix#3964]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.6
* NodeJS version (node -v): 10.19
* NPM version (npm -v):
* Operating system: RHEL 7

### Issue

I want to run Phoenix server in background with following command

MIX_ENV=prod elixir --erl --name "compose-api@svdt5fusion01" "-detached" -S mix phx.server

but it output with an error "No file named compose-api@svdt5fusion01" and server is not starting.

![api](https://user-images.githubusercontent.com/9816285/90733457-32c1ae80-e2ea-11ea-8ceb-af69696a9824.png)

If I remove the name option and run it works fine.
MIX_ENV=prod elixir --erl "-detached" -S mix phx.server

![running](https://user-images.githubusercontent.com/9816285/90733791-acf23300-e2ea-11ea-9eb0-86170a17992a.png)

What is the issue with name option, is it no longer support? Same command with name is running properly on some other servers with same configurations, OS etc..

**Comment by delameko** [comment]
You just have the ordering wrong.  --erl is for passing switches to erlang, but you have "-detached" after the --name switch.  This should work:

    MIX_ENV=prod elixir --erl "-detached" --name "compose-api@svdt5fusion01" -S mix phx.server

**Comment by aruna470** [comment]
Hi @delameko Thanks for the reply. I tried the command you sent but still it's not working. Without name option its working.

![issue](https://user-images.githubusercontent.com/9816285/90860200-3830fe80-e3a7-11ea-84bd-dfa765659cc8.png)

**Comment by aruna470** [comment]
> 
> 
> Hi @delameko Thanks for the reply. I tried the command you sent but still it's not working. Without name option its working.
> 
> ![issue](https://user-images.githubusercontent.com/9816285/90860200-3830fe80-e3a7-11ea-84bd-dfa765659cc8.png)

Issue resolved. Command should be like this

MIX_ENV=prod elixir --erl "-detached --name compose-api@svdt5fusion02" -S mix phx.server
