### ISSUE TITLE
Changes to :format_encoders are not picked up until IEX is restarted

### ISSUE THREAD

**Issue by software-opal** [phoenixframework/phoenix#3974]
When running as IEX shell for development, we are not able to see the effects of changes to the phoenix configuration by running `recompile`, instead we need to restart the IEX shell. On investigation I noticed that Phoenix [caches the value of `:format_encoders`](https://github.com/phoenixframework/phoenix/blob/v1.4.17/lib/phoenix/template.ex#L212-L225); and this value doesn't appear to be cleared during a recompile call.

I don't have the full picture(I'm very much an inexperienced Elixir developer), but I expect that the caching is used to provide speedups in production. I wonder if that caching pattern could be disabled when running in development mode, just to limit the surprises.

### Environment

* Elixir version (elixir -v): `Elixir 1.10.3 (compiled with Erlang/OTP 22)`
* Phoenix version (mix deps): `phoenix 1.4.17 (Hex package) (mix)`
* NodeJS version (node -v): Not applicable
* NPM version (npm -v): Not applicable
* Operating system: `Debian 10 (buster)`(`elixir:1.10` Docker container)

### Expected behavior

When running an IEX shell, changes to configuration values should be applied after running `recompile`. For us, we were trying to add the following configuration to our app's `config.exs` file:

```
config :phoenix, :format_encoders,
  html: Phoenix.Template.HTML,
  xml: Phoenix.Template.HTML
```

Which should mean that subsequent requests to render an XML template should have the rendered values are escaped.

### Actual behavior

The escaping is not applied until restarting the IEX shell

### Example

For this template, saved as `example.xml`:
```eex
<%= "this & that is > 'something' else" %>
```

It should be rendered as this before making the change:
```xml
this & that is > 'something' else
```

and be rendered as thing after making the change:
```xml
this &amp; that &gt; &#39;something&#39; else
```

**Comment by josevalim** [comment]
Yes, format_encoders is cached, therefore any changes to it won't propagate. Generally speaking, you should not assume that changing the configuration will automatically reflect on the app without restarting it. In particular to the `recompile` command, it only recompiles modules, it doesn't reload configs for example. I will improve its docs to make it clear. Thanks!
