### ISSUE TITLE
Erlang 23 is considerably slower (+50%) than 21/22 in the Phoenix test suite

### ISSUE THREAD

**Issue by plicjo** [phoenixframework/phoenix#3976]
### Environment

* Elixir version (elixir -v): 1.10.4
* Erlang version: 23.0.3

vs

* Elixir version (elixir -v): 1.10.4
* Erlang version: 21.3.8.17

### Expected behavior

I expected performance to be similar/faster using Erlang 23. This test suite speed slowdown was seen in my own application after an Erlang upgrade from 22 to 23.

### Actual behavior

I noticed a considerable slowdown in test suite speed when I upgraded from Erlang 22 to 23 in my own Phoenix project.

To cross-reference what I was seeing, I compared the latest builds against the Phoenix framework:
**Using Elixir 1.10.4 and Erlang 21.3.8.17, the Phoenix test suite took 23.5 seconds on a recent build with the same code.**
![Screen Shot 2020-08-27 at 12 09 30 PM](https://user-images.githubusercontent.com/7145362/91467189-41661380-e85e-11ea-87f9-1c64ea85e127.png)
https://github.com/phoenixframework/phoenix/runs/1028174653?check_suite_focus=true

**Using Elixir 1.10.4 and Erlang 23.03, the Phoenix test suite took 36.3 seconds on a recent build with the same code.**

![Screen Shot 2020-08-27 at 12 10 43 PM](https://user-images.githubusercontent.com/7145362/91467274-5c388800-e85e-11ea-89b5-5a4d4fe5a21d.png)
https://github.com/phoenixframework/phoenix/runs/1028174680?check_suite_focus=true

**Comment by chrismccord** [comment]
Can you provide your local results on the same machine? CI alone is not trustworthy as we have no idea what the instances backing the runs are like. Closing until we have more info. Thanks!

**Comment by plicjo** [comment]
I made a repository with the standard Phoenix installation + generating code with `phx_gen_auth`

https://github.com/plicjo/phoenix_otp_22_vs_23

My specs:

```
Hardware Overview:

  Model Name:	Mac mini
  Model Identifier:	Macmini6,2
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	286.0.0.0.0
  SMC Version (system):	2.8f1
  Serial Number (system):	C07N1161DY3H
  Hardware UUID:	7C3792EF-B8F7-54FB-A607-E0FF2D31EBF1
```

With OTP 23, with the same code, same Phoenix and Elixir version, on the same machine:
![Screen Shot 2020-09-02 at 11 09 32 AM](https://user-images.githubusercontent.com/7145362/92005745-d612ba80-ed11-11ea-8338-667ea006e707.png)

**The test suite took 4.5 seconds.**

With OTP 22, with the same code, same Phoenix and Elixir version, on the same machine:
![Screen Shot 2020-09-02 at 11 42 51 AM](https://user-images.githubusercontent.com/7145362/92005831-f2165c00-ed11-11ea-8369-a6bd02660b2c.png)
**The test suite took 1.3 seconds.**
