### ISSUE TITLE
Inability to persist flash across non-300 status code responses

### ISSUE THREAD

**Issue by liamwhite** [phoenixframework/phoenix#3980]
Given the following code:
https://github.com/phoenixframework/phoenix/blob/f3eb2a9e93f7a8f7caa2ebd0e94305db03fe8612/lib/phoenix/controller.ex#L1334-L1358

There is simply no possible method to persist the flash using the built-in Phoenix controller methods across a response that fits a  particular status code if it is not a 300-range code.

For an example usecase, I have client logic that may trigger the status code 429 Too Many Requests to a submission endpoint from a fetch-initiated request. In the event this happens, I would like for the client script to reload the page and display the flash error. But it is not possible with just Phoenix alone to persist the flash I set, unless I use a non-redirecting 300 response like 300 Multiple Choices. Unfortunately, this response status does not align with the reason the request has been blocked and complicates my code to support.

**Comment by josevalim** [comment]
A PR that adds some sort of force_flash, that always forces it to be persisted, is welcome!

**Comment by chrismccord** [comment]
If someone would like to move forward with a PR please ping this issue.
