### ISSUE TITLE
No way to tell when debugger is invoked

### ISSUE THREAD

**Issue by liamwhite** [phoenixframework/phoenix#3981]
As part of the plug pipeline for my application, I have a `before_send` callback registered. This callback sets a content-security-policy header which restricts access to all inline styles and scripts. However, when encountering an error in development, this callback is still run, and results in the Phoenix debug error page looking like this:
![Screenshot_2020-08-29 ArgumentError at GET ](https://user-images.githubusercontent.com/9658600/91645616-8fbd1300-ea14-11ea-823d-54af39d990a2.png)
However, it is supposed to look like this:
![Screenshot_2020-08-29 ArgumentError at GET (1)](https://user-images.githubusercontent.com/9658600/91645620-96e42100-ea14-11ea-92cc-a7ff8811ce0c.png)
Since the installation of this header is done in a `before_send` callback, if a way to tell when the debugger has been invoked in the conn was available, I could simply choose to not to install it. But I looked through every field in the conn and Phoenix provides no information that the debugger has been invoked at all, so as it stands I have no way to fix debug error pages without making serious compromises like disabling the CSP in development.

**Comment by chrismccord** [comment]
Check the Plug.Debugger docs to see if there's some information in the connection that you can key off of. The plug debugger wraps the entire plug stack and rescues errors. Moving your CSP plug further down the stack may give you want you want, but I don't know the particulars of your setup. Closing as this is not a Phoenix issue. Thanks!

https://github.com/elixir-plug/plug/blob/master/lib/plug/debugger.ex
