### ISSUE TITLE
[Question] Should the path helper automatically use the `param` of a resource?

### ISSUE THREAD

**Issue by zimt28** [phoenixframework/phoenix#3983]
I'm using [`Phoenix.Router.resources/4`](https://hexdocs.pm/phoenix/Phoenix.Router.html?#resources/4) with the `param` option:

> `:param` - the name of the parameter for this resource, defaults to "id"

```elixir
resources "/settings", SettingController,
  only: [:edit, :update],
  param: "key"
```

When using the path helper and give it a resource, the id is still being extracted:

```elixir
Routes.setting_path(conn, :edit, setting_struct)
# -> /settings/75715498-80f2-4247-b1ec-6a655883376a/edit
```

Shouldn't be the `param` setting be respected here? I currently have to specify the `key` field manually:
```elixir
Routes.setting_path(conn, :edit, setting_struct.key)
# -> /settings/account/edit
```

**Comment by chrismccord** [comment]
Please send questions to slack, irc, or the forums per the issue template. You need to implement the `Phoenix.Param` protocol for that struct. The helpers only indicate the name of the key in the params. Thanks!
