### ISSUE TITLE
`mix phx.gen.live --no-context` warns about existing context

### ISSUE THREAD

**Issue by axelclark** [phoenixframework/phoenix#3994]
### Environment

* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.5.4

### Expected behavior

When I run `mix phx.gen.live --no-context`, I do not expect a warning about adding to an existing context.

### Actual behavior

The `--no-context` command warns about adding to an existing context.  If you proceed `y`, then it doesn't create the context as expected.  However, the warning is confusing because it implies the generator is going to inject code into your existing context.

See terminal output below.

```terminal
$ mix phx.gen.live --no-context --no-schema --web commish FantasyLeagues FantasyLeague fantasy_leagues fantasy_league_name:string 

You are generating into an existing context.

The Ex338.FantasyLeagues context currently has 9 functions and 5 files in its directory.

  * It's OK to have multiple resources in the same context as long as they are closely related. But if a context grows too large, consider breaking it apart

  * If they are not closely related, another context probably works better

The fact two entities are related in the database does not mean they belong to the same context.

If you are not sure, prefer creating a new context over adding to the existing one.

Would you like to proceed? [Yn] y

* creating lib/ex338_web/live/commish/fantasy_league_live/show.ex
* creating lib/ex338_web/live/commish/fantasy_league_live/index.ex
* creating lib/ex338_web/live/commish/fantasy_league_live/form_component.ex
* creating lib/ex338_web/live/commish/fantasy_league_live/form_component.html.leex
* creating lib/ex338_web/live/commish/fantasy_league_live/index.html.leex
* creating lib/ex338_web/live/commish/fantasy_league_live/show.html.leex
* creating test/ex338_web/live/commish/fantasy_league_live_test.exs
```

**Comment by axelclark** [comment]
It looks like `prompt_for_conflicts/1` should have a similar approach as `context_files/1` to do nothing when `%Context{generate?: false}`.
https://github.com/phoenixframework/phoenix/blob/0c045af1a86b24cfa02187abdeeb58da6cd6dcaf/lib/mix/tasks/phx.gen.live.ex#L101-L120

**Comment by aaronrenner** [comment]
I can confirm this issue. I'd be happy to take a look at it if you like.
