### ISSUE TITLE
JS-Source-Maps are not generated 

### ISSUE THREAD

**Issue by Aduril** [phoenixframework/phoenix#4002]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): phoenix 1.5.5
* NodeJS version (node -v): 12.16.1
* NPM version (npm -v): 6.13.4
* Operating system: macOS Catalina

### Expected behavior

Hello,
I did a quick search and found no related issue here. If I overlooked something: Sorry in advance.
When I run `mix phx.server` phoenix should create source-maps for my JS and CSS files.

### Actual behavior

This does not occurr. Instead there is simply my JS/CSS file.

I found a 'fix' for myself and created a pull request here: https://github.com/phoenixframework/phoenix/pull/4001
I like to encourage you to have someone with a little more insight into webpack look into it. I read about that the `eval-*source-map` improves rebuilds, but somehow it does not build the maps in this case.
 
Thanks for the great framework and stuff - hope my input helps :)

Kind regards,
Aduril

**Comment by Gazler** [comment]
Thanks for the issue.

When you use the `eval` option, the source maps are generated inline with the files. This means you won't see separate `.map` files, but the source maps will be available in the browser.

![source-maps](https://user-images.githubusercontent.com/477511/94236458-2b9f4900-ff05-11ea-9188-26057983003b.png)

Please confirm if this is what you are seeing. If not then I'll leave this issue open.

**Comment by Aduril** [comment]
Ahhhh :man_facepalming: ,
Yeah - that is exactly what I'm seeing.
That explains a lot. Thanks for answering fast. :sweat_smile:
