### ISSUE TITLE
Automatically add Github Actions workflow when creating new project with phx.new

### ISSUE THREAD

**Issue by ruudk** [phoenixframework/phoenix#4004]
I think it would be super convenient if Phoenix would automatically add a Github Actions workflow template that runs the tests and spawns a Postgres DB service. That way, people that use Github will have the CI set-up immediately.

Same thing can be done for Github Dependabot configuration. That is moving to YAML config which we can also automatically generate. It will help people keeping their dependencies up to date.

If this is something that can be accepted, I would like to work on a PR 😊

**Comment by josevalim** [comment]
While I am an avid user of GitHub, even for private stuff, I would be worried about directly promoting github CI and other practices on new projects. If this is of interest, then someone can create a project called `phx.gen.github` or similar, like we did for `phx.gen.auth`, and provide that externally, thanks!
