### ISSUE TITLE
socket.transport send error

### ISSUE THREAD

**Issue by RDP1974** [phoenixframework/phoenix#4016]
hello,

I have correctly implemented https://hexdocs.pm/phoenix/Phoenix.Socket.Transport.html#module-example

I want to send a message directly to a target websocket
however using a code as follow (in handle_in callback):

socket_pid = self()
send(socket_pid, “TEST”) #trying to send a message to myself

it throwns an error

how to send directly a message to another websocket (eg. using pid) without subscribe to a pg2: or endpoint.broadcast?

**Comment by chrismccord** [comment]
Please send questions to slack, the forum, or irc. Without seeing the error it's impossible to say what's happening, but you can define a `handle_info/2` to handle whatever messages you are sending to `self()`. Thanks!
