### ISSUE TITLE
Upgrading webpack from 4 to 5

### ISSUE THREAD

**Issue by joshchernoff** [phoenixframework/phoenix#4020]
### Environment

phoenix 1.5.5
elixir      1.10.3-otp-23 
erlang   23.0.1 
nodejs  12.18.4  
npm      6.14.6
OSX 10.15.6 (19G2021)
Webpack 5
```
% mix phx.server
Compiling 59 files (.ex)
Generated morphic_pro app
[info] [alarm_handler: {:set, {:system_memory_high_watermark, []}}]
[info] Running MorphicProWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4001 (https)
[info] Access MorphicProWeb.Endpoint at https://localhost:4001
[webpack-cli]
TypeError: Cannot read property 'tap' of undefined
[error] Task MorphicProWeb.Endpoint started from #PID<0.1043.0> terminating
** (stop) :watcher_command_error
    (phoenix 1.5.5) lib/phoenix/endpoint/watcher.ex:37: Phoenix.Endpoint.Watcher.watch/3
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["node", ["node_modules/webpack/bin/webpack.js", "--config", "webpack.dev.config.js", "--color", "--bail"], [cd: "/Users/joshchernoff/Dev/morphic.pro/assets"]]
```
Looks like watch is broken with the webpack 5 upgrade. 

Also, note `--watch-stdin` is no longer an option

**Comment by joshchernoff** [comment]
Not related to phoenix.

**Comment by zoidbergwill** [comment]
I think this is related to Phoenix, and we should re-open?

Webpack 5 is [out](https://webpack.js.org/blog/2020-10-10-webpack-5-release/)

`--watch-stdin` is gone, which is used in the base here: https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_single/config/dev.exs#L19

We wanna bump webpack [here](https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_assets/package.json#L27)

**Comment by markevich** [comment]
@joshchernoff Hi! Can you please explain why it's not related to Phoenix?

Phoenix compiles assets through `Webpack`. Phoenix has `webpack.config` included in the `phx.new` generator. IMHO assets handling `IS` the part of the framework.

**Comment by ruudk** [comment]
@joshchernoff Please re-open.

**Comment by cw789** [comment]
PR in work.

**Comment by ruudk** [comment]
@cw789 Already done https://github.com/phoenixframework/phoenix/pull/4053:)

**Comment by cw789** [comment]
> @cw789 Already done #4053:)

Thx. But I've prepared it to really ship webpack 5 with `phx.new` ... (at least I think so ;)
