### ISSUE TITLE
pipe through stacktrace

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#4022]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps): 1.5.5
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

### Expected behavior

Have useful stacktraces for exceptions in pipelines

### Actual behavior

```
lib/connect_web/router.ex:1 ConnectWeb.Router.__pipe_through7__/1
```

Can't the generated function include the name of the pipeline? Like `__pipe_through_browser__/1`?

**Comment by josevalim** [comment]
If the pipe_through has a single entry, then we don't generate any function, but I am assuming in your case you have more than one, which is why it has the mangled name.
