### ISSUE TITLE
Can't use Socket with NodeJS and TypeScript (type for Socket option: transport is too narrow)

### ISSUE THREAD

**Issue by marcinkoziej** [phoenixframework/phoenix#4025]
Problem:
The `phoenix.js` file contains `Socket` class, implementing Phoenix WebSocket channel transport peculiarities.
It uses the WebSocket implementation from the browser, (`global.WebSocket`), or a privided value (`transport` option).
If I use phoenix.js in nodeJS environment, I need to use WebSocket provided by 'ws' npm package, passing it as follows:

```js
import Socket from 'phoenix'
import WebSocket from 'ws'
const socket = new Socket(wsUrl, {transport: WebSocket})
```

However, when using Typescript, the `@types/phoenix` package defines `transport` option as `string` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/003bce81eeb20c42ad7708e47586799a5461a2da/types/phoenix/index.d.ts#L40)

In fact, the transport option can also be other things https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix.js#L756

```
    this.transport            = opts.transport || global.WebSocket || LongPoll
```

This leads to a problem where it is not possible to use Phoenix Socket with Typescript in NodeJS environment.
An ugly hack is to assign the transport after creating the object:
```js
import Socket from 'phoenix'
import WebSocket from 'ws'
const socket = new Socket(wsUrl, {transport: "hack"})
const x = phoenixSocket as any
x['transport'] = WebSocket
```

The type declaration should be fixed, but I am not really sure how (hence no PR, sorry). It seems there are many implementations of WebSocket and they do not share a type (Even the 'ws' WebSocket is not type-compatible with browser WebSocket (see https://github.com/websockets/ws/issues/1583)

### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.5
* NodeJS version (node -v): v12.19.0
* NPM version (npm -v): 6.14.8
* TypeScript  (tsc -v): 4.0.3
* Operating system:

### Expected behavior

The `@types/phoenix` package allows `new Socket(url, {transport: WebSocket})` with WebSocket from  'ws'.

### Actual behavior
tsc produces error:
```
src/client.ts:3:1 - error TS2322: Type 'typeof WebSocket' is not assignable to type '{ new (url: string, protocols?: string | string[]): WebSocket; prototype: WebSocket; readonly CLOSED: number; readonly CLOSING: number; readonly CONNECTING: number; readonly OPEN: number; }'.
  Types of property 'prototype' are incompatible.
    Property 'dispatchEvent' is missing in type 'import("/home/marcin/Projects/proca-api/node_modules/@types/ws/index")' but required in type 'WebSocket'.
```

**Comment by chrismccord** [comment]
The typescript package is third party, so I suggest you file the issue over there. We do not provide type definitions for typescript. Thanks!
