### ISSUE TITLE
Subscribing a socket to a Phoenix Channel server side

### ISSUE THREAD

**Issue by chrism2671** [phoenixframework/phoenix#4028]
I appreciate this is the wrong place to ask for support, so please close this issue if it's inappropriate

I'm trying to programatically auto-subscribe a `socket` connection to various channels, on connect. I know this can be done from the client side by sending `phx_join` messages, but I cannot figure out how to do this from the server side.

I think I want to trigger:
https://github.com/phoenixframework/phoenix/blob/e82161eb8f724a69cb17b8e2a22ea54e595b29ca/lib/phoenix/socket.ex#L614

So I've set up a command of the form:

    Endpoint.PubSub.broadcast("user_socket:chris", "phx_join", %{event: "phx_join", topic: "room:time"})

But variations of this don't seem to trigger it. What am I doing wrong?

Incidentally, `MyAppWeb.Endpoint.broadcast("users_socket:" <> user.id, "disconnect", %{})` works just fine.

One again, apologies I shouldn't ask here, and feel to just close the issue. Thanks so much.

**Comment by chrismccord** [comment]
You cannot subscribe the client to other channels from the server side. You *can* subscribe to other topics and handle those messages in the `handle_info` callback in your channel, but you need to have the client initiate the join.

**Comment by chrism2671** [comment]
Thanks @chrismccord ! :)

**Comment by chrismccord** [comment]
Sounds like what you want is to issue a token to the client via an existing channel and the client can use that to join a new channel. You may also already have all the info needed to verify the join (connect/3 current_user from your user socket), so you may only need to send a message to the client with the topic they should join, then join on the client => verify current_user (or token) on the new channel.

**Comment by chrism2671** [comment]
The issue I'm facing is that I'm trying to auto-subscribe the user to various channels on connect, without the client having to explicitly request it.

I'm trying to build a websocket interface for one-way communication that other developers can consume, without them knowing how to work a phoenix channel or using a socket client.
