### ISSUE TITLE
Update mix phx.new to use Elixir v1.11 new config/runtime.exs

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#4038]
The plan is to do a gradual migration. For now, we will update the generator so that:

1. It requires Elixir v1.11 and later

2. `config/prod.secret.exs` will be renamed to `config/runtime.exs`. We want to run the `config/runtime.exs` contents only in prod, so we will wrap its existing body in a `if config_env() == :prod` check.

3. We will replace the use of `Mix.env()` in all configs by `config_env()`

4. We will update the guides to refer to `config/runtime.exs` first and foremost (although we should add a parens and say it was called `config/prod.secret.exs` in previous releases)

**Comment by landongrindheim** [comment]
I should have left a `closes` keyword on #4040. Is this good to be closed now?

**Comment by josevalim** [comment]
Yes, thank you! :heart:

**Comment by syfgkjasdkn** [comment]
👋

Is there any downside to using runtime config for everything not related to compilation?

I've made a small dummy project to try out this idea where [I moved all config to `config/runtime.exs`](https://github.com/syfgkjasdkn/runtime-config-all-in/pull/1/files) and then [grouped `config/3` by module being configured](https://github.com/syfgkjasdkn/runtime-config-all-in/pull/2/files).

In that setup when I change some config value, the whole project is not being recompiled which seems like a plus.

The only downside I see is that `runtime.exs` file seems a bit unstructured.

**Comment by josevalim** [comment]
The main limitation is that there is no easy way right now to know if something is a compile or a runtime config besides trial and error, so I am wary of blindingly pushing folks to this direction. When the new Application.compile_env! becomes widespread enough, we will at least have some indicators, that’s when we can start using this more.
