### ISSUE TITLE
Libsass deprecated

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#4042]
https://sass-lang.com/blog/libsass-is-deprecated

With libsass being deprecated the generators should be updated to use `sass` instead of `node-sass`.

**Comment by josevalim** [comment]
A PR is welcome!

**Comment by sean-clayton** [comment]
@LostKobrakai I just created a fresh phoenix app and replaced the `node-sass` dep with just `sass` `^1.27.0` and it worked flawlessly.
