### ISSUE TITLE
Add randomization to exponential backoff strategy?

### ISSUE THREAD

**Issue by dbi1** [phoenixframework/phoenix#4045]
Might it make sense to add a little bit of randomization to the websocket js client's reconnect interval times?

This way the "thundering herd" that is trying to reconnect after server update/restart might not all try (and retry) at the same times, but be spread out a little bit more.

Thank you!

**Comment by chrismccord** [comment]
You can do that with the `reconnectAfterMs` socket options (see the phoenix.js docs). Thanks!

**Comment by dbi1** [comment]
Got it, thanks, Chris!
