### ISSUE TITLE
Trying to use phoenix as a web application firewall to block DDOS like attacks.

### ISSUE THREAD

**Issue by gitmko0** [phoenixframework/phoenix#4047]
1. Trying to use phoenix as a web application firewall to block DDOS like attacks. is it advisable to write a WAF using phoenix? else, what should be fronting phoenix as a firewall? i cant use iptables because i would like to block bad / missed IPs from cloudflare. it's already fronted by cloudflare but cloudflare doesnt block everything.

2. i'm totally newbie to erlang / phoenix / elixir etc. since it's running concurrently, how do i ensure that the ip gotten is blocked specifically? meaning, can i specifically route ip to process? or i cant? or i shouldnt?

**Comment by chrismccord** [comment]
Please send support requests to the forums and/or slack where folks are well equipped to help you. We reserve the issue tracker for issues and active development. Thanks!

**Comment by gitmko0** [comment]
ok thx
