### ISSUE TITLE
We need to internationalize the document.

### ISSUE THREAD

**Issue by quentininwork** [phoenixframework/phoenix#4056]
There are many developers in China, but the English level of most people is not very good. I think this framework is very good. If the document is in Chinese, it must be very popular. Please consider adding Chinese support to the document.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by prodis** [comment]
https://translate.google.com/translate?hl=&sl=en&tl=zh-CN&u=https%3A%2F%2Fhexdocs.pm%2Fphoenix%2Foverview.html

**Comment by quentininwork** [comment]
@prodis Haha, I know how to do the method you mentioned, but there are many mistakes in machine translation compared with manual translation, which is not suitable for newcomers to learn.

**Comment by jeepers3327** [comment]
@quentininwork yeah this is really good idea. It would increase the adoption for the framework.

**Comment by chrismccord** [comment]
This would be a great community resource to have, but not something the Phoenix team itself is well prepared to take on. I encourage folks in the community who are interested in this to explore an external translation of the guides. Thanks!
