### ISSUE TITLE
What firewall / ssl terminator is suggested for phoenix framework?

### ISSUE THREAD

**Issue by gitmko0** [phoenixframework/phoenix#4060]
What runs in front of phoenix?

e.g. i mean for 
1. websocket
2. web accelerator
3. http3 / quic / http2 ssl terminator
4. reverse proxy
5. load balancer

in view of the soft real time / distributed nature + high numbers of connected nodes for elixir handling, what is more suitable to be placed in front of phoenix? i actually thought phoenix should be the frontend of everything until i realised how slow it is compared with varnish (for web acceleration), nginx (for ssl), openlitespeed etc BUT i'm worried the frontend is not optimum enough in terms of concurrent connection for phoenix.

so how do you guys architect phoenix framework?

**Comment by mcrumm** [comment]
We reserve the issue tracker for issues and active dev. Please send questions to slack, the elixir forum, etc. Thanks!
