### ISSUE TITLE
Phoenix 1.5.7 Javascript error when encoding channel payload

### ISSUE THREAD

**Issue by mtarnovan** [phoenixframework/phoenix#4074]
### Environment

* Elixir version (elixir -v): 1.11.1-otp-23
* Phoenix version (mix deps):  1.5.7
* NodeJS version (node -v): 10.15.3
* NPM version (npm -v): yarn 1.22.5
* Operating system: MacOS Catalina / Ubuntu 16.04

After upgrading from Phoenix 1.5.6 to 1.5.7 we're seeing Javascript errors like these:
![Screen Shot 2020-11-23 at 14 18 51](https://user-images.githubusercontent.com/4074/99968371-ba173600-2da1-11eb-91ba-7627a49bf9c1.png)
![Screen Shot 2020-11-23 at 14 20 11](https://user-images.githubusercontent.com/4074/99968631-09f5fd00-2da2-11eb-9e26-6d8562d19f4f.png)

This seems to be related to [this commit](https://github.com/phoenixframework/phoenix/commit/07b401901fc1d649f126eee6315b5eb01fa5c85c)

**Comment by chrismccord** [comment]
Are you pushing a payload? Perhaps you are not passing a payload and it's being send as `undefined`, ie `channel.push("foo")`?

**Comment by mtarnovan** [comment]
I found some code that pushed to the channel without a payload, changing that to an empty object fixes the problem. Thank you.
