### ISSUE TITLE
Small typo in Phoenix Channels hexdocs

### ISSUE THREAD

**Issue by mjftw** [phoenixframework/phoenix#4084]
### Environment

* Elixir version (elixir -v): N/A
* Phoenix version (mix deps): N/A
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: N/A

### Expected behavior

There's a small typo in the Phoenix Channels hexdocs page.
https://hexdocs.pm/phoenix/channels.html#using-token-authentication

> Step 3 - Pass the Token to the Socket Constructor and Verify
> ...
> In our JavaScript, we can use the token set previously ~when to pass the token~ when constructing the Socket:

**Comment by chrismccord** [comment]
Thanks for the report!

**Comment by mjftw** [comment]
Oops sorry, didn't see you'd closed the issue already. Feel free to ignore the PR if you've fixed this already.
