### ISSUE TITLE
Show custom bound address when server starts

### ISSUE THREAD

**Issue by AlexJuca** [phoenixframework/phoenix#4097]
### Environment

* Elixir version (elixir -v): 1.11.2 compiled with Erlang/OTP 23
* Phoenix version (mix deps): 1.5.4
* NodeJS version (node -v): v10.16.0
* NPM version (npm -v): 6.9.0
* Operating system: MacOs Big Sur 11.0.1

### Expected behavior
When running mix phx.server with the following config:
```elixir
http: [port: 4000, ip: {172, 20, 10 , 3}]
```

It is expected that Phoenix output the following to the terminal during server startup:

```bash
[info] Running DevAppWeb.Endpoint with cowboy 2.8.0 at 172.20.10.3:4000 (http)
[info] Access DevAppWeb.Endpoint at http://172.20.10.3:4000 (http)
```

### Actual behavior
Instead it outputs:
```bash
[info] Running DevAppWeb.Endpoint with cowboy 2.8.0 at 172.20.10.3:4000 (http)
[info] Access DevAppWeb.Endpoint at http://0.0.0.0:4000 (http)
```

When a user clicks on the link that is generated the browser can not access the page because the server is not bound to http:0.0.0.0:4000 but rather http:172.20.10.3:4000 as is expected.

**Comment by josevalim** [comment]
Hi @AlexJuca, can you please show your complete configuration? The access message is supposed to show the URL you have configured in your router, not the ip:port you are listening on. That's because in most setups behind proxies, the ip:port != url.

Have you set your URL to 0.0.0.0 or similar by any chance?

**Comment by AlexJuca** [comment]
Well, it's the default configuration. All I did was create a new app using mix with it's default configuration.
Afterwords I added the following configuration:

```elixir
http: [port: 4000, ip: {172, 20, 10 , 3}]
```

I did this because I was running two different phoenix api's on my local network and one needed to talk to the other, so I bound the server to that machine's address. 

when I clicked on the link generated by phoenix, my browser could not talk to the server since it probably was not bound to that server address http://0.0.0.0:4000.

**Comment by josevalim** [comment]
@AlexJuca I cannot reproduce this behaviour. When I configure the IP as above, here is what I see:

```
[info] Running DemoWeb.Endpoint with cowboy 2.8.0 at 110.42.0.212:4000 (http)
[info] Access DemoWeb.Endpoint at http://localhost:4000
```

We don't show the IP in the "Access" bit unless the url was configured to show such.

**Comment by AlexJuca** [comment]
I see. How can one configure the url to show it?

My assumption was that the "Access" IP or URL was the one I would click on to view my servers root page.

What happens when you click on your "Access" url if it's not configured?

**Comment by AlexJuca** [comment]
But I see why you closed the PR. The Access url is not meant to show the I.P at all. 
I will close this.

**Comment by josevalim** [comment]
> What happens when you click on your "Access" url if it's not configured?

Then it means you need to fix something, because those will be the URLs generated by your application. :)
