### ISSUE TITLE
using phx.gen.live ANY_CONTEXT Action actions at:utc_datetime breaks due to "action" being used internally

### ISSUE THREAD

**Issue by amattn** [phoenixframework/phoenix#4104]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.7
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

### Expected behavior

I expect to be able to use Ecto entity models named action or be warned that  "action" is a reserved word and might break things.

### Actual behavior

Due to this line:

https://github.com/phoenixframework/phoenix/blob/8efa655ddb7d95a87e75ced1951cc1349494220a/priv/templates/phx.gen.live/form_component.ex#L27

  def handle_event("save", %{"<%= schema.singular %>" => <%= schema.singular %>_params}, socket) do
    save_<%= schema.singular %>(socket, socket.assigns.action, <%= schema.singular %>_params)
  end

stuff breaks.  

The form cannot save due to    ` save_action(socket, socket.assigns.action, action_params)`

In this case, the middle of the 3 arguments, should be an atom to match against :edit or :new

However, socket.assigns.action is actually an Ecto model entity %Action{...}

The save operations fails because of "no function clause matching in HabitShowWeb.ActionLive.FormComponent.save_action/3"

Additionally, there is no visible feedback on the webpage that the save operation fails.  The console does log the failure.

**Comment by chrismccord** [comment]
We'll evaluate a PR that warns or raises, but the conflict exists at the template level for the assigns we pass to the modal/form component, including title/action/etc. Thanks!
