### ISSUE TITLE
DOCS - can't find live view or file uploads docs on the phoenix website

### ISSUE THREAD

**Issue by ankopainting** [phoenixframework/phoenix#4105]
I'm not sure where to log this ticket but from the phoenix site I can't navigate to live view or the new file uploads docs.

The live view docs themselves are very good, is there a prominent place we could link to them from?  Especially considering you can add --live when you create a phoenix project?

**Comment by chrismccord** [comment]
https://hexdocs.pm/phoenix_live_view/uploads.html

**Comment by ankopainting** [comment]
Sorry Chris, I think you misunderstand my ticket.  If I go to https://www.phoenixframework.org/ then where do I click to get to the phoenix live view docs?

If I click docs it goes to the phoenix docs, not phoenix live view docs.

If I click guides they are the guides in phoenix, not phoenix live view.

cheers,
Anko

**Comment by Gazler** [comment]
Perhaps we should include a link to LiveView here where we list the dependencies:

https://hexdocs.pm/phoenix/Phoenix.html

**Comment by dvic** [comment]
Or add at least a link to the liveview docs on this card :
![image](https://user-images.githubusercontent.com/1214337/102079521-27504100-3e0d-11eb-814f-cdad904c49cf.png)

**Comment by ankopainting** [comment]
I like the suggestions! 

I guess the high level issue is that our guides are part of specific packages as opposed to being about phoenix as a whole, so there is a disconnect.

**Comment by ankopainting** [comment]
@chrismccord is there a way we can get this re-opened?
