### ISSUE TITLE
Regression in websocket message deserialization

### ISSUE THREAD

**Issue by lukaszsamson** [phoenixframework/phoenix#4108]
### Environment

* Phoenix version (mix deps): 1.5.7

### Expected behavior

When connecting to a phoenix socket via elixir client `phoenix_gen_socket_client` the server process crashes.
```
17:16:29.235 [error] Ranch listener 'Elixir.WebqoutesWeb.Endpoint.HTTP' terminated with reason: no function clause matching 'Elixir.Phoenix.Socket.V2.JSONSerializer':decode_binary(<<"[1,1,\"some:channel\",\"phx_join\",{}]">>)
```

The regression was introduced in 1.5.7

Originally reported in https://github.com/Aircloak/phoenix_gen_socket_client/issues/54

**Comment by chrismccord** [comment]
This looks like a bug on the websocket client where it's sending the binary opcode, but a text frame. The client should be sending a text opcode for that payload. Thanks!
