### ISSUE TITLE
render/3 breaks spec definition in Phoenix 1.5

### ISSUE THREAD

**Issue by hauleth** [phoenixframework/phoenix#4110]
### Environment

* Elixir version (elixir -v): `Elixir 1.11.2 (compiled with Erlang/OTP 22)`
* Phoenix version (mix deps): `phoenix 1.5.7 (Hex package)`
* Operating system: macOS 11.1

### Expected behavior

```elixir
defmodule Foo do
  defstruct []
end

render(conn, view, %Foo{})
```

Should not throw an error as structure is `map()` which is specified by the specs of the `render/3` function.

### Actual behavior

It fails due to fact that 3rd argument to `render/3` should in fact be `Enumerable.t()` (as that is the requirement of `Map.new/1` which is used internally). It worked in previous (at least `1.4.x`) versions.

**Comment by josevalim** [comment]
The previous version accepted structs by accident. If we accept the proposed PR, this means if someone passes a RedBlackTree as argument which is backed by a struct, it would not work the same as a map. In other words, consider the arg to be Enumerable.t indeed. Thank you!
