### ISSUE TITLE
Migrating Phoenix Channels Javascript Implementation to Typescript

### ISSUE THREAD

**Issue by VictorGaiva** [phoenixframework/phoenix#4148]
The current Phoenix Channels Javascript implementation is great, however I believe I lacks in features and extensibility by not having a Strongly Typed implementation with Typescript, and not following the widely used Event Stream API pattern used by RxJS.

With this in mind I'd like to make a proposal for a new implementation. Since I believe that this change would have a mild impact in the stability of the project, following `CONTRIBUTING.md` I'm here asking for the feedback from you guys about this. 

I have a working alternative implementation of the Channel handling class, defined in `assets/js/phoenix.js`, using  [RxJS's WebSocket wrapper](https://rxjs-dev.firebaseapp.com/api/webSocket/WebSocketSubject). It is able to join, and leave channels, receive and send messages, and provides an API that follows RxJS patterns.

If the feedback is positive, I'll create a project to host the source code for this implementation and update this issue.

I'd love to hear what you have to say about it.

**Comment by chrismccord** [comment]
We have no plans for a typescript client but you are free to implement one on your own and make it available. Please note we do not use the issue tracker for proposals. Thanks!
