### ISSUE TITLE
Mix phx.gen.live generates invalid tests when a unique constraint is present

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#4156]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps): 1.5.7
* NodeJS version (node -v):
* NPM version (npm -v):
* Operating system:

### Expected behavior

All tests pass.

### Actual behavior

```
1) test Index saves new registry (PourWeb.RegistryLiveTest)
     test/pour_web/live/registry_live_test.exs:32
     ** (RuntimeError) LiveView did not redirect
     code: |> follow_redirect(conn, Routes.registry_index_path(conn, :index))
     stacktrace:
       test/pour_web/live/registry_live_test.exs:48: (test)
```

Generated with `mix phx.gen.live Registries Registry registries name:string:unique type:string`. This happens because the setup and the test both generate a registry with `@create_attrs`, which then triggers the unique constraint.

**Comment by josevalim** [comment]
@feliperenan do you want to pick this one up? :)

**Comment by josevalim** [comment]
@aaronrenner beautiful!

**Comment by a8t** [comment]
I'm also getting failing tests upon running the generator, due to conflicting HTML escaping. Is it somehow related? Otherwise I can make another issue.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/7440689/115327446-f8503000-a15c-11eb-8a09-19cb039f28a4.png">

**Comment by crova** [comment]
I see the same things as @a8t.

**Comment by feliperenan** [comment]
This issue is solved on master by this PR: https://github.com/phoenixframework/phoenix/pull/3829. Maybe close this one @josevalim? 🤔
