### ISSUE TITLE
Erlang Flag "-connect_all false" Not Working on Start

### ISSUE THREAD

**Issue by keatz55** [phoenixframework/phoenix#4157]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4
* Phoenix version (mix deps): phoenix 1.5.7 (774cd644)
* NodeJS version (node -v): v12.13.0
* NPM version (npm -v): 6.12.0
* Operating system: macOS Catalina 10.15.5

### Expected behavior

If `--erl "-connect_all false"` is configured on start, distributed erlang node connections should be non-transitive. I.e., If a node A connects to node B, and node B has a connection to node C, then node A should not try to connect to node C.

```shell
# terminal 1
iex --erl "-connect_all false" --sname app1@localhost --cookie monster -S mix phx.server

# terminal 2
iex --erl "-connect_all false" --sname app2@localhost --cookie monster -S mix phx.server
iex(app2@localhost)1> Node.connect(:app1@localhost)
true
iex(app2@localhost)2> Node.list()
[:app1@localhost]

# terminal 3
iex --erl "-connect_all false" --sname app3@localhost --cookie monster -S mix phx.server
iex(app3@localhost)1> Node.connect(:app2@localhost)
true
iex(app3@localhost)2> Node.list()                  
[:app2@localhost] # <- HERE - should return non-transitive result
```

### Actual behavior

```shell
# terminal 1
iex --erl "-connect_all false" --sname app1@localhost --cookie monster -S mix phx.server

# terminal 2
iex --erl "-connect_all false" --sname app2@localhost --cookie monster -S mix phx.server
iex(app2@localhost)1> Node.connect(:app1@localhost)
true
iex(app2@localhost)2> Node.list()
[:app1@localhost]

# terminal 3
iex --erl "-connect_all false" --sname app3@localhost --cookie monster -S mix phx.server
iex(app3@localhost)1> Node.connect(:app2@localhost)
true
iex(app3@localhost)2> Node.list()                  
[:app2@localhost, :app1@localhost] # <- HERE - returns transitive result, expected only [:app2@localhost]
```

Also worth noting that distributed erlang node connections work as expected without `-S mix phx.server`:

```shell
# terminal 1
iex --erl "-connect_all false" --sname app1@localhost --cookie monster

# terminal 2
iex --erl "-connect_all false" --sname app2@localhost --cookie monster
iex(app2@localhost)1> Node.connect(:app1@localhost)
true
iex(app2@localhost)2> Node.list()
[:app1@localhost]

# terminal 3
iex --erl "-connect_all false" --sname app3@localhost --cookie monster
iex(app3@localhost)1> Node.connect(:app2@localhost)
true
iex(app3@localhost)2> Node.list()                  
[:app2@localhost] # <- HERE - returns non-transitive result
```

For reference, here is the official Erlang documentation on `-connect_all false`:
http://erlang.org/doc/reference_manual/distributed.html#node-connections

**Comment by chrismccord** [comment]
There is nothing in particular phoenix is doing to connect nodes. Are you sure you aren't doing the connection yourself as part of your app startup (ie libcluster or similar?). Closing as this is not on the Phoenix side. Thanks!

**Comment by keatz55** [comment]
@chrismccord I appreciate the prompt response and just to add further clarity, these are freshly generated phoenix apps with zero code added. There is no libcluster or anything, just `Node.connect/1` after an iex session has started.

For reference, I've created an example repo where the following commands can be run exactly:

https://github.com/keatz55/phx_erl_connect_all_false

```shell
# Terminal 1
make compose.up # Starts apps 1-3 with `iex --erl "-connect_all false"`
make app1.iex # attaches to running app1 iex session
iex(app1@app1)1>

# Terminal 2
make app2.iex # attaches to running app2 iex session
iex(app2@app2)1> Node.connect(:app1@app1)
true
iex(app2@app2)2> Node.list()
[:app1@app1]

# Terminal 3
make app3.iex # attaches to running app3 iex session
iex(app3@app3)1> Node.connect(:app2@app2)
true
iex(app3@app3)2> Node.list()                  
[:app2@app2, :app1@app1] # <- HERE - returns transitive result, expected only [:app2@app2]
```

**Comment by chrismccord** [comment]
You'll have to explore your dependencies and see if anything is setting net_kernel options or similar. We don't touch net_kernel ourselves to start dist erl and we don't do any Node connections ourselves. The other thing to check is if `--sname` is conflicting with the erl flag. Try your connect_all false and starting net_kernel yourself with a short/long name and see with happens. `:net_kernel.start([:"primary@127.0.0.1"])`

**Comment by keatz55** [comment]
@chrismccord Thanks for the response. I'll continue exploring the dependencies to see what the root cause could be. As far as the following goes:
> The other thing to check is if --sname is conflicting with the erl flag. Try your connect_all false and starting net_kernel yourself with a short/long name and see with happens. :net_kernel.start([:"primary@127.0.0.1"])

I tried the following, but unfortunately got the same transitive response:
```shell
# Terminal 1
make compose.up # Starts apps 1-3 with `epmd -daemon && iex --erl "-connect_all false" --cookie monster -S mix phx.server`
make app1.iex # attaches to running app1 iex session
iex(1)> :net_kernel.start([:"app1@172.31.0.2"])
{:ok, #PID<0.386.0>}

# Terminal 2
make app2.iex # attaches to running app2 iex session
iex(1)> :net_kernel.start([:"app2@172.31.0.4"])
{:ok, #PID<0.386.0>}
iex(app2@172.31.0.4)2> Node.connect(:"app1@172.31.0.2")
true
iex(app2@172.31.0.4)3> Node.list
[:"app1@172.31.0.2"]

# Terminal 3
make app3.iex # attaches to running app3 iex session
iex(1)> :net_kernel.start([:"app3@172.31.0.6"])
{:ok, #PID<0.387.0>}
iex(app3@172.31.0.6)2> Node.connect(:"app1@172.31.0.2")       
true
iex(app3@172.31.0.6)3> Node.list
[:"app1@172.31.0.2", :"app2@172.31.0.4"]
```
