### ISSUE TITLE
LiveView: <audio> tag in comprehension does not update properly

### ISSUE THREAD

**Issue by hexaron** [phoenixframework/phoenix#4162]
Hi guys,

there seems to be bug, when LiveView tries to update a list which contains urls to audio files. Since this problem is a bit hard to explain, I have created a minimal working example at https://github.com/hexaron/test_live. The only change done to the default project is the "Add HomeLive" commit.

### Environment

* Elixir version (elixir -v): 1.11.0
* Phoenix version (mix deps): 1.5.7
* NodeJS version (node -v): v14.0.0
* NPM version (npm -v): 6.14.4
* Operating system: Linux 5.10 (Manjaro)

Maybe relevant:
* Browser: Chromium

### Issue

Basically I have a form with a text input which is supposed to be an mp3 audio url (bound to `audio_url`).
When submitting the form the `"add_audio_url"` event gets triggered, which prepends the new `audio_url` to a `audio_url_list`.
The template then should get updated by LiveView to display all the audios in `audio_url_list` with the `<audio>` tag:

```
# home_live.html.leex

...

<%= for audio_url <- @audio_url_list do %>
  <audio controls>
    <source src="<%= audio_url %>" type="audio/mp3">
  </audio>
  <small><%= audio_url %></small>
<% end %>
```

This works fine, when entering the first url (e.g. https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3).
However when entering another url (e.g. https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3), the second `<audio>` tag loads **exactly the same audio** (see the screenshot at https://github.com/hexaron/test_live/blob/master/Screenshot.png).
I have added ` <small><%= audio_url %></small>` to show that the actual loop works fine.

#### Using an initial audio list

After some bug chasing, I have the following to add, which describes the behavior more explicitly:
If we already assign some `audio_url`s in the `mount` of the LiveView to initialize the `audio_url_list`, then some crazy stuff is going on. I will call the audios specified in the mount the _initial audios_.

The following may be confusing, but I drew a picture of what's happening, please see https://github.com/hexaron/test_live/blob/master/Bug%20visualization.pdf (the ellipses are supposed to be the html audio player).

These initial audios will all get the correct audio, when first rendering the page. When adding a new audio, two things happen essentially:
1. The urls I print for debugging all move down as they are supposed to be and the new url appears on top.
2. However the audios (in the html players) do **not** get shifted down. They somehow stay where they were. This would leave the last item without audio and this is where the duplication of audios is happening. This last audio gets the **exactly the same audio** as the one right above it.

This shows that the issue described above is just a special case of this.
 
If this was not clear, please look at my visualization (mentioned above).

#### Even more

* This whole issue does not occur, when we do the same thing, but with images instead of audios.
* This has nothing to do with using `type="audio/mp3"`.

**Comment by chrismccord** [comment]
This sounds more like a browser issue having problems with dynamic audio children being updated. You can rule this out by giving each audio tag an explicit id, ie:

```
<%= for {audio_url, i} <- Enum.with_index(@audio_url_list) do %>
  <audio controls id="url-<%= id %>">
    <source src="<%= audio_url %>" type="audio/mp3">
  </audio>
  <small><%= audio_url %></small>
<% end %>
```

Please try that and report back. Thanks!

**Comment by hexaron** [comment]
Hi, thank you for the reply!
I tried with the id attribute, but that didn't fix the issue. When using Firefox instead of Chromium (just to be sure), the only thing that changed was the design of the audio player, i.e. the problem still persisted. The example on my Github is now updated to include the id.

**Comment by hexaron** [comment]
Ok, you were right, I managed to fix it with your suggestion!
The thing was, that in your definition with the id, the new audio (which gets prepended) will be the new 0 and thus copy the audio of the previous audio. The code that worked in the end was:
```
<%= for {audio_url, i} <- Enum.with_index(@audio_url_list) do %>
  <audio controls id="url-<%= length(@audio_url_list) - i %>">
    <source src="<%= audio_url %>" type="audio/mp3">
  </audio>
  <small><%= audio_url %></small>
<% end %>
```
Notice how the `id` is `length(@audio_url_list) - i` which turns the ids around. A better solution would obviously be to use _actual ids_ instead of this, because one might want to append instead of prepend and then this would fail. A quick workaround for anyone stumbling upon this is to use the `audio_url` as the `id`.
