### ISSUE TITLE
Copyright on website still saying 2020

### ISSUE THREAD

**Issue by thewatts** [phoenixframework/phoenix#4182]
Assuming this is not by design - the copyright on https://www.phoenixframework.org/ in the footer still says 2020.

![image](https://user-images.githubusercontent.com/1141717/105873258-e8430d00-5fc0-11eb-8cc3-82e7589808b3.png)

I tried to dig into where this is located to submit a PR, but couldn't find it (in here, or the archived https://github.com/phoenixframework/phoenix_site for a reference).

I'm sure I'm missing something, so apologies that I don't have the fix itself. Would be happy to submit a quick fix with a little help as to where I would go about changing it.

**Comment by cw789** [comment]
Copyright in my opinion / knowledge should always reflect the date of creation.

**Comment by thewatts** [comment]
@cw789 thanks for the feedback! Did some Googling to confirm:

> if website is published, the year of publication

> The copyright notice must also state the year the work was published. It has yet to be decided exactly when a website is "published" for copyright purposes, since many websites are updated daily. You should assume that any website that can be accessed has been "published" as soon as it launches, and include a copyright notice on it to reflect the original date.

source: https://www.nolo.com/legal-encyclopedia/when-do-you-need-copyright-notice-websites-and-where-do-you-place-it.html

---

Closing :)
