### ISSUE TITLE
localhost:4000 redirects me to another local route of a different project

### ISSUE THREAD

**Issue by ItzaMi** [phoenixframework/phoenix#4189]
Today when I tried to start a Phoenix project, as I went to `localhost:4000` I got redirected to `localhost:4000/en` and the page I was showed was _elixirschool's_ homepage (I worked on a PR for this repo last week).

When I do `localhost:4000/123` to deliberately get an error page and get the available routes, there´s no `/en` route to be seen (obviously). _elixirschool's_ project is not running and I even deleted it from my laptop but I still have the same issue.  
  
Thought that it could be something related with cache but happens to me on `Firefox`, `Chrome` and `Safari`.

After following [this issue](https://github.com/phoenixframework/phoenix/issues/1349), I saw that `http://127.0.0.1:4000/` could solve this situation and indeed it did but I'm not completely sure if it's something wrong on my behalf (I'm newbie to Elixir and Phoenix)

**Comment by chrismccord** [comment]
Sounds like a cached browser thing, not anything on our side. Thanks!
