### ISSUE TITLE
log: false not respected

### ISSUE THREAD

**Issue by benwilson512** [phoenixframework/phoenix#4194]
### Environment

* Elixir version (elixir -v): 1.11.1
* Phoenix version (mix deps): 1.5.7

### Expected behavior

This route should not emit logs:
```
get("/health", HealthController, :ready, log: false)
```

### Actual behavior

[info] GET /health
[info] Sent 200 in 88µs

I think there is something missing with respect to how Phoenix router options and Plug.Telemetry interact. The code here https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/logger.ex#L186 seems to think that `options` will have the router options, but this is an event emitted by `Plug.Telemetry`, not the phoenix router. Plug Telemetry only emits options set on the plug itself: https://github.com/elixir-plug/plug/blob/master/lib/plug/telemetry.ex#L72. I don't see how the router options could end up on those events.

**Comment by mcrumm** [comment]
> I think there is something missing with respect to how Phoenix router options and Plug.Telemetry interact.

@benwilson512 They do not interact. :) That is to say, `Phoenix.Logger` subscribes to `:telemetry` events executed from both `Plug.Telemetry` (assuming your event prefix is `[:phoenix, :endpoint]`) and from `Phoenix.Router`, but aside from that they are separate.

This is laid out in the [`Phoenix.Logger`](https://hexdocs.pm/phoenix/Phoenix.Logger.html#module-instrumentation) docs, though a little hard to find as it's embedded in the details of each event.

Code-wise, this means:

1. `Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: false` disables logging `[:phoenix, :endpoint, *]`
2. `get("/", Controller, :index, log: false)` disables logging `[:phoenix, :router_dispatch, *]`
3. To filter Endpoint logging by path, one needs to wrap `Plug.Telemetry` and conditionally set the log level per request.

Here's some example output - 

**Default output after `mix phx.new`:**

```sh
[info] GET /ready
[debug] Processing with YULogWeb.PageController.ready/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 779µs
```

**Router `log: :info`**
```ex
# lib/yulog_web/router.ex
get "/ready", PageController, :ready, log: :info
```

```sh
[info] GET /ready
[info] Processing with YULogWeb.PageController.ready/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 176µs
```

**Router `log: false`**

```ex
# lib/yulog_web/router.ex
get "/ready", PageController, :ready, log: false
```

```sh
[info] GET /ready
[info] Sent 200 in 126µs
```

**Endpoint `log: false`** (this is notably _not_ route-specific)
```ex
# lib/my_app_web/endpoint.ex
plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: false
```

```sh
[debug] Processing with YULogWeb.PageController.ready/2
  Parameters: %{}
  Pipelines: [:browser]
```
