### ISSUE TITLE
Code reloader temporarily changes Erlang file server CWD

### ISSUE THREAD

**Issue by hrubi** [phoenixframework/phoenix#4204]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.7
* Node.js version (node -v): v14.15.4
* NPM version (npm -v): 6.14.10
* Operating system: Gentoo

### Expected behavior

Phoenix code reloader does not change the global state of the Erlang file server.

### Actual behavior

Phoenix code reloader uses `Mix.Dep.in_dependency/2` during the recompilation of apps, see https://github.com/phoenixframework/phoenix/blob/25ef2660bbd3eedcc267236a22d957c0452eb3fa/lib/phoenix/code_reloader/server.ex#L191. This temporarily changes the global state of the Erlang file server, because it calls `Mix.Project.in_project/4`, which in turn calls `File.cd!/2`, which in turn calls  `:file.set_cwd/1`.

If there is some application code which relies on the file server CWD and it runs at the same time when the CWD is temporarily changed, it can cause an error. E.g. application tries to read some file with a path relative to the directory where it was run from.

This bug could be possibly fixed in `Mix.Project.in_project/4` or `File.cd!/2` instead, by not changing the global Erlang file server state.

**Comment by josevalim** [comment]
Compiling projects requires them to be running from the project root, as to mimic Mix, so there is nothing we can do here, unfortunately.
