### ISSUE TITLE
Phoenix Installation Issue

### ISSUE THREAD

**Issue by kaushikbiswas1984** [phoenixframework/phoenix#4208]
Hi,

 I am unable to install phoenix:

![image](https://user-images.githubusercontent.com/44670045/107870600-d7026780-6ebf-11eb-8fff-b7024de76547.png)

The install command does not show the status and I tried other ways as well like downloading the repository but phx.new task error still persists.

**Comment by sandeshsoni** [comment]
hey @kaushikbiswas1984 

its `mix archive.install hex phx_new 1.5.7`

I think you used `phx.new` over `phx_new`

**Comment by eksperimental** [comment]
> its `mix archive.install hex phx_new 1.5.7`

correct!, but Why didn't it error?

**Comment by sandeshsoni** [comment]
> > its `mix archive.install hex phx_new 1.5.7`
> 
> correct!, but Why didn't it error?

maybe because it is windows?

```
➜  ~ mix archive.install hex phx.new
Failed to fetch record for 'hexpm/phx.new' from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
** (Mix) No package with name phx.new (from: mix.exs) in registry
➜  ~
```
mac throws error message

**Comment by kaushikbiswas1984** [comment]
Maybe yes, but that's still an issue. Considering how many windows systems/user out there, it might be stumbling block for adoptability as many might still try out on windows while learning, just like me.

**Comment by josevalim** [comment]
This should be fixed on more recent OTP versions:

<img width="974" alt="Screenshot 2021-02-21 at 20 10 36" src="https://user-images.githubusercontent.com/9582/108635707-12350580-7481-11eb-87f0-efb260e9d823.png">

Thanks!
