### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by yitzackRabin** [phoenixframework/phoenix#4211]
![image](https://user-images.githubusercontent.com/49115936/108051357-d9012d80-705b-11eb-9eb0-6c867e4256a0.png)

the error is here help on update

**Comment by petermm** [comment]
hi @yitzackRabin 

something is up with your erlang install pls see:
https://elixir-lang.org/install.html
```
Ubuntu 14.04/16.04/17.04/18.04/19.04 or Debian 7/8/9/10
Add Erlang Solutions repository: wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
Run: sudo apt-get update
Install the Erlang/OTP platform and all of its applications: sudo apt-get install esl-erlang
Install Elixir: sudo apt-get install elixir
```

(note the 2.0 vs your 1.0)

I suggest using something like https://asdf-vm.com though

ps: better to post issues like this over at https://elixirforum.com another time..

**Comment by josevalim** [comment]
Usually this error happens because you have a limited Erlang installation. Some distributions break Erlang into a bunch of smaller packages, which is really not recommended, so you often have to install erlang-parser_tools or similar, or another distribution of Erlang. :)
