### ISSUE TITLE
Phoenix Static File handling leaks file descriptors

### ISSUE THREAD

**Issue by benmmurphy** [phoenixframework/phoenix#4212]
The underlying issue seems to be an erlang bug. I've raised it here: https://github.com/erlang/otp/issues/4540

I've raised it here because I've seen this issue complained about in phoenix slack and in other places and it will be useful for people to be able to find the problem in this bug tracker after it is resolved.

Note: This allows a trivial denial of service attack against phoenix apps that serve static files larger than the TCP send buffer size.

The issue can also be solved without an erlang fix by setting `active: false` on the socket before calling `file:sendfile`.

### Expected behavior

My server doesn't crash because I run out of file descriptors when serving static files.

### Actual behavior

My server crashes because it runs out of file descriptors.

**Comment by josevalim** [comment]
It has been fixed upstream, thank you so much for the report! :heart:
