### ISSUE TITLE
[:router_dispatch, :stop] telemetry event does not fire for conns that are halted

### ISSUE THREAD

**Issue by fivetanley** [phoenixframework/phoenix#4216]
### Environment

* Phoenix version: <= 1.5.8 (this is also present on the current master branch)

### Expected behavior

The `[:phoenix, :router_dispatch, :stop]` telemetry event should fire for requests that get halted by a plug. Some common reasons you might want to halt a `Plug.Conn`. For instance: Validating request parameters (checking the presence of authorization tokens, that certain headers are present) or rate limiting. Halting is the only way to stop the request from going through the rest of the pipeline, as mentioned in the [Plug docs](https://hexdocs.pm/plug/Plug.Conn.html#send_resp/1):

> Note that this function does not halt the connection, so if subsequent plugs try to send another response, it will error out. Use `halt/1` after this function if you want to halt the plug pipeline.

This can technically be worked around by using some of the `[:plug]` telemetry events but then you miss out on some of the metadata from the phoenix router and it's also seems inconsistent and harder to document/remember over time that you need to listen for events in multiple places.

The fix for this looks pretty easy and I would be happy to open a pull request for it if the framework maintainers agree it is a good way to go

 It looks like we could add the telemetry event to the `%Plug.Conn{halted: true}` match in the case `statement` in `Phoenix.Router`.

The events for successful/non-halted-through-pipeline conns are set up here: 

https://github.com/phoenixframework/phoenix/blob/92e15520541795796855233e3f72e4422c2db9f3/lib/phoenix/router.ex#L355-L357

We could copy/refactor to a method and then call the method in the halted case here:

https://github.com/phoenixframework/phoenix/blob/92e15520541795796855233e3f72e4422c2db9f3/lib/phoenix/router.ex#L347-L349

### Actual behavior

The telemetry event `[:phoenix, :router_dispatch, :stop]` is never fired if the `Plug.Conn` is halted by a plug. This plug can be either in the router, the endpoint, or the controller.

This example code can be used to reproduce the lack of events for `halt`'d connections:

```elixir
defmodule MyApp.Router do
  use Phoenix.Router

  pipeline :api do 
    plug :check_bearer_token
  end

  scope "/api/v1", MyApp.Web do
    pipe_through [:api]
    get "/posts", PostsController, :index
  end

  def check_bearer_token(conn, _opts) do
    with "Bearer " <> token <- Plug.Conn.get_req_header("Authorization"),
          :ok <- MyApp.Token.validate(token) do
        conn
    else
      :invalid_token -> Plug.Conn.send_resp(conn, 401, "Unauthorized") |> Plug.Conn.halt()
    end
end
```

And then attaching a telemetry listener:

```elixir
:ok = :telemetry.attach(
  # unique handler id
  {MyApp.Telemetry, [:phoenix, :router_dispatch, :stop]}
  [:phoenix, :router_dispatch, :stop],
  &MyApp.Telemetry.handle_event/4,
  nil
)
```

The event will never fire.

**Comment by mcrumm** [comment]
Hi @fivetanley! I'm almost certain this is just an oversight and a PR would be very welcome :)
