### ISSUE TITLE
mix phx.gen.live does not create a view file

### ISSUE THREAD

**Issue by MarkZsombor** [phoenixframework/phoenix#4236]
### Environment

* Elixir version (elixir -v): 1.11.1
* Phoenix version (mix deps): 1.5.8
* Node.js version (node -v):
* NPM version (npm -v):
* Operating system: 

### Expected behavior

According to the documentation, when you run `mix phx.gen.live Accounts User users name:string age:integer` it should create a view file at `lib/app_web/views/user_view.ex` https://github.com/phoenixframework/phoenix/blob/cfd5a6e91b0d60c5dc84ad5874506444f5d65251/lib/mix/tasks/phx.gen.live.ex#L34

### Actual behavior
The view file is not created.

My assumption is that this is an error in the documentation, as looking through the generator code and tests it does not attempt to create a view file. This has caused some confusion as the generator is not behaving has documented, nor does it make sense why such a file would be made or how it would be used.

**Comment by chrismccord** [comment]
Definitely an error in the docs. Can you send a PR? Thanks!

**Comment by MarkZsombor** [comment]
Will do

**Comment by MarkZsombor** [comment]
Closing as duplicate, Looks like this was fixed in https://github.com/phoenixframework/phoenix/pull/4193
