### ISSUE TITLE
Edit / Back links are not clear in default style

### ISSUE THREAD

**Issue by eksperimental** [phoenixframework/phoenix#4237]
### Actual behavior

![image](https://user-images.githubusercontent.com/9133420/110022027-749bca80-7cf9-11eb-92c3-597c1ab738f7.png)

The "Edit" and "Back" links look too close. They look like one word.
I think they could either be separated more, or make them look like buttons.

**Comment by TheFirstAvenger** [comment]
I have noticed the same issue and because of it, in my code, I usually add a pipe between the two to separate them. I have pushed #4242 to do this in the generators.

**Comment by eksperimental** [comment]
> I have noticed the same issue and because of it, in my code, I usually add a pipe between the two to separate them. I have pushed #4242 to do this in the generators.

Thank you for the PR @The
