### ISSUE TITLE
Copying "Try it now" codeblock from phoenixframework.org includes $ character

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [phoenixframework/phoenix#4246]
I tried finding the phoenixframeworkg.org site repo but it seems it is private (or hosted elsewehere).

### Expected behavior
Triple-clicking the try it now code sample and copying does not include `$` character

### Actual behavior

Triple-clicking the try it now code sample and copying  includes `$` character.

### Suggested fix

By using the css `before` pseudo selector the `$` can be added but will not be selected when copying.

```css
code::before {
    content: "$ ";
}
```

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥
