### ISSUE TITLE
Issues with included Milligram.css

### ISSUE THREAD

**Issue by ykurtbas** [phoenixframework/phoenix#4256]
Hi,

I had a look around and couldn't find anything related and I know this is not a framework issue but I would like to highlight the points for improvement :)

The included Milligram.css kind of does all the things you shouldn't do in a CSS file, like overriding globals and defaults.

Thus getting weird bugs during prototyping and going crazy about why it doesn't look the way it should.

The amazing button override. You can not have a simple icon button or smaller button in the application anymore without overriding a ton of button, hover, focus values yourself.

```
.button,
button,
input[type="button"],
input[type="reset"],
input[type="submit"] {
.....
.button:focus,
.button:hover,
button:focus,
button:hover,
input[type="button"]:focus,
....
.button[disabled]:focus,
.button[disabled]:hover,
button[disabled]:focus,
button[disabled]:hover,
```

For example, the following definition will prevent any reasonable mobile rendering under a flex box as table will be miniscule.

```
table {
    border-spacing: 0;
    display: block;
    overflow-x: auto;
    text-align: left;
    width: 100%;
}
```

list goes on

- Full-width labels, inputs!
- hidden legends
- only desktop version row, column setup

## Why do I mention this?

I am new to the phoenix and it is a great initiative, project, having fun learning and creating new things. 

Vendor-specific bugs and issues will actually affect the project too as it hinders the user experience.

I know people don't have to use this and it comes as a starter kit when you generate an application.

But let's please choose one with fewer issues and bigger support, maybe mini.css? or don't include anything?

ps: I hate CSS :)

**Comment by chrismccord** [comment]
Milligram is there as a tiny, unobtrusive starting point that works well with our generated HTML on making something look reasonable. You are free to replace it with your CSS libs of choice. Thanks!
