### ISSUE TITLE
mix phx.gen.schema doesn't follow the same logic as ecto.gen.migration

### ISSUE THREAD

**Issue by krainboltgreene** [phoenixframework/phoenix#4259]
As you can see here: https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phx.gen.schema.ex#L160-L165

The path is hardcoded, however strangely `mix ecto.gen.migration` actually determines location and namespace from the `ecto_repo` value. It also allows you to specify the repository!

I would love to help with this issue, because it generates quite a lot of work for me.

**Comment by josevalim** [comment]
@krainboltgreene PRs are welcome!

**Comment by krainboltgreene** [comment]
Okay, I will set aside some time tonight or this weekend to work on it. My plan currently is to proxy the work to ecto's own logic where we can do that, and where phoenix generates we'll try to match.

**Comment by chrismccord** [comment]
let us know if you'd like to revisit this! Thanks!
