### ISSUE TITLE
[DOCS]: Documentation on what is included in mix phx.new

### ISSUE THREAD

**Issue by jasonlimantoro** [phoenixframework/phoenix#4269]
For beginners, it is a bit frustrating to see random files being created without any explanation.
For example, the command `mix phx.new` gives us some opinionated setups like using Cookie store as opposed to the ETS found in `lib/{app}_web/endpoint.ex`. Another example, is that the `{app}Web` module is bootstrapped with `Plug.Conn`, which is why some magic function like `get_session` is suddenly available in `{app}Web.Router` module. (I may be wrong, but you get the point).

To date, I haven't seen other defaults it has given me nor do I have any reference to look up.
The [docs](https://hexdocs.pm/phoenix/Mix.Tasks.Phx.New.html) itself unfortunately just explains how to use it and not what it does in detail.

Anyway, I had a very great time learning this piece of framework, aside from not knowing what I get by default after running the first ever command (`mix phx.new`). 

It would be helpful to have a comprehensive documentation on what those defaults are.

**Comment by josevalim** [comment]
The guides explain those. For example:

1. the directory structure: https://hexdocs.pm/phoenix/directory_structure.html
2. the plug chapter talk about the endpoint plugs: https://hexdocs.pm/phoenix/plug.html
3. the controller: https://hexdocs.pm/phoenix/controllers.html talks about plug conn

There is always run for improvement (for example the plug guide does not talk about the plug.session default) but PRs are very welcome to address those gaps that you find! Thank you!
