### ISSUE TITLE
Phoenix Code Reloader always marks erlang (umbrella) siblings as stale

### ISSUE THREAD

**Issue by MThomassen** [phoenixframework/phoenix#4278]
### Environment

* Elixir version (elixir -v): `1.11.2`
* Phoenix version (mix deps): `1.5.8`
* Node.js version (node -v): `v10.24.0`
* NPM version (npm -v): `5.8.0`
* Operating system: `debian buster`

### Expected behavior

When starting Phoenix development server `mix phx.server`, umbrella application that includes erlang applications should sucessfully start.

### Actual behavior

Upon handling first web request, application raises:
```
** (RuntimeError) could not compile application: ${ERLANG_APP}.

You must restart your server after changing the following config or lib files:

  * ${ELIXIR_UMBRELLA_APP_PATH}/_build/dev/lib/${ERLANG_APP}/.mix/compile.lock
  * mix.exs
  * ${ELIXIR_UMBRELLA_APP_PATH}/config/dev.exs
  * ${ELIXIR_UMBRELLA_APP_PATH}/config/config.exs
  * ${ELIXIR_UMBRELLA_APP_PATH}/mix.exs
```

It seems the fucntion `Mix.Utils.extract_stale(configs, manifests)` (`server.ex:214`) erroneously detects config files as being stale

Values:
```elixir
manifests = [
  # This file doesnt exist! Instead there's `${ERLANG_APP}/.mix/compile.erlang`
  "${ELIXIR_UMBRELLA_APP_PATH}/_build/dev/lib/${ERLANG_APP}/.mix/compile.elixir"
]
configs = [
  "${ELIXIR_UMBRELLA_APP_PATH}/_build/dev/lib/${ERLANG_APP}/.mix/compile.lock",
  "${ELIXIR_UMBRELLA_APP_PATH}/apps/${ERLANG_APP}/mix.exs",
  "${ELIXIR_UMBRELLA_APP_PATH}/config/dev.exs",
  "${ELIXIR_UMBRELLA_APP_PATH}/config/config.exs",
  "${ELIXIR_UMBRELLA_APP_PATH}/mix.exs"
]
```

### Workaround

Override the `manifests` and `configs` variables in `server.ex:211`. Although this also disables valid stale checks!

```elixir
    manifests = [] #Mix.Tasks.Compile.Elixir.manifests()
    configs = [] #Mix.Project.config_files()
```

**Comment by josevalim** [comment]
My suggestion is to set [`reloadable_apps: [....]`](https://hexdocs.pm/phoenix/Phoenix.CodeReloader.html#reload!/1) for your endpoint and explicit mention the apps you want to reload.

It is hard to detect otherwise based on the .compile.elixir because maybe it is as Elixir app after all... it just was not compiled yet. Thanks for the report!
