### ISSUE TITLE
no function clause matching in Keyword.has_key?/2

### ISSUE THREAD

**Issue by conradwt** [phoenixframework/phoenix#4280]
### Environment

* Elixir version (elixir -v):  Elixir 1.11.4 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): phoenix 1.5.8 (Hex package) (mix)
* Node.js version (node -v): v14.16.0
* NPM version (npm -v): 6.14.11
* Operating system: macOS 11.2.3

### Expected behavior

**When clicking**

movie/show.html.eex
```elixir
<%= link "Write Review", to: Routes.movie_review_path(@conn, :new, @movie) %>
```

**invokes**

review_controller.ex
```elixir
  def new(conn, %{"movie_id" => movie_id}) do
    movie = Catalogs.get_movie!(movie_id)

    changeset =
      movie
      |> Ecto.build_assoc(:reviews, %Review{})

    render(conn, "new.html", movie: movie, changeset: changeset)
  end
```

catalogs.ex
```elixir
 def get_movie!(id), do: Repo.get!(Movie, id)
```

**renders**

review/new.html.eex
```
<%= render "form.html", Map.put(assigns, :action, movie_review_path(@conn, :new, @movie)) %>
```

**invokes**

review/form.html.eex
```elixir
<%= form_for @changeset, movie_review_path(@conn, @action, @movie), fn f -> %> # blows up here

...

<% end %>
```

I'm expecting that the `review/new.html.eex` would properly render in the browser.

### Actual behavior

The actual result is as follows within the browser:

![Screen Shot 2021-03-30 at 10 55 56 PM](https://user-images.githubusercontent.com/20219/113097017-1accda00-91ab-11eb-8dae-7de4c785ef2f.png)

Finally, I have reviewed the limited documentation regarding `Nested Resources` but the docs didn't go into any detail about the actual view and template code.  I'm not sure if I'm doing something wrong here or there's a potential bug within Phoenix here.

**Comment by eksperimental** [comment]
sorry, after the change you need to run `mix deps.compile phoenix`

**Comment by conradwt** [comment]
@eksperimental There's only 87 lines within my `router.ex`.  However, the code that you're referring to here is code owned by the `Phoenix` project.

**Comment by eksperimental** [comment]
> @eksperimental There's only 87 lines within my `router.ex`. However, the code that you're referring to here is code owned by the `Phoenix` project.

my bad.
`deps/lib/phoenix/rounter/helpers.ex`

**Comment by conradwt** [comment]
@eksperimental This is what I'm seeing and this is much more informative than the previous error message.

![Screen Shot 2021-03-31 at 10 16 14 PM](https://user-images.githubusercontent.com/20219/113246868-b96e3f00-926e-11eb-845d-3066efb6c302.png)

**Comment by eksperimental** [comment]
What are the values of @action and @movie when you invoke movie_review_path(@conn, @action, @movie)

I think you action is "movies/1/review" whichis wrong. and I don't now your movie_id

**Comment by conradwt** [comment]
@eksperimental The value of `movie_id` here is equal to 1 from the `params`.

**Comment by eksperimental** [comment]
print the value of those assigns I mentioned earlier. And see where they are being defined,  
I think `@action` is wrong.

**Comment by conradwt** [comment]
@eksperimental Hey, thanks for your assistance.  Anyway, I'll do some more reading to figure things out regarding Phoenix's render method.

**Comment by delameko** [comment]
Hi @conradwt,

your error is in these two parts, you're calling the route helper twice which is why you're seeing the error.

```elixir
    # review/new.html.eex
    <%= render "form.html", Map.put(assigns, :action, movie_review_path(@conn, :new, @movie)) %>

    # review/form.html.eex
    <%= form_for @changeset, movie_review_path(@conn, @action, @movie), fn f -> %> # blows up here
```

In the first line `Map.put(assigns, :action, movie_review_path(@conn, :new, @movie)` is added the review path to the @action attribute.

In the second line, you're trying to get the route again, but you're passing in the @action (which already contains the full path) into the route helper, which is where the error is coming from.  It's expecting :new (or :index, :edit, etc) but instead it's receiving '/movies/1/reviews'.

You can fix it, by only calling it once, like so:

```elixir
    # review/new.html.eex
    <%= render "form.html", Map.put(assigns, :action, Routes.movie_review_path(@conn, :new, @movie)) %>

    # review/form.html.eex
    <%= form_for @changeset, @action, fn f -> %>
```

**Comment by conradwt** [comment]
@delameko I'll definitely give this a try later this evening and thanks for the explanation here.

**Comment by Gazler** [comment]
@delameko is correct here. Please re-open this issue if there's still a problem.
