### ISSUE TITLE
Phoenix's hidden live reload iframe is breaking a footer that should be pushed down from CSS (TailwindCSS)

### ISSUE THREAD

**Issue by nickjj** [phoenixframework/phoenix#4290]
### Environment

* Elixir version (elixir -v): 1.11.4
* Phoenix version (mix deps): 1.5.8
* Node.js version (node -v): 14.15.5
* NPM version (npm -v): 6.14.11
* Operating system: Ubuntu
* TailwindCSS: 2.1.0

This issue isn't related to TailwindCSS but it's what I'm using to create this type of layout and it's reproduceable.

### Situation

This HTML layout should produce a layout where the footer is pushed down to the bottom of the screen:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= live_title_tag assigns[:page_title] || "Hello" %>
    <%= csrf_meta_tag() %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>

  </head>
  <body class="flex flex-col h-screen justify-between">
    <div class="bg-gray-700">
      <div class="max-w-screen-lg mx-auto py-3 px-3 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between flex-wrap text-white">
          <p>Nav</p>
          <p>Test</p>
        </div>
      </div>
    </div>

    <main class="max-w-screen-lg mx-auto mb-auto">
      <p class="mt-5">Main content</p>
    </main>

    <footer class="text-center mt-6 pb-6 h-10">
      <p class="text-gray-500">
        This should be pushed down to the bottom of the screen.
      </p>
    </footer>
  </body>
</html>
```

### Expected behavior

Here's a screenshot of what it should look like:

![image](https://user-images.githubusercontent.com/813219/114417152-58543e80-9b7f-11eb-9ab3-9cbc44fdf7b2.png)

*Just adding text here so you can see where the image ends.*

### Actual behavior

Here's a screenshot of what it looks like as is:

![image](https://user-images.githubusercontent.com/813219/114417067-47a3c880-9b7f-11eb-8b60-a2414d99e9fb.png)

*Just adding text here so you can see where the image ends.*

### Potential issue

It's related to the hidden iframe that Phoenix adds directly before the `</body>` which is `<iframe hidden src="/phoenix/live_reload/frame"></iframe>`.

When I delete this iframe from the source code in my browser's dev tools then the footer correctly jumps down to the bottom of the screen like it shows in the expected output screenshot.

**Comment by dbernheisel** [comment]
maybe related: https://github.com/phoenixframework/phoenix_live_reload/issues/109

**Comment by nickjj** [comment]
Seems like it could be yes.

When I set `iframe_attrs: [class: "hidden"]` it's fixed now, but it's also no longer straight forward when using the JIT compiler with TailwindCSS because it also involved adding the `config/` path to the list of paths for PurgeCSS. This seems like a non-optimal path to add to get around the issue.

I wonder if the iframe could have an inline `style="display: none;` applied to it by default which makes it hidden no matter what CSS library or tools you use?

**Comment by fertapric** [comment]
@nickjj This is another workaround:

```css
[hidden] {
  display: none !important;
}
```

**Comment by nickjj** [comment]
Good one, or maybe `iframe[hidden]` to scope it to only iframes?

Maybe this isn't the best spot to ask but what are a few use cases where you would want Phoenix's live reload iframe to be visible in the DOM? Was there a reason for it not being `display: none;` by default?

**Comment by mcrumm** [comment]
I am going to close this since solutions have been posted here and phoenixframework/phoenix_live_reload#109 and this isn't the place to discuss the merits of the current behaviour. Thanks!

**Comment by nickjj** [comment]
If anyone sees this in the future, Jose fixed the issue in the Phoenix Live Reload library. As of v1.3.1 it no longer requires an app level workaround.
