### ISSUE TITLE
414 returned for large query string

### ISSUE THREAD

**Issue by acco** [phoenixframework/phoenix#4293]
### Environment

* Elixir version (elixir -v): 1.11.3
* Phoenix version (mix deps): 1.5.8
* Operating system: macOS Big Sur 11.1

### Expected behavior

When making a `curl` request with a large query string (>10,000 bytes), the request succeeds.

### Actual behavior

Request fails with:

```
> Host: localhost:4000
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 414 Request-URI Too Long
< connection: close
< content-length: 0
<
* Closing connection 0
```

I thought this may have been happening in `Plug.Parsers.fetch_query_params/x` but (a) that function has a default limit of 1M bytes and (b) I can prove that function is never called.

I made [this example repo](https://github.com/acco/hit414/blob/master/lib/hit414_web/endpoint.ex#L2-L20) where the first plug called in `Endpoint` prints a "HERE" and halts. Alas, the response is the same (414) and there is no indication that this plug is invoked. Therefore, I have reason to suspect the 414 is coming higher up in the chain.

**Comment by josevalim** [comment]
You also want to configure Cowboy. For example, in your endpoint, do:

    http: [protocol_options: [max_request_line_length: 10_000]]

Keep in mind though browsers will trim large query strings too. You should consider using POST whenever possible.

**Comment by josevalim** [comment]
I have updated the docs for Plug to mention so, thanks!

**Comment by acco** [comment]
Thanks a million @josevalim !
