### ISSUE TITLE
Error while `npm install`  inside the assets folder.

### ISSUE THREAD

**Issue by SyedMuzamilM** [phoenixframework/phoenix#4313]
### Environment

* Elixir version (1.11.4):
* Phoenix version (1.5.8):
* Node.js version (15.12.0):
* NPM version (7.6.3):
* Operating system: Windows 10

### Expected behavior

Should behave normally

### Actual behavior
`
npm ERR! code 1
npm ERR! path F:\projects_startup\goop\assets\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe F:\projects_startup\goop\assets\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= 
--libsass_cflags= --libsass_ldflags= --libsass_library=       
npm ERR! Building the projects 
in this solution one at a time. To enable parallel build, please add the "/m" switch.        
npm ERR! Build started 5/4/2021 2:10:58 AM.
npm ERR! Project "F:\projects_startup\goop\assets\node_modules\node-sass\build\binding.sln" on node 1 (default targets).    
npm ERR! ValidateSolutionConfiguration:
npm ERR!   Building solution configuration "Release|x64".     
npm ERR! MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [F:\projects_startup\goop\assets\node_modules\node-sass\build\binding.sln]
npm ERR! Done Building Project 
"F:\projects_startup\goop\assets\node_modules\node-sass\build\binding.sln" (default targets) 
-- FAILED.
npm ERR! 
npm ERR! Build FAILED.
npm ERR!
npm ERR! "F:\projects_startup\goop\assets\node_modules\node-sass\build\binding.sln" (default 
target) (1) ->
npm ERR! (_src_\libsass target) ->
npm ERR!   MSBUILD : error MSB3428: Could not load the Visual 
C++ component "VCBuild.exe". To fix this, 1) install the .NET 
Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 
3) add the location of the component to the system path if it 
is installed elsewhere.  [F:\projects_startup\goop\assets\node_modules\node-sass\build\binding.sln]
npm ERR! 
npm ERR!     0 Warning(s)      
npm ERR!     1 Error(s)        
npm ERR!
npm ERR! Time Elapsed 00:00:01.45
npm ERR! gyp info it worked if 
it ends with ok
npm ERR! gyp verb cli [        
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',npm ERR! gyp verb cli   'F:\\projects_startup\\goop\\assets\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]        
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.12.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python 
checking for Python executable 
"C:Program" in the PATH        
npm ERR! gyp verb `which` failed Error: not found: C:Program  
npm ERR! gyp verb `which` failed     at getNotFoundError (F:\projects_startup\goop\assets\node_modules\which\which.js:13:12)npm ERR! gyp verb `which` failed     at F (F:\projects_startup\goop\assets\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (F:\projects_startup\goop\assets\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at F:\projects_startup\goop\assets\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at F:\projects_startup\goop\assets\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at F:\projects_startup\goop\assets\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21)
npm ERR! gyp verb `which` failed  C:Program Error: not found: 
C:Program
npm ERR! gyp verb `which` failed     at getNotFoundError (F:\projects_startup\goop\assets\node_modules\which\which.js:13:12)npm ERR! gyp verb `which` failed     at F (F:\projects_startup\goop\assets\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (F:\projects_startup\goop\assets\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at F:\projects_startup\goop\assets\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at F:\projects_startup\goop\assets\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at F:\projects_startup\goop\assets\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "C:Program". checking python 
launcher
npm ERR! gyp verb check python 
launcher python executable found: "C:\\Users\\Syed Muzamil\\.windows-build-tools\\python27\\python.exe"
npm ERR! gyp verb check python 
version `C:\Users\Syed Muzamil\.windows-build-tools\python27\python.exe -c "import sys; print "2.7.15
npm ERR! gyp verb check python 
version .%s.%s" % sys.version_info[:3];"` returned: %j        
npm ERR! gyp verb get node dir 
no --target version specified, 
falling back to host node version: 15.12.0
npm ERR! gyp verb command install [ '15.12.0' ]
npm ERR! gyp verb install input version string "15.12.0"      
npm ERR! gyp verb install installing version: 15.12.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed       
npm ERR! gyp verb install version is already installed, need to check "installVersion"       
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir 
target node version installed: 
15.12.0
npm ERR! gyp verb build dir attempting to create "build" dir: 
F:\projects_startup\goop\assets\node_modules\node-sass\build  
npm ERR! gyp verb build dir "build" dir needed to be created? 
F:\projects_startup\goop\assets\node_modules\node-sass\build  
npm ERR! gyp verb Not using VS2017: Could not use PowerShell to find VS2017
npm ERR! gyp verb build/config.gypi creating config file      
npm ERR! gyp verb build/config.gypi writing out config file: F:\projects_startup\goop\assets\node_modules\node-sass\build\config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: F:\projects_startup\goop\assets\node_modules\node-sass\config.gypi    
npm ERR! gyp verb common.gypi checking for gypi file: F:\projects_startup\goop\assets\node_modules\node-sass\common.gypi    
npm ERR! gyp verb gyp gyp format was not specified; forcing "msvs"
npm ERR! gyp info spawn C:\Users\Syed Muzamil\.windows-build-tools\python27\python.exe       
npm ERR! gyp info spawn args [ 
npm ERR! gyp info spawn args   
'F:\\projects_startup\\goop\\assets\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   
'binding.gyp',
npm ERR! gyp info spawn args   
'-f',
npm ERR! gyp info spawn args   
'msvs',
npm ERR! gyp info spawn args   
'-G',
npm ERR! gyp info spawn args   
'msvs_version=auto',
npm ERR! gyp info spawn args   
'-I',
npm ERR! gyp info spawn args   
'F:\\projects_startup\\goop\\assets\\node_modules\\node-sass\\build\\config.gypi',
npm ERR! gyp info spawn args   
'-I',
npm ERR! gyp info spawn args   
'F:\\projects_startup\\goop\\assets\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   
'-I',
npm ERR! gyp info spawn args   
'C:\\Users\\Syed Muzamil\\.node-gyp\\15.12.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   
'-Dlibrary=shared_library',    
npm ERR! gyp info spawn args   
'-Dvisibility=default',        
npm ERR! gyp info spawn args   
'-Dnode_root_dir=C:\\Users\\Syed Muzamil\\.node-gyp\\15.12.0',npm ERR! gyp info spawn args   
'-Dnode_gyp_dir=F:\\projects_startup\\goop\\assets\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   
'-Dnode_lib_file=C:\\Users\\Syed Muzamil\\.node-gyp\\15.12.0\\<(target_arch)\\node.lib',     
npm ERR! gyp info spawn args   
'-Dmodule_root_dir=F:\\projects_startup\\goop\\assets\\node_modules\\node-sass',
npm ERR! gyp info spawn args   
'-Dnode_engine=v8',
npm ERR! gyp info spawn args   
'--depth=.',
npm ERR! gyp info spawn args   
'--no-parallel',
npm ERR! gyp info spawn args   
'--generator-output',
npm ERR! gyp info spawn args   
'F:\\projects_startup\\goop\\assets\\node_modules\\node-sass\\build',
npm ERR! gyp info spawn args   
'-Goutput_dir=.'
npm ERR! gyp info spawn args ] 
npm ERR! Warning: unrecognized 
setting VCCLCompilerTool/MultiProcessorCompilation
npm ERR! Warning: unrecognized 
setting VCCLCompilerTool/MultiProcessorCompilation
npm ERR! Warning: unrecognized 
setting VCCLCompilerTool/MultiProcessorCompilation
npm ERR! Warning: unrecognized 
setting VCCLCompilerTool/MultiProcessorCompilation
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture 
x64
npm ERR! gyp verb node dev dir 
C:\Users\Syed Muzamil\.node-gyp\15.12.0
npm ERR! gyp verb found first Solution file build/binding.sln 
npm ERR! gyp verb could not find "msbuild.exe" in PATH - finding location in registry        
npm ERR! gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   
'build/binding.sln',
npm ERR! gyp info spawn args   
'/nologo',
npm ERR! gyp info spawn args   
'/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (F:\projects_startup\goop\assets\node_modules\node-gyp\lib\build.js:262:23)    
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\projects_startup\\goop\\assets\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd F:\projects_startup\goop\assets\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.12.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Syed Muzamil\AppData\Local\npm-cache\_logs\2021-05-03T20_41_11_380Z-debug.log
`

**Comment by chrismccord** [comment]
This appears to be an issue strictly on the node side with your system. Unfortunately, we won't be able to provide much assistance here, but please try the forums and elixir slack. Thanks!

**Comment by alfredbaudisch** [comment]
I also fought with this exact same issue for hours, until I managed to come up with a step by step solution, as per my writeup: https://github.com/nodejs/node-gyp/issues/2467#issuecomment-902003727

**Comment by cclauss** [comment]
> npm ERR! gyp info using node-gyp@3.8.0

Is out of date.

**Comment by alfredbaudisch** [comment]
> This appears to be an issue strictly on the node side with your system. Unfortunately, we won't be able to provide much assistance here, but please try the forums and elixir slack. Thanks!

Hey @chrismccord, I can see the `npm install` as described here kind of recurring in Phoenix (https://github.com/phoenixframework/phoenix/issues/4308, https://github.com/phoenixframework/phoenix/issues/4358, https://github.com/phoenixframework/phoenix/issues/4359, https://github.com/phoenixframework/phoenix/issues/4390, https://github.com/phoenixframework/phoenix/issues/4403), and it seems it's due to the usage of `node-sass` in which in turns lead to the usage of an old version of `node-gyp`, which is causing all those issues.

Considering that `node-sass` is [deprecated](https://sass-lang.com/blog/libsass-is-deprecated) (also: https://github.com/nodejs/node-gyp/issues/2467#issuecomment-902012983), are there any plans to update that in Phoenix?
