### ISSUE TITLE
Unable to reproduce documented functionality of double calling plug with forward

### ISSUE THREAD

**Issue by hassanshaikley** [phoenixframework/phoenix#4314]
I'm working on a blog post about splitting up a router in Phoenix. And I came across documented functionality that I wasn't able to reproduce.

Docs say 

```
  However, we don't advise forwarding to another endpoint.
  The reason is that plugs defined by your app and the forwarded
  endpoint would be invoked twice, which may lead to errors.
```

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/router.ex#L946-L948

But I haven't been able to achieve that functionality. I've tried a couple of things and I can't seem to get a plug to get invoked twice using forward.

### Environment

Elixir 1.11.2 (compiled with Erlang/OTP 23)
phoenix 1.5.8
mac 10.15.7

### Expected behavior

I want a plug to get called twice. I have tried endpoint plugs, controller plugs, router plugs and I used match and forward.

### Actual behavior

I tried to mess with the pipelines and everything but no matter what I did `forward` behaved the same as `match`.

Also I would share my work but it's a bit messy and I tried moving a lot of things around. So it might be difficult to share. If you really feel it is valuable I could whip something up, I am sure.

**Comment by chrismccord** [comment]
The documentation is saying that your endpoints typically are constructed stand-alone, with plugs to parse headers, handle uploads, configure the session, etc, but if you forward from one endpoint to another, you'd have two session plugs called, but the second call would conflict with the first.
