### ISSUE TITLE
"Mix Tasks" section of Phoenix->GUIDES document has some typo

### ISSUE THREAD

**Issue by jim168chang** [phoenixframework/phoenix#4333]
### Environment
* Phoenix version (mix deps): 1.5.9

### Document typo
There are 2 "lib/hello.ex" in https://hexdocs.pm/phoenix/mix_tasks.html#ecto-tasks, and I think they should be "lib/hello/application.ex".

### Actual behavior
$ mix ecto.gen.repo -r OurCustom.Repo
* creating lib/our_custom
* creating lib/our_custom/repo.ex
* updating config/config.exs
Don't forget to add your new repo to your supervision tree
(typically in **lib/hello/application.ex**):

    {OurCustom.Repo, []}

And to add it to the list of Ecto repositories in your
configuration files (so Ecto tasks work as expected):

    config :hello,
      ecto_repos: [OurCustom.Repo]

$

**Comment by Gazler** [comment]
You are correct, a PR is welcome!

**Comment by jim168chang** [comment]
Thanks Gazler. I never did PR before, but I'll try later.

**Comment by hi-rustin** [comment]
I think it's already done in https://github.com/phoenixframework/phoenix/pull/4317
