### ISSUE TITLE
What is the expected behavior of `websocket: [compress: true]` configuration for socket ?

### ISSUE THREAD

**Issue by phtrivier** [phoenixframework/phoenix#4345]
### Environment

* Elixir version (elixir -v): 1.10.4
* Phoenix version (mix deps): 1.5.0
* Node.js version (node -v): 12.18
* NPM version (npm -v): 6.14.15
* Operating system: linux x86_64

### Expected behavior

I want to compress the _messages_ that are sent over a phoenix channels (the actual content of the message is JSON that can be big in some situations, but is pretty repetitive, so simple text-compression should help.) 

Following the configuration in https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3-websocket-configuration, I set up my Endpoint and Socket like this: 

```
defmodule Xxxx.Endpoint do

  use Phoenix.Endpoint, otp_app: :xxx

  socket("/foo", XXXX.Channels.FooSocket, websocket: [compress: true])
```

When frontend code connects to the webscoket using the `phoenix` npm module, using either modern Firefox or Chrome, the request is done with the following header: 

```
Sec-WebSocket-Extensions | permessage-deflate
```

And the server responds with 

```
sec-websocket-extensions | permessage-deflate
```

I was expecting the messages to be much smaller, and the measured traffic while receiving messages to be much smaller.

### Actual behavior

However, when measuring the size of messages in Chrome / FF Browser (in the Network / WS tab),  it seems that the size of the messages is the same.

But the documentation is not very clear about what `compress: true` is supposed to do : 

* does it only compress the _initial_ response to the `/websocket` request ? 
* or is it supposed to compress each frame's content ? 

(In my case, it's possible that even when compressing my frame's content, the difference is not obvious...)

**Comment by chrismccord** [comment]
The compression is per frame, but I can't speak to what specific payload reductions you will see. As a sanity check, make sure you are on latest `plug_cowboy`, as I believe cowboy at some point changed their compression options and plug_cowboy was updated to remap `compress` to work as expected. Thanks!
