### ISSUE TITLE
Documentation for mix phx.new includes reference to invalid option "--no-context"

### ISSUE THREAD

**Issue by abrookewood** [phoenixframework/phoenix#4353]
### Environment

* Elixir version (elixir -v): Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]. Elixir 1.12.1 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.5.9 (Hex package) (mix)
* Node.js version (node -v): v14.8.0
* NPM version (npm -v): 6.14.7
* Operating system: Win 10 Pro

### Expected behavior

As written on hex docs (https://hexdocs.pm/phoenix/Mix.Tasks.Phx.New.html#module-options), running the following command should create a new Phoenix application without Ecto, webpack and context files:
mix phx.new my_app --install --no-ecto --no-webpack --no-context

### Actual behavior

Running that command results in an error: "** (Mix) Invalid option: --no-context"
Running that command without the option " --no-context" succeeds.

**Comment by chrismccord** [comment]
The documentation is saying that if you forgo `--no-ecto`, then the html generator tasks will require you to pass `--no-context` *to those tasks*, so it is not related to phx.new.

>   When passing the `--no-ecto` flag, Phoenix generators such as
  `phx.gen.html`, `phx.gen.json`, `phx.gen.live`, and `phx.gen.context`
  may no longer work as expected as they generate context files that rely
  on Ecto for the database access. In those cases, you can pass the
  `--no-context` flag to generate most of the HTML and JSON files
  but skip the context, allowing you to fill in the blanks as desired.


If you think it could be clearer. Please send a PR. Thanks!
