### ISSUE TITLE
phoenix --live

### ISSUE THREAD

**Issue by OlekRia** [phoenixframework/phoenix#4354]
Hi, 
I am using phx 1.5.9 version.

Repro steps:
1. mix phx.new hello --live
2. mix deps.get
3. cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode development
4. mix deps.compile
5. mix ecto.create

Everything goes OK and finally I am trying to run a server:

iex -S mix phx.server

And I have a following error:

```
17:06  iex -S mix phx.server
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Compiling 13 files (.ex)
Generated hello app
[info] Running HelloWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (http)
[error] Could not start Node.js watcher because script "/Users/userA/sources/_ELIXIR/hello/hello/assets/node_modules/webpack/bin/webpack.js" does not exist. Your Phoenix application is still running, however assets won't be compiled. You may fix this by running "npm install" inside the "assets" directory.
[info] Access HelloWeb.Endpoint at http://localhost:4000
Interactive Elixir (1.12.1) - press Ctrl+C to exit (type h() ENTER for help)
```

If I run `npm install` inside of /assets folder I have a timeout error: "reify:lodash: timing reifyNode:node_modules/es-abstract"

Guys, help needed!

**Comment by chrismccord** [comment]
Please try elixir slack or elixir forum for support requests. The timeout issue sounds like a problem on your side or the package manager side, but nothing for us to be able to fix on our end. Thanks!

**Comment by OlekRia** [comment]
The problem is not on my side. But at your side and the side of your documentation.
I resolved the issue downgrading the version of nodejs. But I guess it should be mentioned somewhere in your documentation if you really care about Elixir popularity.
