### ISSUE TITLE
Deletion on auto-generated CRUD items executes :show function instead of :delete

### ISSUE THREAD

**Issue by vitorlimadev** [phoenixframework/phoenix#4362]
### Environment

* Elixir version: Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): phoenix 1.5.9
* Operating system: PopOS! 21.04

## The Issue
Reproducing this issue is very simple.

I created a fresh Phoenix project with:
`mix phx.new --umbrella --no-webpack  --no-gettext --no-dashboard --binary-id site`

After that, I ran the html generator: 
`mix phx.gen.html Posts Post posts title:string body:text created_at:naive_datetime`

When I try to delete a post, I'm redirected to the show page of the post. I have changed nothing in the generated code.

I've looked into the code of the template itself, but couldn't see what was wrong. A temporary solution would be to change the delete route in the router to a get or post route, but with the `Routes.post_path(@conn, :delete, post), method: :delete, data: [confirm: "Are you sure?"]`, the original code, it just doesn't work

**Comment by chrismccord** [comment]
The delete links use phoenix_html to send the http method which you excluded with —no-webpack so you need to include the js on the page on your own.  Thanks!

**Comment by vitorlimadev** [comment]
Thank you @chrismccord!
