### ISSUE TITLE
Router.Helpers slowdown when upgrading from Phoenix 1.5.8 to 1.5.9

### ISSUE THREAD

**Issue by tomekowal** [phoenixframework/phoenix#4365]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 23 [erts-11.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.11.4 (compiled with Erlang/OTP 23)
```
* Phoenix version (mix deps): 1.5.9
* Node.js version (node -v): v8.11.2
* NPM version (npm -v): 5.6.0
* Operating system: Ubuntu 20.04 (Heroku-20 Stack)

### Expected behavior

Works as fast as on 1.5.8

### Actual behavior

Performance of Router.Helpers drops.

### Details

In the app we use, we noticed timeouts after upgrading from Phoenix 1.5.8 to 1.5.9. We isolated the issue to calls to `Router.Helpers` E.g. an index site displaying around 500 items loaded in ~4s before the upgrade and after the upgrade it loads in ~8s.

While debugging the issue, we tried changing `Routes.some_path(@conn, @model)` to `Routes.some_path(@conn, @model.id)` and that made it go back to the previous speed.

We've checked that we've consolidated protocols because we suspected `Phoenix.Param` but `Protocol.consolidated?(Phoenix.Param)` returns `true`.

Unfortunately, not all developers were able to reproduce it locally. It is possible to reproduce it on Heroku. We will try to pinpoint a specific commit between 1.5.8 and 1.5.9

**Comment by josevalim** [comment]
Ping. Please let us know if you have more info!

**Comment by tomekowal** [comment]
Sorry for the long silence. In production, we replaced some `@entity` with `@entity.id` and moved on. I got sick before the weekend and didn't have time to look at it.
I'll try to get back with more info after next weekend.

**Comment by josevalim** [comment]
Cool! There were no changes on Elixir code between 1.5.8 and 1.5.9, so I am suspecting there is something else at play here. If some of your coworkers do not have an issue, try moving to the same Elixir+Erlang/OTP as them and see if it still exists.

**Comment by tomekowal** [comment]
We do use the same versions. Locally installed via asdf version manager and on Heroku via buildpack which makes the mystery even harder to untangle.

**Comment by tomekowal** [comment]
We were not able to replicate the slowdowns on an empty project and decided to work around the issue by calling `entinty.id` in templates.
