### ISSUE TITLE
Reverse proxy library needs a to way exclude init and call from Plug

### ISSUE THREAD

**Issue by edescourtis** [phoenixframework/phoenix#4367]
I built a library to dispatch requests in my umbrella. However, when trying to extend PhoenixEndpoint I cannot override init and call from my library `defoverride` is only supported by the target module, not my library which is using `__using__`.

Could we add an exclude parameter to skip including plug callbacks in the `__using__` macro?

I am more than happy to provide a PR if we can decide on a parameter.

https://github.com/phoenixframework/phoenix/blob/5d4265e106abe2a654d1aa6f32d92f89fc50347a/lib/phoenix/endpoint.ex#L610

**Comment by josevalim** [comment]
Apologies but I am not quite sure what is being requested. Can you please provide more information on the changes you need (or even a sample PR if that's not too much work)? Thanks!

**Comment by josevalim** [comment]
Closing this for now. Please reply if you have more info. Thanks.
