### ISSUE TITLE
after migrating to esbuild newly generated app with LV couldn't find topbar

### ISSUE THREAD

**Issue by tank-bohr** [phoenixframework/phoenix#4380]
Steps to reproduce

1. generate an app with `phx.new my_app --live`
2. Follow instructions in the console
    - `cd my_app`
    - `mix ecto.create`
    - `iex -S mix phx.server` 
3. Got the output

```
Interactive Elixir (1.12.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>  > js/app.js:22:19: error: Could not resolve "topbar" (mark it as external to exclude it from the bundle)
    22 │ import topbar from "topbar"
       ╵                    ~~~~~~~~

1 error
[watch] build finished, watching for changes...
```

### Environment

* Elixir version (elixir -v): `Elixir 1.12.2 (compiled with Erlang/OTP 22) on Erlang/OTP 24 [erts-12.0.3]` 
* Phoenix version (mix deps): `phoenix 1.6.0-dev (https://github.com/phoenixframework/phoenix.git) locked at d467c88`
* Node.js version (node -v): `v14.17.3`
* Operating system: `Darwin 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64 i386`

### Expected behavior

no JS error `js/app.js:22:19: error: Could not resolve "topbar" (mark it as external to exclude it from the bundle)`

### Actual behavior

There is a JS error `js/app.js:22:19: error: Could not resolve "topbar" (mark it as external to exclude it from the bundle)`

**Comment by Cervajz** [comment]
The same issue still persists in freshly generated umbrella apps, I tried to fixed it in: https://github.com/phoenixframework/phoenix/pull/4386
