### ISSUE TITLE
Windows terminal show not readable words.

### ISSUE THREAD

**Issue by cnmade** [phoenixframework/phoenix#4384]
```
[info] Sent 200 in 0碌s
```
![image](https://user-images.githubusercontent.com/278153/126581813-631c526c-535d-46a3-b708-333d35f7b19f.png)

I am try to run phoenix hello world .

But i see the  terminal print `0碌s` , what does it means.

**Comment by cnmade** [comment]
Ok, i got the point. the Windows terminal not using UTF-8 by default. it using GBK encoding for Chinese.

So we should switch to utf-8 first. then we can type like this
```
chcp 65001 
```
Then it work normal

![image](https://user-images.githubusercontent.com/278153/126582116-fc786f58-ed43-4f7f-b9c4-d8993a6620bb.png)

**Comment by josevalim** [comment]
Correct. Both JavaScript and Elixir tooling will use Unicode, so the terminal needs to be enabled to do so. Thanks! :)
