### ISSUE TITLE
Elixir version requirements diverging between HexDocs and mix.exs

### ISSUE THREAD

**Issue by adrianomitre** [phoenixframework/phoenix#4385]
##### For Phoenix 1.5.9
* "Elixir 1.6 or later" on hexdocs: [Installation — Phoenix v1.5.9](https://hexdocs.pm/phoenix/1.5.9/installation.html#elixir-1-6-or-later)
* `@elixir_requirement "~> 1.7"` on [mix.exs for v1.5.9](https://github.com/phoenixframework/phoenix/blob/v1.5.9/mix.exs#L9)

##### For master/upcoming Phoenix 1.6.0
* "Elixir 1.12 or later" on [Installation — Phoenix (HEAD of master as of now)](https://github.com/phoenixframework/phoenix/blob/04466484d30019c1bf4a45f24519730d02f26600/guides/introduction/installation.md#elixir-112-or-later)
* `@elixir_requirement "~> 1.9"` on [mix.exs on HEAD of master as of now](https://github.com/phoenixframework/phoenix/blob/04466484d30019c1bf4a45f24519730d02f26600/mix.exs#L10)

Is this a case of multiple sources of truth getting out of sync?

**Comment by adrianomitre** [comment]
https://github.com/phoenixframework/phoenix/pull/4346 indicates that Elixir 1.12 is required only for the [installer tests](https://github.com/phoenixframework/phoenix/blob/c030fb01276b806e62a6b1467c4dc57bd4f60d86/Earthfile#L18).

Should [installation.md](https://github.com/phoenixframework/phoenix/blob/master/guides/introduction/installation.md) mention the installer requirement? Or the "although" in "Although often the installer is ahead of Phoenix itself." comment in [mix.exs](https://github.com/phoenixframework/phoenix/blob/master/mix.exs#L8) means the opposite?

**Comment by chrismccord** [comment]
We require newer elixir's for `phx.new`, but maintain older compatibility for existing installs. Thanks!

**Comment by adrianomitre** [comment]
> We require newer elixir's for `phx.new`, but maintain older compatibility for existing installs. Thanks!

For Phoenix 1.5.9 it seems to be inverted: 1.6+ on the docs and 1.7+ on mix.exs.

What are you thoughts on clarifying this duality on the docs?
