### ISSUE TITLE
Something wrong with the way Subject Alternative Name is assigned with mix phx.gen.cert

### ISSUE THREAD

**Issue by joshchernoff** [phoenixframework/phoenix#4387]
When dealing with wildcard certs locally running `mix phx.gen.cert --name "*.foo.bar"` does not work for OSX I belive due to the way it's generating the Subject Alternative Name

IE:

```
openssl req -new -x509 -nodes -sha1 -days 3650 -key host.key > host.crt \
-subj "/CN=*.foo.bar" -reqexts SAN -extensions SAN \
-config <(cat /usr/local/etc/openssl/openssl.cnf \
<(printf '[SAN]\nsubjectAltName=DNS:*.foo.bar"))
```

will work on osx when signing a local wildcard cert.

<img width="508" alt="__elixir_group_dev" src="https://user-images.githubusercontent.com/961877/126878690-16599ef2-8523-47ca-897d-08b3b004c7ad.png">

<img width="410" alt="Connection_is_secure_and_https___foo_elixir_group_dev_4001" src="https://user-images.githubusercontent.com/961877/126878710-baf62cb8-645f-4978-baa8-076634b6edec.png">

But as already stated when only using mix command the SAN I belive is misconfigured though it does show in the crt file. 
<img width="507" alt="__elixir_group_dev" src="https://user-images.githubusercontent.com/961877/126878871-4aa7fff7-f002-432a-b40b-32776828eb28.png">

<img width="658" alt="Privacy_error" src="https://user-images.githubusercontent.com/961877/126878908-2ead3976-b965-4427-9c61-33e2c9c02b78.png">

Look at the cert from firefox it shows the subject alt name is still localhost
<img width="928" alt="Certificate_for___elixir_group_dev" src="https://user-images.githubusercontent.com/961877/126882970-5a9c69aa-5be4-496b-b43b-130cab839562.png">

**Comment by voltone** [comment]
The `--name` argument controls the contents of the Subject's Common Name field. The hostname(s) for inclusion in the SAN extension are taken the unnamed argument(s) to the Mix task. So you want:

`mix phx.gen.cert "*.foo.bar"`

**Comment by josevalim** [comment]
Closing per the above. :)
