### ISSUE TITLE
Broadcasts are not intercepted during testing

### ISSUE THREAD

**Issue by Awlexus** [phoenixframework/phoenix#4398]
I defined a channel where I intercept broadcast
```elixir
  intercept ["intercept_out"]

  def handle_out("intercept_out", _msg, socket) do
    IO.puts("#{socket.id} has intercepted the message")
    {:noreply, socket}
  end
```
Then wrote the following test, which should fail at multiple points
```elixir
  test "intercepts broadcast" do
    this = self()

    socket = create_socket("Main")

    spawn_link(fn ->
      create_socket("Other")
      send(this, :ready)
      assert_broadcast("intercept_out", %{intercept: true})
      send(this, :received)
    end)

    assert_receive(:ready)
    Phoenix.Channel.broadcast(socket, "intercept_out", %{intercept: true})
    assert_broadcast("intercept_out", %{intercept: true})
    assert_receive(:received)
  end

  defp create_socket(id) do
    {:ok, _, socket} =
      UserSocket
      |> socket(id, %{})
      |> subscribe_and_join("room:welcome")

    assert socket.assigns.joined_room?

    socket
  end
```
However, this test passes with the following output
```bash
$ mix test test/channel_test.exs
main has intercepted the message
other has intercepted the message
.
```

I made [this repo](https://github.com/Awlexus/broadcast_test) where this bug can be reproducted.

### Environment

* Elixir version:
```
Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Elixir 1.11.4 (compiled with Erlang/OTP 23)
```
* Phoenix version:
```
phoenix 1.5.9 (Hex package) (mix)
```

### Expected behavior
This test should fail at multiple points, because the broadcast are intercepted

### Actual behavior
The test doest not fail, and the broadcast is received by every socket

**Comment by chrismccord** [comment]
The test process subscribes to the topic along with your channel process. Only your channel process is intercepting, so the test is correctly passing because it also receives the broadcast. Thanks!
