### ISSUE TITLE
How to know the reason of socket connection failure?

### ISSUE THREAD

**Issue by nallwhy** [phoenixframework/phoenix#4414]
I want to make an app that make user logged out when the token of user is expired.

```elixir
defmodule MyApp.UserSocket do
  use Phoenix.Socket

  ## Channels
  ..

  @impl true
  def connect(%{"token" => token}, socket, _connect_info) do
    case verify_token(token) do
      {:ok, _} -> {:ok, socket}
      :error -> :error
    else
  end

  ..
end
```

But the web client can't know the reason of socket connection failure.
For example, `onError` hook of `socket` returns the same error whether the reason of the socket connection failure is 'unstable internet connection'  or 'already expired token' or others.

```js
socket.onError((e) => console.log(e))
socket.connect()
```

I think, if `Phoenix.Socket.connect/3` can return `{:error, message}` and `onError` hook of `socket` can show that message, it would be better to handle the failure of socket connection.

**Comment by josevalim** [comment]
Unfortunately no, because the browser doesn’t report it. It is not a Phoenix limitation, it is just not supported at the browser level. There are previous issues you can look at for discussions.
