### ISSUE TITLE
Replace gettext with Cldr

### ISSUE THREAD

**Issue by benkeil** [phoenixframework/phoenix#4416]
Gettext is no longer contemporary, it has a lack of features and any other framework uses [ICU message format](https://unicode-org.github.io/icu/userguide/format_parse/messages/).
It is time to do this in Phoenix to. On the site of the module are more examples of why get text is bad.

https://github.com/elixir-cldr/cldr_messages

### Expected behavior

If you create a new project with `phx.new` `cldr` is the default localization framework.

### Actual behavior

If you create a new project with `phx.new` `gettext` is the default localization framework.

**Comment by chrismccord** [comment]
Closing as this is not an actual issue. Per the issue template we don’t take feature requests on the issues tracker. Thanks!
