### ISSUE TITLE
Should we update .gitignore from new project template to skip tools produced assets in priv/static ?

### ISSUE THREAD

**Issue by ybod** [phoenixframework/phoenix#4422]
* Elixir version 1.12.2:
* Phoenix version 1.6 (master):

by default `.gitignore` in the new project excludes only `/priv/static/assets` dir

```
# Ignore assets that are produced by build tools.
/priv/static/assets/
```

which results in bunch of the files generated by `mix assets.deploy` being included in the commit changes

![image](https://user-images.githubusercontent.com/14310587/130366933-e099e29c-b33f-4435-af88-6cc4a8d20585.png)

maybe we can update default `.gitignore` to make more "selective" exclusion like

```
# Ignore assets that are produced by build tools.
/priv/static/*
!/priv/static/images/

!/priv/static/favicon.ico
!/priv/static/robots.txt

/priv/static/images/*
!/priv/static/images/phoenix.png
```

to exclude all files generated by tools from `static`?

![image](https://user-images.githubusercontent.com/14310587/130367082-ca62e4ab-6179-4ef5-ad8f-598a14afda9f.png)

I'm not a FE guy that much so maybe I've came up with non existing problem though...

**Comment by josevalim** [comment]
Some projects add those files as part of their build, so it is up to them. Note you can use `mix phx.digest.clean --all` to remove them.

**Comment by josevalim** [comment]
The --all flag is available in master.
