### ISSUE TITLE
Test mode recompilation time increased significantly after upgrading to 1.5.10

### ISSUE THREAD

**Issue by jonleighton** [phoenixframework/phoenix#4423]
### Environment

* Elixir version (elixir -v): 1.11.3
* Phoenix version (mix deps): 1.5.11
* Node.js version (node -v): N/A
* Operating system: Linux

---

In our application, we have a plug called `CheckRole` that is used for user authorisation.

We use the plug in some pipelines defined in `lib/my_app_web/router.ex`, as well as in numerous controllers via the `plug` macro.

After upgrading from 1.5.9 to 1.5.11, I noticed that changing a module in `lib/my_app/` would result lots of controllers getting recompiled too. Running this command:

```
$ MIX_ENV=test mix xref graph --sink lib/my_app/context.ex --label compile
```

Would result in lots of lines like this:

```
lib/my_app_web/controllers/my_controller.ex
└── lib/my_app_web/plugs/check_role.ex (compile)
```

The problem does not happen with `MIX_ENV=dev`.

After lots of head-scratching, I used `git bisect` to find that the problem had been introduced with the upgrade.

I reviewed the changes, and found https://github.com/phoenixframework/phoenix/pull/4394 which changes the `plug` macro, so I assume it is responsible.

I tried adding this:

```
config :phoenix, :plug_init_mode, :runtime
```

To `config/test.exs`. That solved the problem.

However, it doesn't appear to be a framework default when generating a fresh app with `mix phx.new`.

I'm not sure what the right solution is. Perhaps this config option should be a default for the test env as well as dev?

**Comment by jonleighton** [comment]
cc @wojtekmach

**Comment by wojtekmach** [comment]
@jonleighton done in #4395 :D

**Comment by jonleighton** [comment]
Ah cool. I wonder if there is a way we can make this more obvious for people upgrading? I lost quite a bit of time trying to figure it out. OTOH I don't know how common it is for apps to be affected by this change :shrug:

**Comment by wojtekmach** [comment]
Would a changelog entry have helped? Do you have any other ideas?

**Comment by josevalim** [comment]
@jonleighton this was a bug fix. We were accidentally hiding some compile time dependencies when we should not. I will add the CHANGELOG entry. :)

**Comment by jonleighton** [comment]
Thanks both. Yeah, I think I would have spotted a changelog entry, so that will help. Cheers :slightly_smiling_face:
