### ISSUE TITLE
(UndefinedFunctionError) function :crypto.hmac/3 is undefined or private: Compatibility with erlang 24

### ISSUE THREAD

**Issue by ankitkalia1195** [phoenixframework/phoenix#4428]
The issue occurs with erlang 24 and using the version of `plug_crypto` `1.2.1` or  older. Erlang 24 has deprecated `hmac` function http://erlang.org/documentation/doc-12.0-rc3/doc/general_info/removed.html. 

`plug_crypto` updated to support the new `crypto` api in https://github.com/elixir-plug/plug_crypto/pull/20/files and version `1.2.2`. But the current mix.exs specifies the dependency as 

```
   {:plug_crypto, "~> 1.1.2 or ~> 1.2"},
``` 

This will cause the error mentioned if using `erlang 24` and `plug_crypto < 1.2.2`. So maybe we can permanently upgrade `plug_crypto` to `1.2.2`.

### Environment

* Elixir version (elixir -v):
1.11.4

* Phoenix version (mix deps):
1.5.10

* Erlang Version
24

* Operating system:
Mac

### Expected behavior
We should not receive the error

### Actual behavior
We recieve the error (UndefinedFunctionError) function :crypto.hmac/3 is undefined or private

**Comment by josevalim** [comment]
Existing projects will need to explicitly call `mix deps.update plug_crypto` but new projects will definitely pick the latest. We can enforce more strict requirements too. Good call.
