### ISSUE TITLE
logout redirects to root of domain instead of root of app

### ISSUE THREAD

**Issue by starkeepers** [phoenixframework/phoenix#4441]
Elixir 1.12.0 , phoenix 1.6.0-rc.0 , Ubuntu 20.04.1

When using phx.gen.auth and setting a url path in a config, such as

   `url: [host: "example.com", path: "/a/b", port: 80],`

successfully logging in, and then clicking logout, users get redirected to `example.com/` instead of `example.com/a/b/`

**Comment by cmaggard** [comment]
Line 84 in a freshly-generated auth controller module (`lib/<project>_web/controllers/user_auth.ex`) has a redirect to a particular path on logout:

` |> redirect(to: "/")`

Perhaps try modifying that?

**Comment by starkeepers** [comment]
Of course (I've already done that in my own app), but that would not fix the real issue. Rephrasing: when the phoenix url is given a path "prefix" in the config, phoenix generates all its urls prefixed with those path segments. The new logout functionality violates that behaviour. As far as I can tell, it should automatically add the path prefix to its redirect.

**Comment by theMarinac** [comment]
The behavior you want (routing relative to the root of scope) is possible if you use `Router.some_path()`, if you give a static path like `to: "/"` it will go to the root.  Try something like this
```elixir
scope "/a/b",  ProjectWeb do
  pipe_through :browser
  
  get "/", PageController,  :index
end
```
```elixir
# Goes to domain root
|> redirect(to: "/")
# Goes to /a/b
|> redirect(to: Router.page_path(conn, :index))
```

**Comment by starkeepers** [comment]
Thanks for you input! The reason I opened an issue about this rather than just silently fixing it in my app, is to find a generic solution shipped by default in `phx.gen.auth`. I was hoping that there exists some way to achieve this independent of which controller and route one has (eg. my app has no PageController, and the `url: [path: "/a/b"]` config is independent of any route/controller). But since PageController is shipped by default, and since the `"/" -> index` route is also shipped by default, your `redirect(to: Router.page_path(conn, :index))` solution seems like a good default for `phx.gen.auth`.

**Comment by josevalim** [comment]
Yes, the root of the app is a reasonable default but I expect people to change it. We can't assume page_path exists because it is really application specific but feel free to tweak it. :)
