### ISSUE TITLE
Use Application.compile_env on all compile time config

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#4451]
Phoenix v1.7 can depend on Elixir v1.10 which means we can use Application.compile_env/3. Therefore, for all compile time configuration Phoenix uses on the endpoint, Phoenix should explicitly mark it as such. For example, for `debug_errors`, we should do:

    debug_errors? = Application.compile_env(otp_app, [__MODULE__, :debug_errors], false)

The benefit of doing this is that, if the user now configures debug errors at runtime.exs instead of config/config.exs, we will let them know the value changed at runtime while it is used at compile time.

Over the years, we removed most of the compile time configuration in Phoenix, but the ones that have stayed should be handled as above.

**Comment by escobera** [comment]
Hey @josevalim 

Seems like these are the compile time configs for the Phoenix Endpoint

https://github.com/phoenixframework/phoenix/blob/510061e24bdd1b53a5ca1ca82cfbd27a3863eda1/lib/phoenix/endpoint/supervisor.ex#L201-L204

Those are the ones that are intended to be marked as `compile_env`?

**Comment by josevalim** [comment]
Yes!

**Comment by josevalim** [comment]
Closing in favor of PR!
