### ISSUE TITLE
`MyAppWeb.Router.__routes__/0` not returning a list of `Phoenix.Router.Route` structs.

### ISSUE THREAD

**Issue by jbcaprell** [phoenixframework/phoenix#4456]
### Environment

* Elixir: `1.12.2-otp-24`
* Phoenix: `1.6.0-rc.0`
* macOS: `1.15.7`

### Expected behavior

In an application dependent upon Phoenix 1.5.12, `MyAppWeb.Router.__routes__/0` would return a list of `Phoenix.Router.Route` structs, something like:
```
[
  %Phoenix.Router.Route{
    assigns: %{},
    helper: "page",
    host: nil,
    kind: :match,
    line: 22,
    metadata: %{log: :debug},
    path: "/hello",
    pipe_through: [:api],
    plug: MyAppWeb.Controller.Page,
    plug_opts: :index,
    private: %{},
    trailing_slash?: false,
    verb: :get
  }
]
```

… for each route defined in a given `Phoenix` router…

### Actual behavior

… whereas in an application dependent upon Phoenix 1.6.0-rc.0, the function now appears to return a list of maps, as in the shape of:
```
[
  %{
    helper: "page",
    metadata: %{log: :debug},
    path: "/hello",
    plug: MyAppWeb.Controller.Page,
    plug_opts: :index,
    verb: :get
  }
]
```

… and I’m not familiar enough with the development of `Phoenix` to know if this intended, but it *smelled* like a regression, anyway!

**Comment by josevalim** [comment]
`__routes__` is not a public API, so we are fine with this change. Thanks for checking!

**Comment by dabaer** [comment]
Are there plans for a public API that exposes the available routes? I also use this private API in lieu of re-specifying every route in my application that is already in my `router.ex`, for access control.

Or perhaps, is there already an alternative way to do this?

**Comment by jbcaprell** [comment]
> Are there plans for a public API that exposes the available routes? I also use this private API in lieu of re-specifying every route in my application that is already in my `router.ex`, for access control.
> 
> Or perhaps, is there already an alternative way to do this?

[In v1.6.0-rc.0](https://hexdocs.pm/phoenix/1.6.0-rc.0/Phoenix.Router.html#routes/1), `Phoenix.Router.routes/1` takes a given `router` as its argument, and then calls `router.__routes__/0`.

**Comment by dabaer** [comment]
Oh, perfect! Very glad there's a public API now.
