### ISSUE TITLE
Use structured logging in `Phoenix.Logger`

### ISSUE THREAD

**Issue by hauleth** [phoenixframework/phoenix#4464]
If #4451 will be accepted then in addition to that we can change `Phoenix.Logger` to use structured logging instead of unstructured strings. This should help future developers to implement better JSON logging or other features in addition to the string logs.

**Comment by josevalim** [comment]
All of the log events from Phoenix comes from telemetry, so if you want structured logging, you can disable Phoenix builtin logs, hook your own telemetry and emit the desired structured logs.

**Comment by josevalim** [comment]
You don't have to reimplement it over and over again, it can easily be a phoenix_structured_logger package maintained by the community. :) We can make it easier to not attach our Logger if desired.
