### ISSUE TITLE
`secret_key_base`, `signing_salt` in version control considered harmful

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [phoenixframework/phoenix#4465]
Howdy Phoenix!

I was in the middle of writing a tutorial about implementing OAuth and session persistence in a Phoenix application, when I noticed something a little ... silly, I think is the right word for it.

I won't beat around the bush, as this issue ticket's title has already gotten down to brass tacks: `config/config.exs` and `/lib/app_web/endpoint.ex` are _terrible_ places to make the default homes for `AppWeb.Endpoint`'s `:secret_key_base` and `:signing_salt`! There's all kinds of opportunity for these keys to unwittingly enter the codebase, and having it be in there as early as the very first `git commit`. I didn't even realize I had committed `secret_key_base` to my own repo until I'd already made 30 commits on `main`!

I think the simplest way to go about fixing this issue is to migrate the secret values into `/config/dev.secret.exs`. Here's how I've implemented it in my own project:

```elixir
# /config/config.exs
import Config

env = config_env()

...

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{env}.exs"

with secret_config <- "#{env}.secret.exs",
  true <- File.exists?("#{__DIR__}/#{secret_config}"),
  do: import_config(secret_config)
```

Then, in `.gitignore`:

```ignore
...
# anything with `.secret` as an extension
*.secret.*
*.secret
...
```

The ignore rule used to be `/config/*.secret.exs`, but then I thought, why limit the scope of an extension I anticipate _only_ using for files I want to keep out of version control?

---

I don't know how important this ranks on the Phoenix team's priorities, but it just feels like an easy thing to correct that'll have reasonable payoff in the short and long-term. Not saying that any other framework is the thing Elixir should strive to become, but it's a strong enough security concern that Rails generates a `/config/master.key` inside of new projects, and immediately adds it to the project's `.gitignore`. It seems reasonable to have similar defaults within new Phoenix apps. Plus, since Elixir releases only contain compiled .beam files, `{env}.secret.exs` config files come with a much greater degree of security, as their source code is fundamentally never needed for an app after the build phase.

Anyway, that's all I got this time. Phoenix 1.6.0 is pretty spiffy so far! I'd already split out Sass's behavior from Webpack in 1.5, and am so happy to finally have an uncomplicated asset pipeline with it and esbuild.

**Comment by josevalim** [comment]
In production you are required to pass a `SECRET_KEY_BASE` as an environment variable. The other values are only used for dev/test:

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_single/config/runtime.exs#L10-L15

We could force SECRET_KEY_BASE to be always set as env var but I don't see how it would provide any benefit and it may harm the getting started experience. The salt, on the other hand, is not harmful if exposed. The big deal is really the secret key base (which is covered).

**Comment by josevalim** [comment]
I also sent a PR #4468 to ensure no one will accidentally fallback on config/config.exs due to misconfiguration.

**Comment by thepeoplesbourgeois** [comment]
Thank you for making that change. I know your time is valuable, and that my tickets probably trend closer to "obnoxious" than "optimizing", but I appreciate that you've always been willing to entertain the dialog, even if just to teach me something about the language, framework, and environment that I [probably could've learned from just a little more time reading the manual](https://elixirforum.com/t/elixir-v1-12-0-rc-0-released/38667/31).
