### ISSUE TITLE
Renaming live view with .html.eex extension to html.leex is not detected automatically

### ISSUE THREAD

**Issue by juanazam** [phoenixframework/phoenix#4480]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [dtrace]

Elixir 1.12.2 (compiled with Erlang/OTP 22)

* Phoenix version (mix deps): "1.5.12"

* Operating system: "OS X 11.5.2"

Hello!

For whoever will take time to read this from the phoenix project, thanks so much for all your hard work, it's really appreciated. 

### Steps to reproduce

Create new live with .html.eex template (by mistake), Phoenix will complain returning:

```
expected MyApp.ExampleLive to return a %Phoenix.LiveView.Rendered{} struct
Ensure your render function uses ~L, or your eex template uses the .leex extension.
```
Which is correct, but after updating the file's extension to `.leex` the change is not detected unless other files are modified.

### Expected behavior

File extension detection is detected and app can be reloaded successfully.

### Actual behavior

Change is not detected which results in confusion.

**Comment by josevalim** [comment]
Great find! This was a bug in Elixir and it has been fixed in master!

**Comment by juanazam** [comment]
Thanks so much for everything you do @josevalim, we really appreciate all the effort you do for this community!
