### ISSUE TITLE
Allow MFArgs for on_mount hooks

### ISSUE THREAD

**Issue by mcrumm** [phoenixframework/phoenix#4488]
Right now we have:

```elixir
on_mount MyHook

on_mount {MyHook, :on_mount}
```

...but we should allow extra args, for example:

```elixir
on_mount {MyHook, :mount_with_args, [:foo, :bar]}
```

which would invoke `MyHook.mount_with_args/5`:

```elixir
def MyHook do

  # Lifecycle callback w/ additional args
  def mount_with_args(params, session, socket, :foo, :bar)
    # ...
    {:cont, socket}
  end

end
```

To do so, we need to update both the `LiveView.on_mount/1` macro and the on_mount option on `LiveView.Router.live_session/3`.

**Comment by chrismccord** [comment]
If you passed a keyword list with Crumm's proposal, it would just work with your code example :)

**Comment by mcrumm** [comment]
Closing in favor of phoenixframework/phoenix_live_view#1630 🙈

**Comment by schrockwell** [comment]
> If you passed a keyword list with Crumm's proposal, it would just work with your code example :)

@chrismccord I thought it would have to be

```elixir
on_mount {MyHook, :mount_with_args, [[one: :two, three: :four]]}
```

in that case?

I guess it depends if `on_mount` just blindly does an `apply` with the args, or if it checks for a keyword list first.

**Comment by mcrumm** [comment]
@schrockwell there is more discussion happening on the LiveView issue I linked above
