### ISSUE TITLE
Assets generated in folder which is not in .gitignore

### ISSUE THREAD

**Issue by ihabunek** [phoenixframework/phoenix#4505]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.12.1 (compiled with Erlang/OTP 24)
```
* Phoenix version (mix deps):

```
* phoenix 1.6.0 (Hex package) (mix)
* phoenix_ecto 4.4.0 (Hex package) (mix)
* phoenix_html 3.0.4 (Hex package) (mix)
* phoenix_live_dashboard 0.5.2 (Hex package) (mix)
* phoenix_live_reload 1.3.3 (Hex package) (mix)
* phoenix_live_view 0.16.4 (Hex package) (mix)
* phoenix_pubsub 2.0.0 (Hex package) (mix)
* phoenix_view 1.0.0 (Hex package) (mix)
```

* Operating system:

Linux/Debian

### Expected behavior

Using a fresh project generated by `mix phx.new test`.

When running `mix assets.deploy`, as a part of [creating a release](https://hexdocs.pm/phoenix/releases.html), assets should be generated in a folder which is listed in .gitignore, so that the generated assets don't get committed.

### Actual behavior
 
`mix assets.deploy` calls `mix phx.digest` which generates assets in `priv/static` which is not listed in .gitignore. Example generated files:

```
priv/static/favicon-a8ca4e3a2bb8fea46a9ee9e102e7d3eb.ico
priv/static/images/phoenix-5bd99a0d17dd41bc9d9bf6840abcc089.png
priv/static/robots-067185ba27a5d9139b10a759679045bf.txt
priv/static/robots-067185ba27a5d9139b10a759679045bf.txt.gz
priv/static/robots.txt.gz
```

In contrast, esbuild generates the css and js in `priv/static/assets` which is in .gitignore, as desired.

I'll look for a fix, but since I'm new to phoenix internals, not sure how to make it work for both dev and prod environments.

**Comment by cw789** [comment]
You can run `mix phx.digest.clean --all` to get rid again of the digest files.

It's mentioned here:
https://hexdocs.pm/phoenix/deployment.html#compiling-your-application-assets

Background:
Generating digest files is mostly part of a remote deployment process (e.g. within CI). But there are projects which do git add pre build assets and digest files on purpose. So it is not jet default gitignored.

**Comment by josevalim** [comment]
Thanks @cw789, you got it! :)
