### ISSUE TITLE
Phoenix.js `undefined is not an object`

### ISSUE THREAD

**Issue by jonstuebe** [phoenixframework/phoenix#4534]
### Environment

- Phoenix.js Version: "1.6"` 
- Platform: `react-native`

### Expected behavior

When an app is backgrounded the socket should disconnect and then reconnect when the app is brought back into the foreground.

### Actual behavior

When the app is brought back into the foreground after being backgrounded I'm getting this error:

<img src="https://user-images.githubusercontent.com/156722/136289741-cb09533a-764f-4c47-81c2-80b28e0edf3e.jpeg" width="400" alt="undefined is not an object (evaluating 'this.reconnectTimer.reset')" />

I dug around a bit but didn't see anything obvious. Any ideas?

**Comment by josevalim** [comment]
New version released.
