### ISSUE TITLE
Phoenix.js TypeError: undefined is not a constructor

### ISSUE THREAD

**Issue by chrisalmeida** [phoenixframework/phoenix#4537]
### Environment

* Node version:  v15.14.0
* Phoenix.js versions: 1.5.13 and 1.6
* React Native Version: 0.66.0
* React Native Template: [Typescript](https://github.com/react-native-community/react-native-template-typescript)
* Operating system: OSX Big Sur 11.5.2 (M1 Chip)

### Expected behavior
Phoenix.js exports should be available in React Native

### Actual behavior
Phoenix.js exports are undefined in React Native. This seems like a similar issue [4534](https://github.com/phoenixframework/phoenix/issues/4534) but I tried downgrading my phoenix js version to 1.5.13 without any luck.

```js
// App.tsx

import {Socket} from 'phoenix'

new Socket('ws://localhost:4000/socket', {})
```

```
TypeError: undefined is not a constructor (evaluating 'new (_$$_REQUIRE(_dependencyMap[7], "phoenix").Socket)('ws://localhost:4000/socket', {})')
```

**Comment by mcrumm** [comment]
Hi @chrisalmeida! Are you able to try this against the latest `master`? We are pretty sure we have solved it, but we would love to know if we have not before we cut a new release :)

**Comment by mcrumm** [comment]
Thanks for the confirmation! There should be a point release out Very Soon

**Comment by chrisalmeida** [comment]
Awesome, much appreciated!
