### ISSUE TITLE
Route _url helpers ignore the route scope's host setting

### ISSUE THREAD

**Issue by kreba** [phoenixframework/phoenix#4540]
### Environment

* Elixir version (elixir -v):  `1.12.3`
* Phoenix version (mix deps): `1.6.2`
* Operating system: `Ubuntu 20.04.3 LTS`

The issue has been around for a while now. At least for about a year.

### Expected behavior

When I define a route in `router.ex` like so:
    
    scope "/", MyAppWeb, host: "app.myapp.local" do
      pipe_through :browser
      get "/about", PageController, :about
    end

Then I want the helper function `Routes.page_url(@conn, :about)` to return this URL:

    http://app.myapp.local:4000/about

### Actual behavior

It generates a URL that uses the host provided in the endpoint configuration:

    http://localhost:4000/about

### Reproducing the issue

We created a repo to illustrate the issue:

[https://gitlab.com/kreba/multihost_routes](https://gitlab.com/kreba/multihost_routes)

(That repo also illustrates a separate but possibly related issue with LiveView's `live_patch`, which we will report to the LiveView Github repo.)

**Comment by josevalim** [comment]
Closing this as VerifiedRoutes are likely to replace the helpers and they composite differently.
