### ISSUE TITLE
Outdated instructions in README for generating phonenix.js

### ISSUE THREAD

**Issue by eksperimental** [phoenixframework/phoenix#4573]
```
Building phoenix.js

$ cd assets
$ npm install
$ npm run watch
```
After the switch to ESbuild, there is no longer a "watch" task

**Comment by NewMountain** [comment]
@eksperimental Hopefully [PR #4580](https://github.com/phoenixframework/phoenix/pull/4580), clears it up.

Thank you and the entire Phoenix community for the amazing work.

**Comment by eksperimental** [comment]
Awesome @NewMountain
