### ISSUE TITLE
Account enumaration possible through timing attacks of email delivery in phx.gen.auth

### ISSUE THREAD

**Issue by christophweegen** [phoenixframework/phoenix#4591]
In the current implementation of the controller action in `phx.gen.auth` which send emails, there's a possible vulnerability to timing attacks depending on the implementation of the email delivery. Emails which don't exist will return a faster response of the request. 

For example in `user_reset_password_controller.ex`:

```elixir
def create(conn, %{"user" => %{"email" => email}}) do
   # timing attack depending on the execution time of this block
    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_reset_password_instructions(
        user,
        &Routes.user_reset_password_url(conn, :edit, &1)
      )
    end

    # In order to prevent user enumeration attacks, regardless of the outcome, show an impartial success/error message.
    conn
    |> put_flash(
      :info,
      "If your email is in our system, you will receive instructions to reset your password shortly."
    )
    |> redirect(to: "/")
  end
``` 
The return value of email delivery won't be considered in all affected controllers either way as far as I've seen, so it would maybe be better to wrap those lines in a `Task.async` block or similar to not block and return immediately?

**Comment by josevalim** [comment]
The default implementation is also vulnerable to email enumeration when validating the uniqueness of the registration form. If we really want to restrict the enumeration attacks, then there will always be an impact on usability. So what we have done so far is to use a more generic messaging, that supports the more restrict cases, but the specialization is really there for developers to make. We could as well improve the error message to make it clear if the email is found, and perhaps we should.
