### ISSUE TITLE
Docs Links not working

### ISSUE THREAD

**Issue by khanakia** [phoenixframework/phoenix#4592]
Here are the online docs link not working

1. https://phoenixframework.readme.io/docs/installation 
  Up and Running - https://www.phoenixframework.org/docs/up-and-running (404 Not Found)

2. https://phoenixframework.readme.io/docs/resources
    Programming Phoenix (print and ebook) - https://pragprog.com/book/phoenix/programming-phoenix (NOT FOUND)

**Comment by khanakia** [comment]
I can see those are OLD docs but any newbie who is learning elixir can get confused easily. So maybe should add some message on the Header to let the users know this is OLD docs and you should go to the hex docs http://hexdocs.pm/phoenix/

**Comment by chrismccord** [comment]
Unfortunately the readme app is many years old. I will see about disabling the content there. Thanks!
