### ISSUE TITLE
Substring matching of logger parameter filtering

### ISSUE THREAD

**Issue by nicnilov** [phoenixframework/phoenix#4602]
### Environment

* Elixir version (elixir -v): Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.2
* Operating system: macOS Catalina

### Expected behavior

Parameters which contain no secrets should not be filtered from the logs even if they happen to have a filter word as part of the name.

### Actual behavior

We currently have a small issue of a request param named `password_reset` being masked in the logs because it contains the `password` substring. In our system such a request carries some user info, but not the password itself (it sends a link), so the masking is not helpful.

[The code in question is here](https://github.com/phoenixframework/phoenix/blob/178ce1a2344515e9145599970313fcc190d4b881/lib/phoenix/logger.ex#L58), and [this comment](https://github.com/ma2gedev/phoenix/commit/c7d00fe186c7e22f82c7195b7083668e06ae8cc3#r8275918) suggest using a substring match instead of a full match in param names. I wonder, was there a specific reason for such choice?

Why not be more explicit about the params to mask? The config might have to either specify them individually, or with the help of wildcards, or as a regex instead of a string literal.

**Comment by chrismccord** [comment]
> Why not be more explicit about the params to mask?

We'd rather be more broad than less when it comes to leaking params in logs. I don't see this particular case as an issue, and you could explicitly log values as needed. Thanks!
