### ISSUE TITLE
Naming of Pages, Components, Hooks and Plugs

### ISSUE THREAD

**Issue by margusp2heathmont** [phoenixframework/phoenix#4603]
Hello!

Our team loves Phoenix and LiveViews! Thank you to all the authors! :) 

I have question about namings of modules:
https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html 
https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Router.html
https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html
https://hexdocs.pm/phoenix/plug.html

If we look at the documentation, then namings are a bit inconsistent:
```
live "/articles", ArticleLive.Index, :index
live "/thermostat", ThermostatLive
plug HelloWeb.Router
plug HelloWeb.Plugs.Locale, "en"
<.live_component module={HeroComponent} id="hero" content={@content} />
on_mount {MyAppWeb.SomeHook, :admin}
live_session :default, on_mount: MyAppWeb.InitAssigns do
``` 

If to look different projects, namings might differ even more.

``` 
defmodule LivebookWeb.UserPlug do
defmodule Phoenix.LiveDashboard.OSMonPage do
``` 

So, the question to @josevalim and other authors is: How arbitary can the naming of modules can be? Does it make sense for a company, to construct rules, that all follow, and how much these rules can differ from what we can see in documentation?

Let us say, that within some company, where are hundreds developers, would it make sense to make rules as follows, so that it is easier to organize and orient in code:
```
live "/articles", MyAppWeb.Pages.ArticlesPage
plug MyAppWeb.Plugs.Auth
live_session :default, on_mount: MyAppWeb.Hooks.InitAssigns
alias MyAppWeb.Components.Button
```

Notice 1, we would like to keep Page as postfix, because there might be, that for ArticlesPage there are subcomponents, that only belong to that page:
```
my_app_web/pages/articles_page/article_thumbnail.ex
```

But sometimes namespace into module:
```
my_app_web/pages/auth/login_page.ex
```

Notice 2, because we use Surface, then our markup looks much prettier without Component postfix.
```
<FormComponent changeset={@user_changeset}>
  <FieldComponent name={:email}>
    <TextInputComponent />
    <ErrorTagComponent />
  </FieldComponent>
</FormComponent>
```
vs
```
<Form changeset={@user_changeset}>
  <Field name={:email}>
    <TextInput />
    <ErrorTag />
  </Field>
</Form>
```

**Comment by josevalim** [comment]
The best way to get a sense of our conventions is to run `mix phx.gen.html` and `mix phx.gen.live`. Those have a predefined structure, even if such is not apparent in the documentation.  Also, we prefer to have suffixes, such as `UserPlug` instead `Plugs.User`. But overall there are no restrictions, you can call it whatever you want!
