### ISSUE TITLE
Default root.html Has No Favicon

### ISSUE THREAD

**Issue by Miserlou** [phoenixframework/phoenix#4604]
This is a tiny, tiny little niggle, feel free to ignore.

The default root.html created by `phx.new` doesn't include a favicon. As a result, I keep losing the tab in my tab bar, and since I'm making a multi-user application, there are lots of them, and they all appear as a big blank area.

I understand not wanting to serve static assets out of the box, but it could use a b64 string instead, ex.,

```html
<link id="favicon" rel="shortcut icon" type="image/png" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABoklEQVQ4ja3Sv2uTURTG8fwjDbg7KU6OuohuDR0ERbFScJAqpdkEqQZLB61F42hLXWwpGgeVVokYiVJCEaJFQYlSDVZ96X3f+/66ufd8HSrIS0qw1gee8Xw4cE6OHSb3XwDne5jXzzHLS7gfX7cHmLevUKf24BePoPr7UAO7iO5cQZxDRP5uA9Osbw4X8pvt7yMsFwnLoySPZnpCOQBxDnV89x/gd6O7V4mmL5PUKth2i7RWIX22gHRMFgDwz+zPDIc3RginzqMnhggnz6LHB4nKRZLHs6TLi91AcGEAVcgTjBwiGD5Acu8WIkKnWcesVHHKw7x4gGk8RZKoG0ir86hCHtOsI0mMvniUtFbBaR+zUiUsF0lfPiSaHSdtPEGszQIiQjx3DV06gQs2cN46/vBB1OBe9Ngxktp9gtHDxHOTmHcNdOkkndZq9pFsu0V4e4xopkQ0fQn7/Qv20yoSazof3+B+thHnsGsfcLHGed+6P9GurxFOncM/vQ89MUS8cBP7+X3vM24VEUFEcMojnr+OCza2B2SwJMK2W/8O9MqOgV9JXqvwReE1ngAAAABJRU5ErkJggg==">
```

which will put a little 16x16 version of the Phoenix logo. Just a thought!

**Comment by Miserlou** [comment]
Or, slightly smaller, with a bird emoji SVG:

```html
<link id="favicon" rel="shortcut icon" href="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2016%2016'%3E%3Ctext%20x='0'%20y='14'%3E🐦%3C/text%3E%3C/svg%3E" type="image/svg+xml" />
```

**Comment by josevalim** [comment]
We don't plan to include one by default, as this is really app specific, but you can easily address it in your app. :) Thanks!
