### ISSUE TITLE
esbuild fails to import Alpinejs

### ISSUE THREAD

**Issue by pyladune** [phoenixframework/phoenix#4607]
When esbuild tries to compile app.js, it fails on

> js/app.js:20:16: error: Expected ";" but found "from"
    20 │ import "Alpine" from "alpinejs";

<!--

### Environment

esbuild : 0.13.14
alipnejs : 3.5.1
* Elixir version (elixir -v): 1.12
* Phoenix version (mix deps): 1.6.2
* Operating system: fedora 34

**Comment by chrismccord** [comment]
Please see this commit and referenced issue https://github.com/phoenixframework/phoenix/commit/e57d396d38ac3da4a32b6484a24bd7bab2b5bea5

**Comment by pyladune** [comment]
Did already that before to post the issue, removed _build and node_modules. But issue remains
