### ISSUE TITLE
Phoenix.js socket disconnect on a disconnected/connecting socket

### ISSUE THREAD

**Issue by pvthuyen** [phoenixframework/phoenix#4616]
### Environment
Phoenix.JS version: 1.2.1
### Expected behavior
When a disconnect is invoked on a disconnected/connecting socket, it should stop trying to reconnect.

### Actual behavior
When socket.disconnect() is invoked on a socket which is trying to connect or disconnected (phoenix server is offline), it will keep trying to reconnect.

**Comment by chrismccord** [comment]
This should be fixed on master. Thanks!
