### ISSUE TITLE
It's hard to write cross-platform watchers

### ISSUE THREAD

**Issue by eteeselink** [phoenixframework/phoenix#4617]
### Environment

* Elixir version (elixir -v): Elixir 1.12.1 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.6.2
* Operating system: Windows

### Situation

Most of our team is on Linux and Mac. A colleague had adopted Phoenix's `watchers` feature, and added the following:

```ex
  watchers: [
    npm: ["run", "assets:watch:js", cd: Path.expand("..", __DIR__)],
    npm: ["run", "assets:watch:css", cd: Path.expand("..", __DIR__)]
  ]
```

### Expected behavior

I expected phoenix to start normally on my Windows computer

### Actual behavior

I got spawn errors and the watchers did not run.

### Underlying problem

I don't grok unix all too deeply so pardon me if I get details wrong. I think Phoenix spawns the watchers directly as OS child processes. On unixes, I think anything that is `+x` can be spawned that way, and if it's a script (and not a binary executable), then the OS reads the hashbang to figure out which shell to use.

On Windows, however, you cannot do this as easily: the OS only lets you spawn an actual binary executable. I noticed that the Phoenix watcher documentation example works around this limitation by launching `node`, which is a binary everywhere, as opposed to some .cmd or .bat file such as `npm.cmd` and `iex.bat`. But that's not very developer friendly (and I couldn't figure how to launch `npm` using `node yadayada` in a cross-platform way, although I'm sure there's a way).

To my understanding, Windows treats batch files as regular text files and not like executables at all. They are associated on the shell level to open in `cmd.exe` by default - exactly like how you open a .txt file in Notepad when double-clicking it.

I was able to solve the problem on my machine by passing `npm.cmd` to `cmd.exe` explicitly, eg:

```ex
  watchers: [
    cmd: ["/c", "npm", "run", "assets:watch:js", cd: Path.expand("..", __DIR__)],
    cmd: ["/c", "npm", "run", "assets:watch:css", cd: Path.expand("..", __DIR__)]
  ]
```

But now it's Windows-only, so I hacked a little local helper function to make it cross-platform:

```ex
npm = fn args ->
  case :os.type() do
    {:win32, _} -> {:cmd, ["/c", "npm"] ++ args}
    _ -> {:npm, args}
  end
end

# ... 

  watchers: [
    npm.(["run", "assets:watch:js", cd: Path.expand("..", __DIR__)]),
    npm.(["run", "assets:watch:css", cd: Path.expand("..", __DIR__)])
  ]
```

This solved it for us, but I still thought it's worth reporting. 

### Possible solutions

I looked around the npm sources a bit, and it looks like they always launch their `npm run` commands through an OS shell (bash on unix, cmd.exe on windows): https://github.com/npm/run-script#usage. Maybe it's worth doing the same for Phoenix? 

That said, doing it like that also imports the questionable NPM design that encourages people to `&&` entire scripts together inside package.json, carefully frankensteined such that a single command is legal bash _and_ legal cmd syntax. I myself have become quite adept at doing that, but it's the kind of skill that nobody should've had to need if our tools were designed better :-) 

An alternative would probably be something like "are we on windows? and does the result of `:os.find_executable('npm')` end with `.cmd` or `.bat`? then launch it with cmd.exe and not directly". I'd be happy to attempt a PR that does this.

**Comment by josevalim** [comment]
> An alternative would probably be something like "are we on windows? and does the result of :os.find_executable('npm') end with .cmd or .bat? then launch it with cmd.exe and not directly". I'd be happy to attempt a PR that does this.

Yes, this sounds like the sane approach to me. Plus, it is not tied to npm either, so it sounds ok. :) A PR is welcome!

**Comment by josevalim** [comment]
Ping! :)

**Comment by eteeselink** [comment]
Sorry, mad corona lockdown kids-at-home stress here, I didn't get to it yet. I still very much intend to produce this PR but can't provide a timeline right now. In case anyone else reads this, I won't be offended if someone beats me to the punch :-)

Sorry for keeping you hanging, I know how much you all like them issues closed.

**Comment by josevalim** [comment]
No problem, just checking you got my message. Thanks for the update!
