### ISSUE TITLE
Wrong Channel is joined due to the `channel` order

### ISSUE THREAD

**Issue by andersonmcook** [phoenixframework/phoenix#4618]
### Environment

* Elixir version (elixir -v): Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.2
* Operating system: MacOS

### Expected behavior

For multiple channels the channel with a more specific topic should match first, or the order should not be reversed when creating the channels in https://github.com/phoenixframework/phoenix/blob/v1.6.2/lib/phoenix/socket.ex#L352

```elixir
  channel "a:b*", ABStar
  channel "a:*", AStar
```

For "a:b1" the `ABStar` channel is joined.

### Actual behavior

For "a:b1" the `AStar` channel is joined.

I've created an example app with a test
https://github.com/andersonmcook/channel_order

https://github.com/andersonmcook/channel_order/blob/main/lib/channel_order_web/channels/user_socket.ex
https://github.com/andersonmcook/channel_order/blob/main/test/channel_order_web/channels/user_socket_test.exs

**Comment by josevalim** [comment]
Can you please provide a pull request with tests? :) Let me know if you need assistance. :)

**Comment by andersonmcook** [comment]
@josevalim I can definitely provide a pull request with tests.  

My initial thought was just to report this as a fix reversing the order could cause a regression in applications that use Phoenix.  I know for our app I added tests very similar to the example app to check if the order ever changed.

We might have to order by specificity.

**Comment by josevalim** [comment]
I think we should reverse it and list it as a bug fixes. It will only be available on v1.7 though.

**Comment by josevalim** [comment]
Closing in favor of PR, thank you! :heart:
