### ISSUE TITLE
mix phoenix.start foo halts too early on umbrellas

### ISSUE THREAD

**Issue by ericmj** [phoenixframework/phoenix#462]
`phoenix.start` is a recursive task so it should not halt with `:timer.sleep(:infinity)`, it will halt on the first on child and the task will not run for the other children.

/cc @josevalim

**Comment by midas** [comment]
Gentlemen: I have opened a discussion on this matter in Phoenix talk channel.  While I figured out how to start the phoenix app from the top level directory of the umbrella project utilizing the information in this discussion/commit, I am still lost on how to start all apps in the umbrella project.

Could you drop by this discussion and clarify this matter for all of us?  Thanks.

https://groups.google.com/forum/#!topic/phoenix-talk/i7lpr2T3w6M

**Comment by josevalim** [comment]
Which Phoenix version are you using? It should just work on more recent
ones. The routers configuration is dropped but it should just work.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by midas** [comment]
I am using Phoenix v0.14.0. When I execute mix run --no-halt only my secondary
app starts.

On Sat, Jul 25, 2015 at 10:35 AM, phoenixframework/phoenix
<reply@reply.github.com>
wrote:
Which Phoenix version are you using? It should just work on more recent
ones. The routers configuration is dropped but it should just work.

--


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
—
Reply to this email directly or view it on GitHub
[https://github.com/phoenixframework/phoenix/issues/462#issuecomment-124853722] .[https://github.com/notifications/beacon/AADSMxN02hTDs33c_gPo0cotgxp1dGBLks5og6RNgaJpZM4C4Hpy.gif]

**Comment by josevalim** [comment]
Ok, I have created two apps locally, inside umbrella, one being a phoenix, another being a regular app. I have run mix run --no-halt at the umbrella root and both apps are running side by side. Thoughts?

**Comment by josevalim** [comment]
Can you push an app to github that reproduces exactly this issue? So we can try it out? I can't see locally.

**Comment by midas** [comment]
Unfortunately I cannot push the specific app to a public github repo as it is the intellectual property of someone else.  Can you tell me the process you employed to generate the apps?  Maybe I went wrong there.

**Comment by josevalim** [comment]
It doesn't need to be that app, but any other that you can reproduce the failure. My process:

    $ mix new foo --umbrella
    $ cd foo/apps
    $ mix new bar
    $ mix phoenix.new baz
    # Setup Phoenix accordingly

Then go to the umbrella root and:

    $ iex -S mix phoenix.server
    iex> :application.loaded_applications

Both are loaded and running.

**Comment by midas** [comment]
OK.  That is the problem.  I was issuing a `mix run --no-halt` not a `iex -S mix phoenix.server`.  When I issue the normal Phoenix start command, all of the apps in my project are running also.  Sorry for the confusion.  This is somewhat counter intuitive because it seems the Phoenix start command would only start the Phoenix application.

Could you explain why/how the Phoenix start command starts all apps in the umbrella project?  Additionally, what process would you use to start the apps in production?  Is there anything different than a normal Elixir or Phoenix app to consider in this case?

**Comment by josevalim** [comment]
@midas the best way to answer your question is to look at the source:

https://github.com/phoenixframework/phoenix/blob/v0.14.0/lib/mix/tasks/phoenix.server.ex#L20-L22

All phoenix.server does is to set a flag for the phoenix endpoints to boot and then starts all apps. If you want to change what is started and not, check the comments in config/prod.exs near to serve: true (it also applies to releases).

**Comment by josevalim** [comment]
Here: https://github.com/phoenixframework/phoenix/blob/v0.14.0/installer/templates/new/config/prod.exs#L37-L47

**Comment by midas** [comment]
@josevalim Thanks for the guidance. I will dig to understand this further and then respond to my question in the phoenix-talk group so others can benefit.  Take care!
