### ISSUE TITLE
Extra heartbeat is sent after disconnect resulting in heartbeat timeout and abnormal close

### ISSUE THREAD

**Issue by Panda-ref** [phoenixframework/phoenix#4623]
### Pre-check
- [x] Use the GitHub issue search — check if the issue has already been reported.
- [x] Check if the issue has been fixed — try to reproduce it using the master (64cb75cd1431e17df5933d111322f65b8251197e) branch in the repository.
- [x] Isolate and report the problem — ideally create a reduced test case.

Once a connection is established we schedule the next heartbeat here:
https://github.com/phoenixframework/phoenix/blob/v1.6.2/assets/js/phoenix/socket.js#L314
end then on a successful heartbeat it's rescheduled again here:
https://github.com/phoenixframework/phoenix/blob/v1.6.2/assets/js/phoenix/socket.js#L502
those two timers are neither saved nor cleared. I believe that causes the problem.

We do actually clear heartbeatTimer which is in fact heartbeatTimeoutTimer:
https://github.com/phoenixframework/phoenix/blob/v1.6.2/assets/js/phoenix/socket.js#L363
I think we need to clear actual heartbeatTimer as well as heartbeatTimeoutTimer on disconnect and maybe do some renaming to be more explicit about our intentions.

### Environment
```
npm info phoenix version
1.6.2
```
and
```
npm info phoenix version
1.6.3
```

### Expected behaviour
No heartbeats being sent after disconnect
No heartbeats should be timed out after disconnect

### Actual behaviour
One heartbeat is sent after disconnect
One heartbeat is timed out after disconnect resulting in "transport heartbeat timeout. Attempting to re-establish connection" being logged and abnormal close

### Failing tests examples
```
describe("onConnClose", function(){
    ...
    it("does not send heartbeat after explicit disconnect", function(done){
      let clock = sinon.useFakeTimers()
      const spy = sinon.spy(socket, "sendHeartbeat")
      socket.onConnOpen()
      socket.disconnect()
      clock.tick(30000)
      assert.ok(spy.notCalled)
      clock.restore()
      done()
    })

    it("does not timeout the heartbeat after explicit disconnect", function(done){
      let clock = sinon.useFakeTimers()
      const spy = sinon.spy(socket, "heartbeatTimeout")
      socket.onConnOpen()
      socket.disconnect()
      clock.tick(30000)
      clock.tick(30000)
      assert.ok(spy.notCalled)
      clock.restore()
      done()
    })

    it("does not fail with abnormal close after explicit disconnect", function(done){
      let clock = sinon.useFakeTimers()
      const spy = sinon.spy(socket, "abnormalClose")
      socket.onConnOpen()
      socket.disconnect()
      clock.tick(30000)
      clock.tick(30000)
      assert.ok(spy.notCalled)
      clock.restore()
      done()
    })
```

**Comment by chrismccord** [comment]
1.6.3 was released moments ago which I believe addresses this. Can you try that out and report back? Thanks!

**Comment by Panda-ref** [comment]
Lol)

**Comment by Panda-ref** [comment]
Hey @chrismccord, I've just pulled latest master and run these tests locally, still fails

**Comment by maxguzenski** [comment]
I'have a large app and after update from 1.5.8 to 1.6.6 I began to receive a lot of emails from users complaining that after losing the websocket connection the chat no longer reconnects. Maybe is related.

**Comment by maxguzenski** [comment]
I confirm, that is my online users after rollback from 1.6.6 to v1.6.2:

<img width="216" alt="Captura de tela 02 03 2022 às 22 07 36 PM" src="https://user-images.githubusercontent.com/6819/156476586-39d2a151-5d2e-4cd1-a030-147edebfbc64.png">

**Comment by tusooa** [comment]
Can reproduce on (js) 1.6.6 .

0. Connect to the websocket on a mobile *Fennec F-Droid*.
1. Debug the Fennec with a desktop Firefox. Set up a logger.
2. On mobile, switch Fennec to another tab (making the websocket tab inactive)
3. Watch the console on desktop.

```
WS: push phoenix heartbeat (undefined, 6) 
Object {  }
[debugger eval code:1:94](chrome://devtools/content/webconsole/debugger%20eval%20code)
WS: receive ok phoenix phx_reply (6) 
Object { response: {}, status: "ok" }
[debugger eval code:1:94](chrome://devtools/content/webconsole/debugger%20eval%20code)
WS: transport close 
close { target: WebSocket, isTrusted: true, wasClean: false, code: 1000, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
[debugger eval code:1:94](chrome://devtools/content/webconsole/debugger%20eval%20code)
WS: channel error chat:public undefined [debugger eval code:1:94](chrome://devtools/content/webconsole/debugger%20eval%20code)
WS: push phoenix heartbeat (undefined, 7) 
Object {  }
[debugger eval code:1:94](chrome://devtools/content/webconsole/debugger%20eval%20code)
WS: transport heartbeat timeout. Attempting to re-establish connection undefined
```

We were using 1.4.0. It also disconnects, but I am not sure whether it is the same problem.

**Comment by chrismccord** [comment]
Thank you for the detailed report and test, as well as hanging in there until I could address this! <3
