### ISSUE TITLE
"phx.gen.release" could not be found

### ISSUE THREAD

**Issue by mwillema** [phoenixframework/phoenix#4627]
### Environment

* Elixir version (elixir -v): 1:12:3
* Phoenix version (mix deps): 1.6.2
* Operating system: macOS

### Expected behavior

[According to the docs](https://hexdocs.pm/phoenix/releases.html#containers), I can generate a Docker file with the command `mix phx.gen.release --docker`.

### Actual behavior

However, when I do so, I get the following error message:

`** (Mix) The task "phx.gen.release" could not be found. Did you mean "phx.gen.presence"?`

**Comment by cw789** [comment]
Isn't this a feature of > v1.6.3 ?

Install the new Phoenix Installer -> `mix archive.install hex phx_new`

**Comment by mwillema** [comment]
I have phx_new 1.6.4, but it's not working.

**Comment by cw789** [comment]
Ok, then my wrong assumption. You'll have to upgrade your project Phoenix -> `mix deps.update phoenix`

**Comment by chrismccord** [comment]
Please ensure you have updated phoenix in your project! Thanks!
