### ISSUE TITLE
Phoenix 1.6.4: Esbuild watcher bug when running in dev container on M1

### ISSUE THREAD

**Issue by restlessronin** [phoenixframework/phoenix#4629]
### Environment

* Elixir version (elixir -v): 1.13.0
* Phoenix version (mix deps): 1.6.4
* OTP: 24.1.7
* Operating system: MacOS Big Sur 11.6.1
* Hardware M1 chip
* Base Docker Image: `hexpm/elixir:1.13.0-erlang-24.1.7-ubuntu-focal-20210325`

### Steps to Reproduce

1. `mix phx.new . --app my_app --no-ecto --no-mailer`
2. `mix phx.server`
3.  browse to http://localhost:4000

### Expected behavior

See the Phoenix Welcome Screen

### Actual behavior

Works as expected when running natively on MacOS

In container there is no page received.

### Workaround

Comment out the esbuild watcher in container
```
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
#    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]
```
The page is then received as normal

### Possible cause

This may be related to the fact that `esbuild` uses `esbuild-darwin-arm64` natively and `esbuild-linux-arm64` in container.

```
mix assets.deploy
```

works correctly on native, but segfaults in container

**Comment by chrismccord** [comment]
I know folks are still having various issues with M1 and docker, so I don't believe this is anything for us to handle on our side. Thanks!

**Comment by restlessronin** [comment]
Fair Enough. If I have some time, I'll look into `esbuild` itself.
