### ISSUE TITLE
Code reloading fails when starting from umbrella project

### ISSUE THREAD

**Issue by cconstantin** [phoenixframework/phoenix#463]
the phoenix project is an in_umbrella project, and the router is started from the application start callback. Running with `mix run --no-halt`. Code reloading fails with

    17:05:13.508 [error] GenServer Phoenix.CodeReloader terminating
    Last message: :reload
    State: :nostate
    ** (exit) an exception was raised:
        ** (Mix.Error) Trying to access app_path for an umbrella project but umbrellas have no app
            (mix) lib/mix.ex:235: Mix.raise/1
            (mix) lib/mix/project.ex:303: Mix.Project.compile_path/1
            (phoenix) lib/mix/phoenix.ex:20: Mix.Phoenix.modules/0
            (phoenix) lib/phoenix/code_reloader.ex:40: Phoenix.CodeReloader.touch/0
            (phoenix) lib/phoenix/code_reloader.ex:75: Phoenix.CodeReloader.mix_compile/1
            (phoenix) lib/phoenix/code_reloader.ex:55: Phoenix.CodeReloader.handle_call/3
            (stdlib) gen_server.erl:580: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3`

**Comment by chrismccord** [comment]
@cconstantin Sorry for the delay on this. Is this still an issue?

**Comment by josevalim** [comment]
It is very likely this is still an issue. I have some ideas to fix it though. I am assigning it to me.

**Comment by cconstantin** [comment]
@chrismccord yes, still an issue. It has to do with identifying the app folder(s) for an umbrella project.

**Comment by josevalim** [comment]
Fixed on 312459157aa0321472dcd9cef41c39cabb501c07.
