### ISSUE TITLE
Change "use Phoenix.HTML" to "import Phoenix.HTML" and "import Phoenix.HTML.Form"

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#4637]
The goal is to improve the clarity over what is imported. Don’t send a pull request for this yet as it requires https://github.com/phoenixframework/phoenix_html/issues/372 to be completed and many helpers to be rewritten.

**Comment by fmterrorf** [comment]
Hello José :wave: I've created a PR above to address this issue
