### ISSUE TITLE
Command `mix phx.new my_app --no-live` still creates live specific things?

### ISSUE THREAD

**Issue by jarmo** [phoenixframework/phoenix#4641]
### Environment

* Elixir version (elixir -v): Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): phoenix 1.6.5
* Operating system: -

### Expected behavior
I expected to not see anything related with live when adding `--no-live` flag to `phx.new`.

### Actual behavior
`live.html.eex` exists under `templates/layout`.

Should it be there?

**Comment by jarmo** [comment]
There are also these functions in `my_app_web.ex`:
```
  def live_view do
    quote do
      use Phoenix.LiveView,
        layout: {MyAppWeb.LayoutView, "live.html"}

      unquote(view_helpers())
    end
  end

  def live_component do
    quote do
      use Phoenix.LiveComponent

      unquote(view_helpers())
    end
  end
```

**Comment by jarmo** [comment]
Also `endpoint.ex` has live related content, but I'm not sure if this is needed only for development or not since I'm not too familiar with LiveView and I know that I don't need this extra complexity for my app:
```
 socket "/live", Phoenix.LiveView.Socket, websocket: [connect_info: [session: @session_options]]
```

**Comment by josevalim** [comment]
As per the documentation:

    * `--no-live` - comment out LiveView socket setup in assets/js/app.js
      and also on the endpoint (the latter also requires `--no-dashboard`)

In other words, it is mostly about disabling the websocket. This is because LiveView is also used to generate HTML (HEEx templates) and the socket is used by LiveDashboard. You can pass `--no-dashboard` to remove the endpoint.

**Comment by jarmo** [comment]
@josevalim thank you for the explanation.

Do you mean by `LiveView is also used to generate HTML (HEEx templates)` in development so that live reload would work or is it some other context?

I would like to have some flag to remove everything Live(View)-related together with live reload in development - as I understand then this is not possible as of this moment?

**Comment by josevalim** [comment]
The way to get rid of LiveView fully is with `--no-html` but that means you don't plan to generating HTML templates. But today, if you are generating HTML, then the recomemndation is to use the high-level template features (that are integrated within LiveView).
