### ISSUE TITLE
Error handling on socket.serializer.decode! 

### ISSUE THREAD

**Issue by mirkobrankovic** [phoenixframework/phoenix#4645]
### Description
Can error handling be added to phonix serializer topic check:
https://github.com/phoenixframework/phoenix/blob/7f17de3ed300f8b324177f7112a3caf995c70da1/lib/phoenix/socket.ex#L474
so maybe a case clause if  there is a topic and when not.

In case of broken or malicious clients that send non-json on joined phoenix channels

### Environment

* Elixir version (elixir -v): Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): * phoenix 1.5.7 (Hex package) (mix)
* Operating system:  Fedora release 35 (Thirty Five)

### Expected behavior
Returned error:
`{:error, "Topic not found in payload"}
`
or something similar 

### Actual behavior
```
Process #PID<0.24789.459> terminating
** (Jason.DecodeError) unexpected byte at position 0: 0x6F ('o')
    (jason 1.2.2) lib/jason.ex:78: Jason.decode!/2
    (phoenix 1.5.7) lib/phoenix/socket/serializers/v1_json_serializer.ex:32: Phoenix.Socket.V1.JSONSerializer.decode!/2
    (phoenix 1.5.7) lib/phoenix/socket.ex:466: Phoenix.Socket.__in__/2
    (phoenix 1.5.7) lib/phoenix/endpoint/cowboy2_handler.ex:175: Phoenix.Endpoint.Cowboy2Handler.websocket_handle/2
    (cowboy 2.9.0) /drone/src/deps/cowboy/src/cowboy_websocket.erl:528: :cowboy_websocket.handler_call/6
    (cowboy 2.9.0) /drone/src/deps/cowboy/src/cowboy_http.erl:257: :cowboy_http.loop/1
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

P.S. I  apologize for my basic knowledge of Elixir and Phoenix :D

**Comment by chrismccord** [comment]
No worries! In the case of malicious clients, failing with an error is completely fine. Thanks!
