### ISSUE TITLE
`code_reloader` should not force a reload unless has actually changed

### ISSUE THREAD

**Issue by marcandre** [phoenixframework/phoenix#4647]
### Environment

* Elixir version (elixir -v): 1.13.1
* Phoenix version (mix deps): 1.6

### Expected behavior

```
$ touch config/dev.exs
```

and server continues working fine

### Actual behavior

```
** (RuntimeError) could not compile application: bobby.

You must restart your server after changing the following files:

  * config/dev.exs
```

Need to do "control-C" twice, redo `mix phx.server` yet no file needs recompilation (in elixir 1.13)

**Comment by josevalim** [comment]
PR is welcome (please CC me as I am not subscribed). :)

**Comment by josevalim** [comment]
Oh wait, actually, this is tricky. Because depending on your configuration, it may require restarting the app. For example, the web server port, a dependency, or any compile time config. So restarting the app is the safest approach/feedback.

**Comment by marcandre** [comment]
Right. We could at least use a digest instead of only last modified date, which would solve the issue when rebasing.

**Comment by josevalim** [comment]
@marcandre ah, perfect. PR is welcome!

**Comment by chrismccord** [comment]
We've discussed this in the past, but the complexity has to be weighed against the value for a dev tool. I would happily review a PR if you want to give it a go :)
