### ISSUE TITLE
Phoenix.Endpoint.socket/2 will prevent HTTP route on the same path

### ISSUE THREAD

**Issue by Sgiath** [phoenixframework/phoenix#4652]
### Environment

* Elixir version (elixir -v): 1.13.1
* Phoenix version (mix deps): 1.6.6
* Operating system: Linux

### Expected behavior
I can use `Phoenix.Endpoint.socket/2` for custom WebSocket connections and serve custom HTTP route on the same path.

### Actual behavior
When using `Phoenix.Endpoint.socket/2` and GET route on the same path my HTTP route configuration is ignored and Phoenix will just return `426 Upgrade Required`.

### Example
`lib/example_web/endpoint.ex`
```elixir
defmodule ExampleWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :example

  socket "/example", ExampleWeb.Socket, websocket: [timeout: :infinity, path: "/"]

  plug ExampleWeb.Router
end
```

`lib/example_web/router.ex`
```elixir
defmodule ExampleWeb.Router do
  use ExampleWeb, :router

  scope "/", ExampleWeb do
    get "/example", ExampleController, :index
  end
end
```

When requesting `/example` I will get `426 Upgrade Required` instead of `ExampleController` output.

### Discussion
It might be intentional but it prevents some legitimate use-cases e.g.: where protocol communication is happening over WebSocket but the server should publish server info on the same path over HTTP

See https://github.com/fiatjaf/nostr/pull/51/files

**Comment by chrismccord** [comment]
This is expected. The transport layer is also extensible, so you can implement a transport (such as we do with long polling), but the client selects the transports via the path, such as `/example/websocket`, `/example/longpoll`. If you think documentation can be improved, we would be happy to review a PR. Thanks!

**Comment by Sgiath** [comment]
@chrismccord thanks for the answer. I am not sure what you mean by: `implement a transport (such as we do with long polling)` - I have implemented my own transport implementing `Phoenix.Socket.Transport` behaviour but I am still not able to handle HTTP requests on this transport.

As far as I can see longpoll is very specific and hardcoded in the `Phoenix.Endpoint` [implementation](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint.ex#L692) - I don't see how I could replicate what you did with the longpoll without avewriting the `Phoenix` source code.

**Comment by chrismccord** [comment]
You can't serve plug HTTP traffic at the same prefix of the socket since we intercept the socket before any of the plug pipeline.

**Comment by Sgiath** [comment]
Yeah that's what I figured and my question is: isn't it something that should be supported? Is there some technical limitation why it cannot be supported? I have use-case - the [specification](https://github.com/fiatjaf/nostr/blob/master/nips/11.md#nip-11) of Nostr protocol - which I cannot work-around without using some external tool (like splitting the traffic in Nginx proxy).

**Comment by chrismccord** [comment]
It's not something we plan on supporting since we necessarily hijack the request for the transport.
