### ISSUE TITLE
Not a discussion , rather a vscode extension support for heex template syntax highlights

### ISSUE THREAD

**Issue by Ritvyk** [phoenixframework/phoenix#4655]
Released my first version of VSCode extension for Syntax highlighting within Heex templates for embedded Alpine JS and PHX out of the box.

https://marketplace.visualstudio.com/items?itemName=ritvyk.heex-html

Need some good reviews and feedback about this , It solves the problem of using embedded syntaxes for Alpine and PHX within Heex templates leads to a gibberish HTML hard to debug and format.

Contribute to the repo and make it better !

**Comment by chrismccord** [comment]
Please send this type of thing to the forums. Thanks!
