### ISSUE TITLE
The auth generator's output references /dev/mailbox but the path in the router is set to /mailbox

### ISSUE THREAD

**Issue by nickjj** [phoenixframework/phoenix#4661]
### Environment

* Elixir version (elixir -v): 1.13.1
* Phoenix version (mix deps): 1.6.6
* Operating system: Debian 11

### Expected behavior

After running: `mix phx.gen.auth Accounts User users`, the generator produced this text to my terminal:

```
Once you are ready, visit "/users/register"
to create your account and then access "/dev/mailbox" to
see the account confirmation email.
```

I would have expected to be able to access http://localhost:8000/dev/mailbox to see the mailbox.

### Actual behavior

It throws a 404 because the `router.ex` file defines:

```ex
    scope "/" do
      pipe_through :browser
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
```

### Workaround

Visit http://localhost:8000/mailbox for things to work out of the box.

I would have opened a PR to address this but it's not clear on what the intended behavior should be. Do you want it to be `/dev/mailbox` or `/mailbox`? If it's supposed to be `/dev/mailbox` would you add `/dev` as the scope instead of `/` or keep the scope as is but adjust the forward to `/dev/mailbox`?

**Comment by chrismccord** [comment]
`/dev/mailbox` is the generated scope since we added the feature, so I believe your app has changed it at some point? Thanks!

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_web/router.ex#L55-L60

**Comment by nickjj** [comment]
True, I had it defined with `/` before running the generator because I was using Swoosh before using the generator.

What do you think about modifying the generator to look at the scope to determine what to produce in its output message? It could help with first impressions for anyone who has an existing app but wants to start using the auth generator.
