### ISSUE TITLE
Route with undefined module/function does not generate warning when compiled

### ISSUE THREAD

**Issue by lkarthee** [phoenixframework/phoenix#4666]
### Environment

* Elixir version (elixir -v): 1.13
* Phoenix version (mix deps):  "~> 1.6.4"
* Operating system: Mac OS 12.0.1

### Expected behavior

```
  scope "/", HelloLiveWeb do
    pipe_through :browser

    get "/", PageController, :index # <-- module and function is defined
    get "/pages/:id", PageController, :undefined_func # <-- function is not defined
    get "/tests/:id", SomeUndefinedController, :id # <-- module is not defined
    live "/demo", Demo # <-- module is defined
    live "/hello_demo", UndefinedDemoLive # <-- module is not defined 
  end
```

Routes with undefinded module or function should generate warnings - 3 warnings expected when routes are compiled.
- function HelloLiveWeb.PageController. undefined_func/2 is undefined
- module SomeUndefinedController is not available or undefined
- module UndefinedDemoLive is not available or undefined

### Actual behavior
Only one warning is generated :
```
 warning: HelloLiveWeb.SomeUndefinedController/1 is undefined (module HelloLiveWeb.SomeUndefinedController is not available or is yet to be defined)
  lib/hello_live_web/router.ex:22: HelloLiveWeb.Router.__checks__/0
```

Undefined functions in plain controllers and undefined live controllers don't generate any warnings.

**Comment by lkarthee** [comment]
```elixir
def __checks__, do: unquote({:__block__, [], Map.keys(checks)})
```

Is __checks__  generated only for warnings about UndefinedModule or is it used anywhere? I searched for it could not find anything related to __checks__.

```elixir
def __checks__() do
  MyAppWeb.PageController.init(:index) # for normal routes
  Phoenix.LiveView.Plug.init(MyAppWeb.ExampleLive.Index) # <- for live view routes
  MyAppWeb.ExampleLive.Index.init(:index) # above line should have been generated like this one ?
end
```

If __checks__ is for generating undefined modules warnings - then it is generating wrong line for live view ?

**Comment by josevalim** [comment]
We can fix this by allowing the routes to annotate what is the function reference it should generate. For example, maybe `live` routes could pass as option/metadata:

```
check_mfa: {Mod, :fun, arity}
```

and then we build this check in particular.

**Comment by lkarthee** [comment]
Router currently generates only warnings whenever there is an issue with route. With warnings, it sometimes becomes tricky. Example a duplicate path will only generate warning (easier for a developer to miss) - resulting in a serious bug in navigation. 
```
warning: this clause cannot match because a previous clause at line 126 always matches
  lib/my_app_web/router.ex:130
```
Should an error be generated instead of a warning (generic elixir warning) when something wrong is detected with router?  This will improve developer experience.

**Comment by josevalim** [comment]
I will close this. The way the router work is that it dispatches to plugs and, as long as the controller obeys the plug contract, it will be fine. The action is a dynamic dispatch done by the controller and unfortunately there is no way for the router to know about it.
