### ISSUE TITLE
Confusion on `put_secure_browser_headers/{1,2}` header `cross-origin-window-policy`

### ISSUE THREAD

**Issue by nickdichev** [phoenixframework/phoenix#4674]
### Environment

* Elixir version (elixir -v): Elixir 1.13.1 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps):  phoenix 1.5.13 (Hex package) (mix) <~ but same code exists on `master`
* Operating system: macOS 12.1

By default the [put_secure_browser_headers{1,2}](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/controller.ex#L1105) function adds a header named `"cross-origin-window-policy"` with value `"deny"`. However, in researching this header I think it was proposed by the Safari team but never actually implemented across other browsers. 

I think the correct header to use is ["cross-origin-opener-policy"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy) with value `"same-origin"`. 

Is there any insight as to why `"cross-origin-window-policy"` is the header used here? I don't get any hits when searching for this header.

**Comment by josevalim** [comment]
Please see #4677. :)
