### ISSUE TITLE
Allow run time socket configuration in Endpoint.ex

### ISSUE THREAD

**Issue by vicmgs** [phoenixframework/phoenix#4681]
* Elixir version (elixir -v): 1.12.1
* Phoenix version (mix deps): 1.6.5
* Operating system: Mac

Using releases.exs to deploy my app and I need to set the websocket check_origin from .env file. There doesn't seem to be a way to do this at run time.

socket "/socket", ConsoleWeb.UserSocket, 
    websocket: [timeout: 45_000, check_origin: [System.get_env("SOCKET_CHECK_ORIGIN")]]

**Comment by chrismccord** [comment]
We support this via MFA. From the docs:

```
      Or a custom MFA function:

          check_origin: {MyAppWeb.Auth, :my_check_origin?, []}

      The MFA is invoked with the request `%URI{}` as the first argument,
      followed by arguments in the MFA list, and must return a boolean.

```

Thanks!

**Comment by vicmgs** [comment]
@chrismccord thanks, but I'm still confused by what should be returned from that MFA?
