### ISSUE TITLE
Docker release has missing files for umbrella project

### ISSUE THREAD

**Issue by timothyvanderaerden** [phoenixframework/phoenix#4689]
### Environment

* Elixir version (elixir -v): 1.12.3
* Phoenix version (mix deps): 6716ea2eceec4b1b5e960cacf626d4146db4b32c
* Operating system: Linux (Ubuntu 21.10)

### Expected behavior

When using `mix phx.gen.release --docker` inside an umbrella project, `docker build` should succeed sucesfully.

### Actual behavior

`docker build` currently fails because it can't find `mix.lock` file, that's the first entry it fails on but it probably will also fail on copying the config files later on. I'm not sure this is the desired behavior and it's expected to manually change the Dockerfile in an umbrella application. I think it's worth adding some documentation for it or set the correct path in the Dockerfile.

**Comment by chrismccord** [comment]
We don't currently support umbrella apps in the Dockefile generator, but I'd accept a PR that handles this scenario. If you're interested, let us know! Thanks!
