### ISSUE TITLE
Route _url helpers don't respect `host:` parameter

### ISSUE THREAD

**Issue by trentjones21** [phoenixframework/phoenix#4690]
This could be a dupe of #4540, but I think different enough that it could warrant a separate issue.  There is also related discussion in #2462

### Environment

* Elixir version (elixir -v): `Elixir 1.13.2`
* Phoenix version (mix deps): `phoenix 1.6.6`
* Operating system: `macOS`

### Expected behavior

Given the following setup in `router.ex`

```elixir
scope "/", MyAppWeb, host: "foo.com" do
  pipe_through :browser
  get "/foo", PageController, :index
end

scope "/", MyAppWeb, host: "bar.com" do
  pipe_through :browser
  get "/bar", PageController, :index
end
```
I would expect the following return values from `Router.Helpers.page_url`
```elixir
%URI{host: "foo.com"} |> MyAppWeb.Router.Helpers.page_url(:index) # "//foo.com/foo"
%URI{host: "bar.com"} |> MyAppWeb.Router.Helpers.page_url(:index) # "//bar.com/bar"
```

### Actual behavior
The following values are returned

```elixir
%URI{host: "foo.com"} |> MyAppWeb.Router.Helpers.page_url(:index) # "//foo.com/foo"
%URI{host: "bar.com"} |> MyAppWeb.Router.Helpers.page_url(:index) # "//bar.com/foo"
```
It feels off to me that the helper would return a url for the host `foo.com`, even though the host was specified as `bar.com`

Sorry if this is working as intended or outside the scope of the Phoenix router.  Thanks for taking a look!

**Comment by chrismccord** [comment]
For your 2nd example, I assume you meant?

    %URI{host: "bar.com"} |> MyAppWeb.Router.Helpers.page_url(:index) # "//foo.com/foo" 

Let me try to recreate locally. Thanks!

**Comment by trentjones21** [comment]
@chrismccord You're right.  My examples work under the assumption that you have configured the endpoint `:url` to match the `host` in the 'URI' in each example, as would be the case if you were running the same Phoenix application on 2 distinct domains.  But I didn't make that clear.  But in either case, I still think that  
```
%URI{host: "bar.com"} |> MyAppWeb.Router.Helpers.page_url(:index) # "//foo.com/bar" 
``` 
would be more correct than
```
%URI{host: "bar.com"} |> MyAppWeb.Router.Helpers.page_url(:index) # "//foo.com/foo" 
```

**Comment by chrismccord** [comment]
Oh I see. Sorry I was not following initially. Since we don't actually dispatch through the router, the current behavior is all we can do, which is to match the generated named helper. To get what you want, the best way would to be to use the `as:` option to generate a unique helper name for the different host routes. Thanks!
