### ISSUE TITLE
Releases generator and docs should mention required edit to config/runtime.exs

### ISSUE THREAD

**Issue by cmcaine** [phoenixframework/phoenix#4695]
### Environment

* Elixir version (elixir -v): 1.13.0
* Phoenix version (mix deps): 1.6.6
* Operating system: Linux

### Expected behavior

Following the Deploying with releases guide should end up with `_build/prod/rel/appname/bin/server` launching a server listening on a port.

### Actual behavior

Server does not listen unless you uncomment a line in `config/runtime.exs` (quoted below) which is not mentioned in docs or the guff printed by the phx.gen.release.

```elixir
  # ## Using releases
  #
  # If you are doing OTP releases, you need to instruct Phoenix
  # to start each relevant endpoint:
  #
      config :votes, VotesWeb.Endpoint, server: true
  #
  # Then you can assemble a release by calling `mix release`.
  # See `mix help release` for more information.
```

### Suggested fix

Uncomment that line by default, maybe?

Uncomment it when the generator is run?

If that's not okay, document it better (and document it better anyway for people who have already used the generators).

Thanks for making Phoenix! <3

**Comment by almirsarajcic** [comment]
When I use the task `phx.gen.release` I get these lines in my `config/runtime.exs`:
```
if System.get_env("PHX_SERVER") && System.get_env("RELEASE_NAME") do
  config :#{app}, #{web_namespace}.Endpoint, server: true
end
```
https://github.com/phoenixframework/phoenix/blob/8833ecc9b36b6f13aeb4a5809ca937169104f28d/lib/mix/tasks/phx.gen.release.ex#L123-L131

I just need to provide `PHX_SERVER` and `RELEASE_NAME` environment variables. Fly.io automatically adds the latter one, but I manually put the `PHX_SERVER`. Like this: https://github.com/phoenixframework/phoenix/blob/380a281bd88a51d002fe567c0652c1cb657e5f9f/priv/templates/phx.gen.release/rel/server.sh.eex#L3

Hope this helps.

**Comment by josevalim** [comment]
New apps have the necessary code already injected and old apps emit the warning above, so we should be all good!
