### ISSUE TITLE
Migrate to Mint.WebSocket

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#4699]
We currently use [jeremyong's websocket_client](https://github.com/jeremyong/websocket_client) for testing but it has not been updated in a couple years and it breaks on Erlang/OTP 25.

We should probably migrate to something like [Mint.WebSocket](https://github.com/NFIBrokerage/mint_web_socket) instead. Pull requests welcome!

/cc @the-mikedavis

**Comment by the-mikedavis** [comment]
Let me know if you have any questions or if I can help :)

I was about to release a v1.0.0 since our testing of v0.2.0 went well and I'd like to stabilize the api. I'll do that now!

**Comment by josevalim** [comment]
@the-mikedavis we only use it for testing, so a stable API is not very important for us. So don't rush on our account! I am leaving this up for grabs in case anyone wants to tackle it! :)

**Comment by the-mikedavis** [comment]
I would be happy to work on this but I'm away on vacation for a few days. If anyone wants to beat me to it, feel free!

**Comment by chrismccord** [comment]
@the-mikedavis awesome. We'd love to have your help!
