### ISSUE TITLE
module TestproblemWeb.ConnCase is not loaded and could not be found

### ISSUE THREAD

**Issue by ebengt** [phoenixframework/phoenix#4700]
### Environment

* Elixir version (elixir -v):
Elixir 1.12.1 (compiled with Erlang/OTP 22)

* Phoenix version (mix deps):
phoenix 1.6.6 (Hex package) (mix)
locked at 1.6.6 (phoenix) 807bd646

* Operating system:
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"

### Expected behavior
$ mix phx.new testproblem
$ cd testproblem
$ mix deps.get
$ cp config/test.exs config/otherconfig.exs
$ MIX_ENV=otherconfig mix test 

Finished in 0.1 seconds (0.09s async, 0.06s sync)
3 tests, 0 failures

Ie, tests pass even if config is not called test.exs

### Actual behavior

== Compilation error in file test/testproblem_web/controllers/page_controller_test.exs ==
** (CompileError) test/testproblem_web/controllers/page_controller_test.exs:2: module TestproblemWeb.ConnCase is not loaded and could not be found
    (elixir 1.12.1) expanding macro: Kernel.use/1
    test/testproblem_web/controllers/page_controller_test.exs:2: TestproblemWeb.PageControllerTest (module)

**Comment by chrismccord** [comment]
Check your `elixirc_paths` in your mix.exs. Mix will only load the test directories in `test` per the elixirc_paths  in your mix file.
