### ISSUE TITLE
New init Telemetry event

### ISSUE THREAD

**Issue by akoutmos** [phoenixframework/phoenix#4712]
Firstly, I am not sure if this is the correct place to bring up this discussion, so feel free to close this if there is a better venue for it :).

In the PromEx project I currently have a bit of a hack in place to get Prometheus metrics related to the Endpoint module configuration and to see when it is up and running.

I am curious if Phoenix could also publish an `init` event when the Endpoint supervision tree has started similarly to how [Broadway](https://hexdocs.pm/broadway/Broadway.html#module-telemetry), [Oban](https://hexdocs.pm/oban/Oban.Telemetry.html), and [Ecto](https://hexdocs.pm/ecto/Ecto.Repo.html#module-telemetry-events) do?

As for what would be published in the telemetry event, I would probably include the `otp_app`, `module`, `config`, `system_time`, and `pid` that are associated with the started Endpoint Supervisor.

If this is something that the Phoenix team would be interested in, I can implement the initial version and open a PR over the weekend for it 😄.

Adding @tsloughter as we talked about this on the Observability working group call this morning.

Thanks in advance!

**Comment by chrismccord** [comment]
I'd be happy to evaluate a PR if you want to put it together. Thanks!
