### ISSUE TITLE
SSL 

### ISSUE THREAD

**Issue by flbn** [phoenixframework/phoenix#4720]
[https://www.phoenixframework.org/](https://www.phoenixframework.org/) is throwing an SSL connection error. Tested on Firefox, Chrome, and Safari. I'm not sure where else to flag this due to not having access to the site so I figured this might be a good place... 

Specifically, I'm shown this on Firefox:
```
Secure Connection Failed

An error occurred during a connection to www.phoenixframework.org. Peer received a valid certificate, but access was denied.

Error code: SSL_ERROR_ACCESS_DENIED_ALERT
```

The dev tools reveal nothing, this is the most descriptive thing I could find. I'll also attach a screenshot.

<img src="https://raw.githubusercontent.com/flbn/trashcan/main/Screen%20Shot%202022-03-14%20at%207.11.59%20PM.png" alt="firefox SSL error"/>

**Comment by flbn** [comment]
seeing as how the website is now back up (with and without the www subdomain), i'm just gonna go ahead and close this myself. thanks for the swift action guys!

**Comment by chrismccord** [comment]
Thanks! We moved things around and generated some new certs, then I fat fingered DNS :)
