### ISSUE TITLE
Dockerfile from phx.gen.release --docker has COPY assets even if phx.new --no-assets

### ISSUE THREAD

**Issue by IMAGE-ET** [phoenixframework/phoenix#4725]
### Environment

* Elixir version (elixir -v): 1.13.3
* Phoenix version (mix deps): 1.6.6
* Operating system: MacOS Monterey

### Expected behavior
When phx.new --no-assets, I would like the Dockerfile from phx.gen.release --docker to not try to copy nonexistant assets folder

### Actual behavior

The dockerfile autogenerated has a line "COPY assets assets" which make the docker build fail.
There is also a RUN mix assets.deploy which should be treated the same way

### Possible solution

Having a second template in priv/templates/phx.gen.release for a release without asset and check in the mix task if the asset folder exist.
This choice could open futures evolutions for more adapted Dockerfiles in the future, depending on things like arguments for the —docker flag or check the presence of optionals folders.

If this issue is deemed pertinent I’ll start a thread on the Phoenix Core mailing list.

**Comment by aaronrenner** [comment]
Just adding a little context to this issue... this has been fixed on master via #4688.

**Comment by aaronrenner** [comment]
I'm going to backport #4688 to the v1.6 branch so it will be released on the next 1.6.x release.
