### ISSUE TITLE
[DOCS] Navigating to `Guides/Controllers` page begins a download

### ISSUE THREAD

**Issue by kjpark** [phoenixframework/phoenix#4729]
### Environment

n/a, web browser
tested on 
- [desktop] firefox, brave, and edge
- [mobile] safari

### Expected behavior

clicking to the `controllers` guide open a webpage

### Actual behavior

clicking the `controllers` guide downloads the html
- clicking the guide directly begins a download
- clicking the "previous" or "next" buttons from adjacent guides begins a download

### More Info

this is the broken page that starts a download:
https://hexdocs.pm/phoenix/controllers.html#content

Tested on mobile as well as desktop. All other guide sections load normally.

I'd be happy to attempt a fix if somebody can point me in the right direction.

**Comment by chrismccord** [comment]
I republished the docs. Not sure what happened. thanks!

**Comment by kjpark** [comment]
awesome! works like a charm now ty
