### ISSUE TITLE
[website] `/blog` is empty / not loading

### ISSUE THREAD

**Issue by kjpark** [phoenixframework/phoenix#4734]
### Environment
web browser

### Expected behavior
navigating to https://phoenixframework.org/blog shows blog posts

### Actual behavior
no posts load (empty)

### Notes
- if blog section has been migrated / deprecated, i can create and assist in an issue to remove the section from the site
- oldest report of the issue i could find was 21/march on elixir#phoenix discord channel (u/Tyranit) attempting to access https://www.phoenixframework.org/blog/phoenix-1.6-released

edit: apologies if this is the wrong repo, `phoenix_website` was archived. will close & move if necessary.

**Comment by chrismccord** [comment]
Fixed! Thank you!

**Comment by kjpark** [comment]
ty!
