### ISSUE TITLE
Setting check_origin: false for socket doesn't work

### ISSUE THREAD

**Issue by Victoria91** [phoenixframework/phoenix#4737]
Hello and thanks for the library! ❤️ 

I encountered an error while trying to make check origin work for websockets.

* Elixir version (1.13.3-otp-24):
* Phoenix version (1.6.6):

In my case websocket request comes form chrome extension and on checking policy I got error:
``` 
Origin of the request: chrome-extension://mjoafcgliglllcpeikhcccmolicpmddh
```
I tried to set check_origin as `[“chrome-extension://*“]`, but when I followed the code I understand that it wouldn't work since it performs [URI.parse](https://github.com/phoenixframework/phoenix/blob/f5d167698dde5ceee031537cc0e1732c9f3424b8/lib/phoenix/socket/transport.ex#L356) on origin and in my case the host will be `mjoafcgliglllcpeikhcccmolicpmddh` which will never match the host I've set in `check_origin`.

Then I tried to disable check for websockets, so I've set
```elixir
  socket("/socket", MyAppWeb.UserSocket,
    websocket: true,
    longpoll: true,
    check_origin: false
  )
```
however it didn't work either, as I followed down the code it always uses [`:check_origin` option from endpoint config](https://github.com/phoenixframework/phoenix/blob/f5d167698dde5ceee031537cc0e1732c9f3424b8/lib/phoenix/socket/transport.ex#L560). 
So is it possible to provide extra check_origin policy for websockets?
Thanks!

**Comment by chrismccord** [comment]
Is there a reason you cannot set it on the endpoint config?

**Comment by Victoria91** [comment]
I wanted to disable check origin only for websockets

**Comment by chrismccord** [comment]
It is not currently possible to enforce per transport. Thanks!

**Comment by Victoria91** [comment]
So `:check_origin` option in [this section](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3-common-configuration) is no longer valid?

**Comment by antondomratchev** [comment]
@Victoria91  try
```
  socket("/socket", MyAppWeb.UserSocket,
    websocket: [check_origin: false],
    longpoll: true,
  )
```

Long poll can also have check_origin set to false.
