### ISSUE TITLE
Have phx.new automatically include heex formatting

### ISSUE THREAD

**Issue by tlietz** [phoenixframework/phoenix#4749]
It could be nice to have `mix phx.new` include the necessary changes to `.formatter.exs` to format `.heex` files upon running `mix format`. 

```elixir
# .formatter.exs
[
  plugins: [Phoenix.LiveView.HTMLFormatter],
  import_deps: [:ecto, :phoenix],
  inputs: ["*.{heex,ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{heex,ex,exs}"],
  subdirectories: ["priv/*/migrations"]
]
```

Are there any considerations to keep in mind if we were to implement this?

**Comment by feliperenan** [comment]
If we are going to include them, these would be the places to update afaik:

https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_single/formatter.exs
https://github.com/phoenixframework/phoenix/blob/master/installer/templates/phx_umbrella/apps/app_name/formatter.exs

It would generate for people who don't use Live View at all though 🤔

**Comment by tlietz** [comment]
What if we added some checks on the flags of `mix phx.new` to determine whether to add heex? 

But I am not sure if that added complexity would be worth it.

**Comment by leandrocp** [comment]
> It would generate for people who don't use Live View at all though 🤔

@feliperenan is it safe to run the html formatter on Elixir below v1.13? New apps may not be on that version.

**Comment by leandrocp** [comment]
> What if we added some checks on the flags of `mix phx.new` to determine whether to add heex?

That would be the `@html` assign like https://github.com/phoenixframework/phoenix/blob/7a6b939aa00714d262d72a8ccb193b6b76b4dfd1/installer/templates/phx_single/lib/app_name_web.ex#L43

**Comment by feliperenan** [comment]
> is it safe to run the html formatter on Elixir below v1.13? New apps may not meet that requirement.

It is not. The formatter shouldn't be present on early Elixir versions bc it wouldn't work at all. We might need to check for Elixir version as well.
