### ISSUE TITLE
Phoenix Channels - generator not working correctly  

### ISSUE THREAD

**Issue by Exadra37** [phoenixframework/phoenix#4752]
### Environment

* Elixir version (elixir -v):
```
$ elixir -v
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```
* Phoenix version (mix deps):
```
{:phoenix, "~> 1.6.6"},
```

Installer:

```bash
$ mix phx.new --version
Phoenix installer v1.6.6
```

* Operating system:
```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Expected behaviour

Creating the Channel Hello:

````bash
mix phx.gen.channel Hello
````

Expected code at `assets/js/user_socket.js`:

```javascript
let channel = socket.channel("hello:lobby", {})
```

It should generate the file `assets/js/user_socket.js` with the channel `hello:lobby`, instead of `room:42`, to match the channel expected in `lib/hello_sockets_web/channels/hello_channel.ex`.

I shouldn't see any warnings in the server logs, like I see now

### Actual behavior

Creating the Channel Hello:

````bash
mix phx.gen.channel Hello
````

Current code at `assets/js/user_socket.js`:

```javascript
let channel = socket.channel("room:42", {})
```

Server logs warnings:

```
[warning] Ignoring unmatched topic "room:42" in HelloSocketsWeb.UserSocket
[warning] Ignoring unmatched topic "room:42" in HelloSocketsWeb.UserSocket
[warning] Ignoring unmatched topic "room:42" in HelloSocketsWeb.UserSocket
```

**Comment by Exadra37** [comment]
I can try to fix this and provide a pull request .

**Comment by chrismccord** [comment]
The channel generator does not generate any js assets. Our `phx.new` generator will drop a `socket.js` with example channel code to get users started. Thanks!

**Comment by Exadra37** [comment]
> Our phx.new generator will drop a socket.js with example channel code to get users started. Thanks!

Ok, but then the `phx.new` generator is not doing it correctly as I stated.

Where do you want me to open this issue?
