### ISSUE TITLE
mix deps.get can't get phoenix 1.6.7 from hex

### ISSUE THREAD

**Issue by michallepicki** [phoenixframework/phoenix#4792]
### Environment

* Elixir version (elixir -v): `Elixir 1.14.0-dev (9ee24a3)`

### Expected behavior

After running these commands on a fresh Elixir setup I would expect Mix to be able to install the dependencies:

```
mix archive.install hex phx_new
mix phx.new hello
cd hello
mix deps.get
```

### Actual behavior

```
$ mix deps.get
** (Mix) No matching version for phoenix ~> 1.6.7 (from: mix.exs) in registry

The latest version is: 1.6.6
```

**Comment by michallepicki** [comment]
This happened to me earlier today, now I can see `phoenix 1.6.7` on [hex](https://hex.pm/packages/phoenix), but Mix still can't find it (?)

**Comment by michallepicki** [comment]
I'll investigate a bit more and reopen if I confirm the issue with stable Erlang and Elixir versions, sorry for the noise!

**Comment by chrismccord** [comment]
You're the third person that has reported this over the last few hours. Is it working locally for you now or still 404? I just tested locally myself and everything is working properly. This seems like a hex CDN issue, but I will need to wait until @ericmj can take a look.

**Comment by alaadahmed** [comment]
I have the same issue, in some apps I see there is update available for `phx 1.6.7` and others I don't see this update. I also ran `mix local.phx` and I see version `1.6.7` installed. But when I create new app, I see in `mix.exs` version of phx is `1.6.7` but when I check for outdated hex, I find it `1.6.6` 🤪
```
➜  testing mix hex.outdated
Dependency              Current  Latest  Status      
ecto_sql                3.7.2    3.7.2   Up-to-date  
esbuild                 0.4.0    0.4.0   Up-to-date  
floki                   0.32.1   0.32.1  Up-to-date  
gettext                 0.19.1   0.19.1  Up-to-date  
jason                   1.3.0    1.3.0   Up-to-date  
phoenix                 1.6.7    1.6.6   Up-to-date  
phoenix_ecto            4.4.0    4.4.0   Up-to-date  
phoenix_html            3.2.0    3.2.0   Up-to-date  
phoenix_live_dashboard  0.6.5    0.6.5   Up-to-date  
phoenix_live_reload     1.3.3    1.3.3   Up-to-date  
phoenix_live_view       0.17.9   0.17.9  Up-to-date  
plug_cowboy             2.5.2    2.5.2   Up-to-date  
postgrex                0.16.2   0.16.2  Up-to-date  
swoosh                  1.6.4    1.6.4   Up-to-date  
telemetry_metrics       0.6.1    0.6.1   Up-to-date  
telemetry_poller        1.0.0    1.0.0   Up-to-date  

Run `mix hex.outdated APP` to see requirements for a specific dependency.
➜  testing 
```

**Comment by michallepicki** [comment]
May be related to https://github.com/elixir-lang/elixir/issues/11745 or https://elixirforum.com/t/cant-get-the-package-from-hex/24433

**Comment by dvic** [comment]
We're seeing this issue as well, re-running the CI jobs randomly make it work, so a CDN issue sounds likely here.

**Comment by ericmj** [comment]
I have purged the CDN. Can you confirm if the issue is fixed?

**Comment by michallepicki** [comment]
It worked for me now, thank you! 🚀

**Comment by dvic** [comment]
We have also not encountered
the issue anymore.

**Comment by chrismccord** [comment]
Thanks Eric!
