### ISSUE TITLE
Error handling in Phoenix

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#482]
Proposal: a module (not a plug) that will wrap call/2 so errors can be rendered in a format available to users. This module will handle throws, errors and exits.

The module will retrieve the proper status code from those failures and invoke a **view**, configurable by the user, that is responsible for rendering a template according to the request format. For example, an exception to be rendered as 404 with HTML will try to render the "404.html" template. After the template is rendered and a response is sent, the failure will be re-raised.

By default a Phoenix application will ship with an `MyApp.ErrorsView`, with templates for 404.html and 500.html pages, and a catch all render that renders "500.html" in case the desired template is not available.
## FAQ
- Why views?
  
  The reasons we chose to views as an abstraction instead of a controller are:
  - Controllers send an implicit message that it would be ok to perform actions like fetching session, params and so on in the error handling scenarios, views do not send this message;
  - Views are easier to re-use than controllers, making it very easy to use the 404 templates from other controllers;
- Can we see how this view will look like?
  
  ```
  defmodule MyApp.ErrorsView do
    use MyApp.View
  
    def render(_, assigns) do
      render "500.html", assigns
    end
  end
  ```
- What happens if a response is not set?
  
  If a response is not set, a 500 error will be raised.

I believe this to be the only blocker for 0.6.1.

**Comment by aphillipo** [comment]
Wow. You did my work for me already 😂 Thanks!
