### ISSUE TITLE
conn struct doesn't set host and port in test live view calls

### ISSUE THREAD

**Issue by chvanikoff** [phoenixframework/phoenix#4825]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.6.8
* Operating system: MacOS 12.3.1

### Expected behavior
The test `conn` should have `host=localhost` and `port=4002` when live view is called

### Actual behavior
The test `conn` have `host=www.example.com` and `port=80`

I have never encountered the issue until I started working with `uri` from the handle_params/3 callback in my liveview, and I think this is unintentional behaviour.
The minimal demo is available here: https://github.com/chvanikoff/phx-lv-conn-bug - the code works as expected, but the tests fail because the uri in the handle_params/3 callback is `http://www.example.com/...`

If I init the test conn with `conn = Phoenix.ConnTest.build_conn(:get, DemoWeb.Endpoint.url(), nil)`, the `host` is properly set, but the port is 80 instead of 4002.

Probably the issue should be moved to phoenix_live_view or even plug, please let me know if that's the case.

**Comment by josevalim** [comment]
The host/port the server is running is often not the host/port you are usually accessed through and I think making tests have this behaviour will be confusing. So we default to example.com and you should set the proper url in your tests, by doing things such as: `get(conn, "https://myactualserver.com/bar")` on the tests that matter. You can also set it after you call `build_conn` :)
