### ISSUE TITLE
JS socket.onClose handler is called multiple times

### ISSUE THREAD

**Issue by axelson** [phoenixframework/phoenix#4828]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): phoenix 1.6.9 (Hex package) (mix)
* Operating system: macOS 12.3.1

### Expected behavior

I expect `socket.onClose` to only be called when the socket goes from open to closed

### Actual behavior

`socket.onClose` is called on every connection attempt.

This is also related to this question: https://github.com/phoenixframework/phoenix/issues/4330#issue-892748602

Where Ian Warshak says
> When a reconnect fails, both socket.onError and socket.onClose are called. I'd expect only the onError

I have the same thought.

I've tried to use the `establishedConnections` that's passed to `socket.onError` but it's a little hard to use because `establishedConnections` is not passed to `socket.onClose` (which is called first), so I'm not sure how to differentiate when `socket.onClose` is called from a failed retry or when it's called because the socket is closed. Is there some way to make that determination?

**Comment by jeregrine** [comment]
So digging into this a bit the basic onError and onClose are actually called by the browser. So ordering/inconsistency is largely on them.

We could give you more information in onClose so you know if it was an error or note. Lemme dig a little and see.

**Comment by jeregrine** [comment]
I guess the next question is, whats the use case here? onError should be enough to report errors to sentry or w/e? Do you also want to report on connection failed?

**Comment by jeregrine** [comment]
EDIT onClose callbacks will get the "event" from the browser which includes a "wasClean" boolean flag. If it was an error, such as reconnect failed, the `wasClean` flag will be false. Does this help?

**Comment by varshneydevansh** [comment]
Can I take this challenge? I got some idea what is going on, but might need some direction, though. @chrismccord

**Comment by jeregrine** [comment]
PR's are always welcome.

**Comment by Gazler** [comment]
I believe the current behaviour is consistent with the WebSocket API

> If an error occurs while attempting to connect, first a simple event with the name error is sent to the [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) object (thereby invoking its [onerror](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/error_event) handler), and then the [CloseEvent](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent) is sent to the WebSocket object (thereby invoking its [onclose](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close_event) handler) to indicate the reason for the connection's closing.

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications#connection_errors
