### ISSUE TITLE
phoenix.js - channel.on() did not capture `push()` from phoenix server in MacOS Safari

### ISSUE THREAD

**Issue by sooonism** [phoenixframework/phoenix#4829]
### Environment

* Elixir 1.13.1 (compiled with Erlang/OTP 22)
* Phoenix 1.5.13
* Operating system: MacOS Big Sur (version 11.5.2)
* Safari Version 14.1.2 (16611.3.10.1.6)

### Expected behavior
The code below:
```
channel.on("presence_state", (response) => { console.log("presence_state", response)}
```
should logged:
> presence_state {13: {…}, 15: {…}}

### Actual behavior
test this with safari, nothing will happen. But Other browsers(Chrome, Brave, Vivaldi) no problem.

### Observation
Only happen when using `push()` from `phoenix.channel`. `broadcast()` do NOT have issue.

**Comment by chrismccord** [comment]
I cannot recreate this on my side. Can you try latest phoenix to see if the issue still persists? Failing that, a complete reproducible example with channel elixir and javascript code would be helpful to rule out something on the phoenix side. Given that it is working for you on other browsers, I'm inclined to blame safari. For example, sometimes when dev'ing in safari, the web console for me simply stops logging activity and I have to kill the tab and start again. Perhaps that is what happens here? Thanks!

**Comment by josevalim** [comment]
Closing, please let us know if you have more info!
