### ISSUE TITLE
Removing Headers from put_secure_browser_headers

### ISSUE THREAD

**Issue by aj-foster** [phoenixframework/phoenix#4852]
Hello there 👋🏼 

I can imagine this desired behaviour being addressed by Phoenix, Plug, or not at all — so please redirect me as appropriate 🙂 

### Environment

* Elixir version (elixir -v): 1.12.2
* Phoenix version (mix deps): 1.6.10
* Operating system: macOS 12.4

### Expected behavior

When using `put_secure_browser_headers/2`, it doesn't appear we can completely remove one of the headers from the response without a separate plug. This makes it difficult to configure the `X-Frame-Options` header, which has no default value (only `SAMEORIGIN` and `DENY`, or no header at all for the default behaviour).

I thought that perhaps `plug :put_secure_browser_headers, %{"x-frame-options" => false}` or `nil` would succeed in removing the headers, but the underlying call to `Plug.Conn.merge_resp_headers/2` does not support this. Similarly, an empty string value leaves an empty header.

### Actual behavior

Instead, the non-binary values cause an error in `Plug.Conn.merge_resp_headers/2`.

---

Would you prefer Phoenix to look for non-binary values and handle them in `put_secure_browser_headers/2`, or should we seek to enhance `Plug.Conn.merge_resp_headers/2` to handle these cases? (Or, require the use of a separate plug to achieve this?)

Thanks! ❤️ 

Edit: related [discussion](https://github.com/livebook-dev/livebook/discussions/1215).

**Comment by josevalim** [comment]
You can call your own version of `put_secure_browser_headers` or call `delete_resp_header` to delete one particular header afterwards.
