### ISSUE TITLE
Phoenix socket path param and Socket javascript endpoint

### ISSUE THREAD

**Issue by haberbyte** [phoenixframework/phoenix#4859]
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): 1.6.10
* Operating system: Mac OS

### Expected behavior
If i customize my socket endpoint with the `path:` websocket option, e.g.
```elixir
defmodule MyAppWeb.Endpoint do
# ...
  socket "/api/realtime", MyAppWeb.UserSocket,
    websocket: [path: "/:key", connect_info: [session: @session_options]]
# ...
```

And then I want to connect to it with:

```javascript
import { Socket } from "phoenix";

let socket = new Socket("/api/realtime/123");
socket.connect();
```

Then I always hit a 404 error because the JS class always adds `/websocket` to the endpoint, so it tries to connect to `/api/realtime/123/websocket`, but this is not the path we set.

### Actual behavior

I would expect `new Socket("/api/realtime/123");` to either directly connect to the specified endpoint (and not append /websocket), or have an equivalent option `path:` in JS as well.

My current workaround is subclassing in JS, which i would like to avoid:

```javascript
import { Socket } from "phoenix";

export class RealtimeSocket extends Socket {
  constructor(endPoint, opts = {}) {
    super(endPoint, opts);

    this.endPoint = endPoint;
  }
}
```

**Comment by chrismccord** [comment]
The client always sends the transport it wants, so this is expected behavior. Thanks!

**Comment by haberbyte** [comment]
Hm okay. I wonder if I am just confused a bit by the docs here then:
https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#socket/3-path-params

```elixir
socket "/ws/:user_id", MyApp.UserSocket,
  websocket: [path: "/project/:project_id"]
```

How would anyone get the JS part working with that example?

**Comment by chrismccord** [comment]
Ah I see. I honestly forgot we added the `:path` option, but that is only a server thing. The channels client will always add the transport name, so you would need to roll your own websocket client to change this behavior from the client. Thanks!
