### ISSUE TITLE
Could not compile dependency :telemetry on new 1.6.10 app

### ISSUE THREAD

**Issue by duffyjp** [phoenixframework/phoenix#4861]
### Environment

<details><summary>Elixir version: 1.13.4</summary>
<pre>
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
Elixir 1.13.4 (compiled with Erlang/OTP 24)
</pre>
</details>
 
<details><summary>Phoenix version: 1.6.10</summary>
<pre>
$ mix deps
* castore (Hex package) (mix)
  locked at 0.1.17 (castore) d9844227
  the dependency build is outdated, please run "mix deps.compile"
* connection 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (connection) 722c1eb0
  ok
* cowboy (Hex package) (rebar3)
  locked at 2.9.0 (cowboy) 2c729f93
  the dependency build is outdated, please run "mix deps.compile"
* cowboy_telemetry (Hex package) (rebar3)
  locked at 0.4.0 (cowboy_telemetry) 7d98bac1
  the dependency build is outdated, please run "mix deps.compile"
* cowlib (Hex package) (rebar3)
  locked at 2.11.0 (cowlib) 2b3e9da0
  the dependency build is outdated, please run "mix deps.compile"
* db_connection (Hex package) (mix)
  locked at 2.4.2 (db_connection) 4fe53ca9
  the dependency build is outdated, please run "mix deps.compile"
* decimal 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (decimal) 34666e9c
  ok
* ecto (Hex package) (mix)
  locked at 3.8.4 (ecto) f9244288
  the dependency build is outdated, please run "mix deps.compile"
* ecto_sql (Hex package) (mix)
  locked at 3.8.3 (ecto_sql) 348cb17f
  the dependency build is outdated, please run "mix deps.compile"
* esbuild (Hex package) (mix)
  locked at 0.5.0 (esbuild) f183a0b3
  the dependency build is outdated, please run "mix deps.compile"
* file_system 0.2.10 (Hex package) (mix)
  locked at 0.2.10 (file_system) 41195edb
  ok
* gettext (Hex package) (mix)
  locked at 0.19.1 (gettext) 10c656c0
  the dependency build is outdated, please run "mix deps.compile"
* jason (Hex package) (mix)
  locked at 1.3.0 (jason) 53fc1f51
  the dependency build is outdated, please run "mix deps.compile"
* mime 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (mime) e6a3f76b
  ok
* phoenix (Hex package) (mix)
  locked at 1.6.10 (phoenix) 08cf70d4
  the dependency build is outdated, please run "mix deps.compile"
* phoenix_ecto (Hex package) (mix)
  locked at 4.4.0 (phoenix_ecto) 09864e55
  the dependency build is outdated, please run "mix deps.compile"
* phoenix_html (Hex package) (mix)
  locked at 3.2.0 (phoenix_html) 36ec97ba
  the dependency build is outdated, please run "mix deps.compile"
* phoenix_live_dashboard (Hex package) (mix)
  locked at 0.6.5 (phoenix_live_dashboard) ef4fa50d
  the dependency build is outdated, please run "mix deps.compile"
* phoenix_live_reload (Hex package) (mix)
  locked at 1.3.3 (phoenix_live_reload) 76679667
  the dependency build is outdated, please run "mix deps.compile"
* phoenix_live_view (Hex package) (mix)
  locked at 0.17.10 (phoenix_live_view) 3e77cf0f
  the dependency build is outdated, please run "mix deps.compile"
* phoenix_pubsub (Hex package) (mix)
  locked at 2.1.1 (phoenix_pubsub) 81367c6d
  the dependency build is outdated, please run "mix deps.compile"
* phoenix_view (Hex package) (mix)
  locked at 1.1.2 (phoenix_view) 7ae90ad2
  the dependency build is outdated, please run "mix deps.compile"
* plug (Hex package) (mix)
  locked at 1.13.6 (plug) 02b9c6b9
  the dependency build is outdated, please run "mix deps.compile"
* plug_cowboy (Hex package) (mix)
  locked at 2.5.2 (plug_cowboy) ea6e87f7
  the dependency build is outdated, please run "mix deps.compile"
* plug_crypto (Hex package) (mix)
  locked at 1.2.2 (plug_crypto) 87631c7a
  the dependency build is outdated, please run "mix deps.compile"
* postgrex (Hex package) (mix)
  locked at 0.16.3 (postgrex) aeaae1d2
  the dependency build is outdated, please run "mix deps.compile"
* ranch (Hex package) (rebar3)
  locked at 1.8.0 (ranch) 49fbcfd3
  the dependency build is outdated, please run "mix deps.compile"
* swoosh (Hex package) (mix)
  locked at 1.7.1 (swoosh) 8206d7da
  the dependency build is outdated, please run "mix deps.compile"
* telemetry (Hex package) (rebar3)
  locked at 1.1.0 (telemetry) b727b2a1
  the dependency build is outdated, please run "mix deps.compile"
* telemetry_metrics (Hex package) (mix)
  locked at 0.6.1 (telemetry_metrics) 7be9e087
  the dependency build is outdated, please run "mix deps.compile"
* telemetry_poller (Hex package) (rebar3)
  locked at 1.0.0 (telemetry_poller) b3a24eaf
  the dependency build is outdated, please run "mix deps.compile"
</pre>
</details>

<details><summary>Operating system: macOS 12.4 (M1)</summary>
<pre>
Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
</pre>
</details>
 
### Expected behavior

```
$ mix phx.new hello
$ cd hello
$ mix ecto.create
 ...
```

### Actual behavior
```bash
$ mix ecto.create
escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
** (Mix) Could not compile dependency :telemetry, "/Users/jacob/.mix/rebar3 bare compile --paths /Users/jacob/Phoenix/hello/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile telemetry", update it with "mix deps.update telemetry" or clean it with "mix deps.clean telemetry"
```
# 🤔 
```bash
$ mix deps.clean telemetry
$ mix deps.get
$ mix ecto.create

=ERROR REPORT==== 9-Jun-2022::10:23:11.748093 ===
beam/beam_load.c(551): Error loading function rebar3:parse_args/1: op put_tuple u x:
  please re-compile this module with an Erlang/OTP 25 compiler


escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
** (Mix) Could not compile dependency :telemetry, "/Users/jacob/.mix/rebar3 bare compile --paths /Users/jacob/Phoenix/hello/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile telemetry", update it with "mix deps.update telemetry" or clean it with "mix deps.clean telemetry"

```

FWIW I'm pretty green, but my existing 1.6.6 app is working fine.  I tried to make sure everything was updated:

```bash
$ brew upgrade elixir
$ mix local.hex --force
$ mix archive.install hex phx_new --force
```

**Comment by duffyjp** [comment]
@petermm Thanks for the tip.  Did the task name change at some point?  

```
$ mix local.rebar3 --force
escript: exception error: undefined function rebar3:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
```


Tried [without the 3](https://github.com/phoenixframework/phoenix/issues/2264#issuecomment-311582903):
```
$ mix local.rebar
/Users/jacob/.mix/rebar already exists, overwrite? [Yn] y
* creating /Users/jacob/.mix/rebar
/Users/jacob/.mix/rebar3 already exists, overwrite? [Yn] y
* creating /Users/jacob/.mix/rebar3
```

Now the `mix ecto.create` succeeds, and but `mix local.rebar3` reports it can't be found:

```
$ mix local.rebar3
** (Mix) The task "local.rebar3" could not be found. Did you mean "local.rebar"?
```

If this is working as intended, I can close the issue.  I nuked the `_build` folder on my 1.6.6 app and did `mix deps.compile` and that worked fine still.

**Comment by petermm** [comment]
adding the 3 was most likely mistake on my part - pardon the confusion ;-) - glad it worked out!
