### ISSUE TITLE
Hex.pm package contains old files

### ISSUE THREAD

**Issue by moogle19** [phoenixframework/phoenix#4862]
### Environment

* Elixir version (elixir -v): 1.14.0-dev
* Phoenix version (mix deps): 1.6.10
* Operating system: macOS

### Expected behavior
Phoenix should contain the new `phx.gen.auth/context_functions.ex` template containing the  
`delete_<%= schema.singular %>_session_token/1` function (see [source](https://github.com/phoenixframework/phoenix/blob/953d802da09e18939dfe21b0f6b6ca8a75bd8799/priv/templates/phx.gen.auth/context_functions.ex#L232))
This  was changed ~5 month ago.

### Actual behavior
It still contains the old template where the function signature is `delete_session_token/1` (see [hexpreview](https://preview.hex.pm/preview/phoenix/1.6.10/show/priv/templates/phx.gen.auth/context_functions.ex#L232))

If I run `mix hex.build` locally, the template are correct. 
One thing I noticed is that the version in the `mix.exs` wasn't updated in a while.
I don't know if it is problematic, when multiple archives with the same name are uploaded to hex.

**Comment by chrismccord** [comment]
The latest release is 1.6.10, which does not include those changes https://github.com/phoenixframework/phoenix/blob/v1.6.10/priv/templates/phx.gen.auth/context_functions.ex#L232

v1.7.0 will be released with the auth changes. Thanks!
