### ISSUE TITLE
Add finch to new project deps and configure swoosh

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#4876]
New apps need finch as a prod dependency with swoosh configured to use it:

    config :swoosh, :api_client, Swoosh.ApiClient.Finch

We also need to add it to the generated sup tree:

```
{Finch, name: Swoosh.Finch}
```

**Comment by wojtekmach** [comment]
Just one note,

> `{Finch, name: Swoosh.Finch}`

if users later add another Finch instance, either for another library or the app itself, they will get an error message that the child I’d, `Finch`, is already taken and they need to overwrite the id. The error message is pretty good but perhaps given this will be the new default and thus a lot of people will run into this we should do something about it. I believe a very easy solution is for Finch.child_spec to return the :id that matches the :name. Thoughts? Cc @sneako

**Comment by sneako** [comment]
Good point @wojtekmach ! I’m happy to add that feature. I should be able to get that done this evening.

**Comment by sneako** [comment]
Released in v0.13.0!

**Comment by christopherlai** [comment]
@chrismccord @bemesa21 let me know if there are any changes required on my PR
