### ISSUE TITLE
Host based routing

### ISSUE THREAD

**Issue by c-spencer** [phoenixframework/phoenix#489]
It would be useful to have some way to route on the host as well as the path, so that routing for subdomains or hosting multiple sites is straightforward.

Workaround suggested by chrismccord for now is to use a `:before` pipeline to add the host into the path for matching inside scope. (https://gist.github.com/chrismccord/94c65dc2b61631210d3d)

**Comment by arpieb** [comment]
Was just referred to this issue off Slack re vhost support in Phoenix - was wondering what the rationale behind using prefix vs least-to-most-specific hostname logic (a la DNS resolution) wasn't used?  A more common use case I've seen in many multihost builds I've been involved in is where there is default logic for a less-specific hostname, and overrides for more-specific.  For example, default behavior for "bar.com" and overrides for "*.bar.com" in the case of "vanity" hostnames.

**Comment by josevalim** [comment]
Great question @arpieb. The rationale is that we use domains in our applications often to handle different panels like "admin.", "settings." and so on. Also, we can only optimize prefix calls, it is quite hard to optimize suffix ones (but it can be done). :)

**Comment by whodidthis** [comment]
Out of interest, what if those multiple sites need SSL certificates? Or are multi-domain certs an easier option?

**Comment by jpiepkow** [comment]
Any way to wildcard route on subdomain. I am trying to route all requests with a subdomain to one set of functions(subdomains are dynamic) and route anything missing a subdomain to another set of functions.

**Comment by OvermindDL1** [comment]
@jpiepkow Like with the original example you can do it via a function plug.  :-)

**Comment by dsignr** [comment]
@jpiepkow Here's a very good article that I followed: http://blog.gazler.com/blog/2015/07/18/subdomains-with-phoenix/

**Comment by jpiepkow** [comment]
Thanks that answered my question perfectly.

**Comment by Kif11** [comment]
If I make use of `scope "/", host: "host.com" do` how do I go about testing in in dev environment with on `localhost`?
Editing `/etc/host` every time is not convenient. Since I still want to be able to access original domain.

**Comment by nicksergeant** [comment]
@Kif11 I'm handling that like this:

```
scope "/", host: host("mydomain.com") do
...

  def host(name) do
    with env <- Mix.env() do
      case env do
        :dev -> "local.#{name}"
        :prod -> name
      end
    end
  end

```
