### ISSUE TITLE
LiveView generator without gettext

### ISSUE THREAD

**Issue by oliver-kriska** [phoenixframework/phoenix#4898]
Hello,

what do you think about using `gettext` in templates for LiveView (or also others) generators. For example:
```
defp page_title(:show), do: "Show Something"
defp page_title(:edit), do: "Edit Somthing"
```
will be:
```
defp page_title(:show), do: gettext "Show Something"
defp page_title(:edit), do: gettext "Edit Somthing"
```
same for heex and other files. I can work on it if you think it's ok. There is already installed gettext and it's used in some code, why not in this?

**Comment by chrismccord** [comment]
We show light gettext usage in the generators, but don't use it everywhere. It's a balance between ease of use for newcomers, but introducing them to important ideas like localization. Thanks!
