### ISSUE TITLE
Phoenix Channels - inaccurate generator error message

### ISSUE THREAD

**Issue by Yarnus** [phoenixframework/phoenix#4899]
### Environment

* Elixir version (elixir -v): `Elixir 1.13.4 (compiled with Erlang/OTP 24)`

* Phoenix version (mix deps): I found it at `1.6.11` and investigated at master branch(`1.7.0`)

* Operating system: `MacOS 12.4`

### Expected behavior
- perform capitalization check for `channel name` in advance.
<img width="866" alt="image" src="https://user-images.githubusercontent.com/18589312/181487172-44fb65ad-d2e4-4fd0-9da1-965e16c8e8f0.png">

### Actual behavior
- scenario 1: (see below gen room) missing capitalization check although the generated files are fine. I am not sure if it is better to be consistent with the `phx.gen.socket`
- scenario 2: (see below gen kitchen) A more inner `phx.gen.socket` error message is thrown.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/18589312/181486370-1c1f5aca-9480-4355-96e4-66f31ee3ab4e.png">

Mainly because only the parameter length is checked here. 
(I've only recently started studying Phoenix and I'm not sure if is an issue. )

Thank you for browsing.

https://github.com/phoenixframework/phoenix/blob/1636787952c736816312387222347770c9228f38/lib/mix/tasks/phx.gen.channel.ex#L100-L106

**Comment by chrismccord** [comment]
Can you send  PR? Thanks!
