### ISSUE TITLE
Suggestion to add a `beforeMount` hook to extend developer's control.

### ISSUE THREAD

**Issue by coenbakker** [phoenixframework/phoenix#4900]
https://elixirforum.com/t/hooks-load-too-slowly-for-use-case-looking-for-a-sensible-alternative/49182/4

**Comment by chrismccord** [comment]
Please see my response on the thread. Thanks!

**Comment by coenbakker** [comment]
Maybe code organization can still be an argument? A beforeMounted hook might not be necessary to get the job done, but some other arguments can still be made.
