### ISSUE TITLE
Issue with deploying app on heroku

### ISSUE THREAD

**Issue by noopur0210** [phoenixframework/phoenix#4906]
I'm trying to deploy my phoenix app on heroku. But the following error is showing

-----> Building dependencies
Installing node modules
npm ERR! Linux 4.4.0-1104-aws
npm ERR! argv "/tmp/build_004bec59/.heroku/node/bin/node" "/tmp/build_004bec59/.heroku/node/bin/npm" "prune"
npm ERR! node v6.9.2
npm ERR! npm v3.10.9
npm ERR! path /tmp/build_004bec59/assets/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/build_004bec59/assets/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/build_004bec59/assets/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Please include the following file with any support request:
npm ERR! /tmp/build_004bec59/assets/npm-debug.log
! Push rejected, failed to compile Phoenix app.
! Push failed

Not sure what am I doing wrong... 

## Expected Behavior
I expect the app to deploy on heroku. This is the [github repo](https://github.com/noopur0210/counter), if anyone wants to see.

## Environment

OS Name: Windows 11

I am new to heroku and phoenix. Heroku is downloading node 6 and npm 3 by default. On my system, I have the latest versions of them running. I'm not sure where to create the `package.json` file, in the **root** folder or the **assets** folder? And what do I have to mention in the file?

**Comment by lkarthee** [comment]
May be post this issue in  https://elixirforum.com ?

**Comment by chrismccord** [comment]
Please try the elixir forums and slack for node issues as folks there will be more likely to be able to help. Thanks!
