### ISSUE TITLE
Yes, apologies. The docs have been fixed in master. It is a *compile* time config.

### ISSUE THREAD

**Issue by Hermanverschooten** [phoenixframework/phoenix#4910]
@josevalim in the current docs for Phoenix 1.6.11 on the SSL page, I do not find any mention of `force_ssl` being a compile time config.

_Originally posted by @josevalim in https://github.com/phoenixframework/phoenix/issues/3714#issuecomment-611411440_

**Comment by Hermanverschooten** [comment]
Would you be open to a PR to adapt the documentation, or should I hold off because there seems to be some changes in the make on runtime vs compile time config?

**Comment by josevalim** [comment]
Force_ssl is definitely a compile config and I don’t see it changing, so a PR is welcome!

in the future though Phoenix will warn if you change a compile config at runtime, but the docs likely help anyway.

**Comment by Hermanverschooten** [comment]
PR #4911 added.
