### ISSUE TITLE
Generator for the new LiveView based authentication system results in two Dialyzer errors

### ISSUE THREAD

**Issue by optikfluffel** [phoenixframework/phoenix#4916]
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): current master branch
* Operating system: macOS 12.5.1

### Expected behavior

```sh
git clone https://github.com/phoenixframework/phoenix
cd phoenix/installer
mix phx.new dev_app --dev
cd dev_app
mix phx.gen.auth Accounts User users
```

Add `{:dialyxir, "~> 1.2", only: [:dev], runtime: false}` to `mix.exs`.

```sh
mix deps.get
mix dialyzer
```

I expect there to be no errors.

### Actual behavior

```
lib/dev_app_web/live/user_registration_live.ex:18:exact_eq
The test <<_::144>> == <<>> can never evaluate to 'true'.
________________________________________________________________________________
lib/dev_app_web/live/user_settings_live.ex:44:exact_eq
The test <<_::192>> == <<>> can never evaluate to 'true'.
________________________________________________________________________________
```

**Comment by chrismccord** [comment]
We'd accept a PR that fixes this, but it's not exactly clear where it's coming from and I'm not a dialyzer user so it's not something I can prioritize at the moment. Thanks!

**Comment by optikfluffel** [comment]
I still haven't quite figured out why Dialyzer is complaining about those Verified Routes, but when I use a Map to build the query string the errors disappear.

`user_registration_live.ex`:

```diff
<.form
  :let={f}
  id="registration_form"
  for={@changeset}
  phx-submit="save"
  phx-change="validate"
  phx-trigger-action={@trigger_submit}
-  action={~p"/users/log_in?_action=registered"}
+  action={~p"/users/log_in?#{%{_action: "registered"}}"}
  method="post"
  as={:user}>
```

`user_settings_live.ex`:

```diff
<.form
  :let={f}
  id="password_form"
  for={@password_changeset}
-  action={~p"/users/log_in?_action=password_updated"}
+  action={~p"/users/log_in?#{%{_action: "password_updated"}}"}
  method="post"
  phx-change="validate_password"
  phx-submit="update_password"
  phx-trigger-action={@trigger_submit}>
```

**Comment by chrismccord** [comment]
Please try latest master. I marked the code as `generated: true` which I hope makes dialyzer happy. Let me know. Thanks!

**Comment by optikfluffel** [comment]
Yes, I can confirm that this did the trick.
Thanks for all the great work you're doing with Phoenix! 🐥🔥🧡
