### ISSUE TITLE
Phoenix.Router.forward/4 results in mix dialyzer warning

### ISSUE THREAD

**Issue by Hajto** [phoenixframework/phoenix#4926]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): phoenix 1.6.10 (Hex package) (mix)
* Operating system: MacOs 12.5 (21G72)

### Expected behavior
No warning if the code is valid

### Actual behavior
Call to:
```
forward "/", MyApp.Router
```

results in:
```
'error' can never match the type 
          {#{'conn' := 'nil',
             'log' := 'debug',
             'path_params' := map(),
             'pipe_through' := [any()],
             'plug' := atom(),
             'plug_opts' := atom() | [any()],
             'route' := nonempty_binary(),
             'log_function' => 'mount',
             'log_module' => atom(),
             'phoenix_live_view' => {_, _, _, _}},
           fun((map(), map()) -> map()),
           fun((_) -> any()),
           {atom(), atom() | [any(), ...] | {_, _, _}}}
```

**Comment by chrismccord** [comment]
Please try master if you are able, and let us know if it still warns. I'm not a dialyzer user so this is not something I can prioritize, but I'd happily review a PR that addresses this. Thanks!

**Comment by Hajto** [comment]
In case someone with bigger knowledge than me decides to fix this warning. It happens only with "/".
