### ISSUE TITLE
Phx.new with master branch is creating broken app

### ISSUE THREAD

**Issue by cvkmohan** [phoenixframework/phoenix#4930]
If a new application is created using https://github.com/phoenixframework/phoenix/blob/master/installer/README.md, we are getting a broken application. The error says unable to compile phoenix live dashboard. Unable to find assigns is the error shown.

**Comment by kelvinst** [comment]
I tried out just executing the install instruction from the mentioned README, run `mix phx.new test`, and `mix compile` and it actually worked. Can you link the Elixir and OTP version you're using? Also, maybe link the whole `mix.lock` file from the generated app?

**Comment by cvkmohan** [comment]
@kelvinst Thanks for the response.  I created a new app and here is the link https://github.com/cvkmohan/new_app 
```
elixir 1.14.0-rc.1-otp-25
erlang 25.0.4
```
elixir and erlang versions.

**Comment by cvkmohan** [comment]
I think present `master` branches of `phoenix` and `phoenix_live_view` have some major reorg going on. If you put them in your `mix` file, we are getting errors.

**Comment by chrismccord** [comment]
Master is unreleased and we are indeed in the middle of work in several areas so this is expected. Thanks!
