### ISSUE TITLE
mix phx.routes and dev env "no route found page" do not handle forwarded routers.

### ISSUE THREAD

**Issue by Hajto** [phoenixframework/phoenix#4931]
### Environment

- Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 24)
- Phoenix version (mix deps): phoenix 1.6.10 (Hex package) (mix)
- Operating system: MacOs 12.5 (21G72)

### Expected behavior
Prints out current absolute path in forwarded router

### Actual behavior
prints path relative to forwarded router

![Screenshot 2022-08-31 at 11 31 06](https://user-images.githubusercontent.com/8336429/187647251-03639001-2f94-45ec-aedd-bae7f501709a.png)

Based on this screenshot I would expect to list it as `/v1/openapi` where as the actual path is `/api/v1/openapi`.

`mix phx.routes` also has not ideal output:
```
                                *       /api                                                                   HawkuDataWeb.Router []
```

I would expect it recursively print all the paths.

**Comment by chrismccord** [comment]
We'd evaluate a PR that improves this for forwarded router, but you can forward to any plug so it may be overly complex. Thanks!
