### ISSUE TITLE
`websocket: [fullsweep_after: ...]` not applied to websocket processes with high memory use 

### ISSUE THREAD

**Issue by balysv** [phoenixframework/phoenix#4933]
### Environment

```
erlang: 24.3.4
elixir: 1.13.0
Cowboy: 2.9.0
plug_cowboy: 2.5.2
phoenix: 1.6.9
OS: Ubuntu 22.04
```

Related issue: https://github.com/phoenixframework/phoenix/issues/4613

### Expected behavior

Setting `websocket: [fullsweep_after: 0]` on sockets should ideally apply the process flag to the `{:cowboy_websocket, :loop, 3}` process that has high memory usage and often needs a forced garbage collection. 

### Actual behavior

When dealing with very large payloads `{:cowboy_websocket, :loop, 3}`  processes accumulate memory usage that lead to OOM errors.
![image (3)](https://user-images.githubusercontent.com/6113842/188085511-7be40816-bdce-4cb0-9f70-fccad3ecfed8.png)

`fullsweep_after` flag introduced [here](https://github.com/phoenixframework/phoenix/blob/bd567cd8dee1793c72a8e8746f2d1be4a69ae885/lib/phoenix/endpoint/cowboy2_handler.ex#L37) is only applied to children of the offending processes. Running manual GCs of said processes temporarily fixes the issue. 

Inspecting process tree at the time `:fullsweep_after` is applied:

```
[
  ...
  dictionary: [
     "$initial_call": {:cowboy_stream_h, :request_process, 3},
     "$ancestors": [#PID<0.5297.0>, ...]
  ],
  garbage_collection: [
    fullsweep_after: 0,
    ...
  ]
]
```

Parent (the one with high memory usage)
```
iex(14)> Process.info(pid(0, 5297, 0))
[
  current_function: {:cowboy_websocket, :loop, 3},
  dictionary: [
    "$initial_call": {:cowboy_clear, :connection_process, 4},
    "$ancestors": [...]
  ],
  trap_exit: true,
  garbage_collection: [
    fullsweep_after: 65535, <<< would like to have this overriden to 0
    ...
  ]
]
```

Any other suggestions on how to deal with this without manual intervention are welcome.

**Comment by josevalim** [comment]
We set this option here: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/cowboy2_handler.ex#L36

Please try debugging if that code is indeed being called in your case or not.

**Comment by balysv** [comment]
Yup, it is called and working as intended for the process it's called on. However, it's not called on the process that has the high memory usage (it is the parent of processes that call https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/cowboy2_handler.ex#L36)

**Comment by balysv** [comment]
Thanks a lot! I can confirm this is now behaving as intended.

**Comment by machakos23** [comment]
Thanks for reporting @balysv and the speedy fix @josevalim. Will this make it into 1.6.x?
