### ISSUE TITLE
redirected_params(conn) gives an error when using forwarded routes

### ISSUE THREAD

**Issue by himangshuj** [phoenixframework/phoenix#4934]
### Environment

* Elixir version (elixir -v): Elixir 1.13.4 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.6.7
* Operating system: Mac OS

### Expected behavior
      assert %{id: id} = redirected_params(conn) should work for the controller for both forwarded and normal routes. 

### Actual behavior
      assert %{id: id} = redirected_params(conn) fails when I put the controller under forwarded routes
### Source of Bug
Phoenix.Router.route_info(router, "GET", path, host ) - this method gives an error because it ignores the script_name "admin" when cycling through the routes 
```
 IO.inspect(Phoenix.Router.route_info(router, "GET", path, host )) ## errors out
 IO.inspect(Phoenix.Router.route_info(router, "GET", String.replace(path, "/admin",""), host )) ## admin is the forwarded prefix, this code works fine
```

**Comment by josevalim** [comment]
We most likely have information in the `conn` that it was a forwarded route. So we need to leverage that before calling `route_info`.

**Comment by himangshuj** [comment]
Sure, happy to help in any way . Does the conn have the information on the top-level scope for me it looks ```  scope "/", PlatformWeb.Admin, as: :admin do``` and the forward code is ```    forward "/admin", PlatformAdminRoutes, path: "/admin"```

**Comment by josevalim** [comment]
Check under `conn.private`. There is some router information in there, including the current router and the mounts it has seen.

**Comment by himangshuj** [comment]
```  :phoenix_router => PlatformWeb.PlatformAdminRoutes,```
```  PlatformWeb.PlatformAdminRoutes => {["admin"], %{}},```
this is present in conn.private if you are okay with using these two variables, I can try to submit a PR

**Comment by josevalim** [comment]
Yes, it is ok :) they are private for Phoenix, so it is ok for phoenix to use it. :)
