### ISSUE TITLE
Phoenix npm package - does not work with `recoil`

### ISSUE THREAD

**Issue by nichita-pasecinic** [phoenixframework/phoenix#4953]
### Environment

* Elixir version (elixir -v): Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] 
* Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): {:phoenix, "~> 1.6.12"},
* Operating system: Win 10 Pro

### Expected behavior
If Socket is being saved globally in a Recoil store it should be accessible from any components without any errors

### Actual behavior
after setting an recoil atom to a Socket value, a few errors are thrown in console

```
socket.js:322 Uncaught TypeError: Cannot assign to read only property 'closeWasClean' of object '#<Socket>'
    at Socket.onConnOpen (socket.js:322:10)
    at conn.onopen (socket.js:232:35)
```

atom
```ts
export const socketAtom = atom<Socket | undefined>({
  key: 'socketAtom',
  default: undefined,
});
```

usage
```ts
  const [socket, setSocket] = useRecoilState(socketAtom);

 const tryConn = () => {
    const s = new Socket('ws://localhost:5000/socket', {
      params: { ...credentials },
    });
    s.connect();
    setSocket(s);
  }
```

and after the connection is established the error above is thrown 
![image](https://user-images.githubusercontent.com/98735377/190903950-a68dfe8a-5675-4cfc-aeac-798edd83ca90.png)

Using react v17.2 & vitejs

**Comment by nichita-pasecinic** [comment]
In case of a failled connection it will throw such an error 
![image](https://user-images.githubusercontent.com/98735377/190904729-551de9d4-1016-47b9-ab40-718fd03409a3.png)

**Comment by chrismccord** [comment]
Fixed. Thanks you!

**Comment by chrismccord** [comment]
Sorry I thought this was #4943, but this is not a phoenix issue and rather needs to be handled in recoil. Thanks!

**Comment by nichita-pasecinic** [comment]
Thanks @chrismccord, I've opened a issue on `recoil` github, I'd appreciate very much if you could comment on it to give some insides of what should be addressed to identify the bug
