### ISSUE TITLE
Adding a deletion option to `mix phx.gen.auth`

### ISSUE THREAD

**Issue by tlietz** [phoenixframework/phoenix#4954]
I posted a thread about this on the mailing list, but new posters need to be whitelisted, and I'd imagine there are a lot of emails to filter through, so I'll try here.

In almost all web apps, there is a way for a user to delete themselves. I would like to work on adding an option to `mix phx.gen.auth` to implement this functionality if it's a good fit for Phoenix.  It could be called something like `--delete`.

Alternatively, `mix phx.gen.auth` could add the user deletion code by default, in which case a `--no-delete` option can be used to skip that part of the code.

**Comment by chrismccord** [comment]
We have no plans to add such a feature, but it's a fine feature to add to your own app :)

The generators are starting points, so if you're requirements include deleting users, by all means add it. This would also make a great blog post to show with the community. Thanks!
