### ISSUE TITLE
Add example on how to use `slot :option` for select input

### ISSUE THREAD

**Issue by jsmestad** [phoenixframework/phoenix#4968]
I could not sort out how to use the [new slot :option for select inputs](https://github.com/phoenixframework/phoenix/blob/22ef871312bd06fa591c2da04d32949ebc77f750/priv/templates/phx.gen.live/components.ex#L252). I think adding an example to the function doc would be helpful. Happy to make a PR if someone can explain how to use it to me first :joy:

**Comment by chrismccord** [comment]
```heex
<.input type="select" ...>
  <:option value="1">One</:option>
  <:option value="2">Two</:option>
</.input>
