### ISSUE TITLE
Make phoenix templates become function components

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#4975]
* [x] Extract `phoenix_template` to its own package
* [x] Allow root layout, layout, and view to be specified per format (and support `use Phoenix.Controller, formats: [:html, :json]`)
* [x] Deprecate passing a string as template to root layout or layout
* [x] Add `embed_templates` to `Phoenix.Component`
* [x] Move rendering logic from `Phoenix.View` (`render/4`, `render_to_iodata/4`, `render_to_string/4`) to `Phoenix.Template` and make controllers use it
* [x] Convert `phx.new` and `phx.gen` to use `def html` (with `use Phoenix.Component`) and instead of `def view` (how are we going to test error views in `phx.new`?)
* [x] Replace `phoenix_view` by `phoenix_template` as a dep :D (actually, we should keep `phoenix_view, ~> 1.2` as an optional dependency because if someone tries to use `phoenix_view 1.1`, the different Phoenix.Template impls will conflict)
* [ ] Update guides!

More context can be found at: https://gist.github.com/josevalim/c5684c210b0b8a323aa70f283d9cb8c5

**Comment by Fudoshiki** [comment]
@josevalim Hello, how can I use html partials in this paradigm?

**page_live.html.heex**

```elixir
<%= PageView.render(@template <> ".html", assigns) %>
```

**Comment by josevalim** [comment]
`render("_form.html", changeset: @changeset, user: @user)` would become something like `<.form changeset={@changeset} user={@user} />`.

**Comment by Fudoshiki** [comment]
It's not form partial, I want render template dynamicaly

**Comment by josevalim** [comment]
@Fudoshiki you can still do it the old way then. The thing about function components is that they are just functions, so you can still define:

```
def render("foo.html", assigns) do
  ~H"""
  """
end

def render("bar.html", assigns) do
  ~H"""
  """
end
```

Or even do this:

```elixir
def render("foo.html", assigns), do: foo(assigns)
def render("bar.html", assigns), do: bar(assigns)
```

**Comment by Fudoshiki** [comment]
How can I render template which is nested in subfolder

`embed_templates("page_html/**/*")` ?

`lib/controllers/page_html/invites/show.html.heex`

**Comment by josevalim** [comment]
It is not possible right now, but we could support a prefix, so you would do:

  embed_templates "page_html/invites/*", prefix: :invites

And then you have `invites_show` and `invites_index`.

**Comment by Fudoshiki** [comment]
> It is not possible right now, but we could support a prefix, so you would do:
> 
> embed_templates "page_html/invites/*", prefix: :invites
> 
> And then you have `invites_show` and `invites_index`.

Do I need new `PageHTML` module per template now?

`PageHTML.Index`
`PageHTML.Invite` with `page_html/invite/index.html.heex`
`PageHTML.Invite.Show`  with `page_html/invite/show/index.html.heex`
etc...

**Comment by Fudoshiki** [comment]
Or include in `PageHTML` mudule multiple `embed_templates`?

```elxiir
defmodule MyAppWeb.PageHTML do
  use EvernowWeb, :html

  embed_templates("page_html/*")
  embed_templates "page_html/invites/*", prefix: :invites

end
```

**Comment by chrismccord** [comment]
No you can embed as many directories into a single module as you want. The function name will be whatever the file name is, so josé's example could be supported today if you named your file `page/invites/invites_show.html.heex` and so on.

**Comment by josevalim** [comment]
Closing, just guides missing!
