### ISSUE TITLE
Changelog missing for phoenix 1.6.12 and 1.6.13

### ISSUE THREAD

**Issue by ethangreenberg** [phoenixframework/phoenix#5007]
<img width="1216" alt="Screen Shot 2022-10-05 at 6 09 10 PM" src="https://user-images.githubusercontent.com/15315492/194191670-a325a5a2-4d28-4c96-8930-7f79aa438ea6.png">

**Comment by petermm** [comment]
already a PR/fix here https://github.com/phoenixframework/phoenix/pull/4996
