### ISSUE TITLE
Duplicate flash messages in root/app templates

### ISSUE THREAD

**Issue by shamanime** [phoenixframework/phoenix#5011]
### Environment

* Elixir version (elixir -v): 1.14
* Phoenix version (mix deps): from master
* Operating system: Linux

### Expected behavior

No duplicate flash messages in root and app templates.

### Actual behavior

The browser is complaining about duplicate IDs "#disconnected" on the page and I found out this issue.

The commit https://github.com/phoenixframework/phoenix/pull/4955/files#diff-2076b17871608fced1ef34220b23da5c55a927e475ddd04a9d74cb87ba119a1f added `plug :put_layout, false when action in [:index]` to PageController so we can get a nice landing page. This led to the duplicate flash messages being inserted on https://github.com/phoenixframework/phoenix/pull/4820/files#diff-e34c19dd158377da0ec2b93b7217bd54bcc8cc2e99d17cb8264a1abd882bb600 to get the PR working.

This is a leftover that needs to be fixed.

I'll inspect the issue and open a PR.

**Comment by mindreframer** [comment]
I hit the same error 3 days ago.

**Comment by Eiji7** [comment]
That's probably because both `root.html.heex` and `app.html.heex` renders `flash` massages.

**Comment by jeregrine** [comment]
Oh man I searched the PRs but I didn't go through issues. Sorry!
