### ISSUE TITLE
Logarithmic memory growth if using `compress: true` on socket

### ISSUE THREAD

**Issue by Zarathustra2** [phoenixframework/phoenix#5015]
### Environment

Elixir version (elixir -v):
```
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:4:1] [ds:4:1:10] [async-threads:1] [jit]

Elixir 1.13.0 (compiled with Erlang/OTP 24)
```
Phoenix version (mix deps):
```
{:phoenix, "~> 1.6.0"}
```

### Behavior

With `compress: true`, i.e. `socket("/socket", MyApp.Socket, websocket: [compress: true])`
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/33396162/194964779-1d134e23-ede9-4565-9bcd-ae0880510349.png">

----------------------------------------

Without `compress: true` i.e. socket("/socket", MyApp.Socket)`:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/33396162/194964867-c8fdfb07-9f75-4096-af3f-4f4109141424.png">

-----------------------

Let me know what kind of other information I should provide. I tried running `:recon.bin_leak(10)` but that did not change anything.
`:observer_cli.start` did also not spot any process with high memory usage. 

Not sure what else I should try to debug/troubleshoot why adding `compress: true` makes such an insane difference in memory usage

**Comment by chrismccord** [comment]
Have you tried experimenting with the `:fullsweep_after` websocket configuration?:

        socket "/socket", AppWeb.UserSocket,
            websocket: [
              fullsweep_after: ...
            ]

>    `:fullsweep_after` - the maximum number of garbage collections
      before forcing a fullsweep for the socket process. You can set
      it to `0` to force more frequent cleanups of your websocket
      transport processes. Setting this option requires Erlang/OTP 24

**Comment by Zarathustra2** [comment]
Hey Chris, 

Thanks for the suggestion, I just tried it but unfortunately same result:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/33396162/195203317-ec823ca3-e122-4e7b-aa87-f260d7c7963d.png">


My settings had been: `websocket: [compress: true, fullsweep_after: 0]`

**Comment by chrismccord** [comment]
does it grow unbounded over time or settle down? It's going to be difficult to track down on its own so if you could make a minimal app that reproduces the memory growth it would be super helpful. Thanks!

**Comment by Zarathustra2** [comment]
It will settle down after some time. I wish I could provide more info but so far had no access finding anything out, I am also wondering if there is something else going on that might get in the ways of the compress option and causing it. 

I will try to reproduce it in a minimal app

**Comment by chrismccord** [comment]
The VM will be greedy with memory under load, so if you're not seeing unbounded growth it may not be anything problematic.

**Comment by Zarathustra2** [comment]
ohhhh, great point I did not think about that. I have the requests for my pods set to 1GB actually so that might be it, let me test later how the memory looks like with reduced requests! Will report back but that is a great point

**Comment by machakos23** [comment]
@Zarathustra2 have you seen this [issue](https://github.com/phoenixframework/phoenix/issues/4933)? I wonder what would happen if you repeated your test with `websocket: [compress: true, fullsweep_after: 0]` after adding the changed phoenix [code](https://github.com/phoenixframework/phoenix/commit/bf1f2bfc9392c515081b1614df1b507f2c120fde) to your deps. You should be able to just drop the relevant [file](https://github.com/phoenixframework/phoenix/blob/bf1f2bfc9392c515081b1614df1b507f2c120fde/lib/phoenix/endpoint/cowboy2_handler.ex) in to overwrite the existing one and re-run.
