### ISSUE TITLE
mix phx.digest broken for umbrella projects

### ISSUE THREAD

**Issue by elliottneilclark** [phoenixframework/phoenix#5017]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): master
* Operating system: linux

### Expected behavior

We have an umbrella app with a mix of phoenix apps and raw otp apps. Previously we ran `mix do phx.digest, compile, release my_release_name` and everything would work. The apps without a priv/static would log warnings:

```
 The input path "priv/static" does not exist
 ```
 However it would still return success and continue on.

### Actual behavior

#4999 Changed the behavior to return non zero, so apps executing mix pxh.digest are now returning an error. Causing the same log error and then stopping. This might be expected behavior and I need to change compilation steps, but if so some documentation in the release notes would be nice.

**Comment by josevalim** [comment]
Fixed in main!
