### ISSUE TITLE
Phoenix JS version displayed on npmjs.org and with `npm outdated` is not the lastest version

### ISSUE THREAD

**Issue by rmonteil** [phoenixframework/phoenix#5036]
### Environment

Phoenix JS

### Expected behavior

The Phoenix JS version displayed on [npmjs.org](https://www.npmjs.com/package/phoenix) should be the last one (v1.6.14).

### Actual behavior

It currently displays v1.3.5 as the latest.
In the "xx versions" tab, it seems that the `latest` tag is wrongly attributed:
![image](https://user-images.githubusercontent.com/18598001/196450348-1242cc64-ae64-4095-b83e-527877315415.png)

Also, when executing `npm outdated`, we can see the same behavior:
![image](https://user-images.githubusercontent.com/18598001/196451149-b658f022-65f6-48a4-9995-aa17c0e16cc5.png)

**Comment by chulkilee** [comment]
Apparently those versions were released in the same day, but `1.3.5` was the last one.

From https://docs.npmjs.com/cli/v8/commands/npm-dist-tag

> Publishing a package sets the latest tag to the published version unless the --tag option is used. For example, npm publish --tag=beta.

To fix it, the npm package maintainer should set it manually. From https://docs.npmjs.com/adding-dist-tags-to-packages)

```
npm dist-tag add phoenix@1.6.14 latest
```

**Comment by chrismccord** [comment]
Done. Thanks!
