### ISSUE TITLE
Missing import in my_app_web.ex

### ISSUE THREAD

**Issue by paddleman** [phoenixframework/phoenix#5051]
### Environment

* Elixir version: Elixir 1.14.0 (compiled with Erlang/OTP 25):
* Phoenix version (mix deps): phoenix 1.7.0-dev (https://github.com/phoenixframework/phoenix.git) (mix) locked at 0cec3cd
* Operating system: Ubuntu 22.04

Ran ```mix phx.gen.auth Accounts User users```, selecting the Live View option.

Generated code was showing errors in some forms related to the input_value function not being available.
```heex
<.input
          field={{f, :password}}
          type="password"
          label="Password"
          value={input_value(f, :password)}
          required
        />
```
Apparently the latest phoenix 1.7 build does not import **Phoenix.HTML.Forms** into the my_app_web.ex module -- specifically into to the ```defp html_helpers```  function.  

including ```import Phoenix.HTML.Forms``` solves the issue.

Not sure how were in the codebase this file is generated upon app creation to submit a PR.

**Comment by mcelaney** [comment]
It was removed from `installer/templates/phx_umbrella/apps/app_name_web/lib/app_name.ex` in a [commit two days ago](https://github.com/phoenixframework/phoenix/commit/ace80f8c992c3d3d520b9bf351ec6f9d8f74d78f#diff-3ac60f531761178360198a77f56d20d74de4459c1505cd8a85243ef7e6dbbced)

Looks like there may be a solution here: https://github.com/phoenixframework/phoenix/pull/5050
