### ISSUE TITLE
Dependency mismatch in new 1.7.0-rc0 umbrella project

### ISSUE THREAD

**Issue by lschmierer** [phoenixframework/phoenix#5079]
I was going to try out the new 1.7.0-rc0 umbrella project template.

I created new umbrella project `mix phx.new pfx --umbrella` and tried running it with `mix phx.server`.
I got the error shown below.

### Environment

* Elixir version (elixir -v): Elixir 1.14.1 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.0-rc.0
* Operating system: macOS 12.3

### Expected behavior
Create new umbrella project `mix phx.new pfx --umbrella` and run with `mix phx.server`.
The application is expected to start up .

### Actual behavior

```
Unchecked dependencies for environment dev:
* phoenix (Hex package)
  the dependency phoenix 1.7.0-rc.0

  > In apps/pfx_web/mix.exs:
    {:phoenix, "~> 1.7.0-rc.0", [env: :prod, repo: "hexpm", hex: "phoenix", override: true]}

  does not match the requirement specified

  > In deps/phoenix_live_view/mix.exs:
    {:phoenix, "~> 1.6.15 or ~> 1.7.0", [env: :prod, hex: "phoenix", repo: "hexpm", optional: false]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

**Comment by lschmierer** [comment]
Easiest fix (workaround ?) is to add `{:phoenix, "~> 1.7.0-rc.0", override: true},` to the top-level `mix.exs` for now.

**Comment by Eiji7** [comment]
@chrismccord I can reproduce this as well. `phoenix` installer template `phx_umbrella/mix.exs` needs to be improved. Currently it adds proper `phoenix` dependency, but only when `dev` flag is set.

Looks like we need to add one more condition for overriding `phoenix` dependency as otherwise such dependency would have a conflict between `apps` (here `example_web/mix.exs`) and `deps` (here `phoenix_live_view/mix.exs`).

```diff
-      # required to run "mix format" on ~H/.heex files from the umbrella root
-      <%= if @dev do %><%= @phoenix_dep_umbrella_root %>,
+      <%= if @dev or String.contains?(@phoenix_dep_umbrella_root, "-rc.") do %><%= @phoenix_dep_umbrella_root %>,
+      # required to run "mix format" on ~H/.heex files from the umbrella root
```

**Comment by lschmierer** [comment]
Thank you for your great work!
