### ISSUE TITLE
Phoenix 1.7 `<.input/>` component does not work with `datetime-local` type

### ISSUE THREAD

**Issue by adriansalamon** [phoenixframework/phoenix#5098]
### Environment

* Elixir version (elixir -v): Elixir 1.14.1
* Phoenix version (mix deps): 1.7.0-rc.0
* Operating system: MacOS

### Expected behavior

Working `<.input type="datetime-local" />` component.

### Actual behavior

Steps to reproduce:

- Generate a LiveView with a datetime field, eg. `mix phx.gen.live Schedule Meeting meeting start_time:utc_datetime`
- Go to `http://localhost:4000/meeting` and create a new meeting with a time
- Edit the created meeting.

The datetime-local input is not displayed with the saved information from the database. This is because the time-string needs to be formatted properly, see https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/form.ex#L758 for example.

Perhaps this should be fixed in the Phoenix.HTML library making the function `Phoenix.HTML.Form.input_value/2` work for DateTime inputs?

**Comment by josevalim** [comment]
Related to #5077.

**Comment by jeregrine** [comment]
This was fixed in https://github.com/phoenixframework/phoenix/pull/5107
