### ISSUE TITLE
mix phx.gen.auth renders undefined for both actions and validation messages

### ISSUE THREAD

**Issue by jeepers3327** [phoenixframework/phoenix#5099]
### Environment

* Elixir version (elixir -v): Elixir 1.14.1 (compiled with Erlang/OTP 25)

* Phoenix version (mix deps): phoenix 1.7.0-rc.0
* Operating system: EndeavourOS Linux x86_64

### Expected behavior
Buttons and validation messages should render properly

### Actual behavior
Buttons and validation messages returns undefined

Steps to reproduce
1. Create a new phoenix project with latest installer `mix archive.install hex phx_new 1.7.0-rc.0`
2. Generate liveview auth using `mix phx.gen.auth Accounts User users`

**User Registration Page**:  Validation message and submit button returns undefined.
![1](https://user-images.githubusercontent.com/70475641/201276246-648c2eae-f444-44d7-9c20-89510b223ff2.png)

If you also navigate to `/users/log_in` route through **Sign In** link in `/users/register` the submit button renders undefined
![2](https://user-images.githubusercontent.com/70475641/201276860-7420554c-b1c3-47bc-82b1-0a551da2aa18.png)

**Comment by chrismccord** [comment]
This is not something I can recreate. Are you positive this was for a fresh 1.7.0-rc project and not something you upgraded yourself with state js client? If you can provide more info or steps to reproduce I can take another look, but this looks like a bad js client to me. Thanks!
