### ISSUE TITLE
deps error when creating new umbrella project in 1.7.0rc

### ISSUE THREAD

**Issue by ZelvaMan** [phoenixframework/phoenix#5110]
### Environment

* Elixir version (elixir -v):
   Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]
   Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps):
  phoenix 1.7.0-rc.0 (Hex package) (mix)
  locked at 1.7.0-rc.0 (phoenix) ed503f6c
* Operating system:
  Windows 10 Home 21H2

### Expected behavior
 Create new project with `mix phx.new project_name --umbrella`
 and be able to run it.

### Actual behavior
 When i create new phoenix project without --umbrella everything is working as expected.
 When i create new project with umbrella and try tu run it i get dependency error:
```
Unchecked dependencies for environment dev:
* phoenix (Hex package)
  the dependency phoenix 1.7.0-rc.0

  > In apps/test_project_u_web/mix.exs:
    {:phoenix, "~> 1.7.0-rc.0", [env: :prod, repo: "hexpm", hex: "phoenix", override: true]}

  does not match the requirement specified

  > In deps/phoenix_live_view/mix.exs:
    {:phoenix, "~> 1.6.15 or ~> 1.7.0", [env: :prod, hex: "phoenix", repo: "hexpm", optional: false]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

deps in mix.exs in project_name_dev 
```
    [
      {:phoenix, "~> 1.7.0-rc.0", override: true},
      {:phoenix_ecto, "~> 4.4"},
      {:phoenix_html, "~> 3.0"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.18.3"},
      {:heroicons, "~> 0.5"},
      {:floki, ">= 0.30.0", only: :test},
      {:phoenix_live_dashboard, "~> 0.7.2"},
      {:esbuild, "~> 0.5", runtime: Mix.env() == :dev},
      {:tailwind, "~> 0.1.8", runtime: Mix.env() == :dev},
      {:telemetry_metrics, "~> 0.6"},
      {:telemetry_poller, "~> 1.0"},
      {:gettext, "~> 0.20"},
      {:test_project_u, in_umbrella: true},
      {:jason, "~> 1.2"},
      {:plug_cowboy, "~> 2.5"}
    ]
```

Hope this is enough information.

**Comment by jrissler** [comment]
I get the same error on macOS Ventura 13.0.1 (22A400) for a newly generated umbrella project.

**Comment by optikfluffel** [comment]
This is probably because of `{:phoenix_live_view, ">= 0.0.0"}` in the root level `mix.exs` in your umbrella apps. Could you try whether adding ` {:phoenix, "~> 1.7.0-rc.0", override: true}` in there helps for now?

**Comment by josevalim** [comment]
Yes, this has been fixed in master. Keeping it open for guidance.

**Comment by josevalim** [comment]
Fixed in rc1.
