### ISSUE TITLE
CoreComponents might need the @rest global attribute?

### ISSUE THREAD

**Issue by loonfly** [phoenixframework/phoenix#5132]
I have updated to latest version of Phoenix v1.7.0-rc.0 and have been feeling awesome using the verified routes and new features like tailwind components. 

But i found something missing in some CoreComponents like the <.table /> and the <.list /> and etc. If we use <.table phx_update="prepend" /> it doesn't work because the table component doesn't assign the global attribute to the <.table />

is this intentional and should be done on our own OR this should be included in the CoreComponents?

the default <.table /> has been a standard to

Assume this issue a Suggestion or a Question.  

thanks with love for the community

**Comment by chrismccord** [comment]
The core components are a starting point, so add the rest attribute and whatever else you need as you go. Thanks!
