### ISSUE TITLE
Compiling many files when edit any file

### ISSUE THREAD

**Issue by diegonogueira** [phoenixframework/phoenix#5135]
* Elixir: 1.14.1
* Phoenix: 1.6.15
* Operating system: Ubuntu

When I changed any file (*.ex, *.heex, *_test.exs), it compiles 112 files... 
If I remove the line `plug(:put_root_layout, {AppWeb.LayoutView, :root}` in router.ex, It works, compile 1 file only.

**Comment by chrismccord** [comment]
Check out the `mix xref` task to help identify where your compile-time dependencies are coming from https://hexdocs.pm/mix/Mix.Tasks.Xref.html
