### ISSUE TITLE
Function component child of a looped anchor produces incorrect result

### ISSUE THREAD

**Issue by jadengis** [phoenixframework/phoenix#5140]
Rendering an anchor tag with a for loop that contains a nested function component produces behavior that is clearly wrong.

For example the following template:

```html
<div class="px-4 py-10 sm:py-28 sm:px-6 lg:px-8 xl:py-32 xl:px-28">
  <h1 class="text-3xl">Rendering Bug</h1>
  <section class="grid grid-flow-row sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <a :for={post <- @posts}>
      <.card post={post}></.card>
    </a>
  </section>
</div>
```

With the following component definitions:

```elixir
  def author(assigns) do
    ~H"""
    <div class="flex flex-row items-center">
      <img
        class="rounded-full h-12 w-12 m-0 border border-accent"
        src={@author.image_url}
        alt="Author Profile Picture"
      />
      <div class="flex flex-col flex-auto pl-4">
        <div class="text-base font-bold">
          <a href={@author.url}>
            <%= @author.name %>
          </a>
        </div>
        <div class="text-sm text-secondary">
          <span>
            <%= Calendar.strftime(@date, "%b %d, %Y") %>
          </span>
        </div>
      </div>
    </div>
    """
  end

  def card(assigns) do
    ~H"""
    <section class="block rounded p-3 h-full transition hover:bg-white hover:shadow-md hover:text-primary">
      <div
        class="bg-center bg-cover h-44 mb-2 border border-divider"
        style={@post.image_url && "background-image: url('" <> @post.image_url <> "')"}
      >
        <div class="flex flex-col">
          <h2 class="text-xl font-bold"><%= @post.title %></h2>
          <p class="mb-5 text-secondary"><%= @post.subtitle %></p>
        </div>
        <.author :for={author <- @post.authors} author={author} date={@post.date}></.author>
      </div>
    </section>
    """
  end
```

Produces the following output in the browser:

![Screenshot from 2022-11-29 23-54-14](https://user-images.githubusercontent.com/13421336/204740286-4cda7684-7673-4bc5-997e-56fdcac3ee52.png)

As you can see, that are a bunch of empty `a` tags added to the DOM as siblings of the rendered card. If I replace `a` with `div` I do not see the same behavior. This is breaking the grid layout as can be seen in the image.

The following repo contains a reproduction of this issue: https://github.com/jadengis/phoenix-a-tag-bug.

To reproduce run `mix phx.server` and go to `localhost:4000` in your browser. 

### Environment

* Elixir version (elixir -v): Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns], Elixir 1.14.0 (compiled with Erlang/OTP 25)

* Phoenix version (mix deps): Phoenix 1.7.0-rc0
* Operating system: Pop_Os 22

### Expected behavior

The looped anchor tag will contain the function component as a child.

### Actual behavior

The looped anchor tag is a sibling of the function component and is also copied as a sibling to every DOM node in the function component.

**Comment by chrismccord** [comment]
This sounds like you are rendering invalid HTML as nested anchors are not valid, and the browser is trying to unwrap it. You can find out by curl'ing the webpage and inspecting the HTML, or running LiveViewTest and rendering it to do the same. I don't believe this is an issue on our side, but let us know if you have more information. Thanks!
