### ISSUE TITLE
`<.input />` has different behaviour around `true` than phoenix_html helpers had

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#5141]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps): 1.7.0-rc.0
* Operating system:

### Expected behavior

An input value of `true` renders a value, at best `"true"` like before.

### Actual behavior

An input value of `true` renders as `value=""` or `value`, due to how HEEx works.

**Comment by chrismccord** [comment]
This is expected. If folks want literal "true" to be in the input, they can do `value="true"`. If the value is coming from an assign that the caller passes, the caller will either need to `to_string` it or the internal input can to_string, but I don't think there's a change here that we need to make. Thanks!

**Comment by LostKobrakai** [comment]
`true` is the value produced by `Phoenix.HTML.input_value` for a `:boolean` changeset field. This is nothing in my control at that point.

**Comment by chrismccord** [comment]
What type of input are you using in this case?

**Comment by LostKobrakai** [comment]
I see I should've been less sparse on the details. Sorry about that.

I've been using `type="hidden"` to set a virtual `:deleted` flag.

**Comment by chrismccord** [comment]
In that case, I think it makes the most sense to coerce to string yourself, because you specifically want it to be `"true"`. You could also define an `input` clause which matches on type="hidden" for special case behavior.

**Comment by LostKobrakai** [comment]
@chrismccord How do you feel about adding "coerce to string" to `core_components.ex` here?

https://github.com/phoenixframework/phoenix/blob/aead257f9303e2d7578be9e5250508a801974ad1/priv/templates/phx.gen.live/core_components.ex#L283

I've certainly used hidden inputs with boolean changeset fields in the past (in situation like seen in [this blog post](https://kobrakai.de/kolumne/one-to-many-liveview-form)) and it's a non obvious failure that values, which worked before with the `Phoenix.HTML.Form` integration would suddenly not work anymore.

I also can't think of a case, where the value pulled by `Phoenix.HTML.Form.input_value(f, field)` wouldn't be supposed to be turned into a string value on the built input.

**Comment by SteffenDE** [comment]
I stumbled across this as well, moving a changeset with a boolean field from the old `hidden_input` function to `<.input type="hidden" />`. I added a `to_string` call here:
https://github.com/phoenixframework/phoenix/blob/58fb905407f74d90c1810454ce5f8a6e47cc2027/priv/templates/phx.gen.live/core_components.ex#L309
and now it works as expected. Are there any downsides to this?

**Comment by SteffenDE** [comment]
> Are there any downsides to this?

I noticed that this breaks when using a `<select multiple>` that expects the value to be a list.´, so that's one downside.
