### ISSUE TITLE
Documentation: ambiguities in request life-cycle guide (v1.7.0-rc)

### ISSUE THREAD

**Issue by ijdickinson** [phoenixframework/phoenix#5154]
### Environment

* Elixir version (elixir -v): n/a
* Phoenix version (mix deps): 1.7.0.rc.0
* Operating system: n/a

### Expected behavior

This is an issue with the online documentation for 1.7.0-rc. Specifically https://hexdocs.pm/phoenix/1.7.0-rc.0/request_lifecycle.html#a-new-view

### Actual behavior

Quoth the docs:

> Now in order to add templates to this view, we can either define them as function components directly in the module:

The "we can either" clause doesn't obviously have an "or else we can" branch. More generally, when I read this section through for the first time it wasn't so clear that there are two equally viable alternatives being discussed: functional components or templated components. I think this could be confusing for new readers.

In addition, that section also has a code snippet:

```elixir
defmodule HelloWeb.HelloHTML do
  use HelloWeb, :html

  embed_templates "hello/*"
end
```

Should the `"hello/*` here be `"hello_html/*`?

**Comment by ben-maclaurin** [comment]
This one caused me some confusion!

**Comment by a8t** [comment]
IMO, the most confusing part is that `Hello` is used both in the app name (`HelloWeb`) and in the controller. It makes it really hard to separate which `Hello` is meaningful at what time. I can try to rewrite these docs but I worry that there are multiple pages that refer to `HelloWeb` and I'd have to change them all...!

**Comment by ijdickinson** [comment]
There's a few elements here. Some small tweaks to fix micro-copy issues, like dangling either/or clauses or minor inaccuracies in examples are always helpful I think, but I recognise it's often hard to schedule those fixes in with other more important/urgent activities.

But more generally, picking good examples to use in these kinds of docs is a really deep and hard issue. I do quite a bit of work coaching people learning to code, and from my personal experience and from what I've read, using abstract names like `hello_world` and `foo_bar` are often really confusing to **new** devs. Otoh, for **experienced** devs who just need the factual info asap, having to separate out essential language/framework info from domain/problem info is just extra cognitive load. Tricky balance.

Fwiw, one of the things I still find hard in LiveView is picking good names for contexts! I don't know if that generalises beyond just me (:grin:), but if so anything the docs could do to model and encourage best practice would be welcome, I expect. Naming **is** one of the Two Hard Problems in computer science, after all! But I also realise that this is huge undertaking across the whole spread of Phoenix docs.

I have a constrained amount of time to budget given the day job, but if I can help in all this then let me know.

**Comment by josevalim** [comment]
Fixed in master. Feel free to send more PRs to clarify any other parts. :)
