### ISSUE TITLE
Route resolution issues in 1.7.0-rc.0

### ISSUE THREAD

**Issue by binarypaladin** [phoenixframework/phoenix#5156]
### Environment

* Elixir version (elixir -v): `Elixir 1.14.2 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps): `1.7.0-rc.0`
* Operating system: `macOS 12.6.1 (Intel)`

We're building an API using Phoenix and are in the process of upgrading to 1.7 on a branch to see if we hit any weird bugs. It appears we've hit one.

We're seeing this issue in multiple environments, not just macOS.

I bumped Elixir to `Elixir 1.13.4 (compiled with Erlang/OTP 24)` and the results were the same.

Consider the following routes:

```
GET     /resources/:id                             MyApp.ResourcesController :show
POST    /resources/:resources_id/related-resources MyApp.RelatedResourcesController :create
GET     /resources/:id/:relationship_name          MyApp.ResourcesController :related
```

With our current setup, if there's a contextual create, it's handled by the related resource's controller, but the parent resource just handles index routes for all its child resources so we don't have to explicitly create new routes every time we add read-only relationships.

### Expected behavior

In 1.6.12

* `POST /resources/1/related-resources` routes to `MyApp.RelatedResourcesController.create`
* `GET /resources/1/related-resources` routes to `MyApp.ResourcesController.related`

### Actual behavior

In 1.17.0-rc.0

* `POST /resources/1/related-resources` routes to `MyApp.RelatedResourcesController.create`
* `GET /resources/1/related-resources` results in `Phoenix.Router.NoRouteError`

If I flip the route order:

```
GET     /resources/:id                             MyApp.ResourcesController :show
GET     /resources/:id/:relationship_name          MyApp.ResourcesController :related
POST    /resources/:resources_id/related-resources MyApp.RelatedResourcesController :create
```

* `POST /resources/1/related-resources` results in `Phoenix.Router.NoRouteError`
* `GET /resources/1/related-resources` routes to `MyApp.ResourcesController.related`

It appears now that if a route matches the route pattern first without the proper verb, it fails, even though another verb/pattern might match down the line (which is the current behavior in 1.6). 

If I explicitly add the route, it works:

```
GET     /resources/:id                             MyApp.ResourcesController :show
POST    /resources/:resources_id/related-resources MyApp.RelatedResourcesController :create
GET     /resources/:resources_id/related-resources MyApp.ResourcesController :related
```

Even if the parameter name changes, it still works fine. So, this also works:

```
GET     /resources/:id                             MyApp.ResourcesController :show
POST    /resources/:resources_id/related-resources MyApp.RelatedResourcesController :create
GET     /resources/:id/related-resources           MyApp.ResourcesController :related
```

Since this expected behavior worked in 1.6, I'm guessing it's expected to work in 1.7. (I'm hoping that's the case!)

Please let me know if you need me to put together a better example or provide anymore information.

**Comment by kotsius** [comment]
This bug is also present in 1.7.0-rc.1. Joshua's detailed description helped me identify it as the underlying cause behind buggy behaviour I reported two months ago in an Elixir [forum post](https://elixirforum.com/t/phoenix-1-7-0-rc-0-is-out/51625/34).

**Comment by bamorim** [comment]
I created a test case for that to help me see if I can find the root cause: https://github.com/bamorim/phoenix/commit/612d584490179dc75006fa0c88f1c7fa221ec662

I tested on 1.6 and the test case passed. I'll see if I can find more information about it.

**Comment by bamorim** [comment]
Ok, I know I found the root cause, but still need to figure out the best way to implement a fix.

The way routes are grouped when compiling the router are solely based on the path as we can see in these two lines:

https://github.com/phoenixframework/phoenix/blob/e5c51edb9af2fc5d50e3ae5b015da6bc0fa768c9/lib/phoenix/router.ex#L498

https://github.com/phoenixframework/phoenix/blob/e5c51edb9af2fc5d50e3ae5b015da6bc0fa768c9/lib/phoenix/router.ex#L558-L561

I think if we just change how we group the routes to take in consideration "overlapping"/"similar" routes it should fix the problem. I'm still digging more into how this is done.

That is, right now the generated group looks like this:

```elixir
%{
  ["users", {:arg0, [], Phoenix.Router.Route}] => [
    {%Phoenix.Router.Route{
       verb: :get,
       path: "/users/:id"
       # ...
     },
     %{
       # ...
     }}
  ],
  ["users", "similar"] => [
    {%Phoenix.Router.Route{
       verb: :post,
       path: "/users/similar"
       # ...
     },
     %{
       # ...
     }}
  ]
}
```

And we probably want to have something like
```elixir
%{
  ["users", {:arg0, [], Phoenix.Router.Route}] => [
    {%Phoenix.Router.Route{
       verb: :get,
       path: "/users/:id"
       # ...
     },
     %{
       # ...
     }},
    {%Phoenix.Router.Route{
       verb: :post,
       path: "/users/similar"
       # ...
     },
     %{
       # ...
     }}
  ]
  # ...
}
```

And we will probably need to pass the decoded URL once again to the fun generated by the `build_match/2`. I guess this is because `__match_route__` needs to be able to respond with information about the route without information about the method.

That being said, the same disclaimer again: I'm still learning and digging deep into how this works, so don't quote me on that 😅

**Comment by bamorim** [comment]
@chrismccord wouldn't it be simpler to just generate the `__match_route__/3` as before to be used for actual routing / `route_info/4` but then generate a `__match_route__/1` that just returns `forward_plug` and `warn_on_verify` to be used for verified routes?

**Comment by josevalim** [comment]
> @chrismccord wouldn't it be simpler to just generate the __match_route__/3 as before to be used for actual routing / route_info/4 but then generate a __match_route__/1 that just returns forward_plug and warn_on_verify to be used for verified routes?

Thank you @bamorim for the test case and spelunking. This is the approach I have decided to go with. Pushed to master!
