### ISSUE TITLE
Not getting compilation warnings with invalid ~p routes

### ISSUE THREAD

**Issue by noozo** [phoenixframework/phoenix#5162]
Not getting compilation warnings when i define an invalid verified route, like `/admin/brandssssssss`. Would expect to get a compiler warning, but nothing. Tried removing _build/dev and rebuilding everything from scratch, but same result. Tried with Phoenix master and same result.

### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.7-rc0 (or master)
* Operating system: OSX
* Other possibly relevant information: Using Surface 0.9 for UI

**Comment by chrismccord** [comment]
We need more information. What route definitions do you have in your router? What is the exact ~p line of code, etc. Thanks!

**Comment by noozo** [comment]
I have a few in live_admin.sface (using surface, like i mentioned)

![image](https://user-images.githubusercontent.com/3353/207411365-9c91f428-d654-4a4a-89c6-a2328bf61664.png)

Router part for brands looks like this:

![image](https://user-images.githubusercontent.com/3353/207411547-9c2c18f8-827d-4310-8d35-4f24b0ece955.png)

**Comment by noozo** [comment]
Could it be a surface issue?

**Comment by noozo** [comment]
Also tried to just printout `{~p"/admin/brandssss"}` in live_admin.sface and still no warnings.

**Comment by chrismccord** [comment]
What does the following return if you run this in `iex -S mix`:

```
iex> Phoenix.Router.route_info(PassionFruitWeb.Router, "GET", "/brandssssssss", nil)
```

**Comment by noozo** [comment]
Tried putting `{~p"/admin/brandssss"}` inside a normal surface component and it finally throws a warning. Wondering if related to being inside a layout?

**Comment by noozo** [comment]
> What does the following return if you run this in `iex -S mix`:
> 
> ```
> iex> Phoenix.Router.route_info(PassionFruitWeb.Router, "GET", "/admin/brandssssssss", nil)
> ```

`:error`

**Comment by chrismccord** [comment]
It ultimately gets expanded as a function definition so it shouldn't be an issue in the layout. Could you make your layout a heex file and see if it properly reports? Also as a sanity check you could `mix clean` and see if it was some sface/upgrade compiler issues.

**Comment by chrismccord** [comment]
also, if you run `mix compile --all-warnings`, are the layout warnings present in the output? Perhaps you missed them the first time they were (re)compiled?

**Comment by noozo** [comment]
If i remove everything from the layout except `{~p"/admin/brandsssss"}` and rename the file to live_admin.html.heex it also does not show warnings

**Comment by noozo** [comment]
same with `mix clean`, no warnings

**Comment by chrismccord** [comment]
Lastly, do you have multiple routers in the app? I'm guessing not, but worth a check.

Without a reproduction it's going to be impossible to say what is going on. I cannot recreate this with layout files (which should be no different than any other template file). If you can wrap things up into a reproducible example I'd be able to dig deeper. Thanks!

**Comment by chrismccord** [comment]
Ruling out surface would be helpful, which the reproduction would do.

**Comment by noozo** [comment]
The only other thing i can think of is that this particular layout is not a default one, but that shouldn't be the issue, right? 
```
 pipeline :browser_admin do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PassionFruitWeb.LayoutView, :root_admin}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end  
```

**Comment by chrismccord** [comment]
layouts themselves are just regular functions like any other template, so it shouldn't have different behavior compared to other layouts or regular templates

**Comment by chrismccord** [comment]
Let me know if you have other information about this. We don't have enough to say what could be the problem. Thanks!

**Comment by francoborr** [comment]
Is there more info about this? I'm facing the exact same issue.
