### ISSUE TITLE
Phoenix generator generates inadequate check for IPV6 Ecto flag

### ISSUE THREAD

**Issue by ijdickinson** [phoenixframework/phoenix#5164]
### Environment

* Elixir version (elixir -v):
  ```
  $ elixir -v
  Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]
  
  Elixir 1.14.2 (compiled with Erlang/OTP 25)
  ```
* Phoenix version (mix deps): 1.7.0-rc.0

* Operating system: Ubuntu 22.04

### Expected behavior

I want to create a Dockerfile that will allow me to choose IP6 support or not. IP6 is required on Fly.io, but is not required when I'm testing the Docker image locally on my dev machine. 

The `flyctl` CLI adds the following lines to `Dockerfile`:

```docker
# Appended by flyctl
ENV ECTO_IPV6 true
ENV ERL_AFLAGS "-proto_dist inet6_tcp"
```

I have changed this to:

```docker
ARG IPV6
....
# only set IP6 env var values in the image if $IPV6 ARG is truthy
ENV ECTO_IPV6=${IPV6:+true}
ENV ERL_AFLAGS=${IPV6:+"-proto_dist inet6_tcp"}
```

Setting environment var `$IPV6` to a falsey value should then deter Ecto from using `:inet6`.

### Actual behavior

Even with my environment containing `IPV6=0`, my Phoenix app starts up in `:inet6` mode.

### Analysis

The Docker construct `ENV ECTO_IPV6=${IPV6:+true}` when `$IPV6` is falsey is equivalent to:

```
ENV ECTO_IPV6=
```

So the `$ECTO_IPV6` variable is present in the environment that Phoenix starts with, but it has no value. However, the check that the generator creates in `config/runtime.exs` is:

```elixir
  maybe_ipv6 = if System.get_env("ECTO_IPV6"), do: [:inet6], else: []
```

So `maybe_ipv6` will contain `[:inet6]` if the environment contains the key `ECTO_IPV6`, **irrespective** of any value it has.

### Proposed solution

In my local `config/runtime.exs`, I have changed this line to:

```elixir
  maybe_ipv6 = if System.get_env("ECTO_IPV6") in ~w(true 1), do: [:inet6], else: []
```

The Phoenix generator could consider adopting a similar pattern? Or a more permissive approach, perhaps less of a potentially breaking change from the current behaviour, would be check that `$ECTO_IPV6` is not either empty or equal to `"0"`

**Comment by jeregrine** [comment]
Could you pr this change? We would happily accept it.

**Comment by ijdickinson** [comment]
@jeregrine Happy to do that, but which do you prefer: a more explicit test (I test for the flag being `"true"` or `"1"` in my local code), or a more permissive / more backward-compatible (i.e. not empty and not equal to 0)?

**Comment by jeregrine** [comment]
Lets roll with backwards compatible. Thanks!
