### ISSUE TITLE
What about adding `mix esbuild.install` and `mix tailwind.install` to `mix setup` task?

### ISSUE THREAD

**Issue by nallwhy** [phoenixframework/phoenix#5168]
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.7.0-rc.0
* Operating system: mac

### Description

At the first run of a new phoenix project, CSS of the main page is broken because downloading tailwind CSS takes a long time. (~2min)
If I weren't familiar with phoenix, I couldn't know the reason.

What about adding`esbuild.install` and `tailwind.install` to `mix setup` task?

**Comment by nallwhy** [comment]
hmm.. `mix tailwind.install` downloads the file again even if it has already been downloaded.

**Comment by josevalim** [comment]
Done in master. We also pre-install both tailwind and esbuild upfront.
