### ISSUE TITLE
(RuntimeError) expected @endpoint to be set

### ISSUE THREAD

**Issue by alaadahmed** [phoenixframework/phoenix#5173]
### Environment

* Elixir version (elixir -v): `1.14.2`
* Phoenix version (mix deps): `1.7.0-rc.0`
* Operating system: `macOS 12.6.2`

I have upgraded my app to *phoenix 1.7.0-rc.0*, and used _verified routes_ all over the app, except in one *HTML* file, when I changed all _Routes_ helper functions to use `~p""`, I get compilation error, that `@endpoint` is not set!

### `my_app_web.ex`
```
def router do
  quote do
    use Phoenix.Router, helpers: false

    import Plug.Conn
    import Phoenix.Controller
    import Phoenix.LiveView.Router
  end
end

# other functions
# ......
# ....

def html do
  quote do
    use Phoenix.Component

    # Import convenience functions from controllers
    import Phoenix.Controller,
      only: [get_csrf_token: 0, view_module: 1, view_template: 1]

    # Include general helpers for rendering HTML
    unquote(html_helpers())
  end
end

defp html_helpers do
  quote do
    # HTML escaping functionality
    use Phoenix.HTML

    # Import LiveView helpers
    import MyAppWeb.LiveHelpers

    # Core UI components and translation
    import MyAppWeb.CoreComponents

    import MyAppWeb.Gettext

    # Shortcut for generating JS commands
    alias Phoenix.LiveView.JS

    # Routes generation with the ~p sigil
    unquote(verified_routes())
  end
end

def verified_routes do
  quote do
    use Phoenix.VerifiedRoutes,
      endpoint: MyAppWeb.Endpoint,
      router: MyAppWeb.Router,
      statics: MyAppWeb.static_paths()
  end
end
```

### `navbar_html.ex`
```
defmodule MyAppWeb.NavbarHTML do
  use MyAppWeb, :html

  embed_templates "layouts/navbar/*"


  @menus [    #<<<<<<<<<<< Maybe because I use ~p inside module attribute that's why I get that compilation error???????
    %{
      title: "Title1",
      items: [
        %{
          label: "Item1",
          path: ~p"/item1"       <<<<<<<
        },
        %{
          label: "Item2",
          path: ~p"/item2/sub2"  <<<<<<<
        },
        %{
          label: "Item3",
          path: ~p"/item3/sub3"  <<<<<<<<
        }
      ]
    }
  ]

  # Other functions 
  # ....
  # ....

end
```

### Expected behavior
I expected when I `use MyAppWeb, :html` which _unquote_ `html_helpers()` -> `verified_routes()` will setup `@endpoint` in any file use it, but it doesn't see that module attribute.

### Actual behavior
Compilation fails and throw this error:
```
== Compilation error in file lib/my_app_web/components/navbar_html.ex ==
** (RuntimeError) expected @endpoint to be set. For dynamic endpoint resolution, use path/2 instead.

for example:

    path(conn_or_socket, ~p"/my-path")

    (phoenix 1.7.0-rc.0) lib/phoenix/verified_routes.ex:747: Phoenix.VerifiedRoutes.attr!/2
    (phoenix 1.7.0-rc.0) expanding macro: Phoenix.VerifiedRoutes.sigil_p/2
    lib/my_app_web/components/navbar_html.ex:17: MyAppWeb.NavbarHTML (module)
    (elixir 1.14.2) expanding macro: Kernel.@/1
    lib/my_app_web/components/navbar_html.ex:9: MyAppWeb.NavbarHTML (module)
```

**Comment by josevalim** [comment]
Can you please post the definition of said file OR provide an app that reproduces the error?

**Comment by chrismccord** [comment]
Most likely you need to `use Phoenix.VerifiedRoutes` with the appropriate `:endpoint` value. If you can provide a sample app we could say more but I don't believe this is an issue outside of missing usage .Thanks!

**Comment by alaadahmed** [comment]
This is very big app, I already used verified routes all over it, so I already during the course of upgrading the app, learned how to `use Phoenix.VerifiedRoutes` with the appropriate `:endpoint` which is only one in our app. It works fine, except when I tried to use `~p` inside a module attribute. 
So in *`navbar_html.ex`* file, I `use MyAppWeb, :html` and this should be sufficient, but was not. Also I wrote explicitly `use Phoenix.VerifiedRoutes, endpoint: MyAppWeb.Endpoint, router: MyAppWeb.Router` but also didn't work. So that's why I came with the result that, `~p` will not work inside module attribute, as this is the only file in the whole app, I tried to use `~p` inside a module attribute.

**Comment by josevalim** [comment]
Verified routes don’t work at compilation time I believe. We should confirm and most likely raise a better error message.

another approach is to detect that we are outside of a function and emit a slightly different code, as the endpoint module attribute won’t be accessible.
