### ISSUE TITLE
`new phx.gen.auth ...` choosing LiveView fails to inject menu items in layouts

### ISSUE THREAD

**Issue by kEND** [phoenixframework/phoenix#5176]
### Environment

* Elixir version (elixir -v):  `Elixir 1.14.0 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps):   `phoenix 1.7.0-rc.0  aead257`
* Operating system:  macOS 12.3.1

Goal:  try out the new LiveView-based auth on a blank `1.7.0-rc.0` project.  

1.  `mix phx.new dev_app` and follow prompts to get deps and create a database.
2.   `mix phx.gen.auth Accounts User users` choosing 'Y' for LiveView based system.

### Expected behavior

```sh
Do you want to create a LiveView based authentication system? [Yn] Y
* creating priv/repo/migrations/20221222005622_create_users_auth_tables.exs
* creating lib/dev_app/accounts/user_notifier.ex
...

dev_app/ ~
```

### Actual behavior

The auth menu items are not injected into the layout files.

```sh
* injecting lib/dev_app_web/router.ex - plug

Unable to find an application layout file to inject user menu items.

Missing files:

  * lib/dev_app_web/templates/layout/root.html.heex
  * lib/dev_app_web/templates/layout/app.html.heex

Please ensure this phoenix app was not generated with
--no-html. If you have changed the name of your application
layout file, please add the following code to it where you'd
like the user menu items to be rendered.

    <ul>
      <%= if @current_user do %>
        <li>
          <%= @current_user.email %>
        </li>
        <li>
          <.link href={~p"/users/settings"}>Settings</.link>
        </li>
        <li>
          <.link href={~p"/users/log_out"} method="delete">Log out</.link>
        </li>
      <% else %>
        <li>
          <.link href={~p"/users/register"}>Register</.link>
        </li>
        <li>
          <.link href={~p"/users/log_in"}>Log in</.link>
        </li>
      <% end %>
    </ul>


Please re-fetch your dependencies with the following command:

```

**Comment by kEND** [comment]
I'm working on adding a test (and then hopefully a PR) to expose this issue.

**Comment by joshchernoff** [comment]
Can you confirm this is still an issue, I think this has been possibly addressed.

**Comment by kEND** [comment]
I'll retest this and #5177 and report back.

**Comment by ghenry** [comment]
Hi all,

Just playing with v1.7.0-rc.1 and notice the menu items are there, but not themed very nice:

![Screenshot 2023-01-08 at 22-11-04 SentrypeerTesting · Phoenix Framework](https://user-images.githubusercontent.com/159608/211221667-ae21b638-a97f-4ceb-b35f-f23c9ccffd87.png)
![Screenshot 2023-01-08 at 22-13-29 SentrypeerTesting · Phoenix Framework](https://user-images.githubusercontent.com/159608/211221734-f77a45c6-96fd-4a2a-91b4-12518f1ae0e7.png)


everything else looks amazing with Tailwindcss bundled in now and the new defaults.

Thanks!

**Comment by jeregrine** [comment]
Looks like the only thing we need to do is update the live auth generators to use the new components in core_components.

I would happily accept a PR for this exact change.

**Comment by FabriDamazio** [comment]
@jeregrine 

I've made a simple solution that added just some styles into menu (1 line of code) and updated the tests.
If its enough i can make a PR.

Home:
![image](https://user-images.githubusercontent.com/3181570/218349262-9a0a285a-612f-4589-aa44-c8f941548e89.png)

![image](https://user-images.githubusercontent.com/3181570/218349315-163be155-8b2e-4dfd-963a-1893e48c2f51.png)

logged in:
![image](https://user-images.githubusercontent.com/3181570/218349339-ce80229b-0ac3-4bd6-82e8-0f4698fe271d.png)

![image](https://user-images.githubusercontent.com/3181570/218349361-8e76adcb-3df7-4133-96e7-43a042328733.png)

**Comment by jeregrine** [comment]
looks like someone took a stab at it here https://github.com/phoenixframework/phoenix/pull/5090/files

**Comment by derpycoder** [comment]
@vanderhoop is working on this.

https://github.com/phoenixframework/phoenix/pull/5090
