### ISSUE TITLE
`mix phx.gen.auth ...` choosing non-LiveView on an fresh `1.7-rc0` app fails to find source files during copy

### ISSUE THREAD

**Issue by kEND** [phoenixframework/phoenix#5177]
### Environment

* Elixir version (elixir -v):  `Elixir 1.14.0 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps):   `phoenix 1.7.0-rc.0  aead257`
* Operating system:  macOS 12.3.1

Goal:  try out the new release using with a generated non-LiveView auth on a blank `1.7.0-rc.0` project.  

1.  `mix phx.new dev_app` and follow prompts to get deps and create a database.
2.   `mix phx.gen.auth Accounts User users` choosing 'n' for LiveView based system.

### Expected behavior

```sh
Do you want to create a LiveView based authentication system? [Yn] Y
* creating priv/repo/migrations/20221222005622_create_users_auth_tables.exs
* creating lib/dev_app/accounts/user_notifier.ex
...

dev_app/ ~
```

### Actual behavior

The `mix phx.gen.auth ...` process fails to copy templates that are missing from source files.

```sh
* creating test/dev_dead_app_web/controllers/user_session_controller_test.exs
** (RuntimeError) could not find confirmation_view.ex in any of the sources
    (phoenix 1.7.0-rc.0) lib/mix/phoenix.ex:37: anonymous fn/4 in Mix.Phoenix.copy_from/4
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix 1.7.0-rc.0) lib/mix/phoenix.ex:32: Mix.Phoenix.copy_from/4
    (phoenix 1.7.0-rc.0) lib/mix/tasks/phx.gen.auth.ex:300: Mix.Tasks.Phx.Gen.Auth.copy_new_files/3
    (phoenix 1.7.0-rc.0) lib/mix/tasks/phx.gen.auth.ex:155: Mix.Tasks.Phx.Gen.Auth.run/2
    (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.0) lib/mix/cli.ex:84: Mix.CLI.run_task/2
dev_app ~ 
```

**Comment by chrismccord** [comment]
I can't recreate this. Can you try `mix clean` and report back? Thanks!
