### ISSUE TITLE
Hard coded ../deps in config should be Mix.Project.deps_path() for NODE_PATH in dev

### ISSUE THREAD

**Issue by ltd** [phoenixframework/phoenix#5179]
### Environment

* Elixir version (elixir -v): Elixir 1.14.2 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.0-rc.0
* Operating system: Darwin Kernel Version 22.2.0

### Expected behavior

NODE_PATH should find assets in deps pointed to by Mix.Project.deps_path

### Actual behavior

NODE_PATH gets configed always to ../deps

**Comment by josevalim** [comment]
It is very uncommon to change deps_path, so in such cases feel free to change NODE_PATH yourself. :)
