### ISSUE TITLE
Test helpers should have put_req_cookie(conn, key, value, signed: true) (or encrypted)

### ISSUE THREAD

**Issue by margusp2heathmont** [phoenixframework/phoenix#5187]
When LiveView is rendered from test, plugs and hooks get executed.

Because Plug reads cookie as:
`|> fetch_cookies(signed: [config[:session_cookie_name]])`

Tests need to be setup so that the cookie for auth pages is signed. 

This support would help a lot? Maybe there is some pattern how to do it, but Google and reading source code, was not successful in few moments.

**Comment by chrismccord** [comment]
Can you explain what is currently not working from generated test code? It's not clear what the issue is. Thanks!

**Comment by margusp2heathmont** [comment]
Application requires, that cookie is signed. Today seems, that manually constructing the cookie only way?

**Comment by chrismccord** [comment]
What of the generated tests or documentation for LiveViewTest falls short of allowing you to test the cookie session? Can you provide an example? Note that there is also [`Plug.Test.init_test_session`](https://hexdocs.pm/plug/Plug.Test.html#init_test_session/2), as well as `Phoenix.ConnTest.bypass_through`

**Comment by margusp2heathmont** [comment]
If I have a plug, that checks for signed cookie, then either that cookie is there or plug fails. For plug to not to fail, there needs to be a cookie, that has a proper signature.

**Comment by chrismccord** [comment]
The plug session is signed (and uses the cookie by default to hold the value), so it's still not clear what you are asking for. Can you *please provide a code example* that fails today and isn't served by the existing session primitives above? Thanks!
