### ISSUE TITLE
Default socket assigns not appearing in Channel socket assigns

### ISSUE THREAD

**Issue by homanchou** [phoenixframework/phoenix#5193]
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.7.0-rc.0
* Operating system: macOS 12.6.2 

### Expected behavior

I expect that variables added to socket.assigns in UserSocket to be present in the Channel

### Actual behavior

The socket.assigns in the Channel is an empty map.

Example repo: https://github.com/homanchou/thexr/blob/main/lib/thexr_web/channels/user_socket.ex

I assigned a user id into socket.assigns in UserSocket.  Did an IO.inspect to make sure it was there.  returned {:ok, socket} in the connection function.  Then in the join function of the corresponding Channel, I did IO.inspect on the socket.assigns and it is an empty map.

**Comment by optikfluffel** [comment]
@homanchou could remove the `{:ok, socket}` in your [user_socket.ex#L39](https://github.com/homanchou/thexr/blob/main/lib/thexr_web/channels/user_socket.ex#L39) and try again? :)

**Comment by chrismccord** [comment]
You are not returning the updated `socket` from your case statement, so it is being discarded. Note that after your case, you return the original socket here https://github.com/homanchou/thexr/blob/main/lib/thexr_web/channels/user_socket.ex#L39
