### ISSUE TITLE
Github actions testing matrix and incompatible elixir versions. 

### ISSUE THREAD

**Issue by joshchernoff** [phoenixframework/phoenix#5202]
Not really sure if this is the best place to call this out but I'm seeing failing CI on PRs where its clearly stating that the current versions of elixir used in the test matrix are not compatible with the current version needed by the framework. 

![Screenshot from 2023-01-08 11-00-18](https://user-images.githubusercontent.com/961877/211214046-1eb94c3f-4fba-4234-b808-7e7399293dd5.png)

For example this PR running on 1.12. 

Whats our thoughts about this?

**Comment by josevalim** [comment]
The installer requires ~> 1.14 for new apps but Phoenix works in earlier versions. In other words, this is fine. We only run `phx_new` tests on 1.14.
