### ISSUE TITLE
Phoenix.Controller layout type has incorrect declaration [1.7.0-rc.1]

### ISSUE THREAD

**Issue by leohner** [phoenixframework/phoenix#5209]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): Phoenix 1.7.0-rc.1
* Operating system: macOS Monterey, Version 12.6

### Expected behavior
Dialyzer passes and everything's happy.

### Actual behavior
Incorrect declaration of `layout` type in `Phoenix.Controller` throws a Dialyzer error. 

The [layout type](https://github.com/phoenixframework/phoenix/blob/v1.7.0-rc.1/lib/phoenix/controller.ex#L11) is defined as `@type layout :: {module(), layout_name :: atom()} | false`.

However, the [documentation](https://hexdocs.pm/phoenix/1.7.0-rc.1/Phoenix.Controller.html#put_layout/2) shows that passing only an atom as a second argument is valid, and it also works correctly in practice:

```
iex> conn = put_layout(conn, :print)
iex> layout(conn)
{AppView, :print}
````

For reference: [the typespec of `Phoenix.Controller.put_layout/2`](https://github.com/phoenixframework/phoenix/blob/v1.7.0-rc.1/lib/phoenix/controller.ex#L611)

The discrepancy is causing Dialyzer to fail.

**Comment by leandrocp** [comment]
That's related to https://github.com/phoenixframework/phoenix/commit/49b9c6e07a5eabeaead6109d1e49a8c8e7880689
