### ISSUE TITLE
get/post with dynamic paths return no route found error [1.7.0-rc.1]

### ISSUE THREAD

**Issue by leohner** [phoenixframework/phoenix#5210]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): Phoenix 1.7.0-rc.1
* Operating system: macOS Monterey, Version 12.6

### Note

Posting this as an issue first without a replication because it seems like a pretty major issue. I can create a new app with a demo of this behavior if need be.

Also, I want to give recognition to @charlottemoche and @coladarci for helping discover this with me.

### Expected behavior

Routes with dynamic paths segments are found regardless of order and method in `router.ex`. 

The following should be able to work without issue:

```
scope "/", AppWeb do
  get "/foo/:bar/:baz", SomeController, :show 
  post "/foo/:bar/post", SomeController, :post
end
```

### Actual behavior

In `router.ex`, a route is declared in the following way:

```
scope "/", AppWeb do
  get "/foo/:bar/:baz", SomeController, :show 
  post "/foo/:bar/post", SomeController, :post
end
```

When running `mix phx.routes`, both routes are displayed as expected. However, when trying to submit a post request to `/foo/:bar/post`, the application returns the following error: 

` ** (Phoenix.Router.NoRouteError) no route found for POST /foo/variable/post (AppWeb.Router)`

By switching the order of the requests, to `post` declared before `get`, the application works as expected. 

This leads me to believe that somewhere in Phoenix the `get "/foo/:bar/:baz"` is taking precedence because it has a dynamic third part of the path that is matching, resulting in the `post` request never matching. So, the application is aware the route exists, but the application is never able to find it.

**Comment by chrismccord** [comment]
Dup of #5156 thanks!
