### ISSUE TITLE
Template not rendered when sharing name with view function

### ISSUE THREAD

**Issue by kotsius** [phoenixframework/phoenix#5218]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.0-rc.2
* Operating system: Windows 10

### Expected behavior
As before v1.7, I expected Phoenix to work fine when a template and a view function have the same name.

### Actual behavior
Templates do not seem to be rendered when a view function has the same name.

**Comment by jeregrine** [comment]
Could you share an example repo or just an example?

**Comment by kotsius** [comment]
This bug came up in a more intricate context, but the following code should reproduce it:
```
#  router
scope "/", PrjWeb do
  get "/my_test", MyController, :my_test
end

#  controller
def my_test(conn, _) do
  render(conn, :my_test)
end

# view
def my_testxxx(_assigns) do
  "!!!"
end

# template
Bug<%= apply(view_module(@conn), :my_testxxx, [assigns]) %>
```
The above should render 'Bug!!!'. Remove 'xxx' from my_test in view and template, and only '!!!' will be left.

**Comment by josevalim** [comment]
Yes. In Phoenix v1.7 each template now defines a function of the name of the template. So if you define a function `my_test`, it will override the template.
