### ISSUE TITLE
error_tag undefined

### ISSUE THREAD

**Issue by v1d3rm3** [phoenixframework/phoenix#5227]
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.7.0-rc.2
* Operating system: Ubuntu

### Expected behavior
It should exist some function `error_tag` to form.

### Actual behavior
There isn't any function `error_tag` in a new generated app with phoenix 1.7.0-rc.2; i already search through all code with vscode search feature. There isn't any module ErrorHelpers, for example.

**Comment by chrismccord** [comment]
`error_tag` is defined in your application. For <= 1.6 applications, it was generated inside the `MyAppWeb.ErrorHelpers` module. For 1.7, everything is indie the CoreComponents. Thanks!

**Comment by v1d3rm3** [comment]
@chrismccord , but it changed the name of the function? Because there isn't any `error_tag` in `core_components.ex`

**Comment by chrismccord** [comment]
`error_tag`, if present in your templates, was always a function that was defined in your app and imported. With 1.7, `phx.new` does not generate this function and does not have any `error_tag` invocation in any generated template. The `core_components.ex` file contains an `<.error />` function component for similar, but more extensible features.
