### ISSUE TITLE
1.7.0-rc2 `put_layout(conn, :test)` throwed an error `no case clause matching: %{"html" => {PhxLabWeb.Layouts, :app}}`

### ISSUE THREAD

**Issue by cj1128** [phoenixframework/phoenix#5237]
I am following the doc about using `put_layout` to customize the app layout [here](https://hexdocs.pm/phoenix/1.7.0-rc.2/components.html#layouts).

`put_layout(conn, :test)` will throw an error but If I use the full version `put_layout(conn, {PhxLabWeb.Layouts, :test})` then everything works.

# CaseClauseError at GET /hello

Exception:

    ** (CaseClauseError) no case clause matching: %{"html" => {PhxLabWeb.Layouts, :app}}
        (phoenix 1.7.0-rc.2) lib/phoenix/controller.ex:656: Phoenix.Controller.put_private_layout/4
        (phx_lab 0.1.0) lib/phx_lab_web/controllers/hello_controller.ex:10: PhxLabWeb.HelloController.index/2
        (phx_lab 0.1.0) lib/phx_lab_web/controllers/hello_controller.ex:1: PhxLabWeb.HelloController.action/2
        (phx_lab 0.1.0) lib/phx_lab_web/controllers/hello_controller.ex:1: PhxLabWeb.HelloController.phoenix_controller_pipeline/2
        (phoenix 1.7.0-rc.2) lib/phoenix/router.ex:425: Phoenix.Router.__call__/5
        (phx_lab 0.1.0) lib/phx_lab_web/endpoint.ex:1: PhxLabWeb.Endpoint.plug_builder_call/2
        (phx_lab 0.1.0) lib/plug/debugger.ex:136: PhxLabWeb.Endpoint."call (overridable 3)"/2
        (phx_lab 0.1.0) lib/phx_lab_web/endpoint.ex:1: PhxLabWeb.Endpoint.call/2
        (phoenix 1.7.0-rc.2) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /Users/cj/Desktop/Lab/abc/phx_lab/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/cj/Desktop/Lab/abc/phx_lab/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/cj/Desktop/Lab/abc/phx_lab/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    

Code:

`lib/phoenix/controller.ex`

    651           # direction while get_layout_formats/put_layout_formats is removed.
    652           put_private_formats(conn, private_key, kind, %{_: {mod, layout}})
    653   
    654         layout when is_binary(layout) or is_atom(layout) ->
    655           # TODO: Deprecate this branch permanently.
    656>          case Map.get(conn.private, private_key, %{_: false}) do
    657             %{_: {mod, _}} ->
    658               put_private_formats(conn, private_key, kind, %{_: {mod, layout}})
    659   
    660             %{_: false} ->
    661               raise "cannot use put_layout/2 or put_root_layout/2 with atom/binary when layout is false, use a tuple instead"

**Comment by josevalim** [comment]
Yes, please use the long version for now. I have updated the guides and added a feature to make it easier. Thanks for the report!
