### ISSUE TITLE
PhoenixFramework logo in simple icons package

### ISSUE THREAD

**Issue by alec-c4** [phoenixframework/phoenix#5239]
Hey!
It would be nice if Phoenix logo will be available in a simple icons package. May I ask you to provide official icon here - https://github.com/simple-icons/simple-icons/issues/4917? @chrismccord

**Comment by arcanemachine** [comment]
I sent you a reply in the original thread.

**Comment by alec-c4** [comment]
thanks!

**Comment by chrismccord** [comment]
Unfortunately we can't provide the official logo for general use everywhere. We've handle it on a case by case basis in the past. Thanks!
