### ISSUE TITLE
`phx.gen.auth` Confirm Email Flash Message Not Rendering 

### ISSUE THREAD

**Issue by theshapguy** [phoenixframework/phoenix#5247]
### Environment

* Elixir version (elixir -v): Elixir 1.14.2
* Phoenix version (mix deps): 1.7.0-rc.2
* Operating system: macOS 13.1

### Expected behavior

In regards to `user_confirmation_controller.ex` generated via `phx.gen.auth`. Issue exists in both LiveView and Controller only generator.

- Flash message should be rendered after clicking on the "Confirm my Account" button. However page is being redirected to the root `/`

```elixir
  def create(conn, %{"user" => %{"email" => email}}) do
    if user = Accounts.get_user_by_email(email) do
      Accounts.deliver_user_confirmation_instructions(
        user,
        &url(~p"/users/confirm/#{&1}")
      )
    end

    conn
    |> put_flash(
      :info,
      "If your email is in our system and it has not been confirmed yet, " <>
        "you will receive an email with instructions shortly."
    )
    |> redirect(to: ~p"/")
  end
```

Just one instance is shown above however, `user_confirmation_controller.ex ` has three instances of it being redirected to the root page `/`.

### Actual behavior

Flash Message is not rendering. No Error Message or Success Message is shown due to the page being redirect to root `/`

https://user-images.githubusercontent.com/1960718/216501430-867dd97b-0bfd-449f-8fae-01c782c7982e.mov

### Possible Solution

https://user-images.githubusercontent.com/1960718/216501972-2e67b065-2641-4ad9-a47f-f59930ac4e01.mov

1. Redirect it to the same page so that the flash message is rendered. I used this to solve the issue.  

```elixir
|> redirect(to: ~p"/users/confirm")

&

|> redirect(to: ~p"/users/confirm/#{token}")
```
2. Implement.`<.flash/>` on the root page.

**Comment by theshapguy** [comment]
I'd be happy to fix this issue once comments are made as this might be related to user authentication didn't want to just submit a pull without discussion. Is there any issue on being redirect to self (if token invalid) or login page (after token confirmation)?

**Comment by josevalim** [comment]
I think we should show flash messages on root! PR is welcome!

**Comment by theshapguy** [comment]
On it!

**Comment by theshapguy** [comment]
I'm working on the PR now

**Comment by theshapguy** [comment]
Phoenix version (mix deps): 1.7.0-rc.3 has the same issue but with the changed tag <.flash_group>. I have fixed it accordingly with pull request #5270 as per https://github.com/phoenixframework/phoenix/issues/5247#issuecomment-1416331997

**Comment by josevalim** [comment]
@theshapguy the issue should no longer happen in 1.7.0-rc.3, no? After all, we are listing <.flash_group in the home page now?

**Comment by chrismccord** [comment]
rc3 should have addressed this one. Thanks!

**Comment by MarthinL** [comment]
I can't tell if this is related, but it seems plausible. **The flash message handling in v1.17.2 seems to now be broken.**

Starting with a freshly generated app with 
```
mix phx.new
```
 in 1.17.2, followed with 
```
mix phx.gen.auth Accounts User users
```
the result is a bog standard minimal system which uses the flash message subsystem to provide user feedback after auth-related actions 

These messages used to, and are expected to display for a defined duration and they have a close button if the user wants to manually close it before the duration had elapsed.

The actual behaviour however is this: 
* The flash messages remains visible indefinitely,
* the close button on success messages does not close the message, though
* the close button on failure messages does close the flash message. 

I've tested with liveview and controller based versions of phx.gen.auth with identical results.
