### ISSUE TITLE
`<.table>` doesn't work for list of simple maps

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix#5249]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps): 1.7.0-rc.2
* Operating system:

### Expected behavior

```
<.table rows={[%{…}, %{…}]}>
  …
</.table>
```

This should work fine.

### Actual behavior

```
maps cannot be converted to_param. A struct was expected, got: %{…}
```

**Comment by FabriDamazio** [comment]
The problem occurs when the `Phoenix.Param.to_param(row)` function is invoked to generate the table's row id.
This function does not support maps.

I think two solutions are possible when a list of maps is provided:

1. Can table rows have no id when a list of maps is provided? If yes, then we can add a conditional in id generation to ignore the id generation.

2. Generate a random id.

 What would be the best solution?

I am available to create a PR for any of them.

**Comment by chrismccord** [comment]
We no longer use to_param in rc.3 core_components. Thanks!
