### ISSUE TITLE
Phoenix 1.7 - `mix phx.gen.release --docker`

### ISSUE THREAD

**Issue by herbedev** [phoenixframework/phoenix#5255]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.0-rc-2
* Operating system: Mac OSX

### Expected behavior

Running `mix phx.gen.release --docker` doesn't crash and generates the files as it should. 

### Actual behavior

Running `mix phx.gen.release --docker` returns the following error

```shell

john@Johns-Personal-MacBook-Pro vx_underground % mix phx.gen.release --docker
* creating rel/overlays/bin/server
* creating rel/overlays/bin/server.bat
* creating rel/overlays/bin/migrate
* creating rel/overlays/bin/migrate.bat
* creating lib/vx_underground/release.ex

22:38:31.457 [debug] Fetching latest image information from https://hub.docker.com/v2/namespaces/hexpm/repositories/elixir/tags?name=1.14.3-erlang-25.2.2-debian-bullseye-
** (UndefinedFunctionError) function CAStore.file_path/0 is undefined (module CAStore is not available)
    CAStore.file_path()
    lib/mix/tasks/phx.gen.release.ex:258: Mix.Tasks.Phx.Gen.Release.fetch_body!/1
    lib/mix/tasks/phx.gen.release.ex:205: Mix.Tasks.Phx.Gen.Release.gen_docker/1
    lib/mix/tasks/phx.gen.release.ex:76: Mix.Tasks.Phx.Gen.Release.run/1
    (mix 1.14.3) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

I confirmed the `castore` is in my `mix.lock` file as well. 

```elixir
  "castore": {:hex, :castore, "0.1.22", "4127549e411bedd012ca3a308dede574f43819fe9394254ca55ab4895abfa1a2", [:mix], [], "hexpm", "c17576df47eb5aa1ee40cc4134316a99f5cad3e215d5c77b8dd3cfef12a22cac"},

```

**Comment by benjamg** [comment]
can I ask what you did to fix this as I get a very similar error and search isn't being helpful?

**Comment by herbedev** [comment]
Kicking myself for not commenting it here when it happened because I'm having a hard time remembering now. Since its a dependency of phoenix itself I would try removing and reinstalling the deps. 


I was experimenting with rc candidates for both `phx_new` and phoenix itself at the time.
