### ISSUE TITLE
Ueberauth Github does not work on Phoenix 1.7.0-rc0.2

### ISSUE THREAD

**Issue by EduardoBorsa** [phoenixframework/phoenix#5269]
Hey guys, IDK if this is the place to put it, but since this just happens for Gihub UeberAuth in phoenix 1.7.0-rc2, I thought maybe might be interesting to take a look.

So, there is a very basic configuration for Ueber Auth with GitHub.
 https://github.com/ueberauth/ueberauth_github.
 
 Works flawlessly in phoenix 1.6.
 But in Phoenix 1.7.0-rc2 fails and a warning pops up:
 
 ```
 [warning] Description: 'Server authenticity is not verified since certificate path validation is not enabled'
     Reason: 'The option {verify, verify_peer} and one of the options \'cacertfile\' or \'cacerts\' are required to enable this.'
```

The strange thing is that it is just for this strategy, the Google one works in both versions of phoenix.

Sorry if this sounds like an issue for the other repo, but I thought could be interesting.
(IDK, maybe some backward compatibility was broken? IDK)

Best regards.
Keep doing the awesome work!

Att.
Eduardo Borsa

**Comment by josevalim** [comment]
Please file it on Uberauth and, if it turns out to be Phoenix, we can look into it. But from a glance it seems unrelated. :)
