### ISSUE TITLE
How to handle `Client sent invalid transport version "*"` error?

### ISSUE THREAD

**Issue by nallwhy** [phoenixframework/phoenix#5273]
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.16.14
* Operating system: Amazon Linux 2

### Expected behavior

No error

### Actual behavior

Sometimes the following error log occurs in my service.

```
Feb 15 08:22:09 Phoenix.Socket: mfa=Phoenix.Socket.negotiate_serializer/2
[error] Client sent invalid transport version "*" 
```

In `Phoenix.Socket.negotiate_serializer/2`, only Semantic Versions seem to be handled, so it does not seem to handle versions like *.

However, I keep getting this error and I want to solve it. Is there a good way to handle it?

**Comment by josevalim** [comment]
It seems someone is trying to connect to your websockets without having the proper configuration. This can be a bot. if you have non-browser devices, check if they are working correctly. If they are, this should be safe to ignore.
