### ISSUE TITLE
Elixir v1.15 new app changes

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#5276]
Once `phx_new` is ready to depend on Elixir v1.15+, we should change `config :logger, :console` to `config :logger, :default_formatter` in the generated config files.

**Comment by yordis** [comment]
@josevalim which file would that be at?

**Comment by michallepicki** [comment]
@yordis Files:
- https://github.com/phoenixframework/phoenix/blob/bd3ce365dcb1e134e874a86997dfaf35f26ea048/installer/templates/phx_single/config/config.exs#L57
- https://github.com/phoenixframework/phoenix/blob/bd3ce365dcb1e134e874a86997dfaf35f26ea048/installer/templates/phx_single/config/dev.exs#L59
- https://github.com/phoenixframework/phoenix/blob/bd3ce365dcb1e134e874a86997dfaf35f26ea048/installer/templates/phx_single/config/config.exs#L57
- https://github.com/phoenixframework/phoenix/blob/bd3ce365dcb1e134e874a86997dfaf35f26ea048/installer/templates/phx_single/config/dev.exs#L59

**Comment by yordis** [comment]
Found the reference in terms of how it suppose to be!

```
config :logger, :default_formatter,
  format: "[$level] $message $metadata\n",
  metadata: [:error_code, :file]
```

Thank you, @michallepicki. I was confused a bit!

**Comment by epinault** [comment]
also it seems that we need more than that. 

```
config :logger, :default_handler,
  level: :info
``` 

need to be set as the level is only set from the handler per 

```
All previous console configuration, except for :level, now go under :default_formatter.
```

**Comment by josevalim** [comment]
You can still set `config :logger, level: ...`. There is a global and a per-handler configuration.

**Comment by epinault** [comment]
yes I see that it s not solving my issue . something in the upgrade is causing the logger to show raised error still , I filed #5628 to track it separately at this point.
