### ISSUE TITLE
Generator issue

### ISSUE THREAD

**Issue by AHBruns** [phoenixframework/phoenix#5277]
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.7.0-rc.3
* Operating system: MacOS 13.1

### Expected behavior

I ran `mix phx.gen.live Accounts User users name:string age:integer`. I expected to get a working users page after running `mix ecto.migrate` and adding the necessary routes to my router.

### Actual behavior

The generated FormComponent heex throws because it generates

```elixir
<.input field={@form[:name]} type="text" label="Name" />
```

instead of

```elixir
<.input field={{@form, :name}} type="text" label="Name" />
```

This causes the page to crash when trying to create a new user or edit and existing user.

### Resolution

If someone can confirm this is not already being fixed + is the root issue, I will open on a PR with a fix.

**Comment by AHBruns** [comment]
No technically related, but in the same vein, the `.table` core component, also throws because `id={"#{@id}-#{Phoenix.Param.to_param(row)}"}` doesn't work when the row doesn't implement the Phoenix.Param protocol, which ecto schema structs don't by default. There's a few ways we could go about fixing this. So, I'll want some guidance before starting on a PR.

**Comment by chrismccord** [comment]
Check the generated output of a new app generated with 1.7.0-rc.3, which uses the `%FormField{}` instead of the tuple approach. You can also delete your core components file and re-run the `phx.gen.live` generator and it will generate a new one for you. We dropped the tuple form. Thanks!

**Comment by chrismccord** [comment]
The to_param issue is also addressed in the new core components file :)

**Comment by AHBruns** [comment]
Ah, this was on me. Thought I was using a different project installer version than I was. Sorry for the inconvenience!

**Comment by caipre** [comment]
I'm quite new to Phoenix (and Elixir et al), but wanted to report that this also affects files generated via `mix phx.gen.auth`. I'll keep digging around on how to proceed, but for now the approach suggested in the original comment works (just have to update it in a handful of places!)
