### ISSUE TITLE
Sessions are not being propagated to the liveviews after of being set in a get conn request

### ISSUE THREAD

**Issue by SashaPetrovska** [phoenixframework/phoenix#5288]
### Environment

* Elixir version (elixir -v):  Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): ~> 1.7.0-rc.2
* Operating system: Linux ebfc4e544227 5.15.79.1-microsoft-standard-WSL2 # 1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 GNU/Linux

### Expected behavior
To be the sessions set through the live views

### Actual behavior
<issue title>

Reproduction:
https://github.com/SashaPetrovska/put_session-reporoduction

**Comment by chrismccord** [comment]
This is expected. You would need to store your information in another place, like the database, and broadcast it for it to be updated. Cookie sessions are only fetch on each request. Thanks!

**Comment by SashaPetrovska** [comment]
> This is expected. You would need to store your information in another place, like the database, and broadcast it for it to be updated. Cookie sessions are only fetch on each request. Thanks!

all right, but if I move the form component to a live view, the session gets propagated correctly, without the need of doing the trick you just said. Why is that acceptable?
