### ISSUE TITLE
Phoenix has gone mad and claims there are no controller modules.

### ISSUE THREAD

**Issue by Intelliractive** [phoenixframework/phoenix#5292]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.6.5
* Operating system: Windows 10
---
At first a message that said that there is no `init` method in my controllers appeared. Then it started saying my controller modules are not defined or unreachable. It suddenly started behaving so and even reinstalling all the things does not help.
---
![изображение](https://user-images.githubusercontent.com/98094811/219960995-88629a6e-5a25-4ed7-a140-8edf3cc8c81a.png)
![изображение](https://user-images.githubusercontent.com/98094811/219961057-fc57fb18-2e01-4bfe-aecb-2748041bb6f6.png)
---
The controllers are newly generated, using mix `phx.gen.html`, so I guess the problem is not in my code.

**Comment by chrismccord** [comment]
Can you share your entire router file? The double alias prefix of `IntellieractiveWeb` looks like you have a nested scope in your router? Thanks!

**Comment by Intelliractive** [comment]
This is a new project, so my router file is almost just regular:
<details>
<summary>router.ex</summary>

``` elixir
defmodule Intelliractive23Web.Router do
  use Intelliractive23Web, :router

  alias Intelliractive23Web.VideoController
  alias Intelliractive23Web.PageController

  import Intelliractive23Web.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {Intelliractive23Web.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Intelliractive23Web do
    pipe_through :browser

    resources "/vh", VideoController
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", Intelliractive23Web do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: Intelliractive23Web.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", Intelliractive23Web do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", Intelliractive23Web do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", Intelliractive23Web do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

```

</details>

---
I've made some research and realised that a Phoenix project breaks after I transfer files using explorer. There is definetily something wrong with FS changes watcher or live code reloader because it's already the 2nd time I encounter disability to use Phoenix after I import my html (the first time it was saying that there are no such html files)

# I do like this and then it's the end:
![изображение](https://user-images.githubusercontent.com/98094811/220144117-6404ee23-4ca9-4497-b136-0a8a6472e092.png)

**Comment by chrismccord** [comment]
You need to remove the `alias` lines in your router. `scope "/", MyWeb` will already providing the alias prefix to all modules within that scope, so drop the alias and you are good to go!

**Comment by Intelliractive** [comment]
Thank you! I wonder how they got there

**Comment by jashanbhoora** [comment]
For what it's worth, I've just had come into this same issue after having generated a Controller etc. using `mix phx.gen.html`. Playing things back using undo/redo, it looks like the `alias MyAppWeb.MyController` was automatically added to my `router.ex` by VSCode (or rather, the ElixirLS plugin I suppose) when I manually typed/used Intellisense to add `resources "/path", MyController` to my `scope`.
