### ISSUE TITLE
Phx.gen.auth in umbrella has a failing tests when run from top folder, but not when run from the app folder

### ISSUE THREAD

**Issue by mindreframer** [phoenixframework/phoenix#5295]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.14.2 (compiled with Erlang/OTP 25)

* Phoenix version (mix deps): phoenix 1.7.0-rc.3
* Operating system: Mac OSX Monterey

### Expected behavior
Tests should pass, not matter where they are run from. 

### Actual behavior
- https://github.com/mindreframer/repro_bug_inspect_password_test

Run from root: 
```bash 
==> example
.......................................

  1) test inspect/2 for the User module does not include password (Example.AccountsTest)
     apps/example/test/example/accounts_test.exs:504
     Refute with =~ failed
     code:  refute inspect(%User{password: "123456"}) =~ "password: \"123456\""
     left:  "%Example.Accounts.User{__meta__: #Ecto.Schema.Metadata<:built, \"users\">, id: nil, email: nil, password: \"123456\", hashed_password: nil, confirmed_at: nil, inserted_at: nil, updated_at: nil}"
     right: "password: \"123456\""
     stacktrace:
       test/example/accounts_test.exs:505: (test)

........................................................................................
Finished in 0.7 seconds (0.3s async, 0.4s sync)
128 tests, 1 failure
```

Run from subapp folder: 
```bash 
$ mix test
................................................................................................................................
Finished in 0.7 seconds (0.3s async, 0.4s sync)
128 tests, 0 failures

Randomized with seed 679613
```
It's probably some strange compilation issue.

**Comment by josevalim** [comment]
This is definitely an Elixir bug related to protocol consolidation, I will investigate.

**Comment by mindreframer** [comment]
Thanks!

**Comment by josevalim** [comment]
Unfortunately I cannot reproduce it in Elixir v1.14.2, branch 1.14, nor main. :(

**Comment by mindreframer** [comment]
I see... Damn. Maybe I have some local weirdness on my system... I'll check a fresh checkout and see if it's fixed. sec.

**Comment by mindreframer** [comment]
That's weird... On a fresh checkout all tests pass from all folders... But the folder, where I've run the generator commands still fails. This can be probably fixed by deleting `_build` and recompiling everything. I'll try that

**Comment by mindreframer** [comment]
Yep, fixed by full fresh recompilation. Sorry for bothering you. 😅  Closing
