### ISSUE TITLE
The scrollbar-gutter property in the default root.html.heex file conflicts with the rendering of flash messages

### ISSUE THREAD

**Issue by jitterbux** [phoenixframework/phoenix#5299]
Browser: 
**Chrome 108.0.5359.98**

By default when you install **Phoenix 1.7.0-rc.3** the flash message looks like this:

<img width="1001" alt="Screenshot 2023-02-22 at 12 01 01" src="https://user-images.githubusercontent.com/102470544/220605506-ec85a5b7-c7fa-4689-93c1-804831e2c58d.png">

This "defect" is caused by the css property scrollbar-gutter that is set in the `root.html.heex` file:

`<html lang="en" style="scrollbar-gutter: stable;">`

If we remove this property completely, the flash messages appear correctly:

<img width="1001" alt="Screenshot 2023-02-22 at 12 02 40" src="https://user-images.githubusercontent.com/102470544/220606283-d55fd4cb-a4b3-4367-91c2-f5d87afcaaa5.png">

I have tried to bump the z-index in tailwind for flash-messages like z-[100000] because it is already at maximum with z-50, but as expected, it didn't help.

**Comment by phoebe100** [comment]
I tried to reproduce it with current 1.7.2 project but looks OK to me

![screenshot1](https://user-images.githubusercontent.com/128167311/231501216-5bcb9655-48c0-4de6-9374-2f20eafb856f.jpg)
![screenshot2](https://user-images.githubusercontent.com/128167311/231501210-416bf54b-2bfc-481b-bf88-54ca9f29cd99.jpg)

My project creating steps:
`
mix phx.new test

cd test/

mix ecto.create

mix phx.gen.auth Accounts User users

Do you want to create a LiveView based authentication system? [Yn] Y

mix deps.get

mix ecto.migrate

mix phx.server
`

**Comment by marcofiset** [comment]
I'm on macOS and had the same issue. It depends on your "Show scroll bars" setting. 

I simply removed the `scrollbar-gutter: stable;` from the layout and it fixed it for all instances of that setting.

**Comment by cabello** [comment]
Alternatively in `core-components.ex` you can change `top-2 right-2` to something else, I changed to `top-4 right-4` but I will use the scrollbar-gutter instead, seems more future proof friendly for other floating things.
