### ISSUE TITLE
Phoenix can't find .html.heex file even though the file exists

### ISSUE THREAD

**Issue by sezaru** [phoenixframework/phoenix#5300]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): 1.7.0-rc.3
* Operating system: Pop OS 22.10

### Expected behavior

I have this route in my router file:

```elixir
  scope "/", MarketplaceWeb do
    pipe_through :browser

    live_session :main, on_mount: [...], session: {...} do
      scope "/adm", Admin do
        live "/properties", Property.ListLive
        live "/properties/:page", Property.ListLive
      end
    end
  end
  ```

The `ListLive` live view lives inside this directory:

`apps/marketplace_web/lib/marketplace_web/live/admin/property/`

I wanted to remove my render function from that live view and create a `list_live.html.heex` file instead.

But after I did that, I will get the following exception:

```
[error] #PID<0.975.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.974.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /adm/properties
** (exit) an exception was raised:
    ** (RuntimeError) render/1 was not implemented for MarketplaceWeb.Admin.Property.ListLive.

Make sure to either explicitly define a render/1 clause with a LiveView template:

    def render(assigns) do
      ~H"""
      ...
      """
    end

Or create a file at "/home/sezdocs/projects/rebuilt/marketplace/apps/marketplace_web/lib/marketplace_web/live/admin/property/list_live.html.heex" with the LiveView template.

        (marketplace_web 0.1.0) lib/marketplace_web/live/admin/property/list_live.ex:1: MarketplaceWeb.Admin.Property.ListLive.render/1
        (phoenix_live_view 0.18.15) lib/phoenix_live_view/utils.ex:183: Phoenix.LiveView.Utils.to_rendered/2
        (phoenix_live_view 0.18.15) lib/phoenix_live_view/static.ex:251: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.18.15) lib/phoenix_live_view/static.ex:135: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.18.15) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.0-rc.3) lib/phoenix/router.ex:425: Phoenix.Router.__call__/5
        (marketplace_web 0.1.0) lib/marketplace_web/endpoint.ex:1: MarketplaceWeb.Endpoint.plug_builder_call/2
        (marketplace_web 0.1.0) lib/plug/debugger.ex:136: MarketplaceWeb.Endpoint."call (overridable 3)"/2
        (marketplace_web 0.1.0) lib/marketplace_web/endpoint.ex:1: MarketplaceWeb.Endpoint.call/2
        (phoenix 1.7.0-rc.3) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.9.0) /home/sezdocs/projects/rebuilt/marketplace/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /home/sezdocs/projects/rebuilt/marketplace/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /home/sezdocs/projects/rebuilt/marketplace/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

The curious thing is that the path the exception says to where I need to create the `list_live.html.heex` file is exactly where my file is. I can literally just copy that path and cat it and it will show my file in the correct place.

So, for some reason, Phoenix is unable to find it even though it is there and it is in the exact path that it expects the file to be.

### Actual behavior

It will find the `list_live.html.heex` file and render the component correctly.

**Comment by chrismccord** [comment]
Can you share your entire LiveView module, and the contents of your app_web.ex? We use Phoenix.Template to find the files, which uses the current LV file's dir as the root dir to look in. Are you `use Phoenix.LiveView` in this module?

**Comment by sezaru** [comment]
I'm not sure why, but now it is working again... I guess it was some package that I updated/remove today that fixed it... I will close it for now since I can't reproduce it anymore

**Comment by tra** [comment]
This was happening to me too.  My "fix" was to add an empty `render/1` clause, render that, then remove the `render`.  Now it finds the `heex` file.  Hopefully this will help someone else who might run into this and find this thread.
