### ISSUE TITLE
Generate a custom Schema for new Phoenix projects

### ISSUE THREAD

**Issue by mathieuprog** [phoenixframework/phoenix#5302]
How about adding a custom Schema when generating new Phoenix projects? I personally always have to copy paste this one for new projects.

This also allows to set the id by default as binary if the `--binary-id` option was set when running `mix phx.new`.

```elixir
defmodule MyApp.Schema do
  defmacro __using__(_) do
    quote do
      use Ecto.Schema
      @primary_key {:id, :binary_id, autogenerate: true} # if --binary-id option present
      @foreign_key_type :binary_id # if --binary-id option present
      @timestamps_opts [type: :utc_datetime] # recommended to enforce timestamps in UTC timezone
    end
  end
end
```

I think in this case we would also need to generate the following:

```elixir
config :my_app, MyApp.Repo,
  migration_primary_key: [name: :id, type: :binary_id],
  migration_timestamps: [type: :utc_datetime]
```

**Comment by josevalim** [comment]
We have no plans for now as the options can also be specified per generator, and that would therefore lead to conflicts. Thanks!
