### ISSUE TITLE
`generators: [binary_id: true]` ignores `migration_primary_key: [name: :id, type: :binary_id]` option

### ISSUE THREAD

**Issue by mathieuprog** [phoenixframework/phoenix#5305]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.14.1 (compiled with Erlang/OTP 25)

* Phoenix version (mix deps):
1.7.0

* Operating system:
MacOS

### Expected behavior

If the Ecto option `migration_primary_key: [name: :id, type: :binary_id]` is set, running for example `mix phx.gen.schema Blog.Post blog_posts title:string views:integer` doesn't need to explicitly mark the `:id` as binary.

 I expect the following:

```elixir
create table(:blog_posts) do
  add :title, :string
  add :views, :integer
  timestamps()
end
```

### Actual behavior

The following is being generated:

```elixir
create table(:blog_posts, primary_key: false) do
  add :id, :binary_id, primary_key: true
  add :title, :string
  add :views, :integer
  timestamps()
end
```

**Comment by josevalim** [comment]
I would say this is correct. One changes the generated code, the other changes the default, but for example, if you change the defaults the generated one will still be correct if you want to be explicit. :)
