### ISSUE TITLE
link to changelog broken on v1.7 welcome page

### ISSUE THREAD

**Issue by kadimisetty** [phoenixframework/phoenix#5307]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): v1.7
* Operating system: NixOS

### Expected behavior
Link to changelog on the new welcome page should point to the changelog in the phoenix repo.

### Actual behavior
404

The branch was renamed from `v1.7` to `master` recently, so that's likely why the link using `v1.7` in the url doesn't exist anymore because the proper link uses the new branch name `master` instead.

As of now, link points to: `https://github.com/phoenixframework/phoenix/blob/v1.7/CHANGELOG.md`

Should point to:
`https://github.com/phoenixframework/phoenix/blob/master/CHANGELOG.md`

**Comment by whalenut** [comment]
Alternatively it should point to https://github.com/phoenixframework/phoenix/blob/v1.7.0/CHANGELOG.md
