### ISSUE TITLE
Docs: Module Plugs / Locale not working

### ISSUE THREAD

**Issue by enlego** [phoenixframework/phoenix#5315]
* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.0
* Operating system: All

### Expected behavior
[Phoenix guides -> Plugs -> Module Plugs section](https://hexdocs.pm/phoenix/plug.html#module-plugs)
The locale is not showing in the website after adding it in the app.html.heex
This is happening because in the Page Controller, the render action has `layout:false` as argument

```elixir
  def home(conn, _params) do
    # The home page is often custom made,
    # so skip the default app layout.
    render(conn, :home, layout: false) # <- Preventing the behaviour
  end
```
### Alternatives
For the locale to show on the webpage, I added it after the H1 in the home template
file location: `lib/hello_web/controllers/page_html/home.html.heex`

```html
    <h1 class="mt-10 flex items-center text-sm font-semibold leading-6 text-brand">
      Phoenix Framework
      <small class="ml-3 rounded-full bg-brand/5 px-2 text-[0.8125rem] font-medium leading-6">
        v1.7
      </small>
    </h1>
    <!-- Adding the locale after the H1 -->
    <p>Locale: <%= @locale %></p> # 
```

**Comment by josevalim** [comment]
@enlego your change is great. Can you please update the guides to the same?

**Comment by nhessler** [comment]
I'm curious if it's better to leave the line in `app.html.heex` and point them to the `http://localhost:4000/hello/` then add a not as to why it doesn't show on the homepage due to the layouts being turned off for it.

**Comment by enlego** [comment]
that sounds simpler!
I'll close the PR and send another one to reflect the change

**Comment by nhessler** [comment]
I have one ready if that works for you?

**Comment by nhessler** [comment]
https://github.com/phoenixframework/phoenix/compare/main...nhessler:phoenix:plug-guide-fix?expand=1

**Comment by enlego** [comment]
Thanks!
This is the first issue I submit, should I close it or do we wait for the PR to be approved?

**Comment by nhessler** [comment]
good question. I'm new as well. I'd leave it open until the PR is accepted personally. the core team can close it if that is the way they work.

**Comment by josevalim** [comment]
Hi @nhessler and @enlego! Thank you for the PR but I prefer the suggestion to change the home page instead of explaining why it does not work. Can you please update accordingly? :heart:

**Comment by enlego** [comment]
Hi @josevalim,
@nhessler submitted the [PR](https://github.com/phoenixframework/phoenix/pull/5335) pointing to the /hello page.
thanks!

**Comment by josevalim** [comment]
Hi @enlego, per above i would prefer to change where print the locale. @nhessler, can you please update your PR accordingly and ping me once done?

**Comment by nhessler** [comment]
@josevalim, done.
