### ISSUE TITLE
Phoenix 1.7 Controller.put_layout @spec does not allow 1.6 usage

### ISSUE THREAD

**Issue by adamu** [phoenixframework/phoenix#5320]
I have upgraded from Phoenix 1.6 to Phoenix 1.7 with minimal code changes, but I am having issues due to the the non-backwards compatible `@spec` [change](https://github.com/phoenixframework/phoenix/commit/9bad31711afa8e17226c130a6a7dbfb29bf94d23?diff=unified#diff-5ace5e108edb68b3ebf1bf05e71a898ef347caecb11b01a54b36456ed318282aL611) to put_layout:

https://github.com/phoenixframework/phoenix/blob/a9ed59bd419417b63c2a749171852ef2271f9bce/lib/phoenix/controller.ex#L617-L618

Although `put_layout` [still accepts](https://github.com/phoenixframework/phoenix/blob/a9ed59bd419417b63c2a749171852ef2271f9bce/lib/phoenix/controller.ex#L662-L663) the 1.6 usage, the `@spec` does not. As a result, [this line](https://github.com/adamu/put_view_example/blob/9d70619143dad715d0e3d96caefa3c25caa2621c/lib/example_web/controllers/page_controller.ex#L4):

```elixir
  plug :put_layout, {ExampleWeb.LayoutView, "app.html"}
```

Fails dialyzer checks with the following error, even though the code works.

```
lib/example_web/controllers/page_controller.ex:1:call
The function call will not succeed.

Phoenix.Controller.put_layout(
  _ :: %Plug.Conn{
    ...
  },
  {ExampleWeb.LayoutView, <<97, 112, 112, 46, 104, 116, 109, 108>>}
)

breaks the contract
(Plug.Conn.t(), [{format :: atom(), layout()}]) :: Plug.Conn.t()
```

Is this intentional, or could the `| layout` be restored to allow the `@spec` to match the behaviour?

**Comment by josevalim** [comment]
Intentional. Consider it an early deprecation warning powered by Dialyzer. :)

**Comment by edds** [comment]
Unless I'm missing something does this change means anyone that uses Dialyzer can no longer use `Phoenix.View` as you can no longer set layouts to be used? This feels like a massive breaking change which didn't even get mentioned in the release notes.

**Comment by josevalim** [comment]
You can use Phoenix.View and you can still set layouts. That's not the problem here. The old style still works and, if you want to avoid the Dialyzer warning (which does not stop the code from executing), it is a matter of replacing this:

  plug :put_layout, {ExampleWeb.LayoutView, "app.html"}

by this:

  plug :put_layout, html: {ExampleWeb.LayoutView, "app.html"}

**Comment by adamu** [comment]
> `plug :put_layout, html: {ExampleWeb.LayoutView, "app.html"}`

This was not a drop-in replacement for me, as it seems to require that you are also using the new-style layouts:

```
put_layout and put_root_layout expects an module and template per format, such as:

    html: {MyView, :app}

Got:

    {ExampleWeb.LayoutView, "custom.html"}
```

If I use the new atom syntax `html: {ExampleWeb.LayoutView, :custom}`, there are no errors, but the `custom` layout is not used, it uses the `app` layout instead.

However, the old syntax works fine.

---

What I did was write a hack to hide it from dialyzer, until we have time to migrate properly:

```elixir
  @spec put_layout_workaround(Plug.Conn.t(), {atom(), String.t()}) :: Plug.Conn.t()
  def put_layout_workaround(conn, arg) do
    # credo:disable-for-next-line Credo.Check.Refactor.Apply
    apply(Phoenix.Controller, :put_layout, [conn, arg])
  end
```

Then

```elixir
plug :put_layout_workaround, {ExampleWeb.LayoutView, "custom.html"}
```

**Comment by edds** [comment]
@adamu yeah I got the same exception trying the code @josevalim is suggesting. Your hack to get around dialyzer looks like it will be necessary as the new style does seem to require you to migrate your app which we just don't have time for in one go and don't want to get left behind.
