### ISSUE TITLE
Dialyzer complains about new type spec of t:Phoenix.Token.context()

### ISSUE THREAD

**Issue by AndrewDryga** [phoenixframework/phoenix#5321]
In commit 2aa5c9b0d6d8a6edfb2df2375868928d02780a0a Phoenix changed the type spec for `context` but for some reason, Dialyzer doesn't pick up the fact that the `Socket` struct still has the `endpoint` property:

```
lib/fz_http_web/sockets/user_socket.ex:51:call
Warning: The function call will not succeed.

Phoenix.Token.verify(
  _socket :: %Phoenix.Socket{:assigns => map(), _ => _},
  <<117, 115, 101, 114, 32, 97, 117, 116, 104>>,
  _token :: any(),
  [{:max_age, 86400}]
)

breaks the contract
(context(), binary(), binary(), [shared_opt() | max_age_opt()]) ::
  {:ok, term()} | {:error, :expired | :invalid | :missing}
```

See: https://github.com/firezone/firezone/actions/runs/4306165105/jobs/7509612170. PLT cache reset doesn't help, it's also reproduced locally on MacOS.

Maybe we can keep the old typespec `Socket.t()` along with the `%{endpoint: atom}` one to work around this issue?

### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.0
* Operating system: MacOS, Ubuntu

**Comment by chrismccord** [comment]
Sounds like a dialyzer issue to me. I’d gladly accept a PR that addresses this but it’s not something I’m going to pike at myself. Thanks!
