### ISSUE TITLE
phoenix 1.7.* (Phoenix.Router.NoRouteError) no route found for GET /assets/*

### ISSUE THREAD

**Issue by johnnrails** [phoenixframework/phoenix#5327]
I installed phoenix today and when I run the project the following error appears:

[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /assets/app.css (MessengyrWeb.Router)
     (messengyr 0.1.0) lib/phoenix/router.ex:482: MessengyrWeb.Router.call/2
     (messengyr 0.1.0) lib/messengyr_web/endpoint.ex:1: MessengyrWeb.Endpoint.plug_builder_call/2
     (messengyr 0.1.0) lib/plug/debugger.ex:136: MessengyrWeb.Endpoint."call (overridable 3)"/2
     (messengyr 0.1.0) lib/messengyr_web/endpoint.ex:1: MessengyrWeb.Endpoint.call/2
     (phoenix 1.7.1) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
     (plug_cowboy 2.6.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
     (cowboy 2.9.0) path-to/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
     (cowboy 2.9.0) path-to/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
     (cowboy 2.9.0) path-to/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
     (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

sorry, but i have no knowledge about how elixir works with static files, but from what i saw, when i open the server only one file appears in `priv/static/assets` folder - app.js, and maybe it should have files css and the tailwind files.
After that I ran `mix phx.digest` and it generated more files inside `priv/static` and `priv/static/assets`. but it can't read tailwind's files this time:

[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /assets/tailwindcss/utilities (MessengyrWeb.Router)
     (messengyr 0.1.0) lib/phoenix/router.ex:482: MessengyrWeb.Router.call/2
     (messengyr 0.1.0) lib/messengyr_web/endpoint.ex:1: MessengyrWeb.Endpoint.plug_builder_call/2
     (messengyr 0.1.0) lib/plug/debugger.ex:136: MessengyrWeb.Endpoint."call (overridable 3)"/2
     (messengyr 0.1.0) lib/messengyr_web/endpoint.ex:1: MessengyrWeb.Endpoint.call/2
     (phoenix 1.7.1) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
     (plug_cowboy 2.6.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
     (cowboy 2.9.0) path-to/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
h.request_process/3 h.execute/3
     (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /assets/tailwindcss/components (MessengyrWeb.Router)
     (exactly the same as before)
     
I switched to version 1.6.15 when I didn't have tailwind and everything worked as expected. am I missing out on something?

**Comment by josevalim** [comment]
You can try running `mix assets.setup` and `mix assets.build` and see what comes out of it. It may be that tailwind was not installed or not running for some reason. But in a nutshell, app.css must be there.

**Comment by johnnrails** [comment]
Sorry, I noticed there was a `mix setup` in the README.md that I should run before starting the server. Everything was installed correctly. value valinho :]
