### ISSUE TITLE
Custom error pages generate broken functions

### ISSUE THREAD

**Issue by tshakah** [phoenixframework/phoenix#5331]
### Environment

* Elixir version (elixir -v): `Elixir 1.14.2 (compiled with Erlang/OTP 24)`
* Phoenix version (mix deps): `phoenix 1.7.1`
* Operating system: NixOS 22.11

### Expected behavior
No syntax errors for custom error page functions

### Actual behavior
If you follow the instructions on https://hexdocs.pm/phoenix/custom_error_pages.html (the `embed_templates` step, in particular), you end up with `MyAppWeb.ErrorHTML.404/1` and `MyAppWeb.ErrorHTML.500/1` functions, which break code analysis tools as they are invalid.

For now, I've worked around this by keeping the `render/2` calls, _not_ creating the specific error HTML files, and then manually rendering a different `layout.html.heex` component:
```elixir
embed_templates "error_html/*"

def render("404.html", assigns) do
  message = ~H"
  Sorry, the thing you are looking for does not exist.<br /><br />
  Please go back or click the logo above to return to the home page
  "

  assigns
  |> Map.put(:message, message)
  |> __MODULE__.layout()
end
```

**Comment by chrismccord** [comment]
What "code analysis tool" are you referring to? The instructions work as described and note that a function like 404/1 is valid when invoked properly (like how we dispatch internally):

```elixir
iex(1)> DemoWeb.ErrorHTML."404"(%{})
%Phoenix.LiveView.Rendered{
  static: ["custom not found page"],
  dynamic: #Function<0.123249744/1 in DemoWeb.ErrorHTML."404"/1>,
  fingerprint: 1218046515898072985892940565834940159,
  root: false,
  caller: :not_available
}```

**Comment by tshakah** [comment]
I discovered it when running `https://github.com/rrrene/inch_ex`
