### ISSUE TITLE
Liveview generated new/edit buttons not working

### ISSUE THREAD

**Issue by kylekermgard** [phoenixframework/phoenix#5347]
### Environment

* Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix v1.7.1
* MacOS 12.3.1

### Steps

- Create a new phoenix project, install deps, create database, start server
 - mix phx.gen.live Accounts User users name:string
 - mix ecto.migrate
 - add routes to router.ex
  ```elixir
    live("/users", UserLive.Index, :index)
    live("/users/new", UserLive.Index, :new)
    live("/users/:id/edit", UserLive.Index, :edit)
    live("/users/:id", UserLive.Show, :show)
    live("/users/:id/show/edit", UserLive.Show, :edit)
```

### Expected behavior

On the users page clicking on "new user" or "edit" should show a form modal.

### Actual behavior

No form modal is shown.

**Comment by ghenry** [comment]
Hi @kylekermgard

Is your phx new v1.7.1 too?

Thanks.

**Comment by kylekermgard** [comment]
Yes `mix help phx.new`

`Location: .asdf/installs/elixir/1.14.3-otp-25/.mix/archives/phx_new-1.7.1/phx_new-1.7.1/ebin`

**Comment by josevalim** [comment]
Hi @kylekermgard, is any error reported in your browser console? Can you send a screenshot of how the page looks like?

**Comment by kylekermgard** [comment]
I was able to resolve this issue by disabling all my browser extensions. It turned out one of them was causing a javascript error.
