### ISSUE TITLE
Plug guide - locale not shown on homepage

### ISSUE THREAD

**Issue by mostalive** [phoenixframework/phoenix#5353]
Hi, thank you for phoenix, and the guides. I'm going through the guide for the second time (with 1.7 instead of 1.6), and found something that no longer seems to work as described.

### Environment

* Elixir version (elixir -v):
Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps):

* castore 0.1.22 (Hex package) (mix)
  locked at 0.1.22 (castore) c17576df
  ok
* connection 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (connection) 722c1eb0
  ok
* cowboy 2.9.0 (Hex package) (rebar3)
  locked at 2.9.0 (cowboy) 2c729f93
  ok
* cowboy_telemetry 0.4.0 (Hex package) (rebar3)
  locked at 0.4.0 (cowboy_telemetry) 7d98bac1
  ok
* cowlib 2.11.0 (Hex package) (rebar3)
  locked at 2.11.0 (cowlib) 2b3e9da0
  ok
* db_connection 2.4.3 (Hex package) (mix)
  locked at 2.4.3 (db_connection) c127c15b
  ok
* decimal 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (decimal) 34666e9c
  ok
* ecto 3.9.4 (Hex package) (mix)
  locked at 3.9.4 (ecto) de5f988c
  ok
* ecto_sql 3.9.2 (Hex package) (mix)
  locked at 3.9.2 (ecto_sql) 1eb5eeb4
  ok
* esbuild 0.6.1 (Hex package) (mix)
  locked at 0.6.1 (esbuild) 569f7409
  ok
* expo 0.4.0 (Hex package) (mix)
  locked at 0.4.0 (expo) a8ed1683
  ok
* file_system 0.2.10 (Hex package) (mix)
  locked at 0.2.10 (file_system) 41195edb
  ok
* finch 0.14.0 (Hex package) (mix)
  locked at 0.14.0 (finch) 5459acaf
  ok
* gettext 0.22.1 (Hex package) (mix)
  locked at 0.22.1 (gettext) ad105b8d
  ok
* hpax 0.1.2 (Hex package) (mix)
  locked at 0.1.2 (hpax) 2c87843d
  ok
* jason 1.4.0 (Hex package) (mix)
  locked at 1.4.0 (jason) 79a37910
  ok
* mime 2.0.3 (Hex package) (mix)
  locked at 2.0.3 (mime) 27a30bf0
  ok
* mint 1.5.1 (Hex package) (mix)
  locked at 1.5.1 (mint) 4a63e1e7
  ok
* nimble_options 0.5.2 (Hex package) (mix)
  locked at 0.5.2 (nimble_options) 4da7f904
  ok
* nimble_pool 0.2.6 (Hex package) (mix)
  locked at 0.2.6 (nimble_pool) 1c715055
  ok
* phoenix 1.7.1 (Hex package) (mix)
  locked at 1.7.1 (phoenix) ea9d4a85
  ok
* phoenix_ecto 4.4.0 (Hex package) (mix)
  locked at 4.4.0 (phoenix_ecto) 09864e55
  ok
* phoenix_html 3.3.1 (Hex package) (mix)
  locked at 3.3.1 (phoenix_html) bed1906e
  ok
* phoenix_live_dashboard 0.7.2 (Hex package) (mix)
  locked at 0.7.2 (phoenix_live_dashboard) 0e5fdf06
  ok
* phoenix_live_reload 1.4.1 (Hex package) (mix)
  locked at 1.4.1 (phoenix_live_reload) 9bffb834
  ok
* phoenix_live_view 0.18.17 (Hex package) (mix)
  locked at 0.18.17 (phoenix_live_view) f4b5710e
  ok
* phoenix_pubsub 2.1.1 (Hex package) (mix)
  locked at 2.1.1 (phoenix_pubsub) 81367c6d
  ok
* phoenix_template 1.0.1 (Hex package) (mix)
  locked at 1.0.1 (phoenix_template) 157dc078
  ok
* plug 1.14.0 (Hex package) (mix)
  locked at 1.14.0 (plug) bf020432
  ok
* plug_cowboy 2.6.0 (Hex package) (mix)
  locked at 2.6.0 (plug_cowboy) 073cf20b
  ok
* plug_crypto 1.2.5 (Hex package) (mix)
  locked at 1.2.5 (plug_crypto) 26549a1d
  ok
* postgrex 0.16.5 (Hex package) (mix)
  locked at 0.16.5 (postgrex) edead639
  ok
* ranch 1.8.0 (Hex package) (rebar3)
  locked at 1.8.0 (ranch) 49fbcfd3
  ok
* swoosh 1.9.1 (Hex package) (mix)
  locked at 1.9.1 (swoosh) 76dffff3
  ok
* tailwind 0.1.10 (Hex package) (mix)
  locked at 0.1.10 (tailwind) e0fc474d
  ok
* telemetry 1.2.1 (Hex package) (rebar3)
  locked at 1.2.1 (telemetry) dad9ce9d
  ok
* telemetry_metrics 0.6.1 (Hex package) (mix)
  locked at 0.6.1 (telemetry_metrics) 7be9e087
  ok
* telemetry_poller 1.0.0 (Hex package) (rebar3)
  locked at 1.0.0 (telemetry_poller) b3a24eaf
  ok
* websock 0.5.0 (Hex package) (mix)
  locked at 0.5.0 (websock) b51ac706
  ok
* websock_adapter 0.4.5 (Hex package) (mix)
  locked at 0.4.5 (websock_adapter) 1d9812dc
  ok

* Operating system:

MacOS Ventura 13.2.1, Apple M1, MacBook Air 16GB
### Expected behavior
Working through the 'plug' guide

https://github.com/phoenixframework/phoenix/blob/v1.7.1/guides/plug.md#L1

"Go to http://localhost:4000/ and you should see the locale exhibited. Visit http://localhost:4000/?locale=fr and you should see the assign changed to "fr"."
.
### Actual behavior

Actual result:
Locale is not displayed on the homepage. It is displayed under the '/hello' path though

### Potential fixes / workarounds

I could think of some possible fixes, none of them great
- change suggestion to uses http://localhost/hello and http://localhost:4000/hello?locale=fr
- use the layout for the homepage as well. I modified PageController so it doesn't set `layout: false`, but it doesn't look great in the browser.

I guess using /hello and maybe explaining about the layout use in the text might help, but it distracts from explaining Plug.
I'm happy to provide a patch.

**Comment by josevalim** [comment]
This has been fixed in main :) It will be out in the next release, thank you!
