### ISSUE TITLE
1.7.2 attempts to generate project with LiveView version that does not yet support JS.exec

### ISSUE THREAD

**Issue by aiwaiwa** [phoenixframework/phoenix#5376]
`mix phx.new` of version 1.7.2 generates an app with `mix.exs`:

```elixir
      {:phoenix, "~> 1.7.2"},
      ...
      {:phoenix_live_view, "~> 0.18.16"},
```
LiveView does not support JS.exec until 0.18.18

**Comment by chrismccord** [comment]
Hex will grab 0.18.18 `{:phoenix_live_view, "~> 0.18.16"}` Thanks!
