### ISSUE TITLE
formData variable is undefined in phoenix generated liveview form

### ISSUE THREAD

**Issue by marcdel** [phoenixframework/phoenix#5379]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.2
* Operating system: macOS Ventura 13.2 (arm and x86)
* Browser: Chrome Version 111.0.5563.64 (Official Build)

Works as expected in Safari 16.3

### Reproduction Steps
Clone https://github.com/marcdel/something or
```
mix phx.new whatever
mix phx.gen.live Accounts User users name:string age:integer
# also migrate the db, add the routes and all that good stuff
```

```
mix phx.server
open http://localhost:4000/users/new
```
Type anything into the name and/or age field.

### Expected behavior
The `handle_event("validate")` event in FormComponent should be fired.

### Actual behavior
A javascript error is raised
```
view.js:68 Uncaught TypeError: formData.forEach is not a function
    at serializeForm (view.js:68:12)
    at View.pushInput (view.js:876:18)
    at js.js:57:20
    at View.withinTargets (view.js:229:9)
    at Object.exec_push (js.js:52:10)
    at js.js:17:22
    at Array.forEach (<anonymous>)
    at js.js:16:40
    at Array.forEach (<anonymous>)
    at Object.exec (js.js:12:14)
```

**Comment by chrismccord** [comment]
I can't recreate this one. Can you double check the live view version in your mix lock?

**Comment by chrismccord** [comment]
I saw you pushed the repo. I am also on Chrome 111.0.5563.64. It's very weird that this would happen since we instantiate using `FormData` which will blow up if we don't pass it a HTMLFormElement. I don't see how it's possible we end up with a `formData` variable that doesn't have `forEach`

**Comment by marcdel** [comment]
Yeah, it's super weird

```
➜  mix deps | grep live_view
* phoenix_live_view 0.18.18 (Hex package) (mix)
  locked at 0.18.18 (phoenix_live_view) a5810d04
```

**Comment by Gazler** [comment]
Closing this issue, I'll re-open if the issue still persists in the latest Phoenix version.
