### ISSUE TITLE
Function put_my_layout/2 has no local return.

### ISSUE THREAD

**Issue by fuelen** [phoenixframework/phoenix#5383]
### Environment

* Elixir version (elixir -v): Elixir 1.14.2 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.2
* Operating system: Linux

### Steps to reproduce
* generate a new project with `mix phx.new hello`
* move `plug :put_root_layout, {HelloWeb.Layouts, :root}` from `:browser` pipeline to the new one:
```diff

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
-    plug :put_root_layout, {HelloWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

+  pipeline :put_my_layout do
+    plug :put_root_layout, {HelloWeb.Layouts, :root}
+  end
``` 
* add dyalixir to deps and run `mix dialyzer`

### Expected behavior
no errors

### Actual behavior
error:
```
lib/hello_web/router.ex:12:no_return
Function put_my_layout/2 has no local return.
```

**Comment by chrismccord** [comment]
We'd except a PR that solve this one, but it's not something I can chase down at the moment. Thanks!

**Comment by Hentioe** [comment]
Before the issue is fixed, you can ignore them through `.dialyzer_ignore.exs`. like:

```elixir
[
  # {file, warning_type, line}
  {"lib/your_app_name_web/router.ex", :no_return, line},
]
```
Replace `your_app_name` and `line` with your own. Unfortunately this doesn't solve the elixir-ls warning, because elixir-ls doesn't support this configuration file.

**Comment by fuelen** [comment]
@edwardsmit thank you, it helps
