### ISSUE TITLE
`No route path` warning changing the static assets path

### ISSUE THREAD

**Issue by avillen** [phoenixframework/phoenix#5387]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.14.3 (compiled with Erlang/OTP 23)
```
* Phoenix version (mix deps): `{:phoenix, "~> 1.7.2"}`
* Operating system: `macOS 11.7.3`

### Expected behavior

If I want to change the path where the static assets will be requested, I want to be able to compile the project without warnings because of no route paths. Steps to reproduce in a new project with the latest phx_new version:
1. `mix archive.install hex phx_new`
2. `mix phx.new test_warning_sigil --no-ecto`
3. `mix setup`
4. Modify the `Plug.Static` in the `lib/test_warning_sigil_web/endpoint.ex` file to:
```
  plug(Plug.Static,
    at: "/custom_path",
    from: :test_warning_sigil,
    gzip: false,
    only: TestWarningSigilWeb.static_paths()
  )
```
5. Update the `lib/test_warning_sigil_web/components/layouts/root.html.heex` file with:
```
    ...
    <link phx-track-static rel="stylesheet" href={~p"/custom_path/assets/app.css"} />
    <script defer phx-track-static type="text/javascript" src={~p"/custom_path/assets/app.js"}>
   ...
```

### Actual behavior

If I follow the previous steps, I can run the application and the static files looks to be properly loaded, but I get those warnings:
```
warning: no route path for TestWarningSigilWeb.Router matches "/custom_path/assets/app.js"
  lib/test_warning_sigil_web/components/layouts/root.html.heex:11: TestWarningSigilWeb.Layouts.root/1

warning: no route path for TestWarningSigilWeb.Router matches "/custom_path/assets/app.css"
  lib/test_warning_sigil_web/components/layouts/root.html.heex:10: TestWarningSigilWeb.Layouts.root/1
```

**Comment by chrismccord** [comment]
https://github.com/phoenixframework/phoenix/pull/5495#issuecomment-1661299048
