### ISSUE TITLE
phx.gen.release --docker generates invalid Dockerfile when application has no priv directory

### ISSUE THREAD

**Issue by viniciusmuller** [phoenixframework/phoenix#5410]
### Environment

* Elixir version (elixir -v): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): master
* Operating system: Linux debian 5.10.0-21-amd64 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### Expected behavior

When running `mix phx.gen.release --docker` in a project that got no priv directory, a valid Dockerfile will be generated.  

### Actual behavior

Currently the `COPY priv priv` directive is hardcoded in the Dockerfile template, so the build ends up failing.

### Steps to Reproduce

- `mix phx.new project --no-assets --no-gettext --no-html --no-live --no-mailer --no-ecto` (gets no priv directory)
- `mix phx.gen.release --docker` always have a `COPY priv priv` directive inside the generated Dockerfile
- `docker build .` fails

### Other

I would be happy contributing to phoenix by trying to fix this issue

**Comment by josevalim** [comment]
It is expected that generators will fail if you opt-out of features. For example, the context generator will fail if you don't have Ecto. So in this case, it is up to you to remove the incompatible parts. Thank you for the report!
