### ISSUE TITLE
use env variable MIX_DEPS_PATH in config.exs templates

### ISSUE THREAD

**Issue by matreyes** [phoenixframework/phoenix#5414]
### Environment

* Phoenix version: 1.7.2

### Expected behavior

When using the MIX_DEPS_PATH env variable, the NODE_PATH (in config.exs) should be taken from that dependencies path.

### Actual behavior

Config templates call `%{"NODE_PATH" => Path.expand("../deps", __DIR__)}` so it fails to get the phoenix js library.
Templates may be defined as` %{"NODE_PATH" => Path.expand(System.get_env("MIX_DEPS_PATH", "../deps"), __DIR__)}`

As it's a template, we shouldn't expect to handle these cases, but in my case it would have saved me a lot of debugging time (I had an old deps folder in the default folder with an old phoenix version. So it was running, but with a lot of js errors).

Thanks!

**Comment by josevalim** [comment]
I would prefer to keep it cleaner for now, as MIX_DEPS_PATH is rarely used. If others run into this, we can consider using it by default. Thank you!
