### ISSUE TITLE
Phoenix.Channel handle_in/2 allows raw string as payload

### ISSUE THREAD

**Issue by davydog187** [phoenixframework/phoenix#5419]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.2
* Operating system: macOS Monteray

### Expected behavior
Phoenix Channels are capable of receiving strings as payloads to `handle_in/3`, so I would expect the signature to be

```elixir
@type payload() :: map() | String.t() | {:binary, binary()}
```

### Actual behavior

The actual signature is 
```elixir
@type payload() :: map() | {:binary, binary()}
```

Note that am sending the string from [Slipstream](https://hexdocs.pm/slipstream/Slipstream.html#push/5), so I'm not sure if this is a client issue or if the typespec should be updated.

**Comment by davydog187** [comment]
I am happy to send a PR to correct the behavior. I'm not sure if it should be a typespec update or something else

**Comment by chrismccord** [comment]
It works by accident, so the spec is right :) Thanks!

**Comment by davydog187** [comment]
If it works by accident can we consider handling and throwing an error?
