### ISSUE TITLE
"Request an invitation" to Slack org links to broken Heroku app

### ISSUE THREAD

**Issue by cachance7** [phoenixframework/phoenix#5424]
The _Request an invitation_ link on the Community docs page links to a broken Heroku app.

https://hexdocs.pm/phoenix/community.html
https://elixir-slackin.herokuapp.com/ <-- link to broken app

### Environment

N/A

### Expected behavior

This should link somewhere useful (or not exist in the docs).
https://github.com/phoenixframework/phoenix/blob/b62d055382d4eaa179acbf1eeb5d1118b97dc04f/guides/introduction/community.md?plain=1#L9

### Actual behavior

<img width="700" alt="Screenshot 2023-04-18 at 4 26 31 PM" src="https://user-images.githubusercontent.com/1068829/232926212-8da4a896-c366-4db1-80cb-33e93e26ec5b.png">

**Comment by rktjmp** [comment]
This was fixed by https://github.com/phoenixframework/phoenix/commit/ed121ed16df7cc7ee613e38e9d00f66c3da84714
