### ISSUE TITLE
Generating a new Phoenix umbrella app with the `--no-live` option still adds LiveView dependencies and code

### ISSUE THREAD

**Issue by mathieuprog** [phoenixframework/phoenix#5436]
Generating a new Phoenix umbrella app with the `--no-live` option still adds dependencies to LiveView-related libraries and code.
> mix phx.new test --umbrella --no-dashboard --no-live --binary-id

in the root `mix.exs`:
```elixir
defp deps do
  [
    # Required to run "mix format" on ~H/.heex files from the umbrella root
    {:phoenix_live_view, ">= 0.0.0"}
  ]
end
```

in the `mix.exs` of the /web folder:
```elixir
{:phoenix_live_view, "~> 0.18.16"},
```

In the formatter:
```elixir
plugins: [Phoenix.LiveView.HTMLFormatter],
```

In the tests:
- `root.html.heex` and `app.html.heex` files.
- lots of code related to LiveView

**Comment by josevalim** [comment]
Correct. As the docs say:

>     * `--no-live` - comment out LiveView socket setup in assets/js/app.js.
>      Automatically disabled if --no-html is given

--no-live means about not estalbishing a live connection. LiveView is still a dependency.
