### ISSUE TITLE
Wrong spec for `put_root_layout/2` method 

### ISSUE THREAD

**Issue by fedeotaran** [phoenixframework/phoenix#5437]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.2 (Hex package) (mix) locked at 1.7.2 (phoenix) 1ebca94b
* Operating system: macOS  Ventura version 13.3.1 (22E261)

### Expected behavior

Should be able to use the `put_root_layout/2` method with the value `false` to replace the root layout as specified in the documentation, without encountering any Dialyzer warnings.

Example:
```elixir
def print(conn, _params) do
    conn
    |> put_root_layout(false)
    |> put_layout("empty.html")
    |> render("print.html")
end
```

### Actual behavior

A Dialyzer warning is observed since the spec does not allow the value `false`.

#### Current spec
```
@spec put_root_layout(Plug.Conn.t(), [{format :: atom(), layout()}]) :: Plug.Conn.t()
```

#### Warning
```
The call 'Elixir.Phoenix.Controller':put_root_layout
         (_conn@1 :: any(),
          'false') breaks the contract ('Elixir.Plug.Conn':t(),[{format::atom(),layout()}]) -> 'Elixir.Plug.Conn':t()ElixirLS Dialyzer
```

Possibly it should have the same spec as the `put_layout/2` method:
```
@spec put_layout(Plug.Conn.t(), [{format :: atom(), layout()}] | false) :: Plug.Conn.t()
```

**Comment by ByeongUkChoi** [comment]
layout type is:
```elixir
@type layout :: {module(), layout_name :: atom()} | atom() | false
```

So Isn't this right?

```elixir
def print(conn, _params) do
    conn
    |> put_root_layout(html: false)
    |> put_layout("empty.html")
    |> render("print.html")
end
```

**Comment by dsignr** [comment]
This is still an issue if you use it at the top of your controllers in this fashion:

```elixir
defmodule AppWeb.UserRegistrationController do
   plug :put_root_layout, {AppWeb.Layouts, :public_iam_root} when action in [:new, :create]
  # or plug :put_root_layout, {AppWeb.Layouts, :public_iam_root, []} when action in [:new, :create]

   def new do
      ....
   end

   # other methods
   ...
end
```

And your entire code is highlighted in orange in VS Code with a warning:

<img width="232" alt="image" src="https://github.com/phoenixframework/phoenix/assets/5097028/1627ceff-ab17-4cc8-8851-1cf1d0a0c28d">

```
The function call will not succeed.

Phoenix.Controller.put_root_layout(
  _ :: %Plug.Conn{
    :adapter => {atom(), _},
    :assigns => %{atom() => _},
    :body_params => %Plug.Conn.Unfetched{:aspect => atom(), binary() => _},
    :cookies => %Plug.Conn.Unfetched{:aspect => atom(), binary() => _},
    :halted => false,
    :host => binary(),
    :method => binary(),
    :owner => pid(),
    :params => %Plug.Conn.Unfetched{:aspect => atom(), binary() => _},
    :path_info => [binary()],
    :path_params => %{
      binary() =>
        binary()
        | [binary() | [any()] | %{binary() => _}]
        | %{binary() => binary() | [any()] | %{binary() => _}}
    },
    :port => char(),
    :private => %{atom() => _},
    :query_params => %Plug.Conn.Unfetched{
      :aspect => atom(),
      binary() =>
        binary()
        | [binary() | [any()] | %{binary() => _}]
        | %{binary() => binary() | [any()] | %{binary() => _}}
    },
    :query_string => binary(),
    :remote_ip =>
      {byte(), byte(), byte(), byte()}
      | {char(), char(), char(), char(), char(), char(), char(), char()},
    :req_cookies => %Plug.Conn.Unfetched{:aspect => atom(), binary() => binary()},
    :req_headers => [{binary(), binary()}],
    :request_path => binary(),
    :resp_body =>
      nil
      | binary()
      | maybe_improper_list(
          binary() | maybe_improper_list(any(), binary() | []) | byte(),
          binary() | []
        ),
    :resp_cookies => %{binary() => map()},
    :resp_headers => [{binary(), binary()}],
    :scheme => :http | :https,
    :script_name => [binary()],
    :secret_key_base => nil | binary(),
    :state =>
      :chunked | :file | :sent | :set | :set_chunked | :set_file | :unset | :upgraded,
    :status => nil | non_neg_integer()
  },
  {UninvoiceWeb.Layouts, :public_iam_root}
)

breaks the contract
(Plug.Conn.t(), [{format :: atom(), layout()}] | false) :: Plug.Conn.t()
ElixirLS Dialyzer
```

**Comment by tkaretsos** [comment]
You should check the [`layout()` typespec](https://hexdocs.pm/phoenix/Phoenix.Controller.html#t:layout/0).

In your case the following should work:
```
plug :put_root_layout, [html: {AppWeb.Layouts, :public_iam_root}] when action in [:new, :create]
```

**Comment by dsignr** [comment]
> @dsignr you should check the [`layout()` typespec](https://hexdocs.pm/phoenix/Phoenix.Controller.html#t:layout/0).
> 
> In your case the following should work:
> 
> ```
> plug :put_root_layout, [html: {AppWeb.Layouts, :public_iam_root}] when action in [:new, :create]
> ```

I did try that before, it clears the error, but the root layout specified isn't respected anymore. This issue persists across two different applications.

**Comment by dsignr** [comment]
I managed to fix this by updating `plug :put_root_layout, [html: {MyAppWeb.Layouts, :root}]` inside my `router.ex` too.
I guess, if it is not specific enough with the format, it gets overridden with the root layout specified in the router. Not sure what consequence this has though.

**Comment by tkaretsos** [comment]
I had to dig into [`put_root_layout/2` implementation](https://github.com/phoenixframework/phoenix/blob/main/lib/phoenix/controller.ex#L758) to understand what is going on. The atom `:html` is practically a key in a map. That map is initially set in the `router.ex` and later updated by the controller. 

The `router.ex` files of applications that are generated with the latest version of Phoenix application generator ([`phx_new`](https://hexdocs.pm/phoenix/installation.html#phoenix)) use the function like this:
```
...
  plug :put_root_layout, html: {MyAppWeb.Layouts, :root}
...
```

Probably, you generated the app with an older version, same as me and probably many others.

**Comment by dsignr** [comment]
Ah, that explains. Thanks a lot for digging into this. Wish you and everyone on this thread a very happy new year.
