### ISSUE TITLE
CodeReloader printing compile warnings of all source files even in noop situations

### ISSUE THREAD

**Issue by narrowtux** [phoenixframework/phoenix#5440]
### Environment

* Elixir version: 1.14.4 OTP 25
* Phoenix version (mix deps): 1.7.2
* Operating system: Ubuntu 20.04

### Expected behavior
When accessing any HTTP Route, the code reloader should 
A) only trigger if any file has changed
B) only print warnings for files that it has to recompile

### Actual behavior
On every HTTP request, even if no source file has changed, code_reloader prints all compile warnings for all files in the current project. 

### More context

| phoenix version | consolidate_protocols | code_reloader | does it warn? |
|-------------------|-------------------------|-----------------|-----------------|
| <= 1.7.1 | true | true | no |
| 1.7.2 | true | true | YES |
| 1.7.2 | false | true | YES |
| 1.7.2 | – | false | no |

I've tried to call `mix compile.#{compiler} #{args}` myself but these won't print warnings on a fully compiled project.

Calling `recompile()` from IEx also doesn't spam warnings on a non-stale project, it just prints `:noop`.

When printing the compile warnings, the ` warning: ` prefix of the log message is not printed in yellow, unlike in the actual compile step.

**Comment by narrowtux** [comment]
I think I've narrowed it down to this change https://diff.hex.pm/diff/phoenix/1.7.1..1.7.2#14900668--305

**Comment by dbii** [comment]
I am seeing something similar, warnings are showing up in the log before the router logs the request, and upon completion of that request.

**Comment by josevalim** [comment]
Can you please try main?

**Comment by narrowtux** [comment]
thanks 🙏

**Comment by dbii** [comment]
That fixed it for me.

**Comment by narrowtux** [comment]
This issue appeared for me after updating to elixir 1.15.5, regardless of the phoenix version. I previously locked it to 1.17.1 to prevent this issue.

**Comment by Gazler** [comment]
@narrowtux Do you have a sample project or single file project (https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix.exs) that can demonstrate the issue?

**Comment by narrowtux** [comment]
@Gazler yes, it was quite easy to generate: 
https://github.com/narrowtux/phoenix-logspam-reproduction

How to use: start the server and do a HTTP request on `GET /`. On my machine with Elixir 1.15.5 / OTP 26, every time I do that request, it will log the warning from `lib/logspam_web/controllers/root_controller.ex:5`:
![image](https://github.com/phoenixframework/phoenix/assets/616791/fb0ca228-2246-418d-8eb4-2fe5f2afffba)

**Comment by josevalim** [comment]
Oh, btw, this is an intentional change in the Elixir compiler, exactly because it is very easy to miss warnings when code is being compiled behind the scenes. Although it probably makes sense to skip them here. I will push a fix.

**Comment by josevalim** [comment]
Done!
