### ISSUE TITLE
Icons not rendering when trying to use dynamic hero icons in app layout

### ISSUE THREAD

**Issue by loganmac** [phoenixframework/phoenix#5443]
### Environment

* Elixir version (elixir -v): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.2
* Operating system: windows (WSL)

### Context
I was trying to dynamically template a sidebar in my app layout `/lib/myapp_web/components/layouts/app.html.heex` with a list of nav items. Like so:

```heex
<% nav_items = [
  %{name: "Dashboard", icon: "chart-pie"},
  %{name: "Roster", icon: "calendar-days"}
] %>

<main class="px-4 py-20 sm:px-6 lg:px-8">
  <div class="max-w-2xl mx-auto">
    <.flash_group flash={@flash} />
    <aside
      id="sidebar-notification"
      class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
      aria-label="Sidebar"
    >
      <div class="h-full px-3 py-4 overflow-y-auto bg-white border-r border-gray-200 dark:bg-gray-800 dark:border-gray-700">
        <a href="/#" class="flex items-center pl-2 mb-5">
          <!-- <img src={logo} class="h-12 mr-3" alt="Logo" /> -->
        </a>
        <ul class="space-y-2">
          <li :for={item <- nav_items}>
            <a
              href="#"
              class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg hover:bg-gray-100 group dark:text-gray-200 dark:hover:bg-gray-700"
            >
              <.icon
                name={"hero-" <> item.icon}
                class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"
              />

              <span class="ml-3"><%= item.name %></span>
            </a>
          </li>
        </ul>
      </div>
    </aside>

    <%= @inner_content %>
  </div>
</main>
```

### Expected behavior
The icons would render correctly

### Actual behavior
The icons would only render if that specific hero icon was being used somewhere else on the page. So if I used `hero-chart-pie` for another `<.icon />` component, it would render in the dynamic sidebar as well. 

Changing it to use the full icon name (i.e. `hero-chart-pie`) fixed the problem, but it seems like a weird edge-case that could bite users.

**Comment by 03juan** [comment]
This is working as intended since the heroicons are generated through tailwind
 https://github.com/phoenixframework/phoenix/blob/v1.7.2/installer/templates/phx_web/components/core_components.ex#L549
https://github.com/phoenixframework/phoenix/blob/v1.7.2/installer/templates/phx_assets/tailwind.config.js#L36

From "Dynamic class names" section in https://tailwindcss.com/docs/content-configuration
> If you use string interpolation or concatenate partial class names together, Tailwind will not find them and therefore will not generate the corresponding CSS

**Comment by aiwaiwa** [comment]
Indeed, Tailwind compiler looks for full names to construct the map of classes to include.

**Comment by loganmac** [comment]
> This is working as intended since the heroicons are generated through tailwind https://github.com/phoenixframework/phoenix/blob/v1.7.2/installer/templates/phx_web/components/core_components.ex#L549 https://github.com/phoenixframework/phoenix/blob/v1.7.2/installer/templates/phx_assets/tailwind.config.js#L36
> 
> From "Dynamic class names" section in https://tailwindcss.com/docs/content-configuration
> 
> > If you use string interpolation or concatenate partial class names together, Tailwind will not find them and therefore will not generate the corresponding CSS

Fair enough! Learned something new, thanks.
