### ISSUE TITLE
Obsure compiling error

### ISSUE THREAD

**Issue by fceruti** [phoenixframework/phoenix#5452]
### Expected behavior

When code is not compiling, Phoenix 1.7.x returns a pretty message like this:
 
<img width="1422" alt="Screenshot 2023-05-05 at 23 29 32" src="https://user-images.githubusercontent.com/250665/236596694-4b9f6a58-d966-483d-a394-6edf3ffad2b3.png">

### Actual behavior

This is the same error using phoenix main branch. I'm not sure if this is a Phoenix issue or a Bandit one, but I thought I should mention.

<img width="1397" alt="Screenshot 2023-05-05 at 23 28 12" src="https://user-images.githubusercontent.com/250665/236596682-5322288e-fe87-42ed-a3e7-2ad4b2496c76.png">

```
defp deps do
    [
      # {:phoenix, "~> 1.7.1", override: true},
      {:phoenix, github: "phoenixframework/phoenix", override: true},
      {:phoenix_html, "~> 3.0"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      # {:phoenix_live_view, "~> 0.18.6"},
      {:phoenix_live_view, github: "phoenixframework/phoenix_live_view", override: true},
      {:bandit, ">= 0.7.1"},
    ]
  end
```

**Comment by fceruti** [comment]
Well, I'd argue it is a Phoenix or Bandit issue since I added phoenix & bandit to the deps, not Plug.

I do have `debug_errors: true`. If you look closely to the second image (main branch), the error shown in the first image (v1.72.) is embedded inside a `String.trim` error. It seems to me there was a miss match in signature.

Anyways, I updated all deps this morning and the error was gone. One more for the X-Files.

**Comment by hg-runs** [comment]
Though this issue has been closed: I still have the same behaviour.

Updating all deps did not help.
This is with:
` {:phoenix, github: "phoenixframework/phoenix", override: true},`

![2023-05-08 19_36_03-FunctionClauseError at GET _support — Mozilla Firefox](https://user-images.githubusercontent.com/29901271/236892995-0b0a38ff-8faf-43ab-996e-aef29101892b.png)

**Comment by fceruti** [comment]
Yeah, sorry for that, I still got the error same as you. I quickly dismissed it cause I just didn't want to waste anyone's time :P

**Comment by phoebe100** [comment]
I'm sorry, I completely misunderstood your issue.
Now, I see that the "no function clause matching in String.trim/1" __is not__ coming from your code-base, but is raised due to some phoenix internal handling when recompiling/reloading your code-base (containing a compilation error)

I can confirm that this is a phoenix issue, introduced with one of the most recent commits in main branch.

The internal data structure in Phoenix.CodeReloader.Proxy has changed from String to List while Phoenix.CodeReloader still expects a String.

So thank you for opening :)

**Comment by josevalim** [comment]
Thank you @phoebe100 for helping debug issues and all the pull requests. Your comment made it very easy for me to fix it. :heart:
