### ISSUE TITLE
** (Mix) You're trying to run :phx_new on Elixir v1.9.1 but it has declared in its mix.exs file it supports only Elixir ~> 1.14

### ISSUE THREAD

**Issue by hillaryomondi** [phoenixframework/phoenix#5458]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* Operating system:

**Comment by Gazler** [comment]
Missing details. Looks like you might be running `phx.new` inside of an existing project instead of from the hex package?
