### ISSUE TITLE
MIX_ENV=prod mix assets.deploy failing in umbrella app

### ISSUE THREAD

**Issue by thomasdola** [phoenixframework/phoenix#5461]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]
Elixir 1.14.0 (compiled with Erlang/OTP 25)

* Phoenix version (mix deps): 1.7.2
* Operating system: Mac Os Ventura

### Steps to reproduce

1. mix phx.new app --umbrella (make app is running without any issue)
2. mix deps.get --only prod
3. MIX_ENV=prod mix compile
4. MIX_ENV=prod mix assets.deploy

### Expected behavior
Assets should be compiled without error

### Actual behavior
** (Mix) The task "assets.deploy" could not be found

**Comment by Shaka-n** [comment]
I might be mistaken, but I think in a vanilla umbrella app you need to run `mix assets.deploy` from the `app_web` directory. It's aliased in the `mix.exs` file there, but not in the umbrella app's mix file:

```
defp aliases do
    [
      setup: ["deps.get", "assets.setup", "assets.build"],
      test: ["ecto.create --quiet", "ecto.migrate --quiet", "test"],
      "assets.setup": ["tailwind.install --if-missing", "esbuild.install --if-missing"],
      "assets.build": ["tailwind default", "esbuild default"],
      "assets.deploy": ["tailwind default --minify", "esbuild default --minify", "phx.digest"]
    ]
  end
```
