### ISSUE TITLE
Implementation of basic CSP fails on new Phoenix install

### ISSUE THREAD

**Issue by sundikhin** [phoenixframework/phoenix#5465]
### Environment

* Elixir version (elixir -v): Elixir 1.14.3
* Phoenix version (mix deps): 1.7.2
* Operating system: MacOS Big Sur

### Expected behavior
* Generate a new app with `mix phx.new` 
* Add a basic default-src CSP rule
* See no errors in the console

### Actual behavior
* Generate a new app with `mix phx.new` 
* Add a basic default-src CSP rule
* Errors rendered in the console regarding inline styles and data:url for icons, see below:

<img width="1279" alt="Screen Shot 2023-05-18 at 1 26 33 PM" src="https://github.com/phoenixframework/phoenix/assets/9601588/396f600d-a02d-4fe2-9203-19f4186230b4">

![csp-issue](https://github.com/phoenixframework/phoenix/assets/9601588/656d60d7-739a-4856-8633-2a448d472f98)

#### How to reproduce this error
* `mix phx.new [some_app]`
* Add a default CSP rule ( `"content-security-policy" => "default-src 'self'"` ) to the `:put_secure_browser_headers` plug in the router.ex file
* Run server (mix phx server)
* Check browser's dev tools console for errors
* See error

#### Suggested Solution for Inline Style issue
There are a few options to fix the inline style issue in your CSP; however most may leave the app vulnerable by allowing inline styles in your application. This [could be bad](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles)

I'm recommending to move the one inline style in the project to the app.css file

In `root.html.heex` there is an inline style on the html:
```
<html lang="en" style="scrollbar-gutter: stable;">
```

It could become this in the app.css:
```
html {
  scrollbar-gutter: stable;
}
```

#### Suggested Solution for Icon rendering issue

The solution for the icon rendering is more complex and may need further input from the Phoenix team. The main issue comes from the Tailwind config utilizing data:url [in the custom plugin for Heroicons](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_assets/tailwind.config.js#L54). Similarly to inline styles, most CSP solutions to allow the icons to render would be to allow data:urls, but is also similarly [unsafe](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs). 

I came up with a workaround / solution that worked for my team to render the icons, but I wouldn't assume that everyone wants that same solution in their core phoenix application. I'm happy to discuss and contribute my solution to anyone who wants to look at this.

![image](https://github.com/phoenixframework/phoenix/assets/9601588/2c6bfb27-308f-4845-b343-02533d13f871)

**Comment by sundikhin** [comment]
Hey @jeregrine, this is the issue we discussed the other day! Tagging for visibility.

**Comment by chrismccord** [comment]
The icons can be fixed by specifying the proper CSP headers:

    img-src 'self' data:;

Going with the most restrictive CSP is going to necessarily break some thikngs. For example the `<.live_image_preview>` relies on data uris. After digging in, I haven’t seen any real risk of data URIs in stylesheets.

I'll fix the style tag issue by using the tailwind JIT for "inline" rules. 

Thanks!
