### ISSUE TITLE
Input component from CoreComponents retains label visibility when type="hidden"

### ISSUE THREAD

**Issue by holobeat** [phoenixframework/phoenix#5467]
### Environment

* Elixir version: 1.14.3
* Phoenix version: 1.7.2
* Operating system: Linux Mint 20.3

### Expected behavior
When `input` component from `CoreComponents` is set to `type="hidden"`, the label should be hidden as well.

### Actual behavior
The following code keeps the label visible:
`<.input type="hidden" field={@form[:customer_id]} label="Customer" />`

**Comment by chrismccord** [comment]
if you pass a label it will be visible, but if you don't pass a label it won't render one, correct? So why pass the label if it's hidden?

**Comment by holobeat** [comment]
Yes I can remove the label attribute. Not a deal breaker. I had a generator to automatically create a series of input fields with labels, one of them was id of the record. So I changed the type to "hidden" and the field's label was still visible.
