### ISSUE TITLE
Documentation for `assert_error_sent/2` does not match actual behavior

### ISSUE THREAD

**Issue by roelandvanbatenburg** [phoenixframework/phoenix#5480]
### Environment

* Elixir version (elixir -v): Elixir 1.14.2 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.3
* Operating system: macOS 12.6.3

### Expected behavior

Test as described in the example for [assert_error_sent/2](https://hexdocs.pm/phoenix/1.7.3/Phoenix.ConnTest.html#assert_error_sent/2) to be working

### Actual behavior

```
  1) test GET /users/not-found (VerifyAssertErrorSentWeb.ErrorHTMLTest)
     test/verify_assert_error_sent_web/controllers/error_html_test.exs:16
     expected error to be sent as 404 status, but response sent 404 without error
     code: assert_error_sent(:not_found, fn ->
     stacktrace:
       (phoenix 1.7.3) lib/phoenix/test/conn_test.ex:669: Phoenix.ConnTest.assert_error_sent/2
       test/verify_assert_error_sent_web/controllers/error_html_test.exs:17: (test)
```

### Context

This is introduced by https://github.com/phoenixframework/phoenix/pull/5445, if I revert those changes, my test succeed again. I do not know if `RenderErrors.__catch__/5`, `assert_error_sent/2` or the documentation needs to be changed.

**Comment by phoebe100** [comment]
I think the change in #5445 is correct, so I would say the examples in `assert_error_sent/2` should be adjusted to reduce confusion
