### ISSUE TITLE
Phoenix.VerifiedRoutes.url/2  is not using the conn.host to generate the url 

### ISSUE THREAD

**Issue by a3kov** [phoenixframework/phoenix#5489]
### Environment

* Elixir version (elixir -v): 1.14.5
* Phoenix version (mix deps): 1.7.5
* Operating system:

### Expected behavior
I am not sure if it's a bug, a missing feature or something wrong with my setup. I am expecting it to use the current host (which is `conn.host`), and not the default one (which is endpoint configuration host)

### Actual behavior
```elixir
IO.inspect(conn)
url = url(conn, ~p"/oauth2/google/callback")
IO.inspect(url)
```
`conn.host` is different from the url hostname. Url hostname seems to be always equal to the endpoint host

**Comment by a3kov** [comment]
I completely missed `Phoenix.Controller.put_router_url()` but I think it should belong to router or endpoint.
I would not expect to find it in the controller api.

**Comment by chrismccord** [comment]
This is expected and the way the router helpers have always worked (before verified routes as well). You can use put_router_url or build a URI specific to the host. Thanks!
