### ISSUE TITLE
ESBuild not allowing import of Phoenix and LiveView suite in the app.js file

### ISSUE THREAD

**Issue by fahedmahidi** [phoenixframework/phoenix#5491]
### Environment

* Elixir version (elixir -v): 1.14.5
* Phoenix version (mix deps): 1.7.6
* Operating system: MacOS Monterey

### Expected behavior
No error at first build right after installing Phoenix with the following command : `mix phx.new projectname --no-ecto`

### Actual behavior

As soon as I create the Phoenix app with `mix phx.new projectname --no-ecto ` I can’t have it to work with LiveView activated.

When I try to launch the server with ` mix phx.server ` I get the following :

```
[info] Running TestWeb.Endpoint with cowboy 2.10.0 at 127.0.0.1:4000 (http)
[info] Access TestWeb.Endpoint at http://localhost:4000
[watch] build finished, watching for changes...
✘ [ERROR] Could not resolve "phoenix_html"

    js/app.js:19:7:
      19 │ import "phoenix_html"
         ╵        ~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "phoenix_html" here because it's not listed as a dependency of this package:

    ../../../../../../../.pnp.cjs:45:33:
      45 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "phoenix_html" as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "phoenix"

    js/app.js:21:21:
      21 │ import {Socket} from "phoenix"
         ╵                      ~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "phoenix" here because it's not listed as a dependency of this package:

    ../../../../../../../.pnp.cjs:45:33:
      45 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "phoenix" as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "phoenix_live_view"

    js/app.js:22:25:
      22 │ import {LiveSocket} from "phoenix_live_view"
         ╵                          ~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "phoenix_live_view" here because it's not listed as a dependency of this package:

    ../../../../../../../.pnp.cjs:45:33:
      45 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "phoenix_live_view" as external to exclude it from the bundle, which will remove this error.

3 errors
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

Rebuilding...

Done in 339ms.
```

In the priv folder there is no js content.

FYI : When downgrading to 1.7.0 there is no such error.

You can save some time and have a look at elements already considered in the following forum post : https://elixirforum.com/t/esbuild-and-yarn-not-allowing-import-of-phoenix-and-liveview-suite-in-the-app-js-file/56569

**Comment by tcoopman** [comment]
I'm just running into the same issue...:

```
Well, I’m just running into this same issue myself.

mix archive.install hex phx_new
mix phx.new --no-ecto TestTailwind
cd tailwind_test/
mix phx.server
...
✘ [ERROR] Could not resolve "phoenix_html"

    js/app.js:19:7:
      19 │ import "phoenix_html"
         ╵        ~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "phoenix_html" here because it's not listed as a dependency of this package:
...
```

Will try to find out what's going on later

**Comment by tcoopman** [comment]
esbuild release 0.15.0 introduces this behaviour (https://github.com/evanw/esbuild/releases/tag/v0.15.0).

There are 2 possible solutions:
1. switching back esbuild 0.14.54 in your `config/config.exs` will fix it.
2. fix the actual reasion yarn is detected as described now:

As you can read in that release, esbuild uses some algorithm to detect yarn plug'n'play. If it detects, yarn it will use that algorithm and you get the errors as described above.

If you had yarn installed at some point in time and didn't clean up completely, you're likely to run into this.
You can easily find out why esbuild uses the yarn plug'n'play mode by changing your esbuild line `config/dev.exs` to this:
```elixir
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch --log-level=verbose)]},
```

This add `--log-level=verbose`. And that will print why it detects yarn mode. For me it was a file `~/.pnp.cjs` file. When I removed this, everything was working fine.

This is not an phoenix issue, so it can be closed.

**Comment by fahedmahidi** [comment]
I went back to it way later than I expected. 

I aded the "verbose" log-level and it was the same issue for me. 

Everything is ok after deleting ~/.pnp.cjs

Thanks for your effort !

**Comment by hichemfantar** [comment]
i had the same problem because [`pnp.loader.mjs` and `.pnp.cjs`](https://stackoverflow.com/questions/74958055/why-yarn-creates-a-pnp-loader-mjs-and-pnp-cjs-files) files exist in the home directory and fixed it by deleting them

related: https://github.com/evanw/esbuild/issues/2495#issuecomment-1227269139
