### ISSUE TITLE
Couldn't watch /home/app: Too many open files

### ISSUE THREAD

**Issue by joyboy67** [phoenixframework/phoenix#5504]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.6
* Operating system: OpenBSD 7.3

### Actual behavior

Hello, I'm using Phoenix Framework 1.7.6 on OpenBSD 7.3

I get this message `Couldn't watch /home/app: Too many open files` after lanch a Phoenix server `mix phx.server`

**Comment by garaujodev** [comment]
I think that isn't phoenix related: It's the resource limit from the shell, generally know/configurable over as`ulimit` in many Linux distros.

I suggest you to search using the term "**openbsd too many open files**" and you'll find some ways to increase this limit.
