### ISSUE TITLE
File with digest is not used on VerifiedRoute with anchor

### ISSUE THREAD

**Issue by yuri-constante-thescore** [phoenixframework/phoenix#5507]
### Environment

* Elixir version (elixir -v): Elixir 1.14.5 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps):  phoenix 1.7.6, phoenix_live_view 0.18.18
* Operating system: macOS 13.4

### Actual behavior

When using verified routes to an asset that has an anchor, for example when using SVG Sprites, the generate route doesn't include the digest file, instead linking to the version without the digest. 

```
defmodule RouteExample do
  use DemoWeb, :verified_routes

  def icons do
    ~p"/images/icons.svg"
  end
  def icons_with_fragment do
    ~p"/images/icons.svg#warning"
  end
end

```

With the module above, running with MIX_ENV=prod, this is the current output:
```
iex> Example.icons()
"/images/icons-6051db34009ab48e6232cf685fca2bd4.svg?vsn=d"
iex> Example.icons_with_fragment()
"/images/icons.svg#warning"

```

### Expected behavior

Both routes should link to the file with the digest in it's name.

**Comment by phoebe100** [comment]
Hi yuri,

I'm curious - does is work if you edit your `priv/static/cache_manifest.json` manually and add:
`"images/icons.svg#warning": "images/icons-6051db34009ab48e6232cf685fca2bd4.svg#warning",`
right after `"images/icons.svg": "images/icons-6051db34009ab48e6232cf685fca2bd4.svg",` ?

This could be your workaround until the issue is fixed

**Comment by yuri-constante-thescore** [comment]
Yes, modifying the `cache_manifest.json`solved it.
Another workaround is to declare the path without the anchor, and add the anchor after

```
defmodule RouteExample do
  use DemoWeb, :verified_routes

  def icons_with_fragment_workaround do
    icons_path = ~p"/images/icons.svg"
    "#{icons_path}#warning"
  end
end
```

```
iex> Example.icons_with_fragment_workaround()
"/images/icons-6051db34009ab48e6232cf685fca2bd4.svg?vsn=d#warning"
```

**Comment by phoebe100** [comment]
Yeah, I think your solution is far more than a workaround. 
You could even solve it in one line (`~p"/images/icons.svg" <> "#warning"`)
Now, I'm not sure whether we really need a fix for something that can be solved that easily.
