### ISSUE TITLE
Inconsistent arithmetic with recursion when placed on vm with multiple cpu

### ISSUE THREAD

**Issue by RobPando** [phoenixframework/phoenix#5520]
### Environment

* Elixir version (elixir -v): Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.15.0 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.6
* Operating system: Docker- debian:bullseye-20230612-slim

### Actual behavior
When I run a simple phoenix app with the following module
```elixir
defmodule TestCurvy.Util do
  # Recursive inv function
  def inv_op(lm, hm, low, high) when low > 1 do
    r = div(high, low)
    inv_op(hm - lm * r, lm, high - low * r, low)
  end

  def inv_op(lm, _hm, _low, _high), do: lm
end
```
and I run something like this `TestCurvy.Util.inv_op(1, 0, 85715544340734810568335997580837940913292120770256072394575581398011106779447, 115792089237316195423570985008687907853269984665640564039457584007908834671663)`
Locally I get the CORRECT output which is: `23540938214369567692016788189744227367858201159418889382729252922507896748155`

However running this on a docker container (I found this out from running in fly.io but can reproduce locally) something happens to the arithmetics along the way get out of wack and I get this output `-12386495990679745160386149006720629616816317566663855265396018338693106960261`

I tried tracking it and I dont know why but along the way `hm - lm * r` trips up within the recursion to where `hm` is not calculated it just rolls with `lm*r` weirdest thing.  I have this test app https://github.com/RobPando/test-fly-curvy-issue
If this is run locally it will give the correct output but if you build it via docker with the following steps:
1. `docker build . --tag roberto:latest`
2. `docker run -e DATABASE_URL=file:///foo.sqlite -e SECRET_KEY_BASE=whatevs -p 8000:8000 roberto:latest`
3.  `docker ps` => to get CONTAINER ID
4. docker exec -it CONTAINER_ID /app/bin/test_fly_curvy_app remote

then run the function I mention you will get the wrong output. At first I thought it was an issue with elixir or Erlang versions however if you copy paste the whole module code I pasted above and run the function on iex it give the correct output no matter the environment. Only occurs within the phoenix app. Also I tried it on fly with 1 CPU and it gives the correct output, anything above 1 gives the wrong one.

### Expected behavior

Consistency across environments.

**Comment by chrismccord** [comment]
This is not a Phoenix issue. The code is built differently when compiling in iex, so it sounds like this is a compiler/erlang issue. But I’m confident it’s not related to Phoenix. Thanks!

**Comment by josevalim** [comment]
This is definitely a bug somewhere lower down the stack. Can you please try Erlang/OTP 26.0.2? Also, if it only happens in Docker, it may be an emulation bug too. Given you can reproduce it with a single module, can you try doing a simple image with Elixir that does `elixir path/to/script.exs` that defines the module and invokes it? Further breaking it down will help report it upstream. (Also, is Debian the system OS or your own OS?).

**Comment by josevalim** [comment]
@RobPando and feel free to further ping me!

**Comment by josevalim** [comment]
Oh, I see you just reported this on Elixir's repo, let's continue the convo there.
