### ISSUE TITLE
Phx digest is not working as expected in production

### ISSUE THREAD

**Issue by derpycoder** [phoenixframework/phoenix#5528]
### Environment

* Elixir version (elixir -v):
`elixir              1.15.4`
`erlang              26.0.2`
* Phoenix version (mix deps):
`phoenix             1.7.6`
* Operating system:
`Mac M1 for Dev`
`Deployed on Render`

Hey Guys,

I have deployed my learning/tools project on [Render.com](http://render.com/).

However, I’m running into an issue. I have used custom Fonts for my site, which works in dev and production build locally, however, when I deploy it using Render, it fails.

See: [DerpyTools](https://derpytools.onrender.com)

### Actual behavior
![image](https://github.com/phoenixframework/phoenix/assets/25662120/d3b3250d-0560-4d49-bc29-8328b7dc6f40)
![image](https://github.com/phoenixframework/phoenix/assets/25662120/f8e55454-a4af-47ba-8cc5-845cd84d7e15)

In digested CSS, the font is referred to in this way:
`url(/fonts/barriecito.ttf)`

Here's the manifest being generated, which also has proper hashed values: [See the Manifest](https://derpytools.onrender.com/cache_manifest.json)

But those hashed values are not being referred to inside the CSS file.

### Expected behavior

![image](https://github.com/phoenixframework/phoenix/assets/25662120/ee51cbd8-f442-4b76-846c-8b9d69ddbae4)
![image](https://github.com/phoenixframework/phoenix/assets/25662120/4b47476d-d67d-4f60-b88c-aa498bdcf166)

In digested CSS, the font is referred to in this way:
`url(/fonts/barriecito-94c9ab0c4e14aa8632e6f0f13bd5dfbb.ttf?vsn=d)`

The production build works amicably, locally. But doesn't work as expected after deploying. 

### Dockerfile
```dockerfile
# Find eligible builder and runner images on Docker Hub. We use Ubuntu/Debian
# instead of Alpine to avoid DNS resolution issues in production.
#
# https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=ubuntu
# https://hub.docker.com/_/ubuntu?tab=tags
#
# This file is based on these images:
#
#   - https://hub.docker.com/r/hexpm/elixir/tags - for the build image
#   - https://hub.docker.com/_/debian?tab=tags&page=1&name=bullseye-20230612-slim - for the release image
#   - https://pkgs.org/ - resource for finding needed packages
#   - Ex: hexpm/elixir:1.15.4-erlang-26.0.2-debian-bullseye-20230612-slim
#
ARG ELIXIR_VERSION=1.15.4
ARG OTP_VERSION=26.0.2
ARG DEBIAN_VERSION=bullseye-20230612-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} as builder

# install build dependencies
RUN apt-get update -y && apt-get install -y build-essential git \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV
ENV MIX_ENV="prod"

# install mix dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

# copy compile-time config files before we compile dependencies
# to ensure any relevant config change will trigger the dependencies
# to be re-compiled.
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY priv priv

COPY lib lib

COPY assets assets

# compile assets
RUN mix assets.deploy

# Compile the release
RUN mix compile

# Changes to config/runtime.exs don't require recompiling the code
COPY config/runtime.exs config/

COPY rel rel
RUN mix release

# start a new build stage so that the final image will only contain
# the compiled release and other runtime necessities
FROM ${RUNNER_IMAGE}

RUN apt-get update -y && apt-get install -y libstdc++6 openssl libncurses5 locales \
  && apt-get clean && rm -f /var/lib/apt/lists/*_*

# Set the locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR "/app"
RUN chown nobody /app

# set runner ENV
ENV MIX_ENV="prod"

# Only copy the final release from the build stage
COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/derpy_tools ./

USER nobody

CMD ["sh", "-c", "/app/bin/migrate && /app/bin/server"]

```

---

P.S.

Here's a discussion on Elixir Forum, that is not leading to a solution.

https://elixirforum.com/t/phx-digest-is-not-working-as-expected-in-production/57171/20

**Comment by derpycoder** [comment]
Here's a discussion on Elixir Forum, that is not leading to a solution.

https://elixirforum.com/t/phx-digest-is-not-working-as-expected-in-production/57171/20

**Comment by Gazler** [comment]
Could you please check that `phx.digest` is included in the `assets.deploy` alias in your `mix.exs` aliases?

**Comment by josevalim** [comment]
Please let us know if this is still an issue given the suggestion above.

**Comment by VictorGaiva** [comment]
I'm having a similar issue, where some static files are ignored, and their compressed version are not being generated by `phx.digest`.

I was able to narrow it down to [this regex](https://github.com/phoenixframework/phoenix/blob/97f7cebbf1bb2ab963d945b0f2271d9eb9405364/lib/phoenix/digester.ex#L2). I'm not sure what the reason for this regex is, but it seems to ignore filenames larger than 32 characters. My .js assets are generated by `yarn`, and due to some internal logic are very long.

It would be a good idea to allow this regex to be overwritten in the configuration.

**Comment by josevalim** [comment]
That regex is meant to match already digested files. I agree we can make it configurable. PRs welcome!
