### ISSUE TITLE
Guide - Layouts - Using suggested layouts not working as expected

### ISSUE THREAD

**Issue by fbozhkov** [phoenixframework/phoenix#5532]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): v1.7.7
* Operating system: Ubuntu 22.04.2 LTS

### Expected behavior
The [guide](https://hexdocs.pm/phoenix/components.html#layouts) suggest to make a new application layout `admin.html.heex` by copying `app.html.heex` and editing it to remove the header. In order to use the new layout it is suggested to use 
`def home(conn, _params) do
  conn
  |> put_layout(html: :admin)
  |> render(:home)
end`
where the only difference should be that there is no header.

### Actual behavior
What happens instead is that the div with the text and buttons is no longer spaced to the left as initially, but centered and part of it is hidden under the SVG to the right.
![Imgur](https://i.imgur.com/k410osy.png)

### Additional comments
This part of the guide as it is written suggests that up until this step `app.html.heex` is used as layout, which is actually not true because the home page is rendered with `layout: false` 
```
def home(conn, _params) do
  # The home page is often custom made,
  # so skip the default app layout.
  render(conn, :home, layout: false)
end
```

**Comment by phoebe100** [comment]
Hi fbozhkov,

Thank you for notification. I agree that this is confusing. A PR to fix this is ready.
