### ISSUE TITLE
Illegal variable reference before declaration: input `phoenix_live_view.js`

### ISSUE THREAD

**Issue by davidudo** [phoenixframework/phoenix#5545]
### Environment

* Elixir version 1.14:
* Phoenix version 1.7.1:
* Operating system: MacOS

### Actual behavior

I'm encountering a Closure compilation error while using Phoenix LiveView with the `shadow-cljs` compiler. When I run `shdaow compile app` to compile my ClojureScript files to JavaScript, I get the following error message from my compiler:

```
Closure compilation failed with 1 errors
--- node_modules/phoenix_live_view/priv/static/phoenix_live_view.cjs.js:3561
Illegal variable reference before declaration: input
```
As you can see from the error message it is orignated from a file named `node_modules/phoenix_live_view/priv/static/phoenix_live_view.cjs.js:3561` on line 3561. The code on that line is:

```javascript
let input = inputs.find((el) => el.type !== "hidden") || input[0];
```

### Expected behavior

I expect the Closure compilation process to complete successfully without encountering the `Illegal variable reference before declaration: input` error.

**Comment by chrismccord** [comment]
This is already fixed in main and will be out soon in the next point release. Thanks!

**Comment by davidudo** [comment]
Okay, thank you @chrismccord
