### ISSUE TITLE
Secure: true cookies over regular HTTP cause infinite reload in Safari

### ISSUE THREAD

**Issue by jakemauer** [phoenixframework/phoenix#5549]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.7
* Operating system: Mac OS Ventura 13.5
* Safari 16.6

### Actual behavior

Our session options is setup as following:

```
  @session_options [
    store: :cookie,
    secure: true,
    signing_salt: "asdgasg4",
    encryption_salt: "dsds<dfas4gdg"
]
```

Our app directs to the route `/login` on first load or if your cookie is expired and you attempt to perform an action or navigate to a new route. In Safari when visiting via localhost this login page infinitely reloads. I can see in the Safari developer tools that no cookie is set. 

When I set up a reverse proxy that serves the site via a domain with a valid SSL certificate, the login page loads once and behaves as you would expect.

If I change `secure:` to `false` and load the page in Safari, it sets the cookie and the page loads normally. 

Firefox and Chromium load the page normally regardless of how `secure` is set.

### Expected behavior

Visiting the login page from a logged out/no cookie state only loads the page once and does not redirect the user back to /login. 

Let me know if I should create a simplified repo that reproduces the issue.

**Comment by chrismccord** [comment]
I believe this issue is specific to safari on localhost. You can handle this by setting `secure: true` only in prod based on your config/*.exs. Thanks!
