### ISSUE TITLE
Guide - Telemetry - Telemetry.Metrics.ConsoleReporter not logging to console

### ISSUE THREAD

**Issue by fbozhkov** [phoenixframework/phoenix#5550]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): v1.7.7
* Operating system: Ubuntu 22.04.2 LTS

### Expected behavior
Following the [guide](https://hexdocs.pm/phoenix/telemetry.html#telemetry-metrics-consolereporter) I have uncommented 
```
{Telemetry.Metrics.ConsoleReporter, metrics: metrics()}
```
in `lib/hello_web/telemetry.ex`
and then made some GET requests from the guide project, and I expected to see some metrics logged in the console.

### Actual behavior
There are no Telemetry metrics logged to the console. On LiveDashboard's Metrics Tab there is change to the tables when I make requests, so it works, but nothing in the console where the server is running.

Am I missing something here?

**Comment by LostKobrakai** [comment]
`Telemetry.Metrics.ConsoleReporter` doesn't log values (using `Logger`), but prints them directly to stdout (using `IO.puts`). Are you sure you're attached to the system in a way you get to see plain stdout and not just logs?

**Comment by Gazler** [comment]
@LostKobrakai is correct. I just tested this and could see the results in the console, so I'm assuming it's an issue with stdout. I'm happy to re-open this issue if that's not the case.
