### ISSUE TITLE
can't find include lib "public_key/include/public_key.hrl"

### ISSUE THREAD

**Issue by ZenenTreadwell** [phoenixframework/phoenix#5552]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps):  1.7.7
* Operating system: Debian 5.10.179-5

### Actual behavior
Error on trying to compile phoenix in accordance to the introduction tutorial. Seemingly caused by the title error, shown in more detail here:

```
$ mix compile                                                                                        
==> mint                                                                                             
Compiling 1 file (.erl)                                                                              
src/mint_shims.erl:37:14: can't find include lib "public_key/include/public_key.hrl"                 
%   37| -include_lib("public_key/include/public_key.hrl").                                           
%     |              ^                                                                               
```
 Many other errors follow.

### Expected behavior
I expect phoenix to compile successfully.

**Comment by Gazler** [comment]
How did you install erlang? If you installed with the package manager, you might need to install erlang-dev.

See this thread for some more details: https://elixirforum.com/t/ubuntu-20-04-compile-ssl-verify-fun-fails/32802

**Comment by ZenenTreadwell** [comment]
Well! That seems to have solved one problem and uncovered another. Upon trying to start phx.server, I'm being told that Mix can't find the application file xmerl.app

Any ideas?

**Comment by Gazler** [comment]
You might have to delete your _build and deps directories then try again.

**Comment by ZenenTreadwell** [comment]
I deleted the project repo and reinstalled phx.new. Still same problem.

**Comment by Gazler** [comment]
Looks like you might also need erlang-xmerl.

For what it's worth, you might find fewer compatibility issues installing via a version manager such as asdf. You'll probably find you are able to update more quickly than with the debian package manager too.

https://github.com/asdf-vm/asdf
https://github.com/asdf-vm/asdf-erlang

**Comment by ZenenTreadwell** [comment]
and... we are live! Thank you for your prompt assistance here.
