### ISSUE TITLE
scaffolding of html is broken

### ISSUE THREAD

**Issue by darkblueorange** [phoenixframework/phoenix#5562]
### Environment

* Elixir version (elixir -v): 1.15.4
* Phoenix version (mix deps): 1.7.7
* Operating system: Mac OS Ventura 13.3.1

### Expected behavior

Scaffolding done with 
`mix phx.gen.html SuperTrucs Utilisateurs utilisateurs prenom:string nom:string age:integer`

should generate 
`<.table id="utilisateurs" rows={@utilisateurs} row_click={&JS.navigate(~p"/utilisateurs/#{&1}")}>`
in **lib/erwan_web/controllers/utilisateurs_html/index.html.heex**
instead of actual broken
`<.table id="utilisateurs" rows={@utilisateurs_collection} row_click={&JS.navigate(~p"/utilisateurs/#{&1}")}>`

**Comment by darkblueorange** [comment]
Stacktrace did not copy-paste correctly, sorry : 
`[error] #PID<0.1634.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.1633.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /utilisateurs
** (exit) an exception was raised:
    ** (KeyError) key :utilisateurs_collection not found in: %{
  flash: %{},
  conn: %Plug.Conn{
    adapter: {Plug.Cowboy.Conn,
     %{
       pid: #PID<0.1633.0>,
       port: 4000,
       scheme: "http",
       version: :"HTTP/1.1",
       path: "/utilisateurs",
       host: "localhost",
       peer: {{127, 0, 0, 1}, 60576},
       bindings: %{},
       ref: ErwanWeb.Endpoint.HTTP,
       cert: :undefined,
       headers: %{
         "accept" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
         "accept-encoding" => "gzip, deflate, br",
         "accept-language" => "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
         "cache-control" => "max-age=0",
         "connection" => "keep-alive",
         "cookie" => "_erwan2_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYT2E1dFNFNFppd2Q3WFkzelFJUWpXNnQx.FQ4mnBui78vuyEBZvu-kpvFIvF9Sk7vrviYIhu1C2MI; _erwan_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYdFo1QTVLUGY0M3Q5ZFhZUl9jYUFYYmVQ.WR_iH7f_Ct9sAk5LCp-Xvik3COH6y3knpnmqfcfZX6o",
         "host" => "localhost:4000",
         "referer" => "http://localhost:4000/utilisateurs",
         "sec-ch-ua" => "\"Chromium\";v=\"116\", \"Not)A;Brand\";v=\"24\", \"Google Chrome\";v=\"116\"",
         "sec-ch-ua-mobile" => "?0",
         "sec-ch-ua-platform" => "\"macOS\"",
         "sec-fetch-dest" => "document",
         "sec-fetch-mode" => "navigate",
         "sec-fetch-site" => "same-origin",
         "upgrade-insecure-requests" => "1",
         "user-agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
       },
       method: "GET",
       path_info: :undefined,
       sock: {{127, 0, 0, 1}, 4000},
       host_info: :undefined,
       streamid: 1,
       body_length: 0,
       has_body: false,
       qs: ""
     }},
    assigns: %{
      layout: {ErwanWeb.Layouts, "app"},
      flash: %{},
      utilisateurs: [
        %Erwan.SuperTrucs.Utilisateurs{
          __meta__: #Ecto.Schema.Metadata<:loaded, "utilisateurs">,
          id: 1,
          prenom: "fez",
          nom: "zr",
          age: 3,
          inserted_at: ~N[2023-08-24 20:41:47],
          updated_at: ~N[2023-08-24 20:41:47]
        },
        %Erwan.SuperTrucs.Utilisateurs{
          __meta__: #Ecto.Schema.Metadata<:loaded, "utilisateurs">,
          id: 2,
          prenom: "zzzz",
          nom: "dedede",
          age: 3,
          inserted_at: ~N[2023-08-24 20:42:00],
          updated_at: ~N[2023-08-24 20:42:00]
        }
      ]
    },
    body_params: %{},
    cookies: %{
      "_erwan2_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYT2E1dFNFNFppd2Q3WFkzelFJUWpXNnQx.FQ4mnBui78vuyEBZvu-kpvFIvF9Sk7vrviYIhu1C2MI",
      "_erwan_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYdFo1QTVLUGY0M3Q5ZFhZUl9jYUFYYmVQ.WR_iH7f_Ct9sAk5LCp-Xvik3COH6y3knpnmqfcfZX6o"
    },
    halted: false,
    host: "localhost",
    method: "GET",
    owner: #PID<0.1634.0>,
    params: %{},
    path_info: ["utilisateurs"],
    path_params: %{},
    port: 4000,
    private: %{
      :phoenix_template => "index.html",
      :phoenix_view => %{
        "html" => ErwanWeb.UtilisateursHTML,
        "json" => ErwanWeb.UtilisateursJSON
      },
      ErwanWeb.Router => [],
      :phoenix_endpoint => ErwanWeb.Endpoint,
      :plug_session_fetch => :done,
      :plug_session => %{"_csrf_token" => "tZ5A5KPf43t9dXYR_caAXbeP"},
      :before_send => [#Function<0.71811376/1 in Plug.CSRFProtection.call/2>,
       #Function<4.76681187/1 in Phoenix.Controller.fetch_flash/2>,
       #Function<0.76384852/1 in Plug.Session.before_send/2>,
       #Function<0.54455629/1 in Plug.Telemetry.call/2>,
       #Function<1.63129719/1 in Phoenix.LiveReloader.before_send_inject_reloader/3>],
      :phoenix_request_logger => {"request_logger", "request_logger"},
      :phoenix_router => ErwanWeb.Router,
      :phoenix_action => :index,
      :phoenix_layout => %{"html" => {ErwanWeb.Layouts, :app}},
      :phoenix_controller => ErwanWeb.UtilisateursController,
      :phoenix_format => "html",
      :phoenix_root_layout => %{"html" => {ErwanWeb.Layouts, :root}}
    },
    query_params: %{},
    query_string: "",
    remote_ip: {127, 0, 0, 1},
    req_cookies: %{
      "_erwan2_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYT2E1dFNFNFppd2Q3WFkzelFJUWpXNnQx.FQ4mnBui78vuyEBZvu-kpvFIvF9Sk7vrviYIhu1C2MI",
      "_erwan_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYdFo1QTVLUGY0M3Q5ZFhZUl9jYUFYYmVQ.WR_iH7f_Ct9sAk5LCp-Xvik3COH6y3knpnmqfcfZX6o"
    },
    req_headers: [
      {"accept",
       "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"},
      {"accept-encoding", "gzip, deflate, br"},
      {"accept-language", "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7"},
      {"cache-control", "max-age=0"},
      {"connection", "keep-alive"},
      {"cookie",
       "_erwan2_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYT2E1dFNFNFppd2Q3WFkzelFJUWpXNnQx.FQ4mnBui78vuyEBZvu-kpvFIvF9Sk7vrviYIhu1C2MI; _erwan_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYdFo1QTVLUGY0M3Q5ZFhZUl9jYUFYYmVQ.WR_iH7f_Ct9sAk5LCp-Xvik3COH6y3knpnmqfcfZX6o"},
      {"host", "localhost:4000"},
      {"referer", "http://localhost:4000/utilisateurs"},
      {"sec-ch-ua",
       "\"Chromium\";v=\"116\", \"Not)A;Brand\";v=\"24\", \"Google Chrome\";v=\"116\""},
      {"sec-ch-ua-mobile", "?0"},
      {"sec-ch-ua-platform", "\"macOS\""},
      {"sec-fetch-dest", "document"},
      {"sec-fetch-mode", "navigate"},
      {"sec-fetch-site", "same-origin"},
      {"upgrade-insecure-requests", "1"},
      {"user-agent",
       "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"}
    ],
    request_path: "/utilisateurs",
    resp_body: nil,
    resp_cookies: %{},
    resp_headers: [
      {"cache-control", "max-age=0, private, must-revalidate"},
      {"x-request-id", "F35sttRUcDlFtSYAAAPF"},
      {"referrer-policy", "strict-origin-when-cross-origin"},
      {"x-content-type-options", "nosniff"},
      {"x-download-options", "noopen"},
      {"x-frame-options", "SAMEORIGIN"},
      {"x-permitted-cross-domain-policies", "none"}
    ],
    scheme: :http,
    script_name: [],
    secret_key_base: :...,
    state: :unset,
    status: nil
  },
  utilisateurs: [
    %Erwan.SuperTrucs.Utilisateurs{
      __meta__: #Ecto.Schema.Metadata<:loaded, "utilisateurs">,
      id: 1,
      prenom: "fez",
      nom: "zr",
      age: 3,
      inserted_at: ~N[2023-08-24 20:41:47],
      updated_at: ~N[2023-08-24 20:41:47]
    },
    %Erwan.SuperTrucs.Utilisateurs{
      __meta__: #Ecto.Schema.Metadata<:loaded, "utilisateurs">,
      id: 2,
      prenom: "zzzz",
      nom: "dedede",
      age: 3,
      inserted_at: ~N[2023-08-24 20:42:00],
      updated_at: ~N[2023-08-24 20:42:00]
    }
  ]
}
        lib/erwan_web/controllers/utilisateurs_html/index.html.heex:10: anonymous fn/2 in ErwanWeb.UtilisateursHTML.index/1
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/engine.ex:150: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1
        (phoenix_live_view 0.19.5) lib/phoenix_live_view/engine.ex:166: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/3
        (phoenix 1.7.7) lib/phoenix/controller.ex:1008: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
        (telemetry 1.2.1) /Users/olivierdeprez/Library/CloudStorage/OneDrive-Personnel/Boulot/7lieues/PRODUCT/Technical_stuff/Code/sources/tuto_vitef/elixir_repo/erwan/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix 1.7.7) lib/phoenix/controller.ex:974: Phoenix.Controller.render_and_send/4
        lib/erwan_web/controllers/utilisateurs_controller.ex:1: ErwanWeb.UtilisateursController.acti (truncated)`

**Comment by dannielb** [comment]
Looks like a behavior related to this [commit](https://github.com/phoenixframework/phoenix/commit/9e723c3657227ebf7c8311e0b4a03fd9ed1cb40f#diff-4307581434ae66da4750cde438c2b192c4a11c8b71ba32dbf78aea36daa0ee3eR88).

When the schema name is also in plural we get that problem.

the same error doesn't happen if we scaffold with the schema name in singular:
`mix phx.gen.html SuperTrucs Utilisateur utilisateurs prenom:string nom:string age:integer`

**Comment by darkblueorange** [comment]
I confirm that on singular the problem does not happen for `mix phx.gen.html ...` 👍

**Comment by Gazler** [comment]
I believe this is an oversight in this commit https://github.com/phoenixframework/phoenix/commit/ace80f8c992c3d3d520b9bf351ec6f9d8f74d78f as now both the HTML and Live generators share components.
