### ISSUE TITLE
Phoenix generators use naive Ecto timestamps - UTC would be much better

### ISSUE THREAD

**Issue by lau** [phoenixframework/phoenix#5564]
### Actual behavior

Currently when using the Phoenix generators the timestamps are NaiveDateTime. That means you can't compare them with other `DateTime`s and see which happened first. You can't use `DateTime.to_unix/1` to convert them to unix timestamps. When serializing them, for instance in a JSON API, the consumers of the API won't know if it's in UTC because there won't automatically be a UTC offset indicator (the Z at the end of the ISO8601 timestamp).

Another thing is that a lot of Elixir projects start with the Phoenix generators and are perhaps seen as a good example or a good starting place. I think this could be improved if UTC DateTime were used for timestamps instead of NaiveDateTime.

NaiveDateTime is meant for when you don't know the timezone. We know the Ecto `timestamps` are UTC, so it makes sense that they are UTC DateTime. It's a very good example of when to use DateTime instead of NaiveDateTime. The Ecto default to NaiveDateTime is there for historical reasons when there was less support for DateTime in the Elixir standard library. As far as I understand it, the reason UTC datetimes have not be made the default in Ecto is because it would require releasing a new major version (Ecto 4) to avoid breaking existing behaviour. The Phoenix generators don't have that same restriction since the generated schemas and tables are new.

### Expected behavior

When using the phx generators timestamps should be [UTC DateTime](http://www.creativedeletion.com/2019/06/17/utc-timestamps-in-ecto.html), not NaiveDateTime. One way to do that is to have the schema line specifying the timestamp say `timestamps([type: :utc_datetime])` instead of `timestamps()`.

**Comment by Gazler** [comment]
Presumably the solution here is that all of the schemas will require either:

```
timestamps([type: :utc_datetime])
```

Or 

```
@timestamps_opts [type: :utc_datetime]
```

And the generated migrations will need to be updated accordingly.

One reason I can think of for not doing this is that if we update the generators, users will end up with mismatched date fields if they upgrade phoenix on an existing project.

**Comment by lau** [comment]
> One reason I can think of for not doing this is that if we update the generators, users will end up with mismatched date fields if they upgrade phoenix on an existing project.

As in one existing schema has naive timestamps, but a another newly generated schema has UTC?

True they wouldn't be the same if people have used the generators previously and not corrected the timestamps to be UTC. However it wouldn't break anything that's existing. They don't necessarily have to be the same. People can update existing schemas so they are all UTC. If they don't it will still work.

The way I see it having the better default (UTC) going forward is much more helpful than consistently having worse timestamps in existing projects. And once the change is done, new projects using the generators would all have UTC timestamps of course.

**Comment by Gazler** [comment]
One option here, is to add a generator config to Phoenix and default it to `naive_datetime`, but make new projects (generated with `phx.new`)use `utc_datetime` to ensure consistency across existing projects. If users upgrading wish to use this feature, they can simply upgrade the config.

I know there's technically no reason why timestamps all need to be in the same format, but it may be confusing to for a user if generators start working in a different way than they expect.
