### ISSUE TITLE
Can't install the framework regardless of Elixir version

### ISSUE THREAD

**Issue by jaeyson** [phoenixframework/phoenix#5572]
### Environment

* Elixir version (elixir -v): using asdf, `1.14.0-otp-25`, `1.15.0-otp-25`, `1.15.5-otp-25`
* Operating system: mac os 13.5.1

### Actual behavior

Changing to different Elixir versions didn't help when installing the framework.

What I did:

1. `asdf install elixir 1.15.5-otp-25`
2. `asdf global elixir 1.15.5-otp-25`
3. `mix local.hex --force`
4. `mix archive.install hex phx_new`

then error:

```
Resolving Hex dependencies...
** (MatchError) no match of right hand side value: :error
    (hex 2.0.6) lib/hex/solver/package_lister.ex:47: anonymous fn/4 in Hex.Solver.PackageLister.dependencies_as_incompatibilities/4
    (elixir 1.15.5) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (hex 2.0.6) lib/hex/solver/package_lister.ex:46: Hex.Solver.PackageLister.dependencies_as_incompatibilities/4
    (hex 2.0.6) lib/hex/solver/solver.ex:123: Hex.Solver.Solver.choose_package_version/1
    (hex 2.0.6) lib/hex/solver/solver.ex:25: Hex.Solver.Solver.solve/2
    (hex 2.0.6) lib/hex/solver.ex:53: Hex.Solver.run/5
    (hex 2.0.6) lib/hex/remote_converger.ex:114: Hex.RemoteConverger.run_solver/5
    (mix 1.15.5) lib/mix/dep/converger.ex:141: Mix.Dep.Converger.all/4
```

I even uninstalled it (`mix archive.uninstall phx.new`) then doing all the steps again, but still the same error throws up.

### Expected behavior

Following the guide from hexdocs (phx v1.7.7) there shouldn't be any issues at all when installing Phoenix framework.

**Comment by Gazler** [comment]
I can't replicate this locally, looks like it could potentially be a hex issue.

https://github.com/hexpm/hex/blob/main/lib/hex/solver/package_lister.ex#L47

Could you please provide the output of `mix hex.info`?

**Comment by jaeyson** [comment]
@Gazler

```
Hex:    2.0.6
Elixir: 1.15.5
OTP:    25.0

Built with: Elixir 1.14.2 and OTP 23.3
```

**Comment by Gazler** [comment]
@ericmj could you please confirm that this is a hex issue and do you have any ideas what could be causing this issue?

**Comment by jaeyson** [comment]
@Gazler @ericmj I've updated the description by adding another scenario.

**Comment by Gazler** [comment]
I think your new issue may be unrelated to this.

Please see https://github.com/phoenixframework/phoenix/issues/5552

**Comment by jaeyson** [comment]
@Gazler you're correct. No issues with running with Ubuntu, it's just weird why I'm getting those error on osx.

**Comment by jaeyson** [comment]
@Gazler @ericmj I'm very sorry for the trouble, removing this folder `.hex` somehow fixed my problem. Can I close this issue?

**Comment by Gazler** [comment]
Thanks for providing your solution, it might help someone in the future!
