### ISSUE TITLE
:fullsweep_after option is ignored

### ISSUE THREAD

**Issue by zookzook** [phoenixframework/phoenix#5573]
### Environment

* Elixir version (elixir -v): Elixir 1.15.4
* Phoenix version (mix deps): 1.6.16
* Operating system: Mac OS X

### Actual behavior

From the [documents](https://github.com/phoenixframework/phoenix/blob/0a089170e02dc91d56545aba9df5bc618acfd247/lib/phoenix/socket.ex#L90C1-L90C1), it is possible to set the `:fullsweep_after` option in the web sockets part of the endpoint configuration. 

```elixir
defmodule Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :web
  
  socket "/socket", OnsenWeb.UserSocket,
    websocket: [fullsweep_after: 20],
    longpoll: false
```

It seems after using the `WebSock` package it does not work anymore. 
See https://github.com/phoenixframework/phoenix/commit/623ea995ddfd60e8d912b0af137351ee1a32f913

My workaround is to set the process flags right in the `init/1` function of my user socket module like this:

```elixir
defmodule Web.UserSocket do
  use Phoenix.Socket
  
  ...
  
  @impl true
  def init(state) do
    res = {:ok, {_, socket}} = super(state)
    :erlang.process_flag(:fullsweep_after, 20)
    res
  end
```

### Expected behavior

Either the documentation must be adjusted, or the `:fullsweep_after` option must be reused in the code. By using the workaround I can verify that the value of the `:fullsweep_after` option changed to the desired value of the web socket process (initial call :cowboy_clear.connection_process/4).

**Comment by Gazler** [comment]
See the discussion here: https://github.com/elixir-plug/plug_cowboy/pull/88#issuecomment-1296287958

and this commit: https://github.com/phoenixframework/phoenix/commit/bf1f2bfc

I believe it should be handled by:

https://github.com/phoenixframework/websock_adapter/blob/cb18cce92a56fa16ec0cc1becccf196de5a27c58/lib/websock_adapter/cowboy_adapter.ex#L15
https://github.com/phoenixframework/websock_adapter/blob/cb18cce92a56fa16ec0cc1becccf196de5a27c58/lib/websock_adapter.ex#L69

But if not, then this could be a bug.

**Comment by zookzook** [comment]
Thank you for your fast response. I think I will update to the latest version first and try it again. I'm closing the issue.

**Comment by zookzook** [comment]
After updating Phoenix to the latest version it works as expected!
