### ISSUE TITLE
Possible inconsistent usage of `unique_index` in context docs

### ISSUE THREAD

**Issue by jakobsen** [phoenixframework/phoenix#5594]
I am going through the guides, and noticed a possible inconsistency in the [Context docs](https://hexdocs.pm/phoenix/contexts.html).

When creating the `product_categories` table, it's made a point about how because one of the columns feature as the leftmost column in a `unique_index`, it doesn't need a separate index as this would only increase the write cost without bringing any benefit for reads. [This is the relevant line in the docs.](https://github.com/phoenixframework/phoenix/blob/2fc7fe7ac3f59adb7fa004e62452cb67551c12c4/guides/contexts.md?plain=1#L379)

Later, in when modifying the generated migration file for `cart_items`, a `unique_index` is added without removing the `cart_id` index. This seems inconsistent with the previous recommendation. [That happens here.](https://github.com/phoenixframework/phoenix/blob/2fc7fe7ac3f59adb7fa004e62452cb67551c12c4/guides/contexts.md?plain=1#L626)

Should this be updated? I am more than happy to create a pull request if that is the case :)

**Comment by Gazler** [comment]
Yeah, I don't see why the docs shouldn't be changed to reflect it for consistency. Would even be happy for a note here, something like:

"As with the product_categories, we are using a multi column index, so a separate index of the leftmost field (cart_id) is not required."

And for reference, here's the postgres docs about multi column indexes. https://www.postgresql.org/docs/16/indexes-multicolumn.html
