### ISSUE TITLE
Phoenix exs files

### ISSUE THREAD

**Issue by Elimuhub-coder** [phoenixframework/phoenix#5597]
### Environment

* [Elixir version (elixir -v): 1.12.3](https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix.exs)
* Phoenix version (mix deps): 1.6.2
* Operating system: Windows 10

### Actual behavior

The error message was:

** (Mix) Could not start application elimuhub_tuition_and_consultants: ElimuhubTuitionAndConsultants.Application.start(:normal, []) returned an error: shutdown: failed to start child: ElimuhubTuitionAndConsultantsWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.Endpoint.Handler
        ** (EXIT) an exception was raised:
            ** (ArgumentError) module Elimuhub Tuition And Consultants is not a valid module name
                (elixir 1.12.3) lib/module.ex:49: Module.split/1
                (phoenix 1.6.2) lib/phoenix/endpoint/handler.ex:109: Phoenix.Endpoint.Handler.init/1
                (stdlib 3.15.2) gen_server.erl:423: :gen_server.init_it/2
                (stdlib 3.15.2) gen_server.erl:390: :gen_server.init_it/6
                (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

### Expected behavior
I tried to run the phoenix.exs file from the mix_install_examples repository, but I got an error saying that Elimuhub Tuition And Consultants was not a valid module name.

I expected the phoenix.exs file to run without errors and start a web server on port 4000.

### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* Operating system:

### Expected behavior
I tried to run the phoenix.exs file from the mix_install_examples repository, but I got an error saying that Elimuhub Tuition And Consultants was not a valid module name.

**Comment by josevalim** [comment]
Did you do any modifications to the file? You say you use `mix_install_examples` but the repository does not mention "elimuhub_tuition_and_consultants". Therefore, please provide the full file you are trying to run.

**Comment by Gazler** [comment]
@Elimuhub-coder ping

**Comment by josevalim** [comment]
Closing this, if this is still a problem, please give us more info!
