### ISSUE TITLE
Unit testing controllers

### ISSUE THREAD

**Issue by sclearion** [phoenixframework/phoenix#560]
How would I go about implementing unit tests for controllers and sockets?

**Comment by amarandon** [comment]
FWIW here's a possible approach to test controllers, including setting up a test database: http://alexmarandon.com/articles/testing_phoenix_controllers/

**Comment by sclearion** [comment]
Amazing!!!!!!!!!!!!! This is what I needed for I was about to brush over
getting into Phoenix for lack of documentation on Unit Testing as I am a
TDD junkie :) You guys are awesome

**Comment by chrismccord** [comment]
fwiw, we’re going to release test helpers soon that should make this easier. Rest assured, testing is very important to use too. One of the beautiful things about functional programming and the plug architecture is it makes testing controllers (and plugs) in isolation super simple.

**Comment by paulcsmith** [comment]
@chrismccord That is great to hear! Is there a checklist or issue somewhere so that we can help contribute?

**Comment by joakimk** [comment]
Just in case anyone finds it useful: this test setup worked for me to make a post to an API endpoint.

```elixir
import Plug.Test

test "..." do
   response = post "/api/something", foo: 5
   assert response.status == 200
end

defp post(url, params) do
  conn = conn(:post, url, params)
  MyApp.Router.call(conn, MyApp.Router.init([]))
end
```

Not sure if this is the recommended way to do phoenix testing, but it is the level of testing I usually go for when building JSON APIs.
