### ISSUE TITLE
phx.gen.html regression from 1.7.7 -> 1.7.9 breaks /new form

### ISSUE THREAD

**Issue by dch** [phoenixframework/phoenix#5603]
### Environment

* Elixir version (elixir -v): 1.15.7
* Phoenix version (mix deps): 1.7.9
* Phoenix install archive: 1.7.9
* Operating system: FreeBSD 15.0-CURRENT

NB this relates to the *phx.new* generators, even though the resulting application
will be running v1.7.9 because mix downloads most recent dependencies.

### Actual behaviour

After creating a new phx project using the 1.7.9 phx_new archive, a generated
HTML form crashes when accessing the `.../new` resource, via post or list, instead
of the expected minimal form.
 
![gen-v1.7.9](https://github.com/phoenixframework/phoenix/assets/284368/18a0598f-244d-4406-8182-9b9fbf50ebee)

...

### Reproduce

```
$ mix archive.install hex phx_new 1.7.9
$ mix phx.new -v
$ Phoenix installer v1.7.9
$ mix phx.new toast
$ mix phx.gen.html Messages Message messages message
```

- add `resources "/messages", MessageController` 
- run `mix ecto.reset`
- run `mix phx.server`
- browse to http://localhost:4000/messages/new
- get `KeyError at GET /messages/new` and following error

```iex
key :name not found in: %{
  id: nil,
  label: "Message",
  type: "text",
  prompt: nil,
  field: {%Phoenix.HTML.Form{
     source: #Ecto.Changeset<
       action: nil,
       changes: %{},
       errors: [message: {"can't be blank", [validation: :required]}],
       data: #Toast.Messages.Message<>,
       valid?: false
     >,
     impl: Phoenix.HTML.FormData.Ecto.Changeset,
     id: "message",
     name: "message",
     data: %Toast.Messages.Message{
       __meta__: #Ecto.Schema.Metadata<:built, "messages">,
       id: nil,
       message: nil,
       inserted_at: nil,
       updated_at: nil
     },
     hidden: [],
     params: %{},
     errors: [],
     options: [method: "post", multipart: false],
     index: nil,
     action: nil
   }, :message},
  errors: [],
  rest: %{},
  __changed__: nil,
  inner_block: [],
  __given__: %{
    label: "Message",
    type: "text",
    field: {%Phoenix.HTML.Form{
       source: #Ecto.Changeset<
         action: nil,
         changes: %{},
         errors: [message: {"can't be blank", [validation: :required]}],
         data: #Toast.Messages.Message<>,
         valid?: false
       >,
       impl: Phoenix.HTML.FormData.Ecto.Changeset,
       id: "message",
       name: "message",
       data: %Toast.Messages.Message{
         __meta__: #Ecto.Schema.Metadata<:built, "messages">,
         id: nil,
         message: nil,
         inserted_at: nil,
         updated_at: nil
       },
       hidden: [],
       params: %{},
       errors: [],
       options: [method: "post", multipart: false],
       index: nil,
       action: nil
     }, :message},
    __changed__: nil
  },
  multiple: false
}
```

### Expected behaviour

When the phx_new archive is still on v1.7.7 the expected behaviour is observed:

```
$ mix archive.install hex phx_new 1.7.9
$ mix phx.new -v
Phoenix installer v1.7.7
... same recipe
```

a beautiful form:

![gen-v1.7.7](https://github.com/phoenixframework/phoenix/assets/284368/55291e50-e98f-4552-9215-af7f25e032ba)

## source

See https://git.sr.ht/~dch/toast tags `gen-v1.7.7` and `gen-v1.7.9` for
comparison in generated code.

**Comment by lawik** [comment]
Did not reproduce for me on 1.7.9.

**Comment by dch** [comment]
I'll close this for the moment until I have more info - in a fully
fresh Ubuntu VM I can't repro this either.

**Comment by dch** [comment]
This appears to be caused by stale files in `~/.mix` and `~/.hex`,
even though mix lockfiles are identical in the generated projects.

- removing these entirely, and we get the expected results
- if I move these files over to Ubuntu, to same failure occurs

Any suggestions on what might cause this?

**Comment by chrismccord** [comment]
I don't believe this is anything on our side. Also double check that you don't have another app running on localhost. Thanks!

**Comment by dch** [comment]
OK, tracked it down - presence of older version of phoenix in
`~/.mix/archives/phoenix-1.7.0-rc.0/` causes this failure.

Hope this helps somebody in future!
