### ISSUE TITLE
Issue with 1.15 and logging Ranch error

### ISSUE THREAD

**Issue by epinault** [phoenixframework/phoenix#5628]
### Environment

* Elixir version (elixir -v): 1.15, OTP 26
* Phoenix version (mix deps): 1.6.16
* Operating system: OSX and Linux

### Actual behavior

Before upgrading from 1.14 OTP25 to 1.15, OTP 26, we never saw those errors. Now those are showing. 

 Ranch listener HalberdWeb.Endpoint.HTTP, connection process #PID<0.1318.0>, stream 1 had its request process #PID<0.1319.0> exit with reason {{%Phoenix.Router.NoRouteError{plug_status: 404,

I don t particular care to see the no route error since they are 404. Did anything change or not compatible with 1.15/OTP26

### Expected behavior

none of the error are showing in logs in 1.14 and OTP25 when I set the logger console to level info (they only show in debug)

**Comment by josevalim** [comment]
I cannot reproduce see those errors in a new app. So please provide a minimal way to reproduce this issue. Thank you.

**Comment by josevalim** [comment]
If there is more info, please let me know!

**Comment by epinault** [comment]
not sure how to repro out side of our apps. it s something maybe due to migrated apps frmo 1.3 all the way to 1.6 likely that must be different but can t tell what yet

**Comment by tarzan** [comment]
@epinault we're experiencing the same behaviour since our upgrade. Normal errors like ArgumentError won't show up in the debug logs anymore, instead we get that same Ranch listener crash error message.

Did you manage to resolve your issues? Can you point me in the right direction?

**Comment by epinault** [comment]
I have not but I am starting to ponder and suspect it relates to this https://github.com/elixir-lang/elixir/issues/13510#issuecomment-2089196649

**Comment by tarzan** [comment]
Thank you! I tried running my code vs the current main branch of the Elixir repo which should have this fix but that did not have any effect.

However, I did stumble upon something else. Our (kinda legacy) code base has the following in the Router:
```ex
  @impl Plug.ErrorHandler
  def handle_errors(conn, params) do
    super(conn, params)

    conn = fetch_session(conn)

    case conn.status do
      # status code 400 is implemented by :phoenix_ecto to translate Ecto.(Query.)CastErrors
      # this happens when for example a user enters an invalid id in the url
      400 -> FallbackController.call(conn, {:error, :not_found})
      403 -> FallbackController.call(conn, {:error, :forbidden})
      404 -> FallbackController.call(conn, {:error, :not_found})
      _ -> FallbackController.call(conn, conn.status, :other)
    end
  end
```

That `super` call was in there to make sure the error was picked up by Sentry, but I do not think it is necessary anymore in their latest version. When I remove the 'super' call I will not get the crashing Ranch errors anymore but just the actual underlying errors (MatchErrors, ArgumentErrors or whatever).

Maybe this can help you out as well @epinault ?

**Comment by epinault** [comment]
maybe? they have disappeared and I am not sure I did anytbing different other that package update around cowboy...
