### ISSUE TITLE
Multiple web apps in umbrella project generate conflicting esbuild and tailwind configs

### ISSUE THREAD

**Issue by bandesz** [phoenixframework/phoenix#5631]
### Environment

* Elixir version (elixir -v): 1.15.6 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.10
* Operating system: macOS Ventura 13.6

### Actual behavior

I've created a Phoenix umbrella app and generated a second web application into it.

This resulted in duplicated configs generated for `:esbuild` and `:tailwind` in `config/config.exs`:

```
config :esbuild,
  version: "0.17.11",
  default: [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../apps/hello_admin_web/assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]

config :esbuild,
  version: "0.17.11",
  default: [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../apps/hello_web/assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]
```

```
config :tailwind,
  version: "3.3.2",
  default: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../apps/hello_admin_web/assets", __DIR__)
  ]

config :tailwind,
  version: "3.3.2",
  default: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../apps/hello_web/assets", __DIR__)
  ]
```

When I run either the umbrella or a single app directly with `mix phx.server`, the `priv/static/assets/app.[css|js]` files will be generated only for one of the applications. It seems that the last definition of `:tailwind` and `:esbuild` will be the effective config.

### Expected behavior

`priv/static/assets/app.[css|js]` should be generated for all web apps in an umbrella.

**Comment by bandesz** [comment]
What I found working is to define an app-specific profile for tailwind and esbuild (credit goes to Chris Dosé for the suggestion), e.g.:
```
config :tailwind,
  version: "3.3.2",
  hello_admin_web: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../apps/hello_admin_web/assets", __DIR__)
  ],
  hello_web: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../apps/hello_web/assets", __DIR__)
  ]
```

Note: as the configs are merged, the generator could generate separate app-specific configs, like:
```
config :tailwind,
  hello_admin_web: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../apps/hello_admin_web/assets", __DIR__)
  ]
```

Similarly for esbuild: [...]

Then we need to change the dev endpoint config:
```
config :hello_web, HelloWeb.Endpoint,
  [...]
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:hello_web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:hello_web, ~w(--watch)]}
  ]
```

And update some build tasks in the project:
```
"assets.build": [
  "tailwind hello_web",
  "esbuild hello_web"
],
"assets.deploy": [
  "tailwind hello_web --minify",
  "esbuild hello_web --minify",
  "phx.digest"
]
```

**Comment by josevalim** [comment]
@bandesz good call. Can you please submit a PR that changes both esbuild and tailwind to generate a profile with the same name as the app name instead of using `default`?

**Comment by agonzalezro** [comment]
Hi! I gave it a go and tried to implement the solution that @bandesz proposed, however I am having a bad time trying to know the apps inside an umbrella. So far I am adding a binding with the following code:

```elixir
        children_web_apps:
          Path.wildcard(Path.join(project_path, "apps/*"))
          |> Enum.filter(&File.dir?/1)
```

But, isn't there a better way to know it?

I am also not fully sure where to do this, as far as I am understanding (I think) it should go in https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_umbrella/config/extra_config.exs so I can check on the template if it's just the umbrella default or there are more, for example:

```elixir
...
config :esbuild,
  version: "0.17.11",<%= if length(@children_web_apps) > 0 do %><%= for child_web_app_name <- @children_web_apps do %>
  "<%= child_web_app_name %>": [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../apps/<%= child_web_app_name %>/assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]<% end %><% else %>
  default: [
    args:
      ~w(js/app.js --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../apps/<%= @web_app_name %>/assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]<% end %><% end %><%= if @css do %>
...
```

But I am also not sure about this one and I need to understand as well where to put the `@children_web_apps` binding.

After investigating this and explaining it above I am thinking that maybe repiting the `config` per each app but instead using `default` using its name, could be cleaner. What I am not sure here is what to do with the watchers, could I use the `wildcard` in the `.exs` generated directly?

Any hint to keep investigating would be helpful.

Thanks!

**Comment by agonzalezro** [comment]
@josevalim, I was wondering if you could give your input here please 🙏🏽

**Comment by josevalim** [comment]
I don't think you need to know what are the apps? When the app is generated, you build a config explicitly for the app using a different name rather than the default and it all should be good! The only issue is that they all attempt to use the default config. :)
