### ISSUE TITLE
Dangling watcher process (`shadow-cljs`)

### ISSUE THREAD

**Issue by c4lliope** [phoenixframework/phoenix#5643]
### Environment

* Elixir version (elixir -v): Erlang 26 / Elixir 1.15.7
* Phoenix version (mix deps): 1.7.9
* Operating system: 

```
calliope@chesapeake:~/base/code/press/ > nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.62, NixOS, 23.11 (Tapir), 23.11pre546442.911ad1e67f45`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"home-manager, nixos, nixos-hardware"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### Actual behavior

Using as a guide https://github.com/dilzeem/hoplon-shadow-cljs -
I am beginning to run the ClojureScript Hoplon package inside my app,
compiled using `shadow-cljs`. Hoplon is running properly and is a nice experience.

`shadow-cljs` has some simple configs and is also seemingly running as planned,
and as the guide recommended I made a Phoenix watcher to manage the process.

Upon closing my Phoenix process (either using `^C^C` or `^C a<cr>`)
I see that the `shadow-cljs` process remains running in the background.
This blocks that watcher from running (port in use) when I launch Phoenix again.
The console is flooded in error messages because the watcher keeps relaunching.

I looked up how `Phoenix.Endpoint.Watcher` is managed,
and had been curious if the problem came from a missing `:shutdown` option in `child_spec/1`.
I cloned the module into my codebase, and none of my changes make a difference.
https://base.bingo/code/press/src/branch/cljs/lib/phoenix/endpoint/watcher.ex#L7-L8

I did consider that this could be an error with NodeJS workers also,
so to give Node many options for cleanup I composed three options for the watcher's command:
https://base.bingo/code/press/src/branch/cljs/config/dev.exs#L30-L32

I am eager to check anyone's recommended solutions here;
I hope someone else can share their ClojureScript experience.

### Expected behavior

Once phoenix process ends, no remaining clojurescript process is running;
as checked using `ps aux | grep cljs`.

**Comment by c4lliope** [comment]
The changes to a basic Phoenix app to enable `shadow-cljs` and `hoplon` are these:

`assets/package.json`: https://base.bingo/code/press/src/branch/cljs/assets/package.json
`assets/shadow-cljs.edn`: https://base.bingo/code/press/src/branch/cljs/assets/shadow-cljs.edn
hoplon code: https://base.bingo/code/press/src/branch/cljs/assets/src/press/page/index.cljs
Include code on page: https://base.bingo/code/press/src/branch/cljs/lib/assembled_web/components/layouts/root.sface#L12

**Comment by josevalim** [comment]
You need to open up an issue on `hoplon` and ask it to listen to stdin and terminate if stdin closes. That's how CLI tools behave. Historically we sent such requests to `esbuild`, `webpack`, and so on. :) If that's not an option, then you will need a wrapper script around it. There is a discussion here: https://hexdocs.pm/elixir/Port.html#module-zombie-operating-system-processes
