### ISSUE TITLE
Strings in generated apps are not fully covered by gettext

### ISSUE THREAD

**Issue by rhcarvalho** [phoenixframework/phoenix#5649]
### Environment

* Elixir version (elixir -v): `any`
* Phoenix version (mix deps): `1.7.10`
* Operating system: `any`

### Actual behavior

1. Create a new app and extract strings for translation:

   ```shell
   mix phx.new  hello
   mix gettext.extract
   ```

2. App comes with `gettext` support, but many strings are not marked for translation. For example, out-of-the-box flash messages are only in English (`"We can't find the internet"`, `"Something went wrong!"`, ...)

### Expected behavior

Given the existing effort to ship `gettext` integration with new apps, it would be useful if all strings would come wrapped for translation, both to serve as an example and to reduce the toll on developers. While many of the strings in the generated code will be eventually replaced with something else, some likely stick around for the lifetime of the project.

I am extracting those strings for a new app, so I might as well send a PR for this if that would be welcome.

**Comment by josevalim** [comment]
@rhcarvalho 100%. A PR is welcome for the installer generator (we don't do gettext for `phx.gen.*` for simplicity, but phx.new should).

**Comment by josevalim** [comment]
We will accept PRs only for phx.new :) thanks!
