### ISSUE TITLE
`ArgumentError` for local redirect path segments starting with `%` too broad?

### ISSUE THREAD

**Issue by hlindset** [phoenixframework/phoenix#5663]
### Environment

* Elixir version (elixir -v): 1.15.4
* Phoenix version (mix deps): 1.7.9
* Operating system: macos

### Actual behavior

`redirect(conn, to: "/æøå)"` causes an `ArgumentError`

### Expected behavior

This behaviour was introduced as a resolution for #5415. However, the solution denies _all_ paths starting with %-encoded characters. A broad denial of `/%`-segments caused a lot of redirect issues for us, because we have the Norwegian characters `æøå` in our URL scheme.

I see that `/\t` is also explicitly disallowed. Does this open redirect issue only exist specifically for the tab character (`%09` - which is the character used in the initial bug report) in chromium? Can this rule be narrowed a bit?

**Comment by josevalim** [comment]
Fixed in main.
