### ISSUE TITLE
Running MIX_ENV=docs mix docs results in compilation errors

### ISSUE THREAD

**Issue by jvdvleuten** [phoenixframework/phoenix#5674]
### Environment

* Elixir version (elixir -v): 1.15.7
* Phoenix version (mix deps): 1.17.10 (master branch)
* Operating system: MacOS

### Actual behavior

When running `MIX_ENV=docs mix docs` the following errors are thrown (alternating):

```
== Compilation error in file installer/lib/phx_new/mailer.ex ==
** (File.Error) could not read file "/private/var/folders/7n/1h6w2_7d5jq7s2yz97mjqylc0000gn/T/mix-local-installer-fetcher-mOA-Ug/deps/phx_new/templates/phx_mailer/lib/app_name/mailer.ex": no such file or directory
```

```
== Compilation error in file installer/lib/phx_new/mailer.ex ==
** (File.Error) could not read file "/private/var/folders/7n/1h6w2_7d5jq7s2yz97mjqylc0000gn/T/mix-local-installer-fetcher-mOA-Ug/deps/phx_new/templates/phx_mailer/lib/app_name/mailer.ex": no such file or directory
```

### Expected behavior

I expected to generate the docs correctly.

What I did was change this line 

[`{:phx_new, path: "./installer", only: :test},`](https://github.com/phoenixframework/phoenix/blob/302017224ef176a1b8c4b8dc19b5280b9031d3eb/mix.exs#L102)

Into:

[`{:phx_new, path: "./installer", only: [:docs, :test]},`](https://github.com/jvdvleuten/phoenix/blob/acf695fdf13b77c4f63262533ddb2b31c2cc26c4/mix.exs#L102)

This fixed my issue. 

I don't know if this correct though, as I am not familiar with the build process for the docs and how they get released normally.

I can create a pull-request for this change if needed.

**Comment by josevalim** [comment]
Yes, please do send a PR and ping me!

**Comment by jvdvleuten** [comment]
@josevalim Thanks, I added the pull request. 

Out of curiosity, how are the releases normally handled? I couldn't find the error I am having on the CI page (https://github.com/phoenixframework/phoenix/actions/workflows/ci.yml), am I missing something?

**Comment by josevalim** [comment]
We run `mix hex.publish` on our machines. I have seen this issue before as well but I could also fix it by removing the local `phx_new`. Your fix is better :D
