### ISSUE TITLE
Deleting  umbrella :context_app config -> all generator files end up in *_web

### ISSUE THREAD

**Issue by bradhanks** [phoenixframework/phoenix#5677]
Per Jose's request: https://github.com/phoenixframework/phoenix/pull/5334#discussion_r1130606306

### Environment
MacOS; Elixir 1.15.7 (compiled with Erlang/OTP 26); {:phoenix, "~> 1.7.7"},

### Setup

$ mix phx.new delete_later --umbrella

`delete_umbrella/config/config.exs`:
config :delete_web,
  ecto_repos: [Delete.Repo],
  generators: [context_app: :delete]

#### :context_app config variable present

$ mix phx.gen.html XAccounts XUser xusers name:string age:integer

file locations -> 
delete_umbrella/apps/**delete**/lib/**delete**/x_accounts.ex
delete_umbrella/apps/**delete_web**/lib/**delete_web**/controllers/x_user_html.ex

Logged output displays context file paths are absolute

#### :context_app config variable deleted

$ mix phx.gen.html Accounts User users name:string age:integer

file locations -> 
delete_umbrella/apps/**delete_web**/lib/**delete_web**/accounts.ex
delete_umbrella/apps/**delete_web**/lib/**delete_web_web**/controllers/user_html.ex

All logged file paths are relative

### Expected behavior

accounts.ex should be created in the folder where x_accounts.ex was created.
user_html.ex should be created  in the folder where  as x_html.ex

**Comment by josevalim** [comment]
Ah, thank you! I missed that the configuration was deleted. In such cases, it makes sense, the app name is then `foo_web` and Phoenix will append the `_web` to the regular app name.
