### ISSUE TITLE
Use mix format?

### ISSUE THREAD

**Issue by PragTob** [phoenixframework/phoenix#5685]
(this is neither a bug report nor a feature request so I was unsure where to put it and decided for here, if that's wrong please point me to where to best post it, thanks!)

I noticed the code base doesn't use `mix format` - as in, it's not configured for use in `.formatter.exs`, & code formatting isn't checked in CI. As one of the premiere elixir projects I think it'd be good for phoenix to use the formatter. That said, I'm of course blissfully unaware of any discussion that happened around this before and so am missing a lot of context - links would be appreciated :)

Running the formatter on lib and test (as is) results in: `65 files changed, 2558 insertions(+), 1641 deletions(-)` and it'd probably be pretty disruptive to the open PRs.

Thanks for all your work!

**Comment by chrismccord** [comment]
We format as we go. Thanks!
