### ISSUE TITLE
Response cookies must be set using cowboy_req

### ISSUE THREAD

**Issue by robkane1** [phoenixframework/phoenix#5705]
### Environment

* Elixir version (elixir -v): 1.16
* Phoenix version (mix deps): 1.7.10
* Operating system: Ubuntu (WSL)

### Actual behavior
Server fails to run on a new project

### Expected behavior
Server runs.

I have created an issue with plug cowboy as that seem to be the root of the issue, so referencing it here as will affect all new phoenix project creations from what I can see:
https://github.com/elixir-plug/plug_cowboy/issues/95

**Comment by chrismccord** [comment]
We are tracking this and will have a new release of Phoenix shortly that pins cowboy to the previous version. In the meantime, folks can follow José's instructions:

https://github.com/elixir-plug/plug_cowboy/issues/95#issuecomment-1915108354

>  I have released Plug Cowboy v2.7 and there will be a new Phoenix release soon. You can either force {:plug_cowboy, "~> 2.7"} or add {:cowboy, "~> 2.10.0"}.

**Comment by robkane1** [comment]
Confirmed as working by upgrading plug_cowboy to the new version - thanks all. :) 

![image](https://github.com/phoenixframework/phoenix/assets/16565371/98f3a716-0692-45f4-9056-aacb92886de8)
