### ISSUE TITLE
Wrong endpoint module used when having more than one project namespace

### ISSUE THREAD

**Issue by ephe-meral** [phoenixframework/phoenix#571]
On 0.7.2, I have a project with name Some.Project, generated and slightly modified from the 0.7.2 template project. The endpoint module thus resides in lib/some/project/endpoint.ex at Some.Project.Endpoint.

I also chose to name the app :some_project in the mixfile:

```Elixir
defmodule Some.Project.Mixfile do
  use Mix.Project

  def project do
    [app: :some_project,
     version: "0.0.1",
     elixir: "~> 1.0",
#...
```

When executing `mix phoenix.start` i get a `undefined function: :"SomeProject.Endpoint".start/0` error. 

As a workaround, i renamed the app in the mixfile to `:'some.Project'` which now forces phoenix to resolve the correct module.

Is this the expected behaviour?

**Comment by josevalim** [comment]
Btw, if you migrate to master, this issue will be gone altogether, the only wrong usage will be in `mix phoenix.routes` which you can fix by passing the router name explicitly!

**Comment by ephe-meral** [comment]
@josevalim for the same reason as described, a similar issue occurs in https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/template.ex#L240 - it does not resolve the right templates path since it assumes through my `Some.Project.BarView` that they are located in `web/templates/project/bar` when they actually are in `web/templates/bar`

**Comment by chrismccord** [comment]
> Is this the expected behaviour?

This is expected behavior today. We could do like José said and have a :phoenix_namespace config, but you could also just manually set your root template with in your `Some.Project.View` file.

**Comment by josevalim** [comment]
@chrismccord I think we should not rely on `phoenix_namespace` for views but simply inflect based on the current module. I will push a fix for it soon.

**Comment by ephe-meral** [comment]
Similar issue when looking up the view from the controller side due to this macro: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/controller.ex#L627
