### ISSUE TITLE
Bandit HTTP1.Handler error log for not handling :now_available when falling back to longpoll

### ISSUE THREAD

**Issue by wkirschbaum** [phoenixframework/phoenix#5712]
### Environment

* Elixir version (elixir -v): 1.16.1
* Phoenix version (mix deps): 1.17.11
* Operating system: Linux

### Actual behavior

When starting up a phoenix server with `mix phx.server` the following error appears in the logs when visiting a page falling back to longpoll
"[error] Bandit.HTTP1.Handler #PID<0.979.0> received unexpected message in handle_info/2: {:now_available, #Reference<0.415999454.1301544964.13739>}". 

### Expected behavior
Even though it does not appear to have any negative impact on the server, it is still a flagged error which seems to be unnecessary. 

### To Reproduce

- mix phx.new foo ( with the latest template for 1.17.11 )
- mix phx.gen.live .....
- update app.js and set longPollFallbackMs to a small number ( 5 works for me )
- load a live page and watch the logs.

**Comment by balexand** [comment]
This can also be reproduced by enabling only long polling for the live socket in the endpoint:

```elixir
defmodule MyAppWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :my_app

  # ...
  
  socket "/live", Phoenix.LiveView.Socket,
    # websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
```

The message gets logged whenever navigating between different live views.

**Comment by PJUllrich** [comment]
Just an FYI that I raised this issue in the `bandit` repo as well: https://github.com/mtrudel/bandit/issues/299

**Comment by wkirschbaum** [comment]
Issue seems to be fixed by https://github.com/mtrudel/bandit/issues/299
