### ISSUE TITLE
Deprecation warning on startup

### ISSUE THREAD

**Issue by the-destro** [phoenixframework/phoenix#5734]
### Environment

* Phoenix version (mix deps): 1.7.11

### Actual behavior
A deprecation warning is being logged on startup. I don't see a reference to this deprecation in the changelog

`warning: MyAppWeb.Endpoint.init/2 is deprecated, use config/runtime.exs instead or pass additional options when starting the endpoint in your supervision tree
  (phoenix 1.7.11) lib/phoenix/endpoint/supervisor.ex:36: Phoenix.Endpoint.Supervisor.init/1
  (stdlib 5.1.1) supervisor.erl:330: :supervisor.init/1
  (stdlib 5.1.1) gen_server.erl:962: :gen_server.init_it/2
  (stdlib 5.1.1) gen_server.erl:917: :gen_server.init_it/6
  (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3`

Also the documentation still mentions this approach:
https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#module-dynamic-configuration
### Expected behavior
Notice in the changelog and updated documentation would be good.

**Comment by woojiahao** [comment]
Hey, I would not mind taking this on if no one else has started working on this yet, would love to get dabble with contributing to Phoenix!
