### ISSUE TITLE
phx.gen.cert cannot generate a certificate on 2024-02-29 with a valid end date

### ISSUE THREAD

**Issue by quitejonny** [phoenixframework/phoenix#5737]
### Environment

* Elixir version: 1.15.7
* Phoenix version (mix deps): 1.7.10
* Operating system: Ubuntu 22.04

### Actual behavior

The task phx.gen.cert could not generate a certificate on 2024-02-29 with a valid end date.
It would try to use 2025-02-29 as the end date.
Today (2024-02-29) the phoenix tests (test/mix/tasks/phx.gen.cert_test.exs) are failing.

### Expected behavior

You can generate a certificate with valid end date on 2028-02-29.

I provided a fix #5736

**Comment by quitejonny** [comment]
#5736

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥
