### ISSUE TITLE
Incorrect parameter name for category IDs in "Contexts" guide section

### ISSUE THREAD

**Issue by lazycoder9** [phoenixframework/phoenix#5749]
### Environment

* Elixir version (elixir -v): `1.16.1 Erlang/OTP 26`
* Phoenix version (mix deps): `~> 1.7.11`
* Operating system: `macOS Sonoma 14.0`

### Description of problem
In the Phoenix Framework guide, specifically in the [Contexts section](https://hexdocs.pm/phoenix/contexts.html) there seems to be a discrepancy in the parameter name used for category IDs when updating a product and adding categories. The guide suggests to fetch categories by IDs provided through the `category_ids` parameter.

```elixir
  def change_product(%Product{} = product, attrs \\ %{}) do
    categories = list_categories_by_id(attrs["category_ids"])

    product
    |> Repo.preload(:categories)
    |> Product.changeset(attrs)
    |> Ecto.Changeset.put_assoc(:categories, categories)
  end

```

 However, when following the guide, updates to a product along with the addition of categories do not succeed. It appears that the parameter expected is actually `category_id`, not `category_ids` as documented. This discrepancy leads to confusion and unsuccessful updates when attempting to follow the guide as is.

There are params that I got (copied from app log locally)

```
Parameters: %{
  "_csrf_token" => "...",
  "_method" => "put",
  "id" => "2",
  "product" => %{
    "category_id" => ["1", "2", "3"],
    "description" => "Desc of product 2",
    "price" => "150.000000",
    "title" => "Product 2",
    "views" => "1"
  }
}
```
<img width="935" alt="image" src="https://github.com/phoenixframework/phoenix/assets/19951609/6c8fee51-c66f-4324-b8cd-25a74d5fe936">

### Proposal

I can update docs and replace all `category_ids` with `category_id`, but I'm not sure if it is a local issue only on my end or if there are some changes on the latest Phoenix Framework version. I also might do something wrong on one of the guide steps which led to the difference in param name

**Comment by josevalim** [comment]
In the guide, we ask you to add this input:

```
+ <.input field={f[:category_ids]} type="select" multiple={true} options={category_opts(@changeset)} />
```

Which one do you have currently?

**Comment by lazycoder9** [comment]
@josevalim Yes, you're right, the mistake was on my end. Sorry for pushing it straight to issue without deeper investigation 😅

**Comment by pangdaxing23** [comment]
I think something should be added in the docs to explain how the form access works. I was very confused wondering where `category_ids` came from, especially after reading the generated documentation for the `input` core component:
```
  attr :field, Phoenix.HTML.FormField,
    doc: "a form field struct retrieved from the form, for example: @form[:email]"
```
Retrieved from the form? Was this some kind of magic where `category_ids` is automatically populated from the `categories` in the changeset? It wasn't until I tried changing it via replace-all to something random like `bugaboo` that I was eventually led to the `Phoenix.HTML.Form` documentation, where it explains that:
```
It is possible to "access" fields which do not exist in the source data structure. 
A Phoenix.HTML.FormField struct will be dynamically created with some attributes such as name and id populated.
```
