### ISSUE TITLE
Decide if Channel should mimic more the GenServer API

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#575]
I propose to have `handle_in` and `handle_out` instead of `incoming` and `outgoing`. Also, the arguments should be ordered as in GenServer (message first, state last). The reason for this is that a lot of developers will learn Elixir through Phoenix. Having a GenServer like API will make it easier for those developers to learn GenServer later on and get used with the idea of behaviours.

**Comment by chrismccord** [comment]
We also need to rename `leave` to `terminate`, but we need to keep some kind of `leave` API around to unsubscribe from a channel. The existing approach conflated these two scenarios, so this will help fix that.

**Comment by josevalim** [comment]
Awesome!

We have agreed to not rename leave to terminate as the underlying process continues running. But we are discussing about returning `{:ok, socket}` | `:leave` of the callbacks in deprecation of the leave function.

**Comment by josevalim** [comment]
Hibernate could also be moved to the return type. Basically speaking, we should remove the side-effect based APIs:

https://github.com/phoenixframework/phoenix/blob/05932fb362fc49289030236f9beb43084cfcbf64/lib/phoenix/channel.ex#L221-L229

**Comment by chrismccord** [comment]
Closed in 2064de8e2d2afb482c1635386789893214cd68a3 . `terminate` and `hibernate` have been removed entirely as we don't need them today. I also killed `Channel.subscribe/unsubscribe` in favor of directly PubSub access.
