### ISSUE TITLE
multiple phx.digest in mix alias doesn't work

### ISSUE THREAD

**Issue by chulkilee** [phoenixframework/phoenix#5752]
### Environment

* Elixir version (elixir -v): Elixir 1.16.1 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.11
* Operating system:

### Actual behavior

I have one app (`myapp`) with two phoenix endpoints (let's say `myapp_a` and `myapp_b`) with own assets (`/assets-a` -> `/priv/static-a/assets` for example) with separate tailwind/esbuild profile.

(I'll work on minimal repo reproducing this when I have time..)

To build all assets digest, I changed the default `assets.deploy` task like this:

```elixir
"assets.deploy": [
  "tailwind myapp_a --minify",
  "esbuild myapp_a --minify",
  "phx.digest priv/static-a",
  "tailwind myapp_b --minify",
  "esbuild myapp_b --minify",
  "phx.digest priv/static-b"
]
```

but the later `phx.digest` doesn't show "Check your digested files at "priv/static-b" message - only the first `phx.digest` worked.

### Expected behavior

It should work as I run individual mix tasks - I tested following shell script and it correctly generated digest/manifest for the two.

```sh
mix tailwind myapp_a --minify \
&& mix esbuild myapp_a --minify \
&& mix phx.digest priv/static-a \
&& mix tailwind myapp_b --minify \
&& mix esbuild myapp_b --minify \
&& mix phx.digest priv/static-b
```

**Comment by chulkilee** [comment]
Okay, seems like mix does not allow running same task twice - so we need to make phx.digest to handle multiple input/output path, or call `Mix.Task.reenable("phx.digest")` to allow run multiple times independently - like tailwind task [does](https://github.com/phoenixframework/tailwind/blob/v0.2.2/lib/mix/tasks/tailwind.ex#L53).

**Comment by michallepicki** [comment]
Having the same problem with `phx.digest.clean`... (not sure if other tasks aren't afected as well?)
