### ISSUE TITLE
Stale moduledoc for `Token` regarding token secrecy

### ISSUE THREAD

**Issue by ollien** [phoenixframework/phoenix#5757]
### Environment

* Elixir version (elixir -v): N/A
* Phoenix version (mix deps): 1.7.11
* Operating system: N/A

### Actual behavior

The moduledoc for `Token` states 

> The data stored in the token is signed to prevent tampering but not encrypted. This means it is safe to store identification information (such as user IDs) but should not be used to store confidential information (such as credit card numbers).

This is definitely true of `Token.sign/4`, but `Token.encrypt/4` seems to perform actual encryption ([Phoenix Implementation](https://github.com/phoenixframework/phoenix/blob/v1.7.11/lib/phoenix/token.ex#L151), which invokes the [`Plug.Crypto` implementation](https://github.com/elixir-plug/plug_crypto/blob/v2.0.0/lib/plug/crypto/message_encryptor.ex#L36-L43)). Doing some archeology, it looks like this snippet was written a [few years before](https://github.com/phoenixframework/phoenix/commit/ffae7b974f1945e1e9ac865b93350ffe47a0579b) the [implementation of `Token.encrypt/4`](https://github.com/phoenixframework/phoenix/commit/50805c74375ba1641996ed27af81a5ae7b06e49c). 

### Expected behavior

The docs should reflect current behavior of the module. Now, perhaps someone shouldn't send credit card numbers to the frontend, but it would seem that the implementation does provide secrecy. Please do let me know if I'm off-base, though, and there's some caveat about this crypto that I'm not seeing.

**Comment by josevalim** [comment]
@ollien you are correct, can you please send a PR and ping me? I'd be glad to review it and merge it!

**Comment by ollien** [comment]
Absolutely! I need to find some time (life is getting in the way this week), but it's on my list :)
