### ISSUE TITLE
Add last_message_id support / message replays to Channels

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#576]
The long polling server currently hides the fact that, if you disconnect, you will lose messages. Also, long polling only works if you have distributed Erlang, which may not be the case for many people who will rather storage the messages elsewhere.

The general solution for this problem is to not make a long polling a special case and support some sort of recorder or replay, that is just another pub sub subscriber that can be used by any channel/transport pair.

This will likely force us to introduce the idea of last_message_id into Phoenix, which is necessary if we want more reliable message distribution in Phoenix.

**Comment by knewter** [comment]
So I've built a decent number of realtime apps with websockets at this point.  For some of those, I was essentially updating a counter (i.e. a single value was being updated over and over), and so the channel sending the "current value" to a new connection made plenty of sense.  For others, I was sending chunks of data that needed to be aggregated some other way, and so I had an actor sitting on the server that aggregated the data and sent its "last message" to any new connector - and then possibly aggregated the data on the frontend as well.  Then there were endpoints where I could not find a meaningful way to start them out with "most recent messages" in a useful way, and the UI elements on the other end really just depended on new data before they initialized.

Maybe this is useful input?  I really don't know :)

**Comment by josevalim** [comment]
Definitely! It is probably best for us to not depend on last_message_id by
default but I believe we very likely need to support it in someways and
make replayable backends easy in practice.

Last message id should also at least be handled easily in the client if one
is provided (similar to how SSE do it).


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by josevalim** [comment]
To be implemented as part of #830.

**Comment by athal7** [comment]
I know this is an old issue, but I just wanted to send along a package I put together to support replay as requested here by utilizing `mnesia`. https://hexdocs.pm/dvr. I think that some people might prefer it as compared to the database-backed example in the Phoenix documentation. Thank you in advance for any thoughts / feedback you might have!
