### ISSUE TITLE
Hexdocs.pm are missing the core_components.ex

### ISSUE THREAD

**Issue by tzugen** [phoenixframework/phoenix#5762]
I understand they will be inserted by mix tasks, and probably edited by the user at some point,
but it would be nice to have the docs of core_components.ex in a nice readable, search engine friendly way on hexdocs.

When I started using Phoenix I was struggling a bit at this, because in code examples things like `<.input>` are mentioned frequently, and I couldn't find the docs on these initially. 

Any advanced user will know where to look for the definitions of them, but for beginners would be helpful.

**Comment by chrismccord** [comment]
docs are derived from code, so it's not something we can easily embed in the project. We could define the module only in the docs env, but then the actual interface wouldn't actually exist and could be confusing for folks, so it would make the most sense as a guide, but in that case it's higher level and not really the greppable "docs" that you're asking for, so the best bet remains the docs and annotations defined in your own application. If you think we could point folks in a better direction via some guide/moduledoc wordage, please send a PR. Thanks!
