### ISSUE TITLE
Custom pubsub backends

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#577]
Today, the pubsub backend is hardcoded to distributed erlang. We should allow other backends, for example, one that stores the messages in a data store like postgres.

We should also use this opportunity to remove pubsubs outside of Phoenix supervision into and into the user application, which would be a great place to configure the backend itself.

**Comment by pspeter3** [comment]
This seems particularly helpful if you want to do something unique, like collapsing messages during long disconnects.

**Comment by chrismccord** [comment]
This is in place in master and will be included in the imminent 0.9.0 release.
