### ISSUE TITLE
Modules with dependencies using fetch_env are not recompiled in dev.

### ISSUE THREAD

**Issue by robkane1** [phoenixframework/phoenix#5772]
### Environment

Elixir: 1.16.1
Phoenix: 1.7.10
OTP: 26.2.2

Operating system: Mac (Intel)

I'm not sure if this is a bug or a misunderstanding on my part, but it just took me such a long time to figure out what the hell was going on, I figure it is worth reporting and you can dismiss as needed. It also might be more of an Elixir issue rather than a Phoenix one. 

### Context:
I have an SMS Service (and others) in my Phoenix app using a (kind of) provider pattern with implementations of the same behaviour. I do "use MyApp.Service.SMS", which is a module that contains a basic macro that simply imports the correct service based on the service provided in the config file. 

In Test It uses a mock service and in Prod, it uses a live service. 
In dev, I use an environment variable that is picked up at compile time to determine whether it should use the mock service or the real one, so I can work without flooding the real service, but still test against the real one as needed. 

I recently switched from using the mock to the real in dev to check my implementation. I killed the app, updated the env var,  sourced the .env file, restarted.

The mock service was still being used. So I went through the following:
Recompiled. 
Restarted and hit an endpoint because sometime context apps don't get rebuilt in phoenix without a http request to identify dependencies.

Still being used. 

So I ran the app in iex, checked the env var in the running app. Correct. Checked the value of the service in the config from mix: correct

This problem persisted until I went to the file where the "use MyApp.Services.SMS" was called. Changed the file and then restarted. Seems that the app was still using the cached/previous version of that file. Which is a bit confusing. If I use that service in multiple modules, I would have to go and make changes in all those modules to get the behaviour I expected. It was working fine in the other usage I have, because I was working on that module and regularly changing it. 

### Actual behavior
In development, code reloading does not identify files that should be recompiled based on their module dependencies.

### Expected behavior
Code reloading follows the usage of modules which utilise fetch_env and recompiles them, so that they are correct implementations of the module when the config changes.

Again - this is what I expect, but It is possibly that my expectations are wrong or unreasonable, or impossible. 

Thanks for reading :)

**Comment by chrismccord** [comment]
You would need to blow away your build dir and recompile with such changes as the elixir compiler cannot "see" the change to your env var. You could also use `Application.compile_env` which would pick up the change, but in general I would instead move this to a runtime lookup and avoid the import and code generation entirely. Hope that helps. Thanks!

**Comment by robkane1** [comment]
Thanks for the reply Chris. 

> the elixir compiler cannot "see" the change to your env var.

To clarify my ramblings... The Elixir compiler has picked up the change to the env var and picked up the change to the config. All is correct there. 

```elixir
Application.get_env(:my_app, :sms_service)
```
Shows the correct service. However calling a method in a module that contains ```elixir use MyApp.Services.SMS ``` still calls the other one. 

So the compiler has not picked up the _config_ change. Which it would normally do.

**Comment by robkane1** [comment]
Ah - I think I see what you are saying now. I should be using compile_env in place of fetch_env in the macro. For some reason, I had it in my head that fetch_env was compile time. Revisiting the docs shows that compile_env should be used. That would be a legit reason for ignoring the change, because fetch_env is expected to be dynamic and therefore wouldn't trigger a recompile of the module dependencies.

Thanks for the prompt - I'll give that a whirl.
