### ISSUE TITLE
Updating tailwind css to 3.4.x for phoenix 1.7.x (default)

### ISSUE THREAD

**Issue by ariandanim** [phoenixframework/phoenix#5774]
### Environment

* Elixir 1.16.2 (elixir -v):
* Phoenix 1.7.11 (mix deps):
* Operating system: Windows 11

### Actual behavior
in default Phoenix 1.7.11 the tailwind it's shows 0.2, but in the tailwindcss web is show the latest is in 3.4

### Expected behavior
Please update the plug tailwind css into latest 3.4.x for phoenix 1.7.11 by default in github repo.

**Comment by SteffenDE** [comment]
The version of the tailwind package on hex does not correspond to the tailwind version used.

https://github.com/phoenixframework/phoenix/commit/dec89f24169d897442fe82a819e0ba312f96c014 already changed the default version for new apps. You can always configure the used tailwind version in your config file.

Thank you!
