### ISSUE TITLE
In Phoenix JS, removing one never-joined Channel removes all never-joined Channels

### ISSUE THREAD

**Issue by gusbicalho** [phoenixframework/phoenix#5779]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.16.0 (compiled with Erlang/OTP 24)
```

* Phoenix version (mix deps): 1.7.11
* Operating system: macOS Sonoma 14.4.1

### Actual behavior

The code below:
```js
const socket = new Socket(`wss://anything`, {})
const c1 = socket.channel('c1')
console.log('c1 joinRef:', c1.joinRef())
const c2 = socket.channel('c2')
console.log('c2 joinRef:', c2.joinRef())
console.log('channels in socket (expect 2):', socket.channels.length)
c1.leave()
console.log('channels in socket (expect 1):', socket.channels.length)
```
Has this output:
```
c1 joinRef: undefined
c2 joinRef: undefined
channels in socket (expect 2): 2
channels in socket (expect 1): 0
```

The more practical consequence of this is that `c2` becomes unusable after we call `c1.leave()`. If one later connects the Socket and attempts to call `c2.join()`, the effect is:
* the Socket actually pushes the `join` message, but the server reply never gets routed back to `c2`
* The `c2.join()` push will always receive a `'timeout'` result

### Expected behavior

Calling `c1.leave()` in the example above should only remove `c1` from the Socket. Calling `c2.join()` after the code above should work correctly.

### Investigation into the root cause

I've done a bit of digging and the root cause seems to be the [implementation of the `Socket.remove` method](https://github.com/phoenixframework/phoenix/blob/28203dd16eabeebf00a127da4ad7135fedae1e71/assets/js/phoenix/socket.js#L544-L547):
```js
  remove(channel){
    this.off(channel.stateChangeRefs)
    this.channels = this.channels.filter(c => c.joinRef() !== channel.joinRef())
  }
```

As we can see in the logs above, `channel.joinRef()` returns `undefined` for any channels before they are `join`ed. Therefore, `c1.joinRef() === c2.joinRef()`, and `c2` ends up being removed alongside `c1`.

This filter code was [added back in 2016](https://github.com/phoenixframework/phoenix/pull/1615/files#diff-13462b4482f82e76f2de4f4b9e695d479f3d0735dc5b01e95fc86d27deab408fR571) by @chrismccord.

### Possible solution
Is there any reason not to do the simpler `this.channels = this.channels.filter(c => c !== channel)` in `remove()`? The PR that introduced the code does not clarify, and I don't have enough context to figure it out.

We could keep the current behaviour, but have a special case when `joinRef() === undefined`:
```js
  remove(channel){
    this.off(channel.stateChangeRefs)
    const ref = channel.joinRef()
    if (ref === undefined) {
      this.channels = this.channels.filter(c => c !== channel)
    } else {
      this.channels = this.channels.filter(c => c.joinRef() !== ref)
    }
  }
```

**Comment by chrismccord** [comment]
Thanks for the report! Instance equality check is all we need here as you mentioned. I'll cut a new release shortly.

**Comment by gusbicalho** [comment]
Thank you for the quick response and solution!
