### ISSUE TITLE
PubSub as a library

### ISSUE THREAD

**Issue by patrickdet** [phoenixframework/phoenix#578]
My use-case is that I have an application that uses Phoenix for web sockets and other applications that are not in the same node. These applications also interact with Phoenix and the web sockets which means so far I have copied all the PubSub code over to the other applications, so they can interact with Phoenix's PubSub layer.

If Phoenix's PubSub code were to be spun out into a standalone library then Phoenix as well as other applications could easily use these.

Am I the only one with this use-case?

**Comment by josevalim** [comment]
@patrickdet right now it doesn't make sense to extract PubSub into a library because it is still evolving. Maybe it is worth considering when we settle down, possibly after 1.0, but definitely not now.

**Comment by patrickdet** [comment]
sounds reasonable! i'll come back to this after 1.0 then
