### ISSUE TITLE
Ensure String keys on reply/broadcast

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#579]
We will allow reply/broadcast to accept any map, but the keys will be converted to strings to ensure consistent matching in `handle_in` and `handle_out`. Because `handle_in` payloads comes from the outside world, they must use string keys. 

Note to self: we also need to document this in the Transport module.

Example of how this will work:

```elixir
# matched as string keys (required from outside data)
def handle_in("new:msg", %{"body" => body}, socket) do
  broadcast socket, "new:msg", %{body: body, foo: "bar"}  #broadcasted as atom keys
end

# matched a string keys for consistency, regardless of `broadcast`
def handle_out("new:msg", %{"body" => body, "foo" => bar}, socket) do
  reply socket, "new:msg", %{body: body, is_editable: socket.assigns[:is_admin]}  
end
```

**Comment by josevalim** [comment]
My suggestion is to allow any dict in reply/broadcast, so it works more transparently:

    reply socket, "new:msg", body: body, is_editable: socket.assigns[:is_admin]

I think it reduces the load of one thinking "one map uses binaries and the other uses atoms" if we remove the second map altogether. :)

**Comment by chrismccord** [comment]
> My suggestion is to allow any dict in reply/broadcast, so it works more transparently:

I would love to do this (and we used to when channels first shipped), but it breaks for nested payloads:

```elixir
iex> Poison.encode!(Enum.into([foo: "bar", baz: [bang: "bing"]], %{}))
** (Poison.EncodeError) unable to encode value: {:bang, "bing"}
...
```

So we either have to recursively traverse the keyword lists and convert to maps, or just require maps. The latter was the easiest so I wen that way. Thoughts?

**Comment by josevalim** [comment]
Ah. :(

**Comment by pspeter3** [comment]
Could you have the function return a potential error code and just allow any message that Poison can encode?

**Comment by chrismccord** [comment]
> Could you have the function return a potential error code and just allow any message that Poison can encode?

The simplest solution would be just to enforce maps. It avoids a ton of edge cases and if we swapped Poison or is Poison's API later changed, it avoids those issues.

**Comment by pspeter3** [comment]
Yeah, agreed. I didn't know how coupled (or in this case not) poison and phoenix are

**Comment by chrismccord** [comment]
Outside of poison, we also need to support arbitrary serializers. So in that sense, enforcing more of a strict rule for payload to be a map makes a lot of sense.

**Comment by chrismccord** [comment]
After discussing on IRC, we are not going to convert keys. Transports must deserialize as string keys, so the `handle_in` callbacks always receive strings. Whatever the user broadcasts as a map will be broadcasted with `handle_out`.
