### ISSUE TITLE
Using `mix phx.new` with `--no-html` still configures live_view in test config

### ISSUE THREAD

**Issue by pcapel** [phoenixframework/phoenix#5790]
### Environment

* Elixir version (elixir -v): 
    Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

    Elixir 1.16.0 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps):
    {:phoenix, "~> 1.7.12"}
* Operating system:
    MacOS Sanoma 14.4.1
    

### Actual behavior

Running `mix test` fails because `config/test.exs` contains a configuration for `:phoenix_live_view` which isn't installed under the `--no-html` flag. The offending block is:

``` elixir
config :phoenix_live_view,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
```

### Expected behavior
Running `mix test` passes all pre-configured tests immediately after project generation.

**Comment by josevalim** [comment]
Good find, please do send a PR!

**Comment by pcapel** [comment]
Okidoki! #5802
