### ISSUE TITLE
Phoenix app has issues with debugging unit tests

### ISSUE THREAD

**Issue by JamesKentDemcon** [phoenixframework/phoenix#5793]
### Environment

* Elixir version (elixir -v): 1.15.4
* Phoenix version (mix deps): 1.7.7
* Operating system: macOS Sonoma 14.4.1

### Actual behavior

When attempting to debug a unit test in an existing Phoenix app using Visual Studio Code with the ElixirLS extension, I get the following error:

```
09:52:20.800 [error] Process #PID<0.3503.0> raised an exception
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.3503.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

See Ecto.Adapters.SQL.Sandbox docs for more information.
    (ecto_sql 3.10.2) Elixir.Ecto.Adapters.SQL.erl:1044: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.2) Elixir.Ecto.Adapters.SQL.erl:945: Ecto.Adapters.SQL.execute/6
```

Doing some research I found that there is an older [issue](https://github.com/phoenixframework/phoenix/pull/3856/files) which makes a comment that the following code snippet should be used in `MyApp.DataCase`:
```
  def setup_sandbox(context) do
    pid = Ecto.Adapters.SQL.Sandbox.start_owner!(MyApp.Repo, shared: not context[:async])
    on_exit(fn -> Ecto.Adapters.SQL.Sandbox.stop_owner(pid) end)
  end

  setup context do
    MyApp.DataCase.setup_sandbox(context)

    ....

    :ok
  end
```

After changing my setup method to this, I still get the same error.

### Expected behavior

If I start a new Phoenix app, which has the same code snippets as above, debugging in Visual Studio Code works as expected.

**Comment by JamesKentDemcon** [comment]
I had a bit of an epiphany last night and realised that this is probably due to some interactions with an external library called [ExMachinima](https://github.com/beam-community/ex_machina).

After doing some research I stumbled upon [this issue](https://github.com/beam-community/ex_machina/issues/144). With some testing in the new application I can confirm this issue is due to the interaction between Ecto and ExMachina.

**Comment by noozo** [comment]
did you end up solving this? i have 2 tests with the same problem, and all they do is submit a form in live view and then query the database to check if the newly created object is there (and that's where it fails)
