### ISSUE TITLE
[optional] lib/ code reloader

### ISSUE THREAD

**Issue by yrashk** [phoenixframework/phoenix#581]
It'd be great if it was possible to enable optional code reloading in lib/ — the reasoning is that if I know what I am doing, I will restart the app should I have processes running there that don't handle code_change well. In my practice, however, I tend to put a lot of "basic" modules there that have nothing to do with processes and therefore perfectly upgradeable; however, currently, this requires me to restart the server each time I change one of those files.

Thoughts?

**Comment by josevalim** [comment]
I have [pushed a commit to Elixir master and v1.0](https://github.com/elixir-lang/elixir/commit/2472bb79abd94ff3c0298a6421a5c38b06ec9e10) that allows Mix to correctly compile subdirectories.

With this, you should be able to change Phoenix to work with directories inside lib too. All you need to do is to change your mix.exs file:

https://github.com/phoenixframework/phoenix/blob/3c980e78e7b589a62937182987cb7015556ba6ce/priv/template/mix.exs#L8

And the code reloader:

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/code_reloader/server.ex#L59

In fact, we could change the code reloader to pass the directories that are reloadable as argument, which we could read from the endpoint itself. Basically, I am proposing we could change [this line](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/code_reloader.ex#L47) to something like this:

    opts[:reloader].(conn.private.phoenix_endpoint.config(:reloadable_paths))

And reloadable_paths is the new configuration that stores all reloadable paths. Feel free to explore this, a pull request would be very welcome.

**Comment by chrismccord** [comment]
Sounds good to me

**Comment by chrismccord** [comment]
This is on master now and will be shipping with 0.8.0. Thanks!
