### ISSUE TITLE
Protocols no longer consolidated after CodeReloader executes

### ISSUE THREAD

**Issue by sb8244** [phoenixframework/phoenix#5831]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.7 (compiled with Erlang/OTP 26)
```

* Phoenix version (mix deps): `1.7.10`
* Operating system: `Mac OSX`

### Actual behavior

I utilize `SomeProtocol.__protocol__(:impls)` to retrieve the implementations of a protocol in my code base. This is to provide an automatic mapping of protocols for certain features. It works great, except when the CodeReloader runs.

When the CodeReloader runs, the protocols in my app become unconsolidated and I have to restart the dev server.

To trigger the CodeReloader, I make an update to an Elixir file and then refresh my app frontend.

I know there's a mix.exs setting regarding consolidation, but it is not present in my mix.exs file.

### Expected behavior

Reloading the code should not result in protocols not being consolidated.

### Workaround

I have been struggling with a workaround for this but finally decided to figure something out for it. I ended up with the following (very hacky) solution that does seem to work.

Effectively, I'm running the same code as the CodeReloader to consolidate protocols, but I have it in `force` mode so it doesn't noop.

```elixir
defmodule Super.Util.Protocol do
  require Logger

  def impls_for(protocol_mod, opts \\ []) do
    case protocol_mod.__protocol__(:impls) do
      {:consolidated, impls} ->
        impls

      :not_consolidated ->
        if Keyword.get(opts, :raise) do
          raise "Protocols not consolidated. This can happen in dev (restart server). In production, this is not expected."
        else
          recompile_protocols(protocol_mod)
          impls_for(protocol_mod, Keyword.put(opts, :raise, true))
        end
    end
  end

  if Mix.env() == :dev do
    defp recompile_protocols(mod) do
      Logger.info("Recompiling protocols due to missing consolidation: #{mod}")
      Mix.Task.reenable("compile.protocols")
      Mix.Task.run("compile.protocols", ["--force"])
    end
  else
    defp recompile_protocols(_mod) do
      :ok
    end
  end
end
```

**Comment by josevalim** [comment]
Hi @sb8244! I cannot reproduce this issue. Here is what I did:

1. Cloned latest Phoenix
2. `cd installer`
3. `mix new demo --dev`
4. Added the following to `lib/demo.ex`:

```
defprotocol Foo do
  def omg(foo)
end
```

Now I started the server and whenever I change a file, I reload the page, triggering the code reloader. Both `Foo` and `Enumerable` are still consolidated.

Besides using latest Phoenix (main), I am also using Elixir v1.17.0.

**Comment by jpbecotte** [comment]
Hello @josevalim @sb8244 . We have the same problem. @josevalim  You actually have to implement and call `Foo.__protocol__(:impls)` somewhere. And the bug will happen if you modify the implementation file (without of course breaking the implementation.

Here's my steps to reproduce:
1. Cloned latest Phoenix
2. cd installer
3. mix new hello --dev
4. Add a file `my_protocol.ex`:

```
defprotocol MyProtocol do
  def omg(foo)
end

```
5. Add a file `protocol_impl.ex`:

```
defmodule SomeModuleImpl do
  defimpl MyProtocol, for: BitString do
    def omg(string) do
      string <> " (omg!)"
    end
  end
end

```

6. Ad a file `some_module.ex`:

```
defmodule SomeModule do
  def some_fun do
    x = MyProtocol.__protocol__(:impls)
    inspect(x)
  end
end

```

7. In `lib/hello_web/controllers/page_html/home.html.heex`, I have modified a little to call both the implementation and the introspecting function:

```
    <p class="text-[2rem] mt-4 font-semibold leading-10 tracking-tighter text-zinc-900 text-balance">
       <%= MyProtocol.omg("Peace of mind from prototype to production.") %>
       Implementations: <%= SomeModule.some_fun %>
    </p>

```

8. Run `mix phx.server`. All is OK.
<img width="529" alt="Capture d’écran, le 2024-08-09 à 12 24 34" src="https://github.com/user-attachments/assets/c3fb5c68-6c6d-4706-89cb-7b594d79359f">


10. Modify `protocol_impl.ex`, change `(omg!)` to `(omgg!)`, for example.
11. Reload the page. 

<img width="595" alt="Capture d’écran, le 2024-08-09 à 12 24 53" src="https://github.com/user-attachments/assets/b936f651-74d8-4f0c-bf99-91d6b0821eb8">

**Comment by josevalim** [comment]
Thank you, I was able to reproduce this issue and it is an Elixir bug. It is not hard to fix it, I should have something up tomorrow.

**Comment by jpbecotte** [comment]
Thank you!

**Comment by sb8244** [comment]
Hey @josevalim , I patched this fix into my deps (so running `1.7.10` with this file patched) and re-compiled. I'm still seeing the issue pop up. It's hard to tell if it happens less or not—I will keep an eye on it. It does seem like when it happens, it is fixed on the next refresh.

My fear with reproduction is that we have quite a lot of protocol usage and a decently large app, so I'm not sure how easy it will be to reproduce.

Could part of the issue be the fix that I attempted for the problem?

```elixir
defmodule Super.Util.Protocol do
  require Logger

  def impls_for(protocol_mod, opts \\ []) do
    case protocol_mod.__protocol__(:impls) do
      {:consolidated, impls} ->
        impls

      :not_consolidated ->
        if Keyword.get(opts, :raise) do
          raise "Protocols not consolidated. This can happen in dev (restart server). In production, this is not expected."
        else
          recompile_protocols(protocol_mod)
          impls_for(protocol_mod, Keyword.put(opts, :raise, true))
        end
    end
  end

  if Mix.env() == :dev do
    defp recompile_protocols(mod) do
      Logger.info("Recompiling protocols due to missing consolidation: #{mod}")
      Mix.Task.reenable("compile.protocols")
      Mix.Task.run("compile.protocols", ["--force"])
    end
  else
    defp recompile_protocols(_mod) do
      :ok
    end
  end
end
```

**Comment by josevalim** [comment]
If you have steps to reproduce the issue, I can take a look. What I can say is that the steps given above no longer show the issue.

**Comment by jpbecotte** [comment]
Hello @josevalim ! I confirm that the bug still there with elixir 1.17.3. I used the same project as described above.

**Comment by josevalim** [comment]
The bug has been fixed only in main. So you will see it on v1.18 :)
