### ISSUE TITLE
In the default Dockerfile, `mix assets.deploy` downloads tailwind & esbuild every time assets change

### ISSUE THREAD

**Issue by jyc** [phoenixframework/phoenix#5833]
Thanks for making Phoenix! I noticed that in the default Dockerfile `mix assets.deploy` downloads tailwind & esbuild every time assets change:

https://github.com/phoenixframework/phoenix/blob/69685f783bc60d2a124fc2fb48028b065bc24b22/priv/templates/phx.gen.release/Dockerfile.eex#L46-L55

Do you think the default could be changed to run

```
mix tailwind.install
mix esbuild.install
```

... after `mix deps.compile` and before `mix assets.deploy`? This should make most Docker image builds faster because they won't have to download tailwind/esbuild every time anything in priv, lib, or assets changes.

I'd be happy to open a small PR to do this if it's alright with you!

The only challenge is that it'd have to handle `--no-tailwind` and `--no-esbuild`. Happy to take a stab at handling that too with some pointers; a cursory search for `no-tailwind` didn't turn up anything: https://github.com/search?q=repo%3Aphoenixframework%2Fphoenix+no-tailwind&type=code

**Comment by SteffenDE** [comment]
@jyc I think it should be possible to add `mix assets.setup` instead of adding the tailwind and esbuild installs separately. We'd only need to check if the `assets.setup` task is actually available when generating the Dockerfile:

```dockerfile
RUN mix deps.compile
<%= if @assets_setup_available? do %>mix assets.setup<% end %>
```

and adding the binding here: https://github.com/phoenixframework/phoenix/blob/c848a8444fc929ae93e027c119b1e9876579dcdd/lib/mix/tasks/phx.gen.release.ex#L246-L250

```diff
            elixir_vsn: elixir_vsn,
+           otp_vsn: otp_vsn,
+           assets_setup_available?: Keyword.has_key?(Mix.Project.config()[:aliases], :"assets.setup")
```

If you want to give it a go and send a PR, I'll be happy to review it.

**Comment by rhcarvalho** [comment]
I do an explicit `mix assets.setup` after `mix deps.compile` in a Dockerfile, can confirm it leads to better caching.

**Comment by josevalim** [comment]
LGTM! Can you folks please submit a PR? :)

**Comment by jyc** [comment]
Sorry for the delay! Thanks @SteffenDE for the guidance—I could make a PR but I realized I'm not sure how best to test this! I don't want to make the PR only for you to have to debug it, so please don't block on me! But let me know what you want to do, I'm also happy to learn how to debug it.

**Comment by jyc** [comment]
Wow! Thanks for making the PR and for documenting the process in detail @rhcarvalho! I really appreciate it.

**Comment by rhcarvalho** [comment]
@jyc :purple_heart::purple_heart::purple_heart:

Thank you for contributing with this well reported issue and  looking forward to seeing your next contributions!
