### ISSUE TITLE
Forms generated by `phx.gen.auth` (using Phoenix.Controller) display password in plaintext inside HTML DOM

### ISSUE THREAD

**Issue by varholak-peter** [phoenixframework/phoenix#5837]
When using `phx.gen.auth` (using Phoenix.Controller only) the resulting code displays passwords as plaintext values in HTML whenever the server re-renders form with validation errors.

When using LiveView this does not happen.

### Security
Keeping password as plaintext in the value attribute is not against any security standards as far as I know. However, it's best to minimize password leaking when possible. Malicious JS would still be able to access the `value` property but at least it wouldn't be showing in HTML as plaintext.

### UX considerations
Usually when we are re-rendering forms with a list of errors after validation we pre-fill existing values so that the user doesn't have to fill it again. In the case of passwords, however, users don't see the value due to obfuscation in the input field so they have to fill it anyway. **I believe a more secure and UX friendlier approach would be to render an empty field.**

### Steps to reproduce
1. Create a new phoenix project
2. Run `mix phx.gen.auth` choosing the controller mode
3. Run appropriate migrations and start the server
4. Visit the login page and submit the form with invalid credentials
5. Inspect the Password input element, the `value` attribute will have the password in plaintext.
![image](https://github.com/phoenixframework/phoenix/assets/19926448/125dabc5-e6ce-41ed-bf6c-e4b3594840b1)

### Environment

* Elixir version (elixir -v): 1.16.3
* Phoenix version (mix deps): 1.7.12
* Operating system: N/A

### Actual behavior

:x: All `<input type="password" />` show the password in plaintext when the form is returned with validation.

### Expected behavior

✅ Password input fields are returned empty.

**Comment by 14tinchov** [comment]
I was able to replicate the issue and I agree with you, we shouldn't expose ourselves with something like this. I'll try to create a PR to handle the password input logic separately

**Comment by dimitrisnl** [comment]
![CleanShot 2024-06-12 at 14 49 13](https://github.com/phoenixframework/phoenix/assets/4951004/c4462db4-40f8-4940-bba7-9afa33776e71)

Also happens in the change-password forms

**Comment by 14tinchov** [comment]
Hi again ! It's true in terms of security, having or not having this value is almost the same, if there is someone listening or some malicious script reading each keydown and reading the DOM, this is not going to imply much change

In terms of UX, you would save just one step haha, I mean if you enter the wrong password, generally you don't know where the error is and you delete everything. I think it's a matter of preference. In any case, I'm leaving the [PR](https://github.com/phoenixframework/phoenix/pull/5838) in case you want to take a look. It's a little change, it's a specific input to handle anything related to the password input, in this case not returning the previous value

**Comment by Schultzer** [comment]
I don’t think this makes sense, and forcing the user to reenter their password, due to issues that is not in their control is a bad precedent.

It would frustrate me to no end if I experienced a website with this behaviour.

**Comment by 14tinchov** [comment]
@josevalim  Anytime !
