### ISSUE TITLE
Move the code reloader configuration to the endpoint

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#585]
Now we can mount the code reloader in the endpoint supervision tree.

**Comment by chrismccord** [comment]
Should we get this in today for 0.8.0, or wait until after?

**Comment by josevalim** [comment]
Nah, we can wait.

**Comment by josevalim** [comment]
When tackling this, we should add a reloeader or watcher feature to the endpoint. @chrismccord let me know if it has worked out well for you.

**Comment by josevalim** [comment]
This also requires us to plug the live reloader explicitly too.

**Comment by josevalim** [comment]
@chrismccord I have added `if code_reloading? do` block to endpoints. Once we make `live_reloader` a plugin, we just need to add it there too. This is done! Pew pew pew!
