### ISSUE TITLE
check_origin set in socket websocket key cannot be overridden in Endpoint application env

### ISSUE THREAD

**Issue by karlosmid** [phoenixframework/phoenix#5855]
### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.6 (compiled with Erlang/OTP 26)
```

* Phoenix version (mix deps):
```
1.7.12
```

* Operating system:
```
MacOs Ventura 13.6.7
```

### Actual behavior

When we set check origin to true in socket
```
socket "/live", Phoenix.LiveView.Socket, websocket: [check_origin: :true, connect_info: [session: @session_options]]
```
and then we try to override it to false in Endpoint configuration:
```
config :testivator, TestivatorWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  load_from_system_env: true,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: false,
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  live_view: [signing_salt: System.get_env("AUTHENTICATOR_SEED")]
```

check_origin value is still true

### Expected behavior

check_origin value should be set to false

### Related Phoenix code

Phoenix code supports this logic:
https://github.com/phoenixframework/phoenix/blob/41c631030b76624598b491b652a90f68310bfeb0/lib/phoenix/socket/transport.ex#L548

as opts is Keyword list from socket websocket: key

Is this on purpose or a bug?

Thank you!

**Comment by Gazler** [comment]
This is deliberate. Config is typically overridden based on how "close" it is to the usage.
