### ISSUE TITLE
Generated new app from latest master not working

### ISSUE THREAD

**Issue by gjaldon** [phoenixframework/phoenix#586]
Did `mix phoenix.new test ~/code/test` and the generated app returns below error when I do `mix phoenix.server`.

![error log](https://www.evernote.com/shard/s280/sh/e2cd83ca-8a1d-4f88-a5e1-c4e8332e71fb/3bb8dcad7a01d6cbbae5bc87d114375a/deep/0/Screenshot%201/11/15,%208:40%20PM.jpg)

**Comment by josevalim** [comment]
Good catch, fixed on master!

**Comment by gjaldon** [comment]
No prob, Jose! Thank you! :+1:
