### ISSUE TITLE
The phx.new project generator generates a todo in the mix.exs

### ISSUE THREAD

**Issue by HeapUnderfl0w** [phoenixframework/phoenix#5862]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 25 [erts-13.2.2.9] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

Elixir 1.16.3 (compiled with Erlang/OTP 25)
```

* Phoenix version (mix deps): `phx_new` 1.7.14
```
* phoenix 1.7.14 (Hex package) (mix)
  locked at 1.7.14 (phoenix) c7859bc5
  ok
* phoenix_ecto 4.6.2 (Hex package) (mix)
  locked at 4.6.2 (phoenix_ecto) 3f94d025
  ok
* phoenix_html 4.1.1 (Hex package) (mix)
  locked at 4.1.1 (phoenix_html) f2f2df5a
  ok
* phoenix_live_dashboard 0.8.4 (Hex package) (mix)
  locked at 0.8.4 (phoenix_live_dashboard) 2984aae9
  ok
* phoenix_live_reload 1.5.3 (Hex package) (mix)
  locked at 1.5.3 (phoenix_live_reload) b4ec9cd7
  ok
* phoenix_live_view 1.0.0-rc.6 (Hex package) (mix)
  locked at 1.0.0-rc.6 (phoenix_live_view) e56e4f16
  ok
* phoenix_pubsub 2.1.3 (Hex package) (mix)
  locked at 2.1.3 (phoenix_pubsub) bba06bc1
  ok
* phoenix_template 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (phoenix_template) 2c0c81f0
  ok
```

* Operating system:
NixOS 24.11 (`Linux gaia 6.8.12 #1-NixOS SMP PREEMPT_DYNAMIC Thu May 30 07:49:53 UTC 2024 x86_64 GNU/Linux`)

### Actual behavior

Generating a project using `mix phx.new repro` leaves a `# TODO` in the generated `mix.exs`

![image](https://github.com/phoenixframework/phoenix/assets/28512568/83220b44-649b-4297-a1dc-e24a3e08e5f3)

### Expected behavior

Id expect a released generator version to not contain any `# TODO` comments.

**Comment by rhcarvalho** [comment]
This is temporary, see https://github.com/phoenixframework/phoenix/commit/5f106b489913815233e381f26e0aa0f2d599bcb6.

Chris and team are certainly using it to expose more people and gather more feedback on the Release Candidates before the final 1.0 release of Phoenix LiveView.

The TODO is actually nice if you care about it, as it is a reminder to update the dependency soon :)

**Comment by HeapUnderfl0w** [comment]
Right. I have no hard stance either way so feel free to close this as "works as designed" :)
(Visually it looked like an oversight at first glance)
