### ISSUE TITLE
`Phoenix.ConnTest.get` navigates to root when path has only query parameters

### ISSUE THREAD

**Issue by jounimakela** [phoenixframework/phoenix#5877]
### Environment

* Elixir version (elixir -v): Elixir 1.16.1 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.14 and main

### Actual behavior

`Phoenix.ConnTest.get/2` does not consider current path (`conn.request_path`) when given path has only query parameters.

For example:

```elixir
# conn.request_path is "/page"
get(conn, "?lang=en")
```

Navigates to root path: `/?lang=en`.

[Example of the issue, GitHub Gist](https://gist.github.com/jounimakela/075e9d4ce4baea8eec892f7d1d369cc5)

### Expected behavior

If the given path has only query parameters, merge the query parameters to current path.

For example:

```elixir
# conn.request_path is "/page"
get(conn, "?lang=en")
```

Should navigate to: `/page?lang=en`.

That's how browsers behave: if you have a link `<a href="?lang=en">English</a>` and you are currently in `/page`, you are going to be navigated to `/page?lang=en`. 

Also see discussion in https://github.com/germsvel/phoenix_test/pull/80

**Comment by chrismccord** [comment]
Honestly I think this is working as expected. If you want to send a doc PR with an example of concat'ing current path yourself, please do! Thanks!
