### ISSUE TITLE
Returning {:ok} from Channel.leave/2 is not intuitive.

### ISSUE THREAD

**Issue by seejee** [phoenixframework/phoenix#588]
Thanks for your hard work, everyone. Phoenix has been fantastic to work with!

I just upgraded to 0.8.0, and I ran into a small hitch that I found to be somewhat unintuitive. Here was my experience:

* I updated the `leave` callbacks in my channels to use the new function signature.
* I changed the `leave` callbacks to return `{:leave, socket}`. 
* I got this error message:

 ```
    ** (Phoenix.Channel.Transport.InvalidReturn) Invalid Handler return: [message: "  expected {:ok, %Socket{}} | {:leave, %Socket{}} got {:leave, %Phoenix.Socket{assigns: %{chat_id: \"9698ce73-ec2d-43e7-8c86-da8afb0869af\", teacher_id: 1}, authorized: true, pid: #PID<0.249.0>, router: ElixirChat.Router, topic: \"chats:9698ce73-ec2d-43e7-8c86-da8afb0869af\", transport: Phoenix.Transports.WebSocket}}\n"]
        (phoenix) lib/phoenix/channel/transport.ex:143: Phoenix.Channel.Transport.handle_result/2
        (elixir) lib/enum.ex:543: anonymous fn/3 in Enum.each/2
        (elixir) lib/enum.ex:1266: anonymous fn/3 in Enum.reduce/3
        (elixir) lib/hash_dict.ex:197: HashDict.do_reduce_each/4
        (elixir) lib/enum.ex:1265: Enum.reduce/3
        (elixir) lib/enum.ex:542: Enum.each/2
        (phoenix) lib/phoenix/channel/transport.ex:175: Phoenix.Channel.Transport.dispatch_leave/2
        (phoenix) lib/phoenix/transports/websocket.ex:75: Phoenix.Transports.WebSocket.ws_terminate/2
```

* I struggled for a while, looked at the Phoenix source code, and eventually changed my `leave` functions to return `{:ok, socket}` instead of `{:leave, socket}`. 
* Everything worked.

So here is my issue:

1) I was surprised to have to return `{:ok}` from `leave` instead of `{:leave}`. It is confusing to use `{:leave}` from a `handle_in` but `:ok` from `leave`.
2) The error message seems to indicate either would work, but in my experience, that was not the case.

Again, thanks everyone for producing such awesome software!

**Comment by josevalim** [comment]
The thing is that we return `{:leave, ...}` from `handle_in/3` to ask for it to leave. It doesn't make sense to ask to leave from leave itself. On the other hand, I think we should just allow any value to be returned from the `leave` callback... :)

**Comment by chrismccord** [comment]
I can see how this is confusing, but it was intentional. My vote would be to have a better error messages saying that `leave/2` must return `{:ok, socket} | {:error, socket, reason}`. The issue with allowing leave to.. leave is that we'd have to special case it in the code to prevent leave'ception.
