### ISSUE TITLE
Documentation Request: Accessing a POST/PUT/PATCH request body

### ISSUE THREAD

**Issue by sriedel** [phoenixframework/phoenix#59]
I'm a bit lost here; I'd like to access the raw request body of a POST/PUT/PATCH request, and can't figure out how to do it. I had a look at the Plug library, but it seems to require one to use a Plug.Parser, which in turn restricts the request to use either a urlencoded or web form content type. 

A POST action in the examples would be nice, to see how I could use phoenix for an API service.

**Comment by chenxsan** [comment]
@scrogson There's a typo, should be:

```
{:ok, body, conn} = read_body(conn)
```
