### ISSUE TITLE
Remove socket_reply indirection

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#590]
Today, `reply/3` in the channel sends a `:socket_reply` message to the connection process that sends itself a `:reply` message. We should skip one of those steps, possibly by keeping a serializer of choice in the `socket` alongside the pid and already sending the encoded message to the process that will dispatch it.

**Comment by josevalim** [comment]
We have the perfect opportunity to clean this up when we move to separate processes per channel.

**Comment by hamiltop** [comment]
In a similar vein, I'm writing a custom websocket handler that does not fit the mold of channels. I'm able to build it fairly easily on top of `Phoenix.Transports.WebSocket`, which is awesome. However, replying to the socket requires sending a message to yourself that is caught by `websocket_info` and then sent to the client. Seems awkward and inefficient.

**Comment by chrismccord** [comment]
Phoenix.Transport.WebSocket is an internal API that's not guaranteed to work in the future as we are binding directly to cowboy in this case.

**Comment by hamiltop** [comment]
Fair enough.
