### ISSUE TITLE
Channels should expect {:error, reason, socket} and start logging them

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#591]
And instead of `{:error, :unauthenticated, socket}`, we could return `:ignore` on join to also mimic GenServer.

**Comment by chrismccord** [comment]
@josevalim Is 19da73a4fca7d49f24db4e2aabad40c862295b30 what you had in mind for logging?

**Comment by josevalim** [comment]
Yes, I added one tiny comment. Since this issues will change the join code too, I have two other things:

1. What happens if you try to join a channel you already joined?

2. Today, we remove the socket if it doesn't handle a message, but a connection that listens on more than one topic will trigger that error clause every other time. So we shouldn't log nor remove the socket in this case, we should just keep running.
