### ISSUE TITLE
Cowboy Dispatch from Endpoint

### ISSUE THREAD

**Issue by hilarycheng** [phoenixframework/phoenix#592]
I have developed the web application by Phoenix from 0.4.0. At the past, I can pass the cowboy dispatch directory from MyApp.Router. But when I upgrade to 0.8.0, the features was removed. Is it able do this features in the MyApp.Endpoint ?

Since my web application consists two parts, the first part is using Phoenix as Web Interface for Customer to access. Another part is giving websocket interface for the mobile app. Since I would like to do the session tracking at the mobile app by my apps. I wants cowboy to connect my WebSocket Handler directly without any phoenix framework.

**Comment by josevalim** [comment]
I just pushed to master a change to allow custom dispatches. So you can set the :dispatch option in your http and https config but you need to add a clause that falls back to the default Phoenix one. Here is the default value:

    http: [dispatch: {:_, [{:_, Phoenix.Endpoint.CowboyHandler, {YourApp.Endpoint, []}}]}]

Use it with care!

**Comment by hilarycheng** [comment]
Thanks a lots
