### ISSUE TITLE
Logs of requests served in <1ms are printed as seconds

### ISSUE THREAD

**Issue by feld** [phoenixframework/phoenix#5933]
Phoenix 1.7.14

```
14:38:22.689 request_id=F_SGAowY9bSH4scAACCc [info] Sent 200 in 1ms
14:38:22.980 request_id=F_SGAp1-WTi9lt0AAAoX [info] GET /health
14:38:22.980 request_id=F_SGAp1-WTi9lt0AAAoX [info] Sent 200 in 799s
```

That request did not take 799 seconds 😅

**Comment by chrismccord** [comment]
It should be printing `µs`. What is your os? https://github.com/phoenixframework/phoenix/blob/48ee8cc407f060eee1152f2c8f64bff49a6b4f15/lib/phoenix/logger.ex#L153

**Comment by josevalim** [comment]
I believe this is a terminal/font issue. Please make sure they can display the `µ` character. :)
