### ISSUE TITLE
Warning about Deprecated Gettext Backend Definition in New Phoenix App

### ISSUE THREAD

**Issue by itzmidinesh** [phoenixframework/phoenix#5936]
### Environment

* Elixir version (elixir -v): 1.17.2
* Phoenix version (mix deps): 1.7.14
* Operating system: Windows 11

### Actual behavior

I recently created a new Phoenix app using `mix phx.new my_app` and encountered the following warning when running it:

```
warning: defining a Gettext backend by calling

    use Gettext, otp_app: ...

is deprecated. To define a backend, call:

    use Gettext.Backend, otp_app: :my_app

Then, instead of importing your backend, call this in your module:

    use Gettext, backend: MyApp.Gettext
```
![image](https://github.com/user-attachments/assets/93e995c3-2637-45fa-a8f5-2146255be9c4)

### Expected behavior

This warning appears in `lib/my_app_web/gettext.ex:23`, indicating that the way of defining the Gettext backend is outdated.

It would be helpful for the generated code to be updated to reflect the new approach to defining Gettext backends. This could prevent confusion for new users encountering this deprecation warning.

**Thank you for your attention!**

**Comment by SteffenDE** [comment]
Hi!

This was already fixed in https://github.com/phoenixframework/phoenix/pull/5902, it’s just not released yet.

**Comment by itzmidinesh** [comment]
Thank you! I looked for related issues but overlooked this one. I appreciate your time on this and I apologize for the oversight.

**Comment by SteffenDE** [comment]
Phoenix 1.7.18 is out now with the updated gettext syntax in the generators!
