### ISSUE TITLE
Reset password duplicates fields on autofill.

### ISSUE THREAD

**Issue by cgarvis** [phoenixframework/phoenix#5947]
### Environment

* Elixir version (elixir -v): 1.17.3
* Phoenix version (mix deps): 1.7.14
* Operating system: MacOS

### Actual behavior

I used `phx.gen.auth` to create auth pages.  I have not touched them.  When I try to reset the password, the browser's autofill causes the form to get out of sync and renders extra fields.

<img width="538" alt="Screenshot 2024-10-08 at 2 57 27 PM" src="https://github.com/user-attachments/assets/61d89a9d-dd26-43ee-a59c-b1e684bc2afc">

### Expected behavior

Auto fill new passwords without getting the form out of sync.

**Comment by cgarvis** [comment]
Seems if I remove ` <.flash_group flash={@flash} />` from the layout, it works fine.

**Comment by chrismccord** [comment]
This was already fixed on LV main, and we'll have a new rc out soon. Thanks! https://github.com/phoenixframework/phoenix_live_view/issues/3471
