### ISSUE TITLE
Missing phx.digest error handling

### ISSUE THREAD

**Issue by KayEss** [phoenixframework/phoenix#5949]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): 1.7.12
* Operating system: Linux (Ubuntu 24.04.1 LTS)

### Actual behavior

Running `mix phx.digest` gives a useless internal error:
```
$ mix phx.digest
** (ArgumentError) errors were found at the given arguments:

* 1st argument: not a bitstring

:erlang.bit_size(nil)
(stdlib 4.3.1.3) eval_bits.erl:114: :eval_bits.eval_exp_field1/9
(stdlib 4.3.1.3) eval_bits.erl:77: :eval_bits.create_binary/2
(stdlib 4.3.1.3) eval_bits.erl:68: :eval_bits.expr_grp/5
(stdlib 4.3.1.3) erl_eval.erl:543: :erl_eval.expr/6
(stdlib 4.3.1.3) erl_eval.erl:856: :erl_eval.eval_map_fields/6
(stdlib 4.3.1.3) erl_eval.erl:313: :erl_eval.expr/6
```

### Expected behavior

The error report tells us what we need to fix so we can build the project

**Comment by josevalim** [comment]
I believe this was an Erlang bug. Please update your Erlang/Elixir installation and you should be good to go.

**Comment by josevalim** [comment]
Closing this for now :) Let us know if it persists.
