### ISSUE TITLE
Code Reloader Issue

### ISSUE THREAD

**Issue by hayesgm** [phoenixframework/phoenix#597]
Just getting started with Phoenix, but I'm really excited about the project.

I'm having an issue when reloading code after a syntax error:

```
== Compilation error on file web/router.ex ==
** (CompileError) web/router.ex:1: cannot define module Exchat.Router because it is currently being defined in web/router.ex:1
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
```

I am using Erlang 17.3.4, Elixir 1.0.2 and Phoenix v0.8.  This occurs after I put and then fix a syntax error in a Controller or in `router.ex`.  Restarting Phoenix by double Ctrl+C fixes the problem.

Thanks for your help-- let me know if you need more information.

**Comment by josevalim** [comment]
This is an Elixir issue. We should release 1.0.3 soon. Thanks for reporting!

**Comment by hayesgm** [comment]
Thanks for being prompt on addressing this.
