### ISSUE TITLE
Module loading error during mix phx.gen.auth

### ISSUE THREAD

**Issue by evnp** [phoenixframework/phoenix#5973]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.17.2 (compiled with Erlang/OTP 26)
```
* Phoenix version (mix deps):
```
$ mix deps | grep phoenix
* phoenix 1.7.14 (Hex package) (mix)
  locked at 1.7.14 (phoenix) c7859bc5
* phoenix_ecto 4.6.2 (Hex package) (mix)
  locked at 4.6.2 (phoenix_ecto) 3f94d025
* phoenix_html 4.1.1 (Hex package) (mix)
  locked at 4.1.1 (phoenix_html) f2f2df5a
* phoenix_live_dashboard 0.8.4 (Hex package) (mix)
  locked at 0.8.4 (phoenix_live_dashboard) 2984aae9
* phoenix_live_reload 1.5.3 (Hex package) (mix)
  locked at 1.5.3 (phoenix_live_reload) b4ec9cd7
* phoenix_live_view 1.0.0-rc.6 (Hex package) (mix)
  locked at 1.0.0-rc.6 (phoenix_live_view) e56e4f16
* phoenix_pubsub 2.1.3 (Hex package) (mix)
  locked at 2.1.3 (phoenix_pubsub) bba06bc1
* phoenix_template 1.0.4 (Hex package) (mix)
  locked at 1.0.4 (phoenix_template) 2c0c81f0
```
* Operating system:
```sh
$ sw_vers
ProductName:	macOS
ProductVersion:	12.3
BuildVersion:	21E230
```

### Actual behavior

My application name is `CC` (a shorthand name). However, when running `mix phx.gen.auth` I encounter an error:
```sh
$ mix phx.gen.auth Accounts User users
An authentication system can be created in two different ways:
- Using Phoenix.LiveView (default)
- Using Phoenix.Controller only
Do you want to create a LiveView based authentication system? [Yn]
Compiling 19 files (.ex)
Generated cc app
** (Mix) Unable to find Cc.Repo

21:02:15.856 [error] beam/beam_load.c(180): Error loading module 'Elixir.Cc.Repo':
  module name in object code is 'Elixir.CC.Repo'
```

Is specific capitalization critical here? I'd expect any PascalCase string would be valid as the app module name (`CC` being a PascalCase string of two one-letter terms).

### Expected behavior

```sh
$ mix phx.gen.auth Accounts User users
An authentication system can be created in two different ways:
- Using Phoenix.LiveView (default)
- Using Phoenix.Controller only
Do you want to create a LiveView based authentication system? [Yn]
Compiling 19 files (.ex)
Generated cc app
* creating priv/repo/migrations/20241110210027_create_users_auth_tables.exs
* creating lib/cc/accounts/user_notifier.ex
...
* injecting lib/cc_web/router.ex - plug
* injecting lib/cc_web/components/layouts/root.html.heex

Please re-fetch your dependencies with the following command:

    $ mix deps.get

Remember to update your repository by running migrations:

    $ mix ecto.migrate

Once you are ready, visit "/users/register"
to create your account and then access "/dev/mailbox" to
see the account confirmation email.
```

**Comment by 03juan** [comment]
> Is specific capitalization critical here? I'd expect any PascalCase string would be valid as the app module name (CC being a PascalCase string of two one-letter terms).

In short, yes it's critical, but there are some idiosyncrasies of the Elixir `Macro` functions, used by the `phx.gen.*` code to create modules, that can lead to confusion as hinted at in the 
[`Macro.camelize/1`](https://hexdocs.pm/elixir/Macro.html#camelize/1) and [`Macro.underscore/1`](https://hexdocs.pm/elixir/Macro.html#underscore/1) docs:

> This function was designed to camelize language identifiers/tokens, that's why it belongs to the `Macro` module. Do not use it as a general mechanism for camelizing strings

> In general, underscore can be thought of as the reverse of camelize, however, in some cases formatting may be lost:
> 
> ```elixir
> Macro.underscore("SAPExample")
> "sap_example"
> 
> Macro.camelize("sap_example")
> "SapExample"
> ```

In your example:

```elixir
iex(16)> Macro.camelize("c_c") |> Macro.underscore() |> Macro.camelize() |> Macro.underscore() |> dbg()
[iex:16: (file)]
Macro.camelize("c_c") #=> "CC"
|> Macro.underscore() #=> "cc"
|> Macro.camelize() #=> "Cc"
|> Macro.underscore() #=> "cc"

"cc"
iex(17)> Macro.camelize("cc") |> Macro.underscore() |> Macro.camelize() |> Macro.underscore() |> dbg()
[iex:17: (file)]
Macro.camelize("cc") #=> "Cc"
|> Macro.underscore() #=> "cc"
|> Macro.camelize() #=> "Cc"
|> Macro.underscore() #=> "cc"

```

So if your application is named `:cc`, this function will try to load the repo module `Cc.Repo`, as seen in your error

https://github.com/phoenixframework/phoenix/blob/dad45278246207b26aa0c42c02398106c10e2b19/lib/mix/tasks/phx.gen.auth.ex#L770-L776

> Generated cc app
> ** (Mix) Unable to find Cc.Repo
> 
> 21:02:15.856 [error] beam/beam_load.c(180): Error loading module 'Elixir.Cc.Repo':
  module name in object code is 'Elixir.CC.Repo'

**Comment by evnp** [comment]
Hi Juan, appreciate the detailed response. That makes sense – I see now that changing project config to either `app: :CC` or `app: :c_c`, both allow the command to proceed as expected (though `:c_c` requires some file name changes, which is to be expected).

I had worked around the issue by doing a temporary search/replace of `CC` -> `Cc` across all files, then reverting that back after auth gen, which seems to have worked fine. But it sounds like I should probably app-wide rename to `Cc` to avoid other issues that stem from going against the grain here.

Will close this as it's working as expected. Thanks again for your help clarifying.
