### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by Slesa** [phoenixframework/phoenix#5982]
Did you ever try to write your first Phoenix app without any knowledge? And this is a bug imho.

**Comment by glhrmv** [comment]
This is not a bug. Guides are [here](https://hexdocs.pm/phoenix/overview.html).

**Comment by SteffenDE** [comment]
What @glhrmv says. Phoenix has a very thorough documentation that is also linked from the README of the repo.

@Slesa if you feel like we are lacking something, please try to be more concrete. Improvements to the docs are always welcome :)
