### ISSUE TITLE
params should not require URI.decode

### ISSUE THREAD

**Issue by jschoch** [phoenixframework/phoenix#599]
```elixir 
# shouldn't have to do this

def foo(conn,params) do
    has_space = params["param_with_space"] |> URI.decode
end
```

**Comment by josevalim** [comment]
I can't reproduce this issue. The data is properly decoded. Can you please give more information on your Phoenix version, how the request body looks like and so on?

**Comment by josevalim** [comment]
Ping, please let us know if you have more information! Thank you.

**Comment by sb8244** [comment]
Hi @josevalim, I think that @jschoch was referring to query string parameters including their URL encoding and forcing a developer to decode in order to use them. For instance:

```
  "myParam" => "a%3D%3D%24b",
```

Can be passed to Phoenix which will return it is `a%3D%3D%24b` rather than `a==$b`
