### ISSUE TITLE
resolved %USERPROFILE% is not being used in the install script

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [phoenixframework/phoenix#5999]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps):
* Operating system: Windows 10

### Actual behavior

The following lines from `https://new.phoenixframework.org/myapp.bat`, seem to set the `%USERPROFILE%` correctly

`@echo %USERPROFILE% `correctly gives `C:\Users\charl` on my machine

```
set "elixir_version=1.17.3"
set "otp_version=27.1.2"
set "otp_release=27"
set "elixir_install_root=%USERPROFILE%\.elixir-install"

if not exist "%elixir_install_root%" (
    mkdir "%elixir_install_root%"
)
```

somehow the installation is looking for `c:\users\wojtek`, hence it fails on my machine ...

```
 λ curl.exe -fsSO https://new.phoenixframework.org/app.bat; .\app.bat
checking OTP... Could not load module C:\Users\wojtek\otp\erts-15.1.2\bin\erlexec.dll.
Could not load module C:\Users\wojtek\otp\erts-15.1.2\bin\erlexec.dll.
Postgres is installed. Using Postgres for the Ecto adapter.
git version 2.45.1.windows.1

Creating new Phoenix project 'app'...

Could not load module C:\Users\wojtek\otp\erts-15.1.2\bin\erlexec.dll.

app created. Starting Phoenix server...

The system cannot find the path specified.
Could not load module C:\Users\wojtek\otp\erts-15.1.2\bin\erlexec.dll.
Could not load module C:\Users\wojtek\otp\erts-15.1.2\bin\erlexec.dll.
```

### Expected behavior

Use the correctly resolved` %USERPROFILE%`

**Comment by chrismccord** [comment]
Sorry this was a patch for testing this on virtualized wndows on osx arm that wasn't supposed to stick around for release. It's now fixed and deployed. Thanks!
