### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kantum** [phoenixframework/phoenix#6017]
### Actual behavior

The home webpage https://phoenixframework.org/ has this broken link: https://voicelayer.io/

The website is not secured, which affect the phoenix framework reputation.

I didn't find the website repo, is there one?

### Expected behavior

A secured link or no link :)

**Comment by SteffenDE** [comment]
Hey @kantum,

thank you for reporting! We're aware of it and have some plans to rework the whole company section. The site itself is currently not open source due to licensing constraints, but we've been thinking about open sourcing it once we have reworked it more.

**Comment by SteffenDE** [comment]
Done :)
