### ISSUE TITLE
no "root" html template defined for ...  (the module does not exist)

### ISSUE THREAD

**Issue by Fudoshiki** [phoenixframework/phoenix#6022]
### Environment

* Elixir version (elixir -v): 1.17 (same 1.18)
* Phoenix version (mix deps): 1.7.19 (same on 1.7.14)
* Operating system: macos

## Example code

Im owner of https://github.com/Youimmi/phoenix_asset_pipeline

I want to fix template error and remove `dets` files and hacks from lib

This is a new code example
https://gist.github.com/Fudoshiki/014d730f27e44916f92a28b69e777d2f

#### Runtime (works, as expected)
1.	`mix phx.server`
2.	Write an incorrect class `<body class={class(["bg-wh ite", "dark:bg-gray-900"])}>` and it will raise an error in runtime (as expected).
3.	Fix the class back, the page will reload (as expected).

#### Mix compile (doesn’t work)

1.	`mix phx.server` is not running.
2.	Write an incorrect class `<body class={class(["bg-wh ite", "dark:bg-gray-900"])}>`.
3.	Start `mix phx.server`, and it will raise an error. (as expected)
4.	Fix the class back to `<body class={class(["bg-white", "dark:bg-gray-900"])}>`.
5.	Run `mix phx.server`, and only `PhoenixAssetPipelineExampleWeb.Layout` will be recompiled, and you will get an error: 

`no "root" html template defined for PhoenixAssetPipelineExampleWeb.Layouts (the module does not exist).`

![Снимок экрана 2024-12-20 в 17 07 07](https://github.com/user-attachments/assets/ee7ba54b-ba3e-4159-baba-0ef9f9ff3c42)

To avoid this, you need to force recompiling `PhoenixAssetPipeline.Helpers`.

Remove `_build` folder or add `__mix_recompile?__, do: true` to `PhoenixAssetPipeline.Helpers`

### Expected behavior

Recompiled template

**Comment by Fudoshiki** [comment]
elixir 1.18.1 fixes this issue

**Comment by paynegreen** [comment]
This issues still exists with elixir 1.18.3

**Comment by GES233** [comment]
> This issues still exists with elixir 1.18.3

Same issue, Elixir 1.18.4.

<img width="1599" height="1075" alt="Image" src="https://github.com/user-attachments/assets/025905e0-4e2e-45b3-a7d7-e4d31937eaf4" />
