### ISSUE TITLE
Nice to have - default directory for new project

### ISSUE THREAD

**Issue by kgish** [phoenixframework/phoenix#603]
If a user doesn't include the second parameter for the directory name, the default should just be the project name.

For example,
```
$ mix phoenix.new hello_phoenix
```
Will place the new project in `./hello_phoenix`

**Comment by josevalim** [comment]
Agreed. I think we should make it behave the same as Elixir's new, at least for consistency!

**Comment by mdesantis** [comment]
I'm taking this: https://github.com/phoenixframework/phoenix/pull/605

**Comment by kgish** [comment]
Nice!

**Comment by mdesantis** [comment]
:pray: (yes I know it is "praying" but there isn't any highfive emoji yet)
