### ISSUE TITLE
`format` field in incoming JSON interferes with pipeline

### ISSUE THREAD

**Issue by zyro** [phoenixframework/phoenix#604]
I have a pipeline set up with `plug :accepts, ~w(json)` and an endpoint receiving JSON through HTTP POST. If the incoming JSON data contains a top-level field called `format` this overrides the existing format and I get an exception:
```
Request: POST /my/endpoint
** (exit) an exception was raised:
    ** (Phoenix.NotAcceptableError) unknown format "coming_from_json_input", expected one of ["json"]
        (phoenix) lib/phoenix/controller.ex:556: Phoenix.Controller.handle_params_accept/3
        (my_application) web/router.ex:16: MyApplication.Router.api/2
        [...]
```

Is this expected behaviour?

**Comment by josevalim** [comment]
At the moment, yes. Phoenix allows the request format to be overridden via the format option. We are discussing if we should rename it to "_format" to avoid conflicts.

**Comment by zyro** [comment]
`_format` is also a valid JSON field name (I think?) so could still conceivably be passed through, which would leave us with the same problem.

How about passing the decoded JSON body as a separate key in the params, one that cannot be set from query parameters?

Alternatively, a flag to disable overriding the `format` from any kind of input?

**Comment by josevalim** [comment]
If we pass as a separate key, then handling JSON requests become a bit more verbose, with no real benefit. Any key will choose will have the chance of conflicts. We just need to choose one that reduces this likelihood. In your case, can't you use another key besides format?

**Comment by zyro** [comment]
Where I have a choice I'm happy to avoid using `format` as a JSON key for now. The issue remains, though, particularly when building endpoints I can't fully control the input to:
* Public endpoints - I can give a spec/guidelines/documentation, but external users may still try to send whatever broken input they like.
* Callbacks - this is my main problem, endpoints that must accept input I can't specify myself, such as callbacks from other systems outside my control.

In those cases it would be best to leave content negotiation fully to the `Accept` and `Content-Type` headers.

Perhaps the option to 'namespace' what gets put into the `params` map? Based on a toggle, instead of freely dropping both query parameters and deserialised JSON input at the top level of the map, it would instead look something like:
```
%{
  "format" => "json",
  "query" => %{
    "some_query_param" => "...",
    [...]
  },
  "body" => %{
    "some_body_param" => "...",
    [...]
  }
}
```

**Comment by chrismccord** [comment]
Maybe the accepts plug should accept the param to use, with option to disable?

```elixir
plug :accepts, formats: ~w(json), param: "format"
plug :accepts, formats: ~w(json), param: false
```

**Comment by josevalim** [comment]
@chrismccord one of the reasons we negotiate here is to know which layout/template to render in the controller. Making it optional here would require configuration everywhere else in the stack. I think we should either go with `_format` or let it be.

**Comment by zyro** [comment]
If changing the way `conn.params["format"]` is set involves too much work, how about the second idea of (optionally) 'namespacing' query parameters and body data?

**Comment by josevalim** [comment]
Great! That can be easily done today by having a plug before the accepts
one that moves everything in params into its own key and stores it as the
new params!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by josevalim** [comment]
```elixir
plug :move_params

def move_params(conn, _opts) do
  put_in conn.params, %{"namespace" => conn.params}
end
```

**Comment by zyro** [comment]
@josevalim Great, that solves the single biggest problem. That said, I can't tell apart the parameters that came from the query, and the ones deserialised from the JSON body. Any ideas on that?

**Comment by josevalim** [comment]
You can get those from the conn.query_string. If you set conn.params to an
empty map before plug parsers they will be out.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by zyro** [comment]
I found a bit of a hacky solution:
```
# So I don't reinvent query string processing.
plug Plug.Parsers,
  parsers: [],
  pass: ["*/*"]

plug :move_query_params

plug Plug.Parsers,
  parsers: [:urlencoded, :multipart, :json],
  pass: ["*/*"],
  json_decoder: Poison

plug :move_body

def move_query_params(conn, _opts) do
  put_in conn.params, %{:query_params => conn.params}
end

def move_body(conn, _opts) do
  query_params = conn.params[:query_params]
    body = Map.drop(conn.params, [:query_params])
    put_in conn.params, %{:query_params => query_params, :body => body}
end
```

In the end, the `params` that reach controllers look like this:
```
%{
  "format" => "json",
  :query_params => %{
    "some_query_param" => "...",
    [...]
  },
  :body => %{
    "some_body_param" => "...",
    [...]
  }
}
```

So that solves the problem of telling which parameter comes from where. While this works, are there any issues with this approach that I'm not seeing?

**Comment by josevalim** [comment]
There are no issues but the first plug parsers call can be simply replaced
by :fetch_params

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by zyro** [comment]
Good call. The function didn't exist in `Phoenix.Endpoint` so I delegated to `Plug.Conn.fetch_params/2`.

Thanks for the help!
