### ISSUE TITLE
Website guide on channels is not yet updated

### ISSUE THREAD

**Issue by hamiltop** [phoenixframework/phoenix#607]
From the phoenix website:

    This guide is under construction

    Currently this data is only valid for 0.70 we apologize for this.
    We have a plan to update this ASAP. If it hasn't been updated
    by end of January 2015 call us out.

    1/11/2015

It's February. Just calling you out :smile:

**Comment by chrismccord** [comment]
haha! Thanks! We're pushing 0.9.0 this week with an overhauled pubsub layer and I promise to give the channel guides some much deserved TLC

**Comment by lancehalvorsen** [comment]
:sweat_smile: Apologies!

I've been working on figuring out the right way to present this material, and I think I hit upon something today. @chrismccord I'll do my best to have something up in the repo by tomorrow evening so you'll at least have more than a blank slate to work with for the 0.9.0 changes.
