### ISSUE TITLE
Linked Process Crash Leads to Error code: ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by rylev** [phoenixframework/phoenix#608]
I have an Agent process that is being supervised. This supervisor is in turn supervised by my application.

```elixir
  def start(_type, _args) do
    children = [
      supervisor(MyApp.CacheSupervisor, []),
      supervisor(MyApp.Endpoint, [])
    ]
    opts = [strategy: :one_for_one, name: Myapp.Supervisor]

    Supervisor.start_link(children, opts)
  end
```

When the Cache crashes due to a timeout, it is restarted by the supervisor, but the exit is never caught and thus the browser does not receive a 500 response but rather a `Error code: ERR_EMPTY_RESPONSE`.

**Comment by chrismccord** [comment]
What Phoenix version on you seeing this on?

**Comment by rylev** [comment]
This is version `0.8.0`

**Comment by josevalim** [comment]
Can you provide something that reproduces this error? All errors and exits happening inside the error are properly exhibited in this app I am working on. Is this happening inside a websocket? Also, which environment?

**Comment by rylev** [comment]
I'm not sure what give besides given full access to my app (which unfortunately I can't do). This is not happening inside of a websocket, and the env is both production and development. I will try to create a toy app to reproduce the issue.

**Comment by josevalim** [comment]
Yeah, a toy app would be great. :)

**Comment by josevalim** [comment]
Any info on how to reproduce this? Let us know so we can reopen it! Thank you!
