### ISSUE TITLE
How to start another application aside

### ISSUE THREAD

**Issue by lud** [phoenixframework/phoenix#609]
Hello,

I'm sorry if this is not the right place to ask this, I've just starting my Elixir journey.

I have an OTP app written in Erlang, and I decided to try Phoenix by writting a Web GUI for it. So I would like to know how to start Phoenix from my app, maybe with `application:start/1` or the opposite : tell Phoenix to start my app.

Thank you

**Comment by josevalim** [comment]
@lud you can use the mailing list for those questions.

In any case, if I was you, I would create a new project from scratch, using phoenix instructions, that depends on your current OTP app written in Erlang. This way you avoid creating a monolith application. If you go into this direction, check the documentation on how to use dependencies with mix (mix help deps) and so on.

**Comment by lud** [comment]
Ok thanks I'll make a post with further questions on the mailing list !
