### ISSUE TITLE
phoenix.js LongPoller should handle timeouts

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#610]

**Comment by chrismccord** [comment]
Closed via https://github.com/phoenixframework/phoenix/commit/701f13b576a0c73fa25ce294ceb027b0e9a6d62f

**Comment by josevalim** [comment]
Do we need to document any of those callbacks?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by chrismccord** [comment]
> Do we need to document any of those callbacks?

In this case, no, because the `onError` callback is triggered for timeouts (which is already doc'd)
