### ISSUE TITLE
Support multiple assets hosts

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#617]

**Comment by josevalim** [comment]
We need to do this before Plug 1.0 as we need to figure out how digest files will be served by Plug.Static.

**Comment by laurocaetano** [comment]
I'm on this one :)

**Comment by laurocaetano** [comment]
Hi there! 

Just pinging here to tell that I didn't fish the first draft, but I'm working on it. I'll open a PR soon :)
