### ISSUE TITLE
Phoenix not compatible with Elixir 1.0.3

### ISSUE THREAD

**Issue by arjan** [phoenixframework/phoenix#618]
`mix.exs` has version 1.0.2 hardcoded: 
https://github.com/phoenixframework/phoenix/blob/master/mix.exs#L7

**Comment by ericmj** [comment]
"~> 1.0.2" is compatible with 1.0.3.

**Comment by chrismccord** [comment]
```elixir
iex(4)> Version.match?("1.0.3", "~> 1.0.2 or ~> 1.1-dev")
true
```

**Comment by arjan** [comment]
oohhh sorry :-/, my mistake. Must be something else wrong then, trying to build a release with 1.0.3

**Comment by chrismccord** [comment]
@arjan We just found a bug when building releases on 0.9.0. Please try master for a fix :)

**Comment by arjan** [comment]
Will do, thanks :)
