### ISSUE TITLE
compilation of web/router.ex takes > 4 minutes with moderate number of routes

### ISSUE THREAD

**Issue by brweber2** [phoenixframework/phoenix#623]
My project compilation speed was very fast (< 5 seconds) until I recently added about 20 "resources" routes in web/router.ex.  For each one I have four options routes (for CORS support). So in total I have roughly 240 routes.  Compilation of models and controllers is fast, but now compilation stops for > four minutes when it gets to web/view.ex.  If I comment the routes out, compilation is fast again.

Why and is there something I can do to speed this up?  Should I not use "resources" and explicitly put the individual routes in myself?

**Comment by josevalim** [comment]
I definitely cannot reproduce a 4 minutes wait for routes but I am pushing compilation improvements to the router directly to master now. Please give master a try and let us know how it goes.

Also, if you can make your router available (you can replace the resource names by foo and bar), it would be a HUGE help. :)

**Comment by brweber2** [comment]
Yeah, sorry.  I should know better than to file bugs at 1 a.m. :/  Here is a gist with the content of lib/router.ex https://gist.github.com/brweber2/113f5f95abb527374fcd  

I'll keep looking into this.  I suppose it could be a combination of one of the plugs + so many routes, but I'm not sure what is going on internally. It is so slow that it makes me think there is something with very bad O notation that gets bad even with a couple hundred routes.

**Comment by brweber2** [comment]
Comparisons:

# Phoenix v0.8.0 

```
~/C/S/p/p/router_bug > time mix compile
Compiled lib/router_bug.ex
Compiled web/controllers/page_controller.ex
Compiled lib/router_bug/endpoint.ex
Compiled web/view.ex
Compiled web/views/error_view.ex
Compiled web/views/layout_view.ex
Compiled web/views/page_view.ex
Compiled web/router.ex
Generated router_bug.app
     1224.22 real      1166.00 user        10.36 sys
```

# Phoenix master

```
~/C/S/p/router_bug > time mix compile
Compiled lib/router_bug.ex
Compiled web/controllers/page_controller.ex
Compiled lib/router_bug/endpoint.ex
Compiled web/view.ex
Compiled web/views/error_view.ex
Compiled web/views/layout_view.ex
Compiled web/views/page_view.ex
Compiled web/router.ex
Generated router_bug.app
      219.93 real       207.30 user         2.30 sys
```

**Comment by brweber2** [comment]
Just to update this based on Jose's progress:

https://gist.github.com/brweber2/1b4b287b623ab829de3e

So the time is way down using master of Phoenix and dict.erl and erl_lint.erl from https://github.com/elixir-lang/elixir/tree/b8ae37dd141e1a41df0ddf258cc5d3ecf14ce99b/lib/elixir/src

My methodology:

* pull master of Phoenix
* create a new project
* add my routes to web/router.ex
* mix deps.get
* mix deps.compile

Then I loop and do these:
* mix clean
* time mix compile

I'm down to about 37 seconds pretty consistently as of right now. (That's way down from the 1200+ I had originally).

**Comment by josevalim** [comment]
You can also try adding this file to [src/beam_jump.erl](https://raw.githubusercontent.com/josevalim/otp/jv-beam-jump/lib/compiler/src/beam_jump.erl). I don't expect it to improve because I have worked around it on Phoenix but who knows? :)

**Comment by brweber2** [comment]
You are correct, no improvement, it is still 38 seconds for me.

**Comment by brweber2** [comment]
I decided to graph the performance of each set of routes (each set contains 12 routes).  The performance of adding new routes is definitely not linear:

Here is the raw data:

Sets of routes, seconds

18, 38.41
17, 32.88
16, 27.75
15, 24.43
14, 19.82
13, 16.97
12, 14.16
11, 11.25
10, 10.01
9, 7.46
8, 6.12
7, 5.19
6, 3.98
5, 3.24
4, 2.73
3, 2.35
2, 2.06
1, 1.85
0, 1.77


And a graph: http://nces.ed.gov/nceskids/createagraph/default.aspx?ID=b37b61c7b9f441abaf63b7aa15f8bc91

**Comment by josevalim** [comment]
It takes 12 seconds for me, using Elixir master, Phoenix master and those files I have earlier mentioned. I am considering this good enough™ for this purposes. Although we may want to prioritize router forwarding as a feature so we can at least split into multiple routers to avoid this issue.

**Comment by brweber2** [comment]
Would you like me to close this issue out then?

**Comment by josevalim** [comment]
If you feel it is adequated, yes. Also, if you are doing some sort of admin panel (hence the duplicated routes) ping me on IRC so we can discuss other designs that would solve the issue right now.

**Comment by josevalim** [comment]
I have actually found a proper fix now. Please try master!
