### ISSUE TITLE
Check origin in the transport if desired

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#629]

**Comment by ericmj** [comment]
I will look into this.

**Comment by josevalim** [comment]
I think the idea is to allow a list of ["*", "*.foo.bar", ...] as an explicit allow_origins configuration in websockets and a similar configuration on long pooling transports. Is this correct, @chrismccord?

**Comment by josevalim** [comment]
The value could default to the one in `url: [host: "..."]`

**Comment by jeregrine** [comment]
Websockets don't care about the origin, but the long polling will if CORs are enabled. :+1: on making the origin, header configurable.

**Comment by ericmj** [comment]
Neither websockets or long polling care about origin unless it's implemented in the application. By adding this check we can have the same cross-origin for both transports.
