### ISSUE TITLE
Fix the Channels documentation page

### ISSUE THREAD

**Issue by ephe-meral** [phoenixframework/phoenix#630]
[Here](http://www.phoenixframework.org/v0.9.0/docs/channels#joining-a-channel-topic) it says that to join a socket via `Transport.dispatch` you will have to initialize your socket like in the docs. However this does not work since the socket also needs the `pubsub_server: MyApp.PubSub` option for `Transport.dispatch` to work. So it should rather be:

```
iex(2)> socket = %Phoenix.Socket{
  pid: self, 
  router: HelloPhoenix.Router, 
  topic: "foods:all", 
  assigns: [], 
  transport: Phoenix.Transports.WebSocket, 
  pubsub_server: HelloPhoenix.PubSub}
```

throughout this documentation page, i guess.

**Comment by lancehalvorsen** [comment]
@ephe-meral @chrismccord I'm on this. I'm going over the whole Channel Guide to make sure all is correct for 0.9.0 - code, return values, whatnot. I'll push changes and update the website tonight.
//cc @jeregrine

**Comment by lancehalvorsen** [comment]
Ok, this should be fixed in the repo and the site.
https://github.com/lancehalvorsen/phoenix-guides/blob/master/G_channels.md
http://www.phoenixframework.org/v0.9.0/docs/channels

@ephe-meral please let me know if you see anything else amiss with the Channel Guide.

**Comment by ephe-meral** [comment]
thanks! will do.

**Comment by ephe-meral** [comment]
Maybe its not the right place for this, but I've been wondering why the Sockets (in the examples on this page, and also in e.g. Tests) need to be initialized with a topic - when i normally connect from an external client the Socket that gets passed into the join function has `topic: nil` and when replying to it in that same function the client will also see a nil topic.
