### ISSUE TITLE
Mix phoenix.routes path helper missing for PUT

### ISSUE THREAD

**Issue by kgish** [phoenixframework/phoenix#634]
Not sure if it is intentional, but I noticed that if I create a new resource like this:
```elixir
resources "/users", UserController
```
and then run  `$ mix phoenix.routes` I see that `user_path` for PUT is missing:
```elixir
user_path  GET     /users           HelloPhoenix.UserController.index/2
...
user_path  PATCH   /users/:id       HelloPhoenix.UserController.update/2
           PUT     /users/:id       HelloPhoenix.UserController.update/2
user_path  DELETE  /users/:id       HelloPhoenix.UserController.delete/2
```

**Comment by josevalim** [comment]
It is the same as PATCH. Since we can't have duplicated ones, we just pick one of them.

**Comment by kgish** [comment]
Why not? Do you mean that duplicate path_helper/action combinations are not allowed?

**Comment by josevalim** [comment]
Yes. They are not allowed because they both point to the same action. They just have different verbs.

**Comment by kgish** [comment]
Cool, I get it.
