### ISSUE TITLE
Unable to use remote host PubSub.Redis

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#636]
See this post for details:
https://groups.google.com/d/msgid/phoenix-talk/b4566816-8052-4819-8d12-fd47fe29f3c3%40googlegroups.com?utm_medium=email&utm_source=footer

I've recreated both issues and it seems like an eredis bug. I'm on vacation this week so this ones up for grabs if anyone is interested

**Comment by jeregrine** [comment]
I will try this out later this evening with an app using the built in pg2, I’ll try it with the heroku redis beta thing we got.

**Comment by josevalim** [comment]
Nice!
