### ISSUE TITLE
Remove "inheritance" like configuration from Phoenix

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#639]
Today, our views are configured as follow:

```elixir
defmodule YourApp.View do
  use Phoenix.View, root: "web/templates"

  # The quoted expression returned by this block is applied
  # to this module and all other views that use this module.
  using do
    quote do
      # Import common functionality
      import YourApp.I18n
      import YourApp.Router.Helpers

      # Use Phoenix.HTML to import all HTML functions (forms, tags, etc)
      use Phoenix.HTML
    end
  end

  # Functions defined here are available to all other views/templates
end
```

There issue is that it smells like inheritance. We have a parent view, where everything is imported. It will definitely become the place where user will put logic on top of logic, ending up with hundreds of LOC.

I think though, however, it is still useful to have a place where we will define all the common imports for views, models and controllers, so we don't need to repeat that particular piece of code.

I have played with some ideas but I don't have anything concrete yet. The best I have so far is:

```elixir
defmodule MyApp do
  use Phoenix.Using

  using View do
    use Phoenix.View, root: ...

    # Import common functionality
    import YourApp.I18n
    import YourApp.Router.Helpers

    use Phoenix.HTML
  end

  using Controller do
    ...
  end
end
```

Here we are only defining the using code. Furthermore, all code is accumulated in one place, so we don't end-up cluttering the web directory.

The downside is that we are mostly defining empty modules. I would love if we had a solution that relied on functions.

**Comment by josevalim** [comment]
Ok, here is another approach:

```elixir
defmodule MyApp.Web do
  def view do
    quote do
      IO.puts "Here goes view base"
    end
  end

  defmacro __using__(kind) do
    apply(__MODULE__, kind, [])
  end
end

defmodule MyApp.View do
  use MyApp.Web, :view
end
```

That is the version without sugar. The sugar version could be:

```
defmodule MyApp.Web do
  use Phoenix.Using

  using :view do
    IO.puts "Here goes view base"
  end
end

defmodule MyApp.View do
  use MyApp.Web, :view
end
```

**Comment by jeregrine** [comment]
I think I like the second approach better. I don't know if it solves the issue of people using it like inheritance though :-/

People will just dump those same methods into using :view as they would in the base view.

**Comment by josevalim** [comment]
That would be even worse. But at least it is easy to tell people to **not** define functions in there. While the previous approach had a explicit place to define functions too!

**Comment by jeregrine** [comment]
Maybe instead of a block people can just define a set of modules they want to be imported into :view etc. Not sure if thats an anti pattern though.

```elixir
defmodule MyApp.Web do
  use Phoenix.Using
  using :view, [MyApp.ViewHelpers, MyApp.FancyDateHelpers] 
end

defmodule MyApp.View do
  use MyApp.Web, :view
end
```

At least this forces separate modules. We could even have phoenix include the form helpers and etc here once we get them?

**Comment by josevalim** [comment]
@jeregrine the goal is that you would *import* any extra helper directly inside the using block for the view. We cannot make everything using though, because you also want to set imoprts, aliases, and other stuff.

**Comment by jeregrine** [comment]
Right. Maybe we just get rid of the whole concept of base view entirely and just suggest people import explicitly :)

**Comment by josevalim** [comment]
@jeregrine that's the point. It is not only about imports, you need to use, do aliases. If you are going to do it manually, you are going to have at least 5 common alias+import+use in *every* view.
