### ISSUE TITLE
Extract phoenix_redis_pubsub to a separate project

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#645]
We should do it when we are closer to 1.0 and push whatever redis dependency (eredis or redo) to hex.

**Comment by janjiss** [comment]
@josevalim FYI, I tried to gut this out from main Phoenix and it was as simple as creating new mix project and putting all files in there. Ping me if you need any help with thins when it is time to do so. 
https://github.com/janjiss/phoenix_pubsub
And all the tests are passing:
https://gist.github.com/janjiss/7fe13483c35f67157953

**Comment by josevalim** [comment]
Awesome @janjiss! We have no plans for doing it now because there will still be development in this area and having multiple projects will slow us down. But help will be welcome once we decide to go this path!

**Comment by janjiss** [comment]
@josevalim Of course, that makes sense.
