### ISSUE TITLE
Extract phoenix_html to a separate project

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#646]
We should do it when we are closer to 1.0 too.

**Comment by shankardevy** [comment]
Just mentioning my interest in doing this task when it's time.

**Comment by BennyHallett** [comment]
I started to take a look at this. The 2 main things I can see is that we have dependencies on both Plug and Phoenix.Controller within the Phoenix.HTML module.

I think the Plug dependency is probably ok, but given we're splitting this out from Phoenix, I think we'll need to find a way to not depend on it.

The only issue I can see is getting hold of the csrf token when generating form tags. Am I on the right track with this?

**Comment by josevalim** [comment]
@BennyHallett to be clear, we are not accepting pull requests for this issue. We will just extract it when it is closer to 1.0. Thanks though! :)

Now, to answer your questions, phoenix_html will likely depend on phoenix. So it is ok to depend on both Plug and Phoenix.Controller.

**Comment by BennyHallett** [comment]
No worries Jose, thanks.

The reason I ask about the Phoenix dependency was because phoenix_html was mentioned in hex/hex_web#69. I thought it'd be nice for Hex to be able to use the module without having to bring in all of Phoenix along with it.

**Comment by josevalim** [comment]
@BennyHallett that's a good point. We should consider something like this, maybe by making the controllers imports explicit instead of a module, and then depending just on plug.

**Comment by lexmag** [comment]
Praise the gods.

**Comment by josevalim** [comment]
I have extracted this. It took much more work than expected and it was hard to find the proper boundaries, that's why I decided to take a stab at it myself. Thanks everyone!

**Comment by shankardevy** [comment]
thanks @josevalim. For everyone who are watching this thread, here is the link to the extracted repo: https://github.com/phoenixframework/phoenix_html
