### ISSUE TITLE
Change the deployment instructions

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#656]
Today we see a lot of issues in the issues tracker and on IRC regarding releases. The issue is that neither @chrismccord nor I use releases in our workflows (at least not for now) so we can't help much in those situations.

Therefore I would like to propose for our official deployment instructions to rely on Mix instead. Basically:

    MIX_ENV=prod mix compile.protocols
    MIX_ENV=prod elixir -pa _build/prod/consolidated -S mix phoenix.server

We can still keep the releases stuff around but as another guide (which is referenced from the deployment one).

Thoughts? /cc @jeregrine @lancehalvorsen

**Comment by jeregrine** [comment]
I am 100% on board with this :+1: until we get more people cutting their teeth on releases/manual deploys lets keep it simple.

**Comment by jeregrine** [comment]
If you want I can swap out the deployment guide for now on the website and link back to the “Advanced Deployment” instructions. Maybe put a red box on top warning of dragons.

**Comment by sorentwo** [comment]
Trying to get releases working sucked about half a day for me. Simply following the compile and run flow worked within 5 minutes. Major :+1: from me.

All that it leaves me wondering is how to do zero-downtime-deploys. Admittedly, I haven't looked into it yet, but I doubt I'll be the only one.

**Comment by jeregrine** [comment]
Parker zero downtime deploys are something that releases can help you achieve, if needed, but can be tricky to get right. 




The better strategy in the near term is to just spin up a new server, add to the load balancer and slowly switch traffic to the new node. 




Or use a service like heroku.

**Comment by sorentwo** [comment]
@jeregrine: Thanks for sharing. I suppose I left a pretty open ended question. What I was really asking is how to do zero downtime on the same instance in the much lauded Erlang fashion.

No need to answer that, just pointing out it will be a great feature to be able to point to.

**Comment by josevalim** [comment]
Using the zero-downtime strategy of releases can be useful but it requires explicit coding and care. Traffic switching via load balancer is a much easier solution if you can do it (and you typically can do it in Phoenix applications).

**Comment by jeregrine** [comment]
I made the changes to the website and pr’d the changes into  Lance’s repo https://github.com/lancehalvorsen/phoenix-guides/pull/151 <3

**Comment by lancehalvorsen** [comment]
@josevalim @jeregrine @chrismccord - sorry, I'm a little late to the party here. I just got back from volunteering at EmberConf (which was great!). I'm totally down with this and have already merged @jeregrine's PR.

(Full Disclosure: The only time I've ever worked with releases is to re-write the guide post-endpoints. :) )

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by mdav43** [comment]
```
MIX_ENV=prod mix compile.protocols
MIX_ENV=prod elixir -pa _build/prod/consolidated -S mix phoenix.server
```

Gives me a error regarding the port. Change to 

```
MIX_ENV=prod mix compile.protocols
MIX_ENV=prod PORT=<the port you want to use> elixir -pa _build/prod/consolidated -S mix phoenix.server
```

**Comment by lancehalvorsen** [comment]
@mdav43, where are you seeing this task invocation without the port specified? I can't seem to find it in the repo or on the site.

**Comment by mdav43** [comment]
Sorry @lancehalvorsen , just in the above example from jose.

**Comment by lancehalvorsen** [comment]
@mdav43 ah, ic.  :+1:
