### ISSUE TITLE
Prescribe a way to encode JSON in the views

### ISSUE THREAD

**Issue by jeregrine** [phoenixframework/phoenix#657]
Lots of discussion happening around weather you should use defimpl (https://gist.github.com/drewolson/ddcbedbc4780c5066bbd) or if you should just return maps from your view's render function.

**Comment by paulcsmith** [comment]
Just chiming in that I think it would be valuable to have some kind of convention/best practice here. I like @drewolson  way of doing this, but I'm not sure what the pros/cons of the different strategies are.

**Comment by drewolson** [comment]
I created a public example[1] of this approach as well.

[1] - https://github.com/drewolson/blox/blob/8329dc79e4290b5c70cbe2cf808e914d0257bc26/lib/blox/protocol/poison/encoder/post.ex

**Comment by josevalim** [comment]
Nice example @drewolson! Quick question though: shouldn't you pass the options forward to when you call encode instead of passing an empty list?

**Comment by drewolson** [comment]
@josevalim that's a really good point, I hadn't thought about it. I'll update the example.

**Comment by josevalim** [comment]
@drewolson btw, have you implemented Poison.Encoder for some default Ecto types like Date, DateTime, Time and Decimal? If so, can you please point me to your implementation so I can add them to `phoenix_ecto`?

**Comment by drewolson** [comment]
@josevalim I've only done something for `Ecto.Date`, but I hadn't used an encoder. That's a really good idea, I'll move to it. My current implementation looks something like this -- https://gist.github.com/drewolson/04440d19b837dc6b4652

**Comment by josevalim** [comment]
Ah, ok. You can probably do something like this too: https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto.ex#L38-L44

**Comment by josevalim** [comment]
The big question is if we should serialize decimals as a string or as a float. :(

**Comment by hahuang65** [comment]
@josevalim I do this for Ecto.Date and Ecto.DateTime.
Just uses Ecto's builtin functions to convert to ISO8601.

https://gist.github.com/hahuang65/aeadef311a6f8ec44d8e

**Comment by paulcsmith** [comment]
Note that in the latest version of `phoenix_ecto` you get datetime JSON encoding for free: https://github.com/phoenixframework/phoenix_ecto/blob/716224086e7e2c1bc613e0eaed15d1a1d9d1c808/lib/phoenix_ecto/json.ex

**Comment by hahuang65** [comment]
I was just gonna link that :)
Jose's link above is outdated. See Paul's link.

**Comment by jeregrine** [comment]
@josevalim we can probably close this one in conjunction with #739 ?

**Comment by josevalim** [comment]
render_one and render_many are a huge step but not everything.  What is left are the generators + guides but we can tackle it on the side.
