### ISSUE TITLE
Add flash message support to redirect

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#658]
Do we want to add flash support on redirect? For example:

    redirect conn, to: path(...), notice: "User created with success"

If so, which keys do we want to use?

**Comment by josevalim** [comment]
Btw, my vote is yes, because it is much more concise. I have no idea if we want to go with notice/alert though. We need to choose something anyway to use in "scaffold".

**Comment by chrismccord** [comment]
We decided to keep flash as functional composition with redirtect, and use `:info` / `:error`, ie:

```elixir
conn
|> put_flash(:info, "it worked!")
|> redirect(to: "/")
```
