### ISSUE TITLE
Suggest to install mix deps.get

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#659]
Since we are installing npm dependencies, we should likely install mix ones too. However, instead of allowing us to disable those with flags, I think it would be better if we asked the user:

    Do you want install npm packages? [Y/n]
    Do you want install hex packages? [Y/n]

Thoughts?

**Comment by scrogson** [comment]
:+1:

**Comment by chrismccord** [comment]
I think this is a great idea. The brunch stuff is in master now. Anyone want to take this on before we release this weekend?

**Comment by josevalim** [comment]
I am tackling this as I work on phoenix.new with ecto. :)
