### ISSUE TITLE
Documentation to configure nginx to work with websockets

### ISSUE THREAD

**Issue by Chipairon** [phoenixframework/phoenix#663]
Hi,
In order to work with websockets proxying the application behind nginx, this configuration is needed to avoid `400` responses on connection negotiation:

```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}
server{
  listen 80;
  server_name <your.domain>;

  location / {
    proxy_pass http://localhost:<port>;
    proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
    proxy_set_header Host $host;  # pass the host header - http://wiki.nginx.org/HttpProxyModule#proxy_pass
    proxy_http_version 1.1;  # recommended with keepalive connections - http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version
    # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
}
```

I am not sure if this should be added to the guides about advanced deployment or channels so I am posting it here.

Cheers

**Comment by josevalim** [comment]
Thank you @Chipairon! The best is if you could write a blog post, as it would be the most googleable way (I think). In any case, we appreciate the info!

**Comment by acrolink** [comment]
@Chipairon, thank you very much. @josevalim, keep up the great work.

**Comment by hopewise** [comment]
@acrolink I've been struggling with using SSL with phoenix directly, I found using nginx much more easier. I wish it was that easy with phoenix, so that I don't have to use nginx as a proxy..
