### ISSUE TITLE
Move live reload to an internal Phoenix router

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#669]
TODO
- [ ] Plug above Logger to keep logs clean
- [ ] Bundle phoenix.js (do not depend on user code)

**Comment by josevalim** [comment]
We can likely keep it before Plug.Static too. It should take a whole namespace only for itself. :)

**Comment by chrismccord** [comment]
@josevalim let me know how that last diff looks. Under this setup, A user can just move `plug Phoenix.CodeReloader` to the top of their endpoint and no extra setup/config/compile checks is required.
