### ISSUE TITLE
Blog for release announcements

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#670]
We should start actually writing blog posts for our release announcements as they have better visibility. @lancehalvorsen & @jeregrine is this something we can include on our current website infrastructure?

/cc @chrismccord

**Comment by chrismccord** [comment]
+1000 I will draft a Blog post for the site about this release later today and post tomorrow. It will be a nice compliment to the screencast.

**Comment by jeregrine** [comment]
Yep its already there, Ive just hidden it as we dont have any posts.
