### ISSUE TITLE
mix phoenix.new ignores path argument (v0.10.0)

### ISSUE THREAD

**Issue by ptrckbrwn** [phoenixframework/phoenix#672]
I was playing around with v0.10.0 and noticed that the project generation mix task seems to ignore the path argument. For example:

`mix phoenix.new hello_phoenix ../hello_phoenix`
`mix phoenix.new hello_phoenix /Users/ptrckbrwn/src/hello_phoenix`

Either of the two commands, when run from the root of the phoenix repo (in my case, `/Users/ptrckbrwn/src/phoenix`), will generate the project *inside* of the phoenix repo, ignoring the last arg.

Let me know if more or what information would be helpful!

**Comment by josevalim** [comment]
It has changed on purpose to mirror mix new generator. It is mentioned in the changelog. :)
