### ISSUE TITLE
resource generator puts code in uncompilable state

### ISSUE THREAD

**Issue by ptrckbrwn** [phoenixframework/phoenix#673]
Given these series of commands:
```
mix phoenix.new hello_phoenix /Users/ptrckbrwn/src/hello_phoenix
cd ../hello_phoenix
mix do deps.get, compile
mix ecto.create
mix phoenix.gen.resource Tweet tweets text:string
mix ecto.migrate
```
On the last command the process errors out.
```
== Compilation error on file web/controllers/tweet_controller.ex ==
** (CompileError) web/controllers/tweet_controller.ex:27: function tweet_path/2 undefined
    (stdlib) lists.erl:1336: :lists.foreach/2
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
```

**Comment by josevalim** [comment]
Yes, the end of the generator says you need  The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by josevalim** [comment]
(Please ignore previous message send accidentally.)

Yes, the end of the generator says you need to add a route to your router. I have been undecided between adding it to the router (which would likely at the wrong place) or asking the user to it. It is basically a choice between failing at compilation time or at runtime. The earlier seems better to me (faster feedback).

Thoughts?

**Comment by ptrckbrwn** [comment]
Ah gotcha, I must of missed the message after running the generator. I think asking the user to do it is better: even if the generator could put it in the right place, the routes.ex could get pretty hairy.

Looking back at my terminal logs the instructions are pretty clear... I think my main issue was that it was 2am :)

**Comment by josevalim** [comment]
:)

**Comment by drewblas** [comment]
I was also struck by this.  I think the expectation is that the generator should not break compilation.  Surely there's a decent 'default' place to put the route?

**Comment by ptrckbrwn** [comment]
Correct me if I'm wrong, but the rest of the generator doesn't modify
existing files; it just creates new ones. Inserting the route into a new
phoenix project's routes.ex would be easy, but I can imagine it breaking
existing code (especially if it's complicated existing code).

Maybe a "do you want mix to automatically append to your routes.ex (y/n)"
option makes sense?

**Comment by chrismccord** [comment]
> I was also struck by this. I think the expectation is that the generator should not break compilation. Surely there's a decent 'default' place to put the route?

This is really tricky to get right. Think @josevalim said it best:

> it's basically a choice between failing at compilation time or at runtime. The earlier seems better to me (faster feedback).

I agree there. Outputting helpful instructions saying what to put in your router is a nice middle ground for me
