### ISSUE TITLE
Roadmap for 1.0

### ISSUE THREAD

**Issue by shankardevy** [phoenixframework/phoenix#677]
"I can make no promises, but I'd love to be there around May. There's still a lot to do and it largely depends on how far we want to go in some areas to brand 1.0" - @chrismccord 

I do not find any discussion related to the features intended for 1.0 and consequently it may not be possible for people interested to contribute to know what is on priority.

I request the contributors to briefly sketch out "how far we want to go in some areas to brand 1.0" so all of us know what will come in 1.0.

PS: If someone is reading this to know what is on priority for the next point release, here it is "form validation erors, silenced live reloader, xdomain channel support" - @chrismccord on irc

**Comment by josevalim** [comment]
This issues tracker is the roadmap. For example, for the next release, xdomain and livereloader are listed here. The form one is not but that is because I am already working on it. :)
