### ISSUE TITLE
Ensure bundled phoenix.js in code reloader does not conflict with the user one

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#679]
Both are being set as `require("phoenix")` and if they are different versions they will conflict.

**Comment by scrogson** [comment]
I wonder if this could be resolved by simply wrapping the injected code from the live reloader in a self calling anonymous function?

**Comment by chrismccord** [comment]
> I wonder if this could be resolved by simply wrapping the injected code from the live reloader in a self calling anonymous function?

We'd still need to skip the require.register("phoenix") bit so we don't stomp on that namespace

**Comment by chrismccord** [comment]
We already custom wrap the code here https://github.com/phoenixframework/phoenix/blob/master/brunch-config.js#L8-L12

So one terrible hack would be to extend the wrapper to check if "phoenix" has been registered, if it has, we register a "phoenix-core" or something and use that for the reloader.. Not sure how I feel about this, but it could be made to work.

```javascript
    wrapper: function(path, data){
      return(
        "var phxRequire = function(exports, require, module){ " + data + " }" +
        "require.define({'phoenix-core': phxRequire});\n" +
        "try{ require('phoenix') } catch(e) { require.define({'phoenix': phxRequire}); }" +
        "if(typeof(window) === 'object' && !window.Phoenix){ window.Phoenix = require('phoenix') };"
      )
    }
```

**Comment by chrismccord** [comment]
iframes to the rescue! I solved this by loading the bundled phoenix.js and code reload script in an iframe, and we just send `window.parent.location.reload()`. All is right with the world again and no nasty JS hack.

**Comment by josevalim** [comment]
Nice!

@scrogson you should try this out. I am not sure if this is going to work on your case given you are using different domains. @chrismccord you may also want to use `window.top` because of this: http://stackoverflow.com/questions/7545633/parent-location-reload-in-iframe-not-working-ie

I know more about iframe issues than I would like to confess. :(

**Comment by chrismccord** [comment]
I changed to `window.top` and confirmed it works with a different domain.
