### ISSUE TITLE
Check for incorrect usage of plural in mix.phoenix.gen.resource

### ISSUE THREAD

**Issue by shankardevy** [phoenixframework/phoenix#680]
Currently we do the following pattern match in mix.phoenix.gen.resource
```
  def run([singular,plural|attrs]) do
...
  def run(_) do
```

However, this does not include the case where `plural` should not contain ":".

I have two options
https://gist.github.com/shankardevy/4eba0fb45d0dd02af407#file-gistfile1-ex-L32-L40

this one looks interesting as well
https://github.com/phoenixframework/phoenix/compare/master...edmz:patch-1

**Comment by josevalim** [comment]
Option 1 is nice. But instead of calling run(""), move the error to a private function and have both functions calling it. :)

**Comment by josevalim** [comment]
Ah, that was @edmz approach. Let's ship with it. @edmz can you please send a PR? We also need a test.
