### ISSUE TITLE
v0.10.0 fails on mix phoenix.new on Windows (W8 x64)

### ISSUE THREAD

**Issue by cmelgarejo** [phoenixframework/phoenix#683]
Trying to create a new phoenix project I get this error, Am I doing something wrong or missing to configure anything? Thanks!

<pre>
* creating ../rest_api/README.md
* creating ../rest_api/config/config.exs
* creating ../rest_api/config/dev.exs
* creating ../rest_api/config/prod.exs
* creating ../rest_api/config/prod.secret.exs
* creating ../rest_api/config/test.exs
* creating ../rest_api/lib/rest_api.ex
* creating ../rest_api/lib/rest_api/endpoint.ex
* creating ../rest_api/mix.exs
* creating ../rest_api/test/rest_api_test.exs
* creating ../rest_api/test/test_helper.exs
* creating ../rest_api/web/controllers/page_controller.ex
* creating ../rest_api/web/router.ex
* creating ../rest_api/web/templates/layout/application.html.eex
* creating ../rest_api/web/templates/page/index.html.eex
* creating ../rest_api/web/views/error_view.ex
* creating ../rest_api/web/views/layout_view.ex
* creating ../rest_api/web/views/page_view.ex
* creating ../rest_api/web/web.ex
* creating ../rest_api/lib/rest_api/repo.ex
* creating ../rest_api/.gitignore
* creating ../rest_api/brunch-config.js
* creating ../rest_api/package.json
* creating ../rest_api/priv/static/images/phoenix.png
* creating ../rest_api/web/static/css/app.scss
* creating ../rest_api/web/static/js/app.js
* creating ../rest_api/web/static/vendor/phoenix.js

Install mix dependencies? [Yn] * running mix deps.get

Install brunch.io dependencies? [Yn] * running npm install

** (EXIT from #PID<0.47.0>) an exception was raised:
    ** (ErlangError) erlang error: :eacces
        :erlang.open_port({:spawn_executable, 'c:/Program Files/nodejs/npm.cmd'}
, [:use_stdio, :exit_status, :binary, :hide, {:args, ["install"]}])
        (elixir) lib/system.ex:445: System.cmd/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
</pre>

**Comment by cmelgarejo** [comment]
Shooting blanks here: 
* Maybe it's because the nodejs or npm version?
got node v0.10.31 and npm 1.4.23 
* Maybe it's the path where the npm is located?
* Maybe the inverted backlashes in the path?

**Comment by josevalim** [comment]
Erlang translates the backslashes so we should be fine there. Can you try running it on your own from iex? Please start iex and do this:

```iex
iex> System.cmd "npm", ["install"]
```

Does it work? If not, can you try this:

```iex
iex> :os.cmd('npm install')
```

If any of them take some while to return then it is because it works! :D

**Comment by mpahrens** [comment]
We are also having this problem on a windows machine (64 bit) with a 64 bit node and it is having the same issue, same error message. Running the npm install succeeds, but does not resolve the error.

**Comment by nickgal** [comment]
It appears to be a problem with the .cmd extension. When I try renaming it to a .bat it works.

Before:
```
iex> System.find_executable "npm"
"c:/Program Files/nodejs/npm.cmd"
iex>  System.cmd "npm", ["-v"]
** (ErlangError) erlang error: :eacces
             :erlang.open_port({:spawn_executable, 'c:/Program Files/nodejs/npm.cmd'}, [:use_stdio, :exit_status, :binary, :hide, {:args, ["-v"]}])
    (elixir) lib/system.ex:445: System.cmd/3
```

After `mv "C:\Program Files\nodejs\npm.cmd" "C:\Program Files\nodejs\npm.bat"`
```
iex>  System.find_executable "npm"
"c:/Program Files/nodejs/npm.bat"
iex>  System.cmd "npm", ["-v"]
{"1.4.28\n", 0}
```

Hope that helps. I started looking into the erlang side and got lost in port.

**Comment by josevalim** [comment]
@nickgal and @mpahrens can you please try running it as:

```iex
iex> :os.cmd('npm install')
```

And let me know if it works. Please try it while running it as `npm.cmd`.

Thank you for all the feedback. Let's get this working great on Windows!

**Comment by josevalim** [comment]
Another idea is to run this as:

    node c:/my_project/node_modules/brunch/bin/brunch watch

Which is a great suggestion from @mguillemot on #684.

**Comment by mpahrens** [comment]
Changing to cmd and running the npm install manually does fix our issue of being able to create a new project, but now we are stuck same as issue #684 . So I will follow that issue. Thanks!

**Comment by josevalim** [comment]
@mpahrens Unfortunately we cannot change it to `.cmd` in Phoenix itself. So we need to find a solution that works for this out of the box. If you could try the command above and let me know if it works out of the box, I would really appreciate it.

**Comment by josevalim** [comment]
Btw, a solution for the next problem was posted in #685.

**Comment by mguillemot** [comment]
`:os.cmd('npm install')` worked perfectly for me!

**Comment by mpahrens** [comment]
Worked fine for me.

**Comment by josevalim** [comment]
Fixed in master!

**Comment by cmelgarejo** [comment]
Thanks @josevalim I'm new @ elixir and phoenix, but this is looking great, cheers!
