### ISSUE TITLE
Brunch script does not run "as it" on Windows

### ISSUE THREAD

**Issue by mguillemot** [phoenixframework/phoenix#684]
When I start my Phoenix app on Windows (win7, 64 bits), I get a bunch of the following errors:

```
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["c:/my_project/node_modules/brunch/bin/brunch", ["watch"]]
** (exit) an exception was raised:
    ** (ErlangError) erlang error: :eacces
        :erlang.open_port({:spawn_executable, 'c:/my_project/node_modules/brunch/bin/brunch'}, [:stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["watch"]}])
        (elixir) lib/system.ex:445: System.cmd/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

It seems that Phoenix tries to invoke the `node_modules/brunch/bin/brunch` script directly, but Windows does not support shebang headers like these:

```
#!/usr/bin/env node
```

On the other hand, since I have node on my PATH, I can run the following without any issue:

```
node c:/my_project/node_modules/brunch/bin/brunch
```

**Comment by josevalim** [comment]
Can you please try the suggestion in #683?

**Comment by josevalim** [comment]
Sorry, I have just realized they are not the same issue. Just very similar. :)

**Comment by josevalim** [comment]
Fixed in master!

**Comment by bramd** [comment]
It seems, that on Windows brunch is not directly executable. However, by explicitly call npm in the watchers definition and giving the path to brunch as first argument, it works here.
