### ISSUE TITLE
Wrong brunch path in umbrella projects

### ISSUE THREAD

**Issue by mguillemot** [phoenixframework/phoenix#685]
If I have a umbrella project, say consisting of 2 apps:

- `C:/my_project` the umbrella project
- `C:/my_project/apps/xxx` a normal OTP application
- `C:/my_project/apps/web` a Phoenix application

Then Phoenix tries to invoke the `brunch` script from the following location:

`c:/my_project/node_modules/brunch/bin/brunch`

Of course this is not going to work since the `node_modules` folder is in `C:/my_project/apps/web/node_modules`

**Comment by josevalim** [comment]
Given #684, if you replace watchers: in your `config/dev.exs` by:

    ["node", [Path.expand("../node_modules/brunch/bin/brunch", __DIR__),  "watch"]]

Does it solve both issues?

**Comment by mguillemot** [comment]
Using `[{"node", [Path.expand("../node_modules/brunch/bin/brunch", __DIR__), "watch"]}]` (with a tuple, since it seems that watchers takes a `[{cmd, [args]}]`), we are getting closer:

```
iex(1)> c:\my_project\apps\web\node_modules\brunch\lib\helpers.js:514
        throw new Error("couldn\'t load config " + fullPath + ". " + error);
              ^
Error: couldn't load config c:\my_project\config. Error: Cannot find module 'c:\my_project\config'
  at Object.exports.loadConfig (c:\my_project\apps\web\node_modules\brunch\lib\helpers.js:514:15)
  at Object.exports.loadConfig (c:\my_project\apps\web\node_modules\brunch\lib\helpers.js:512:24)
  at initialize (c:\my_project\apps\web\node_modules\brunch\lib\watch.js:447:20)
  at new BrunchWatcher (c:\my_project\apps\web\node_modules\brunch\lib\watch.js:618:7)
  at module.exports.watch (c:\my_project\apps\web\node_modules\brunch\lib\watch.js:674:12)
  at start (c:\lbs\lbs_umbrella\apps\web\node_modules\brunch\lib\index.js:13:33)
  at Command.<anonymous> (c:\my_project\apps\web\node_modules\brunch\node_modules\commander\index.js:249:8)
  at Command.emit (events.js:110:17)
  at Command.parseArgs (c:\my_project\apps\web\node_modules\brunch\node_modules\commander\index.js:472:12)
  at Command.parse (c:\my_project\apps\web\node_modules\brunch\node_modules\commander\index.js:370:21)
  at Object.exports.run (c:\my_project\apps\web\node_modules\brunch\lib\cli.js:49:13)
  at Object.<anonymous> (c:\my_project\apps\web\node_modules\brunch\bin\brunch:11:22)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

So the `brunch` script is being executed properly, just not from the right working directory it seems. Digging into the Phoenix watchers code now to see if this can be fixed...

**Comment by josevalim** [comment]
Ah, brunch will look at the config file in the current directory. We may need to pass that as an option too.

**Comment by josevalim** [comment]
Try:

    [{"node", [Path.expand("../node_modules/brunch/bin/brunch", __DIR__), "watch", "-c", Path.expand("../brunch-config.js")]}]

**Comment by mguillemot** [comment]
I was reaching exactly the same conclusion, before realizing that the `-c` option is deprecated.

```
iex(1)> 10 Mar 16:59:18 - warn: `-c, --config` option is deprecated. Use `--env` and `config.overrides` instead
iex(1)> c:\my_project\apps\web\node_modules\brunch\lib\watch.js:406
      throw new Error("Current directory is not brunch application root path,
            ^
Error: Current directory is not brunch application root path, as it does not contain package.json (Error: Cannot find module 'c:\my_project\package.json')
  at loadPackages (c:\my_project\apps\web\node_modules\brunch\lib\watch.js:406:13)
  at c:\my_project\apps\web\node_modules\brunch\lib\watch.js:458:19
  at c:\my_project\apps\web\node_modules\brunch\lib\helpers.js:529:16
  at c:\my_project\apps\web\node_modules\brunch\lib\helpers.js:485:14
  at c:\my_project\apps\web\node_modules\brunch\node_modules\read-components\index.js:263:16
  at c:\my_project\apps\web\node_modules\brunch\node_modules\read-components\index.js:72:14
  at FSReqWrap.cb [as oncomplete] (fs.js:228:19)
```

I've read the docs for the new `--env` option but it seems geared toward a totally different problem (people using different config files for each build environment, and not "I want to specify where my one and only config file is located).

It seems we have to either submit a patch to brunch to add a new command-line flag that has an effect similar to the old `-c` (maybe only for specifying the path) or add a way for the Phoenix watchers to specify the `cd:` option of `System.cmd`...

**Comment by josevalim** [comment]
Ah, let's use the `cd:` option of System.cmd. Great idea.

**Comment by josevalim** [comment]
Btw, did you have issues with running npm install?

**Comment by mguillemot** [comment]
I commented there, but in essence it worked for me.

**Comment by mguillemot** [comment]
I just did a quick-and-dirty add of the `cd:` option on a local checkout of Phoenix, and it worked perfectly. 

Want me to do a pull request to add a facultative 3-tuple version of the watchers declaration that sends additional parameters to `System.cmd`?

**Comment by josevalim** [comment]
Oops, sorry @mguillemot, I have not seen your comment. I have just pushed a bunch of umbrella and windows related fixes to master. Can you please give them a try?

You will need to add: `root: Path.expand("..", __DIR__)` to your config/config.exs endpoint.

**Comment by mguillemot** [comment]
All good for me (both umbrella and node invoke)!

You're too fast for me to follow :smile:

**Comment by josevalim** [comment]
I couldn't have been this fast without your help. :) Thank you!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
