### ISSUE TITLE
Is grunt really needed?

### ISSUE THREAD

**Issue by arpunk** [phoenixframework/phoenix#692]
Dear phoenix team,

Everything was working fine until I decided to try v0.10.0 to write a small application. To my surprise, I had to compile and node.js, along with npm, in order to install something called grunt. The new `phoenix.new` tasks asks for it. If I choose to install the brunch dependencies, it all goes crazy because I'm running FreeBSD and npm cannot install the node-sass binary blob because it's either not in the npm registry or I need some GNU/Linux pathism in order to be able to run an Elixir application.

I'm back to v0.9.0 as I cannot get node.js installed on my servers because they are running FreeBSD aswell.

Is the brunch (and node.js) dependency needed?

**Comment by chrismccord** [comment]
> To my surprise, I had to compile and node.js, along with npm, in order to install something called grunt.

I assume you mean "brunch" instead of "grunt"? As we said in the announcement, brunch is an *optional* dependency. You can skip it it by running

`mix phoenix.new my_app --no-brunch` and continue to enjoy the same `priv/static` serving you had in 0.9.0

**Comment by arpunk** [comment]
Yea, I meant "brunch" sorry. I was not aware of that _optional_ flag (there is no mention of it in the announcement). Thanks for the quickreply.

**Comment by chrismccord** [comment]
No worries. Let me be clear that node is not, and will never be a  hard dependency. Brunch/node isn't required, but it gives you a super fast and simple static asset compilation system, so if you need to compile assets it's really nice. If you're just building an API, by all means pass the `--no-brunch` flag :)
