### ISSUE TITLE
Does Phoenix leverage this feature? 

### ISSUE THREAD

**Issue by ordiep** [phoenixframework/phoenix#697]
### From [Chicago Boss](http://chicagoboss.org/about.htm)
> Erlang is different from other platforms because when rendering a server-side template, it doesn't create a separate copy of a web page in memory for each connected client. Instead, it constructs pointers to the same pieces of immutable memory across multiple requests.

**Comment by lancehalvorsen** [comment]
The mailing list is probably a better place for this question.
https://groups.google.com/forum/#!forum/phoenix-talk

Having said that . . . Phoenix templates are compiled, so they do not create new copies in memory for each connected client.
