### ISSUE TITLE
Extracting comma seperated string in query parameters as list of items

### ISSUE THREAD

**Issue by miwee** [phoenixframework/phoenix#702]
While going through spec at http://jsonapi.org, I found usage of comma for denoting collection of related items. One example is
GET /comments?filter[post]=1,2&filter[author]=12

This is how phoenix processed it
  Parameters: %{"filter" => %{"author" => "12", "post" => "1,2"}, "format" => "json"}

If the above scenario is considered common enough, so that other people might be following this convention, then it would be better to extract "post" => "1,2" as "post => ["1", "2"]. So the response may look like this, which presents the intent more clearly
  Parameters: %{"filter" => %{"author" => "12", "post" => ["1", "2"]}, "format" => "json"}

**Comment by chrismccord** [comment]
I think this is best left up to a plug, which could do the parsing. The problem with auto doing this is we can't be sure things are id's, or just comma delimitted user input for arbitrary fields (common in html forms), so I would prefer something like this be used:

```elixir
plug Api.Params, ["post"]
```
I think this would make a great little hex package
