### ISSUE TITLE
mix phoenix.gen.resource does not work

### ISSUE THREAD

**Issue by hunterboerner** [phoenixframework/phoenix#706]
```
❯ mix phoenix.gen.resource Something somethings name:string
** (FunctionClauseError) no function clause matching in Module.split/1
    (elixir) lib/module.ex:853: Module.split("Rabbitci.Something")
    (phoenix) lib/mix/tasks/phoenix.gen.resource.ex:37: Mix.Tasks.Phoenix.Gen.Resource.run/1
    (mix) lib/mix/cli.ex:60: Mix.CLI.run_task/2
    (elixir) lib/code.ex:314: Code.require_file/2


17:39:40.851 [error] Error in process <0.47.0> with exit value: {#{'__exception__'=>true,'__struct__'=>'Elixir.FunctionClauseError',arity=>1,function=>split,module=>'Elixir.Module'},[{'Elixir.Module',split,[<<18 bytes>>],[{file,"lib/module.ex"},{line,853}]},{'Elixir.Mix.Tasks.Phoenix.Gen.Resource',run,1,[{... 
```

**Comment by chrismccord** [comment]
To fill other's in, @hunterboerner is on Elixir `1.1.0-dev`. I'm unable to recreate this on Elixir `1.0.3`. Perhaps something has changed/regressed in Elixir master?

**Comment by hunterboerner** [comment]
Yep, I just tested with 1.0.3 so it's definitely a problem with master.

**Comment by pma** [comment]
https://github.com/elixir-lang/elixir/commit/2024b48d71d6abd81dd0cce99137e405991047ef changed Module.split to expect an atom or a string with prefix "Elixir.".

But Phoenix master seems to reflect this change since  https://github.com/phoenixframework/phoenix/commit/45100119d3527e931767acaa64bb45007bec9b40

**Comment by chrismccord** [comment]
Ah, thanks @pma. Looks like we're good

**Comment by josevalim** [comment]
@hunterboerner it is nice that you are using Elixir master but keep in mind that you can run into trouble exactly like these. :) Btw, the change in Module.split to error defintiely caught a bug on Phoenix side.

**Comment by hunterboerner** [comment]
@josevalim yep, that's why I'm using it. :) Gotta find the bugs.
