### ISSUE TITLE
API generator

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#707]
Today we have a resource generator that generates pages for a browser. I think we should also include an API generator, that generates a resource but focused on a more API drive approach, including status codes and what not. The only issue is: what should we name this generator?

We have a couple options:

1. Keep a single resource generator and have an --api flag. I don't like this because it is going to amount to code and docs complexity in the generator

2. Have phoenix.gen.browser and phoenix.gen.api. The name is a bit misleading because we are not generating a browser. :P

3. Another alternative is to name them based on the format: phoenix.gen.html and phoenix.gen.json (generates an html resource and a json resource respectively). This is my preferred solution so far.

Thoughts? Ideas?

**Comment by paulcsmith** [comment]
I love the idea and option 3 makes the most sense to me.

**Comment by chrismccord** [comment]
+1 for option 3

**Comment by lancehalvorsen** [comment]
+1 for option 3 as well

**Comment by jeregrine** [comment]
3 :+1:

**Comment by scrogson** [comment]
Couple of ideas:

1. Ask the user at runtime:

```
λ mix phoenix.gen.resource User users name email

* creating priv/repo/migrations/20150321160957_create_user.exs
...

Would you like to generate HTML view templates? [Yn]

* creating web/templates/user/index.html.eex
...
```

2. Split generators into separate tasks `phoenix.gen.model`, `phoenix.gen.controller`, `phoenix.gen.template`, and `phoenix.gen.scaffold`.
  * The scaffold would invoke `model`, `controller`, and `template` generators.

I think I prefer option 2 here, because it will allow users to generate only what they need.

Thoughts?

**Comment by josevalim** [comment]
Having `phoenix.gen.scaffold` does not solve the problem because the plan is to have two "scaffolds", one for HTML and another for JSON. Hence the format proposal.

However, you are right, once we get to implement this, we need to break the generators apart anyway. We need at least a model generator since both "HTML" and "JSON" generators will need it.

**Comment by scrogson** [comment]
So maybe the `scaffold` generator can ask the user for which format they want?

**Comment by josevalim** [comment]
@scrogson asking is good for the first time but just the first time. All other times it is an annoyance because I know my options and what I want to generate. Specially for such generators which would be run frequently compared to the new application one which we just run from time to time. That's why I am more inclined towards something like .html asit may lead users to think: "ah, maybe there is another format too!".
