### ISSUE TITLE
Add path prefix configuration to Endpoint for prefixed path building

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#708]

**Comment by josevalim** [comment]
Nice. We already have a good place for adding this which is here:

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/adapter.ex#L109

And then consider it here:

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/adapter.ex#L130

What should be the name of the option @chrismccord? :prefix? :path?

**Comment by josevalim** [comment]
Sorry, my comment is wrong, it needs to use script_name.

**Comment by josevalim** [comment]
I have pushed this on ec2ce96. It is somewhat incomplete as it requires script_name to be explicitly set but I will work on making it better next.
