### ISSUE TITLE
Do not use ":" in channel events

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#712]
I am frequently confused by the fact events use ":" in their naming. Every time I glance at one, I think it is a topic, then I need to think twice and ask myself which one is it. Since we don't use ":" for anything in case of an events, what if our recommendation is to have them as simple strings and not include ":" in them? This way, if I look at "foo:bar", I know it is a topic, if it is just "foo", it is very likely it is event.

PS: I know we don't require ":" to exist in a topic strictly speaking but this is mostly a guiding convention.

**Comment by chrismccord** [comment]
:+1: I've thought about this too. For multi-world event names, should we promote hyphens instead?

`chan.send("new-msg")`

**Comment by josevalim** [comment]
I don't know what is cleaner from the JavaScript side but the Elixir in me simply says: "new_message".

**Comment by scrogson** [comment]
I actually like the `:` separator. I look at it as a namespace.

**Comment by josevalim** [comment]
I am ok with having a separator too as long as it is not the same one as the topic. :P
