### ISSUE TITLE
npm issue during installation on a Mac

### ISSUE THREAD

**Issue by pkoppstein** [phoenixframework/phoenix#715]
I followed the instructions at http://www.phoenixframework.org/v0.10.0/docs
and ran into some kind of npm issue, during the "mix phoenix.new DIR" step.  Everything went well until the "Install brunch.io dependencies?" substep, as shown below.

```
Install mix dependencies? [Yn] 

* running mix deps.get

Install brunch.io dependencies? [Yn] 

* running npm install
npm ERR! Error: Attempt to unlock clean-css-brunch@>= 1.0 < 1.8, which hasn't been locked
npm ERR!     at unlock (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/lib/cache.js:1304:11)
npm ERR!     at cb (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/lib/cache.js:646:5)
npm ERR!     at /usr/local/Cellar/node/0.10.26/lib/node_modules/npm/lib/cache.js:655:20
npm ERR!     at /usr/local/Cellar/node/0.10.26/lib/node_modules/npm/lib/cache.js:1290:7
npm ERR!     at /usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
npm ERR!     at OpenReq.Req.done (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
npm ERR!     at OpenReq.done (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:64:22)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
....
```
In case it's relevant:
```
$ /usr/bin/sw_vers
/usr/bin/sw_vers
ProductName:	Mac OS X
ProductVersion:	10.9.5
BuildVersion:	13F1066

$ node -v
v0.10.26

$ elixir --version
Elixir 1.0.3
```

Thanks!

**Comment by lancehalvorsen** [comment]
Caveat: I'm no npm expert.

This stackoverflow issue may be of assistance:
http://stackoverflow.com/questions/22152162/npm-cannot-install-dependencies-attempt-to-unlock-something-which-hasnt-been

**Comment by pkoppstein** [comment]
@lancehalvorsen - Thanks for the pointer.  I ran chmod on many directories (including $TMPDIR, /usr/local/bin/, /usr/local/Cellar, but not on /usr/local itself), to no avail.

It is sad that Phoenix has a dependency that makes it so brittle.

**Comment by josevalim** [comment]
@pkoppstein the dependency won't allow you to serve assets but everything else should work. Plus, if you don't want it, you can skip it completely by passing --no-brunch.

**Comment by chrismccord** [comment]
> It is sad that Phoenix has a dependency that makes it so brittle.

Let's be fair – this is exactly the first time this issue has been reported, and as José has said, if you pass `--no-brunch` you can enjoy all the Phoenix has to offer except asset compilation. This does indeed sound like a permissions issue. Can you try upgrading your node installation? `brew update && brew upgrade node`

**Comment by pkoppstein** [comment]
@chrismccord - Thanks for the suggestion to upgrade node.  That did not quite work, but it did make clear what the problem was: extended permissions on ~/.npm were causing npm to fail when attempting to create ~/.npm/javascript-brunch

The solution:
```
sudo xattr -c ~/.npm
sudo chmod -N ~/.npm
```
Unfortunately, since I upgraded node first, I don't know whether there was a node version dependency after all.  If there is such a dependency, shouldn't `mix` know about it?

@josevalim - Thanks for `elixir` -- a breath of fresh air!  A quick question (completely "off-topic" w.r.t. phoenix -- sorry about that): on p 236 of Paul Butcher's "Seven Concurrency Models in Seven Weeks", he writes "MapReduce is the only technology we're going to cover that realistically allows that quantity of data to be processed." Can you point to something that shows how Elixir could tackle the task as effectively?  It seems to be a matter of abstracting away the difference between physical computing resources and Elixir processes.

**Comment by josevalim** [comment]
@pkoppstein You are welcome! I advise you to bring this question (with a bit mode detail possibly) to the elixir-lang-talk mailing list. I think everyone contributions may make it more productive. :)
