### ISSUE TITLE
Brunch related error upon "mix phoenix.server" in umbrella apps

### ISSUE THREAD

**Issue by essenciary** [phoenixframework/phoenix#724]
Having an umbrella app with the following structure: 
```
├── _build
│   └── dev
├── apps
│   ├── feedlex
│   └── web_ui
├── config
└── deps
    ├── cowboy
    ├── cowlib
    ├── decimal
    ├── ecto
    ├── phoenix
    ├── phoenix_ecto
    ├── plug
    ├── poison
    ├── poolboy
    ├── postgrex
    └── ranch
```
When running `mix phoenix.server` in the root of the umbrella app, I get: 

```
mix phoenix.server
[info] Running WebUi.Endpoint with Cowboy on port 4000 (http)
[error] Could not start watcher "/Users/adrian/Dropbox/Projects/essenciary/essenciary_feedlex/node_modules/brunch/bin/brunch", executable does not exist
```

Not sure about the side effects yet - might end up with assets not being automatically compiled in development. I'll test and follow up.

**Comment by chrismccord** [comment]
The only side-effects are assets not being compiled. You need to update your `watchers:` to point to the correct path(s)

**Comment by chrismccord** [comment]
@essenciary Can you include the inner `apps` dir structure as well as the snippets from your dev.exs's?

**Comment by essenciary** [comment]
Thanks @chrismccord updating my `watchers:` worked 

Maybe it can be made more robust by: 
1. extending the `phoenix.new` generator to check the existence of `whatever/here/umbrella_dir/apps/my_app` and confirm by looking for `mix.exs` in `umbrella_dir/`
2. if yes, `dev.exs` could generate the umbrella compatible path instead - potentially by asking the user to confirm.

**Comment by essenciary** [comment]
@chrismccord 
```
➜  apps  tree -d -L 3
.
├── feedlex
│   ├── config
│   ├── lib
│   └── test
└── web_ui
    ├── _build
    │   └── dev
    ├── config
    ├── lib
    │   └── web_ui
    ├── node_modules
    │   ├── babel-brunch
    │   ├── brunch
    │   ├── clean-css-brunch
    │   ├── css-brunch
    │   ├── javascript-brunch
    │   ├── sass-brunch
    │   └── uglify-js-brunch
    ├── priv
    │   ├── repo
    │   └── static
    ├── test
    └── web
        ├── channels
        ├── controllers
        ├── models
        ├── static
        ├── templates
        └── views
```

They're the default configs as I'm just starting to work on a new project. The phoenix app was created directly inside the umbrella `apps/` dir. 

web_ui: https://gist.github.com/f07ed0918fc99c000872
feedlex: haven't created the configs per environment yet, just the regular `config.exs` for a `mix new`:
```
use Mix.Config
```

The issue also occurred on a previous project, after upgrading phoenix from 0.9 to 0.10

**Comment by josevalim** [comment]
Yeah, we have fixed this bug in master and should be ok in new applications.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer
