### ISSUE TITLE
Submodules not handled correctly

### ISSUE THREAD

**Issue by anagromataf** [phoenixframework/phoenix#727]
Creating an project with phoenix.new (version 0.10.0) and using a submodule (e.g., "Web.API") results into an error.

I created a project with ```mix phoenix.new /tmp/web_api  --no-ecto --no-brunch --module Web.API``` and tried to run it as is. Starting the server with ```mix phoenix.server``` compiles everything without an error. But accessing the root results into this error:

    Could not render "index.html" for Web.API.PageView, please define a clause for render/2 or define a template at "web/templates/api/page". No templates were compiled for this module.

Moving the template folder for _page_ and _layout_ into the subfolder _api_ or setting the namespace in web.ex (```use Phoenix.View, root: "web/templates", namespace: Web.API```) results into an other error:

    undefined function: Web.LayoutView.render/2 (module Web.LayoutView is not available)

**Comment by josevalim** [comment]
@anagromataf good catch. You will need to call `plug :put_new_layout, {Web.API.LayoutView, :application}` to your browser pipeline.

**Comment by anagromataf** [comment]
@josevalim I hacked some kind of namespace support into the Controller. Maybe that would also be an options compared to the view.

```
defmodule Phoenix.Controller do
  defmacro __using__(options) do
  namespace = Keyword.get(options, :namespace, nil)
    quote do
      @controller_namespace unquote(namespace)
      import Plug.Conn
      import Phoenix.Controller

      use Phoenix.Controller.Pipeline

      plug Phoenix.Controller.Logger
      plug :put_new_layout, {Phoenix.Controller.__layout__(__MODULE__, @controller_namespace), :application}
      plug :put_new_view, Phoenix.Controller.__view__(__MODULE__)
    end
  end
  
  # ...
  
  def __layout__(controller_module) do
    __layout__(controller_module, nil)
  end
  
  def __layout__(controller_module, nil) do
    Phoenix.Naming.base_concat(controller_module, "LayoutView")
  end
  
  def __layout__(controller_module, namespace) do
    Module.concat(namespace, "LayoutView")
  end
end
```

With this I can use ```use Phoenix.Controller, namespace: Web.API``` in my web.ex. If that is also an option, I would do it a bit nicer and provide and pull request. ;-)

**Comment by chrismccord** [comment]
> With this I can use use Phoenix.Controller, namespace: Web.API in my web.ex. If that is also an option, I would do it a bit nicer and provide and pull request. ;-)

As José said 

```elixir
plug :put_new_layout, {Web.API.LayoutView, :application}
```
is the best approach. Not code injection required and pipelines work perfectly for these scenarios.

**Comment by chrismccord** [comment]
I don't think we need any changes on this one. Let us know if you have issues getting the pipelines set up.

**Comment by anagromataf** [comment]
Thanks for the help. Using the namespace option for the view and the plug it works. Maybe the generated project should contain this als well?

**Comment by josevalim** [comment]
Yeah, we should leave this open. @chrismccord I was thinking about support namespace in controller... at least for consistency with how views work. Wdyt?

**Comment by chrismccord** [comment]
@josevalim just explained the need for this, so I can see how a `:namespace` option would remove the need for putting `plug put_view` in every controller. We'll do some more internal discussion on this, but it's probably something we can sneak in for 0.11 if we decide to move forward.

**Comment by josevalim** [comment]
Fixed in master.
