### ISSUE TITLE
phoenix.server task doesn't start after installing the phoenix archive

### ISSUE THREAD

**Issue by scrogson** [phoenixframework/phoenix#728]
It seems like the archive collides with running local phoenix mix tasks...

Running:

```
iex -S mix phoenix.server
```

I'm not getting a message in the log that cowboy is listening on port 4000 and visiting in the browser results in a web page unreachable error page in Chrome.

Uninstalling the mix archive fixed this.

**Comment by chrismccord** [comment]
You need to build/install the archive in the installer/ (not the root
Phx die). You'll also need to rm the archive you just built from ~/.mix/archives
