### ISSUE TITLE
Performance expectations

### ISSUE THREAD

**Issue by fatum** [phoenixframework/phoenix#729]
Hi to all!

I started use phoenix for high throughput app and have couple of questions:

* What performance can i expect? Phoenix based on cowboy and i saw very impressive numbers (20-30RPS)

* When i bench simple "hello world" at localhost i get only 2K rps with high latency (150-200msec), i used wrk with 1K concurrent connections. This is my issue only? What is a roundtrip through the full Phoenix stack?

* Can anyone share some real numbers from production usage?

PS My app doesn't depend on external IO (ets tables only) and simple render json and tiny html widget
PPS Elixir 1.0.3, Phoenix 0.10.0, Max OS

Thanks for any help!

**Comment by chrismccord** [comment]
Are you running with MIX_ENV=prod and consolidated protocols?

**Comment by fatum** [comment]
@chrismccord Yes!

MIX_ENV=prod mix compile.protocols 
MIX_ENV=prod PORT=4001 elixir -pa _build/prod/consolidated -S mix phoenix.server

**Comment by josevalim** [comment]
@fatum can you put the app or something similar available somewhere so we can take a look? Also, which Elixir / Phoenix versions are you using?

**Comment by josevalim** [comment]
Nevermind, I was able to reproduce it in a new app. I will investigate.

**Comment by josevalim** [comment]
@fatum I have pushed some fixes to master, we had two issues but the biggest one being that static lookup was disabled on production. If you add `cache_static_lookup: true` to your prod config, does it make things better?

**Comment by fatum** [comment]
Yes, with cache_static_lookup: true result little better (it was 0.10)

```
2 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    85.71ms   12.75ms 128.87ms   79.50%
    Req/Sec     1.53k   340.80     1.96k    50.00%
  3107 requests in 1.00s, 731.24KB read
```

But, when i checkout master i get error 

```
Code reloader was invoked for Adserver.Endpoint but no code reloader server was started. Be sure to move `plug Phoenix.CodeReloader` inside a `if code_reloading? do` block
        (phoenix) lib/phoenix/code_reloader/server.ex:21: Phoenix.CodeReloader.Server.reload!/1
        (phoenix) lib/phoenix/code_reloader.ex:45: Phoenix.CodeReloader.call/2
```

**Comment by chrismccord** [comment]
> But, when i checkout master i get error

Update your `plug Phoenix.CodeReloader` in your endpoint.ex to be:

```elixir
if code_reloading? do
  plug Phoenix.CodeReloader
end
```

Then re-run your measurements.

**Comment by fatum** [comment]
Thanks, it works, but result not changed. 

Only i have this result?

**Comment by josevalim** [comment]
I got 8k req/s on my machine with logging. About 16k with logging only
warn. If you have a simple app, I would love to take a look and give
pointers.
>
>

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by fatum** [comment]
@josevalim @chrismccord Thanks for your help!

> If you have a simple app, I would love to take a look and give
pointers.

Thanks, but I just bench fresh new app with one controller which set status 200 and body "hello world", if nobody in community got result like me, i think this is my local case

In my toy test i want to measure what is a roundtrip through the full phoenix stack and, when i set logging only warn i got ~ 8K rps on my old laptop with wrk running on the same machine

PS I work with elixir and phoenix couple of weeks and it was so simple, productive and impressive for my purpose (ad serving) and i think it would be right choice for our (http://dispply.com/) new version of adserver
