### ISSUE TITLE
Fix RedisServer and RedisConn EXIT semantics

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#732]

**Comment by josevalim** [comment]
Wait, we still need to call shutdown on terminate and receive the EXIT
message on both. The change is that we should not call shutdown *only* in
the exit message.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by chrismccord** [comment]
Since we link with redo, do we need to call shutdown?

**Comment by josevalim** [comment]
@chrismccord terminate is also called for normal exits.

**Comment by josevalim** [comment]
I am reopening this. :)
