### ISSUE TITLE
NPM Brunch installation failure

### ISSUE THREAD

**Issue by rossjones** [phoenixframework/phoenix#733]
If you choose not to install the brunch dependencies at ```phoenix.new``` (0.10.0)  time you are told:

```
Brunch was setup for static assets, but node deps were not
installed via npm. Installation instructions for nodejs,
which includes npm, can be found at http://nodejs.org

Install your brunch dependencies by running inside your app:

    $ npm install
```

If however you chose Yes at ```phoenix.new``` time, **and the installation fails** (connecting to github :( ) you are no longer instructed that you can use ```npm install``` in the app folder to get the same result.

**Comment by chrismccord** [comment]
I don't think we need to worry about this one tbh. The output after you answer yes says "running npm install", so I think we're ok.
