### ISSUE TITLE
Digest, gzip and generate manifest files for assets

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#735]
We need to do this before Plug 1.0 as we need to figure out how digest files will be served by Plug.Static.

**Comment by laurocaetano** [comment]
I'm working on this one!

I'll open a W.I.P Pull Request as soon as I get something working.

**Comment by laurocaetano** [comment]
I have some questions:

1 - How the links will work? Example: A CSS that points to an image.
```css 
.class { background-image: url('image.png') }
```
How can we make it point to the digested file?

2 - How it will be integrated with third party assets? One [example](https://github.com/rails/sprockets/blob/master/UPGRADING.md#preference-for-asset-manifest-and-links) is how links works on sprockets.

I'm completely new to phoenix codebase, so I might be saying something not related with this issue at all. Ideas?

**Comment by josevalim** [comment]
That's a very good point we will need to discuss them eventually. I think we can leave them to a later stage though since our static system will still serve image.png with conditional cache.

**Comment by laurocaetano** [comment]
That's great, thanks!

**Comment by laurocaetano** [comment]
Hi there!

I've been working on this issue the past few days and I have a draft for the implementation: https://gist.github.com/laurocaetano/ee876a71fc0c32afa6dd What do you think?

How is this going to work on Phoenix? Is it going to be a new mix task or something?

**Comment by laurocaetano** [comment]
I think this can be closed now, right?
