### ISSUE TITLE
RFC: JSON serialization helpers

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix#739]
## The Rundown

First, I'm writing this pretty quickly when I have spare time so it isn't organized as well as I'd like. *Feel free to ask lots of questions*. Code examples are at the bottom.

**The problem**

When serializing JSON there is still a lot of boilerplate functions being defined. A lot of typing what could (fairly) easily be inferred (view names, actions names, etc.).

**The solution**

* Add helpers for rendering records with sensible conventions that are *easy to override*. `put_one/many` and `render_one/many`. By default they use the view's Base (App.V1.PostView -> App.V1) and appends the module of the record with the word view (App.V1.UserView when a record is a App.user).
* Override easily with `view: MyView` and/or `action: "show_lite.json"`
* Add some boilerplate functions for rendering lists of records. `render("index.json")` and `render("show.json")` for lists.

Having strong conventions makes it clear when we break them. So if you use a view that is not the default it is very easy to spot. *Skip to the bottom to see example code*.

**Pros/Cons**

* It does add a few more conventions. More to remember and learn at first.
* Once you know the convention, you can write code more efficiently and it makes it obvious when you break the convention.

## The Proposal

**Add `put_one/many` functions for adding serialized records to maps**

 `put_one` and `put_many` work almost identically, except one is for Lists and
 one is for a single struct.  The first argument is the key to insert, second
  is the struct or list of structs and the third is options.
  
  If you pass in a `App.User` struct like this
      
      %{title: post.title}
      |> put_one(:author, %App.User{name: "Gumbo"})
  
  The function will use the base of the current view (in this case `App.V1`) and
  append the suffix of the struct with `View` So in the example below it will use
  `App.V1.UserView` as the default view to render with. You can override this
  with the option `view: App.MyView`, e.g. `put_one(:author, %App.User{name:
  "Gumbo"}, view: App.AwesomeUserView)`
  
  `put_one` and `put_many` will use the `show.json` action by default (or
  whatever we decide makes sense as a name).  This can be overridden by passing `action:
  "show_lite.json"`. `put_many` will need a "show.json" function defined specifically for handling
  lists. I think we should auto generate that:

**Generate a default function for rendering a list of objects without a root key**
  
  A function for `render("show.json", %{data: records}) when is_list(records)`
  will automatically be added when importing the view helpers. It will make a
  list of records that are serialized with "show.json". This function will be
  overridable. It would look something like this.
  
      def render("show.json", %{data: records}) when is_list(records) do
         for record <- records, do: render("show.json", %{data: record})
      end
      
  **Add `render_one/many` function for serializing inside of a map literal**
  
  `render_one` and `render_many` are identical to `put_one/many`, but return the serialized
  result and don't put the result into a key in a map.  You would have to do
  something like: `Map.put(:author, render_one(post.author))` or use the
  function above, `put_one`. I like the option of having both of these functions.
  
  All functions will assume that render functions accept a map that looks like
  `%{data: my_record}`.  I prefer something like `%{comments: comments}`, but
  the inflections/pluralization could get tricky.

**Default `index.json` function.**

  I also believe that we should generate a default function for
  render("index.json"). This can of course be overridden when you need to do
  something more complex. You can override the root key with `@root_key :oxen`.

      def render("index.json", %{data: records}) do
        %{}
        |> Map.put(root_key_for(records), render_many(records))
      end

      def root_key_for(records) do
        # Gets the name of the struct of the first record and downcases and
        # pluralizes it. 
        # You can override this if `@root_key` is provided in the view. 
        # e.g. @root_key :oxen
      end

## Examples

```elixir
defmodule App.V1.PostController do
  # imports, etc.
  
  def show(conn, %{"id" => post_id) do
    post = Repo.get(Post, post_id)
    
    render conn, data: post
  end
end
```

```elixir
defmodule App.V1.PostView do
  @attributes ~W(id title body tags permalink)a
  
  # Option 1
  def render("show.json", %{data: post}) do
    post
    |> Map.take(@attributes)
    |> put_many(:comments, post.comments)
    |> put_one(:author, post.user, view: App.UserView)
    |> put_many(:related_articles, action: "show_lite.json")
  end
  
  # Option 2. I think `render_one` and `put_one` 
  # should both be included, but `put_one` could be removed and you could do
  # `Map.put(:author, render_one(post.author))`. but I'm not a huge fan of that.
  # I think both function should be provided.
  def render("show.json", %{data: post}) do
    %{
      id: post.id,
      title: post.title,
      body: post.body,
      tags: post.tags,
      permalink: post.permalink,
      author: render_one(post.user, view: App.UserView),
      comments: render_many(post.comments),
      related_articles: render_many(post.related_articles, action: "index_lite.json")
    }
  end
  
  # Option 3. I'm not a huge fan of this, but maybe it will inspire some other ideas?
  def render("show.json", %{data: post}) do
    %{
      id: post.id,
      title: post.title,
      body: post.body,
      tags: post.tags,
      permalink: post.permalink,
      author: post.user,
      comments: post.comments,
      related_articles: post.related_articles
    }
    # This is like updating the comments key with a serialized version of comments
    # `|> Map.update(:comments, fn(comments) -> render_many(comments) end)
    |> serialize(:comments)
    |> serialize(:author, with: App.V1.UserView)
    |> serialize(:related_articles, action: "index_lite.json")
  end
end
```

**Comment by paulcsmith** [comment]
BTW, I would be happy to create a PR once I get some feedback on what people like/dislike.

**Comment by josevalim** [comment]
@paulcsmith great rundown, thanks for this! Here are my thoughts:

  * `render_one` and `render_many` definitely need to be included. That's for sure our starting point.

  * "By default they use the view's Base (App.V1.PostView -> App.V1)" we can't actually do this unless they are macros, which pushes me more towards a no-go. We can inflect it based on the model name (i.e. basically `App.User` becomes `App.UserView`) but that introduces the issue that the view will be correct up to some point and passing `view: ...` all the time can get tedious. Generally though, I am +1 for inflecting the view.

  * I am not sure if we should inflect the "action". The reason is that render_one and render_many are also useful outside JSON. We could for example use it to render a collection in HTML! The issue though is that in HTML, we likely want the default action to be "post.html" while in JSON it will end-up being "show.json". There is also the issue we can't actually access the format in render_one/render_many so we can't even generate the proper action name anyway.

With all that said, I would provide `render_one/render_many` with the following signatures:

    render_many(collection, template)
    render_many(collection, template, assigns)
    render_many(collection, view, template)
    render_many(collection, view, template, assigns)

`render_one` would be similar.

Another idea which we discussed is if we should pass the data as simply `:data` or using something more relevant, based on the view. For example, we could have:

    render_many collection, App.UserView, "show.html"

which would call:

    App.UserView.render "show.html", user: each_item

Which is a bit better than having `:data` everywhere. The `:user` bit is extracted from the view and can be configured with the `:as` option:

    render_many collection, App.User, "show.html", as: :lite_user

Thoughts?

**Comment by paulcsmith** [comment]
@josevalim Thanks for the feedback!

> By default they use the view's Base (App.V1.PostView -> App.V1)" we can't actually do this unless they are macros, which pushes me more towards a no-go

I've tried this function and it works without a macro. If you call it from `App.V1.PostView` and pass it a `App.User` struct it will return `App.V1.UserView`.

```elixir
# Added to the `view` function in MyApp.Web

def view_for_record(%{__struct__: model}) do
      namespaces = Module.split(__MODULE__)
      base_view = namespaces |> Enum.take(Enum.count(namespaces) - 1)

      model_name = Module.split(model) |> Enum.reverse |> List.first
      view_name = "#{model_name}View"
      full_view_name = List.flatten([base_view, view_name])
      |> Module.concat
end
```
I wrote this quickly and it could obviously use some cleanup :P, but it works. No macros needed :)

> I am not sure if we should inflect the "action". The reason is that render_one and render_many are also useful outside JSON. We could for example use it to render a collection in HTML!

I never thought of using these for HTML. Good point! Maybe we could have a default template and change the function names to `render_json` and it would render one or many based on whether you pass it a list or not. Maybe that's too much magic, but I figure it's worth bringing up.

I'm fine if we don't inflect the action/template name. Given that we don't need a macro for the view I definitely think the view should be inflected since it can be properly namespaced with that function above :D

> Another idea which we discussed is if we should pass the data as simply :data or using something more relevant, based on the view

Totally agree that it would be nice to not have `data` everywhere. I think this could be inflected from the model and if you need to override it might be nice to do it with an attribute in the view as I suggested in the original post. You probably missed it because I wrote way too much haha.

I wrote:

> Default index.json function.

> I also believe that we should generate a default function for
render("index.json"). This can of course be overridden when you need to do
something more complex. You can override the root key with @root_key :oxen.

This attribute could be renamed to @singular_key and @plural_key. That way the attribute could be used for a default `index.json` function and  also for the key when calling render. What do you think of that?

**Comment by josevalim** [comment]
> I wrote this quickly and it could obviously use some cleanup :P, but it works. No macros needed :)

In your example you are using the model as basis. Not the view. So that will definitely work. :) The simplest implementation would be:

```elixir
defp view_for_model(%{__struct__: struct}) do
  struct
  |> Atom.to_string
  |> Kernel.<>("View")
  |> String.to_atom
end
```

> This attribute could be renamed to @singular_key and @plural_key. That way the attribute could be used for a default index.json function and also for the key when calling render. What do you think of that?

:-1: for singular and plural. We have done tons of work on Phoenix to *not* have plural and singular, so I wouldn't introduce them now. :) Just explicitly define the index view and we are fine.

**Comment by josevalim** [comment]
@paulcsmith I think we agree with everything else though. That said, can you please send a pull request for `render_one`/`render_many` with the signatures proposed earlier:

```elixir
render_many(collection, template)
render_many(collection, template, assigns)
render_many(collection, view, template)
render_many(collection, view, template, assigns)
```

* We are inflecting the view, as you proposed
* The template name is explicit
* The render parameter will be inflected from the *view* but can be configurable with `:as`

Those can be directly added to `Phoenix.View`.

**Comment by paulcsmith** [comment]
Sounds good! Thanks for laying that out clearly I'll work on a PR.

**Comment by jeregrine** [comment]
:+1: Here I thought @josevalim had merged these already!

**Comment by josevalim** [comment]
@paulcsmith have you started any work on this? I want to pick this up as it is on my bucket for 0.12.

**Comment by paulcsmith** [comment]
I'm on vacation and won't be able to work on it for a few more days. I started on it but it's not worth pushing up. Feel free to tackle it if you need it soon!

**Comment by josevalim** [comment]
@paulcsmith ok, thanks. Enjoy the vacation!

**Comment by paulcsmith** [comment]
@josevalim thanks! :)

**Comment by josevalim** [comment]
I have pushed this. Thank you for the write up @paulcsmith. Although reluctant at first, I really like your idea of "inflecting" the view as it allows us to render a collection of different models dynamically. :+1:

**Comment by paulcsmith** [comment]
@josevalim You're welcome, and thanks for implementing. It looks great!
