### ISSUE TITLE
Add a channel generator

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#741]

**Comment by gjaldon** [comment]
Hi @josevalim! I'd like to take this on if no one else has worked on it yet.

**Comment by josevalim** [comment]
please go ahead :)

**Comment by gjaldon** [comment]
Is this channel generator going to generate Channel files for a resource similar to `phoenix.gen.json` and `phoenix.gen.html`? Where instead of a controller we generate a channel which handles incoming CRUD events?

**Comment by josevalim** [comment]
The channel will generate just the channel (no model for it).
