### ISSUE TITLE
Generate test files in phoenix.gen.html and phoenix.gen.model

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#748]

**Comment by parkerl** [comment]
I'd love to take a stab at this @josevalim if you are not already working on it.

**Comment by josevalim** [comment]
@parkerl I have already started on the test files for phoenix.gen.model, so feel free to tackle the ones for phoenix.gen.html.

**Comment by parkerl** [comment]
On it!

**Comment by parkerl** [comment]
@josevalim I'm looking for some feedback on that second SHA above. (Github is doing something unhelpful by displaying the first) Am I on the right track? What else should the generated tests be testing? Also, the tests generated by this implementation will not be green without user intervention. I'm not dynamically generating valid params for create and update. I assume that generating those would be ideal.

**Comment by josevalim** [comment]
@parkerl This looks *fantastic*. I have added some comments but those comments are because we (phoenix + plug) are lacking the tools to make those tests more elegant. So we will need to improve the surrounding area a bit.

About the params, good question. Maybe we should define an attribute:

    @user_params [name: "foo", age: 0]

And pass those as argument on create and update so we at least don't have to duplicate them in different places?

**Comment by parkerl** [comment]
@josevalim oh great! I will see what I can do on the params issue when I get a few more free minutes. One more thing, views do not appear to have much in them when they are generated beyond boilerplate. Do we want a boilerplate test file generated? A good 'ol `1 == 1`?

**Comment by josevalim** [comment]
@parkerl let's not generate anything for views. I think they will be mostly boilerplate. I will generate a simple test for the ErrorView but that will be it. I am waiting for your html tests PR, it is almost good to go. :D

**Comment by parkerl** [comment]
@josevalim sorry, I'm just trying to clean things up and get it out. Hopefully sometime today.

**Comment by josevalim** [comment]
Don't be! I was not trying to hurry you in any way, it was just a reminder that it is good to go. Take your time. :)

**Comment by josevalim** [comment]
Just a follow up. This is almost ready! We just need tests for the failure scenarios in create/update and I believe @parkerl is on it.
