### ISSUE TITLE
mix phoenix.server doesnt start endpoint 

### ISSUE THREAD

**Issue by 2kodes** [phoenixframework/phoenix#750]
Hi 

After creating a new phoenix v0.11.0 project, running mix phoenix.server in the project directory in dev mode doesnt start the endpoint or server. It only works after setting the config "server" for the endpoint to true. I believe the default behaviour was to flip it on to true automatically?? :( 
I am using elixir 1.0.4  with erlang 17.4

**Comment by josevalim** [comment]
I cannot reproduce this. The generated Phoenix application worked out of the box just fine. Are you upgrading an existing application?

**Comment by 2kodes** [comment]
No i am not upgrading an existing application. 
PS: I generated the application with the --no-brunch option. Is there a possibility of this being the cause??  

mix phoenix.new   my_app  --no-brunch

**Comment by chrismccord** [comment]
Can you include your dev.exs  contents?

**Comment by josevalim** [comment]
I think you changed your `mix.exs` somehow. In any case, you have uncovered a bug, this is fixed in master! :D Thank you!

**Comment by 2kodes** [comment]
@josevalim  You are welcome . Glad to have helped. :)

**Comment by 2kodes** [comment]
@chrismccord 

use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :my_app, MyApp.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  cache_static_lookup: false,
  watchers: []

# Watch static and templates for browser reloading.
config :my_app, MyApp.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif)$},
      ~r{web/views/.*(ex)$},
      ~r{web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Configure your database
config :my_app, MyApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "my_app_dev"
