### ISSUE TITLE
Error when running in prod mode

### ISSUE THREAD

**Issue by 2kodes** [phoenixframework/phoenix#751]
I am using elixir v1.0.4 with erlang 17.4
Currently in a freshly generated phoenix v0.11.0 project running 
MIX_ENV=prod mix phoenix.server 
or  

MIX_ENV=prod mix compile.protocols
MIX_ENV=prod PORT=4001 elixir -pa _build/prod/consolidated -S mix phoenix.server

results in the stacktrace below

Generated ecto app
==> phoenix_ecto
Compiled lib/phoenix_ecto.ex
Compiled lib/phoenix_ecto/json.ex
Compiled lib/phoenix_ecto/html.ex
Generated phoenix_ecto app

16:10:00.228 [error] Module 'Elixir.Phoenix.HTML.Safe' must be purged before loading

16:10:00.228 [error] Module 'Elixir.Phoenix.Param' must be purged before loading

==> archive_phoenix
Compiled lib/archive_phoenix.ex
Compiled web/web.ex
Compiled lib/archive_phoenix/repo.ex
Compiled web/router.ex
Compiled web/views/error_view.ex
Compiled web/controllers/page_controller.ex
Compiled lib/archive_phoenix/endpoint.ex
Compiled web/views/layout_view.ex
Compiled web/views/page_view.ex
Generated archive_phoenix app
Consolidated Ecto.Queryable
Consolidated Phoenix.HTML.Safe
Consolidated Phoenix.HTML.FormData
Consolidated Phoenix.Param
Consolidated Plug.Exception
Consolidated Poison.Decoder
Consolidated Poison.Encoder
Consolidated Access
Consolidated List.Chars
Consolidated String.Chars
Consolidated Enumerable
Consolidated Inspect
Consolidated Collectable
Consolidated Range.Iterator
Consolidated protocols written to _build/prod/consolidated
{"Kernel pid terminated",application_controller,"{application_start_failure,archive_phoenix,{{shutdown,{failed_to_start_child,'Elixir.ArchivePhoenix.Endpoint',{'EXIT',{badarg,[{erlang,bit_size,[nil],[]},{'Elixir.Phoenix.Endpoint.Adapter',url,1,[{file,\"lib/phoenix/endpoint/adapter.ex\"},{line,154}]},{'Elixir.Phoenix.Config',cache,3,[{file,\"lib/phoenix/config.ex\"},{line,48}]},{'Elixir.Phoenix.Endpoint.Adapter',start_link,2,[{file,\"lib/phoenix/endpoint/adapter.ex\"},{line,24}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,314}]},{supervisor,start_children,3,[{file,\"supervisor.erl\"},{line,297}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,263}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,306}]}]}}}},{'Elixir.ArchivePhoenix',start,[normal,[]]}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,archive_phoenix,{{shutdown,{failed_to_start_child,'Elixir.ArchivePhoenix.Endpoint',{'EXIT',{badarg,[{erlang,bit_size,[nil],

**Comment by josevalim** [comment]
You no longer need to do the protocol dance with Elixir v1.0.4.

**Comment by 2kodes** [comment]
the protocol dance..lol
May i please know the correct way to run phoenix in production mode??

**Comment by josevalim** [comment]
`MIX_ENV=prod PORT=4001 mix phoenix.server` should be enough now. I will try to verify your reports soon.

**Comment by 2kodes** [comment]
thanks .. tried but still the same.:(  however i will wait for the results on your end. Perhaps i might be doing something wrong or have a faulty configuration somewhere

**Comment by 2kodes** [comment]
yipeeee.. 
@josevalim   Setting "server" setting for the Endpoint to true in prod.exs under the config folder makes it work with MIX_ENV=prod PORT=4001 mix phoenix.server   :)

However theres another issue I think. 
running MIX_ENV=prod mix phoenix.server  without setting the port seems to give a stacktrace similar to above. It seems the config is expecting the port to be given in prod mode???

**Comment by josevalim** [comment]
> running MIX_ENV=prod mix phoenix.server without setting the port seems to give a stacktrace similar to above. It seems the config is expecting the port to be given in prod mode???

The stacktrace is horrible. You either need to set the PORT=... or configure your port properly.

**Comment by josevalim** [comment]
Are you sure you have a new Phoenix application? I think you are missing the `compilers: [:phoenix] ++ Mix.compilers` option in your mix.exs...

**Comment by 2kodes** [comment]
no. the contents are as follows :

defmodule Evo.Mixfile do
  use Mix.Project

  def project do
    [app: :evo,
     version: "0.0.1",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type `mix help compile.app` for more information
  def application do
    [mod: {Evo, []},
     applications: [:phoenix, :cowboy, :logger, :ecto]]
  end

  # Specifies which paths to compile per environment
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies
  #
  # Type `mix help deps` for examples and options
  defp deps do
    [{:phoenix, "~> 0.11"},
     {:phoenix_ecto, "~> 0.3"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_live_reload, "~> 0.3"},
     {:cowboy, "~> 1.0"},
     {:timex,[]},
     {:mariaex,[]},
     {:gutenex,[]},
     {:chunky_svg,[]}

    ]
  end
end
