### ISSUE TITLE
Add Phoenix.ChannelTest

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#754]
Started in #652 . Adding here for 0.12 milestone.

**Comment by paulcsmith** [comment]
Just a heads up, I'm working on upgrading our internal app to Phoenix 0.11.0 and along with it, the test helpers I wrote. I'm way busy, but I'll see what I can do. @chrismccord When do you want to release 0.12?

**Comment by josevalim** [comment]
Landed on master. I will write the docs soon.
