### ISSUE TITLE
Code reloader doesn't properly load in dev environment

### ISSUE THREAD

**Issue by hahuang65** [phoenixframework/phoenix#755]
In the upgrade instructions from 0.10 to 0.11, it states that we should add
`config :your_app, Your.Endpoint, code_reloader: true`
in config/dev.exs file.

Then, to support this option, we need to actually load the code reloader, which we do by adding
```
if code_reloading? do
  plug Phoenix.LiveReloader
  plug Phoenix.CodeReloader
end
```
in lib/your_app/endpoint.ex

This is working great, but only when the Endpoint is up and running.

When running anything that doesn't kick up the Endpoint, such as mix tasks like `mix ecto.migrate`, it will complain that CodeReloader is not available.

Here's the stacktrace. It actually looks like it's Phoenix.LiveReloader
```
== Compilation error on file lib/khronika/endpoint.ex ==
** (UndefinedFunctionError) undefined function: Phoenix.LiveReloader.init/1 (module Phoenix.LiveReloader is not available)
    Phoenix.LiveReloader.init([])
    (plug) lib/plug/builder.ex:205: Plug.Builder.init_module_plug/3
    (plug) lib/plug/builder.ex:193: anonymous fn/4 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:193: Plug.Builder.compile/3
    (phoenix) expanding macro: Phoenix.Endpoint.__before_compile__/1
    lib/khronika/endpoint.ex:1: Khronika.Endpoint (module)
```

**Comment by hahuang65** [comment]
Sorry, this was a false alarm. @josevalim made me aware that Phoenix.LiveReloader is separately required as an external dep.

I removed it. It might help to make this clear(er) on the upgrade guide. If it's there, I apologize to have missed it.

**Comment by iraasta** [comment]
Have it when launching with MIX_ENV=prod
How to go through that error?

**Comment by josevalim** [comment]
You need to set the code_reloading option to false in your production
config.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by gissandrogama** [comment]
@josevalim very good!
I had the same problem, I managed to get through this tip.
