### ISSUE TITLE
The task phoenix.new could not be found

### ISSUE THREAD

**Issue by sononix** [phoenixframework/phoenix#756]
Getting a "The task phoenix.new could not be found. Did you mean 'phoenix.server'?"

running something like this for my startup -
```
sudo git clone https://github.com/phoenixframework/phoenix.git
sudo chmod -R 777 phoenix/
cd phoenix/
sudo git checkout v0.10.0
sudo mix do deps.get, compile
sudo mix phoenix.new ~/CODE/SITES/www
```

```
iex -v
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.1.0-dev
```

**Comment by chrismccord** [comment]
The new task is now available as a mix archive so you can skip the git clone dance:

    mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.11.0/phoenix_new-0.11.0.ez


Now `mix phoenix.new` will be available from anywhere on your system.

**Comment by osmanehmad** [comment]
I was getting the following

** (Mix) The task phonix.server could not be found

I did as posted by chrismccord and it worked.

**Comment by tenzan** [comment]
@chrismccord :+1:

**Comment by kkoci** [comment]
Hi, it says error 404, I went to: https://github.com/phoenixframework/phoenix/releases/

But no mix.new package, can someone help me please?

Thanks in advance!

**Comment by josevalim** [comment]
Try this one:

    mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez

**Comment by kkoci** [comment]
Awesome!

Thank You very much!

**Comment by ktec** [comment]
This comes up top in google search, so I'll add this here.

As of Phoenix 1.3+ this should be:

```
mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez
```

**Comment by Garachu** [comment]
It worked on Windows 10. Thank you

**Comment by mattcantstop** [comment]
I've been working through why I can't create a new Phoenix project. It seems I have Phoenix installed here: 

`Found existing entry: /Users/matt/.mix/archives/phx_new-1.5.1`

But when I run this command: `mix phoenix.new rsvp_web --no-ecto`

the output is: 

```
Compiling 2 files (.ex)
Generated rsvp app
** (Mix) The task "phoenix.new" could not be found
```

Any ideas?

**Comment by josevalim** [comment]
The task has been renamed to phx.new a couple releases ago. :)

**Comment by mattcantstop** [comment]
Watching an old tutorial. That makes sense 😆. Thanks!

**Comment by sushant12** [comment]
@mattcantstop  you can use `mix help` to see the list of tasks like `phx.new` and on its side you will see a small description. 

If you want a detailed description you can always run `mix help phx.new` :)

**Comment by mattcantstop** [comment]
Thanks, that’s helpful. I just immediately assumed something wasn’t connected during installation, but I should have looked at the docs and verified. Appreciate it!

**Comment by aliwo** [comment]
Thanks!
