### ISSUE TITLE
Decimal ecto fields specified in mix phoenix.gen.html create number fields in the HTML

### ISSUE THREAD

**Issue by lsimoneau** [phoenixframework/phoenix#759]
Example:

```
mix phoenix.gen.html Product products name:string price:decimal quantity:integer
```

At least in Chrome, this makes it impossible to submit the form with a decimal input.

![screen shot 2015-04-10 at 7 31 24 pm](https://cloud.githubusercontent.com/assets/31768/7085251/41b92480-dfb8-11e4-9b80-848c7e06082c.png)

It's easy enough to change the template back to a text field, but it seems like it would be best to only output a number field for integer columns.

**Comment by josevalim** [comment]
> It's easy enough to change the template back to a text field, but it seems like it would be best to only output a number field for integer columns.

Yes, defnitely, please send a PR?

**Comment by josevalim** [comment]
Another option is this: https://blog.isotoma.com/2012/03/html5-input-typenumber-and-decimalsfloats-in-chrome/

Just add step: "any" to float and decimals.

**Comment by lsimoneau** [comment]
Yep, ok, I'll have a look at making a PR for this (using `step: "any"`, that seems like the best solution).

**Comment by lsimoneau** [comment]
Ok, I've had a look into the code, and I'd like to know what others think before diving in. Looking at the `inputs/1` function [here](https://github.com/phoenixframework/phoenix/blob/1ebea0bd1651a03914c6bd455c4be69bf1033108/lib/mix/tasks/phoenix.gen.resource.ex#L69), a two-element tuple is passed along in the bindings to the template, in the form `{ :name_of_field, :form_helper_function }`. In order to add `step: "all"` to decimal and float column types, I'd need to either:

1. Update `inputs/1` to return a 3-element tuple, with the last element being a map of options to be passed to the helper function. This is complicated and requires more changes to more files, but feels like it provides some greater flexibility for handling other similar cases where different input types might potentially want different form attributes.

2. Create a new helper function like `decimal_input` that generates a number input with `step: "any"`. This feels like a hack to me, but is certainly much narrower in scope.

Any thoughts?

**Comment by lsimoneau** [comment]
Alternately I could just make decimals and floats output a text field. That feels kind of like giving up, but at least avoids the bad experience of generating a form that doesn't work at all.

**Comment by josevalim** [comment]
@lsimoneau If you do a 3 tuple, something like this would be the best:

https://github.com/phoenixframework/phoenix/blob/1ebea0bd1651a03914c6bd455c4be69bf1033108/lib/mix/tasks/phoenix.gen.model.ex#L98

Another alternative is to generate the whole input as a string still in the generator: "number_input f, #{inspect field}, step: "any"`

I think this may be the cleanest approach and support more robust schemas in the future. Thoughts?

**Comment by lsimoneau** [comment]
We can't just use a single string, since the `index` and `show` templates use those tuples to output the headers of tables using the field names. Although I guess we could have 2-element tuples of `{ :field_name, :whole_input_string }`?

**Comment by josevalim** [comment]
@lsimoneau we can make the second element of the tuple the string. The index view cares only about the key. :)

**Comment by lsimoneau** [comment]
Sounds good :+1: On it.
