### ISSUE TITLE
Ask instead of saying sorry when it comes to npm

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#763]
Today we are generating brunch assets and then telling people that it won't work if they don't have npm. Maybe we could flip it a bit.

If the user does not have npm in his system, we should ask them: "Phoenix uses a node.js build tool called brunch.io but you don't have node.js in your system. Would you like to skip the build tool setup?".

If the user say yes, we go with static, if the user says no, we install brunch files and then generate the instructions for installing node deps after. Note that we are not adding a new question, we are slightly changing the workflow so users are not caught by surprise and later we end-up telling them "oh, you should have used --no-brunch".

Thoughts?

**Comment by chrismccord** [comment]
This is what we did at first, before we changed to the `--no-brunch`, so I would be fine with this.
