### ISSUE TITLE
Running phoenix.new multiple times results in duplicated database configs

### ISSUE THREAD

**Issue by parkerl** [phoenixframework/phoenix#766]
I ran this command `mix phoenix.new ../../scratch` and then ran the exact same command again and entered `n` for all the overwrite responses. As you can see here in the commit below the database config is duplicated.

https://github.com/parkerl/scratch/commit/760268be580f172b989d63da07294bf629087d4e

**Comment by chrismccord** [comment]
I'm assuming we append to *.exs and that's why yo get the dup. I think this is OK to be honest. The preferred upgrade path is usually a manual one. Running `mix phoenix.new` on top of an existing project is always going to require a bit of fiddling after the fact to get things right.

**Comment by parkerl** [comment]
Thanks @chrismccord that is totally reasonable. I ran into this while working on the test generators. I was running it multiple times with `--dev` to update the scratch app I was using to fiddle with the generators. I was not using the default database setup for dev. I will fix that but perhaps that is not the best workflow?

**Comment by chrismccord** [comment]
It would be very difficult to us to make any guarantees when running phoenix.new over top of an existing app. I'd prefer to leave this as is and rely on `git diff` and version control to handle the rest of job.

**Comment by parkerl** [comment]
Yup. Totally get it. Wasn't trying to argue against closing the issue. Thanks.
