### ISSUE TITLE
Remove inconsistency in "use" inside web/

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#768]
Today, inside the web directory we have:

* `use MyApp.Web, :controller`
* `use MyApp.Web, :view`
* `use Phoenix.Router`
* `use Phoenix.Channel`

I would like that all "use" inside the web directory went through `MyApp.Web`. Thoughts?

**Comment by chrismccord** [comment]
I've had similar thoughts, but we haven't had much of a need for routers/channels. I'm still :+1: since it would be a nice place to group aliases/imports as they come up
