### ISSUE TITLE
[error] backend port not found: :inotifywait

### ISSUE THREAD

**Issue by jhlllnd** [phoenixframework/phoenix#776]
I get the message
```
[error] backend port not found: :inotifywait
```
when running ```mix phoenix.server```

I think i am missing something but i can't find something about phoenix and inotify or inotifywait on google or in the docs. Maybe it has something to do with code reloading?

Edit:
I have Elixir 1.0.3 and phoenix 0.11

**Comment by josevalim** [comment]
Yes! You need that for live reloading, we need to make the docs/guides better. Install instructions here:

https://github.com/rvoicilas/inotify-tools/wiki

I can improve phoenix_live_reload readme but I am pinging @jeregrine @lancehalvorsen to let them know and figure out if something needs to be done in the guides front.

**Comment by jhlllnd** [comment]
Thanks, that was what i needed to know :)

**Comment by sanford** [comment]
Having just hit the issue on my linux install, seems the inotify instructions should also be on the installation page, not just the overview page:

http://www.phoenixframework.org/docs/installation

**Comment by twajjo** [comment]
Ok, that's great; but how do I just turn inotifywait off?  What if I don't need it?  What if the error shuts down a dockerized phoenix container I am trying to run?

**Comment by josevalim** [comment]
@twajjo it shouldn't shutdown a phoenix container and it is used only in development. If you don't want it at all, remove phoenix_live_reload as a dependency and from your endpoint.ex.

**Comment by twajjo** [comment]
Thanks, Jose.  I agree that it should not shut down the phoenix container, and it does not if I use a shell entry point and start the server by hand, but (weirdly enough) it does.  Still trying to figure out what the issue is.

**Comment by josevalim** [comment]
@twajjo are you setting `MIX_ENV=prod` when building and starting the app?

**Comment by twajjo** [comment]
Yes I am.  The issue was a bad Dockerfile example provided by a co-worker.  I have resolved the issue, but many thanks for your attention.

And many more thanks for my new favorite language, Jose.
