### ISSUE TITLE
Phoenix missing from Web Framework Benchmark

### ISSUE THREAD

**Issue by JakobHealey** [phoenixframework/phoenix#777]
Even though phoenix appears to be in the Github source, Phoenix is not in the latest benchmarks

http://www.techempower.com/benchmarks/previews/round10/

https://github.com/TechEmpower/FrameworkBenchmarks

**Comment by chrismccord** [comment]
I would love to see it there if someone wants to setup the test/notify the powers that be. I have other priorities at the moment though. Thanks!
