### ISSUE TITLE
Rendering of shared view without assigns fails

### ISSUE THREAD

**Issue by c-rack** [phoenixframework/phoenix#782]
Following [the template guide](http://www.phoenixframework.org/v0.11.0/docs/templates#shared-templates-across-views), it is possible to include a shared view (aka partial) by using
```elixir
<!-- within a MyApp.PageView layout, for example -->
<%= render MyApp.SharedView, "key.html", key: key %>
```
If you try to render a shared view without assigns, a "template not found" exception is raised, because the parent view searches for the key template its own directory instead of the shared directory:
```elixir
<%= render MyApp.SharedView, "key.html" %>
```
Passing empty assigns, however, work:
```elixir
<%= render MyApp.SharedView, "key.html", %{} %>
```

If passing assigns is required, then the "template not found" error message is confusing. Finding a way to render shared views without assigns required would be the optimal solution IMHO.

**Comment by josevalim** [comment]
@chrismccord we already added an extra clause to all render/2 functions in views, maybe it is worth adding another way to handle this case?

**Comment by chrismccord** [comment]
> maybe it is worth adding another way to handle this case?

Different clauses or different functions?

**Comment by josevalim** [comment]
A different clause. If we get an atom as first arg, we need to dispatch to
the view.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*
