### ISSUE TITLE
Phoenix needs stickers

### ISSUE THREAD

**Issue by jeffweiss** [phoenixframework/phoenix#792]
Can we get a large-ish version of the Phoenix logo (minus the `Phoenix Framework` text or perhaps the text smaller and below the logo)?
Then we can submit to https://www.stickermule.com/products/die-cut-stickers (or other vendor, I'm not partial)

**Comment by DevL** [comment]
:+1:

**Comment by h4cc** [comment]
:+1:

**Comment by Frost** [comment]
:+1:

**Comment by Kosmas** [comment]
:+1:

**Comment by 2kodes** [comment]
:+1:

**Comment by williamgueiros** [comment]
:+1:

**Comment by alexdaube** [comment]
![phoenix](https://cloud.githubusercontent.com/assets/8660478/7289460/91105b86-e93e-11e4-8581-3d1182e58f6c.png)

**Comment by optikfluffel** [comment]
:+1:

**Comment by Tuxified** [comment]
:+1:

**Comment by asconix** [comment]
(y)

**Comment by jeregrine** [comment]
💯

**Comment by esbanarango** [comment]
:+1:

**Comment by schaary** [comment]
:+1:

**Comment by jeffweiss** [comment]
I have requested a proof from [Sticker Mule](https://www.stickermule.com).
They claim the proof will be ready in 15 hours, 8 minutes.
![screen shot 2015-05-08 at 5 08 30 pm](https://cloud.githubusercontent.com/assets/818053/7547568/fd01e720-f5a4-11e4-9ed9-5a26d6a7ddc1.png)

**Comment by Kosmas** [comment]
:+1:

**Comment by jeffweiss** [comment]
Phoenicians, I just took a look at the online proofs from Sticker Mule, and I'm excited. We have a few more variants to evaluate too.

**Comment by asconix** [comment]
@jeffweiss do you have a sample to see online?

**Comment by jeffweiss** [comment]
Prototype stickers ordered, in production, and will be shipped to @chrismccord for final in-person approval.

Here's a preview
![r706615016_r](https://cloud.githubusercontent.com/assets/818053/7570613/3a94c530-f7c6-11e4-8c36-edf7e0b80884.png)

**Comment by optikfluffel** [comment]
![Me likey!](http://www.reactiongifs.com/wp-content/uploads/2013/08/happydog.gif)

**Comment by mjs2600** [comment]
![Shut up and take my money!](http://i1.kym-cdn.com/photos/images/original/000/264/241/9e9.gif)

**Comment by asconix** [comment]
@jeffweiss awesome, i like them a lot :) thanks for your work!

**Comment by jeffweiss** [comment]
@mjs2600 it looks like Sticker Mule will allow for selling online once we get the :+1: after @chrismccord examines in-person. They should arrive to Chris around May 20-ish. We'll see what he has to say then... :smiley:

**Comment by jeregrine** [comment]
Any way to get one of JUST the phoenix?

**Comment by jeffweiss** [comment]
@jeregrine yup. A trial of just the phoenix is already on order too.

**Comment by jeregrine** [comment]
Awesome.

**Comment by mogadget** [comment]
@jeffweiss Cool!! .. could you have it where the Phoenix Framework text is after the firebird? with burning effect?

**Comment by chrismccord** [comment]
Thanks for the enthusiasm everyone! And big thanks to @jeffweiss for the hookup! Stickers are being printed  now. If you'd like some, come to ElixirConfUS in Austin, TX Oct 1-3 :) We'll also see about making them available online somewhere

**Comment by jeffweiss** [comment]
The sticker is now [for sale at Sticker Mule](https://www.stickermule.com/marketplace/5553-phoenix-framework).

**Comment by lancehalvorsen** [comment]
That is awesome! Thanks @jeffweiss for making the magic happen. :)
