### ISSUE TITLE
Improve description of mix phoenix.gen.html

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix#801]
From IRC: 

> edmz: "Generates HTML files for a resource"
> edmz: sounds like it *only* generates html files, which in my mind sounded like "views/templates"

Maybe this should be something like "Generates controller, and HTML files for a resource"?

**Comment by chrismccord** [comment]
:+1:  PR?

**Comment by scrogson** [comment]
https://github.com/phoenixframework/phoenix/pull/802
