### ISSUE TITLE
Template and view layout incorrect when using nested --module

### ISSUE THREAD

**Issue by limhoff-r7** [phoenixframework/phoenix#804]
I am using `--module` to match the namespacing we do on our Ruby projects, but the `pheonix.new` task generators aren't handling it correctly for the `web/templates`:

# Reproduction Steps

1. `mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.11.0/phoenix_new-0.11.0.ez`
2. `mix phoenix.new elixir-metasploit-pro --module Metasploit.Pro --app metasploit_pro`
3. Install mix dependencies? [Yn] `y`
4. Install brunch.io dependencies? [Yn] `y`
5. `cd elixir-metasploit-pro`
6. `mix phoenix.server`
7. `open localhost:4000`

Actual:
Could not render "index.html" for Metasploit.Pro.PageView
![screen shot 2015-04-24 at 11 11 36 am](https://cloud.githubusercontent.com/assets/2230482/7323243/b711fa8a-ea72-11e4-9c5b-3fe006326957.png)

Expected:
Welcome to Phoenix!

# File Structure
![screen shot 2015-04-24 at 11 15 19 am](https://cloud.githubusercontent.com/assets/2230482/7323315/3aa357f4-ea73-11e4-8425-26502b1c58c1.png)

# Questions
Should I not be using `--module Metasploit.Pro` and instead just smoosh the name together to `MetasploitPro`?  In Ruby/Rails project we use a shared top-level Metasploit namespace because we own metasploit.com.

**Comment by limhoff-r7** [comment]
I should note, `rails new` also doesn't handle nested namespace well and I have to manually fix them up.

**Comment by limhoff-r7** [comment]
I renamed `web/templates/page/index.html.eex` to `web/templates/pro/page/index.html.eex` and I now get `undefined function: Metasploit.LayoutView.render/2 (module Metasploit.LayoutView is not available)`

![screen shot 2015-04-24 at 11 37 41 am](https://cloud.githubusercontent.com/assets/2230482/7323728/65d9b4d8-ea76-11e4-8d77-2fad8538b480.png)

I thought it odd that the LayoutView was being looked up under Metasploit instead of Metasploit.Pro, so I traced this to [`Phoenix.Controller.__layout/1`](https://github.com/phoenixframework/phoenix/blob/v0.11.0/lib/phoenix/controller.ex#L860-L863), which calls [`Phoenix.Naming.base_concat/2`](https://github.com/phoenixframework/phoenix/blob/v0.11.0/lib/phoenix/naming.ex#L55-L75).

`Phoenix.Naming.base_concat/2` was [removed](https://github.com/phoenixframework/phoenix/commit/55218fc37e2e651b28c0dfc82fdd5a505a57aa62#diff-fc1fd40cbd5d8ebabade4acc70cf5e77) on master after 0.11.0, so I'll try recreating the project with master to see if that fixes these issues.

**Comment by limhoff-r7** [comment]
Using 893ef92651aaa99f1e47923cb6b9341bf220176d, I get `Could not render "index.html" for Metasploit.Pro.PageView, please define a clause for render/2 or define a template at "web/templates/pro/page".`:
![screen shot 2015-04-24 at 12 19 41 pm](https://cloud.githubusercontent.com/assets/2230482/7324466/3e860048-ea7c-11e4-87b2-f0a591f57d94.png)

So, I did the template move again `web/templates/page/index.html.eex` to `web/templates/pro/page/index.html.eex` and I now get `undefined function: Metasploit.LayoutView.render/2 (module Metasploit.LayoutView is not available)`
![screen shot 2015-04-24 at 12 21 48 pm](https://cloud.githubusercontent.com/assets/2230482/7324507/a46c3df0-ea7c-11e4-8565-0eb3270b3965.png)

Then I added `namespace: "Metasploit.Pro"` to the `use Pheonix.Controller` call  in `web/web.ex`, which got

![screen shot 2015-04-24 at 12 36 54 pm](https://cloud.githubusercontent.com/assets/2230482/7324739/9e3d9de6-ea7e-11e4-8256-3e45b08e8a4f.png)

So, one more move: `web/templates/layout/application.html.eex -> web/templates/pro/layout/application.html.eex` and the welcome page works!

![screen shot 2015-04-24 at 12 38 12 pm](https://cloud.githubusercontent.com/assets/2230482/7324756/d05ddb2e-ea7e-11e4-81c4-a2098be9d9ed.png)

**Comment by limhoff-r7** [comment]
So, I have work-arounds, so I just need to know if using nested namespace for the `--module` is meant to be supported.  If it is supported, then I'll try to come up with PR to do the work-around I found correctly in `mix pheonix.new` OR if it is NOT supported, then I'll just rename the top-level module to `MetasploitPro` and I'll come up with a PR to check that `--module`'s argument does not contain a `.`.

**Comment by scrogson** [comment]
@limhoff-r7 this has been addressed in master. See the [changelog](https://github.com/phoenixframework/phoenix/blob/master/CHANGELOG.md#v0120-dev) for more details.

**Comment by josevalim** [comment]
I don't think this is fixed in master because the generator does not
generate the proper namespace calls... Or do we?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by limhoff-r7** [comment]
@scrogson, I used master when triaging myself.  I said so in https://github.com/phoenixframework/phoenix/issues/804#issuecomment-96009046, and I still needed to make changes.  Please reopen.

**Comment by limhoff-r7** [comment]
Here's a patch of the changes I had to make @scrogson 

```
commit 115173b81d00e4faccd27bd19b4089cacb8744d0
Author: Luke Imhoff <luke_imhoff@rapid7.com>
Date:   Fri Apr 24 12:41:41 2015 -0500

    Fix nested namespacing

diff --git a/web/templates/layout/application.html.eex b/web/templates/layout/application.html.eex
deleted file mode 100644
index 9a2e5af..0000000
--- a/web/templates/layout/application.html.eex
+++ /dev/null
@@ -1,36 +0,0 @@
-<!DOCTYPE html>
-<html lang="en">
-  <head>
-    <meta charset="utf-8">
-    <meta http-equiv="X-UA-Compatible" content="IE=edge">
-    <meta name="viewport" content="width=device-width, initial-scale=1">
-    <meta name="description" content="">
-    <meta name="author" content="">
-
-    <title>Hello Phoenix!</title>
-    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
-  </head>
-
-  <body>
-    <div class="container">
-      <div class="header">
-        <ul class="nav nav-pills pull-right">
-          <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
-        </ul>
-        <span class="logo"></span>
-      </div>
-
-      <p class="alert alert-info"><%= get_flash(@conn, :info) %></p>
-      <p class="alert alert-danger"><%= get_flash(@conn, :error) %></p>
-
-      <%= @inner %>
-
-      <div class="footer">
-        <p><a href="http://phoenixframework.org">phoenixframework.org</a></p>
-      </div>
-
-    </div> <!-- /container -->
-    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
-    <script>require("web/static/js/app")</script>
-  </body>
-</html>
diff --git a/web/templates/page/index.html.eex b/web/templates/page/index.html.eex
deleted file mode 100644
index e59dbbc..0000000
--- a/web/templates/page/index.html.eex
+++ /dev/null
@@ -1,34 +0,0 @@
-<div class="jumbotron">
-  <h2>Welcome to Phoenix!</h2>
-  <p class="lead">Phoenix is an Elixir Web Framework targeting full-featured, fault tolerant applications with realtime functionality.</p>
-</div>
-
-<div class="row marketing">
-  <div class="col-lg-6">
-    <h4>Resources</h4>
-    <ul>
-      <li>
-        <a href="http://hexdocs.pm/phoenix">Docs</a>
-      </li>
-      <li>
-        <a href="https://github.com/phoenixframework/phoenix">Source</a>
-      </li>
-    </ul>
-  </div>
-
-  <div class="col-lg-6">
-    <h4>Help</h4>
-    <ul>
-      <li>
-        <a href="https://github.com/phoenixframework/phoenix/issues?state=open">Issues</a>
-      </li>
-      <li>
-        <a href="irc://irc.freenode.net/elixir-lang">#elixir-lang on freenode IRC</a>
-      </li>
-      <li>
-        <a href="https://twitter.com/chris_mccord">@chris_mccord</a>
-      </li>
-    </ul>
-  </div>
-</div>
-
diff --git a/web/templates/pro/layout/application.html.eex b/web/templates/pro/layout/application.html.eex
new file mode 100644
index 0000000..9a2e5af
--- /dev/null
+++ b/web/templates/pro/layout/application.html.eex
@@ -0,0 +1,36 @@
+<!DOCTYPE html>
+<html lang="en">
+  <head>
+    <meta charset="utf-8">
+    <meta http-equiv="X-UA-Compatible" content="IE=edge">
+    <meta name="viewport" content="width=device-width, initial-scale=1">
+    <meta name="description" content="">
+    <meta name="author" content="">
+
+    <title>Hello Phoenix!</title>
+    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
+  </head>
+
+  <body>
+    <div class="container">
+      <div class="header">
+        <ul class="nav nav-pills pull-right">
+          <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
+        </ul>
+        <span class="logo"></span>
+      </div>
+
+      <p class="alert alert-info"><%= get_flash(@conn, :info) %></p>
+      <p class="alert alert-danger"><%= get_flash(@conn, :error) %></p>
+
+      <%= @inner %>
+
+      <div class="footer">
+        <p><a href="http://phoenixframework.org">phoenixframework.org</a></p>
+      </div>
+
+    </div> <!-- /container -->
+    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
+    <script>require("web/static/js/app")</script>
+  </body>
+</html>
diff --git a/web/templates/pro/page/index.html.eex b/web/templates/pro/page/index.html.eex
new file mode 100644
index 0000000..e59dbbc
--- /dev/null
+++ b/web/templates/pro/page/index.html.eex
@@ -0,0 +1,34 @@
+<div class="jumbotron">
+  <h2>Welcome to Phoenix!</h2>
+  <p class="lead">Phoenix is an Elixir Web Framework targeting full-featured, fault tolerant applications with realtime functionality.</p>
+</div>
+
+<div class="row marketing">
+  <div class="col-lg-6">
+    <h4>Resources</h4>
+    <ul>
+      <li>
+        <a href="http://hexdocs.pm/phoenix">Docs</a>
+      </li>
+      <li>
+        <a href="https://github.com/phoenixframework/phoenix">Source</a>
+      </li>
+    </ul>
+  </div>
+
+  <div class="col-lg-6">
+    <h4>Help</h4>
+    <ul>
+      <li>
+        <a href="https://github.com/phoenixframework/phoenix/issues?state=open">Issues</a>
+      </li>
+      <li>
+        <a href="irc://irc.freenode.net/elixir-lang">#elixir-lang on freenode IRC</a>
+      </li>
+      <li>
+        <a href="https://twitter.com/chris_mccord">@chris_mccord</a>
+      </li>
+    </ul>
+  </div>
+</div>
+
diff --git a/web/web.ex b/web/web.ex
index 85df63f..b398107 100644
--- a/web/web.ex
+++ b/web/web.ex
@@ -24,7 +24,7 @@ defmodule Metasploit.Pro.Web do
 
   def controller do
     quote do
-      use Phoenix.Controller
+      use Phoenix.Controller, namespace: "Metasploit.Pro"
 
       # Alias the data repository and import query/model functions
       alias Metasploit.Pro.Repo
```

**Comment by chrismccord** [comment]
The changes you needed to perform are expected for an unconventional namespace. I'm not sure if we should accommodate this for the new project generator or not. On one hand it sucks to generate a project that doesn't build by default, but having the nested hierarchy/namespace complexity in the generator is something we'll have to maintain for unconventional edge cases.

**Comment by limhoff-r7** [comment]
If you want to not support it @chrismccord that is fine.  I'll make a PR to validate `--module`'s argument and disallow `.` in the name then so that people can't do what I did and get a broken file structure then.

**Comment by josevalim** [comment]
We should support it. It is an easy fix, I am already on it. :)

**Comment by josevalim** [comment]
Btw, this was a fantastic bug report.

**Comment by limhoff-r7** [comment]
# Test Plan

## Move workaround repository aside
1. `cd ~/git/rapid7`
2. `mv elixir-metasploit-pro elixir-metasploit-pro-804`

## Update to fix commit
1. `cd ~/git/phoenixframework/phoenix`
2. `git pull`
3. `git checkout 97482df`

## Generate new project
1. `cd installer`
2. `mix phoenix.new ~/git/rapid7/elixir-metasploit-pro --app metasploit_pro  --dev --module Metasploit.Pro`
3. Install mix dependencies? [Yn] `y`
4. Install brunch.io dependencies? [Yn] `y`

## Run server
1. `cd ~/git/rapid7/elixir-metasploit-pro`
2. `mix phoenix.server`

## View Welcome
1. `open http://localhost:4000`

# Test report
Welcome page successfully displayed with no changes.
