### ISSUE TITLE
Default .gitignore should ignore secrets

### ISSUE THREAD

**Issue by limhoff-r7** [phoenixframework/phoenix#807]
`mix pheonix.new` supplies a .gitignore, but it's not ignoring `config/prod.secret.exs` by default.  Additionally, only the production database's password is considered secret, when really all environments databases shouldn't have their password in source control.  Repositories are already leaking their secret_key_base as you can see in this search: https://github.com/search?utf8=%E2%9C%93&q=filename%3Aprod.secret.exs&type=Code&ref=searchresults.

**Comment by scrogson** [comment]
@limhoff-r7 https://github.com/phoenixframework/phoenix/pull/717
