### ISSUE TITLE
Channel message considerations

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#810]
After some great discussions at ElixirConf, I'm proposing the following channel additions:

1. All clients will be expected to send a `vsn` on connect, containing the Phoenix version they are expecting to be talking to. This will be very useful later when Phoenix applications need to be migrated up to a new version, with old clients.

2. We should pass an ignore reason when the join returns `:ignore`. Today, the only change would be to return `%{reason: "unauthorized"}` when replying to the client. Later, we could consider adding overload protection and dropping client joins under certain scenarios. In these cases Phoenix would handle sending a different return reason like "timeout" or "retry", and the client would handle it exactly the same as a chan.onError with retry/expo backoff. Joe Armstrong provided some wisdom for handling overload by occasionally dropping requests when load is high. It's not something we will do now, but giving an ignore reason will let us easily extend later if we want to go this route.

3. We need to consider adding a key to the message protocol for priority/rank. MQTT refers to this as QOS  (Quality of Service). This will come in later for replays, and most likely would be a backwards compat addition, but I'm listing it here right now because I want to make sure we provide as much upfront specs for channel client implementations when we ship 1.0.

Thoughts?

**Comment by josevalim** [comment]
> We should pass an ignore reason when the join returns :ignore. Today, the only change would be to return %{reason: "unauthorized"} when replying to the client.

Actually, I was thinking about something similar. Since we have made `join` sync, we should consider allowing actual replays from it. It will happen on spotty connections because we will ensure clients can be updated on join (and the data won't be sent async later on).

> We need to consider adding a key to the message protocol for priority/rank. MQTT refers to this as QOS (Quality of Service). This will come in later for replays, and most likely would be a backwards compat addition, but I'm listing it here right now because I want to make sure we provide as much upfront specs for channel client implementations when we ship 1.0.

I don't think we need to worry about this if our current transport protocols are extensible. For example, let's just guarantee websockets sends/expects maps, then it is easy to add new keys in the future, and missing keys can get a default value in the server.

**Comment by mobileoverlord** [comment]
> All clients will be expected to send a vsn on connect, containing the Phoenix version they are expecting to be talking to.

Should this reference the phoenix version or should we reference a channel protocol version? For example, what if phoenix 0.13.x has protocol changes, 0.14.x doesn't but 0.15.x does. Technically 0.13 and 0.14 are the same and could be confusing.

**Comment by josevalim** [comment]
It should be the message protocol version. So not the Phoenix version.

**Comment by jeregrine** [comment]
Could also be a header we pass up on initialization of the websocket/long
poller.

**Comment by ericmj** [comment]
We can't send headers with XDomainRequest unfortunately.

**Comment by chrismccord** [comment]
It could just be a param. The transport can send it up however it likes as long as it makes it into the `socket.vsn` field.

**Comment by josevalim** [comment]
Yeah, 1. could be done on socket connection rather than every message.

**Comment by josevalim** [comment]
@chrismccord is this done?

**Comment by chrismccord** [comment]
Still on my todolist to finish/talk to you about how exactly we should handle vsn
