### ISSUE TITLE
Support view fragments

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#811]
Having a `yield/content_for` like feature comes up often and I have so far punted on the issue because solutions have required other processes or abusing the process dict. @danielberkompas from irc came up with a  nice solution and we've outlined it as follows:

1. We can inject a `fragment/2` catch-all clause into all views, with an impl like this:

```elixir
# injected before_compile
def fragment(name, %{conn: conn} = assigns) do
  if conn.private.phoenix_layout == __MODULE__ do
    conn.private.phoenix_view.fragment(name, assigns)
  end
end
```

And then you can use it like this in your templates:

```erb
<%= fragment(:banner, assigns) %>
```

```elixir
defmodule MyApp.MyView do
  def fragment(:banner, assigns), do: render("banner.html", assigns)
end
```

If it's a layout, it delegates to the view, if it's not, it noops by default but lets you define multiple clauses to optionally provide the fragment. I really love how simple this is. Thoughts?

**Comment by chrismccord** [comment]
If we wanted to be able to easily scope this to "per template", we could do something like:

```elixir
# injected before_compile
def fragment(name, %{conn: conn} = assigns) do
  if conn.private.phoenix_layout == __MODULE__ do
    conn.private.phoenix_view.fragment(name, conn.private.phoenix_template, assigns)
  end
end
```

And then you can use it like this in your templates:

```erb
<%= fragment(:banner, assigns) %>
...
<%= fragment(:scripts, assigns) %>
```

```elixir
defmodule MyApp.MyView do
  def fragment(:banner, _any, assigns), do: render("banner.html", assigns)
  
  def fragment(:scripts, "index.html", assigns), do: render("index_scripts.html", assigns)
 
  def fragment(:scripts, "show.html", assigns), do: render("show_scripts.html", assigns)
end
```

**Comment by chrismcg** [comment]
I'm not sure I like `fragment(:foo, assigns)` doing different things depending on which template it's rendered in. IMHO `fragment(:index_scripts)` and `fragment(:show_scripts)` are much clearer and explicit and not very much more typing. You also wouldn't have to switch to the view to see if there are multiple clauses that might be in play when looking at the template.

**Comment by josevalim** [comment]
:+1: for @chrismcg feedback.

Also, we can avoid injecting a function into views if we make it a bit more explicit. In the layout, we will call:

    fragment @conn, :my_fragment, foo: :bar

And that will invoke:

    conn.private.phoenix_view.fragment(:my_fragment, foo: :bar)

Ideally, it would be nice if we had different names to avoid confusion, like content_for/yield) in Rails, but we should likely pick different ones.

Also, I don't see why we would have different behaviour in the layout from the view. Do we even care? Maybe I have a "partial" being invoked from different places and having the same feature would be nice.

**Comment by josevalim** [comment]
Actually, it seems we are reimplementing the rendering dispatch. If I could do this in my layout:

    render @conn, "header.html", foo: :bar

It is literally the same I proposed above... the problem is that header.html would be needed on all views (the same with fragment) while in Rails I would usually do:

    render(conn, "header.html", ...) || default

Thoughts?

**Comment by chrismccord** [comment]
> Actually, it seems we are reimplementing the rendering dispatch. If I could do this in my layout:

I had this thought too, but it's not the same because we are in the context of the layout view, but we want to render the fragment from our `@inner` view. `render @conn, "header.html", foo: :bar` would be looking for "header.html" on the layout. We need to dispatch to the `@inner`.

**Comment by chrismccord** [comment]
Just so we're clear, if we follow the Rails functionality which people are asking for, content_for/yield are controller per template, and are a special case from render because they are dynamic. They may or may not be implemented downstream.

**Comment by chrismccord** [comment]
@josevalim About as close as we can get is something like this if we stay with just render:

layout:
```elixir
<%= maybe_render view_module(@conn), "banner.html" %>
```

Better/worse?

**Comment by josevalim** [comment]
@chrismccord yeah, something like that is the direction to go. Which one do you prefer: `maybe_render` or `render_if_exists`?

**Comment by chrismccord** [comment]
What about `render_existing` ? It fits well with our render functions, `render_one`, `render_many`, `render_existing` 

```erb
<%= render_existing view_module(@conn), "banner.html", assigns %>
```

**Comment by josevalim** [comment]
:+1:

**Comment by chrismccord** [comment]
Thanks for the feedback everyone. We get most of what we want, without introducing another concept which is a big win :+1: 

@josevalim should we import `view_module/2` and friends or let the user add as needed. Right now without this import/example:

    <%= render_existing view_module(@conn), "banner.html", assigns %>

users won't really recognize they can use this like a dynamic content_for

**Comment by josevalim** [comment]
> @josevalim should we import view_module/2 and friends or let the user add as needed. Right now without this import/example:

We have an import in the view block in `web/web.ex`. We should just add `view_module/2` to the list.

**Comment by umuro** [comment]
It think we need to get rid of the layout concept to make it much more clean.

I think the concept of layout is unnecessary. There are better solutions in functional programming. Can we write such a thing?
<%= tag_page do %>
      This is my page content
<% end %>

Assume tag_page is defined in the view module and it just calls tag_title in the view module. Each view module can simply override tag_page and it's other components like tag_tile.

I have been using this approach in Ruby on Rails for the last 8 years. The designs I can manage this way make you pick your hairs if done with templates. Customize side bar, customize title, customize header, customize footer, customize toolbar, customize menu, aaaarg.

**Comment by chrismccord** [comment]
We have this feature already, see:

https://github.com/phoenixframework/phoenix/blob/b48e62f0c9ecaa48b8a61a35a1c0573a9afef024/lib/phoenix/view.ex#L214-L259

Also please consult the mailing list for feature requests and discussion. Thanks!
