### ISSUE TITLE
Controller should add :phoenix_template conn assign when rendering

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#812]
Will enable #811 and provide testing tool integration point

**Comment by garbles** [comment]
Giving this a go.

**Comment by josevalim** [comment]
`phoenix_template` or `phoenix_view` and `phoenix_layout`?

**Comment by chrismccord** [comment]
All 3. We have `phoenix_view` and `phoenix_layout` today, and we can add `phoenix_template` for use within render and test helpers. So things like `assert rendered(conn, UserView, "show.html") =~ "Name:"` are possible

**Comment by josevalim** [comment]
`assert rendered(conn, UserView, "show.html") =~ "Name:"`

Please don't :D It makes no sense to test which template was invoked. We just care about the result. I would like to close this unless we come up with an actual use case as #811 likely won't need this.

**Comment by chrismccord** [comment]
> It makes no sense to test which template was invoked. We just care about the result.

You are right. As usual! :)  I see how testing the template is just coupling  your test, not giving you anything. JoséConscience™ as a Service
