### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by maxnordlund** [phoenixframework/phoenix#814]
This would be very useful to have, and [exocoveralls][1] adds support for Elixir on coveralls.io + travis. However I believe only repo owners can add this.

[1]: https://github.com/parroty/excoveralls

**Comment by chrismccord** [comment]
Do you mean for us to add exocoveralls to phoenix or? Sorry not following atm

**Comment by maxnordlund** [comment]
Yes, I think I wasn't very clear :-) Right now coveralls.io doesn't support Elixir out of the box, but exocoveralls solves that problem. However, as far as I can remember, only repo owners can add their repo to coveralls, which is why I'm asking here. See https://github.com/parroty/coverage_sample for an example.

**Comment by chrismccord** [comment]
Ah neat. I will look into this. Thanks!
