### ISSUE TITLE
Clean up websocket termination

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#815]
The documentation for terminate should be:

* `terminate({:shutdown, :leave}, state)` - when the client has explicitly left. called even when not trapping exits
* `terminate({:shutdown, :close}, state)` - when the client connection has been closed. called even when not trapping exits
* `terminate(error, state)` - when there is an error. called only when trapping exits

@chrismccord now I am wondering. what if the client asks to leave but for some reason the server does not get this message. should leave be sync? or the client knows from which channel the messages are and it can just refuse receiving them if not currently joined?

**Comment by chrismccord** [comment]
Thanks for writing this down. I had forgotten what we decided.

> or the client knows from which channel the messages are and it can just refuse receiving them if not currently joined?

This is what will happen today if you receive a message for which you aren't joined. So no problems there. 



> what if the client asks to leave but for some reason the server does not get this message. should leave be sync?

It will be sync, so the client can just `chan.leave().receive("ok", () => // gone )`

**Comment by josevalim** [comment]
Furthermore, `socket.disconnect()` should trigger leave on the server for all channels.

**Comment by josevalim** [comment]
We have decided that leave should be sync although the leaving  confirmation will be sent by the transport.
