### ISSUE TITLE
Slow resource_path method

### ISSUE THREAD

**Issue by jhlllnd** [phoenixframework/phoenix#823]
In my current project, the current time for rendering a view with 100 models takes about 8ms. When I add a simple

```<% vehicle_path(@conn, :show, vehicle) %>```

it jumps up to over 200ms.
I'm not even altering the generated html, I'm just calling the method.

In contrast, the following code does not slow down anything:

```<%= link "Show", to: "/", class: "btn btn-default btn-xs %>```

**Comment by chrismccord** [comment]
@jhlllnd If you are running in development, it is likely lack of protocol consolidation that is biting you. Please try running in prod with protocol consolidation and report back

**Comment by jhlllnd** [comment]
Thank you for the fast response :)

It goes away when running in production mode. So all is fine then :)

**Comment by josevalim** [comment]
Let's keep this open. 200ms is not acceptable even in development. Let's
see if I can speed things up a bit!

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by jhlllnd** [comment]
To be clear, its not a single call, it's inside a loop of 100 items...

**Comment by josevalim** [comment]
I have good and bad news.

* Good news: I know how to make this fast.
* Bad news: we will have to wait until Elixir v1.1.
