### ISSUE TITLE
Spec all public APIs

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#825]

**Comment by chrismccord** [comment]
Just trolling @jeregrine with the assignee, but this is something we can all take part in as we finalize things for 1.0 :)

**Comment by Tuxified** [comment]
@chrismccord sounds like something that should be enforced? like a style guide / rubocop-like check?

**Comment by chrismccord** [comment]
> sounds like something that should be enforced? like a style guide / rubocop-like check?

I'm late to the party of specs. We should promote them, but we are far from enforcing anything.

**Comment by josevalim** [comment]
I am closing this. Specs are definitely welcome but instead of having a main issue, let's all verify pull requests more closely for specs and docs actively.
