### ISSUE TITLE
Extract phoenix.js into it's own repo and npm package

### ISSUE THREAD

**Issue by garbles** [phoenixframework/phoenix#827]
Since phoenix is using npm to install brunch, would it be a good idea to move phoenix.js to its own repo/npm package? At the moment, separating the library into multiple files and setting up a JavaScript test suite seems cumbersome.

I could create a repo this week and transfer ownership to the phoenixframework org once I'm done.

**Comment by chrismccord** [comment]
We plan to extract eventually once the churn slows down, but it doesn't make sense for us to extract quite yet.

**Comment by hph** [comment]
It seems a bit weird to me to include it in the vendor folder by default. I opted to use a CDN (RawGit) instead, for now.

**Comment by casio** [comment]
+1 for factoring out the js client

Some thoughts:
* not having any unit/integration testing for a 600+ loc piece in a 1.0 release may come across a bit unsettling. adding the whole js testing machinery here might clutter this codebase on the other hand
* generally allow npm/bower/component/... & ES5 users to get started more seamlessly

Like @garbles happy to help, if there's sth I can do..

**Comment by optikfluffel** [comment]
+1 from me

**Comment by chrismccord** [comment]
> not having any unit/integration testing for a 600+ loc piece in a 1.0 release may come across a bit unsettling. 

PR's accepted for js tests. Folks, the client will be extracted  when I have time to prioritize it.  Until then, hang tight.

**Comment by bbhoss** [comment]
Subscribed. Is there anything we can do to help out? What do you have planned other than just putting this into its own project? It seems there has already been one added to npm, maybe it could be used as a base for the official version?

**Comment by chrismccord** [comment]
> Is there anything we can do to help out?

It really needs a proper test suite that stubs the websocket connection and ajax requests properly. I just haven't had the time to set this up, so help in this area would be appreciated. Thanks!

**Comment by clessg** [comment]
This would be quite useful, I agree. For now I'm using [the phoenix-js npm package](https://www.npmjs.com/package/phoenix-js) but it's currently out-of-date. Seems to work fine though.

**Comment by dropfen** [comment]
> It really needs a proper test suite that **stubs** the websocket connection and ajax requests properly. I just haven't had the time to set this up, so help in this area would be appreciated. Thanks!

Hmm, an Idea would be to host some **phoenix-socket-test-app** on a free heroku account just for testing purposes where the clients are pointing to by default.. it maybe sounds a bit weird, but why not? We could also have some kind of counter for all the tests :)
