### ISSUE TITLE
Long poller should first search for the process locally and fallback to pubsub only if configured

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#829]
The docs should mention how to enable session affinity on places like Heroku or using HAproxy.

**Comment by chrismccord** [comment]
Brining @lancehalvorsen into the loop here. Nothing to act on yet, but just to keep on eye on these developments

**Comment by lancehalvorsen** [comment]
Thanks @chrismccord, will do.

**Comment by josevalim** [comment]
In master!

**Comment by josevalim** [comment]
We always look for the process locally and then automatically fallback to pubsub.
