### ISSUE TITLE
Generate implementations of Phoenix.Param on the fly

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#832]
Today, `Phoenix.Param` is expensive because falling back to Any is expensive as it implies a code server miss (and therefore traversing the code path).

We can optimize this if we automatically generate implementation for the struct every time we reach `Phoenix.Param`. However, we should only do this if the protocol was not consolidated and currently there is no way to check this in Elixir v1.0. However, we can implement this feature in Elixir v1.1 and therefore speed up the development environment considerably with this. We would need to be careful though to not define the same module over and over again (a central dispatch would be needed).

Adding this as an issue so we don't forget this feature in the future.

Related to #823

**Comment by acconrad** [comment]
Looks like @josevalim [released 1.1.0-dev](https://github.com/elixir-lang/elixir/blob/master/CHANGELOG.md) 2 days ago, how would one go about implementing this? Branch to a 1.0.1?

**Comment by josevalim** [comment]
I have not release 1.1.0 and we cannot add this whole 1.0 is supported. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
We no longer need this since Elixir v1.2 will always consolidate.
