### ISSUE TITLE
Provide a phoenix-static buildpack

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#835]
We need a phoenix build pack that is going to compile brunch.io assets on Heroku. The phoenix-static build pack is supposed to play with the existing [Elixir buildpack](https://github.com/HashNuke/heroku-buildpack-elixir) and just add the following steps:

1. Installation and cache of node.js
2. Running `brunch --production`
3. Running `mix phoenix.digest` in the appropriate MIX_ENV to copy the files

For now, brunch can be hardcoded, but we can make it configurable in the future to support other build tools.

We would really appreciate help from developers interested in tackling and providing this build pack as a separate project!

**Comment by tsloughter** [comment]
A new Heroku CLI feature that should help with this will land today or tomorrow. I'll update when it is.

**Comment by josevalim** [comment]
:speak_no_evil:

**Comment by lstor** [comment]
I personally think using a multi-buildpack approach is better, because then we don't have to maintain the node buildpack.

I've been thinking about writing a guide on how to do this, but a sooper quick rundown is:

1. **Use `heroku-buildpack-multi` as buildpack**

    ```
    heroku buildpacks:set https://github.com/heroku/heroku-buildpack-multi
    ```
2. **Add this to `.buildpacks`**

    ```
    https://github.com/HashNuke/heroku-buildpack-elixir.git#36f2ff22d0236589256d9044091b950b7cc565d2
    https://github.com/heroku/heroku-buildpack-nodejs.git#v75
    ```
3. **Profit!**

I'm using this for [patback](http://patback-dev.herokuapp.com) (very WIP project), and it works like a charm.

**Comment by tsloughter** [comment]
You'll be able to do it without using that buildpack very soon.

**Comment by tsloughter** [comment]
The buildpack stuff has been released if you update your client. They are still working on a devcenter article:

```
$ heroku buildpacks --help
.....
Additional commands, type "heroku help COMMAND" for more details:

  buildpacks:add BUILDPACK_URL       #  add new app buildpack, inserting into list of buildpacks if neccessary
  buildpacks:clear                   #  clear all buildpacks set on the app
  buildpacks:remove [BUILDPACK_URL]  #  remove a buildpack set on the app
  buildpacks:set BUILDPACK_URL       #  set new app buildpack, overwriting into list of buildpacks if neccessary

```

**Comment by ptrckbrwn** [comment]
Awesome!! :smile: :+1:

**Comment by tsloughter** [comment]
Devcenter article: https://devcenter.heroku.com/changelog-items/653?utm_source=dlvr.it&utm_medium=twitter

**Comment by hayesgm** [comment]
As there's a few gotchas (e.g. multiple buildpacks and asset digesting), would it be good to add a "Deploying to Heroku" section to the official Phoenix guides?  This would an alternative to creating a phoenix static buildpack.

**Comment by ericmj** [comment]
We don't need a separate buildpack - just a post_compile hook in the existing buildpack, with that it should be fairly straight forward process of setting it up. Either way documenting it in the guides is a good idea.

**Comment by lancehalvorsen** [comment]
Revamping the way we handle deployment in the guides is coming up right after the current chunk of work on testing. Right now, we have this tabula rasa for Heroku deployment:
https://github.com/phoenixframework/phoenix_guides/blob/master/deployment/E_heroku.md

As always, PR's are very welcome. :)

**Comment by ericmj** [comment]
@lancehalvorsen I will contribute docs when the buildpack is ready.

**Comment by lancehalvorsen** [comment]
@ericmj, for that, you get the @josevalim -style-all-the-hearts-emoji!
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by gjaldon** [comment]
Hi all!

Just created a [phoenix static buildpack](https://github.com/gjaldon/phoenix-static-buildpack). It has configuration much like elixir buildpack. It caches node, npm modules and bower components and runs `brunch build --production` and `mix phoenix.digest`. 

I tried it out with several Heroku deploys and it seems to work fine. I also had @ericmj initially review it. I'll address any issues reported as soon as I can. Feel free to leave any feedback!

**Comment by josevalim** [comment]
This is just fantastic! Thank you @gjaldon!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by gjaldon** [comment]
My pleasure! :smile:

**Comment by sheharyarn** [comment]
@gjaldon Awesome! 😮

**Comment by gjaldon** [comment]
Thanks! :D

On Tue, Jun 23, 2015 at 3:40 AM, Sheharyar Naseer <notifications@github.com>
wrote:

> @gjaldon <https://github.com/gjaldon> Awesome! [image: 😮]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/835#issuecomment-114232676>
> .
>



-- 
Gabe Jaldon

**Comment by ulrikaugustsson** [comment]
@gjaldon I think doing something like `npm production` or something like that would be better if some one want to use gulp/webpack/whatever instead of brunch.

**Comment by gjaldon** [comment]
@ulrikaugustsson you could customize the commands being run for compiling your assets. Check it out here: `https://github.com/gjaldon/heroku-buildpack-phoenix-static#compile`

**Comment by ulrikaugustsson** [comment]
Okey, sorry! Just thought that a "sane default" would be best but documentation should give the same result. :) :+1:

**Comment by chrismccord** [comment]
I've tested this out and it worked perfectly. Thank you very much @gjaldon. We have a Heroku guide in place here
https://github.com/phoenixframework/phoenix_guides/blob/master/deployment/E_heroku.md

I think the only thing left to close this one out is to get this up on the site. // @lancehalvorsen @jeregrine

**Comment by lancehalvorsen** [comment]
Fabulous! I'm on it.

**Comment by lancehalvorsen** [comment]
Heroku Deployment Guide is now live on phoenixframework.org.

Thanks so much @gjaldon for providing the buildpack, and thanks again to @stevedomin for the guide!

**Comment by gjaldon** [comment]
My pleasure, guys! Looking forward to seeing the Heroku guide up on Phoenix Guides. :)

**Comment by matthewlehner** [comment]
Howdy folks, following along with the Heroku guide and ran into what is probably a small issue with the secret key and crypto key generation on forms, I think for CSRF stuff – detailed this in #1033 

The tooling has really come along nicely! Thanks for so much hard work with the guides, and build packs, etc. :smile_cat:

**Comment by gjaldon** [comment]
@matthewlehner I just responded to the issue you posted

**Comment by stevedomin** [comment]
@matthewlehner @gjaldon sorry about that one, was a last minute change based on some reading I had done, forgot to try it

**Comment by gjaldon** [comment]
No prob at all, @stevedomin. I'm just happy you wrote the guide :)

**Comment by gjaldon** [comment]
@chrismccord @josevalim looks like this is good to close

**Comment by josevalim** [comment]
Indeed!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
