### ISSUE TITLE
Use "clean" frontend libraries

### ISSUE THREAD

**Issue by lstor** [phoenixframework/phoenix#836]
Instead of putting all the [sass](http://www.goodreads.com/quotes/24780-hey-you-sass-that-hoopy-ford-prefect-there-s-a-frood) code in `phoenix.scss`, the Phoenix and Bootstrap CSS should be split up. Having bootstrap on its own means that you can upgrade the bootstrap version or use [bootswatch](https://bootswatch.com/) or other bootstrap themes without having to do any manual work.

Since Phoenix ships with Bootstrap CSS and Bootstrap [uses LESS](http://lesscss.org/), then perhaps a move to LESS might be worth considering as well?

**Comment by chrismccord** [comment]
We promote es6 and Sass by default, but you are free to use whatever preprocessors you'd like. We are in the  middle of discussions around the bootstrap bundle. If may be staying, it may be split up, it may be going away entire. We'll see

**Comment by lstor** [comment]
Yes, I ported my project to LESS long ago, it was just a suggestion. It wasn't the key point of the issue anyway.

I must've missed the bootstrap discussion, do you have a link to it? I couldn't find it on either mailing list.

**Comment by scrogson** [comment]
It was in IRC yesterday.

**Comment by lstor** [comment]
Ah, I see. Thanks!
