### ISSUE TITLE
mix phoenix.routes --watch

### ISSUE THREAD

**Issue by danielberkompas** [phoenixframework/phoenix#837]
I recently put together a little tool to help me learn Phoenix's routing system:

http://phoenixroutes.herokuapp.com/

It would be nice to see this functionality built-in to Phoenix, and I think the best way to do that might be to add a `--watch` option to the `mix phoenix.routes` task. The task would then loop, updating its output every time `router.ex` is changed. Rather than firing up my tool above, I could then just run `mix phoenix.routes --watch` in a terminal window and use my preferred editor to make my changes.

**Comment by josevalim** [comment]
This made me smile, thank you! The biggest issue with adding this feature to Phoenix right now is that it would add a dependency to `fs` and it requires C extensions and we want to avoid those as a Phoenix requirement.

The second point is that I don't think the console is the best place to reload this stuff, honestly. But it could be really nice as part of the browser, as you did. Maybe we could add it as phoenix_live_reloader extension? Maybe a `/phoenix/routes` route in there?

**Comment by danielberkompas** [comment]
This could work as a live_reload extension, but it has a few drawbacks in that form. 

For example, would the page _actually change_ your router? If so, developers might prefer to use their own editor to do that rather than a web-based one. If not, you'd have to copy/paste between your editor and the web editor, which might feel weird when you're changing something on your local filesystem.

That's why I suggested a console `--watch` option. It's not as cool, but it might fit more elegantly into a development workflow. If you don't want FS dependencies in Phoenix by default, maybe the live version of the task could be a separate hex package that users could depend on if they wish?

**Comment by danielberkompas** [comment]
**Edit**: I think I misunderstood what you're saying. This _would_ work quite well as a live reload extension if the editor part was dropped completely. /phoenix/routes would just show the current output of `mix phoenix.routes`, much like `/rails/routes` does for Rails in Rails 4.

**Comment by josevalim** [comment]
Yes, and if you save the routes file, we will automatically reload the
routes. We could even highlight the new entries.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by chrismccord** [comment]
@danielberkompas this is really neat! Please open an issue over at phoenixframework/phoenix_live_reload and we can discuss potentially adding this as a feature.

**Comment by danielberkompas** [comment]
@chrismccord @josevalim Done: https://github.com/phoenixframework/phoenix_live_reload/issues/10
