### ISSUE TITLE
Up and running tutorial does unexpected things and frustrates first contact users

### ISSUE THREAD

**Issue by COLABORATI** [phoenixframework/phoenix#842]
Hi, the first contact with this framework unfortunately leads to frustration, because the up and running tutorial does not work as expected. I will try to describe.

First the sentence 

 Note: If we don't prepend a path to our application name, Phoenix will generate our new application inside of the Phoenix repo itself. That will work, but if we want our application to be in its own repo, we need to generate our application outside of Phoenix.

makes no sense, as there is no repo anywhere. Irritation on first step. Also the sentence seems to be plain wrong, because in fact I just can type 

 mix phoenix.new hello_phoenix

and it creates a project just fine. This also seems to be indicated by the sentence above this sentence. 

Then, following the tutorial, instead of starting the phoenix server I get this error:

  xxx@laptop ~/code/elixir/hello_phoenix> mix phoenix.server
Could not find hex, which is needed to build dependency :phoenix
Shall I install hex? [Yn] y

Ok, wtf is this. Why is this happening? what should I do? I answer yes and it goes on:

2015-05-03 18:02:00 URL:https://s3.amazonaws.com/s3.hex.pm/installs/1.0.0/hex.ez [257739/257739] -> "/home/xxx/.mix/archives/hex.ez" [1]
* creating /home/xxx/.mix/archives/hex.ez
Unchecked dependencies for environment dev:
* phoenix_live_reload (Hex package)
  the dependency is not available, run `mix deps.get`
* cowboy (Hex package)
  the dependency is not available, run `mix deps.get`
* phoenix (Hex package)
  the dependency is not available, run `mix deps.get`
* postgrex (Hex package)
  the dependency is not available, run `mix deps.get`
* phoenix_ecto (Hex package)
  the dependency is not available, run `mix deps.get`
** (Mix) Can't continue due to errors on dependencies

Hmm, so here I have to leave the tutorial path and try to figure out what happened and why the first step goes wrong. I did not learn much about phoenix right now and do not feel like I can debug this. But OK, as it says to do so, I just run mix deps.get, which seems to work fine, so I do not paste the output. Then again I try to mix phoenix.server and get this:

 xxx@laptop ~/code/elixir/hello_phoenix> mix phoenix.server
Could not find rebar, which is needed to build dependency :fs
I can install a local copy which is just used by mix
Shall I install rebar? [Yn] y

Rebar? Why isn this mentioned in the tutorial? Do I need it? Why? What is it? Ok, I just press Y and lots of output follows and it seems to work then and the local server is available as expected. 

However, I am frustrated at this point because there happened so many unexpected things and I have no clue if I am still on the right track or if everything is broken now - it is just the up and running tutorial, a place where unexpected things make me feel unhappy.

Yes, I make it a drama a little bit, but I believe the first contact should be less irritating. I did not find the tutorial code in any repo, so I am whining here instead of just correcting things, sorry.

**Comment by josevalim** [comment]
@COLABORATI Thanks for channeling your frustations. We agree this needs to be better and I have already sent a pull request (linked above) that addresses the points you complained.

Your feedback is particularly valuable because it seems you have done just a fresh Elixir install and often we forget many users will be starting from this exact scenario. The pull request removes the notes you have said that are out of date and adds new notes with the gotchas you have mentioned.

Keep in mind Phoenix is in active development (the installer for example is very recent) so the guides may be outdated in some places.

**Comment by lstor** [comment]
I shared your frustration the first time I tried out Phoenix I had a problem that took me three days to figure out, with practically no help from the community. As you say, trying to debug a problem in a system with *a lot* of moving parts where you don't know anything about half of them is... challenging.

The Phoenix guides are largely due to the heroic effort of @lancehalvorsen. You can contribute to it at [lancehalvorsen/phoenix-guides](https://github.com/lancehalvorsen/phoenix-guides). They welcome pull requests, and others will surely share your experience. Since Phoenix is still in pre-1.0, I have the impression they are focusing on development and let the documentation suffer for it. Hopefully it will get better once it hits 1.0 and stabilizes a little =)

I get the impression that most of your woes are due to being new to the Elixir and Erlang ecosystem. That is fine, of course, and I think it provides a valuable insight that the Phoenix guides can benefit from.

Finally: `hex` is the Elixir package manager and -repository. `rebar` is an Erlang build tool.

**Comment by chrismccord** [comment]
@COLABORATI thanks for the feedback. The new user onboard process is one of the highest priorities for us. Understand that *months* of hard work has gone into the guides, getting started process, etc, but since we only have a handful of folks and things have changed fast, sometimes our guides have lagged. 


> I had a problem that took me three days to figure out, with practically no help from the community

@lstor Did you try IRC? I practically live on there to help newcomers with elixir and phoenix issues (as do many others), so if we weren't able to reach you, where were seeking help?

> I have the impression they are focusing on development and let the documentation suffer for it.

We are focusing on both at once, but sometimes things fall out of sink. Let me be clear that this is a top priority for us

**Comment by lancehalvorsen** [comment]
@COLABORATI I echo what both @josevalim and @chrismccord have said above.

Just to let you know, changes to the Up and Running Guide which address your frustrations are in both the guides repository, and on http://www.phoenixframework.org/.

**Comment by lstor** [comment]
@chrismccord Thanks, I'll keep that in mind and make sure to try irc next time :)

**Comment by lancehalvorsen** [comment]
I totally forgot; thanks @lstor for your kind words. :)

**Comment by chrismccord** [comment]
@COLABORATI I hope we addressed your concerns and keep you around as a happy Elixir and Phoenix user.

**Comment by COLABORATI** [comment]
Thanjks for your quick corrections, seems to work now like described. I will follow the flight of the phoenix :)

**Comment by lancehalvorsen** [comment]
@COLABORATI glad that we could address your issues and keep you interested in Phoenix. :)

Also, for anybody following this thread, the guides have moved into the phoenixframework github organization. You can find them here:
https://github.com/phoenixframework/phoenix-guides

**Comment by tnt** [comment]
The [channel example](http://www.phoenixframework.org/v0.13.1/docs/channels) seemingly don't work at all with 0.13.1.

**Comment by sevenseacat** [comment]
@tnt which part of it doesn't work? Do you have a specific error at from a part of the example that might pinpoint getting it fixed?

**Comment by lancehalvorsen** [comment]
@tnt, I second what @sevenseacat said. Please give us as much detail as you can about what's not working so we can get it sorted out for everybody's benefit. 

Meanwhile, I'll set up a new project myself to see what I can see.

**Comment by tnt** [comment]
Sorry, I suppose this to be easily reproducable. 

    $ mix phoenix.new testapp
    ...

Now you have a `mix.lock` with the following content:

    %{"cowboy": {:hex, :cowboy, "1.0.0"},
      "cowlib": {:hex, :cowlib, "1.0.1"},
      "decimal": {:hex, :decimal, "1.1.0"},
      "ecto": {:hex, :ecto, "0.12.0-rc"},
      "fs": {:hex, :fs, "0.9.2"},
      "phoenix": {:hex, :phoenix, "0.13.1"},
      "phoenix_ecto": {:hex, :phoenix_ecto, "0.4.0"},
      "phoenix_html": {:hex, :phoenix_html, "1.2.1"},
      "phoenix_live_reload": {:hex, :phoenix_live_reload, "0.4.1"},
      "plug": {:hex, :plug, "0.13.0"},
      "poison": {:hex, :poison, "1.4.0"},
      "poolboy": {:hex, :poolboy, "1.5.1"},
      "postgrex": {:hex, :postgrex, "0.8.2"},
      "ranch": {:hex, :ranch, "1.0.0"}}

When you then apply the code from the basic example in http://www.phoenixframework.org/v0.13.1/docs/channels (basic versions of router, channel, and JS-code) and look in the browsers console, the "Welcome to Phoenix Chat!" message does not show up. 

When you then  change the deps in mix.exs to:

    defp deps do
      [
          {:plug,                 "0.12.2"},
          {:phoenix,              "0.13.0"},
          {:phoenix_ecto,         "~> 0.4"},
          {:postgrex,             ">= 0.0.0"},
          {:phoenix_html,         "~> 1.0"},
          {:phoenix_live_reload,  "0.4.0", only: :dev},
          {:cowboy,               "~> 1.0"}
      ]
    end

(`plug` and `phoenix` versions changed) It works. Maybe this is just a JS issue...

**Comment by chrismccord** [comment]
@tnt : can you verify the version of your installed `phoenix.new` archive?

    $ mix phoenix.new -v
    Phoenix v0.13.1

My bet is you have `0.13.0`, which is causing the problem. Phoenix 0.13.1 was released and requires an updated `phoenix.js` channels client.  The 0.13.0 mix archive does includes the phoenix dep as `~> 0.13`, so you probably grabbed the bumped phoenix version, but haven't updated your client. Sorry for this issue, but the easiest fix is updating your phoenix.js and then updating your installed mix archive with 0.13.1 to avoid for new projects:

https://gist.github.com/chrismccord/4a62780056b08c60542d

**Comment by tnt** [comment]
@chrismccord Right! It's been `0.13.0`. After `mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.13.1/phoenix_new-0.13.1.ez` resp. updating `phoenix.js` it works. Thank you for your time.

**Comment by josevalim** [comment]
I am glad this is figured out! :heart:

**Comment by skullncode** [comment]
Unable to get past this error when trying the "Up and running" tutorial;When finally running "mix phoenix.server" I get the following error:

```
=INFO REPORT==== 22-Jan-2016::08:59:44 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application hello_phoenix: HelloPhoenix.start(:normal, []) returned an error: shutdown: failed to start child: HelloPhoenix.Repo
    ** (EXIT) shutdown: failed to start child: Ecto.Adapters.Postgres
        ** (EXIT) an exception was raised:
            ** (RuntimeError) could not find Ecto.Adapters.Postgres.Connection.

Please verify you have added :postgrex as a dependency:

    {:postgrex, ">= 0.0.0"}

And remember to recompile Ecto afterwards by cleaning the current build:

    mix deps.clean ecto

                (ecto) lib/ecto/adapters/sql.ex:420: Ecto.Adapters.SQL.start_link/4
                (stdlib) supervisor.erl:343: :supervisor.do_start_child/2
                (stdlib) supervisor.erl:326: :supervisor.start_children/3
                (stdlib) supervisor.erl:292: :supervisor.init_children/2
                (stdlib) gen_server.erl:328: :gen_server.init_it/6
                (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
After running "mix deps.clean ecto" I end up having to run "mix deps.get" again, and then encounter the exact same error after running "mix phoenix.server" again. First time Phoenix user here, how do I get past this error?

Thanks a ton in advance! @josevalim @chrismccord

**Comment by chrismccord** [comment]
Please see the workaround here:
https://github.com/phoenixframework/phoenix/issues/1489#issuecomment-173771374

This will be fixed asap tomorrow. Thanks!

**Comment by TiSer** [comment]
I'm trying to do tutorial at http://phoenix.thefirehoseproject.com/1.html
After `$ mix do deps.get, compile` I have an error:

> $mix do deps.get, compile 
> Could not find Hex, which is needed to build dependency :cowboy
> Shall I install Hex? (if running non-interactively, use: "mix local.hex --force") [Yn] Y
> ** (MatchError) no match of right hand side value: {:error, {:ssl, {'no such file or directory', 'ssl.app'}}}

**Comment by wojtekmach** [comment]
@TiSer see this issue: https://github.com/phoenixframework/phoenix/issues/1949, in particular this SO answer might help you: http://stackoverflow.com/questions/35170911/mix-deps-get-failed-seems-missing-ssl/35173096#35173096

**Comment by serhiit-iRonin** [comment]
@wojtekmach Where I should place this `KERL_CONFIGURE_OPTIONS`?

**Comment by TiSer** [comment]
@wojtekmach Where I should place this `KERL_CONFIGURE_OPTIONS`?

**Comment by lukewatts** [comment]
I'm also trying Phoenix out for the first time. I just installed Elixir yesterday so it's a completely fresh install.

Phoenix v 1.2.1
Windows 10

For me the `mix deps.get` failed on installation and `npm install && node node_modules/brunch/bin/brunch build` failed also.

Then I ran both commands after and they seemed to work fine.

Then I ran `mix ecto.create` and it said could not find rebar. I said to install it and that failed.

```
C:\projects\elixir\hello_phoenix>mix deps.compile ranch
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
** (Mix) Could not compile dependency :ranch, "escript.exe "c:/Users/LukeWatts85/.mix/rebar3" bare compile --paths "c:/projects/elixir/hello_phoenix/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile ranch", update it with "mix deps.update ranch" or clean it with "mix deps.clean ranch"
```

`mix deps.compile ranch` simply causes this to repeat.

Disappointed but I want to try Phoenix so if someone has ideas I'll gladly try them!

**Comment by josevalim** [comment]
Sorry to hear @lukewatts. Can you please include your Elixir version? This is likely an Elixir issue rather then Phoenix. Also, can you please try running `DEBUG=1 mix deps.compile ranch`? What does it say?

**Comment by jwipeout** [comment]
I was excited to start my very first phoenix project. Ran into the same error that luke ran into. 

```
➜  phoenix cd twixler
➜  twixler mix ecto.create

11:40:07.893 [info]  Compiling file system watcher for Mac...

11:40:12.172 [info]  Done.
==> file_system
Compiling 6 files (.ex)
Generated file_system app
==> connection
Compiling 1 file (.ex)
Generated connection app
==> gettext
Compiling 1 file (.yrl)
Compiling 1 file (.erl)
Compiling 20 files (.ex)
warning: String.strip/1 is deprecated, use String.trim/1
  lib/gettext/po/parser.ex:47

warning: String.strip/1 is deprecated, use String.trim/1
  lib/gettext/po/parser.ex:55

warning: String.lstrip/1 is deprecated, use String.trim_leading/1
  lib/gettext/po/parser.ex:65

warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
  lib/gettext/po/tokenizer.ex:147

Generated gettext app
==> twixler
Could not find "rebar3", which is needed to build dependency :ranch
I can install a local copy which is just used by Mix
Shall I install rebar3? (if running non-interactively, use "mix local.rebar --force") [Yn]
```

Still very excited to to get up and running :) 

I am using
**Phoenix v1.3.0**
**Elixir 1.5.1**
