### ISSUE TITLE
Website: search broken

### ISSUE THREAD

**Issue by COLABORATI** [phoenixframework/phoenix#843]
The search box on the website seems to be broken. I input a word and press enter and nothing happens. Also clicking the looking glass symbol does not do anything.

**Comment by josevalim** [comment]
It is working here but you need to wait it show a box with the options (i.e. it doesn't send you to a search page).

**Comment by COLABORATI** [comment]
hmm, I input e.g. the word "security", but nothing happens, I wait but no box visible. When I press enter, also nothing happens. I checked with Chromium and Firefox on Ubuntu 14.04, adblockers disabled.

**Comment by chrismccord** [comment]
@COLABORATI sounds an issue on readme.io's end (where we host the guides). In the future, please direct guides/website issues to https://github.com/phoenixframework/phoenix-guides  thanks!
