### ISSUE TITLE
server-side session expiry hook

### ISSUE THREAD

**Issue by jeffweiss** [phoenixframework/phoenix#845]
I am using ETS sessions to store data server-side. The situation, as I understand it, is as follows:
 * Browser cookie stores the session id
 * Session map stored in ETS keyed off of session id (retrieved from browser cookie)
 * If browser cookie expires and is deleted, ETS entry remains, leading to slow memory leak

My particular situation is compounded because I am creating an `:eldap` connection for each user session, with its pid stored in the ETS session map; however, when the session expires, I don't know that I can clean up that process in addition to the ETS session entry.

I would like to be able to register session expiration hook(s) that will be executed either 
 * just prior to ETS session table removal, with the session key (and I can fetch the current session map from the ETS table w/ the key), or
 * undefined about whether before/after ETS session table removal, but with both the session id and the session map (as it existed just prior to removal)

That will allow me to clean up any resources I've allocated for the session.

I'm open to other possible solutions (something like poolboy w/ timeout/expiration?).

I don't have an urgent need here because I'll likely deploy to Heroku where daily dyno restarts will prevent this from becoming a serious problem.

It's possible that elixir-lang/plug is a more appropriate place for this issue.

[This StackOverflow thread](http://stackoverflow.com/questions/1701049/erlang-session-management-and-timeout) has ideas about how portions of this may be implemented.

**Comment by josevalim** [comment]
Well, we can't ever know that a session was expired, can we? For example, if you want the user session can be valid for a whole year, until he decides to sign out. At least, in this scenario, we would know to delete it. However, if he deletes the cookie in his machine, we would never know that it will never be used again.

So I don't think we can ever have a session expiry hook. The best we can do is to store last access dates on ETS and you can traverse it deleting things based on a timestamp.

In fact, this issue has actually convinced me the session based ETS is a bad idea... :)

**Comment by josevalim** [comment]
To clarify, what I have in mind is similar to what was proposed. Except you will have a single process, that goes through ETS every 1 minute to clear up stale entries. Another alternative is to have the eldap processes shutting down after x minutes of inactivity, detecting it, and then removing the relevant entry from the table.

I would recommend you to fork Plug.Session.ETS and add your logic. I am pretty sure we will remove it from Plug. :)

**Comment by jeffweiss** [comment]
I think that if we have an expiry of 1 year, then we have a timer fire after a year (or whatever `max_age` is), even if the user decides to delete her cookie and we don't know about it. I have never tried to fire a timer event after 1 year though. :) 

I don't know what to do if `max_age` isn't set. :)

That definitely leaves us vulnerable to a DOS attack though: Create a session; delete the cookie; repeat.

**Comment by jeffweiss** [comment]
As I said above though, I'm not super worried about it because Heroku will "fix" it for me. :smiley:

**Comment by josevalim** [comment]
@jeffweiss yes! I was mostly arguing why this mechanism does not make sense for Phoenix itself. If you have some special constraints, a limited amount of users, etc, then a simple solution as proposed becomes viable. But supporting such mechanism out of the box is asking for trouble. :)

**Comment by Immortalin** [comment]
@josevalim Rails have `:expire_after` for sessions.

**Comment by blackham** [comment]
I can't understand why ETS sessions is a bad idea just to know if a user is currently logged in or not. Call me old fashioned, but when talking security the idea of storing anything more than a session ID on the client is like the bank teller asking how much money I have in the bank before I make a withdraw. I don't trust the client any more than the bank trusts me. 

ETS is just a cache so I don't have to do an expensive DB hit for every sensitive HTTP request. It's easier to setup than Redis. It doesn't require another TCP connection to access Redis (or Memcache). It will scale to the needs of most use cases (sorry Google or Amazon, you'll need to write your own). It will make it easier to use Cookies w/ HttpOnly vs the less than ideal localStorage. The only downside is having to clean out old sessions. 

Hook the logout function to:
1) Set the session cookie expire time to 1 second (aka delete the cookie)
`put_resp_cookie(cookie_sid, %{deleted: true}, sign: true, max_age: 1)`
2) Delete the ETS entry

Hook any user triggered event (post/get) from the client to update the timestamp in ETS. (optional)

Last, write a function to search for and delete any ETS entry that has an access time older than X minutes. Toss that into cron and call it a day. (or a GenServer)

And for the nice lady that sits in front of the web page for 24 hours without clicking anything, Que Pena. She has to log back after her ETS cookie expires. Or, if you don't "touch" the optional timestamps then delete all sessions after 7 days. Now she can stare for a week!

I'm not storing anything critical or long term in ETS. It's volatile memory. Fast, but not permanent. I just want to know if I can trust the session or not. Maybe call it Plug.AuthSession to only use it for authentication verification. Store the user ID, timestamp, IP addr, etc. Add some plugs to make it easy to block the session if the IP address suddenly changed, clean up old ETS entries automagically, delete recently removed accounts, etc. 

Am I missing something? 

Plug + Phx is flipping awesome! Thanks. I hope I don't sound like I'm bitching. I seriously want to know if I'm missing something. ETS sessions seem too good to be true to verify users.  (JWT, localStorage, and/or normal cookies for stuff like user_name, favorite color, last viewed item, etc)

**Comment by chrismccord** [comment]
ETS is node-local, so without sticky sessions it will not work going multimode. Your best option is used the encrypted options with the cookie session

**Comment by blackham** [comment]
I understand ETS sessions need to be sticky. And that's not a hard problem to fix if load ever grew that big. But for small to mid-sized environments, if every employee connected at the same time, I'd still only use about 15% of the total load. Elixir is fast!

On the reverse side, it's highly unlikely going stateless with an an encrypted cookie would run into any issues either. I guess I can see why that would be more appealing in most use cases. 

However, given that security is more a concern than being able to scale to millions of simultaneous users, I'll keep session state on the server with ETS. I'll reply to the thread in a couple years if I have any regrets picking ETS.
