### ISSUE TITLE
Provide better error messages for when the connection is not assigned in tests

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#847]
http://stackoverflow.com/questions/30063819/runtimeerror-expected-connection-to-have-a-response

**Comment by parkerl** [comment]
@josevalim can I be any help on this one or do you have it covered?

**Comment by josevalim** [comment]
@parkerl Oh, please go ahead! The idea is to store something when we create the connection and remove it when the user calls get/post/etc. Then, in response, if we see the flag is still there, we can give a really nice example of what should be done!

**Comment by josevalim** [comment]
Ping? :)

**Comment by josevalim** [comment]
Ok, I am tackling this.

**Comment by parkerl** [comment]
@josevalim sorry I did not see you ping. Moved offices this week...just a wee bit of chaos.

**Comment by josevalim** [comment]
No worries! Thanks for all the help anyway! :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*
