### ISSUE TITLE
terminate/2 isn't called in a Channel without trapping exits when using Chrome

### ISSUE THREAD

**Issue by adamkittelson** [phoenixframework/phoenix#848]
It is called when I trap exits. Also it is called when I don't trap exits if I'm using Safari.

It looks like in Phoenix.Endpoint.CowboyWebsocket.websocket_terminate/3 the reason when chrome navigates away from a page with a WS connection is `{:remote, 1001, ""}` but in Safari it is `{:error, :closed}`

**Comment by adamkittelson** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent might be useful if there are other chrome exits that need handling

**Comment by chrismccord** [comment]
@adamkittelson Please verify fixed on master. Thanks for reporting

**Comment by adamkittelson** [comment]
Fix verified, thanks Chris!
