### ISSUE TITLE
Consider shipping errors_on with ModelCase

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#853]
It will be convenient and it will teach folks how to add custom functions to their test cases.

**Comment by chrismccord** [comment]
+1

**Comment by gjaldon** [comment]
Hi guys. I'd love to take this on. What should `errors_on` do? Check that a specific error is found in the Ecto changeset after running a validation?

**Comment by josevalim** [comment]
The code is literally:

```elixir
def errors_on(model, data) do
  model.__struct__.changeset(model, data).errors
end
```

We need to include it in the model case and guarantee it is imported. We should also include some docs with examples, for example:

      assert {:password, "is unsafe"} in errors_on(%User{}, password: "password")

**Comment by danielberkompas** [comment]
+1. Since @josevalim pointed this out to me, I've been adding it to ModelCase manually on all my Phoenix projects.

**Comment by gjaldon** [comment]
This issue can be closed now @josevalim @chrismccord :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
