### ISSUE TITLE
Multipart/form-data without file rises a MatchError

### ISSUE THREAD

**Issue by jonhkr** [phoenixframework/phoenix#859]
Hi,
I'm sending a post request with `Content-Type: multipart/form-data` with some parameters but no file and I receive the following error:
```
Request: POST /api/v1/transactions
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: false
        (cowboy) src/cowboy_req.erl:734: :cowboy_req.init_multipart/1
        (cowboy) src/cowboy_req.erl:672: :cowboy_req.part/2
        (plug) lib/plug/adapters/cowboy/conn.ex:70: Plug.Adapters.Cowboy.Conn.parse_req_multipart/3
        (plug) lib/plug/parsers/multipart.ex:11: Plug.Parsers.MULTIPART.parse/5
        (plug) lib/plug/parsers.ex:187: Plug.Parsers.reduce/6
        (api) lib/api/endpoint.ex:1: Api.Endpoint.phoenix_endpoint_pipeline/1
        (api) lib/plug/debugger.ex:90: Api.Endpoint."call (overridable 3)"/2
        (api) lib/phoenix/endpoint/render_errors.ex:34: Api.Endpoint.call/2
```

If I send a file with the same content type everything works fine.
I know `multipart/form-data` is intended to be used with files, but I should not receive a `500` status code if I send a post without a file.

**Comment by josevalim** [comment]
I don't think it is related to the lack of a file. Can you provide more information about the form you are sending and which browser? The error looks like there is no content-type header or it is poorly formatted (for example, no boundary).

**Comment by jonhkr** [comment]
I'm using REST Console chrome extension to make the requests, here are the request headers:

```
POST /api/v1/transactions HTTP/1.1
Host: localhost:4000
Connection: keep-alive
Content-Length: 7
Origin: chrome-extension://cokgbflfommojglbmbpenpphppikmonn
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
Content-Type: multipart/form-data
Accept: */*
DNT: 1
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```

And the request payload:

```
test=hi
```

**Comment by josevalim** [comment]
So the payload you are sending is not multipart/form-data is it? It is x-www-form-urlencoded. More info here: http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4

**Comment by jonhkr** [comment]
Yeah, I've just checked that the Chrome extension I'm using is not sending the request correctly. Either way, I think the server should not send a `500` response in this case, since it's the client that is sending a malformed request the server should respond with a `4xx` status code.

**Comment by josevalim** [comment]
Yes, agreed. Thanks for the report @jonhkr !

**Comment by josevalim** [comment]
I have moved this to plug (see linked issue above).

**Comment by jonhkr** [comment]
Thank you :+1:
