### ISSUE TITLE
Brunch installation fails but failure not reported

### ISSUE THREAD

**Issue by larshesel** [phoenixframework/phoenix#862]
When creating a new phoenix project including brunch.io dependencies, everything looks good, but in fact the brunch.io dependencies failed (the reason is most likely due to my age-old node and npm installations). The problem is that the error is never shown when running `mix phoenix.new`, which seems to be because the status code from npm is not returned (and checked) from :os.cmd/1: https://github.com/phoenixframework/phoenix/blob/master/installer/lib/phoenix_new.ex#L313

From my npm-debug.log:

```shell
27129 error brunch@1.8.2 postinstall: `node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"`
27129 error Exit status 127
27130 error Failed at the brunch@1.8.2 postinstall script.
27130 error This is most likely a problem with the brunch package,
27130 error not with npm itself.
27130 error Tell the author that this fails on your system:
27130 error     node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"
27130 error You can get their info via:
27130 error     npm owner ls brunch
27130 error There is likely additional logging output above.
27131 error System Linux 3.16.0-4-amd64
27132 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
27133 error cwd /home/lhc/dev/temp/hellophoenix
27134 error node -v v0.10.29
27135 error npm -v 1.4.21
27136 error code ELIFECYCLE
27137 verbose exit [ 1, true ]
```

My `mix phoenix.new hellophoenix` output:

```shell
$ mix phoenix.new hellophoenix
* creating hellophoenix/config/config.exs
* creating hellophoenix/config/dev.exs
* creating hellophoenix/config/prod.exs
...
* creating hellophoenix/priv/static/images/phoenix.png

Install mix dependencies? [Yn] 
* running mix deps.get

Install brunch.io dependencies? [Yn] 
* running npm install

We are all set! Run your Phoenix application:

    $ cd hellophoenix
    $ mix phoenix.server

You can also run it inside IEx (Interactive Elixir) as:

    $ iex -S mix phoenix.server
```

**Comment by chrismccord** [comment]
I don't think we can do much here if node is not respecting the status code. Can you jump up to node >= 0.12? We should list the min node requirements (if we already don't")

**Comment by josevalim** [comment]
Node may be respecting the status code. The problem is that we ignore it because we can't retrieve it with `:os.cmd` and `Mix.shell.cmd` only supports quiet mode on v1.1. However, I am not sure if we should really worry about this. If node fails, it means the next brunch command will fail anyway and then you need to debug it, regardless of the info we show now.

Thoughts?

**Comment by larshesel** [comment]
@chrismccord I did update my node installation afterwards and then I don't get the error (live_reload still doesn't work for some reason, but I haven't investigated why yet).

@josevalim I'm not sure if I agree. I think the right thing, although I understand it might not be realistic to implement, would be to fail immediately. It's really not easy to understand later why brunch fails - especially for people like me who don't really know nothing about node.

But as Chris mentioned a workaround could be to list the min node requirements. Another option might be to check the available versions of `node` and `npm`?

**Comment by chrismccord** [comment]
> But as Chris mentioned a workaround could be to list the min node requirements. Another option might be to check the available versions of node and npm

I think we should just document on the guides the minimum node requirement and go from there. Checking versions and what not is going to couple us tightly to brunch, where right now it's quite swappable and other node watchers may not be 0.12 specific. Thanks for the report and hopefully this does enough to point folks in the right direction

**Comment by lancehalvorsen** [comment]
For the record, I just merged a PR from @chrismccord to document the minimum node version, and I made the corresponding change on phoenixframework.org.

**Comment by larshesel** [comment]
Awesome!
