### ISSUE TITLE
static_path not used in web/static/css/app.scss

### ISSUE THREAD

**Issue by limhoff-r7** [phoenixframework/phoenix#864]
I [figured out](https://gist.github.com/limhoff-r7/79be3e78a5f1d39edae7) with @chrismccord's help on #elixir-lang how to host phoenix under the path /phoenix behind nginx, but while preparing the PR for our project, I realized the phoenix.png logo wasn't loading.  Looking at the Network panel in chrome, I saw that it was trying to load from `https://localhost:<nginx-port>/images/phoenix.png` instead of the expected `https://localhost:<nginx-port>/phoenix/images/phoenix.png`.  I tracked this down to `web/static/css/app.scss` hard-coding

```scss
.logo {
  background-image: url("/images/phoenix.png")
}
```

This means that setting the url.path in config.exs does not influence the url for app.scss assets.

# Reproduction Steps
1. Host phoenix at a non-root url (`/phoenix`)
2. Set config.exs url.path 
```
config :my_app, MyApp.Endpoint,
  url: [host: "localhost", path: "/phoenix"],
```
3. `open http://localhost/phoenix`

## Actual
phoenix.png does not load because it's url is `/images/phoenix.png`.

## Expected
phoenix.png loads from `/phoenix/images/phoenix.png`.  In general, the url.path (with the `static_path` helper or something similar) should used to access assets in app.scss.

## Workaround
1. Change `web/static/css/app.scss` `url` calls so they are prefixed with config.url.path from config.exs.

**Comment by josevalim** [comment]
Just to be clear: Is it not working because the static plug cannot find the file or because we are not using the static_path function?

**Comment by josevalim** [comment]
Doh, sorry. The answer to my question is in the title. Thank you!

**Comment by josevalim** [comment]
I am going to mark this as won't fix for now. Use SASS variables or some SASS helper to clean things up.

**Comment by chrismccord** [comment]
@scrogson Any interest in putting a sass helper together that we can ship with?

**Comment by scrogson** [comment]
I'll look into it.

**Comment by leiyangyou** [comment]
Any progress update on this?

**Comment by leiyangyou** [comment]
Looks like we may have to create a brunch plugin to do the digest part

**Comment by tispratik** [comment]
Any suggestions on the sass helper? I am running into the same issue wherein i cannot use 
constructs like `background-image: url("<%= static_path(@conn, "/images/background.png") %>");` in the app.scss file.

**Comment by leiyangyou** [comment]
looks like on phoenix on master replaces url in compiled css file on digest

**Comment by tispratik** [comment]
Does anyone know of a work around for this? Thanks.

**Comment by chrismccord** [comment]
@tispratik The `mix phoenix.digest` task will replace the asset paths with your configured static_path, so it has been solved for a while now. Check the Phoenix.Digester docs
