### ISSUE TITLE
api.phoenixframework.org returning "Server Not Found"

### ISSUE THREAD

**Issue by neildaemond** [phoenixframework/phoenix#873]
According to 'http://www.phoenixframework.org/v0.13.0/docs/resources', the official documentation is supposed to reside at api.phoenixframework.org

I'm getting "Server Not Found" when visiting that url

**Comment by kkirsche** [comment]
@neildaemond Thanks for pointing this out. I've suggested the edit via the website to move to the correct link of http://hexdocs.pm/phoenix/

**Comment by neildaemond** [comment]
Cool, then a cname record from api.phoenixframework.org to hexdocs.pm/phoenix/ on the DNS level should easy enough?

**Comment by kkirsche** [comment]
Not sure. Core team would be able to help with that aspect of it.

**Comment by chrismccord** [comment]
We'll get the site updated. Thanks!

**Comment by lancehalvorsen** [comment]
I just accepted your suggested edit, @kkirsche. Thanks very much for that. I'll fix this in the repo now.

**Comment by lancehalvorsen** [comment]
And now fixed in the repo.
