### ISSUE TITLE
gitignore manifest.json

### ISSUE THREAD

**Issue by ericmj** [phoenixframework/phoenix#875]
I think manifest.json should be ignored by default since the other compiled assets are ignored by default. /cc @josevalim

**Comment by josevalim** [comment]
There is one issue though, since we added priv/static/robots.txt, running the digest task will also generate a digest for robots.txt, which we won't/can't .gitignore. So even if we gitignore manifest.json, we will have "garbage" in there. Thoughts? /cc @chrismccord

**Comment by chrismccord** [comment]
Seems like the easiest thing is to keep it as is then? It doesn't hurt and folks that build on deploy won't end up with messy diffs so seems fine as is?

**Comment by josevalim** [comment]
Or that or we move to web/static/assets and gitignore the whole priv.

**Comment by ericmj** [comment]
> Or that or we move to web/static/assets and gitignore the whole priv/static.

 :+1:

**Comment by chrismccord** [comment]
we can't though because we put non js and css assets (images, fonts) directly in priv/static/images, priv/static/fonts, etc

**Comment by josevalim** [comment]
@chrismccord right, we would ask people to put those in web/static/assets/ which is brunch convention for thos.

**Comment by gjaldon** [comment]
Putting the non-css and non-js assets in the web/static/assets directory would show users new to brunch.io where to put those. Had to look this up in Brunch readme/guides since the new Phoenix app didn't show where to put it.

**Comment by chrismccord** [comment]
> right, we would ask people to put those in web/static/assets/ which is brunch convention for those.

Ah I see. This is probably the way to go then. I know @scrogson had issue with a brunch package putting things there so this change may resolve that as well

**Comment by mguillemot** [comment]
Just another +1 for Jose's solution.

I had to add a `crossdomain.xml` file to my app today and naturally put it in `web/static` without thinking. It took me a few minutes of digging into the brunch config to realize that it should have been put in `priv/static` directly. So definitely in favor of simplifying the thought process and putting everything in `web/static`!

**Comment by chrismccord** [comment]
Agree. I think /static/assets is the way to go since it will make brunch interop much better.
