### ISSUE TITLE
phoenix.new creates broken project if doesn't install brunch.io

### ISSUE THREAD

**Issue by rodrigues** [phoenixframework/phoenix#880]
I say `n` when asked: `Install brunch.io dependencies? [Yn]`.

The generated project fails when running `iex -S mix phoenix.server`:

```elixir
iex(1)> module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/victor/code/an_api/node_modules/brunch/bin/brunch'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Before that I did `mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.13.0/phoenix_new-0.13.0.ez`

Full log here: https://gist.github.com/rodrigues/04096d1bea2668bbda71

--------

EDIT: Perhaps I was really supposed to install it, so not completely sure if it's a non-issue.

I just don't need any html for this project, it's just json.

**Comment by arpunk** [comment]
Hi @rodrigues, if you don't need brunch at all, you can generate your project like this:

`mix phoenix.new project_name --no-brunch`

**Comment by rodrigues** [comment]
Hi @arpunk, thanks!

So I guess it's not a bug, going to close the issue then.

It was a bit confusing, though, as I though saying `no` to install brunch would have that `--no-brunch` effect.

**Comment by nurugger07** [comment]
Umm, I would say that's a bug. If you are requiring brunch then the
question needs to be removed.

**Comment by doomspork** [comment]
To me these are two different questions:  "Do you want to use brunch?" vs "Do you want to install the dependencies defined in brunch?".

**Comment by chrismccord** [comment]
We default to brunch with the question "Install brunch.io dependencies?". So we aren't asking to install brunch, we are asking to install brunch (npm) deps. No bug here just sane defaults. The `--no-brunch` switch is there for those that want to skip. We may be able to make the question clearer tho. @rodrigues if you don't want to use brunch you can do this on your new project instead of starting over:


1. `rm -rf web/static/`
2. remove the `watchers: [...]` line from your dev.exs.

Then you should be all set

**Comment by nurugger07** [comment]
Sean, I think we are on the same page on this. If I don't want to install
dependencies then that shouldn't prevent the server from running. But, if
it will prevent the server from working correctly then it shouldn't be an
option.

**Comment by chrismccord** [comment]
To be clear, in the event brunch is setup, but node is not installed, the server runs just fine, but you get the watcher error.

**Comment by nurugger07** [comment]
I think better messaging would help and maybe attempting to quiet the error.

**Comment by galtenberg** [comment]
I got the error simply following the steps at http://www.phoenixframework.org/v0.13.1/docs/up-and-running, wasn't even asked about installing brunch.

```bash
$ mix phoenix.new hello_phoenix
* creating hello_phoenix/config/config.exs
...

Fetch and install dependencies? [Yn] Y
* running npm install
* running mix deps.get

We are all set! Run your Phoenix application:
...

$ cd hello_phoenix/
$ mix phoenix.server
Could not find rebar, which is needed to build dependency :fs
I can install a local copy which is just used by mix
Shall I install rebar? [Yn] Y
* creating /Users/cmg/.mix/rebar
...
Compiled lib/hello_phoenix/endpoint.ex
Generated hello_phoenix app
[info] Running HelloPhoenix.Endpoint with Cowboy on port 4000 (http)

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/cmg/dev/hello_phoenix/node_modules/brunch/bin/brunch'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

You should re-open and fix.

**Comment by chrismccord** [comment]
@galtenberg Did you have node >= 0.12 installed prior to running this?

**Comment by scrogson** [comment]
His Node version was not up to date. Worked through this with him last
night.

**Comment by josevalim** [comment]
I have also improved master to say we cannot run when the given node script does not exits. We are special casing node here but I think it is worth it due to the getting started experience. If you are customzing your watchers, you know what you are doing anyway.
