### ISSUE TITLE
Some notes on creating a new app

### ISSUE THREAD

**Issue by Rodeoclash** [phoenixframework/phoenix#886]
I thought it might be useful to track the current experience of a user creating a new app who is not too familiar with the language or framework, but has a background in Rails.

I've configured a docker container using the following: https://gist.github.com/Rodeoclash/ad9c80edc96ef16fc961

This is paired with a postgres container using docker-compose.

* I was able to create a new application without any trouble using ```mix phoenix.new . --app Antipode```
* ```mix test``` compiled a bunch of assets but ran into an error: ``` module Phoenix.HTML is not loaded and could not be found```
* I fixed the missing module by adding, ```{:phoenix_html, "~> 1.0.1"}``` to the ```mix.exs``` file then running ```mix.deps get```
* After creating and configuring the databases manually, I was able to run the tests using ```mix test```,  1 test passed and the process exited correctly.
* I was able to generate a migration using: ```mix phoenix.gen.json Link links post_href:string article_href:string published_at:datetime``` although I couldn't find anything in the guides about using the ```.json``` generator - I guessed it might exist because of the presence of ```.html``` and that was confirmed by searching the issues in this repo.
* I was able to migrate the new table with ```ecto.migrate```.
* I now have an error ```Antipode.ModelCase is not loaded and could not be found``` which I'm in the process of debugging.

All in all the two hiccups to working with the framework are:
* It seems Phoenix.HTML was recently removed which caused some minor problems until I figured out it needed to be added back in manually.
* The error with the ModelCase which I haven't been able to resolve (some direction on where to look for this would be great).

I also had some problems when I originally tried the framework getting going with tools like ```rebar`` and ```hex```. I worked past them with the code you seen in the Dockerfile however this may no longer be required.

All in all it's been a fairly smooth experience.

**Comment by chrismccord** [comment]
Thanks for the feedback and glad to hear it was a mostly smooth experience. wrt the phoenix_html issues, was `{:phoenix_html, "~> 1.0"}` missing entirely from your mix.exs? It looks like you used the 0.13 project generator so this shouldn't be the case.

**Comment by Rodeoclash** [comment]
Correct. I ran through two clean installs from scratch and encountered the issue both times, I was pulling the archive directly from ```https://github.com/phoenixframework/phoenix/releases/download/v0.13.0/phoenix_new-0.13.0.ez``` rather than using mix to install, could that be an issue?

Also, the full stack trace for the ModelCase error is:

```
** (CompileError) test/models/link_test.exs:2: module Antipode.ModelCase is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    test/models/link_test.exs:2: Antipode.LinkTest (module)
    (elixir) lib/code.ex:307: Code.require_file/2
```

**Comment by chrismccord** [comment]
I just tested by:

    mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.13.0/phoenix_new-0.13.0.ez

Then creating a new project, and everything works as expected for both reported issues. Can you expand on "pulling the archive directly?". Can you also give me a sanity check with:

    $ mix phoenix.new --version

**Comment by Rodeoclash** [comment]
Will do. At work at the moment but will endeavour to get to you within the next 24 hours. I'll also try cleaning up the Dockerfile to see if it was an environmental issue.

**Comment by Rodeoclash** [comment]
Ok, retested and I had an old version of the framework (0.11). Upgraded an had no problems whatsoever outside of the generator not adding a route which caused the tests to fail. Adding the route I think will fix that. Sorry for the bother :)
