### ISSUE TITLE
Allow assigns to be merged on a router

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#887]
Similar to how we do private:

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/router.ex#L588

**Comment by chrismccord** [comment]
What's the use-case for this that private's don't include. Defaults? Just curious if a specific need came up or if this is for future convenience

**Comment by josevalim** [comment]
Yeah, folks want this to be in assigns because they want to use it directly and not as part of a library (which is what privates are advised for).

**Comment by chrismccord** [comment]
:+1:

**Comment by gjaldon** [comment]
@josevalim I'd like to help by working on this. 

Just to clarify, we want an `:assigns` option added to the `scope` macro? Whatever map we pass to this `assigns` opt will be merged to the conn struct when the route matches?

**Comment by josevalim** [comment]
Yes! It is literally the same as the private feature we have today. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*
