### ISSUE TITLE
Remove plug :action in controllers

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#888]
It is going to be invoked automatically (in fact, we could get rid of the `action/2` function and just invoke it on call). We will also add `register_after_action/2`, similar to `register_before_send/2`, that will invoke the given functions after the action.

**Comment by jeregrine** [comment]
:+1:

**Comment by chrismccord** [comment]
Should register_after_action respect halting or always be invoked after the controller pipeline?

**Comment by josevalim** [comment]
That's a good question. At first I say it should respect halting, on the other hand, it is easy to check if it halted in the register_after_action callback. 

However, we are likely NOT going to invoke it on errors, so you shouldn't rely on register_after_action for clean up anyway, so it doesn't matter if we call it when halting or not.

**Comment by josevalim** [comment]
So I would say we can always invoke it and you can check for halting inside register_after_action. Or we can just postpone the decision and not add it... :D

**Comment by chrismccord** [comment]
@josevalim I decided to respect halting since my goal was for this to uphold the "plug pipeline" flow as much as possible. Let me know how it looks! (I pushed 0.13.1 just prior to this)

**Comment by sumerman** [comment]
@chrismccord how can use `register_after_action`? there is no documentation and it's not found in the code.

**Comment by Gazler** [comment]
@sumerman It looks like it was removed in this commit: https://github.com/phoenixframework/phoenix/commit/d85f59cc42157fffeb0b041a07ceed591ac0df30

**Comment by sumerman** [comment]
@Gazler thanks, it's good to know, but what it the right way to execute smth. after an action in 0.15?

**Comment by josevalim** [comment]
@sumerman it depends on what you want to do. Typically, the `Plug.Conn.register_before_send/2` is enough.

**Comment by sumerman** [comment]
@josevalim thanks, looks good.
