### ISSUE TITLE
Param issues

### ISSUE THREAD

**Issue by ricn** [phoenixframework/phoenix#889]
I have created a new Phoenix project (v 0.13.0) and then I ran 
`mix phoenix.gen.html User users name:string`

Then I added IO.inspect params in the generated changeset function in the User model and I noticed that the params looks different if I run the controller test or the model test.

The controller test outputs this: %{"name" => "some content"}

The model test outputs this: %{name: "some content"}

Should it be like this? I have another project where I do some more stuff with the params in the changeset function but I cannot get the tests passing because I must use params[:name] or params["name"] depending on which tests I'm running.

I have created a git repo for this here: https://github.com/ricn/params_issue

**Comment by josevalim** [comment]
Hrm, maybe we should normalize this on the Ecto side. Can you please close this issue and open exactly the same on github.com/elixir-lang/ecto? Thank you.

**Comment by ricn** [comment]
I will do that.
