### ISSUE TITLE
How do I replace `brunch` with `webpack`?

### ISSUE THREAD

**Issue by unindented** [phoenixframework/phoenix#891]
I'm a complete beginner to Phoenix, so this may be a trivial question, but how can I replace `brunch` with `webpack`?

If someone explains me how to do it, I can contribute a PR for a new section in the documentation...

**Comment by chrismccord** [comment]
It's very easy http://manukall.de/2015/05/01/automatically-building-your-phoenix-assets-with-webpack/

We don't need a guide since we should promote one good default. Thanks!

**Comment by mfn** [comment]
There's also a very recent one: http://matthewlehner.net/using-webpack-with-phoenix-and-elixir/
