### ISSUE TITLE
Allow socket params to be assigned and merged into all channel params

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#892]
For default chan.params

**Comment by doomspork** [comment]
As an exercise in familiarizing myself with Phoenix I took a crack at this, I'd love to know if I'm even on the right track.  I started by tracing the flow and it seems that by merging the `socket.assigns` with the `payload` in the `handle_reply` this could be accomplished: 

```elixir
  defp handle_reply(socket, {status, payload}, :handle_in)
       when is_atom(status) and is_map(payload) do
    send socket.transport_pid, %Reply{status: status, topic: socket.topic,
                                      ref: socket.ref, payload: socket.assigns ++ payload}
  end
```

Thanks for Phoenix btw!

**Comment by chrismccord** [comment]
@doomspork thanks, but this was a client-only addition :)
