### ISSUE TITLE
DB not being cleaned completely between tests using ConnCase and Ecto

### ISSUE THREAD

**Issue by paulcsmith** [phoenixframework/phoenix#894]
I'm not sure why, but sometimes record are still in the DB when running multiple tests. Example below shows what's currently in Phoenix (doesn't work) and what I added (does work). Not sure if this is a good way to fix it or why it works :S

```elixir
# From Phoenix's ConnCase template: https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/test/support/conn_case.ex
 
setup tags do
  unless tags[:async] do
    # Results in some records being left in the db.
    # Ecto.Adapters.SQL.restart_test_transaction(Constable.Repo, [])
    # The following cleans up correctly. It's what I was using before ConnCase came along
    Ecto.Adapters.SQL.begin_test_transaction(Constable.Repo)
 
    on_exit fn ->
      Ecto.Adapters.SQL.rollback_test_transaction(Constable.Repo)
    end
  end
 
  :ok
end
```

**Comment by josevalim** [comment]
It is funny because @ericmj was using the setup above and it definitely had race conditions causing data to remain in the database. Do you confirm @ericmj?

**Comment by josevalim** [comment]
Also, none of your tests are async, right?

**Comment by paulcsmith** [comment]
I didn't explicitly make them async. That means they're sync right? I'm pretty sure that's the default. 

Either way, I tried explicitly setting async: false and got the same results

**Comment by josevalim** [comment]
Sync is the default, yes.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by ericmj** [comment]
I have been using `SQL.restart_test_transaction` without any issues for several weeks. With `SQL.rollback_test_transaction` the DB was often left in a bad state when I had test failures.

@paulcsmith Do you still have `SQL.begin_test_transaction` in your `test_helper.exs` file?

**Comment by paulcsmith** [comment]
@ericmj I clear the database in test_helper to ensure an empty database. So maybe that's why I haven't had issues with `SQL.rollback_test_transaction` and failed test.

@ericmj I never had `SQL.begin_test_transaction` was I supposed to? Maybe that was the problem? I don't see any documentation on that and the default Phoenix install doesn't provide that AFAIK

**Comment by ericmj** [comment]
@paulcsmith It does generate it: https://github.com/phoenixframework/phoenix/blob/master/installer/templates/new/test/test_helper.exs#L6

**Comment by paulcsmith** [comment]
That was probably the issue. It was not mentioned in the upgrade guides. I'll add an issue there so people know they need it to use ConnCase.

**Comment by paulcsmith** [comment]
This can probably be closed. I think it's a guides issue, not a Phoenix issue
