### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by jordi-chacon** [phoenixframework/phoenix#898]
Hi,

first of all, thank you for building this great framework and for writing such a great documentation for it.

As a developer and system operator, I would like to be in full of control the logging within my application. Ideally I would like to log things only when I find it relevant, with the information I find most relevant, in the format I find the easiest to work with.

Therefore, I would like to be able to completely disable all logging performed by Phoenix through a configuration option.

In particular, I would like to have an option that allows me to set the Phoenix.Controller.Logger plug to not be plugged into my controllers.

Is this feature something you would be ok with? Or would you be against this feature?

Thanks a lot for your work.
Jordi

**Comment by josevalim** [comment]
So, our recommendation is to set the log level to :error. Check your config files in the config directory. If you want to not log even errors, just do not enable any logging backend. Check the Logger configuration for more info: http://elixir-lang.org/docs/stable/logger/

Also,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
