### ISSUE TITLE
new Socket() or new Phoenix.Socket()?

### ISSUE THREAD

**Issue by stanonyime** [phoenixframework/phoenix#906]
I've been trying to set up a realtime tracker with phoenix but I keep getting this error:
`
Uncaught ReferenceError: Socket is not defined
`
The phoenix.js is loaded.
I keep seeing variations of "socket = new Socket("...")" and "socket = new Socket("..")" on online examples.
I'm using React js, Elixir 1.0.2, phoenix v0.13.1 on Windows 8

Also my js files are not served after change and reload unless I rename the file

**Comment by chrismccord** [comment]
If you are using es6 javascript, (which we support by default if using brunch), you can import the `Socket` object, i.e.:

```javascript
import {Socket} from "phoenix"
let socket = new Socket("/ws")
```

If you aren't using es6, or don't want to use imports, you can also do:

```javascript
var socket = new Phoenix.Socket("/ws")
```

That should clear things up. If you still have issues, find me on #elixir-lang irc.

**Comment by iacobson** [comment]
I am running into the same kind of issue. If I keep the default:
```
import {Socket} from "phoenix"
let socket = new Socket("/socket", { ...
```

then I get this error:
`socket.js:14 Uncaught TypeError: _phoenix.Socket is not a constructor`

but if I add:
`let socket = new Phoenix.Socket("/socket", { ...`
seems to work. 
And I am using ES6.
