### ISSUE TITLE
Namespacing view and controllers

### ISSUE THREAD

**Issue by danmcclain** [phoenixframework/phoenix#910]
I've tested the following against both `v0.13` (where I encountered this) and against `master`

I want my api to be `/api/v1/blah` so the controller lives at `App.Api.V1.BlahController`, which is all good. 

### Router:
```
scope "/api", App do
  pipe_through :api

  scope "/v1", Api.V1 do
    resources "/blah", BlahController, only: [:index, :show]
  end
end
```

### Controller location
```
web/
  controllers/
    api/
      v1/
        blah_controller.ex (App.Api.V1.BlahController)
```

Now when I start with the view at `web/views/blah_view` 

### Initial view location
```
web/
  view/
    blah_view.ex (App.BlahView)
```

When I try to run my tests to hit that endpoint I get the following error: 
```
** (UndefinedFunctionError) undefined function: Dockyard.Api.V1.CaseStudyView.render/2 (module App.Api.V1.BlahView is not available)
```

Ok, that makes sense, my controller is namespaced so my view should be to. I move it to `web/views/api/v1` and update the module definition. 

### New view location
```
web/
  view/
    api/
      v1/
        blah_view.ex (App.Api.V1.BlahView)
```

When I run my tests now, I get a different error:

```
  1) test shows chosen resource (App.Test.Acceptance.Api.V1.BlahControllerTest)
     test/acceptance/api/v1/blah_test.exs:18
     ** (UndefinedFunctionError) undefined function: App.BlahView.__resource__/0 (module App.BlahView is not available)
```

It seems as though it looks for it in the original location. Is this a bug, or did I miss something when trying to namesapce the view? 

This is a JSON resource, so no template

**Comment by josevalim** [comment]
Today we infer the resource named based on the model. Which is a bug, although we are not sure how to fix it. :)

**Comment by danmcclain** [comment]
@josevalim Is there a way I can tell my controller to look for it at the same place. I can deal with it living under `App.BlahView` for now, since I get an error either way :smile:

**Comment by danmcclain** [comment]
If I try the following, I yield a new error

```
defmodule App.Api.V1.BlahController do
  # ...
  
  def index(conn, _params) do
    blahs = Repo.all(Blah)
    conn
    |> put_view(App.BlahView)
    render("index.json", blahs: blah)
  end

  def show(conn, %{"id" => id}) do
    blah = Repo.get(Blah, id)
    conn
    |> put_view(App.BlahView)
    render("show.json", blah: blah)
  end
end
```

I get the following error:

```
     ** (ArgumentError) argument error
     stacktrace:
       :erlang.apply("index.json", :private, [])
       (phoenix) lib/phoenix/controller.ex:113: Phoenix.Controller.action_name/1
       (phoenix) lib/phoenix/controller.ex:383: Phoenix.Controller.render/2
       (dockyard) web/controllers/api/v1/blah_controller.ex:1: App.Api.V1.BlahController.phoenix_controller_pipeline/2
       (dockyard) lib/phoenix/router.ex:297: App.Router.dispatch/2
       (dockyard) lib/phoenix/router.ex:2: App.Router.call/2
       (dockyard) lib/dockyard/endpoint.ex:1: App.Endpoint.phoenix_endpoint_pipeline/1
       (dockyard) lib/phoenix/endpoint/render_errors.ex:34: App.Endpoint.call/2
```

**Comment by chrismccord** [comment]
Can you include your view module. The "workaround" if we want to call it that is to be explicit about the the view in `render_one` and `render_many`, i.e.: `render_one(Blah, BlahView, "show.json")`

**Comment by danmcclain** [comment]
The 2 work arounds:

### Telling the controller to use a different view

```
def show(conn, %{"id" => id}) do
  blah = Repo.get(Blah, id)
  conn
  |> put_view(App.BlahView
  |> render("show.json", blah: blah)
end
```

### Telling `render_many`/`render_one` to use the appropriate view (@chrismccord's workaround)

```
  def render("show.json", %{blah: blah}) do
    %{data: render_one(blah, App.Api.V1.BlahView, "blah.json")}
  end
```

I will leave this issue open still

**Comment by CDainMiller** [comment]
Thanks for this @danmcclain

**Comment by josevalim** [comment]
After long thinking about this, I have concluded that being explicit on `render_many` and `render_one` is the best way to go. Thanks @danmcclain for documenting the solutions. :heart:

**Comment by danmcclain** [comment]
@josevalim I'll write up a blog post about this too, so people can be pointed to a more detailed explanation

**Comment by brado** [comment]
@danmcclain Did you ever get your blog post completed? If so, can you post a link?

**Comment by danmcclain** [comment]
@brado ah crap, I never did :disappointed: I'll see if I can soon

**Comment by brado** [comment]
@danmcclain No worries....just wanted to let you know that there's still interest. I'm presently traversing this terrain now, and this would be a valuable resource to have (can I give a +1 to having this be a guide on the Phoenix Framework web site?). 

One thing I'd be interested in discussing (not necessarily here, but somewhere) is not just the 1's and 0's - HOW-TO, but the overall strategy / best practice for accomplishing a quality REST / JSON API to a Phoenix web app, using the existing model or the duplicate namespaced model as a strategy, etc. I think some interesting things might come out of that discussion. 

Anyway, good work guys, carry on!
