### ISSUE TITLE
provide a way to update vendor assets

### ISSUE THREAD

**Issue by jlirochon** [phoenixframework/phoenix#913]
I started a fresh project with v0.13.0. After upgrading to v0.13.1 my app was broken. Took me some time to figure out the problem came from `web/static/vendor/phoenix.js`. So I copied if from `deps/phoenix/priv/static/phoenix.js` and it worked again.

Maybe Phoenix needs a way to install vendor assets like other frameworks do. For example, we could have a `mix phoenix.assets.install` task.

`deps/#{vendorName}/priv/static/#{fileName}` would be copied to `web/static/vendor/#{vendorName}/#{fileName}`.

**Comment by chrismccord** [comment]
The plan is to eventually extract the javascript client and at that point you'd update the vendor'd assets via your choice of tool (bower, manually vendor, etc). Be sure to check the changelog in the future as we link to upgrade guides for every release, i.e. https://gist.github.com/chrismccord/4a62780056b08c60542d which includes updating the js client for 0.13.1. Thanks for the idea and glad you got it figured out.

**Comment by jlirochon** [comment]
Hi Chris !

I see your point, but in this particular case one can argue that `phoenix.js` is tightly coupled to the framework. Having it upgraded by bower won't help to keep it in sync when you update Phoenix. That's true for Phoenix, and that can be true other deps built on top of it.

On the other hand, I agree that stuff like angular, react and co have to be installed by bower and not copied from deps.

Anyway thank you for the upgrade guide, it's a very valuable document for newcomers like me. Actually I didn't see the link because it was not part of `CHANGELOG.md` at the time v0.13.1 release was tagged. Also, providing an upgrade guide is not part of `RELEASE.md` instructions.

Cheers

**Comment by dgulino** [comment]
my steps to get this to work:
cd web/static/vendor
wget https://raw.githubusercontent.com/phoenixframework/phoenix/v0.13.1/priv/static/phoenix.js
cd ../../..
npm update

**Comment by jlirochon** [comment]
Thank you @dgulino, your method undoubtedly works. 

`cp deps/phoenix/priv/static/phoenix.js web/static/vendor` will work too.

However, my proposal was to get this done automatically.
