### ISSUE TITLE
[error] fs does not support the current operating system

### ISSUE THREAD

**Issue by muhendees** [phoenixframework/phoenix#920]
On FreeBSD 10.1-RELEASE after starting server with mix phoenix.server i've got a message:
[error] fs does not support the current operating system

System is FreeBSD 10.1 amd64/ FS is ZFS / Lenovo X201 tablet laptop
i dont really know what it will affect, but server is running and i can access new apps through http://localhost:4000/
If needed i can give more info. Please be informed that, this is clean install and basic app creation based on official guideline.

**Comment by josevalim** [comment]
Can you open up `iex` and type `:os.type` please? And then let us know the return value. :)

**Comment by muhendees** [comment]
muhendees@spoon:~ % iex
Erlang/OTP 17 [erts-6.4.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :os.type
{:unix, :freebsd}
iex(2)>

**Comment by josevalim** [comment]
Thank you! `fs` doesn't work because we are not sure if inotify-tools works on freebsd. Can you please give it a try and let us know? The project is here: https://github.com/rvoicilas/inotify-tools/wiki

If it does, we will provide a fix. In any case, you don't have to worry about this, it only means you won't have live reloading. :)

**Comment by muhendees** [comment]
Thank you too for your response. so, i did some little investigation and find that inotify and tools are linux thingie and will not work on FreeBSD. bu i have found this https://github.com/emcrisostomo/fswatch

as far as i understand fs(which isnt working on freebsd) is realtime filesystem watcher. on my mac i can use it where i change file lets say html and immediately see changes on browser. if this is that [fs] so i think fswatch will work for freebsd.

**Comment by josevalim** [comment]
Yeah, fswatch may work but we don't support it in `fs` yet. I can open up an issue on the fs project but there is no guarantee when they/we will work on it. If you want to give it a try and send a PR, they will probably appreciate it.

**Comment by josevalim** [comment]
Issue opened here: https://github.com/synrc/fs/issues/17 Closing this for now as it is not a Phoenix issue per se. :) Thanks for reporting and verifying!

**Comment by muhendees** [comment]
thanks, last 2 years i observe that freebsd support on such projects are not stable because of community. currently im learning elixir, maybe will find time to give it a try later.
