### ISSUE TITLE
Overriding url used in *_url methods?

### ISSUE THREAD

**Issue by citizenparker** [phoenixframework/phoenix#922]
When I'm fronting a Phoenix application with something like nginx, all the `*_url()` methods generate incorrect URLs. They include the port the application is listening on, but when it's behind nginx that is usually not a publicly accessible port.

Is there a way to override this URL globally that I'm missing?

**Comment by chrismccord** [comment]
The `:url` endpoint configuration is what you're after, i.e.:

```elixir
config :my_app, MyApp.Endpoint,
  ...
  http: [port: 1234], # nginx's port
  url: [host: "foobar.com", port: 80] # _url host/port
```

Feel free to reopen if you still have issues

**Comment by citizenparker** [comment]
Ah, I didn't think to specify a port within the `url` config key. Looking at the source now, I see that it will omit the port when you set it to `80`. I must admit I find that behavior a little surprising. 

My only idea for an alternative is allowing a bare string as the value for this key rather than a keyword list, and if a base string is passed, it will be used as the URL root in its entirety. What do you think?

**Comment by chrismccord** [comment]
Port 80 is special cased for urls for pretty much all clients in my experience, so I think the current behavior is what we want. Is there a case where you need "http://example.com:80" to be generated?

**Comment by citizenparker** [comment]
No, it just didn't occur to me that if I wanted to suppress the output of a port entirely in my url methods, I have to specify a port. I'm not vehemently opposed to the current behavior, but I just found it surprising. I'm happy to accept that perhaps I'm easily surprised. =)

**Comment by chrismccord** [comment]
Ah I see. We should probably include `port: 80` in the prod.exs config when generating new projects. @josevalim

**Comment by josevalim** [comment]
I don't think we should include the port. All the URLs have a port, so the
only reason for including it is for configuration but there are tons of
other options, maybe more useful, that we don't include because we don't
want to clutter config files.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by citizenparker** [comment]
Is there a reason this isn't a string or at least accepts a string in addition to a keyword list? That would have solved my confusion as well, and it looks like this is almost exclusively used to reconstitute the individual parts into a string that is used as a prefix on URLs anyway.

**Comment by josevalim** [comment]
@chrismccord will you tackle this one? I don't remember what we discussed anymore. :)

**Comment by chrismccord** [comment]
@josevalim I will have to dig up the logs. I think we settled on `port: 80` and docs in prod.exs. I'm on it

**Comment by josevalim** [comment]
Yeah, I think that generating a port: 80 and adding notes to the SSL comments in config/prod.exs.

**Comment by doomspork** [comment]
@chrismccord I've got PR #923 open from when this issue was first created, I can either add the necessary documentation or close it.
