### ISSUE TITLE
Newly created project doesn't compile

### ISSUE THREAD

**Issue by darthdeus** [phoenixframework/phoenix#927]
See https://groups.google.com/forum/#!topic/phoenix-talk/x7VyYKw3tRI for details regarding the issue.

Basically the problem is that there's a missing dependency, and adding

     {:phoenix_html, "~> 1.0"},

to the `mix.deps` file seems to fix it. To reproduce this, simply run `mix phoenix.server` in a newly generated project. I've tested this on 0.13.1.

**Comment by ericmj** [comment]
Should be fixed on master.
