### ISSUE TITLE
Customize logging format?

### ISSUE THREAD

**Issue by jclem** [phoenixframework/phoenix#932]
I see that I can customize the logging format to a very small degree in `config.exs`, but the logging customization still seems pretty restrictive, unless I'm missing something.

Typically, I format my logs according to the loose [logfmt][logfmt] standard, and have a [module that can format a Dict as a logfmt line][logfmt-elixir].

Typically, I prefer my log lines to look more like this:

```bash
level=info method=GET path=/ status=200 elapsed=132ms
```

This is extremely useful, because I can automatically get great metrics and visualizations from services that are logfmt-aware, such as [Librato][librato] (which is, in part, a hosted [l2met][l2met]) or [Logentries][logentries].

Is this something that's currently doable in Phoenix?

[logfmt]: https://brandur.org/logfmt
[logfmt-elixir]: https://github.com/jclem/logfmt-elixir
[librato]: https://www.librato.com
[l2met]: https://github.com/ryandotsmith/l2met
[logentries]: https://logentries.com

**Comment by jclem** [comment]
I more or less figured it out, I was just a bit confused over some Phoenix/Plug conventions. I'm using [this logger](https://gist.github.com/anonymous/8a940db2772cdb9e85a3) now instead of the standard plug logger.

**Comment by doomspork** [comment]
Thanks for posting this @jclem, I was wondering about this myself so it's very useful to me.

**Comment by jclem** [comment]
@doomspork Note that I also updated my [logger config](https://gist.github.com/anonymous/19c9d66b4f20bb08dc77) to output better UTC timestamps and log levels. You'll still get some weird-looking logs (In Node, I actually split my error stack traces up on separate logfmt lines, and it's amazing), but I consider it a work in progress.
