### ISSUE TITLE
Controller :plug :render Assign 2 variables

### ISSUE THREAD

**Issue by rizafahmi** [phoenixframework/phoenix#934]
I follow this tutorial: [http://www.phoenixframework.org/v0.13.1/docs/controllers](http://www.phoenixframework.org/v0.13.1/docs/controllers). When I tried to assign 2 variables using `:plug :render`, but it got an error: `no function clause matching in Plug.Conn.assign/3`.
![Imgur](http://i.imgur.com/Z9jFit8.png)

**Comment by chrismccord** [comment]
you need to add parenthesis, i.e.: 

```elixir
conn
|> assign(:message, "welcome")
|> assign(:name, "Riza")
```

**Comment by rizafahmi** [comment]
Noted. So I guess parenthesis is mandatory now, not optional anymore yea.. :)

**Comment by chrismccord** [comment]
Not quite. Parens are optional, but a good rule is to always use them when piping because the operator precedence is not what you think. For example, here's how your initial code was seen by Elixir:

```elixir
iex(1)> quote do
...(1)>   conn
...(1)>   |> assign :message, "Welcome Back!"
...(1)>   |> assign :name, "Riza"
...(1)> end |> Macro.to_string() |> IO.puts()
conn |> assign(:message, "Welcome Back!" |> assign(:name, "Riza"))
:ok
```

**Comment by rizafahmi** [comment]
Duly noted!
