### ISSUE TITLE
Phoenix 0.13.1 is incompatible with phoenix.js generated from 0.13.0

### ISSUE THREAD

**Issue by obrok** [phoenixframework/phoenix#940]
I have phoenix `0.13.0` installed globally (as an archive I guess it's called?) and generate a new app from it. All goes well, but the dependency on phoenix is specified as

```elixir
[{:phoenix, "~> 0.13"},
```

Making it bump the version to 0.13.1 in mix.lock:

```elixir
"phoenix": {:hex, :phoenix, "0.13.1"},
```

This is all fairly normal, but the problem is that the `phoenix.js` file that got generated comes from `0.13.0` and there has been a change in that file that breaks connecting to channels in this scenario:

```js
// 0.13.0
this.on(CHAN_EVENTS.reply, function (payload) {
  _this.trigger(_this.replyEventName(payload.ref), payload);
});

// 0.13.1
this.on(CHAN_EVENTS.reply, function (payload, ref) {
  _this.trigger(_this.replyEventName(ref), payload);
});
```

I guess the point is that that file is also a dependency of the project but its version isn't specified anywhere and isn't checked for compatibility with the version of phoenix in use.

**Comment by chrismccord** [comment]
Yes, sorry for this frustration. As the 0.13.1 upgrades guides say, you'll need the 0.13.1 phoenix.js https://gist.github.com/chrismccord/4a62780056b08c60542d

**Comment by obrok** [comment]
It makes sense when upgrading, but in my case the upgrade sort of happened on its own. Maybe there could be a check that the file has the correct version?

**Comment by chrismccord** [comment]
Yeah you are right, but there's not much we can do in this case. Like if we released a new 0.13.0 archive, it wouldn't help. Folks that sill have the 0.13.0 archive installed and haven't jumped to 0.13.1 archive will have this issue, but there's nothing to fix this growing pain unfortunately. Some upgrades have required a new phoenix.js while others haven't, so there's nothing to check at the moment. We'll eventually extract and version the js client, but that won't help figuring out if your phoenix version and phoenix.js version are correct, especially when folks are on different js build tools.

**Comment by obrok** [comment]
I just had the idea that the client could ask the server (when in dev mode) about its version, check if its the same and display some kind of warning if not - would that make sense?

**Comment by chrismccord** [comment]
If you follow this thread https://github.com/phoenixframework/phoenix/issues/810 , we're going to include a `vsn` when connecting so the server knows what version the client is speaking. For this to happen, we first need to start versioning the channel protocol, which will happen soon. Thanks for the ideas!
