### ISSUE TITLE
phoenix.new creates faulty page when --no-brunch is used

### ISSUE THREAD

**Issue by pb82** [phoenixframework/phoenix#942]
Not critical, but using the `--no-brunch` switch with `phoenix.new` results in a javascript error:

```
ReferenceError: require is not defined
<script>require("web/static/js/app")</script>
```
I'm using Phoenix 0.13.1

Steps to reproduce:

1. Create project with `mix phoenix.new testapp --no-brunch`
2. Start the server and open localhost:4000 in a browser
3. You will see the javascript error in the browser console

The reason is that without brunch, phoenix.js is not merged into app.js and thus `require` is not available. app.js is an empty file.

Proposed solution:

When not using brunch the layout template (application.html.eex) should explicitely load phoenix.js and provide a stub app.js. The question is what this stub should contain: maybe register an empty module named `app`?

**Comment by Gazler** [comment]
I'll take a stab at this one - not generating the require line should prevent this issue, but still let you use app.js from `priv`

**Comment by pb82** [comment]
Thanks for looking into this! Not generating the require will suppress the javascript error. But then phoenix.js is still not available without brunch. What about including the line

```html
<script src="<%= static_path(@conn, "/js/phoenix.js") %>"></script>
```

in the layout template? Then `require` is also available.
