### ISSUE TITLE
Unable to run phoenix.gen.html and phoenix.gen.json for the same model

### ISSUE THREAD

**Issue by brweber2** [phoenixframework/phoenix#949]
Only one controller, view and controller test can win....

## Run gen.html first

```bash
mix phoenix.gen.html Bar bars name:string count:integer
```

Then I add the route info to the router and run mix ecto.migrate.

```bash
mix phoenix.gen.json Bar bars --no-model
```

At this point I *must* choose which controller I want to win:

```text
* creating web/controllers/bar_controller.ex
web/controllers/bar_controller.ex already exists, overwrite? [Yn] n
* creating web/views/bar_view.ex
web/views/bar_view.ex already exists, overwrite? [Yn] n
* creating test/controllers/bar_controller_test.exs
test/controllers/bar_controller_test.exs already exists, overwrite? [Yn] n
```

## Run gen.json first

Once again I must choose which one I want to win....

```text
...
* creating web/controllers/quux_controller.ex
web/controllers/quux_controller.ex already exists, overwrite? [Yn] n
* creating web/templates/quux/edit.html.eex
* creating web/templates/quux/form.html.eex
* creating web/templates/quux/index.html.eex
* creating web/templates/quux/new.html.eex
* creating web/templates/quux/show.html.eex
* creating web/views/quux_view.ex
web/views/quux_view.ex already exists, overwrite? [Yn] n
* creating test/controllers/quux_controller_test.exs
test/controllers/quux_controller_test.exs already exists, overwrite? [Yn] n
```

It would be nice if I could use gen.html, gen.json and gen.channel for the same model.  

Perhaps a --model <name> option instead of --no-model?  Or perhaps change the naming conventions of the files so they don't match?

**Comment by josevalim** [comment]
Yes, only one will be able to win. Phoenix currently does not support generating one controller that does it all, it is up to you to build it. The current alternative is to namespace one of them:

    mix phoenix.gen.json API.Bar bars --no-model

We don't expect folks to use generators to build their whole application, they are mostly learning tools.

**Comment by brweber2** [comment]
Just to follow up with this the generator for API.Bar generated ap_i._bar and it did not compile.  However, if I use Api.Bar it is in a better state.  It still generates code that does not compile, but it gives this error (note I used Foo instead of Bar below, but obviously it is the same thing):

```
== Compilation error on file web/controllers/api/foo_controller.ex ==
** (CompileError) web/controllers/api/foo_controller.ex:15: Rackit.Api.Foo.__struct__/0 is undefined, cannot expand struct Rackit.Api.Foo
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
```

So I assume that there is no Rackit.Api.Foo.__struct__ because we used --no-model.

In the Api.Foo controller I changed the alias from ```alias Rackit.Api.Foo``` to ```alias Rackit.Foo``` thining that I'd like to re-use the existing model and then 

```
[error] #PID<0.468.0> running Rackit.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /api/api/foos
** (exit) an exception was raised:
    ** (Phoenix.Template.UndefinedError) Could not render "foo.json" for Rackit.FooView, please define a matching clause for render/2 or define a template at "web/templates/foo". The following templates were compiled:

* edit.html
* form.html
* index.html
* new.html
* show.html

Assigns:

%{foo: %Rackit.Foo{__meta__: %Ecto.Schema.Metadata{source: "foos", state: :loaded}, count: 2, id: 1, inserted_at: %Ecto.DateTime{day: 7, hour: 11, min: 48, month: 6, sec: 12, usec: 0, year: 2015}, name: "boo", updated_at: %Ecto.DateTime{day: 7, hour: 11, min: 48, month: 6, sec: 12, usec: 0, year: 2015}}}

        (rackit) web/views/foo_view.ex:2: Rackit.FooView.template_not_found/2
        (phoenix) lib/phoenix/view.ex:274: anonymous fn/4 in Phoenix.View.render_many/3
        (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (phoenix) lib/phoenix/view.ex:272: Phoenix.View.render_many/3
        (rackit) web/views/api/foo_view.ex:5: Rackit.Api.FooView.render/2
        (phoenix) lib/phoenix/view.ex:429: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:533: Phoenix.Controller.do_render/4
        (rackit) web/controllers/api/foo_controller.ex:1: Rackit.Api.FooController.phoenix_controller_pipeline/2
```

So it looks like it can't find the view because it can't pattern match on the entity (possibly because the generated code was expecting something that matched a convention based on the route/controller/view/etc. ?).

How can I get my namespaced API code finding the correct view?  I tried looking for documentation on namespacing on the website, I feel like I've seen it before, but when I went back to look I couldn't find it on the Controller or Templates page...

**Comment by josevalim** [comment]
> How can I get my namespaced API code finding the correct view? I tried looking for documentation on namespacing on the website, I feel like I've seen it before, but when I went back to look I couldn't find it on the Controller or Templates page...

This is the issue with #910. We are going to fix it... we are not yet sure how.

**Comment by brweber2** [comment]
Ok then I am going to close this issue. This is more feature request than bug and 910 covers the namespacing. 

I can imagine a rich set of mix gen.* tasks being pretty popular someday. Combining a few could get you a fully functioning app... One for authentication, one for crud, etc. Most interesting apps will need more but I think they could take you pretty far.
