### ISSUE TITLE
mix test should use schema from development db

### ISSUE THREAD

**Issue by HeroicEric** [phoenixframework/phoenix#951]
I've run into this a few times.

When I'm creating a new feature that includes a database migration, after the initially running the migration, the test db has the correct schema during test runs. Sometimes I'll realize that I need to change the migration while working on the feature so I'll `mix ecto.rollback`, make the changes, then migrate forward again.

The problem is that the test database thinks it has already ran that migration.

I've been manually dropping the test db, which works because the migrations are run from the beginning again for the test db.

**Comment by josevalim** [comment]
That's exactly what you should do for now. The development database is
going to have development data and Ecto currently does not provide anyway
to copy the development schema into test.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by chrismccord** [comment]
We'll have to shelve this for now until Ecto has a better story here. Doc'ing this somewhere might be a good idea, but I'm sure where it fits.
