### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by DavidAwad** [phoenixframework/phoenix#952]
I think the favicon might be missing? 

I went through the docs and did the basic phoenix install. 

looks like a small thing but I wanted to report anyway. Thanks!

**Comment by josevalim** [comment]
Which version? How have you installed it? Did you see any error in your terminal? In any way, can you please paste the logs? Thanks! :D

**Comment by doomspork** [comment]
@josevalim I tried with `master` and noticed that the `favicon.ico` 404 error is present, doesn't look like there is currently one in the installer;  I can open a PR to add the Phoenix favicon.ico.
