### ISSUE TITLE
How to make release for other environment?

### ISSUE THREAD

**Issue by infernalmaster** [phoenixframework/phoenix#953]
I'm using MacOS and trying to run my first project on Ubuntu server and getting error 
```
/app/erts-6.3.1/bin/run_erl: 1: /app/erts-6.3.1/bin/run_erl: Syntax error: Unterminated quoted string
```
I found this issue https://github.com/bitwalker/exrm/issues/96, but can`t handle that, because I'm newbie to erlang. I'll be very grateful if someone describes in detail how to solve this problem (and possibly include it in the official guide)

**Comment by chrismccord** [comment]
Releases are still a WIP as Alfaro as the guides are concerned and it's unfortunately not something I've had enough time to explore yet. I recommend newcomers don't immediately jump into releases. This sounds like an exrm issue so you'll need to address over there.

**Comment by lexmag** [comment]
@infernalmaster, to build a release for Ubuntu you need to specify a version of ERTS (Erlang Run-Time System) precompiled for Ubuntu. More info there: https://github.com/bitwalker/exrm/pull/99.

**Comment by izelnakri** [comment]
I spent few hours trying to deploy a simple phoenix app to a VPS. After trying many things I went ahead with scp my directory to my VPS which isnt optimal of course... Can we have a guide on a deployment solution? Also, removing/archiving this page would be great as the solution on this page doesnt work: http://www.phoenixframework.org/docs/advanced-deployment

**Comment by chrismccord** [comment]
Please open an issue on the phoenix_guides repo if you find technical inaccuracies and use the phoenix-talk mailing list for support requests. The deployments guides as far as we are aware are just fine, but between os's and configuration there's  a lot that can go wrong. Thanks!
