### ISSUE TITLE
Implicit dependency on ecto

### ISSUE THREAD

**Issue by skylerparr** [phoenixframework/phoenix#956]
Is there a way to run phoenix > 0.12.0 without having a dependency on ecto?

**Comment by chrismccord** [comment]
`mix phoenix.new my_app --no-ecto`

**Comment by skylerparr** [comment]
I have a dependency on ecto 0.4.0 on a separate (legacy) library. I tried mix phoenix.new my_app --no-ecto and included my dependency. When I run mix deps.get I get the following error:

Running dependency resolution
Looking up alternatives for conflicting requirements on poolboy
  From phoenix v0.13.1: ~> 1.5.1 or ~> 1.6
  From ecto v0.4.0: ~> 1.4.1
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

How do I get around this (without upgrading the other ecto dependency library)?

**Comment by josevalim** [comment]
The issue here is that they depend on conflicting poolboy versions. You should update Ecto but, since that is not possible, you can choose a poolboy yourself:

    {:poolboy, "~> 1.6", override: true}
