### ISSUE TITLE
Mix generated controllers spits out 500 instead of 404 error when things aren't found

### ISSUE THREAD

**Issue by foxnewsnetwork** [phoenixframework/phoenix#957]
Mix generated json (and html) controllers for common resourceful functions such as delete look like this:
```elixir
def delete(conn, %{"id" => id}) do
  camera = Repo.get(Camera, id)

  camera = Repo.delete(camera)
  render(conn, "show.json", camera: camera)
end
```
so if you hit this function with an id not in your database, `camera` is nil which causes `Repo.delete` to throw a 500 error. In my opinion, a 404 error would be more appropriate here. Therefore, I would like to make a pull request to change the template controllers living in `priv/templates/json/controller.ex` from using `Repo.get` to using `Repo.get!`... but is this a good idea?

**Comment by josevalim** [comment]
Great catch. We should defintiely use `Repo.get!`. Pull request please? :)

**Comment by gjaldon** [comment]
Sounds like a good idea to me :)

**Comment by foxnewsnetwork** [comment]
Cool, I will pr tonight after work
