### ISSUE TITLE
Javascript: Socket.onMessage should include channel and event

### ISSUE THREAD

**Issue by ericmj** [phoenixframework/phoenix#967]
Just including the message is not very useful. A similar `onMessage` would also be useful on the channel.

**Comment by chrismccord** [comment]
onMessage includes topic, event, payload, and ref in a js literal. What useless do you need channel for? We can add it, but the client carries the message => channel map. So the `onMessage` here is referring to a phoenix channel message per the spec. Adding the mapped channel can't hurt, but that was my thinking for it.

**Comment by chrismccord** [comment]
I just realized, we have "channel" in this context. @ericmj What would you like to see output as the channel? The channel module on the server? The inspected `chan` javascript object that the client matches to the topic?

**Comment by ericmj** [comment]
Sorry, I completely misread the code and made a mistake in my test. (I also meant topic instead of channel).

What do you think of a similar function on `Channel` though? We would like a catch-all function that receives all events without the need of pattern matching in `on`.

**Comment by chrismccord** [comment]
> What do you think of a similar function on Channel though? We would like a catch-all function that receives all events without the need of pattern matching in on.

Makes sense, but you'll get all the ref replies, which might be confusing/unexpected, since they are hidden today. I think having it as a low-level callback option is easier enough and won't hurt

**Comment by chrismccord** [comment]
Much improved logging in master:

![](https://s3.amazonaws.com/f.cl.ly/items/3g2j3U0O210h0u3a1U1F/Image%202015-06-27%20at%209.03.13%20AM.png)
