### ISSUE TITLE
Ensure terminate is triggered on unclean disconnect

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#969]
ref: https://groups.google.com/d/msgid/phoenix-talk/fd6dbc97-6e21-4d38-84a4-ce1d3632a782%40googlegroups.com?utm_medium=email&utm_source=footer

I still need to recreate this bug, but I'm willing to bet `{:error, :closed}` may not be everything we need to match on here https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint/cowboy_websocket.ex#L50

**Comment by josevalim** [comment]
Well, isn't terminate supposed to be called only on clean cases? I think
the current behavior is correct and documented.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by chrismccord** [comment]
> Well, isn't terminate supposed to be called only on clean cases? I think
> the current behavior is correct and documented.

I just recalled our talk from ndc. You are right.
