### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix#971]
README should link to the guides and resources.

We should also consider including deploy buttons on the README to make it really easy to get up and running. Many platforms support them, we could get started with Heroku.

**Comment by gjaldon** [comment]
I'd like to take this on. What sample app should we deploy to Heroku? Just a new basic Phoenix app or should we add some basic CRUD stuff and features that make use of channels?

**Comment by josevalim** [comment]
Sorry, I was not super precise. We need to improve the README of the *generated* application. Heroku supports deploy to Heroku buttons, which we need to figure out how they work too.

**Comment by gjaldon** [comment]
My bad. That makes more sense now. Will have a PR ready for this over the weekend. Looked up the [Heroku deploy button](https://devcenter.heroku.com/articles/heroku-button) and it looks simple enough. 

Looking at the [app.json schema](https://devcenter.heroku.com/articles/app-json-schema#example-app-json), not sure if it supports multiple buildpacks and not yet clear to me how to dynamically generate the user's "repository". I'm roughly thinking asking for the user's github name when creating a new app and encouraging them to create a `"https://github.com/username/myapp"` repo. Or add instructions in the readme to put in their app's repo name in `app.json`. The latter one looks like the winner to me.

**Comment by josevalim** [comment]
Definitely the latter. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Thanks @gjaldon! After some thought, we have decided to not ship with this in favor of Phoenix guides. I will be bringing some of the improvements here over there though! Thank you very much!

**Comment by gjaldon** [comment]
You're welcome! :)
