### ISSUE TITLE
Generated test cases fail if the json resource contains an association

### ISSUE THREAD

**Issue by adanselm** [phoenixframework/phoenix#972]
In Phoenix 13.1, test cases generated by phoenix.gen.json fail if the resource contains an association:

## Steps
* Create 2 resources, one of which has a belongs_to field:
```
$ mix phoenix.gen.json Category categories title:string
$ mix phoenix.gen.json Post posts message category:belongs_to
```
* Edit the router as advised by the generators
* Run `mix test` :

>  3) test creates and renders resource when data is valid (MyApp.PostControllerTest)
>     test/controllers/post_controller_test.exs:26
>     ** (Ecto.QueryError) deps/ecto/lib/ecto/repo/queryable.ex:195: field `MyApp.Post.category` in `where` does not exist in the model source in query:
>     
>     from p in MyApp.Post,
>       where: p.category == ^nil,
>       where: p.message == ^"some content"
>     
>     stacktrace:
>       (ecto) lib/ecto/query/planner.ex:86: Ecto.Query.Planner.prepare/3
>       (ecto) lib/ecto/query/planner.ex:65: Ecto.Query.Planner.query/4
>       (ecto) lib/ecto/repo/queryable.ex:20: Ecto.Repo.Queryable.all/4
>       (ecto) lib/ecto/repo/queryable.ex:53: Ecto.Repo.Queryable.one/4
>       test/controllers/post_controller_test.exs:29

## Fix
Removing `category: nil` from the `@valid_attrs` in `test/controllers/post_controller_test.exs:5` solves the problem:
```
  @valid_attrs %{category: nil, message: "some content"}
```
replaced by
```
  @valid_attrs %{message: "some content"}
```

**Comment by josevalim** [comment]
Fixed in Ecto.
