### ISSUE TITLE
Path functions insert && with empty maps

### ISSUE THREAD

**Issue by jeregrine** [phoenixframework/phoenix#973]
I know I've seen this before, but I haven't been able to isolate the issue specifically

```elixir
iex(2)> App.Router.Helpers.project_path(CometApi.Endpoint, :index,  %{:filter => %{}, :include => %{}, :page => %{number: 0, size: 20}, :sort => [desc: :created_at], "format" => "json", "sort" => "-created_at"})
"/api/projects?&&page[number]=0&page[size]=20&sort[desc]=created_at&format=json"
```

**Comment by chrismccord** [comment]
Does the Mix env make a difference? Can you recreate it every time with the above code? Or it randomly happens?

**Comment by jeregrine** [comment]
I will test those. I get this every time in IEX.

**Comment by josevalim** [comment]
Maybe we should do a Skype next week to figure this out. :) But finding out
if it happens in dev or prod would help too!

**Comment by jeregrine** [comment]
This is a very old bug that I've reported directly to Chris but the code
tells me this isn't possible. So I've just ignored it a bunch. Happy to
skype whenever.

**Comment by josevalim** [comment]
Closing in favor of the plug report.
