### ISSUE TITLE
Bidirectional associations?

### ISSUE THREAD

**Issue by arthurcolle** [phoenixframework/phoenix#976]
In Rails I can do something like:

```
class Order < ActiveRecord::Base
  belongs_to :buyer, class_name: 'User'
  belongs_to :seller, class_name: 'User'
end
```

I want to do the same in my Ecto Model of an Order, but right now I'm doing this:

```
defmodule Repo.Order do
  use Repo.Web, :model

  schema "orders" do
    belongs_to :user, Repo.User
    field :dish_id, :integer
    field :buyer_id, :integer
    field :subtotal, :integer
    timestamps
  end
  [...]
end
```

But the above has it belonging to the seller, with a "buyer_id" foreign key. So the two don't seem to be equivalent. How can I get the same functionality as in Rails? 

Thanks!

**Comment by josevalim** [comment]
@arthurcolle please Phoenix or Ecto mailing list for questions! You can also look into the docs for belongs to that will allow you to customize field names, associations and so on: https://hexdocs.pm/ecto/Ecto.Schema.html#belongs_to/3

**Comment by arthurcolle** [comment]
Thank you for the link, and noted for the mailing list.
