### ISSUE TITLE
Logging around Channels for better introspection

### ISSUE THREAD

**Issue by senny** [phoenixframework/phoenix#982]
I just started toying around with Phoenix and found myself doing a couple copy and paste errors when working with Channels. As a beginner, it's sometimes hard to find the error. Even more so with Channels as they feel like a black box. It would be nice to get some idea about what's going on beneath the surface.

I'm thinking about basic log statements for:
* Someone connected
* Someone subscribed to a topic
* Incoming event

**Comment by chrismccord** [comment]
@senny Thanks for the idea. @josevalim the channel integration tests include some logging noise now, even though we are using capture_log,  ¯\_(ツ)_/¯
