### ISSUE TITLE
ConnTest.recycle/1 does not recycle session

### ISSUE THREAD

**Issue by gjaldon** [phoenixframework/phoenix#985]
I store user data in session and it works fine in prod and development. However in test, `recycle/1` does not recycle session. Shouldn't we emulate session persisting across requests?

I realize this would be implemented in Plug but created the issue here since I want to make use of it `Phoenix.ConnTest`.

**Comment by josevalim** [comment]
Well, the session is supposed to generate a cookie, which we then recycle, and it will be read in following requests. So it is supposed to work, unless the session cookie is not being generated. This can happen if the response is set but never sent.

What if we do this:

1. recycle should raise if the connection is unset or set in Plug
2. we ensure Phoenix test helpers (get, post, etc) guarantee the response is sent

**Comment by gjaldon** [comment]
Here's my findings:
1. Looks like responses are sent in test. Conn's are set to `:sent` and my own before_send callbacks are triggered. I tried creating a plug that registers a before_send callback and it gets triggered in test
2. Added `puts` messages in the `init/1` funs for `Plug.Session` and `Plug.Static`. The messages display in dev but not in test. Haven't found out why yet but saw that my custom plugs work fine in test.

Any idea what's causing the above behavior? Is it possible it's only me that's experiencing this?

**Comment by josevalim** [comment]
No idea. Can you paste a sample test here?

**Comment by gjaldon** [comment]
Here's a sample test https://github.com/gjaldon/manang/blob/recycle/test/controllers/admin/professional_controller_test.exs.
All the controller tests that require login fails in that branch since I used `put_session` in the `login_user` helper. 

Try putting a `puts` debug message in `Plug.Session` and see if it gets called in test environment.

**Comment by josevalim** [comment]
This approach is not going to work. You need to put_session inside the app. If you call it in the test case, the response was already sent, the cookies serialised and it won't have any effect.

**Comment by gjaldon** [comment]
Ok copy that. Thanks for looking into this!
