### ISSUE TITLE
Force ssl by default in all environments

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#986]
This will require special care in dev, such as generating certs and we'll need to navigate the install process

**Comment by jeregrine** [comment]
:+1: Could possibly configure it to off on dev? 

Assuming we'll be using https://github.com/elixir-lang/plug/blob/master/lib/plug/ssl.ex to redirect all requests.

**Comment by williamgueiros** [comment]
:+1:

**Comment by chrismccord** [comment]
> Could possibly configure it to off on dev?

Of course. Good defaults, but always overridable. In this case, it would only require changing dev.exs to use `:http` instead of `:https`. Easy peasy
