### ISSUE TITLE
Unable to join ("Ignoring unmatched topic" error) if channel is limited to WebSockets

### ISSUE THREAD

**Issue by mspanc** [phoenixframework/phoenix#989]
There's no way to join a channel (keep getting "Ignoring unmatched topic" error in the console) if channel is limited to WebSockets.

Phoenix 0.13.1, Elixir 1.0.4, Firefox 38.0.5 (Mac) as a client.

Router:

```
defmodule WsChannel.Router do
  use WsChannel.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WsChannel do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  socket "/ws", WsChannel, via: [WebSocket] do
    channel "test:xyz", TestChannel
  end

  # Other scopes may use custom stacks.
  # scope "/api", WsChannel do
  #   pipe_through :api
  # end
end
```

Channel:

```
defmodule WsChannel.TestChannel do
  use Phoenix.Channel
  require Logger

  def join("test:xyz", msg, socket) do
    send(self(), {:after_join, msg})
    {:ok, socket}
  end


  def handle_info({:after_join, msg}, socket) do
    Logger.debug "Joined"
    {:noreply, socket}
  end
end
```

app.js:

```
import {Socket} from "phoenix"

let socket = new Socket("/ws")
socket.connect()
let chan = socket.chan("test:xyz", {})
chan.join().receive("ok", chan => {
  console.log("Success!")
})

let App = {
}

export default App
```

Removing `via: [WebSocket]` fixes the issue.

Something is wrong here, because underlying WebSocket connection is established (server knows the name of the channel) but matching does not work.

The same happens if `via: [WebSocket]` is assigned to the particular channel route.

**Comment by chrismccord** [comment]
Try `socket "/ws", WsChannel, via: [Phoenix.Transports.WebSocket] do` and report back. We don't inject the alias for you so the full module is required (or you can alias it in your router)

**Comment by josevalim** [comment]
Actually, why did you try `via: [WebSocket]` @mspanc? is it a documentation bug somewhere?

**Comment by mspanc** [comment]
Oh, it is a documentation bug, indeed.

http://www.phoenixframework.org/v0.13.1/docs/routing

There are many occurences of `via: [WebSocket]`.

**Comment by chrismccord** [comment]
Well get this fixed. Can you confirm that using the full alias fixed your problem?
https://github.com/phoenixframework/phoenix_guides/issues/299

**Comment by mspanc** [comment]
I can confirm it works fine with full alias.

**Comment by lancehalvorsen** [comment]
This is fixed both in the repo and on the live site.

**Comment by shanthivardhan** [comment]
I am seeing this issue "Ignoring unmatched topic" when I try to join from sample iOS app with the following configuration in my user_socket.ex.

`defmodule PhoenixServer.UserSocket do
 use Phoenix.Socket

 channel "test:*", PhoenixServer.TestChannel , via: [Phoenix.Transports.WebSocket]
 transport :websocket, Phoenix.Transports.WebSocket
 transport :longpoll, Phoenix.Transports.LongPoll
end
`
Removing , via: [Phoenix.Transports.WebSocket] fixes the issue.
