### ISSUE TITLE
Extract Socket into separate NPM package

### ISSUE THREAD

**Issue by mspanc** [phoenixframework/phoenix#990]
Hello,

I need to use JS code for Socket in my Node.JS app. I however, strongly rely on NPM for package and dependencies management. I was unable to find it anywhere in the NPM directory, so I am ready to prepare such package.

If you don't mind I think it would be nice if you've created a dedicated repository (such as phonixframework/socket-js) and assigned push permissions to me. I can obviously create this on my private account but it can be quite confusing for others.

We should also agree on the package name in the NPM registry (I don't know if you have any convention for such purpose), maybe `phoenixframework-socket`? I will obviously add you as an owner when the package is ready.

NPM versioning scheme would follow versioning of phoenix. 

Is it ok for you?

**Comment by chrismccord** [comment]
This is on my todo list as we prep the Phoenix 1.0 release, but we need to version the channels api first and wait for the churn to stop. The client is stabilizing, so I will be able to address this soon. In the meantime, vendoring the client is the best way to go.

**Comment by mspanc** [comment]
Ok, I am ready to help when it will be ready.

**Comment by yeehaa123** [comment]
@chrismccord @mspanc I'd also be willing to help out with this. It would be great for people (like me) who use webpack and/or run their frontend from a separate server to have it available as a package.

**Comment by daytonn** [comment]
I would also be interested in lending a hand. Would be great to get some tests on this.

**Comment by mspanc** [comment]
@chrismccord can we re-open this? Phoenix reached already 1.0.0, lack of proper NPM package is really painful.

**Comment by chrismccord** [comment]
I addressed this in one of the other issues of this same topic. I will extract to a package when I have a chance to prioritize it. In the meantime hang tight and vendor the source as necessary. Thanks!

**Comment by josevalim** [comment]
Actually, I would like to propose another approach for this. People have already asked us to publish phoenix.js in a couple different places and we can't maintain all of those, there are just too many because the ecosystem is still fragmented.

Therefore, I would like to invite folks like @mspanc and others that really need this feature to extract the package and publish it to NPM and wherever they believe to be necessary. Folks working with package managers do that all the time: imagine I was the one responsible to push Elixir to Fedora, Ubuntu, Homebrew, Chocolatey, etc. It is simply not doable.

What do you say @chrismccord?

**Comment by chrismccord** [comment]
> What do you say @chrismccord?

Agree absolutely!

**Comment by scrogson** [comment]
Agreed.

**Comment by mspanc** [comment]
I really need this soon, it is critical for my project. I will extract this in the upcoming +/- week and take care for maintaining this in the upcoming months as I will be actively developing project based on Phoenix. 

But I don't want to be the only owner of the npm package so other people can take over if I am on holidays or hit by the car.

If you agree can you please provide your npm logins?

**Comment by daytonn** [comment]
I'd love to help, my npm handle is `daytonn`

**Comment by josevalim** [comment]
@mspanc that's great to hear! Thank you for taking care of this.

**Comment by daytonn** [comment]
Any movement on this?

**Comment by mspanc** [comment]
Hello

I am off until Sunday. I'll do this right after I return.

**Comment by andrewvy** [comment]
I would love to create a bower package for this, many of my systems use bower for front-end components and it would be great to have. :)

**Comment by daytonn** [comment]
I think bower can be a build target of the npm package. No need to get too
crazy.

**Comment by willrax** [comment]
I think I pulled something together here https://github.com/willrax/phoenix-js. Seemed to work ok for me in another small application using bower and the `glob/main.js` file.

**Comment by chrismccord** [comment]
It seem we have a few efforts going on at once. I met @jerel at ElixirConf, and we has extracted the client and is now putting together a test suite with CI testing for all supported browsers. Perhaps we can unit the effort around his repo here?

https://github.com/jerel/phoenix_js

**Comment by willrax** [comment]
Oh awesome! Absolutely.

**Comment by willrax** [comment]
This also looks like a much better implementation. I want to use the socket stuff in an Ember application so this will be really handy.

**Comment by mspanc** [comment]
I've made this, finally: https://www.npmjs.com/package/phoenix-socket

Added @daytonn as a package co-owner.
