### ISSUE TITLE
Reload static assets in production mode without rebooting server

### ISSUE THREAD

**Issue by Nicd** [phoenixframework/phoenix#992]
Currently, AFAIK, there is no way to reload static assets (digested with `phoenix.digest`) in production mode without restarting the server. So for example if I make a simple CSS-only change, I have to take down the entire Phoenix instance. I would much rather remsh into the server and call some function to reload the assets (in my case I always have a remsh running anyway so it would be very useful).

I mentioned this to @josevalim and he suggested I make a feature request for it.

**Comment by josevalim** [comment]
I am wondering what our options are. We can definitely provide a function you would call but you would have to log into the node and call IEx. Another option is to support some sort of restart file. We can check for it every minute and clean up the config once we notice it.

**Comment by Nicd** [comment]
A function would definitely work for me, since I can easily remsh into the node. Can't speak for other people's workflow's though.

**Comment by guttusu** [comment]
I am thinking the file based approach can scale if file has actual instructions to perform but overall taking instructions from files can be a security risk. The function way can scale as more functions can be added for production interventions and functions can authenticate requests, so my preference is the function approach. 

Related to this, if there are multiple nodes running phoenix, does this action have to performed on all nodes individually or just on one node.

**Comment by chrismccord** [comment]
> Another option is to support some sort of restart file. We can check for it every minute and clean up the config once we notice it.

Would a good option be to have the config server refresh on an interval instead? No restart file required, we could bump the config ourselves?

**Comment by josevalim** [comment]
@chrismccord no because refreshing configs expires all caches and we don't want to be expiring caches every 30 minutes for free. Doing a system call to check if a file exists is much, much cheaper.
