### ISSUE TITLE
Model migration, :text gets changed to :string without size option

### ISSUE THREAD

**Issue by foxnewsnetwork** [phoenixframework/phoenix#993]
I was using the the mix tasks to build some models just now by running:
```shell
mix phoenix.model.gen Post posts entry:text other_stuff:string
```
But the task converted my `:text` to `:string` in the actual migration:
```elixir
...
add :entry, :string
...
```
Looking into the mix code at: 

https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phoenix.gen.model.ex#L137

I discover the following private function:
```elixir
defp value_to_type(:text), do: :string
```
Which means this change from text to string is clearly intentional. Is there a reason for this change? Is it some weird thing that has to do with postgres that I, as a pleb mysql/maria user, would know nothing about?

But whatever the case, this is problematic for end-users like me, as I expect `text` fields to have `size: 65535`, but instead I got bait-and-switched into using a vanilla string that limits me to `size: 255`. So, if we must stick with mapping `:text` to `:string`, can we at least modify the code at:

https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phoenix.gen.model.ex#L130

to:
```elixir
defp defaults(attrs) do
    Enum.into attrs, %{}, fn
      {k, :boolean}  -> {k, ", default: false"}
      {k, :text} -> {k, ", size: 65535"}
      {k, _}         -> {k, ""}
    end
  end
```

**Comment by josevalim** [comment]
I can't reproduce this. The `value_to_type` is used to figure out the **model** type and not used in the migration. To confirm my suspicions, I have improved the test to confirm text is indeed written as text in the migration: 

https://github.com/phoenixframework/phoenix/commit/16a71ee56b89cc86bfbaf787a75e8217d63d2b63#diff-ec39d994f66fd64afd0cf92c4418a707R31

**Comment by foxnewsnetwork** [comment]
weird, I generated a new phoenix project in an attempt to reproduce, and indeed, this problem went away. lol I must have done really egregiously dumb in my original use case. Anyway, thanks for taking time to look into it so promptly.
