### ISSUE TITLE
Unable to change static_path using static_url

### ISSUE THREAD

**Issue by nicksanders** [phoenixframework/phoenix#997]
http://hexdocs.pm/phoenix/Phoenix.Endpoint.html says static_url accepts the same options as url which are :host, :scheme, :path and :port

But where its used

static_script_name = (var!(config)[:static_url] || var!(config)[:url])[:path] || "/"

it looks like its expecting a string.

I have tried adding

static_url: "/static",
and
static_url: [path: "/static/"],

to dev.exs but static_path is still returns an empty string for the prefix in both cases

**Comment by josevalim** [comment]
Which Phoenix version are you using? There was a bug in Phoenix and I believe this to be fixed on v0.14.0. Can you please give it a try?

**Comment by nicksanders** [comment]
Thanks, its fixed in v0.14.0
