### ISSUE TITLE
Root forward should raise

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix#998]
A user on the ML reported an ambiguous clause warning with this router:

```elixir
defmodule Api.Router do
  use Api.Web, :router

  pipeline :api do
    plug :accepts, ["json"]
    plug :put_resp_content_type, Plug.MIME.type("json")
  end

  scope "/", Api do
    pipe_through :api
    forward "/", VersionRouter
  end
end
```

I think we have to disallow root forwards and raise as there is no way for use to catch-all 404s. // @josevalim thoughts?

**Comment by josevalim** [comment]
Well, we could allow it... as long as it is clear it will always match and that will be the only route invoked.

**Comment by chrismccord** [comment]
José is right. On master we now silence the warning so root forward is fine as long as your forward chain wants to handle 404's
